import type { Exam } from '../../../engine/types'

// A practice paper in the exact format of the real Term 1 final exam (Units 1–6).
export const term1D: Exam = {
  id: 't1-d',
  term: 1,
  title: 'Term 1 — Test (D)',
  titleAr: 'الفصل الأول — النموذج (D)',
  minutes: 60,
  totalMarks: 400,
  sourceAr: 'نموذج تدريبي بشكل امتحان الفصل الأول نفسه يغطّي الوحدات 1–6 (نصّا القراءة من الوحدة 5: الأمان على الإنترنت، والوحدة 2: تحدٍّ في مدرسة جديدة).',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text then choose the correct answer a, b, c or d:',
      titleAr: 'اقرأ النص التالي ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 50,
      passage: {
        paragraphs: [
          "Joud is a thirteen-year-old student who loves to surf the net and share posts with her friends. Last month, something bad happened. A student from another class started sending her harsh messages via social media. He made fun of her appearance and wrote unkind comments under her photos. Every evening, Joud received new messages, and she lived in constant fear of what would come next. She felt upset and lonely, and she did not want to go to school.",
          "At first, Joud did not tell anyone. She thought that it was her fault and that people would laugh at her. But one day, her mother noticed that she looked sad and asked her what was wrong. Joud told her everything. Her mother said, \"You mustn't blame yourself. The bully is the person with the problem, not you.\"",
          "The next day, they went to see the school counselor. {She} listened carefully and gave Joud a lot of support and encouragement. She also told her to keep the messages and not to answer them. The school contacted the bully's parents, and the messages stopped.",
          "Now Joud knows that cyber bullying can occur anywhere, but there is always a solution. Her advice to other students is simple: \"Don't stay silent. Talk to a trusted adult.\"",
        ],
        paragraphsAr: [
          'جود طالبة في الثالثة عشرة من عمرها تحبّ تصفّح الإنترنت ومشاركة المنشورات مع صديقاتها. في الشهر الماضي حدث شيء سيّئ. بدأ طالب من صفّ آخر يرسل إليها رسائل قاسية عبر وسائل التواصل الاجتماعي. سخر من مظهرها وكتب تعليقات غير لطيفة تحت صورها. كل مساء كانت جود تتلقّى رسائل جديدة، وعاشت في خوف دائم مما سيأتي بعد ذلك. شعرت بالانزعاج والوحدة، ولم تعد تريد الذهاب إلى المدرسة.',
          'في البداية لم تخبر جود أحداً. ظنّت أن الذنب ذنبها وأن الناس سيضحكون عليها. لكن في أحد الأيام لاحظت أمها أنها تبدو حزينة وسألتها ما الأمر. فأخبرتها جود بكل شيء. قالت أمها: "لا يجب أن تلومي نفسك. المتنمّر هو صاحب المشكلة، لا أنتِ."',
          'في اليوم التالي ذهبتا لمقابلة المرشدة في المدرسة. استمعت إليها بانتباه وقدّمت لجود كثيراً من الدعم والتشجيع. وقالت لها أيضاً أن تحتفظ بالرسائل وألّا تردّ عليها. تواصلت المدرسة مع والدَي المتنمّر، فتوقّفت الرسائل.',
          'تعرف جود الآن أن التنمّر الإلكتروني يمكن أن يحدث في أي مكان، لكن هناك دائماً حلّ. ونصيحتها للطلاب الآخرين بسيطة: "لا تبقوا صامتين. تحدّثوا إلى شخص بالغ موثوق."',
        ],
      },
      questions: [
        { n: 1, kind: 'mcq', prompt: "The student made fun of Joud's ___.", promptAr: 'سخر الطالب من ___ جود.', options: ['school', 'appearance', 'mother', 'friends'], answer: 1, explainAr: 'النص: "He made fun of her appearance" — سخر من مظهرها.' },
        { n: 2, kind: 'mcq', prompt: 'At first, Joud ___.', promptAr: 'في البداية، ___ جود.', options: ['told her mother about the messages', 'kept the problem to herself', "answered the bully's messages", 'went to the school counselor'], answer: 1, explainAr: 'النص: "At first, Joud did not tell anyone" — أي أنها أبقت المشكلة لنفسها ولم تخبر أحداً.' },
        { n: 3, kind: 'mcq', prompt: 'What does "She" in the text refer to?', promptAr: 'إلامَ تعود كلمة "She" في النص؟', options: ['Joud', "Joud's mother", 'the school counselor', 'the bully'], answer: 2, explainAr: 'الجملة السابقة: "they went to see the school counselor. She listened carefully"، فالتي استمعت وقدّمت الدعم هي المرشدة المدرسية (the school counselor).' },
        { n: 4, kind: 'mcq', prompt: '"Harsh" is the opposite of:', promptAr: 'كلمة "Harsh" (قاسٍ) عكسها:', options: ['constant', 'upset', 'aggressive', 'kind'], answer: 3, explainAr: 'harsh تعني قاسٍ وغير لطيف (cruel, unkind)، وعكسها kind أي لطيف. أما aggressive فمعناها عدواني وهي قريبة من معنى harsh.' },
        { n: 5, kind: 'mcq', prompt: '"Occur" means ___.', promptAr: 'كلمة "Occur" تعني ___.', options: ['to keep something', 'to need', 'to happen', 'to embarrass someone'], answer: 2, explainAr: 'occur = يحدث (to happen). أما to keep something فهي retain، وto need فهي require، وto embarrass someone فهي humiliate.' },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then write if the sentences are True or False:',
      titleAr: 'اقرأ النص التالي ثم اكتب إن كانت الجمل صحيحة أم خاطئة:',
      marks: 50,
      passage: {
        paragraphs: [
          "Last year, Kinan's family moved from Hama to Damascus because his father had found a new job there. For Kinan, the move was a real challenge. He had to leave his old school, his friends and his kind neighbours.",
          "On his first day at the new school, Kinan felt lonely. He didn't know anyone, and the classroom was noisy. While the other students were talking and laughing in the playground, he was sitting alone under a tree. He wondered if he would ever make new friends.",
          "Things were difficult for a few weeks. Kinan felt less motivated, and his marks in maths became low. He didn't tell his parents because he didn't want to worry them. Then one day, his teacher noticed the problem and talked to him after the lesson. She told him to join the school football team.",
          "Kinan took her advice. While he was playing in his first match, he scored a goal, and his team won. After that, the other players started to talk to him, and he soon got on with everyone in his class. By the end of the year, he had overcome his difficulties, and his marks had improved. Now Kinan feels happy and satisfied at his new school.",
        ],
        paragraphsAr: [
          'في العام الماضي انتقلت عائلة كنان من حماة إلى دمشق لأن والده كان قد وجد عملاً جديداً هناك. بالنسبة إلى كنان كان الانتقال تحدّياً حقيقياً. فقد كان عليه أن يترك مدرسته القديمة وأصدقاءه وجيرانه الطيّبين.',
          'في يومه الأول في المدرسة الجديدة شعر كنان بالوحدة. لم يكن يعرف أحداً، وكان الصف مزعجاً. وبينما كان الطلاب الآخرون يتحدّثون ويضحكون في الملعب، كان هو جالساً وحده تحت شجرة. وتساءل إن كان سيكوّن أصدقاء جدداً يوماً ما.',
          'كانت الأمور صعبة لبضعة أسابيع. شعر كنان بحماس أقل، وانخفضت علاماته في الرياضيات. لم يخبر والديه لأنه لم يرد أن يقلقهما. ثم في أحد الأيام لاحظت معلّمته المشكلة وتحدّثت إليه بعد الدرس. وقالت له أن ينضمّ إلى فريق كرة القدم في المدرسة.',
          'أخذ كنان بنصيحتها. وبينما كان يلعب في مباراته الأولى سجّل هدفاً وفاز فريقه. بعد ذلك بدأ اللاعبون الآخرون يتحدّثون معه، وسرعان ما صار على وفاق مع الجميع في صفّه. وبحلول نهاية العام كان قد تغلّب على صعوباته وتحسّنت علاماته. والآن يشعر كنان بالسعادة والرضا في مدرسته الجديدة.',
        ],
      },
      questions: [
        { n: 6, kind: 'truefalse', prompt: "Kinan's family moved to Damascus because of his father's new job.", promptAr: 'انتقلت عائلة كنان إلى دمشق بسبب عمل والده الجديد.', answer: true, explainAr: 'النص: "moved from Hama to Damascus because his father had found a new job there".' },
        { n: 7, kind: 'truefalse', prompt: 'Kinan made many new friends on his first day.', promptAr: 'كوّن كنان أصدقاء جدداً كثيرين في يومه الأول.', answer: false, explainAr: 'النص: "On his first day ... Kinan felt lonely. He didn\'t know anyone" — شعر بالوحدة ولم يعرف أحداً.' },
        { n: 8, kind: 'truefalse', prompt: 'Kinan told his parents about his problem at once.', promptAr: 'أخبر كنان والديه بمشكلته فوراً.', answer: false, explainAr: 'النص: "He didn\'t tell his parents because he didn\'t want to worry them" — لم يخبرهما.' },
        { n: 9, kind: 'truefalse', prompt: "Kinan's teacher advised him to join the football team.", promptAr: 'نصحت المعلّمة كنان بالانضمام إلى فريق كرة القدم.', answer: true, explainAr: 'النص: "She told him to join the school football team" ثم "Kinan took her advice".' },
        { n: 10, kind: 'truefalse', prompt: "At the end of the year, Kinan's marks were still low.", promptAr: 'في نهاية العام كانت علامات كنان ما تزال منخفضة.', answer: false, explainAr: 'النص: "By the end of the year, he had overcome his difficulties, and his marks had improved" — تحسّنت علاماته.' },
      ],
    },
    {
      letter: 'C',
      title: 'Read the sentences then choose the correct answer a, b, c or d:',
      titleAr: 'اقرأ الجمل ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 200,
      questions: [
        { n: 11, kind: 'mcq', topic: 'tense', prompt: 'My mother ___ dinner at the moment.', promptAr: 'أمي ___ العشاء في هذه اللحظة.', options: ['cooks', 'cooked', 'was cooking', 'is cooking'], answer: 3, explainAr: 'at the moment تدلّ على حدث يجري الآن، فنستخدم المضارع المستمر: is cooking.' },
        { n: 12, kind: 'mcq', topic: 'tense', prompt: 'The sun ___ in the east.', promptAr: 'الشمس ___ من الشرق.', options: ['rises', 'is rising', 'rose', 'rise'], answer: 0, explainAr: 'حقيقة ثابتة فنستخدم المضارع البسيط، ومع The sun (مفرد) نضيف s: rises.' },
        { n: 13, kind: 'mcq', topic: 'tense', prompt: 'Nour ___ her grandparents next weekend. She has already bought the bus tickets.', promptAr: '___ نور جدّيها في عطلة نهاية الأسبوع القادمة. لقد اشترت تذاكر الحافلة.', options: ['visits', 'visited', 'is going to visit', 'was visiting'], answer: 2, explainAr: 'خطة قرّرتها مسبقاً للمستقبل (اشترت التذاكر، next weekend) فنستخدم be going to: is going to visit.' },
        { n: 14, kind: 'mcq', topic: 'tense', prompt: 'While Rami ___ down the street, he met his old teacher.', promptAr: 'بينما كان رامي ___ في الشارع، قابل معلّمه القديم.', options: ['walked', 'was walking', 'is walking', 'walks'], answer: 1, explainAr: 'While + الماضي المستمر لحدث طويل كان مستمراً حين وقع الحدث القصير (met): was walking.' },
        { n: 15, kind: 'mcq', topic: 'tense', prompt: 'I was having breakfast when my friend ___.', promptAr: 'كنت أتناول الفطور عندما ___ صديقي.', options: ['was calling', 'calls', 'called', 'has called'], answer: 2, explainAr: 'الحدث القصير الذي قطع الحدث الطويل (was having) يأتي بعد when بالماضي البسيط: called.' },
        { n: 16, kind: 'mcq', topic: 'tense', prompt: 'My laptop ___ working two days ago.', promptAr: '___ حاسوبي المحمول عن العمل قبل يومين.', options: ['stops', 'has stopped', 'was stopping', 'stopped'], answer: 3, explainAr: 'two days ago تدلّ على زمن منتهٍ في الماضي، فنستخدم الماضي البسيط: stopped.' },
        { n: 17, kind: 'mcq', topic: 'reported', prompt: '"I have lost my key." Aya said that she ___ her key.', promptAr: '"لقد أضعت مفتاحي." قالت آية إنها ___ مفتاحها.', options: ['had lost', 'has lost', 'loses', 'was losing'], answer: 0, explainAr: 'في الكلام المنقول يتحوّل المضارع التام (have lost) إلى الماضي التام: had lost.' },
        { n: 18, kind: 'mcq', topic: 'reported', prompt: '"We are going to travel to Egypt." They said that they ___ to Egypt.', promptAr: '"سنسافر إلى مصر." قالوا إنهم ___ إلى مصر.', options: ['are going to travel', 'were going to travel', 'will travel', 'going to travel'], answer: 1, explainAr: 'في الكلام المنقول تتحوّل are going to إلى were going to.' },
        { n: 19, kind: 'mcq', topic: 'reported', prompt: '"I am staying here." Zeina said that she was staying ___.', promptAr: '"أنا أقيم هنا." قالت زينة إنها تقيم ___.', options: ['here', 'there', 'now', 'this'], answer: 1, explainAr: 'في الكلام المنقول تتغيّر كلمات المكان: here تصبح there.' },
        { n: 20, kind: 'mcq', topic: 'conditional', prompt: 'If Hadi ___ a smart phone, he would call his friends every day.', promptAr: 'لو ___ هادي هاتفاً ذكياً، لاتصل بأصدقائه كل يوم.', options: ['has', 'had', 'will have', 'would have'], answer: 1, explainAr: 'الشرطية الثانية: If + الماضي البسيط (had)، ثم would + الفعل الأساسي.' },
        { n: 21, kind: 'mcq', topic: 'conditional', prompt: 'If you studied harder, you ___ better marks.', promptAr: 'لو درست بجدّ أكبر، ___ على علامات أفضل.', options: ['will get', 'get', 'would get', 'got'], answer: 2, explainAr: 'جملة If في الماضي البسيط (studied)، فالجواب would + الفعل الأساسي: would get.' },
        { n: 22, kind: 'mcq', topic: 'grammar', prompt: '___ is your favourite subject? — Science.', promptAr: '___ مادّتك المفضّلة؟ — العلوم.', options: ['Who', 'Where', 'How many', 'What'], answer: 3, explainAr: 'نسأل عن شيء (مادة دراسية) بـ What. أما Who فللأشخاص، وWhere للمكان، وHow many للعدد.' },
        { n: 23, kind: 'mcq', topic: 'pronunciation', prompt: 'The word that has a silent letter is:', promptAr: 'الكلمة التي فيها حرف صامت هي:', options: ['cat', 'what', 'pool', 'bed'], answer: 1, explainAr: 'في what الحرف h صامت (كلمات wh-)، أما cat و pool و bed فتُلفظ كل حروفها.' },
        { n: 24, kind: 'mcq', topic: 'pronunciation', prompt: "The word that doesn't have /k/ sound is:", promptAr: 'الكلمة التي لا تحتوي على الصوت /k/ هي:', options: ['city', 'cake', 'duck', 'school'], answer: 0, explainAr: 'في city يأتي بعد c حرف i فيُلفظ /s/. أما cake و duck (ck) و school (ch) ففيها صوت /k/.' },
        { n: 25, kind: 'mcq', topic: 'pronunciation', prompt: 'The word "cook" has ___ sound.', promptAr: 'كلمة "cook" فيها الصوت ___.', options: ['/s/ and /u/', '/k/ and /u:/', '/k/ and /u/', '/s/ and /u:/'], answer: 2, explainAr: 'cook تُلفظ /kʊk/: الحرف c قبل o يُلفظ /k/، وoo هنا صوت قصير /u/ كما في took و good.' },
        { n: 26, kind: 'mcq', topic: 'wordform', prompt: 'Shopping online is easy and ___.', promptAr: 'التسوّق عبر الإنترنت سهل و___.', options: ['conveniently', 'convenient', 'convenience', 'conveniences'], answer: 1, explainAr: 'بعد is نحتاج صفة معطوفة على الصفة easy، فنستخدم convenient (مريح/مناسب) لا الظرف conveniently.' },
        { n: 27, kind: 'mcq', topic: 'vocab', prompt: 'Help given to someone who has a problem:', promptAr: 'مساعدة تُقدَّم لشخص لديه مشكلة:', options: ['fear', 'fault', 'support', 'contact'], answer: 2, explainAr: 'support = الدعم والمساعدة (كلمة من الوحدة الخامسة).' },
        { n: 28, kind: 'mcq', topic: 'vocab', prompt: 'To say you will hurt someone:', promptAr: 'أن تقول إنك ستؤذي شخصاً ما:', options: ['threaten', 'annoy', 'retain', 'participate'], answer: 0, explainAr: 'threaten = يهدّد (كلمة من الوحدة الخامسة).' },
        { n: 29, kind: 'mcq', topic: 'vocab', prompt: 'A person who starts a company or organization:', promptAr: 'شخص يبدأ شركة أو منظّمة:', options: ['customer', 'expert', 'counselor', 'founder'], answer: 3, explainAr: 'founder = المؤسِّس (كلمة من الوحدة السادسة).' },
        { n: 30, kind: 'mcq', topic: 'vocab', prompt: 'Suggestions about what to do:', promptAr: 'اقتراحات حول ما يجب فعله:', options: ['reality', 'advice', 'risk', 'strategy'], answer: 1, explainAr: 'advice = النصيحة (كلمة من الوحدة السادسة).' },
      ],
    },
    {
      letter: 'D',
      title: 'Ask about the underline word(s):',
      titleAr: 'اسأل عن الكلمة (الكلمات) التي تحتها خط:',
      marks: 40,
      questions: [
        { n: 31, kind: 'ask', prompt: '{The counselor} helped Joud.', promptAr: 'ساعدت المرشدة جود.', options: ['Who did the counselor help?', 'Who helped Joud?', 'What helped Joud?', 'Who helps Joud?'], answer: 1, explainAr: 'نسأل عن الفاعل (شخص) بـ Who، وعندما تكون Who هي الفاعل لا نستخدم did ونُبقي الفعل في الماضي: Who helped Joud?' },
        { n: 32, kind: 'ask', prompt: 'There are {thirty} students in our class.', promptAr: 'يوجد ثلاثون طالباً في صفّنا.', options: ['How many students are there in your class?', 'How much students are there in your class?', 'How many students there are in your class?', 'How many students is there in your class?'], answer: 0, explainAr: 'نسأل عن عدد اسم معدود بالجمع بـ How many، ونقدّم are على there، ونحوّل our إلى your.' },
        { n: 33, kind: 'ask', prompt: 'They are going to meet {in the park}.', promptAr: 'سيلتقون في الحديقة.', options: ['Where they are going to meet?', 'When are they going to meet?', 'Where do they going to meet?', 'Where are they going to meet?'], answer: 3, explainAr: 'نسأل عن المكان بـ Where، ونقدّم الفعل المساعد are على الفاعل they: Where are they going to meet?' },
        { n: 34, kind: 'ask', prompt: 'Rahaf went to bed early {because she was tired}.', promptAr: 'ذهبت رهف إلى النوم باكراً لأنها كانت متعبة.', options: ['Why did Rahaf went to bed early?', 'When did Rahaf go to bed?', 'Why did Rahaf go to bed early?', 'Why Rahaf went to bed early?'], answer: 2, explainAr: 'نسأل عن السبب (because) بـ Why، والفعل ماضٍ فنستخدم did + الفعل المجرد go.' },
      ],
    },
    {
      letter: 'E',
      title: 'Choose the wrong part in each phrase:',
      titleAr: 'اختر الجزء الخاطئ في كل جملة:',
      marks: 20,
      questions: [
        { n: 35, kind: 'wrongpart', prompt: 'I {was} {walking} home {when} I {was meeting} my friend.', promptAr: 'كنت أمشي إلى البيت عندما قابلت صديقي.', answer: 3, explainAr: 'الحدث القصير بعد when يكون بالماضي البسيط: was meeting ← met.' },
        { n: 36, kind: 'wrongpart', prompt: 'Aya {said} {that} she {has} {never} seen the sea.', promptAr: 'قالت آية إنها لم ترَ البحر أبداً.', answer: 2, explainAr: 'في الكلام المنقول بعد said يتحوّل المضارع التام إلى ماضٍ تام: has ← had.' },
        { n: 37, kind: 'wrongpart', prompt: 'If Omar {has} more time, he {would} {join} the {football} team.', promptAr: 'لو كان لدى عمر وقت أكثر، لانضمّ إلى فريق كرة القدم.', answer: 0, explainAr: 'الشرطية الثانية: If + الماضي البسيط ثم would: has ← had.' },
        { n: 38, kind: 'wrongpart', prompt: 'My sister {usually} {is going} {to} bed {at} ten.', promptAr: 'أختي عادةً تذهب إلى النوم في العاشرة.', answer: 1, explainAr: 'usually تدلّ على عادة فنستخدم المضارع البسيط: is going ← goes.' },
      ],
    },
    {
      letter: 'F',
      title: 'Write a 50-word paragraph about the following topic:',
      titleAr: 'اكتب فقرة من 50 كلمة عن الموضوع التالي:',
      marks: 40,
      writing: {
        topic: 'Advise a friend who spends too much time on social media',
        topicAr: 'انصح صديقاً يقضي وقتاً طويلاً جداً على وسائل التواصل الاجتماعي',
        words: 50,
        model: 'If I were you, I would take a break from social media. Firstly, I would put my mobile away while I was studying, because it takes a lot of time. Secondly, I would spend more time with my family and real friends. Thirdly, I would do some sport or read a good book. If you followed this advice, your marks would improve and you would feel more relaxed.',
        modelAr: 'لو كنتُ مكانك لأخذت استراحة من وسائل التواصل الاجتماعي. أولاً، كنت سأضع هاتفي جانباً أثناء الدراسة لأنه يأخذ وقتاً طويلاً. ثانياً، كنت سأقضي وقتاً أطول مع عائلتي وأصدقائي الحقيقيين. ثالثاً، كنت سأمارس بعض الرياضة أو أقرأ كتاباً جيداً. لو اتّبعت هذه النصيحة لتحسّنت علاماتك ولشعرت براحة أكبر.',
        checklistAr: [
          'كتبت عن الموضوع المطلوب نفسه (نصيحة لصديق يكثر من استخدام وسائل التواصل).',
          'استخدمت الشرط الثاني بشكل صحيح: If I were you, I would ...',
          'رتّبت النصائح بكلمات ربط مثل Firstly, Secondly, Thirdly, because.',
          'راعيت الإملاء وعلامات الترقيم والحروف الكبيرة.',
        ],
      },
    },
  ],
}
