import type { Exam } from '../../../engine/types'

// A practice paper in the exact format of the real Term 1 final exam (Units 1–6).
export const term1B: Exam = {
  id: 't1-b',
  term: 1,
  title: 'Term 1 — Test (B)',
  titleAr: 'الفصل الأول — النموذج (B)',
  minutes: 60,
  totalMarks: 400,
  sourceAr: 'نموذج تدريبي بشكل امتحان الفصل الأول نفسه يغطّي الوحدات 1–6 (نصّا القراءة من الوحدة 1: مدرسة المستقبل، والوحدة 4: وجهات سياحية).',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text then choose the correct answer a, b, c or d:',
      titleAr: 'اقرأ النص التالي ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 50,
      passage: {
        paragraphs: [
          "Thirty years ago, most schools were very different from the schools of today. Classrooms had only a blackboard, some chalk and a few books. Teachers relied on traditional methods of teaching, and students spent most of the lesson listening and writing. Nowadays, technology plays a major role in education. Many schools are provided with computers, laptops and smart boards, and students can surf the net to find information in a few seconds. Teachers use videos and pictures to convey their ideas, so difficult lessons become easier to understand.",
          "Education experts believe that the schools of the future will be even more modern. They will combine good teaching with new technological innovations. Students will learn in a flexible format, and each student will be able to study at his or her own speed. Virtual reality will take students on trips to ancient cities or into space without leaving their classroom. Some people think that robotic teachers will help human teachers {who} have large classes.",
          "However, technology alone is not enough. Students still need practical work in the laboratory, and they must pay attention to safety. They also need good teachers who care about them. In the end, the best school is the one that helps every student to improve and to prepare for a successful career.",
        ],
        paragraphsAr: [
          'قبل ثلاثين عاماً كانت معظم المدارس مختلفة جداً عن مدارس اليوم. لم يكن في الصفوف سوى سبّورة سوداء وبعض الطباشير وقليل من الكتب. كان المعلمون يعتمدون على طرق التدريس التقليدية، وكان الطلاب يقضون معظم الدرس في الاستماع والكتابة. أما اليوم فالتكنولوجيا تؤدّي دوراً رئيسياً في التعليم. فكثير من المدارس مزوّدة بالحواسيب والحواسيب المحمولة والسبّورات الذكية، ويستطيع الطلاب تصفّح الإنترنت للعثور على المعلومات في ثوانٍ قليلة. ويستخدم المعلمون الفيديوهات والصور لإيصال أفكارهم، فتصبح الدروس الصعبة أسهل فهماً.',
          'يعتقد خبراء التعليم أن مدارس المستقبل ستكون أكثر حداثة. فستجمع بين التدريس الجيد والابتكارات التكنولوجية الجديدة. وسيتعلّم الطلاب بصيغة مرنة، وسيتمكّن كل طالب من الدراسة بسرعته الخاصة. وسيأخذ الواقع الافتراضي الطلاب في رحلات إلى مدن قديمة أو إلى الفضاء دون أن يغادروا صفّهم. ويظنّ بعض الناس أن المعلمين الآليين سيساعدون المعلمين البشر الذين لديهم صفوف كبيرة.',
          'ومع ذلك، فالتكنولوجيا وحدها لا تكفي. فما زال الطلاب يحتاجون إلى العمل العملي في المختبر، ويجب أن ينتبهوا إلى السلامة. كما يحتاجون إلى معلمين جيدين يهتمّون بهم. وفي النهاية، أفضل مدرسة هي التي تساعد كل طالب على التحسّن والاستعداد لمهنة ناجحة.',
        ],
      },
      questions: [
        { n: 1, kind: 'mcq', prompt: 'Thirty years ago, teachers relied on ___.', promptAr: 'قبل ثلاثين عاماً، كان المعلمون يعتمدون على ___.', options: ['smart boards and videos', 'traditional methods of teaching', 'virtual reality', 'robotic teachers'], answer: 1, explainAr: 'النص: "Teachers relied on traditional methods of teaching" — أي طرق التدريس التقليدية. أما السبّورات الذكية والواقع الافتراضي والمعلمون الآليون فهي من الحاضر أو المستقبل.' },
        { n: 2, kind: 'mcq', prompt: 'In the schools of the future, students will ___.', promptAr: 'في مدارس المستقبل، سوف ___ الطلاب.', options: ['all study at the same speed', 'never do practical work', 'be able to learn at their own speed', 'travel into space every day'], answer: 2, explainAr: 'النص: "each student will be able to study at his or her own speed" — أي أن كل طالب يتعلّم بسرعته الخاصة. والخيار b خاطئ لأن النص يقول إنهم ما زالوا يحتاجون إلى العمل العملي، والسفر إلى الفضاء يكون بالواقع الافتراضي فقط.' },
        { n: 3, kind: 'mcq', prompt: 'What does "who" in the text refer to?', promptAr: 'إلامَ تعود كلمة "who" في النص؟', options: ['robotic teachers', 'human teachers', 'students', 'large classes'], answer: 1, explainAr: 'الجملة: "robotic teachers will help human teachers who have large classes"، فالذين لديهم صفوف كبيرة هم المعلمون البشر (human teachers)، وwho تعود على أقرب اسم عاقل قبلها.' },
        { n: 4, kind: 'mcq', prompt: '"Modern" is the opposite of:', promptAr: 'كلمة "Modern" (حديث) عكسها:', options: ['practical', 'traditional', 'flexible', 'major'], answer: 1, explainAr: 'modern تعني حديث/عصري، وعكسها traditional أي تقليدي يتبع الطرق القديمة (كلمتان من الوحدة الأولى).' },
        { n: 5, kind: 'mcq', prompt: '"Convey" means ___.', promptAr: 'كلمة "Convey" تعني ___.', options: ['to put two things together', 'to depend on', 'to make ideas known to somebody', 'to give something to be used'], answer: 2, explainAr: 'convey = ينقل أو يوصل الأفكار إلى شخص ما. أما to put two things together فهي combine، وto depend on فهي rely، وto give something to be used فهي provide.' },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then write if the sentences are True or False:',
      titleAr: 'اقرأ النص التالي ثم اكتب إن كانت الجمل صحيحة أم خاطئة:',
      marks: 50,
      passage: {
        paragraphs: [
          "Last summer, Tareq and his family spent their vacation in Tartous, a city which is located on the Syrian coast. They had booked two rooms in a small hotel near the sea before they left Damascus. When they arrived, the check-in was quick, and the rooms had air-conditioning, so they felt comfortable even on hot days.",
          "On the second day, they took a ferry to Arwad, a small island not far from the coast. Tareq had never travelled by boat before, so it was an exciting adventure for him. The scenery was magnificent: blue water, old houses and fishing boats everywhere. They visited an ancient castle, which is one of the island's famous landmarks.",
          "At lunchtime, they ate at a small restaurant by the sea. The waiter told them that the fishermen had caught the fish that morning. Tareq's father ordered grilled fish, and his mother chose a seafood dish with rice. In the evening, they went to an open market, where the food and the souvenirs were good and cheap.",
          "When they returned home, Tareq said that it had been the most unforgettable vacation of his life. He told his friends that he wanted to visit the island again.",
        ],
        paragraphsAr: [
          'في الصيف الماضي قضى طارق وعائلته عطلتهم في طرطوس، وهي مدينة تقع على الساحل السوري. كانوا قد حجزوا غرفتين في فندق صغير قرب البحر قبل أن يغادروا دمشق. وعندما وصلوا كان تسجيل الوصول سريعاً، وكانت الغرف مكيّفة، فشعروا بالراحة حتى في الأيام الحارّة.',
          'في اليوم الثاني ركبوا العبّارة إلى أرواد، وهي جزيرة صغيرة ليست بعيدة عن الساحل. لم يكن طارق قد سافر بالقارب من قبل، فكانت مغامرة مثيرة بالنسبة إليه. كان المنظر رائعاً: ماء أزرق وبيوت قديمة وقوارب صيد في كل مكان. وزاروا قلعة قديمة هي واحدة من المعالم المشهورة في الجزيرة.',
          'وفي وقت الغداء أكلوا في مطعم صغير على البحر. أخبرهم النادل أن الصيّادين كانوا قد اصطادوا السمك ذلك الصباح. طلب والد طارق سمكاً مشوياً، واختارت أمه طبق مأكولات بحرية مع الأرز. وفي المساء ذهبوا إلى سوق مكشوف حيث كان الطعام والتذكارات جيدة ورخيصة.',
          'وعندما عادوا إلى البيت قال طارق إنها كانت أكثر عطلة لا تُنسى في حياته. وأخبر أصدقاءه أنه يريد أن يزور الجزيرة مرة أخرى.',
        ],
      },
      questions: [
        { n: 6, kind: 'truefalse', prompt: "Tareq's family booked their hotel rooms after they arrived in Tartous.", promptAr: 'حجزت عائلة طارق غرف الفندق بعد أن وصلت إلى طرطوس.', answer: false, explainAr: 'النص: "They had booked two rooms ... before they left Damascus" — حجزوا قبل مغادرة دمشق، لا بعد الوصول.' },
        { n: 7, kind: 'truefalse', prompt: 'Arwad is a small island near the coast.', promptAr: 'أرواد جزيرة صغيرة قرب الساحل.', answer: true, explainAr: 'النص: "Arwad, a small island not far from the coast".' },
        { n: 8, kind: 'truefalse', prompt: 'Tareq had travelled by boat many times before this trip.', promptAr: 'كان طارق قد سافر بالقارب مرات كثيرة قبل هذه الرحلة.', answer: false, explainAr: 'النص: "Tareq had never travelled by boat before" — لم يسافر بالقارب قبلها أبداً.' },
        { n: 9, kind: 'truefalse', prompt: "Tareq's mother had a seafood dish for lunch.", promptAr: 'تناولت أم طارق طبق مأكولات بحرية على الغداء.', answer: true, explainAr: 'النص: "his mother chose a seafood dish with rice".' },
        { n: 10, kind: 'truefalse', prompt: 'The food at the open market was expensive.', promptAr: 'كان الطعام في السوق المكشوف غالياً.', answer: false, explainAr: 'النص: "the food and the souvenirs were good and cheap" — كان رخيصاً لا غالياً.' },
      ],
    },
    {
      letter: 'C',
      title: 'Read the sentences then choose the correct answer a, b, c or d:',
      titleAr: 'اقرأ الجمل ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 200,
      questions: [
        { n: 11, kind: 'mcq', topic: 'tense', prompt: 'Listen! Somebody ___ at the door.', promptAr: 'اسمع! أحدهم ___ الباب.', options: ['knocks', 'knocked', 'is knocking', 'was knocking'], answer: 2, explainAr: 'Listen! تدلّ على حدث يجري الآن، فنستخدم المضارع المستمر: is knocking.' },
        { n: 12, kind: 'mcq', topic: 'tense', prompt: 'My brother usually ___ to school by bus.', promptAr: 'أخي عادةً ___ إلى المدرسة بالحافلة.', options: ['is going', 'goes', 'go', 'went'], answer: 1, explainAr: 'usually تدلّ على عادة، فنستخدم المضارع البسيط، ومع My brother (هو) نضيف es: goes.' },
        { n: 13, kind: 'mcq', topic: 'tense', prompt: '"The phone is ringing." "I ___ it."', promptAr: '"الهاتف يرنّ." "___ عليه."', options: ['will answer', 'answer', 'am going to answer', 'answered'], answer: 0, explainAr: 'قرار نتّخذه في لحظة الكلام (سمعنا الهاتف الآن) فنستخدم will: will answer. أما going to فللخطط المقرّرة مسبقاً.' },
        { n: 14, kind: 'mcq', topic: 'tense', prompt: 'While Rami ___ his homework, the lights went out.', promptAr: 'بينما كان رامي ___ واجبه، انطفأت الأضواء.', options: ['did', 'does', 'is doing', 'was doing'], answer: 3, explainAr: 'While + الماضي المستمر لحدث طويل كان مستمراً، قطعه حدث قصير بالماضي البسيط (went out): was doing.' },
        { n: 15, kind: 'mcq', topic: 'tense', prompt: 'Hala ___ her grandparents in Homs last week.', promptAr: '___ هالة جدّيها في حمص الأسبوع الماضي.', options: ['visits', 'has visited', 'visited', 'is visiting'], answer: 2, explainAr: 'last week تدلّ على زمن منتهٍ في الماضي، فنستخدم الماضي البسيط: visited. والمضارع التام لا يأتي مع last week.' },
        { n: 16, kind: 'mcq', topic: 'reported', prompt: '"I will call you tomorrow." Nour said that she ___ me the following day.', promptAr: '"سأتصل بك غداً." قالت نور إنها ___ بي في اليوم التالي.', options: ['will call', 'would call', 'calls', 'is calling'], answer: 1, explainAr: 'في الكلام المنقول تتحوّل will إلى would، وtomorrow إلى the following day: would call.' },
        { n: 17, kind: 'mcq', topic: 'reported', prompt: '"We are watching TV now." The boys said that they ___ TV then.', promptAr: '"نحن نشاهد التلفاز الآن." قال الأولاد إنهم ___ التلفاز حينها.', options: ['were watching', 'are watching', 'had watched', 'watch'], answer: 0, explainAr: 'في الكلام المنقول يتحوّل المضارع المستمر (are watching) إلى الماضي المستمر (were watching)، وnow تصبح then.' },
        { n: 18, kind: 'mcq', topic: 'tense', prompt: 'When we arrived at the station, the train ___.', promptAr: 'عندما وصلنا إلى المحطة، كان القطار ___.', options: ['has already left', 'already leaves', 'had already left', 'is already leaving'], answer: 2, explainAr: 'مغادرة القطار حدثت قبل وصولنا في الماضي، فنستخدم الماضي التام: had + التصريف الثالث = had already left.' },
        { n: 19, kind: 'mcq', topic: 'conditional', prompt: 'If I ___ a lot of money, I would travel around the world.', promptAr: 'لو ___ الكثير من المال، لسافرت حول العالم.', options: ['have', 'will have', 'would have', 'had'], answer: 3, explainAr: 'الشرطية الثانية: If + الماضي البسيط، ثم would + الفعل. فنقول: If I had.' },
        { n: 20, kind: 'mcq', topic: 'conditional', prompt: 'If Tareq took a break from his mobile, he ___ more relaxed.', promptAr: 'لو أخذ طارق استراحة من هاتفه، ___ براحة أكبر.', options: ['will feel', 'would feel', 'feels', 'felt'], answer: 1, explainAr: 'جملة If في الماضي البسيط (took)، فالجواب يكون would + الفعل الأساسي: would feel.' },
        { n: 21, kind: 'mcq', topic: 'grammar', prompt: '___ did you spend your vacation? — In Lattakia.', promptAr: '___ قضيت عطلتك؟ — في اللاذقية.', options: ['What', 'When', 'Where', 'Who'], answer: 2, explainAr: 'الجواب مكان (In Lattakia)، وأداة السؤال عن المكان هي Where.' },
        { n: 22, kind: 'mcq', topic: 'tense', prompt: 'My uncle ___ to Egypt three times.', promptAr: 'عمّي ___ إلى مصر ثلاث مرات.', options: ['has been', 'have been', 'was been', 'is being'], answer: 0, explainAr: 'نتحدّث عن خبرة حتى الآن فنستخدم المضارع التام: has + been (مع he نستخدم has لا have).' },
        { n: 23, kind: 'mcq', topic: 'pronunciation', prompt: 'The word that has a silent "h" is:', promptAr: 'الكلمة التي فيها حرف "h" صامت هي:', options: ['house', 'hour', 'happy', 'hotel'], answer: 1, explainAr: 'hour تُلفظ /aʊə/ دون h. أما house و happy و hotel فيُلفظ فيها h.' },
        { n: 24, kind: 'mcq', topic: 'pronunciation', prompt: 'The word in which "c" sounds /s/ is:', promptAr: 'الكلمة التي يُلفظ فيها الحرف "c" صوت /s/ هي:', options: ['cake', 'cook', 'city', 'cup'], answer: 2, explainAr: 'يُلفظ c صوت /s/ إذا جاء بعده i أو e أو y كما في city. أما cake و cook و cup فيُلفظ فيها /k/.' },
        { n: 25, kind: 'mcq', topic: 'pronunciation', prompt: 'The word that has /u/ sound is:', promptAr: 'الكلمة التي فيها الصوت /u/ هي:', options: ['pool', 'foot', 'spoon', 'tooth'], answer: 1, explainAr: 'foot تُلفظ بالصوت القصير /u/، أما pool و spoon و tooth فبالصوت الطويل /u:/.' },
        { n: 26, kind: 'mcq', topic: 'wordform', prompt: 'Omar ___ finished his project on time.', promptAr: 'أنهى عمر مشروعه في الوقت المحدّد ___.', options: ['successful', 'success', 'successfully', 'succeed'], answer: 2, explainAr: 'نحتاج ظرفاً يصف الفعل finished، والظرف يُصاغ بإضافة ly إلى الصفة: successfully (بنجاح).' },
        { n: 27, kind: 'mcq', topic: 'vocab', prompt: 'A person who teaches:', promptAr: 'شخص يقوم بالتعليم:', options: ['vehicle', 'educator', 'weapon', 'format'], answer: 1, explainAr: 'educator = المربّي أو المعلّم (كلمة من الوحدة الأولى).' },
        { n: 28, kind: 'mcq', topic: 'vocab', prompt: 'To depend on:', promptAr: 'أن تعتمد على:', options: ['rely', 'convey', 'combine', 'provide'], answer: 0, explainAr: 'rely (on) = يعتمد على (كلمة من الوحدة الأولى).' },
        { n: 29, kind: 'mcq', topic: 'vocab', prompt: 'The place you are travelling to:', promptAr: 'المكان الذي تسافر إليه:', options: ['arrival', 'souvenir', 'passport', 'destination'], answer: 3, explainAr: 'destination = الوجهة، المكان الذي تسافر إليه (كلمة من الوحدة الثالثة).' },
        { n: 30, kind: 'mcq', topic: 'vocab', prompt: 'A famous place or building that is easy to recognize:', promptAr: 'مكان أو بناء مشهور يسهل التعرّف عليه:', options: ['border', 'landmark', 'coast', 'agency'], answer: 1, explainAr: 'landmark = مَعْلَم مشهور (كلمة من الوحدة الرابعة).' },
      ],
    },
    {
      letter: 'D',
      title: 'Ask about the underline word(s):',
      titleAr: 'اسأل عن الكلمة (الكلمات) التي تحتها خط:',
      marks: 40,
      questions: [
        { n: 31, kind: 'ask', prompt: 'Rama went to {Aleppo} last summer.', promptAr: 'ذهبت راما إلى حلب الصيف الماضي.', options: ['Where Rama went last summer?', 'Where did Rama go last summer?', 'Where does Rama go last summer?', 'When did Rama go to Aleppo?'], answer: 1, explainAr: 'نسأل عن المكان بـ Where، والفعل في الماضي (went) فنستخدم did + الفعل المجرد go، ونضع did قبل الفاعل.' },
        { n: 32, kind: 'ask', prompt: 'The tourists visited the old market {yesterday}.', promptAr: 'زار السيّاح السوق القديم البارحة.', options: ['Where did the tourists visit the old market?', 'When the tourists visited the old market?', 'When did the tourists visit the old market?', 'When do the tourists visit the old market?'], answer: 2, explainAr: 'yesterday زمن، فنسأل بـ When. والفعل ماضٍ فنستخدم did + visit (المجرد)، لا do.' },
        { n: 33, kind: 'ask', prompt: '{My uncle} fixed the old car.', promptAr: 'أصلح عمّي السيارة القديمة.', options: ['What did your uncle fix?', 'Who fixed the old car?', 'Who fixes the old car?', 'Where did your uncle fix the old car?'], answer: 1, explainAr: 'نسأل عن الفاعل (شخص) بـ Who، وعندما تكون Who هي الفاعل لا نستخدم did ونُبقي الفعل في الماضي: Who fixed...?' },
        { n: 34, kind: 'ask', prompt: 'Kinan has {two} brothers.', promptAr: 'لدى كنان أخَوان.', options: ['How much brothers does Kinan have?', 'How many brothers has Kinan have?', 'How many brothers Kinan has?', 'How many brothers does Kinan have?'], answer: 3, explainAr: 'نسأل عن عدد اسم معدود بالجمع بـ How many، والفعل has في المضارع فنستخدم does + have.' },
      ],
    },
    {
      letter: 'E',
      title: 'Choose the wrong part in each phrase:',
      titleAr: 'اختر الجزء الخاطئ في كل جملة:',
      marks: 20,
      questions: [
        { n: 35, kind: 'wrongpart', prompt: 'Rama {was} reading {when} her brother {was coming} {into} the room.', promptAr: 'كانت راما تقرأ عندما دخل أخوها إلى الغرفة.', answer: 2, explainAr: 'بعد when يأتي الحدث القصير الذي قطع الحدث الطويل، فيكون بالماضي البسيط: was coming ← came.' },
        { n: 36, kind: 'wrongpart', prompt: 'If I {had} a car, I {will} drive {to} school {every day}.', promptAr: 'لو كانت لديّ سيارة، لقدتها إلى المدرسة كل يوم.', answer: 1, explainAr: 'الشرطية الثانية: If + ماضٍ بسيط (had) ثم would + الفعل: will ← would.' },
        { n: 37, kind: 'wrongpart', prompt: 'Nour {told} {us} that {her} brother {has broken} his leg.', promptAr: 'أخبرتنا نور أن أخاها كسر ساقه.', answer: 3, explainAr: 'في الكلام المنقول بعد told يتحوّل المضارع التام إلى ماضٍ تام: has broken ← had broken.' },
        { n: 38, kind: 'wrongpart', prompt: '{Where} {did} you {went} {last} summer?', promptAr: 'أين ذهبت الصيف الماضي؟', answer: 2, explainAr: 'بعد did نستخدم الفعل في صيغته المجردة: went ← go.' },
      ],
    },
    {
      letter: 'F',
      title: 'Write a 50-word paragraph about the following topic:',
      titleAr: 'اكتب فقرة من 50 كلمة عن الموضوع التالي:',
      marks: 40,
      writing: {
        topic: 'The school of the future',
        topicAr: 'مدرسة المستقبل',
        words: 50,
        model: 'I think the school of the future will be very different from my school today. Students will learn in a flexible, personalized format, and they will use laptops and virtual reality screens in every lesson. Robotic teachers will help human teachers, and flying vehicles will take students to school. There will also be modern laboratories for practical work. I hope I will study in a school like this one day.',
        modelAr: 'أظنّ أن مدرسة المستقبل ستكون مختلفة جداً عن مدرستي اليوم. سيتعلّم الطلاب بصيغة مرنة ومخصّصة، وسيستخدمون الحواسيب المحمولة وشاشات الواقع الافتراضي في كل درس. سيساعد المعلمون الآليون المعلمين البشر، وستنقل المركبات الطائرة الطلاب إلى المدرسة. وستكون هناك أيضاً مختبرات حديثة للعمل العملي. أتمنّى أن أدرس في مدرسة كهذه يوماً ما.',
        checklistAr: [
          'كتبت عن الموضوع المطلوب نفسه (مدرسة المستقبل).',
          'استخدمت المستقبل بـ will + الفعل الأساسي بشكل صحيح.',
          'استخدمت مفردات الوحدة الأولى مثل flexible, modern, practical, virtual reality.',
          'راعيت الإملاء وعلامات الترقيم والحروف الكبيرة.',
        ],
      },
    },
  ],
}
