import type { Module } from '../../engine/types'
import { withExtras } from './extras/merge'
import { extras } from './extras/module5'

const base: Module = {
  number: 5,
  title: "Values & Time",
  titleAr: "القيم والوقت",
  color: "#ff4b4b",
  units: [
    // ===================== UNIT 9 — Stay Positive (pages 56–59) =====================
    {
      id: "u9", number: 9, module: 5,
      title: "Stay Positive", titleAr: "كن إيجابياً", pages: "56–59", emoji: "🌱",
      planAr: "المحادثة: نناقش مع الزميل عبارات تعبّر عن القيم (الطموح، الأمانة، الوفاء، الإيثار). القراءة: نص «مَن يستحق الجائزة؟» عن الأخلاق. المفردات: كلمات مرتبطة بالقيم واشتقاق الكلمات. القواعد: ضمائر الوصل وجمل الصلة (who – which – that – whose – where – when). الاستماع: قصة «لا يضيع المعروف أبداً» (No Good Deed Goes Unrewarded) وأغنية السلام. الكتابة: تقديم نصائح لتغيير سلوك سيئ.",
      vocab: [
        { en: "deserve", ar: "يستحق", pos: "verb", def: "to be worthy of something", defAr: "أن تكون جديراً بشيء ما", example: "Who Deserves the Award?", exampleAr: "مَن يستحق الجائزة؟" },
        { en: "rejoice", ar: "يفرح / يبتهج", pos: "verb", def: "to express great happiness about something/ celebrate", defAr: "أن تُظهر سعادة كبيرة بشيء ما / أن تحتفل", example: "Children rejoiced over this challenge and they all started writing diligently.", exampleAr: "فرح الأطفال بهذا التحدّي وبدؤوا جميعاً يكتبون باجتهاد." },
        { en: "challenge", ar: "تحدٍّ", pos: "noun", def: "a difficult task that tests somebody’s ability and skill", defAr: "مهمّة صعبة تختبر قدرة الشخص ومهارته", example: "Children rejoiced over this challenge and they all started writing diligently.", exampleAr: "فرح الأطفال بهذا التحدّي وبدؤوا جميعاً يكتبون باجتهاد." },
        { en: "diligently", ar: "باجتهاد / بجدّ", pos: "adverb", def: "showing care and effort in your work or duties", defAr: "بعناية وجهد في عملك أو واجباتك", example: "Children rejoiced over this challenge and they all started writing diligently.", exampleAr: "فرح الأطفال بهذا التحدّي وبدؤوا جميعاً يكتبون باجتهاد." },
        { en: "fold", ar: "يطوي", pos: "verb", def: "to lay one part of a paper on the other part/ to bend", defAr: "أن تضع جزءاً من الورقة فوق الجزء الآخر / أن تثني", example: "The students’ opinion was that each of them would write his/her name on a folded paper and put it in a box from which the teacher would pick one.", exampleAr: "كان رأي الطلاب أن يكتب كلٌّ منهم اسمه على ورقة مطويّة ويضعها في صندوق تسحب منه المعلّمة ورقة واحدة." },
        { en: "reveal", ar: "يكشف", pos: "verb", def: "make something known/ show something hidden", defAr: "أن تجعل شيئاً معروفاً / أن تُظهر شيئاً مخفياً", example: "So, the paper would reveal the name of the award’s winner.", exampleAr: "وهكذا تكشف الورقة اسم الفائز بالجائزة." },
        { en: "afford", ar: "يقدر على دفع ثمن شيء", pos: "verb", def: "to have enough money to buy something", defAr: "أن يكون لديك مال كافٍ لشراء شيء ما", example: "Her parents couldn't afford to buy her new shoes because of their extreme poverty.", exampleAr: "لم يكن والداها قادرَين على شراء حذاء جديد لها بسبب فقرهما الشديد." },
        { en: "motivate", ar: "يحفّز", pos: "verb", def: "to make someone want to do something", defAr: "أن تجعل شخصاً يرغب في فعل شيء ما", example: "Mariam was a teacher who wanted to motivate her students and make them do their best in the exam.", exampleAr: "كانت مريم معلّمةً أرادت أن تحفّز طلابها وتجعلهم يبذلون أقصى جهدهم في الامتحان." },
        { en: "poverty", ar: "الفقر", pos: "noun", def: "lack of money", defAr: "قلّة المال", example: "Her parents couldn't afford to buy her new shoes because of their extreme poverty.", exampleAr: "لم يكن والداها قادرَين على شراء حذاء جديد لها بسبب فقرهما الشديد." },
        { en: "award", ar: "جائزة", pos: "noun", def: "prize", defAr: "جائزة تُعطى لمن يستحقها", example: "The teacher thanked everyone for their effort but she was confused about who would deserve the award as everyone had got the full mark.", exampleAr: "شكرت المعلّمة الجميع على جهدهم، لكنها كانت محتارة فيمن يستحق الجائزة لأن الجميع حصلوا على العلامة الكاملة." },
        { en: "gift", ar: "هدية", pos: "noun", def: "something that you give to someone", defAr: "شيء تقدّمه لشخص ما", example: "She thanked everyone for this wonderful gift.", exampleAr: "شكرت الجميع على هذه الهدية الرائعة." },
        { en: "present", ar: "هدية", pos: "noun", def: "a gift", defAr: "هدية", example: "Why did the teacher decide to give her students a present?", exampleAr: "لماذا قرّرت المعلّمة أن تقدّم هدية لطلابها؟" },
        { en: "effort", ar: "جهد", pos: "noun", def: "hard work that you do to achieve something", defAr: "العمل الجادّ الذي تبذله لتحقيق شيء ما", example: "The teacher thanked everyone for their effort but she was confused about who would deserve the award as everyone had got the full mark.", exampleAr: "شكرت المعلّمة الجميع على جهدهم، لكنها كانت محتارة فيمن يستحق الجائزة لأن الجميع حصلوا على العلامة الكاملة." },
        { en: "confused", ar: "محتار / مرتبك", pos: "adjective", def: "not able to decide or understand something", defAr: "غير قادر على أن يقرّر أو يفهم شيئاً", example: "The teacher thanked everyone for their effort but she was confused about who would deserve the award as everyone had got the full mark.", exampleAr: "شكرت المعلّمة الجميع على جهدهم، لكنها كانت محتارة فيمن يستحق الجائزة لأن الجميع حصلوا على العلامة الكاملة." },
        { en: "solution", ar: "حلّ", pos: "noun", def: "a way to solve a problem", defAr: "طريقة لحلّ مشكلة", example: "The teacher thought of a suitable solution with her students.", exampleAr: "فكّرت المعلّمة مع طلابها في حلّ مناسب." },
        { en: "suitable", ar: "مناسب", pos: "adjective", def: "right for a particular situation", defAr: "ملائم لموقف معيّن", example: "The teacher thought of a suitable solution with her students.", exampleAr: "فكّرت المعلّمة مع طلابها في حلّ مناسب." },
        { en: "opinion", ar: "رأي", pos: "noun", def: "what you think about something", defAr: "ما تفكّر فيه بخصوص أمر ما", example: "The students’ opinion was that each of them would write his/her name on a folded paper and put it in a box from which the teacher would pick one.", exampleAr: "كان رأي الطلاب أن يكتب كلٌّ منهم اسمه على ورقة مطويّة ويضعها في صندوق تسحب منه المعلّمة ورقة واحدة." },
        { en: "winner", ar: "فائز", pos: "noun", def: "the person who wins a prize", defAr: "الشخص الذي يفوز بجائزة", example: "So, the paper would reveal the name of the award’s winner.", exampleAr: "وهكذا تكشف الورقة اسم الفائز بالجائزة." },
        { en: "owner", ar: "صاحب / مالك", pos: "noun", def: "the person who has something", defAr: "الشخص الذي يملك شيئاً", example: "Indeed, the teacher picked a paper in front of all students and read the child's name [Nada], and said: “you are the owner of the award”.", exampleAr: "وبالفعل، سحبت المعلّمة ورقة أمام جميع الطلاب وقرأت اسم الطفلة [ندى]، وقالت: «أنتِ صاحبة الجائزة»." },
        { en: "joy", ar: "فرح", pos: "noun", def: "great happiness", defAr: "سعادة كبيرة", example: "With joy and tears in her eyes, Nada came forward where the shoes were.", exampleAr: "وبفرحٍ ودموعٍ في عينيها، تقدّمت ندى إلى حيث كان الحذاء." },
        { en: "tear", ar: "دمعة", pos: "noun", def: "a drop of water that comes from your eye when you cry", defAr: "قطرة ماء تخرج من عينك عندما تبكي", example: "He was surprised and wanted to know the reason of her tears.", exampleAr: "تفاجأ وأراد أن يعرف سبب دموعها." },
        { en: "extreme", ar: "شديد / بالغ", pos: "adjective", def: "very great", defAr: "كبير جداً / شديد جداً", example: "Her parents couldn't afford to buy her new shoes because of their extreme poverty.", exampleAr: "لم يكن والداها قادرَين على شراء حذاء جديد لها بسبب فقرهما الشديد." },
        { en: "astonished", ar: "مندهش", pos: "adjective", def: "very surprised", defAr: "متفاجئ جداً", example: "When was the teacher astonished?", exampleAr: "متى اندهشت المعلّمة؟" },
        { en: "surprised", ar: "متفاجئ", pos: "adjective", def: "feeling that something is unexpected", defAr: "تشعر بأن شيئاً ما لم يكن متوقّعاً", example: "He was surprised and wanted to know the reason of her tears.", exampleAr: "تفاجأ وأراد أن يعرف سبب دموعها." },
        { en: "unfold", ar: "يفتح (شيئاً مطويّاً)", pos: "verb", def: "to open something that was folded", defAr: "أن تفتح شيئاً كان مطويّاً", example: "What did the teacher discover when she unfolded the papers?", exampleAr: "ماذا اكتشفت المعلّمة عندما فتحت الأوراق المطويّة؟" },
        { en: "discover", ar: "يكتشف", pos: "verb", def: "to find out something you did not know", defAr: "أن تعرف شيئاً لم تكن تعرفه", example: "What did the teacher discover when she unfolded the papers?", exampleAr: "ماذا اكتشفت المعلّمة عندما فتحت الأوراق المطويّة؟" },
        { en: "value", ar: "قيمة", pos: "noun", def: "a belief about what is good and important in life", defAr: "مبدأ عمّا هو جيد ومهمّ في الحياة", example: "Are values important for the society?", exampleAr: "هل القيم مهمّة للمجتمع؟" },
        { en: "moral", ar: "خُلُق / مبدأ أخلاقي", pos: "noun", def: "a rule about right and wrong behaviour", defAr: "قاعدة عن السلوك الصحيح والخاطئ", example: "Name other values and morals.", exampleAr: "اذكر قيماً وأخلاقاً أخرى." },
        { en: "ambition", ar: "طموح", pos: "noun", def: "a strong wish to achieve something great", defAr: "رغبة قوية في تحقيق شيء عظيم" },
        { en: "honesty", ar: "الأمانة / الصدق", pos: "noun", def: "telling the truth and not taking what is not yours", defAr: "قول الحقيقة وعدم أخذ ما ليس لك" },
        { en: "loyalty", ar: "الوفاء / الإخلاص", pos: "noun", def: "staying a true friend to someone", defAr: "أن تبقى صديقاً مخلصاً لشخص ما" },
        { en: "selflessness", ar: "الإيثار / نكران الذات", pos: "noun", def: "caring about other people more than yourself", defAr: "أن تهتمّ بالآخرين أكثر من نفسك" },
        { en: "respect", ar: "احترام", pos: "noun", def: "a good opinion of someone and polite behaviour towards them", defAr: "تقدير الآخرين ومعاملتهم بأدب" },
        { en: "courage", ar: "شجاعة", pos: "noun", def: "the ability to do something difficult without fear", defAr: "القدرة على فعل شيء صعب دون خوف" },
        { en: "belong to", ar: "يخصّ / يعود ملكه إلى", pos: "verb", def: "to be owned by someone", defAr: "أن يكون الشيء ملكاً لشخص ما", example: "I think this belongs to you.", exampleAr: "أظنّ أن هذا يخصّك." },
        { en: "limit", ar: "حدّ", pos: "noun", def: "the greatest amount or point possible", defAr: "أقصى مقدار أو نقطة ممكنة", example: "The sky has no limit.", exampleAr: "السماء ليس لها حدود (الطموح لا حدود له)." },
        { en: "behaviour", ar: "سلوك", pos: "noun", def: "the way someone acts", defAr: "الطريقة التي يتصرّف بها الشخص", example: "My friend complained about her teenage son's behaviour and his struggle with the family about studying and academic failure.", exampleAr: "اشتكت صديقتي من سلوك ابنها المراهق ومن صراعه مع العائلة بشأن الدراسة ومن فشله الدراسي." },
        { en: "complain", ar: "يشتكي", pos: "verb", def: "to say that you are not happy about something", defAr: "أن تقول إنك غير راضٍ عن شيء ما", example: "My friend complained about her teenage son's behaviour and his struggle with the family about studying and academic failure.", exampleAr: "اشتكت صديقتي من سلوك ابنها المراهق ومن صراعه مع العائلة بشأن الدراسة ومن فشله الدراسي." },
        { en: "struggle", ar: "صراع / نزاع", pos: "noun", def: "a fight or strong disagreement", defAr: "خلاف أو نزاع قوي", example: "My friend complained about her teenage son's behaviour and his struggle with the family about studying and academic failure.", exampleAr: "اشتكت صديقتي من سلوك ابنها المراهق ومن صراعه مع العائلة بشأن الدراسة ومن فشله الدراسي." },
        { en: "failure", ar: "فشل / إخفاق", pos: "noun", def: "not succeeding in something", defAr: "عدم النجاح في شيء ما", example: "My friend complained about her teenage son's behaviour and his struggle with the family about studying and academic failure.", exampleAr: "اشتكت صديقتي من سلوك ابنها المراهق ومن صراعه مع العائلة بشأن الدراسة ومن فشله الدراسي." },
        { en: "independence", ar: "استقلال", pos: "noun", def: "being free and not controlled by other people", defAr: "أن تكون حرّاً لا يتحكّم بك الآخرون" },
        { en: "authority", ar: "سلطة", pos: "noun", def: "the power to control or give orders", defAr: "القدرة على التحكّم وإعطاء الأوامر" },
        { en: "mutual", ar: "متبادل", pos: "adjective", def: "shared by two or more people", defAr: "مشترك بين شخصين أو أكثر", example: "She told me that he began to show negative feelings towards others and his relationship with his community has no longer become based on mutual understanding and giving.", exampleAr: "أخبرتني أنه بدأ يُظهر مشاعر سلبية تجاه الآخرين، وأن علاقته بمجتمعه لم تعد قائمة على التفاهم المتبادل والعطاء." },
        { en: "negative", ar: "سلبي", pos: "adjective", def: "bad or harmful; not positive", defAr: "سيئ أو ضارّ؛ عكس إيجابي", example: "She told me that he began to show negative feelings towards others and his relationship with his community has no longer become based on mutual understanding and giving.", exampleAr: "أخبرتني أنه بدأ يُظهر مشاعر سلبية تجاه الآخرين، وأن علاقته بمجتمعه لم تعد قائمة على التفاهم المتبادل والعطاء." },
        { en: "deed", ar: "عمل / صنيع", pos: "noun", def: "something that someone does, good or bad", defAr: "شيء يفعله الشخص، خيراً كان أو شرّاً" },
      ],
      reading: {
        title: "Who Deserves the Award?",
        paragraphs: [
          "Mariam was a teacher who wanted to motivate her students and make them do their best in the exam. So, she told them that she would give a gift, which was a new pair of shoes, to the one whose marks would be excellent. Children rejoiced over this challenge and they all started writing diligently. After collecting the papers, the teacher was surprised to find that everyone had a full mark.",
          "Who would get the gift? she thought. The teacher thanked everyone for their effort but she was confused about who would deserve the award as everyone had got the full mark.",
          "The teacher thought of a suitable solution with her students. The students’ opinion was that each of them would write his/her name on a folded paper and put it in a box from which the teacher would pick one. So, the paper would reveal the name of the award’s winner.",
          "Indeed, the teacher picked a paper in front of all students and read the child's name [Nada], and said: “you are the owner of the award”. With joy and tears in her eyes, Nada came forward where the shoes were. She thanked everyone for this wonderful gift. Her parents couldn't afford to buy her new shoes because of their extreme poverty.",
          "The teacher returned home crying and told her husband what had happened. He was surprised and wanted to know the reason of her tears. She said: “When I opened the rest of the papers, I found that all the students had written the same name [Nada]”.",
        ],
        paragraphsAr: [
          "كانت مريم معلّمةً أرادت أن تحفّز طلابها وتجعلهم يبذلون أقصى جهدهم في الامتحان. لذلك أخبرتهم أنها ستقدّم هدية، وهي زوج أحذية جديد، لمن تكون علاماته ممتازة. فرح الأطفال بهذا التحدّي وبدؤوا جميعاً يكتبون باجتهاد. وبعد جمع الأوراق، فوجئت المعلّمة بأن الجميع حصلوا على العلامة الكاملة.",
          "«مَن سيحصل على الهدية؟» فكّرت في نفسها. شكرت المعلّمة الجميع على جهدهم، لكنها كانت محتارة فيمن يستحق الجائزة لأن الجميع حصلوا على العلامة الكاملة.",
          "فكّرت المعلّمة مع طلابها في حلّ مناسب. كان رأي الطلاب أن يكتب كلٌّ منهم اسمه على ورقة مطويّة ويضعها في صندوق تسحب منه المعلّمة ورقة واحدة. وهكذا تكشف الورقة اسم الفائز بالجائزة.",
          "وبالفعل، سحبت المعلّمة ورقة أمام جميع الطلاب وقرأت اسم الطفلة [ندى]، وقالت: «أنتِ صاحبة الجائزة». وبفرحٍ ودموعٍ في عينيها، تقدّمت ندى إلى حيث كان الحذاء. شكرت الجميع على هذه الهدية الرائعة. فوالداها لم يكونا قادرَين على شراء حذاء جديد لها بسبب فقرهما الشديد.",
          "عادت المعلّمة إلى البيت باكيةً وأخبرت زوجها بما حدث. فتفاجأ وأراد أن يعرف سبب دموعها. فقالت: «عندما فتحتُ بقية الأوراق، وجدتُ أن جميع الطلاب قد كتبوا الاسم نفسه [ندى]».",
        ],
        questions: [
          { q: "Why did the teacher decide to give her students a present?", qAr: "لماذا قرّرت المعلّمة أن تقدّم هدية لطلابها؟",
            options: ["Because it was Nada’s birthday.", "Because the students were poor.", "To motivate them and make them do their best in the exam.", "To thank them for cleaning the classroom."],
            answer: 2, explainAr: "الفقرة الأولى: Mariam was a teacher who wanted to motivate her students and make them do their best in the exam — أرادت أن تحفّزهم ليبذلوا أقصى جهدهم في الامتحان." },
          { q: "When was the teacher astonished?", qAr: "متى اندهشت المعلّمة؟",
            options: ["Before the exam started.", "After collecting the papers, when she found that everyone had a full mark.", "When Nada came forward to take the shoes.", "When her husband asked her about her tears."],
            answer: 1, explainAr: "astonished = surprised. النص يقول: After collecting the papers, the teacher was surprised to find that everyone had a full mark — بعد جمع الأوراق وجدت أن الجميع أخذوا العلامة الكاملة." },
          { q: "What did the teacher discover when she unfolded the papers?", qAr: "ماذا اكتشفت المعلّمة عندما فتحت الأوراق المطويّة؟",
            options: ["Each student had written his/her own name.", "Some papers were empty.", "All the students had written the same name, Nada.", "Nada had written her name twice."],
            answer: 2, explainAr: "في آخر النص قالت المعلّمة: When I opened the rest of the papers, I found that all the students had written the same name [Nada] — كل الطلاب كتبوا اسم ندى." },
          { q: "Correct the statement: “Mariam was the headteacher of the school.”", qAr: "صحّح العبارة: «كانت مريم مديرة المدرسة.»",
            options: ["Mariam was a student.", "Mariam was a teacher.", "Mariam was Nada’s mother.", "Mariam was a doctor."],
            answer: 1, explainAr: "العبارة خاطئة؛ النص يقول: Mariam was a teacher — كانت معلّمة وليست مديرة (headteacher)." },
          { q: "Correct the statement: “She decided to give a gift to the politest student.”", qAr: "صحّح العبارة: «قرّرت أن تقدّم هدية للطالب الأكثر تهذيباً.»",
            options: ["She decided to give a gift to the tallest student.", "She decided to give a gift to the one whose marks would be excellent.", "She decided to give a gift to the poorest student.", "She decided to give a gift to every student."],
            answer: 1, explainAr: "النص يقول: to the one whose marks would be excellent — الهدية لمن تكون علاماته ممتازة، وليست للأكثر تهذيباً." },
          { q: "Correct the statement: “The gift was a series of stories.”", qAr: "صحّح العبارة: «كانت الهدية سلسلة من القصص.»",
            options: ["The gift was a new bag.", "The gift was a box of pens.", "The gift was a new pair of shoes.", "The gift was some money."],
            answer: 2, explainAr: "النص يقول: a gift, which was a new pair of shoes — كانت الهدية زوج أحذية جديد." },
          { q: "Check the statement: “The students suggested an idea for choosing the winner.” What does the text say?", qAr: "تحقّق من العبارة: «اقترح الطلاب فكرة لاختيار الفائز.» ماذا يقول النص؟",
            options: ["It is wrong: the teacher’s husband suggested the idea.", "It is wrong: the headteacher chose the winner.", "It is wrong: Nada suggested the idea.", "It is right: the students’ opinion was that each of them would write a name on a folded paper and put it in a box."],
            answer: 3, explainAr: "هذه العبارة في الحقيقة صحيحة حسب النص: The students’ opinion was that each of them would write his/her name on a folded paper… — الفكرة جاءت من الطلاب، وقد فكّرت المعلّمة معهم في الحلّ." },
          { q: "Correct the statement: “Each student wrote his/her name on the paper to get the prize.”", qAr: "صحّح العبارة: «كتب كل طالب اسمه على الورقة ليحصل على الجائزة.»",
            options: ["Each student wrote the teacher’s name on the paper.", "Each student wrote Nada’s name on the paper so that she would get the prize.", "Each student left the paper empty.", "Each student wrote the name of his/her best friend."],
            answer: 1, explainAr: "في النهاية وجدت المعلّمة أن all the students had written the same name [Nada] — كلهم كتبوا اسم ندى لأن والديها فقيران ولا يستطيعان شراء حذاء جديد لها؛ وهذا هو الإيثار (selflessness)." },
        ],
        trueFalse: [
          { statement: "After collecting the papers, the teacher found that everyone had a full mark.", answer: true },
          { statement: "Nada’s parents could afford to buy her new shoes.", answer: false },
          { statement: "The teacher picked a paper in front of all students.", answer: true },
          { statement: "The teacher returned home laughing.", answer: false },
          { statement: "All the students had written the same name.", answer: true },
        ],
      },
      vocabFocus: {
        name: "Words Related to Values, Derivatives",
        nameAr: "مفردات مرتبطة بالقيم، واشتقاق الكلمات",
        ruleEn: [
          "Find words in the text that mean: to make someone want to do something → motivate; lack of money → poverty; prize → award.",
          "Complete the sentences with suitable words from exercise 1.",
          "Values: ambition – honesty – loyalty – selflessness (It is better to give than to take. I’m a friend to the end. I think this belongs to you. The sky has no limit.)",
          "Derivatives: one root gives different parts of speech: poor → poverty, honest → honesty, loyal → loyalty, ambitious → ambition, motivate → motivation, diligent → diligently.",
        ],
        ruleAr: [
          "ابحث في النص عن الكلمات التي تعني: أن تجعل شخصاً يريد فعل شيء ← motivate (يحفّز)، قلّة المال ← poverty (الفقر)، جائزة ← award.",
          "القيم الأربع في المحادثة: ambition (الطموح): The sky has no limit. / honesty (الأمانة): I think this belongs to you. / loyalty (الوفاء): I’m a friend to the end. / selflessness (الإيثار): It is better to give than to take.",
          "الاشتقاق: من الجذر نفسه نأخذ اسماً وصفةً وظرفاً وفعلاً. الصفة تصف اسماً (an honest person)، والاسم يأتي بعد حرف جر أو أداة (in poverty)، والظرف (-ly) يصف الفعل (writing diligently).",
          "لواحق الأسماء الشائعة: ‎-ty / -ity (honesty, loyalty, poverty)، ‎-tion (motivation, ambition)، ‎-ness (selflessness). ولاحقة الظرف: ‎-ly (diligently).",
        ],
        examples: [
          "It is better to give than to take.",
          "I’m a friend to the end.",
          "I think this belongs to you.",
          "The sky has no limit.",
          "Children rejoiced over this challenge and they all started writing diligently.",
          "Her parents couldn't afford to buy her new shoes because of their extreme poverty.",
        ],
        exercises: [
          { type: "mcq", prompt: "Find a word in the text (Paragraph 1) that means: “to make someone want to do something”.", promptAr: "ابحث في النص (الفقرة 1) عن كلمة تعني: «أن تجعل شخصاً يرغب في فعل شيء».", options: ["motivate", "rejoice", "deserve", "reveal"], answer: 0, explainAr: "Mariam was a teacher who wanted to motivate her students — motivate = يحفّز، أي يجعل الشخص يرغب في العمل." },
          { type: "mcq", prompt: "Find a word in the text that means: “lack of money”.", promptAr: "ابحث في النص عن كلمة تعني: «قلّة المال».", options: ["tears", "poverty", "joy", "effort"], answer: 1, explainAr: "because of their extreme poverty — poverty = الفقر، أي قلّة المال." },
          { type: "mcq", prompt: "Find a word in the text that means: “prize”.", promptAr: "ابحث في النص عن كلمة تعني: «جائزة».", options: ["challenge", "paper", "award", "box"], answer: 2, explainAr: "who would deserve the award — award = prize = جائزة." },
          { type: "fill", prompt: "Millions of people in the world live in ___.", promptAr: "يعيش ملايين الناس في العالم في ___.", promptArFull: "يعيش ملايين الناس في العالم في الفقر.", options: ["poverty", "award", "motivate"], answer: 0, explainAr: "بعد حرف الجر in نحتاج اسماً، والمعنى: يعيشون في الفقر ← poverty." },
          { type: "fill", prompt: "She was nominated for the best actor ___.", promptAr: "رُشّحت لـ___ أفضل ممثّل.", promptArFull: "رُشّحت لجائزة أفضل ممثّل.", options: ["award", "poverty", "motivate"], answer: 0, explainAr: "nominated for = رُشّح لـ… والشيء الذي يُرشَّح له الممثّل هو جائزة ← award." },
          { type: "fill", prompt: "The plan is designed to ___ workers to work efficiently.", promptAr: "صُمّمت الخطة لـ___ العمّال على العمل بكفاءة.", promptArFull: "صُمّمت الخطة لتحفيز العمّال على العمل بكفاءة.", options: ["poverty", "award", "motivate"], answer: 2, explainAr: "بعد to نحتاج فعلاً في المصدر، والمعنى: لتحفيز العمّال ← motivate." },
          { type: "mcq", prompt: "What value does this statement refer to? “It is better to give than to take.”", promptAr: "إلى أي قيمة تشير هذه العبارة؟ «العطاء خير من الأخذ.»", options: ["ambition", "honesty", "loyalty", "selflessness"], answer: 3, explainAr: "أن تعطي الآخرين وتفضّلهم على نفسك هو الإيثار ← selflessness." },
          { type: "mcq", prompt: "What value does this statement refer to? “I’m a friend to the end.”", promptAr: "إلى أي قيمة تشير هذه العبارة؟ «أنا صديق حتى النهاية.»", options: ["ambition", "honesty", "loyalty", "selflessness"], answer: 2, explainAr: "أن تبقى مع صديقك حتى النهاية هو الوفاء ← loyalty." },
          { type: "mcq", prompt: "What value does this statement refer to? “I think this belongs to you.”", promptAr: "إلى أي قيمة تشير هذه العبارة؟ «أظنّ أن هذا يخصّك.»", options: ["ambition", "honesty", "loyalty", "selflessness"], answer: 1, explainAr: "أن تُرجع الشيء لصاحبه هو الأمانة ← honesty." },
          { type: "mcq", prompt: "What value does this statement refer to? “The sky has no limit.”", promptAr: "إلى أي قيمة تشير هذه العبارة؟ «السماء ليس لها حدود.»", options: ["honesty", "ambition", "loyalty", "selflessness"], answer: 1, explainAr: "من يرى أن لا حدود لما يمكنه تحقيقه طموح ← ambition." },
          { type: "fill", prompt: "Children ___ over this challenge.", promptAr: "___ الأطفال بهذا التحدّي.", promptArFull: "فرح الأطفال بهذا التحدّي.", options: ["rejoiced", "afforded", "revealed"], answer: 0, explainAr: "rejoice = to express great happiness (يفرح). الأطفال فرحوا بالتحدّي ← rejoiced." },
          { type: "fill", prompt: "Children rejoiced over this ___ and they all started writing diligently.", promptAr: "فرح الأطفال بهذا ___ وبدؤوا جميعاً يكتبون باجتهاد.", promptArFull: "فرح الأطفال بهذا التحدّي وبدؤوا جميعاً يكتبون باجتهاد.", options: ["challenge", "poverty", "winner"], answer: 0, explainAr: "challenge = a difficult task that tests somebody’s ability and skill (تحدٍّ): المنافسة على الهدية تحدٍّ." },
          { type: "fill", prompt: "They all started writing ___.", promptAr: "بدؤوا جميعاً يكتبون ___.", promptArFull: "بدؤوا جميعاً يكتبون باجتهاد.", options: ["diligent", "diligently", "diligence"], answer: 1, explainAr: "بعد الفعل writing نحتاج ظرفاً يصف طريقة الكتابة، والظرف ينتهي غالباً بـ ‎-ly ← diligently (باجتهاد)." },
          { type: "fill", prompt: "Her parents couldn't ___ to buy her new shoes.", promptAr: "لم يكن والداها ___ على شراء حذاء جديد لها.", promptArFull: "لم يكن والداها قادرَين على شراء حذاء جديد لها.", options: ["deserve", "fold", "afford"], answer: 2, explainAr: "afford = to have enough money to buy something. couldn't afford to buy = لم يملكا مالاً كافياً للشراء." },
          { type: "fill", prompt: "So, the paper would ___ the name of the award’s winner.", promptAr: "وهكذا ___ الورقة اسم الفائز بالجائزة.", promptArFull: "وهكذا تكشف الورقة اسم الفائز بالجائزة.", options: ["rejoice", "afford", "reveal"], answer: 2, explainAr: "reveal = make something known / show something hidden (يكشف): الورقة تكشف الاسم المخفي." },
          { type: "fill", prompt: "The teacher was confused about who would ___ the award.", promptAr: "كانت المعلّمة محتارة فيمن ___ الجائزة.", promptArFull: "كانت المعلّمة محتارة فيمن يستحق الجائزة.", options: ["fold", "deserve", "reveal"], answer: 1, explainAr: "deserve = to be worthy of something (يستحق). من يستحق الجائزة ← deserve." },
          { type: "fill", prompt: "Each student wrote his/her name on a ___ paper.", promptAr: "كتب كل طالب اسمه على ورقة ___.", promptArFull: "كتب كل طالب اسمه على ورقة مطويّة.", options: ["folded", "revealed", "rejoiced"], answer: 0, explainAr: "fold = to bend a paper (يطوي)، والصفة folded = مطويّة، تصف الورقة." },
          { type: "fill", prompt: "Nada’s parents couldn't buy her new shoes because they were very ___.", promptAr: "لم يستطع والدا ندى شراء حذاء جديد لها لأنهما كانا ___ جداً.", promptArFull: "لم يستطع والدا ندى شراء حذاء جديد لها لأنهما كانا فقيرَين جداً.", options: ["poor", "poverty", "poorly"], answer: 0, explainAr: "بعد were very نحتاج صفة ← poor (فقير). أما poverty فاسم (الفقر)، و poorly ظرف." },
          { type: "fill", prompt: "An ___ person gives back what belongs to others.", promptAr: "الشخص ___ يُرجع ما يخصّ الآخرين.", promptArFull: "الشخص الأمين يُرجع ما يخصّ الآخرين.", options: ["honesty", "honest", "honestly"], answer: 1, explainAr: "قبل الاسم person نحتاج صفة ← honest (أمين). honesty اسم (الأمانة)." },
          { type: "fill", prompt: "A ___ friend is a friend to the end.", promptAr: "الصديق ___ صديق حتى النهاية.", promptArFull: "الصديق الوفيّ صديق حتى النهاية.", options: ["loyalty", "loyally", "loyal"], answer: 2, explainAr: "قبل الاسم friend نحتاج صفة ← loyal (وفيّ). loyalty اسم (الوفاء)." },
          { type: "fill", prompt: "An ___ student believes that the sky has no limit.", promptAr: "الطالب ___ يؤمن بأن السماء ليس لها حدود.", promptArFull: "الطالب الطموح يؤمن بأن السماء ليس لها حدود.", options: ["ambitious", "ambition", "ambitiously"], answer: 0, explainAr: "قبل الاسم student نحتاج صفة ← ambitious (طموح). ambition اسم (الطموح)." },
          { type: "fill", prompt: "The gift was a good ___ for the students to do their best.", promptAr: "كانت الهدية ___ جيداً للطلاب ليبذلوا أقصى جهدهم.", promptArFull: "كانت الهدية حافزاً جيداً للطلاب ليبذلوا أقصى جهدهم.", options: ["motivation", "motivate", "motivated"], answer: 0, explainAr: "بعد a good نحتاج اسماً ← motivation (حافز). motivate فعل، و motivated صفة." },
          { type: "truefalse", prompt: "“Diligently” is an adverb: it tells us how the children wrote.", promptAr: "الكلمة «diligently» ظرف: تخبرنا كيف كتب الأطفال.", answer: true, explainAr: "صحيح: diligently ظرف ينتهي بـ ‎-ly ويصف الفعل writing (يكتبون باجتهاد)." },
          { type: "truefalse", prompt: "“Poverty” is an adjective.", promptAr: "الكلمة «poverty» صفة.", answer: false, explainAr: "خطأ: poverty اسم (الفقر)، والصفة منها poor (فقير)." },
        ],
      },
      grammar: {
        name: "Relative Pronouns and Relative Clauses",
        nameAr: "ضمائر الوصل وجمل الصلة",
        ruleEn: [
          "A relative clause comes after a noun and gives more information about it. It starts with a relative pronoun.",
          "who → for people: Mary was a teacher who wanted to motivate her students.",
          "which → for things: She thought of a simple and symbolic gift, which is a new pair of shoes.",
          "that → for people or things: My parents bought a new house that was very expensive.",
          "whose → for possession (his / her / their): The gift was for the student whose marks are excellent.",
          "where → for places: Nada came forward where the shoes were.",
          "when → for time: He arrived at seven when it was nearly dark.",
        ],
        ruleAr: [
          "جملة الصلة تأتي بعد الاسم مباشرة لتعطي معلومات إضافية عنه، وتبدأ بضمير وصل (مثل: الذي، التي، الذين).",
          "who للعاقل (الأشخاص): a teacher who wanted… = معلّمة أرادت…",
          "which لغير العاقل (الأشياء والحيوانات): a gift which is a new pair of shoes. وبعد الفاصلة نستخدم which وليس that.",
          "that للعاقل وغير العاقل معاً: a house that was very expensive.",
          "whose للملكية، ويأتي بعده اسم مباشرة: the student whose marks are excellent = الطالب الذي علاماتُه ممتازة (whose = his / her / their).",
          "where للمكان: a school where we all studied = مدرسة درسنا فيها. و when للزمان: at seven when it was nearly dark.",
          "لا نكرّر الضمير بعد ضمير الوصل: نقول a teacher who wanted ولا نقول a teacher who she wanted.",
        ],
        examples: [
          "Mary was a teacher who wanted to motivate her students.",
          "She thought of a simple and symbolic gift, which is a new pair of shoes.",
          "The gift was for the student whose marks are excellent.",
          "Nada came forward where the shoes were.",
          "She thanked everyone for this wonderful gift which came on time.",
          "This is the bank which was robbed yesterday.",
          "My parents bought a new house that was very expensive.",
          "The woman whose car was broken is my neighbour.",
          "My sister teaches in a school where we all studied.",
          "He arrived at seven when it was nearly dark.",
        ],
        exercises: [
          // Book, exercise A (p. 58)
          { type: "fill", prompt: "Mary was a teacher ___ wanted to motivate her students.", promptAr: "كانت ماري معلّمةً ___ أرادت أن تحفّز طلابها.", promptArFull: "كانت ماري معلّمةً أرادت أن تحفّز طلابها.", options: ["which", "whose", "who", "where"], answer: 2, explainAr: "teacher شخص (عاقل)، وبعد الفراغ فعل مباشرة (wanted)، فنستخدم who. أما which فللأشياء، و whose للملكية، و where للمكان." },
          { type: "fill", prompt: "She thought of a simple and symbolic gift, ___ is a new pair of shoes.", promptAr: "فكّرت في هدية بسيطة ورمزية، ___ زوج أحذية جديد.", promptArFull: "فكّرت في هدية بسيطة ورمزية، وهي زوج أحذية جديد.", options: ["who", "which", "where", "whose"], answer: 1, explainAr: "gift شيء (غير عاقل) ← which. وبعد الفاصلة لا نستخدم that، بل which." },
          { type: "fill", prompt: "The gift was for the student ___ marks are excellent.", promptAr: "كانت الهدية للطالب ___ ممتازة.", promptArFull: "كانت الهدية للطالب الذي علاماته ممتازة.", options: ["whose", "who", "which", "where"], answer: 0, explainAr: "بعد الفراغ اسم (marks) يملكه الطالب: علاماتُه ← whose للملكية. whose = his/her." },
          { type: "fill", prompt: "The teacher thought ___ would get the gift?", promptAr: "فكّرت المعلّمة: ___ سيحصل على الهدية؟", promptArFull: "فكّرت المعلّمة: مَن سيحصل على الهدية؟", options: ["which", "where", "whose", "who"], answer: 3, explainAr: "في النص: Who would get the gift? she thought. نتحدّث عن شخص لا نعرفه (مَن؟) ← who." },
          { type: "fill", prompt: "Nada came forward ___ the shoes were.", promptAr: "تقدّمت ندى ___ كان الحذاء.", promptArFull: "تقدّمت ندى إلى حيث كان الحذاء.", options: ["when", "where", "which", "who"], answer: 1, explainAr: "نتحدّث عن مكان (المكان الذي كان فيه الحذاء) ← where للمكان." },
          { type: "fill", prompt: "She thanked everyone for this wonderful gift ___ came on time.", promptAr: "شكرت الجميع على هذه الهدية الرائعة ___ جاءت في وقتها.", promptArFull: "شكرت الجميع على هذه الهدية الرائعة التي جاءت في وقتها.", options: ["who", "where", "which", "whose"], answer: 2, explainAr: "gift شيء، وبعد الفراغ فعل (came) ← which (ويصحّ that أيضاً)." },
          // Book, exercise B (p. 58)
          { type: "mcq", prompt: "Complete with the suitable relative clause: “This is the bank ___”", promptAr: "أكمل بجملة الصلة المناسبة: «هذا هو المصرف ___»", options: ["is my neighbour.", "when it was nearly dark.", "which was robbed yesterday."], answer: 2, explainAr: "bank شيء ← which: This is the bank which was robbed yesterday = هذا هو المصرف الذي سُرق أمس." },
          { type: "mcq", prompt: "Complete with the suitable relative clause: “My parents bought a new house ___”", promptAr: "أكمل بجملة الصلة المناسبة: «اشترى والداي بيتاً جديداً ___»", options: ["is my neighbour.", "that was very expensive.", "when it was nearly dark."], answer: 1, explainAr: "house شيء، و that تصلح للأشياء: My parents bought a new house that was very expensive = بيتاً جديداً كان غالياً جداً." },
          { type: "mcq", prompt: "Complete with the suitable relative clause: “The woman whose car was broken ___”", promptAr: "أكمل بجملة الصلة المناسبة: «المرأة التي تعطّلت سيارتها ___»", options: ["which was robbed yesterday.", "where we all studied.", "when it was nearly dark.", "is my neighbour."], answer: 3, explainAr: "The woman whose car was broken هي الفاعل، وتحتاج فعلاً يكمل الجملة ← is my neighbour = المرأة التي تعطّلت سيارتها هي جارتي." },
          { type: "mcq", prompt: "Complete with the suitable relative clause: “My sister teaches in a school ___”", promptAr: "أكمل بجملة الصلة المناسبة: «تدرّس أختي في مدرسة ___»", options: ["where we all studied.", "is my neighbour.", "when it was nearly dark."], answer: 0, explainAr: "school مكان ← where: My sister teaches in a school where we all studied = في مدرسة درسنا فيها جميعاً." },
          { type: "mcq", prompt: "Complete with the suitable relative clause: “He arrived at seven ___”", promptAr: "أكمل بجملة الصلة المناسبة: «وصل في السابعة ___»", options: ["where we all studied.", "when it was nearly dark.", "is my neighbour."], answer: 1, explainAr: "at seven وقت (زمان) ← when: He arrived at seven when it was nearly dark = وصل في السابعة حين كان الظلام قد حلّ تقريباً." },
          // More practice
          { type: "fill", prompt: "Nada was the girl ___ name was on all the papers.", promptAr: "كانت ندى الفتاة ___ على جميع الأوراق.", promptArFull: "كانت ندى الفتاة التي كان اسمها على جميع الأوراق.", options: ["who", "which", "whose", "where"], answer: 2, explainAr: "بعد الفراغ اسم (name) تملكه الفتاة: اسمُها ← whose." },
          { type: "fill", prompt: "The shoes ___ Nada got were new.", promptAr: "الحذاء ___ أخذته ندى كان جديداً.", promptArFull: "الحذاء الذي أخذته ندى كان جديداً.", options: ["which", "who", "whose", "where"], answer: 0, explainAr: "shoes أشياء (غير عاقل) ← which." },
          { type: "fill", prompt: "The students wrote their names on papers ___ they put in a box.", promptAr: "كتب الطلاب أسماءهم على أوراق ___ في صندوق.", promptArFull: "كتب الطلاب أسماءهم على أوراق وضعوها في صندوق.", options: ["who", "whose", "when", "which"], answer: 3, explainAr: "papers أشياء ← which." },
          { type: "fill", prompt: "Nada’s parents were poor people ___ couldn't afford to buy her new shoes.", promptAr: "كان والدا ندى فقيرَين ___ يقدران على شراء حذاء جديد لها.", promptArFull: "كان والدا ندى فقيرَين لا يقدران على شراء حذاء جديد لها.", options: ["which", "whose", "who", "where"], answer: 2, explainAr: "people أشخاص (عاقل)، وبعد الفراغ فعل مباشرة ← who." },
          { type: "fill", prompt: "This is the school ___ Mariam teaches.", promptAr: "هذه هي المدرسة ___ مريم.", promptArFull: "هذه هي المدرسة التي تدرّس فيها مريم.", options: ["when", "where", "who", "whose"], answer: 1, explainAr: "school مكان، ومعنى الجملة: المدرسة التي تدرّس فيها مريم ← where." },
          { type: "fill", prompt: "I will never forget the day ___ Nada got the gift.", promptAr: "لن أنسى أبداً اليوم ___ ندى على الهدية.", promptArFull: "لن أنسى أبداً اليوم الذي حصلت فيه ندى على الهدية.", options: ["when", "where", "who", "whose"], answer: 0, explainAr: "day زمان ← when (اليوم الذي حصلت فيه…)." },
          { type: "fill", prompt: "Mariam is the teacher ___ students all wrote the same name.", promptAr: "مريم هي المعلّمة ___ جميعاً الاسم نفسه.", promptArFull: "مريم هي المعلّمة التي كتب طلابها جميعاً الاسم نفسه.", options: ["who", "which", "where", "whose"], answer: 3, explainAr: "بعد الفراغ اسم (students) يعود للمعلّمة: طلابُها ← whose." },
          { type: "fill", prompt: "A challenge is a difficult task ___ tests somebody’s ability and skill.", promptAr: "التحدّي مهمّة صعبة ___ قدرة الشخص ومهارته.", promptArFull: "التحدّي مهمّة صعبة تختبر قدرة الشخص ومهارته.", options: ["who", "that", "whose", "where"], answer: 1, explainAr: "task شيء، و that تصلح للأشياء والأشخاص. (هذا هو تعريف الكلمة في Key Words.)" },
          { type: "fill", prompt: "The students ___ got full marks thanked the teacher.", promptAr: "الطلاب ___ على العلامة الكاملة شكروا المعلّمة.", promptArFull: "الطلاب الذين حصلوا على العلامة الكاملة شكروا المعلّمة.", options: ["which", "whose", "who", "where"], answer: 2, explainAr: "students أشخاص ← who (الذين حصلوا…)." },
          { type: "fill", prompt: "The teacher returned home, ___ she told her husband what had happened.", promptAr: "عادت المعلّمة إلى البيت، ___ زوجها بما حدث.", promptArFull: "عادت المعلّمة إلى البيت، حيث أخبرت زوجها بما حدث.", options: ["when", "who", "where", "whose"], answer: 2, explainAr: "home مكان ← where (حيث)." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["The teacher who students wrote the same name cried.", "The teacher whose students wrote the same name cried.", "The teacher which students wrote the same name cried.", "The teacher where students wrote the same name cried."], answer: 1, explainAr: "الطلاب يعودون للمعلّمة (طلابُها)، والملكية تحتاج whose ويأتي بعده اسم (students)." },
          { type: "mcq", prompt: "Which relative pronoun do we use for places?", promptAr: "أي ضمير وصل نستخدم للمكان؟", options: ["when", "where", "who", "which"], answer: 1, explainAr: "where للمكان: a school where we all studied." },
          { type: "mcq", prompt: "Which relative pronoun shows possession?", promptAr: "أي ضمير وصل يدلّ على الملكية؟", options: ["who", "which", "that", "whose"], answer: 3, explainAr: "whose للملكية ويأتي بعده اسم: the student whose marks are excellent." },
          { type: "mcq", prompt: "Which relative pronoun can we use for both people and things?", promptAr: "أي ضمير وصل نستطيع استخدامه للأشخاص والأشياء معاً؟", options: ["that", "who", "where", "whose"], answer: 0, explainAr: "that تصلح للعاقل وغير العاقل: a teacher that… / a house that…" },
          { type: "mcq", prompt: "Join the two sentences: “Mariam was a teacher. She wanted to motivate her students.”", promptAr: "اربط الجملتين: «كانت مريم معلّمة. أرادت أن تحفّز طلابها.»", options: ["Mariam was a teacher which wanted to motivate her students.", "Mariam was a teacher who wanted to motivate her students.", "Mariam was a teacher who she wanted to motivate her students.", "Mariam was a teacher whose wanted to motivate her students."], answer: 1, explainAr: "She تعود على شخص فنضع who مكانها، ولا نكرّر she بعد who." },
          { type: "mcq", prompt: "Join the two sentences: “This is the student. His marks are excellent.”", promptAr: "اربط الجملتين: «هذا هو الطالب. علاماته ممتازة.»", options: ["This is the student who his marks are excellent.", "This is the student which marks are excellent.", "This is the student whose marks are excellent.", "This is the student whose his marks are excellent."], answer: 2, explainAr: "His (ملكية) تتحوّل إلى whose، ولا نكرّر his بعدها." },
          { type: "mcq", prompt: "Join the two sentences: “Nada came forward. The shoes were there.”", promptAr: "اربط الجملتين: «تقدّمت ندى. كان الحذاء هناك.»", options: ["Nada came forward where the shoes were.", "Nada came forward when the shoes were.", "Nada came forward who the shoes were.", "Nada came forward where the shoes were there."], answer: 0, explainAr: "there تدلّ على مكان فنستبدلها بـ where ونحذف there." },
          { type: "truefalse", prompt: "In “The gift was for the student whose marks are excellent.”, whose shows possession.", promptAr: "في الجملة «The gift was for the student whose marks are excellent.» تدلّ whose على الملكية.", answer: true, explainAr: "صحيح: whose marks = his/her marks (علاماتُه)." },
          { type: "truefalse", prompt: "“Mariam was a teacher which wanted to motivate her students.” is correct.", promptAr: "الجملة «Mariam was a teacher which wanted to motivate her students.» صحيحة.", answer: false, explainAr: "خطأ: teacher شخص، فنستخدم who وليس which. which للأشياء." },
          { type: "truefalse", prompt: "In “He arrived at seven when it was nearly dark.”, when is used for time.", promptAr: "في الجملة «He arrived at seven when it was nearly dark.» تُستخدم when للزمان.", answer: true, explainAr: "صحيح: at seven وقت، و when لجملة الصلة الزمانية." },
          { type: "build", prompt: "رتّب الكلمات: كانت ماري معلّمة أرادت أن تحفّز طلابها.", answer: "Mary was a teacher who wanted to motivate her students.", extraWords: ["which", "whose"] },
          { type: "build", prompt: "رتّب الكلمات: كانت الهدية للطالب الذي علاماته ممتازة.", answer: "The gift was for the student whose marks are excellent.", extraWords: ["who", "which"] },
          { type: "build", prompt: "رتّب الكلمات: تقدّمت ندى إلى حيث كان الحذاء.", answer: "Nada came forward where the shoes were.", extraWords: ["when", "which"] },
          { type: "build", prompt: "رتّب الكلمات: هذا هو المصرف الذي سُرق أمس.", answer: "This is the bank which was robbed yesterday.", extraWords: ["where", "who"] },
          { type: "build", prompt: "رتّب الكلمات: المرأة التي تعطّلت سيارتها هي جارتي.", answer: "The woman whose car was broken is my neighbour.", extraWords: ["who", "her"] },
        ],
      },
      listening: {
        taskAr: "استمع إلى قصة «لا يضيع المعروف أبداً» (No Good Deed Goes Unrewarded)، ثم: A. حدّد إن كانت العبارات صحيحة (T) أو خاطئة (F). B. اختر الإجابة الصحيحة. (الإجابات في التسجيل الصوتي.) وفي الوحدة أيضاً الاستماع إلى أغنية السلام (the song of peace).",
        items: [
          "A1. The boy spent his days delivering letters.",
          "A2. He asked the girl for some food.",
          "A3. Doctors told the girl that her medical situation would cost a lot of money.",
          "A4. She could afford to pay the bill.",
          "B1. The boy was very …… (a. brave  b. weak  c. strong)",
          "B2. The girl had a beautiful …… (a. face  b. dimple  c. voice)",
          "B3. The girl …… payment for the milk. (a. saved  b. accepted  c. refused)",
          "B4. The doctor spent …… treating her until she was finally cured. (a. days  b. months  c. years)",
        ],
      },
      writing: {
        taskAr: "اقرأ الفقرة واكتب نصائح مناسبة لتغيير السلوك السيئ. ترجمة الفقرة: «اشتكت صديقتي من سلوك ابنها المراهق ومن صراعه مع العائلة بشأن الدراسة ومن فشله الدراسي. كان يضيّع وقته في أشياء غير مفيدة، ويتمرّد على سلطة والديه، ويُظهر رغبة في الاستقلال التام عن العائلة. وأخبرتني أنه بدأ يُظهر مشاعر سلبية تجاه الآخرين، وأن علاقته بمجتمعه لم تعد قائمة على التفاهم المتبادل والعطاء.» ثم أكمل الجمل: I advised her to… (نصحتُها أن…) / She is supposed to… (يُفترض بها أن…) / It is better to… (من الأفضل أن…) / I added that… (وأضفتُ أن…) / She should… (يجب عليها أن…) / She shouldn’t… (لا يجب عليها أن…).",
        model: [
          "My friend complained about her teenage son's behaviour and his struggle with the family about studying and academic failure. He used to waste time with things that were not useful, rebell against the authority of his parents and showing a desire for complete independence from the family. She told me that he began to show negative feelings towards others and his relationship with his community has no longer become based on mutual understanding and giving.",
        ],
        linkers: ["I advised her to …", "She is supposed to …", "It is better to …", "I added that …", "She should …", "She shouldn’t …"],
      },
      sentences: [
        "It is better to give than to take.",
        "I think this belongs to you.",
        "The sky has no limit.",
        "Are values important for the society?",
        "Children rejoiced over this challenge and they all started writing diligently.",
        "The teacher thought of a suitable solution with her students.",
        "So, the paper would reveal the name of the award’s winner.",
        "With joy and tears in her eyes, Nada came forward where the shoes were.",
        "She thanked everyone for this wonderful gift.",
        "Her parents couldn't afford to buy her new shoes because of their extreme poverty.",
        "The teacher returned home crying and told her husband what had happened.",
        "He was surprised and wanted to know the reason of her tears.",
        "Why did the teacher decide to give her students a present?",
        "What did the teacher discover when she unfolded the papers?",
      ],
    },
    // ===================== UNIT 10 — Time Waits for No One (pages 60–65) =====================
    {
      id: "u10", number: 10, module: 5,
      title: "Time Waits for No One", titleAr: "الوقت لا ينتظر أحداً", pages: "60–65", emoji: "⏰",
      planAr: "المحادثة: الحديث عن تنظيم الوقت. القراءة: نص «قتل الوقت ليس جريمة قتل!!!» عن أهمية الوقت ومبدأ «افعلها الآن» (Do It Now). المفردات: كلمات مرتبطة بالوقت. القواعد: الأسئلة المنقولة (Reported Questions). اللفظ: الصوت القصير /u/ والطويل /u:/. الاستماع: حوار عن وقت الفراغ. الكتابة: علامات الترقيم والأحرف الكبيرة. وفي آخر الوحدة: صفحة «Focus on» عن تاريخ قياس الوقت، ومشروع كتابة ملف حقائق (Fact File) عن اختراع قديم.",
      vocab: [
        { en: "productive", ar: "مُنتِج / مثمر", pos: "adjective", def: "fruitful", defAr: "مثمر، يعطي نتائج جيدة", example: "We all should use our time in productive ways.", exampleAr: "علينا جميعاً أن نستخدم وقتنا بطرق مثمرة." },
        { en: "efficiently", ar: "بكفاءة", pos: "adverb", def: "getting good results without wasting time or energy", defAr: "بالحصول على نتائج جيدة دون إضاعة الوقت أو الطاقة", example: "If you master the technique of managing time efficiently, you can achieve anything in your life.", exampleAr: "إذا أتقنتَ أسلوب إدارة الوقت بكفاءة، فبإمكانك أن تحقّق أي شيء في حياتك." },
        { en: "attain", ar: "يحقّق / ينال", pos: "verb", def: "gain", defAr: "يكسب / يحصل على", example: "Time management helps you to attain more with less effort.", exampleAr: "تساعدك إدارة الوقت على تحقيق المزيد بجهد أقل." },
        { en: "eventually", ar: "في النهاية", pos: "adverb", def: "in the end", defAr: "في النهاية / في آخر الأمر", example: "Eventually, this will encourage you to achieve more in life.", exampleAr: "في النهاية، سيشجّعك هذا على أن تحقّق المزيد في الحياة." },
        { en: "murder", ar: "جريمة قتل", pos: "noun", def: "illegal killing of a person", defAr: "قتل شخص بشكل مخالف للقانون", example: "Killing time is not a murder.", exampleAr: "قتل الوقت ليس جريمة قتل." },
        { en: "suicide", ar: "انتحار", pos: "noun", def: "self-murder", defAr: "أن يقتل الإنسان نفسه", example: "The proverb, “killing time is not a murder; it’s a suicide” is applicable for those who don’t understand the value of time and don’t respect it.", exampleAr: "المثل القائل «قتل الوقت ليس جريمة قتل، بل هو انتحار» ينطبق على الذين لا يفهمون قيمة الوقت ولا يحترمونه." },
        { en: "applicable", ar: "ينطبق على / قابل للتطبيق", pos: "adjective", def: "concerns or related to", defAr: "يخصّ الشيء أو يتعلّق به", example: "The proverb, “killing time is not a murder; it’s a suicide” is applicable for those who don’t understand the value of time and don’t respect it.", exampleAr: "المثل القائل «قتل الوقت ليس جريمة قتل، بل هو انتحار» ينطبق على الذين لا يفهمون قيمة الوقت ولا يحترمونه." },
        { en: "principle", ar: "مبدأ", pos: "noun", def: "moral rule", defAr: "قاعدة أخلاقية" },
        { en: "precious", ar: "ثمين", pos: "adjective", def: "very valuable", defAr: "ذو قيمة كبيرة جداً", example: "Time is precious!", exampleAr: "الوقت ثمين!" },
        { en: "waste", ar: "يضيّع / يهدر", pos: "verb", def: "to use something badly or for nothing useful", defAr: "أن تستخدم شيئاً بشكل سيئ أو في شيء غير مفيد", example: "We should never waste it in any way.", exampleAr: "يجب ألّا نضيّعه أبداً بأي شكل من الأشكال." },
        { en: "valuable", ar: "قيّم / ثمين", pos: "adjective", def: "very important and useful", defAr: "مهمّ ومفيد جداً", example: "That is why most of successful people consider time more important and valuable than money.", exampleAr: "لهذا يعتبر معظم الناجحين الوقت أهمّ وأثمن من المال." },
        { en: "consider", ar: "يعتبر / يَعُدّ", pos: "verb", def: "to think of something in a particular way", defAr: "أن تنظر إلى شيء بطريقة معيّنة", example: "That is why most of successful people consider time more important and valuable than money.", exampleAr: "لهذا يعتبر معظم الناجحين الوقت أهمّ وأثمن من المال." },
        { en: "master", ar: "يُتقن", pos: "verb", def: "to learn to do something very well", defAr: "أن تتعلّم فعل شيء بشكل ممتاز", example: "If you master the technique of managing time efficiently, you can achieve anything in your life.", exampleAr: "إذا أتقنتَ أسلوب إدارة الوقت بكفاءة، فبإمكانك أن تحقّق أي شيء في حياتك." },
        { en: "technique", ar: "أسلوب / تقنية", pos: "noun", def: "a special way of doing something", defAr: "طريقة خاصة لفعل شيء ما", example: "If you master the technique of managing time efficiently, you can achieve anything in your life.", exampleAr: "إذا أتقنتَ أسلوب إدارة الوقت بكفاءة، فبإمكانك أن تحقّق أي شيء في حياتك." },
        { en: "manage", ar: "يدير / ينظّم", pos: "verb", def: "to control and organise something", defAr: "أن تتحكّم بشيء وتنظّمه", example: "Managing time efficiently enables us to achieve our goals.", exampleAr: "إدارة الوقت بكفاءة تمكّننا من تحقيق أهدافنا." },
        { en: "achieve", ar: "يحقّق / يُنجز", pos: "verb", def: "to succeed in doing something", defAr: "أن تنجح في فعل شيء ما", example: "Managing time efficiently enables us to achieve our goals.", exampleAr: "إدارة الوقت بكفاءة تمكّننا من تحقيق أهدافنا." },
        { en: "regularly", ar: "بانتظام", pos: "adverb", def: "often and at the same times", defAr: "باستمرار وفي أوقات ثابتة", example: "In the beginning, it will feel like a boring task, but when you do it regularly, you realize that it only helps you to increase your productivity.", exampleAr: "في البداية ستشعر أنها مهمّة مملّة، لكن عندما تقوم بها بانتظام، تدرك أنها تساعدك فقط على زيادة إنتاجيتك." },
        { en: "productivity", ar: "الإنتاجية", pos: "noun", def: "how much good work you do", defAr: "مقدار العمل الجيد الذي تنجزه", example: "In the beginning, it will feel like a boring task, but when you do it regularly, you realize that it only helps you to increase your productivity.", exampleAr: "في البداية ستشعر أنها مهمّة مملّة، لكن عندما تقوم بها بانتظام، تدرك أنها تساعدك فقط على زيادة إنتاجيتك." },
        { en: "encourage", ar: "يشجّع", pos: "verb", def: "to give someone the wish and confidence to do something", defAr: "أن تمنح شخصاً الرغبة والثقة لفعل شيء", example: "Eventually, this will encourage you to achieve more in life.", exampleAr: "في النهاية، سيشجّعك هذا على أن تحقّق المزيد في الحياة." },
        { en: "involved", ar: "منشغل / منخرط", pos: "adjective", def: "taking part in something", defAr: "مشارك في شيء ما", example: "Being productive doesn’t mean that we have to be involved in multiple tasks at the same time.", exampleAr: "أن تكون منتِجاً لا يعني أن علينا الانشغال بمهام متعدّدة في الوقت نفسه." },
        { en: "multiple", ar: "متعدّد", pos: "adjective", def: "many", defAr: "كثير / عديد", example: "Being productive doesn’t mean that we have to be involved in multiple tasks at the same time.", exampleAr: "أن تكون منتِجاً لا يعني أن علينا الانشغال بمهام متعدّدة في الوقت نفسه." },
        { en: "proverb", ar: "مَثَل", pos: "noun", def: "a short well-known saying that gives advice", defAr: "قول قصير مشهور يقدّم نصيحة", example: "The proverb, “killing time is not a murder; it’s a suicide” is applicable for those who don’t understand the value of time and don’t respect it.", exampleAr: "المثل القائل «قتل الوقت ليس جريمة قتل، بل هو انتحار» ينطبق على الذين لا يفهمون قيمة الوقت ولا يحترمونه." },
        { en: "divide", ar: "يقسّم", pos: "verb", def: "to separate something into parts", defAr: "أن تفصل شيئاً إلى أجزاء", example: "Divide what you have to do.", exampleAr: "قسّم ما عليك فعله." },
        { en: "organise", ar: "ينظّم / يرتّب", pos: "verb", def: "to put things in order", defAr: "أن تضع الأشياء في ترتيب معيّن", example: "Organise your materials.", exampleAr: "رتّب أدواتك وموادّك." },
        { en: "ignore", ar: "يتجاهل", pos: "verb", def: "to pay no attention to something", defAr: "ألّا تعير شيئاً أي انتباه" },
        { en: "interruption", ar: "مقاطعة / انقطاع", pos: "noun", def: "something that stops you while you are doing something", defAr: "شيء يوقفك وأنت تقوم بعمل ما" },
        { en: "opportunity", ar: "فرصة", pos: "noun", def: "a good chance to do something", defAr: "فرصة جيدة لفعل شيء ما", example: "Take advantage of opportunities.", exampleAr: "اغتنم الفرص." },
        { en: "take advantage of", ar: "يغتنم / يستفيد من", pos: "phrase", def: "to use a chance well", defAr: "أن تستفيد من فرصة جيداً", example: "Take advantage of opportunities.", exampleAr: "اغتنم الفرص." },
        { en: "time stealer", ar: "سارق الوقت", pos: "noun", def: "something that takes your time without being useful", defAr: "شيء يأخذ وقتك دون فائدة", example: "Watch out for time stealers.", exampleAr: "احذر من سارقي الوقت." },
        { en: "invest", ar: "يستثمر", pos: "verb", def: "to use something so that you get something good later", defAr: "أن تستخدم شيئاً لتحصل على فائدة لاحقاً", example: "Therefore, we should know how to invest it.", exampleAr: "لذلك يجب أن نعرف كيف نستثمره." },
        { en: "leisure time", ar: "وقت الفراغ", pos: "noun", def: "free time when you are not working", defAr: "الوقت الحرّ الذي لا تعمل فيه", example: "The two friends are talking about leisure time.", exampleAr: "يتحدّث الصديقان عن وقت الفراغ." },
        { en: "roam", ar: "يتجوّل", pos: "verb", def: "to walk around with no special aim", defAr: "أن تمشي هنا وهناك دون هدف محدّد" },
        { en: "punctuation", ar: "علامات الترقيم", pos: "noun", def: "marks like the full stop (.) and the comma (,) in writing", defAr: "إشارات مثل النقطة (.) والفاصلة (,) في الكتابة", example: "Rewrite the following paragraph using correct punctuation and capitalization.", exampleAr: "أعد كتابة الفقرة الآتية مستخدماً علامات الترقيم والأحرف الكبيرة بشكل صحيح." },
        { en: "capitalization", ar: "استخدام الأحرف الكبيرة", pos: "noun", def: "writing capital letters in the right places", defAr: "كتابة الأحرف الكبيرة في أماكنها الصحيحة", example: "Rewrite the following paragraph using correct punctuation and capitalization.", exampleAr: "أعد كتابة الفقرة الآتية مستخدماً علامات الترقيم والأحرف الكبيرة بشكل صحيح." },
        { en: "observation", ar: "ملاحظة / مراقبة", pos: "noun", def: "watching something carefully", defAr: "مراقبة شيء ما بعناية", example: "Ancient humans used simple observation to dictate the time.", exampleAr: "استخدم البشر القدماء الملاحظة البسيطة لتحديد الوقت." },
        { en: "ancient", ar: "قديم", pos: "adjective", def: "from a very long time ago", defAr: "من زمن بعيد جداً", example: "The water clock was created by the ancient Greeks.", exampleAr: "صنع الإغريق القدماء الساعة المائية." },
        { en: "sundial", ar: "المزولة (الساعة الشمسية)", pos: "noun", def: "a clock that uses the sun’s shadow to show the time", defAr: "ساعة تستخدم ظلّ الشمس لتبيّن الوقت", example: "Then, the sundial was developed.", exampleAr: "ثم طُوِّرت المزولة الشمسية." },
        { en: "solar-powered", ar: "يعمل بالطاقة الشمسية", pos: "adjective", def: "working by the energy of the sun", defAr: "يعمل بطاقة الشمس", example: "It was the first solar-powered clock.", exampleAr: "كانت أول ساعة تعمل بالطاقة الشمسية." },
        { en: "obelisk", ar: "مِسَلّة", pos: "noun", def: "a tall stone column with four sides", defAr: "عمود حجري طويل له أربعة جوانب", example: "Egyptians then created four-sided obelisks that throw away a shadow on the ground to show what time of day it was.", exampleAr: "ثم صنع المصريون مسلّات رباعية الجوانب تُلقي ظلاً على الأرض لتبيّن الوقت من النهار." },
        { en: "shadow", ar: "ظلّ", pos: "noun", def: "the dark shape made when something blocks the light", defAr: "الشكل المظلم الذي يتكوّن عندما يحجب شيءٌ الضوء", example: "Egyptians then created four-sided obelisks that throw away a shadow on the ground to show what time of day it was.", exampleAr: "ثم صنع المصريون مسلّات رباعية الجوانب تُلقي ظلاً على الأرض لتبيّن الوقت من النهار." },
        { en: "water clock", ar: "الساعة المائية", pos: "noun", def: "an old clock that measures time by the flow of water", defAr: "ساعة قديمة تقيس الوقت بجريان الماء", example: "The water clock was created by the ancient Greeks.", exampleAr: "صنع الإغريق القدماء الساعة المائية." },
        { en: "hourglass", ar: "الساعة الرملية", pos: "noun", def: "two glass bulbs joined by a narrow neck, used to measure time", defAr: "كرتان زجاجيتان يصل بينهما عنق ضيّق، تُستخدمان لقياس الوقت", example: "The hourglass is yet another piece which was made from two separate glass bulbs that had been rounded.", exampleAr: "الساعة الرملية قطعة أخرى صُنعت من كرتين زجاجيتين منفصلتين مستديرتين." },
        { en: "keep track of", ar: "يتتبّع / يحسب", pos: "phrase", def: "to follow and know how something changes", defAr: "أن تتابع شيئاً وتعرف كيف يتغيّر", example: "It was used to keep track of the hours of night time, but could be used in the day as well.", exampleAr: "كانت تُستخدم لحساب ساعات الليل، لكن كان يمكن استخدامها في النهار أيضاً." },
      ],
      reading: {
        title: "Killing Time is not a Murder!!!",
        paragraphs: [
          "Time is precious! We should never waste it in any way. People can spend a lot of time doing various things, but they can never get back the time they had spent. That is why most of successful people consider time more important and valuable than money.",
          "We all should use our time in productive ways. If you master the technique of managing time efficiently, you can achieve anything in your life. Time management helps you to attain more with less effort.",
          "In the beginning, it will feel like a boring task, but when you do it regularly, you realize that it only helps you to increase your productivity. Eventually, this will encourage you to achieve more in life. Being productive doesn’t mean that we have to be involved in multiple tasks at the same time.",
          "The proverb, “killing time is not a murder; it’s a suicide” is applicable for those who don’t understand the value of time and don’t respect it. People who say that they don't have enough time to complete their work, don’t really know how to manage time. For those, here is an easy way to help them apply the “Do It Now” principle:",
          "D = Divide what you have to do.",
          "O = Organise your materials.",
          "I = Ignore interruption.",
          "T = Take the time to learn how to do things yourself.",
          "N = Now, not tomorrow.",
          "O = Opportunity is knocking. Take advantage of opportunities.",
          "W = Watch out for time stealers. Control how much time you spend on the Internet, reading and sending emails, watching TV, or talking on the phone.",
          "Time is the greatest gift of God. Therefore, we should know how to invest it.",
        ],
        paragraphsAr: [
          "الوقت ثمين! يجب ألّا نضيّعه أبداً بأي شكل من الأشكال. يستطيع الناس أن يقضوا وقتاً طويلاً في فعل أشياء متنوّعة، لكنهم لا يستطيعون أبداً استعادة الوقت الذي قضوه. لهذا يعتبر معظم الناجحين الوقت أهمّ وأثمن من المال.",
          "علينا جميعاً أن نستخدم وقتنا بطرق مثمرة. إذا أتقنتَ أسلوب إدارة الوقت بكفاءة، فبإمكانك أن تحقّق أي شيء في حياتك. تساعدك إدارة الوقت على تحقيق المزيد بجهد أقل.",
          "في البداية ستشعر أنها مهمّة مملّة، لكن عندما تقوم بها بانتظام، تدرك أنها تساعدك فقط على زيادة إنتاجيتك. وفي النهاية، سيشجّعك هذا على أن تحقّق المزيد في الحياة. وأن تكون منتِجاً لا يعني أن علينا الانشغال بمهام متعدّدة في الوقت نفسه.",
          "المثل القائل «قتل الوقت ليس جريمة قتل، بل هو انتحار» ينطبق على الذين لا يفهمون قيمة الوقت ولا يحترمونه. فالذين يقولون إنه ليس لديهم وقت كافٍ لإنهاء عملهم لا يعرفون حقاً كيف يديرون الوقت. ولهؤلاء، إليك طريقة سهلة تساعدهم على تطبيق مبدأ «افعلها الآن» (Do It Now):",
          "D = قسّم ما عليك فعله.",
          "O = رتّب أدواتك وموادّك.",
          "I = تجاهل المقاطعات.",
          "T = خصّص الوقت لتتعلّم كيف تفعل الأشياء بنفسك.",
          "N = الآن، وليس غداً.",
          "O = الفرصة تطرق الباب. اغتنم الفرص.",
          "W = احذر من سارقي الوقت. تحكّم في مقدار الوقت الذي تقضيه على الإنترنت، وفي قراءة الرسائل الإلكترونية وإرسالها، ومشاهدة التلفاز، والتحدّث على الهاتف.",
          "الوقت أعظم هبة من الله. لذلك يجب أن نعرف كيف نستثمره.",
        ],
        questions: [
          { q: "Explain in other words: “Time is precious.”", qAr: "اشرح بكلمات أخرى: «الوقت ثمين.»", options: ["Time passes slowly.", "Time is cheap and easy to get back.", "We have a lot of time to spend.", "Time is very valuable, so we should never waste it."], answer: 3, explainAr: "precious = ثمين جداً. والنص يكمل: We should never waste it in any way — فالوقت قيّم ولا يجوز تضييعه." },
          { q: "Explain in other words: “We should use our time in productive ways.”", qAr: "اشرح بكلمات أخرى: «يجب أن نستخدم وقتنا بطرق مثمرة.»", options: ["We should do many tasks at the same time.", "We should spend all our time watching TV.", "We should spend our time doing useful things that give good results.", "We should never work hard."], answer: 2, explainAr: "productive = fruitful (مثمر): أن نستخدم الوقت في أشياء مفيدة تعطي نتائج جيدة." },
          { q: "Explain in other words: “Killing time is not a murder.”", qAr: "اشرح بكلمات أخرى: «قتل الوقت ليس جريمة قتل.»", options: ["Killing time is a crime against other people.", "When you waste your time, you harm yourself, not others: it’s a suicide.", "Wasting time is never a problem.", "Time can kill people."], answer: 1, explainAr: "المثل يكمل: it’s a suicide (إنه انتحار) — من يضيّع وقته يؤذي نفسه هو." },
          { q: "Explain in other words: “Managing time efficiently enables us to achieve our goals.”", qAr: "اشرح بكلمات أخرى: «إدارة الوقت بكفاءة تمكّننا من تحقيق أهدافنا.»", options: ["If we organise our time well, we can reach what we want.", "If we have a lot of money, we can reach our goals.", "Goals are not important for managing time.", "We cannot achieve our goals without doing many tasks together."], answer: 0, explainAr: "efficiently = بكفاءة دون إضاعة وقت أو جهد. النص: If you master the technique of managing time efficiently, you can achieve anything in your life." },
          { q: "Complete from the text: “People can’t get back the time …”", qAr: "أكمل من النص: «لا يستطيع الناس استعادة الوقت …»", options: ["they will have tomorrow.", "of successful people.", "they spend on money.", "they had spent."], answer: 3, explainAr: "الفقرة الأولى: they can never get back the time they had spent — الوقت الذي قضوه." },
          { q: "Complete from the text: “Time for successful people is considered …”", qAr: "أكمل من النص: «يُعتبر الوقت عند الناجحين …»", options: ["less important than money.", "more important and valuable than money.", "a boring task.", "a time stealer."], answer: 1, explainAr: "النص: most of successful people consider time more important and valuable than money — أهمّ وأثمن من المال." },
          { q: "Complete from the text: “You can achieve anything in your life when …”", qAr: "أكمل من النص: «تستطيع أن تحقّق أي شيء في حياتك عندما …»", options: ["you are involved in multiple tasks at the same time.", "you spend more time on the Internet.", "you master the technique of managing time efficiently.", "you have a lot of money."], answer: 2, explainAr: "الفقرة الثانية: If you master the technique of managing time efficiently, you can achieve anything in your life." },
          { q: "Complete from the text: “When you do a task regularly …”", qAr: "أكمل من النص: «عندما تقوم بمهمّة بانتظام …»", options: ["it will always feel like a boring task.", "you waste your time.", "you realize that it only helps you to increase your productivity.", "you don’t need to manage your time."], answer: 2, explainAr: "الفقرة الثالثة: when you do it regularly, you realize that it only helps you to increase your productivity." },
        ],
        trueFalse: [
          { statement: "Most successful people consider time more important than money.", answer: true },
          { statement: "People can get back the time they had spent.", answer: false },
          { statement: "Being productive means doing multiple tasks at the same time.", answer: false },
          { statement: "Time management helps you to attain more with less effort.", answer: true },
          { statement: "The “Do It Now” principle tells us to ignore interruption.", answer: true },
        ],
      },
      extraReadings: [
        {
          title: "Focus on Social Studies: The History of Time Measurement",
          paragraphs: [
            "Ancient humans used simple observation to dictate the time. They used the stars to guide them through the change of day and seasons.",
            "Then, the sundial was developed. It was the first solar-powered clock.",
            "Egyptians then created four-sided obelisks that throw away a shadow on the ground to show what time of day it was.",
            "The water clock was created by the ancient Greeks.",
            "It was used to keep track of the hours of night time, but could be used in the day as well.",
            "The hourglass is yet another piece which was made from two separate glass bulbs that had been rounded. They were connected with a narrow neck made of glass between the two bulbs.",
          ],
          paragraphsAr: [
            "استخدم البشر القدماء الملاحظة البسيطة لتحديد الوقت. فقد استعانوا بالنجوم لتهديهم إلى تغيّر النهار والفصول.",
            "ثم طُوِّرت المزولة الشمسية. وكانت أول ساعة تعمل بالطاقة الشمسية.",
            "ثم صنع المصريون مسلّات رباعية الجوانب تُلقي ظلاً على الأرض لتبيّن الوقت من النهار.",
            "وصنع الإغريق القدماء الساعة المائية.",
            "كانت تُستخدم لحساب ساعات الليل، لكن كان يمكن استخدامها في النهار أيضاً.",
            "والساعة الرملية قطعة أخرى صُنعت من كرتين زجاجيتين منفصلتين مستديرتين، تصل بينهما رقبة ضيّقة من الزجاج.",
          ],
          questions: [
            { q: "What did ancient humans use to guide them through the change of day and seasons?", qAr: "ماذا استخدم البشر القدماء ليهتدوا إلى تغيّر النهار والفصول؟", options: ["the hourglass", "the stars", "the water clock", "the obelisks"], answer: 1, explainAr: "النص: They used the stars to guide them through the change of day and seasons — استخدموا النجوم." },
            { q: "What was the first solar-powered clock?", qAr: "ما أول ساعة عملت بالطاقة الشمسية؟", options: ["the water clock", "the hourglass", "the stars", "the sundial"], answer: 3, explainAr: "النص: Then, the sundial was developed. It was the first solar-powered clock." },
            { q: "Who created the water clock?", qAr: "مَن صنع الساعة المائية؟", options: ["the ancient Greeks", "the Egyptians", "the Romans", "ancient humans who used the stars"], answer: 0, explainAr: "النص: The water clock was created by the ancient Greeks." },
            { q: "What was the hourglass made from?", qAr: "مِمّ صُنعت الساعة الرملية؟", options: ["a four-sided stone", "two separate glass bulbs connected with a narrow glass neck", "water and stars", "wood and metal"], answer: 1, explainAr: "النص: made from two separate glass bulbs … connected with a narrow neck made of glass between the two bulbs." },
          ],
          trueFalse: [
            { statement: "The Egyptians created four-sided obelisks that throw a shadow on the ground.", answer: true },
            { statement: "The water clock could only be used at night.", answer: false },
          ],
        },
      ],
      vocabFocus: {
        name: "Vocabulary Related to Time",
        nameAr: "مفردات مرتبطة بالوقت",
        ruleEn: [
          "Fill the space with words from the box: efficiently – productive – attain – principle – applicable.",
          "productive: fruitful — efficiently: getting good results without wasting time or energy — attain: gain — eventually: in the end",
          "murder: illegal killing of a person — suicide: self-murder — applicable: concerns or related to — principle: moral rule",
        ],
        ruleAr: [
          "productive (صفة) = مثمر/منتِج، يأتي قبل الاسم: a productive day.",
          "efficiently (ظرف) = بكفاءة، يأتي بعد الفعل ليصف طريقة العمل: use her time efficiently.",
          "attain (فعل) = يحقّق/ينال: attain high grades. و eventually (ظرف) = في النهاية.",
          "principle (اسم) = مبدأ أخلاقي: It's against my principle. و applicable (صفة) = ينطبق على: Is that rule applicable in this case?",
          "murder = جريمة قتل، و suicide = انتحار (قتل النفس): من يضيّع وقته يؤذي نفسه.",
          "لتختار الكلمة المناسبة انظر إلى مكان الفراغ: قبل اسم ← صفة، بعد فعل ← ظرف، بعد فاعل ← فعل، بعد my / the ← اسم.",
        ],
        examples: [
          "We all should use our time in productive ways.",
          "If you master the technique of managing time efficiently, you can achieve anything in your life.",
          "Time management helps you to attain more with less effort.",
          "Eventually, this will encourage you to achieve more in life.",
          "Killing time is not a murder.",
        ],
        exercises: [
          { type: "fill", prompt: "Is that rule ___ in this case?", promptAr: "هل تلك القاعدة ___ في هذه الحالة؟", promptArFull: "هل تلك القاعدة تنطبق في هذه الحالة؟", options: ["efficiently", "principle", "applicable", "attain"], answer: 2, explainAr: "بعد is that rule نحتاج صفة، والمعنى: هل تنطبق القاعدة؟ ← applicable (concerns or related to)." },
          { type: "fill", prompt: "It's against my ___ to lie.", promptAr: "الكذب ضدّ ___.", promptArFull: "الكذب ضدّ مبادئي.", options: ["principle", "productive", "applicable", "attain"], answer: 0, explainAr: "بعد my نحتاج اسماً، والكذب ضدّ القاعدة الأخلاقية ← principle (moral rule)." },
          { type: "fill", prompt: "She is a successful person. She knows how to use her time ___.", promptAr: "إنها شخص ناجح. تعرف كيف تستخدم وقتها ___.", promptArFull: "إنها شخص ناجح. تعرف كيف تستخدم وقتها بكفاءة.", options: ["productive", "principle", "applicable", "efficiently"], answer: 3, explainAr: "بعد use her time نحتاج ظرفاً يصف طريقة الاستخدام ← efficiently (بكفاءة)." },
          { type: "fill", prompt: "Most of our students ___ high grades in the final exam.", promptAr: "معظم طلابنا ___ علامات عالية في الامتحان النهائي.", promptArFull: "معظم طلابنا ينالون علامات عالية في الامتحان النهائي.", options: ["applicable", "efficiently", "attain", "productive"], answer: 2, explainAr: "بعد الفاعل (Most of our students) نحتاج فعلاً ← attain = gain (ينال/يحقّق)." },
          { type: "fill", prompt: "I had a very ___ day; I finished the whole work.", promptAr: "كان يومي ___ جداً؛ أنهيت العمل كله.", promptArFull: "كان يومي مثمراً جداً؛ أنهيت العمل كله.", options: ["efficiently", "productive", "principle", "attain"], answer: 1, explainAr: "قبل الاسم day نحتاج صفة، ومن أنهى عمله كله كان يومه مثمراً ← productive (fruitful)." },
          { type: "mcq", prompt: "What does “productive” mean?", promptAr: "ما معنى «productive»؟", options: ["fruitful", "in the end", "moral rule", "self-murder"], answer: 0, explainAr: "productive = fruitful (مثمر / منتِج)." },
          { type: "mcq", prompt: "What does “efficiently” mean?", promptAr: "ما معنى «efficiently»؟", options: ["illegal killing of a person", "concerns or related to", "in the end", "getting good results without wasting time or energy"], answer: 3, explainAr: "efficiently = بكفاءة، أي نتائج جيدة دون إضاعة وقت أو طاقة." },
          { type: "mcq", prompt: "What does “attain” mean?", promptAr: "ما معنى «attain»؟", options: ["waste", "gain", "ignore", "divide"], answer: 1, explainAr: "attain = gain (ينال / يحقّق)." },
          { type: "mcq", prompt: "What does “eventually” mean?", promptAr: "ما معنى «eventually»؟", options: ["at the beginning", "at the same time", "in the end", "never"], answer: 2, explainAr: "eventually = in the end (في النهاية)." },
          { type: "mcq", prompt: "What does “murder” mean?", promptAr: "ما معنى «murder»؟", options: ["self-murder", "moral rule", "illegal killing of a person", "fruitful"], answer: 2, explainAr: "murder = قتل شخص بشكل غير قانوني (جريمة قتل)." },
          { type: "mcq", prompt: "What does “suicide” mean?", promptAr: "ما معنى «suicide»؟", options: ["illegal killing of a person", "self-murder", "gain", "moral rule"], answer: 1, explainAr: "suicide = self-murder (أن يقتل الإنسان نفسه). لذلك يقول المثل إن من يقتل وقته يقتل نفسه." },
          { type: "mcq", prompt: "What does “applicable” mean?", promptAr: "ما معنى «applicable»؟", options: ["in the end", "fruitful", "gain", "concerns or related to"], answer: 3, explainAr: "applicable = concerns or related to (ينطبق على / يتعلّق بـ)." },
          { type: "mcq", prompt: "What does “principle” mean?", promptAr: "ما معنى «principle»؟", options: ["moral rule", "self-murder", "fruitful", "in the end"], answer: 0, explainAr: "principle = moral rule (مبدأ أخلاقي)، مثل مبدأ Do It Now." },
          { type: "fill", prompt: "Time is ___! We should never waste it in any way.", promptAr: "الوقت ___! يجب ألّا نضيّعه أبداً بأي شكل.", promptArFull: "الوقت ثمين! يجب ألّا نضيّعه أبداً بأي شكل.", options: ["boring", "precious", "applicable", "multiple"], answer: 1, explainAr: "precious = ثمين جداً، ولذلك لا يجب تضييعه." },
          { type: "fill", prompt: "We should never ___ it in any way.", promptAr: "يجب ألّا ___ أبداً بأي شكل.", promptArFull: "يجب ألّا نضيّعه أبداً بأي شكل.", options: ["invest", "attain", "waste", "organise"], answer: 2, explainAr: "should never + فعل: لا يجب أن نضيّع الوقت ← waste (يضيّع)." },
          { type: "fill", prompt: "Time is the greatest gift of God. Therefore, we should know how to ___ it.", promptAr: "الوقت أعظم هبة من الله. لذلك يجب أن نعرف كيف ___.", promptArFull: "الوقت أعظم هبة من الله. لذلك يجب أن نعرف كيف نستثمره.", options: ["invest", "waste", "kill", "ignore"], answer: 0, explainAr: "الهبة الثمينة نستثمرها ولا نضيّعها ← invest (يستثمر)." },
          { type: "fill", prompt: "___ your materials.", promptAr: "___ أدواتك وموادّك.", promptArFull: "رتّب أدواتك وموادّك.", options: ["Ignore", "Waste", "Divide", "Organise"], answer: 3, explainAr: "حرف O في مبدأ DO IT NOW: Organise your materials (رتّب موادّك)." },
          { type: "fill", prompt: "Opportunity is knocking. Take ___ of opportunities.", promptAr: "الفرصة تطرق الباب. ___ الفرص.", promptArFull: "الفرصة تطرق الباب. اغتنم الفرص.", options: ["care", "part", "advantage", "place"], answer: 2, explainAr: "take advantage of = يغتنم / يستفيد من." },
          { type: "fill", prompt: "Watch out for time ___.", promptAr: "احذر من ___ الوقت.", promptArFull: "احذر من سارقي الوقت.", options: ["gifts", "stealers", "principles", "managers"], answer: 1, explainAr: "time stealers = سارقو الوقت، مثل الإنترنت والتلفاز والهاتف." },
          { type: "fill", prompt: "___, this will encourage you to achieve more in life.", promptAr: "___، سيشجّعك هذا على أن تحقّق المزيد في الحياة.", promptArFull: "في النهاية، سيشجّعك هذا على أن تحقّق المزيد في الحياة.", options: ["Eventually", "Productive", "Applicable", "Precious"], answer: 0, explainAr: "في بداية الجملة نحتاج ظرفاً بمعنى (في النهاية) ← Eventually." },
          { type: "fill", prompt: "When you do it ___, you realize that it only helps you to increase your productivity.", promptAr: "عندما تقوم بها ___، تدرك أنها تساعدك فقط على زيادة إنتاجيتك.", promptArFull: "عندما تقوم بها بانتظام، تدرك أنها تساعدك فقط على زيادة إنتاجيتك.", options: ["regular", "rule", "regulation", "regularly"], answer: 3, explainAr: "بعد الفعل do it نحتاج ظرفاً ينتهي بـ ‎-ly ← regularly (بانتظام)." },
          { type: "truefalse", prompt: "“Productive” means fruitful.", promptAr: "«productive» تعني مثمر.", answer: true, explainAr: "صحيح: productive = fruitful." },
          { type: "truefalse", prompt: "“Eventually” means at the beginning.", promptAr: "«eventually» تعني في البداية.", answer: false, explainAr: "خطأ: eventually = in the end (في النهاية)." },
        ],
      },
      grammar: {
        name: "Reported Questions",
        nameAr: "الأسئلة المنقولة (الكلام غير المباشر)",
        ruleEn: [
          "Wh- questions: asked (me) + question word + subject + verb. “Where have you been?” → He asked me where I had been.",
          "Yes/No questions: asked (me) + if / whether + subject + verb. “Are you happy to be back?” → He asked me if I was happy to be back.",
          "The tense moves one step back: am / is / are → was / were; do you want → I wanted; have you been → I had been; did you stay → I had stayed; can → could.",
          "Pronouns change: you → I; me → him / her; your → my. Do / does / did disappear, and there is no question mark.",
        ],
        ruleAr: [
          "السؤال المنقول هو أن تخبر شخصاً بسؤال سأله شخص آخر: قال لي آدم «أين كنت؟» ← سألني آدم أين كنت.",
          "أسئلة Wh (how, where, what…): نكتب asked me + أداة السؤال + الفاعل + الفعل. يصبح ترتيب الجملة مثل الجملة الخبرية: where I had been وليس where had I been.",
          "أسئلة Yes/No (التي تبدأ بـ Are / Do / Can…): نضع if أو whether (بمعنى: إذا / ما إذا كان) ثم الفاعل ثم الفعل: He asked me if I was happy.",
          "نرجع بالزمن خطوة إلى الماضي: am/is ← was، are ← were، المضارع البسيط ← الماضي البسيط (want ← wanted)، المضارع التام ← الماضي التام (have been ← had been)، الماضي البسيط ← الماضي التام (did you stay ← had stayed)، can ← could، will ← would.",
          "نغيّر الضمائر حسب المعنى: you ← I، me ← him/her، your ← my. نحذف do / does / did، ولا نضع علامة استفهام في آخر الجملة، بل نقطة.",
        ],
        examples: [
          "Adam asked me how I was.",
          "He asked me where I had been.",
          "He asked me what I wanted to do.",
          "He asked me where I had stayed.",
          "He asked me if I was happy to be back.",
          "He asked me if I planned to go back.",
          "He asked me where my parents were.",
          "He asked me if I could help him to go there.",
          "He asked her if she spoke English.",
          "They wanted to know whether we had a computer.",
        ],
        exercises: [
          // Book, exercise A (p. 62): Adam's questions reported to your mother
          { type: "fill", prompt: "“How are you?” → Adam asked me how I ___.", promptAr: "«كيف حالك؟» ← سألني آدم كيف ___.", promptArFull: "«كيف حالك؟» ← سألني آدم كيف كان حالي.", options: ["am", "was", "is"], answer: 1, explainAr: "am/are في السؤال المباشر تصبح was مع I في السؤال المنقول (نرجع بالزمن خطوة). والترتيب: how + I + was." },
          { type: "fill", prompt: "“Where have you been?” → He asked me where I ___ been.", promptAr: "«أين كنت؟» ← سألني أين ___.", promptArFull: "«أين كنت؟» ← سألني أين كنتُ.", options: ["have", "has", "had"], answer: 2, explainAr: "المضارع التام have been يصبح ماضياً تاماً had been في السؤال المنقول." },
          { type: "fill", prompt: "“What do you want to do now?” → He asked me what I ___ to do.", promptAr: "«ماذا تريد أن تفعل الآن؟» ← سألني ماذا ___ أن أفعل.", promptArFull: "«ماذا تريد أن تفعل الآن؟» ← سألني ماذا أريد أن أفعل.", options: ["want", "did want", "wanted"], answer: 2, explainAr: "نحذف do، والمضارع البسيط want يصبح ماضياً بسيطاً wanted." },
          { type: "fill", prompt: "“Where did you stay?” → He asked me where I ___.", promptAr: "«أين أقمت؟» ← سألني أين ___.", promptArFull: "«أين أقمت؟» ← سألني أين كنتُ قد أقمت.", options: ["did stay", "had stayed", "stay"], answer: 1, explainAr: "الماضي البسيط (did you stay) يصبح ماضياً تاماً had stayed، ونحذف did." },
          { type: "fill", prompt: "“Are you happy to be back?” → He asked me ___ I was happy to be back.", promptAr: "«هل أنت سعيد بعودتك؟» ← سألني ___ كنت سعيداً بعودتي.", promptArFull: "«هل أنت سعيد بعودتك؟» ← سألني إن كنت سعيداً بعودتي.", options: ["if", "that", "what"], answer: 0, explainAr: "السؤال يبدأ بـ Are (سؤال Yes/No) فنستخدم if (أو whether) في السؤال المنقول." },
          { type: "fill", prompt: "“Do you plan to go back?” → He asked me if I ___ to go back.", promptAr: "«هل تخطّط للعودة؟» ← سألني إن كنت ___ للعودة.", promptArFull: "«هل تخطّط للعودة؟» ← سألني إن كنت أخطّط للعودة.", options: ["planned", "plan", "did plan"], answer: 0, explainAr: "نحذف do، ويصبح plan ماضياً planned (نرجع بالزمن خطوة)." },
          { type: "fill", prompt: "“Where are your parents?” → He asked me where my parents ___.", promptAr: "«أين والداك؟» ← سألني أين ___ والداي.", promptArFull: "«أين والداك؟» ← سألني أين كان والداي.", options: ["are", "were", "was"], answer: 1, explainAr: "are تصبح were (الجمع parents)، والفعل يأتي بعد الفاعل: where my parents were. و your تصبح my." },
          { type: "fill", prompt: "“Can you help me to go there?” → He asked me if I ___ help him to go there.", promptAr: "«هل تستطيع مساعدتي للذهاب إلى هناك؟» ← سألني إن كنت ___ مساعدته للذهاب إلى هناك.", promptArFull: "«هل تستطيع مساعدتي للذهاب إلى هناك؟» ← سألني إن كنت أستطيع مساعدته للذهاب إلى هناك.", options: ["can", "will", "could"], answer: 2, explainAr: "can تصبح could، و me تصبح him لأن المتكلّم (آدم) هو المقصود." },
          // Book, exercise B (p. 62)
          { type: "fill", prompt: "He asked her if she ___ English.", promptAr: "سألها إن كانت ___ الإنجليزية.", promptArFull: "سألها إن كانت تتكلّم الإنجليزية.", options: ["spoke", "speak", "speaks"], answer: 0, explainAr: "في السؤال المنقول بعد asked نرجع بالزمن إلى الماضي: speak ← spoke." },
          { type: "fill", prompt: "He asked me if I ___ British or American.", promptAr: "سألني إن ___ بريطانياً أم أمريكياً.", promptArFull: "سألني إن كنت بريطانياً أم أمريكياً.", options: ["was", "am", "is"], answer: 0, explainAr: "am تصبح was في السؤال المنقول." },
          { type: "fill", prompt: "They wanted to know whether we ___ a computer.", promptAr: "أرادوا أن يعرفوا ما إذا كان ___ حاسوب.", promptArFull: "أرادوا أن يعرفوا ما إذا كان لدينا حاسوب.", options: ["have", "has", "had"], answer: 2, explainAr: "wanted to know فعل في الماضي، فنرجع بالزمن: have ← had. و whether بمعنى if." },
          { type: "fill", prompt: "She asked if he ___ type.", promptAr: "سألت إن كان ___ الكتابة على الآلة الكاتبة.", promptArFull: "سألت إن كان يستطيع الكتابة على الآلة الكاتبة.", options: ["can", "could", "cans"], answer: 1, explainAr: "can تصبح could في السؤال المنقول." },
          { type: "fill", prompt: "He asked how old her mother ___.", promptAr: "سأل كم ___ عمر أمها.", promptArFull: "سأل كم كان عمر أمها.", options: ["was", "is", "be"], answer: 0, explainAr: "is تصبح was، والفعل يأتي في آخر السؤال المنقول بعد الفاعل: how old her mother was." },
          // More practice
          { type: "fill", prompt: "“Do you like reading?” → Tom asked Rita if she ___ reading.", promptAr: "«هل تحبّين القراءة؟» ← سأل توم ريتا إن كانت ___ القراءة.", promptArFull: "«هل تحبّين القراءة؟» ← سأل توم ريتا إن كانت تحبّ القراءة.", options: ["liked", "likes", "like"], answer: 0, explainAr: "سؤال Yes/No فنستخدم if، ونحذف do، ويصبح like ماضياً liked." },
          { type: "fill", prompt: "“How do you spend your leisure time?” → Rita asked Tom how he ___ his leisure time.", promptAr: "«كيف تقضي وقت فراغك؟» ← سألت ريتا توم كيف ___ وقت فراغه.", promptArFull: "«كيف تقضي وقت فراغك؟» ← سألت ريتا توم كيف يقضي وقت فراغه.", options: ["spends", "spent", "did spend"], answer: 1, explainAr: "نحذف do ونرجع بالزمن: spend ← spent. و your تصبح his." },
          { type: "fill", prompt: "“Is this possible?” → She asked ___ it was possible.", promptAr: "«هل هذا ممكن؟» ← سألت ___ كان ذلك ممكناً.", promptArFull: "«هل هذا ممكن؟» ← سألت إن كان ذلك ممكناً.", options: ["what", "that", "if"], answer: 2, explainAr: "السؤال يبدأ بـ Is (سؤال Yes/No) ← if. ولا نستخدم that في الأسئلة المنقولة." },
          { type: "fill", prompt: "“What is the man doing?” → The teacher asked us what the man ___ doing.", promptAr: "«ماذا يفعل الرجل؟» ← سألنا المعلّم ماذا ___ الرجل يفعل.", promptArFull: "«ماذا يفعل الرجل؟» ← سألنا المعلّم ماذا كان الرجل يفعل.", options: ["is", "does", "was"], answer: 2, explainAr: "is doing تصبح was doing، والفاعل (the man) يأتي قبل الفعل." },
          { type: "fill", prompt: "“How can we use time correctly?” → He asked how we ___ use time correctly.", promptAr: "«كيف نستطيع أن نستخدم الوقت بشكل صحيح؟» ← سأل كيف ___ أن نستخدم الوقت بشكل صحيح.", promptArFull: "«كيف نستطيع أن نستخدم الوقت بشكل صحيح؟» ← سأل كيف نستطيع أن نستخدم الوقت بشكل صحيح.", options: ["can", "could", "do"], answer: 1, explainAr: "can تصبح could، والترتيب: how + we + could." },
          { type: "fill", prompt: "“Have you planted different kinds of trees?” → Rita asked Tom if he ___ planted different kinds of trees.", promptAr: "«هل زرعت أنواعاً مختلفة من الأشجار؟» ← سألت ريتا توم إن كان ___ أنواعاً مختلفة من الأشجار.", promptArFull: "«هل زرعت أنواعاً مختلفة من الأشجار؟» ← سألت ريتا توم إن كان قد زرع أنواعاً مختلفة من الأشجار.", options: ["had", "has", "have"], answer: 0, explainAr: "المضارع التام have planted يصبح ماضياً تاماً had planted." },
          { type: "fill", prompt: "“Where is the post office?” → A man asked me where the post office ___.", promptAr: "«أين مكتب البريد؟» ← سألني رجل أين ___ مكتب البريد.", promptArFull: "«أين مكتب البريد؟» ← سألني رجل أين يقع مكتب البريد.", options: ["was", "is", "were"], answer: 0, explainAr: "is تصبح was، وتأتي بعد الفاعل: where the post office was." },
          { type: "fill", prompt: "“Do you want to buy stamps?” → He asked her ___ she wanted to buy stamps.", promptAr: "«هل تريدين شراء طوابع؟» ← سألها ___ كانت تريد شراء طوابع.", promptArFull: "«هل تريدين شراء طوابع؟» ← سألها ما إذا كانت تريد شراء طوابع.", options: ["what", "whether", "that"], answer: 1, explainAr: "سؤال Yes/No (يبدأ بـ Do) ← whether أو if." },
          { type: "mcq", prompt: "“Do you know how to manage your time?” Choose the correct reported question.", promptAr: "«هل تعرف كيف تدير وقتك؟» اختر السؤال المنقول الصحيح.", options: ["He asked me do I know how to manage my time.", "He asked me if did I know how to manage my time.", "He asked me if I knew how to manage my time.", "He asked me if I know how to manage your time?"], answer: 2, explainAr: "سؤال Yes/No ← if، نحذف do، know ← knew، your ← my، ولا علامة استفهام." },
          { type: "mcq", prompt: "“Why do you waste your time?” Choose the correct reported question.", promptAr: "«لماذا تضيّع وقتك؟» اختر السؤال المنقول الصحيح.", options: ["My mother asked me why I wasted my time.", "My mother asked me why did I waste my time.", "My mother asked me why I waste your time?", "My mother asked me if why I wasted my time."], answer: 0, explainAr: "أداة السؤال why + الفاعل I + الفعل wasted (نحذف do ونرجع بالزمن)، و your ← my." },
          { type: "mcq", prompt: "“When will you finish your work?” Choose the correct reported question.", promptAr: "«متى ستنهي عملك؟» اختر السؤال المنقول الصحيح.", options: ["He asked me when will I finish my work.", "He asked me when I will finish your work.", "He asked me if when I would finish my work.", "He asked me when I would finish my work."], answer: 3, explainAr: "will تصبح would، والترتيب: when + I + would finish، و your ← my." },
          { type: "mcq", prompt: "“Can you organise your materials?” → She asked me …", promptAr: "«هل تستطيع ترتيب موادّك؟» ← سألتني …", options: ["if I can organise your materials.", "could I organise my materials.", "if I could organise my materials.", "if could I organise my materials."], answer: 2, explainAr: "سؤال Yes/No ← if + الفاعل I + could (بدلاً من can)، و your ← my." },
          { type: "mcq", prompt: "Which word do we use to report a yes/no question?", promptAr: "أي كلمة نستخدم لنقل سؤال جوابه نعم / لا؟", options: ["what", "if", "where", "that"], answer: 1, explainAr: "أسئلة Yes/No تُنقل بـ if أو whether." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["She asked me where I had been.", "She asked me where had I been.", "She asked me where I had been?", "She asked me where have I been."], answer: 0, explainAr: "في السؤال المنقول يأتي الفاعل قبل الفعل (where I had been)، ولا نضع علامة استفهام." },
          { type: "mcq", prompt: "“Are you happy to be back?” — In the reported question, “you” becomes:", promptAr: "«هل أنت سعيد بعودتك؟» — في السؤال المنقول تصبح «you»:", options: ["I", "you", "they"], answer: 0, explainAr: "أنا أنقل لأمي سؤالاً وُجّه إليّ، فتصبح you ← I: He asked me if I was happy to be back." },
          { type: "truefalse", prompt: "In a reported question the subject comes before the verb: “He asked me where my parents were.”", promptAr: "في السؤال المنقول يأتي الفاعل قبل الفعل: «He asked me where my parents were.»", answer: true, explainAr: "صحيح: my parents (فاعل) ثم were (فعل)، مثل الجملة الخبرية." },
          { type: "truefalse", prompt: "We keep the question mark at the end of a reported question.", promptAr: "نُبقي علامة الاستفهام في آخر السؤال المنقول.", answer: false, explainAr: "خطأ: السؤال المنقول جملة خبرية تنتهي بنقطة: Adam asked me how I was." },
          { type: "truefalse", prompt: "In “They wanted to know whether we had a computer.”, whether has the same meaning as if.", promptAr: "في «They wanted to know whether we had a computer.» تحمل whether معنى if نفسه.", answer: true, explainAr: "صحيح: whether = if (ما إذا كان) في أسئلة Yes/No المنقولة." },
          { type: "build", prompt: "رتّب الكلمات: سألني أين كنت.", answer: "He asked me where I had been.", extraWords: ["have", "did"] },
          { type: "build", prompt: "رتّب الكلمات: أرادوا أن يعرفوا ما إذا كان لدينا حاسوب.", answer: "They wanted to know whether we had a computer.", extraWords: ["have", "do"] },
          { type: "build", prompt: "رتّب الكلمات: سألني إن كنت أستطيع مساعدته للذهاب إلى هناك.", answer: "He asked me if I could help him to go there.", extraWords: ["can", "me"] },
          { type: "build", prompt: "رتّب الكلمات: سألت ريتا توم كيف يقضي وقت فراغه.", answer: "Rita asked Tom how he spent his leisure time.", extraWords: ["does", "spends"] },
        ],
      },
      pronunciation: {
        title: "Short /u/ and long /u:/",
        ruleAr: "الصوت القصير /u/ (يُكتب في المعاجم /ʊ/) نلفظه قصيراً سريعاً بلا مدّ، مثل: put, look, full. أما الصوت الطويل /u:/ فنمدّه كالواو الممدودة «أوو»، مثل: shoot, juice, school. غالباً يأتي الطويل مع الحروف oo و ui و ue و ou و u-e (school, fruit, blue, group, rude)، لكن انتبه: oo قد تكون قصيرة كما في look, took, foot, cook، و would و pull و bush فيها الصوت القصير.",
        groups: [
          { label: "/u/ — put", words: ["put", "look", "full", "butcher", "push", "would", "took", "pull", "foot", "cook", "bush"] },
          { label: "/u:/ — shoot", words: ["shoot", "juice", "fool", "school", "soup", "fruit", "cruel", "rude", "group", "blue", "true"] },
        ],
      },
      listening: {
        taskAr: "استمع إلى الحوار بين صديقين (ريتا وتوم) عن وقت الفراغ، ثم: A. اختر الإجابة الصحيحة. B. حدّد إن كانت العبارات صحيحة (T) أو خاطئة (F). (الإجابات في التسجيل الصوتي.)",
        items: [
          "A1. The two friends are talking about …… (a. studying  b. sport  c. leisure time)",
          "A2. Rita likes reading …… (a. science fiction  b. poetry  c. history)",
          "A3. Tom spends his time …… (a. reading  b. gardening  c. roaming)",
          "A4. Tom has planted …… kinds of trees. (a. similar  b. the same  c. different)",
          "B1. She likes reading because books give her pleasure only.",
          "B2. Tom loves watching TV.",
          "B3. Rita likes to roam in her leisure time.",
          "B4. Planting trees gives much money.",
        ],
      },
      writing: {
        taskAr: "أعد كتابة الفقرة الآتية مستخدماً علامات الترقيم والأحرف الكبيرة بشكل صحيح (وصحّح الأخطاء فيها). الأخطاء: نضع مسافة بعد النقطة (centre. There)؛ نبدأ الجملة بحرف كبير بعد النقطة (Some)؛ نضع نقطة في آخر الجملة (packages.)؛ alot ← a lot؛ There is ← There are (people جمع)؛ They are wait ← They are waiting؛ wants ← want؛ stambs ← stamps؛ sent ← send؛ parking space ← parking spaces؛ there horns ← their horns؛ ونضع فاصلة قبل honking. الفقرة بعد التصحيح: The post office is in a city centre. There are a lot of people. They are waiting in line. Some people want to buy stamps. Others want to mail letters. Some people want to send packages. There are not many parking spaces near the post office. The drivers are waiting for parking places, honking their horns. ومعناها: «يقع مكتب البريد في وسط المدينة. هناك كثير من الناس ينتظرون في الطابور. بعضهم يريد شراء طوابع، وآخرون يريدون إرسال رسائل، وبعضهم يريد إرسال طرود. لا توجد أماكن كثيرة لركن السيارات قرب مكتب البريد، والسائقون ينتظرون أماكن للركن وهم يطلقون أبواق سياراتهم.»",
        model: [
          "The post office is in a city centre.There is alot of people. They are wait in line.some people wants to buy stambs. Others want to mail letters. Some people want to sent packages There are not many parking space near the post office. The drivers are waiting for parking places honking there horns.",
        ],
      },
      sentences: [
        "We should never waste it in any way.",
        "We all should use our time in productive ways.",
        "Time management helps you to attain more with less effort.",
        "Eventually, this will encourage you to achieve more in life.",
        "Take the time to learn how to do things yourself.",
        "Time is the greatest gift of God.",
        "Therefore, we should know how to invest it.",
        "How can we use time correctly?",
        "Adam asked me how I was.",
        "He asked me where I had been.",
        "He asked me what I wanted to do.",
        "He asked me if I was happy to be back.",
        "He asked me if I could help him to go there.",
        "He asked her if she spoke English.",
        "They wanted to know whether we had a computer.",
        "He asked how old her mother was.",
      ],
    },
  ],
  focus: {
    title: "Focus on Social Studies — The History of Time Measurement",
    paragraphs: [
      "Ancient humans used simple observation to dictate the time. They used the stars to guide them through the change of day and seasons.",
      "Then, the sundial was developed. It was the first solar-powered clock.",
      "Egyptians then created four-sided obelisks that throw away a shadow on the ground to show what time of day it was.",
      "The water clock was created by the ancient Greeks.",
      "It was used to keep track of the hours of night time, but could be used in the day as well.",
      "The hourglass is yet another piece which was made from two separate glass bulbs that had been rounded. They were connected with a narrow neck made of glass between the two bulbs.",
    ],
    glossary: [
      { en: "Stars", ar: "النجوم", pos: "noun", def: "used by ancient humans to guide them through the change of day and seasons", defAr: "استخدمها البشر القدماء ليهتدوا إلى تغيّر النهار والفصول" },
      { en: "The Sundial", ar: "المزولة (الساعة الشمسية)", pos: "noun", def: "the first solar-powered clock", defAr: "أول ساعة تعمل بالطاقة الشمسية" },
      { en: "The Obelisk", ar: "المِسَلّة", pos: "noun", def: "a four-sided stone that throws a shadow on the ground to show the time of day", defAr: "حجر رباعي الجوانب يُلقي ظلاً على الأرض ليبيّن الوقت من النهار" },
      { en: "The Water Clock", ar: "الساعة المائية", pos: "noun", def: "created by the ancient Greeks to keep track of the hours of night time", defAr: "صنعها الإغريق القدماء لحساب ساعات الليل" },
      { en: "The Hourglass", ar: "الساعة الرملية", pos: "noun", def: "two glass bulbs connected with a narrow glass neck", defAr: "كرتان زجاجيتان تصل بينهما رقبة زجاجية ضيّقة" },
    ],
  },
  project: {
    title: "Project — A Fact File",
    steps: [
      "Write a Fact file about an ancient invention that helped in developing human life.",
      "A fact file is a short report of all the most important information on one subject. This subject can be a thing, a place, an animal or even a person.",
      "Fact files are a great resource. They help us to learn or teach lessons about particular topics and they are also quick ways to give information.",
      "You can use the Internet to get help.",
      "Example: Great Inventions That Changed History — The Wheel",
    ],
  },
}

export const module5: Module = withExtras(base, extras)
