import type { Module } from '../../engine/types'
import { withExtras } from './extras/merge'
import { extras } from './extras/module1'

const base: Module = {
  number: 1,
  title: "Make a Difference",
  titleAr: "أحدِثْ فرقاً",
  color: "#58cc02",
  units: [
    // ===================== UNIT 1 — Work Together to Make it Better (pages 4–8) =====================
    {
      id: "u1", number: 1, module: 1,
      title: "Work Together to Make it Better", titleAr: "لنعمل معاً لنجعلها أفضل", pages: "4–8", emoji: "🤝",
      planAr: "المحادثة عن المهن (Jobs)، قراءة نص «صفّ مختلف» (A Different Class) عن المعلّمة حنان الحروب وطريقتها «العب وتعلّم»، مفردات: استخدام الكلمات المفتاحية في سياقات مختلفة، القواعد: مراجعة المضارع البسيط والمضارع المستمر (Present Simple & Present Progressive)، اللفظ: حرف a القصير /æ/ والطويل /a:/، الاستماع إلى آدم يتحدث عن تجربته مع فرقة كشّافة، والكتابة: ترتيب أجزاء فقرة عن التطوّع.",
      vocab: [
        { en: "committee", ar: "لجنة", pos: "noun", def: "a group of people chosen to make decisions", defAr: "مجموعة من الناس يُختارون لاتخاذ القرارات", example: "The committee praised Mrs. Al-Hroub’s “play and learn” method, which she still employs.", exampleAr: "أثنت اللجنة على طريقة السيدة الحروب «العب وتعلّم»، التي ما زالت تستخدمها." },
        { en: "praise", ar: "يمدح / يُثني على", pos: "verb", def: "to express approval, love, or admiration for something", defAr: "أن تعبّر عن استحسانك أو حبّك أو إعجابك بشيء", example: "The committee praised Mrs. Al-Hroub’s “play and learn” method, which she still employs.", exampleAr: "أثنت اللجنة على طريقة السيدة الحروب «العب وتعلّم»، التي ما زالت تستخدمها." },
        { en: "employ", ar: "يستخدم / يوظّف", pos: "verb", def: "to make use of something", defAr: "أن تستفيد من شيء وتستعمله", example: "The committee praised Mrs. Al-Hroub’s “play and learn” method, which she still employs.", exampleAr: "أثنت اللجنة على طريقة السيدة الحروب «العب وتعلّم»، التي ما زالت تستخدمها." },
        { en: "outfit", ar: "زيّ / طقم ملابس", pos: "noun", def: "a set of clothes that you wear together", defAr: "مجموعة من الملابس تلبسها معاً", example: "Besides her clown outfit, Mrs. Al-Hroub uses balloons, hula-hoops, toy cars and puppets to explain her lessons.", exampleAr: "إلى جانب زيّ المهرّج، تستخدم السيدة الحروب البالونات وأطواق الهولا هوب والسيارات الصغيرة والدمى لشرح دروسها." },
        { en: "struggle", ar: "معاناة / كفاح", pos: "noun", def: "something that is difficult for you to do or achieve", defAr: "شيء يصعب عليك فعله أو تحقيقه", example: "Her aim is to make the classroom a calm and fun place where children can forget about the struggle of daily life, and open their minds.", exampleAr: "هدفها أن تجعل الصف مكاناً هادئاً وممتعاً ينسى فيه الأطفال معاناة الحياة اليومية ويفتحون عقولهم." },
        { en: "violence", ar: "عنف", pos: "noun", def: "the use of physical force to harm someone", defAr: "استخدام القوة الجسدية لإيذاء شخص ما", example: "“No to violence” is a motto in her classes.", exampleAr: "«لا للعنف» شعارٌ في صفوفها." },
        { en: "poorly paid", ar: "ذو أجر زهيد", pos: "adjective", def: "earning very little money for your work", defAr: "يكسب مالاً قليلاً جداً مقابل عمله", example: "Hanan Al-Hroub was a poorly paid teacher in the West Bank.", exampleAr: "كانت حنان الحروب معلّمةً ذات أجر زهيد في الضفة الغربية." },
        { en: "prize", ar: "جائزة", pos: "noun", def: "something (like money) given to the winner", defAr: "شيء (كالمال) يُعطى للفائز", example: "Then she won the $1 million Global Teacher Prize.", exampleAr: "ثم فازت بجائزة المعلّم العالمية وقيمتها مليون دولار." },
        { en: "method", ar: "طريقة / أسلوب", pos: "noun", def: "a way of doing something", defAr: "طريقة لفعل شيء ما", example: "That soon changes, Mrs. Al-Hroub says, when they realise that her methods improve behaviour – especially in troubled kids – and academic results.", exampleAr: "تقول السيدة الحروب إن ذلك يتغيّر سريعاً عندما يدركون أن أساليبها تحسّن السلوك – ولا سيّما لدى الأطفال المضطربين – وتحسّن النتائج الدراسية." },
        { en: "clown", ar: "مهرّج", pos: "noun", def: "a person who wears funny clothes and makes people laugh", defAr: "شخص يلبس ملابس مضحكة ويُضحك الناس", example: "Besides her clown outfit, Mrs. Al-Hroub uses balloons, hula-hoops, toy cars and puppets to explain her lessons.", exampleAr: "إلى جانب زيّ المهرّج، تستخدم السيدة الحروب البالونات وأطواق الهولا هوب والسيارات الصغيرة والدمى لشرح دروسها." },
        { en: "balloon", ar: "بالون", pos: "noun", def: "a small coloured rubber bag that you fill with air", defAr: "كيس مطاطي ملوّن صغير تملؤه بالهواء", example: "In addition to the toys and balloons, which she pays for with her own money, she uses videos and even PowerPoint in the classroom.", exampleAr: "بالإضافة إلى الألعاب والبالونات التي تدفع ثمنها من مالها الخاص، تستخدم مقاطع الفيديو وحتى برنامج PowerPoint في الصف." },
        { en: "puppet", ar: "دمية (عروسة متحرّكة)", pos: "noun", def: "a toy person or animal that you move with your hand or strings", defAr: "دمية على شكل إنسان أو حيوان تحرّكها بيدك أو بخيوط", example: "Besides her clown outfit, Mrs. Al-Hroub uses balloons, hula-hoops, toy cars and puppets to explain her lessons.", exampleAr: "إلى جانب زيّ المهرّج، تستخدم السيدة الحروب البالونات وأطواق الهولا هوب والسيارات الصغيرة والدمى لشرح دروسها." },
        { en: "aim", ar: "هدف", pos: "noun", def: "what you want to achieve", defAr: "ما تريد أن تحقّقه", example: "Her aim is to make the classroom a calm and fun place where children can forget about the struggle of daily life, and open their minds.", exampleAr: "هدفها أن تجعل الصف مكاناً هادئاً وممتعاً ينسى فيه الأطفال معاناة الحياة اليومية ويفتحون عقولهم." },
        { en: "calm", ar: "هادئ", pos: "adjective", def: "quiet and peaceful", defAr: "هادئ ومسالم", example: "Her aim is to make the classroom a calm and fun place where children can forget about the struggle of daily life, and open their minds.", exampleAr: "هدفها أن تجعل الصف مكاناً هادئاً وممتعاً ينسى فيه الأطفال معاناة الحياة اليومية ويفتحون عقولهم." },
        { en: "realise", ar: "يُدرك", pos: "verb", def: "to understand or notice something", defAr: "أن تفهم شيئاً أو تنتبه إليه", example: "The kids don’t even realise they are learning.", exampleAr: "حتى إن الأطفال لا يدركون أنهم يتعلّمون." },
        { en: "pupil", ar: "تلميذ", pos: "noun", def: "a child who goes to school", defAr: "طفل يذهب إلى المدرسة", example: "For the first month of a new school year, her eight-year-old pupils may not even see an exercise book.", exampleAr: "في الشهر الأول من العام الدراسي الجديد، قد لا يرى تلاميذها ذوو الأعوام الثمانية دفترَ تمارين أصلاً." },
        { en: "refuse", ar: "يرفض", pos: "verb", def: "to say no to something", defAr: "أن تقول «لا» لشيء ما", example: "Parents often refuse the focus on play.", exampleAr: "غالباً ما يرفض الأهل التركيز على اللعب." },
        { en: "focus", ar: "تركيز", pos: "noun", def: "special attention given to something", defAr: "اهتمام خاص يُعطى لشيء ما", example: "Parents often refuse the focus on play.", exampleAr: "غالباً ما يرفض الأهل التركيز على اللعب." },
        { en: "behaviour", ar: "سلوك", pos: "noun", def: "the way someone acts", defAr: "الطريقة التي يتصرّف بها الشخص", example: "That soon changes, Mrs. Al-Hroub says, when they realise that her methods improve behaviour – especially in troubled kids – and academic results.", exampleAr: "تقول السيدة الحروب إن ذلك يتغيّر سريعاً عندما يدركون أن أساليبها تحسّن السلوك – ولا سيّما لدى الأطفال المضطربين – وتحسّن النتائج الدراسية." },
        { en: "troubled", ar: "مضطرب / يعاني مشكلات", pos: "adjective", def: "having many problems or worries", defAr: "لديه مشكلات أو هموم كثيرة", example: "She successfully deals with troubled-kids.", exampleAr: "هي تتعامل بنجاح مع الأطفال المضطربين." },
        { en: "academic", ar: "دراسي / أكاديمي", pos: "adjective", def: "connected with studying and school work", defAr: "متعلّق بالدراسة والعمل المدرسي", example: "That soon changes, Mrs. Al-Hroub says, when they realise that her methods improve behaviour – especially in troubled kids – and academic results.", exampleAr: "تقول السيدة الحروب إن ذلك يتغيّر سريعاً عندما يدركون أن أساليبها تحسّن السلوك – ولا سيّما لدى الأطفال المضطربين – وتحسّن النتائج الدراسية." },
        { en: "duty", ar: "واجب", pos: "noun", def: "something you feel you must do", defAr: "شيء تشعر أن عليك فعله", example: "She also sees it as her duty to build their characters.", exampleAr: "وهي ترى أيضاً أن من واجبها بناء شخصياتهم." },
        { en: "character", ar: "شخصية", pos: "noun", def: "the qualities that make a person who they are", defAr: "الصفات التي تجعل الإنسان على ما هو عليه", example: "She also sees it as her duty to build their characters.", exampleAr: "وهي ترى أيضاً أن من واجبها بناء شخصياتهم." },
        { en: "motto", ar: "شعار", pos: "noun", def: "a short sentence that shows what a person or group believes", defAr: "جملة قصيرة تعبّر عمّا يؤمن به شخص أو جماعة", example: "“No to violence” is a motto in her classes.", exampleAr: "«لا للعنف» شعارٌ في صفوفها." },
        { en: "establish", ar: "يؤسّس", pos: "verb", def: "to start a company or an organisation", defAr: "أن تُنشئ شركة أو مؤسسة", example: "Mrs. Al-Hroub plans to establish her own foundation and use some of her winnings to train other teachers to follow her approach.", exampleAr: "تخطّط السيدة الحروب لتأسيس مؤسستها الخاصة واستخدام جزء من المال الذي ربحته لتدريب معلّمين آخرين على اتّباع أسلوبها." },
        { en: "foundation", ar: "مؤسسة", pos: "noun", def: "an organisation that gives money or help for a good purpose", defAr: "منظّمة تقدّم المال أو المساعدة لهدف نبيل", example: "Mrs. Al-Hroub plans to establish her own foundation and use some of her winnings to train other teachers to follow her approach.", exampleAr: "تخطّط السيدة الحروب لتأسيس مؤسستها الخاصة واستخدام جزء من المال الذي ربحته لتدريب معلّمين آخرين على اتّباع أسلوبها." },
        { en: "winnings", ar: "المال الذي رُبح (الجائزة)", pos: "noun", def: "money that you win", defAr: "المال الذي تربحه", example: "Mrs. Al-Hroub plans to establish her own foundation and use some of her winnings to train other teachers to follow her approach.", exampleAr: "تخطّط السيدة الحروب لتأسيس مؤسستها الخاصة واستخدام جزء من المال الذي ربحته لتدريب معلّمين آخرين على اتّباع أسلوبها." },
        { en: "approach", ar: "نهج / أسلوب", pos: "noun", def: "a way of dealing with something", defAr: "طريقة في التعامل مع شيء ما", example: "Mrs. Al-Hroub plans to establish her own foundation and use some of her winnings to train other teachers to follow her approach.", exampleAr: "تخطّط السيدة الحروب لتأسيس مؤسستها الخاصة واستخدام جزء من المال الذي ربحته لتدريب معلّمين آخرين على اتّباع أسلوبها." },
        { en: "prevent", ar: "يمنع", pos: "verb", def: "to stop something from happening or someone from doing something", defAr: "أن توقف حدوث شيء أو تمنع شخصاً من فعل شيء", example: "It is worth mentioning that Mrs. Al-Hroub's dream was to be a doctor but failing to do so did not prevent her from being a special person who could make a difference.", exampleAr: "ومن الجدير بالذكر أن حلم السيدة الحروب كان أن تصبح طبيبة، لكنّ إخفاقها في ذلك لم يمنعها من أن تكون شخصاً مميّزاً استطاع أن يُحدث فرقاً." },
        { en: "make a difference", ar: "يُحدث فرقاً", pos: "phrase", def: "to have a good effect on a situation or on people", defAr: "أن يكون لك أثر جيد في موقف ما أو في الناس", example: "To sum up, by volunteering you can make a huge difference.", exampleAr: "خلاصة القول، بالتطوّع يمكنك أن تُحدث فرقاً كبيراً." },
        { en: "career", ar: "مهنة / مسيرة مهنية", pos: "noun", def: "the job you do for a long part of your life", defAr: "العمل الذي تمارسه جزءاً طويلاً من حياتك", example: "How do you think your career will make a difference?", exampleAr: "كيف تعتقد أن مهنتك ستُحدث فرقاً؟" },
        { en: "volunteering", ar: "التطوّع", pos: "noun", def: "doing work for other people without being paid", defAr: "القيام بعمل من أجل الآخرين دون أجر", example: "The benefits of volunteering can be enormous.", exampleAr: "يمكن أن تكون فوائد التطوّع هائلة." },
        { en: "benefit", ar: "فائدة", pos: "noun", def: "a good or useful result", defAr: "نتيجة جيدة أو مفيدة", example: "The benefits of volunteering can be enormous.", exampleAr: "يمكن أن تكون فوائد التطوّع هائلة." },
        { en: "enormous", ar: "هائل / ضخم", pos: "adjective", def: "very big", defAr: "كبير جداً", example: "The benefits of volunteering can be enormous.", exampleAr: "يمكن أن تكون فوائد التطوّع هائلة." },
        { en: "skill", ar: "مهارة", pos: "noun", def: "the ability to do something well", defAr: "القدرة على فعل شيء بإتقان", example: "Volunteering can help you make friends, learn new skills, advance your career, and even feel happier and healthier.", exampleAr: "يمكن للتطوّع أن يساعدك على تكوين صداقات وتعلّم مهارات جديدة والتقدّم في مسيرتك المهنية، بل وأن تشعر بسعادة وصحة أكبر." },
        { en: "advance", ar: "يُطوّر / يتقدّم في", pos: "verb", def: "to move forward or make progress", defAr: "أن تتقدّم أو تحرز تطوّراً", example: "Volunteering can help you make friends, learn new skills, advance your career, and even feel happier and healthier.", exampleAr: "يمكن للتطوّع أن يساعدك على تكوين صداقات وتعلّم مهارات جديدة والتقدّم في مسيرتك المهنية، بل وأن تشعر بسعادة وصحة أكبر." },
        { en: "fitness", ar: "اللياقة البدنية", pos: "noun", def: "being healthy and strong in your body", defAr: "أن يكون جسمك سليماً وقوياً", example: "Researchers also say that nearly half of volunteers enjoy improved health and fitness, and a quarter lose weight - especially those working with children.", exampleAr: "ويقول الباحثون أيضاً إن نحو نصف المتطوّعين يتمتّعون بصحة ولياقة أفضل، وإن ربعهم يفقدون من أوزانهم – ولا سيّما الذين يعملون مع الأطفال." },
        { en: "stressed", ar: "متوتّر / مضغوط", pos: "adjective", def: "worried and nervous", defAr: "قلق ومتوتّر الأعصاب", example: "Two-thirds feel less stressed.", exampleAr: "ويشعر ثلثاهم بتوتّر أقلّ." },
        { en: "scout", ar: "كشّاف", pos: "noun", def: "a member of a group that teaches young people useful skills and helping others", defAr: "عضو في فرقة تعلّم الشباب مهارات مفيدة ومساعدة الآخرين" },
        { en: "neckerchief", ar: "منديل الرقبة (الشال الكشفي)", pos: "noun", def: "a piece of cloth worn around the neck, part of a scout uniform", defAr: "قطعة قماش تُلبس حول الرقبة، وهي جزء من الزيّ الكشفي" },
      ],
      reading: {
        title: "A Different Class",
        paragraphs: [
          "Hanan Al-Hroub was a poorly paid teacher in the West Bank. Then she won the $1 million Global Teacher Prize. The committee praised Mrs. Al-Hroub’s “play and learn” method, which she still employs.",
          "Besides her clown outfit, Mrs. Al-Hroub uses balloons, hula-hoops, toy cars and puppets to explain her lessons. Her aim is to make the classroom a calm and fun place where children can forget about the struggle of daily life, and open their minds.",
          "“We play first, and when we play we learn,” she said. “The kids don’t even realise they are learning.”",
          "In addition to the toys and balloons, which she pays for with her own money, she uses videos and even PowerPoint in the classroom. For the first month of a new school year, her eight-year-old pupils may not even see an exercise book.",
          "Parents often refuse the focus on play. That soon changes, Mrs. Al-Hroub says, when they realise that her methods improve behaviour – especially in troubled kids – and academic results. She also sees it as her duty to build their characters. “No to violence” is a motto in her classes.",
          "Mrs. Al-Hroub plans to establish her own foundation and use some of her winnings to train other teachers to follow her approach.",
          "It is worth mentioning that Mrs. Al-Hroub's dream was to be a doctor but failing to do so did not prevent her from being a special person who could make a difference.",
        ],
        paragraphsAr: [
          "كانت حنان الحروب معلّمةً ذات أجر زهيد في الضفة الغربية. ثم فازت بجائزة المعلّم العالمية وقيمتها مليون دولار. وقد أثنت اللجنة على طريقة السيدة الحروب «العب وتعلّم»، التي ما زالت تستخدمها.",
          "إلى جانب زيّ المهرّج الذي ترتديه، تستخدم السيدة الحروب البالونات وأطواق الهولا هوب والسيارات الصغيرة (الألعاب) والدمى لشرح دروسها. وهدفها أن تجعل الصف مكاناً هادئاً وممتعاً يستطيع فيه الأطفال أن ينسوا معاناة الحياة اليومية، وأن يفتحوا عقولهم.",
          "قالت: «نحن نلعب أولاً، وعندما نلعب نتعلّم. حتى إن الأطفال لا يدركون أنهم يتعلّمون.»",
          "بالإضافة إلى الألعاب والبالونات التي تدفع ثمنها من مالها الخاص، تستخدم مقاطع الفيديو وحتى برنامج العروض PowerPoint في الصف. وفي الشهر الأول من العام الدراسي الجديد، قد لا يرى تلاميذها ذوو الأعوام الثمانية دفترَ تمارين أصلاً.",
          "غالباً ما يرفض الأهل التركيز على اللعب. لكنّ ذلك يتغيّر سريعاً، كما تقول السيدة الحروب، عندما يدركون أن أساليبها تحسّن السلوك – ولا سيّما لدى الأطفال الذين يعانون من مشكلات – وتحسّن النتائج الدراسية. وهي ترى أيضاً أن من واجبها بناء شخصياتهم. و«لا للعنف» شعارٌ في صفوفها.",
          "تخطّط السيدة الحروب لتأسيس مؤسستها الخاصة واستخدام جزء من المال الذي ربحته في تدريب معلّمين آخرين على اتّباع أسلوبها.",
          "ومن الجدير بالذكر أن حلم السيدة الحروب كان أن تصبح طبيبة، لكنّ إخفاقها في ذلك لم يمنعها من أن تكون شخصاً مميّزاً استطاع أن يُحدث فرقاً.",
        ],
        questions: [
          { q: "What are Mrs. Al-Hroub's teaching tools?", qAr: "ما أدوات التعليم التي تستخدمها السيدة الحروب؟",
            options: ["A clown outfit, balloons, hula-hoops, toy cars, puppets, videos and PowerPoint.", "Only exercise books from the first day of the school year.", "Only a board and a pen.", "Doctors' tools, because her dream was to be a doctor."],
            answer: 0, explainAr: "النص يذكر: clown outfit (زيّ المهرّج)، balloons، hula-hoops، toy cars، puppets، ثم videos و PowerPoint. أمّا دفتر التمارين فقد لا يراه التلاميذ في الشهر الأول أصلاً." },
          { q: "How do parents usually react to Mrs. Al-Hroub's method?", qAr: "كيف يتفاعل الأهل عادةً مع طريقة السيدة الحروب؟",
            options: ["They often refuse the focus on play, but that changes when they see her methods improve behaviour and results.", "They always praise her method from the first day.", "They pay for the toys and balloons.", "They ask her to give their children more exercise books."],
            answer: 0, explainAr: "النص يقول: Parents often refuse the focus on play — يرفض الأهل غالباً التركيز على اللعب، ثم That soon changes عندما يدركون أن أساليبها تحسّن السلوك والنتائج الدراسية." },
          { q: "What are Mrs. Al-Hroub's future plans?", qAr: "ما خطط السيدة الحروب المستقبلية؟",
            options: ["To establish her own foundation and use some of her winnings to train other teachers.", "To stop teaching and become a doctor.", "To buy a new school in the West Bank.", "To win another prize next year."],
            answer: 0, explainAr: "الفقرة السادسة: Mrs. Al-Hroub plans to establish her own foundation … to train other teachers to follow her approach — تخطّط لتأسيس مؤسستها وتدريب معلّمين آخرين." },
          { q: "True or False? “Mrs. Al-Hroub has always wanted to become a teacher.”", qAr: "صح أم خطأ؟ «لطالما أرادت السيدة الحروب أن تصبح معلّمة.»",
            options: ["False — her dream was to be a doctor.", "True — she has always wanted to be a teacher.", "False — her dream was to be a clown.", "False — her dream was to win a prize."],
            answer: 0, explainAr: "العبارة خاطئة؛ الفقرة الأخيرة تقول: Mrs. Al-Hroub's dream was to be a doctor — كان حلمها أن تصبح طبيبة." },
          { q: "True or False? “She teaches in a secondary school.”", qAr: "صح أم خطأ؟ «هي تدرّس في مدرسة ثانوية.»",
            options: ["True — her pupils are in the secondary school.", "False — her pupils are eight years old.", "False — she teaches at a university.", "True — she teaches the 12th grade."],
            answer: 1, explainAr: "العبارة خاطئة؛ النص يقول: her eight-year-old pupils — تلاميذها في الثامنة من العمر، أي أنهم صغار وليسوا في المرحلة الثانوية." },
          { q: "True or False? “Mrs. Al-Hroub's school provides her with all the materials.”", qAr: "صح أم خطأ؟ «مدرسة السيدة الحروب تزوّدها بكل المواد.»",
            options: ["True — the school buys all her toys.", "False — the committee pays for her toys.", "False — she pays for the toys and balloons with her own money.", "True — the parents buy everything for her."],
            answer: 2, explainAr: "العبارة خاطئة؛ النص يقول: the toys and balloons, which she pays for with her own money — تدفع ثمن الألعاب والبالونات من مالها الخاص." },
          { q: "True or False? “She successfully deals with troubled kids.”", qAr: "صح أم خطأ؟ «هي تتعامل بنجاح مع الأطفال المضطربين.»",
            options: ["False — she refuses to teach troubled kids.", "True — her methods improve behaviour, especially in troubled kids.", "False — troubled kids don't like her classes.", "True — she sends troubled kids to a doctor."],
            answer: 1, explainAr: "العبارة صحيحة؛ النص يقول: her methods improve behaviour – especially in troubled kids — أساليبها تحسّن السلوك ولا سيّما لدى الأطفال المضطربين." },
          { q: "What is the motto in Mrs. Al-Hroub's classes?", qAr: "ما الشعار في صفوف السيدة الحروب؟",
            options: ["“Play and learn” only on Fridays.", "“No to violence”.", "“No exercise books”.", "“Learn first, then play”."],
            answer: 1, explainAr: "النص يقول: “No to violence” is a motto in her classes — «لا للعنف» شعار في صفوفها. انتبه: motto = شعار." },
        ],
        trueFalse: [
          { statement: "Mrs. Al-Hroub has always wanted to become a teacher.", answer: false },
          { statement: "She teaches in a secondary school.", answer: false },
          { statement: "Mrs. Al-Hroub's school provides her with all the materials.", answer: false },
          { statement: "She successfully deals with troubled-kids.", answer: true },
          { statement: "Hanan Al-Hroub won the $1 million Global Teacher Prize.", answer: true },
        ],
      },
      vocabFocus: {
        name: "Using key words in different contexts", nameAr: "استخدام الكلمات المفتاحية في سياقات مختلفة",
        ruleEn: [
          "Complete the following statements with words from the text.",
          "committee: a group of people chosen to make decisions",
          "praise: to express approval, love, or admiration for something",
          "employ: to make use of something",
          "outfit: a set of clothes that you wear together",
          "struggle: something that is difficult for you to do or achieve",
          "violence: the use of physical force to harm someone",
        ],
        ruleAr: [
          "الكلمة الواحدة تُستخدم في سياقات (مواقف) مختلفة: تعلّمنا praise في النص عن لجنة تمدح معلّمة، ونستخدمها أيضاً عن معلّم يمدح طلابه.",
          "لتختار الكلمة الصحيحة انظر إلى موقعها في الجملة: بعد to نضع فعلاً (to praise / to employ)، وبعد a / his / of نضع اسماً (an outfit / his struggle / an act of violence).",
          "committee = لجنة، praise = يمدح، employ = يستخدم، outfit = زيّ، struggle = معاناة / كفاح، violence = عنف.",
          "احفظ معنى كل كلمة من صندوق Key Words، ثم فكّر: أيّ معنى يناسب الجملة؟",
        ],
        examples: [
          "The committee praised Mrs. Al-Hroub’s “play and learn” method, which she still employs.",
          "Besides her clown outfit, Mrs. Al-Hroub uses balloons, hula-hoops, toy cars and puppets to explain her lessons.",
          "Her aim is to make the classroom a calm and fun place where children can forget about the struggle of daily life, and open their minds.",
          "“No to violence” is a motto in her classes.",
        ],
        exercises: [
          // the book's exercise (p. 6)
          { type: "fill", prompt: "The teacher began to ___ the students for their excellent work.", promptAr: "بدأ المعلّم ___ الطلاب على عملهم الممتاز.", promptArFull: "بدأ المعلّم يمدح الطلاب على عملهم الممتاز.", options: ["praise", "employ", "violence", "struggle"], answer: 0, explainAr: "بعد to نحتاج فعلاً، والمعنى: المعلّم يمدح الطلاب لأن عملهم ممتاز. praise = يعبّر عن الإعجاب والاستحسان." },
          { type: "fill", prompt: "An act of ___ caused the window to be broken.", promptAr: "عملٌ من أعمال ___ تسبّب في كسر النافذة.", promptArFull: "عملٌ من أعمال العنف تسبّب في كسر النافذة.", options: ["violence", "committee", "outfit", "praise"], answer: 0, explainAr: "بعد act of نحتاج اسماً، وكسر النافذة يكون باستخدام القوة الجسدية للإيذاء = violence (عنف)." },
          { type: "fill", prompt: "The artist had to ___ a hammer to open his paint cans.", promptAr: "اضطرّ الفنان أن ___ مطرقةً ليفتح علب الطلاء.", promptArFull: "اضطرّ الفنان أن يستخدم مطرقةً ليفتح علب الطلاء.", options: ["employ", "praise", "struggle", "violence"], answer: 0, explainAr: "بعد had to نحتاج فعلاً بمعنى «يستخدم»: employ = to make use of something." },
          { type: "fill", prompt: "She was wearing a splendid ___.", promptAr: "كانت ترتدي ___ رائعاً.", promptArFull: "كانت ترتدي زيّاً رائعاً.", options: ["outfit", "struggle", "committee", "violence"], answer: 0, explainAr: "الفعل wearing (ترتدي) يدلّ على الملابس: outfit = a set of clothes that you wear together." },
          { type: "fill", prompt: "His ___ against cancer lasted for two years.", promptAr: "استمرّ ___ ضدّ السرطان سنتين.", promptArFull: "استمرّ كفاحه ضدّ السرطان سنتين.", options: ["struggle", "outfit", "violence", "committee"], answer: 0, explainAr: "مواجهة مرض صعب = كفاح ومعاناة: struggle = something that is difficult for you to do or achieve. وتأتي غالباً مع against (ضدّ)." },
          // the key words: meanings
          { type: "mcq", prompt: "“committee” means:", promptAr: "معنى «committee» هو:", options: ["a group of people chosen to make decisions", "a set of clothes that you wear together", "the use of physical force to harm someone", "to make use of something"], answer: 0, explainAr: "committee = لجنة، أي مجموعة من الناس يُختارون لاتخاذ القرارات، مثل اللجنة التي منحت الجائزة للسيدة الحروب." },
          { type: "mcq", prompt: "“praise” means:", promptAr: "معنى «praise» هو:", options: ["to make use of something", "to express approval, love, or admiration for something", "something that is difficult for you to do", "to say no to something"], answer: 1, explainAr: "praise = يمدح / يُثني: أن تعبّر عن الاستحسان أو الحبّ أو الإعجاب بشيء." },
          { type: "mcq", prompt: "“employ” means:", promptAr: "معنى «employ» هو:", options: ["to express admiration for something", "to make use of something", "to harm someone", "to wear clothes"], answer: 1, explainAr: "employ = يستخدم: to make use of something. في النص: her method, which she still employs = طريقتها التي ما زالت تستخدمها." },
          { type: "mcq", prompt: "“outfit” means:", promptAr: "معنى «outfit» هو:", options: ["a group of people chosen to make decisions", "a set of clothes that you wear together", "a short sentence that a group believes", "a toy that you move with your hand"], answer: 1, explainAr: "outfit = زيّ / طقم ملابس، مثل clown outfit = زيّ المهرّج." },
          { type: "mcq", prompt: "“struggle” means:", promptAr: "معنى «struggle» هو:", options: ["the use of physical force to harm someone", "something that is difficult for you to do or achieve", "a set of clothes", "a good or useful result"], answer: 1, explainAr: "struggle = معاناة / كفاح: شيء يصعب عليك فعله أو تحقيقه، مثل the struggle of daily life = معاناة الحياة اليومية." },
          { type: "mcq", prompt: "“violence” means:", promptAr: "معنى «violence» هو:", options: ["the use of physical force to harm someone", "to express approval for something", "a group of people", "something you feel you must do"], answer: 0, explainAr: "violence = عنف: استخدام القوة الجسدية لإيذاء شخص ما. وشعار صفوفها: No to violence = لا للعنف." },
          // the key words back in the text
          { type: "fill", prompt: "The ___ praised Mrs. Al-Hroub’s “play and learn” method.", promptAr: "أثنت ___ على طريقة السيدة الحروب «العب وتعلّم».", promptArFull: "أثنت اللجنة على طريقة السيدة الحروب «العب وتعلّم».", options: ["committee", "outfit", "motto", "struggle"], answer: 0, explainAr: "الذي يمدح الطريقة ويمنح الجائزة هو مجموعة من الناس تتخذ القرار = committee (لجنة)." },
          { type: "fill", prompt: "The committee ___ Mrs. Al-Hroub’s “play and learn” method.", promptAr: "___ اللجنة على طريقة السيدة الحروب «العب وتعلّم».", promptArFull: "أثنت اللجنة على طريقة السيدة الحروب «العب وتعلّم».", options: ["praised", "employed", "refused", "prevented"], answer: 0, explainAr: "اللجنة أُعجبت بالطريقة فمنحتها الجائزة، فالمعنى «مدحت / أثنت» = praised (الماضي من praise)." },
          { type: "fill", prompt: "Her “play and learn” method, which she still ___.", promptAr: "طريقتها «العب وتعلّم» التي ما زالت ___ها.", promptArFull: "طريقتها «العب وتعلّم» التي ما زالت تستخدمها.", options: ["employs", "praises", "refuses", "struggles"], answer: 0, explainAr: "employ = يستخدم، ونضيف s لأن الفاعل she مفرد غائب في المضارع البسيط: she still employs." },
          { type: "fill", prompt: "Besides her clown ___, Mrs. Al-Hroub uses balloons.", promptAr: "إلى جانب ___ المهرّج، تستخدم السيدة الحروب البالونات.", promptArFull: "إلى جانب زيّ المهرّج، تستخدم السيدة الحروب البالونات.", options: ["outfit", "committee", "violence", "duty"], answer: 0, explainAr: "clown outfit = زيّ المهرّج؛ outfit مجموعة ملابس تُلبس معاً." },
          { type: "fill", prompt: "Children can forget about the ___ of daily life.", promptAr: "يستطيع الأطفال أن ينسوا ___ الحياة اليومية.", promptArFull: "يستطيع الأطفال أن ينسوا معاناة الحياة اليومية.", options: ["struggle", "outfit", "praise", "committee"], answer: 0, explainAr: "الحياة اليومية فيها صعوبات، و struggle = شيء يصعب فعله أو تحقيقه (معاناة)." },
          { type: "fill", prompt: "“No to ___” is a motto in her classes.", promptAr: "«لا لـ___» شعارٌ في صفوفها.", promptArFull: "«لا للعنف» شعارٌ في صفوفها.", options: ["violence", "praise", "outfit", "committee"], answer: 0, explainAr: "المعلّمة تبني شخصيات الأطفال وترفض الإيذاء، فشعارها «لا للعنف» = No to violence." },
          { type: "fill", prompt: "Mrs. Al-Hroub plans to ___ her own foundation.", promptAr: "تخطّط السيدة الحروب لـ___ مؤسستها الخاصة.", promptArFull: "تخطّط السيدة الحروب لتأسيس مؤسستها الخاصة.", options: ["establish", "praise", "prevent", "refuse"], answer: 0, explainAr: "establish = يؤسّس؛ نقول establish a foundation = يؤسّس مؤسسة." },
          { type: "fill", prompt: "She also sees it as her ___ to build their characters.", promptAr: "وهي ترى أيضاً أن من ___ها بناء شخصياتهم.", promptArFull: "وهي ترى أيضاً أن من واجبها بناء شخصياتهم.", options: ["duty", "motto", "outfit", "prize"], answer: 0, explainAr: "duty = واجب: شيء تشعر أن عليك فعله. بناء شخصيات الأطفال واجب المعلّمة." },
          { type: "fill", prompt: "Failing to be a doctor did not ___ her from being a special person.", promptAr: "إخفاقها في أن تصبح طبيبة لم ___ها من أن تكون شخصاً مميّزاً.", promptArFull: "إخفاقها في أن تصبح طبيبة لم يمنعها من أن تكون شخصاً مميّزاً.", options: ["prevent", "employ", "praise", "establish"], answer: 0, explainAr: "prevent somebody from doing something = يمنع شخصاً من فعل شيء. لاحظ حرف الجر from بعدها." },
          { type: "truefalse", prompt: "In “the struggle of daily life”, struggle means “something that is difficult for you to do or achieve”.", promptAr: "في عبارة «the struggle of daily life» تعني struggle «شيئاً يصعب عليك فعله أو تحقيقه».", answer: true, explainAr: "صحيح؛ هذا هو تعريف struggle في صندوق Key Words: معاناة / كفاح." },
          { type: "truefalse", prompt: "“outfit” means “the use of physical force to harm someone”.", promptAr: "كلمة «outfit» تعني «استخدام القوة الجسدية لإيذاء شخص ما».", answer: false, explainAr: "خطأ؛ هذا تعريف violence (عنف). أمّا outfit فتعني طقم ملابس يُلبس معاً." },
        ],
      },
      grammar: {
        name: "Revision of present simple and present progressive", nameAr: "مراجعة المضارع البسيط والمضارع المستمر",
        ruleEn: [
          "Present simple: I / you / we / they + verb; he / she / it + verb + s (use → uses, pay → pays, teach → teaches).",
          "Negative and questions in the present simple: don't / doesn't + verb; Do / Does + subject + verb? (The kids don't even realise they are learning.)",
          "Use the present simple for habits, routines and facts, often with always, usually, often, every day. (Parents often refuse the focus on play.)",
          "Present progressive: am / is / are + verb-ing. (They are building a new bridge nowadays.)",
          "Use the present progressive for actions happening now or around now, often with now, right now, at the moment, nowadays, Look! Listen! (She is talking on the phone right now.)",
          "State verbs such as know, like, want, realise, understand are not usually used in the progressive.",
        ],
        ruleAr: [
          "المضارع البسيط: الفعل كما هو مع I / you / we / they، ونضيف s أو es مع he / she / it: she uses, she pays, she teaches.",
          "النفي: don't / doesn't + الفعل بلا s، والسؤال: Do / Does + الفاعل + الفعل؟ مثال: The kids don't even realise.",
          "نستعمل المضارع البسيط للعادات والأمور المتكرّرة والحقائق، ومن علاماته: always, usually, often, every day.",
          "المضارع المستمر: am / is / are + الفعل مع ing، مثل: They are building a new bridge nowadays.",
          "نستعمله لحدث يجري الآن أو في هذه الفترة، ومن علاماته: now, right now, at the moment, nowadays, Look!, Listen!",
          "أفعال الحالة (الشعور والمعرفة) مثل know, like, want, realise لا تأتي عادةً بصيغة ing، فنقول: I know ولا نقول I am knowing.",
        ],
        examples: [
          "Mrs. Al-Hroub uses balloons, hula-hoops, toy cars and puppets to explain her lessons.",
          "Parents often refuse the focus on play.",
          "We play first, and when we play we learn.",
          "The kids don’t even realise they are learning.",
          "They are building a new bridge nowadays.",
          "She is talking on the phone right now.",
          "I am studying in the library at the moment.",
        ],
        exercises: [
          // A. present simple from the text (p. 6)
          { type: "fill", prompt: "Mrs. Al-Hroub ___ balloons, hula-hoops, toy cars and puppets.", promptAr: "السيدة الحروب ___ البالونات وأطواق الهولا هوب والسيارات الصغيرة والدمى.", promptArFull: "السيدة الحروب تستخدم البالونات وأطواق الهولا هوب والسيارات الصغيرة والدمى.", options: ["uses", "use", "is use", "using"], answer: 0, explainAr: "هذه عادتها في التعليم فنستعمل المضارع البسيط، والفاعل Mrs. Al-Hroub مفرد غائب (she) فنضيف s: uses." },
          { type: "fill", prompt: "Parents often ___ the focus on play.", promptAr: "غالباً ما ___ الأهل التركيز على اللعب.", promptArFull: "غالباً ما يرفض الأهل التركيز على اللعب.", options: ["refuse", "refuses", "are refuse", "refusing"], answer: 0, explainAr: "often علامة المضارع البسيط، والفاعل Parents جمع (they) فلا نضيف s: refuse." },
          { type: "fill", prompt: "Her methods ___ behaviour.", promptAr: "أساليبها ___ السلوك.", promptArFull: "أساليبها تحسّن السلوك.", options: ["improve", "improves", "improving", "is improving"], answer: 0, explainAr: "حقيقة عامة فنستعمل المضارع البسيط، والفاعل Her methods جمع فيبقى الفعل بلا s: improve." },
          { type: "fill", prompt: "We ___ first and when we play we learn.", promptAr: "نحن ___ أولاً، وعندما نلعب نتعلّم.", promptArFull: "نحن نلعب أولاً، وعندما نلعب نتعلّم.", options: ["play", "plays", "are play", "played"], answer: 0, explainAr: "هذه طريقتهم الدائمة (عادة) فنستعمل المضارع البسيط، ومع We لا نضيف s: play." },
          { type: "fill", prompt: "The kids ___ even ___ they are learning.", promptAr: "الأطفال ___ حتى ___ أنهم يتعلّمون.", promptArFull: "الأطفال لا يدركون حتى أنهم يتعلّمون.", options: ["don't … realise", "doesn't … realise", "don't … realises", "aren't … realise"], answer: 0, explainAr: "نفي المضارع البسيط مع الجمع (The kids = they) يكون don't + الفعل بلا s: don't realise. و realise فعل حالة فلا يأتي بصيغة ing." },
          // B. present progressive (p. 6)
          { type: "fill", prompt: "She ___ (talk) on the phone right now.", promptAr: "هي ___ على الهاتف الآن.", promptArFull: "هي تتحدّث على الهاتف الآن.", options: ["is talking", "talks", "are talking", "talking"], answer: 0, explainAr: "right now علامة المضارع المستمر: is + talking لأن الفاعل She مفرد." },
          { type: "fill", prompt: "I ___ (study) in the library at the moment.", promptAr: "أنا ___ في المكتبة في هذه اللحظة.", promptArFull: "أنا أدرس في المكتبة في هذه اللحظة.", options: ["am studying", "is studying", "study", "are studying"], answer: 0, explainAr: "at the moment علامة المضارع المستمر، ومع I نستعمل am: am studying." },
          { type: "fill", prompt: "It’s good news to hear that John’s health ___ (improve).", promptAr: "من الأخبار الجيدة أن نسمع أن صحة جون ___.", promptArFull: "من الأخبار الجيدة أن نسمع أن صحة جون تتحسّن.", options: ["is improving", "are improving", "improve", "improving"], answer: 0, explainAr: "التحسّن يحدث في هذه الفترة (تغيّر مستمر) فنستعمل المضارع المستمر. John’s health مفرد فنقول is improving. وتحذف e من improve قبل ing." },
          { type: "fill", prompt: "Where are the children? There they are. They ___ (play) tennis.", promptAr: "أين الأطفال؟ ها هم. إنهم ___ التنس.", promptArFull: "أين الأطفال؟ ها هم. إنهم يلعبون التنس.", options: ["are playing", "is playing", "play", "plays"], answer: 0, explainAr: "نراهم الآن (There they are) فالحدث يجري الآن: They + are playing." },
          // more practice in the unit's world
          { type: "fill", prompt: "Mrs. Al-Hroub ___ in the West Bank.", promptAr: "السيدة الحروب ___ في الضفة الغربية.", promptArFull: "السيدة الحروب تُدرّس في الضفة الغربية.", options: ["teaches", "teach", "teachs", "teaching"], answer: 0, explainAr: "عملها الدائم فنستعمل المضارع البسيط مع she. الفعل ينتهي بـ ch فنضيف es: teaches." },
          { type: "fill", prompt: "She ___ for the toys with her own money.", promptAr: "هي ___ ثمن الألعاب من مالها الخاص.", promptArFull: "هي تدفع ثمن الألعاب من مالها الخاص.", options: ["pays", "pay", "paies", "paying"], answer: 0, explainAr: "عادة متكرّرة ← مضارع بسيط، ومع she نضيف s. الفعل pay ينتهي بحرف علّة + y فنضيف s فقط: pays." },
          { type: "fill", prompt: "Her pupils ___ an exercise book in the first month.", promptAr: "تلاميذها ___ دفتر تمارين في الشهر الأول.", promptArFull: "تلاميذها لا يرون دفتر تمارين في الشهر الأول.", options: ["don't see", "doesn't see", "aren't see", "not see"], answer: 0, explainAr: "نفي المضارع البسيط مع الجمع (Her pupils = they): don't + الفعل الأساسي: don't see." },
          { type: "fill", prompt: "___ Mrs. Al-Hroub use videos in the classroom? — Yes, she does.", promptAr: "هل ___ السيدة الحروب مقاطع الفيديو في الصف؟ — نعم.", promptArFull: "هل تستخدم السيدة الحروب مقاطع الفيديو في الصف؟ — نعم.", options: ["Does", "Do", "Is", "Are"], answer: 0, explainAr: "السؤال في المضارع البسيط مع مفرد غائب يبدأ بـ Does، ويبقى الفعل بعده بلا s: Does … use? والجواب Yes, she does." },
          { type: "fill", prompt: "Look! The children ___ with balloons now.", promptAr: "انظر! الأطفال ___ بالبالونات الآن.", promptArFull: "انظر! الأطفال يلعبون بالبالونات الآن.", options: ["are playing", "play", "is playing", "plays"], answer: 0, explainAr: "Look! و now علامتا المضارع المستمر، والفاعل جمع: are playing." },
          { type: "fill", prompt: "At the moment, Mrs. Al-Hroub ___ her clown outfit.", promptAr: "في هذه اللحظة، السيدة الحروب ___ زيّ المهرّج.", promptArFull: "في هذه اللحظة، السيدة الحروب ترتدي زيّ المهرّج.", options: ["is wearing", "wears", "are wearing", "wear"], answer: 0, explainAr: "At the moment علامة المضارع المستمر، والفاعل مفرد: is wearing." },
          { type: "fill", prompt: "Parents ___ her method at first.", promptAr: "الأهل ___ طريقتها في البداية.", promptArFull: "الأهل لا يحبّون طريقتها في البداية.", options: ["don't like", "doesn't like", "aren't liking", "not like"], answer: 0, explainAr: "like فعل حالة (شعور) فلا يأتي بصيغة ing، ونفيه مع الجمع don't like." },
          { type: "fill", prompt: "Nowadays, Mrs. Al-Hroub ___ other teachers to follow her approach.", promptAr: "هذه الأيام، السيدة الحروب ___ معلّمين آخرين على اتّباع أسلوبها.", promptArFull: "هذه الأيام، السيدة الحروب تدرّب معلّمين آخرين على اتّباع أسلوبها.", options: ["is training", "are training", "train", "training"], answer: 0, explainAr: "Nowadays علامة المضارع المستمر (حدث في هذه الفترة)، والفاعل مفرد: is training. انتبه: training وحدها بدون is خطأ." },
          { type: "fill", prompt: "Volunteering ___ you make friends.", promptAr: "التطوّع ___ك على تكوين صداقات.", promptArFull: "التطوّع يساعدك على تكوين صداقات.", options: ["helps", "help", "helping", "are helping"], answer: 0, explainAr: "حقيقة عامة ← مضارع بسيط، و Volunteering اسم مفرد (it) فنضيف s: helps." },
          { type: "fill", prompt: "My brother ___ as a volunteer this month.", promptAr: "أخي ___ متطوّعاً هذا الشهر.", promptArFull: "أخي يعمل متطوّعاً هذا الشهر.", options: ["is working", "are working", "work", "working"], answer: 0, explainAr: "this month يدلّ على حدث مؤقت في هذه الفترة ← مضارع مستمر: is working." },
          { type: "fill", prompt: "Scouts ___ a uniform in their meetings.", promptAr: "الكشّافة ___ زيّاً موحّداً في اجتماعاتهم.", promptArFull: "الكشّافة يرتدون زيّاً موحّداً في اجتماعاتهم.", options: ["wear", "wears", "are wear", "wearing"], answer: 0, explainAr: "أمر معتاد يتكرّر في كل اجتماع ← مضارع بسيط، والفاعل Scouts جمع فلا نضيف s: wear." },
          { type: "fill", prompt: "Mrs. Al-Hroub usually ___ puppets, but today she ___ videos.", promptAr: "السيدة الحروب عادةً ___ الدمى، لكنها اليوم ___ مقاطع الفيديو.", promptArFull: "السيدة الحروب عادةً تستخدم الدمى، لكنها اليوم تستخدم مقاطع الفيديو.", options: ["uses … is using", "is using … uses", "use … is using", "uses … uses"], answer: 0, explainAr: "usually علامة المضارع البسيط (uses)، و today تدلّ على ما يحدث الآن بشكل مؤقت ← مضارع مستمر (is using)." },
          { type: "fill", prompt: "Look! Mrs. Al-Hroub ___ her clown outfit, and the kids ___.", promptAr: "انظر! السيدة الحروب ___ زيّ المهرّج، والأطفال ___.", promptArFull: "انظر! السيدة الحروب ترتدي زيّ المهرّج، والأطفال يلعبون.", options: ["is wearing … are playing", "wears … play", "is wearing … is playing", "wear … are playing"], answer: 0, explainAr: "Look! تعني أن الحدثين يجريان الآن ← مضارع مستمر: مع المفرد is wearing ومع الجمع (the kids) are playing." },
          { type: "mcq", prompt: "Which sentence is in the present progressive?", promptAr: "أيّ جملة في زمن المضارع المستمر؟", options: ["They are building a new bridge nowadays.", "Parents often refuse the focus on play.", "We play first.", "Her methods improve behaviour."], answer: 0, explainAr: "المضارع المستمر = are + building (فعل مع ing)، والكلمة nowadays من علاماته. الجمل الأخرى في المضارع البسيط." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["She is knowing the answer.", "She knows the answer.", "She know the answer.", "She knowing the answer."], answer: 1, explainAr: "know فعل حالة (معرفة) فلا يأتي بصيغة ing، ومع she نضيف s: She knows the answer." },
          { type: "mcq", prompt: "Which time expression goes with the present simple?", promptAr: "أيّ تعبير زمني يأتي مع المضارع البسيط؟", options: ["usually", "now", "at the moment", "right now"], answer: 0, explainAr: "usually (عادةً) تدلّ على العادة ← مضارع بسيط. أمّا now و at the moment و right now فهي علامات المضارع المستمر." },
          { type: "mcq", prompt: "Which time expression goes with the present progressive?", promptAr: "أيّ تعبير زمني يأتي مع المضارع المستمر؟", options: ["often", "every day", "at the moment", "always"], answer: 2, explainAr: "at the moment (في هذه اللحظة) علامة المضارع المستمر. أمّا often و every day و always فهي علامات العادة (المضارع البسيط)." },
          { type: "mcq", prompt: "The -ing form of “improve” is:", promptAr: "صيغة ing من الفعل «improve» هي:", options: ["improveing", "improving", "improvving", "improvinng"], answer: 1, explainAr: "الفعل الذي ينتهي بـ e صامتة نحذف منه e ثم نضيف ing: improve ← improving." },
          { type: "mcq", prompt: "The pupils are ___ on the floor. (sit)", promptAr: "التلاميذ ___ على الأرض. (sit)", options: ["siting", "sitting", "sitng", "sits"], answer: 1, explainAr: "الفعل sit مقطع واحد ينتهي بحرف ساكن قبله حرف علّة قصير، فنضاعف الحرف الأخير: sit ← sitting." },
          { type: "truefalse", prompt: "“She teach in the West Bank.” is correct.", promptAr: "الجملة «She teach in the West Bank.» صحيحة.", answer: false, explainAr: "خطأ؛ مع she في المضارع البسيط نضيف es: She teaches in the West Bank." },
          { type: "truefalse", prompt: "“They are building a new bridge nowadays.” is in the present progressive.", promptAr: "الجملة «They are building a new bridge nowadays.» في زمن المضارع المستمر.", answer: true, explainAr: "صحيح؛ are + building = am/is/are + فعل مع ing، و nowadays من علامات هذا الزمن." },
          { type: "truefalse", prompt: "“The kids aren't realising they are learning.” is correct.", promptAr: "الجملة «The kids aren't realising they are learning.» صحيحة.", answer: false, explainAr: "خطأ؛ realise فعل حالة لا يأتي بصيغة ing. الصحيح كما في النص: The kids don’t even realise they are learning." },
          { type: "truefalse", prompt: "“Parents often refuse the focus on play.” is in the present simple.", promptAr: "الجملة «Parents often refuse the focus on play.» في زمن المضارع البسيط.", answer: true, explainAr: "صحيح؛ often علامة العادة، والفعل refuse في المضارع البسيط بلا s لأن الفاعل جمع." },
          { type: "build", prompt: "رتّب: السيدة الحروب تستخدم البالونات والدمى لشرح دروسها.", answer: "Mrs. Al-Hroub uses balloons and puppets to explain her lessons." },
          { type: "build", prompt: "رتّب: هي تتحدّث على الهاتف الآن.", answer: "She is talking on the phone right now." },
          { type: "build", prompt: "رتّب: غالباً ما يرفض الأهل التركيز على اللعب.", answer: "Parents often refuse the focus on play." },
          { type: "build", prompt: "رتّب: إنهم يبنون جسراً جديداً هذه الأيام.", answer: "They are building a new bridge nowadays." },
        ],
      },
      pronunciation: {
        title: "Short and long /a/: /æ/ and /a:/",
        ruleAr: "الحرف a له صوتان: صوت قصير /æ/ كما في cab و map (فتحة قصيرة مائلة قليلاً نحو الكسر)، وصوت طويل /a:/ كما في car و father (ألف ممدودة مفتوحة من الحلق). غالباً يكون الصوت طويلاً عندما يأتي بعد a حرف r (car, part, art) أو lm (palm, calm).",
        groups: [
          { label: "/æ/ — cab", words: ["cab", "dad", "bag", "van", "mat", "hat", "map", "sad", "ant", "flag", "glad"] },
          { label: "/a:/ — car", words: ["jar", "father", "car", "class", "arch", "part", "art", "palm", "calm"] },
        ],
      },
      listening: {
        taskAr: "استمع إلى آدم يتحدّث عن تجربته مع فرقة كشّافة. تعرّف أولاً على أجزاء الزيّ الكشفي في الصورة: Headgear (غطاء الرأس)، Neckerchief (منديل الرقبة)، Shirt (القميص)، Web Belt (الحزام)، Shoulder Loops (أشرطة الكتف)، Badge of Rank (شارة الرتبة)، Trousers or shorts (البنطال أو الشورت). ثم A: اختر الإجابة الصحيحة، و B: قرّر إن كانت الجمل صحيحة أو خاطئة. (إجابات هذه الأسئلة في التسجيل الصوتي، وهو غير مطبوع في الكتاب.)",
        items: [
          "Adam is a member in ... scout group. (a. Sanad b. Watad c. Sa’ed (help))",
          "He joined the group when he was ... (a. 10 b. 11 c. 12)",
          "The neckerchief is ... (a. blue b. navy-blue c. yellow)",
          "Adam and his group members usually meet on ... (a. Fridays b. Saturdays c. Sundays)",
          "Members in the scout group have to wear the uniform in all the meetings.",
          "Nowadays they are learning sign language.",
          "Some of their activities are about child protection.",
          "They helped old people last week.",
        ],
      },
      writing: {
        taskAr: "رتّب الأجزاء الثلاثة لتكوّن فقرة جيدة التنظيم عن التطوّع: ابدأ بالجملة الرئيسية التي تذكر الفكرة العامة (The benefits of volunteering can be enormous.)، ثم الجمل الداعمة التي تعطي التفاصيل والأرقام (Volunteering can help you…)، ثم الخاتمة التي تبدأ بـ To sum up (خلاصة القول). اكتب الفقرة كاملة في مكانها.",
        model: [
          "The benefits of volunteering can be enormous.",
          "Volunteering can help you make friends, learn new skills, advance your career, and even feel happier and healthier. Researchers also say that nearly half of volunteers enjoy improved health and fitness, and a quarter lose weight - especially those working with children. Two-thirds feel less stressed. So, it seems that volunteering may improve your life.",
          "To sum up, by volunteering you can make a huge difference.",
        ],
        linkers: ["Besides", "In addition to", "also", "especially", "So,", "To sum up,"],
      },
      sentences: [
        "Hanan Al-Hroub was a poorly paid teacher in the West Bank.",
        "Mrs. Al-Hroub uses balloons, hula-hoops, toy cars and puppets to explain her lessons.",
        "We play first, and when we play we learn.",
        "The kids don’t even realise they are learning.",
        "Parents often refuse the focus on play.",
        "She also sees it as her duty to build their characters.",
        "She successfully deals with troubled kids.",
        "They are building a new bridge nowadays.",
        "The benefits of volunteering can be enormous.",
        "To sum up, by volunteering you can make a huge difference.",
        "What would you like to be in the future?",
        "How do you think your career will make a difference?",
        "Name other careers that can positively change the world.",
      ],
    },

    // ===================== UNIT 2 — Creativity & Initiatives (pages 9–12) =====================
    {
      id: "u2", number: 2, module: 1,
      title: "Creativity & Initiatives", titleAr: "الإبداع والمبادرات", pages: "9–12", emoji: "💡",
      planAr: "المحادثة عن مساعدة الناس (Helping people)، قراءة نص عن «مبادرة ضوء» (Light Initiative) التي تسجّل الكتب صوتياً لذوي الإعاقة البصرية، مفردات: استخدام تعابير معيّنة في سياقات مختلفة (for the benefit of, meet the needs, have access to)، القواعد: مراجعة المضارع التام (Present Perfect)، الاستماع إلى ثلاثة أشخاص (شذا ودانيال وأحمد) يتحدّثون عن مبادراتهم الشخصية، والكتابة: فقرة تشرح خطوات مساعدة صبي من ذوي الإعاقة.",
      vocab: [
        { en: "initiative", ar: "مبادرة", pos: "noun", def: "a new plan for dealing with a particular problem", defAr: "خطة جديدة للتعامل مع مشكلة معيّنة", example: "Light Initiative’s new project is turning the Syrian curriculum into Braille.", exampleAr: "مشروع مبادرة ضوء الجديد هو تحويل المنهاج السوري إلى طريقة برايل." },
        { en: "visually impaired", ar: "ذو إعاقة بصرية / ضعيف البصر", pos: "adjective", def: "people with sight problems", defAr: "أشخاص لديهم مشكلات في البصر", example: "They voluntarily record school and college books for the benefit of the visually impaired people.", exampleAr: "يسجّلون طوعاً كتب المدارس والجامعات لصالح الأشخاص ذوي الإعاقة البصرية." },
        { en: "reference", ar: "مرجع", pos: "noun", def: "source of information like books or articles", defAr: "مصدر للمعلومات مثل الكتب أو المقالات", example: "They started recording the books of the 9th and the 12th grades; they also record university books and references.", exampleAr: "بدأوا بتسجيل كتب الصفّين التاسع والثاني عشر، ويسجّلون أيضاً الكتب الجامعية والمراجع." },
        { en: "provide", ar: "يزوّد / يقدّم", pos: "verb", def: "to give somebody something or to supply", defAr: "أن تعطي شخصاً شيئاً أو تزوّده به", example: "Usually, the visually impaired person who has the desire to study a curriculum or a reference, contacts the initiative administration and provides them with the books needed.", exampleAr: "عادةً، يتواصل الشخص ذو الإعاقة البصرية الذي يرغب في دراسة منهاج أو مرجع مع إدارة المبادرة ويزوّدهم بالكتب المطلوبة." },
        { en: "curriculum", ar: "منهاج", pos: "noun", def: "the subjects that are taught by a school, college ...etc./ syllabus", defAr: "المواد التي تُدرَّس في مدرسة أو كلية... إلخ / المقرّر الدراسي", example: "Light Initiative’s new project is turning the Syrian curriculum into Braille.", exampleAr: "مشروع مبادرة ضوء الجديد هو تحويل المنهاج السوري إلى طريقة برايل." },
        { en: "announce", ar: "يُعلن", pos: "verb", def: "to tell people something officially", defAr: "أن تخبر الناس بشيء بشكل رسمي", example: "On the Facebook page they announce that they finished this book or this curriculum, and they use the YouTube channel to publish the recordings.", exampleAr: "على صفحة فيسبوك يعلنون أنهم أنهوا هذا الكتاب أو هذا المنهاج، ويستخدمون قناة يوتيوب لنشر التسجيلات." },
        { en: "absolutely", ar: "تماماً / كلّياً", pos: "adverb", def: "completely true", defAr: "صحيح تماماً / بشكل كامل", example: "Their services are absolutely free; i.e. the volunteer is not paid, and it doesn’t cost the visually impaired person anything.", exampleAr: "خدماتهم مجانية تماماً؛ أي إن المتطوّع لا يتقاضى أجراً، ولا تكلّف الشخص ذا الإعاقة البصرية شيئاً." },
        { en: "Braille", ar: "طريقة برايل", pos: "noun", def: "a system of printing for blind people in which the letters and the numbers are printed as raised dots", defAr: "نظام طباعة للمكفوفين تُطبع فيه الحروف والأرقام على شكل نقاط بارزة", example: "Light Initiative’s new project is turning the Syrian curriculum into Braille.", exampleAr: "مشروع مبادرة ضوء الجديد هو تحويل المنهاج السوري إلى طريقة برايل." },
        { en: "volunteer", ar: "متطوّع", pos: "noun", def: "a person who works without being paid", defAr: "شخص يعمل دون أن يتقاضى أجراً", example: "Light Initiative started with two people and now it includes more than 350 volunteers.", exampleAr: "بدأت مبادرة ضوء بشخصين، وهي تضمّ الآن أكثر من 350 متطوّعاً." },
        { en: "voluntarily", ar: "طوعاً / تطوّعاً", pos: "adverb", def: "because you want to, without being paid", defAr: "برغبتك ودون أجر", example: "They voluntarily record school and college books for the benefit of the visually impaired people.", exampleAr: "يسجّلون طوعاً كتب المدارس والجامعات لصالح الأشخاص ذوي الإعاقة البصرية." },
        { en: "include", ar: "يضمّ / يشمل", pos: "verb", def: "to have something as a part", defAr: "أن يكون الشيء جزءاً منه", example: "Light Initiative started with two people and now it includes more than 350 volunteers.", exampleAr: "بدأت مبادرة ضوء بشخصين، وهي تضمّ الآن أكثر من 350 متطوّعاً." },
        { en: "record", ar: "يسجّل (صوتياً)", pos: "verb", def: "to put sounds on a device so you can listen to them later", defAr: "أن تحفظ الأصوات على جهاز لتستمع إليها لاحقاً", example: "Then, the book is divided into tasks for a number of volunteers to record them.", exampleAr: "ثم يُقسَّم الكتاب إلى مهامّ على عدد من المتطوّعين ليسجّلوها." },
        { en: "recording", ar: "تسجيل", pos: "noun", def: "sounds that have been recorded", defAr: "أصوات تمّ تسجيلها", example: "On the Facebook page they announce that they finished this book or this curriculum, and they use the YouTube channel to publish the recordings.", exampleAr: "على صفحة فيسبوك يعلنون أنهم أنهوا هذا الكتاب أو هذا المنهاج، ويستخدمون قناة يوتيوب لنشر التسجيلات." },
        { en: "for the benefit of", ar: "لصالح / لمنفعة", pos: "phrase", def: "in order to help somebody", defAr: "من أجل مساعدة شخص ما", example: "They voluntarily record school and college books for the benefit of the visually impaired people.", exampleAr: "يسجّلون طوعاً كتب المدارس والجامعات لصالح الأشخاص ذوي الإعاقة البصرية." },
        { en: "meet somebody's needs", ar: "يلبّي احتياجات شخص ما", pos: "phrase", def: "to give people what they need", defAr: "أن تعطي الناس ما يحتاجون إليه", example: "Their aim is to meet the visually impaired people's actual needs whatever they are.", exampleAr: "هدفهم تلبية الاحتياجات الفعلية للأشخاص ذوي الإعاقة البصرية أيّاً كانت." },
        { en: "actual", ar: "فعلي / حقيقي", pos: "adjective", def: "real", defAr: "حقيقي", example: "Their aim is to meet the visually impaired people's actual needs whatever they are.", exampleAr: "هدفهم تلبية الاحتياجات الفعلية للأشخاص ذوي الإعاقة البصرية أيّاً كانت." },
        { en: "desire", ar: "رغبة", pos: "noun", def: "a strong wish", defAr: "أمنية قوية", example: "Usually, the visually impaired person who has the desire to study a curriculum or a reference, contacts the initiative administration and provides them with the books needed.", exampleAr: "عادةً، يتواصل الشخص ذو الإعاقة البصرية الذي يرغب في دراسة منهاج أو مرجع مع إدارة المبادرة ويزوّدهم بالكتب المطلوبة." },
        { en: "contact", ar: "يتواصل مع / يتّصل بـ", pos: "verb", def: "to call or write to somebody", defAr: "أن تتّصل بشخص أو تكتب إليه", example: "Usually, the visually impaired person who has the desire to study a curriculum or a reference, contacts the initiative administration and provides them with the books needed.", exampleAr: "عادةً، يتواصل الشخص ذو الإعاقة البصرية الذي يرغب في دراسة منهاج أو مرجع مع إدارة المبادرة ويزوّدهم بالكتب المطلوبة." },
        { en: "administration", ar: "إدارة", pos: "noun", def: "the people who manage an organisation", defAr: "الأشخاص الذين يديرون منظّمة ما" },
        { en: "divide", ar: "يقسّم", pos: "verb", def: "to separate something into parts", defAr: "أن تفصل الشيء إلى أجزاء", example: "Then, the book is divided into tasks for a number of volunteers to record them.", exampleAr: "ثم يُقسَّم الكتاب إلى مهامّ على عدد من المتطوّعين ليسجّلوها." },
        { en: "task", ar: "مهمّة", pos: "noun", def: "a piece of work that you have to do", defAr: "عمل عليك أن تقوم به", example: "Then, the book is divided into tasks for a number of volunteers to record them.", exampleAr: "ثم يُقسَّم الكتاب إلى مهامّ على عدد من المتطوّعين ليسجّلوها." },
        { en: "channel", ar: "قناة", pos: "noun", def: "a place on the internet (or TV) where videos are published", defAr: "مكان على الإنترنت (أو التلفاز) تُنشر فيه المقاطع", example: "They use a Facebook page and a YouTube channel.", exampleAr: "يستخدمون صفحة على فيسبوك وقناة على يوتيوب." },
        { en: "publish", ar: "ينشر", pos: "verb", def: "to make something available for people to see, hear or read", defAr: "أن تجعل شيئاً متاحاً ليراه الناس أو يسمعوه أو يقرؤوه", example: "On the Facebook page they announce that they finished this book or this curriculum, and they use the YouTube channel to publish the recordings.", exampleAr: "على صفحة فيسبوك يعلنون أنهم أنهوا هذا الكتاب أو هذا المنهاج، ويستخدمون قناة يوتيوب لنشر التسجيلات." },
        { en: "format", ar: "صيغة / تنسيق", pos: "noun", def: "the form in which a file is saved", defAr: "الشكل الذي يُحفظ به الملف", example: "These records are saved in mp3 format.", exampleAr: "تُحفظ هذه التسجيلات بصيغة mp3." },
        { en: "service", ar: "خدمة", pos: "noun", def: "help or work that someone does for others", defAr: "مساعدة أو عمل يقدّمه شخص للآخرين", example: "Their services are absolutely free; i.e. the volunteer is not paid, and it doesn’t cost the visually impaired person anything.", exampleAr: "خدماتهم مجانية تماماً؛ أي إن المتطوّع لا يتقاضى أجراً، ولا تكلّف الشخص ذا الإعاقة البصرية شيئاً." },
        { en: "free", ar: "مجاني", pos: "adjective", def: "costing no money", defAr: "لا يكلّف مالاً", example: "Their services are absolutely free; i.e. the volunteer is not paid, and it doesn’t cost the visually impaired person anything.", exampleAr: "خدماتهم مجانية تماماً؛ أي إن المتطوّع لا يتقاضى أجراً، ولا تكلّف الشخص ذا الإعاقة البصرية شيئاً." },
        { en: "cost", ar: "يكلّف", pos: "verb", def: "to need an amount of money to buy or do", defAr: "أن يحتاج الشيء مبلغاً من المال", example: "Their services are absolutely free; i.e. the volunteer is not paid, and it doesn’t cost the visually impaired person anything.", exampleAr: "خدماتهم مجانية تماماً؛ أي إن المتطوّع لا يتقاضى أجراً، ولا تكلّف الشخص ذا الإعاقة البصرية شيئاً." },
        { en: "have access to", ar: "يتمكّن من الوصول إلى", pos: "phrase", def: "to be able to get or use something", defAr: "أن تستطيع الحصول على شيء أو استخدامه", example: "Anyone with a network can have access to their records.", exampleAr: "يستطيع أي شخص لديه اتصال بالشبكة الوصول إلى تسجيلاتهم." },
        { en: "network", ar: "شبكة (اتصال بالإنترنت)", pos: "noun", def: "a connection to the internet", defAr: "اتصال بالإنترنت", example: "Anyone with a network can have access to their records.", exampleAr: "يستطيع أي شخص لديه اتصال بالشبكة الوصول إلى تسجيلاتهم." },
        { en: "tool", ar: "أداة", pos: "noun", def: "a thing you use to do a job", defAr: "شيء تستخدمه لإنجاز عمل", example: "No professional tools are needed.", exampleAr: "لا حاجة إلى أدوات احترافية." },
        { en: "professional", ar: "احترافي / مهني", pos: "adjective", def: "made for experts in a job", defAr: "مصنوع لأصحاب الخبرة في مهنة ما", example: "No professional tools are needed.", exampleAr: "لا حاجة إلى أدوات احترافية." },
        { en: "montage", ar: "مونتاج", pos: "noun", def: "putting recorded parts together to make one finished recording", defAr: "تجميع أجزاء مسجّلة لصنع تسجيل واحد جاهز", example: "They use mobiles for recording and laptops to do the montage.", exampleAr: "يستخدمون الهواتف المحمولة للتسجيل والحواسيب المحمولة لإجراء المونتاج." },
        { en: "suffer from", ar: "يعاني من", pos: "phrasal verb", def: "to have a problem or an illness", defAr: "أن تكون لديك مشكلة أو مرض", example: "This will help Syrian students who suffer from sight problems.", exampleAr: "سيساعد هذا الطلاب السوريين الذين يعانون من مشكلات في البصر." },
        { en: "sight", ar: "البصر", pos: "noun", def: "the ability to see", defAr: "القدرة على الرؤية", example: "This will help Syrian students who suffer from sight problems.", exampleAr: "سيساعد هذا الطلاب السوريين الذين يعانون من مشكلات في البصر." },
        { en: "target", ar: "هدف", pos: "noun", def: "what you want to achieve", defAr: "ما تريد تحقيقه" },
        { en: "blind", ar: "كفيف / أعمى", pos: "adjective", def: "not able to see", defAr: "لا يستطيع الرؤية" },
        { en: "elderly", ar: "المسنّون / كبار السنّ", pos: "noun", def: "old people", defAr: "الأشخاص كبار السنّ" },
        { en: "accident", ar: "حادث", pos: "noun", def: "something bad that happens suddenly and hurts people", defAr: "أمر سيّئ يحدث فجأة ويؤذي الناس" },
        { en: "offer help", ar: "يعرض المساعدة", pos: "phrase", def: "to say that you are ready to help", defAr: "أن تقول إنك مستعدّ للمساعدة" },
        { en: "disabled", ar: "من ذوي الإعاقة", pos: "adjective", def: "having a problem with the body that makes some things difficult", defAr: "لديه مشكلة جسدية تجعل بعض الأمور صعبة" },
        { en: "neighbour", ar: "جار", pos: "noun", def: "a person who lives near you", defAr: "شخص يسكن قريباً منك", example: "Ahmed is your neighbour.", exampleAr: "أحمد جارك." },
        { en: "experienced", ar: "ذو خبرة", pos: "adjective", def: "having knowledge and skill from doing something for a long time", defAr: "لديه معرفة ومهارة لأنه مارس شيئاً مدة طويلة", example: "She’s very experienced now.", exampleAr: "هي ذات خبرة كبيرة الآن." },
        { en: "charity", ar: "جمعية خيرية", pos: "noun", def: "an organisation that collects money to help people in need", defAr: "منظّمة تجمع المال لمساعدة المحتاجين" },
      ],
      reading: {
        title: "Light Initiative",
        paragraphs: [
          "What is ‘Light Initiative’?",
          "Light Initiative started with two people and now it includes more than 350 volunteers. They voluntarily record school and college books for the benefit of the visually impaired people. They started recording the books of the 9th and the 12th grades; they also record university books and references. Their aim is to meet the visually impaired people's actual needs whatever they are.",
          "How do they work?",
          "Usually, the visually impaired person who has the desire to study a curriculum or a reference, contacts the initiative administration and provides them with the books needed. Then, the book is divided into tasks for a number of volunteers to record them.",
          "Social Media",
          "They use a Facebook page and a YouTube channel. On the Facebook page they announce that they finished this book or this curriculum, and they use the YouTube channel to publish the recordings. These records are saved in mp3 format.",
          "Service Cost",
          "Their services are absolutely free; i.e. the volunteer is not paid, and it doesn’t cost the visually impaired person anything. Anyone with a network can have access to their records.",
          "Tools",
          "Volunteers need very simple things. They use mobiles for recording and laptops to do the montage. No professional tools are needed.",
          "What’s New?",
          "Light Initiative’s new project is turning the Syrian curriculum into Braille. This will help Syrian students who suffer from sight problems.",
          "Light Initiative’s Target",
          "Light Initiative is trying to bring some light into the visually impaired people’s lives.",
        ],
        paragraphsAr: [
          "ما هي «مبادرة ضوء»؟",
          "بدأت مبادرة ضوء بشخصين، وهي تضمّ الآن أكثر من 350 متطوّعاً. يسجّلون طوعاً (صوتياً) كتب المدارس والجامعات لصالح الأشخاص ذوي الإعاقة البصرية. بدأوا بتسجيل كتب الصفّين التاسع والثاني عشر، ويسجّلون أيضاً الكتب الجامعية والمراجع. وهدفهم تلبية الاحتياجات الفعلية للأشخاص ذوي الإعاقة البصرية أيّاً كانت.",
          "كيف يعملون؟",
          "عادةً، يتواصل الشخص ذو الإعاقة البصرية الذي يرغب في دراسة منهاج أو مرجع مع إدارة المبادرة، ويزوّدهم بالكتب المطلوبة. ثم يُقسَّم الكتاب إلى مهامّ على عدد من المتطوّعين ليسجّلوها.",
          "وسائل التواصل الاجتماعي",
          "يستخدمون صفحة على فيسبوك وقناة على يوتيوب. فعلى صفحة فيسبوك يعلنون أنهم أنهوا هذا الكتاب أو هذا المنهاج، ويستخدمون قناة يوتيوب لنشر التسجيلات. وتُحفظ هذه التسجيلات بصيغة mp3.",
          "تكلفة الخدمة",
          "خدماتهم مجانية تماماً؛ أي إن المتطوّع لا يتقاضى أجراً، ولا تكلّف الشخصَ ذا الإعاقة البصرية شيئاً. ويستطيع أي شخص لديه اتصال بالشبكة (الإنترنت) الوصول إلى تسجيلاتهم.",
          "الأدوات",
          "يحتاج المتطوّعون إلى أشياء بسيطة جداً. فهم يستخدمون الهواتف المحمولة للتسجيل والحواسيب المحمولة لإجراء المونتاج. ولا حاجة إلى أدوات احترافية.",
          "ما الجديد؟",
          "مشروع مبادرة ضوء الجديد هو تحويل المنهاج السوري إلى طريقة برايل. وسيساعد هذا الطلابَ السوريين الذين يعانون من مشكلات في البصر.",
          "هدف مبادرة ضوء",
          "تحاول مبادرة ضوء أن تُدخل بعض النور إلى حياة الأشخاص ذوي الإعاقة البصرية.",
        ],
        questions: [
          { q: "Who is Light Initiative targeted for?", qAr: "لمن تستهدف مبادرة ضوء (لمن وُجِّهت)؟",
            options: ["The visually impaired people.", "The teachers of the 9th grade.", "People who want to learn recording.", "People who work on YouTube."],
            answer: 0, explainAr: "النص يقول: for the benefit of the visually impaired people، وهدفها: to bring some light into the visually impaired people’s lives — أي الأشخاص ذوو الإعاقة البصرية." },
          { q: "Where are the recorded books published?", qAr: "أين تُنشر الكتب المسجّلة؟",
            options: ["On the Facebook page only.", "On their YouTube channel.", "In printed Braille books.", "In school libraries."],
            answer: 1, explainAr: "النص يقول: they use the YouTube channel to publish the recordings — يستخدمون قناة يوتيوب لنشر التسجيلات. أمّا صفحة فيسبوك فللإعلان (announce) فقط." },
          { q: "What do volunteers use to record books?", qAr: "ماذا يستخدم المتطوّعون لتسجيل الكتب؟",
            options: ["Professional recording tools.", "Laptops.", "Mobiles.", "Braille machines."],
            answer: 2, explainAr: "النص يقول: They use mobiles for recording and laptops to do the montage — الهواتف المحمولة للتسجيل، والحواسيب المحمولة للمونتاج. No professional tools are needed." },
          { q: "How much does it cost to have the recorded books?", qAr: "كم يكلّف الحصول على الكتب المسجّلة؟",
            options: ["It costs a lot of money.", "Nothing — the services are absolutely free.", "The visually impaired person pays the volunteer.", "Only the Braille books cost money."],
            answer: 1, explainAr: "النص يقول: Their services are absolutely free … it doesn’t cost the visually impaired person anything — الخدمة مجانية تماماً." },
          { q: "Match: “Volunteers record the book …”", qAr: "صِل: «يسجّل المتطوّعون الكتاب …»",
            options: ["if you have a network.", "the syllabus into Braille.", "after it is divided into several tasks.", "of the recordings."],
            answer: 2, explainAr: "1 ← c: الكتاب يُقسَّم أولاً إلى مهامّ (Then, the book is divided into tasks) ثم يسجّله المتطوّعون: Volunteers record the book after it is divided into several tasks." },
          { q: "Match: “Mp3 is the form …”", qAr: "صِل: «mp3 هي الصيغة …»",
            options: ["of the recordings.", "if you have a network.", "after it is divided into several tasks.", "the syllabus into Braille."],
            answer: 0, explainAr: "2 ← d: النص يقول These records are saved in mp3 format، إذن Mp3 is the form of the recordings = mp3 هي صيغة التسجيلات." },
          { q: "Match: “You can listen to the recordings …”", qAr: "صِل: «يمكنك الاستماع إلى التسجيلات …»",
            options: ["the syllabus into Braille.", "of the recordings.", "if you have a network.", "after it is divided into several tasks."],
            answer: 2, explainAr: "3 ← a: النص يقول Anyone with a network can have access to their records — تستطيع الاستماع إليها إذا كان لديك اتصال بالشبكة." },
          { q: "Match: “Nowadays, volunteers are turning …”", qAr: "صِل: «هذه الأيام، يحوّل المتطوّعون …»",
            options: ["of the recordings.", "the syllabus into Braille.", "if you have a network.", "after it is divided into several tasks."],
            answer: 1, explainAr: "4 ← b: مشروعهم الجديد turning the Syrian curriculum into Braille، و syllabus = curriculum (منهاج)." },
        ],
        trueFalse: [
          { statement: "Light Initiative started with two people.", answer: true },
          { statement: "The volunteers are paid for recording the books.", answer: false },
          { statement: "Volunteers need professional tools to record the books.", answer: false },
          { statement: "The recordings are saved in mp3 format.", answer: true },
          { statement: "Light Initiative’s new project is turning the Syrian curriculum into Braille.", answer: true },
        ],
      },
      vocabFocus: {
        name: "Using certain expressions in different contexts", nameAr: "استخدام تعابير معيّنة في سياقات مختلفة",
        ruleEn: [
          "Fill in the blanks with suitable expressions from the text.",
          "for the benefit of + somebody: in order to help somebody (… for the benefit of the visually impaired people.)",
          "meet somebody's needs: give people what they need (… to meet the visually impaired people's actual needs …)",
          "have access to + something: be able to get or use something (Anyone with a network can have access to their records.)",
          "provide somebody with something (… provides them with the books needed.)",
          "suffer from + a problem (… students who suffer from sight problems.)",
        ],
        ruleAr: [
          "التعبير (expression) مجموعة كلمات تأتي معاً دائماً، فنحفظها كاملة مع حرف الجر الذي بعدها.",
          "for the benefit of = لصالح / لمنفعة، ويأتي بعده الشخص المستفيد: for the benefit of the poor.",
          "meet somebody's needs = يلبّي احتياجات شخص ما: meet the disabled people's needs.",
          "have access to = يتمكّن من الوصول إلى / الحصول على: have access to safe drinking water.",
          "provide somebody with something = يزوّد شخصاً بشيء (لاحظ with)، و suffer from = يعاني من (لاحظ from).",
        ],
        examples: [
          "They voluntarily record school and college books for the benefit of the visually impaired people.",
          "Their aim is to meet the visually impaired people's actual needs whatever they are.",
          "Anyone with a network can have access to their records.",
          "This will help Syrian students who suffer from sight problems.",
        ],
        exercises: [
          // the book's exercise (p. 11)
          { type: "fill", prompt: "This party was done ___ the poor.", promptAr: "أُقيم هذا الحفل ___ الفقراء.", promptArFull: "أُقيم هذا الحفل لصالح الفقراء.", options: ["for the benefit of", "have access to", "suffer from", "provide with"], answer: 0, explainAr: "الحفل أُقيم لمساعدة الفقراء، والتعبير for the benefit of = لصالح / لمنفعة، ويأتي بعده المستفيد (the poor)." },
          { type: "fill", prompt: "A lift was put to ___ the disabled ___.", promptAr: "وُضع مصعد لـ___ ذوي الإعاقة ___.", promptArFull: "وُضع مصعد لتلبية احتياجات الأشخاص ذوي الإعاقة.", options: ["meet … people's needs", "announce … people's needs", "suffer … from", "access … with"], answer: 0, explainAr: "المصعد يلبّي ما يحتاجه ذوو الإعاقة، والتعبير من النص: meet the visually impaired people's actual needs ← A lift was put to meet the disabled people's needs." },
          { type: "fill", prompt: "Some people in Africa do not ___ to safe drinking water.", promptAr: "بعض الناس في أفريقيا لا ___ إلى مياه الشرب الآمنة.", promptArFull: "بعض الناس في أفريقيا لا يستطيعون الوصول إلى مياه الشرب الآمنة.", options: ["have access", "provide", "suffer", "meet"], answer: 0, explainAr: "بعد الفراغ يأتي to، والتعبير have access to = يستطيع الوصول إلى / الحصول على، كما في النص: can have access to their records." },
          // the same expressions in the text
          { type: "fill", prompt: "They voluntarily record school and college books ___ the visually impaired people.", promptAr: "يسجّلون طوعاً كتب المدارس والجامعات ___ الأشخاص ذوي الإعاقة البصرية.", promptArFull: "يسجّلون طوعاً كتب المدارس والجامعات لصالح الأشخاص ذوي الإعاقة البصرية.", options: ["for the benefit of", "have access to", "suffer from", "in the form of"], answer: 0, explainAr: "المتطوّعون يسجّلون الكتب لمساعدة ذوي الإعاقة البصرية: for the benefit of = لصالح." },
          { type: "fill", prompt: "Their aim is to ___ the visually impaired people's actual needs.", promptAr: "هدفهم ___ الاحتياجات الفعلية للأشخاص ذوي الإعاقة البصرية.", promptArFull: "هدفهم تلبية الاحتياجات الفعلية للأشخاص ذوي الإعاقة البصرية.", options: ["meet", "announce", "divide", "suffer"], answer: 0, explainAr: "نقول meet somebody's needs = يلبّي الاحتياجات. الكلمة needs تأتي مع الفعل meet." },
          { type: "fill", prompt: "The visually impaired person ___ them with the books needed.", promptAr: "الشخص ذو الإعاقة البصرية ___هم بالكتب المطلوبة.", promptArFull: "الشخص ذو الإعاقة البصرية يزوّدهم بالكتب المطلوبة.", options: ["provides", "announces", "suffers", "divides"], answer: 0, explainAr: "provide somebody with something = يزوّد شخصاً بشيء. وجود with بعد them دليل على provide، ونضيف s لأن الفاعل مفرد." },
          { type: "fill", prompt: "Anyone with a network can ___ their records.", promptAr: "أي شخص لديه اتصال بالشبكة يستطيع ___ تسجيلاتهم.", promptArFull: "أي شخص لديه اتصال بالشبكة يستطيع الوصول إلى تسجيلاتهم.", options: ["have access to", "suffer from", "for the benefit of", "provide with"], answer: 0, explainAr: "بعد can نحتاج فعلاً، والمعنى الحصول على التسجيلات واستخدامها: have access to." },
          { type: "fill", prompt: "This will help Syrian students who ___ sight problems.", promptAr: "سيساعد هذا الطلاب السوريين الذين ___ مشكلات في البصر.", promptArFull: "سيساعد هذا الطلاب السوريين الذين يعانون من مشكلات في البصر.", options: ["suffer from", "have access to", "provide", "meet"], answer: 0, explainAr: "suffer from + مشكلة أو مرض = يعاني من. الطلاب يعانون من مشكلات في البصر." },
          { type: "fill", prompt: "On the Facebook page they ___ that they finished this book.", promptAr: "على صفحة فيسبوك ___ أنهم أنهوا هذا الكتاب.", promptArFull: "على صفحة فيسبوك يعلنون أنهم أنهوا هذا الكتاب.", options: ["announce", "provide", "divide", "record"], answer: 0, explainAr: "announce = يخبر الناس بشيء بشكل رسمي (يُعلن). يُعلنون على فيسبوك انتهاء الكتاب." },
          { type: "fill", prompt: "Their services are ___ free.", promptAr: "خدماتهم مجانية ___.", promptArFull: "خدماتهم مجانية تماماً.", options: ["absolutely", "visually", "voluntarily", "actual"], answer: 0, explainAr: "absolutely = تماماً / كلّياً، وتأتي قبل الصفة free لتقوّيها: absolutely free = مجانية تماماً." },
          { type: "fill", prompt: "Light Initiative’s new project is turning the Syrian curriculum into ___.", promptAr: "مشروع مبادرة ضوء الجديد هو تحويل المنهاج السوري إلى ___.", promptArFull: "مشروع مبادرة ضوء الجديد هو تحويل المنهاج السوري إلى طريقة برايل.", options: ["Braille", "montage", "a network", "a channel"], answer: 0, explainAr: "Braille = نظام طباعة للمكفوفين بنقاط بارزة، وهو ما سيساعد الطلاب الذين يعانون من مشكلات في البصر." },
          { type: "fill", prompt: "They also record university books and ___.", promptAr: "ويسجّلون أيضاً الكتب الجامعية و___.", promptArFull: "ويسجّلون أيضاً الكتب الجامعية والمراجع.", options: ["references", "tools", "tasks", "channels"], answer: 0, explainAr: "reference = مرجع، أي مصدر معلومات مثل الكتب والمقالات، ويأتي مع university books." },
          { type: "fill", prompt: "Then, the book is ___ into tasks for a number of volunteers.", promptAr: "ثم ___ الكتاب إلى مهامّ على عدد من المتطوّعين.", promptArFull: "ثم يُقسَّم الكتاب إلى مهامّ على عدد من المتطوّعين.", options: ["divided", "provided", "announced", "suffered"], answer: 0, explainAr: "divide something into parts = يقسّم الشيء إلى أجزاء؛ وهنا بصيغة المبني للمجهول is divided into." },
          // meanings of the key words
          { type: "mcq", prompt: "“initiative” means:", promptAr: "معنى «initiative» هو:", options: ["a new plan for dealing with a particular problem", "source of information like books or articles", "to tell people something officially", "people with sight problems"], answer: 0, explainAr: "initiative = مبادرة: خطة جديدة للتعامل مع مشكلة معيّنة، مثل Light Initiative." },
          { type: "mcq", prompt: "“visually impaired” means:", promptAr: "معنى «visually impaired» هو:", options: ["people with sight problems", "people who record books", "people who are not paid", "people who live near you"], answer: 0, explainAr: "visually impaired = ذوو الإعاقة البصرية: أشخاص لديهم مشكلات في البصر (visual = بصري)." },
          { type: "mcq", prompt: "“curriculum” has the same meaning as:", promptAr: "كلمة «curriculum» لها معنى:", options: ["syllabus", "channel", "montage", "network"], answer: 0, explainAr: "curriculum = syllabus = منهاج: المواد التي تُدرَّس في مدرسة أو كلية." },
          { type: "mcq", prompt: "“provide” means:", promptAr: "معنى «provide» هو:", options: ["to tell people something officially", "to give somebody something or to supply", "to separate something into parts", "to make use of something"], answer: 1, explainAr: "provide = يزوّد / يقدّم: أن تعطي شخصاً شيئاً. ونقول provide somebody with something." },
          { type: "mcq", prompt: "“announce” means:", promptAr: "معنى «announce» هو:", options: ["to tell people something officially", "to give somebody something", "completely true", "to record books"], answer: 0, explainAr: "announce = يُعلن: أن تخبر الناس بشيء بشكل رسمي." },
          { type: "mcq", prompt: "“Braille” is:", promptAr: "«Braille» هي:", options: ["a system of printing for blind people with raised dots", "a YouTube channel for books", "a kind of mp3 recording", "a new plan for dealing with a problem"], answer: 0, explainAr: "Braille = طريقة برايل: نظام طباعة للمكفوفين تُطبع فيه الحروف والأرقام نقاطاً بارزة تُقرأ باللمس." },
          { type: "truefalse", prompt: "“for the benefit of the poor” means “in order to help the poor”.", promptAr: "عبارة «for the benefit of the poor» تعني «من أجل مساعدة الفقراء».", answer: true, explainAr: "صحيح؛ for the benefit of = لصالح / لمنفعة، أي لمساعدة شخص ما." },
          { type: "truefalse", prompt: "“have access to” means “to tell people something officially”.", promptAr: "التعبير «have access to» يعني «أن تخبر الناس بشيء رسمياً».", answer: false, explainAr: "خطأ؛ هذا معنى announce. أمّا have access to فيعني أن تستطيع الوصول إلى شيء أو استخدامه." },
        ],
      },
      grammar: {
        name: "Revision of present perfect", nameAr: "مراجعة المضارع التام",
        ruleEn: [
          "Form: have / has + past participle (V3). I / you / we / they have helped; he / she / it has arrived.",
          "Negative: haven't / hasn't + past participle (He hasn’t eaten for four days). Question: Have / Has + subject + past participle? (Have you done your homework? — Yes, I have.)",
          "Use the present perfect for an action that started in the past and continues until now: for + a period of time (for two years), since + a starting point (since we graduated from university).",
          "Use it for a past action with a result now, when we don't say exactly when: just, already, yet, ever, never, before (She has just arrived. I haven’t been to Paris before.)",
          "Don't use the present perfect with a finished time (yesterday, last week, ago); use the past simple.",
        ],
        ruleAr: [
          "التكوين: have / has + التصريف الثالث للفعل (V3). نستعمل has مع he / she / it والمفرد، و have مع I / you / we / they والجمع.",
          "النفي: haven't / hasn't + V3، والسؤال: Have / Has + الفاعل + V3؟ والجواب المختصر: Yes, I have. / No, I haven't.",
          "نستعمله لحدث بدأ في الماضي وما زال مستمراً: for + مدة (for two years = منذ سنتين)، و since + نقطة بداية (since we graduated = منذ تخرّجنا).",
          "ونستعمله لحدث انتهى وله نتيجة الآن دون ذكر وقت محدّد، ومن علاماته: just (للتو)، already (مسبقاً)، yet (بعد — في النفي والسؤال)، ever (أبداً — في السؤال)، never، before.",
          "لا نستعمله مع وقت منتهٍ مثل yesterday و last week و ago، بل نستعمل الماضي البسيط.",
        ],
        examples: [
          "She’s very experienced now. She has been a volunteer for two years.",
          "Good news! They have raised enough money for the charity this year.",
          "We have helped a lot of young people since we graduated from university.",
          "He’s hungry. He hasn’t eaten for four days.",
          "Have you done your homework? Yes, I have.",
          "She has just arrived. She will speak to you in a minute.",
          "I haven’t been to Paris before.",
        ],
        exercises: [
          // A. select the correct answer (p. 11)
          { type: "fill", prompt: "She’s very experienced now. She ___ been a volunteer for two years.", promptAr: "هي ذات خبرة كبيرة الآن. ___ متطوّعة منذ سنتين.", promptArFull: "هي ذات خبرة كبيرة الآن. إنها متطوّعة منذ سنتين.", options: ["has", "hasn't", "have"], answer: 0, explainAr: "صارت ذات خبرة لأنها تطوّعت فترة طويلة، فالمعنى إثبات: has been. ومع She نستعمل has لا have." },
          { type: "fill", prompt: "Good news! They ___ enough money for the charity this year.", promptAr: "أخبار جيدة! ___ ما يكفي من المال للجمعية الخيرية هذا العام.", promptArFull: "أخبار جيدة! لقد جمعوا ما يكفي من المال للجمعية الخيرية هذا العام.", options: ["have raised", "haven't raised", "has raised"], answer: 0, explainAr: "Good news! (خبر جيد) يعني أنهم نجحوا، فالجملة مثبتة: have raised. ومع They نستعمل have." },
          { type: "fill", prompt: "We ___ helped a lot of young people since we graduated from university.", promptAr: "___ الكثير من الشباب منذ تخرّجنا في الجامعة.", promptArFull: "لقد ساعدنا الكثير من الشباب منذ تخرّجنا في الجامعة.", options: ["have", "haven't", "has"], answer: 0, explainAr: "a lot of young people (الكثير من الشباب) يدلّ على الإثبات، ومع We نستعمل have. و since + نقطة بداية." },
          { type: "fill", prompt: "He’s hungry. He hasn’t ___ for four days.", promptAr: "هو جائع. لم ___ منذ أربعة أيام.", promptArFull: "هو جائع. لم يأكل منذ أربعة أيام.", options: ["eaten", "eat", "ate", "eating"], answer: 0, explainAr: "بعد hasn't نضع التصريف الثالث (V3): eat – ate – eaten، إذن hasn’t eaten." },
          { type: "fill", prompt: "She misses the bus, she ___ got up early.", promptAr: "إنها تفوّت الحافلة، فهي ___ مبكراً.", promptArFull: "إنها تفوّت الحافلة، فهي لم تستيقظ مبكراً.", options: ["hasn't", "haven't", "isn't"], answer: 0, explainAr: "الفاعل She مفرد فنستعمل hasn't لا haven't، و got هنا تصريف ثالث (get up – got up). وفاتتها الحافلة لأنها لم تستيقظ باكراً." },
          // B. match A with B (p. 11)
          { type: "mcq", prompt: "Have you done your homework? — ___", promptAr: "هل أنهيت واجبك؟ — ___", options: ["Yes, I have.", "for two months.", "to Paris before.", "since she arrived to our city."], answer: 0, explainAr: "1 ← d: السؤال يبدأ بـ Have فالجواب المختصر Yes, I have (نكرّر have ولا نكرّر done)." },
          { type: "mcq", prompt: "She has just arrived. ___", promptAr: "لقد وصلت للتو. ___", options: ["She will speak to you in a minute.", "Yes, I have.", "for two months.", "to Paris before."], answer: 0, explainAr: "2 ← a: وصلت للتو (just) ولذلك ستتحدّث إليك بعد دقيقة. الجملة الثانية مكمّلة للمعنى." },
          { type: "mcq", prompt: "We have known her ___", promptAr: "نعرفها ___", options: ["since she arrived to our city.", "Yes, I have.", "She will speak to you in a minute.", "to Paris before."], answer: 0, explainAr: "3 ← e: have known + since + نقطة بداية: since she arrived to our city = منذ وصلت إلى مدينتنا." },
          { type: "mcq", prompt: "He has worked here ___", promptAr: "لقد عمل هنا ___", options: ["for two months.", "to Paris before.", "Yes, I have.", "She will speak to you in a minute."], answer: 0, explainAr: "4 ← b: has worked + for + مدة زمنية: for two months = منذ شهرين (مدة)." },
          { type: "mcq", prompt: "I haven’t been ___", promptAr: "لم أذهب ___", options: ["to Paris before.", "for two months.", "Yes, I have.", "since she arrived to our city."], answer: 0, explainAr: "5 ← c: have been to + مكان = ذهبت إلى مكان وعدت. I haven’t been to Paris before = لم أذهب إلى باريس من قبل." },
          // more practice in the unit's world
          { type: "fill", prompt: "The volunteers ___ many books since they started.", promptAr: "المتطوّعون ___ كتباً كثيرة منذ أن بدأوا.", promptArFull: "المتطوّعون سجّلوا كتباً كثيرة منذ أن بدأوا.", options: ["have recorded", "has recorded", "are record", "recording"], answer: 0, explainAr: "since علامة المضارع التام، و The volunteers جمع فنستعمل have + V3: have recorded." },
          { type: "fill", prompt: "Light Initiative ___ just ___ a new project.", promptAr: "مبادرة ضوء ___ للتو مشروعاً جديداً.", promptArFull: "مبادرة ضوء بدأت للتو مشروعاً جديداً.", options: ["has … started", "have … started", "has … start", "is … started"], answer: 0, explainAr: "Light Initiative مفرد (it) فنستعمل has، و just تأتي بين has والتصريف الثالث: has just started." },
          { type: "fill", prompt: "They ___ already ___ the books of the 9th grade.", promptAr: "___ مسبقاً كتب الصف التاسع.", promptArFull: "لقد سجّلوا مسبقاً كتب الصف التاسع.", options: ["have … recorded", "has … recorded", "have … record", "are … recorded"], answer: 0, explainAr: "They جمع فنستعمل have، و already تأتي بين have و V3: have already recorded." },
          { type: "fill", prompt: "___ you ever ___ a blind person to cross the street?", promptAr: "هل ___ يوماً شخصاً كفيفاً على عبور الشارع؟", promptArFull: "هل ساعدت يوماً شخصاً كفيفاً على عبور الشارع؟", options: ["Have … helped", "Has … helped", "Did … helped", "Have … help"], answer: 0, explainAr: "السؤال في المضارع التام: Have + you + ever + V3. مع you نستعمل Have، والتصريف الثالث helped." },
          { type: "fill", prompt: "I ___ never ___ blood.", promptAr: "أنا ___ دماً أبداً.", promptArFull: "أنا لم أتبرّع بالدم أبداً.", options: ["have … given", "has … given", "have … gave", "am … given"], answer: 0, explainAr: "مع I نستعمل have، و never بين have و V3، والتصريف الثالث لـ give هو given (give – gave – given)." },
          { type: "fill", prompt: "Ahmed ___ played football with us for a long time.", promptAr: "أحمد ___ كرة القدم معنا منذ وقت طويل.", promptArFull: "أحمد لم يلعب كرة القدم معنا منذ وقت طويل.", options: ["hasn't", "haven't", "isn't", "don't"], answer: 0, explainAr: "Ahmed مفرد فالنفي في المضارع التام hasn't + V3 (played). ولا يستطيع المشي فلم يلعب معنا." },
          { type: "fill", prompt: "She has been a volunteer ___ two years.", promptAr: "هي متطوّعة ___ سنتين.", promptArFull: "هي متطوّعة منذ سنتين.", options: ["for", "since", "yet", "ago"], answer: 0, explainAr: "two years مدة زمنية، ومع المدة نستعمل for. (since تأتي مع نقطة بداية)." },
          { type: "fill", prompt: "We have known Ahmed ___ we were children.", promptAr: "نعرف أحمد ___ كنّا أطفالاً.", promptArFull: "نعرف أحمد منذ كنّا أطفالاً.", options: ["since", "for", "yet", "already"], answer: 0, explainAr: "we were children نقطة بداية (بداية المعرفة)، ومعها نستعمل since." },
          { type: "fill", prompt: "They haven’t finished the Braille project ___.", promptAr: "لم ينهوا مشروع برايل ___.", promptArFull: "لم ينهوا مشروع برايل بعد.", options: ["yet", "already", "just", "since"], answer: 0, explainAr: "yet (بعد) تأتي في آخر الجملة المنفية أو السؤال في المضارع التام. أمّا already و just فللجمل المثبتة." },
          { type: "fill", prompt: "Have you ___ heard of Light Initiative?", promptAr: "هل سمعت ___ بمبادرة ضوء؟", promptArFull: "هل سمعت يوماً بمبادرة ضوء؟", options: ["ever", "yet", "since", "for"], answer: 0, explainAr: "ever (يوماً / في حياتك) تأتي في السؤال بين الفاعل والتصريف الثالث: Have you ever heard …?" },
          { type: "fill", prompt: "The volunteers have ___ published the recordings on YouTube.", promptAr: "المتطوّعون نشروا التسجيلات ___ على يوتيوب.", promptArFull: "المتطوّعون نشروا التسجيلات مسبقاً على يوتيوب.", options: ["already", "yet", "since", "ago"], answer: 0, explainAr: "already (مسبقاً / سابقاً) تأتي في الجملة المثبتة بين have و V3. yet لا تأتي في الجملة المثبتة، و ago للماضي البسيط." },
          { type: "fill", prompt: "My friend has ___ the steps to help Ahmed.", promptAr: "صديقي ___ الخطوات لمساعدة أحمد.", promptArFull: "صديقي كتب الخطوات لمساعدة أحمد.", options: ["written", "wrote", "write", "writed"], answer: 0, explainAr: "بعد has نضع التصريف الثالث: write – wrote – written. فعل شاذّ فلا نقول writed." },
          { type: "fill", prompt: "How many books ___ the volunteers ___?", promptAr: "كم كتاباً ___ المتطوّعون؟", promptArFull: "كم كتاباً سجّل المتطوّعون؟", options: ["have … recorded", "has … recorded", "have … record", "did … recorded"], answer: 0, explainAr: "السؤال في المضارع التام: have + الفاعل الجمع (the volunteers) + V3 (recorded)." },
          { type: "mcq", prompt: "Which sentence is in the present perfect?", promptAr: "أيّ جملة في زمن المضارع التام؟", options: ["She has just arrived.", "She arrived yesterday.", "She is arriving now.", "She arrives every day."], answer: 0, explainAr: "has + arrived (V3) = مضارع تام، و just من علاماته. الجمل الأخرى: ماضٍ بسيط، مضارع مستمر، مضارع بسيط." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["They have recorded the book last week.", "They recorded the book last week.", "They have record the book last week.", "They has recorded the book."], answer: 1, explainAr: "last week وقت منتهٍ في الماضي فنستعمل الماضي البسيط recorded، ولا نستعمل المضارع التام مع last week أو yesterday." },
          { type: "mcq", prompt: "The past participle (V3) of “do” is:", promptAr: "التصريف الثالث (V3) للفعل «do» هو:", options: ["done", "did", "doed", "doing"], answer: 0, explainAr: "do – did – done. فنقول: Have you done your homework?" },
          { type: "mcq", prompt: "The past participle (V3) of “give” is:", promptAr: "التصريف الثالث (V3) للفعل «give» هو:", options: ["gave", "given", "gived", "giving"], answer: 1, explainAr: "give – gave – given. فنقول مثلاً: I have given blood." },
          { type: "mcq", prompt: "We use ___ with a period of time, like “two years” or “four days”.", promptAr: "نستعمل ___ مع مدة زمنية مثل «two years» أو «four days».", options: ["for", "since", "yet", "just"], answer: 0, explainAr: "for + مدة: for two years, for four days. أمّا since فمع نقطة البداية." },
          { type: "mcq", prompt: "We use ___ with a starting point, like “we graduated from university”.", promptAr: "نستعمل ___ مع نقطة بداية مثل «we graduated from university».", options: ["for", "since", "ago", "already"], answer: 1, explainAr: "since + نقطة بداية: since we graduated from university، since she arrived to our city." },
          { type: "truefalse", prompt: "“He hasn’t eat for four days.” is correct.", promptAr: "الجملة «He hasn’t eat for four days.» صحيحة.", answer: false, explainAr: "خطأ؛ بعد hasn't نضع التصريف الثالث: He hasn’t eaten for four days." },
          { type: "truefalse", prompt: "“They has raised enough money for the charity.” is correct.", promptAr: "الجملة «They has raised enough money for the charity.» صحيحة.", answer: false, explainAr: "خطأ؛ مع They نستعمل have: They have raised enough money for the charity." },
          { type: "truefalse", prompt: "“She has been a volunteer for two years.” is correct.", promptAr: "الجملة «She has been a volunteer for two years.» صحيحة.", answer: true, explainAr: "صحيح؛ She + has + been (V3 من be) + for + مدة." },
          { type: "build", prompt: "رتّب: هي متطوّعة منذ سنتين.", answer: "She has been a volunteer for two years." },
          { type: "build", prompt: "رتّب: لقد جمعوا ما يكفي من المال للجمعية الخيرية هذا العام.", answer: "They have raised enough money for the charity this year." },
          { type: "build", prompt: "رتّب: لم أذهب إلى باريس من قبل.", answer: "I haven't been to Paris before." },
        ],
      },
      listening: {
        taskAr: "استمع إلى شذا ودانيال وأحمد يتحدّثون عن مبادراتهم الفردية، ثم A: قرّر إن كانت الجمل صحيحة أو خاطئة، و B: اختر الإجابة الصحيحة. (إجابات هذه الأسئلة في التسجيل الصوتي، وهو غير مطبوع في الكتاب.)",
        items: [
          "Shaza tried to provide the girls with money.",
          "Daniel wanted to repair the house.",
          "Ahmad’s project was to help the old people in crossing the street.",
          "Shaza wanted to help her ... friends. (a. neighbours’ b. daughters’ c. sisters’)",
          "Daniel felt responsible for repairing the house because it is ... (a. his parents’ house. b. next to his house. c. on his way to work.)",
          "Ahmad is ... boy. (a. a school b. a scout c. an office)",
        ],
      },
      writing: {
        taskAr: "أحمد جارك. لديه مشكلة في ساقيه فلا يستطيع المشي، وتراه دائماً يراقبك بحزن وأنت تلعب مع أصدقائك. فكّر في فكرة لمساعدته، واكتب الخطوات التي ستتّبعها لحلّ مشكلته (فقرة عملية تشرح خطوات بالترتيب). رتّب خطواتك بكلمات مثل Usually و Then كما في فقرة «How do they work?» في نص القراءة.",
        linkers: ["Usually,", "Then,"],
      },
      sentences: [
        "Light Initiative started with two people and now it includes more than 350 volunteers.",
        "Their aim is to meet the visually impaired people's actual needs whatever they are.",
        "They use a Facebook page and a YouTube channel.",
        "These records are saved in mp3 format.",
        "Anyone with a network can have access to their records.",
        "Volunteers need very simple things.",
        "They use mobiles for recording and laptops to do the montage.",
        "No professional tools are needed.",
        "Light Initiative’s new project is turning the Syrian curriculum into Braille.",
        "This will help Syrian students who suffer from sight problems.",
        "Have you done your homework?",
        "She will speak to you in a minute.",
        "What did you do to help them?",
        "Did anyone ask you to do that?",
        "He has a problem with his legs, so he can’t walk.",
        "You always see him watching you sadly playing with your friends.",
      ],
    },
  ],
  focus: {
    title: "Focus on Social Studies — Map skills",
    paragraphs: [
      "Reading a map: Places around town — قراءة خريطة: أماكن حول البلدة",
      "The map has a compass: N = north (شمال), S = south (جنوب), E = east (شرق), W = west (غرب). Its roads are Della road, Hamburg road, Grand Street and Atwood Street.",
      "On the map (from west to east): north of Della road — the airport, the hospital, the restaurant; south of Della road — the park, the hotel and the pet shop; then the library, the flower shop and the supermarket; then the school, the bakery and the police station. (هذا وصف لما في صورة الخريطة.)",
      "Write north, south, east, and west in the spaces to complete each sentence. — اكتب شمال، جنوب، شرق، غرب في الفراغات لإكمال كل جملة.",
      "1. The pet shop is south of the park. — متجر الحيوانات الأليفة جنوب الحديقة.",
      "2. The flower shop is east of the library. — محل الزهور شرق المكتبة.",
      "3. The school is north of the police station. — المدرسة شمال مركز الشرطة.",
      "4. The hospital is north-west of the police station (it is north of Della road and west of Atwood Street). — المستشفى في الشمال الغربي من مركز الشرطة.",
      "5. The bakery is west of the police station. — المخبز غرب مركز الشرطة.",
      "6. The library is north of the supermarket. — المكتبة شمال السوبرماركت.",
      "7. The hospital is west of the restaurant. — المستشفى غرب المطعم.",
      "8. The police station is south of the school. — مركز الشرطة جنوب المدرسة.",
    ],
    glossary: [
      { en: "north", ar: "شمال", pos: "noun" },
      { en: "south", ar: "جنوب", pos: "noun" },
      { en: "east", ar: "شرق", pos: "noun" },
      { en: "west", ar: "غرب", pos: "noun" },
      { en: "map", ar: "خريطة", pos: "noun" },
      { en: "airport", ar: "مطار", pos: "noun" },
      { en: "hospital", ar: "مستشفى", pos: "noun" },
      { en: "restaurant", ar: "مطعم", pos: "noun" },
      { en: "hotel", ar: "فندق", pos: "noun" },
      { en: "pet shop", ar: "متجر الحيوانات الأليفة", pos: "noun" },
      { en: "library", ar: "مكتبة", pos: "noun" },
      { en: "flower shop", ar: "محل الزهور", pos: "noun" },
      { en: "supermarket", ar: "سوبرماركت", pos: "noun" },
      { en: "bakery", ar: "مخبز", pos: "noun" },
      { en: "police station", ar: "مركز الشرطة", pos: "noun" },
    ],
  },
  project: {
    title: "Project: \"Me on the Map\"",
    steps: [
      "Draw a map entitled:",
      "My house",
      "My town/ city",
      "My school",
      "Show the map to your classmates.",
    ],
  },
}

export const module1: Module = withExtras(base, extras)
