import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const out = process.argv[2]
const b = await chromium.launch({ args: ['--autoplay-policy=no-user-gesture-required'] })
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 3, isMobile: true, hasTouch: true })
const p = await ctx.newPage(); p.setDefaultTimeout(15000)
await p.goto('http://localhost:8790/index.html'); await p.waitForTimeout(2000)
await p.screenshot({ path: `${out}/s-home.png` })
await p.evaluate(() => [...document.querySelectorAll('button')].find(b => b.textContent.includes('فهمت'))?.click()); await p.waitForTimeout(500)
await p.evaluate(() => window.scrollTo(0, 420)); await p.waitForTimeout(400)
await p.screenshot({ path: `${out}/s-path.png` })
await p.evaluate(() => document.querySelector('button.node').click()); await p.waitForTimeout(1800)
await p.screenshot({ path: `${out}/s-lesson1.png` })
for (let i = 0; i < 3; i++) { await p.evaluate(() => [...document.querySelectorAll('button')].find(b => /متابعة|تابع/.test(b.textContent))?.click()); await p.waitForTimeout(900) }
await p.screenshot({ path: `${out}/s-lesson2.png` })
await p.goto('http://localhost:8790/index.html'); await p.waitForTimeout(1500)
await p.evaluate(() => [...document.querySelectorAll('.tabbar button, nav button, button')].find(b => b.textContent.trim().endsWith('القواعد'))?.click()); await p.waitForTimeout(900)
await p.screenshot({ path: `${out}/s-grammar.png` })
await p.evaluate(() => [...document.querySelectorAll('button')].find(b => b.textContent.trim().endsWith('امتحانات'))?.click()); await p.waitForTimeout(900)
await p.screenshot({ path: `${out}/s-exams.png` })
await p.evaluate(() => [...document.querySelectorAll('button')].find(b => b.textContent.includes('ابدأ'))?.click()); await p.waitForTimeout(1500)
await p.screenshot({ path: `${out}/s-exam-paper.png` })
await p.goto('http://localhost:8790/index.html'); await p.waitForTimeout(1500)
await p.evaluate(() => [...document.querySelectorAll('button')].find(b => b.textContent.trim().endsWith('الكتاب'))?.click()); await p.waitForTimeout(800)
await p.evaluate(() => [...document.querySelectorAll('button, div')].find(b => b.textContent.trim().startsWith('Unit 1'))?.click()); await p.waitForTimeout(900)
await p.screenshot({ path: `${out}/s-book.png` })
await b.close()
