import type { GrammarExercise } from '../../../engine/types'
import type { ModuleExtras } from './merge'

// Module 4 — Activity Book pages 56–72: Unit 16 (56–58), 17 (59–61), 18 (62–64), 19 (65–67), 20 (68–70),
// Revision 4 (71–72). Every exercise the pages print is here, solved, in the book's order. Items that need the
// recording (or are open personal answers) are left out or turned into items the page's own words can solve.

const fill = (prompt: string, promptAr: string, promptArFull: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, promptAr, promptArFull, options, answer, explainAr })
const mcq = (prompt: string, promptAr: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, promptAr, options, answer, explainAr })
const tf = (prompt: string, promptAr: string, answer: boolean, explainAr: string): GrammarExercise =>
  ({ type: 'truefalse', prompt, promptAr, answer, explainAr })
const build = (answer: string, prompt: string): GrammarExercise => ({ type: 'build', answer, prompt })

// ---------- Unit 18, page 63b: the four words of the box ----------
const u18Box = ['luggage', 'gate', 'flight', 'scale']

// ---------- Unit 18, page 64 (7): the four words of the box ----------
const u18Some = ['something', 'nothing', 'someone', 'anybody']

// ---------- Unit 19, page 67 (9): the three sounds of "-ed" ----------
const edSounds = ['/t/ as in "liked"', '/id/ as in "pointed"', '/d/ as in "played"']
function edItem(verb: string, sound: 0 | 1 | 2, explainAr: string): GrammarExercise {
  return mcq(`Listen and classify. How do we say the "-ed" in "${verb}"?`,
    `صنّف: كيف نلفظ "-ed" في كلمة "${verb}"؟`, edSounds, sound, explainAr)
}

// ---------- Revision 4, page 71 (2): Much / Many ----------
const revMuch = ['rice', 'salt', 'butter', 'tea']
const revMany = ['desks', 'cookies', 'cars', 'children']

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 16 — Food and Drinks (Activity Book pages 56–58) =====================
    u16: {
      workbook: {
        pages: '56–58',
        readings: [
          {
            title: 'What do you want for lunch?',
            paragraphs: [
              'Len: What do you want for lunch?',
              'Kitty: I don’t know.',
              'Len: Well, let’s think about what we have.',
              'Kitty: We have an apple, some eggs, some cheese and some milk.',
              'Len: Hmm. We also have some rice, some bread and some grapes but we don’t have any pasta. Do we have any juice?',
              'Kitty: Yes, we have some orange juice but we don’t have any apple juice.',
              'Len: So how about a cheese sandwich with some tomatoes and a glass of orange juice?',
              'Kitty: And some sweets afterwards?',
              'Len: You can have one sweet, my dear!',
            ],
            paragraphsAr: [
              'لين: ماذا تريدين على الغداء؟',
              'كيتي: لا أعرف.',
              'لين: حسناً، لنفكّر في ما لدينا.',
              'كيتي: لدينا تفاحة، وبعض البيض، وبعض الجبن، وبعض الحليب.',
              'لين: امم. لدينا أيضاً بعض الأرز، وبعض الخبز، وبعض العنب، لكن ليس لدينا أي معكرونة. هل لدينا أي عصير؟',
              'كيتي: نعم، لدينا بعض عصير البرتقال، لكن ليس لدينا أي عصير تفاح.',
              'لين: إذن ما رأيك بشطيرة جبن مع بعض البندورة وكأس من عصير البرتقال؟',
              'كيتي: وبعض الحلوى بعد ذلك؟',
              'لين: يمكنك أن تأكلي قطعة حلوى واحدة يا عزيزتي!',
            ],
            questions: [
              {
                q: '___ asked about lunch.', qAr: '___ سأل عن الغداء.',
                options: ['Len', 'Kitty', 'both'], answer: 0,
                explainAr: 'لين هو الذي سأل في أول سطر: What do you want for lunch?',
              },
              {
                q: 'There is ___ juice.', qAr: 'يوجد عصير ___.',
                options: ['apple', 'orange', 'grapes'], answer: 1,
                explainAr: 'قالت كيتي: we have some orange juice but we don’t have any apple juice. إذن يوجد عصير برتقال فقط.',
              },
              {
                q: 'They don’t have any ___ .', qAr: 'ليس لديهم أي ___.',
                options: ['eggs', 'pasta', 'tomatoes'], answer: 1,
                explainAr: 'قال لين: we don’t have any pasta، أي ليس لديهم معكرونة.',
              },
              {
                q: 'They will make a sandwich with some ___ .', qAr: 'سيصنعان شطيرة مع بعض ___.',
                options: ['eggs / bread', 'cheese / tomatoes', 'milk / cheese'], answer: 1,
                explainAr: 'اقترح لين: a cheese sandwich with some tomatoes، أي شطيرة جبن مع البندورة.',
              },
              {
                q: 'They will have sweets ___ lunch.', qAr: 'سيأكلان الحلوى ___ الغداء.',
                options: ['before', 'after', 'during'], answer: 1,
                explainAr: 'قالت كيتي: some sweets afterwards، وafterwards تعني «بعد ذلك»، أي بعد الغداء.',
              },
            ],
            trueFalse: [
              { statement: 'They will have dinner.', answer: false },
              { statement: 'There are many different foods.', answer: true },
              { statement: 'They don’t have any juice.', answer: false },
              { statement: 'They will make pasta.', answer: false },
            ],
          },
        ],
        exercises: [
          // ---- page 57 (2): Look and say ----
          mcq('Look and say. Picture 1: a hand cuts a tomato into thin round pieces with a knife. Which word is it?',
            'انظر وقل. الصورة 1: يدٌ تقطّع حبّة بندورة بالسكين إلى قطع رقيقة مستديرة. ما الكلمة المناسبة؟',
            ['slice', 'fry', 'peel', 'boil'], 0,
            'slice = يقطّع إلى شرائح. البندورة في الصورة تُقطَّع إلى شرائح رقيقة.'),
          mcq('Look and say. Picture 2: a hand puts butter on a piece of bread with a knife. Which word is it?',
            'انظر وقل. الصورة 2: يدٌ تضع الزبدة على قطعة خبز بالسكين. ما الكلمة المناسبة؟',
            ['boil', 'spread', 'fry', 'peel'], 1,
            'spread = يدهن أو يفرد. نحن ندهن الزبدة على الخبز بالسكين.'),
          mcq('Look and say. Picture 3: a hand takes the skin off an apple with a knife. Which word is it?',
            'انظر وقل. الصورة 3: يدٌ تنزع قشرة تفاحة بالسكين. ما الكلمة المناسبة؟',
            ['mix', 'slice', 'peel', 'spread'], 2,
            'peel = يقشّر، أي ينزع القشرة عن الفاكهة.'),
          mcq('Look and say. Picture 4: two eggs cook in a hot pan. Which word is it?',
            'انظر وقل. الصورة 4: بيضتان تُطهيان في مقلاة ساخنة. ما الكلمة المناسبة؟',
            ['peel', 'mix', 'spread', 'fry'], 3,
            'fry = يقلي. البيض يُقلى في المقلاة.'),

          // ---- page 57 (3): Write — Sana wants to make a cake ----
          mcq('Sana wants to make a cake. "How many eggs does she need?" Choose a good answer.',
            'تريد سناء أن تصنع كعكة. «كم بيضة تحتاج؟» اختر جواباً مناسباً.',
            ['She needs a teaspoon of vanilla.', 'She need three egg.', 'She needs three eggs.', 'She needs 3 cups of flour.'], 2,
            'How many eggs يسأل عن عدد البيض، فنجيب بعدد: She needs three eggs (ويمكن أن يكون العدد غير ثلاثة). انتبه: needs مع she، وeggs بالجمع.'),
          fill('___ does she need? — She needs 3 cups of flour.',
            '___ تحتاج؟ — تحتاج 3 أكواب من الطحين.',
            'كم من الطحين تحتاج؟ — تحتاج 3 أكواب من الطحين.',
            ['How much flour', 'How many flour', 'How much eggs'], 0,
            'الطحين flour لا نعدّه حبّة حبّة، لذلك نسأل عنه بـ How much.'),
          mcq('"How much sugar does she need?" Choose a good answer.',
            '«كم من السكر تحتاج؟» اختر جواباً مناسباً.',
            ['She needs two eggs.', 'She needs a cup of sugar.', 'She needs many sugar.'], 1,
            'السكر لا يُعدّ، فنقيسه بالكوب أو الملعقة: a cup of sugar. ولا نقول many sugar.'),
          fill('___ does she need? — She needs a teaspoon of vanilla.',
            '___ تحتاج؟ — تحتاج ملعقة صغيرة من الفانيليا.',
            'كم من الفانيليا تحتاج؟ — تحتاج ملعقة صغيرة من الفانيليا.',
            ['How many vanilla', 'How much teaspoons', 'How much vanilla'], 2,
            'الفانيليا vanilla لا تُعدّ، فنسأل عنها بـ How much.'),

          // ---- page 57 (4): Listen and match (solved with the page's words) ----
          fill('Chop the tomatoes ___.', 'قطّع البندورة ___.', 'قطّع البندورة بالسكين.',
            ['in the oven', 'with a knife', 'in the fridge'], 1,
            'نقطّع البندورة بالسكين. هذا هو المثال المحلول في الكتاب.'),
          fill('Spread ___ on the bread.', 'اِدهن ___ على الخبز.', 'اِدهن الجبن على الخبز.',
            ['the juice', 'the potatoes', 'the cheese'], 2,
            'ندهن الجبن على الخبز. العصير نشربه ولا ندهنه.'),
          fill('Put the juice ___.', 'ضع العصير ___.', 'ضع العصير في البرّاد.',
            ['in the fridge', 'in the oven', 'on the bread'], 0,
            'نضع العصير في البرّاد ليبقى بارداً، لا في الفرن.'),
          fill('Bake the dough ___.', 'اخبز العجين ___.', 'اخبز العجين في الفرن.',
            ['with a knife', 'in the oven', 'in the fridge'], 1,
            'bake = يخبز، والخَبز يكون في الفرن.'),

          // ---- page 57 (5): How much / How many ----
          fill('___ sugar do you put in your tea?', '___ من السكر تضع في شايك؟', 'كم من السكر تضع في شايك؟',
            ['How much', 'How many', 'Many'], 0,
            'السكر لا يُعدّ، فنستعمل How much.'),
          fill('___ onions did she cut?', '___ بصلة قطّعت؟', 'كم بصلة قطّعت؟',
            ['How much', 'How many', 'Much'], 1,
            'onions جمع ويمكن عدّه (بصلة، بصلتان...)، فنستعمل How many.'),
          fill('___ chocolate was there in that box?', '___ من الشوكولا كان في تلك العلبة؟', 'كم من الشوكولا كان في تلك العلبة؟',
            ['How many', 'Many', 'How much'], 2,
            'chocolate هنا لا تُعدّ، والفعل was مفرد، فنستعمل How much.'),
          fill('___ biscuits did you eat?', '___ قطعة بسكويت أكلت؟', 'كم قطعة بسكويت أكلت؟',
            ['How many', 'How much', 'Much'], 0,
            'biscuits جمع ويمكن عدّه، فنستعمل How many.'),

          // ---- page 57 (6): Listen and put the sentences in the correct order (the first steps) ----
          mcq('We make a salad. Which step comes first?', 'نحضّر سلطة. أيّ خطوة تأتي أولاً؟',
            ['Mix the vegetables together.', 'Cut the tomatoes, cucumbers and lettuce.', 'Add salt and oil.', 'Wash the vegetables.'], 3,
            'أولاً نغسل الخضار (Wash the vegetables) قبل أن نقطّعها.'),
          mcq('We washed the vegetables. Which step comes next?', 'غسلنا الخضار. أيّ خطوة تأتي بعدها؟',
            ['Add salt and oil.', 'Cut the tomatoes, cucumbers and lettuce.', 'Mix the vegetables together.'], 1,
            'بعد الغسل نقطّع البندورة والخيار والخسّ، ثم نخلطها ونضيف الملح والزيت.'),

          // ---- page 58 (7): Ask and answer ----
          fill('How ___ bananas are there? — There are five bananas.', 'كم ___ موزة هناك؟ — هناك خمس موزات.', 'كم موزة هناك؟ — هناك خمس موزات.',
            ['much', 'many', 'any'], 1,
            'bananas جمع يُعدّ، فنقول How many.'),
          fill('How much sugar is there? — There ___ some sugar.', 'كم من السكر هناك؟ — ___ بعض السكر.', 'كم من السكر هناك؟ — يوجد بعض السكر.',
            ['is', 'are', 'am'], 0,
            'sugar لا يُعدّ، ومعه نستعمل is: There is some sugar.'),
          fill('How ___ butter is there? — There is some butter.', 'كم ___ من الزبدة هناك؟ — يوجد بعض الزبدة.', 'كم من الزبدة هناك؟ — يوجد بعض الزبدة.',
            ['many', 'much', 'any'], 1,
            'butter لا تُعدّ، فنسأل بـ How much.'),
          fill('How many oranges are there? — There ___ three oranges.', 'كم برتقالة هناك؟ — ___ ثلاث برتقالات.', 'كم برتقالة هناك؟ — هناك ثلاث برتقالات.',
            ['is', 'are', 'be'], 1,
            'oranges جمع، فنستعمل are: There are three oranges.'),

          // ---- page 58 (8): Put the words in the right order ----
          build('How much water do you drink every day?', 'كم من الماء تشرب كل يوم؟'),
          build('How much milk do you like in your coffee?', 'كم من الحليب تحبّ في قهوتك؟'),
          build('How many carrots did she cut?', 'كم جزرة قطّعت؟'),
          build('How much butter does he use?', 'كم من الزبدة يستعمل؟'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'What is your favourite sandwich? How do you make it?',
          topicAr: 'ما شطيرتك المفضّلة؟ كيف تحضّرها؟',
          words: 40,
          points: ['My favourite sandwich is …', 'First, …', 'Then, …', 'After that, …', 'Finally, …'],
          pointsAr: ['شطيرتي المفضّلة هي …', 'أولاً، …', 'ثم، …', 'بعد ذلك، …', 'أخيراً، …'],
          plan: [
            { en: 'Say what your favourite sandwich is.', ar: 'قل ما شطيرتك المفضّلة.' },
            { en: 'Tell the steps in order with First, Then, After that and Finally.', ar: 'اذكر الخطوات بالترتيب باستعمال: First ثم Then ثم After that ثم Finally.' },
            { en: 'End with how you feel about it.', ar: 'اختم بجملة عن رأيك فيها.' },
          ],
          phrases: [
            { en: 'a cheese sandwich', ar: 'شطيرة جبن' },
            { en: 'some bread', ar: 'بعض الخبز' },
            { en: 'spread', ar: 'يدهن' },
            { en: 'slice', ar: 'يقطّع إلى شرائح' },
            { en: 'some tomatoes', ar: 'بعض البندورة' },
            { en: 'a glass of orange juice', ar: 'كأس من عصير البرتقال' },
            { en: 'First, … Then, … After that, … Finally, …', ar: 'أولاً… ثم… بعد ذلك… أخيراً…' },
          ],
          model: 'My favourite sandwich is a cheese sandwich. First, I take two pieces of bread. Then, I spread some cheese on the bread. After that, I slice some tomatoes and put them on the cheese. Finally, I eat my sandwich with a glass of orange juice. It is delicious!',
          modelAr: 'شطيرتي المفضّلة هي شطيرة الجبن. أولاً، آخذ قطعتين من الخبز. ثم أدهن بعض الجبن على الخبز. بعد ذلك، أقطّع بعض البندورة إلى شرائح وأضعها فوق الجبن. أخيراً، آكل شطيرتي مع كأس من عصير البرتقال. إنها لذيذة!',
          checklistAr: [
            'ذكرتُ اسم شطيرتي المفضّلة في أول جملة.',
            'رتّبتُ الخطوات بـ First وThen وAfter that وFinally.',
            'استعملتُ some مع الأطعمة مثل some cheese وsome tomatoes.',
            'استعملتُ أفعال المطبخ مثل spread وslice.',
            'بدأتُ كل جملة بحرف كبير وختمتها بنقطة.',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write a paragraph about how to make a cake.',
          topicAr: 'اكتب فقرة عن طريقة صنع كعكة.',
          words: 40,
          points: ['First …'],
          pointsAr: ['أولاً …'],
          plan: [
            { en: 'Say what you need to make the cake.', ar: 'اذكر ما تحتاجه لصنع الكعكة.' },
            { en: 'Tell the steps in order, starting with First.', ar: 'اذكر الخطوات بالترتيب، وابدأ بـ First.' },
            { en: 'End with the cake in the oven and ready to eat.', ar: 'اختم بخَبز الكعكة في الفرن وأنها جاهزة.' },
          ],
          phrases: [
            { en: 'eggs', ar: 'بيض' },
            { en: '3 cups of flour', ar: '3 أكواب من الطحين' },
            { en: 'some sugar', ar: 'بعض السكر' },
            { en: 'a teaspoon of vanilla', ar: 'ملعقة صغيرة من الفانيليا' },
            { en: 'mix', ar: 'يخلط' },
            { en: 'bake in the oven', ar: 'يخبز في الفرن' },
            { en: 'After that / Finally', ar: 'بعد ذلك / أخيراً' },
          ],
          model: 'To make a cake, we need eggs, flour, sugar, milk and vanilla. First, we mix three eggs and some sugar. Then, we add 3 cups of flour, some milk and a teaspoon of vanilla. After that, we mix them together. Finally, we bake the cake in the oven. It is delicious!',
          modelAr: 'لكي نصنع كعكة، نحتاج إلى البيض والطحين والسكر والحليب والفانيليا. أولاً، نخلط ثلاث بيضات وبعض السكر. ثم نضيف 3 أكواب من الطحين وبعض الحليب وملعقة صغيرة من الفانيليا. بعد ذلك، نخلطها معاً. أخيراً، نخبز الكعكة في الفرن. إنها لذيذة!',
          checklistAr: [
            'ذكرتُ المكوّنات التي نحتاجها.',
            'بدأتُ الخطوات بـ First ورتّبتها بـ Then وAfter that وFinally.',
            'استعملتُ الكميات بشكل صحيح مثل a cup of و a teaspoon of.',
            'استعملتُ أفعالاً مثل mix وadd وbake.',
            'كتبتُ جملاً قصيرة وواضحة.',
          ],
        },
      ],
      translations: [
        { en: 'What do you want for lunch?', ar: 'ماذا تريد على الغداء؟' },
        { en: 'Well, let’s think about what we have.', ar: 'حسناً، لنفكّر في ما لدينا.' },
        { en: 'We have an apple, some eggs, some cheese and some milk.', ar: 'لدينا تفاحة، وبعض البيض، وبعض الجبن، وبعض الحليب.' },
        { en: 'Do we have any juice?', ar: 'هل لدينا أي عصير؟' },
        { en: 'You can have one sweet, my dear!', ar: 'يمكنك أن تأكل قطعة حلوى واحدة يا عزيزي!' },
        { en: 'Sana wants to make a cake.', ar: 'تريد سناء أن تصنع كعكة.' },
        { en: 'How much sugar does she need?', ar: 'كم من السكر تحتاج؟' },
        { en: 'Mix the vegetables together.', ar: 'اخلط الخضار معاً.' },
        { en: 'There is some honey on the table.', ar: 'يوجد بعض العسل على الطاولة.' },
        { en: 'There isn’t any butter.', ar: 'لا يوجد أي زبدة.' },
      ],
    },

    // ===================== UNIT 17 — Farming (Activity Book pages 59–61) =====================
    u17: {
      workbook: {
        pages: '59–61',
        readings: [
          {
            title: 'Bees',
            paragraphs: [
              'Bees make honey. They live in hives. A hive has only one queen, many worker bees, drones and male bees. It usually has around 50,000 bees. Worker bees go from one flower to another, collecting nectar. When they sip the nectar, they store it in their bodies in order to make honey when they return to the hive. In one trip, a bee visits 50 to 100 flowers. Bees have 5 eyes and 6 legs. It takes a great effort and hard work from bees to make the honey we enjoy.',
            ],
            paragraphsAr: [
              'النحل يصنع العسل. ويعيش في خلايا. في الخلية ملكة واحدة فقط، وكثير من النحل العامل، وذكور النحل. وفي الخلية عادةً نحو 50,000 نحلة. ينتقل النحل العامل من زهرة إلى أخرى ليجمع الرحيق. وعندما يمتصّ الرحيق، يخزّنه في جسمه لكي يصنع العسل عندما يعود إلى الخلية. في رحلة واحدة تزور النحلة من 50 إلى 100 زهرة. للنحلة 5 عيون و6 أرجل. يبذل النحل جهداً كبيراً وعملاً شاقاً ليصنع العسل الذي نستمتع به.',
            ],
            questions: [
              {
                q: 'Match the word with the definition: "The biggest female bee."', qAr: 'صِل الكلمة بالتعريف: «أكبر نحلة أنثى».',
                options: ['a queen bee', 'honey', 'hive', 'nectar'], answer: 0,
                explainAr: 'الملكة a queen bee هي أكبر أنثى في الخلية، وفي الخلية ملكة واحدة فقط. (هذا هو المثال المحلول في الكتاب.)',
              },
              {
                q: 'Match the word with the definition: "The sweet liquid made by bees."', qAr: 'صِل الكلمة بالتعريف: «السائل الحلو الذي يصنعه النحل».',
                options: ['nectar', 'honey', 'sip', 'hive'], answer: 1,
                explainAr: 'العسل honey يصنعه النحل. أمّا الرحيق nectar فموجود داخل الزهرة.',
              },
              {
                q: 'Match the word with the definition: "The place where bees live."', qAr: 'صِل الكلمة بالتعريف: «المكان الذي يعيش فيه النحل».',
                options: ['honey', 'a queen bee', 'hive', 'sip'], answer: 2,
                explainAr: 'الخلية hive هي بيت النحل: They live in hives.',
              },
              {
                q: 'Match the word with the definition: "To get liquid from flowers."', qAr: 'صِل الكلمة بالتعريف: «أن يأخذ السائل من الأزهار».',
                options: ['hive', 'nectar', 'honey', 'sip'], answer: 3,
                explainAr: 'sip فعل معناه يرتشف أو يمتصّ، والنحل يمتصّ الرحيق من الأزهار.',
              },
              {
                q: 'Match the word with the definition: "The sweet liquid inside the flower."', qAr: 'صِل الكلمة بالتعريف: «السائل الحلو داخل الزهرة».',
                options: ['nectar', 'honey', 'hive', 'a queen bee'], answer: 0,
                explainAr: 'الرحيق nectar هو السائل الحلو داخل الزهرة، ومنه يصنع النحل العسل.',
              },
            ],
            trueFalse: [
              { statement: 'There are about 50,000 drones in a hive.', answer: false },
              { statement: 'The queen collects the nectar and stores it in its body.', answer: false },
              { statement: 'Honey is made from nectar.', answer: true },
              { statement: 'Bees have five eyes and six legs.', answer: true },
              { statement: 'Bees work very hard to make honey.', answer: true },
            ],
          },
        ],
        exercises: [
          // ---- page 60 (2): Ask and answer ----
          fill('Where do bees live? — Bees live in a ___.', 'أين يعيش النحل؟ — يعيش النحل في ___.', 'أين يعيش النحل؟ — يعيش النحل في خلية.',
            ['hive', 'honey', 'flower'], 0,
            'النص يقول: They live in hives. الخلية hive هي بيت النحل.'),
          fill('What do bees make? — Bees make ___.', 'ماذا يصنع النحل؟ — يصنع النحل ___.', 'ماذا يصنع النحل؟ — يصنع النحل العسل.',
            ['nectar', 'honey', 'hives'], 1,
            'أول جملة في النص: Bees make honey. النحل يأخذ الرحيق ويصنع منه العسل.'),

          // ---- page 60 (4): Listen and underline the correct word (the grammar and the story decide) ----
          fill('One day, a man went to the farm in order to ___ the beautiful trees.',
            'في أحد الأيام، ذهب رجل إلى المزرعة لكي ___ الأشجار الجميلة.',
            'في أحد الأيام، ذهب رجل إلى المزرعة لكي يرى الأشجار الجميلة.',
            ['saw', 'see', 'seeing'], 1,
            'بعد in order to يأتي الفعل بشكله الأصلي دائماً: see، وليس saw.'),
          fill('While he was walking in the farm, he saw lots of ___ flying around their hive.',
            'بينما كان يمشي في المزرعة، رأى كثيراً من ___ تطير حول الخلية.',
            'بينما كان يمشي في المزرعة، رأى كثيراً من النحل يطير حول الخلية.',
            ['bees', 'birds', 'cows'], 0,
            'الخلية hive بيت النحل، وفي آخر القصة لسعه النحل، إذن رأى النحل bees.'),
          fill('He saw lots of bees flying around their ___.',
            'رأى كثيراً من النحل يطير حول ___.',
            'رأى كثيراً من النحل يطير حول خليّته.',
            ['house', 'farm', 'hive'], 2,
            'بيت النحل اسمه hive (خلية)، وفي الجملة التالية: He went to the hive.'),
          fill('He went to the hive in order to ___ some honey.',
            'ذهب إلى الخلية لكي ___ بعض العسل.',
            'ذهب إلى الخلية لكي يأخذ بعض العسل.',
            ['took', 'take', 'takes'], 1,
            'بعد in order to يأتي الفعل بشكله الأصلي: take.'),
          fill('When he tried to take the honey out of the hive, the bees ___ him badly.',
            'عندما حاول أن يُخرج العسل من الخلية، ___ النحل بشدّة.',
            'عندما حاول أن يُخرج العسل من الخلية، لسعه النحل بشدّة.',
            ['sting', 'stung', 'stings'], 1,
            'القصة في الماضي (went, tried)، فنستعمل الماضي stung (لسع).'),
          fill('He quickly ran away crying: "I\'m not going to ___ what isn\'t mine."',
            'هرب بسرعة وهو يبكي: «لن ___ ما ليس لي».',
            'هرب بسرعة وهو يبكي: «لن آخذ ما ليس لي».',
            ['take', 'give', 'took'], 0,
            'أخذ العسل الذي ليس له فلُسع، فتعلّم الدرس: لن آخذ take ما ليس لي. وبعد going to يأتي الفعل الأصلي.'),

          // ---- page 61 (5): Read and choose ----
          fill('Bees fly thousands of miles in order to ___ for flowers.',
            'يطير النحل آلاف الأميال لكي ___ عن الأزهار.',
            'يطير النحل آلاف الأميال لكي يبحث عن الأزهار.',
            ['searched', 'search', 'searching'], 1,
            'بعد in order to نستعمل الفعل الأصلي: search.'),
          fill('Bees move their wings to ___ the hive cool.',
            'يحرّك النحل أجنحته لكي ___ الخلية باردة.',
            'يحرّك النحل أجنحته لكي يجعل الخلية باردة.',
            ['made', 'makes', 'make'], 2,
            'بعد to (بمعنى لكي) نستعمل الفعل الأصلي: make.'),
          fill('Ants pick wheat in order to ___ them in winter.',
            'يجمع النمل القمح لكي ___ في الشتاء.',
            'يجمع النمل القمح لكي يأكله في الشتاء.',
            ['eat', 'ate', 'eats'], 0,
            'بعد in order to نستعمل الفعل الأصلي: eat، وليس الماضي ate.'),
          fill('People go to the supermarket to ___ fruit.',
            'يذهب الناس إلى السوبرماركت لكي ___ الفاكهة.',
            'يذهب الناس إلى السوبرماركت لكي يشتروا الفاكهة.',
            ['bought', 'buys', 'buy'], 2,
            'بعد to (بمعنى لكي) نستعمل الفعل الأصلي: buy.'),

          // ---- page 61 (6): Classify — Wild / Domestic ----
          tf('Classify: A cow is a domestic animal.', 'صنّف: البقرة حيوان أليف.', true,
            'البقرة يربّيها الفلاح في المزرعة، فهي حيوان أليف domestic.'),
          tf('Classify: A tiger is a domestic animal.', 'صنّف: النمر حيوان أليف.', false,
            'النمر يعيش في الغابة ولا يربّيه الناس، فهو حيوان برّي wild.'),
          tf('Classify: A chicken is a wild animal.', 'صنّف: الدجاجة حيوان برّي.', false,
            'الدجاجة يربّيها الناس في المزرعة، فهي حيوان أليف domestic.'),
          tf('Classify: A sheep is a domestic animal.', 'صنّف: الخروف حيوان أليف.', true,
            'الخروف يعيش في المزرعة مع الفلاح، فهو حيوان أليف domestic.'),
          tf('Classify: A wolf is a wild animal.', 'صنّف: الذئب حيوان برّي.', true,
            'الذئب يعيش في الغابة بعيداً عن الناس، فهو حيوان برّي wild.'),
          tf('Classify: A rabbit is a wild animal.', 'صنّف: الأرنب حيوان برّي.', true,
            'في جدول الكتاب يوضع الأرنب مع الحيوانات البرّية، لأنه يعيش حرّاً في الحقول. (بعض الناس يربّون الأرانب في البيوت أيضاً.)'),
          tf('Classify: A fox is a domestic animal.', 'صنّف: الثعلب حيوان أليف.', false,
            'الثعلب يعيش حرّاً في الغابة، فهو حيوان برّي wild.'),
          tf('Classify: A horse is a domestic animal.', 'صنّف: الحصان حيوان أليف.', true,
            'الحصان يربّيه الناس ويعمل معهم، فهو حيوان أليف domestic.'),
        ],
      },
      compositions: [
        {
          source: 'workbook',
          topic: 'Complete the paragraph.',
          topicAr: 'أكمل الفقرة: أحمد فلّاح. يستيقظ باكراً في الصباح. ثم، …',
          words: 40,
          points: ['Ahmad is a farmer. He wakes up early in the morning. Then, …'],
          pointsAr: ['أحمد فلّاح. يستيقظ باكراً في الصباح. ثم، …'],
          plan: [
            { en: 'Copy the beginning: Ahmad is a farmer. He wakes up early in the morning.', ar: 'انسخ البداية: أحمد فلّاح. يستيقظ باكراً في الصباح.' },
            { en: 'Tell what he does on the farm, in order: Then, After that…', ar: 'اذكر ما يفعله في المزرعة بالترتيب: Then ثم After that…' },
            { en: 'Use in order to / to once to say why he does something.', ar: 'استعمل in order to أو to مرة واحدة لتقول لماذا يفعل شيئاً.' },
            { en: 'End with how hard he works.', ar: 'اختم بجملة عن تعبه وعمله الكثير.' },
          ],
          phrases: [
            { en: 'feed the cows, sheep and chickens', ar: 'يُطعم الأبقار والخراف والدجاج' },
            { en: 'plant seeds', ar: 'يزرع البذور' },
            { en: 'grow crops', ar: 'يزرع المحاصيل' },
            { en: 'keep bees', ar: 'يربّي النحل' },
            { en: 'in order to', ar: 'لكي' },
            { en: 'sell the food', ar: 'يبيع الطعام' },
            { en: 'work very hard', ar: 'يعمل بجدّ كبير' },
          ],
          model: 'Ahmad is a farmer. He wakes up early in the morning. Then, he feeds his cows, sheep and chickens. After that, he plants seeds in order to grow crops for food. He also keeps bees to get honey. In the evening, he sells the food at the market. He works very hard.',
          modelAr: 'أحمد فلّاح. يستيقظ باكراً في الصباح. ثم يُطعم أبقاره وخرافه ودجاجه. بعد ذلك، يزرع البذور لكي تنمو المحاصيل للطعام. ويربّي النحل أيضاً ليحصل على العسل. وفي المساء يبيع الطعام في السوق. إنه يعمل بجدّ كبير.',
          checklistAr: [
            'بدأتُ بجملتَي الكتاب كما هما.',
            'رتّبتُ الأعمال بـ Then وAfter that.',
            'استعملتُ in order to أو to وبعدها فعل أصلي.',
            'أضفتُ s إلى الفعل مع he (feeds, plants, keeps).',
            'استعملتُ كلمات المزرعة: cows, sheep, crops, bees.',
          ],
        },
      ],
      translations: [
        { en: 'They live in hives.', ar: 'يعيش النحل في خلايا.' },
        { en: 'Worker bees go from one flower to another, collecting nectar.', ar: 'ينتقل النحل العامل من زهرة إلى أخرى ليجمع الرحيق.' },
        { en: 'In one trip, a bee visits 50 to 100 flowers.', ar: 'في رحلة واحدة، تزور النحلة من 50 إلى 100 زهرة.' },
        { en: 'Honey is made from nectar.', ar: 'يُصنع العسل من الرحيق.' },
        { en: 'Bees work very hard to make honey.', ar: 'يعمل النحل بجدّ كبير ليصنع العسل.' },
        { en: 'Bees fly thousands of miles in order to search for flowers.', ar: 'يطير النحل آلاف الأميال لكي يبحث عن الأزهار.' },
        { en: 'Ahmad is a farmer.', ar: 'أحمد فلّاح.' },
        { en: 'He wakes up early in the morning.', ar: 'يستيقظ باكراً في الصباح.' },
        { en: 'Many families can live on a farm.', ar: 'تستطيع عائلات كثيرة أن تعيش في مزرعة.' },
        { en: 'There are two main types of farming: crops and animals.', ar: 'هناك نوعان رئيسيان من الزراعة: المحاصيل والحيوانات.' },
      ],
    },

    // ===================== UNIT 18 — At the Airport (Activity Book pages 62–64) =====================
    u18: {
      workbook: {
        pages: '62–64',
        readings: [
          {
            title: 'At the check-in',
            paragraphs: [
              'Mr. Scott is going to travel by plane. He is at the airport and he is talking to the check-in assistant now.',
              'The Assistant: Good morning sir. May I see your passport and your airline ticket?',
              'Mr. Scott: Good morning madam. Here you are.',
              'The Assistant: How many bags are you checking in?',
              'Mr. Scott: Only this one.',
              'The Assistant: Can you put it on the scale, please?',
              'Mr. Scott: Yes, sure.',
              'The Assistant: Do you have any hand luggage to take with you on the plane?',
              'Mr. Scott: No, I don\'t have any. Just my mobile phone.',
              'The Assistant: Ok, here is your passport and your boarding pass. Your flight leaves from gate 7B at 10:00 am.',
              'Mr. Scott: Thank you very much. Shall I go through the airport security now?',
              'The Assistant: Sure. Have a nice flight sir.',
            ],
            paragraphsAr: [
              'السيد سكوت سيسافر بالطائرة. هو في المطار، ويتحدّث الآن مع الموظفة في مكتب تسجيل المسافرين.',
              'الموظفة: صباح الخير يا سيدي. هل يمكنني أن أرى جواز سفرك وتذكرة الطيران؟',
              'السيد سكوت: صباح الخير يا سيدتي. تفضّلي.',
              'الموظفة: كم حقيبة ستشحن؟',
              'السيد سكوت: هذه فقط.',
              'الموظفة: هل يمكنك أن تضعها على الميزان، من فضلك؟',
              'السيد سكوت: نعم، بالتأكيد.',
              'الموظفة: هل معك حقيبة يد تأخذها معك إلى الطائرة؟',
              'السيد سكوت: لا، ليس معي. فقط هاتفي المحمول.',
              'الموظفة: حسناً، هذا جواز سفرك وبطاقة الصعود إلى الطائرة. رحلتك تنطلق من البوابة 7B الساعة العاشرة صباحاً.',
              'السيد سكوت: شكراً جزيلاً. هل أمرّ الآن عبر التفتيش الأمني في المطار؟',
              'الموظفة: بالتأكيد. رحلة سعيدة يا سيدي.',
            ],
            questions: [
              {
                q: 'Mr. Scott is ___ .', qAr: 'السيد سكوت ___.',
                options: ['on a plane', 'outside the airport', 'at the check-in'], answer: 2,
                explainAr: 'النص يقول إنه يتحدّث مع موظفة تسجيل المسافرين (check-in assistant)، إذن هو عند مكتب التسجيل.',
              },
              {
                q: 'He has got ___ .', qAr: 'معه ___.',
                options: ['no bag', 'one bag', 'two bags'], answer: 1,
                explainAr: 'سألته: How many bags؟ فقال: Only this one، أي حقيبة واحدة فقط.',
              },
              {
                q: 'The assistant asked him for his ___ .', qAr: 'طلبت منه الموظفة ___.',
                options: ['passport', 'boarding pass', 'gate number'], answer: 0,
                explainAr: 'قالت: May I see your passport؟ أمّا بطاقة الصعود فهي التي أعطته إيّاها في النهاية.',
              },
              {
                q: 'After the check in he is going to the ___ .', qAr: 'بعد مكتب التسجيل سيذهب إلى ___.',
                options: ['departure hall', 'airport security', 'plane'], answer: 1,
                explainAr: 'سأل: Shall I go through the airport security now؟ فقالت: Sure. إذن سيذهب إلى التفتيش الأمني.',
              },
              {
                q: 'Match the definition with the word: "The place where people get on a plane."', qAr: 'صِل التعريف بالكلمة: «المكان الذي يصعد منه الناس إلى الطائرة».',
                options: u18Box, answer: 1,
                explainAr: 'البوابة gate هي المكان الذي نمرّ منه لنصعد إلى الطائرة، مثل: gate 7B.',
              },
              {
                q: 'Match the definition with the word: "A journey in a plane."', qAr: 'صِل التعريف بالكلمة: «رحلة بالطائرة».',
                options: u18Box, answer: 2,
                explainAr: 'flight تعني رحلة جوية، مثل: Have a nice flight.',
              },
              {
                q: 'Match the definition with the word: "A machine for weighing people or things."', qAr: 'صِل التعريف بالكلمة: «آلة لوزن الناس أو الأشياء».',
                options: u18Box, answer: 3,
                explainAr: 'scale هو الميزان، وعليه نضع الحقيبة لنعرف وزنها.',
              },
              {
                q: 'Match the definition with the word: "The bags that you carry when you are travelling."', qAr: 'صِل التعريف بالكلمة: «الحقائب التي تحملها وأنت مسافر».',
                options: u18Box, answer: 0,
                explainAr: 'luggage تعني الأمتعة أو حقائب السفر، مثل: hand luggage (حقيبة اليد).',
              },
            ],
          },
        ],
        exercises: [
          // ---- page 63 (2): Classify — At the airport / On the plane ----
          tf('"Make sure to weigh your luggage." — We do this at the airport.', '«تأكّد من وزن أمتعتك.» — نفعل هذا في المطار.', true,
            'نزن الحقائب على الميزان عند مكتب التسجيل في المطار. (هذا هو المثال المحلول في الكتاب.)'),
          tf('"You have to put your seat belt on." — We do this at the airport.', '«يجب أن تضع حزام الأمان.» — نفعل هذا في المطار.', false,
            'حزام الأمان seat belt نضعه في الطائرة on the plane، لا في المطار.'),
          tf('"You could ask the flight attendant for help." — We do this on the plane.', '«يمكنك أن تطلب المساعدة من المضيف.» — نفعل هذا في الطائرة.', true,
            'المضيف flight attendant يعمل داخل الطائرة ويساعد المسافرين.'),
          tf('"You should know where your boarding gate is." — We do this on the plane.', '«يجب أن تعرف أين بوابة الصعود.» — نفعل هذا في الطائرة.', false,
            'نبحث عن البوابة gate في المطار قبل أن نصعد إلى الطائرة.'),
          tf('"Keep your boarding pass in your hand." — We do this at the airport.', '«أبقِ بطاقة الصعود في يدك.» — نفعل هذا في المطار.', true,
            'نحتاج بطاقة الصعود boarding pass في المطار عند البوابة.'),
          tf('"Don\'t forget to put your mobile on the flight mode." — We do this on the plane.', '«لا تنسَ أن تضع هاتفك على وضع الطيران.» — نفعل هذا في الطائرة.', true,
            'وضع الطيران flight mode نشغّله في الهاتف ونحن داخل الطائرة.'),

          // ---- page 63 (3): Look and give your friend an advice ----
          fill('Look and give your friend an advice: you ___ arrive at the airport early.',
            'انظر وقدّم نصيحة لصديقك: ___ أن تصل إلى المطار باكراً.',
            'انظر وقدّم نصيحة لصديقك: ينبغي أن تصل إلى المطار باكراً.',
            ['should', 'don\'t', 'shouldn\'t'], 0,
            'نستعمل should لنعطي نصيحة جيدة: you should = ينبغي عليك.'),

          // ---- page 63 (4): Match ----
          fill('You weigh your luggage ___.', 'تزن أمتعتك ___.', 'تزن أمتعتك عند مكتب التسجيل.',
            ['from the ticket office', 'at the check-in', 'on the plane'], 1,
            'نضع الحقيبة على الميزان عند مكتب التسجيل check-in.'),
          fill('You wait for your flight ___.', 'تنتظر رحلتك ___.', 'تنتظر رحلتك في صالة المغادرة.',
            ['at the airport security', 'on the plane', 'at the departure hall'], 2,
            'ننتظر موعد الرحلة في صالة المغادرة departure hall.'),
          fill('You put on your seat belt ___.', 'تضع حزام الأمان ___.', 'تضع حزام الأمان في الطائرة.',
            ['on the plane', 'at the check-in', 'from the ticket office'], 0,
            'حزام الأمان موجود في مقعد الطائرة، فنضعه on the plane.'),
          fill('You buy the ticket ___.', 'تشتري التذكرة ___.', 'تشتري التذكرة من مكتب التذاكر.',
            ['at the departure hall', 'from the ticket office', 'at the airport security'], 1,
            'نشتري التذكرة من مكتب التذاكر ticket office.'),
          fill('You go through a scanner ___.', 'تمرّ عبر جهاز الفحص ___.', 'تمرّ عبر جهاز الفحص عند التفتيش الأمني في المطار.',
            ['at the check-in', 'on the plane', 'at the airport security'], 2,
            'جهاز الفحص scanner موجود عند التفتيش الأمني airport security.'),

          // ---- page 64 (6): Listen and choose the correct word ----
          fill('Tomorrow, I will meet ___ at the airport. He is an old friend.',
            'غداً سألتقي ___ في المطار. إنه صديق قديم.',
            'غداً سألتقي شخصاً في المطار. إنه صديق قديم.',
            ['anyone', 'someone', 'something'], 1,
            'نتكلّم عن شخص (صديق قديم) في جملة مثبتة، فنقول someone. وكلمة somebody في الكتاب لها المعنى نفسه وصحيحة أيضاً.'),
          fill('We will go home together. ___ in my family will be happy.',
            'سنذهب إلى البيت معاً. ___ في عائلتي سيكون سعيداً.',
            'سنذهب إلى البيت معاً. الجميع في عائلتي سيكون سعيداً.',
            ['Something', 'Anything', 'Everybody'], 2,
            'نتكلّم عن كل أفراد العائلة، فنقول Everybody. وكلمة Everyone في الكتاب لها المعنى نفسه وصحيحة أيضاً.'),
          fill('In fact, they haven\'t met ___ of my old friends before.',
            'في الحقيقة، لم يلتقوا ___ من أصدقائي القدامى من قبل.',
            'في الحقيقة، لم يلتقوا أحداً من أصدقائي القدامى من قبل.',
            ['anyone', 'someone', 'everything'], 0,
            'الجملة منفية (haven\'t)، ومع النفي نستعمل anyone.'),
          fill('We have ___ to do at home. So we will go somewhere to have lunch.',
            'ليس لدينا ___ نفعله في البيت. لذلك سنذهب إلى مكان ما لنتناول الغداء.',
            'ليس لدينا شيء نفعله في البيت. لذلك سنذهب إلى مكان ما لنتناول الغداء.',
            ['something', 'nothing', 'anything'], 1,
            'سيخرجون من البيت (So we will go somewhere)، لأنه لا يوجد شيء يفعلونه في البيت: nothing.'),
          fill('So we will go ___ to have lunch and get a lovely time.',
            'لذلك سنذهب إلى ___ لنتناول الغداء ونقضي وقتاً جميلاً.',
            'لذلك سنذهب إلى مكان ما لنتناول الغداء ونقضي وقتاً جميلاً.',
            ['anywhere', 'somewhere', 'anything'], 1,
            'الجملة مثبتة، فنقول somewhere (مكان ما). أمّا anywhere فللسؤال والنفي.'),

          // ---- page 64 (7): Fill in the spaces with the words from the box ----
          fill('If you don\'t know where to go, ask ___ over there.',
            'إذا كنت لا تعرف إلى أين تذهب، اسأل ___ هناك.',
            'إذا كنت لا تعرف إلى أين تذهب، اسأل شخصاً هناك.',
            u18Some, 2,
            'نسأل شخصاً، لا شيئاً، فنقول someone.'),
          fill('Does ___ play football well?', 'هل ___ يلعب كرة القدم جيداً؟', 'هل يوجد أحد يلعب كرة القدم جيداً؟',
            u18Some, 3,
            'في السؤال نستعمل anybody (أيّ أحد).'),
          fill('I found ___ under my desk.', 'وجدتُ ___ تحت طاولتي.', 'وجدتُ شيئاً تحت طاولتي.',
            u18Some, 0,
            'وجدتُ شيئاً (شيء، لا شخص) في جملة مثبتة: something.'),
          fill('I can buy ___ . I don\'t have money.', 'أستطيع أن أشتري ___. ليس معي مال.', 'لا أستطيع أن أشتري شيئاً. ليس معي مال.',
            u18Some, 1,
            'ليس معه مال، فلا يستطيع شراء أي شيء: nothing (لا شيء).'),
        ],
      },
      compositions: [
        {
          source: 'workbook',
          topic: 'Write about what you do at the airport.',
          topicAr: 'اكتب عمّا تفعله في المطار.',
          words: 40,
          plan: [
            { en: 'Start at the check-in: your passport, your ticket and your luggage.', ar: 'ابدأ بمكتب التسجيل: جواز السفر والتذكرة والأمتعة.' },
            { en: 'Then the airport security and the departure hall.', ar: 'ثم التفتيش الأمني وصالة المغادرة.' },
            { en: 'End at the gate and on the plane.', ar: 'اختم بالبوابة ثم الطائرة.' },
          ],
          phrases: [
            { en: 'the check-in', ar: 'مكتب تسجيل المسافرين' },
            { en: 'passport', ar: 'جواز السفر' },
            { en: 'airline ticket', ar: 'تذكرة الطيران' },
            { en: 'weigh my luggage on the scale', ar: 'أزن أمتعتي على الميزان' },
            { en: 'go through the airport security', ar: 'أمرّ عبر التفتيش الأمني' },
            { en: 'the departure hall', ar: 'صالة المغادرة' },
            { en: 'boarding gate', ar: 'بوابة الصعود' },
            { en: 'put on my seat belt', ar: 'أضع حزام الأمان' },
          ],
          model: 'At the airport, I go to the check-in first. I show my passport and my airline ticket. I weigh my luggage on the scale. Then, I go through the airport security. After that, I wait for my flight at the departure hall. Finally, I go through the boarding gate to the plane and put on my seat belt.',
          modelAr: 'في المطار، أذهب أولاً إلى مكتب تسجيل المسافرين. أُظهر جواز سفري وتذكرة الطيران. أزن أمتعتي على الميزان. ثم أمرّ عبر التفتيش الأمني. بعد ذلك، أنتظر رحلتي في صالة المغادرة. أخيراً، أمرّ عبر بوابة الصعود إلى الطائرة وأضع حزام الأمان.',
          checklistAr: [
            'ذكرتُ الخطوات بترتيبها الصحيح في المطار.',
            'استعملتُ first وThen وAfter that وFinally.',
            'استعملتُ كلمات المطار: passport, luggage, scale, gate.',
            'كتبتُ بزمن المضارع البسيط لأنه شيء نفعله كل مرة.',
            'بدأتُ كل جملة بحرف كبير وختمتها بنقطة.',
          ],
        },
      ],
      translations: [
        { en: 'Mr. Scott is going to travel by plane.', ar: 'السيد سكوت سيسافر بالطائرة.' },
        { en: 'May I see your passport and your airline ticket?', ar: 'هل يمكنني أن أرى جواز سفرك وتذكرة الطيران؟' },
        { en: 'How many bags are you checking in?', ar: 'كم حقيبة ستشحن؟' },
        { en: 'Can you put it on the scale, please?', ar: 'هل يمكنك أن تضعها على الميزان، من فضلك؟' },
        { en: 'Your flight leaves from gate 7B at 10:00 am.', ar: 'رحلتك تنطلق من البوابة 7B الساعة العاشرة صباحاً.' },
        { en: 'Shall I go through the airport security now?', ar: 'هل أمرّ الآن عبر التفتيش الأمني في المطار؟' },
        { en: 'Have a nice flight sir.', ar: 'رحلة سعيدة يا سيدي.' },
        { en: 'You have to put your seat belt on.', ar: 'يجب أن تضع حزام الأمان.' },
        { en: 'Keep your boarding pass in your hand.', ar: 'أبقِ بطاقة الصعود إلى الطائرة في يدك.' },
        { en: 'We buy airline tickets before we fly.', ar: 'نشتري تذاكر الطيران قبل أن نطير.' },
      ],
    },

    // ===================== UNIT 19 — Festivals (Activity Book pages 65–67) =====================
    u19: {
      workbook: {
        pages: '65–67',
        readings: [
          {
            title: 'The Festival of Colours',
            paragraphs: [
              'The Festival of Colours is my mum’s favourite. She went there when she was younger. It lasted for two days. She was excited. Bands came to play music and people danced. The second day was the most interesting. Everyone threw coloured powder at each other. They bought so much coloured powder to enjoy the colours. They had fun! Nowadays DJ\'s play music from CDs.',
            ],
            paragraphsAr: [
              'مهرجان الألوان هو المهرجان المفضّل عند أمي. ذهبت إليه عندما كانت أصغر سنّاً. استمرّ يومين. كانت متحمّسة. جاءت فرق موسيقية لتعزف، ورقص الناس. كان اليوم الثاني هو الأكثر متعة. رمى الجميع مسحوق الألوان على بعضهم. اشتروا كثيراً من مسحوق الألوان ليستمتعوا بالألوان. لقد استمتعوا كثيراً! وفي أيامنا هذه يشغّل منسّقو الأغاني (الدي جي) الموسيقى من الأقراص المدمجة.',
            ],
            questions: [
              {
                q: 'Cross the odd word out: music - CD - band - young', qAr: 'اشطب الكلمة المختلفة: موسيقى - قرص مدمج - فرقة - شابّ',
                options: ['music', 'CD', 'band', 'young'], answer: 3,
                explainAr: 'music وCD وband كلها عن الموسيقى، أمّا young (صغير السن) فلا علاقة لها بها.',
              },
              {
                q: 'Cross the odd word out: colour - excited - interesting - lovely', qAr: 'اشطب الكلمة المختلفة: لون - متحمّس - ممتع - جميل',
                options: ['colour', 'excited', 'interesting', 'lovely'], answer: 0,
                explainAr: 'excited وinteresting وlovely صفات تصف الأشياء والناس، أمّا colour فاسم (لون).',
              },
              {
                q: 'Cross the odd word out: enjoy - dance - play - day', qAr: 'اشطب الكلمة المختلفة: يستمتع - يرقص - يلعب - يوم',
                options: ['enjoy', 'dance', 'play', 'day'], answer: 3,
                explainAr: 'enjoy وdance وplay أفعال (أشياء نفعلها)، أمّا day فاسم (يوم).',
              },
            ],
            trueFalse: [
              { statement: 'The Festival continued for three days.', answer: false },
              { statement: 'People danced while the bands played music.', answer: true },
              { statement: 'She really enjoyed the second day.', answer: true },
              { statement: 'They threw water at each other.', answer: false },
              { statement: 'The festival was boring.', answer: false },
            ],
          },
        ],
        exercises: [
          // ---- page 65 (1): Match the words with the pictures ----
          mcq('Match. Picture: 1 + 1 = 2. Which word goes with it?', 'صِل. الصورة: 1 + 1 = 2. أيّ كلمة تناسبها؟',
            ['easy', 'delicious', 'beautiful', 'happy'], 0,
            'جمع 1 + 1 سهل جداً، فالكلمة easy (سهل).'),
          mcq('Match. Picture: a lovely flower. Which word goes with it?', 'صِل. الصورة: زهرة جميلة. أيّ كلمة تناسبها؟',
            ['different', 'beautiful', 'easy', 'delicious'], 1,
            'الزهرة جميلة، فالكلمة beautiful (جميل).'),
          mcq('Match. Picture: a boy reading a book. Which word goes with it?', 'صِل. الصورة: ولد يقرأ كتاباً. أيّ كلمة تناسبها؟',
            ['happy', 'delicious', 'interesting', 'different'], 2,
            'الكتاب الذي نحبّ قراءته ممتع، فالكلمة interesting (ممتع).'),
          mcq('Match. Picture: a boy jumping with joy. Which word goes with it?', 'صِل. الصورة: ولد يقفز من الفرح. أيّ كلمة تناسبها؟',
            ['easy', 'beautiful', 'different', 'happy'], 3,
            'الولد يقفز فرحاً، فالكلمة happy (سعيد).'),
          mcq('Match. Picture: a circle and a triangle. Which word goes with it?', 'صِل. الصورة: دائرة ومثلّث. أيّ كلمة تناسبها؟',
            ['different', 'interesting', 'happy', 'easy'], 0,
            'الدائرة والمثلّث شكلان غير متشابهين، فالكلمة different (مختلف).'),
          mcq('Match. Picture: a big birthday cake. Which word goes with it?', 'صِل. الصورة: كعكة عيد ميلاد كبيرة. أيّ كلمة تناسبها؟',
            ['beautiful', 'delicious', 'different', 'easy'], 1,
            'الكعكة طعام طيّب، فالكلمة delicious (لذيذ).'),

          // ---- page 66 (4): Listen again and match (the words decide) ----
          fill('Brazil’s Festival is ___', 'مهرجان البرازيل هو ___', 'مهرجان البرازيل هو أعظم عرض.',
            ['in January.', 'the greatest show.', 'of all colours.'], 1,
            'نصف المهرجان كله بأنه أعظم عرض: the greatest show.'),
          fill('The Snow Festival starts ___', 'مهرجان الثلج يبدأ ___', 'مهرجان الثلج يبدأ في كانون الثاني.',
            ['in January.', 'the greatest show.', 'of all colours.'], 0,
            'بعد starts (يبدأ) نذكر الوقت: in January. والثلج يكون في الشتاء.'),
          fill('The balloons are ___', 'البالونات ___', 'البالونات بكل الألوان.',
            ['the greatest show.', 'in January.', 'of all colours.'], 2,
            'البالونات في الصورة كثيرة ومختلفة، فهي of all colours (بكل الألوان).'),

          // ---- page 66 (5): Read and practise ----
          fill('In the past, people ___ to attend festivals.', 'في الماضي، ___ الناس ليحضروا المهرجانات.', 'في الماضي، سافر الناس ليحضروا المهرجانات.',
            ['travel', 'travelled', 'travels'], 1,
            'In the past تعني «في الماضي»، فنستعمل الفعل الماضي travelled.'),
          fill('Nowadays, they can ___ them on TV.', 'في أيامنا هذه، يستطيعون أن ___ المهرجانات على التلفاز.', 'في أيامنا هذه، يستطيعون أن يشاهدوا المهرجانات على التلفاز.',
            ['watch', 'watched', 'watches'], 0,
            'بعد can يأتي الفعل بشكله الأصلي: watch.'),

          // ---- page 67 (7): Fill in the spaces with the words in the box ----
          fill('Nowadays, we ___ the Children\'s Day.', 'في أيامنا هذه، ___ بيوم الطفل.', 'في أيامنا هذه، نحتفل بيوم الطفل.',
            ['wore', 'celebrate', 'gathered', 'cooked'], 1,
            'Nowadays تعني «في أيامنا هذه»، فنستعمل المضارع: celebrate (نحتفل). هذا هو المثال المحلول في الكتاب.'),
          fill('In the past, we ___ traditional clothes.', 'في الماضي، ___ ملابس تقليدية.', 'في الماضي، لبسنا ملابس تقليدية.',
            ['go', 'wore', 'gave', 'celebrate'], 1,
            'نلبس الملابس، وفي الماضي نستعمل wore (ماضي wear).'),
          fill('Nowadays, they ___ to cafés to watch The Football World Cup.', 'في أيامنا هذه، ___ إلى المقاهي لمشاهدة كأس العالم لكرة القدم.', 'في أيامنا هذه، يذهبون إلى المقاهي لمشاهدة كأس العالم لكرة القدم.',
            ['gathered', 'cooked', 'go', 'wore'], 2,
            'Nowadays تحتاج المضارع، وبعدها to cafés، فالكلمة go (يذهبون).'),
          fill('Our family ___ for the New Year’s Eve in the past.', 'عائلتنا ___ ليلة رأس السنة في الماضي.', 'عائلتنا اجتمعت ليلة رأس السنة في الماضي.',
            ['gave', 'gathered', 'go', 'celebrate'], 1,
            'in the past تحتاج الماضي، والعائلة تجتمع: gathered (اجتمعت).'),
          fill('In the past, mum ___ big meals for Eid.', 'في الماضي، ___ أمي وجبات كبيرة للعيد.', 'في الماضي، طبخت أمي وجبات كبيرة للعيد.',
            ['cooked', 'wore', 'go', 'celebrate'], 0,
            'الوجبات تُطبخ، وفي الماضي نقول cooked (طبخت).'),
          fill('In the past, dad ___ me pocket money.', 'في الماضي، ___ أبي مصروفاً لي.', 'في الماضي، أعطاني أبي مصروفاً.',
            ['cooked', 'gathered', 'gave', 'go'], 2,
            'الأب يعطي المصروف، وفي الماضي نقول gave (أعطى).'),

          // ---- page 67 (9): Listen and classify — the sound of "-ed" ----
          edItem('closed', 2, 'قبل ed صوت /z/ (clo-se)، وهو صوت فيه اهتزاز، فنلفظها /d/ مثل played.'),
          edItem('needed', 1, 'الفعل need ينتهي بصوت /d/، فنلفظ ed مقطعاً كاملاً /id/ مثل pointed.'),
          edItem('danced', 0, 'dance ينتهي بصوت /s/، فنلفظ ed صوت /t/ مثل liked.'),
          edItem('walked', 0, 'walk ينتهي بصوت /k/، فنلفظ ed صوت /t/ مثل liked.'),
          edItem('opened', 2, 'open ينتهي بصوت /n/، فنلفظ ed صوت /d/ مثل played.'),
          edItem('started', 1, 'start ينتهي بصوت /t/، فنلفظ ed مقطعاً كاملاً /id/ مثل pointed.'),
          edItem('worked', 0, 'work ينتهي بصوت /k/، فنلفظ ed صوت /t/ مثل liked.'),
          edItem('lived', 2, 'live ينتهي بصوت /v/، فنلفظ ed صوت /d/ مثل played.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Complete.',
          topicAr: 'أكمل: في الماضي… / في أيامنا هذه…',
          words: 40,
          points: ['In the past, …', 'Nowadays, …'],
          pointsAr: ['في الماضي، …', 'في أيامنا هذه، …'],
          plan: [
            { en: 'Write what people did in the past, with past verbs.', ar: 'اكتب ما كان الناس يفعلونه في الماضي، بأفعال ماضية.' },
            { en: 'Write what people do nowadays, with present verbs.', ar: 'اكتب ما يفعله الناس في أيامنا هذه، بأفعال مضارعة.' },
          ],
          phrases: [
            { en: 'In the past, …', ar: 'في الماضي، …' },
            { en: 'Nowadays, …', ar: 'في أيامنا هذه، …' },
            { en: 'made Eid sweets together', ar: 'صنعن حلوى العيد معاً' },
            { en: 'went to the market to shop', ar: 'ذهبوا إلى السوق للتسوّق' },
            { en: 'buy sweets from the shop', ar: 'نشتري الحلوى من المحل' },
            { en: 'shop online', ar: 'نتسوّق عبر الإنترنت' },
            { en: 'watch it on TV', ar: 'نشاهده على التلفاز' },
          ],
          model: 'In the past, people went to the market to shop. Women made Eid sweets together, and my grandmother sewed clothes for her children. Nowadays, we buy sweets from the shop. My mother buys clothes from the shops, and many people shop online.',
          modelAr: 'في الماضي، كان الناس يذهبون إلى السوق للتسوّق. كانت النساء يصنعن حلوى العيد معاً، وكانت جدّتي تخيط الملابس لأولادها. في أيامنا هذه، نشتري الحلوى من المحل. أمي تشتري الملابس من المحلات، وكثير من الناس يتسوّقون عبر الإنترنت.',
          checklistAr: [
            'بدأتُ الجزء الأول بـ In the past والثاني بـ Nowadays.',
            'استعملتُ الماضي بعد In the past (went, made).',
            'استعملتُ المضارع بعد Nowadays (buy, shop).',
            'أضفتُ s إلى الفعل مع he / she / my mother (buys).',
          ],
        },
        {
          source: 'workbook',
          topic: 'Complete.',
          topicAr: 'أكمل الفقرة عن الأعياد في الماضي واليوم.',
          words: 40,
          points: ['In the past, mum …… our …… clothes.', 'We were very …… .', 'We …… with our friends and …… …… food.', 'Nowadays, we …… .'],
          pointsAr: ['في الماضي، … أمي ملابسنا …', 'كنّا … جداً.', '… مع أصدقائنا و… طعاماً …', 'في أيامنا هذه، نحن …'],
          plan: [
            { en: 'Fill the past part with past verbs: mum sewed our clothes, we played, we ate.', ar: 'املأ جزء الماضي بأفعال ماضية: خاطت أمي ملابسنا، لعبنا، أكلنا.' },
            { en: 'Say how you felt: We were very happy / excited.', ar: 'قل بماذا شعرت: كنّا سعداء جداً / متحمّسين جداً.' },
            { en: 'Finish with Nowadays and present verbs.', ar: 'اختم بـ Nowadays وأفعال مضارعة.' },
          ],
          phrases: [
            { en: 'sewed our Eid clothes', ar: 'خاطت ملابس العيد' },
            { en: 'We were very happy.', ar: 'كنّا سعداء جداً.' },
            { en: 'excited', ar: 'متحمّس' },
            { en: 'played with our friends', ar: 'لعبنا مع أصدقائنا' },
            { en: 'ate delicious food', ar: 'أكلنا طعاماً لذيذاً' },
            { en: 'buy our clothes from the shops', ar: 'نشتري ملابسنا من المحلات' },
          ],
          model: 'In the past, mum sewed our Eid clothes. We were very happy. We played with our friends and ate delicious food. Nowadays, we buy our clothes from the shops. We watch the festivals on TV, but we still eat delicious sweets.',
          modelAr: 'في الماضي، خاطت أمي ملابس العيد لنا. كنّا سعداء جداً. لعبنا مع أصدقائنا وأكلنا طعاماً لذيذاً. في أيامنا هذه، نشتري ملابسنا من المحلات. نشاهد المهرجانات على التلفاز، لكنّنا ما زلنا نأكل الحلوى اللذيذة.',
          checklistAr: [
            'ملأتُ كل الفراغات بكلمات مناسبة.',
            'استعملتُ الماضي في الجمل الأولى (sewed, were, played, ate).',
            'استعملتُ المضارع بعد Nowadays.',
            'استعملتُ صفة تصف الشعور مثل happy أو excited.',
          ],
        },
      ],
      translations: [
        { en: 'The Festival of Colours is my mum’s favourite.', ar: 'مهرجان الألوان هو المهرجان المفضّل عند أمي.' },
        { en: 'She went there when she was younger.', ar: 'ذهبت إليه عندما كانت أصغر سنّاً.' },
        { en: 'It lasted for two days.', ar: 'استمرّ يومين.' },
        { en: 'Bands came to play music and people danced.', ar: 'جاءت فرق موسيقية لتعزف، ورقص الناس.' },
        { en: 'The second day was the most interesting.', ar: 'كان اليوم الثاني هو الأكثر متعة.' },
        { en: 'Everyone threw coloured powder at each other.', ar: 'رمى الجميع مسحوق الألوان على بعضهم.' },
        { en: 'In the past, people travelled to attend festivals.', ar: 'في الماضي، سافر الناس ليحضروا المهرجانات.' },
        { en: 'Nowadays, they can watch them on TV.', ar: 'في أيامنا هذه، يستطيعون مشاهدتها على التلفاز.' },
        { en: 'In the past, women made Eid sweets together.', ar: 'في الماضي، صنعت النساء حلوى العيد معاً.' },
        { en: 'Nowadays, we buy sweets from the shop.', ar: 'في أيامنا هذه، نشتري الحلوى من المحل.' },
      ],
    },

    // ===================== UNIT 20 — Places Around the World (Activity Book pages 68–70) =====================
    u20: {
      workbook: {
        pages: '68–70',
        readings: [
          {
            title: 'Famous places',
            paragraphs: [
              'The Great Wall of China is an ancient wall. The Chinese built it to protect the Empire of China from enemy attacks. It is the longest wall ever built.',
              'The Eiffel Tower in Paris, France was first built for the World’s Fair in 1889. In cold weather, the tower becomes shorter.',
              'The Colosseum is an ancient stadium in Rome, Italy. It is the largest theatre in the world. Fights and competitions took place there.',
            ],
            paragraphsAr: [
              'سور الصين العظيم سور قديم. بناه الصينيون ليحموا إمبراطورية الصين من هجمات الأعداء. إنه أطول سور بُني على الإطلاق.',
              'بُني برج إيفل في باريس، فرنسا، أول مرة من أجل المعرض العالمي عام 1889. في الطقس البارد يصبح البرج أقصر.',
              'الكولوسيوم ملعب قديم في روما، إيطاليا. إنه أكبر مسرح في العالم. كانت تُقام فيه المعارك والمسابقات.',
            ],
            questions: [
              {
                q: 'Read and match: The Colosseum — ___', qAr: 'اقرأ وصِل: الكولوسيوم — ___',
                options: ['France', 'Italy', 'China'], answer: 1,
                explainAr: 'النص يقول: The Colosseum is an ancient stadium in Rome, Italy.',
              },
              {
                q: 'Read and match: The Great Wall — ___', qAr: 'اقرأ وصِل: السور العظيم — ___',
                options: ['France', 'Italy', 'China'], answer: 2,
                explainAr: 'اسمه The Great Wall of China، فهو في الصين.',
              },
              {
                q: 'Read and match: The Eiffel Tower — ___', qAr: 'اقرأ وصِل: برج إيفل — ___',
                options: ['France', 'Italy', 'China'], answer: 0,
                explainAr: 'النص يقول: The Eiffel Tower in Paris, France.',
              },
            ],
            trueFalse: [
              { statement: 'The Great Wall of China is modern.', answer: false },
              { statement: 'They built The Eiffel Tower in 1889.', answer: true },
              { statement: 'The Colosseum is an ancient theatre.', answer: true },
            ],
          },
        ],
        exercises: [
          // ---- page 68 (1 a, b): Look and say where the places are ----
          fill('This is ___. It is in Syria.', 'هذه ___. إنها في سوريا.', 'هذه جزيرة أرواد. إنها في سوريا.',
            ['Big Ben', 'Arwad Island', 'The Colosseum'], 1,
            'جزيرة أرواد Arwad Island في سوريا، قرب طرطوس. هذا هو المثال في الكتاب.'),
          fill('This is The Eiffel Tower. It is in ___.', 'هذا برج إيفل. إنه في ___.', 'هذا برج إيفل. إنه في فرنسا.',
            ['France', 'Italy', 'Australia'], 0,
            'برج إيفل في باريس، فرنسا: The Eiffel Tower in Paris, France.'),
          fill('This is The Colosseum. It is in ___.', 'هذا الكولوسيوم. إنه في ___.', 'هذا الكولوسيوم. إنه في إيطاليا.',
            ['France', 'Syria', 'Italy'], 2,
            'الكولوسيوم في روما، إيطاليا: in Rome, Italy.'),
          fill('This is The Opera House. It is in ___.', 'هذه دار الأوبرا. إنها في ___.', 'هذه دار الأوبرا. إنها في أستراليا.',
            ['Australia', 'Syria', 'Lebanon'], 0,
            'دار الأوبرا في مدينة سيدني في أستراليا، كما في نص كتاب الطالب عن رايان وماريا.'),
          fill('This is Big Ben. It is in ___.', 'هذه ساعة بيغ بن. إنها في ___.', 'هذه ساعة بيغ بن. إنها في لندن.',
            ['Italy', 'London', 'France'], 1,
            'ساعة بيغ بن Big Ben في مدينة لندن.'),
          build('This is Arwad Island. It is in Syria.', 'هذه جزيرة أرواد. إنها في سوريا.'),

          // ---- page 68 (2): Read and match ----
          mcq('Read and match: Where will they go on holiday?', 'اقرأ وصِل: إلى أين سيذهبون في العطلة؟',
            ['They will arrive on Tuesday.', 'They will travel to Italy.', 'They will visit Pisa Tower.'], 1,
            'السؤال بـ Where (أين) يحتاج مكاناً: They will travel to Italy.'),
          mcq('Read and match: What will they visit?', 'اقرأ وصِل: ماذا سيزورون؟',
            ['They will arrive on Tuesday.', 'They will travel to Italy.', 'They will visit Pisa Tower.'], 2,
            'السؤال What will they visit يُجاب بالمكان الذي سيزورونه: They will visit Pisa Tower.'),
          mcq('Read and match: When will they arrive?', 'اقرأ وصِل: متى سيصلون؟',
            ['They will arrive on Tuesday.', 'They will travel to Italy.', 'They will visit Pisa Tower.'], 0,
            'السؤال بـ When (متى) يحتاج وقتاً: on Tuesday (يوم الثلاثاء).'),

          // ---- page 69 (4a): Listen and choose — the pairs that go together ----
          mcq('Kate says: "I am from (London / Australia). We will visit (The Opera House / Big Ben)." If she is from Australia, what will they visit?',
            'تقول كيت: «أنا من (لندن / أستراليا). سنزور (دار الأوبرا / بيغ بن).» إذا كانت من أستراليا، فماذا سيزورون؟',
            ['Big Ben', 'The Opera House', 'The Colosseum'], 1,
            'دار الأوبرا The Opera House في أستراليا، أمّا بيغ بن ففي لندن.'),
          mcq('Victor says: "I am from (France / Italy). I will take you to see The (Colosseum / Eiffel Tower)." If he is from France, what will they see?',
            'يقول فيكتور: «أنا من (فرنسا / إيطاليا). سآخذكم لتروا (الكولوسيوم / برج إيفل).» إذا كان من فرنسا، فماذا سيرون؟',
            ['The Eiffel Tower', 'The Colosseum', 'Arwad Island'], 0,
            'برج إيفل في فرنسا، أمّا الكولوسيوم ففي إيطاليا.'),

          // ---- page 70 (6): Write what you will do ----
          fill('Next week, I will ___ to Lebanon.', 'الأسبوع القادم، ___ إلى لبنان.', 'الأسبوع القادم، سأذهب إلى لبنان.',
            ['went', 'goes', 'go'], 2,
            'بعد will يأتي الفعل بشكله الأصلي دائماً: will go.'),
          mcq('Tomorrow I will … Which sentence is correct?', 'غداً سوف… أيّ جملة صحيحة؟',
            ['Tomorrow I will visit some friends.', 'Tomorrow I will visits some friends.', 'Tomorrow I will visited some friends.'], 0,
            'بعد will نستعمل الفعل الأصلي بلا s وبلا ed: will visit.'),
          mcq('On Friday I won’t … Which sentence is correct?', 'يوم الجمعة لن… أيّ جملة صحيحة؟',
            ['On Friday I won’t goes to school.', 'On Friday I not will go to school.', 'On Friday I won’t go to school.'], 2,
            'النفي في المستقبل: won’t + الفعل الأصلي، مثل won’t go. (won’t = will not)'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Write about your holiday.',
          topicAr: 'اكتب عن عطلتك.',
          words: 40,
          points: ['Where will you go on holiday?', 'How long will you stay there?', 'Who will you go with?', 'What will you do during your holiday?'],
          pointsAr: ['إلى أين ستذهب في العطلة؟', 'كم ستبقى هناك؟', 'مع مَن ستذهب؟', 'ماذا ستفعل خلال عطلتك؟'],
          plan: [
            { en: 'Say where you will go and who you will go with.', ar: 'قل إلى أين ستذهب ومع مَن.' },
            { en: 'Say how long you will stay there.', ar: 'قل كم ستبقى هناك.' },
            { en: 'Say what you will do and what you won’t do there.', ar: 'قل ماذا ستفعل وماذا لن تفعل هناك.' },
          ],
          phrases: [
            { en: 'I will travel to …', ar: 'سأسافر إلى …' },
            { en: 'I will stay for a few days / a week.', ar: 'سأبقى بضعة أيام / أسبوعاً.' },
            { en: 'with my family', ar: 'مع عائلتي' },
            { en: 'We will visit …', ar: 'سنزور …' },
            { en: 'We won’t …', ar: 'لن …' },
            { en: 'interesting places', ar: 'أماكن ممتعة' },
            { en: 'Arwad Island', ar: 'جزيرة أرواد' },
          ],
          model: 'In the summer, I will go on holiday to Tartous. I will stay there for a week. I will go with my family. We will visit Arwad Island and many interesting places. We will swim in the sea and take photos. We won’t stay at home. It will be a lovely holiday!',
          modelAr: 'في الصيف، سأذهب في عطلة إلى طرطوس. سأبقى هناك أسبوعاً. سأذهب مع عائلتي. سنزور جزيرة أرواد وأماكن ممتعة كثيرة. سنسبح في البحر ونلتقط الصور. لن نبقى في البيت. ستكون عطلة جميلة!',
          checklistAr: [
            'أجبتُ عن الأسئلة الأربعة في الكتاب.',
            'استعملتُ will + الفعل الأصلي (will go, will visit).',
            'استعملتُ won’t مرة واحدة على الأقل.',
            'ذكرتُ مكاناً ومدة وأشخاصاً ونشاطات.',
            'بدأتُ كل جملة بحرف كبير وكتبتُ أسماء الأماكن بحرف كبير.',
          ],
        },
        {
          source: 'workbook',
          topic: 'Read the following story and write what will happen at the end.',
          topicAr: 'اقرأ القصة التالية واكتب ماذا سيحدث في النهاية.',
          words: 40,
          points: ['Hazem decides to travel to India. He has a friend there called Raji who will help him. When Hazem arrives in India, he will call Raji and …'],
          pointsAr: ['يقرّر حازم أن يسافر إلى الهند. لديه صديق هناك اسمه راجي سيساعده. عندما يصل حازم إلى الهند، سيتّصل براجي و…'],
          plan: [
            { en: 'Copy the beginning of the story.', ar: 'انسخ بداية القصة.' },
            { en: 'Say what Raji will do to help Hazem.', ar: 'قل ماذا سيفعل راجي ليساعد حازم.' },
            { en: 'Say what they will do together, and end the story.', ar: 'قل ماذا سيفعلان معاً، واختم القصة.' },
          ],
          phrases: [
            { en: 'will meet him at the airport', ar: 'سيلتقي به في المطار' },
            { en: 'find a good hotel', ar: 'يجد فندقاً جيداً' },
            { en: 'eat and rest', ar: 'يأكل ويرتاح' },
            { en: 'visit many interesting places', ar: 'يزور أماكن ممتعة كثيرة' },
            { en: 'take photos', ar: 'يلتقط الصور' },
            { en: 'have a lovely time', ar: 'يقضي وقتاً جميلاً' },
          ],
          model: 'Hazem decides to travel to India. He has a friend there called Raji who will help him. When Hazem arrives in India, he will call Raji and Raji will meet him at the airport. They will find a good hotel where Hazem will eat and rest. Then, they will visit many interesting places together. Hazem will have a lovely time.',
          modelAr: 'يقرّر حازم أن يسافر إلى الهند. لديه صديق هناك اسمه راجي سيساعده. عندما يصل حازم إلى الهند، سيتّصل براجي، وسيلتقي به راجي في المطار. سيجدان فندقاً جيداً يأكل فيه حازم ويرتاح. ثم سيزوران معاً أماكن ممتعة كثيرة. سيقضي حازم وقتاً جميلاً.',
          checklistAr: [
            'أكملتُ القصة بعد كلمة and.',
            'استعملتُ will + الفعل الأصلي لأن القصة عن المستقبل.',
            'جعلتُ راجي يساعد حازم كما تقول القصة.',
            'كتبتُ نهاية واضحة للقصة.',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write about your favourite place in the world.',
          topicAr: 'اكتب عن مكانك المفضّل في العالم.',
          words: 40,
          points: ['What is it?', 'Where is it?', 'What is interesting about it?'],
          pointsAr: ['ما هو؟', 'أين هو؟', 'ما الممتع فيه؟'],
          plan: [
            { en: 'Say what your favourite place is.', ar: 'قل ما مكانك المفضّل.' },
            { en: 'Say where it is.', ar: 'قل أين يقع.' },
            { en: 'Say what is interesting about it, and when you will visit it.', ar: 'قل ما الممتع فيه، ومتى ستزوره.' },
          ],
          phrases: [
            { en: 'My favourite place in the world is …', ar: 'مكاني المفضّل في العالم هو …' },
            { en: 'It is in …', ar: 'إنه في …' },
            { en: 'an ancient …', ar: '… قديم' },
            { en: 'the largest / the longest', ar: 'الأكبر / الأطول' },
            { en: 'interesting', ar: 'ممتع' },
            { en: 'I will visit it …', ar: 'سأزوره …' },
          ],
          model: 'My favourite place in the world is The Colosseum. It is in Rome, Italy. It is an ancient stadium. It is interesting because it is the largest theatre in the world, and fights and competitions took place there. I will visit it with my family one day.',
          modelAr: 'مكاني المفضّل في العالم هو الكولوسيوم. إنه في روما، إيطاليا. إنه ملعب قديم. هو ممتع لأنه أكبر مسرح في العالم، وكانت تُقام فيه المعارك والمسابقات. سأزوره مع عائلتي في يوم من الأيام.',
          checklistAr: [
            'أجبتُ عن الأسئلة الثلاثة: ما هو؟ أين هو؟ ما الممتع فيه؟',
            'كتبتُ اسم المكان والبلد بحرف كبير.',
            'استعملتُ is للوصف وwill للمستقبل.',
            'استعملتُ because لأشرح لماذا أحبّه.',
          ],
        },
      ],
      translations: [
        { en: 'This is Arwad Island.', ar: 'هذه جزيرة أرواد.' },
        { en: 'They will travel to Italy.', ar: 'سيسافرون إلى إيطاليا.' },
        { en: 'They will visit Pisa Tower.', ar: 'سيزورون برج بيزا.' },
        { en: 'Hazem decides to travel to India.', ar: 'يقرّر حازم أن يسافر إلى الهند.' },
        { en: 'Next week, I will go to Lebanon.', ar: 'الأسبوع القادم، سأذهب إلى لبنان.' },
        { en: 'The Great Wall of China is an ancient wall.', ar: 'سور الصين العظيم سور قديم.' },
        { en: 'It is the longest wall ever built.', ar: 'إنه أطول سور بُني على الإطلاق.' },
        { en: 'In cold weather, the tower becomes shorter.', ar: 'في الطقس البارد، يصبح البرج أقصر.' },
        { en: 'The Colosseum is an ancient stadium in Rome, Italy.', ar: 'الكولوسيوم ملعب قديم في روما، إيطاليا.' },
        { en: 'Fights and competitions took place there.', ar: 'كانت تُقام هناك المعارك والمسابقات.' },
      ],
    },
  },

  // ===================== Revision 4 (Activity Book pages 71–72) =====================
  progressTest: {
    title: 'Revision 4',
    titleAr: 'المراجعة الرابعة',
    pages: '71–72',
    exercises: [
      // ---- 1. Fill in the spaces with much or many ----
      fill('Jane hasn\'t got ___ time.', 'ليس لدى جين ___ وقت.', 'ليس لدى جين وقت كثير.',
        ['much', 'many', 'a'], 0,
        'time (الوقت) لا يُعدّ، فنستعمل much.'),
      fill('He didn\'t eat ___ meat.', 'لم يأكل ___ لحماً.', 'لم يأكل لحماً كثيراً.',
        ['many', 'much', 'a'], 1,
        'meat (اللحم) لا يُعدّ، فنستعمل much.'),
      fill('How ___ lessons did you study yesterday?', 'كم ___ درساً درستَ أمس؟', 'كم درساً درستَ أمس؟',
        ['much', 'any', 'many'], 2,
        'lessons جمع يُعدّ، فنقول How many.'),
      fill('Are there ___ cars in the street?', 'هل هناك ___ سيارات في الشارع؟', 'هل هناك سيارات كثيرة في الشارع؟',
        ['many', 'much', 'a'], 0,
        'cars جمع يُعدّ، فنستعمل many.'),

      // ---- 2. Classify: Much / Many ----
      mcq('Classify. Which word goes in the "Much" column?', 'صنّف. أيّ كلمة نضعها في عمود Much؟',
        ['desks', revMuch[0], 'cookies', 'cars'], 1,
        'rice (الأرز) لا نعدّه حبّة حبّة، فنقول much rice.'),
      mcq('Classify. Which word goes in the "Much" column?', 'صنّف. أيّ كلمة نضعها في عمود Much؟',
        ['children', 'cars', revMuch[1], 'desks'], 2,
        'salt (الملح) لا يُعدّ، فنقول much salt.'),
      mcq('Classify. Which word goes in the "Much" column?', 'صنّف. أيّ كلمة نضعها في عمود Much؟',
        [revMuch[2], 'cookies', 'children', 'desks'], 0,
        'butter (الزبدة) لا تُعدّ، فنقول much butter.'),
      mcq('Classify. Which word goes in the "Much" column?', 'صنّف. أيّ كلمة نضعها في عمود Much؟',
        ['cars', 'cookies', 'children', revMuch[3]], 3,
        'tea (الشاي) سائل لا يُعدّ، فنقول much tea.'),
      mcq('Classify. Which word goes in the "Many" column?', 'صنّف. أيّ كلمة نضعها في عمود Many؟',
        [revMany[0], 'rice', 'salt', 'tea'], 0,
        'desks (مقاعد) جمع يُعدّ، فنقول many desks.'),
      mcq('Classify. Which word goes in the "Many" column?', 'صنّف. أيّ كلمة نضعها في عمود Many؟',
        ['butter', revMany[1], 'tea', 'rice'], 1,
        'cookies (قطع البسكويت) جمع يُعدّ، فنقول many cookies.'),
      mcq('Classify. Which word goes in the "Many" column?', 'صنّف. أيّ كلمة نضعها في عمود Many؟',
        ['salt', 'rice', revMany[2], 'butter'], 2,
        'cars (سيارات) جمع يُعدّ، فنقول many cars.'),
      mcq('Classify. Which word goes in the "Many" column?', 'صنّف. أيّ كلمة نضعها في عمود Many؟',
        ['tea', 'butter', 'salt', revMany[3]], 3,
        'children (أطفال) جمع child، ويُعدّ، فنقول many children.'),

      // ---- 3. Write the correct tense ----
      fill('He always ___ football on Fridays. (play)', 'هو دائماً ___ كرة القدم أيام الجمعة. (يلعب)', 'هو دائماً يلعب كرة القدم أيام الجمعة.',
        ['play', 'plays', 'played', 'will play'], 1,
        'always تدلّ على عادة، فنستعمل المضارع البسيط، ومع he نضيف s: plays.'),
      fill('Louma and Lubna ___ us next week. (visit)', 'لمى ولبنى ___ الأسبوع القادم. (تزور)', 'لمى ولبنى ستزوراننا الأسبوع القادم.',
        ['visited', 'visits', 'will visit', 'visiting'], 2,
        'next week (الأسبوع القادم) تدلّ على المستقبل، فنستعمل will visit.'),
      fill('Ola ___ many delicious cakes yesterday. (make)', 'علا ___ كعكات لذيذة كثيرة أمس. (تصنع)', 'علا صنعت كعكات لذيذة كثيرة أمس.',
        ['made', 'makes', 'will make', 'make'], 0,
        'yesterday (أمس) تدلّ على الماضي، وماضي make هو made.'),
      fill('Majed went to the market to ___ some vegetables. (buy)', 'ذهب ماجد إلى السوق لكي ___ بعض الخضار. (يشتري)', 'ذهب ماجد إلى السوق لكي يشتري بعض الخضار.',
        ['bought', 'buys', 'buy', 'buying'], 2,
        'بعد to (بمعنى لكي) نستعمل الفعل الأصلي: buy، حتى لو كانت الجملة في الماضي.'),

      // ---- 4. Choose the correct word between brackets ----
      fill('Did you go ___ last evening?', 'هل ذهبتَ إلى ___ مساء أمس؟', 'هل ذهبتَ إلى أيّ مكان مساء أمس؟',
        ['anywhere', 'anything', 'nothing'], 0,
        'الفعل go يحتاج مكاناً، وفي السؤال نقول anywhere (أيّ مكان).'),
      fill('___ took my bag.', '___ أخذ حقيبتي.', 'شخصٌ ما أخذ حقيبتي.',
        ['Something', 'Someone', 'Anything'], 1,
        'الذي يأخذ الحقيبة شخص، فنقول Someone (شخصٌ ما).'),
      fill('There is ___ in the basket. It\'s empty.', 'يوجد ___ في السلّة. إنها فارغة.', 'لا يوجد شيء في السلّة. إنها فارغة.',
        ['anything', 'something', 'nothing'], 2,
        'السلّة فارغة (empty)، إذن There is nothing = لا يوجد شيء.'),
      fill('___ could move the heavy stone.', '___ استطاع أن يحرّك الحجر الثقيل.', 'لا أحد استطاع أن يحرّك الحجر الثقيل.',
        ['Nothing', 'Nobody', 'Anybody'], 1,
        'الذي يحرّك الحجر شخص، والحجر ثقيل جداً، فنقول Nobody (لا أحد).'),

      // ---- 5. Fill in the spaces with the words in the box ----
      fill('My children had fun in the ___ last night.', 'استمتع أطفالي في ___ ليلة أمس.', 'استمتع أطفالي في المهرجان ليلة أمس.',
        ['places', 'honey', 'festival', 'healthy'], 2,
        'بعد the نحتاج اسماً لمكان فيه متعة: festival (المهرجان).'),
      fill('We should eat ___ food.', 'يجب أن نأكل طعاماً ___.', 'يجب أن نأكل طعاماً صحياً.',
        ['healthy', 'places', 'honey', 'festival'], 0,
        'قبل food نحتاج صفة: healthy (صحّي).'),
      fill('Bees make ___ from nectar.', 'يصنع النحل ___ من الرحيق.', 'يصنع النحل العسل من الرحيق.',
        ['festival', 'honey', 'healthy', 'places'], 1,
        'النحل يصنع العسل honey من الرحيق nectar.'),
      fill('How many ___ did you visit?', 'كم ___ زرت؟', 'كم مكاناً زرت؟',
        ['honey', 'healthy', 'festival', 'places'], 3,
        'بعد How many نحتاج اسماً بالجمع: places (أماكن).'),

      // ---- 6. Reorder ----
      build('There are many cars in the street.', 'هناك سيارات كثيرة في الشارع.'),
      build('There is much salt on the table.', 'يوجد ملح كثير على الطاولة.'),
      build('My grandfather is running now.', 'جدّي يركض الآن.'),
      build('My grandmother baked delicious cookies yesterday.', 'خبزت جدّتي بسكويتاً لذيذاً أمس.'),
    ],
  },
}
