import type { GrammarExercise } from '../../../engine/types'
import type { ModuleExtras } from './merge'

// Module 3 — Activity Book pages 39–55: Unit 11 Nature (39–41), Unit 12 Jobs (42–44), Unit 13 Houses (45–47),
// Unit 14 At the Sports Centre (48–50), Unit 15 Sports Equipment (51–53) and Revision 3 (54–55).
// Left out: the "Listen and …" tasks whose answers come only from the recording (pages 40, 41, 44, 47, 49, 52),
// except the items the page's own words already answer.

const fill = (prompt: string, promptAr: string, promptArFull: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, promptAr, promptArFull, options, answer, explainAr })
const mcq = (prompt: string, promptAr: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, promptAr, options, answer, explainAr })
const tf = (prompt: string, promptAr: string, answer: boolean, explainAr: string): GrammarExercise =>
  ({ type: 'truefalse', prompt, promptAr, answer, explainAr })
const build = (answer: string, hintAr: string): GrammarExercise => ({ type: 'build', answer, prompt: hintAr })

// ---------- Unit 11, page 40b: find words that mean … ----------
const u11Words = ['creatures', 'necessary', 'source', 'breathing']
// ---------- Unit 11, page 41 (6) / Revision 3: must or mustn't ----------
const must = ['must', "mustn't", "don't must"]
// ---------- Unit 12, page 44 (6): question words ----------
const how = ['How much', 'How many', 'How', 'How tall']
// ---------- Unit 13, page 45b: the words in the box ----------
const u13Box = ['huts', 'animal', 'building', 'different']
// ---------- Unit 14, page 49 (4): the endings to match ----------
const u14Endings = ['when the time was over.', 'when the referee ended the match.', 'when it started to rain.', 'when she fell off.']
// ---------- Revision 3, page 54 (3): classify ----------
const classes = ['Sport', 'Jobs', 'Houses']
const classify = (word: string, answer: number, explainAr: string): GrammarExercise =>
  mcq(`Classify: ${word}`, `صنّف الكلمة: ${word}. هل هي رياضة (Sport) أم مهنة (Jobs) أم نوع بيت (Houses)؟`, classes, answer, explainAr)

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 11 — Nature (Activity Book pages 39–41) =====================
    u11: {
      workbook: {
        pages: '39–41',
        readings: [
          {
            title: 'Water and Air',
            paragraphs: [
              "All living things need water and air to live. Water plays an important role in our life. Water is necessary for drinking, cooking, washing and growing food. Most fresh water is in the form of ice. Plants need water to live. Rain is the main source of fresh water. Air is everywhere. We can't see it, but we can feel it. Oxygen in the air is important for breathing. All creatures need air and water to live.",
            ],
            paragraphsAr: [
              'كل الكائنات الحية تحتاج إلى الماء والهواء لتعيش. للماء دور مهم في حياتنا. الماء ضروري للشرب والطبخ والغسيل وزراعة الطعام. معظم الماء العذب موجود على شكل جليد. النباتات تحتاج إلى الماء لتعيش. المطر هو المصدر الرئيسي للماء العذب. الهواء موجود في كل مكان. لا نستطيع أن نراه، لكننا نستطيع أن نشعر به. الأكسجين الموجود في الهواء مهم للتنفّس. كل المخلوقات تحتاج إلى الهواء والماء لتعيش.',
            ],
            questions: [
              { q: 'All living things need water to ___.', qAr: 'كل الكائنات الحية تحتاج إلى الماء لكي ___.', options: ['eat', 'breathe', 'stay alive'], answer: 2,
                explainAr: 'النص يقول: تحتاج الكائنات الحية إلى الماء to live «لتعيش»، أي لتبقى على قيد الحياة stay alive.' },
              { q: 'Most ___ water is in the form of ice.', qAr: 'معظم الماء ___ موجود على شكل جليد.', options: ['salty', 'fresh', 'dirty'], answer: 1,
                explainAr: 'النص: Most fresh water is in the form of ice «معظم الماء العذب على شكل جليد».' },
              { q: 'The main source of fresh water is ___.', qAr: 'المصدر الرئيسي للماء العذب هو ___.', options: ['rain', 'sea', 'ocean'], answer: 0,
                explainAr: 'النص: Rain is the main source of fresh water «المطر هو المصدر الرئيسي للماء العذب». ماء البحر مالح.' },
              { q: 'We need oxygen for ___.', qAr: 'نحتاج إلى الأكسجين من أجل ___.', options: ['cooking', 'breathing', 'washing'], answer: 1,
                explainAr: 'النص: Oxygen in the air is important for breathing «الأكسجين مهم للتنفّس».' },
            ],
          },
        ],
        exercises: [
          // 1. Look at these pictures and talk about them.
          fill('In the first picture, we have many kinds of green plants. They give us ___.',
            'في الصورة الأولى عندنا أنواع كثيرة من النباتات الخضراء. هي تعطينا ___.',
            'في الصورة الأولى عندنا أنواع كثيرة من النباتات الخضراء. هي تعطينا الأكسجين.',
            ['rubbish', 'oxygen', 'ice'], 1, 'النباتات الخضراء تعطينا الأكسجين oxygen، وهو الغاز الذي نتنفّسه.'),
          // 2. Ask and answer.
          build('I am looking after the plants.', 'أنا أعتني بالنباتات.'),
          mcq('Anas: What do plants need to grow? Bader: …', 'أنس: ماذا تحتاج النباتات لكي تنمو؟ ماذا يجيب بدر؟',
            ['They give us oxygen.', 'They need water and air.', 'I am looking after the plants.'], 1,
            'السؤال: ماذا تحتاج النباتات؟ والجواب: تحتاج إلى الماء والهواء، كما قرأنا في الصفحة 40.'),
          mcq('Anas: What do plants and trees give us? Bader: …', 'أنس: ماذا تعطينا النباتات والأشجار؟ ماذا يجيب بدر؟',
            ['They need water.', 'Yes, you can.', 'They give us oxygen.'], 2,
            'السؤال فيه give us «تعطينا»، فالجواب: They give us oxygen «تعطينا الأكسجين».'),
          mcq('Anas: How can we protect our nature? Bader: …', 'أنس: كيف نستطيع أن نحمي طبيعتنا؟ ماذا يجيب بدر؟',
            ['We must cut down trees.', 'We must keep our nature clean.', 'We must throw rubbish on the ground.'], 1,
            'نحمي الطبيعة عندما نحافظ عليها نظيفة. قطع الأشجار ورمي القمامة على الأرض يؤذيان الطبيعة.'),
          mcq('Anas: Can I water the plants please? Bader: …', 'أنس: هل أستطيع أن أسقي النباتات من فضلك؟ ماذا يجيب بدر؟',
            ['Yes, you can.', 'They need water and air.', 'I am looking after the plants.'], 0,
            'السؤال يبدأ بـ Can I «هل أستطيع»، فالجواب المناسب: Yes, you can «نعم، تستطيع».'),
          // 3b. Read again and find words that mean the following.
          fill('A place from which something comes: ___.', 'مكان يأتي منه الشيء: ___.', 'مكان يأتي منه الشيء: مصدر.',
            u11Words, 2, 'source تعني «مصدر»: المكان الذي يأتي منه الشيء. المطر هو المصدر الرئيسي للماء العذب.'),
          fill('Very important: ___.', 'مهم جداً: ___.', 'مهم جداً: ضروري.',
            u11Words, 1, 'necessary تعني «ضروري»، أي مهم جداً: الماء ضروري للشرب.'),
          fill('Taking air in and out: ___.', 'إدخال الهواء وإخراجه: ___.', 'إدخال الهواء وإخراجه: التنفّس.',
            u11Words, 3, 'breathing تعني «التنفّس»: نُدخل الهواء ونُخرجه.'),
          fill('Living things: ___.', 'الكائنات الحية: ___.', 'الكائنات الحية: المخلوقات.',
            u11Words, 0, 'creatures تعني «مخلوقات»، أي كل الكائنات الحية.'),
          // 6. Choose the correct answer between brackets.
          fill('You ___ be late for your school bus.', '___ تتأخّر عن حافلة المدرسة.', 'يجب ألّا تتأخّر عن حافلة المدرسة.',
            must, 1, "التأخّر عن الحافلة شيء غير جيد، فنستعمل mustn't «يجب ألّا». ولا نقول don't must أبداً."),
          fill('We ___ protect animals.', '___ نحمي الحيوانات.', 'يجب أن نحمي الحيوانات.',
            must, 0, 'حماية الحيوانات شيء جيد ولازم، فنستعمل must «يجب».'),
          fill('People ___ cut down trees.', '___ يقطع الناس الأشجار.', 'يجب ألّا يقطع الناس الأشجار.',
            ["don't must", 'must', "mustn't"], 2, "قطع الأشجار يؤذي الطبيعة، فنستعمل mustn't «يجب ألّا»."),
          fill('Students ___ help to save the environment.', '___ يساعد الطلاب في إنقاذ البيئة.', 'يجب أن يساعد الطلاب في إنقاذ البيئة.',
            ["mustn't", 'must', "don't must"], 1, 'مساعدة البيئة شيء جيد ولازم، فنستعمل must «يجب».'),
          // 7. Write three sentences about water.
          fill('Water is ___ for drinking, cooking, washing and growing food.', 'الماء ___ للشرب والطبخ والغسيل وزراعة الطعام.',
            'الماء ضروري للشرب والطبخ والغسيل وزراعة الطعام.',
            ['dirty', 'necessary', 'salty'], 1, 'جملة عن الماء من نص الصفحة 40: الماء ضروري necessary لأشياء كثيرة في حياتنا.'),
          build('We must keep water clean.', 'يجب أن نحافظ على الماء نظيفاً.'),
          build("We mustn't throw rubbish in the river.", 'يجب ألّا نرمي القمامة في النهر.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Complete the following sentences.',
          topicAr: 'أكمل الجمل التالية عن البيئة.',
          words: 40,
          points: ['The environment is very important.', 'We must …', 'We must …', "We mustn't …", "I mustn't …"],
          pointsAr: ['البيئة مهمة جداً.', 'يجب علينا أن …', 'يجب علينا أن …', 'يجب علينا ألّا …', 'يجب عليّ ألّا …'],
          plan: [
            { en: 'Start with the sentence: The environment is very important.', ar: 'ابدأ بالجملة: البيئة مهمة جداً.' },
            { en: 'Write two things we must do: We must …', ar: 'اكتب شيئين يجب أن نفعلهما: We must …' },
            { en: "Write two things we mustn't do: We mustn't … / I mustn't …", ar: "اكتب شيئين يجب ألّا نفعلهما: We mustn't … / I mustn't …" },
          ],
          phrases: [
            { en: 'The environment is very important.', ar: 'البيئة مهمة جداً.' },
            { en: 'keep our nature clean', ar: 'نحافظ على طبيعتنا نظيفة' },
            { en: 'plant trees', ar: 'نزرع الأشجار' },
            { en: 'water them', ar: 'نسقيها' },
            { en: 'throw rubbish on the ground', ar: 'نرمي القمامة على الأرض' },
            { en: 'cut down trees', ar: 'نقطع الأشجار' },
            { en: 'put the rubbish in the bins', ar: 'نضع القمامة في الحاويات' },
            { en: 'keep our wonderful nature safe', ar: 'نحافظ على طبيعتنا الرائعة آمنة' },
          ],
          model: "The environment is very important. We must keep our nature clean. We must plant trees and water them. We mustn't throw rubbish on the ground. I mustn't cut down trees. We must keep our wonderful nature safe.",
          modelAr: 'البيئة مهمة جداً. يجب أن نحافظ على طبيعتنا نظيفة. يجب أن نزرع الأشجار ونسقيها. يجب ألّا نرمي القمامة على الأرض. يجب عليّ ألّا أقطع الأشجار. يجب أن نحافظ على طبيعتنا الرائعة آمنة.',
          checklistAr: [
            'هل بدأت بالجملة: The environment is very important؟',
            'هل كتبت جملتين بـ must عن أشياء جيدة نفعلها؟',
            "هل كتبت جملتين بـ mustn't عن أشياء تؤذي الطبيعة؟",
            'هل جاء الفعل بعد must وmustn\'t بدون to وبدون s؟',
            'هل بدأت كل جملة بحرف كبير وختمتها بنقطة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Finish this story.',
          topicAr: 'أكمل هذه القصة.',
          words: 40,
          points: ['One day, I went with my friend to the park. We walked between the trees and everything was great. We met some children playing on the grass and throwing rubbish on the ground, so …'],
          pointsAr: ['في يوم من الأيام، ذهبت مع صديقي إلى الحديقة. مشينا بين الأشجار وكان كل شيء رائعاً. قابلنا بعض الأطفال يلعبون على العشب ويرمون القمامة على الأرض، لذلك …'],
          plan: [
            { en: 'Copy the beginning of the story.', ar: 'انسخ بداية القصة كما هي في الكتاب.' },
            { en: "Say what you did: tell the children what they must and mustn't do.", ar: 'قل ماذا فعلت: أخبر الأطفال بما يجب وما لا يجب أن يفعلوه.' },
            { en: 'End the story: say what the children did.', ar: 'اختم القصة: قل ماذا فعل الأطفال بعد ذلك.' },
          ],
          phrases: [
            { en: "You mustn't throw rubbish on the ground.", ar: 'يجب ألّا ترموا القمامة على الأرض.' },
            { en: 'We must keep our nature clean.', ar: 'يجب أن نحافظ على طبيعتنا نظيفة.' },
            { en: 'said sorry', ar: 'اعتذروا' },
            { en: 'put the rubbish in the bins', ar: 'وضعوا القمامة في الحاويات' },
            { en: 'we said to them', ar: 'قلنا لهم' },
            { en: 'the park', ar: 'الحديقة' },
          ],
          model: "One day, I went with my friend to the park. We walked between the trees and everything was great. We met some children playing on the grass and throwing rubbish on the ground, so we said to them, \"You mustn't throw rubbish on the ground. We must keep our nature clean.\" The children said sorry and put the rubbish in the bins.",
          modelAr: 'في يوم من الأيام، ذهبت مع صديقي إلى الحديقة. مشينا بين الأشجار وكان كل شيء رائعاً. قابلنا بعض الأطفال يلعبون على العشب ويرمون القمامة على الأرض، لذلك قلنا لهم: «يجب ألّا ترموا القمامة على الأرض. يجب أن نحافظ على طبيعتنا نظيفة.» فاعتذر الأطفال ووضعوا القمامة في الحاويات.',
          checklistAr: [
            'هل نسخت بداية القصة كما هي؟',
            "هل استعملت must أو mustn't فيما قلته للأطفال؟",
            'هل ختمت القصة بما فعله الأطفال في النهاية؟',
            'هل كتبت الأفعال بالماضي: went, met, said, put؟',
            'هل راجعت الحروف الكبيرة والنقاط؟',
          ],
        },
      ],
      translations: [
        { en: 'All living things need water and air to live.', ar: 'كل الكائنات الحية تحتاج إلى الماء والهواء لتعيش.' },
        { en: 'Water plays an important role in our life.', ar: 'للماء دور مهم في حياتنا.' },
        { en: 'Rain is the main source of fresh water.', ar: 'المطر هو المصدر الرئيسي للماء العذب.' },
        { en: "We can't see it, but we can feel it.", ar: 'لا نستطيع أن نراه، لكننا نستطيع أن نشعر به.' },
        { en: 'Oxygen in the air is important for breathing.', ar: 'الأكسجين الموجود في الهواء مهم للتنفّس.' },
        { en: 'I am looking after the plants.', ar: 'أنا أعتني بالنباتات.' },
        { en: 'We must put the rubbish in the bins not on the ground.', ar: 'يجب أن نضع القمامة في الحاويات وليس على الأرض.' },
        { en: "We mustn't throw rubbish on the ground.", ar: 'يجب ألّا نرمي القمامة على الأرض.' },
        { en: 'The Sun gives light and heat.', ar: 'الشمس تعطي الضوء والحرارة.' },
        { en: "Water covers a large part of the Earth's surface.", ar: 'الماء يغطّي جزءاً كبيراً من سطح الأرض.' },
      ],
    },

    // ===================== UNIT 12 — Jobs (Activity Book pages 42–44) =====================
    u12: {
      workbook: {
        pages: '42–44',
        readings: [
          {
            title: "Yazan's Family",
            paragraphs: [
              "Hello! My name is Yazan. I am a student. I like reading books. My mother's name is Hind. She is a teacher. She works in a school and she likes teaching children. My father's name is Sami. He is a vet. He likes animals. He works in a clinic. My brother's name is Nader. He is a policeman and he is brave.",
            ],
            paragraphsAr: [
              'مرحباً! اسمي يزن. أنا طالب. أحب قراءة الكتب. اسم أمي هند. هي معلّمة. تعمل في مدرسة وتحب تعليم الأطفال. اسم أبي سامي. هو طبيب بيطري. يحب الحيوانات. يعمل في عيادة. اسم أخي نادر. هو شرطي وهو شجاع.',
            ],
            questions: [
              { q: 'Write the names: picture 1 shows a teacher. What is her name?', qAr: 'اكتب الأسماء: في الصورة 1 معلّمة. ما اسمها؟',
                options: ['Hind', 'Sami', 'Nader', 'Yazan'], answer: 0, explainAr: "النص: My mother's name is Hind. She is a teacher. فالمعلّمة اسمها هند." },
              { q: 'Write the names: picture 2 shows a policeman. What is his name?', qAr: 'اكتب الأسماء: في الصورة 2 شرطي. ما اسمه؟',
                options: ['Sami', 'Yazan', 'Nader', 'Hind'], answer: 2, explainAr: "النص: My brother's name is Nader. He is a policeman. فالشرطي اسمه نادر." },
              { q: 'Write the names: picture 3 shows a student with a book. What is his name?', qAr: 'اكتب الأسماء: في الصورة 3 طالب يقرأ كتاباً. ما اسمه؟',
                options: ['Nader', 'Yazan', 'Sami', 'Hind'], answer: 1, explainAr: 'النص: My name is Yazan. I am a student. I like reading books. فالطالب اسمه يزن.' },
              { q: 'Write the names: picture 4 shows a vet with animals. What is his name?', qAr: 'اكتب الأسماء: في الصورة 4 طبيب بيطري مع حيوانات. ما اسمه؟',
                options: ['Yazan', 'Hind', 'Nader', 'Sami'], answer: 3, explainAr: "النص: My father's name is Sami. He is a vet. فالطبيب البيطري اسمه سامي." },
            ],
            trueFalse: [
              { statement: 'Yazan is a vet.', answer: false },
              { statement: "Yazan's mother works in a school.", answer: true },
              { statement: "Yazan's father is a doctor.", answer: false },
              { statement: 'Sami likes animals.', answer: true },
              { statement: 'Nader is a brave policeman.', answer: true },
            ],
          },
        ],
        exercises: [
          // 2. Complete. What do they do? Where do they work?
          mcq('Picture 1 (a woman with children in a classroom): What does she do? Where does she work?',
            'الصورة 1 (امرأة مع أطفال في صفّ): ماذا تعمل؟ وأين تعمل؟',
            ['I am a teacher. I work at a farm.', 'I am a teacher. I work at a school.', 'I am a farmer. I work at a school.'], 1,
            'المعلّمة teacher تعمل في المدرسة school.'),
          mcq('Picture 2 (a man in a white coat with a stethoscope): What does he do? Where does he work?',
            'الصورة 2 (رجل بمعطف أبيض ومعه سمّاعة طبيب): ماذا يعمل؟ وأين يعمل؟',
            ['I am a doctor. I work at a hospital.', 'I am a pilot. I work at a hospital.', 'I am a doctor. I work at a restaurant.'], 0,
            'الطبيب doctor يعمل في المستشفى hospital.'),
          mcq('Picture 3 (a man with a straw hat and a garden tool): What does he do? Where does he work?',
            'الصورة 3 (رجل بقبّعة من القش ومعه أداة زراعية): ماذا يعمل؟ وأين يعمل؟',
            ['I am a cook. I work at a farm.', 'I am a farmer. I work at an office.', 'I am a farmer. I work at a farm.'], 2,
            'المزارع farmer يعمل في المزرعة farm.'),
          mcq('Picture 4 (a woman in a uniform with a stethoscope and papers): What does she do? Where does she work?',
            'الصورة 4 (امرأة بلباس العمل ومعها سمّاعة طبيب وأوراق): ماذا تعمل؟ وأين تعمل؟',
            ['I am a nurse. I work at a hospital.', 'I am a nurse. I work at a fire station.', 'I am a barber. I work at a hospital.'], 0,
            'الممرّضة nurse تعمل في المستشفى hospital وتساعد المرضى.'),
          mcq('Picture 5 (a man in a police uniform and cap): What does he do? Where does he work?',
            'الصورة 5 (رجل بلباس الشرطة وقبّعتها): ماذا يعمل؟ وأين يعمل؟',
            ['I am a policeman. I work at a restaurant.', 'I am a fireman. I work at a police station.', 'I am a policeman. I work at a police station.'], 2,
            'الشرطي policeman يعمل في مركز الشرطة police station.'),
          mcq('Picture 6 (a woman in a helmet): What does she do? Where does she work?',
            'الصورة 6 (امرأة تلبس خوذة): ماذا تعمل؟ وأين تعمل؟',
            ['I am an engineer. I work at an office.', 'I am a engineer. I work at an office.', 'I am an engineer. I work at a salon.'], 0,
            'engineer تبدأ بصوت متحرّك (e)، لذلك نقول an engineer وليس a engineer. والمهندسة تعمل في مكتب office.'),
          // 3. Ask and answer.
          mcq('What do you want to be when you grow up?', 'ماذا تريد أن تصبح عندما تكبر؟',
            ['I work in a clinic.', 'I want to be a doctor.', 'I like to help sick people.'], 1,
            'السؤال عن المستقبل: What do you want to be؟ والجواب: I want to be a doctor «أريد أن أصبح طبيباً».'),
          mcq('Why do you want to be a doctor?', 'لماذا تريد أن تصبح طبيباً؟',
            ['I want to be a doctor when I grow up.', 'Yes, I want to be a doctor.', 'I want to be a doctor because I like to help sick people.'], 2,
            'نجيب عن السؤال بـ Why «لماذا» بكلمة because «لأنّ».'),
          build('I want to be a doctor because I like to help sick people.', 'أريد أن أصبح طبيباً لأنني أحب أن أساعد المرضى.'),
          // 4. Fill in the spaces with these words: works (2) – likes (2) – work – like – am – is (2)
          fill('I ___ a taxi driver.', 'أنا ___ سائق تاكسي.', 'أنا سائق تاكسي.', ['am', 'is', 'are'], 0, 'مع I نستعمل am.'),
          fill('I ___ in the city.', 'أنا ___ في المدينة.', 'أنا أعمل في المدينة.', ['works', 'work', 'am'], 1, 'مع I يبقى الفعل بدون s: I work.'),
          fill('I ___ driving cars.', 'أنا ___ قيادة السيارات.', 'أنا أحب قيادة السيارات.', ['likes', 'work', 'like'], 2, 'مع I نقول like بدون s: I like driving cars.'),
          fill('He ___ a pharmacist.', 'هو ___ صيدلي.', 'هو صيدلي.', ['am', 'are', 'is'], 2, 'مع He نستعمل is.'),
          fill('He ___ at a pharmacy.', 'هو ___ في صيدلية.', 'هو يعمل في صيدلية.', ['work', 'works', 'likes'], 1, 'مع He نضيف s للفعل: He works.'),
          fill('He ___ preparing medicine.', 'هو ___ تحضير الأدوية.', 'هو يحب تحضير الأدوية.', ['likes', 'like', 'is'], 0, 'مع He نضيف s للفعل: He likes.'),
          fill('She ___ a cook.', 'هي ___ طاهية.', 'هي طاهية.', ['is', 'am', 'works'], 0, 'مع She نستعمل is: She is a cook.'),
          fill('She ___ at a restaurant.', 'هي ___ في مطعم.', 'هي تعمل في مطعم.', ['work', 'is', 'works'], 2, 'مع She نضيف s للفعل: She works.'),
          fill('She ___ cooking.', 'هي ___ الطبخ.', 'هي تحب الطبخ.', ['like', 'likes', 'works'], 1, 'مع She نضيف s للفعل: She likes cooking.'),
          // 5. Listen and tick — only item b is answered by the page itself ("Emma the cook").
          mcq('Emma the cook: Where does Emma work?', 'إيما الطاهية: أين تعمل إيما؟', ['In a bank.', 'In a school.', 'In a restaurant.'], 2,
            'إيما طاهية cook، والطاهي يعمل في المطعم restaurant، كما قرأنا: She is a cook. She works at a restaurant.'),
          // 6. Fill in the blanks: how much (2) – how many – how – how tall
          fill("___ are you? — I'm 1.40 m.", '___ أنت؟ — طولي 1.40 متر.', 'كم طولك؟ — طولي 1.40 متر.', how, 3,
            'الجواب طول (1.40 متر)، فنسأل بـ How tall «كم طولك».'),
          fill("___ is this pen? — It's 200 SP.", '___ هذا القلم؟ — سعره 200 ليرة.', 'بكم هذا القلم؟ — سعره 200 ليرة.', how, 0,
            'الجواب سعر (200 ليرة)، فنسأل عن السعر بـ How much «بكم».'),
          fill('___ water do you drink? — A lot.', '___ ماءً تشرب؟ — كثيراً.', 'كم من الماء تشرب؟ — كثيراً.', how, 0,
            'الماء لا نعدّه، فنسأل عن كميّته بـ How much: How much water.'),
          fill('___ students are there in the class? — There are 25 students.', '___ طالباً في الصف؟ — يوجد 25 طالباً.', 'كم طالباً في الصف؟ — يوجد 25 طالباً.', how, 1,
            'الطلاب نعدّهم (1، 2، 3…)، فنسأل بـ How many: How many students.'),
          fill("___ are you? — I'm fine.", '___ حالك؟ — أنا بخير.', 'كيف حالك؟ — أنا بخير.', how, 2,
            'للسؤال عن الحال نقول How are you? «كيف حالك؟».'),
          // 7. Notice and complete: write / writer – sing / singer – run / runner
          fill('A builder ___ a new house.', 'البنّاء ___ بيتاً جديداً.', 'البنّاء يبني بيتاً جديداً.', ['build', 'builder', 'builds'], 2,
            'builder «بنّاء» هو الشخص، وbuild «يبني» هو الفعل. مع A builder (شخص واحد) نقول builds.'),
          fill('A ___ teaches the children.', '___ يعلّم الأطفال.', 'المعلّم يعلّم الأطفال.', ['teach', 'teacher', 'teaches'], 1,
            'نحتاج هنا اسم الشخص: teach + er = teacher «معلّم»، مثل write / writer.'),
          fill('The bus driver ___ carefully.', 'سائق الحافلة ___ بحذر.', 'سائق الحافلة يقود بحذر.', ['drive', 'driver', 'drives'], 2,
            'نحتاج الفعل drive «يقود». مع The bus driver (شخص واحد) نقول drives.'),
          fill('This chess ___ plays very well.', '___ الشطرنج هذا يلعب جيداً جداً.', 'لاعب الشطرنج هذا يلعب جيداً جداً.', ['play', 'player', 'plays'], 1,
            'نحتاج اسم الشخص: play + er = player «لاعب».'),
          fill('Many workers ___ in the supermarket.', 'عمّال كثيرون ___ في السوبرماركت.', 'عمّال كثيرون يعملون في السوبرماركت.', ['works', 'worker', 'work'], 2,
            'workers جمع (أكثر من واحد)، فالفعل يبقى بدون s: work.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Complete the following.',
          topicAr: 'أكمل ما يلي: اكتب عن عمل الشرطية وعن عمل الطاهية.',
          words: 40,
          points: ["She's …", 'She works in a police …', 'She … a police car.', 'She … people.', "She's …", '… works in …', "She … at 5 o'clock in the morning.", 'She wears … .'],
          pointsAr: ['هي …', 'تعمل في … الشرطة.', 'هي … سيارة الشرطة.', 'هي … الناس.', 'هي …', '… تعمل في …', 'هي … في الساعة الخامسة صباحاً.', 'هي تلبس … .'],
          plan: [
            { en: 'The police officer: her job, where she works and what she does.', ar: 'الشرطية: عملها، وأين تعمل، وماذا تفعل.' },
            { en: 'The cook: her job, where she works, when she starts and what she wears.', ar: 'الطاهية: عملها، وأين تعمل، ومتى تبدأ، وماذا تلبس.' },
          ],
          phrases: [
            { en: 'a police officer', ar: 'شرطية' },
            { en: 'a police station', ar: 'مركز الشرطة' },
            { en: 'drives a police car', ar: 'تقود سيارة الشرطة' },
            { en: 'helps people', ar: 'تساعد الناس' },
            { en: 'a cook', ar: 'طاهية' },
            { en: 'a restaurant', ar: 'مطعم' },
            { en: 'gets up', ar: 'تستيقظ' },
            { en: 'a white uniform', ar: 'زيّ أبيض' },
          ],
          model: "She's a police officer. She works in a police station. She drives a police car. She helps people. She's a cook. She works in a restaurant. She gets up at 5 o'clock in the morning. She wears a white uniform.",
          modelAr: 'هي شرطية. تعمل في مركز الشرطة. تقود سيارة الشرطة. تساعد الناس. هي طاهية. تعمل في مطعم. تستيقظ في الساعة الخامسة صباحاً. تلبس زيّاً أبيض.',
          checklistAr: [
            'هل أكملت كل الجمل عن الشرطية وعن الطاهية؟',
            'هل أضفت s للفعل بعد She: works, drives, helps, wears؟',
            'هل ذكرت مكان العمل الصحيح لكل مهنة؟',
            'هل استعملت a قبل اسم المهنة: a cook؟',
            'هل بدأت كل جملة بحرف كبير وختمتها بنقطة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write about your future job.',
          topicAr: 'اكتب عن عملك في المستقبل.',
          words: 40,
          points: ['I want to be a / an …'],
          pointsAr: ['أريد أن أصبح …'],
          plan: [
            { en: 'Say what you want to be: I want to be a / an …', ar: 'قل ماذا تريد أن تصبح: I want to be a / an …' },
            { en: 'Say what this person does, where he or she works and what he or she wears.', ar: 'قل ماذا يفعل صاحب هذه المهنة، وأين يعمل، وماذا يلبس.' },
            { en: 'Say why you want this job: because …', ar: 'قل لماذا تريد هذا العمل: because …' },
          ],
          phrases: [
            { en: 'I want to be', ar: 'أريد أن أصبح' },
            { en: 'a vet', ar: 'طبيب بيطري' },
            { en: 'takes care of sick animals', ar: 'يعتني بالحيوانات المريضة' },
            { en: 'works in a clinic', ar: 'يعمل في عيادة' },
            { en: 'a white uniform', ar: 'زيّ أبيض' },
            { en: 'because I like animals', ar: 'لأنني أحب الحيوانات' },
          ],
          model: 'I want to be a vet. A vet takes care of sick animals. A vet works in a clinic and wears a white uniform. I want to be a vet because I like animals. I want to help sick animals every day.',
          modelAr: 'أريد أن أصبح طبيباً بيطرياً. الطبيب البيطري يعتني بالحيوانات المريضة. يعمل الطبيب البيطري في عيادة ويلبس زيّاً أبيض. أريد أن أصبح طبيباً بيطرياً لأنني أحب الحيوانات. أريد أن أساعد الحيوانات المريضة كل يوم.',
          checklistAr: [
            'هل بدأت بـ I want to be a / an …؟',
            'هل استعملت an قبل المهنة التي تبدأ بصوت متحرّك (an engineer)؟',
            'هل ذكرت أين يعمل صاحب المهنة وماذا يفعل؟',
            'هل ذكرت السبب باستعمال because؟',
            'هل راجعت الحروف الكبيرة والنقاط؟',
          ],
        },
      ],
      translations: [
        { en: 'She works in a school and she likes teaching children.', ar: 'هي تعمل في مدرسة وتحب تعليم الأطفال.' },
        { en: 'He is a policeman and he is brave.', ar: 'هو شرطي وهو شجاع.' },
        { en: 'What do you want to be when you grow up?', ar: 'ماذا تريد أن تصبح عندما تكبر؟' },
        { en: 'I want to be a doctor because I like to help sick people.', ar: 'أريد أن أصبح طبيباً لأنني أحب أن أساعد المرضى.' },
        { en: 'He works on a farm.', ar: 'هو يعمل في مزرعة.' },
        { en: 'He likes growing fruits.', ar: 'هو يحب زراعة الفواكه.' },
        { en: "Sami doesn't like visiting the dentist.", ar: 'سامي لا يحب زيارة طبيب الأسنان.' },
        { en: 'He was frightened but the dentist was kind and gentle.', ar: 'كان خائفاً، لكن طبيب الأسنان كان لطيفاً ورقيقاً.' },
        { en: 'She goes to work by bus.', ar: 'هي تذهب إلى العمل بالحافلة.' },
        { en: 'I wear a white uniform and take care of sick animals.', ar: 'ألبس زيّاً أبيض وأعتني بالحيوانات المريضة.' },
      ],
    },

    // ===================== UNIT 13 — Houses (Activity Book pages 45–47) =====================
    u13: {
      workbook: {
        pages: '45–47',
        readings: [
          {
            title: 'Different Types of Houses',
            paragraphs: [
              'All around the world, people live in different types of houses. That depends on the environment. People live in flats, houses or villas with big swimming pools. Eskimos live in igloos. Igloos are made of huge blocks of ice. In some hot countries, people live in huts made of mud, straw and leaves with no windows. Some Native Americans still live in teepees, which are made of animal skin.',
            ],
            paragraphsAr: [
              'في كل أنحاء العالم، يعيش الناس في أنواع مختلفة من البيوت. وهذا يعتمد على البيئة. يعيش الناس في شقق أو بيوت أو فيلات فيها مسابح كبيرة. يعيش الإسكيمو في بيوت الإيغلو. الإيغلو مصنوع من قطع ضخمة من الجليد. في بعض البلاد الحارّة، يعيش الناس في أكواخ مصنوعة من الطين والقش وأوراق الشجر وليس فيها نوافذ. وما زال بعض الأمريكيين الأصليين يعيشون في خيام التيبي، وهي مصنوعة من جلد الحيوانات.',
            ],
            questions: [
              { q: 'Some Native Americans live in ___.', qAr: 'بعض الأمريكيين الأصليين يعيشون في ___.', options: ['igloos', 'teepees', 'villas'], answer: 1,
                explainAr: 'النص: Some Native Americans still live in teepees «خيام التيبي».' },
              { q: '___ are made of mud, straw and leaves.', qAr: '___ مصنوعة من الطين والقش وأوراق الشجر.', options: ['Huts', 'Igloos', 'Teepees'], answer: 0,
                explainAr: 'النص: huts made of mud, straw and leaves «أكواخ من الطين والقش وأوراق الشجر».' },
              { q: 'Igloos are made of ___ blocks of ice.', qAr: 'الإيغلو مصنوع من قطع ___ من الجليد.', options: ['big', 'small', 'tiny'], answer: 0,
                explainAr: 'النص يقول huge blocks of ice «قطع ضخمة»، وأقرب كلمة لـ huge هي big «كبيرة».' },
            ],
          },
        ],
        exercises: [
          // 1b. Fill in the spaces with the words in the box.
          fill('Teepees are made of ___ skin.', 'خيام التيبي مصنوعة من جلد ___.', 'خيام التيبي مصنوعة من جلد الحيوانات.', u13Box, 1,
            'النص: teepees, which are made of animal skin «جلد الحيوانات».'),
          fill('People live in ___ types of homes.', 'يعيش الناس في أنواع ___ من البيوت.', 'يعيش الناس في أنواع مختلفة من البيوت.', u13Box, 3,
            'different «مختلفة»: people live in different types of houses.'),
          fill('___ have no windows.', '___ ليس فيها نوافذ.', 'الأكواخ ليس فيها نوافذ.', ['Huts', 'Animal', 'Building', 'Different'], 0,
            'النص: huts … with no windows «أكواخ بلا نوافذ».'),
          fill('Some people live in an apartment ___.', 'بعض الناس يعيشون في ___ شقق.', 'بعض الناس يعيشون في بناء شقق.', u13Box, 2,
            'apartment building «بناء فيه شقق كثيرة». apartment كلمة أخرى لـ flat «شقّة».'),
          // 2. Write the comparative or superlative form.
          fill("Leen's villa is ___ than Farah's house. (expensive)", 'فيلا لين ___ من بيت فرح.', 'فيلا لين أغلى من بيت فرح.',
            ['more expensive', 'the most expensive', 'expensiver'], 0,
            'بعدها than، فنستعمل المقارنة. expensive كلمة طويلة، فنقول more expensive «أغلى».'),
          fill('Living in an igloo is ___. (interesting)', 'العيش في الإيغلو ___.', 'العيش في الإيغلو هو الأكثر إثارة للاهتمام.',
            ['more interesting', 'the most interesting', 'interestinger'], 1,
            'لا توجد than، فنستعمل التفضيل: the most interesting «الأكثر إثارة للاهتمام».'),
          fill('Skyscrapers are ___. (modern)', 'ناطحات السحاب ___.', 'ناطحات السحاب هي الأحدث.',
            ['the most modern', 'more modern', 'modernest'], 0,
            'لا توجد than، فنستعمل التفضيل: the most modern «الأحدث».'),
          fill('Living in a hut is ___ than living in a house. (dangerous)', 'العيش في كوخ ___ من العيش في بيت.', 'العيش في كوخ أخطر من العيش في بيت.',
            ['the most dangerous', 'dangerouser', 'more dangerous'], 2,
            'بعدها than، فنستعمل المقارنة: more dangerous «أخطر».'),
          // 3. Find the types of houses and write them (the letter puzzle).
          mcq('Find the type of house in row 2 of the puzzle: i h o u s e', 'ابحث عن نوع البيت المخبّأ في السطر الثاني من الأحرف: i h o u s e',
            ['hut', 'house', 'igloo', 'villa'], 1, 'نقرأ في السطر: h-o-u-s-e = house «بيت».'),
          mcq('Find the type of house in row 6 of the puzzle: m i g l o o', 'ابحث عن نوع البيت المخبّأ في السطر السادس: m i g l o o',
            ['igloo', 'villa', 'teepee', 'cottage'], 0, 'نقرأ في السطر: i-g-l-o-o = igloo «إيغلو»، بيت من الجليد.'),
          mcq('Find the type of house in row 7 of the puzzle: t e e p e e', 'ابحث عن نوع البيت المخبّأ في السطر السابع: t e e p e e',
            ['hut', 'house', 'teepee', 'igloo'], 2, 'السطر كله كلمة واحدة: teepee «خيمة التيبي».'),
          mcq('Find the type of house in column 1, from top to bottom: v i l l a m t', 'ابحث عن نوع البيت في العمود الأول من الأعلى إلى الأسفل: v i l l a m t',
            ['cottage', 'hut', 'house', 'villa'], 3, 'نقرأ من الأعلى: v-i-l-l-a = villa «فيلا».'),
          mcq('Find the type of house in column 3, from top to bottom: c o t t a g e', 'ابحث عن نوع البيت في العمود الثالث من الأعلى إلى الأسفل: c o t t a g e',
            ['villa', 'cottage', 'teepee', 'flat'], 1, 'العمود كله كلمة واحدة: cottage «بيت ريفي صغير».'),
          mcq('Find the type of house in column 4, from top to bottom: h u t a v l p', 'ابحث عن نوع البيت في العمود الرابع من الأعلى إلى الأسفل: h u t a v l p',
            ['hut', 'house', 'flat', 'igloo'], 0, 'نقرأ أول ثلاثة أحرف: h-u-t = hut «كوخ».'),
          // 4. Listen and write true or false — item 1 is answered by the text on page 45.
          tf('Eskimos live in cottages.', 'يعيش الإسكيمو في بيوت ريفية صغيرة (cottages).', false,
            'خطأ. قرأنا في الصفحة 45: Eskimos live in igloos «يعيش الإسكيمو في الإيغلو».'),
          // 5. Look and describe (Tom's house: 115 million SP, 2020, 600 m² · Sami's: 90 million SP, 1990, 400 m² · Jane's: 50 million SP, 1870, 100 m²).
          fill("Sami's house is ___ than Jane's house. (90 million SP / 50 million SP)", 'بيت سامي ___ من بيت جين. (بيت سامي 90 مليون ليرة، وبيت جين 50 مليوناً)',
            'بيت سامي أغلى من بيت جين.', ['more expensive', 'expensiver', 'the most expensive'], 0,
            'هذا مثال الكتاب: بعدها than، فنقول more expensive «أغلى».'),
          fill("Tom's house is ___. (115 million SP)", 'بيت توم ___. (سعره 115 مليون ليرة، وبيت سامي 90 مليوناً، وبيت جين 50 مليوناً)',
            'بيت توم هو الأغلى.', ['the most expensive', 'more expensive', 'the oldest'], 0,
            'بيت توم أغلى البيوت الثلاثة، ولا توجد than، فنقول the most expensive «الأغلى».'),
          fill("Jane's house is ___ than Sami's house. (built in 1870 / built in 1990)", 'بيت جين ___ من بيت سامي. (بيت جين بُني سنة 1870، وبيت سامي سنة 1990)',
            'بيت جين أقدم من بيت سامي.', ['newer', 'older', 'the oldest'], 1,
            'بيت جين بُني قبل بيت سامي بزمن طويل، وبعدها than، فنقول older «أقدم».'),
          fill("Tom's house is the ___. (600 square metres)", 'بيت توم هو ___. (مساحته 600 متر مربّع، وبيت سامي 400، وبيت جين 100)',
            'بيت توم هو الأكبر.', ['bigger', 'smallest', 'biggest'], 2,
            'بيت توم أكبر البيوت الثلاثة، وقبلها the، فنقول the biggest «الأكبر».'),
          fill("Jane's house is ___ than Tom's house. (100 square metres / 600 square metres)", 'بيت جين ___ من بيت توم. (مساحة بيت جين 100 متر مربّع، وبيت توم 600)',
            'بيت جين أصغر من بيت توم.', ['smaller', 'bigger', 'the smallest'], 0,
            'مساحة بيت جين أقل، وبعدها than، فنقول smaller «أصغر».'),
          fill("Tom's house is ___ than Jane's house. (built in 2020 / built in 1870)", 'بيت توم ___ من بيت جين. (بيت توم بُني سنة 2020، وبيت جين سنة 1870)',
            'بيت توم أحدث من بيت جين.', ['modern', 'more modern', 'the most modern'], 1,
            'بيت توم جديد، وبعدها than، فنقول more modern «أحدث».'),
          // 7. Read the dialogue and practise.
          mcq('A: Which type of home do you prefer to live in? B: …', 'أ: أيّ نوع من البيوت تفضّل أن تعيش فيه؟ ماذا يجيب ب؟',
            ["It's made of mud and straw.", 'I prefer to live in a hut.', 'It is small with no windows.'], 1,
            'السؤال عن نوع البيت المفضّل، والجواب: I prefer to live in a hut «أفضّل أن أعيش في كوخ».'),
          mcq('A: What is it made of? B: …', 'أ: ممّ هو مصنوع؟ ماذا يجيب ب؟',
            ['I prefer to live in a hut.', 'It is small with no windows.', "It's made of mud and straw."], 2,
            "What is it made of? «ممّ هو مصنوع؟» والجواب: It's made of mud and straw «مصنوع من الطين والقش»."),
          mcq('A: What does it look like? B: …', 'أ: كيف يبدو شكله؟ ماذا يجيب ب؟',
            ['It is small with no windows.', "It's made of mud and straw.", 'I prefer to live in a hut.'], 0,
            'What does it look like? تسأل عن الشكل، والجواب وصف: صغير وبلا نوافذ.'),
          build('Which type of home do you prefer to live in?', 'أيّ نوع من البيوت تفضّل أن تعيش فيه؟'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Describe your house.',
          topicAr: 'صِف بيتك.',
          words: 40,
          points: ['What type of home do you live in?', 'Is it in the city or in the country?', 'What is it made of?', 'How many rooms are there?', 'Is it modern- beautiful- comfortable?'],
          pointsAr: ['في أيّ نوع من البيوت تعيش؟', 'هل هو في المدينة أم في الريف؟', 'ممّ هو مصنوع؟', 'كم غرفة فيه؟', 'هل هو حديث؟ جميل؟ مريح؟'],
          plan: [
            { en: 'Say what type of home you live in and where it is.', ar: 'قل في أيّ نوع من البيوت تعيش وأين هو.' },
            { en: 'Say what it is made of and how many rooms there are.', ar: 'قل ممّ هو مصنوع وكم غرفة فيه.' },
            { en: 'Describe it and compare it with another home.', ar: 'صِفه وقارنه ببيت آخر.' },
          ],
          phrases: [
            { en: 'I live in a flat', ar: 'أعيش في شقّة' },
            { en: 'in the city', ar: 'في المدينة' },
            { en: 'It is made of', ar: 'إنه مصنوع من' },
            { en: 'There are five rooms', ar: 'فيه خمس غرف' },
            { en: 'modern and comfortable', ar: 'حديث ومريح' },
            { en: 'smaller than', ar: 'أصغر من' },
            { en: 'the coziest', ar: 'الأكثر دفئاً وراحة' },
          ],
          model: "I live in a flat in the city. It is on the third floor of a high building. It is made of stone. There are five rooms: three bedrooms, a living room and a kitchen. My flat is modern and comfortable. It is smaller than my grandfather's villa, but it is the coziest home for me.",
          modelAr: 'أعيش في شقّة في المدينة. إنها في الطابق الثالث من بناء عالٍ. إنها مصنوعة من الحجر. فيها خمس غرف: ثلاث غرف نوم وغرفة جلوس ومطبخ. شقّتي حديثة ومريحة. إنها أصغر من فيلا جدّي، لكنها أدفأ وأريح بيت بالنسبة لي.',
          checklistAr: [
            'هل أجبت عن الأسئلة الخمسة في المهمّة؟',
            'هل ذكرت نوع البيت ومكانه (في المدينة أو في الريف)؟',
            'هل استعملت صفة مقارنة (smaller than / more comfortable than) أو تفضيل (the biggest)؟',
            'هل استعملت There are لعدد الغرف؟',
            'هل راجعت الحروف الكبيرة والنقاط؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Compare between houses in the city and houses in the village.',
          topicAr: 'قارن بين البيوت في المدينة والبيوت في القرية.',
          words: 40,
          plan: [
            { en: 'Say which houses are more expensive.', ar: 'قل أيّ البيوت أغلى.' },
            { en: 'Compare the types of houses, their size and the life around them.', ar: 'قارن أنواع البيوت وحجمها والحياة حولها.' },
            { en: 'End with the houses you prefer.', ar: 'اختم بالبيوت التي تفضّلها.' },
          ],
          phrases: [
            { en: 'more expensive than', ar: 'أغلى من' },
            { en: 'in the city', ar: 'في المدينة' },
            { en: 'in the village', ar: 'في القرية' },
            { en: 'high buildings', ar: 'أبنية عالية' },
            { en: 'skyscrapers', ar: 'ناطحات سحاب' },
            { en: 'bigger', ar: 'أكبر' },
            { en: 'more comfortable', ar: 'أكثر راحة' },
          ],
          model: 'Houses in the city are more expensive than houses in the village. In the city, many people live in flats in high buildings and skyscrapers. Houses in the village are bigger and they have gardens. The city is noisier, but the village is quieter and more beautiful. I think houses in the village are more comfortable.',
          modelAr: 'البيوت في المدينة أغلى من البيوت في القرية. في المدينة، يعيش كثير من الناس في شقق في أبنية عالية وناطحات سحاب. البيوت في القرية أكبر ولها حدائق. المدينة أكثر ضجيجاً، لكن القرية أهدأ وأجمل. أعتقد أن البيوت في القرية أكثر راحة.',
          checklistAr: [
            'هل قارنت بين بيوت المدينة وبيوت القرية؟',
            'هل استعملت than بعد صفة المقارنة؟',
            'هل استعملت more مع الصفات الطويلة (more expensive) وer مع القصيرة (bigger)؟',
            'هل ختمت برأيك؟',
            'هل راجعت الحروف الكبيرة والنقاط؟',
          ],
        },
      ],
      translations: [
        { en: 'People live in flats, houses or villas with big swimming pools.', ar: 'يعيش الناس في شقق أو بيوت أو فيلات فيها مسابح كبيرة.' },
        { en: 'Eskimos live in igloos.', ar: 'يعيش الإسكيمو في الإيغلو.' },
        { en: 'Igloos are made of huge blocks of ice.', ar: 'الإيغلو مصنوع من قطع ضخمة من الجليد.' },
        { en: 'I prefer to live in a hut.', ar: 'أفضّل أن أعيش في كوخ.' },
        { en: "It's made of mud and straw.", ar: 'إنه مصنوع من الطين والقش.' },
        { en: 'It is small with no windows.', ar: 'إنه صغير وليس فيه نوافذ.' },
        { en: 'A house is smaller than a villa.', ar: 'البيت أصغر من الفيلا.' },
        { en: 'The villa is the most expensive.', ar: 'الفيلا هي الأغلى.' },
        { en: 'The new flat is higher and cooler than our house.', ar: 'الشقّة الجديدة أعلى وأبرد من بيتنا.' },
        { en: 'Houses in the city are more expensive than houses in the country.', ar: 'البيوت في المدينة أغلى من البيوت في الريف.' },
      ],
    },

    // ===================== UNIT 14 — At the Sports Centre (Activity Book pages 48–50) =====================
    u14: {
      workbook: {
        pages: '48–50',
        readings: [
          {
            title: 'Football Game',
            paragraphs: [
              "Football is the most popular sport in the world. It's a game with two teams of 11 players, one of them is the goalkeeper. It's played on a rectangular grass field, with a goal at each end of the field.",
              'The Rules of the Game: A player can use any part of his body to score the goal, but not his hands or arms. Only the goalkeeper can use them to stop the ball. The team that scores the most goals by the end of the match wins.',
              'The World Cup: The most famous football competition is the World Cup, which is held every four years. This event is the most widely viewed and famous in the world.',
            ],
            paragraphsAr: [
              'كرة القدم هي الرياضة الأكثر شعبية في العالم. إنها لعبة فيها فريقان، في كل فريق 11 لاعباً، واحد منهم هو حارس المرمى. تُلعب على ملعب عشبي مستطيل، وفي كل طرف من الملعب مرمى.',
              'قواعد اللعبة: يستطيع اللاعب أن يستعمل أيّ جزء من جسمه ليسجّل الهدف، ما عدا يديه وذراعيه. حارس المرمى فقط يستطيع أن يستعملهما ليوقف الكرة. الفريق الذي يسجّل أهدافاً أكثر حتى نهاية المباراة هو الذي يفوز.',
              'كأس العالم: أشهر مسابقة لكرة القدم هي كأس العالم، وتُقام كل أربع سنوات. هذا الحدث هو الأكثر مشاهدة والأشهر في العالم.',
            ],
            questions: [
              { q: 'Football is the ___ sport in the world.', qAr: 'كرة القدم هي الرياضة ___ في العالم.', options: ['oldest', 'newest', 'most famous'], answer: 2,
                explainAr: 'النص: Football is the most popular sport in the world «الأكثر شعبية»، وأقرب خيار لها most famous «الأشهر».' },
              { q: 'A football team consists of ___ players.', qAr: 'يتكوّن فريق كرة القدم من ___ لاعباً.', options: ['ten', 'eleven', 'twelve'], answer: 1,
                explainAr: 'النص: two teams of 11 players، والرقم 11 نكتبه eleven.' },
              { q: "The players can't use their ___ to score.", qAr: 'لا يستطيع اللاعبون أن يستعملوا ___ ليسجّلوا.', options: ['hands', 'legs', 'heads'], answer: 0,
                explainAr: 'النص: … but not his hands or arms «ما عدا يديه وذراعيه».' },
              { q: 'The World Cup happens every ___.', qAr: 'تُقام كأس العالم كل ___.', options: ['year', '2 years', '4 years'], answer: 2,
                explainAr: 'النص: the World Cup, which is held every four years «كل أربع سنوات».' },
            ],
          },
        ],
        exercises: [
          // 1. Match the name of the sport to the picture.
          mcq('Which sport is it? (picture: a bat and a small ball)', 'ما هذه الرياضة؟ (الصورة: مضرب خشبي طويل وكرة صغيرة)',
            ['golf', 'baseball', 'tennis', 'boxing'], 1, 'في البيسبول baseball نضرب الكرة الصغيرة بمضرب خشبي طويل اسمه bat.'),
          mcq('Which sport is it? (picture: a big ball with black lines)', 'ما هذه الرياضة؟ (الصورة: كرة كبيرة عليها خطوط سوداء، نرميها في السلّة)',
            ['basketball', 'volleyball', 'golf', 'table tennis'], 0, 'basketball «كرة السلة»: نرمي الكرة الكبيرة داخل السلّة basket.'),
          mcq('Which sport is it? (picture: a long stick and a very small ball)', 'ما هذه الرياضة؟ (الصورة: عصا طويلة وكرة صغيرة جداً)',
            ['baseball', 'badminton', 'golf', 'boxing'], 2, 'golf «الغولف»: نضرب كرة صغيرة جداً بعصا طويلة stick.'),
          mcq('Which sport is it? (picture: a racket and a ball)', 'ما هذه الرياضة؟ (الصورة: مضرب له شبكة وكرة)',
            ['golf', 'baseball', 'volleyball', 'tennis'], 3, 'tennis «التنس»: نضرب الكرة بمضرب له شبكة racket.'),
          mcq('Which sport is it? (picture: a white ball with curved lines)', 'ما هذه الرياضة؟ (الصورة: كرة بيضاء بخطوط منحنية نضربها بأيدينا فوق الشبكة)',
            ['boxing', 'volleyball', 'golf', 'gymnastics'], 1, 'volleyball «الكرة الطائرة»: نضرب الكرة بأيدينا فوق الشبكة.'),
          mcq('Which sport is it? (picture: a girl bending her body on her hands)', 'ما هذه الرياضة؟ (الصورة: فتاة تثني جسمها وتقف على يديها)',
            ['gymnastics', 'boxing', 'tennis', 'baseball'], 0, 'gymnastics «الجمباز»: حركات مرنة بالجسم.'),
          mcq('Which sport is it? (picture: a small round bat and a small ball)', 'ما هذه الرياضة؟ (الصورة: مضرب صغير مدوّر وكرة صغيرة، نلعبها على طاولة)',
            ['badminton', 'golf', 'table tennis', 'baseball'], 2, 'table tennis «كرة الطاولة»: نلعبها على طاولة بمضرب صغير.'),
          mcq('Which sport is it? (picture: two light rackets and a shuttlecock)', 'ما هذه الرياضة؟ (الصورة: مضربان خفيفان وريشة)',
            ['tennis', 'badminton', 'volleyball', 'boxing'], 1, 'badminton «الريشة الطائرة»: نضرب الريشة بمضرب خفيف.'),
          mcq('Which sport is it? (picture: two big gloves)', 'ما هذه الرياضة؟ (الصورة: قفّازان كبيران)',
            ['golf', 'gymnastics', 'basketball', 'boxing'], 3, 'boxing «الملاكمة»: نلبس فيها قفّازات كبيرة gloves.'),
          // 2. Complete using the verbs. Yesterday, at 3 o'clock … (✓ = yes, ✗ = no in the picture)
          fill("Yesterday, at 3 o'clock, they ___ gymnastics. (do ✓)", 'البارحة، في الساعة الثالثة، ___ الجمباز. (الصورة عليها ✓)',
            'البارحة، في الساعة الثالثة، كانوا يمارسون الجمباز.', ['was doing', 'were doing', "weren't doing"], 1,
            'هذا مثال الكتاب: الصورة عليها ✓ فالجملة مثبتة، ومع they نقول were doing.'),
          fill("Yesterday, at 3 o'clock, they ___ badminton. (play ✗)", 'البارحة، في الساعة الثالثة، ___ الريشة الطائرة. (الصورة عليها ✗)',
            'البارحة، في الساعة الثالثة، لم يكونوا يلعبون الريشة الطائرة.', ['were playing', "weren't playing", "wasn't playing"], 1,
            "هذا مثال الكتاب: الصورة عليها ✗ فالجملة منفية، ومع they نقول weren't playing."),
          fill("Yesterday, at 3 o'clock, he was ___ the ball. (throw ✓)", 'البارحة، في الساعة الثالثة، كان ___ الكرة. (الصورة عليها ✓)',
            'البارحة، في الساعة الثالثة، كان يرمي الكرة.', ['throw', 'throwing', 'throwed'], 1,
            'بعد was نضع الفعل مع ing: was throwing.'),
          fill("Yesterday, at 3 o'clock, he ___ the ball. (hit ✗)", 'البارحة، في الساعة الثالثة، ___ الكرة. (الصورة عليها ✗)',
            'البارحة، في الساعة الثالثة، لم يكن يضرب الكرة.', ["wasn't hitting", "weren't hitting", 'was hitting'], 0,
            "الصورة عليها ✗، ومع he نقول wasn't. ونضاعف t في hitting."),
          fill("Yesterday, at 3 o'clock, we ___ for the boxing match. (train ✓)", 'البارحة، في الساعة الثالثة، ___ لمباراة الملاكمة. (الصورة عليها ✓)',
            'البارحة، في الساعة الثالثة، كنّا نتدرّب لمباراة الملاكمة.', ['was training', 'were training', 'are training'], 1,
            'الصورة عليها ✓، ومع we نقول were training. وكلمة Yesterday تعني الماضي، فلا نستعمل are.'),
          fill("Yesterday, at 3 o'clock, we ___ karate. (do ✗)", 'البارحة، في الساعة الثالثة، ___ الكاراتيه. (الصورة عليها ✗)',
            'البارحة، في الساعة الثالثة، لم نكن نمارس الكاراتيه.', ["weren't doing", "wasn't doing", 'were doing'], 0,
            "الصورة عليها ✗، ومع we نقول weren't doing."),
          // 3. The games: tennis and basketball (the facts the table states).
          tf('In tennis, you hit the ball over a net.', 'في التنس، تضرب الكرة فوق الشبكة.', true,
            'صحيح. في التنس نضرب الكرة بالمضرب فوق الشبكة net.'),
          tf('You play basketball in a team.', 'تلعب كرة السلة ضمن فريق.', true,
            'صحيح. كرة السلة لعبة فِرَق، ولكل فريق عدد من اللاعبين.'),
          tf('In tennis, you throw the ball through a basket.', 'في التنس، ترمي الكرة داخل السلّة.', false,
            'خطأ. نرمي الكرة داخل السلّة basket في كرة السلة basketball، وليس في التنس.'),
          tf('In basketball, you hit the ball over a net.', 'في كرة السلة، تضرب الكرة فوق الشبكة.', false,
            'خطأ. ضرب الكرة فوق الشبكة يكون في التنس. في كرة السلة نرمي الكرة داخل السلّة.'),
          // 4. Look at the pictures then match the sentences.
          fill('I was running with the ball ___', '(الصورة 1: لاعب يركض بالكرة والحَكَم يرفع يده) كنت أركض بالكرة ___',
            'كنت أركض بالكرة عندما أنهى الحَكَم المباراة.', u14Endings, 1,
            'في الصورة 1 الحَكَم يرفع يده لينهي المباراة: when the referee ended the match.'),
          fill('She was doing gymnastics ___', '(الصورة 2: فتاة تسقط عن عارضة الجمباز) كانت تمارس الجمباز ___',
            'كانت تمارس الجمباز عندما سقطت.', u14Endings, 3,
            'في الصورة 2 الفتاة تسقط: when she fell off.'),
          fill('He was playing baseball ___', '(الصورة 3: لاعب بيسبول وساعة تُظهر 00:00) كان يلعب البيسبول ___',
            'كان يلعب البيسبول عندما انتهى الوقت.', u14Endings, 0,
            'الساعة في الصورة 3 تُظهر 00:00، أي انتهى الوقت: when the time was over.'),
          fill('The band was playing music ___', '(الصورة 4: فرقة تعزف والمطر يبدأ) كانت الفرقة تعزف الموسيقى ___',
            'كانت الفرقة تعزف الموسيقى عندما بدأ المطر يهطل.', u14Endings, 2,
            'في الصورة 4 المطر يبدأ بالهطول: when it started to rain.'),
          // 5. Look at the examples and add 'ing' (dance → dancing, hit → hitting, kick → kicking).
          fill('have => ___', 'أضف ing إلى have: ___', 'have ← having', ['haveing', 'having', 'havving'], 1,
            'الفعل ينتهي بـ e: نحذف e ونضيف ing، مثل dance → dancing.'),
          fill('run => ___', 'أضف ing إلى run: ___', 'run ← running', ['runing', 'running', 'runeing'], 1,
            'run قصير: حرف متحرّك واحد (u) ثم حرف ساكن (n)، فنضاعف n، مثل hit → hitting.'),
          fill('throw => ___', 'أضف ing إلى throw: ___', 'throw ← throwing', ['throwing', 'throwwing', 'throweing'], 0,
            'نضيف ing مباشرة، مثل kick → kicking.'),
          fill('smile => ___', 'أضف ing إلى smile: ___', 'smile ← smiling', ['smileing', 'smilling', 'smiling'], 2,
            'الفعل ينتهي بـ e: نحذف e ونضيف ing، مثل dance → dancing.'),
          fill('swim => ___', 'أضف ing إلى swim: ___', 'swim ← swimming', ['swimming', 'swiming', 'swimeing'], 0,
            'swim قصير: حرف متحرّك واحد (i) ثم حرف ساكن (m)، فنضاعف m، مثل hit → hitting.'),
          fill('train => ___', 'أضف ing إلى train: ___', 'train ← training', ['trainning', 'training', 'traineing'], 1,
            'قبل n حرفان متحرّكان (ai)، فلا نضاعف n، ونضيف ing مباشرة: training.'),
          fill('come => ___', 'أضف ing إلى come: ___', 'come ← coming', ['comming', 'comeing', 'coming'], 2,
            'الفعل ينتهي بـ e: نحذف e ونضيف ing: coming.'),
          fill('shop => ___', 'أضف ing إلى shop: ___', 'shop ← shopping', ['shoping', 'shopping', 'shopeing'], 1,
            'shop قصير: حرف متحرّك واحد (o) ثم حرف ساكن (p)، فنضاعف p: shopping.'),
          fill('play => ___', 'أضف ing إلى play: ___', 'play ← playing', ['plaing', 'playying', 'playing'], 2,
            'play ينتهي بـ y، فنضيف ing مباشرة: playing.'),
          // 6a. Match the pictures with the underlined words (player, teams, World Cup, goalkeeper, goal).
          mcq('Match the picture to the underlined word: a man kicking the ball.', 'صِل الصورة بالكلمة: رجل يركل الكرة.',
            ['goal', 'player', 'teams', 'World Cup'], 1, 'player «لاعب»: A player can use any part of his body to score the goal.'),
          mcq('Match the picture to the underlined word: a group of players standing together.', 'صِل الصورة بالكلمة: مجموعة من اللاعبين يقفون معاً.',
            ['goalkeeper', 'goal', 'teams', 'player'], 2, 'team «فريق» مجموعة لاعبين. في النص: two teams of 11 players.'),
          mcq('Match the picture to the underlined word: a big cup.', 'صِل الصورة بالكلمة: كأس كبيرة.',
            ['World Cup', 'teams', 'goal', 'goalkeeper'], 0, 'كأس العالم World Cup أشهر مسابقة لكرة القدم.'),
          mcq('Match the picture to the underlined word: a player jumping to stop the ball with his hands.', 'صِل الصورة بالكلمة: لاعب يقفز ليوقف الكرة بيديه.',
            ['player', 'World Cup', 'teams', 'goalkeeper'], 3, 'goalkeeper «حارس المرمى» هو الوحيد الذي يستعمل يديه ليوقف الكرة.'),
          mcq('Match the picture to the underlined word: a net with a ball in it.', 'صِل الصورة بالكلمة: شبكة داخلها كرة.',
            ['teams', 'goal', 'goalkeeper', 'player'], 1, 'goal «مرمى»: with a goal at each end of the field.'),
          // 7. Reorder.
          build('Ahmed was watching TV when his father arrived.', 'كان أحمد يشاهد التلفاز عندما وصل أبوه.'),
          build("Yesterday at 5 o'clock they were playing badminton.", 'البارحة في الساعة الخامسة كانوا يلعبون الريشة الطائرة.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Write about you.',
          topicAr: 'اكتب عن نفسك: ماذا كنت تفعل عندما حدث شيء ما؟',
          words: 40,
          points: ['I was … when it started to rain.', 'I was … when … .'],
          pointsAr: ['كنت … عندما بدأ المطر يهطل.', 'كنت … عندما … .'],
          plan: [
            { en: 'Write what you were doing when it started to rain.', ar: 'اكتب ماذا كنت تفعل عندما بدأ المطر يهطل.' },
            { en: 'Write two more sentences: I was … when … .', ar: 'اكتب جملتين أخريين: I was … when … .' },
          ],
          phrases: [
            { en: 'I was playing football', ar: 'كنت ألعب كرة القدم' },
            { en: 'when it started to rain', ar: 'عندما بدأ المطر يهطل' },
            { en: 'I was running with the ball', ar: 'كنت أركض بالكرة' },
            { en: 'the referee ended the match', ar: 'أنهى الحَكَم المباراة' },
            { en: 'I was doing my homework', ar: 'كنت أكتب وظيفتي' },
            { en: 'my mum called me', ar: 'نادتني أمي' },
          ],
          model: 'Yesterday, I was playing football with my friends when it started to rain. I was running with the ball when the referee ended the match. In the evening, I was doing my homework when my mum called me.',
          modelAr: 'البارحة، كنت ألعب كرة القدم مع أصدقائي عندما بدأ المطر يهطل. كنت أركض بالكرة عندما أنهى الحَكَم المباراة. في المساء، كنت أكتب وظيفتي عندما نادتني أمي.',
          checklistAr: [
            'هل استعملت I was + فعل مع ing للحدث الطويل؟',
            'هل جاء الفعل بعد when في الماضي البسيط (started, ended, called)؟',
            'هل كتبت ثلاث جمل على الأقل؟',
            'هل بدأت كل جملة بحرف كبير وختمتها بنقطة؟',
          ],
        },
      ],
      translations: [
        { en: 'They were doing gymnastics.', ar: 'كانوا يمارسون الجمباز.' },
        { en: "They weren't playing badminton.", ar: 'لم يكونوا يلعبون الريشة الطائرة.' },
        { en: 'Football is the most popular sport in the world.', ar: 'كرة القدم هي الرياضة الأكثر شعبية في العالم.' },
        { en: 'Only the goalkeeper can use them to stop the ball.', ar: 'حارس المرمى فقط يستطيع أن يستعملهما ليوقف الكرة.' },
        { en: 'Yesterday, we had a sports competition at school.', ar: 'البارحة، كانت عندنا مسابقة رياضية في المدرسة.' },
        { en: 'I played football for our school team.', ar: 'لعبت كرة القدم مع فريق مدرستنا.' },
        { en: 'We were playing very well when it started to rain.', ar: 'كنّا نلعب جيداً جداً عندما بدأ المطر يهطل.' },
        { en: 'My parents were cheering for me.', ar: 'كان أبي وأمي يشجّعانني.' },
        { en: 'We won the match.', ar: 'فزنا بالمباراة.' },
        { en: "They weren't playing table tennis.", ar: 'لم يكونوا يلعبون كرة الطاولة.' },
      ],
    },

    // ===================== UNIT 15 — Sports Equipment (Activity Book pages 51–53) =====================
    u15: {
      workbook: {
        pages: '51–53',
        readings: [
          {
            title: 'Dan, Lea and Toni',
            paragraphs: [
              'I usually play this with my cousins. One player throws the ball carefully. The other tries to hit the ball with a bat. (Dan)',
              "I really enjoy racket sports and I run very fast too. That's why I started playing this sport. (Lea)",
              'Playing this game makes me feel strong. I practice it happily every day. I want to be a black belt. (Toni)',
            ],
            paragraphsAr: [
              'دان: عادةً ألعب هذه اللعبة مع أبناء عمّي. لاعب يرمي الكرة بحذر، واللاعب الآخر يحاول أن يضرب الكرة بالمضرب.',
              'ليا: أنا أستمتع حقاً برياضات المضرب، وأركض بسرعة كبيرة أيضاً. لهذا بدأت ألعب هذه الرياضة.',
              'توني: ممارسة هذه اللعبة تجعلني أشعر بالقوة. أتمرّن عليها بسعادة كل يوم. أريد أن أحصل على الحزام الأسود.',
            ],
            questions: [
              { q: 'Dan: which sport is it? (Volleyball – Baseball)', qAr: 'دان: ما هذه الرياضة؟', options: ['Volleyball', 'Baseball', 'Golf'], answer: 1,
                explainAr: 'دان يتكلّم عن رمي الكرة وضربها بالمضرب bat، وهذه هي البيسبول baseball.' },
              { q: 'Lea: which sport is it? (Tennis – Golf)', qAr: 'ليا: ما هذه الرياضة؟', options: ['Golf', 'Boxing', 'Tennis'], answer: 2,
                explainAr: 'ليا تحب رياضات المضرب racket: إنها التنس tennis. في الغولف نستعمل عصا stick وليس مضرباً.' },
              { q: 'Toni: which sport is it? (Boxing – Karate)', qAr: 'توني: ما هذه الرياضة؟', options: ['Karate', 'Boxing', 'Tennis'], answer: 0,
                explainAr: 'الحزام الأسود black belt نحصل عليه في الكاراتيه karate.' },
              { q: '___ wants to be a black belt.', qAr: '___ يريد أن يحصل على الحزام الأسود.', options: ['Dan', 'Lea', 'Toni'], answer: 2,
                explainAr: 'توني هو الذي قال: I want to be a black belt.' },
            ],
          },
        ],
        exercises: [
          // 1. Write: racket – trainers – trophy – bat – gloves – stick
          fill('It is a ___.', '(الصورة: عصا طويلة للغولف وكرة صغيرة) هذه ___.', 'هذه عصا غولف.', ['bat', 'stick', 'racket'], 1,
            'في الغولف نضرب الكرة بعصا طويلة اسمها stick.'),
          fill('It is a ___.', '(الصورة: كأس عليها رقم 1) هذه ___.', 'هذه كأس.', ['trophy', 'whistle', 'bat'], 0,
            'trophy «كأس» يأخذها الفائز.'),
          fill('They are ___.', '(الصورة: حذاءان رياضيّان) هذه ___.', 'هذه أحذية رياضية.', ['gloves', 'rackets', 'trainers'], 2,
            'trainers «أحذية رياضية». نقول They are لأنها أكثر من واحد.'),
          fill('They are ___.', '(الصورة: قفّازا ملاكمة) هذه ___.', 'هذه قفّازات.', ['trainers', 'gloves', 'sticks'], 1,
            'gloves «قفّازات»، نلبسها في الملاكمة.'),
          fill('It is a ___.', '(الصورة: مضرب خشبي طويل وكرة بيسبول) هذا ___.', 'هذا مضرب بيسبول.', ['bat', 'racket', 'stick'], 0,
            'bat مضرب خشبي طويل نضرب به كرة البيسبول.'),
          fill('It is a ___.', '(الصورة: مضرب له شبكة وريشة) هذا ___.', 'هذا مضرب.', ['stick', 'bat', 'racket'], 2,
            'racket مضرب فيه شبكة، نلعب به التنس والريشة الطائرة.'),
          // 2. Fill in the spaces with: mine – yours – ours – theirs – his – hers
          fill('I bought these new trainers. They are ___.', 'اشتريت هذا الحذاء الرياضي الجديد. إنه ___.', 'اشتريت هذا الحذاء الرياضي الجديد. إنه لي.',
            ['yours', 'mine', 'hers', 'ours'], 1, 'أنا I اشتريت الحذاء، فهو لي: mine.'),
          fill('Hurray!! We won. The trophy is ___.', 'مرحى! فزنا. الكأس ___.', 'مرحى! فزنا. الكأس لنا.',
            ['ours', 'theirs', 'mine', 'his'], 0, 'نحن We فزنا، فالكأس لنا: ours.'),
          fill('She is a tennis player. The racket is ___.', 'هي لاعبة تنس. المضرب ___.', 'هي لاعبة تنس. المضرب لها.',
            ['his', 'hers', 'yours', 'mine'], 1, 'هي She لاعبة التنس، فالمضرب لها: hers.'),
          fill('They are the baseball team. I think this bat is ___.', 'هم فريق البيسبول. أظن أن هذا المضرب ___.', 'هم فريق البيسبول. أظن أن هذا المضرب لهم.',
            ['ours', 'his', 'theirs', 'mine'], 2, 'هم They فريق البيسبول، فالمضرب لهم: theirs.'),
          fill('He is the referee. The whistle is ___.', 'هو الحَكَم. الصفّارة ___.', 'هو الحَكَم. الصفّارة له.',
            ['hers', 'his', 'theirs', 'yours'], 1, 'هو He الحَكَم، فالصفّارة له: his.'),
          fill('You do boxing. Are these gloves ___?', 'أنت تمارس الملاكمة. هل هذه القفّازات ___؟', 'أنت تمارس الملاكمة. هل هذه القفّازات لك؟',
            ['mine', 'ours', 'yours', 'hers'], 2, 'أنت You تمارس الملاكمة، فالقفّازات لك: yours.'),
          // 3a. Match.
          mcq('Match: This is our bat.', 'صِل: هذا مضربنا.',
            ['This racket is yours.', 'This bat is ours.', 'This trophy is theirs.', 'This whistle is mine.'], 1,
            'our bat «مضربنا» = This bat is ours «هذا المضرب لنا». (مثال الكتاب)'),
          mcq('Match: This is your racket.', 'صِل: هذا مضربك.',
            ['This racket is yours.', 'These gloves are his.', 'This bat is ours.', 'This trophy is theirs.'], 0,
            'your racket «مضربك» = This racket is yours «هذا المضرب لك».'),
          mcq('Match: This is their trophy.', 'صِل: هذه كأسهم.',
            ['This whistle is mine.', 'This racket is yours.', 'This trophy is theirs.', 'These trainers are hers.'], 2,
            'their trophy «كأسهم» = This trophy is theirs «هذه الكأس لهم».'),
          mcq('Match: This is my whistle.', 'صِل: هذه صفّارتي.',
            ['These gloves are his.', 'This trophy is theirs.', 'This bat is ours.', 'This whistle is mine.'], 3,
            'my whistle «صفّارتي» = This whistle is mine «هذه الصفّارة لي».'),
          mcq('Match: These are her trainers.', 'صِل: هذه أحذيتها الرياضية.',
            ['These gloves are his.', 'These trainers are hers.', 'This racket is yours.', 'This whistle is mine.'], 1,
            'her trainers «أحذيتها» = These trainers are hers «هذه الأحذية لها».'),
          mcq('Match: These are his gloves.', 'صِل: هذه قفّازاته.',
            ['These trainers are hers.', 'This bat is ours.', 'These gloves are his.', 'This trophy is theirs.'], 2,
            'his gloves «قفّازاته» = These gloves are his «هذه القفّازات له».'),
          // 4a. Choose and write.
          fill('He ran ___.', '(الصورة: ولد يركض بسرعة كبيرة) ركض ___.', 'ركض بسرعة.', ['slowly', 'fast', 'fastly'], 1,
            'الولد في الصورة يركض بسرعة، فنقول fast. انتبه: fast لا تتغيّر، ولا نقول fastly.'),
          fill('She cheered ___.', '(الصورة: فتاة تهتف بمكبّر صوت) هتفت ___.', 'هتفت بصوت عالٍ.', ['loudly', 'quietly', 'loud'], 0,
            'معها مكبّر صوت، فهي تهتف بصوت عالٍ: loudly. نصف الفعل بكلمة تنتهي بـ ly.'),
          fill('He played ___.', '(الصورة: ولد يركل الهواء والكرة خلفه) لعب ___.', 'لعب بشكل سيّئ.', ['well', 'bad', 'badly'], 2,
            'الولد لم يُصب الكرة، فقد لعب بشكل سيّئ: badly. نصف الفعل بـ badly وليس bad.'),
          fill('He went home ___.', '(الصورة: ولد حزين قرب مرمى مكسور) ذهب إلى البيت ___.', 'ذهب إلى البيت حزيناً.', ['happily', 'sadly', 'sad'], 1,
            'الولد في الصورة حزين، فنقول sadly «بحزن».'),
          // 4b. Ask and answer about the pictures.
          mcq('How did he run? (picture: a boy running very fast)', 'كيف ركض؟ (الصورة: ولد يركض بسرعة كبيرة)',
            ['He ran fast.', 'He ran slowly.', 'He runs fast.'], 0,
            'السؤال بالماضي How did he run?، فالجواب بالماضي ran، والولد يركض بسرعة: He ran fast.'),
          mcq('How did she cheer? (picture: a girl with a megaphone)', 'كيف هتفت؟ (الصورة: فتاة تهتف بمكبّر صوت)',
            ['She cheered quietly.', 'She cheers loudly.', 'She cheered loudly.'], 2,
            'الجواب بالماضي cheered، ومكبّر الصوت يعني صوتاً عالياً: She cheered loudly.'),
          // 6. Choose a, b and c (items 2–4; item 1 is with the texts).
          fill('We use a racket in a game of ___.', 'نستعمل المضرب في لعبة ___.', 'نستعمل المضرب في لعبة التنس.', ['baseball', 'tennis', 'karate'], 1,
            'في التنس نستعمل racket. في البيسبول نستعمل bat، والكاراتيه بلا مضرب.'),
          fill('In baseball, the players throw the ball ___.', 'في البيسبول، يرمي اللاعبون الكرة ___.', 'في البيسبول، يرمي اللاعبون الكرة بحذر.', ['carefully', 'badly', 'slowly'], 0,
            'قال دان: One player throws the ball carefully «يرمي الكرة بحذر».'),
          fill('We ___ the ball with a bat.', 'نحن ___ الكرة بالمضرب.', 'نحن نضرب الكرة بالمضرب.', ['throw', 'hit', 'kick'], 1,
            'قال دان: The other tries to hit the ball with a bat. نضرب hit بالمضرب، ونرمي throw باليد، ونركل kick بالقدم.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Choose three adverbs and write sentences about them.',
          topicAr: 'اختر ثلاثة ظروف (كلمات تصف كيف نفعل الشيء) واكتب جملاً بها.',
          words: 40,
          plan: [
            { en: 'Choose three adverbs: quietly, loudly, happily, sadly, slowly, badly, fast, well.', ar: 'اختر ثلاثة ظروف: quietly, loudly, happily, sadly, slowly, badly, fast, well.' },
            { en: 'Write one sentence for each adverb: put it after the verb.', ar: 'اكتب جملة لكل ظرف، وضعه بعد الفعل.' },
          ],
          phrases: [
            { en: 'smiled happily', ar: 'ابتسموا بسعادة' },
            { en: 'cheered loudly', ar: 'هتفت بصوت عالٍ' },
            { en: 'ran slowly', ar: 'ركضوا ببطء' },
            { en: 'the volleyball match', ar: 'مباراة الكرة الطائرة' },
            { en: "my friend's team", ar: 'فريق صديقي' },
            { en: 'were tired', ar: 'كانوا متعبين' },
          ],
          model: "At the end of the match, Sami's team smiled happily. I cheered loudly for my friend's team in the volleyball match. The other team players were tired, so they ran slowly.",
          modelAr: 'في نهاية المباراة، ابتسم فريق سامي بسعادة. هتفت بصوت عالٍ لفريق صديقي في مباراة الكرة الطائرة. كان لاعبو الفريق الآخر متعبين، لذلك ركضوا ببطء.',
          checklistAr: [
            'هل كتبت ثلاث جمل، في كل جملة ظرف واحد؟',
            'هل وضعت الظرف بعد الفعل (smiled happily)؟',
            'هل كتبت الظروف صحيحة: happy → happily, loud → loudly، أما fast وwell فلا تنتهيان بـ ly؟',
            'هل كتبت الأفعال بالماضي بشكل صحيح (ran, cheered, smiled)؟',
            'هل بدأت كل جملة بحرف كبير وختمتها بنقطة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write about your favourite sport.',
          topicAr: 'اكتب عن رياضتك المفضّلة.',
          words: 40,
          plan: [
            { en: 'Name your favourite sport and say where and with whom you play it.', ar: 'اذكر رياضتك المفضّلة، وأين تلعبها ومع مَن.' },
            { en: 'Say what equipment you use and how you play it.', ar: 'قل ما الأدوات التي تستعملها وكيف تلعبها.' },
            { en: 'End with how you play and what you want.', ar: 'اختم بكيف تلعب وماذا تتمنّى.' },
          ],
          phrases: [
            { en: 'My favourite sport is', ar: 'رياضتي المفضّلة هي' },
            { en: 'at the sports centre', ar: 'في المركز الرياضي' },
            { en: 'rackets', ar: 'مضارب' },
            { en: 'hit the ball over a net', ar: 'نضرب الكرة فوق الشبكة' },
            { en: 'very fast', ar: 'بسرعة كبيرة' },
            { en: 'win a trophy', ar: 'أفوز بكأس' },
          ],
          model: 'My favourite sport is tennis. I play it with my sister at the sports centre every Friday. We use rackets and a small ball. You hit the ball over a net. I run very fast and I hit the ball well. I want to win a trophy one day.',
          modelAr: 'رياضتي المفضّلة هي التنس. ألعبها مع أختي في المركز الرياضي كل يوم جمعة. نستعمل المضارب وكرة صغيرة. نضرب الكرة فوق الشبكة. أركض بسرعة كبيرة وأضرب الكرة جيداً. أريد أن أفوز بكأس في يوم من الأيام.',
          checklistAr: [
            'هل ذكرت اسم رياضتك المفضّلة في الجملة الأولى؟',
            'هل ذكرت أدوات الرياضة (racket, bat, ball, gloves…)؟',
            'هل استعملت ظرفاً واحداً على الأقل (fast, well, happily…)؟',
            'هل استعملت المضارع البسيط لما تفعله عادةً (I play, I run)؟',
            'هل راجعت الحروف الكبيرة والنقاط؟',
          ],
        },
      ],
      translations: [
        { en: 'The teams walked quietly to the court.', ar: 'مشى الفريقان بهدوء إلى الملعب.' },
        { en: 'They ran quickly and they played very well.', ar: 'ركضوا بسرعة ولعبوا جيداً جداً.' },
        { en: 'The other team players were tired.', ar: 'كان لاعبو الفريق الآخر متعبين.' },
        { en: 'They ran slowly and they played badly.', ar: 'ركضوا ببطء ولعبوا بشكل سيّئ.' },
        { en: 'I usually play this with my cousins.', ar: 'عادةً ألعب هذه اللعبة مع أبناء عمّي.' },
        { en: 'One player throws the ball carefully.', ar: 'لاعب يرمي الكرة بحذر.' },
        { en: 'I practice it happily every day.', ar: 'أتمرّن عليها بسعادة كل يوم.' },
        { en: 'I want to be a black belt.', ar: 'أريد أن أحصل على الحزام الأسود.' },
        { en: 'These gloves are yours.', ar: 'هذه القفّازات لك.' },
        { en: 'Whose trainers are these?', ar: 'لمن هذه الأحذية الرياضية؟' },
      ],
    },
  },

  // ===================== REVISION 3 (Activity Book pages 54–55) =====================
  progressTest: {
    title: 'Revision 3',
    titleAr: 'المراجعة الثالثة (كتاب الأنشطة): الطبيعة، المهن، البيوت، المركز الرياضي، أدوات الرياضة',
    pages: '54–55',
    exercises: [
      // 1. Choose the correct answer.
      fill("I work in a salon. I have a pair of scissors. I'm a ___.", 'أعمل في صالون. عندي مقصّ. أنا ___.', 'أعمل في صالون. عندي مقصّ. أنا حلّاق.',
        ['cook', 'farmer', 'barber'], 2, 'الحلّاق barber يعمل في الصالون salon ويستعمل المقصّ.'),
      fill('A field where you play football is a ___.', 'الساحة التي تلعب فيها كرة القدم اسمها ___.', 'الساحة التي تلعب فيها كرة القدم اسمها ملعب.',
        ['pitch', 'score', 'team'], 0, 'pitch «ملعب». أما score فتعني النتيجة، وteam تعني الفريق.'),
      fill("It's a very high building. It has many flats. It's a ___.", 'إنه بناء عالٍ جداً. فيه شقق كثيرة. إنه ___.', 'إنه بناء عالٍ جداً. فيه شقق كثيرة. إنه ناطحة سحاب.',
        ['villa', 'skyscraper', 'igloo'], 1, 'skyscraper «ناطحة سحاب»: بناء عالٍ جداً فيه شقق كثيرة.'),
      fill('To do boxing, you need ___.', 'لكي تمارس الملاكمة تحتاج إلى ___.', 'لكي تمارس الملاكمة تحتاج إلى قفّازات.',
        ['rackets', 'bats', 'gloves'], 2, 'في الملاكمة boxing نلبس قفّازات gloves.'),
      // 2. Choose.
      fill('Hala plays badminton. This racket is ___.', 'هالة تلعب الريشة الطائرة. هذا المضرب ___.', 'هالة تلعب الريشة الطائرة. هذا المضرب لها.',
        ['her', 'hers', 'she'], 1, 'في آخر الجملة (لا يوجد اسم بعدها) نقول hers. أما her فتأتي قبل اسم: her racket.'),
      fill('You ___ throw rubbish on the ground.', '___ ترمي القمامة على الأرض.', 'يجب ألّا ترمي القمامة على الأرض.',
        must, 1, "رمي القمامة على الأرض يؤذي البيئة، فنقول mustn't «يجب ألّا»."),
      fill('___ do you go to school?', '___ تذهب إلى المدرسة؟', 'كيف تذهب إلى المدرسة؟',
        ['Who', 'How', 'What'], 1, 'نسأل عن طريقة الذهاب (بالحافلة، مشياً…) بـ How «كيف». Who تسأل عن شخص.'),
      fill('Your house is ___ expensive than mine.', 'بيتك ___ غلاءً من بيتي.', 'بيتك أكثر غلاءً من بيتي.',
        ['most', 'more', 'the most'], 1, 'بعدها than، فنستعمل more للمقارنة بين شيئين.'),
      // 3. Classify: Sport – Jobs – Houses.
      classify('igloo', 2, 'igloo «إيغلو»: بيت من الجليد، فهو من Houses.'),
      classify('engineer', 1, 'engineer «مهندس»: مهنة، فهو من Jobs.'),
      classify('teepee', 2, 'teepee «خيمة التيبي» من جلد الحيوانات: نوع بيت، فهو من Houses.'),
      classify('karate', 0, 'karate «الكاراتيه»: رياضة، فهي من Sport.'),
      classify('barber', 1, 'barber «حلّاق»: مهنة، فهو من Jobs.'),
      classify('boxing', 0, 'boxing «الملاكمة»: رياضة، فهي من Sport.'),
      classify('cook', 1, 'cook «طاهٍ»: مهنة، فهو من Jobs.'),
      classify('flat', 2, 'flat «شقّة»: نوع بيت، فهي من Houses.'),
      classify('baseball', 0, 'baseball «البيسبول»: رياضة، فهي من Sport.'),
      // 4. Look and write.
      build('He must put the rubbish in the bin.', 'يجب أن يضع القمامة في سلّة المهملات.'),
      mcq('Look and write: (picture 2: a girl with a watering can next to a small plant)', 'انظر واكتب: (الصورة 2: فتاة تحمل إبريق سقاية قرب نبتة صغيرة)',
        ["She mustn't water the plants.", 'She must water the plants.', 'She must cut down the trees.'], 1,
        'النبتة تحتاج إلى الماء، فيجب أن تسقيها الفتاة: She must water the plants.'),
      mcq('Look and write: (picture 3: a boy watching TV, his books are on the floor)', 'انظر واكتب: (الصورة 3: ولد يشاهد التلفاز وكتبه على الأرض)',
        ['He must watch TV all day.', "He mustn't do his homework.", 'He must do his homework.'], 2,
        'كتبه متروكة على الأرض وهو يشاهد التلفاز. يجب أن يكتب وظيفته: He must do his homework.'),
      mcq('Look and write: (picture 4: a sick girl in bed, medicine and a glass of water next to her)', 'انظر واكتب: (الصورة 4: فتاة مريضة في السرير وبجانبها دواء وكأس ماء)',
        ['She must take her medicine.', 'She must play football now.', "She mustn't stay in bed."], 0,
        'الفتاة مريضة، فيجب أن تأخذ دواءها: She must take her medicine.'),
      // 5. Correct the mistakes.
      mcq('Correct the mistake: They were sleeping when it start to rain.', 'صحّح الخطأ: كانوا نائمين عندما بدأ المطر يهطل.',
        ['They were sleeping when it starts to rain.', 'They were sleeping when it started to rain.', 'They was sleeping when it started to rain.'], 1,
        'الفعل بعد when يكون في الماضي البسيط: start ← started. ومع They نقول were.'),
      mcq('Correct the mistake: Mine trainers are white and black.', 'صحّح الخطأ: حذائي الرياضي أبيض وأسود.',
        ['My trainers are white and black.', 'Mine trainer are white and black.', 'Me trainers are white and black.'], 0,
        'قبل الاسم (trainers) نستعمل my. أما mine فتأتي وحدها بدون اسم بعدها: They are mine.'),
      mcq('Correct the mistake: The footballer ran quick and scored a goal.', 'صحّح الخطأ: ركض لاعب كرة القدم بسرعة وسجّل هدفاً.',
        ['The footballer run quick and scored a goal.', 'The footballer ran quickly and scored a goal.', 'The footballer ran quicks and scored a goal.'], 1,
        'نصف طريقة الركض بظرف ينتهي بـ ly: quick ← quickly.'),
      mcq("Correct the mistake: You mustn't water the plants.", 'صحّح الخطأ: يجب ألّا تسقي النباتات.',
        ['You must water the plants.', "You mustn't waters the plants.", "You don't must water the plants."], 0,
        "سقاية النباتات شيء جيد ولازم، فنقول must وليس mustn't."),
      // 6. Write the question words.
      fill('___ is her friend? — Her friend is Hala.', '___ صديقتها؟ — صديقتها هالة.', 'مَن صديقتها؟ — صديقتها هالة.',
        ['What', 'Who', 'Where'], 1, 'الجواب شخص (هالة)، فنسأل بـ Who «مَن».'),
      fill("___ is your job? — I'm a teacher.", '___ عملك؟ — أنا معلّم.', 'ما عملك؟ — أنا معلّم.',
        ['What', 'Who', 'When'], 0, 'نسأل عن العمل بـ What «ما».'),
      fill('___ was he playing tennis? — He was playing in the tennis court.', '___ كان يلعب التنس؟ — كان يلعب في ملعب التنس.', 'أين كان يلعب التنس؟ — كان يلعب في ملعب التنس.',
        ['When', 'Why', 'Where'], 2, 'الجواب مكان (ملعب التنس)، فنسأل بـ Where «أين».'),
    ],
  },
}
