import type { GrammarExercise } from '../../../engine/types'
import type { ModuleExtras } from './merge'

// Module 2 — Activity Book pages 22–38: Unit 6 (22–24), Unit 7 (25–27), Unit 8 (28–30), Unit 9 (31–33),
// Unit 10 (34–36) and Revision 2 (37–38). Exercises that need the recording, a drawing or an open personal
// answer are left out or turned into a solvable item with the page's own words.

const fill = (prompt: string, promptAr: string, promptArFull: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, promptAr, promptArFull, options, answer, explainAr })
const mcq = (prompt: string, promptAr: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, promptAr, options, answer, explainAr })
const tf = (prompt: string, promptAr: string, answer: boolean, explainAr: string): GrammarExercise =>
  ({ type: 'truefalse', prompt, promptAr, answer, explainAr })
const build = (answer: string, prompt: string, extraWords?: string[]): GrammarExercise =>
  ({ type: 'build', answer, prompt, ...(extraWords ? { extraWords } : {}) })

// ---------- Unit 8, page 28 ex. 2: the four answers to match ----------
const u8Answers = ['The Wi-Fi', 'Thomas Edison did.', 'She discovered radium.', 'Edward Jenner invented vaccination.']

// ---------- Unit 9, page 31 ex. 2b: the box ----------
const u9Box = ['concert', 'famous', 'musician', 'favourite']

// ---------- Revision 2, page 37 ex. 1: the four groups ----------
const groups = ['Hobbies', 'Inventions', 'Music', 'Technology']
const groupsAr: Record<string, string> = { Hobbies: 'الهوايات', Inventions: 'الاختراعات', Music: 'الموسيقى', Technology: 'التكنولوجيا' }
function classify(word: string, wordAr: string, group: string, why: string): GrammarExercise {
  return mcq(`Classify: "${word}"`, `صنّف كلمة "${word}" (${wordAr}): إلى أيّ مجموعة تنتمي؟`, groups, groups.indexOf(group),
    `${word} تعني «${wordAr}»، ${why} فمكانها في عمود ${group} (${groupsAr[group]}).`)
}

// ---------- Revision 2, page 37 ex. 2: the five answers to match ----------
const r2Answers = ['Yes, I can.', 'I like the violin.', 'Exercise is good for me.', 'I usually use Google.', 'Thomas Edison did.']
function r2Match(q: string, qAr: string, right: number, others: number[], explainAr: string): GrammarExercise {
  const options = [right, ...others].map(i => r2Answers[i]).sort()
  return mcq(`Read and match: "${q}"`, `اقرأ وصِل: ما جواب السؤال «${qAr}»؟`, options, options.indexOf(r2Answers[right]), explainAr)
}

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 6 — Healthy Lifestyle (Activity Book pages 22–24) =====================
    u6: {
      workbook: {
        pages: '22–24',
        readings: [
          {
            title: 'A Healthy Lifestyle',
            paragraphs: [
              'The Thomas family live a healthy life. They have three children, Alice, Tony and baby Grace. They have three meals together: breakfast, lunch and dinner. Mr. and Mrs. Thomas walk to work every morning. Alice and Tony go to school by bicycle. Every day, the family wakes up early. They do exercises in the fresh air. The Thomas family always cooks at home. They eat a lot of fruit and vegetables and drink lots of water. They do everything they need to have a good life. They are very excited about it.',
            ],
            paragraphsAr: [
              'تعيش عائلة توماس حياة صحية. عندهم ثلاثة أولاد: أليس وتوني والطفلة الصغيرة غريس. يأكلون ثلاث وجبات معاً: الفطور والغداء والعشاء. يذهب السيد توماس والسيدة توماس إلى العمل مشياً كل صباح. تذهب أليس وتوني إلى المدرسة بالدراجة. كل يوم تستيقظ العائلة باكراً. يمارسون التمارين في الهواء النقي. عائلة توماس تطبخ في البيت دائماً. يأكلون الكثير من الفواكه والخضار ويشربون الكثير من الماء. يفعلون كل ما يحتاجونه ليعيشوا حياة جيدة. وهم متحمّسون جداً لذلك.',
            ],
            questions: [
              {
                q: 'How do Mr. and Mrs. Thomas go to work?', qAr: 'كيف يذهب السيد والسيدة توماس إلى العمل؟',
                options: ['By bus', 'On foot', 'By bicycle'], answer: 1,
                explainAr: 'يقول النص: "Mr. and Mrs. Thomas walk to work" أي يمشيان إلى العمل، و On foot تعني «مشياً على الأقدام».',
              },
              {
                q: 'How many members are there in the family?', qAr: 'كم عدد أفراد العائلة؟',
                options: ['Three', 'Four', 'Five'], answer: 2,
                explainAr: 'الأب والأم وثلاثة أولاد (أليس وتوني وغريس)، فالمجموع خمسة.',
              },
              {
                q: 'How do they feel about living healthy?', qAr: 'بماذا يشعرون تجاه العيش بطريقة صحية؟',
                options: ['Nervous', 'Excited', 'Sad'], answer: 1,
                explainAr: 'آخر جملة في النص: "They are very excited about it." أي هم متحمّسون جداً.',
              },
              {
                q: 'How do Alice and Tony go to school?', qAr: 'كيف تذهب أليس وتوني إلى المدرسة؟',
                options: ['On foot', 'By car', 'By bicycle'], answer: 2,
                explainAr: 'يقول النص: "Alice and Tony go to school by bicycle." أي بالدراجة.',
              },
            ],
            trueFalse: [
              { statement: 'The family eat together.', answer: true },
              { statement: 'They always go to restaurants.', answer: false },
              { statement: 'They do activities in the fresh air.', answer: true },
            ],
          },
        ],
        exercises: [
          // Ex. 1 — Look and fill in the spaces (get enough sleep · eat healthy food · be active)
          fill('Picture 1 (a plate of fruit, vegetables, grains and fish): ___', 'الصورة ١ (صحن فيه فواكه وخضار وحبوب وسمك): ___',
            'الصورة ١ (صحن فيه فواكه وخضار وحبوب وسمك): تناوَلْ طعاماً صحياً.',
            ['be active', 'eat healthy food', 'get enough sleep'], 1,
            'الصحن مليء بالطعام المفيد، فالعبارة المناسبة eat healthy food أي «تناوَلْ طعاماً صحياً».'),
          fill('Picture 2 (a boy doing exercises): ___', 'الصورة ٢ (ولد يمارس التمارين): ___',
            'الصورة ٢ (ولد يمارس التمارين): كُنْ نشيطاً.',
            ['be active', 'eat healthy food', 'get enough sleep'], 0,
            'الولد يتحرّك ويتمرّن، فالعبارة المناسبة be active أي «كُنْ نشيطاً».'),
          fill('Picture 3 (a boy waking up in his bed): ___', 'الصورة ٣ (ولد يستيقظ في سريره): ___',
            'الصورة ٣ (ولد يستيقظ في سريره): نَمْ وقتاً كافياً.',
            ['eat healthy food', 'be active', 'get enough sleep'], 2,
            'الولد في سريره بعد نوم مريح، فالعبارة المناسبة get enough sleep أي «نَمْ وقتاً كافياً».'),
          // Ex. 2 — Let's play: the page's questions, with the question word to choose
          fill('How ___ hours do you sleep at night?', 'كم ___ ساعة تنام في الليل؟', 'كم ساعة تنام في الليل؟',
            ['much', 'many', 'often'], 1,
            'نستخدم How many مع الأشياء التي نعدّها، مثل hours (ساعات).'),
          fill('How ___ do you walk every day?', 'كم ___ تمشي كل يوم؟', 'كم تمشي كل يوم؟',
            ['many', 'often', 'much'], 2,
            'How much تسأل عن الكمية (كم تمشي)، ولا يوجد بعدها شيء نعدّه.'),
          fill('How ___ do you have a bath?', 'كم ___ تستحمّ؟', 'كم مرة تستحمّ؟',
            ['often', 'many', 'much'], 0,
            'How often تعني «كم مرة»، ونسأل بها عن تكرار الشيء.'),
          fill('How ___ glasses of water do you drink every day?', 'كم ___ كأس ماء تشرب كل يوم؟', 'كم كأس ماء تشرب كل يوم؟',
            ['many', 'much', 'often'], 0,
            'glasses (كؤوس) أشياء نعدّها، فنقول How many.'),
          // Ex. 3 — Look at the pictures and say (Good for you) or (Bad for you)
          tf('Picture 1 (a girl eating ice cream): This is good for you.', 'الصورة ١ (بنت تأكل البوظة): هذا مفيد لك.', false,
            'الإكثار من الحلويات مثل البوظة Bad for you أي «مضرّ لك».'),
          tf('Picture 2 (a boy doing exercises): This is good for you.', 'الصورة ٢ (ولد يمارس التمارين): هذا مفيد لك.', true,
            'التمارين تجعل جسمك قوياً، فهي Good for you أي «مفيدة لك».'),
          tf('Picture 3 (watching TV in an armchair): This is good for you.', 'الصورة ٣ (الجلوس على الكرسي أمام التلفاز): هذا مفيد لك.', false,
            'الجلوس طويلاً أمام التلفاز Bad for you أي «مضرّ لك»، والأفضل أن تتحرّك.'),
          tf('Picture 4 (a bowl of fruit and vegetables): This is good for you.', 'الصورة ٤ (وعاء فيه فواكه وخضار): هذا مفيد لك.', true,
            'الفواكه والخضار مليئة بالفيتامينات، فهي Good for you أي «مفيدة لك».'),
          // Ex. 5 — Read and choose (Taim and the doctor)
          fill('Taim: Doctor, can you tell me how to stay ___?', 'تيم: أيها الطبيب، هل تستطيع أن تخبرني كيف أبقى ___؟',
            'تيم: أيها الطبيب، هل تستطيع أن تخبرني كيف أبقى بصحة جيدة؟',
            ['problem', 'healthy', 'late'], 1,
            'تيم يريد أن يبقى بصحة جيدة، فالكلمة healthy. أما problem فتعني «مشكلة» ولا تناسب.'),
          fill('Doctor: Well. First of all you should ___.', 'الطبيب: حسناً. أولاً يجب أن ___.',
            'الطبيب: حسناً. أولاً يجب أن تأكل الطعام الصحيح.',
            ['eat the right food', 'watch too much TV', 'sleep late'], 0,
            'بعد should تأتي نصيحة مفيدة. مشاهدة التلفاز كثيراً والسهر ليستا نصيحة جيدة.'),
          fill('Doctor: You ___ eat a lot of fresh fruit and vegetables, along with grains and fish.', 'الطبيب: ___ تأكل الكثير من الفواكه والخضار الطازجة، مع الحبوب والسمك.',
            'الطبيب: يجب أن تأكل الكثير من الفواكه والخضار الطازجة، مع الحبوب والسمك.',
            ['shouldn’t', 'should', 'don’t'], 1,
            'الفواكه والخضار مفيدة، فالطبيب ينصح بأكلها ويقول should (يجب أن).'),
          fill('Doctor: You should ___.', 'الطبيب: يجب أن ___.', 'الطبيب: يجب أن تكون نشيطاً.',
            ['sleep late', 'eat many sweets', 'be active'], 2,
            'الطبيب ينصح بشيء مفيد: be active أي «كُنْ نشيطاً».'),
          fill('You should do ___ with your friends.', 'يجب أن تمارس ___ مع أصدقائك.', 'يجب أن تمارس الرياضة مع أصدقائك.',
            ['sports', 'computer', 'television'], 0,
            'نقول do sports أي «نمارس الرياضة»، وهي مفيدة مع الأصدقاء.'),
          // Ex. 7 — Read and write (shouldn't · Why don't you · should)
          fill('You ___ turn off the computer and get active.', '___ أن تطفئ الحاسوب وتتحرّك بنشاط.', 'يجب أن تطفئ الحاسوب وتتحرّك بنشاط.',
            ['should', 'shouldn’t', 'Why don’t you'], 0,
            'إطفاء الحاسوب والحركة شيء مفيد، فنقول should (يجب أن).'),
          fill('You ___ go to bed too late.', '___ أن تذهب إلى السرير متأخراً جداً.', 'لا ينبغي أن تذهب إلى السرير متأخراً جداً.',
            ['should', 'shouldn’t', 'Why don’t you'], 1,
            'النوم متأخراً مضرّ، فنقول shouldn’t (لا ينبغي أن).'),
          fill('___ go for a walk in the morning?', '___ تتمشّى في الصباح؟', 'لماذا لا تتمشّى في الصباح؟',
            ['should', 'shouldn’t', 'Why don’t you'], 2,
            'الجملة سؤال تنتهي بعلامة ؟، فنبدأ بـ Why don’t you (لماذا لا…؟) لنقدّم نصيحة لطيفة.'),
          fill('You ___ eat different kinds of foods.', '___ أن تأكل أنواعاً مختلفة من الطعام.', 'يجب أن تأكل أنواعاً مختلفة من الطعام.',
            ['should', 'shouldn’t', 'Why don’t you'], 0,
            'أكل أنواع مختلفة من الطعام مفيد، فنقول should (يجب أن).'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Write advice to your friend on how to live a healthy life.',
          topicAr: 'اكتب نصائح لصديقك عن كيف يعيش حياة صحية.',
          words: 40,
          points: ['You should …', 'You shouldn’t …', 'Why don’t you … ?'],
          pointsAr: ['يجب أن …', 'لا ينبغي أن …', 'لماذا لا … ؟'],
          plan: [
            { en: 'Give good advice with "You should …".', ar: 'قدّم نصائح مفيدة تبدأ بـ You should (يجب أن).' },
            { en: 'Say what is bad for your friend with "You shouldn’t …".', ar: 'قل ما هو مضرّ لصديقك بـ You shouldn’t (لا ينبغي أن).' },
            { en: 'End with a kind idea: "Why don’t you … ?"', ar: 'اختم بفكرة لطيفة على شكل سؤال: Why don’t you … ? (لماذا لا …؟)' },
          ],
          phrases: [
            { en: 'You should get enough sleep.', ar: 'يجب أن تنام وقتاً كافياً.' },
            { en: 'You shouldn’t eat many sweets.', ar: 'لا ينبغي أن تأكل الكثير من الحلويات.' },
            { en: 'Why don’t you walk for an hour every day?', ar: 'لماذا لا تمشي ساعة كل يوم؟' },
            { en: 'drink lots of water', ar: 'يشرب الكثير من الماء' },
            { en: 'a lot of fruit and vegetables', ar: 'الكثير من الفواكه والخضار' },
            { en: 'be active', ar: 'يكون نشيطاً' },
            { en: 'get some fresh air', ar: 'يستنشق بعض الهواء النقي' },
            { en: 'playing computer games', ar: 'اللعب بألعاب الحاسوب' },
          ],
          model: 'Dear friend, you should eat a lot of fruit and vegetables and drink lots of water every day. You should get enough sleep. You shouldn’t eat many sweets. You shouldn’t spend a long time playing computer games. Why don’t you walk for an hour every day?',
          modelAr: 'صديقي العزيز، يجب أن تأكل الكثير من الفواكه والخضار وأن تشرب الكثير من الماء كل يوم. يجب أن تنام وقتاً كافياً. لا ينبغي أن تأكل الكثير من الحلويات. لا ينبغي أن تقضي وقتاً طويلاً في ألعاب الحاسوب. لماذا لا تمشي ساعة كل يوم؟',
          checklistAr: [
            'هل كتبت نصيحة واحدة على الأقل بـ You should؟',
            'هل كتبت نصيحة واحدة على الأقل بـ You shouldn’t؟',
            'هل كتبت سؤالاً يبدأ بـ Why don’t you وينتهي بعلامة ؟',
            'هل وضعت الفعل بعد should و shouldn’t بدون to وبدون s؟',
            'هل بدأت كل جملة بحرف كبير وأنهيتها بنقطة أو علامة سؤال؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write about what you do to keep healthy.',
          topicAr: 'اكتب عمّا تفعله لتحافظ على صحتك.',
          words: 40,
          plan: [
            { en: 'Start with a first sentence: "I do many things to keep healthy."', ar: 'ابدأ بجملة أولى: أفعل أشياء كثيرة لأحافظ على صحتي.' },
            { en: 'Say what you eat and drink.', ar: 'اذكر ماذا تأكل وماذا تشرب.' },
            { en: 'Say how you exercise and how many hours you sleep.', ar: 'اذكر كيف تتمرّن وكم ساعة تنام.' },
          ],
          phrases: [
            { en: 'keep healthy', ar: 'يحافظ على صحته' },
            { en: 'wake up early', ar: 'يستيقظ باكراً' },
            { en: 'I exercise every day.', ar: 'أتمرّن كل يوم.' },
            { en: 'I eat a lot of fruit and vegetables.', ar: 'آكل الكثير من الفواكه والخضار.' },
            { en: 'drink lots of water', ar: 'يشرب الكثير من الماء' },
            { en: 'in the fresh air', ar: 'في الهواء النقي' },
            { en: 'I usually sleep about 8 hours.', ar: 'أنام عادةً حوالي ٨ ساعات.' },
          ],
          model: 'I do many things to keep healthy. Every day, I wake up early and I exercise in the fresh air. I eat a lot of fruit and vegetables and I drink lots of water. I don’t eat many sweets. I usually sleep about 8 hours every night.',
          modelAr: 'أفعل أشياء كثيرة لأحافظ على صحتي. كل يوم أستيقظ باكراً وأتمرّن في الهواء النقي. آكل الكثير من الفواكه والخضار وأشرب الكثير من الماء. لا آكل الكثير من الحلويات. أنام عادةً حوالي ٨ ساعات كل ليلة.',
          checklistAr: [
            'هل ذكرت ماذا تأكل وماذا تشرب؟',
            'هل ذكرت الرياضة أو الحركة التي تقوم بها؟',
            'هل ذكرت النوم؟',
            'هل استخدمت المضارع البسيط (I eat, I drink, I sleep) للعادات اليومية؟',
            'هل كتبت حوالي 40 كلمة وراجعت التهجئة؟',
          ],
        },
      ],
      translations: [
        { en: 'You should get enough sleep.', ar: 'يجب أن تنام وقتاً كافياً.' },
        { en: 'You shouldn’t spend a long time playing computer games.', ar: 'لا ينبغي أن تقضي وقتاً طويلاً في ألعاب الحاسوب.' },
        { en: 'Why don’t you walk for an hour every day?', ar: 'لماذا لا تمشي ساعة كل يوم؟' },
        { en: 'Exercise is good for me.', ar: 'التمارين مفيدة لي.' },
        { en: 'Eating too many sweets is bad for me.', ar: 'أكل الكثير من الحلويات مضرّ لي.' },
        { en: 'The Thomas family live a healthy life.', ar: 'تعيش عائلة توماس حياة صحية.' },
        { en: 'Every day, the family wakes up early.', ar: 'كل يوم تستيقظ العائلة باكراً.' },
        { en: 'They do exercises in the fresh air.', ar: 'يمارسون التمارين في الهواء النقي.' },
        { en: 'Healthy food is delicious.', ar: 'الطعام الصحي لذيذ.' },
      ],
    },

    // ===================== UNIT 7 — Hobbies (Activity Book pages 25–27) =====================
    u7: {
      workbook: {
        pages: '25–27',
        readings: [
          {
            title: 'Rana’s Favourite Hobby',
            paragraphs: [
              'Rana is a clever girl. She lives in Aleppo. She usually helps her mother, but she prefers cooking. She cooks in her free time and at the weekends. Rana enjoys preparing food for her family. Her favourite food is rice and chicken and she can make pizza and sweets. Cooking is an interesting hobby for her.',
            ],
            paragraphsAr: [
              'رنا بنت ذكية. تعيش في حلب. هي عادةً تساعد أمها، لكنها تفضّل الطبخ. تطبخ في وقت فراغها وفي عطلة نهاية الأسبوع. تستمتع رنا بتحضير الطعام لعائلتها. طعامها المفضّل هو الرز مع الدجاج، وتستطيع أن تصنع البيتزا والحلويات. الطبخ هواية ممتعة بالنسبة لها.',
            ],
            questions: [
              {
                q: 'What is Rana’s hobby?', qAr: 'ما هي هواية رنا؟',
                options: ['Reading', 'Dancing', 'Cooking'], answer: 2,
                explainAr: 'يقول النص: "Cooking is an interesting hobby for her." فهوايتها الطبخ.',
              },
              {
                q: 'When does she cook?', qAr: 'متى تطبخ؟',
                options: ['In her free time', 'On Sunday', 'After school'], answer: 0,
                explainAr: 'يقول النص: "She cooks in her free time" أي في وقت فراغها.',
              },
              {
                q: 'What does she prefer doing?', qAr: 'ماذا تفضّل أن تفعل؟',
                options: ['Preparing food', 'Watching TV', 'Reading'], answer: 0,
                explainAr: 'هي تفضّل الطبخ (she prefers cooking) وتستمتع بتحضير الطعام (preparing food).',
              },
              {
                q: 'What can she make?', qAr: 'ماذا تستطيع أن تصنع؟',
                options: ['Salad', 'Chicken', 'Pizza and sweets'], answer: 2,
                explainAr: 'يقول النص: "she can make pizza and sweets" أي تستطيع أن تصنع البيتزا والحلويات.',
              },
            ],
          },
        ],
        exercises: [
          // Ex. 1b — Read again and fill in the spaces (favourite · helps · interesting · pizza)
          fill('Rana usually ___ her mother.', 'رنا عادةً ___ أمها.', 'رنا عادةً تساعد أمها.',
            ['favourite', 'helps', 'interesting', 'pizza'], 1,
            'helps تعني «تساعد»، وهي الفعل الذي يناسب «أمها». في النص: She usually helps her mother.'),
          fill('Her ___ food is rice and chicken.', 'طعامها ___ هو الرز مع الدجاج.', 'طعامها المفضّل هو الرز مع الدجاج.',
            ['favourite', 'helps', 'interesting', 'pizza'], 0,
            'favourite تعني «المفضّل». في النص: Her favourite food is rice and chicken.'),
          fill('Rana likes making ___ and sweets.', 'تحبّ رنا صنع ___ والحلويات.', 'تحبّ رنا صنع البيتزا والحلويات.',
            ['favourite', 'helps', 'interesting', 'pizza'], 3,
            'في النص: she can make pizza and sweets، فالكلمة pizza (بيتزا).'),
          fill('Cooking is an ___ hobby.', 'الطبخ هواية ___.', 'الطبخ هواية ممتعة.',
            ['favourite', 'helps', 'interesting', 'pizza'], 2,
            'interesting تعني «ممتعة / مشوّقة»، ونقول an قبلها لأنها تبدأ بحرف i.'),
          // Ex. 2 — Look at these pictures and describe what they can do
          fill('(a girl at an easel) She can ___ in her free time.', '(بنت أمام لوحة الرسم) تستطيع أن ___ في وقت فراغها.', '(بنت أمام لوحة الرسم) تستطيع أن ترسم بالألوان في وقت فراغها.',
            ['painting', 'paint', 'paints'], 1,
            'بعد can يأتي الفعل بشكله الأساسي: can paint، بدون ing وبدون s.'),
          fill('(a boy with small plants) He can ___ flowers in his free time.', '(ولد بجانب نباتات صغيرة) يستطيع أن ___ الأزهار في وقت فراغه.', '(ولد بجانب نباتات صغيرة) يستطيع أن يزرع الأزهار في وقت فراغه.',
            ['plant', 'planting', 'plants'], 0,
            'بعد can يأتي الفعل بشكله الأساسي: can plant.'),
          fill('(a girl in the kitchen) She can ___ in her free time.', '(بنت في المطبخ) تستطيع أن ___ في وقت فراغها.', '(بنت في المطبخ) تستطيع أن تطبخ في وقت فراغها.',
            ['cooks', 'cook', 'cooking'], 1,
            'بعد can لا نضيف s ولا ing: She can cook.'),
          fill('(a girl with a book) She can ___ in her free time.', '(بنت أمامها كتاب) تستطيع أن ___ في وقت فراغها.', '(بنت أمامها كتاب) تستطيع أن تقرأ في وقت فراغها.',
            ['reading', 'reads', 'read'], 2,
            'بعد can يأتي الفعل بشكله الأساسي: She can read.'),
          fill('(a girl with music notes) She can ___ in her free time.', '(بنت حولها نوتات موسيقية) تستطيع أن ___ في وقت فراغها.', '(بنت حولها نوتات موسيقية) تستطيع أن تغنّي في وقت فراغها.',
            ['sing', 'sings', 'singing'], 0,
            'بعد can يأتي الفعل بشكله الأساسي: She can sing.'),
          // Ex. 3 — Ask and answer about yourselves
          mcq('Salma: What do you do for fun, Ruba? — What does Ruba answer?', 'سلمى: ماذا تفعلين للتسلية يا ربا؟ — بماذا تجيب ربا؟',
            ['Yes, I can.', 'I paint in my free time.', 'In Aleppo.'], 1,
            'السؤال عن الهواية، والجواب في الحوار: I paint in my free time أي «أرسم في وقت فراغي».'),
          // Ex. 6 — Choose the correct answer
          fill('She can ___ the piano.', 'هي تستطيع أن ___ على البيانو.', 'هي تستطيع أن تعزف على البيانو.',
            ['playing', 'play', 'plays'], 1,
            'بعد can يأتي الفعل بشكله الأساسي بدون ing وبدون s: can play.'),
          fill('It is raining. They ___ go to the mountains.', 'إنها تمطر. هم ___ الذهاب إلى الجبال.', 'إنها تمطر. هم لا يستطيعون الذهاب إلى الجبال.',
            ['can', 'can’t', 'is'], 1,
            'المطر يمنعهم من الذهاب، فنقول can’t (لا يستطيعون).'),
          fill('My family ___ live in the country because we don’t have a house.', 'عائلتي ___ العيش في الريف لأنه ليس عندنا بيت هناك.', 'عائلتي لا تستطيع العيش في الريف لأنه ليس عندنا بيت هناك.',
            ['can', 'can’t', 'is'], 1,
            'السبب: ليس عندهم بيت، إذاً لا يستطيعون العيش هناك: can’t.'),
          fill('Sandy is clever. She ___ pass her exams.', 'ساندي ذكية. هي ___ أن تنجح في امتحاناتها.', 'ساندي ذكية. هي تستطيع أن تنجح في امتحاناتها.',
            ['can', 'can’t', 'is'], 0,
            'ساندي ذكية، إذاً هي تستطيع أن تنجح: can.'),
          fill('He is too young. He ___ drive a car.', 'هو صغير جداً. هو ___ أن يقود سيارة.', 'هو صغير جداً. هو لا يستطيع أن يقود سيارة.',
            ['can’t', 'can', 'is'], 0,
            'الصغير لا يُسمح له بقيادة السيارة، فنقول can’t (لا يستطيع).'),
          // Ex. 7 — Complete the dialogue
          mcq('Sara: What is your favourite hobby? Nada: ___', 'سارة: ما هوايتك المفضّلة؟ ندى: ___',
            ['In my free time.', 'My favourite hobby is cooking.', 'Yes, I can.'], 1,
            'السؤال عن الهواية المفضّلة، فالجواب يذكر الهواية: My favourite hobby is …'),
          mcq('Sara: ___? Nada: In my free time.', 'سارة: ___؟ ندى: في وقت فراغي.',
            ['When do you usually do it', 'What is your favourite food', 'How old are you'], 0,
            'الجواب «في وقت فراغي» يخبرنا عن الوقت، فالسؤال يبدأ بـ When (متى).'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Write three sentences about your favourite hobby.',
          topicAr: 'اكتب ثلاث جمل عن هوايتك المفضّلة.',
          words: 40,
          points: ['My favourite hobby is …', 'I …', 'I …'],
          pointsAr: ['هوايتي المفضّلة هي …', 'أنا … (ماذا تفعل أو تستطيع أن تفعل)', 'أنا … (متى أو لماذا تحبّها)'],
          plan: [
            { en: 'Sentence 1: name your favourite hobby.', ar: 'الجملة ١: اذكر هوايتك المفضّلة.' },
            { en: 'Sentence 2: say what you can do and when.', ar: 'الجملة ٢: قل ماذا تستطيع أن تفعل ومتى.' },
            { en: 'Sentence 3: say why you like it.', ar: 'الجملة ٣: قل لماذا تحبّها.' },
          ],
          phrases: [
            { en: 'My favourite hobby is …', ar: 'هوايتي المفضّلة هي …' },
            { en: 'I can read in my free time.', ar: 'أستطيع أن أقرأ في وقت فراغي.' },
            { en: 'I go to the library every week.', ar: 'أذهب إلى المكتبة كل أسبوع.' },
            { en: 'adventure stories', ar: 'قصص المغامرات' },
            { en: 'very interesting', ar: 'ممتعة جداً' },
            { en: 'painting / drawing / cooking / playing chess', ar: 'الرسم بالألوان / الرسم / الطبخ / لعب الشطرنج' },
          ],
          model: 'My favourite hobby is reading. I can read in my free time and I go to the library every week to borrow some books. I like adventure stories because they are very interesting.',
          modelAr: 'هوايتي المفضّلة هي القراءة. أستطيع أن أقرأ في وقت فراغي، وأذهب إلى المكتبة كل أسبوع لأستعير بعض الكتب. أحبّ قصص المغامرات لأنها ممتعة جداً.',
          checklistAr: [
            'هل كتبت ثلاث جمل؟',
            'هل بدأت بـ My favourite hobby is …؟',
            'هل استخدمت can مع الفعل بشكله الأساسي (I can read)؟',
            'هل بدأت كل جملة بحرف كبير وأنهيتها بنقطة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write a paragraph about your friend’s favourite hobby.',
          topicAr: 'اكتب فقرة عن الهواية المفضّلة لصديقك.',
          words: 40,
          plan: [
            { en: 'Start with "My friend …" and name the hobby.', ar: 'ابدأ بـ My friend … واذكر الهواية.' },
            { en: 'Say when your friend does it and what he or she can do.', ar: 'قل متى يمارسها صديقك وماذا يستطيع أن يفعل.' },
            { en: 'End with what the hobby means to your friend.', ar: 'اختم بما تعنيه الهواية لصديقك.' },
          ],
          phrases: [
            { en: 'My friend … loves …', ar: 'صديقي … يحبّ …' },
            { en: 'in his free time', ar: 'في وقت فراغه' },
            { en: 'at the weekends', ar: 'في عطلة نهاية الأسبوع' },
            { en: 'He can …', ar: 'يستطيع أن …' },
            { en: 'the Syrian National Gallery', ar: 'المتحف الوطني السوري للفنون' },
            { en: 'is an interesting hobby for him', ar: 'هواية ممتعة بالنسبة له' },
          ],
          model: 'My friend Adam loves painting. It is his favourite hobby. He paints in his free time and at the weekends. He can paint trees, flowers and animals. He loves going to the Syrian National Gallery. Painting is an interesting hobby for him.',
          modelAr: 'صديقي آدم يحبّ الرسم بالألوان. إنه هوايته المفضّلة. يرسم في وقت فراغه وفي عطلة نهاية الأسبوع. يستطيع أن يرسم الأشجار والأزهار والحيوانات. يحبّ الذهاب إلى المتحف الوطني السوري للفنون. الرسم هواية ممتعة بالنسبة له.',
          checklistAr: [
            'هل بدأت بـ My friend وذكرت اسم الهواية؟',
            'هل أضفت s إلى الفعل مع he أو she (He paints, She cooks)؟',
            'هل استخدمت can مع الفعل بشكله الأساسي (He can paint)؟',
            'هل ذكرت متى يمارس صديقك هوايته؟',
            'هل كتبت حوالي 40 كلمة وراجعت التهجئة؟',
          ],
        },
      ],
      translations: [
        { en: 'Rana is a clever girl.', ar: 'رنا بنت ذكية.' },
        { en: 'She cooks in her free time and at the weekends.', ar: 'تطبخ في وقت فراغها وفي عطلة نهاية الأسبوع.' },
        { en: 'Her favourite food is rice and chicken.', ar: 'طعامها المفضّل هو الرز مع الدجاج.' },
        { en: 'Cooking is an interesting hobby for her.', ar: 'الطبخ هواية ممتعة بالنسبة لها.' },
        { en: 'I can read in my free time.', ar: 'أستطيع أن أقرأ في وقت فراغي.' },
        { en: 'I can’t read difficult books.', ar: 'لا أستطيع أن أقرأ الكتب الصعبة.' },
        { en: 'Can you ride a bike?', ar: 'هل تستطيع أن تركب الدراجة؟' },
        { en: 'What do you do in your free time?', ar: 'ماذا تفعل في وقت فراغك؟' },
        { en: 'I go to the library every week to borrow some books.', ar: 'أذهب إلى المكتبة كل أسبوع لأستعير بعض الكتب.' },
      ],
    },

    // ===================== UNIT 8 — Inventions (Activity Book pages 28–30) =====================
    u8: {
      workbook: {
        pages: '28–30',
        readings: [
          {
            title: 'Important Inventions',
            paragraphs: [
              'In the past, life was different from today. Here are some inventions that changed our world and improved our life:',
              'Alexander Graham Bell invented the telephone. He wanted to invent a way to talk to his friends and family without moving and he succeeded.',
              'The use of solar energy began with the work of the French Edmond Becquerel. He produced power from the sun. This is good for the Earth.',
              'Hedy Lamarr was an actress and an inventor. She developed a technology that led to the invention of the Wi-Fi, GPS, and Bluetooth.',
            ],
            paragraphsAr: [
              'في الماضي كانت الحياة مختلفة عن اليوم. إليك بعض الاختراعات التي غيّرت عالمنا وحسّنت حياتنا:',
              'اخترع ألكسندر غراهام بيل الهاتف. أراد أن يخترع طريقة ليتكلّم مع أصدقائه وعائلته دون أن يتحرّك من مكانه، ونجح في ذلك.',
              'بدأ استخدام الطاقة الشمسية بعمل الفرنسي إدمون بيكريل. لقد أنتج الطاقة من الشمس. وهذا مفيد لكوكب الأرض.',
              'كانت هيدي لامار ممثّلة ومخترعة. طوّرت تقنية أدّت إلى اختراع الواي فاي ونظام تحديد المواقع (GPS) والبلوتوث.',
            ],
            questions: [
              {
                q: 'Hedy Lamarr was an inventor and …', qAr: 'كانت هيدي لامار مخترعة و …',
                options: ['a teacher.', 'an actress.', 'a doctor.'], answer: 1,
                explainAr: 'يقول النص: "Hedy Lamarr was an actress and an inventor." أي ممثّلة ومخترعة.',
              },
              {
                q: 'Alexander Graham Bell invented the …', qAr: 'اخترع ألكسندر غراهام بيل …',
                options: ['Wi-Fi.', 'telephone.', 'solar energy.'], answer: 1,
                explainAr: 'يقول النص: "Alexander Graham Bell invented the telephone." أي الهاتف.',
              },
              {
                q: 'Edmond Becquerel was the first to use …', qAr: 'كان إدمون بيكريل أوّل من استخدم …',
                options: ['the solar energy.', 'the telephone.', 'the plane.'], answer: 0,
                explainAr: 'يقول النص إن استخدام الطاقة الشمسية بدأ بعمل إدمون بيكريل، فقد أنتج الطاقة من الشمس.',
              },
            ],
            trueFalse: [
              { statement: 'The inventions made life different.', answer: true },
              { statement: 'Using the solar power is bad for the environment.', answer: false },
            ],
          },
        ],
        exercises: [
          // Ex. 1 — Write the number next to the picture
          mcq('Which invention is in the picture of a light bulb?', 'أيّ اختراع في صورة المصباح الكهربائي؟',
            ['Vaccination', 'Television', 'Radium', 'Electric light'], 3,
            'المصباح يعطي الضوء بالكهرباء، فهو Electric light (الضوء الكهربائي)، رقمه 5.'),
          mcq('Which invention is in the picture of an old TV?', 'أيّ اختراع في صورة جهاز التلفاز القديم؟',
            ['Television', 'Wi-Fi', 'Vaccination', 'Radium'], 0,
            'الجهاز ذو الشاشة والهوائيات هو Television (التلفاز)، رقمه 2.'),
          mcq('Which invention is in the picture of a hand with a Wi-Fi sign?', 'أيّ اختراع في صورة اليد مع علامة الواي فاي؟',
            ['Electric light', 'Radium', 'Wi-Fi', 'Television'], 2,
            'علامة الموجات هي علامة Wi-Fi (الواي فاي)، رقمه 3.'),
          mcq('Which invention is in the picture of a syringe and a small bottle?', 'أيّ اختراع في صورة الإبرة والزجاجة الصغيرة؟',
            ['Wi-Fi', 'Vaccination', 'Electric light', 'Television'], 1,
            'الإبرة والدواء يدلّان على Vaccination (التلقيح / اللقاح)، رقمه 1.'),
          mcq('Which discovery is in the X-ray picture of a hand?', 'أيّ اكتشاف في صورة الأشعة لليد؟',
            ['Television', 'Vaccination', 'Wi-Fi', 'Radium'], 3,
            'صورة الأشعة تدلّ على Radium (الراديوم) الذي اكتشفته ماري كوري، رقمه 4.'),
          // Ex. 2 — Read and match the questions to the answers
          mcq('Who was the inventor of vaccination?', 'من كان مخترع التلقيح؟', u8Answers, 3,
            'السؤال بـ Who (مَن) عن مخترع التلقيح، والجواب: Edward Jenner invented vaccination.'),
          mcq('What did Marie Curie discover?', 'ماذا اكتشفت ماري كوري؟', u8Answers, 2,
            'السؤال بـ What (ماذا) عن اكتشاف ماري كوري، والجواب: She discovered radium.'),
          mcq('Who invented the light bulb?', 'مَن اخترع المصباح الكهربائي؟', u8Answers, 1,
            'السؤال بـ Who (مَن)، والجواب: Thomas Edison did أي توماس إديسون هو الذي اخترعه.'),
          mcq('Which invention helps us use the Internet?', 'أيّ اختراع يساعدنا على استخدام الإنترنت؟', u8Answers, 0,
            'الواي فاي (The Wi-Fi) يوصلنا بالإنترنت.'),
          // Ex. 4 — Read and practise a similar conversation
          mcq('Who is the most important inventor? — John Logie Baird. What did he invent?', 'مَن أهمّ مخترع؟ — جون لوجي بيرد. ماذا اخترع؟',
            ['He invented the Television.', 'He invented the telephone.', 'He discovered radium.'], 0,
            'في الحوار: "He invented the Television." أي اخترع التلفاز.'),
          // Ex. 5 — Fill in the spaces with these words: invent inventor inventions
          fill('An ___ is the first person to make a new thing.', 'الـ___ هو أول شخص يصنع شيئاً جديداً.', 'المخترع هو أول شخص يصنع شيئاً جديداً.',
            ['invent', 'inventor', 'inventions'], 1,
            'inventor تعني «المخترع» وهو شخص. كلمة person (شخص) تدلّنا على الجواب.'),
          fill('When they ___ new things, they change the world.', 'عندما ___ أشياء جديدة، يغيّرون العالم.', 'عندما يخترعون أشياء جديدة، يغيّرون العالم.',
            ['invent', 'inventor', 'inventions'], 0,
            'بعد they نحتاج فعلاً: invent تعني «يخترع».'),
          fill('___ make our life easier.', '___ تجعل حياتنا أسهل.', 'الاختراعات تجعل حياتنا أسهل.',
            ['Invent', 'Inventor', 'Inventions'], 2,
            'Inventions تعني «الاختراعات» (جمع)، وهي الأشياء الجديدة التي تجعل حياتنا أسهل.'),
          // Ex. 7 — Find the past in the word search
          fill('Find the past: make → ___', 'ابحث عن الماضي: make (يصنع) ← ___', 'ابحث عن الماضي: make (يصنع) ← made (صنع)',
            ['made', 'maked', 'makes'], 0,
            'make فعل شاذّ، ماضيه made وليس maked.'),
          fill('Find the past: see → ___', 'ابحث عن الماضي: see (يرى) ← ___', 'ابحث عن الماضي: see (يرى) ← saw (رأى)',
            ['seed', 'saw', 'sees'], 1,
            'see فعل شاذّ، ماضيه saw.'),
          fill('Find the past: are → ___', 'ابحث عن الماضي: are (يكونون) ← ___', 'ابحث عن الماضي: are (يكونون) ← were (كانوا)',
            ['was', 'ared', 'were'], 2,
            'ماضي are هو were، أما was فهو ماضي is و am.'),
          fill('Find the past: carry → ___', 'ابحث عن الماضي: carry (يحمل) ← ___', 'ابحث عن الماضي: carry (يحمل) ← carried (حمل)',
            ['carryed', 'carried', 'carries'], 1,
            'الفعل ينتهي بـ y وقبلها حرف ساكن، فنحذف y ونضيف ied: carried.'),
          fill('Find the past: become → ___', 'ابحث عن الماضي: become (يصبح) ← ___', 'ابحث عن الماضي: become (يصبح) ← became (أصبح)',
            ['became', 'becomed', 'becomes'], 0,
            'become فعل شاذّ، ماضيه became.'),
          fill('Find the past: have → ___', 'ابحث عن الماضي: have (يملك) ← ___', 'ابحث عن الماضي: have (يملك) ← had (ملك / كان عنده)',
            ['haved', 'has', 'had'], 2,
            'have فعل شاذّ، ماضيه had.'),
          fill('Find the past: try → ___', 'ابحث عن الماضي: try (يحاول) ← ___', 'ابحث عن الماضي: try (يحاول) ← tried (حاول)',
            ['tried', 'tryed', 'tries'], 0,
            'try ينتهي بـ y وقبلها حرف ساكن، فنكتب tried.'),
          fill('Find the past: fly → ___', 'ابحث عن الماضي: fly (يطير) ← ___', 'ابحث عن الماضي: fly (يطير) ← flew (طار)',
            ['flied', 'flew', 'flys'], 1,
            'fly فعل شاذّ، ماضيه flew.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'You are an inventor. Write about your invention.',
          topicAr: 'أنت مخترع. اكتب عن اختراعك.',
          words: 40,
          points: ['What is its name?', 'What does it do?', 'How will it change the world?'],
          pointsAr: ['ما اسمه؟', 'ماذا يفعل؟', 'كيف سيغيّر العالم؟'],
          plan: [
            { en: 'Give your invention a name.', ar: 'أعطِ اختراعك اسماً.' },
            { en: 'Say what it does.', ar: 'قل ماذا يفعل.' },
            { en: 'Say how it will change the world.', ar: 'قل كيف سيغيّر العالم.' },
          ],
          phrases: [
            { en: 'I am an inventor.', ar: 'أنا مخترع.' },
            { en: 'My invention is called …', ar: 'اختراعي اسمه …' },
            { en: 'It can …', ar: 'يستطيع أن …' },
            { en: 'shade from the sun', ar: 'ظلّ يحمي من الشمس' },
            { en: 'on rainy days', ar: 'في الأيام الممطرة' },
            { en: 'It will change the world because …', ar: 'سيغيّر العالم لأن …' },
            { en: 'make our life easier', ar: 'يجعل حياتنا أسهل' },
          ],
          model: 'I am an inventor. My invention is called the Smart Umbrella. It opens when it rains and it gives you shade from the sun. It can also play music. It will change the world because people will not get wet or feel hot in the street.',
          modelAr: 'أنا مخترع. اختراعي اسمه «المظلّة الذكية». تنفتح عندما تمطر وتعطيك ظلاً من الشمس. وتستطيع أيضاً أن تعزف الموسيقى. ستغيّر العالم لأن الناس لن يبتلّوا ولن يشعروا بالحرّ في الشارع.',
          checklistAr: [
            'هل ذكرت اسم اختراعك؟',
            'هل شرحت ماذا يفعل؟',
            'هل قلت كيف سيغيّر العالم (It will …)؟',
            'هل استخدمت المضارع البسيط لتصف ما يفعله (It opens, It gives)؟',
            'هل كتبت حوالي 40 كلمة وراجعت التهجئة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write about your favourite invention.',
          topicAr: 'اكتب عن اختراعك المفضّل.',
          words: 40,
          points: ['My favourite invention is …', 'The inventor who invented it is …', 'I like it because …'],
          pointsAr: ['اختراعي المفضّل هو …', 'المخترع الذي اخترعه هو …', 'أحبّه لأن …'],
          plan: [
            { en: 'Name your favourite invention.', ar: 'اذكر اختراعك المفضّل.' },
            { en: 'Name the inventor who invented it.', ar: 'اذكر المخترع الذي اخترعه.' },
            { en: 'Say why you like it.', ar: 'قل لماذا تحبّه.' },
          ],
          phrases: [
            { en: 'My favourite invention is …', ar: 'اختراعي المفضّل هو …' },
            { en: 'Alexander Graham Bell invented the telephone.', ar: 'اخترع ألكسندر غراهام بيل الهاتف.' },
            { en: 'Thomas Edison invented the light bulb.', ar: 'اخترع توماس إديسون المصباح الكهربائي.' },
            { en: 'a great invention', ar: 'اختراع عظيم' },
            { en: 'We need it to talk to people.', ar: 'نحتاجه لنتكلّم مع الناس.' },
            { en: 'without moving', ar: 'دون أن نتحرّك' },
          ],
          model: 'My favourite invention is the telephone. The inventor who invented it is Alexander Graham Bell. I like it because I can talk to my friends and family without moving. The telephone is a great invention. We need it to talk to people.',
          modelAr: 'اختراعي المفضّل هو الهاتف. المخترع الذي اخترعه هو ألكسندر غراهام بيل. أحبّه لأنني أستطيع أن أتكلّم مع أصدقائي وعائلتي دون أن أتحرّك من مكاني. الهاتف اختراع عظيم. نحتاجه لنتكلّم مع الناس.',
          checklistAr: [
            'هل أكملت الجمل الثلاث: My favourite invention is / The inventor who invented it is / I like it because؟',
            'هل كتبت اسم المخترع بحروف كبيرة في أوله؟',
            'هل استخدمت الماضي invented عند الكلام عن المخترع؟',
            'هل ذكرت سبباً واضحاً بعد because؟',
          ],
        },
      ],
      translations: [
        { en: 'The telephone is a great invention.', ar: 'الهاتف اختراع عظيم.' },
        { en: 'We need it to talk to people.', ar: 'نحتاجه لنتكلّم مع الناس.' },
        { en: 'Alexander Graham Bell invented the telephone.', ar: 'اخترع ألكسندر غراهام بيل الهاتف.' },
        { en: 'He produced power from the sun.', ar: 'لقد أنتج الطاقة من الشمس.' },
        { en: 'This is good for the Earth.', ar: 'هذا مفيد لكوكب الأرض.' },
        { en: 'People first used umbrellas as a shade from the sun.', ar: 'استخدم الناس المظلّات أول مرة ظلاً يحميهم من الشمس.' },
        { en: 'In Europe men didn’t use umbrellas at first.', ar: 'في أوروبا لم يستخدم الرجال المظلّات في البداية.' },
        { en: 'When did the Chinese invent the umbrellas?', ar: 'متى اخترع الصينيون المظلّات؟' },
        { en: 'The Wright brothers designed a small machine.', ar: 'صمّم الأخوان رايت آلة صغيرة.' },
      ],
    },

    // ===================== UNIT 9 — Music (Activity Book pages 31–33) =====================
    u9: {
      workbook: {
        pages: '31–33',
        readings: [
          {
            title: 'Music',
            paragraphs: [
              'People listen to music when they are happy or sad. You can see musicians in the streets. They play all types of music, pop, hip hop, jazz and classical. The guitar, the flute, the piano and the harp are used to play western music. On the other hand, the oud, mizmar, qanun and tabla are used to play Arabian music. People go to concerts to listen to their favourite singers. Beethoven, Bach and Sayed Darwish are famous musicians throughout history.',
            ],
            paragraphsAr: [
              'يستمع الناس إلى الموسيقى عندما يكونون سعداء أو حزينين. يمكنك أن ترى الموسيقيين في الشوارع. إنهم يعزفون كل أنواع الموسيقى: البوب والهيب هوب والجاز والموسيقى الكلاسيكية. تُستخدم الغيتار والفلوت (الناي) والبيانو والهارب (القيثارة) لعزف الموسيقى الغربية. ومن ناحية أخرى، يُستخدم العود والمزمار والقانون والطبلة لعزف الموسيقى العربية. يذهب الناس إلى الحفلات الموسيقية ليستمعوا إلى مطربيهم المفضّلين. بيتهوفن وباخ وسيد درويش موسيقيون مشهورون عبر التاريخ.',
            ],
            questions: [
              {
                q: 'Pop, hip hop and jazz are …', qAr: 'البوب والهيب هوب والجاز هي …',
                options: ['musicians', 'types of music', 'places to play music'], answer: 1,
                explainAr: 'يقول النص: "They play all types of music, pop, hip hop, jazz" فهي أنواع من الموسيقى.',
              },
              {
                q: 'The oud, mizmar and qanun are … instruments.', qAr: 'العود والمزمار والقانون آلات …',
                options: ['cooking', 'fishing', 'musical'], answer: 2,
                explainAr: 'نعزف بها الموسيقى العربية، فهي آلات موسيقية (musical instruments).',
              },
              {
                q: 'The flute and the piano are used to play … music.', qAr: 'يُستخدم الفلوت والبيانو لعزف الموسيقى …',
                options: ['northern', 'western', 'southern'], answer: 1,
                explainAr: 'يقول النص إن الغيتار والفلوت والبيانو والهارب تُستخدم لعزف western music أي الموسيقى الغربية.',
              },
              {
                q: 'Beethoven and Darwish are …', qAr: 'بيتهوفن ودرويش …',
                options: ['doctors', 'teachers', 'musicians'], answer: 2,
                explainAr: 'يقول النص: "Beethoven, Bach and Sayed Darwish are famous musicians" أي موسيقيون مشهورون.',
              },
            ],
          },
        ],
        exercises: [
          // Ex. 1 — Correct the mistake then match
          mcq('Correct the mistake: "tembourine"', 'صحّح الخطأ في كتابة الكلمة: "tembourine"',
            ['tambourine', 'tamborine', 'tambourin'], 0,
            'الكتابة الصحيحة tambourine (الدفّ)، وتُوصل بصورة الدفّ.'),
          mcq('Correct the mistake: "peano"', 'صحّح الخطأ في كتابة الكلمة: "peano"',
            ['pieno', 'piano', 'piyano'], 1,
            'الكتابة الصحيحة piano (البيانو)، وتُوصل بصورة البيانو الكبير.'),
          mcq('Correct the mistake: "flut"', 'صحّح الخطأ في كتابة الكلمة: "flut"',
            ['floot', 'flutte', 'flute'], 2,
            'الكتابة الصحيحة flute (الفلوت / الناي) وفي آخرها e، وتُوصل بصورة الفلوت الطويل.'),
          mcq('Correct the mistake: "drams"', 'صحّح الخطأ في كتابة الكلمة: "drams"',
            ['drums', 'droms', 'drumes'], 0,
            'الكتابة الصحيحة drums (الطبول)، وتُوصل بصورة الطبل.'),
          mcq('Correct the mistake: "keyboord"', 'صحّح الخطأ في كتابة الكلمة: "keyboord"',
            ['keybord', 'keyboard', 'kayboard'], 1,
            'الكتابة الصحيحة keyboard (الأورغ / لوحة المفاتيح الموسيقية)، وتُوصل بصورة الأورغ.'),
          mcq('Correct the mistake: "Violeen"', 'صحّح الخطأ في كتابة الكلمة: "Violeen"',
            ['violen', 'vialin', 'violin'], 2,
            'الكتابة الصحيحة violin (الكمان)، وتُوصل بصورة الكمان.'),
          // Ex. 2b — Fill in the spaces with the words in the box
          fill('She listened to her ___ music.', 'استمعت إلى موسيقاها ___.', 'استمعت إلى موسيقاها المفضّلة.',
            u9Box, 3,
            'favourite تعني «المفضّل/المفضّلة»، وتأتي بعد her وقبل music.'),
          fill('He is a ___ singer.', 'هو مطرب ___.', 'هو مطرب مشهور.',
            u9Box, 1,
            'famous تعني «مشهور»، وهي صفة تصف المطرب (singer).'),
          fill('The ___ played the guitar in the street.', 'عزف الـ___ على الغيتار في الشارع.', 'عزف الموسيقيّ على الغيتار في الشارع.',
            u9Box, 2,
            'الذي يعزف هو شخص: musician أي «موسيقيّ».'),
          fill('They are going to a ___ tonight.', 'سيذهبون إلى ___ الليلة.', 'سيذهبون إلى حفلة موسيقية الليلة.',
            u9Box, 0,
            'concert تعني «حفلة موسيقية»، وهي مكان نذهب إليه لنسمع الموسيقى.'),
          // Ex. 4 — The piano (facts about the piano, so they need no recording)
          fill('The keys of the piano are ___.', 'مفاتيح البيانو ___.', 'مفاتيح البيانو سوداء وبيضاء.',
            ['red and white', 'white and grey', 'black and white'], 2,
            'مفاتيح البيانو لونها أسود وأبيض (black and white).'),
          fill('The ___ keys are larger and longer.', 'المفاتيح ___ أكبر وأطول.', 'المفاتيح البيضاء أكبر وأطول.',
            ['black', 'white', 'grey'], 1,
            'في البيانو المفاتيح البيضاء (white) أكبر وأطول، والسوداء أصغر وأقصر.'),
          fill('We make the piano from ___.', 'نصنع البيانو من ___.', 'نصنع البيانو من الخشب.',
            ['glass', 'wood', 'plastic'], 1,
            'البيانو مصنوع من الخشب (wood).'),
          fill('To make sounds, you ___ down the keys.', 'لتُخرج الأصوات، ___ على المفاتيح.', 'لتُخرج الأصوات، تضغط على المفاتيح.',
            ['press', 'see', 'watch'], 0,
            'press down تعني «يضغط»، ونحن نضغط على المفاتيح لنعزف.'),
          // Ex. 5 — Read then act out
          mcq('What kind of music do you like?', 'ما نوع الموسيقى الذي تحبّه؟',
            ['I like pop music.', 'I listen to music in my free time.', 'I am going to play the guitar.'], 0,
            'السؤال عن نوع الموسيقى (What kind)، والجواب: I like pop music أي «أحبّ موسيقى البوب».'),
          mcq('When do you listen to music?', 'متى تستمع إلى الموسيقى؟',
            ['I like pop music.', 'I listen to music in my free time.', 'He is interested in music.'], 1,
            'السؤال بـ When (متى)، والجواب يذكر الوقت: in my free time أي «في وقت فراغي».'),
          // Ex. 6 — Talk about yourself
          fill('I am good ___ playing the guitar.', 'أنا بارع ___ عزف الغيتار.', 'أنا بارع في عزف الغيتار.',
            ['in', 'at', 'on'], 1,
            'نقول دائماً good at (بارع في).'),
          fill('He is interested ___ music.', 'هو مهتمّ ___ الموسيقى.', 'هو مهتمّ بالموسيقى.',
            ['in', 'at', 'about'], 0,
            'نقول دائماً interested in (مهتمّ بـ).'),
          fill('She likes ___.', 'هي تحبّ ___.', 'هي تحبّ الغناء.',
            ['sing', 'singing', 'sings'], 1,
            'بعد like نضع الفعل مع ing: likes singing.'),
          // Ex. 7 — Classify: car /ɑː/ or cat /æ/
          tf('The word "guitar" has the same sound as "car".', 'كلمة "guitar" فيها نفس صوت كلمة "car".', true,
            'الحرفان ar في guitar يُلفظان /ɑː/ مثل car.'),
          tf('The word "hand" has the same sound as "car".', 'كلمة "hand" فيها نفس صوت كلمة "car".', false,
            'حرف a في hand قصير /æ/ مثل cat، فمكانها في عمود cat.'),
          tf('The word "hat" has the same sound as "cat".', 'كلمة "hat" فيها نفس صوت كلمة "cat".', true,
            'hat و cat فيهما صوت /æ/ القصير.'),
          tf('The word "jar" has the same sound as "cat".', 'كلمة "jar" فيها نفس صوت كلمة "cat".', false,
            'jar فيها ar الطويلة /ɑː/ مثل car، فمكانها في عمود car.'),
          tf('The word "father" has the same sound as "car".', 'كلمة "father" فيها نفس صوت كلمة "car".', true,
            'حرف a في father طويل /ɑː/ مثل car.'),
          tf('The word "smart" has the same sound as "cat".', 'كلمة "smart" فيها نفس صوت كلمة "cat".', false,
            'smart فيها ar الطويلة /ɑː/ مثل car، فمكانها في عمود car.'),
          tf('The word "sat" has the same sound as "cat".', 'كلمة "sat" فيها نفس صوت كلمة "cat".', true,
            'sat و cat فيهما صوت /æ/ القصير.'),
          tf('The word "star" has the same sound as "car".', 'كلمة "star" فيها نفس صوت كلمة "car".', true,
            'star و car تنتهيان بـ ar الطويلة /ɑː/.'),
          // Ex. 8 — Choose
          fill('Sama: Hey, Amer! What ___ do this weekend?', 'سما: مرحباً يا عامر! ماذا ___ أن تفعل في عطلة نهاية هذا الأسبوع؟', 'سما: مرحباً يا عامر! ماذا تنوي أن تفعل في عطلة نهاية هذا الأسبوع؟',
            ['did you', 'are you going to', 'is you going to'], 1,
            'this weekend وقت في المستقبل، فنستخدم are you going to. أما did you فللماضي.'),
          fill('Amer: I ___ go to my friend’s birthday party.', 'عامر: ___ أن أذهب إلى حفلة عيد ميلاد صديقتي.', 'عامر: سوف أذهب إلى حفلة عيد ميلاد صديقتي.',
            ['is going to', 'am going to', 'are going to'], 1,
            'مع I نستخدم am: I am going to.'),
          fill('Sama: That’s nice! What ___ you going to take as a present?', 'سما: هذا جميل! ماذا ___ أن تأخذ هدية؟', 'سما: هذا جميل! ماذا ستأخذ هدية؟',
            ['is', 'are', 'am'], 1,
            'مع you نستخدم are: are you going to.'),
          fill('Amer: I am going to ___ a recorder. She likes music.', 'عامر: سوف ___ مزماراً (ريكوردر). هي تحبّ الموسيقى.', 'عامر: سوف أشتري مزماراً (ريكوردر). هي تحبّ الموسيقى.',
            ['buy', 'sell', 'lose'], 0,
            'الهدية نشتريها: buy تعني «يشتري»، أما sell فتعني «يبيع».'),
          fill('Amer: No, she isn’t. She ___ travel to London.', 'عامر: لا، لن تأتي. ___ أن تسافر إلى لندن.', 'عامر: لا، لن تأتي. إنها ستسافر إلى لندن.',
            ['is going to', 'going to', 'are going to'], 0,
            'مع she نستخدم is، ولا يجوز حذفها: She is going to travel.'),
          // Ex. 9 — Read Lily's list and write what she is or isn't going to do
          build('She isn’t going to go to a concert.', 'لن تذهب إلى حفلة موسيقية. (✗ go to a concert)', ['aren’t']),
          build('She is going to play the piano.', 'ستعزف على البيانو. (✓ play the piano)', ['playing']),
          build('She is going to buy a ticket for the concert.', 'ستشتري تذكرة للحفلة الموسيقية. (✓ buy a ticket)', ['am']),
          build('She isn’t going to dance in the concert.', 'لن ترقص في الحفلة الموسيقية. (✗ dance in the concert)', ['dances']),
          build('She is going to have a party.', 'ستقيم حفلة. (✓ have a party)', ['are']),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Today, I have lots of things to do! I am going to clean my room because my friends are going to visit me tomorrow. We …',
          topicAr: 'أكمل: اليوم عندي أشياء كثيرة لأفعلها! سأنظّف غرفتي لأن أصدقائي سيزورونني غداً. نحن …',
          words: 40,
          plan: [
            { en: 'Copy the beginning, then say what you and your friends are going to do.', ar: 'انسخ البداية، ثم قل ماذا ستفعل أنت وأصدقاؤك.' },
            { en: 'Add what someone in your family is going to do.', ar: 'أضف ماذا سيفعل أحد أفراد عائلتك.' },
            { en: 'End with your plan for the evening.', ar: 'اختم بخطّتك للمساء.' },
          ],
          phrases: [
            { en: 'We are going to …', ar: 'نحن سوف …' },
            { en: 'play games', ar: 'نلعب الألعاب' },
            { en: 'listen to music', ar: 'نستمع إلى الموسيقى' },
            { en: 'make a cake', ar: 'تصنع كعكة' },
            { en: 'have a party', ar: 'نقيم حفلة' },
            { en: 'practise the piano', ar: 'أتدرّب على البيانو' },
            { en: 'in the evening', ar: 'في المساء' },
          ],
          model: 'Today, I have lots of things to do! I am going to clean my room because my friends are going to visit me tomorrow. We are going to play games and listen to music. My mother is going to make a cake. In the evening, I am going to practise the piano.',
          modelAr: 'اليوم عندي أشياء كثيرة لأفعلها! سأنظّف غرفتي لأن أصدقائي سيزورونني غداً. سوف نلعب الألعاب ونستمع إلى الموسيقى. أمي ستصنع كعكة. وفي المساء سأتدرّب على البيانو.',
          checklistAr: [
            'هل أكملت النص بعد كلمة We؟',
            'هل استخدمت am / is / are going to مع الفعل بشكله الأساسي؟',
            'هل اخترت am مع I و is مع he/she و are مع we/they؟',
            'هل ذكرت كلمات وقت للمستقبل مثل tomorrow و in the evening؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write about what you are going to do this weekend.',
          topicAr: 'اكتب عمّا ستفعله في عطلة نهاية هذا الأسبوع.',
          words: 40,
          plan: [
            { en: 'Start with "This weekend, I am going to …".', ar: 'ابدأ بـ This weekend, I am going to … (في عطلة نهاية هذا الأسبوع سوف …).' },
            { en: 'Say what you are going to do on each day, and with whom.', ar: 'قل ماذا ستفعل في كل يوم، ومع مَن.' },
            { en: 'Say one thing you are not going to do.', ar: 'اذكر شيئاً واحداً لن تفعله.' },
          ],
          phrases: [
            { en: 'This weekend, I am going to …', ar: 'في عطلة نهاية هذا الأسبوع سوف …' },
            { en: 'play the guitar', ar: 'أعزف على الغيتار' },
            { en: 'go to a concert', ar: 'أذهب إلى حفلة موسيقية' },
            { en: 'have a party', ar: 'نقيم حفلة' },
            { en: 'join a music club', ar: 'أنضمّ إلى نادٍ موسيقي' },
            { en: 'I am not going to …', ar: 'لن …' },
          ],
          model: 'This weekend, I am going to visit my grandparents. On Friday, I am going to play the guitar with my friends. We are going to have a party. On Saturday, I am going to go to a concert with my family. I am not going to watch TV.',
          modelAr: 'في عطلة نهاية هذا الأسبوع سأزور جدّي وجدّتي. يوم الجمعة سأعزف على الغيتار مع أصدقائي. سوف نقيم حفلة. يوم السبت سأذهب إلى حفلة موسيقية مع عائلتي. لن أشاهد التلفاز.',
          checklistAr: [
            'هل بدأت بـ This weekend, I …؟',
            'هل استخدمت going to مع الفعل بشكله الأساسي في كل جملة عن المستقبل؟',
            'هل كتبت جملة واحدة على الأقل بـ not going to؟',
            'هل كتبت أيام الأسبوع بحرف كبير (Friday, Saturday)؟',
            'هل كتبت حوالي 40 كلمة وراجعت التهجئة؟',
          ],
        },
      ],
      translations: [
        { en: 'People listen to music when they are happy or sad.', ar: 'يستمع الناس إلى الموسيقى عندما يكونون سعداء أو حزينين.' },
        { en: 'You can see musicians in the streets.', ar: 'يمكنك أن ترى الموسيقيين في الشوارع.' },
        { en: 'People go to concerts to listen to their favourite singers.', ar: 'يذهب الناس إلى الحفلات الموسيقية ليستمعوا إلى مطربيهم المفضّلين.' },
        { en: 'I am going to play the piano tomorrow.', ar: 'سوف أعزف على البيانو غداً.' },
        { en: 'She is going to make a cake in the evening.', ar: 'سوف تصنع كعكة في المساء.' },
        { en: 'We are going to have a party tonight.', ar: 'سوف نقيم حفلة الليلة.' },
        { en: 'She is not going to go to the concert.', ar: 'لن تذهب إلى الحفلة الموسيقية.' },
        { en: 'I am good at playing the guitar.', ar: 'أنا بارع في عزف الغيتار.' },
        { en: 'He is interested in music.', ar: 'هو مهتمّ بالموسيقى.' },
      ],
    },

    // ===================== UNIT 10 — Technology (Activity Book pages 34–36) =====================
    u10: {
      workbook: {
        pages: '34–36',
        readings: [
          {
            title: 'The Computer Lab',
            paragraphs: [
              'Hello everybody! Before you go into the computer lab, there are things you need to know.',
              'Clean your hands.',
              'Come into the lab quietly.',
              'Open your file only.',
              'Put your chair back in place.',
              'Don’t bring food or drinks to the lab.',
              'Listen to the directions and follow them.',
              'Save your work.',
              'Treat computers with care.',
            ],
            paragraphsAr: [
              'مرحباً بالجميع! قبل أن تدخلوا مخبر الحاسوب، هناك أشياء يجب أن تعرفوها.',
              'نظّف يديك.',
              'ادخل إلى المخبر بهدوء.',
              'افتح ملفّك فقط.',
              'أعِد كرسيك إلى مكانه.',
              'لا تُحضِر طعاماً أو مشروبات إلى المخبر.',
              'استمع إلى التعليمات واتّبعها.',
              'احفظ عملك.',
              'تعامل مع الحواسيب بعناية.',
            ],
            questions: [
              {
                q: 'How should you come into the lab?', qAr: 'كيف يجب أن تدخل إلى المخبر؟',
                options: ['Loudly', 'Quietly', 'Quickly'], answer: 1,
                explainAr: 'القاعدة تقول: "Come into the lab quietly." أي بهدوء.',
              },
              {
                q: 'Which file can you open?', qAr: 'أيّ ملف تستطيع أن تفتح؟',
                options: ['All the files', 'Your friend’s file', 'Your file only'], answer: 2,
                explainAr: 'القاعدة تقول: "Open your file only." أي افتح ملفّك أنت فقط.',
              },
              {
                q: 'What should you do with your chair?', qAr: 'ماذا يجب أن تفعل بكرسيك؟',
                options: ['Put it back in place', 'Take it home', 'Leave it in the door'], answer: 0,
                explainAr: 'القاعدة تقول: "Put your chair back in place." أي أعِده إلى مكانه.',
              },
            ],
            trueFalse: [
              { statement: 'You can speak loudly in the lab.', answer: false },
              { statement: 'You can open others files.', answer: false },
              { statement: 'Eat and drink outside the computer lab.', answer: true },
              { statement: 'Listen to what your teacher says.', answer: true },
            ],
          },
          {
            title: 'Internet Safety',
            paragraphs: [
              'Think before you type.',
              'Don’t share your personal information.',
              'Tell your password to your friends.',
              'Talk to strangers.',
              'Share nice things.',
              'Tell your parents when you see things you don’t like.',
              'Trust all the information.',
              'Write bad words.',
            ],
            paragraphsAr: [
              'فكّر قبل أن تكتب.',
              'لا تشارك معلوماتك الشخصية.',
              'أخبِر أصدقاءك بكلمة السرّ الخاصة بك.',
              'تكلّم مع الغرباء.',
              'شارك أشياء لطيفة.',
              'أخبِر والديك عندما ترى أشياء لا تحبّها.',
              'صدّق كل المعلومات.',
              'اكتب كلمات سيئة.',
            ],
            questions: [
              {
                q: 'Which one is a good idea?', qAr: 'أيّ واحدة منها فكرة جيدة؟',
                options: ['Talk to strangers.', 'Share nice things.', 'Write bad words.'], answer: 1,
                explainAr: 'مشاركة الأشياء اللطيفة فكرة جيدة. أما الكلام مع الغرباء وكتابة الكلمات السيئة فأفكار سيئة.',
              },
              {
                q: 'What should you do when you see things you don’t like?', qAr: 'ماذا يجب أن تفعل عندما ترى أشياء لا تحبّها؟',
                options: ['Tell your password to your friends.', 'Trust all the information.', 'Tell your parents.'], answer: 2,
                explainAr: 'أخبِر والديك دائماً عندما ترى شيئاً لا تحبّه على الإنترنت.',
              },
              {
                q: 'Which one is a bad idea?', qAr: 'أيّ واحدة منها فكرة سيئة؟',
                options: ['Trust all the information.', 'Think before you type.', 'Share nice things.'], answer: 0,
                explainAr: 'ليست كل المعلومات على الإنترنت صحيحة، فتصديقها كلها فكرة سيئة.',
              },
            ],
          },
        ],
        exercises: [
          // Ex. 1 — Match
          mcq('Match: "You use it to surf the net and play games. You can carry it."', 'صِل: «تستخدمه لتتصفّح الإنترنت وتلعب الألعاب. تستطيع أن تحمله.»',
            ['router', 'tablet', 'webcam', 'smart watch'], 1,
            'الجهاز اللوحي tablet نحمله معنا ونتصفّح به الإنترنت ونلعب.'),
          mcq('Match: "You wear it on your hand and use it to surf the net."', 'صِل: «تلبسه على يدك وتستخدمه لتتصفّح الإنترنت.»',
            ['smart watch', 'E-book', 'VR', 'tablet'], 0,
            'الساعة الذكية smart watch نلبسها على اليد.'),
          mcq('Match: "You use it to connect to the Internet."', 'صِل: «تستخدمه لتتصل بالإنترنت.»',
            ['webcam', 'E-book', 'router', 'VR'], 2,
            'جهاز الراوتر router يوصلنا بالإنترنت.'),
          mcq('Match: "Electronic book."', 'صِل: «كتاب إلكتروني.»',
            ['VR', 'E-book', 'webcam', 'router'], 1,
            'E-book اختصار Electronic book أي الكتاب الإلكتروني.'),
          mcq('Match: "You play games like in real life."', 'صِل: «تلعب ألعاباً كأنها في الحياة الحقيقية.»',
            ['smart watch', 'router', 'E-book', 'VR'], 3,
            'نظّارة الواقع الافتراضي VR تجعلك تلعب وكأنك في الحياة الحقيقية.'),
          mcq('Match: "It helps you to make video calls on your computer."', 'صِل: «تساعدك على إجراء مكالمات فيديو على حاسوبك.»',
            ['webcam', 'tablet', 'VR', 'E-book'], 0,
            'كاميرا الويب webcam نستعملها لمكالمات الفيديو على الحاسوب.'),
          // Ex. 4 — Match
          fill('turn off ___', 'أطفئ ___', 'أطفئ الحاسوب',
            ['online', 'the computer', 'to the Internet'], 1,
            'نقول turn off the computer أي «أطفئ الحاسوب».'),
          fill('download ___', 'حمّل (نزّل) ___', 'حمّل (نزّل) الموسيقى',
            ['the music', 'to the Internet', 'your work'], 0,
            'نقول download the music أي «حمّل الموسيقى» من الإنترنت.'),
          fill('search ___', 'ابحث في ___', 'ابحث في الإنترنت',
            ['your work', 'to the Internet', 'the Internet'], 2,
            'نقول search the Internet أي «ابحث في الإنترنت».'),
          fill('save ___', 'احفظ ___', 'احفظ عملك',
            ['to the Internet', 'your work', 'online'], 1,
            'نقول save your work أي «احفظ عملك».'),
          fill('study ___', 'ادرس ___', 'ادرس عبر الإنترنت',
            ['online', 'the email address', 'to the Internet'], 0,
            'نقول study online أي «ادرس عبر الإنترنت».'),
          fill('connect ___', 'اتّصل ___', 'اتّصل بالإنترنت',
            ['the music', 'your work', 'to the Internet'], 2,
            'بعد connect نضع to: connect to the Internet أي «اتّصل بالإنترنت».'),
          fill('type ___', 'اكتب ___', 'اكتب عنوان البريد الإلكتروني',
            ['the email address', 'to the Internet', 'online'], 0,
            'نقول type the email address أي «اكتب عنوان البريد الإلكتروني» على لوحة المفاتيح.'),
          // Ex. 5 — Ask and answer
          mcq('What kind of websites do you like best?', 'ما نوع المواقع الإلكترونية التي تحبّها أكثر؟',
            ['I use it two hours a day.', 'Websites with information about science are my favourite.', 'Turn on the computer.'], 1,
            'السؤال عن نوع المواقع، والجواب: المواقع التي فيها معلومات عن العلوم هي المفضّلة عندي.'),
          // Ex. 6 — Write in the table (Good idea ✓ / Bad idea ✗)
          tf('"Think before you type." is a good idea.', '«فكّر قبل أن تكتب» فكرة جيدة.', true,
            'التفكير قبل الكتابة يحميك من الأخطاء، فهي Good idea.'),
          tf('"Don’t share your personal information." is a good idea.', '«لا تشارك معلوماتك الشخصية» فكرة جيدة.', true,
            'معلوماتك الشخصية (اسمك الكامل، عنوانك) يجب أن تبقى سرّاً، فهي Good idea.'),
          tf('"Tell your password to your friends." is a good idea.', '«أخبِر أصدقاءك بكلمة السرّ» فكرة جيدة.', false,
            'كلمة السرّ لا نخبر بها أحداً، فهي Bad idea.'),
          tf('"Talk to strangers." is a bad idea.', '«تكلّم مع الغرباء» فكرة سيئة.', true,
            'الكلام مع الغرباء على الإنترنت خطر، فهي Bad idea.'),
          tf('"Share nice things." is a bad idea.', '«شارك أشياء لطيفة» فكرة سيئة.', false,
            'مشاركة الأشياء اللطيفة فكرة جيدة (Good idea).'),
          tf('"Tell your parents when you see things you don’t like." is a good idea.', '«أخبِر والديك عندما ترى أشياء لا تحبّها» فكرة جيدة.', true,
            'والداك يساعدانك دائماً، فهي Good idea.'),
          tf('"Trust all the information." is a good idea.', '«صدّق كل المعلومات» فكرة جيدة.', false,
            'ليست كل المعلومات على الإنترنت صحيحة، فهي Bad idea.'),
          tf('"Write bad words." is a bad idea.', '«اكتب كلمات سيئة» فكرة سيئة.', true,
            'الكلمات السيئة تؤذي الآخرين، فهي Bad idea.'),
          // Ex. 7 — Choose
          fill('___ your house address online.', '___ عنوان بيتك على الإنترنت.', 'لا تشارك عنوان بيتك على الإنترنت.',
            ['Share', 'Don’t share', 'Send'], 1,
            'عنوان البيت معلومة شخصية، فنقول Don’t share (لا تشارك).'),
          fill('___ to what the teacher says.', '___ إلى ما يقوله المعلّم.', 'استمع إلى ما يقوله المعلّم.',
            ['Listen', 'Don’t listen', 'Look'], 0,
            'يجب أن نستمع إلى المعلّم، فنقول Listen (استمع).'),
          fill('___ hours playing games.', '___ ساعات في لعب الألعاب.', 'لا تقضِ ساعات في لعب الألعاب.',
            ['Spend', 'Don’t spend', 'Play'], 1,
            'اللعب ساعات طويلة مضرّ، فنقول Don’t spend (لا تقضِ).'),
          fill('___ on the icon to download the file.', '___ على الأيقونة لتحمّل الملف.', 'انقر على الأيقونة لتحمّل الملف.',
            ['Click', 'Press', 'Type'], 0,
            'مع الأيقونة نقول Click on (انقر على)، كما في الكتاب: Click on the icon.'),
          fill('Don’t turn ___ the computer before you save your work.', 'لا ___ الحاسوب قبل أن تحفظ عملك.', 'لا تطفئ الحاسوب قبل أن تحفظ عملك.',
            ['on', 'off', 'in'], 1,
            'إذا أطفأنا الحاسوب قبل الحفظ يضيع العمل، فنقول turn off (أطفئ).'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Write what Tia should do. (These verbs may help you)',
          topicAr: 'اكتب ماذا يجب أن تفعل تيا. (قد تساعدك هذه الأفعال: use, connect, save, install, click, write, print, leave, put)',
          words: 40,
          points: ['I can’t send the email!', 'I want to keep the file on my computer.', 'The words are close to each other.', 'The spelling is incorrect.'],
          pointsAr: ['لا أستطيع أن أرسل البريد الإلكتروني!', 'أريد أن أحتفظ بالملف على حاسوبي.', 'الكلمات قريبة من بعضها.', 'التهجئة غير صحيحة.'],
          plan: [
            { en: 'Problem 1: tell Tia to connect to the Internet and click on send.', ar: 'المشكلة ١: قل لتيا أن تتصل بالإنترنت وتنقر على «إرسال».' },
            { en: 'Problem 2: tell her to save the file.', ar: 'المشكلة ٢: قل لها أن تحفظ الملف.' },
            { en: 'Problem 3: tell her to leave a space between the words.', ar: 'المشكلة ٣: قل لها أن تترك مسافة بين الكلمات.' },
            { en: 'Problem 4: tell her to correct the spelling.', ar: 'المشكلة ٤: قل لها أن تصحّح التهجئة.' },
          ],
          phrases: [
            { en: 'You should …', ar: 'يجب أن …' },
            { en: 'connect to the Internet', ar: 'تتصل بالإنترنت' },
            { en: 'click on send', ar: 'تنقر على «إرسال»' },
            { en: 'save the file', ar: 'تحفظ الملف' },
            { en: 'leave a space between the words', ar: 'تترك مسافة بين الكلمات' },
            { en: 'correct the spelling', ar: 'تصحّح التهجئة' },
          ],
          model: 'Tia, you should connect to the Internet and then click on send. You should save the file on your computer. You should leave a space between the words. You should use the spelling check and correct the spelling.',
          modelAr: 'يا تيا، يجب أن تتصلي بالإنترنت ثم تنقري على «إرسال». يجب أن تحفظي الملف على حاسوبك. يجب أن تتركي مسافة بين الكلمات. يجب أن تستخدمي مدقّق التهجئة وتصحّحي التهجئة.',
          checklistAr: [
            'هل أجبت عن مشكلات تيا الأربع؟',
            'هل استخدمت should مع الفعل بشكله الأساسي؟',
            'هل استخدمت بعض الأفعال المعطاة (connect, save, leave, click…)؟',
            'هل بدأت كل جملة بحرف كبير وأنهيتها بنقطة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Lily wants to send her homework to her teacher’s email but she doesn’t know how. Tell her what to do.',
          topicAr: 'ليلي تريد أن ترسل وظيفتها إلى البريد الإلكتروني لمعلّمتها لكنها لا تعرف كيف. أخبرها ماذا تفعل.',
          words: 40,
          plan: [
            { en: 'Begin with "First" and turn on the computer.', ar: 'ابدأ بكلمة First (أولاً) وقل لها أن تشغّل الحاسوب.' },
            { en: 'Give the steps in order with Second, Next, Then, After that, Now.', ar: 'اذكر الخطوات بالترتيب مع Second, Next, Then, After that, Now.' },
            { en: 'End with "Finally, click on send."', ar: 'اختم بـ Finally, click on send (أخيراً، انقري على «إرسال»).' },
          ],
          phrases: [
            { en: 'First, turn on the computer.', ar: 'أولاً، شغّلي الحاسوب.' },
            { en: 'open the webpage', ar: 'افتحي صفحة الإنترنت' },
            { en: 'type the email address in the space', ar: 'اكتبي عنوان البريد الإلكتروني في المكان الفارغ' },
            { en: 'click on subject', ar: 'انقري على «الموضوع»' },
            { en: 'check your spelling', ar: 'راجعي التهجئة' },
            { en: 'Finally, click on send.', ar: 'أخيراً، انقري على «إرسال».' },
            { en: 'After that, …', ar: 'بعد ذلك، …' },
          ],
          model: 'First, turn on the computer. Second, open the webpage. Next, type your teacher’s email address in the space. Then, click on subject and write what the email is about. After that, type your message and add your homework. Now, check your spelling. Finally, click on send.',
          modelAr: 'أولاً، شغّلي الحاسوب. ثانياً، افتحي صفحة الإنترنت. بعد ذلك، اكتبي عنوان البريد الإلكتروني لمعلّمتك في المكان الفارغ. ثم انقري على «الموضوع» واكتبي عمّا يتحدّث البريد. بعد ذلك، اكتبي رسالتك وأضيفي وظيفتك. الآن، راجعي التهجئة. أخيراً، انقري على «إرسال».',
          checklistAr: [
            'هل بدأت بـ First وانتهيت بـ Finally؟',
            'هل كتبت الخطوات بالترتيب الصحيح؟',
            'هل استخدمت الأمر (turn on, open, type, click) في بداية كل خطوة؟',
            'هل وضعت فاصلة بعد كلمات الترتيب (First, Then, …)؟',
          ],
        },
      ],
      translations: [
        { en: 'Turn on the computer.', ar: 'شغّل الحاسوب.' },
        { en: 'Click on the icon.', ar: 'انقر على الأيقونة.' },
        { en: 'Come into the lab quietly.', ar: 'ادخل إلى المخبر بهدوء.' },
        { en: 'Don’t bring food or drinks to the lab.', ar: 'لا تُحضِر طعاماً أو مشروبات إلى المخبر.' },
        { en: 'Treat computers with care.', ar: 'تعامل مع الحواسيب بعناية.' },
        { en: 'Think before you type.', ar: 'فكّر قبل أن تكتب.' },
        { en: 'Don’t share your personal information.', ar: 'لا تشارك معلوماتك الشخصية.' },
        { en: 'Tell your parents when you see things you don’t like.', ar: 'أخبِر والديك عندما ترى أشياء لا تحبّها.' },
        { en: 'The first computers were very big.', ar: 'كانت الحواسيب الأولى كبيرة جداً.' },
        { en: 'Today computers are smaller and cheaper.', ar: 'اليوم أصبحت الحواسيب أصغر وأرخص.' },
      ],
    },
  },

  // ===================== REVISION 2 (Activity Book pages 37–38) =====================
  progressTest: {
    title: 'Revision 2',
    titleAr: 'المراجعة الثانية',
    pages: '37–38',
    exercises: [
      // Ex. 1 — Classify (Hobbies · Inventions · Music · Technology)
      classify('vaccination', 'التلقيح', 'Inventions', 'وقد اخترعه إدوارد جينر،'),
      classify('website', 'موقع إلكتروني', 'Technology', 'وهو من عالم الإنترنت،'),
      classify('printer', 'طابعة', 'Technology', 'وهي جهاز نصله بالحاسوب،'),
      classify('tambourine', 'الدفّ', 'Music', 'وهو آلة موسيقية،'),
      classify('Wi-Fi', 'الواي فاي', 'Inventions', 'وقد أدّى إليه عمل المخترعة هيدي لامار،'),
      classify('painting', 'الرسم بالألوان', 'Hobbies', 'وهو هواية نمارسها في وقت الفراغ،'),
      classify('cooking', 'الطبخ', 'Hobbies', 'وهو هواية رنا المفضّلة،'),
      classify('radium', 'الراديوم', 'Inventions', 'وقد اكتشفته ماري كوري،'),
      classify('drums', 'الطبول', 'Music', 'وهي آلة موسيقية،'),
      classify('flute', 'الفلوت (الناي)', 'Music', 'وهو آلة موسيقية،'),
      classify('singing', 'الغناء', 'Hobbies', 'وهو هواية نمارسها في وقت الفراغ،'),
      classify('touchpad', 'لوحة اللمس', 'Technology', 'وهي جزء من الحاسوب المحمول،'),
      // Ex. 2 — Read and match
      r2Match('What is good for your health?', 'ما المفيد لصحتك؟', 2, [0, 1, 4],
        'السؤال عن الشيء المفيد للصحة، والجواب: Exercise is good for me أي «التمارين مفيدة لي».'),
      r2Match('Can you ride a bike?', 'هل تستطيع أن تركب الدراجة؟', 0, [1, 3, 4],
        'السؤال يبدأ بـ Can، فالجواب القصير: Yes, I can.'),
      r2Match('Who invented the light bulb?', 'مَن اخترع المصباح الكهربائي؟', 4, [0, 2, 3],
        'السؤال بـ Who (مَن)، والجواب: Thomas Edison did.'),
      r2Match('Which instrument do you prefer?', 'أيّ آلة موسيقية تفضّل؟', 1, [2, 3, 4],
        'السؤال عن آلة موسيقية، والجواب يذكر آلة: I like the violin أي «أحبّ الكمان».'),
      r2Match('How do you search online?', 'كيف تبحث على الإنترنت؟', 3, [0, 1, 2],
        'السؤال بـ How (كيف) عن البحث، والجواب: I usually use Google.'),
      // Ex. 3 — Choose
      fill('She is good ___ playing the oud.', 'هي بارعة ___ عزف العود.', 'هي بارعة في عزف العود.',
        ['in', 'at', 'on'], 1,
        'نقول دائماً good at (بارع في).'),
      fill('Turn ___ the computer and log on.', '___ الحاسوب وسجّل الدخول.', 'شغّل الحاسوب وسجّل الدخول.',
        ['on', 'off', 'in'], 0,
        'لنسجّل الدخول يجب أن نشغّل الحاسوب أولاً: turn on.'),
      fill('Graham Bell is the inventor ___ the telephone.', 'غراهام بيل هو مخترع ___ الهاتف.', 'غراهام بيل هو مخترع الهاتف.',
        ['of', 'by', 'at'], 0,
        'نقول the inventor of … أي «مخترع الشيء».'),
      fill('Eating too many sweets is bad ___ you.', 'أكل الكثير من الحلويات مضرّ ___ك.', 'أكل الكثير من الحلويات مضرّ لك.',
        ['on', 'for', 'at'], 1,
        'نقول bad for you و good for you أي «مضرّ لك» و«مفيد لك».'),
      fill('He is interested ___ cooking.', 'هو مهتمّ ___ الطبخ.', 'هو مهتمّ بالطبخ.',
        ['about', 'at', 'in'], 2,
        'نقول دائماً interested in (مهتمّ بـ).'),
      // Ex. 4 — Choose a, b, or c
      fill('Lana can ___ a bike.', 'لانا تستطيع أن ___ الدراجة.', 'لانا تستطيع أن تركب الدراجة.',
        ['ride', 'rides', 'riding'], 0,
        'بعد can يأتي الفعل بشكله الأساسي: can ride.'),
      fill('___ get enough sleep?', '___ تنام وقتاً كافياً؟', 'لماذا لا تنام وقتاً كافياً؟',
        ['Why don’t you', 'should', 'shouldn’t'], 0,
        'الجملة سؤال بدون فاعل، فنبدأ بـ Why don’t you (لماذا لا…؟).'),
      fill('They are going to go to the theatre ___.', 'سيذهبون إلى المسرح ___.', 'سيذهبون إلى المسرح الأسبوع القادم.',
        ['yesterday', 'always', 'next week'], 2,
        'going to للمستقبل، فنختار next week (الأسبوع القادم). أما yesterday فللماضي.'),
      fill('___ turn on the computer. It’s time to go to bed.', '___ الحاسوب. حان وقت النوم.', 'لا تشغّل الحاسوب. حان وقت النوم.',
        ['Don’t', 'Doesn’t', 'Didn’t'], 0,
        'هذا أمر بالنفي، ونبدأه بـ Don’t (لا تفعل).'),
      fill('He didn’t ___ to Tartous last holiday.', 'هو لم ___ إلى طرطوس في العطلة الماضية.', 'هو لم يسافر إلى طرطوس في العطلة الماضية.',
        ['travel', 'travelled', 'travelling'], 0,
        'بعد didn’t يعود الفعل إلى شكله الأساسي: didn’t travel.'),
    ],
  },
}
