import type { Module } from '../../engine/types'

export const module5: Module = {
  number: 5,
  title: "Culture",
  titleAr: "الثقافة",
  color: "#ff4b4b",
  units: [
    // ===================== UNIT 9 — Citizenship (pages 88–96) =====================
    {
      id: "u9", number: 9, module: 5,
      title: "Citizenship", titleAr: "المواطنة", pages: "88–96", emoji: "🏛️",
      quotes: [
        { text: "Every citizen of the republic ought to consider himself / herself an unofficial policeman, and keep unsalaried watch and ward over the laws and their execution.", by: "Mark Twain" },
      ],
      planAr: "قراءة نص عن المواطنة وحقوق المواطن السوري وواجباته، مفردات عائلة الكلمة (member → membership) والصفات التي يتبعها حرف جر (afraid of, proud of, keen on...)، قواعد أدوات الربط المزدوجة (both...and, not only...but also, either...or, neither...nor)، لفظ الكلمات المتشابهة في الكتابة المختلفة في المعنى (Homographs)، تعابير قبول العروض ورفضها، الاستماع إلى نص عن سلوك المواطن الصالح، التحدث لإبداء الرأي، وكتابة مقال عمّا يجعل الإنسان مواطناً صالحاً.",
      vocab: [
        { en: "citizenship", ar: "المواطنة / الجنسية", pos: "noun", def: "the legal right of belonging to a particular country", defAr: "الحق القانوني في الانتماء إلى بلد معيّن", example: "The concept of citizenship first arose in towns and city-states of ancient Greece, disappeared in Europe during the Middle Ages and crystallissed in the 18th century.", exampleAr: "نشأ مفهوم المواطنة أول مرة في مدن اليونان القديمة ودولها المدن، واختفى في أوروبا خلال العصور الوسطى، ثم تبلور في القرن الثامن عشر." },
        { en: "vested", ar: "مُخوَّل / ممنوح (حقاً)", pos: "adjective", def: "given the official right to do or own something", defAr: "مُنح الحق الرسمي في فعل شيء أو امتلاكه", example: "Citizenship is not only the state of being vested with the rights and duties of a citizen, but it can also be defined as the character of an individual who is viewed as a member of a particular society.", exampleAr: "ليست المواطنة حالة التمتّع بحقوق المواطن وواجباته فحسب، بل يمكن أيضاً تعريفها بأنها صفة الفرد الذي يُنظر إليه على أنه عضو في مجتمع معيّن." },
        { en: "concept", ar: "مفهوم", pos: "noun", def: "an idea that is connected with something", defAr: "فكرة مرتبطة بشيء ما", example: "The concept of citizenship has never been fixed or static, but constantly changes within each society.", exampleAr: "لم يكن مفهوم المواطنة ثابتاً أو جامداً أبداً، بل يتغيّر باستمرار داخل كل مجتمع." },
        { en: "voluntary", ar: "طوعي / اختياري", pos: "adjective", def: "done willingly, not because you are forced", defAr: "يُفعل عن رغبة، لا لأنك مُجبَر عليه", example: "In spite of the fact that all Syrian citizens enjoy freedom, protection and legal rights, they also have responsibilities that are voluntary as well as obligatory.", exampleAr: "على الرغم من أن جميع المواطنين السوريين يتمتعون بالحرية والحماية والحقوق القانونية، فإن عليهم أيضاً مسؤوليات طوعية وأخرى إلزامية." },
        { en: "abandon", ar: "يتخلّى عن / يترك نهائياً", pos: "verb", def: "leave something forever", defAr: "أن تترك شيئاً إلى الأبد", example: "The nationality law does not give Syrians the right to unilaterally abandon their Syrian nationality.", exampleAr: "لا يعطي قانون الجنسية السوريين الحق في التخلّي من طرف واحد عن جنسيتهم السورية." },
        { en: "unilaterally", ar: "من طرف واحد / بشكل منفرد", pos: "adverb", def: "done by only one member without the agreement of others", defAr: "يقوم به طرف واحد فقط دون موافقة الآخرين", example: "The nationality law does not give Syrians the right to unilaterally abandon their Syrian nationality.", exampleAr: "لا يعطي قانون الجنسية السوريين الحق في التخلّي من طرف واحد عن جنسيتهم السورية." },
        { en: "citizen", ar: "مواطن", pos: "noun", def: "a person who belongs to a particular country and has its rights and duties", defAr: "شخص ينتمي إلى بلد معيّن وله حقوقه وعليه واجباته", example: "Every Syrian citizen must obey state laws, and pay the penalties when a law is broken.", exampleAr: "يجب على كل مواطن سوري أن يطيع قوانين الدولة، وأن يدفع الغرامات عندما يُخالَف القانون." },
        { en: "duty", ar: "واجب", pos: "noun", def: "something that you must do because it is right or the law", defAr: "شيء يجب أن تفعله لأنه صواب أو لأن القانون يفرضه", example: "Citizenship is not only the state of being vested with the rights and duties of a citizen, but it can also be defined as the character of an individual who is viewed as a member of a particular society.", exampleAr: "ليست المواطنة حالة التمتّع بحقوق المواطن وواجباته فحسب، بل يمكن أيضاً تعريفها بأنها صفة الفرد الذي يُنظر إليه على أنه عضو في مجتمع معيّن." },
        { en: "right", ar: "حق", pos: "noun", def: "something that the law allows you to have or do", defAr: "شيء يسمح لك القانون بامتلاكه أو فعله", example: "The Syrian government protects the rights of each individual regardless of their background or culture.", exampleAr: "تحمي الحكومة السورية حقوق كل فرد بغضّ النظر عن خلفيته أو ثقافته." },
        { en: "individual", ar: "فرد", pos: "noun", def: "a single person", defAr: "شخص واحد", example: "The Syrian government protects the rights of each individual regardless of their background or culture.", exampleAr: "تحمي الحكومة السورية حقوق كل فرد بغضّ النظر عن خلفيته أو ثقافته." },
        { en: "society", ar: "مجتمع", pos: "noun", def: "people living together in a country or group with the same laws and customs", defAr: "أناس يعيشون معاً في بلد أو جماعة لها القوانين والعادات نفسها", example: "The concept of citizenship has never been fixed or static, but constantly changes within each society.", exampleAr: "لم يكن مفهوم المواطنة ثابتاً أو جامداً أبداً، بل يتغيّر باستمرار داخل كل مجتمع." },
        { en: "arise", ar: "ينشأ / يظهر", pos: "verb", def: "to begin to exist (past: arose)", defAr: "أن يبدأ الشيء بالوجود (الماضي: arose)", example: "The concept of citizenship first arose in towns and city-states of ancient Greece, disappeared in Europe during the Middle Ages and crystallissed in the 18th century.", exampleAr: "نشأ مفهوم المواطنة أول مرة في مدن اليونان القديمة ودولها المدن، واختفى في أوروبا خلال العصور الوسطى، ثم تبلور في القرن الثامن عشر." },
        { en: "ancient", ar: "قديم / عريق", pos: "adjective", def: "very old; from a long time ago", defAr: "قديم جداً؛ من زمن بعيد", example: "Syrians have the right to pride themselves on being good citizens in a nation of ancient civilisations that helped to build and enrich human culture.", exampleAr: "يحقّ للسوريين أن يفخروا بكونهم مواطنين صالحين في وطن حضارات عريقة ساعدت على بناء الثقافة الإنسانية وإغنائها." },
        { en: "static", ar: "ثابت / جامد", pos: "adjective", def: "not moving or changing", defAr: "لا يتحرّك ولا يتغيّر", example: "The concept of citizenship has never been fixed or static, but constantly changes within each society.", exampleAr: "لم يكن مفهوم المواطنة ثابتاً أو جامداً أبداً، بل يتغيّر باستمرار داخل كل مجتمع." },
        { en: "constantly", ar: "باستمرار / دائماً", pos: "adverb", def: "all the time", defAr: "طوال الوقت", example: "The concept of citizenship has never been fixed or static, but constantly changes within each society.", exampleAr: "لم يكن مفهوم المواطنة ثابتاً أو جامداً أبداً، بل يتغيّر باستمرار داخل كل مجتمع." },
        { en: "vary", ar: "يختلف / يتنوّع", pos: "verb", def: "to be different in different situations or times", defAr: "أن يكون مختلفاً باختلاف المواقف أو الأزمنة", example: "While citizenship has varied considerably throughout history, and within societies over time, there are some common related elements.", exampleAr: "مع أن المواطنة اختلفت كثيراً عبر التاريخ وداخل المجتمعات مع مرور الزمن، فهناك بعض العناصر المشتركة المرتبطة بها." },
        { en: "aspect", ar: "جانب", pos: "noun", def: "one part or side of something", defAr: "جزء أو ناحية من شيء ما", example: "Citizenship refers to many aspects of society such as family, military service, individual's freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.", exampleAr: "تشير المواطنة إلى جوانب كثيرة من المجتمع مثل الأسرة، والخدمة العسكرية، وحرية الفرد، وأفكار الصواب والخطأ، ودفع الضرائب، وأنماط السلوك التي ينبغي أن يتبعها الشخص في المجتمع." },
        { en: "military service", ar: "الخدمة العسكرية", pos: "noun", def: "a period of time serving in the army", defAr: "فترة من الزمن يخدم فيها الشخص في الجيش", example: "Citizenship refers to many aspects of society such as family, military service, individual's freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.", exampleAr: "تشير المواطنة إلى جوانب كثيرة من المجتمع مثل الأسرة، والخدمة العسكرية، وحرية الفرد، وأفكار الصواب والخطأ، ودفع الضرائب، وأنماط السلوك التي ينبغي أن يتبعها الشخص في المجتمع." },
        { en: "freedom", ar: "حرية", pos: "noun", def: "the right to do or say what you want", defAr: "الحق في أن تفعل أو تقول ما تريد", example: "In spite of the fact that all Syrian citizens enjoy freedom, protection and legal rights, they also have responsibilities that are voluntary as well as obligatory.", exampleAr: "على الرغم من أن جميع المواطنين السوريين يتمتعون بالحرية والحماية والحقوق القانونية، فإن عليهم أيضاً مسؤوليات طوعية وأخرى إلزامية." },
        { en: "tax", ar: "ضريبة", pos: "noun", def: "money that you must pay to the government", defAr: "مال يجب أن تدفعه للحكومة", example: "All citizens must pay taxes in one form or another.", exampleAr: "يجب على جميع المواطنين دفع الضرائب بشكل أو بآخر." },
        { en: "behave", ar: "يتصرّف / يسلك", pos: "verb", def: "to act in a particular way", defAr: "أن تتصرّف بطريقة معيّنة", example: "Citizenship refers to many aspects of society such as family, military service, individual's freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.", exampleAr: "تشير المواطنة إلى جوانب كثيرة من المجتمع مثل الأسرة، والخدمة العسكرية، وحرية الفرد، وأفكار الصواب والخطأ، ودفع الضرائب، وأنماط السلوك التي ينبغي أن يتبعها الشخص في المجتمع." },
        { en: "responsibility", ar: "مسؤولية", pos: "noun", def: "a duty to do something or to take care of something", defAr: "واجب أن تفعل شيئاً أو تعتني بشيء", example: "Although Syrian citizenship provides many rights, it also involves many responsibilities.", exampleAr: "مع أن المواطنة السورية تمنح حقوقاً كثيرة، فإنها تتضمّن أيضاً مسؤوليات كثيرة." },
        { en: "involve", ar: "يتضمّن / يشمل", pos: "verb", def: "to include something as a necessary part", defAr: "أن يشمل شيئاً كجزء ضروري منه", example: "Although Syrian citizenship provides many rights, it also involves many responsibilities.", exampleAr: "مع أن المواطنة السورية تمنح حقوقاً كثيرة، فإنها تتضمّن أيضاً مسؤوليات كثيرة." },
        { en: "protect", ar: "يحمي", pos: "verb", def: "to keep someone or something safe", defAr: "أن تحافظ على سلامة شخص أو شيء", example: "The Syrian government protects the rights of each individual regardless of their background or culture.", exampleAr: "تحمي الحكومة السورية حقوق كل فرد بغضّ النظر عن خلفيته أو ثقافته." },
        { en: "regardless of", ar: "بغضّ النظر عن", pos: "preposition", def: "without being affected by something", defAr: "دون أن يتأثر بشيء ما", example: "The Syrian government protects the rights of each individual regardless of their background or culture.", exampleAr: "تحمي الحكومة السورية حقوق كل فرد بغضّ النظر عن خلفيته أو ثقافته." },
        { en: "obligatory", ar: "إلزامي / إجباري", pos: "adjective", def: "that you must do because of a law or rule", defAr: "يجب عليك فعله بسبب قانون أو قاعدة", example: "In spite of the fact that all Syrian citizens enjoy freedom, protection and legal rights, they also have responsibilities that are voluntary as well as obligatory.", exampleAr: "على الرغم من أن جميع المواطنين السوريين يتمتعون بالحرية والحماية والحقوق القانونية، فإن عليهم أيضاً مسؤوليات طوعية وأخرى إلزامية." },
        { en: "obey", ar: "يطيع / يلتزم بـ", pos: "verb", def: "to do what a law or a person tells you to do", defAr: "أن تفعل ما يأمرك به القانون أو شخص ما", example: "Every Syrian citizen must obey state laws, and pay the penalties when a law is broken.", exampleAr: "يجب على كل مواطن سوري أن يطيع قوانين الدولة، وأن يدفع الغرامات عندما يُخالَف القانون." },
        { en: "penalty", ar: "غرامة / عقوبة", pos: "noun", def: "a punishment for breaking a law or rule", defAr: "عقوبة على مخالفة قانون أو قاعدة", example: "Every Syrian citizen must obey state laws, and pay the penalties when a law is broken.", exampleAr: "يجب على كل مواطن سوري أن يطيع قوانين الدولة، وأن يدفع الغرامات عندما يُخالَف القانون." },
        { en: "generation", ar: "جيل", pos: "noun", def: "all the people born at about the same time", defAr: "جميع الناس الذين وُلدوا في الفترة الزمنية نفسها تقريباً", example: "It is the responsibility of citizens to pass along the importance of good citizenship to future generations by teaching their children how to obey the law.", exampleAr: "من مسؤولية المواطنين أن ينقلوا أهمية المواطنة الصالحة إلى الأجيال القادمة بتعليم أطفالهم كيف يطيعون القانون." },
        { en: "nationality", ar: "جنسية", pos: "noun", def: "the legal right of belonging to a particular nation", defAr: "الحق القانوني في الانتماء إلى أمة معيّنة", example: "The nationality law does not give Syrians the right to unilaterally abandon their Syrian nationality.", exampleAr: "لا يعطي قانون الجنسية السوريين الحق في التخلّي من طرف واحد عن جنسيتهم السورية." },
        { en: "pride oneself on", ar: "يفخر بـ / يعتزّ بـ", pos: "verb", def: "to be proud of something you are or do", defAr: "أن تكون فخوراً بشيء أنت عليه أو تفعله", example: "Syrians have the right to pride themselves on being good citizens in a nation of ancient civilisations that helped to build and enrich human culture.", exampleAr: "يحقّ للسوريين أن يفخروا بكونهم مواطنين صالحين في وطن حضارات عريقة ساعدت على بناء الثقافة الإنسانية وإغنائها." },
        { en: "enrich", ar: "يُغني / يُثري", pos: "verb", def: "to improve something by adding something good to it", defAr: "أن تحسّن شيئاً بإضافة شيء جيد إليه", example: "Syrians have the right to pride themselves on being good citizens in a nation of ancient civilisations that helped to build and enrich human culture.", exampleAr: "يحقّ للسوريين أن يفخروا بكونهم مواطنين صالحين في وطن حضارات عريقة ساعدت على بناء الثقافة الإنسانية وإغنائها." },
        { en: "civilisation", ar: "حضارة", pos: "noun", def: "human society with its culture and way of life", defAr: "المجتمع البشري بثقافته وطريقة حياته", example: "They have had a vital role in developing human civilisation.", exampleAr: "لقد كان لهم دور حيوي في تطوير الحضارة الإنسانية." },
        { en: "vital", ar: "حيوي / أساسي", pos: "adjective", def: "very important and necessary", defAr: "مهم جداً وضروري", example: "They have had a vital role in developing human civilisation.", exampleAr: "لقد كان لهم دور حيوي في تطوير الحضارة الإنسانية." },
        { en: "guideline", ar: "توجيه / مبدأ إرشادي", pos: "noun", def: "a piece of advice or a rule about how to do something", defAr: "نصيحة أو قاعدة حول كيفية فعل شيء ما", example: "From the earliest years, laws representing various points of view have been passed and guidelines have been developed through generations to instruct citizens on Syrian history, values, rights, and responsibilities.", exampleAr: "منذ أقدم السنين، أُقرّت قوانين تمثّل وجهات نظر مختلفة، وطُوّرت توجيهات عبر الأجيال لتعليم المواطنين تاريخ سوريا وقيمها وحقوقهم ومسؤولياتهم." },
        { en: "value", ar: "قيمة / مبدأ", pos: "noun", def: "a belief about what is right and important in life", defAr: "اعتقاد حول ما هو صحيح ومهم في الحياة", example: "From the earliest years, laws representing various points of view have been passed and guidelines have been developed through generations to instruct citizens on Syrian history, values, rights, and responsibilities.", exampleAr: "منذ أقدم السنين، أُقرّت قوانين تمثّل وجهات نظر مختلفة، وطُوّرت توجيهات عبر الأجيال لتعليم المواطنين تاريخ سوريا وقيمها وحقوقهم ومسؤولياتهم." },
        { en: "membership", ar: "عضوية", pos: "noun", def: "the state of being a member of a group (from: member)", defAr: "حالة كونك عضواً في جماعة (من الكلمة member)" },
        { en: "active", ar: "نشِط / فعّال", pos: "adjective", def: "doing things and taking part (from: act)", defAr: "يفعل الأشياء ويشارك (من الكلمة act)" },
        { en: "behaviour", ar: "سلوك / تصرّف", pos: "noun", def: "the way a person acts (from: behave)", defAr: "الطريقة التي يتصرّف بها الشخص (من الكلمة behave)" },
        { en: "election", ar: "انتخابات", pos: "noun", def: "choosing people for an official job by voting (from: elect)", defAr: "اختيار أشخاص لمنصب رسمي عن طريق التصويت (من الكلمة elect)" },
        { en: "devotion", ar: "إخلاص / تفانٍ", pos: "noun", def: "great love and loyalty (from: devote)", defAr: "حب كبير ووفاء (من الكلمة devote)" },
        { en: "employment", ar: "عمل / توظيف", pos: "noun", def: "work that you do (from: employ)", defAr: "العمل الذي تقوم به (من الكلمة employ)" },
        { en: "patriotism", ar: "الوطنية / حب الوطن", pos: "noun", def: "love of and devotion to one's country", defAr: "حب الإنسان لبلده وإخلاصه له" },
        { en: "polite", ar: "مهذّب / مؤدّب", pos: "adjective", def: "behaving well and respecting other people", defAr: "يتصرّف بشكل حسن ويحترم الآخرين", example: "To be a good citizen, one should be polite in everyday activities.", exampleAr: "لكي يكون المرء مواطناً صالحاً، ينبغي أن يكون مهذّباً في أنشطته اليومية." },
        { en: "community", ar: "مجتمع محلي / جماعة", pos: "noun", def: "the people who live in the same area", defAr: "الناس الذين يعيشون في المنطقة نفسها" },
      ],
      reading: {
        title: "Citizenship",
        paragraphs: [
          "Citizenship is not only the state of being vested with the rights and duties of a citizen, but it can also be defined as the character of an individual who is viewed as a member of a particular society. The concept of citizenship first arose in towns and city-states of ancient Greece, disappeared in Europe during the Middle Ages and crystallissed in the 18th century. The concept of citizenship has never been fixed or static, but constantly changes within each society.",
          "While citizenship has varied considerably throughout history, and within societies over time, there are some common related elements. Citizenship refers to many aspects of society such as family, military service, individual's freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.",
          "Although Syrian citizenship provides many rights, it also involves many responsibilities. The Syrian government protects the rights of each individual regardless of their background or culture. In spite of the fact that all Syrian citizens enjoy freedom, protection and legal rights, they also have responsibilities that are voluntary as well as obligatory. Every Syrian citizen must obey state laws, and pay the penalties when a law is broken. All citizens must pay taxes in one form or another. It is the responsibility of citizens to pass along the importance of good citizenship to future generations by teaching their children how to obey the law. The nationality law does not give Syrians the right to unilaterally abandon their Syrian nationality.",
          "Syrians have the right to pride themselves on being good citizens in a nation of ancient civilisations that helped to build and enrich human culture. They have had a vital role in developing human civilisation. From the earliest years, laws representing various points of view have been passed and guidelines have been developed through generations to instruct citizens on Syrian history, values, rights, and responsibilities.",
        ],
        paragraphsAr: [
          "ليست المواطنة حالة التمتّع بحقوق المواطن وواجباته فحسب، بل يمكن أيضاً تعريفها بأنها صفة الفرد الذي يُنظر إليه على أنه عضو في مجتمع معيّن. نشأ مفهوم المواطنة أول مرة في مدن اليونان القديمة ودولها المدن، واختفى في أوروبا خلال العصور الوسطى، ثم تبلور في القرن الثامن عشر. لم يكن مفهوم المواطنة ثابتاً أو جامداً أبداً، بل يتغيّر باستمرار داخل كل مجتمع.",
          "مع أن المواطنة اختلفت كثيراً عبر التاريخ وداخل المجتمعات مع مرور الزمن، فهناك بعض العناصر المشتركة المرتبطة بها. تشير المواطنة إلى جوانب كثيرة من المجتمع مثل الأسرة، والخدمة العسكرية، وحرية الفرد، وأفكار الصواب والخطأ، ودفع الضرائب، وأنماط السلوك التي ينبغي أن يتبعها الشخص في المجتمع.",
          "مع أن المواطنة السورية تمنح حقوقاً كثيرة، فإنها تتضمّن أيضاً مسؤوليات كثيرة. تحمي الحكومة السورية حقوق كل فرد بغضّ النظر عن خلفيته أو ثقافته. وعلى الرغم من أن جميع المواطنين السوريين يتمتعون بالحرية والحماية والحقوق القانونية، فإن عليهم أيضاً مسؤوليات طوعية وأخرى إلزامية. يجب على كل مواطن سوري أن يطيع قوانين الدولة، وأن يدفع الغرامات عندما يُخالَف القانون. ويجب على جميع المواطنين دفع الضرائب بشكل أو بآخر. ومن مسؤولية المواطنين أن ينقلوا أهمية المواطنة الصالحة إلى الأجيال القادمة بتعليم أطفالهم كيف يطيعون القانون. ولا يعطي قانون الجنسية السوريين الحق في التخلّي من طرف واحد عن جنسيتهم السورية.",
          "يحقّ للسوريين أن يفخروا بكونهم مواطنين صالحين في وطن حضارات عريقة ساعدت على بناء الثقافة الإنسانية وإغنائها. لقد كان لهم دور حيوي في تطوير الحضارة الإنسانية. ومنذ أقدم السنين، أُقرّت قوانين تمثّل وجهات نظر مختلفة، وطُوّرت توجيهات عبر الأجيال لتعليم المواطنين تاريخ سوريا وقيمها وحقوقهم ومسؤولياتهم.",
        ],
        questions: [
          { q: "Where did the concept of citizenship first arise?", qAr: "أين نشأ مفهوم المواطنة أول مرة؟",
            options: ["In Europe during the Middle Ages.", "In towns and city-states of ancient Greece.", "In Syria in the 18th century.", "In ancient Rome."],
            answer: 1, explainAr: "الفقرة الأولى: The concept of citizenship first arose in towns and city-states of ancient Greece. أما في أوروبا في العصور الوسطى فقد اختفى." },
          { q: "What aspects does citizenship refer to?", qAr: "ما الجوانب التي تشير إليها المواطنة؟",
            options: ["Only paying taxes.", "Only the rights of the government.", "Family, military service, individual's freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.", "Travelling, studying abroad and learning languages."],
            answer: 2, explainAr: "الفقرة الثانية تعدّد هذه الجوانب كلها بعد عبارة such as." },
          { q: "Name the two kinds of responsibilities of citizenship.", qAr: "اذكر نوعَي مسؤوليات المواطنة.",
            options: ["Voluntary and obligatory.", "Legal and illegal.", "Military and political.", "Old and new."],
            answer: 0, explainAr: "النص يقول: they also have responsibilities that are voluntary as well as obligatory — أي طوعية وإلزامية." },
          { q: "Why do some people pay penalties?", qAr: "لماذا يدفع بعض الناس غرامات؟",
            options: ["Because they pay taxes.", "Because they abandon their nationality.", "Because they teach their children.", "Because they break a law."],
            answer: 3, explainAr: "النص يقول: pay the penalties when a law is broken — أي عندما يخالفون القانون." },
          { q: "Why is it necessary to pass the concept of citizenship to the coming generation?", qAr: "لماذا من الضروري نقل مفهوم المواطنة إلى الجيل القادم؟",
            options: ["Because the government will pay the citizens.", "Because it is the responsibility of citizens, so their children learn how to obey the law.", "Because children must do military service.", "Because the concept never changes."],
            answer: 1, explainAr: "النص يقول: It is the responsibility of citizens to pass along the importance of good citizenship to future generations by teaching their children how to obey the law." },
          { q: "Correct the information: “In Syria, the rights of each individual are preserved due to background or culture.” Replace “due to” with words from the text.", qAr: "صحّح المعلومة: “في سوريا، تُصان حقوق كل فرد بسبب خلفيته أو ثقافته.” استبدل “due to” بكلمات من النص.",
            options: ["because of", "regardless of", "in spite of the fact that", "as well as"],
            answer: 1, explainAr: "النص يقول: protects the rights of each individual regardless of their background or culture — أي بغضّ النظر عن الخلفية أو الثقافة، لا بسببها." },
          { q: "Correct the information: “Throughout history, Syrians have played a minor role in building human civilisation.” Replace “minor” with a word from the text.", qAr: "صحّح المعلومة: “عبر التاريخ، أدّى السوريون دوراً ثانوياً في بناء الحضارة الإنسانية.” استبدل “minor” بكلمة من النص.",
            options: ["static", "small", "vital", "voluntary"],
            answer: 2, explainAr: "النص يقول: They have had a vital role in developing human civilisation — دور حيوي وليس ثانوياً." },
          { q: "Correct the information: “It is optional for citizens to obey the laws of their society.” Replace “optional” with a word from the text.", qAr: "صحّح المعلومة: “طاعة قوانين المجتمع أمر اختياري للمواطنين.” استبدل “optional” بكلمة من النص.",
            options: ["voluntary", "obligatory", "unilateral", "legal"],
            answer: 1, explainAr: "النص يقول: Every Syrian citizen must obey state laws — كلمة must تعني أن الطاعة إلزامية (obligatory)." },
        ],
        trueFalse: [
          { statement: "The concept of citizenship is the same in all societies.", answer: false },
          { statement: "The concept of citizenship disappeared in Europe during the Middle Ages.", answer: true },
          { statement: "All citizens must pay taxes in one form or another.", answer: true },
          { statement: "The nationality law gives Syrians the right to unilaterally abandon their Syrian nationality.", answer: false },
          { statement: "Syrians have had a vital role in developing human civilisation.", answer: true },
        ],
      },
      extraReadings: [
        {
          title: "Listening extract: How a good citizen behaves",
          paragraphs: [
            "When it comes to what it takes to be a good (1) ……………, the public has a long list of traits and (2) …………… that it says are important. It is important that you understand the (3) …………… of good citizenship. These rules help you at (4) ……………, at (5) ……………, and everywhere you go. You should use these rules in your everyday life because they (6) …………… with sharing, helping people, and being a good person. The rules to being a good citizen no matter where you live or who you are with. Good citizens always (7) …………… things if someone needs something. If you are able to offer (8) …………… hand by carrying something for a friend who has their hands full or offering a pencil, for example, to the person sitting next to you then you should do it. Sharing (9) …………… taking turns, asking nicely before borrowing someone's things, and (10) …………… you can to help.",
            "Sometimes it is not okay to share and you do not have to.",
          ],
          paragraphsAr: [
            "عندما يتعلّق الأمر بما يلزم ليكون المرء (1) …… صالحاً، فلدى الناس قائمة طويلة من الصفات و(2) …… التي يقولون إنها مهمة. من المهم أن تفهم (3) …… المواطنة الصالحة. تساعدك هذه القواعد في (4) ……، وفي (5) ……، وفي كل مكان تذهب إليه. ينبغي أن تستخدم هذه القواعد في حياتك اليومية لأنها (6) …… بالمشاركة، ومساعدة الناس، وأن تكون شخصاً صالحاً. قواعد المواطن الصالح (تنطبق) أينما عشت ومع من كنت. المواطنون الصالحون دائماً (7) …… الأشياء إذا احتاج أحد إلى شيء. إذا كنت قادراً على أن تمدّ (8) …… العون بحمل شيء عن صديق يداه مشغولتان، أو بإعطاء قلم مثلاً للشخص الجالس بجانبك، فعليك أن تفعل ذلك. المشاركة (9) …… تبادل الأدوار، والاستئذان بلطف قبل استعارة أغراض الآخرين، و(10) …… تستطيع لتساعد.",
            "أحياناً لا يكون من المناسب أن تشارك أغراضك، وليس عليك أن تفعل ذلك.",
          ],
          questions: [
            { q: "The main idea of the extract is …", qAr: "الفكرة الرئيسية للمقطع هي …",
              options: ["rights of citizens", "how a good citizen should behave", "paying taxes", "the history of citizenship"],
              answer: 1, explainAr: "التمرين b1 من الكتاب: المقطع كله عن قواعد سلوك المواطن الصالح (المشاركة، المساعدة، الاستئذان قبل الاستعارة)." },
            { q: "What should you do if a friend has their hands full?", qAr: "ماذا ينبغي أن تفعل إذا كانت يدا صديقك مشغولتين؟",
              options: ["Borrow his things.", "Offer a hand by carrying something for him.", "Wait until he asks you.", "Offer him a pencil."],
              answer: 1, explainAr: "النص يقول: If you are able to offer a hand by carrying something for a friend who has their hands full … then you should do it." },
            { q: "What should you do before borrowing someone's things?", qAr: "ماذا ينبغي أن تفعل قبل استعارة أغراض شخص آخر؟",
              options: ["Ask nicely.", "Take them quickly.", "Pay for them.", "Share your food."],
              answer: 0, explainAr: "النص يذكر: asking nicely before borrowing someone's things — أي أن تستأذن بلطف." },
            { q: "According to the extract, do you always have to share?", qAr: "بحسب المقطع، هل عليك أن تشارك أغراضك دائماً؟",
              options: ["Yes, always.", "Only with your family.", "No. Sometimes it is not okay to share and you do not have to.", "Only at school."],
              answer: 2, explainAr: "الجملة الأخيرة: Sometimes it is not okay to share and you do not have to." },
          ],
        },
      ],
      vocabFocus: {
        name: "Word family and Adjectives followed by prepositions", nameAr: "عائلة الكلمة والصفات التي يتبعها حرف جر",
        ruleEn: [
          "Word family: we make new words from a root word, e.g. member → membership, act → active, behave → behaviour, elect → election, devote → devotion, employ → employment.",
          "Some adjectives can be followed by a preposition + noun: afraid of, angry with, brilliant / good at, keen on, busy with, careless with, grateful for, proud of, sure about, surprised by, cruel to.",
          "Some adjectives are followed by a preposition + -ing form: She was sick of cleaning dishes. My brother is used to working at night.",
        ],
        ruleAr: [
          "عائلة الكلمة: نشتقّ من الكلمة الأصلية كلمات جديدة بإضافة لواحق: ship- و ion- و ment- و iour- تصنع أسماء (membership, election, employment, behaviour)، و ive- تصنع صفة (active).",
          "انظر إلى مكان الفراغ: بعد a / an / the أو صفة نحتاج اسماً (voluntary employment)، وقبل الاسم نحتاج صفة (an active role).",
          "بعض الصفات يأتي بعدها حرف جر خاص بها يجب حفظه معها: afraid of (خائف من)، angry with (غاضب من شخص)، good / brilliant at (بارع في)، keen on (مولع بـ)، busy with (مشغول بـ)، careless with (مهمل في)، grateful for (ممتنّ لـ)، proud of (فخور بـ)، sure about (متأكد من)، surprised by (مندهش من)، cruel to (قاسٍ على).",
          "إذا جاء بعد حرف الجر فعل، فإنه يأتي بصيغة ing: sick of cleaning (سئم من التنظيف)، used to working (معتاد على العمل). انتبه: to في used to هنا حرف جر، لذلك نقول working وليس work.",
        ],
        examples: [
          "I’m afraid of spiders.",
          "Laila is angry with her little brother.",
          "He’s very keen on chess.",
          "Tom was busy with his work.",
          "My grandfather is careless with his money.",
          "The people were grateful for our help.",
          "The parents were proud of their child’s achievement.",
          "I was surprised by her exam results.",
          "Suzy’s dog was cruel to her.",
          "She was sick of cleaning dishes.",
          "My brother is used to working at night.",
        ],
        exercises: [
          // Book exercise a — word family
          { type: "fill", prompt: "Citizenship is ___ in a political community. (member)", promptAr: "المواطنة هي ___ في مجتمع سياسي. (member)", promptArFull: "المواطنة هي عضوية في مجتمع سياسي.", options: ["member", "membership", "members"], answer: 1, explainAr: "نحتاج اسماً يدل على الحالة (العضوية): member + ship = membership، كما في citizenship." },
          { type: "fill", prompt: "Some citizens take an ___ role in the community. (act)", promptAr: "يؤدّي بعض المواطنين دوراً ___ في المجتمع. (act)", promptArFull: "يؤدّي بعض المواطنين دوراً فعّالاً في المجتمع.", options: ["act", "action", "active", "actively"], answer: 2, explainAr: "قبل الاسم role نحتاج صفة: act + ive = active (فعّال). و an تناسب الصفة التي تبدأ بحرف علة." },
          { type: "fill", prompt: "Civic ___ is what citizens are expected to demonstrate in their daily lives. (behave)", promptAr: "___ المدني هو ما يُتوقَّع من المواطنين أن يُظهروه في حياتهم اليومية. (behave)", promptArFull: "السلوك المدني هو ما يُتوقَّع من المواطنين أن يُظهروه في حياتهم اليومية.", options: ["behave", "behaviour", "behaved", "behaving"], answer: 1, explainAr: "بعد الصفة Civic نحتاج اسماً: behave → behaviour (سلوك)." },
          { type: "fill", prompt: "She was too young to vote in the national ___ . (elect)", promptAr: "كانت صغيرة جداً على التصويت في ___ الوطنية. (elect)", promptArFull: "كانت صغيرة جداً على التصويت في الانتخابات الوطنية.", options: ["elect", "elections", "elected", "elective"], answer: 1, explainAr: "بعد the national نحتاج اسماً: elect + ion = election، ونستخدم الجمع elections (الانتخابات)." },
          { type: "fill", prompt: "Patriotism is love of and ___ to one's country. (devote)", promptAr: "الوطنية هي حب الإنسان لبلده و___ له. (devote)", promptArFull: "الوطنية هي حب الإنسان لبلده وإخلاصه له.", options: ["devote", "devoted", "devotion", "devotedly"], answer: 2, explainAr: "الكلمة معطوفة على الاسم love بـ and، فنحتاج اسماً: devote → devotion (إخلاص)." },
          { type: "fill", prompt: "In economics, voluntary ___ is unpaid. (employ)", promptAr: "في الاقتصاد، ___ التطوعي غير مدفوع الأجر. (employ)", promptArFull: "في الاقتصاد، العمل التطوعي غير مدفوع الأجر.", options: ["employ", "employer", "employment", "employed"], answer: 2, explainAr: "بعد الصفة voluntary نحتاج اسماً يدل على العمل: employ + ment = employment. أما employer فتعني صاحب العمل." },
          // More word family from the reading
          { type: "fill", prompt: "It is the ___ of citizens to pass along the importance of good citizenship to future generations. (responsible)", promptAr: "من ___ المواطنين أن ينقلوا أهمية المواطنة الصالحة إلى الأجيال القادمة. (responsible)", promptArFull: "من مسؤولية المواطنين أن ينقلوا أهمية المواطنة الصالحة إلى الأجيال القادمة.", options: ["responsible", "responsibility", "responsibly"], answer: 1, explainAr: "بعد the نحتاج اسماً: responsible → responsibility (مسؤولية)." },
          { type: "fill", prompt: "All Syrian citizens enjoy freedom, ___ and legal rights. (protect)", promptAr: "يتمتع جميع المواطنين السوريين بالحرية و___ والحقوق القانونية. (protect)", promptArFull: "يتمتع جميع المواطنين السوريين بالحرية والحماية والحقوق القانونية.", options: ["protect", "protective", "protection"], answer: 2, explainAr: "الكلمة في قائمة أسماء (freedom … rights)، فنحتاج اسماً: protect + ion = protection." },
          { type: "fill", prompt: "They also have responsibilities that are voluntary as well as ___ . (oblige)", promptAr: "عليهم أيضاً مسؤوليات طوعية وأخرى ___ . (oblige)", promptArFull: "عليهم أيضاً مسؤوليات طوعية وأخرى إلزامية.", options: ["oblige", "obligatory", "obligation"], answer: 1, explainAr: "الكلمة معطوفة على الصفة voluntary، فنحتاج صفة: obligatory (إلزامي)." },
          { type: "fill", prompt: "They have had a vital role in developing human ___ . (civilise)", promptAr: "لقد كان لهم دور حيوي في تطوير ___ الإنسانية. (civilise)", promptArFull: "لقد كان لهم دور حيوي في تطوير الحضارة الإنسانية.", options: ["civilise", "civilised", "civilisation"], answer: 2, explainAr: "بعد الصفة human نحتاج اسماً: civilise → civilisation (حضارة)." },
          // Book exercise a — short dialogues (adjective + preposition)
          { type: "fill", prompt: "A: (Bell, why/ be/ you/ angry/ Jack?) ___", promptAr: "أ: (بيل، لماذا/ يكون/ أنتِ/ غاضبة/ جاك؟) ___", promptArFull: "أ: بيل، لماذا أنتِ غاضبة من جاك؟", options: ["Bell, why are you angry with Jack?", "Bell, why are you angry of Jack?", "Bell, why you are angry with Jack?", "Bell, why is you angry to Jack?"], answer: 0, explainAr: "المثال في الكتاب: angry with + شخص، وفي السؤال يأتي are قبل you." },
          { type: "fill", prompt: "B: (Because he/ be/ very careless/ his money) ___", promptAr: "ب: (لأن هو/ يكون/ مهمل جداً/ ماله) ___", promptArFull: "ب: لأنه مهمل جداً في ماله.", options: ["Because he is very careless of his money.", "Because he is very careless with his money.", "Because he are very careless with his money.", "Because he is very careless about his money."], answer: 1, explainAr: "المثال في الكتاب: careless with (مهمل في)، ومع he نستخدم is." },
          { type: "fill", prompt: "A: (be/ their son/ good/ school work?) ___", promptAr: "أ: (يكون/ ابنهم/ جيد/ الواجبات المدرسية؟) ___", promptArFull: "أ: هل ابنهم جيد في واجباته المدرسية؟", options: ["Is their son good in school work?", "Is their son good at school work?", "Their son is good at school work?", "Are their son good at school work?"], answer: 1, explainAr: "good at = جيد في / بارع في، والسؤال بصيغة Yes/No يبدأ بـ Is لأن الفاعل مفرد (their son)." },
          { type: "fill", prompt: "B: (Yes, in fact he/ be/ brilliant/ everything) ___", promptAr: "ب: (نعم، في الحقيقة هو/ يكون/ بارع/ كل شيء) ___", promptArFull: "ب: نعم، في الحقيقة هو بارع في كل شيء.", options: ["Yes, in fact he is brilliant on everything.", "Yes, in fact he is brilliant with everything.", "Yes, in fact he is brilliant at everything.", "Yes, in fact he brilliant at everything."], answer: 2, explainAr: "brilliant at مثل good at: بارع في." },
          { type: "fill", prompt: "A: (be/ you pleased/ Anna’s exam result?) ___", promptAr: "أ: (يكون/ أنتم مسرورون/ نتيجة امتحان آنا؟) ___", promptArFull: "أ: هل أنتم مسرورون بنتيجة امتحان آنا؟", options: ["Are you pleased with Anna’s exam result?", "Are you pleased of Anna’s exam result?", "Is you pleased with Anna’s exam result?", "You are pleased at Anna’s exam result?"], answer: 0, explainAr: "pleased with = مسرور بـ، والسؤال يبدأ بـ Are مع you." },
          { type: "fill", prompt: "B: (Yes, we/ be/ very proud/ her) ___", promptAr: "ب: (نعم، نحن/ يكون/ فخورون جداً/ هي) ___", promptArFull: "ب: نعم، نحن فخورون بها جداً.", options: ["Yes, we are very proud with her.", "Yes, we are very proud of her.", "Yes, we is very proud of her.", "Yes, we are very proud for her."], answer: 1, explainAr: "proud of = فخور بـ، ومع we نستخدم are." },
          { type: "fill", prompt: "A: (Why/ be/ Mr Jack’s dog/ afraid/ him?) ___", promptAr: "أ: (لماذا/ يكون/ كلب السيد جاك/ خائف/ هو؟) ___", promptArFull: "أ: لماذا يخاف كلب السيد جاك منه؟", options: ["Why is Mr Jack’s dog afraid from him?", "Why Mr Jack’s dog is afraid of him?", "Why is Mr Jack’s dog afraid of him?", "Why are Mr Jack’s dog afraid of him?"], answer: 2, explainAr: "afraid of = خائف من، وفي السؤال يأتي is قبل الفاعل Mr Jack’s dog." },
          { type: "fill", prompt: "B: (Because he/ be/ often/ cruel/ it) ___", promptAr: "ب: (لأن هو/ يكون/ غالباً/ قاسٍ/ هو) ___", promptArFull: "ب: لأنه غالباً ما يكون قاسياً عليه.", options: ["Because he is often cruel to it.", "Because he is often cruel with it.", "Because he often is cruel of it.", "Because he are often cruel to it."], answer: 0, explainAr: "cruel to = قاسٍ على، وظرف التكرار often يأتي بعد الفعل is." },
          // More adjectives + prepositions from the book's list
          { type: "fill", prompt: "I’m afraid ___ spiders.", promptAr: "أنا خائف ___ العناكب.", promptArFull: "أنا خائف من العناكب.", options: ["from", "of", "with"], answer: 1, explainAr: "afraid of = خائف من. لا نقول afraid from." },
          { type: "fill", prompt: "He’s very keen ___ chess.", promptAr: "إنه مولع جداً ___ الشطرنج.", promptArFull: "إنه مولع جداً بالشطرنج.", options: ["on", "at", "of"], answer: 0, explainAr: "keen on = مولع بـ / متحمّس لـ." },
          { type: "fill", prompt: "The people were grateful ___ our help.", promptAr: "كان الناس ممتنّين ___ مساعدتنا.", promptArFull: "كان الناس ممتنّين لمساعدتنا.", options: ["of", "to", "for"], answer: 2, explainAr: "grateful for + الشيء = ممتنّ لـ (على شيء)." },
          { type: "fill", prompt: "I was surprised ___ her exam results.", promptAr: "اندهشت ___ نتائج امتحانها.", promptArFull: "اندهشت من نتائج امتحانها.", options: ["by", "on", "for"], answer: 0, explainAr: "surprised by = مندهش من." },
          { type: "fill", prompt: "She was sick of ___ dishes.", promptAr: "كانت قد سئمت من ___ الصحون.", promptArFull: "كانت قد سئمت من تنظيف الصحون.", options: ["clean", "to clean", "cleaning"], answer: 2, explainAr: "بعد حرف الجر of يأتي الفعل بصيغة ing: sick of cleaning." },
          { type: "fill", prompt: "My brother is used to ___ at night.", promptAr: "أخي معتاد على ___ في الليل.", promptArFull: "أخي معتاد على العمل في الليل.", options: ["work", "working", "works"], answer: 1, explainAr: "to في be used to حرف جر، فيأتي بعده الفعل بصيغة ing: used to working." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["Are you sure of the information he has just given you?", "Are you sure about the information he has just given you?", "Are you sure with the information he has just given you?"], answer: 1, explainAr: "في قائمة الكتاب: sure about = متأكد من." },
        ],
      },
      grammar: {
        name: "Paired Conjunctions", nameAr: "أدوات الربط المزدوجة",
        ruleEn: [
          "both...and, not only...but also, either…or, neither...nor",
          "Two subjects connected by both ... and take a plural verb: Both my mother and my sister are here.",
          "When two subjects are connected by not only...but also, either...or, or neither...nor, the subject that is closer to the verb determines whether the verb is singular or plural: Not only my mother but also my sister is here. Not only my sister but also my parents are here. Neither my mother nor my sister is here. Neither my sister nor my parents are here.",
          "Not only...but also is used for emphasis or to indicate surprise.",
          "Notice the parallel structure in the examples. The same grammatical forms should follow each part of the paired conjunctions: both time and money / not only a fox … but also a bear / either chemistry or physics / neither interesting nor accurate.",
          "Paired conjunctions are usually used for emphasis; they draw attention to both parts of the parallel structure.",
        ],
        ruleAr: [
          "أدوات الربط المزدوجة تربط شيئين معاً: both...and (كلاهما / … و …)، not only...but also (ليس فقط … بل أيضاً)، either...or (إمّا … أو)، neither...nor (لا … ولا).",
          "مع both...and يكون الفعل دائماً جمعاً لأن الفاعل شخصان أو شيئان: Both my mother and my sister are here.",
          "مع not only...but also و either...or و neither...nor ننظر إلى الفاعل الأقرب إلى الفعل (الفاعل الثاني): إن كان مفرداً فالفعل مفرد (is / lies)، وإن كان جمعاً فالفعل جمع (are / lie).",
          "neither...nor معناها منفي، لذلك يأتي الفعل بعدها مثبتاً: Neither Tom nor Paul lies (وليس doesn’t lie).",
          "التوازي: يجب أن يأتي بعد جزأي الأداة الشكل النحوي نفسه: اسم + اسم (time and money)، صفة + صفة (interesting nor accurate)، فعل + فعل (apologise or leave).",
          "نستخدم not only...but also للتأكيد أو لإظهار الدهشة، وتلفت أدوات الربط المزدوجة الانتباه إلى الجزأين معاً.",
          "عند إعادة الصياغة: So does Linda → Both … and، Neither is Tom → Neither … nor، والجملتان المتكرّرتان (I’ve betrayed … I’ve betrayed …) → not only … but also.",
        ],
        examples: [
          "Both my mother and my sister are here.",
          "Not only my mother but also my sister is here.",
          "Not only my sister but also my parents are here.",
          "Neither my mother nor my sister is here.",
          "Neither my sister nor my parents are here",
          "The research project will take both time and money.",
          "Sue saw not only a fox in the woods but also a bear.",
          "I’ll take either chemistry or physics next quarter.",
          "That book is neither interesting nor accurate.",
          "Neither Tom nor Paul lies to their friends.",
        ],
        exercises: [
          // Book exercise — rewrite with paired conjunctions
          { type: "mcq", prompt: "Rewrite with (neither...nor): “Tom doesn’t lie to his friends. Paul doesn’t either.”", promptAr: "أعد الصياغة باستخدام (neither...nor): “توم لا يكذب على أصدقائه. وبول لا يكذب أيضاً.”", options: ["Neither Tom nor Paul lies to their friends.", "Neither Tom nor Paul doesn’t lie to their friends.", "Neither Tom or Paul lies to their friends.", "Neither Tom nor Paul lie to his friends."], answer: 0, explainAr: "المثال في الكتاب: neither...nor منفية بنفسها فلا نضيف doesn’t، والفعل يتبع الفاعل الأقرب Paul (مفرد) فنقول lies." },
          { type: "mcq", prompt: "Rewrite with (both...and): “Fred likes helping his friends. So does Linda.”", promptAr: "أعد الصياغة باستخدام (both...and): “فريد يحب مساعدة أصدقائه. وكذلك ليندا.”", options: ["Both Fred and Linda likes helping their friends.", "Both Fred and Linda like helping their friends.", "Both Fred or Linda like helping their friends.", "Fred both Linda like helping their friends."], answer: 1, explainAr: "فاعلان مربوطان بـ both...and يأخذان فعلاً جمعاً: like (بدون s)." },
          { type: "build", prompt: "رتّب الكلمات (either...or): كان هاري يساعد إمّا آن أو هيلين.", answer: "Harry used to help either Ann or Helen.", extraWords: ["neither", "nor"] },
          { type: "mcq", prompt: "Rewrite with (not only...but also): “We should learn to accept our weaknesses and our strengths.”", promptAr: "أعد الصياغة باستخدام (not only...but also): “ينبغي أن نتعلّم تقبّل نقاط ضعفنا ونقاط قوتنا.”", options: ["We should learn to accept not only our weaknesses but also our strengths.", "We should learn not only to accept our weaknesses but also our strengths.", "Not only we should learn to accept our weaknesses but also our strengths.", "We should learn to accept not only our weaknesses and also our strengths."], answer: 0, explainAr: "التوازي: بعد not only اسم (our weaknesses) وبعد but also اسم (our strengths)." },
          { type: "mcq", prompt: "Rewrite with (neither...nor): “He never listens to or advises his friends when they have a problem.”", promptAr: "أعد الصياغة باستخدام (neither...nor): “إنه لا يستمع أبداً إلى أصدقائه ولا ينصحهم عندما تكون لديهم مشكلة.”", options: ["He neither listens to nor advises his friends when they have a problem.", "He neither doesn’t listen to nor advises his friends when they have a problem.", "He never neither listens to nor advises his friends when they have a problem.", "He neither listens to or advises his friends when they have a problem."], answer: 0, explainAr: "neither...nor تحلّ محلّ never (فهي منفية)، وبعد جزأيها فعلان متوازيان: listens to / advises." },
          { type: "mcq", prompt: "Rewrite with (not only...but also): “I’ve betrayed your trust. I’ve betrayed your love for me.”", promptAr: "أعد الصياغة باستخدام (not only...but also): “لقد خنتُ ثقتك. لقد خنتُ حبّك لي.”", options: ["I’ve betrayed not only your trust but your love also for me.", "I’ve betrayed not only your trust but also your love for me.", "I’ve not only betrayed your trust but also your love for me.", "Not only I’ve betrayed your trust but also your love for me."], answer: 1, explainAr: "الفعل المشترك betrayed نذكره مرة واحدة، ثم اسم بعد not only (your trust) واسم بعد but also (your love)." },
          { type: "build", prompt: "رتّب الكلمات (both...and): شعر بخيبة الأمل وبأنه غير مفهوم معاً.", answer: "He felt both disappointed and misunderstood.", extraWords: ["neither", "or"] },
          { type: "mcq", prompt: "Rewrite with (neither...nor): “Brian isn’t very considerate. Neither is Tom.”", promptAr: "أعد الصياغة باستخدام (neither...nor): “براين ليس مراعياً لمشاعر الآخرين كثيراً. ولا توم أيضاً.”", options: ["Neither Brian nor Tom are very considerate.", "Neither Brian nor Tom isn’t very considerate.", "Neither Brian nor Tom is very considerate.", "Neither Brian or Tom is very considerate."], answer: 2, explainAr: "الفعل يتبع الفاعل الأقرب Tom (مفرد) فنقول is، ولا ننفي الفعل لأن neither منفية." },
          { type: "build", prompt: "رتّب الكلمات (both...and): الصديق الحقيقي هو شخص حنون ومحبّ في آنٍ معاً.", answer: "A true friend is someone who is both caring and loving.", extraWords: ["either", "nor"] },
          { type: "mcq", prompt: "Rewrite with (either...or): “Rachel should apologise or leave.”", promptAr: "أعد الصياغة باستخدام (either...or): “ينبغي أن تعتذر راشيل أو تغادر.”", options: ["Rachel should either apologise or leave.", "Rachel either should apologise or leaving.", "Either Rachel should apologise or leave.", "Rachel should either apologise nor leave."], answer: 0, explainAr: "التوازي: فعلان مجرّدان بعد should: either apologise or leave." },
          { type: "build", prompt: "رتّب الكلمات (neither...nor): لم يحفظ لا ريتشارد ولا جون سرّها.", answer: "Neither Richard nor John kept her secret.", extraWords: ["didn’t", "or"] },
          // Subject–verb agreement (book examples)
          { type: "fill", prompt: "Both my mother and my sister ___ here.", promptAr: "كلٌّ من أمي وأختي ___ هنا.", promptArFull: "كلٌّ من أمي وأختي موجودتان هنا.", options: ["is", "are", "am"], answer: 1, explainAr: "فاعلان مربوطان بـ both...and يأخذان فعلاً جمعاً: are." },
          { type: "fill", prompt: "Not only my mother but also my sister ___ here.", promptAr: "ليست أمي فقط بل أختي أيضاً ___ هنا.", promptArFull: "ليست أمي فقط بل أختي أيضاً موجودة هنا.", options: ["are", "be", "is"], answer: 2, explainAr: "مع not only...but also الفعل يتبع الفاعل الأقرب my sister (مفرد): is." },
          { type: "fill", prompt: "Not only my sister but also my parents ___ here.", promptAr: "ليست أختي فقط بل والداي أيضاً ___ هنا.", promptArFull: "ليست أختي فقط بل والداي أيضاً موجودان هنا.", options: ["are", "is", "was"], answer: 0, explainAr: "الفاعل الأقرب my parents (جمع)، فالفعل are." },
          { type: "fill", prompt: "Neither my mother nor my sister ___ here.", promptAr: "لا أمي ولا أختي ___ هنا.", promptArFull: "لا أمي ولا أختي موجودة هنا.", options: ["are", "is", "isn’t"], answer: 1, explainAr: "الفاعل الأقرب my sister (مفرد) فنقول is، ولا نقول isn’t لأن neither...nor منفية أصلاً." },
          { type: "fill", prompt: "Neither my sister nor my parents ___ here.", promptAr: "لا أختي ولا والداي ___ هنا.", promptArFull: "لا أختي ولا والداي موجودون هنا.", options: ["is", "aren’t", "are"], answer: 2, explainAr: "الفاعل الأقرب my parents (جمع) فنقول are، دون نفي." },
          { type: "fill", prompt: "The research project will take both time ___ money.", promptAr: "سيحتاج مشروع البحث إلى الوقت ___ المال معاً.", promptArFull: "سيحتاج مشروع البحث إلى الوقت والمال معاً.", options: ["or", "and", "nor", "but also"], answer: 1, explainAr: "both تأتي دائماً مع and." },
          { type: "fill", prompt: "Sue saw not only a fox in the woods ___ a bear.", promptAr: "رأت سو في الغابة ليس ثعلباً فقط ___ دبّاً.", promptArFull: "رأت سو في الغابة ليس ثعلباً فقط بل دبّاً أيضاً.", options: ["and", "or", "but also", "nor"], answer: 2, explainAr: "not only تأتي مع but also." },
          { type: "fill", prompt: "I’ll take either chemistry ___ physics next quarter.", promptAr: "سأدرس إمّا الكيمياء ___ الفيزياء في الفصل القادم.", promptArFull: "سأدرس إمّا الكيمياء أو الفيزياء في الفصل القادم.", options: ["or", "nor", "and"], answer: 0, explainAr: "either تأتي مع or (إمّا … أو)." },
          { type: "fill", prompt: "That book is ___ interesting nor accurate.", promptAr: "ذلك الكتاب ___ ممتع ولا دقيق.", promptArFull: "ذلك الكتاب ليس ممتعاً ولا دقيقاً.", options: ["either", "neither", "both", "not only"], answer: 1, explainAr: "nor تأتي مع neither (لا … ولا)." },
          { type: "fill", prompt: "Neither Richard nor John ___ her secret.", promptAr: "لا ريتشارد ولا جون ___ سرّها.", promptArFull: "لا ريتشارد ولا جون حفظ سرّها.", options: ["didn’t keep", "kept", "keeps not"], answer: 1, explainAr: "neither...nor منفية، فيأتي الفعل مثبتاً بالماضي: kept." },
          // Practice in the unit's world
          { type: "fill", prompt: "Both rights and duties ___ part of citizenship.", promptAr: "كلٌّ من الحقوق والواجبات ___ جزءاً من المواطنة.", promptArFull: "كلٌّ من الحقوق والواجبات تشكّل جزءاً من المواطنة.", options: ["is", "are", "was"], answer: 1, explainAr: "both...and تأخذ دائماً فعلاً جمعاً: are." },
          { type: "fill", prompt: "Not only the government but also the citizens ___ responsibilities.", promptAr: "ليست الحكومة فقط بل المواطنون أيضاً ___ مسؤوليات.", promptArFull: "ليست الحكومة فقط بل المواطنون أيضاً لديهم مسؤوليات.", options: ["has", "have", "having"], answer: 1, explainAr: "الفاعل الأقرب the citizens (جمع)، فالفعل have." },
          { type: "fill", prompt: "Neither the citizens nor the government ___ the right to break the law.", promptAr: "لا المواطنون ولا الحكومة ___ الحق في مخالفة القانون.", promptArFull: "لا المواطنون ولا الحكومة يملكون الحق في مخالفة القانون.", options: ["have", "has", "doesn’t have"], answer: 1, explainAr: "الفاعل الأقرب the government (مفرد) فنقول has، ولا ننفي لأن neither منفية." },
          { type: "fill", prompt: "Either the parents or the teacher ___ the children how to obey the law.", promptAr: "إمّا الوالدان أو المعلّم ___ الأطفال كيف يطيعون القانون.", promptArFull: "إمّا الوالدان أو المعلّم يعلّم الأطفال كيف يطيعون القانون.", options: ["teach", "teaches", "teaching"], answer: 1, explainAr: "مع either...or الفعل يتبع الفاعل الأقرب the teacher (مفرد): teaches." },
          { type: "fill", prompt: "Every Syrian citizen must ___ obey state laws and pay taxes.", promptAr: "يجب على كل مواطن سوري ___ أن يطيع قوانين الدولة ويدفع الضرائب.", promptArFull: "يجب على كل مواطن سوري أن يطيع قوانين الدولة ويدفع الضرائب معاً.", options: ["both", "either", "neither"], answer: 0, explainAr: "مع and نستخدم both، والتوازي صحيح: فعلان مجرّدان (obey / pay)." },
          { type: "fill", prompt: "Citizenship involves not only rights ___ responsibilities.", promptAr: "تتضمّن المواطنة ليس الحقوق فقط ___ المسؤوليات.", promptArFull: "تتضمّن المواطنة ليس الحقوق فقط بل المسؤوليات أيضاً.", options: ["but also", "nor", "or"], answer: 0, explainAr: "not only تأتي مع but also، وبعدهما اسمان متوازيان (rights / responsibilities)." },
          { type: "fill", prompt: "Responsibilities can be either voluntary ___ obligatory.", promptAr: "يمكن أن تكون المسؤوليات إمّا طوعية ___ إلزامية.", promptArFull: "يمكن أن تكون المسؤوليات إمّا طوعية أو إلزامية.", options: ["nor", "and", "or"], answer: 2, explainAr: "either تأتي مع or، وبعدهما صفتان متوازيتان." },
          { type: "mcq", prompt: "Which sentence has correct parallel structure?", promptAr: "أي جملة فيها توازٍ صحيح؟", options: ["That book is neither interesting nor accuracy.", "That book is neither interesting nor accurate.", "That book is neither interest nor accurate.", "That book neither is interesting nor accurate."], answer: 1, explainAr: "بعد neither صفة (interesting) وبعد nor صفة (accurate): الشكل النحوي نفسه." },
          { type: "mcq", prompt: "“Not only...but also” is used …", promptAr: "تُستخدم “Not only...but also” …", options: ["for emphasis or to indicate surprise", "to give a choice between two things", "to say that two things are not true", "only with plural verbs"], answer: 0, explainAr: "القاعدة في الكتاب: Not only...but also is used for emphasis or to indicate surprise." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["Neither my sister nor my parents is here.", "Both my mother and my sister is here.", "Neither my sister nor my parents are here.", "Not only my mother but also my sister are here."], answer: 2, explainAr: "مع neither...nor الفعل يتبع الأقرب my parents (جمع) → are. الجمل الأخرى فيها خطأ في المطابقة." },
          { type: "truefalse", prompt: "Two subjects connected by both ... and take a plural verb.", promptAr: "الفاعلان المربوطان بـ both ... and يأخذان فعلاً جمعاً.", answer: true, explainAr: "صحيح، كما في المثال: Both my mother and my sister are here." },
          { type: "truefalse", prompt: "With either...or, the verb always agrees with the first subject.", promptAr: "مع either...or يتبع الفعل دائماً الفاعل الأول.", answer: false, explainAr: "خطأ: الفعل يتبع الفاعل الأقرب إليه (الفاعل الثاني)." },
          { type: "truefalse", prompt: "The same grammatical forms should follow each part of the paired conjunctions.", promptAr: "يجب أن يأتي الشكل النحوي نفسه بعد كل جزء من أدوات الربط المزدوجة.", answer: true, explainAr: "صحيح، وهذا ما يسمّيه الكتاب parallel structure (التوازي)." },
        ],
      },
      pronunciation: {
        title: "Homographs",
        ruleAr: "الـ Homographs كلمات تُكتب بالطريقة نفسها لكن معانيها وأصولها مختلفة تماماً، وقد يختلف لفظها أيضاً. نعرف المعنى واللفظ من السياق: bow (قوس) تُلفظ /bəʊ/ أما bow (انحناءة) فتُلفظ /baʊ/. close (قريب) /kləʊs/ و close (يغلق) /kləʊz/. lead (يتقدّم/الصدارة) /liːd/ و lead (الرصاص) /led/. wind (الريح) /wɪnd/ و wind (يتعرّج) /waɪnd/. object (يعترض) فعل والنبر على المقطع الثاني /əbˈdʒekt/، و object (شيء) اسم والنبر على المقطع الأول /ˈɒbdʒɪkt/.",
        groups: [
          { label: "bow — /bəʊ/ weapon · /baʊ/ bending", words: ["After shooting the bull with his bow¹ (b: a weapon used for shooting arrows)", "the Spanish archer made a grand bow² to the audience (a: the polite gesture of bending at the waist)"] },
          { label: "close — /kləʊs/ nearby · /kləʊz/ shut", words: ["the store close¹ to her house (b: being nearby)", "careful to close² and lock the front door (a: to shut)"] },
          { label: "lead — /liːd/ in front · /led/ metal", words: ["The city took the lead¹ (b: starting in front)", "getting lead² out of the municipal waste (a: a type of metal)"] },
          { label: "wind — /wɪnd/ air · /waɪnd/ curve", words: ["The wind¹ blew softly (b: the moving of air)", "the river wind² its way through the valley (a: to move or have a curving course)"] },
          { label: "object — /əbˈdʒekt/ verb · /ˈɒbdʒɪkt/ noun", words: ["I object¹ to being given (b: to disagree)", "this object²! (a: an item)"] },
        ],
      },
      everyday: {
        title: "Accepting and Declining Offers",
        titleAr: "قبول العروض ورفضها",
        explainAr: "عندما يعرض عليك شخص شيئاً (طعاماً أو شراباً أو مساعدة) تقبل بلطف (Yes, please. / I’d love some. / Thank you. That would be great.) أو ترفض بلطف مع الشكر (No, thank you. / Not just at the moment, thank you.). ولتعرض أنت المساعدة أو شيئاً ما نستخدم: Would you like …? / Can I …? / Shall I …? / Do you want me to …?",
        expressions: [
          { en: "Would you like …?", ar: "هل تودّ …؟", note: "offering" },
          { en: "Can I …? / Shall I…?", ar: "هل أستطيع أن …؟ / هل أ…؟", note: "offering help" },
          { en: "Do you want me to…?", ar: "هل تريدني أن …؟", note: "offering help" },
          { en: "I’d be glad to help…", ar: "يسعدني أن أساعد …", note: "offering help" },
          { en: "Would you care for a ginger biscuit?", ar: "هل ترغب في بسكويتة بالزنجبيل؟", note: "offering (formal)" },
          { en: "I’d love some.", ar: "يسعدني أن آخذ بعضاً منه.", note: "accepting" },
          { en: "Yes, please. I’d love to.", ar: "نعم، من فضلك. يسعدني ذلك.", note: "accepting" },
          { en: "If you wouldn’t mind.", ar: "إن لم يكن لديك مانع.", note: "accepting" },
          { en: "Thank you. That would be great.", ar: "شكراً لك. سيكون ذلك رائعاً.", note: "accepting" },
          { en: "No thank you.", ar: "لا، شكراً.", note: "declining" },
          { en: "Not just at the moment, thank you.", ar: "ليس الآن، شكراً لك.", note: "declining politely" },
          { en: "It’s OK. I can do it myself.", ar: "لا بأس. أستطيع أن أفعل ذلك بنفسي.", note: "declining help" },
          { en: "Don’t worry. I’ll do it.", ar: "لا تقلق. سأفعل ذلك.", note: "declining help" },
          { en: "…if I may.", ar: "… إن سمحت لي.", note: "asking politely" },
          { en: "Please help yourself.", ar: "تفضّل، خُذ بنفسك.", note: "inviting someone to take" },
          { en: "That's kind of you.", ar: "هذا لطف منك.", note: "thanking" },
          { en: "Not at all.", ar: "لا شكر على واجب.", note: "answering thanks" },
        ],
        dialogue: [
          { speaker: "Waiter", en: "Would you like some more tea?", ar: "هل تودّ المزيد من الشاي؟" },
          { speaker: "John", en: "Oh, thank you very much. I’d love some.", ar: "أوه، شكراً جزيلاً. يسعدني أن آخذ بعضاً منه." },
          { speaker: "Waiter", en: "Would you like it with milk or lemon?", ar: "هل تريده بالحليب أم بالليمون؟" },
          { speaker: "John", en: "Milk, please. Not too much.", ar: "بالحليب، من فضلك. ليس كثيراً." },
          { speaker: "Waiter", en: "Sugar?", ar: "سكّر؟" },
          { speaker: "John", en: "No thank you. No sugar. I’m trying to lose weight.", ar: "لا، شكراً. بدون سكّر. أحاول أن أخسر بعض الوزن." },
          { speaker: "Waiter", en: "Would you care for a ginger biscuit?", ar: "هل ترغب في بسكويتة بالزنجبيل؟" },
          { speaker: "John", en: "Not just at the moment, thank you, but I’d like another piece of Angel cake, if I may.", ar: "ليس الآن، شكراً لك، لكنني أودّ قطعة أخرى من كعكة الملاك، إن سمحت لي." },
          { speaker: "Waiter", en: "Certainly. Please help yourself.", ar: "بالتأكيد. تفضّل، خُذ بنفسك." },
          { speaker: "John", en: "That's kind of you.", ar: "هذا لطف منك." },
          { speaker: "Waiter", en: "Not at all.", ar: "لا شكر على واجب." },
        ],
        exercises: [
          // Book exercise b — situations
          { type: "mcq", prompt: "The person opposite you in the train has been trying to read your newspaper. What do you say?", promptAr: "الشخص المقابل لك في القطار يحاول منذ فترة أن يقرأ جريدتك. ماذا تقول؟", options: ["No, thank you.", "Would you like to read my newspaper?", "It’s OK. I can do it myself.", "If you wouldn’t mind."], answer: 1, explainAr: "نعرض عليه الجريدة بعبارة العرض Would you like …? أما الخيارات الأخرى فهي للقبول أو الرفض." },
          { type: "mcq", prompt: "The person on your right is looking hungrily at the vegetable dish on your left. What do you say?", promptAr: "الشخص الجالس عن يمينك ينظر بجوع إلى طبق الخضار الذي عن يسارك. ماذا تقول؟", options: ["Shall I pass you the vegetable dish?", "Not just at the moment, thank you.", "Thank you. That would be great.", "Don’t worry. I’ll do it."], answer: 0, explainAr: "نعرض المساعدة بـ Shall I …? (هل أناولك الطبق؟)." },
          { type: "mcq", prompt: "Your bag is full of crisps, chocolate and fruit. Offer them to others.", promptAr: "حقيبتك مليئة بالبطاطا المقرمشة والشوكولا والفاكهة. اعرضها على الآخرين.", options: ["I’d love some.", "No thank you. I’m trying to lose weight.", "Would you like some crisps, chocolate or fruit?", "That's kind of you."], answer: 2, explainAr: "للعرض نستخدم Would you like …? والباقي عبارات قبول أو رفض أو شكر." },
          // More practice with the dialogue and the table
          { type: "mcq", prompt: "The waiter asks: “Would you like some more tea?” You want some. What do you say?", promptAr: "يسأل النادل: “هل تودّ المزيد من الشاي؟” وأنت تريد. ماذا تقول؟", options: ["Oh, thank you very much. I’d love some.", "Not at all.", "It’s OK. I can do it myself.", "No sugar."], answer: 0, explainAr: "I’d love some عبارة قبول لطيفة، كما قال جون." },
          { type: "mcq", prompt: "The waiter offers you sugar, but you are trying to lose weight. What do you say?", promptAr: "يعرض عليك النادل السكّر، لكنك تحاول أن تخسر بعض الوزن. ماذا تقول؟", options: ["Yes, please. I’d love to.", "No thank you. No sugar.", "If you wouldn’t mind.", "Please help yourself."], answer: 1, explainAr: "No thank you عبارة رفض مهذّبة." },
          { type: "mcq", prompt: "You don’t want a biscuit now, but maybe later. What do you say?", promptAr: "لا تريد بسكويتاً الآن، لكن ربما لاحقاً. ماذا تقول؟", options: ["Not just at the moment, thank you.", "Thank you. That would be great.", "I’d love some.", "Certainly."], answer: 0, explainAr: "Not just at the moment, thank you = ليس الآن، شكراً — رفض مهذّب مؤقت." },
          { type: "mcq", prompt: "Your friend’s hands are full, and you offer to carry something. He says “Yes”. What does he say?", promptAr: "يدا صديقك مشغولتان وأنت تعرض أن تحمل عنه شيئاً. فيقبل. ماذا يقول؟", options: ["It’s OK. I can do it myself.", "Don’t worry. I’ll do it.", "Thank you. That would be great.", "No, thank you."], answer: 2, explainAr: "Thank you. That would be great من عبارات قبول العرض في الجدول، والباقي عبارات رفض." },
          { type: "mcq", prompt: "Someone offers to help you, but you want to do it alone. What do you say?", promptAr: "يعرض عليك شخص المساعدة، لكنك تريد أن تقوم بالأمر وحدك. ماذا تقول؟", options: ["If you wouldn’t mind.", "It’s OK. I can do it myself.", "Yes, please. I’d love to.", "I’d be glad to help…"], answer: 1, explainAr: "It’s OK. I can do it myself من عبارات رفض العرض." },
          { type: "mcq", prompt: "Which expression is used for offering help?", promptAr: "أي عبارة تُستخدم لعرض المساعدة؟", options: ["If you wouldn’t mind.", "No, thank you.", "Do you want me to…?", "That's kind of you."], answer: 2, explainAr: "Do you want me to…? = هل تريدني أن …؟ من عبارات عرض المساعدة في الجدول." },
          { type: "fill", prompt: "Would you care ___ a ginger biscuit?", promptAr: "هل ترغب ___ بسكويتة بالزنجبيل؟", promptArFull: "هل ترغب في بسكويتة بالزنجبيل؟", options: ["about", "for", "of"], answer: 1, explainAr: "Would you care for …? = هل ترغب في …؟ طريقة مهذّبة للعرض." },
          { type: "fill", prompt: "I’d like another piece of Angel cake, if I ___ .", promptAr: "أودّ قطعة أخرى من كعكة الملاك، إن ___ لي.", promptArFull: "أودّ قطعة أخرى من كعكة الملاك، إن سمحت لي.", options: ["may", "must", "will"], answer: 0, explainAr: "if I may = إن سمحت لي، عبارة مهذّبة عند الطلب." },
          { type: "fill", prompt: "Certainly. Please help ___ .", promptAr: "بالتأكيد. تفضّل، خُذ ___ .", promptArFull: "بالتأكيد. تفضّل، خُذ بنفسك.", options: ["you", "yourself", "me"], answer: 1, explainAr: "help yourself = خُذ بنفسك (تفضّل)." },
          { type: "mcq", prompt: "John says: “That's kind of you.” What does the waiter answer?", promptAr: "يقول جون: “هذا لطف منك.” بماذا يجيب النادل؟", options: ["Not at all.", "No sugar.", "I’d love some.", "If I may."], answer: 0, explainAr: "Not at all = لا شكر على واجب، ردّ على الشكر." },
          { type: "truefalse", prompt: "“If you wouldn’t mind.” is used to decline an offer.", promptAr: "تُستخدم عبارة “If you wouldn’t mind.” لرفض العرض.", answer: false, explainAr: "خطأ: If you wouldn’t mind (إن لم يكن لديك مانع) عبارة لقبول العرض." },
        ],
      },
      listening: {
        taskAr: "استمع (R9.2) وأكمل الفراغات العشرة في المقطع عن سلوك المواطن الصالح، ثم استمع مرة أخرى واختر الإجابة الصحيحة (الإجابات في التسجيل الصوتي). بعد ذلك في التحدث: ناقش في مجموعات عبارة “To be a good citizen, one should be polite in everyday activities”، وأعط مثالين عن السلوك المهذّب، ثم وافق أو اعترض على كل عبارة مع ذكر السبب (I agree/disagree because …).",
        items: [
          "The main idea of the extract is — a rights of citizens / b how a good citizen should behave",
          "According to the extract, holding doors open for people to pass is something — a obligatory / b voluntary",
          "………… have the priority to pass streets. — a Car drivers / b Pedestrians",
          "Using car ………. is not acceptable unless necessary. — a horns / b lights",
          "When driving, a good citizen avoids — a playing music / b throwing trash",
          "Speaking: A citizen is defined only by the country he or she lives in.",
          "Speaking: A government should treat all of its citizens equally.",
          "Speaking: Being a citizen means you should be responsible to your country at all times.",
          "Speaking: Your identification with your country is more important than your identification with anything else.",
        ],
      },
      writing: {
        taskAr: "ناقش في مجموعات قول مارك توين: على كل مواطن أن يعدّ نفسه شرطياً غير رسمي يراقب القوانين وتنفيذها دون أجر. ثم اكتب مقالاً عمّا يلزم ليكون الإنسان مواطناً صالحاً في مجتمعك، واذكر فيه حقوق المواطن وواجباته. بعد ذلك تبادل المقال مع زميلك وراجعا الإملاء والقواعد وعلامات الترقيم.",
        linkers: ["Although", "In spite of the fact that", "While", "regardless of", "as well as", "both ... and", "not only ... but also", "either ... or", "neither ... nor"],
      },
      sentences: [
        "All citizens must pay taxes in one form or another.",
        "They have had a vital role in developing human civilisation.",
        "Although Syrian citizenship provides many rights, it also involves many responsibilities.",
        "Both my mother and my sister are here.",
        "Neither my mother nor my sister is here.",
        "The research project will take both time and money.",
        "I’ll take either chemistry or physics next quarter.",
        "That book is neither interesting nor accurate.",
        "Neither Tom nor Paul lies to their friends.",
        "Laila is angry with her little brother.",
        "My grandfather is careless with his money.",
        "The people were grateful for our help.",
        "The parents were proud of their child’s achievement.",
        "My brother is used to working at night.",
        "To be a good citizen, one should be polite in everyday activities.",
      ],
    },
    // @@UNIT10@@
  ],
}
