import type { Module } from '../../engine/types'

export const module4: Module = {
  number: 4,
  title: "Biology",
  titleAr: "علم الأحياء",
  color: "#ff9600",
  units: [
    // ===================== UNIT 7 =====================
    {
      id: "u7", number: 7, module: 4,
      title: "Microorganisms", titleAr: "الكائنات الحية الدقيقة", pages: "66–73", emoji: "🦠",
      planAr: "قراءة نص «الفيروسات والبكتيريا»، المتلازمات اللفظية فعل + اسم (Verb-noun collocations) مثل make an effort و lose your temper، قاعدة الجمل الشرطية من النوعين الثاني والثالث، لفظ الحروف الصامتة (Silent letters)، عبارات المكالمات الهاتفية (On the phone)، الاستماع لمعلومات محددة عن نظافة السيارات، مناقشة المخاطر الصحية في الأماكن العامة، وكتابة فقرة عن الصحة البيئية.",
      vocab: [
        { en: "causative", ar: "مسبِّب", pos: "adjective", def: "acting as the cause of something", defAr: "يكون هو سبب حدوث شيء ما", example: "The two most common causative agents of infectious diseases are the virus and the bacterium.", exampleAr: "أكثر مسبّبين شيوعاً للأمراض المعدية هما الفيروس والجرثومة." },
        { en: "infectious", ar: "مُعدٍ", pos: "adjective", def: "(of a disease) that can pass from one person to another", defAr: "(المرض) الذي ينتقل من شخص إلى آخر", example: "The two most common causative agents of infectious diseases are the virus and the bacterium.", exampleAr: "أكثر مسبّبين شيوعاً للأمراض المعدية هما الفيروس والجرثومة." },
        { en: "virus", ar: "فيروس", pos: "noun", def: "a very small thing that is not a cell and needs a host to multiply; it causes viral infections", defAr: "شيء صغير جداً ليس خلية ويحتاج إلى عائل ليتكاثر، ويسبّب العدوى الفيروسية", example: "Bacteria are living organisms, but viruses aren't.", exampleAr: "البكتيريا كائنات حية، لكن الفيروسات ليست كذلك." },
        { en: "bacterium", ar: "جرثومة (بكتيريا) — الجمع: bacteria", pos: "noun", def: "a single complex cell that can live on its own; the plural is bacteria", defAr: "خلية واحدة معقّدة تستطيع العيش وحدها، وجمعها bacteria", example: "A bacterium is a single complex cell.", exampleAr: "الجرثومة خلية واحدة معقّدة." },
        { en: "naked eye", ar: "العين المجرّدة", pos: "noun", def: "the eye alone, without a microscope", defAr: "العين وحدها من دون مجهر", example: "They both are tiny to be seen by the naked eye, they can cause similar symptoms and often spread in the same way.", exampleAr: "كلاهما أصغر من أن يُرى بالعين المجرّدة، ويمكن أن يسبّبا أعراضاً متشابهة، وغالباً ما ينتشران بالطريقة نفسها." },
        { en: "symptom", ar: "عَرَض (علامة مرض)", pos: "noun", def: "a sign that something exists, especially bad", defAr: "علامة تدل على وجود شيء ما، وخاصة شيء سيئ", example: "It can be very difficult to know what causes an infection because viral and bacterial infections can cause similar symptoms.", exampleAr: "قد يكون من الصعب جداً معرفة سبب العدوى لأن العدوى الفيروسية والبكتيرية قد تسبّبان أعراضاً متشابهة." },
        { en: "spread", ar: "ينتشر", pos: "verb", def: "to move and reach more people or places", defAr: "أن ينتقل ويصل إلى أشخاص أو أماكن أكثر", example: "They both are tiny to be seen by the naked eye, they can cause similar symptoms and often spread in the same way.", exampleAr: "كلاهما أصغر من أن يُرى بالعين المجرّدة، ويمكن أن يسبّبا أعراضاً متشابهة، وغالباً ما ينتشران بالطريقة نفسها." },
        { en: "organism", ar: "كائن حي", pos: "noun", def: "a living thing", defAr: "شيء حي", example: "Bacteria are living organisms, but viruses aren't.", exampleAr: "البكتيريا كائنات حية، لكن الفيروسات ليست كذلك." },
        { en: "cell", ar: "خلية", pos: "noun", def: "the smallest part of a living thing", defAr: "أصغر جزء في الكائن الحي", example: "A bacterium is a single complex cell.", exampleAr: "الجرثومة خلية واحدة معقّدة." },
        { en: "survive", ar: "يعيش / يبقى على قيد الحياة", pos: "verb", def: "to continue to live", defAr: "أن يستمر في الحياة", example: "It can survive on its own, inside or outside the body.", exampleAr: "تستطيع أن تعيش وحدها، داخل الجسم أو خارجه." },
        { en: "harmful", ar: "ضارّ", pos: "adjective", def: "causing damage or illness", defAr: "يسبّب الضرر أو المرض", example: "Most bacteria aren't harmful; we have many bacteria on and inside our body, especially in the gut to help digest food.", exampleAr: "معظم البكتيريا ليست ضارة؛ فلدينا بكتيريا كثيرة على أجسامنا وداخلها، وخاصة في الأمعاء لتساعد على هضم الطعام." },
        { en: "gut", ar: "الأمعاء", pos: "noun", def: "a tube in the body through which food passes when it leaves the stomach", defAr: "أنبوب في الجسم يمرّ فيه الطعام عندما يخرج من المعدة", example: "Most bacteria aren't harmful; we have many bacteria on and inside our body, especially in the gut to help digest food.", exampleAr: "معظم البكتيريا ليست ضارة؛ فلدينا بكتيريا كثيرة على أجسامنا وداخلها، وخاصة في الأمعاء لتساعد على هضم الطعام." },
        { en: "digest", ar: "يهضم", pos: "verb", def: "to change food you have just eaten into substances that your body can use", defAr: "أن تحوّل الطعام الذي أكلته للتو إلى مواد يستطيع جسمك أن يستعملها", example: "Most bacteria aren't harmful; we have many bacteria on and inside our body, especially in the gut to help digest food.", exampleAr: "معظم البكتيريا ليست ضارة؛ فلدينا بكتيريا كثيرة على أجسامنا وداخلها، وخاصة في الأمعاء لتساعد على هضم الطعام." },
        { en: "vital", ar: "حيوي / ضروري جداً", pos: "adjective", def: "very important and necessary", defAr: "مهم جداً وضروري", example: "They also serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants.", exampleAr: "وهي تؤدي أيضاً أدواراً حيوية كثيرة في الطبيعة بتحليل المواد العضوية وتحويل النيتروجين إلى مواد كيميائية تستفيد منها النباتات." },
        { en: "decompose", ar: "يتحلّل / يحلّل", pos: "verb", def: "to destroy gradually by natural chemical processes", defAr: "أن يُتلف الشيء تدريجياً بعمليات كيميائية طبيعية", example: "They also serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants.", exampleAr: "وهي تؤدي أيضاً أدواراً حيوية كثيرة في الطبيعة بتحليل المواد العضوية وتحويل النيتروجين إلى مواد كيميائية تستفيد منها النباتات." },
        { en: "host", ar: "عائل (مضيف)", pos: "noun", def: "a human, animal or cell that a virus lives in and uses to multiply", defAr: "إنسان أو حيوان أو خلية يعيش فيها الفيروس ويستعملها ليتكاثر", example: "Unlike bacteria, they need a host such as a human or an animal to multiply.", exampleAr: "على عكس البكتيريا، تحتاج الفيروسات إلى عائل مثل الإنسان أو الحيوان لكي تتكاثر." },
        { en: "multiply", ar: "يتكاثر", pos: "verb", def: "to increase greatly in number", defAr: "أن يزداد العدد كثيراً", example: "Viruses infect a host cell and then multiply by the thousands, leaving the host and infecting other cells of the body.", exampleAr: "تُصيب الفيروسات خلية عائلة ثم تتكاثر بالآلاف، فتغادر العائل وتُصيب خلايا أخرى في الجسم." },
        { en: "infect", ar: "يُعدي / يُصيب بالعدوى", pos: "verb", def: "to pass a disease to a person, animal or cell", defAr: "أن ينقل مرضاً إلى إنسان أو حيوان أو خلية", example: "Viruses only grow and reproduce inside the host cells they infect.", exampleAr: "لا تنمو الفيروسات ولا تتكاثر إلا داخل الخلايا العائلة التي تُصيبها." },
        { en: "reproduce", ar: "يتكاثر / يُنتج نسخاً من نفسه", pos: "verb", def: "to produce new copies or young ones of itself", defAr: "أن يُنتج نسخاً جديدة أو صغاراً من نفسه", example: "Viruses only grow and reproduce inside the host cells they infect.", exampleAr: "لا تنمو الفيروسات ولا تتكاثر إلا داخل الخلايا العائلة التي تُصيبها." },
        { en: "hijack", ar: "يستولي على / يختطف", pos: "verb", def: "attack to control something", defAr: "أن يهاجم شيئاً ليسيطر عليه", example: "Their life involves the hijacking of the biochemical activities of a living cell.", exampleAr: "تقوم حياتها على الاستيلاء على النشاطات الكيميائية الحيوية لخلية حية." },
        { en: "biochemical", ar: "كيميائي حيوي", pos: "adjective", def: "connected with the chemical processes in living things", defAr: "مرتبط بالعمليات الكيميائية في الكائنات الحية", example: "Their life involves the hijacking of the biochemical activities of a living cell.", exampleAr: "تقوم حياتها على الاستيلاء على النشاطات الكيميائية الحيوية لخلية حية." },
        { en: "infection", ar: "عدوى / التهاب", pos: "noun", def: "an illness caused by bacteria or a virus", defAr: "مرض تسبّبه البكتيريا أو الفيروسات", example: "Viruses and bacteria differ in how they cause infections.", exampleAr: "تختلف الفيروسات والبكتيريا في طريقة تسبيبها للعدوى." },
        { en: "viral", ar: "فيروسي", pos: "adjective", def: "caused by a virus", defAr: "يسبّبه فيروس", example: "As the names suggest, viruses cause viral infections, whereas bacteria cause bacterial infections.", exampleAr: "كما يدل الاسمان، تسبّب الفيروسات العدوى الفيروسية، بينما تسبّب البكتيريا العدوى البكتيرية." },
        { en: "bacterial", ar: "بكتيري / جرثومي", pos: "adjective", def: "caused by bacteria", defAr: "تسبّبه البكتيريا", example: "Bacterial infections include pneumonia, strep throat, ear infection and food poisoning.", exampleAr: "تشمل العدوى البكتيرية ذات الرئة والتهاب الحلق العقدي والتهاب الأذن والتسمم الغذائي." },
        { en: "influenza", ar: "الإنفلونزا", pos: "noun", def: "a viral infection that causes fever and pain; flu", defAr: "عدوى فيروسية تسبّب الحمّى والألم؛ الزكام الشديد", example: "Diseases caused by a viral infection include influenza, common cold, flu, AIDS and COVID - 19.", exampleAr: "تشمل الأمراض التي تسبّبها عدوى فيروسية الإنفلونزا والزكام والنزلة الوافدة والإيدز وكوفيد-19." },
        { en: "pneumonia", ar: "ذات الرئة (التهاب الرئة)", pos: "noun", def: "an acute inflammation of the lungs", defAr: "التهاب حاد في الرئتين", example: "Bacterial infections include pneumonia, strep throat, ear infection and food poisoning.", exampleAr: "تشمل العدوى البكتيرية ذات الرئة والتهاب الحلق العقدي والتهاب الأذن والتسمم الغذائي." },
        { en: "treatment", ar: "علاج", pos: "noun", def: "the medicine or care used to cure an illness", defAr: "الدواء أو الرعاية المستعملة لشفاء المرض", example: "In fact, it is very important to know whether bacteria or viruses cause an infection because the treatments differ.", exampleAr: "في الحقيقة، من المهم جداً أن نعرف هل البكتيريا أم الفيروسات هي سبب العدوى، لأن العلاجات تختلف." },
        { en: "sample", ar: "عيّنة", pos: "noun", def: "a small amount of something taken to be tested", defAr: "كمية صغيرة من شيء تؤخذ لفحصها", example: "Doctors need a sample of your urine, blood or swab from your nose or throat to see what infection you have.", exampleAr: "يحتاج الأطباء إلى عيّنة من بولك أو دمك أو مسحة من أنفك أو حلقك ليعرفوا نوع العدوى التي لديك." },
        { en: "swab", ar: "مسحة", pos: "noun", def: "a small amount of a substance that is taken from someone's body in order to test it", defAr: "كمية صغيرة من مادة تؤخذ من جسم الإنسان لفحصها", example: "Doctors need a sample of your urine, blood or swab from your nose or throat to see what infection you have.", exampleAr: "يحتاج الأطباء إلى عيّنة من بولك أو دمك أو مسحة من أنفك أو حلقك ليعرفوا نوع العدوى التي لديك." },
        { en: "germ", ar: "جرثومة (ميكروب)", pos: "noun", def: "a very small living thing that can cause disease", defAr: "كائن حي صغير جداً يمكن أن يسبّب المرض", example: "What everyday things can carry germs?", exampleAr: "ما الأشياء اليومية التي يمكن أن تحمل الجراثيم؟" },
        { en: "make an effort", ar: "يبذل جهداً", pos: "phrase", def: "to try hard to do something", defAr: "أن تحاول بجدّ أن تفعل شيئاً" },
        { en: "raise taxes", ar: "يرفع الضرائب", pos: "phrase", def: "to make taxes higher", defAr: "أن تجعل الضرائب أعلى", example: "One of the most important income for local councils is raising taxes.", exampleAr: "من أهم مصادر الدخل للمجالس المحلية رفع الضرائب." },
        { en: "give someone a lift", ar: "يوصل شخصاً بسيارته", pos: "phrase", def: "to take someone somewhere in your car", defAr: "أن تأخذ شخصاً إلى مكان ما بسيارتك", example: "My car is broken; could you give me a lift to the nearest bus stop?", exampleAr: "سيارتي معطّلة؛ هل يمكنك أن توصلني إلى أقرب موقف حافلات؟" },
        { en: "run a risk", ar: "يُعرّض نفسه للخطر / يخاطر", pos: "phrase", def: "to be in a situation where something bad may happen", defAr: "أن تكون في موقف قد يحدث فيه شيء سيئ" },
        { en: "meet expectations", ar: "يلبّي التوقعات", pos: "phrase", def: "to be as good as people hoped", defAr: "أن تكون جيداً كما كان الناس يأملون" },
        { en: "lose your temper", ar: "يفقد أعصابه", pos: "phrase", def: "to suddenly become very angry", defAr: "أن تغضب غضباً شديداً فجأة", example: "Being late for the final exam, Kamel was very angry and lost his temper.", exampleAr: "لأنه تأخر عن الامتحان النهائي، غضب كامل كثيراً وفقد أعصابه." },
        { en: "alienate", ar: "يُنفِّر / يُبعِد", pos: "verb", def: "to make people stop feeling friendly towards you", defAr: "أن تجعل الناس يتوقفون عن الشعور بالودّ تجاهك" },
        { en: "put through", ar: "يُوصل (المكالمة)", pos: "phrasal verb", def: "to connect a caller to the person they want on the phone", defAr: "أن توصل المتصل بالشخص الذي يريده على الهاتف", example: "Just a moment Miss Zaina, I'll put you through.", exampleAr: "لحظة يا آنسة زينة، سأحوّل مكالمتك." },
        { en: "engaged", ar: "مشغول (خط الهاتف)", pos: "adjective", def: "(of a phone line) busy, being used", defAr: "(خط الهاتف) مشغول، يستعمله شخص آخر", example: "I'm sorry, Dr. Amal's line is engaged.", exampleAr: "آسفة، خط الدكتورة أمل مشغول." },
        { en: "hold on", ar: "ينتظر (على الهاتف)", pos: "phrasal verb", def: "to wait on the phone", defAr: "أن تنتظر على الهاتف", example: "Will you hold on or can I take a message?", exampleAr: "هل ستنتظرين على الخط أم أستطيع أن آخذ رسالة؟" },
        { en: "ring back", ar: "يعاود الاتصال", pos: "phrasal verb", def: "to phone someone again, or to phone someone who phoned you", defAr: "أن تتصل بشخص مرة أخرى، أو تتصل بمن اتصل بك", example: "Could you ask her to ring me back, please?", exampleAr: "هل يمكنك أن تطلبي منها أن تعاود الاتصال بي من فضلك؟" },
        { en: "hygienic", ar: "صحّي / نظيف", pos: "adjective", def: "clean and free of germs", defAr: "نظيف وخالٍ من الجراثيم", example: "How can people keep their cars hygienic?", exampleAr: "كيف يستطيع الناس أن يحافظوا على نظافة سياراتهم؟" },
        { en: "steering wheel", ar: "مِقوَد السيارة", pos: "noun", def: "the wheel a driver turns to control the direction of a car", defAr: "العجلة التي يديرها السائق ليتحكم في اتجاه السيارة", example: "How often should drivers clean steering wheels?", exampleAr: "كم مرة يجب على السائقين أن ينظّفوا مقاود السيارات؟" },
        { en: "environmental health", ar: "الصحة البيئية", pos: "noun", def: "how the air, water, soil and food around us affect our health", defAr: "كيف يؤثّر الهواء والماء والتربة والطعام من حولنا في صحتنا", example: "What do you know about environmental health?", exampleAr: "ماذا تعرف عن الصحة البيئية؟" },
        { en: "silent letter", ar: "حرف صامت", pos: "noun", def: "a letter that is written but not pronounced", defAr: "حرف يُكتب ولا يُلفظ", example: "A silent or mute letter in a word is a letter that is written but not pronounced.", exampleAr: "الحرف الصامت أو الأبكم في الكلمة هو حرف يُكتب ولكنه لا يُلفظ." },
      ],
      reading: {
        title: "Viruses and Bacteria",
        paragraphs: [
          "The two most common causative agents of infectious diseases are the virus and the bacterium. They both are tiny to be seen by the naked eye, they can cause similar symptoms and often spread in the same way.",
          "Bacteria are living organisms, but viruses aren't. A bacterium is a single complex cell. It can survive on its own, inside or outside the body. This allows bacteria to live in many places - soil, water, plants and the human body. Most bacteria aren't harmful; we have many bacteria on and inside our body, especially in the gut to help digest food. They also serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants. On the other hand, viruses are smaller and aren't cells. Unlike bacteria, they need a host such as a human or an animal to multiply. Viruses only grow and reproduce inside the host cells they infect. Their life involves the hijacking of the biochemical activities of a living cell.",
          "Viruses and bacteria differ in how they cause infections.",
          "As the names suggest, viruses cause viral infections, whereas bacteria cause bacterial infections. Viruses infect a host cell and then multiply by the thousands, leaving the host and infecting other cells of the body. Diseases caused by a viral infection include influenza, common cold, flu, AIDS and COVID - 19. Bacteria, on the other hand, have a more varied operation and will often infect when the right opportunity arises. Bacterial infections include pneumonia, strep throat, ear infection and food poisoning.",
          "In fact, it is very important to know whether bacteria or viruses cause an infection because the treatments differ. It can be very difficult to know what causes an infection because viral and bacterial infections can cause similar symptoms. Doctors need a sample of your urine, blood or swab from your nose or throat to see what infection you have.",
        ],
        paragraphsAr: [
          "أكثر مسبّبين شيوعاً للأمراض المعدية هما الفيروس والجرثومة (البكتيريا). وكلاهما أصغر من أن يُرى بالعين المجرّدة، ويمكن أن يسبّبا أعراضاً متشابهة، وغالباً ما ينتشران بالطريقة نفسها.",
          "البكتيريا كائنات حية، لكن الفيروسات ليست كذلك. فالجرثومة خلية واحدة معقّدة، تستطيع أن تعيش وحدها، داخل الجسم أو خارجه. وهذا يسمح للبكتيريا بأن تعيش في أماكن كثيرة: في التربة والماء والنباتات وجسم الإنسان. ومعظم البكتيريا ليست ضارة؛ فلدينا بكتيريا كثيرة على أجسامنا وداخلها، وخاصة في الأمعاء لتساعد على هضم الطعام. وهي تؤدي أيضاً أدواراً حيوية كثيرة في الطبيعة بتحليل المواد العضوية وتحويل النيتروجين إلى مواد كيميائية تستفيد منها النباتات. أما الفيروسات فهي أصغر وليست خلايا. وعلى عكس البكتيريا، تحتاج الفيروسات إلى عائل مثل الإنسان أو الحيوان لكي تتكاثر. ولا تنمو الفيروسات ولا تتكاثر إلا داخل الخلايا العائلة التي تُصيبها. وتقوم حياتها على الاستيلاء على النشاطات الكيميائية الحيوية لخلية حية.",
          "تختلف الفيروسات والبكتيريا في طريقة تسبيبها للعدوى.",
          "كما يدل الاسمان، تسبّب الفيروسات العدوى الفيروسية، بينما تسبّب البكتيريا العدوى البكتيرية. تُصيب الفيروسات خلية عائلة ثم تتكاثر بالآلاف، فتغادر العائل وتُصيب خلايا أخرى في الجسم. وتشمل الأمراض التي تسبّبها عدوى فيروسية الإنفلونزا والزكام والنزلة الوافدة والإيدز وكوفيد-19. أما البكتيريا فعملها أكثر تنوعاً، وغالباً ما تُسبّب العدوى عندما تسنح لها الفرصة المناسبة. وتشمل العدوى البكتيرية ذات الرئة والتهاب الحلق العقدي والتهاب الأذن والتسمم الغذائي.",
          "في الحقيقة، من المهم جداً أن نعرف هل البكتيريا أم الفيروسات هي سبب العدوى، لأن العلاجات تختلف. وقد يكون من الصعب جداً معرفة سبب العدوى لأن العدوى الفيروسية والبكتيرية قد تسبّبان أعراضاً متشابهة. ويحتاج الأطباء إلى عيّنة من بولك أو دمك أو مسحة من أنفك أو حلقك ليعرفوا نوع العدوى التي لديك.",
        ],
        questions: [
          { q: "Why can't viruses and bacteria be seen by the naked eye?", qAr: "لماذا لا يمكن رؤية الفيروسات والبكتيريا بالعين المجرّدة؟",
            options: ["Because they live only inside the body.", "Because they are tiny.", "Because they aren't living organisms.", "Because they spread in the same way."],
            answer: 1, explainAr: "النص يقول: They both are tiny to be seen by the naked eye — أي إنهما صغيران جداً." },
          { q: "Where can bacteria survive?", qAr: "أين تستطيع البكتيريا أن تعيش؟",
            options: ["Only inside the host cells they infect", "Only in the gut", "On their own, inside or outside the body: in soil, water, plants and the human body", "Only in water and soil"],
            answer: 2, explainAr: "النص يقول: It can survive on its own, inside or outside the body... soil, water, plants and the human body." },
          { q: "In what ways are bacteria useful to nature?", qAr: "بأي طرق تفيد البكتيريا الطبيعة؟",
            options: ["By decomposing organic matter and converting nitrogen to chemicals usable by plants", "By hijacking the activities of living cells", "By causing pneumonia and food poisoning", "By multiplying inside host cells"],
            answer: 0, explainAr: "النص يقول: They also serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants." },
          { q: "What do viruses require to multiply?", qAr: "ماذا تحتاج الفيروسات لكي تتكاثر؟",
            options: ["Soil and water", "Organic matter", "Nitrogen", "A host such as a human or an animal"],
            answer: 3, explainAr: "النص يقول: they need a host such as a human or an animal to multiply." },
          { q: "Why is it difficult to know what causes an infection?", qAr: "لماذا يصعب معرفة سبب العدوى؟",
            options: ["Because doctors can't take samples", "Because viral and bacterial infections can cause similar symptoms", "Because viruses are bigger than bacteria", "Because the treatments are the same"],
            answer: 1, explainAr: "النص يقول: because viral and bacterial infections can cause similar symptoms." },
          { q: "What do the words in bold \"It\" (It can survive on its own) and \"they\" (they need a host) refer to?", qAr: "إلامَ تعود الكلمتان «It» في (It can survive on its own) و«they» في (they need a host)؟",
            options: ["It = the body; they = bacteria", "It = a virus; they = bacteria", "It = a bacterium; they = viruses", "It = the naked eye; they = plants"],
            answer: 2, explainAr: "It تعود إلى a bacterium (الجملة قبلها: A bacterium is a single complex cell)، و they تعود إلى viruses (Unlike bacteria, they need a host)." },
          { q: "Complete: The gut has many bacteria to ___.", qAr: "أكمل: في الأمعاء بكتيريا كثيرة لكي ___.",
            options: ["cause food poisoning", "help digest food", "convert nitrogen", "infect other cells"],
            answer: 1, explainAr: "النص يقول: we have many bacteria... especially in the gut to help digest food." },
          { q: "Complete: Because the treatment of viruses and bacteria differs, it is important to ___.", qAr: "أكمل: لأن علاج الفيروسات والبكتيريا مختلف، من المهم أن ___.",
            options: ["know whether bacteria or viruses cause an infection", "see them with the naked eye", "keep them outside the body", "take the same medicine for both"],
            answer: 0, explainAr: "النص يقول: it is very important to know whether bacteria or viruses cause an infection because the treatments differ." },
        ],
        trueFalse: [
          { statement: "The life of viruses needs the hijacking of the biochemical activities of a living cell.", answer: true },
          { statement: "Pneumonia is caused by viruses.", answer: false },
          { statement: "Most bacteria aren't harmful.", answer: true },
          { statement: "Viruses are bigger than bacteria.", answer: false },
          { statement: "Doctors need a sample of your urine, blood or a swab to see what infection you have.", answer: true },
        ],
      },
      vocabFocus: {
        name: "Verb-noun Collocations", nameAr: "المتلازمات اللفظية: فعل + اسم",
        ruleEn: [
          "Some verbs and nouns always go together. We call them collocations.",
          "make an effort = try hard to do something.",
          "raise taxes = make taxes higher.",
          "give (someone) a lift = take someone somewhere in your car.",
          "run a risk = be in a situation where something bad may happen (run the risk of + verb-ing).",
          "meet (someone's) expectations = be as good as people hoped.",
          "lose (your) temper = suddenly become very angry.",
          "Use the correct form of the verb: lose / loses / lost, run / runs / ran, give / gave, meet / met, make / made, raise / raised / raising.",
        ],
        ruleAr: [
          "المتلازمة اللفظية (collocation) كلمتان تأتيان معاً دائماً، ولا نستطيع أن نضع فعلاً آخر مكان الفعل الصحيح.",
          "make an effort = يبذل جهداً (ولا نقول do an effort).",
          "raise taxes = يرفع الضرائب (ولا نقول rise taxes؛ فـ rise فعل لازم).",
          "give someone a lift = يوصل شخصاً بسيارته.",
          "run a risk / run the risk of + ing = يخاطر، يعرّض نفسه لخطر.",
          "meet someone's expectations = يلبّي توقعات شخص ما.",
          "lose your temper = يفقد أعصابه ويغضب.",
          "نصرّف الفعل حسب الزمن والفاعل: loses (مع he/she في المضارع)، lost (ماضٍ)، gave، met، made، ran.",
        ],
        examples: [
          "Our boss often gets angry and loses his temper when things go wrong.",
          "If she never posts anything on her personal website, she runs the risk of alienating her fans.",
          "Politicians often think the government should raise taxes in order to get more money to spend.",
          "The new clerk didn't meet his boss's expectations and was fired after only two months.",
          "His car broke down, so I gave him a lift to the nearest garage.",
          "Not everything happens on its own sometimes. You have to make an effort to get things done.",
        ],
        exercises: [
          // Book exercise — complete the sentences
          { type: "fill", prompt: "Our boss often gets angry and ___ when things go wrong.", promptAr: "مديرنا يغضب كثيراً و___ عندما تسوء الأمور.", promptArFull: "مديرنا يغضب كثيراً ويفقد أعصابه عندما تسوء الأمور.", options: ["lose his temper", "loses his temper", "raises his temper", "runs his temper"], answer: 1, explainAr: "نقول lose your temper = يفقد أعصابه، والفاعل Our boss مفرد في المضارع البسيط فنضيف s: loses." },
          { type: "fill", prompt: "If she never posts anything on her personal website, she ___ of alienating her fans.", promptAr: "إذا لم تنشر أي شيء على موقعها الشخصي أبداً، فإنها ___ بأن تُنفّر معجبيها.", promptArFull: "إذا لم تنشر أي شيء على موقعها الشخصي أبداً، فإنها تخاطر بأن تُنفّر معجبيها.", options: ["makes the risk", "meets the risk", "runs the risk", "run the risk"], answer: 2, explainAr: "نقول run the risk of + ing = يخاطر بـ، والفاعل she فنقول runs." },
          { type: "fill", prompt: "Politicians often think the government should ___ in order to get more money to spend.", promptAr: "يظن السياسيون غالباً أن على الحكومة أن ___ لكي تحصل على مال أكثر لتنفقه.", promptArFull: "يظن السياسيون غالباً أن على الحكومة أن ترفع الضرائب لكي تحصل على مال أكثر لتنفقه.", options: ["raise taxes", "rise taxes", "make taxes", "raises taxes"], answer: 0, explainAr: "نقول raise taxes = يرفع الضرائب، وبعد should نستخدم الفعل الأساسي raise. أما rise فلا يأخذ مفعولاً به." },
          { type: "fill", prompt: "The new clerk didn't ___ and was fired after only two months.", promptAr: "الموظف الجديد لم ___ فطُرد بعد شهرين فقط.", promptArFull: "الموظف الجديد لم يلبِّ توقعات مديره فطُرد بعد شهرين فقط.", options: ["met his boss's expectations", "give his boss's expectations", "meet his boss's expectations", "run his boss's expectations"], answer: 2, explainAr: "نقول meet someone's expectations = يلبّي توقعاته، وبعد didn't نستخدم الفعل الأساسي meet." },
          { type: "fill", prompt: "His car broke down, so I ___ to the nearest garage.", promptAr: "تعطّلت سيارته، لذلك ___ إلى أقرب مرأب.", promptArFull: "تعطّلت سيارته، لذلك أوصلته بسيارتي إلى أقرب مرأب.", options: ["gave him a lift", "give him a lift", "made him a lift", "raised him a lift"], answer: 0, explainAr: "نقول give someone a lift = يوصل شخصاً بسيارته، والقصة في الماضي (broke down) فنقول gave." },
          { type: "fill", prompt: "Not everything happens on its own sometimes. You have to ___ to get things done.", promptAr: "ليس كل شيء يحدث من تلقاء نفسه أحياناً. عليك أن ___ لتُنجز الأمور.", promptArFull: "ليس كل شيء يحدث من تلقاء نفسه أحياناً. عليك أن تبذل جهداً لتُنجز الأمور.", options: ["do an effort", "make an effort", "made an effort", "give an effort"], answer: 1, explainAr: "نقول make an effort = يبذل جهداً (وليس do)، وبعد have to نستخدم الفعل الأساسي make." },
          // Matching verbs with nouns
          { type: "mcq", prompt: "Which verb goes with \"a lift\"?", promptAr: "أي فعل يأتي مع «a lift»؟", options: ["make", "give", "raise", "lose"], answer: 1, explainAr: "المتلازمة الصحيحة: give someone a lift." },
          { type: "mcq", prompt: "Which verb goes with \"temper\"?", promptAr: "أي فعل يأتي مع «temper»؟", options: ["lose", "run", "meet", "make"], answer: 0, explainAr: "المتلازمة الصحيحة: lose your temper." },
          { type: "mcq", prompt: "Which verb goes with \"an effort\"?", promptAr: "أي فعل يأتي مع «an effort»؟", options: ["give", "raise", "make", "run"], answer: 2, explainAr: "المتلازمة الصحيحة: make an effort." },
          { type: "mcq", prompt: "Which verb goes with \"a risk\"?", promptAr: "أي فعل يأتي مع «a risk»؟", options: ["meet", "lose", "give", "run"], answer: 3, explainAr: "المتلازمة الصحيحة: run a risk." },
          { type: "mcq", prompt: "Which verb goes with \"taxes\"?", promptAr: "أي فعل يأتي مع «taxes»؟", options: ["raise", "make", "lose", "give"], answer: 0, explainAr: "المتلازمة الصحيحة: raise taxes." },
          { type: "mcq", prompt: "Which verb goes with \"expectations\"?", promptAr: "أي فعل يأتي مع «expectations»؟", options: ["run", "meet", "raise", "lose"], answer: 1, explainAr: "المتلازمة الصحيحة: meet someone's expectations." },
          // Meanings
          { type: "mcq", prompt: "\"lose your temper\" means:", promptAr: "عبارة «lose your temper» تعني:", options: ["to forget something", "to suddenly become very angry", "to feel tired", "to lose money"], answer: 1, explainAr: "lose your temper = يفقد أعصابه ويغضب فجأة." },
          { type: "mcq", prompt: "\"give someone a lift\" means:", promptAr: "عبارة «give someone a lift» تعني:", options: ["to take someone somewhere in your car", "to help someone carry a heavy bag", "to make someone happy", "to lift someone up"], answer: 0, explainAr: "give someone a lift = يوصل شخصاً بسيارته." },
          { type: "mcq", prompt: "\"meet someone's expectations\" means:", promptAr: "عبارة «meet someone's expectations» تعني:", options: ["to meet someone at the airport", "to disappoint someone", "to be as good as someone hoped", "to expect a lot from someone"], answer: 2, explainAr: "meet someone's expectations = يكون جيداً كما كان الشخص يأمل." },
          { type: "mcq", prompt: "\"run the risk of\" means:", promptAr: "عبارة «run the risk of» تعني:", options: ["to run very fast", "to be in danger that something bad may happen", "to stop something bad", "to win a race"], answer: 1, explainAr: "run the risk of + ing = يعرّض نفسه لخطر حدوث شيء سيئ." },
          // Practice in the unit's world
          { type: "fill", prompt: "Drivers who never clean their steering wheels ___ of carrying germs on their hands.", promptAr: "السائقون الذين لا ينظّفون مقاود سياراتهم أبداً ___ بحمل الجراثيم على أيديهم.", promptArFull: "السائقون الذين لا ينظّفون مقاود سياراتهم أبداً يخاطرون بحمل الجراثيم على أيديهم.", options: ["run the risk", "runs the risk", "make the risk", "lose the risk"], answer: 0, explainAr: "run the risk of + ing، والفاعل Drivers جمع فلا نضيف s: run." },
          { type: "fill", prompt: "The receptionist was very patient; she never ___ on the phone.", promptAr: "كانت موظفة الاستقبال صبورة جداً؛ لم ___ أبداً على الهاتف.", promptArFull: "كانت موظفة الاستقبال صبورة جداً؛ لم تفقد أعصابها أبداً على الهاتف.", options: ["lost her temper", "lose her temper", "raised her temper", "met her temper"], answer: 0, explainAr: "lose your temper، والجملة في الماضي (was) فنقول lost." },
          { type: "fill", prompt: "Zaina's car broke down, so her neighbour ___ to the National Health Agency.", promptAr: "تعطّلت سيارة زينة، لذلك ___ جارُها إلى الوكالة الوطنية للصحة.", promptArFull: "تعطّلت سيارة زينة، لذلك أوصلها جارُها بسيارته إلى الوكالة الوطنية للصحة.", options: ["made her a lift", "gave her a lift", "gives her a lift", "ran her a lift"], answer: 1, explainAr: "give someone a lift، والقصة في الماضي فنقول gave." },
          { type: "fill", prompt: "Doctors must ___ to find out whether bacteria or viruses cause an infection.", promptAr: "يجب على الأطباء أن ___ ليكتشفوا هل البكتيريا أم الفيروسات هي سبب العدوى.", promptArFull: "يجب على الأطباء أن يبذلوا جهداً ليكتشفوا هل البكتيريا أم الفيروسات هي سبب العدوى.", options: ["do an effort", "makes an effort", "make an effort", "run an effort"], answer: 2, explainAr: "make an effort، وبعد must نستخدم الفعل الأساسي make." },
        ],
      },
      grammar: {
        name: "Conditional Sentences Type II, III", nameAr: "الجمل الشرطية من النوعين الثاني والثالث",
        ruleEn: [
          "Conditional sentences type II (if + simple past, main clause with would + infinitive) refer to imaginary situations in the present: e.g. If I had enough money, I would buy a Ferrari.",
          "Conditional sentences type III (if + past perfect, main clause with would + have + past participle) refer to imaginary situations in the past: e.g. If I had had enough money, I would have bought a Ferrari.",
          "The if-clause can come first (with a comma) or second (without a comma): I would ring the police if I saw a burglar breaking into my house.",
          "In type II we can use were with I / he / she / it: If I weren't in debt, I would quit my job.",
          "Never put would in the if-clause: If you had come in time, you wouldn't have missed the lesson. (NOT If you would have come)",
        ],
        ruleAr: [
          "النوع الثاني: If + ماضٍ بسيط ، would + المصدر (الفعل الأساسي). نستخدمه لموقف خيالي غير حقيقي في الحاضر: If I had enough money, I would buy a Ferrari. (المعنى: ليس معي مال كافٍ الآن).",
          "النوع الثالث: If + ماضٍ تام (had + التصريف الثالث) ، would + have + التصريف الثالث. نستخدمه لموقف خيالي في الماضي لم يحدث: If I had had enough money, I would have bought a Ferrari. (المعنى: لم يكن معي مال فلم أشترِها).",
          "يمكن أن تأتي جملة if أولاً فنضع بعدها فاصلة، أو تأتي ثانياً بلا فاصلة.",
          "في النوع الثاني نستطيع استعمال were مع جميع الضمائر: If I weren't in debt...",
          "لا نضع would أبداً في جملة if، بل في الجملة الرئيسية فقط.",
          "لنفهم المعنى نعكس الجملة: If you had come in time, you wouldn't have missed the lesson = لم تأتِ في الوقت المحدد، ففاتك الدرس.",
        ],
        examples: [
          "If I had enough money, I would buy a Ferrari.",
          "If I had had enough money, I would have bought a Ferrari.",
          "If you practiced more, your English would improve.",
          "I would ring the police if I saw a burglar breaking into my house.",
          "If the referee had seen the foul, he would have awarded a penalty kick to our team.",
          "If I had had your address, I would have written you a postcard.",
          "She wouldn't have arrived on time if she had taken the bus.",
        ],
        exercises: [
          // Book a — match (A) with (B)
          { type: "fill", prompt: "If you practiced more, ___", promptAr: "لو تدرّبت أكثر، ___", promptArFull: "لو تدرّبت أكثر، لتحسّنت لغتك الإنكليزية.", options: ["your English would improve.", "he would have awarded a penalty kick to our team.", "if I won the lottery.", "I would have written you a postcard."], answer: 0, explainAr: "If + ماضٍ بسيط (practiced) ← النوع الثاني، فالجواب would + المصدر: would improve." },
          { type: "fill", prompt: "I would ring the police ___", promptAr: "كنت سأتصل بالشرطة ___", promptArFull: "كنت سأتصل بالشرطة لو رأيت لصاً يقتحم بيتي.", options: ["if she had taken the bus.", "if I saw a burglar breaking into my house.", "your English would improve.", "I would have written you a postcard."], answer: 1, explainAr: "would ring (النوع الثاني) تحتاج if + ماضٍ بسيط: if I saw." },
          { type: "fill", prompt: "If the referee had seen the foul, ___", promptAr: "لو رأى الحكم الخطأ، ___", promptArFull: "لو رأى الحكم الخطأ، لمنح فريقنا ركلة جزاء.", options: ["your English would improve.", "if I won the lottery.", "he would have awarded a penalty kick to our team.", "if she had taken the bus."], answer: 2, explainAr: "If + ماضٍ تام (had seen) ← النوع الثالث، فالجواب would have + التصريف الثالث: would have awarded." },
          { type: "fill", prompt: "I would build a huge house by the beach ___", promptAr: "كنت سأبني بيتاً ضخماً على الشاطئ ___", promptArFull: "كنت سأبني بيتاً ضخماً على الشاطئ لو ربحت اليانصيب.", options: ["if I won the lottery.", "if she had taken the bus.", "he would have awarded a penalty kick to our team.", "if I had won the lottery yesterday."], answer: 0, explainAr: "would build (النوع الثاني) تحتاج if + ماضٍ بسيط: if I won." },
          { type: "fill", prompt: "If I had had your address, ___", promptAr: "لو كان عندي عنوانك، ___", promptArFull: "لو كان عندي عنوانك، لكتبتُ لك بطاقة بريدية.", options: ["I would write you a postcard.", "I would have written you a postcard.", "your English would improve.", "if I saw a burglar breaking into my house."], answer: 1, explainAr: "If + ماضٍ تام (had had) ← النوع الثالث: I would have written you a postcard." },
          { type: "fill", prompt: "She wouldn't have arrived on time ___", promptAr: "ما كانت لتصل في الوقت المحدد ___", promptArFull: "ما كانت لتصل في الوقت المحدد لو ركبت الحافلة.", options: ["if I won the lottery.", "if she took the bus.", "if she had taken the bus.", "your English would improve."], answer: 2, explainAr: "wouldn't have arrived (النوع الثالث) تحتاج if + ماضٍ تام: if she had taken the bus." },
          // Book b — choose a, b or c
          { type: "fill", prompt: "I ___ very unhappy if my friends didn't come to the party.", promptAr: "___ حزيناً جداً لو لم يأتِ أصدقائي إلى الحفلة.", promptArFull: "كنت سأكون حزيناً جداً لو لم يأتِ أصدقائي إلى الحفلة.", options: ["would have been", "will be", "would be"], answer: 2, explainAr: "if + ماضٍ بسيط (didn't come) ← النوع الثاني، فالجواب would + المصدر: would be." },
          { type: "fill", prompt: "Your brother wouldn't have found such a nice job if he ___ a university diploma.", promptAr: "ما كان أخوك ليجد عملاً جميلاً كهذا لو ___ شهادة جامعية.", promptArFull: "ما كان أخوك ليجد عملاً جميلاً كهذا لو لم تكن لديه شهادة جامعية.", options: ["hadn't had", "didn't have", "doesn't have"], answer: 0, explainAr: "wouldn't have found (النوع الثالث) ← if + ماضٍ تام: hadn't had." },
          { type: "fill", prompt: "If you had come in time, you ___ the lesson.", promptAr: "لو أتيت في الوقت المحدد، ___ الدرس.", promptArFull: "لو أتيت في الوقت المحدد، لما فاتك الدرس.", options: ["wouldn't miss", "wouldn't have missed", "won't miss"], answer: 1, explainAr: "If + ماضٍ تام (had come) ← النوع الثالث: wouldn't have missed." },
          { type: "fill", prompt: "People wouldn't have crossed the Bosphorus if they ___ these bridges.", promptAr: "ما كان الناس ليعبروا البوسفور لو ___ هذه الجسور.", promptArFull: "ما كان الناس ليعبروا البوسفور لو لم يبنوا هذه الجسور.", options: ["haven't built", "didn't build", "hadn't built"], answer: 2, explainAr: "wouldn't have crossed (النوع الثالث) ← if + ماضٍ تام: hadn't built." },
          { type: "fill", prompt: "You would have some money in your pocket if you ___ it so generously.", promptAr: "لكان معك بعض المال في جيبك لو ___ بهذا الكرم.", promptArFull: "لكان معك بعض المال في جيبك لو لم تنفقه بهذا الكرم.", options: ["wouldn't spend", "hadn't spent", "didn't spend"], answer: 2, explainAr: "would have (بدون have بعدها + تصريف ثالث) ← النوع الثاني عن الحاضر، فنستخدم if + ماضٍ بسيط: didn't spend. ولا نضع would في جملة if." },
          { type: "fill", prompt: "If I ___ in debt, I would quit my job.", promptAr: "لو ___ مَديناً، لتركت عملي.", promptArFull: "لو لم أكن مَديناً، لتركت عملي.", options: ["am not", "weren't", "hadn't been"], answer: 1, explainAr: "would quit (النوع الثاني) ← if + ماضٍ بسيط، ومع I نستخدم weren't." },
          // Own practice — type II
          { type: "fill", prompt: "If viruses ___ a host, they would multiply on their own.", promptAr: "لو ___ الفيروسات إلى عائل، لتكاثرت وحدها.", promptArFull: "لو لم تحتج الفيروسات إلى عائل، لتكاثرت وحدها.", options: ["don't need", "didn't need", "hadn't needed", "wouldn't need"], answer: 1, explainAr: "would multiply (النوع الثاني، موقف خيالي في الحاضر) ← if + ماضٍ بسيط: didn't need." },
          { type: "fill", prompt: "If people cleaned their steering wheels more often, their cars ___ more hygienic.", promptAr: "لو نظّف الناس مقاود سياراتهم أكثر، ___ سياراتهم أنظف.", promptArFull: "لو نظّف الناس مقاود سياراتهم أكثر، لكانت سياراتهم أنظف.", options: ["will be", "would be", "would have been", "are"], answer: 1, explainAr: "If + ماضٍ بسيط (cleaned) ← النوع الثاني: would + المصدر be." },
          { type: "fill", prompt: "If I ___ a doctor, I would take a swab from your throat.", promptAr: "لو ___ طبيباً، لأخذت مسحة من حلقك.", promptArFull: "لو كنت طبيباً، لأخذت مسحة من حلقك.", options: ["am", "were", "had been", "would be"], answer: 1, explainAr: "would take (النوع الثاني) ← if + ماضٍ بسيط، ومع I نستخدم were." },
          { type: "fill", prompt: "If Dr. Amal's line weren't engaged, the receptionist ___ Zaina through.", promptAr: "لو لم يكن خط الدكتورة أمل مشغولاً، ___ موظفة الاستقبال مكالمة زينة.", promptArFull: "لو لم يكن خط الدكتورة أمل مشغولاً، لحوّلت موظفة الاستقبال مكالمة زينة.", options: ["will put", "would have put", "would put", "puts"], answer: 2, explainAr: "if + ماضٍ بسيط (weren't) ← النوع الثاني: would put." },
          { type: "fill", prompt: "If she made an effort, she ___ her boss's expectations.", promptAr: "لو بذلت جهداً، ___ توقعات مديرها.", promptArFull: "لو بذلت جهداً، للبّت توقعات مديرها.", options: ["would meet", "will meet", "would have met", "met"], answer: 0, explainAr: "If + ماضٍ بسيط (made) ← النوع الثاني: would meet." },
          { type: "fill", prompt: "I would give you a lift to the hospital if I ___ a car.", promptAr: "كنت سأوصلك إلى المستشفى لو ___ سيارة.", promptArFull: "كنت سأوصلك إلى المستشفى لو كانت عندي سيارة.", options: ["have", "had had", "would have", "had"], answer: 3, explainAr: "would give (النوع الثاني) ← if + ماضٍ بسيط: had." },
          // Own practice — type III
          { type: "fill", prompt: "If the doctor had taken a sample of your blood, she ___ what infection you had.", promptAr: "لو أخذت الطبيبة عيّنة من دمك، ___ نوع العدوى التي لديك.", promptArFull: "لو أخذت الطبيبة عيّنة من دمك، لعرفت نوع العدوى التي لديك.", options: ["would know", "would have known", "will know", "had known"], answer: 1, explainAr: "If + ماضٍ تام (had taken) ← النوع الثالث: would have + التصريف الثالث known." },
          { type: "fill", prompt: "Dr. Amal would have rung Zaina back if the receptionist ___ a message.", promptAr: "كانت الدكتورة أمل ستعاود الاتصال بزينة لو ___ موظفة الاستقبال رسالة.", promptArFull: "كانت الدكتورة أمل ستعاود الاتصال بزينة لو أخذت موظفة الاستقبال رسالة.", options: ["took", "would take", "had taken", "has taken"], answer: 2, explainAr: "would have rung (النوع الثالث) ← if + ماضٍ تام: had taken." },
          { type: "fill", prompt: "If the new clerk had made an effort, he ___ fired.", promptAr: "لو بذل الموظف الجديد جهداً، ___ من العمل.", promptArFull: "لو بذل الموظف الجديد جهداً، لما طُرد من العمل.", options: ["wouldn't be", "won't be", "wouldn't have been", "hadn't been"], answer: 2, explainAr: "If + ماضٍ تام (had made) ← النوع الثالث: wouldn't have been (مبني للمجهول)." },
          { type: "fill", prompt: "If our boss ___ his temper, the meeting would have ended well.", promptAr: "لو ___ مديرنا أعصابه، لانتهى الاجتماع على خير.", promptArFull: "لو لم يفقد مديرنا أعصابه، لانتهى الاجتماع على خير.", options: ["didn't lose", "hadn't lost", "wouldn't lose", "doesn't lose"], answer: 1, explainAr: "would have ended (النوع الثالث) ← if + ماضٍ تام: hadn't lost." },
          // MCQ — meaning and rewriting
          { type: "mcq", prompt: "Which sentence refers to an imaginary situation in the present?", promptAr: "أي جملة تتحدث عن موقف خيالي في الحاضر؟", options: ["If I had had enough money, I would have bought a Ferrari.", "If I had enough money, I would buy a Ferrari.", "If I have enough money, I will buy a Ferrari.", "I had enough money, so I bought a Ferrari."], answer: 1, explainAr: "النوع الثاني (If + ماضٍ بسيط، would + مصدر) لموقف خيالي في الحاضر." },
          { type: "mcq", prompt: "Which sentence refers to an imaginary situation in the past?", promptAr: "أي جملة تتحدث عن موقف خيالي في الماضي؟", options: ["If you practiced more, your English would improve.", "I would ring the police if I saw a burglar.", "If the referee had seen the foul, he would have awarded a penalty kick to our team.", "If I won the lottery, I would build a huge house."], answer: 2, explainAr: "النوع الثالث (If + ماضٍ تام، would have + تصريف ثالث) لموقف خيالي في الماضي." },
          { type: "mcq", prompt: "\"I don't have enough money, so I can't buy a Ferrari.\" Which sentence has the same meaning?", promptAr: "«ليس معي مال كافٍ، لذلك لا أستطيع شراء سيارة فيراري.» أي جملة لها المعنى نفسه؟", options: ["If I had enough money, I would buy a Ferrari.", "If I have enough money, I will buy a Ferrari.", "If I had had enough money, I would have bought a Ferrari.", "If I would have enough money, I would buy a Ferrari."], answer: 0, explainAr: "الموقف في الحاضر، فنستخدم النوع الثاني وننفي المعنى: don't have ← had." },
          { type: "mcq", prompt: "\"You didn't come in time, so you missed the lesson.\" Which sentence has the same meaning?", promptAr: "«لم تأتِ في الوقت المحدد، ففاتك الدرس.» أي جملة لها المعنى نفسه؟", options: ["If you came in time, you wouldn't miss the lesson.", "If you had come in time, you wouldn't have missed the lesson.", "If you had come in time, you would have missed the lesson.", "If you come in time, you won't miss the lesson."], answer: 1, explainAr: "الموقف في الماضي، فنستخدم النوع الثالث ونعكس النفي والإثبات: didn't come ← had come، missed ← wouldn't have missed." },
          { type: "mcq", prompt: "\"She didn't take the bus, so she arrived on time.\" Which sentence has the same meaning?", promptAr: "«لم تركب الحافلة، لذلك وصلت في الوقت المحدد.» أي جملة لها المعنى نفسه؟", options: ["She would have arrived on time if she had taken the bus.", "She wouldn't arrive on time if she took the bus.", "She wouldn't have arrived on time if she had taken the bus.", "She won't arrive on time if she takes the bus."], answer: 2, explainAr: "النوع الثالث مع عكس المعنى: didn't take ← had taken، arrived ← wouldn't have arrived." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["If I would have your address, I would write to you.", "If I had your address, I would write to you.", "If I had your address, I will write to you.", "If I have your address, I would write to you."], answer: 1, explainAr: "النوع الثاني: If + ماضٍ بسيط (had)، would + مصدر (would write). ولا نضع would في جملة if." },
          // True / false
          { type: "truefalse", prompt: "In conditional sentences type III, the if-clause uses the past perfect.", promptAr: "في الجمل الشرطية من النوع الثالث، تستخدم جملة if الماضي التام.", answer: true, explainAr: "صحيح: If + had + التصريف الثالث، مثل If I had had enough money..." },
          { type: "truefalse", prompt: "Conditional sentences type II refer to imaginary situations in the past.", promptAr: "الجمل الشرطية من النوع الثاني تتحدث عن مواقف خيالية في الماضي.", answer: false, explainAr: "خطأ: النوع الثاني للحاضر، والنوع الثالث هو الذي يتحدث عن الماضي." },
          { type: "truefalse", prompt: "\"If you had come in time, you wouldn't have missed the lesson.\" This means that you came in time.", promptAr: "«لو أتيت في الوقت المحدد لما فاتك الدرس.» هذا يعني أنك أتيت في الوقت المحدد.", answer: false, explainAr: "خطأ: الجملة الشرطية من النوع الثالث تعني عكس ما حدث: لم تأتِ في الوقت المحدد ففاتك الدرس." },
          // Build
          { type: "build", prompt: "لو كان معي مال كافٍ، لاشتريت سيارة فيراري.", answer: "If I had enough money, I would buy a Ferrari." },
          { type: "build", prompt: "لو تدرّبت أكثر، لتحسّنت لغتك الإنكليزية.", answer: "If you practiced more, your English would improve." },
          { type: "build", prompt: "لو كان عندي عنوانك، لكتبتُ لك بطاقة بريدية.", answer: "If I had had your address, I would have written you a postcard." },
        ],
      },
      pronunciation: {
        title: "Silent Letters",
        ruleAr: "الحرف الصامت (silent / mute letter) هو حرف يُكتب في الكلمة ولكنه لا يُلفظ. أشهرها: k قبل n في أول الكلمة (knife, know)، و b بعد m (climb, comb)، و w قبل r (write, wrong)، و l في كلمات مثل calm و talk و should، و h في كلمات مثل honest و where و ghost. احفظ لفظ هذه الكلمات لأنها تأتي كثيراً في الامتحان.",
        groups: [
          { label: "Silent «k» — knife", words: ["knife", "knee", "knot", "knock", "knight", "know"] },
          { label: "Silent «h» — exhaust", words: ["exhaust", "ghost", "whale", "rhyme", "honest", "where", "choir"] },
          { label: "Silent «b» — climb", words: ["climb", "bomb", "comb", "thumb", "crumb", "doubt"] },
          { label: "Silent «l» — calm", words: ["calm", "halfpenny", "salmon", "yolk", "should", "talk"] },
          { label: "Silent «w» — sword", words: ["sword", "wrist", "wrong", "write", "answer", "whole"] },
          { label: "Silent «c» — muscle", words: ["muscle", "scissors"] },
          { label: "Silent «t» — castle", words: ["castle"] },
          { label: "Silent «n» — autumn", words: ["autumn"] },
          { label: "Silent «m» — mnemonic", words: ["mnemonic"] },
          { label: "Silent «d» — Wednesday", words: ["Wednesday"] },
          { label: "Silent «gh» — alight", words: ["alight"] },
          { label: "Silent «i» — business", words: ["business"] },
          { label: "Silent «a» — logically", words: ["logically"] },
          { label: "Silent «e» — make", words: ["make", "tissue"] },
          { label: "Silent «u» / «ue» — guitar, colleague", words: ["guitar", "colleague"] },
        ],
      },
      everyday: {
        title: "On the Phone Terms", titleAr: "عبارات المكالمات الهاتفية",
        explainAr: "نستخدم هذه العبارات في المكالمات الهاتفية الرسمية: موظف الاستقبال يردّ باسم المكان ويسأل عن اسم المتصل ويحوّل المكالمة، وإذا كان الخط مشغولاً يعرض على المتصل الانتظار أو ترك رسالة. والمتصل يطلب الشخص الذي يريده ويعرّف بنفسه بقوله This is... (وليس I am...)، ويطلب معاودة الاتصال به.",
        expressions: [
          { en: "I'd like to speak to ...", ar: "أودّ أن أتحدث إلى ...", note: "Caller" },
          { en: "May I ask who's calling, please?", ar: "هل لي أن أسأل من المتصل من فضلك؟", note: "Receptionist" },
          { en: "This is ...", ar: "معك ... (للتعريف بالنفس على الهاتف)", note: "Caller" },
          { en: "Just a moment.", ar: "لحظة من فضلك.", note: "Receptionist" },
          { en: "I'll put you through.", ar: "سأحوّل مكالمتك.", note: "Receptionist" },
          { en: "... line is engaged.", ar: "الخط مشغول.", note: "Receptionist" },
          { en: "Will you hold on or can I take a message?", ar: "هل ستنتظر على الخط أم أستطيع أن آخذ رسالة؟", note: "Receptionist" },
          { en: "Could you ask her to ring me back, please?", ar: "هل يمكنك أن تطلب منها أن تعاود الاتصال بي من فضلك؟", note: "Caller" },
          { en: "Thank you for calling.", ar: "شكراً لاتصالك.", note: "Receptionist" },
        ],
        dialogue: [
          { speaker: "Receptionist", en: "National Health Agency, good morning.", ar: "الوكالة الوطنية للصحة، صباح الخير." },
          { speaker: "Caller", en: "Good morning. I'd like to speak to Dr. Amal please.", ar: "صباح الخير. أودّ أن أتحدث إلى الدكتورة أمل من فضلك." },
          { speaker: "Receptionist", en: "May I ask who's calling, please?", ar: "هل لي أن أسأل من المتصل من فضلك؟" },
          { speaker: "Caller", en: "This is Zaina.", ar: "معك زينة." },
          { speaker: "Receptionist", en: "Just a moment Miss Zaina, I'll put you through .... I'm sorry, Dr. Amal's line is engaged. Will you hold on or can I take a message?", ar: "لحظة يا آنسة زينة، سأحوّل مكالمتك... آسفة، خط الدكتورة أمل مشغول. هل ستنتظرين على الخط أم أستطيع أن آخذ رسالة؟" },
          { speaker: "Caller", en: "Could you ask her to ring me back, please? My phone number is 0303-242892.", ar: "هل يمكنك أن تطلبي منها أن تعاود الاتصال بي من فضلك؟ رقم هاتفي 0303-242892." },
          { speaker: "Receptionist", en: "Certainly. Thank you for calling.", ar: "بالتأكيد. شكراً لاتصالك." },
        ],
        exercises: [
          { type: "mcq", prompt: "You work at the National Health Agency and you answer the phone. What do you say?", promptAr: "تعمل في الوكالة الوطنية للصحة وتردّ على الهاتف. ماذا تقول؟", options: ["This is Zaina.", "National Health Agency, good morning.", "Could you ask her to ring me back?", "I'd like to speak to Dr. Amal."], answer: 1, explainAr: "يردّ موظف الاستقبال باسم المكان والتحية: National Health Agency, good morning." },
          { type: "mcq", prompt: "You phone the agency and you want to talk to Dr. Amal. What do you say?", promptAr: "تتصل بالوكالة وتريد أن تتحدث إلى الدكتورة أمل. ماذا تقول؟", options: ["I'd like to speak to Dr. Amal please.", "I'll put you through.", "Thank you for calling.", "Will you hold on?"], answer: 0, explainAr: "نطلب الشخص بلطف: I'd like to speak to ... please." },
          { type: "mcq", prompt: "The receptionist wants to know the caller's name. What does she ask?", promptAr: "تريد موظفة الاستقبال أن تعرف اسم المتصل. ماذا تسأل؟", options: ["Who are you?", "Will you hold on?", "May I ask who's calling, please?", "What's your number?"], answer: 2, explainAr: "السؤال المهذب على الهاتف: May I ask who's calling, please?" },
          { type: "mcq", prompt: "How do you say your name on the phone?", promptAr: "كيف تذكر اسمك على الهاتف؟", options: ["I am Zaina.", "This is Zaina.", "Here Zaina is.", "My name Zaina."], answer: 1, explainAr: "على الهاتف نعرّف بأنفسنا بقولنا This is ... وليس I am ..." },
          { type: "mcq", prompt: "The receptionist is going to connect the caller to Dr. Amal. What does she say?", promptAr: "ستوصل موظفة الاستقبال المتصل بالدكتورة أمل. ماذا تقول؟", options: ["I'll put you through.", "I'll ring you back.", "Thank you for calling.", "Can I take a message?"], answer: 0, explainAr: "put someone through = يوصل المكالمة: I'll put you through." },
          { type: "mcq", prompt: "Dr. Amal is talking to someone else on the phone. What does the receptionist say?", promptAr: "الدكتورة أمل تتحدث مع شخص آخر على الهاتف. ماذا تقول موظفة الاستقبال؟", options: ["Dr. Amal's line is free.", "I'm sorry, Dr. Amal's line is engaged.", "Dr. Amal is calling.", "This is Dr. Amal."], answer: 1, explainAr: "عندما يكون الخط مشغولاً نقول: the line is engaged." },
          { type: "mcq", prompt: "The line is engaged. The receptionist gives the caller two choices. What does she say?", promptAr: "الخط مشغول. تعطي موظفة الاستقبال المتصل خيارين. ماذا تقول؟", options: ["Could you ask her to ring me back?", "May I ask who's calling?", "Will you hold on or can I take a message?", "I'd like to speak to her."], answer: 2, explainAr: "الخياران: أن ينتظر (hold on) أو أن يترك رسالة (take a message)." },
          { type: "mcq", prompt: "You can't wait. You want Dr. Amal to call you later. What do you say?", promptAr: "لا تستطيع الانتظار، وتريد أن تتصل بك الدكتورة أمل لاحقاً. ماذا تقول؟", options: ["Could you ask her to ring me back, please?", "Will you hold on?", "I'll put you through.", "Thank you for calling."], answer: 0, explainAr: "ring back = يعاود الاتصال: Could you ask her to ring me back, please?" },
          { type: "mcq", prompt: "How does the receptionist finish the call politely?", promptAr: "كيف تُنهي موظفة الاستقبال المكالمة بلطف؟", options: ["Just a moment.", "Certainly. Thank you for calling.", "May I ask who's calling?", "Good morning."], answer: 1, explainAr: "نختم المكالمة بالشكر: Thank you for calling." },
          { type: "fill", prompt: "Receptionist: Just a moment Miss Zaina, I'll put you ___.", promptAr: "موظفة الاستقبال: لحظة يا آنسة زينة، سأ___ مكالمتك.", promptArFull: "موظفة الاستقبال: لحظة يا آنسة زينة، سأحوّل مكالمتك.", options: ["on", "back", "through"], answer: 2, explainAr: "الفعل المركب put through = يوصل المكالمة." },
          { type: "fill", prompt: "Receptionist: Will you hold ___ or can I take a message?", promptAr: "موظفة الاستقبال: هل ستنتظرين ___ أم أستطيع أن آخذ رسالة؟", promptArFull: "موظفة الاستقبال: هل ستنتظرين على الخط أم أستطيع أن آخذ رسالة؟", options: ["on", "up", "back"], answer: 0, explainAr: "hold on = ينتظر على الهاتف." },
          { type: "fill", prompt: "Caller: Could you ask her to ring me ___, please?", promptAr: "المتصلة: هل يمكنك أن تطلبي منها أن ___ بي من فضلك؟", promptArFull: "المتصلة: هل يمكنك أن تطلبي منها أن تعاود الاتصال بي من فضلك؟", options: ["through", "back", "on"], answer: 1, explainAr: "ring back = يعاود الاتصال." },
          { type: "fill", prompt: "Lucy rings her new neighbours: \"Hello, ___ Lucy from the house next door.\"", promptAr: "تتصل لوسي بجيرانها الجدد: «مرحباً، ___ لوسي من البيت المجاور.»", promptArFull: "تتصل لوسي بجيرانها الجدد: «مرحباً، معكم لوسي من البيت المجاور.»", options: ["I'm calling", "this is", "here is"], answer: 1, explainAr: "على الهاتف نعرّف بأنفسنا بقولنا This is ..." },
          { type: "fill", prompt: "Lucy: If you need any help, please ___ me. My number is 844842.", promptAr: "لوسي: إذا احتجتم أي مساعدة، من فضلكم ___ بي. رقمي 844842.", promptArFull: "لوسي: إذا احتجتم أي مساعدة، من فضلكم اتصلوا بي. رقمي 844842.", options: ["hold on", "put through", "ring"], answer: 2, explainAr: "ring someone = يتصل به هاتفياً، كما في مهمة الكتاب: tell them to ring you if they need any help." },
          { type: "truefalse", prompt: "Zaina spoke to Dr. Amal on the phone.", promptAr: "تحدثت زينة مع الدكتورة أمل على الهاتف.", answer: false, explainAr: "خطأ: كان خط الدكتورة أمل مشغولاً، فطلبت زينة أن تعاود الاتصال بها." },
        ],
      },
      listening: {
        taskAr: "قبل الاستماع ناقش مع زملائك: هل وسائل النقل العامة أكثر أماناً وخلوّاً من الجراثيم من السيارات؟ كم مرة يجب على السائقين تنظيف المقاود؟ كيف نحافظ على نظافة السيارات؟ ثم استمع إلى مقتطف عن دراسة حول البكتيريا في السيارات واختر a أو b أو c لإكمال الجمل. وأخيراً: ما رأيك في السائقين الذين يأكلون ويشربون أثناء القيادة؟",
        items: [
          "People usually think that ___ is safer than public transport. (bicycle / airplane / their own car)",
          "The survey found out that cars are ___. (clean from bacteria / full of bacteria / hygienic places)",
          "The survey was carried out by ___ University. (Nottingham / Cambridge / Oxford)",
          "Microbiologists discovered that bacteria can be found on ___. (steering wheels / hand brakes and seats / both a and b)",
          "The study showed that car owners are ___ cleaning their cars. (not interested in / aware of / worried about)",
        ],
      },
      writing: {
        taskAr: "ناقش في مجموعات: ماذا تعرف عن الصحة البيئية؟ إلى أي حدّ يحافظ البشر على البيئة؟ كيف نقلّل المشكلات الصحية في الأماكن العامة؟ ثم اكتب فقرة لا تزيد على 100 كلمة عن الصحة البيئية، مستعيناً بالأفكار: سنّ قوانين للحدّ من التلوث، وقوانين تمنع التدخين في الأماكن العامة، والتوعية والتثقيف الصحي، والماء والهواء والتربة والطعام غير الملوّثة. (قبل ذلك في قسم المحادثة: ناقش المخاطر الصحية في وسائل النقل العامة ومطاعم الوجبات السريعة والمدارس والمستشفيات والحدائق، والإجراءات الصحية لكل منها.)",
      },
      sentences: [
        "Bacteria are living organisms, but viruses aren't.",
        "A bacterium is a single complex cell.",
        "It can survive on its own, inside or outside the body.",
        "Unlike bacteria, they need a host such as a human or an animal to multiply.",
        "Viruses only grow and reproduce inside the host cells they infect.",
        "Viruses and bacteria differ in how they cause infections.",
        "Bacterial infections include pneumonia, strep throat, ear infection and food poisoning.",
        "If I had enough money, I would buy a Ferrari.",
        "If I had had enough money, I would have bought a Ferrari.",
        "May I ask who's calling, please?",
        "Could you ask her to ring me back, please?",
        "Will you hold on or can I take a message?",
        "What everyday things can carry germs?",
        "How can people keep their cars hygienic?",
        "Why is it difficult to know what causes an infection?",
      ],
    },
    // @@UNIT8@@
  ],
}
