import type { Module } from '../../engine/types'

export const module1: Module = {
  number: 1,
  title: "Learning for Life",
  titleAr: "التعلّم من أجل الحياة",
  color: "#58cc02",
  units: [
    // ===================== UNIT 1 — Life Choices (pages 8–16) =====================
    {
      id: "u1", number: 1, module: 1,
      title: "Life Choices", titleAr: "خيارات الحياة", pages: "8–16", emoji: "🧭",
      quotes: [{ text: "Life is a matter of choices, and every choice you make makes you.", by: "John C. Maxwell" }],
      planAr: "قراءة نص «مهن المستقبل» (Future Careers) عن دور الآباء والعوامل المهمة في اختيار المهنة، مفردات عائلة الكلمة والأفعال المركّبة (Word Family and Phrasal Verbs)، مراجعة الأزمنة 1 (المضارع البسيط والمستمر، المضارع التام البسيط والمستمر، الماضي البسيط)، لفظ الكلمات المتشابهة في النطق (Homophones)، عبارات تقديم النصيحة (Giving Advice)، الاستماع إلى مقابلة مع صوفيا للحصول على معلومات محددة، الحديث عن المهن، وكتابة وصف لوظيفة الأحلام.",
      vocab: [
        { en: "aspire", ar: "يطمح", pos: "verb", def: "seek to attain a goal", defAr: "أن تسعى إلى تحقيق هدف" },
        { en: "aspiration", ar: "طموح", pos: "noun", def: "a strong hope or goal you want to achieve", defAr: "أمل قوي أو هدف تريد تحقيقه", example: "A job’s earnings should match the child’s aspirations and provide a satisfying comfortable life.", exampleAr: "ينبغي أن يتناسب دخل الوظيفة مع طموحات الطفل وأن يوفّر حياة مريحة مُرضية." },
        { en: "burden", ar: "يُثقِل / يُحمِّل عبئاً", pos: "verb", def: "load", defAr: "أن تُحمِّل شخصاً حِملاً ثقيلاً" },
        { en: "aptitude", ar: "استعداد / موهبة طبيعية", pos: "noun", def: "natural ability or skill", defAr: "قدرة أو مهارة طبيعية", example: "Hence, a designed aptitude test can reveal a lot of information regarding the child that can help in taking a well-informed career selection.", exampleAr: "لذلك يمكن لاختبار قدرات مُصمَّم جيداً أن يكشف الكثير من المعلومات عن الطفل، مما يساعد على اختيار المهنة عن معرفة ودراية." },
        { en: "sway", ar: "يؤثّر في / يستميل", pos: "verb", def: "to influence (swayed = influenced)", defAr: "أن تؤثّر في شخص (swayed = متأثّر)" },
        { en: "remuneration", ar: "أجر / مكافأة مالية", pos: "noun", def: "money paid for work or services", defAr: "مال يُدفع مقابل العمل أو الخدمات" },
        { en: "demotivation", ar: "الإحباط / فقدان الحافز", pos: "noun", def: "making someone less eager or willing to do their job", defAr: "جعل الشخص أقل حماساً أو رغبة في أداء عمله" },
        { en: "opt for", ar: "يختار", pos: "verb", def: "to choose something", defAr: "أن تختار شيئاً" },
        { en: "misguide", ar: "يُضلِّل / يوجّه توجيهاً خاطئاً", pos: "verb", def: "to lead someone in the wrong direction", defAr: "أن توجّه شخصاً في الاتجاه الخاطئ", example: "Many parents said they had misguided their children into choosing a career of their choice.", exampleAr: "قال كثير من الآباء إنهم وجّهوا أبناءهم توجيهاً خاطئاً فدفعوهم إلى اختيار مهنة من اختيار الآباء." },
        { en: "clarity", ar: "وضوح", pos: "noun", def: "the quality of being clear and easy to understand", defAr: "صفة الشيء الواضح السهل الفهم", example: "Not all people have the ability to explore their future and build it with more confidence and clarity.", exampleAr: "ليس كل الناس قادرين على استكشاف مستقبلهم وبنائه بمزيد من الثقة والوضوح." },
        { en: "highlight", ar: "يُبرز / يسلّط الضوء على", pos: "verb", def: "to show that something is important", defAr: "أن تُظهر أن شيئاً ما مهم", example: "Most studies have highlighted the role of parents as active agents in the career development of their children.", exampleAr: "سلّطت معظم الدراسات الضوء على دور الآباء بوصفهم عناصر فاعلة في التطوّر المهني لأبنائهم." },
        { en: "agent", ar: "عامل مؤثّر / عنصر فاعل", pos: "noun", def: "a person or thing that makes something happen", defAr: "شخص أو شيء يجعل أمراً ما يحدث", example: "Most studies have highlighted the role of parents as active agents in the career development of their children.", exampleAr: "سلّطت معظم الدراسات الضوء على دور الآباء بوصفهم عناصر فاعلة في التطوّر المهني لأبنائهم." },
        { en: "career", ar: "مهنة / مسيرة مهنية", pos: "noun", def: "the job or series of jobs you do during your working life", defAr: "العمل أو سلسلة الأعمال التي تقوم بها خلال حياتك المهنية", example: "Researchers told us that through self-reflection and guided activities, we would find our core values and a clearer path towards the right career.", exampleAr: "أخبرنا الباحثون أنه من خلال التأمّل الذاتي والأنشطة الموجَّهة سنجد قيمنا الأساسية وطريقاً أوضح نحو المهنة المناسبة." },
        { en: "factor", ar: "عامل", pos: "noun", def: "one of the things that affect a decision or result", defAr: "أحد الأشياء التي تؤثّر في قرار أو نتيجة", example: "There are a few factors that are of great importance in the career selection process.", exampleAr: "هناك بعض العوامل ذات الأهمية الكبيرة في عملية اختيار المهنة." },
        { en: "reveal", ar: "يكشف", pos: "verb", def: "to show something that was hidden", defAr: "أن تُظهر شيئاً كان مخفياً", example: "Hence, a designed aptitude test can reveal a lot of information regarding the child that can help in taking a well-informed career selection.", exampleAr: "لذلك يمكن لاختبار قدرات مُصمَّم جيداً أن يكشف الكثير من المعلومات عن الطفل، مما يساعد على اختيار المهنة عن معرفة ودراية." },
        { en: "well-informed", ar: "مبنيّ على معرفة / مُطَّلِع", pos: "adjective", def: "based on a lot of useful information", defAr: "قائم على كثير من المعلومات المفيدة", example: "Hence, a designed aptitude test can reveal a lot of information regarding the child that can help in taking a well-informed career selection.", exampleAr: "لذلك يمكن لاختبار قدرات مُصمَّم جيداً أن يكشف الكثير من المعلومات عن الطفل، مما يساعد على اختيار المهنة عن معرفة ودراية." },
        { en: "peer", ar: "نظير / زميل من العمر نفسه", pos: "noun", def: "a person of the same age or group as you", defAr: "شخص من عمرك نفسه أو من مجموعتك", example: "What is the influence of peers on children?", exampleAr: "ما تأثير الأقران في الأطفال؟" },
        { en: "earnings", ar: "دخل / أرباح", pos: "noun", def: "the money that you get from working", defAr: "المال الذي تحصل عليه من العمل", example: "A job’s earnings should match the child’s aspirations and provide a satisfying comfortable life.", exampleAr: "ينبغي أن يتناسب دخل الوظيفة مع طموحات الطفل وأن يوفّر حياة مريحة مُرضية." },
        { en: "professional", ar: "مهنيّ / صاحب اختصاص", pos: "noun", def: "a person who does a job that needs special training", defAr: "شخص يمارس عملاً يحتاج إلى تدريب خاص", example: "Modern societies need professionals in every field: utility workers, garbage collectors, farmers, nurses, doctors, engineers, teachers, professors and many others.", exampleAr: "تحتاج المجتمعات الحديثة إلى أصحاب مهن في كل مجال: عمّال المرافق العامة، وعمّال جمع القمامة، والمزارعين، والممرّضين، والأطباء، والمهندسين، والمعلّمين، والأساتذة وغيرهم كثير." },
        { en: "suitable", ar: "مناسب", pos: "adjective", def: "right for a particular person or purpose", defAr: "ملائم لشخص معيّن أو غرض معيّن", example: "Parents can work together to gather information about a career and then help the child in deciding whether it is suitable or not.", exampleAr: "يستطيع الآباء أن يعملوا معاً لجمع المعلومات عن مهنة ما، ثم يساعدوا الطفل في تقرير ما إذا كانت مناسبة أم لا." },
        { en: "certain", ar: "متأكّد", pos: "adjective", def: "completely sure", defAr: "واثق تماماً", example: "Most people have dreams of future jobs and there’s no limit to what this could be, but we can't be absolutely certain about our career choices.", exampleAr: "لدى معظم الناس أحلام بوظائف المستقبل ولا حدود لما يمكن أن تكون عليه، لكننا لا نستطيع أن نكون متأكّدين تماماً من خياراتنا المهنية." },
        { en: "self-reflection", ar: "التأمّل الذاتي", pos: "noun", def: "careful thinking about your own feelings and behaviour", defAr: "التفكير المتأنّي في مشاعرك وسلوكك", example: "Researchers told us that through self-reflection and guided activities, we would find our core values and a clearer path towards the right career.", exampleAr: "أخبرنا الباحثون أنه من خلال التأمّل الذاتي والأنشطة الموجَّهة سنجد قيمنا الأساسية وطريقاً أوضح نحو المهنة المناسبة." },
        { en: "core values", ar: "القيم الأساسية", pos: "phrase", def: "the most important beliefs that guide your life", defAr: "أهم المبادئ التي توجّه حياتك", example: "Researchers told us that through self-reflection and guided activities, we would find our core values and a clearer path towards the right career.", exampleAr: "أخبرنا الباحثون أنه من خلال التأمّل الذاتي والأنشطة الموجَّهة سنجد قيمنا الأساسية وطريقاً أوضح نحو المهنة المناسبة." },
        { en: "accomplish", ar: "يُنجز / يحقّق", pos: "verb", def: "to succeed in doing something", defAr: "أن تنجح في فعل شيء ما", example: "What do you hope to accomplish through your future job?", exampleAr: "ماذا تأمل أن تحقّق من خلال وظيفتك المستقبلية؟" },
        { en: "accomplishment", ar: "إنجاز", pos: "noun", def: "something good that you succeed in doing", defAr: "شيء جيد تنجح في فعله" },
        { en: "inspire", ar: "يُلهِم", pos: "verb", def: "to give someone the wish and the ideas to do something", defAr: "أن تمنح شخصاً الرغبة والأفكار لفعل شيء", example: "Who inspired you to choose it?", exampleAr: "مَن ألهمك أن تختارها؟" },
        { en: "attract", ar: "يجذب", pos: "verb", def: "to make someone interested in something", defAr: "أن تجعل شخصاً مهتماً بشيء ما", example: "What attracts you to this job?", exampleAr: "ما الذي يجذبك إلى هذه الوظيفة؟" },
        { en: "graduate", ar: "خرّيج", pos: "noun", def: "a person who has finished university", defAr: "شخص أنهى دراسته الجامعية", example: "What kinds of jobs are most popular for graduates in your country at the moment?", exampleAr: "ما أنواع الوظائف الأكثر رواجاً بين الخرّيجين في بلدك في الوقت الحالي؟" },
        { en: "challenging", ar: "مُتحدٍّ / صعب ومثير", pos: "adjective", def: "difficult in an interesting way", defAr: "صعب بطريقة مثيرة للاهتمام", example: "I can’t enjoy a job unless it is quite challenging.", exampleAr: "لا أستطيع أن أستمتع بوظيفة إلا إذا كانت فيها تحدّيات كافية." },
        { en: "status", ar: "مكانة اجتماعية", pos: "noun", def: "your position or rank in society", defAr: "موقعك أو منزلتك في المجتمع", example: "A position with power and status is attractive to me.", exampleAr: "المنصب الذي فيه سلطة ومكانة جذّاب بالنسبة لي." },
        { en: "responsibility", ar: "مسؤولية", pos: "noun", def: "a duty to take care of something or someone", defAr: "واجب رعاية شيء أو شخص ما", example: "I wouldn’t like a job with too much responsibility.", exampleAr: "لا أحب وظيفة فيها مسؤولية كبيرة جداً." },
        { en: "contribute", ar: "يُسهِم", pos: "verb", def: "to give something to help a group or society", defAr: "أن تقدّم شيئاً لمساعدة جماعة أو مجتمع", example: "I want a job that allows me to contribute to society.", exampleAr: "أريد وظيفة تتيح لي الإسهام في خدمة المجتمع." },
        { en: "motivation", ar: "دافع / حافز", pos: "noun", def: "the reason that makes you want to do something", defAr: "السبب الذي يجعلك تريد فعل شيء ما", example: "My main motivation for working is to make money.", exampleAr: "دافعي الأساسي للعمل هو كسب المال." },
        { en: "part time", ar: "دوام جزئي", pos: "adverb", def: "working only part of the day or week", defAr: "العمل جزءاً من اليوم أو الأسبوع فقط", example: "I’d prefer to work part time instead of full time.", exampleAr: "أفضّل أن أعمل بدوام جزئي بدلاً من الدوام الكامل." },
        { en: "various", ar: "متنوّع / مختلف", pos: "adjective", def: "of many different kinds (from the verb vary)", defAr: "من أنواع كثيرة مختلفة (من الفعل vary)" },
        { en: "reality", ar: "حقيقة / واقع", pos: "noun", def: "something that really exists or happens (from real)", defAr: "شيء موجود أو يحدث فعلاً (من real)" },
        { en: "guidance", ar: "إرشاد / توجيه", pos: "noun", def: "help and advice (from the verb guide)", defAr: "مساعدة ونصيحة (من الفعل guide)" },
        { en: "reach out to", ar: "يمدّ يد العون إلى", pos: "phrasal verb", def: "offer help and support to someone", defAr: "أن تقدّم المساعدة والدعم لشخص ما", example: "The rich have to reach out to the poor.", exampleAr: "على الأغنياء أن يمدّوا يد العون إلى الفقراء." },
        { en: "fit in", ar: "يندمج / يتأقلم", pos: "phrasal verb", def: "be accepted by other people in a group", defAr: "أن يتقبّلك الآخرون في مجموعة ما", example: "She didn’t really fit in with her workmates in her previous job.", exampleAr: "لم تندمج حقاً مع زملائها في وظيفتها السابقة." },
        { en: "get into", ar: "يبدأ الاهتمام بـ", pos: "phrasal verb", def: "start to become interested in something", defAr: "أن تبدأ بالاهتمام بشيء ما", example: "I got into writing when I was a kid, and I just never stopped loving it.", exampleAr: "بدأت أهتم بالكتابة عندما كنت طفلاً، ولم أتوقف أبداً عن حبّها." },
        { en: "follow through", ar: "يُتمّ / يتابع حتى النهاية", pos: "phrasal verb", def: "start something and finish it in a satisfactory way", defAr: "أن تبدأ شيئاً وتنهيه بطريقة مُرضية", example: "We’ve been talking about this project for a while, and it’s time to follow it through.", exampleAr: "نحن نتحدث عن هذا المشروع منذ مدة، وقد حان الوقت لنُتمّه حتى النهاية." },
        { en: "run into", ar: "يواجه فجأة", pos: "phrasal verb", def: "encounter problems or difficulties unexpectedly", defAr: "أن تواجه مشكلات أو صعوبات بشكل غير متوقّع", example: "If you run into any trouble, just give me a call.", exampleAr: "إذا واجهت أي مشكلة، فقط اتصل بي." },
        { en: "keep up with", ar: "يواكب / يبقى على اطّلاع بـ", pos: "phrasal verb", def: "stay updated and informed about something", defAr: "أن تبقى مطّلعاً على آخر المستجدّات في أمر ما", example: "A big part of my job is keeping up with the latest research in medical technology.", exampleAr: "جزء كبير من عملي هو مواكبة أحدث الأبحاث في التكنولوجيا الطبية." },
        { en: "homophone", ar: "كلمة متشابهة اللفظ", pos: "noun", def: "a word with the same pronunciation as another word but a different meaning and spelling", defAr: "كلمة تُلفظ مثل كلمة أخرى لكن معناها وتهجئتها مختلفان", example: "Homophones are words that have the same pronounciation but different meanings and spellings.", exampleAr: "الكلمات المتشابهة اللفظ هي كلمات لها النطق نفسه لكن معانيها وتهجئتها مختلفة." },
        { en: "challenge", ar: "تحدٍّ", pos: "noun", def: "something difficult that tests your ability", defAr: "شيء صعب يختبر قدرتك", example: "What kind of challenges do you expect to face in your future career?", exampleAr: "ما نوع التحدّيات التي تتوقّع أن تواجهها في مهنتك المستقبلية؟" },
      ],
      reading: {
        title: "Future Careers",
        paragraphs: [
          "Not all people have the ability to explore their future and build it with more confidence and clarity. Most studies have highlighted the role of parents as active agents in the career development of their children. Parents want their children to opt for a career they know well about, but what their children want or aspire to become can be completely different. Many parents said they had misguided their children into choosing a career of their choice. It is very important not to burden our children with unreal expectations. There are a few factors that are of great importance in the career selection process. The child’s aptitude is a mirror of his/her personality, strengths, and weaknesses. Hence, a designed aptitude test can reveal a lot of information regarding the child that can help in taking a well-informed career selection. It is very difficult to spend your life working in a field that you are not interested in. Courses leading towards a desired career should be found easily for the young to enable them to make right decisions about their future. Psychologists said that it was very easy for a child to get swayed by peer pressure into choosing a career that the majority was opting rather than the one which was best for him/her.",
          "Although it should not be the most important, remuneration of a career holds value in one’s life; nobody likes to earn little. A job’s earnings should match the child’s aspirations and provide a satisfying comfortable life. Modern societies need professionals in every field: utility workers, garbage collectors, farmers, nurses, doctors, engineers, teachers, professors and many others.",
          "Furthermore, demotivation might have a negative impact on the child’s mental health when rejecting all of his/her ideas. Parents can work together to gather information about a career and then help the child in deciding whether it is suitable or not. Most people have dreams of future jobs and there’s no limit to what this could be, but we can't be absolutely certain about our career choices. Researchers told us that through self-reflection and guided activities, we would find our core values and a clearer path towards the right career.",
        ],
        paragraphsAr: [
          "ليس كل الناس قادرين على استكشاف مستقبلهم وبنائه بمزيد من الثقة والوضوح. لقد سلّطت معظم الدراسات الضوء على دور الآباء بوصفهم عناصر فاعلة في التطوّر المهني لأبنائهم. يريد الآباء أن يختار أبناؤهم مهنة يعرفونها جيداً، لكن ما يريده الأبناء أو يطمحون أن يصبحوا عليه قد يكون مختلفاً تماماً. وقد قال كثير من الآباء إنهم وجّهوا أبناءهم توجيهاً خاطئاً فدفعوهم إلى اختيار مهنة من اختيار الآباء. من المهم جداً ألّا نُثقل أبناءنا بتوقّعات غير واقعية. هناك بعض العوامل ذات الأهمية الكبيرة في عملية اختيار المهنة. فاستعداد الطفل (قدرته الطبيعية) مرآةٌ لشخصيته ونقاط قوته وضعفه. لذلك يمكن لاختبار قدرات مُصمَّم جيداً أن يكشف الكثير من المعلومات عن الطفل، مما يساعد على اختيار المهنة عن معرفة ودراية. من الصعب جداً أن تقضي حياتك تعمل في مجال لا يهمّك. وينبغي أن تتوفّر للشباب بسهولة دوراتٌ تقود إلى المهنة التي يرغبون فيها، لتمكّنهم من اتخاذ قرارات صحيحة بشأن مستقبلهم. وقال علماء النفس إنه من السهل جداً أن يتأثّر الطفل بضغط الأقران فيختار المهنة التي تختارها الأغلبية بدلاً من المهنة الأفضل له.",
          "مع أن الأجر لا ينبغي أن يكون الأمر الأهم، فإن للأجر الذي تقدّمه المهنة قيمةً في حياة الإنسان؛ فلا أحد يحب أن يكسب القليل. ينبغي أن يتناسب دخل الوظيفة مع طموحات الطفل وأن يوفّر حياة مريحة مُرضية. تحتاج المجتمعات الحديثة إلى أصحاب مهن في كل مجال: عمّال المرافق العامة، وعمّال جمع القمامة، والمزارعين، والممرّضين، والأطباء، والمهندسين، والمعلّمين، والأساتذة وغيرهم كثير.",
          "علاوة على ذلك، قد يكون للإحباط أثر سلبي في الصحة النفسية للطفل عندما تُرفَض كل أفكاره. يستطيع الآباء أن يعملوا معاً لجمع المعلومات عن مهنة ما، ثم يساعدوا الطفل في تقرير ما إذا كانت مناسبة له أم لا. لدى معظم الناس أحلام بوظائف المستقبل ولا حدود لما يمكن أن تكون عليه، لكننا لا نستطيع أن نكون متأكّدين تماماً من خياراتنا المهنية. وقد أخبرنا الباحثون أنه من خلال التأمّل الذاتي والأنشطة الموجَّهة سنجد قيمنا الأساسية وطريقاً أوضح نحو المهنة المناسبة.",
        ],
        questions: [
          { q: "How do most parents nowadays guide their children to choose their future career?", qAr: "كيف يوجّه معظم الآباء في أيامنا هذه أبناءهم لاختيار مهنتهم المستقبلية؟",
            options: ["They let their children choose any career they like.", "They want their children to opt for a career they know well about.", "They send their children to psychologists.", "They ask the majority of people to choose for them."],
            answer: 1, explainAr: "النص يقول: Parents want their children to opt for a career they know well about — أي يريدون أن يختار أبناؤهم مهنة يعرفها الآباء جيداً، بل إن كثيراً منهم دفعوا أبناءهم إلى مهنة من اختيار الآباء." },
          { q: "Do parents follow the right strategy, according to the text? Why?", qAr: "هل يتّبع الآباء الاستراتيجية الصحيحة حسب النص؟ ولماذا؟",
            options: ["Yes, because parents always know the best career for their children.", "Yes, because children cannot think about their future.", "No, because what their children want can be completely different, and many parents misguided their children.", "No, because parents never talk to their children about jobs."],
            answer: 2, explainAr: "النص يوضّح أن ما يريده الأبناء قد يكون مختلفاً تماماً، وأن كثيراً من الآباء اعترفوا بأنهم وجّهوا أبناءهم توجيهاً خاطئاً، وأنه يجب ألّا نُثقلهم بتوقّعات غير واقعية." },
          { q: "What factors should be taken into consideration to decide a future career?", qAr: "ما العوامل التي يجب أخذها بعين الاعتبار لتقرير المهنة المستقبلية؟",
            options: ["Only the opinion of friends.", "The child’s aptitude, his/her interest in the field, the courses available and the remuneration of the career.", "Only what the majority is choosing.", "Only the job that the parents know well."],
            answer: 1, explainAr: "ذكر النص: استعداد الطفل (aptitude)، والعمل في مجال يهتم به، والدورات التي تقود إلى المهنة (courses)، والأجر (remuneration)." },
          { q: "What is the influence of peers on children?", qAr: "ما تأثير الأقران في الأطفال؟",
            options: ["They help children find the best career for them.", "They have no influence at all.", "A child can easily get swayed by peer pressure into choosing the career that the majority is choosing.", "They make children study harder."],
            answer: 2, explainAr: "النص يقول إنه من السهل جداً أن يتأثّر الطفل بضغط الأقران (swayed by peer pressure) فيختار المهنة التي تختارها الأغلبية بدلاً من الأفضل له." },
          { q: "How can demotivation affect the child's character?", qAr: "كيف يمكن أن يؤثّر الإحباط في شخصية الطفل؟",
            options: ["It might have a negative impact on the child’s mental health.", "It makes the child more confident.", "It helps the child choose a career quickly.", "It has a positive effect on his/her ideas."],
            answer: 0, explainAr: "النص يقول: demotivation might have a negative impact on the child’s mental health — قد يكون للإحباط أثر سلبي في صحته النفسية عندما تُرفَض كل أفكاره." },
          { q: "What do researchers recommend to choose our future career?", qAr: "بماذا يوصي الباحثون لاختيار مهنتنا المستقبلية؟",
            options: ["Following what our friends choose.", "Choosing the job that pays the most.", "Self-reflection and guided activities, to find our core values and a clearer path.", "Waiting until we are absolutely certain."],
            answer: 2, explainAr: "النص يقول: through self-reflection and guided activities, we would find our core values and a clearer path towards the right career." },
          { q: "What can a designed aptitude test do?", qAr: "ماذا يستطيع اختبار القدرات المُصمَّم أن يفعل؟",
            options: ["It can reveal a lot of information about the child that helps in a well-informed career selection.", "It can choose a job for the child.", "It can increase the child’s earnings.", "It can stop peer pressure."],
            answer: 0, explainAr: "النص يقول: a designed aptitude test can reveal a lot of information regarding the child that can help in taking a well-informed career selection." },
          { q: "What does the word “it” refer to in “help the child in deciding whether it is suitable or not”?", qAr: "إلى ماذا يعود الضمير “it” في عبارة “help the child in deciding whether it is suitable or not”؟",
            options: ["the child", "a career", "information", "mental health"],
            answer: 1, explainAr: "الجملة تقول: Parents can work together to gather information about a career … — فالضمير it يعود على المهنة (a career) التي يجمع الآباء معلومات عنها." },
        ],
        trueFalse: [
          { statement: "Studies have highlighted the role of parents as active agents in the career development of their children.", answer: true },
          { statement: "What children want to become is always the same as what their parents want.", answer: false },
          { statement: "The child’s aptitude is a mirror of his/her personality, strengths, and weaknesses.", answer: true },
          { statement: "According to the text, remuneration should be the most important factor in choosing a career.", answer: false },
          { statement: "We can be absolutely certain about our career choices.", answer: false },
        ],
      },
      vocabFocus: {
        name: "Word Family and Phrasal Verbs", nameAr: "عائلة الكلمة والأفعال المركّبة",
        ruleEn: [
          "Word family: words that come from the same root but are different parts of speech: vary (verb) → various (adjective); real (adjective) → reality (noun); decide (verb) → decision (noun); accomplish (verb) → accomplishment (noun); guide (verb) → guidance (noun).",
          "Choose the form the sentence needs: after a / the / great we need a noun (a reality, a great accomplishment); before a noun we need an adjective (various dreams).",
          "Phrasal verbs: a verb + a particle with a new meaning: reach out to = offer help and support to someone; fit in = be accepted by other people in a group; get into = start to become interested in something; follow through = start something and finish it in a satisfactory way; run into = encounter problems or difficulties unexpectedly; keep up with = stay updated and informed about something.",
          "Words from the article: aspire = seek to attain a goal; burden = load; aptitude = natural ability or skill; swayed = influenced; remuneration = money paid for work or services; demotivation = making someone less eager or willing to do their job.",
        ],
        ruleAr: [
          "عائلة الكلمة: كلمات من جذر واحد لكنها أقسام كلام مختلفة: vary (يتنوّع) ← various (متنوّع)، real (حقيقي) ← reality (حقيقة/واقع)، decide (يقرّر) ← decision (قرار)، accomplish (يُنجز) ← accomplishment (إنجاز)، guide (يرشد) ← guidance (إرشاد).",
          "انظر إلى مكان الفراغ: بعد a / the / great نحتاج اسماً (a reality)، وقبل الاسم نحتاج صفة (various dreams). اللاحقة ‎-ment و ‎-ance و ‎-ity و ‎-ion تصنع أسماء، واللاحقة ‎-ous تصنع صفة.",
          "الفعل المركّب (phrasal verb) = فعل + أداة، ويصبح له معنى جديد يجب حفظه: reach out to (يمدّ يد العون)، fit in (يندمج مع الجماعة)، get into (يبدأ الاهتمام بـ)، follow through (يُتمّ الشيء حتى نهايته)، run into (يواجه مشكلة فجأة)، keep up with (يواكب آخر المستجدّات).",
          "كلمات من نص القراءة: aspire (يطمح)، burden (يُثقل)، aptitude (استعداد/موهبة طبيعية)، swayed (متأثّر)، remuneration (أجر)، demotivation (إحباط/فقدان الحافز).",
        ],
        examples: [
          "The rich have to reach out to the poor.",
          "She didn’t really fit in with her workmates in her previous job.",
          "I got into writing when I was a kid, and I just never stopped loving it.",
          "We’ve been talking about this project for a while, and it’s time to follow it through.",
          "If you run into any trouble, just give me a call.",
          "A big part of my job is keeping up with the latest research in medical technology.",
        ],
        exercises: [
          // Vocabulary a — word family
          { type: "fill", prompt: "Individuals have ___ dreams in their day-to-day existence. (vary)", promptAr: "لدى الأفراد أحلام ___ في حياتهم اليومية. (vary)", promptArFull: "لدى الأفراد أحلام متنوّعة في حياتهم اليومية.", options: ["various", "variety", "vary", "variously"], answer: 0, explainAr: "قبل الاسم dreams نحتاج صفة، وصفة الفعل vary هي various (متنوّعة)." },
          { type: "fill", prompt: "Everyone endeavours a great deal to make dreams a ___. (real)", promptAr: "يجتهد الجميع كثيراً ليجعلوا الأحلام ___. (real)", promptArFull: "يجتهد الجميع كثيراً ليجعلوا الأحلام حقيقة.", options: ["real", "reality", "really", "realize"], answer: 1, explainAr: "بعد أداة التنكير a نحتاج اسماً: reality (حقيقة). make dreams a reality = يحقّق الأحلام." },
          { type: "fill", prompt: "Future plans and ___s have a great importance in a person’s life. (decide)", promptAr: "للخطط و___ المستقبلية أهمية كبيرة في حياة الإنسان. (decide)", promptArFull: "للخطط والقرارات المستقبلية أهمية كبيرة في حياة الإنسان.", options: ["decide", "decisive", "decision", "deciding"], answer: 2, explainAr: "نحتاج اسماً معطوفاً على plans (اسم جمع)، واسم الفعل decide هو decision، ومع s يصبح decisions (قرارات)." },
          { type: "fill", prompt: "Gaining your boss confidence is really a great ___. (accomplish)", promptAr: "إن كسب ثقة مديرك ___ عظيم حقاً. (accomplish)", promptArFull: "إن كسب ثقة مديرك إنجاز عظيم حقاً.", options: ["accomplish", "accomplished", "accomplishment", "accomplishing"], answer: 2, explainAr: "بعد a great (أداة + صفة) نحتاج اسماً: accomplishment (إنجاز)، واللاحقة ‎-ment تصنع الاسم." },
          { type: "fill", prompt: "I went to a counselor for ___ on my career. (guide)", promptAr: "ذهبت إلى مرشد للحصول على ___ بشأن مهنتي. (guide)", promptArFull: "ذهبت إلى مرشد للحصول على إرشاد بشأن مهنتي.", options: ["guide", "guidance", "guided", "guiding"], answer: 1, explainAr: "بعد حرف الجر for نحتاج اسماً بمعنى النصيحة والتوجيه: guidance (إرشاد)." },
          // Vocabulary b — phrasal verbs
          { type: "mcq", prompt: "“The rich have to reach out to the poor.” What does “reach out to” mean?", promptAr: "“على الأغنياء أن يمدّوا يد العون إلى الفقراء.” ما معنى “reach out to”؟", options: ["be accepted by other people in a group", "offer help and support to someone", "stay updated and informed about something", "start to become interested in something"], answer: 1, explainAr: "الجواب: 1 ← f. reach out to = يقدّم المساعدة والدعم لشخص ما." },
          { type: "mcq", prompt: "“She didn’t really fit in with her workmates in her previous job.” What does “fit in” mean?", promptAr: "“لم تندمج حقاً مع زملائها في وظيفتها السابقة.” ما معنى “fit in”؟", options: ["encounter problems or difficulties unexpectedly", "offer help and support to someone", "be accepted by other people in a group", "start something and finish it in a satisfactory way"], answer: 2, explainAr: "الجواب: 2 ← a. fit in = أن يتقبّلك الآخرون في مجموعة ما (تندمج معهم)." },
          { type: "mcq", prompt: "“I got into writing when I was a kid, and I just never stopped loving it.” What does “get into” mean?", promptAr: "“بدأت أهتم بالكتابة عندما كنت طفلاً، ولم أتوقف أبداً عن حبّها.” ما معنى “get into”؟", options: ["start to become interested in something", "stay updated and informed about something", "be accepted by other people in a group", "encounter problems or difficulties unexpectedly"], answer: 0, explainAr: "الجواب: 3 ← d. get into = يبدأ الاهتمام بشيء ما." },
          { type: "mcq", prompt: "“We’ve been talking about this project for a while, and it’s time to follow it through.” What does “follow through” mean?", promptAr: "“نحن نتحدث عن هذا المشروع منذ مدة، وقد حان الوقت لنُتمّه.” ما معنى “follow through”؟", options: ["offer help and support to someone", "start something and finish it in a satisfactory way", "start to become interested in something", "be accepted by other people in a group"], answer: 1, explainAr: "الجواب: 4 ← c. follow through = يبدأ شيئاً وينهيه بطريقة مُرضية." },
          { type: "mcq", prompt: "“If you run into any trouble, just give me a call.” What does “run into” mean?", promptAr: "“إذا واجهت أي مشكلة، فقط اتصل بي.” ما معنى “run into”؟", options: ["stay updated and informed about something", "start something and finish it in a satisfactory way", "offer help and support to someone", "encounter problems or difficulties unexpectedly"], answer: 3, explainAr: "الجواب: 5 ← b. run into = يواجه مشكلات أو صعوبات بشكل غير متوقّع." },
          { type: "mcq", prompt: "“A big part of my job is keeping up with the latest research in medical technology.” What does “keep up with” mean?", promptAr: "“جزء كبير من عملي هو مواكبة أحدث الأبحاث في التكنولوجيا الطبية.” ما معنى “keep up with”؟", options: ["stay updated and informed about something", "be accepted by other people in a group", "encounter problems or difficulties unexpectedly", "start to become interested in something"], answer: 0, explainAr: "الجواب: 6 ← e. keep up with = يبقى على اطّلاع بآخر المستجدّات." },
          // Reading b — meanings of the highlighted words
          { type: "mcq", prompt: "In the text, “aspire” (what their children want or aspire to become) means:", promptAr: "في النص، كلمة “aspire” تعني:", options: ["seek to attain a goal", "advance", "load"], answer: 0, explainAr: "تمرين القراءة b ‏(1 ← a): aspire = يسعى إلى تحقيق هدف (يطمح)." },
          { type: "mcq", prompt: "In the text, “burden” (not to burden our children with unreal expectations) means:", promptAr: "في النص، كلمة “burden” تعني:", options: ["reduce", "load", "influence"], answer: 1, explainAr: "تمرين القراءة b ‏(2 ← b): burden = يُحمِّل (يُثقل) بحِمل ثقيل، أي ألّا نُثقل أبناءنا بتوقّعات غير واقعية." },
          { type: "mcq", prompt: "In the text, “aptitude” (the child’s aptitude is a mirror of his/her personality) means:", promptAr: "في النص، كلمة “aptitude” تعني:", options: ["quality", "natural ability or skill", "money paid for work or services"], answer: 1, explainAr: "تمرين القراءة b ‏(3 ← b): aptitude = قدرة أو مهارة طبيعية (استعداد)." },
          { type: "mcq", prompt: "In the text, “swayed” (to get swayed by peer pressure) means:", promptAr: "في النص، كلمة “swayed” تعني:", options: ["influenced", "lost", "advanced"], answer: 0, explainAr: "تمرين القراءة b ‏(4 ← a): swayed = متأثّر، أي يتأثّر الطفل بضغط أقرانه." },
          { type: "mcq", prompt: "In the text, “remuneration” (remuneration of a career holds value in one’s life) means:", promptAr: "في النص، كلمة “remuneration” تعني:", options: ["an amount of money given to someone as a debt", "money paid for work or services", "natural ability or skill"], answer: 1, explainAr: "تمرين القراءة b ‏(5 ← a): remuneration = المال المدفوع مقابل العمل أو الخدمات (الأجر)." },
          { type: "mcq", prompt: "In the text, “demotivation” (demotivation might have a negative impact) means:", promptAr: "في النص، كلمة “demotivation” تعني:", options: ["making someone more eager or willing to do their job", "making someone less eager or willing to do their job", "an amount of money given to someone as a debt"], answer: 1, explainAr: "تمرين القراءة b ‏(6 ← b): البادئة de- تعطي معنى عكسياً، فـ demotivation = جعل الشخص أقل حماساً ورغبة (إحباط)." },
          // Reading c — complete with words from the article
          { type: "fill", prompt: "Parents play a vital ___ in the career development of their children.", promptAr: "يؤدّي الآباء ___ حيوياً في التطوّر المهني لأبنائهم.", promptArFull: "يؤدّي الآباء دوراً حيوياً في التطوّر المهني لأبنائهم.", options: ["aptitude", "role", "course"], answer: 1, explainAr: "تمرين القراءة c: النص يقول the role of parents as active agents — play a vital role = يؤدّي دوراً حيوياً." },
          { type: "fill", prompt: "Parents should study very well the ___ of their children to decide their future career.", promptAr: "يجب أن يدرس الآباء جيداً ___ أبنائهم لتقرير مهنتهم المستقبلية.", promptArFull: "يجب أن يدرس الآباء جيداً استعداد (قدرات) أبنائهم لتقرير مهنتهم المستقبلية.", options: ["remuneration", "role", "aptitude"], answer: 2, explainAr: "تمرين القراءة c: النص يقول إن استعداد الطفل (aptitude) مرآة لشخصيته ونقاط قوته وضعفه، فيجب دراسته." },
          { type: "fill", prompt: "There should be leading ___ to help children choose the best job for them in the future.", promptAr: "يجب أن تكون هناك ___ توجيهية لمساعدة الأطفال على اختيار أفضل وظيفة لهم في المستقبل.", promptArFull: "يجب أن تكون هناك دورات توجيهية لمساعدة الأطفال على اختيار أفضل وظيفة لهم في المستقبل.", options: ["courses", "earnings", "peers"], answer: 0, explainAr: "تمرين القراءة c: النص يقول Courses leading towards a desired career should be found easily — الدورات التي تقود إلى المهنة." },
          { type: "fill", prompt: "Nowadays, most people encourage their children to choose their future profession based on the ___ that profession brings to them.", promptAr: "في أيامنا هذه، يشجّع معظم الناس أبناءهم على اختيار مهنتهم المستقبلية بناءً على ___ الذي تجلبه لهم تلك المهنة.", promptArFull: "في أيامنا هذه، يشجّع معظم الناس أبناءهم على اختيار مهنتهم المستقبلية بناءً على الأجر الذي تجلبه لهم تلك المهنة.", options: ["demotivation", "remuneration", "aptitude"], answer: 1, explainAr: "تمرين القراءة c: ما تجلبه المهنة من مال هو الأجر remuneration (ويمكن أيضاً earnings)." },
          // More practice on the same word families
          { type: "fill", prompt: "What do you hope to ___ through your future job?", promptAr: "ماذا تأمل أن ___ من خلال وظيفتك المستقبلية؟", promptArFull: "ماذا تأمل أن تحقّق من خلال وظيفتك المستقبلية؟", options: ["accomplishment", "accomplish", "accomplished"], answer: 1, explainAr: "بعد to نحتاج الفعل في مصدره: to accomplish (أن تحقّق). أما accomplishment فهو الاسم." },
          { type: "fill", prompt: "Parents can help the child in ___ whether it is suitable or not.", promptAr: "يستطيع الآباء أن يساعدوا الطفل في ___ ما إذا كانت (المهنة) مناسبة أم لا.", promptArFull: "يستطيع الآباء أن يساعدوا الطفل في تقرير ما إذا كانت (المهنة) مناسبة أم لا.", options: ["decision", "decide", "deciding"], answer: 2, explainAr: "بعد حرف الجر in يأتي الفعل بصيغة ing: in deciding. ولا يصح decision هنا لأن بعده whether ويحتاج فعلاً." },
          { type: "fill", prompt: "Through self-reflection and ___ activities, we would find our core values.", promptAr: "من خلال التأمّل الذاتي والأنشطة ___ سنجد قيمنا الأساسية.", promptArFull: "من خلال التأمّل الذاتي والأنشطة الموجَّهة سنجد قيمنا الأساسية.", options: ["guidance", "guided", "guide"], answer: 1, explainAr: "قبل الاسم activities نحتاج صفة، والتصريف الثالث guided يعمل صفة بمعنى (موجَّهة)." },
          { type: "fill", prompt: "It is very important not to burden our children with ___ expectations.", promptAr: "من المهم جداً ألّا نُثقل أبناءنا بتوقّعات ___.", promptArFull: "من المهم جداً ألّا نُثقل أبناءنا بتوقّعات غير واقعية.", options: ["reality", "unreal", "really"], answer: 1, explainAr: "قبل الاسم expectations نحتاج صفة: unreal (غير واقعية)، والبادئة un- تعطي المعنى المعاكس لـ real." },
        ],
      },
      grammar: {
        name: "Revision of Tenses 1", nameAr: "مراجعة الأزمنة 1",
        ruleEn: [
          "Present Continuous (am / is / are + verb-ing): an action happening now or around now. (John is swimming in the pool. Are you working hard at the moment?)",
          "Spelling of -ing: double the last consonant after a short vowel: get → getting, sit → sitting; ie → y: lie → lying. (not geting, siting)",
          "Present Simple: state verbs such as think (= have an opinion), like, know and understand are not usually used in the continuous. (We think it’s great here. We like Egypt. I know your exams start tomorrow.)",
          "Present Perfect Continuous (have / has been + verb-ing): an activity that has been going on recently; we can see its result now. (Jane, why are you sweating? Because I have been sweeping the floors.)",
          "Present Perfect Simple (have / has + past participle): a completed action with a result now. (Is the lawn finished? Yes, George has cut the grass.)",
          "Past Simple: a completed action in the past; recent actions when we say exactly when. (I saw Jack last night. I won a writing competition in 2006.)",
          "Present Perfect: things which started in the past and are true now; recent actions when we don’t say exactly when. (We have been friends for more than ten years. I have just bought it.)",
        ],
        ruleAr: [
          "المضارع المستمر (am / is / are + الفعل + ing): لحدث يجري الآن أو في هذه الفترة: John is swimming in the pool.",
          "تهجئة ing: نضاعف الحرف الأخير إذا سبقه حرف علّة قصير: get ← getting و sit ← sitting، وإذا انتهى الفعل بـ ie نحوّلها إلى y: lie ← lying.",
          "أفعال الحالة مثل think (بمعنى أعتقد) و like (يحب) و know (يعرف) و understand (يفهم) لا تأتي عادةً بصيغة المستمر، بل بالمضارع البسيط: We like Egypt.",
          "المضارع التام المستمر (have / has been + الفعل + ing): لنشاط استمر حتى وقت قريب ونرى أثره الآن (يتعرّق لأنه كان يكنس الأرض): I have been sweeping the floors.",
          "المضارع التام البسيط (have / has + التصريف الثالث): لعمل انتهى ونتيجته واضحة الآن (العشب قُصّ): George has cut the grass.",
          "الماضي البسيط: لعمل انتهى في الماضي، أو لعمل حديث عندما نذكر وقته بالتحديد (last night / in 2006): I saw Jack last night.",
          "المضارع التام: لأشياء بدأت في الماضي وما زالت صحيحة الآن (for / since)، أو لأعمال حديثة لا نذكر وقتها بالتحديد (just / ever): I have just bought it.",
        ],
        examples: [
          "Everyone is having a good time.",
          "We think it’s great here.",
          "Because I have been sweeping the floors.",
          "Yes, George has cut the grass.",
          "I saw Jack last night.",
          "I’ve been using a computer for at least three years.",
        ],
        exercises: [
          // Grammar a — Tom's email: correct the Present Continuous where necessary
          { type: "fill", prompt: "I’m ___ in the Nile Hotel.", promptAr: "أنا ___ في فندق النيل.", promptArFull: "أنا جالس في فندق النيل.", options: ["siting", "sitting", "sit"], answer: 1, explainAr: "(1) الصيغة المستمرة صحيحة لكن التهجئة خاطئة: sit ← sitting، نضاعف t لأن قبلها حرف علّة قصيراً." },
          { type: "fill", prompt: "John ___ in the pool.", promptAr: "جون ___ في المسبح.", promptArFull: "جون يسبح في المسبح.", options: ["is swimming", "swims", "is swiming"], answer: 0, explainAr: "(2) ✓ صحيحة: حدث يجري الآن، والتهجئة صحيحة swimming (بمضاعفة m)." },
          { type: "fill", prompt: "Sally ___ in the sun.", promptAr: "سالي ___ تحت الشمس.", promptArFull: "سالي مستلقية تحت الشمس.", options: ["is lieing", "lies", "is lying"], answer: 2, explainAr: "(3) ✓ صحيحة: is lying حدث يجري الآن، وتهجئة lie مع ing هي lying." },
          { type: "fill", prompt: "And Jane ___!", promptAr: "وجين ___!", promptArFull: "وجين تتسوّق!", options: ["is shoping", "is shopping", "shops"], answer: 1, explainAr: "(4) ✓ صحيحة: is shopping حدث يجري الآن، ونضاعف p." },
          { type: "fill", prompt: "___ Egypt.", promptAr: "___ مصر.", promptArFull: "نحن نحب مصر.", options: ["We’re liking", "We like", "We likes"], answer: 1, explainAr: "(5) خطأ في الأصل: like فعل حالة (شعور) لا يأتي بالمستمر، فنقول We like Egypt." },
          { type: "fill", prompt: "We’re all ___.", promptAr: "نحن جميعاً ___.", promptArFull: "نحن جميعاً نسترخي.", options: ["relax", "relaxing", "relaxes"], answer: 1, explainAr: "(6) ✓ صحيحة: We’re all relaxing حدث يجري الآن في العطلة." },
          { type: "fill", prompt: "Are you ___ hard at the moment?", promptAr: "هل ___ بجدّ في هذه الفترة؟", promptArFull: "هل تعمل بجدّ في هذه الفترة؟", options: ["work", "works", "working"], answer: 2, explainAr: "(7) ✓ صحيحة: at the moment تدل على الآن / هذه الفترة، فنستخدم Are you working." },
          { type: "fill", prompt: "___ your exams start tomorrow.", promptAr: "___ أن امتحاناتك تبدأ غداً.", promptArFull: "أعرف أن امتحاناتك تبدأ غداً.", options: ["I’m knowning", "I know", "I’m knowing"], answer: 1, explainAr: "(8) خطأ في الأصل: know فعل حالة لا يأتي بالمستمر، فنقول I know." },
          { type: "fill", prompt: "___ in England?", promptAr: "___ في إنكلترا؟", promptArFull: "هل تمطر في إنكلترا؟", options: ["Is it raining", "Does it raining", "Is it rainning"], answer: 0, explainAr: "(9) ✓ صحيحة: سؤال عمّا يحدث الآن، والتهجئة raining (لا نضاعف n لأن قبلها حرفا علّة)." },
          { type: "fill", prompt: "The sun ___ here, of course!", promptAr: "الشمس ___ هنا بالطبع!", promptArFull: "الشمس مشرقة هنا بالطبع!", options: ["is shineing", "are shining", "is shining"], answer: 2, explainAr: "(10) ✓ صحيحة: is shining حدث يجري الآن، ونحذف e من shine قبل ing." },
          { type: "fill", prompt: "I’m ___ a bit of Arabic, but not very much.", promptAr: "أنا ___ قليلاً من العربية، لكن ليس كثيراً.", promptArFull: "أنا أتعلّم قليلاً من العربية، لكن ليس كثيراً.", options: ["learning", "learnning", "learn"], answer: 0, explainAr: "(11) ✓ صحيحة: I’m learning لحالة مؤقتة في هذه الفترة." },
          { type: "fill", prompt: "___ some of the things that people say.", promptAr: "___ بعض الأشياء التي يقولها الناس.", promptArFull: "أفهم بعض الأشياء التي يقولها الناس.", options: ["I’m understanding", "I understanding", "I understand"], answer: 2, explainAr: "(12) خطأ في الأصل: understand فعل حالة (فهم) لا يأتي بالمستمر، فنقول I understand." },
          // Grammar b — Present Perfect Simple or Continuous
          { type: "mcq", prompt: "Rachel, why are your hands so soft? Because I …", promptAr: "راشيل، لماذا يداكِ ناعمتان جداً؟ لأنني …", options: ["have done the washing-up.", "have been doing the washing-up.", "am doing the washing-up.", "did the washing-up."], answer: 1, explainAr: "اليدان ناعمتان الآن نتيجةً لنشاط استمر مدة (غسل الصحون)، فنستخدم المضارع التام المستمر: have been doing." },
          { type: "mcq", prompt: "Are the onions ready for the pan? Yes, Mike … them.", promptAr: "هل البصل جاهز للمقلاة؟ نعم، مايك … ـه.", options: ["has been peeling", "has peeled", "is peeling", "peeled"], answer: 1, explainAr: "السؤال عن نتيجة عمل انتهى (البصل جاهز)، فنستخدم المضارع التام البسيط: has peeled them." },
          { type: "mcq", prompt: "George, you look tired. Yes, I …", promptAr: "جورج، تبدو متعباً. نعم، …", options: ["have cut the grass.", "cut the grass.", "have been cutting the grass.", "am cutting the grass."], answer: 2, explainAr: "التعب أثر لنشاط استمر مدة (قصّ العشب)، فنستخدم المضارع التام المستمر: have been cutting." },
          { type: "mcq", prompt: "Tom, your hands are very cold. Yes, I …", promptAr: "توم، يداك باردتان جداً. نعم، …", options: ["have been defrosting the fridge.", "have defrosted the fridge.", "defrost the fridge.", "am defrosted the fridge."], answer: 0, explainAr: "برودة اليدين أثر لنشاط استمر مدة (إذابة الثلج في البرّاد)، فنقول: have been defrosting." },
          { type: "mcq", prompt: "Are the floors clean? Yes, Jane … them.", promptAr: "هل الأرضيات نظيفة؟ نعم، جين … ـها.", options: ["has been sweeping", "has swept", "sweeps", "has sweeped"], answer: 1, explainAr: "السؤال عن النتيجة (الأرض نظيفة) فنستخدم المضارع التام البسيط، والتصريف الثالث لـ sweep هو swept (فعل شاذ)." },
          { type: "mcq", prompt: "Why are your eyes red, Mike? Because I …", promptAr: "لماذا عيناك حمراوان يا مايك؟ لأنني …", options: ["have peeled the onions.", "peel the onions.", "have been peeling the onions.", "had peeled the onions."], answer: 2, explainAr: "احمرار العينين أثر لنشاط استمر مدة (تقشير البصل)، فنستخدم: have been peeling." },
          { type: "mcq", prompt: "Are the plates clean? Yes, Rachel …", promptAr: "هل الصحون نظيفة؟ نعم، راشيل …", options: ["has done the washing-up.", "has been doing the washing-up.", "does the washing-up.", "has did the washing-up."], answer: 0, explainAr: "السؤال عن النتيجة المكتملة (الصحون نظيفة)، فنستخدم المضارع التام البسيط: has done." },
          { type: "mcq", prompt: "Is the fridge all right now? Yes, Tom …", promptAr: "هل البرّاد على ما يرام الآن؟ نعم، توم …", options: ["has been defrosting it.", "has defrosted it.", "defrosts it.", "is defrosting it."], answer: 1, explainAr: "السؤال عن النتيجة المكتملة (البرّاد جاهز الآن)، فنستخدم: has defrosted it." },
          // Grammar c — Present Perfect Simple or Past Simple
          { type: "fill", prompt: "A: I saw Jack last night. B: Oh really. I ___ him for months. How is he? (not / see)", promptAr: "أ: رأيت جاك الليلة الماضية. ب: أوه حقاً. ___ منذ أشهر. كيف حاله؟", promptArFull: "أ: رأيت جاك الليلة الماضية. ب: أوه حقاً. لم أره منذ أشهر. كيف حاله؟", options: ["didn’t see", "haven’t seen", "don’t see", "hadn’t saw"], answer: 1, explainAr: "(1) for months مدة بدأت في الماضي وما زالت مستمرة حتى الآن، فنستخدم المضارع التام: haven’t seen." },
          { type: "fill", prompt: "A: ___ a competition? (you / ever / win) B: Yes, I won a writing competition in 2006.", promptAr: "أ: ___ في مسابقة؟ ب: نعم، فزت في مسابقة كتابة عام 2006.", promptArFull: "أ: هل سبق أن فزت في مسابقة؟ ب: نعم، فزت في مسابقة كتابة عام 2006.", options: ["Did you ever win", "Have you ever won", "Have you ever win", "Do you ever win"], answer: 1, explainAr: "(2) ever (في أي وقت من حياتك) دون ذكر وقت محدد، فنستخدم المضارع التام: Have you ever won." },
          { type: "fill", prompt: "B: Yes, I ___ a writing competition in 2006. (win)", promptAr: "ب: نعم، ___ في مسابقة كتابة عام 2006.", promptArFull: "ب: نعم، فزت في مسابقة كتابة عام 2006.", options: ["have won", "won", "have been winning"], answer: 1, explainAr: "(3) in 2006 وقت محدد في الماضي، فنستخدم الماضي البسيط: won." },
          { type: "fill", prompt: "A: Is that a new tab? B: Yes, I ___ it. (just / buy)", promptAr: "أ: هل هذا جهاز لوحي جديد؟ ب: نعم، ___ للتو.", promptArFull: "أ: هل هذا جهاز لوحي جديد؟ ب: نعم، اشتريته للتو.", options: ["just bought", "have just bought", "have just buy", "am just buying"], answer: 1, explainAr: "(4) just مع حدث قريب لم نذكر وقته بالتحديد، فنستخدم المضارع التام: have just bought (’ve just bought)." },
          { type: "fill", prompt: "A: How long ___ a computer? (you / use) B: I’ve been using a computer for at least three years.", promptAr: "أ: منذ متى ___ الحاسوب؟ ب: أستخدم الحاسوب منذ ثلاث سنوات على الأقل.", promptArFull: "أ: منذ متى تستخدم الحاسوب؟ ب: أستخدم الحاسوب منذ ثلاث سنوات على الأقل.", options: ["did you use", "have you been using", "do you use", "are you using"], answer: 1, explainAr: "(5) How long عن شيء بدأ في الماضي وما زال مستمراً، فنستخدم المضارع التام (هنا المستمر كما في جواب B: I’ve been using، ويُقبل أيضاً have you used)." },
          { type: "fill", prompt: "A: So, Jack is your best friend. ___ him when you were at university? (you / meet)", promptAr: "أ: إذاً، جاك أعزّ أصدقائك. ___ عندما كنت في الجامعة؟", promptArFull: "أ: إذاً، جاك أعزّ أصدقائك. هل التقيته عندما كنت في الجامعة؟", options: ["Have you met", "Did you meet", "Do you meet", "Have you meet"], answer: 1, explainAr: "(6) when you were at university وقت منتهٍ في الماضي، فنستخدم الماضي البسيط: Did you meet." },
          { type: "fill", prompt: "B: Yes, we ___ friends for more than ten years. (be)", promptAr: "ب: نعم، ___ أصدقاء منذ أكثر من عشر سنوات.", promptArFull: "ب: نعم، نحن أصدقاء منذ أكثر من عشر سنوات.", options: ["were", "have been", "are", "has been"], answer: 1, explainAr: "(7) صداقة بدأت في الماضي وما زالت قائمة الآن (for more than ten years)، فنستخدم المضارع التام: have been." },
          // Grammar d — which form?
          { type: "mcq", prompt: "Which form of the verb do we use for a completed action in the past?", promptAr: "أي صيغة للفعل نستخدم لعمل مكتمل في الماضي؟", options: ["Present Perfect", "Past Simple", "Present Continuous"], answer: 1, explainAr: "(1) الماضي البسيط لعمل انتهى في الماضي: I saw Jack last night." },
          { type: "mcq", prompt: "Which form of the verb do we use for things which started in the past and are true now?", promptAr: "أي صيغة للفعل نستخدم لأشياء بدأت في الماضي وما زالت صحيحة الآن؟", options: ["Past Simple", "Present Simple", "Present Perfect"], answer: 2, explainAr: "(2) المضارع التام: we have been friends for more than ten years." },
          { type: "mcq", prompt: "Which form of the verb do we use for recent actions when we don’t say exactly when?", promptAr: "أي صيغة للفعل نستخدم لأعمال حديثة عندما لا نذكر وقتها بالتحديد؟", options: ["Present Perfect", "Past Simple", "Past Continuous"], answer: 0, explainAr: "(3) المضارع التام: I have just bought it." },
          { type: "mcq", prompt: "Which form of the verb do we use for recent actions when we say exactly when?", promptAr: "أي صيغة للفعل نستخدم لأعمال حديثة عندما نذكر وقتها بالتحديد؟", options: ["Present Perfect", "Present Perfect Continuous", "Past Simple"], answer: 2, explainAr: "(4) الماضي البسيط مع وقت محدد: I saw Jack last night." },
          // Practice in the unit's world
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["We’re thinking it’s great here.", "We think it’s great here.", "We thinks it’s great here.", "We are think it’s great here."], answer: 1, explainAr: "think بمعنى (نرى / نعتقد) فعل حالة، فلا يأتي بالمستمر: We think." },
          { type: "truefalse", prompt: "“How are you geting on, Simon?” is spelt correctly.", promptAr: "الجملة “How are you geting on, Simon?” مكتوبة بتهجئة صحيحة.", answer: false, explainAr: "خطأ: نضاعف t فنكتب getting." },
          { type: "truefalse", prompt: "In “Jane, why are you sweating? Because I have been sweeping the floors.”, we use the Present Perfect Continuous because we can see the result of the activity now.", promptAr: "في “جين، لماذا تتعرّقين؟ لأنني كنت أكنس الأرضيات.” نستخدم المضارع التام المستمر لأننا نرى أثر النشاط الآن.", answer: true, explainAr: "صحيح: التعرّق أثر ظاهر الآن لنشاط استمر مدة." },
          { type: "build", prompt: "رتّب الكلمات: نعم، لقد قصّ جورج العشب.", answer: "Yes, George has cut the grass.", extraWords: ["cutting", "been"] },
          { type: "build", prompt: "رتّب الكلمات: أستخدم الحاسوب منذ ثلاث سنوات على الأقل.", answer: "I’ve been using a computer for at least three years.", extraWords: ["since", "use"] },
        ],
      },
      pronunciation: {
        title: "Homophones",
        ruleAr: "الـ Homophones كلمات لها اللفظ نفسه لكن معانيها وتهجئتها مختلفة، مثل way و weigh (كلتاهما تُلفظ /weɪ/). لا نميّز بينها بالسمع، بل بالمعنى في الجملة: way = طريقة/طريق، و weigh = يزن. ركّز على معنى الجملة لتختار التهجئة الصحيحة.",
        groups: [
          { label: "/weɪ/ — way · weigh", words: ["way (a method)", "weigh (find how heavy)", "Which way should we use to weigh the goods?"] },
          { label: "/ˈweðə/ — whether · weather", words: ["whether (if)", "weather (rain, sun…)", "No one knows whether the weather will be fine tomorrow."] },
          { label: "/rəʊd/ — rode · road", words: ["rode (past of ride)", "road (a street)", "The cyclist rode his bike and set off quickly on the road."] },
          { label: "/sʌn/ — son · sun", words: ["son (a boy child)", "sun (the star in the sky)", "The man is enjoying his time with his son on the beach under the sun."] },
          { label: "/eɪt/ — ate · eight", words: ["ate (past of eat)", "eight (8)", "I only ate a sandwich at eight before I went to bed."] },
          { label: "/raɪt/ — write · right", words: ["write (put words on paper)", "right (correct)", "The teacher asked the students to write down the right answer."] },
          { label: "/baɪ/ — buy · by", words: ["buy (pay for)", "by (near / next to)", "We usually buy our food from a shop by the corner."] },
          { label: "/hɪə/ — here · hear", words: ["here (in this place)", "hear (with your ears)", "I wanted to sit here to be able to hear the speech well."] },
        ],
      },
      everyday: {
        title: "Giving Advice",
        titleAr: "تقديم النصيحة",
        explainAr: "عندما يواجه صديقك أو أحد أقاربك مشكلة نقدّم له النصيحة بعبارات مثل: If I were you (لو كنت مكانك)، You’d better (من الأفضل لك)، You should (يجب عليك)، Try to (حاول أن). والشخص الذي يسمع النصيحة إما أن يقبلها تماماً (That’s true / OK. I can do that / Yes, you’re right) أو يتردّد (Maybe you’re right, but… / I’m not sure…).",
        expressions: [
          { en: "If I were you…", ar: "لو كنتُ مكانك…", note: "Giving advice" },
          { en: "You’d better…", ar: "من الأفضل لك أن…", note: "Giving advice" },
          { en: "You should…", ar: "يجب عليك أن… / ينبغي أن…", note: "Giving advice" },
          { en: "Try to…", ar: "حاول أن…", note: "Giving advice" },
          { en: "Instead of… you can…", ar: "بدلاً من… يمكنك أن…", note: "Giving advice" },
          { en: "That’s true. I haven’t thought about that before.", ar: "هذا صحيح. لم أفكّر في ذلك من قبل.", note: "Accepting the advice completely" },
          { en: "OK. I can do that.", ar: "حسناً. أستطيع فعل ذلك.", note: "Accepting the advice completely" },
          { en: "Yes, you’re right. I’ll do that.", ar: "نعم، أنت محق. سأفعل ذلك.", note: "Accepting the advice completely" },
          { en: "Of course! I should’ve thought about that.", ar: "بالطبع! كان يجب أن أفكّر في ذلك.", note: "Accepting the advice completely" },
          { en: "Maybe you’re right, but…", ar: "ربما أنت محق، لكن…", note: "Hesitating" },
          { en: "Well, you see…", ar: "حسناً، كما ترى…", note: "Hesitating" },
          { en: "I’m not sure. Maybe I could…", ar: "لست متأكداً. ربما أستطيع أن…", note: "Hesitating" },
          { en: "I’m not sure if this is the best thing to do now.", ar: "لست متأكداً إن كان هذا أفضل ما يمكن فعله الآن.", note: "Hesitating" },
        ],
        exercises: [
          { type: "mcq", prompt: "Your friend is a heavy smoker. Which expression gives him advice to quit smoking?", promptAr: "صديقك مدخّن شَرِه. أي عبارة تقدّم له نصيحة بالإقلاع عن التدخين؟", options: ["OK. I can do that.", "You’d better quit smoking.", "Well, you see….", "I’m not sure if this is the best thing to do now."], answer: 1, explainAr: "You’d better (من الأفضل لك) من عبارات تقديم النصيحة، وبعدها الفعل في المصدر بدون to: quit." },
          { type: "mcq", prompt: "Your friend accepts your advice completely. What does he say?", promptAr: "صديقك يقبل نصيحتك تماماً. ماذا يقول؟", options: ["Maybe you’re right, but….", "I’m not sure. Maybe I could….", "Yes, you’re right. I’ll do that.", "Well, you see…."], answer: 2, explainAr: "Yes, you’re right. I’ll do that من عبارات قبول النصيحة تماماً، أما الباقي فللتردّد." },
          { type: "mcq", prompt: "Your cousin is not sure about your advice. What does he say?", promptAr: "ابن عمك غير متأكد من نصيحتك. ماذا يقول؟", options: ["Maybe you’re right, but….", "Of course! I should’ve thought about that.", "OK. I can do that.", "If I were you…."], answer: 0, explainAr: "Maybe you’re right, but… من عبارات التردّد (Hesitating)." },
          { type: "mcq", prompt: "Which expression belongs to “Giving advice”?", promptAr: "أي عبارة تنتمي إلى “تقديم النصيحة”؟", options: ["That’s true. I haven’t thought about that before.", "Instead of… you can…", "I’m not sure. Maybe I could….", "Well, you see…."], answer: 1, explainAr: "Instead of… you can… (بدلاً من… يمكنك…) نقترح بها بديلاً أفضل، فهي نصيحة." },
          { type: "mcq", prompt: "Which expression shows hesitating?", promptAr: "أي عبارة تدل على التردّد؟", options: ["You should….", "Yes, you’re right. I’ll do that.", "I’m not sure if this is the best thing to do now.", "Try to…."], answer: 2, explainAr: "I’m not sure… (لست متأكداً…) تعبّر عن التردّد." },
          { type: "mcq", prompt: "Which expression shows accepting the advice completely?", promptAr: "أي عبارة تدل على قبول النصيحة تماماً؟", options: ["Well, you see….", "Of course! I should’ve thought about that.", "Maybe you’re right, but….", "You’d better…."], answer: 1, explainAr: "Of course! I should’ve thought about that = بالطبع! كان يجب أن أفكّر في ذلك — قبول كامل للنصيحة." },
          { type: "fill", prompt: "If I ___ you, I would quit smoking.", promptAr: "لو ___ مكانك، لأقلعت عن التدخين.", promptArFull: "لو كنتُ مكانك، لأقلعت عن التدخين.", options: ["am", "were", "be"], answer: 1, explainAr: "العبارة الثابتة لتقديم النصيحة هي If I were you (نستخدم were مع I في هذا التعبير)." },
          { type: "fill", prompt: "You’d ___ quit smoking.", promptAr: "من ___ لك أن تُقلع عن التدخين.", promptArFull: "من الأفضل لك أن تُقلع عن التدخين.", options: ["better", "best", "good"], answer: 0, explainAr: "You’d better = You had better (من الأفضل لك)، ويأتي بعدها الفعل في المصدر بدون to." },
          { type: "fill", prompt: "That’s true. I haven’t ___ about that before.", promptAr: "هذا صحيح. لم ___ في ذلك من قبل.", promptArFull: "هذا صحيح. لم أفكّر في ذلك من قبل.", options: ["think", "thinking", "thought"], answer: 2, explainAr: "بعد haven’t (مضارع تام) نستخدم التصريف الثالث: thought." },
          { type: "fill", prompt: "Yes, you’re ___. I’ll do that.", promptAr: "نعم، أنت ___. سأفعل ذلك.", promptArFull: "نعم، أنت محق. سأفعل ذلك.", options: ["right", "write", "wrong"], answer: 0, explainAr: "you’re right = أنت محق (عبارة قبول). وانتبه: write تُلفظ مثلها لكن معناها يكتب." },
          { type: "fill", prompt: "I’m not sure ___ this is the best thing to do now.", promptAr: "لست متأكداً ___ كان هذا أفضل ما يمكن فعله الآن.", promptArFull: "لست متأكداً إن كان هذا أفضل ما يمكن فعله الآن.", options: ["if", "that", "what"], answer: 0, explainAr: "بعد I’m not sure نستخدم if بمعنى (إذا/إن كان) للتعبير عن التردّد." },
          { type: "truefalse", prompt: "“Well, you see….” shows that you accept the advice completely.", promptAr: "العبارة “Well, you see….” تدل على أنك تقبل النصيحة تماماً.", answer: false, explainAr: "خطأ: Well, you see… من عبارات التردّد." },
          { type: "truefalse", prompt: "“You should….” and “Try to….” are used for giving advice.", promptAr: "العبارتان “You should….” و “Try to….” تُستخدمان لتقديم النصيحة.", answer: true, explainAr: "صحيح: كلتاهما في عمود Giving advice." },
        ],
      },
      listening: {
        taskAr: "أجب مع زميلك عن أسئلة عن العمل أو الدراسة لمدة سنة في بلد آخر، ثم استمع إلى مقابلة مع صوفيا (R1.1) وأجب عن الأسئلة، ثم قارن إجاباتك مع زميلك واستمع مرة أخرى للتأكد (الإجابات في التسجيل الصوتي).",
        items: [
          "If you had the chance to spend a year working or studying in another country, which country would you choose? Why?",
          "What things would you like to do there?",
          "What kind of problems do you think you might face?",
          "Why did she choose Damascus?",
          "Why did she want to take a year off?",
          "Who is Salma?",
          "Why does Sofia think Arabic is a difficult language?",
          "How long has Sofia been teaching dancing?",
          "How do her students feel about her?",
          "What does she like most about living in Damascus?",
        ],
      },
      writing: {
        taskAr: "ناقش مع زميلك المقولة: «الحياة مسألة خيارات، وكل خيار تتخذه يصنعك» (جون ماكسويل). ثم اكتب موضوعاً لا يزيد على 100 كلمة تصف فيه الوظيفة التي تريدها بعد التخرّج، وما التحدّيات التي تتوقّع أن تواجهها في مهنتك المستقبلية. اذكر: متطلبات الوظيفة، واحتياجاتك، وتوقّعاتك، ومعتقداتك ومعرفتك. ثم راجع التهجئة والقواعد وعلامات الترقيم وتبادل موضوعك مع زميلك.",
      },
      sentences: [
        "I’d like to work in a company.",
        "I can’t enjoy a job unless it is quite challenging.",
        "I prefer working with other people to working alone.",
        "A position with power and status is attractive to me.",
        "I want a job that allows me to contribute to society.",
        "My main motivation for working is to make money.",
        "Modern societies need professionals in every field.",
        "The rich have to reach out to the poor.",
        "She didn’t really fit in with her workmates in her previous job.",
        "If you run into any trouble, just give me a call.",
        "Because I have been sweeping the floors.",
        "Yes, George has cut the grass.",
        "I’ve been using a computer for at least three years.",
        "Life is a matter of choices, and every choice you make makes you.",
        "Your friend is a heavy smoker.",
      ],
    },
    // @@UNIT2@@
  ],
}
