import type { Module } from '../../engine/types'

export const module3: Module = {
  number: 3,
  title: "Politics",
  titleAr: "السياسة",
  color: "#ce82ff",
  units: [
    // ===================== UNIT 5 — Civil Rights (pages 52–58) =====================
    {
      id: "u5", number: 5, module: 3,
      title: "Civil Rights", titleAr: "الحقوق المدنية", pages: "52–58", emoji: "⚖️",
      planAr: "قراءة نص عن الحقوق المدنية والفرق بينها وبين حقوق الإنسان، مفردات قانونية وتعابير القانون (Law Idioms) مثل break the law و by the book، قواعد جمل الصلة (Relative Clauses: which, that, who, whose, where)، الأصوات المجهورة والمهموسة (Voiced and Voiceless Sounds)، تعابير الشكوى والاعتذار، الاستماع إلى حوار عن المسؤولية، وكتابة مقال عن حقوق الإنسان وواجباته في المجتمع.",
      vocab: [
        { en: "vote", ar: "يصوّت / تصويت", pos: "verb / noun", def: "a formal choice you take in an election", defAr: "اختيار رسمي تقوم به في الانتخابات", example: "Examples of civil rights include the right to vote, the right to a fair trial, the right to government services, the right to a public education, and the right to use public facilities.", exampleAr: "من أمثلة الحقوق المدنية: حق التصويت، والحق في محاكمة عادلة، والحق في الخدمات الحكومية، والحق في التعليم العام، والحق في استخدام المرافق العامة." },
        { en: "guarantee", ar: "يضمن / يكفل", pos: "verb", def: "to give an assurance that something will be done right", defAr: "أن تعطي تأكيداً بأن شيئاً ما سيتم على الوجه الصحيح", example: "They guarantee equal social opportunities and equal protection under the law, regardless of race, religion, or other personal characteristics.", exampleAr: "وهي تضمن تكافؤ الفرص الاجتماعية والحماية المتساوية في ظل القانون، بغضّ النظر عن العِرق أو الدين أو غير ذلك من الصفات الشخصية." },
        { en: "violation", ar: "انتهاك / خرق", pos: "noun", def: "an action that breaks a law, an agreement or a principle", defAr: "فعل يخرق قانوناً أو اتفاقاً أو مبدأً", example: "Civil and political rights are a class of rights that protect individuals' freedom from violation by governments, social organisations, and private individuals.", exampleAr: "الحقوق المدنية والسياسية فئة من الحقوق تحمي حرية الأفراد من الانتهاك من قِبل الحكومات والمنظمات الاجتماعية والأفراد العاديين." },
        { en: "discrimination", ar: "تمييز", pos: "noun", def: "the practice of treating someone less fairly than others", defAr: "معاملة شخص ما بعدل أقل من غيره", example: "They ensure one's right to participate in the civil and political life of society and the state without discrimination or repression.", exampleAr: "وهي تكفل حق المرء في المشاركة في الحياة المدنية والسياسية للمجتمع والدولة دون تمييز أو قمع." },
        { en: "repression", ar: "قمع", pos: "noun", def: "using force to control a group of people and restrict their freedom", defAr: "استخدام القوة للسيطرة على مجموعة من الناس وتقييد حريتهم", example: "They ensure one's right to participate in the civil and political life of society and the state without discrimination or repression.", exampleAr: "وهي تكفل حق المرء في المشاركة في الحياة المدنية والسياسية للمجتمع والدولة دون تمييز أو قمع." },
        { en: "restraints", ar: "قيود", pos: "noun", def: "rules which limit what people can do", defAr: "قواعد تحدّ مما يستطيع الناس فعله", example: "In contrast to civil liberties, which are freedoms that are secured by placing restraints on government, civil rights are secured by positive government action, often in the form of legislation.", exampleAr: "على عكس الحريات المدنية، وهي حريات تُصان بفرض قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي، غالباً في صورة تشريعات." },
        { en: "trial", ar: "محاكمة", pos: "noun", def: "a legal process to decide if somebody is guilty or not", defAr: "إجراء قانوني لتقرير ما إذا كان شخص ما مذنباً أم لا", example: "Examples of civil rights include the right to vote, the right to a fair trial, the right to government services, the right to a public education, and the right to use public facilities.", exampleAr: "من أمثلة الحقوق المدنية: حق التصويت، والحق في محاكمة عادلة، والحق في الخدمات الحكومية، والحق في التعليم العام، والحق في استخدام المرافق العامة." },
        { en: "deny", ar: "ينكر / يحرم من", pos: "verb", def: "to say that something isn't true", defAr: "أن تقول إن شيئاً ما ليس صحيحاً", example: "Civil rights are an essential component of democracy; when individuals are prevented from participating in political society, their civil rights are being denied.", exampleAr: "الحقوق المدنية عنصر أساسي من عناصر الديمقراطية؛ فعندما يُمنع الأفراد من المشاركة في المجتمع السياسي، فإن حقوقهم المدنية تُسلب منهم." },
        { en: "legislation", ar: "تشريع / قوانين", pos: "noun", def: "a law or set of laws", defAr: "قانون أو مجموعة من القوانين", example: "In contrast to civil liberties, which are freedoms that are secured by placing restraints on government, civil rights are secured by positive government action, often in the form of legislation.", exampleAr: "على عكس الحريات المدنية، وهي حريات تُصان بفرض قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي، غالباً في صورة تشريعات." },
        { en: "acquire", ar: "يكتسب", pos: "verb", def: "to get or gain something", defAr: "أن تحصل على شيء أو تكسبه", example: "Simply speaking, human rights are the rights which one acquires by being alive, while civil rights are the rights that one obtains by being a legal member of a certain political life.", exampleAr: "ببساطة، حقوق الإنسان هي الحقوق التي يكتسبها المرء لمجرد كونه حياً، بينما الحقوق المدنية هي الحقوق التي يحصل عليها المرء بكونه عضواً قانونياً في حياة سياسية معيّنة." },
        { en: "obtain", ar: "يحصل على", pos: "verb", def: "to get something", defAr: "أن تحصل على شيء", example: "Simply speaking, human rights are the rights which one acquires by being alive, while civil rights are the rights that one obtains by being a legal member of a certain political life.", exampleAr: "ببساطة، حقوق الإنسان هي الحقوق التي يكتسبها المرء لمجرد كونه حياً، بينما الحقوق المدنية هي الحقوق التي يحصل عليها المرء بكونه عضواً قانونياً في حياة سياسية معيّنة." },
        { en: "citizen", ar: "مواطن", pos: "noun", def: "a person who legally belongs to a country", defAr: "شخص ينتمي قانونياً إلى بلد ما", example: "In other words, civil rights are the rights of citizens to political and social freedom and equality.", exampleAr: "وبعبارة أخرى، الحقوق المدنية هي حقوق المواطنين في الحرية والمساواة السياسية والاجتماعية." },
        { en: "equality", ar: "مساواة", pos: "noun", def: "the state of being equal, with the same rights and chances", defAr: "أن يكون الناس متساوين في الحقوق والفرص", example: "In other words, civil rights are the rights of citizens to political and social freedom and equality.", exampleAr: "وبعبارة أخرى، الحقوق المدنية هي حقوق المواطنين في الحرية والمساواة السياسية والاجتماعية." },
        { en: "protection", ar: "حماية", pos: "noun", def: "keeping someone or something safe from harm", defAr: "حفظ شخص أو شيء من الأذى", example: "They guarantee equal social opportunities and equal protection under the law, regardless of race, religion, or other personal characteristics.", exampleAr: "وهي تضمن تكافؤ الفرص الاجتماعية والحماية المتساوية في ظل القانون، بغضّ النظر عن العِرق أو الدين أو غير ذلك من الصفات الشخصية." },
        { en: "regardless of", ar: "بغضّ النظر عن", pos: "preposition", def: "without being affected by something", defAr: "دون أن يتأثر بشيء ما", example: "They guarantee equal social opportunities and equal protection under the law, regardless of race, religion, or other personal characteristics.", exampleAr: "وهي تضمن تكافؤ الفرص الاجتماعية والحماية المتساوية في ظل القانون، بغضّ النظر عن العِرق أو الدين أو غير ذلك من الصفات الشخصية." },
        { en: "characteristic", ar: "صفة / سمة", pos: "noun", def: "a quality that belongs to a person and makes him different", defAr: "صفة تخص شخصاً وتميّزه عن غيره", example: "Civil rights laws attempt to guarantee full and equal citizenship for people who have traditionally been discriminated against on the basis of some characteristics.", exampleAr: "تسعى قوانين الحقوق المدنية إلى ضمان المواطنة الكاملة والمتساوية للأشخاص الذين تعرّضوا تاريخياً للتمييز على أساس بعض الصفات." },
        { en: "participate", ar: "يشارك", pos: "verb", def: "to take part in something", defAr: "أن تشارك في شيء ما", example: "They ensure one's right to participate in the civil and political life of society and the state without discrimination or repression.", exampleAr: "وهي تكفل حق المرء في المشاركة في الحياة المدنية والسياسية للمجتمع والدولة دون تمييز أو قمع." },
        { en: "inherently", ar: "بالفطرة / أصلاً", pos: "adverb", def: "as a natural part of something", defAr: "بوصفه جزءاً طبيعياً من الشيء", example: "Unlike other rights concepts, such as human rights or natural rights, in which people acquire rights inherently from God, civil rights must be given and guaranteed by the power of the state.", exampleAr: "على خلاف مفاهيم الحقوق الأخرى، مثل حقوق الإنسان أو الحقوق الطبيعية، التي يكتسب فيها الناس حقوقهم بالفطرة من الله، فإن الحقوق المدنية يجب أن تمنحها سلطة الدولة وتضمنها." },
        { en: "essential", ar: "أساسي / ضروري", pos: "adjective", def: "very important and necessary", defAr: "مهم جداً وضروري", example: "Civil rights are an essential component of democracy; when individuals are prevented from participating in political society, their civil rights are being denied.", exampleAr: "الحقوق المدنية عنصر أساسي من عناصر الديمقراطية؛ فعندما يُمنع الأفراد من المشاركة في المجتمع السياسي، فإن حقوقهم المدنية تُسلب منهم." },
        { en: "component", ar: "عنصر / مكوّن", pos: "noun", def: "one of the parts of something", defAr: "أحد أجزاء الشيء", example: "Civil rights are an essential component of democracy; when individuals are prevented from participating in political society, their civil rights are being denied.", exampleAr: "الحقوق المدنية عنصر أساسي من عناصر الديمقراطية؛ فعندما يُمنع الأفراد من المشاركة في المجتمع السياسي، فإن حقوقهم المدنية تُسلب منهم." },
        { en: "democracy", ar: "ديمقراطية", pos: "noun", def: "a system in which the people choose their government by voting", defAr: "نظام يختار فيه الشعب حكومته بالتصويت", example: "Civil rights are an essential component of democracy; when individuals are prevented from participating in political society, their civil rights are being denied.", exampleAr: "الحقوق المدنية عنصر أساسي من عناصر الديمقراطية؛ فعندما يُمنع الأفراد من المشاركة في المجتمع السياسي، فإن حقوقهم المدنية تُسلب منهم." },
        { en: "civil liberties", ar: "الحريات المدنية", pos: "noun", def: "freedoms that are secured by placing restraints on government", defAr: "حريات تُصان بفرض قيود على الحكومة", example: "In contrast to civil liberties, which are freedoms that are secured by placing restraints on government, civil rights are secured by positive government action, often in the form of legislation.", exampleAr: "على عكس الحريات المدنية، وهي حريات تُصان بفرض قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي، غالباً في صورة تشريعات." },
        { en: "secure", ar: "يصون / يؤمّن", pos: "verb", def: "to make something safe and certain", defAr: "أن تجعل شيئاً آمناً ومضموناً", example: "In contrast to civil liberties, which are freedoms that are secured by placing restraints on government, civil rights are secured by positive government action, often in the form of legislation.", exampleAr: "على عكس الحريات المدنية، وهي حريات تُصان بفرض قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي، غالباً في صورة تشريعات." },
        { en: "citizenship", ar: "المواطنة / الجنسية", pos: "noun", def: "the legal right to belong to a country", defAr: "الحق القانوني في الانتماء إلى بلد ما", example: "Civil rights laws attempt to guarantee full and equal citizenship for people who have traditionally been discriminated against on the basis of some characteristics.", exampleAr: "تسعى قوانين الحقوق المدنية إلى ضمان المواطنة الكاملة والمتساوية للأشخاص الذين تعرّضوا تاريخياً للتمييز على أساس بعض الصفات." },
        { en: "discriminate against", ar: "يميّز ضد", pos: "verb", def: "to treat someone less fairly than others", defAr: "أن تعامل شخصاً بعدل أقل من غيره", example: "Civil rights laws attempt to guarantee full and equal citizenship for people who have traditionally been discriminated against on the basis of some characteristics.", exampleAr: "تسعى قوانين الحقوق المدنية إلى ضمان المواطنة الكاملة والمتساوية للأشخاص الذين تعرّضوا تاريخياً للتمييز على أساس بعض الصفات." },
        { en: "public facilities", ar: "المرافق العامة", pos: "noun", def: "buildings and services that everyone can use, such as parks and hospitals", defAr: "مبانٍ وخدمات يستطيع الجميع استخدامها، مثل الحدائق والمستشفيات", example: "Examples of civil rights include the right to vote, the right to a fair trial, the right to government services, the right to a public education, and the right to use public facilities.", exampleAr: "من أمثلة الحقوق المدنية: حق التصويت، والحق في محاكمة عادلة، والحق في الخدمات الحكومية، والحق في التعليم العام، والحق في استخدام المرافق العامة." },
        { en: "society", ar: "مجتمع", pos: "noun", def: "people living together in a community", defAr: "أناس يعيشون معاً في جماعة واحدة", example: "What duties should people do in society?", exampleAr: "ما الواجبات التي يجب على الناس القيام بها في المجتمع؟" },
        { en: "duty", ar: "واجب", pos: "noun", def: "something you must do because it is right or the law says so", defAr: "شيء يجب أن تفعله لأنه صواب أو لأن القانون يفرضه", example: "What duties should people do in society?", exampleAr: "ما الواجبات التي يجب على الناس القيام بها في المجتمع؟" },
        { en: "obligation", ar: "التزام / واجب", pos: "noun", def: "something that you must do", defAr: "شيء يجب عليك فعله" },
        { en: "responsibility", ar: "مسؤولية", pos: "noun", def: "a duty to take care of something or do something", defAr: "واجب الاعتناء بشيء أو القيام بعمل ما" },
        { en: "standard", ar: "معيار / مستوى", pos: "noun", def: "a level of quality", defAr: "مستوى من الجودة" },
        { en: "beat around / about the bush", ar: "يلفّ ويدور / يراوغ", pos: "idiom", def: "to hesitate in getting to the point", defAr: "أن تتردد في الدخول إلى صلب الموضوع" },
        { en: "an act of God", ar: "قضاء وقدر / كارثة طبيعية", pos: "idiom", def: "the will of God; something natural that nobody can control", defAr: "مشيئة الله؛ أمر طبيعي لا يستطيع أحد التحكم فيه" },
        { en: "break the law", ar: "يخالف القانون", pos: "idiom", def: "to act against the law", defAr: "أن تتصرف بما يخالف القانون" },
        { en: "assemble the case", ar: "يجمع أدلة القضية", pos: "idiom", def: "to collect data against someone", defAr: "أن تجمع معلومات وأدلة ضد شخص ما" },
        { en: "by the book", ar: "حسب الأصول / وفق القواعد", pos: "idiom", def: "exactly as the rules say", defAr: "تماماً كما تقول القواعد" },
        { en: "complaint", ar: "شكوى", pos: "noun", def: "a statement that something is wrong or not good enough", defAr: "قول إن شيئاً ما خاطئ أو غير مقبول", example: "I’m afraid I have a complaint to make.", exampleAr: "أخشى أن لديّ شكوى أريد تقديمها." },
        { en: "apologise", ar: "يعتذر", pos: "verb", def: "to say that you are sorry", defAr: "أن تقول إنك آسف", example: "Ah. Well, I must apologise, madam.", exampleAr: "آه. حسناً، يجب أن أعتذر يا سيدتي." },
        { en: "inconvenient", ar: "مزعج / غير مناسب", pos: "adjective", def: "causing trouble or problems", defAr: "يسبّب المتاعب أو المشكلات", example: "It’s very inconvenient.", exampleAr: "هذا مزعج جداً." },
        { en: "assure", ar: "يؤكّد لـ / يطمئن", pos: "verb", def: "to tell someone that something is certainly true", defAr: "أن تقول لشخص إن شيئاً ما صحيح بالتأكيد", example: "I assure you it won’t happen again.", exampleAr: "أؤكد لك أن ذلك لن يتكرر." },
        { en: "drill", ar: "مِثقب", pos: "noun", def: "a tool which is used to make a hole in something", defAr: "أداة تُستخدم لعمل ثقب في شيء ما", example: "A drill is a tool which is used to make a hole in something.", exampleAr: "المِثقب أداة تُستخدم لعمل ثقب في شيء ما." },
        { en: "photocopier", ar: "آلة تصوير المستندات", pos: "noun", def: "a machine which makes copies of documents", defAr: "آلة تصنع نسخاً من الوثائق" },
        { en: "bodyguard", ar: "حارس شخصي", pos: "noun", def: "a person who protects important people from being attacked", defAr: "شخص يحمي الأشخاص المهمّين من التعرّض للاعتداء" },
        { en: "launderette", ar: "مغسلة ملابس عامة", pos: "noun", def: "a place with washing machines where you can wash your clothes", defAr: "مكان فيه غسالات تستطيع أن تغسل فيه ملابسك" },
        { en: "plumber", ar: "سبّاك / مصلّح أدوات صحية", pos: "noun", def: "a person whose job is to mend central heating, taps, etc.", defAr: "شخص عمله إصلاح التدفئة المركزية والصنابير وغيرها" },
        { en: "vacuum cleaner", ar: "مكنسة كهربائية", pos: "noun", def: "a machine which you use to clean floors and carpets", defAr: "آلة تستخدمها لتنظيف الأرضيات والسجاد" },
      ],
      reading: {
        title: "Civil Rights",
        paragraphs: [
          "Simply speaking, human rights are the rights which one acquires by being alive, while civil rights are the rights that one obtains by being a legal member of a certain political life. In other words, civil rights are the rights of citizens to political and social freedom and equality. They guarantee equal social opportunities and equal protection under the law, regardless of race, religion, or other personal characteristics.",
          "Civil and political rights are a class of rights that protect individuals' freedom from violation by governments, social organisations, and private individuals. They ensure one's right to participate in the civil and political life of society and the state without discrimination or repression. Unlike other rights concepts, such as human rights or natural rights, in which people acquire rights inherently from God, civil rights must be given and guaranteed by the power of the state.",
          "Examples of civil rights include the right to vote, the right to a fair trial, the right to government services, the right to a public education, and the right to use public facilities.",
          "Civil rights are an essential component of democracy; when individuals are prevented from participating in political society, their civil rights are being denied. In contrast to civil liberties, which are freedoms that are secured by placing restraints on government, civil rights are secured by positive government action, often in the form of legislation. Civil rights laws attempt to guarantee full and equal citizenship for people who have traditionally been discriminated against on the basis of some characteristics.",
        ],
        paragraphsAr: [
          "ببساطة، حقوق الإنسان هي الحقوق التي يكتسبها المرء لمجرد كونه حياً، بينما الحقوق المدنية هي الحقوق التي يحصل عليها المرء بكونه عضواً قانونياً في حياة سياسية معيّنة. وبعبارة أخرى، الحقوق المدنية هي حقوق المواطنين في الحرية والمساواة السياسية والاجتماعية. وهي تضمن تكافؤ الفرص الاجتماعية والحماية المتساوية في ظل القانون، بغضّ النظر عن العِرق أو الدين أو غير ذلك من الصفات الشخصية.",
          "الحقوق المدنية والسياسية فئة من الحقوق تحمي حرية الأفراد من الانتهاك من قِبل الحكومات والمنظمات الاجتماعية والأفراد العاديين. وهي تكفل حق المرء في المشاركة في الحياة المدنية والسياسية للمجتمع والدولة دون تمييز أو قمع. وعلى خلاف مفاهيم الحقوق الأخرى، مثل حقوق الإنسان أو الحقوق الطبيعية، التي يكتسب فيها الناس حقوقهم بالفطرة من الله، فإن الحقوق المدنية يجب أن تمنحها سلطة الدولة وتضمنها.",
          "ومن أمثلة الحقوق المدنية: حق التصويت، والحق في محاكمة عادلة، والحق في الخدمات الحكومية، والحق في التعليم العام، والحق في استخدام المرافق العامة.",
          "الحقوق المدنية عنصر أساسي من عناصر الديمقراطية؛ فعندما يُمنع الأفراد من المشاركة في المجتمع السياسي، فإن حقوقهم المدنية تُسلب منهم. وعلى عكس الحريات المدنية، وهي حريات تُصان بفرض قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي، غالباً في صورة تشريعات. وتسعى قوانين الحقوق المدنية إلى ضمان المواطنة الكاملة والمتساوية للأشخاص الذين تعرّضوا تاريخياً للتمييز على أساس بعض الصفات.",
        ],
        questions: [
          { q: "Human rights are guaranteed to each individual in society ___.", qAr: "حقوق الإنسان مضمونة لكل فرد في المجتمع ___.",
            options: ["after death", "during lifetime", "after the age of 18", "after becoming a legal member of political life"],
            answer: 1, explainAr: "التمرين a (1) من الكتاب: الإجابة b. النص يقول: human rights are the rights which one acquires by being alive — أي يكتسبها المرء لمجرد أنه حيّ، فهي طوال حياته." },
          { q: "In comparison with civil rights, human rights ___.", qAr: "بالمقارنة مع الحقوق المدنية، فإن حقوق الإنسان ___.",
            options: ["are given to individuals by the government", "are secured by placing restraints on government", "are given by God", "are freedoms made by the individuals themselves"],
            answer: 2, explainAr: "التمرين a (2) من الكتاب: الإجابة b. النص يقول: human rights or natural rights, in which people acquire rights inherently from God — أما الحقوق المدنية فتمنحها الدولة." },
          { q: "The right to use public facilities is an example of a ___.", qAr: "الحق في استخدام المرافق العامة مثال على ___.",
            options: ["human right", "civil liberty", "natural right", "civil right"],
            answer: 3, explainAr: "التمرين a (3) من الكتاب: الإجابة c. الفقرة الثالثة: Examples of civil rights include ... the right to use public facilities." },
          { q: "It is ___ to prevent people from participating in political life.", qAr: "من ___ منع الناس من المشاركة في الحياة السياسية.",
            options: ["urgent", "legal", "illegal", "essential"],
            answer: 2, explainAr: "التمرين a (4) من الكتاب: الإجابة c. منع الأفراد من المشاركة في الحياة السياسية يعني سلب حقوقهم المدنية التي يضمنها القانون، فهو غير قانوني." },
          { q: "Legislations are formed by the government to ___ that people enjoy their civil rights.", qAr: "تضع الحكومة التشريعات لكي ___ أن يتمتع الناس بحقوقهم المدنية.",
            options: ["assure", "ignore", "protect", "deny"],
            answer: 0, explainAr: "التمرين a (5) من الكتاب: الإجابة a. assure that = يضمن / يتأكد أن. الفعل protect لا يأتي بعده that، و ignore (يتجاهل) و deny (يحرم) عكس المعنى." },
          { q: "What do civil rights guarantee?", qAr: "ماذا تضمن الحقوق المدنية؟",
            options: ["Freedom from paying taxes", "Equal social opportunities and equal protection under the law", "Rights that people acquire only from their families", "Special rights for rich people"],
            answer: 1, explainAr: "النص يقول: They guarantee equal social opportunities and equal protection under the law." },
          { q: "How are civil rights secured, in contrast to civil liberties?", qAr: "كيف تُصان الحقوق المدنية، على عكس الحريات المدنية؟",
            options: ["By placing restraints on government", "By private individuals only", "By positive government action, often in the form of legislation", "By social organisations only"],
            answer: 2, explainAr: "النص يقول: civil rights are secured by positive government action, often in the form of legislation. أما الحريات المدنية فتُصان بفرض قيود على الحكومة." },
          { q: "Who do civil rights laws attempt to guarantee full and equal citizenship for?", qAr: "لمن تسعى قوانين الحقوق المدنية إلى ضمان المواطنة الكاملة والمتساوية؟",
            options: ["For people who have traditionally been discriminated against", "For government leaders only", "For people who break the law", "For foreign visitors only"],
            answer: 0, explainAr: "النص يقول: for people who have traditionally been discriminated against on the basis of some characteristics." },
        ],
        trueFalse: [
          { statement: "Civil rights must be given and guaranteed by the power of the state.", answer: true },
          { statement: "Human rights are the rights that one obtains by being a legal member of a certain political life.", answer: false },
          { statement: "The right to a fair trial is an example of civil rights.", answer: true },
          { statement: "Civil liberties are secured by positive government action.", answer: false },
          { statement: "Civil rights are an essential component of democracy.", answer: true },
        ],
      },
      vocabFocus: {
        name: "Law Idioms", nameAr: "تعابير القانون",
        ruleEn: [
          "Law idioms: beat around / about the bush, an act of God, break the law, assemble the case, by the book.",
          "beat around / about the bush = hesitate in getting to the point.",
          "an act of God = the will of God (something natural like a forest fire that nobody can control).",
          "break the law = act against the law; assemble the case = collect data against somebody.",
          "by the book = exactly as the rules say.",
          "Use the correct form of the idiom in the sentence: he had broken the law (past perfect).",
        ],
        ruleAr: [
          "التعابير الاصطلاحية لا تُترجم كلمة كلمة، بل نحفظ معناها كاملاً.",
          "beat around / about the bush = يلفّ ويدور ولا يدخل في صلب الموضوع (يتردد في قول ما يريد مباشرة).",
          "an act of God = قضاء وقدر، أي أمر طبيعي لا يد لأحد فيه مثل حريق غابة أو زلزال.",
          "break the law = يخالف القانون، و assemble the case = يجمع الأدلة والمعلومات ضد شخص في قضية.",
          "by the book = حسب الأصول، تماماً كما تقول القواعد والأنظمة.",
          "انتبه لتصريف الفعل داخل التعبير حسب زمن الجملة: had broken the law (ماضٍ تام)، broke the law (ماضٍ بسيط).",
          "ويتدرّب هذا القسم أيضاً على كلمات النص القانونية وأضدادها (alive ↔ dead، fair ↔ unjust، denied ↔ admitted...).",
        ],
        examples: [
          "You should speak directly and ask for a raise.",
          "The lawyers were unable to collect data against the man.",
          "Our lawyer is very good and he does every thing exactly as the rules say.",
        ],
        exercises: [
          // Book: Law idioms — replace the underlined phrases
          { type: "fill", prompt: "You should speak directly and ask for a raise. Don't ___. (hesitate in getting to the point)", promptAr: "يجب أن تتحدث بصراحة وتطلب زيادة في الراتب. لا ___ (تتردد في الدخول إلى صلب الموضوع).", promptArFull: "يجب أن تتحدث بصراحة وتطلب زيادة في الراتب. لا تلفّ وتدُر حول الموضوع.", options: ["break the law", "beat around the bush", "go by the book", "assemble the case"], answer: 1, explainAr: "beat around / about the bush = يتردد في الدخول إلى صلب الموضوع، وهذا عكس speak directly (تحدّث بصراحة)." },
          { type: "fill", prompt: "The insurance company refused to pay the money because they said that the forest fire was ___. (the will of God)", promptAr: "رفضت شركة التأمين دفع المال لأنها قالت إن حريق الغابة كان ___ (مشيئة الله).", promptArFull: "رفضت شركة التأمين دفع المال لأنها قالت إن حريق الغابة كان قضاءً وقدراً.", options: ["by the book", "an act of God", "beat around the bush", "assemble the case"], answer: 1, explainAr: "an act of God = مشيئة الله، أي حادثة طبيعية لا يتحمّل أحد مسؤوليتها، لذلك رفضت شركة التأمين الدفع." },
          { type: "fill", prompt: "The lawyers were unable to ___ against the man. (collect data)", promptAr: "لم يتمكن المحامون من ___ ضد الرجل (جمع المعلومات).", promptArFull: "لم يتمكن المحامون من جمع أدلة القضية ضد الرجل.", options: ["break the law", "beat about the bush", "assemble the case", "an act of God"], answer: 2, explainAr: "assemble the case = يجمع المعلومات والأدلة ضد شخص ما. وبعد to نستخدم المصدر assemble." },
          { type: "fill", prompt: "The man was forced to quit his job after it was discovered that he had ___. (acted against the law)", promptAr: "أُجبر الرجل على ترك عمله بعد أن اكتُشف أنه ___ (تصرّف ضد القانون).", promptArFull: "أُجبر الرجل على ترك عمله بعد أن اكتُشف أنه قد خالف القانون.", options: ["break the law", "broke the law", "assembled the case", "broken the law"], answer: 3, explainAr: "break the law = يخالف القانون. وبعد had نحتاج التصريف الثالث (الماضي التام): had broken the law." },
          { type: "fill", prompt: "Our lawyer is very good and he does everything ___. (exactly as the rules say)", promptAr: "محامينا جيد جداً ويفعل كل شيء ___ (تماماً كما تقول القواعد).", promptArFull: "محامينا جيد جداً ويفعل كل شيء حسب الأصول.", options: ["by the book", "an act of God", "break the law", "beat around the bush"], answer: 0, explainAr: "by the book = تماماً كما تقول القواعد، حسب الأصول." },
          // More practice on the idioms
          { type: "mcq", prompt: "“by the book” means:", promptAr: "التعبير “by the book” يعني:", options: ["against the law", "the will of God", "exactly as the rules say", "collecting data"], answer: 2, explainAr: "by the book = exactly as the rules say (حسب الأصول والقواعد)." },
          { type: "mcq", prompt: "“beat around / about the bush” means:", promptAr: "التعبير “beat around / about the bush” يعني:", options: ["hesitate in getting to the point", "act against the law", "speak directly", "collect data against someone"], answer: 0, explainAr: "beat around the bush = يلفّ ويدور ويتردد في قول الشيء المهم مباشرة، وهو عكس speak directly." },
          { type: "mcq", prompt: "Which idiom means “the will of God”, for example a forest fire that nobody caused?", promptAr: "أي تعبير يعني “مشيئة الله”، مثل حريق غابة لم يتسبب به أحد؟", options: ["break the law", "by the book", "assemble the case", "an act of God"], answer: 3, explainAr: "an act of God = قضاء وقدر، حدث طبيعي لا يد للإنسان فيه." },
          { type: "truefalse", prompt: "“break the law” means “to act against the law”.", promptAr: "التعبير “break the law” يعني “أن يتصرف ضد القانون”.", answer: true, explainAr: "صحيح: break the law = يخالف القانون، كما في جملة الكتاب: he had acted against the law." },
          // Reading b — opposites from the text
          { type: "fill", prompt: "Find the opposite in the text: dead ≠ ___", promptAr: "جد الضدّ في النص: ميت ≠ ___", promptArFull: "جد الضدّ في النص: ميت ≠ حيّ", options: ["alive", "natural", "equal", "positive"], answer: 0, explainAr: "في النص: the rights which one acquires by being alive. عكس dead (ميت) هو alive (حيّ)." },
          { type: "fill", prompt: "Find the opposite in the text: artificial ≠ ___", promptAr: "جد الضدّ في النص: اصطناعي ≠ ___", promptArFull: "جد الضدّ في النص: اصطناعي ≠ طبيعي", options: ["political", "natural", "public", "legal"], answer: 1, explainAr: "في النص: human rights or natural rights. عكس artificial (اصطناعي) هو natural (طبيعي)." },
          { type: "fill", prompt: "Find the opposite in the text: unjust ≠ ___", promptAr: "جد الضدّ في النص: ظالم / غير عادل ≠ ___", promptArFull: "جد الضدّ في النص: ظالم / غير عادل ≠ عادل", options: ["full", "equal", "fair", "positive"], answer: 2, explainAr: "في النص: the right to a fair trial. عكس unjust (غير عادل) هو fair (عادل)." },
          { type: "fill", prompt: "Find the opposite in the text: allowed ≠ ___", promptAr: "جد الضدّ في النص: مسموح له ≠ ___", promptArFull: "جد الضدّ في النص: مسموح له ≠ ممنوع", options: ["guaranteed", "secured", "given", "prevented"], answer: 3, explainAr: "في النص: when individuals are prevented from participating. عكس allowed (مسموح) هو prevented (ممنوع)." },
          { type: "fill", prompt: "Find the opposite in the text: admitted ≠ ___", promptAr: "جد الضدّ في النص: مُعترَف به ≠ ___", promptArFull: "جد الضدّ في النص: مُعترَف به ≠ مُنكَر", options: ["denied", "obtained", "acquired", "protected"], answer: 0, explainAr: "في النص: their civil rights are being denied. عكس admitted (أقرّ / اعترف) هو denied (أنكر)." },
          { type: "fill", prompt: "Find the opposite in the text: negative ≠ ___", promptAr: "جد الضدّ في النص: سلبي ≠ ___", promptArFull: "جد الضدّ في النص: سلبي ≠ إيجابي", options: ["essential", "positive", "equal", "social"], answer: 1, explainAr: "في النص: civil rights are secured by positive government action. عكس negative (سلبي) هو positive (إيجابي)." },
          // Reading c — fill in the paragraph
          { type: "fill", prompt: "The right to education includes a ___ to provide basic education for individuals.", promptAr: "يتضمن الحق في التعليم ___ بتوفير التعليم الأساسي للأفراد.", promptArFull: "يتضمن الحق في التعليم مسؤوليةً بتوفير التعليم الأساسي للأفراد.", options: ["standards", "responsibility", "addition", "obligations"], answer: 1, explainAr: "بعد a نحتاج اسماً مفرداً، والمعنى: مسؤولية توفير التعليم = responsibility. أما obligations و standards فجمع." },
          { type: "fill", prompt: "... for individuals who have not ___ primary education from the school and college levels.", promptAr: "... للأفراد الذين لم ___ التعليم الابتدائي من مستويات المدرسة والكلية.", promptArFull: "... للأفراد الذين لم يُكملوا التعليم الابتدائي من مستويات المدرسة والكلية.", options: ["addition", "standards", "completed", "responsibility"], answer: 2, explainAr: "بعد have not نحتاج التصريف الثالث للفعل (مضارع تام): have not completed = لم يُكملوا." },
          { type: "fill", prompt: "In ___ to this access to education necessities, the right to education includes the obligations of the students.", promptAr: "___ إلى هذا الوصول إلى ضروريات التعليم، يتضمن الحق في التعليم التزامات الطلاب.", promptArFull: "بالإضافة إلى هذا الوصول إلى ضروريات التعليم، يتضمن الحق في التعليم التزامات الطلاب.", options: ["addition", "obligations", "completed", "standards"], answer: 0, explainAr: "In addition to = بالإضافة إلى، تعبير ثابت." },
          { type: "fill", prompt: "The right to education includes the ___ of the students to avoid discrimination at all levels of the educational system.", promptAr: "يتضمن الحق في التعليم ___ الطلاب بتجنّب التمييز في جميع مستويات النظام التعليمي.", promptArFull: "يتضمن الحق في التعليم التزامات الطلاب بتجنّب التمييز في جميع مستويات النظام التعليمي.", options: ["addition", "completed", "standards", "obligations"], answer: 3, explainAr: "obligations = التزامات / واجبات، وهي ما يجب على الطلاب فعله: تجنّب التمييز." },
          { type: "fill", prompt: "... to set minimum ___ of education and to improve its quality.", promptAr: "... ولوضع حدّ أدنى من ___ التعليم وتحسين جودته.", promptArFull: "... ولوضع حدّ أدنى من معايير التعليم وتحسين جودته.", options: ["obligations", "standards", "addition", "responsibility"], answer: 1, explainAr: "minimum standards = الحدّ الأدنى من المعايير / المستويات، وهي تناسب to improve its quality (تحسين الجودة)." },
          // Preview b — law words and their meanings
          { type: "mcq", prompt: "“trial” means:", promptAr: "كلمة “trial” تعني:", options: ["a law or set of laws", "a legal process to decide if somebody is guilty or not", "a formal choice you take in an election", "rules which limit what people can do"], answer: 1, explainAr: "trial = محاكمة، إجراء قانوني لتقرير إن كان الشخص مذنباً أم لا." },
          { type: "mcq", prompt: "“legislation” means:", promptAr: "كلمة “legislation” تعني:", options: ["a law or set of laws", "an action that breaks a law", "to say that something isn't true", "the practice of treating someone less fairly than others"], answer: 0, explainAr: "legislation = تشريع، قانون أو مجموعة قوانين." },
          { type: "mcq", prompt: "“repression” means:", promptAr: "كلمة “repression” تعني:", options: ["a formal choice you take in an election", "to give an assurance that something will be done right", "using force to control a group of people and restrict their freedom", "a law or set of laws"], answer: 2, explainAr: "repression = قمع، استخدام القوة للسيطرة على الناس وتقييد حريتهم." },
          { type: "mcq", prompt: "“violation” means:", promptAr: "كلمة “violation” تعني:", options: ["rules which limit what people can do", "a legal process to decide if somebody is guilty", "to say that something isn't true", "an action that breaks a law, an agreement or a principle"], answer: 3, explainAr: "violation = انتهاك، فعل يخرق قانوناً أو اتفاقاً أو مبدأً." },
          { type: "mcq", prompt: "“guarantee” means:", promptAr: "كلمة “guarantee” تعني:", options: ["to give an assurance that something will be done right", "to say that something isn't true", "using force to control people", "the practice of treating someone less fairly than others"], answer: 0, explainAr: "guarantee = يضمن، يعطي تأكيداً بأن الشيء سيتم على الوجه الصحيح." },
        ],
      },
      grammar: {
        name: "Relative Clauses", nameAr: "جمل الصلة (الضمائر الموصولة)",
        ruleEn: [
          "Relative clauses tell you which thing, person or place we are talking about.",
          "Relative clauses tell you what a thing, person or place is or does.",
          "Use which or that for things. (A drill is a tool which is used to make a hole in something. Mobile phones are phones that you can carry around in your pocket.)",
          "Use who or that for people. (The man who worked in a printing company visited me last night.)",
          "Use where for places. (Lattakia, where I spent my last holiday, is a wonderful city.)",
          "Use whose for possession. (The woman whose car was stolen called the police.)",
        ],
        ruleAr: [
          "جملة الصلة تخبرنا عن أي شيء أو شخص أو مكان نتحدث، أو ماذا يكون هذا الشيء أو الشخص أو المكان وماذا يفعل.",
          "which أو that للأشياء (التي / الذي لغير العاقل): A drill is a tool which is used to make a hole.",
          "who أو that للأشخاص (الذي / التي للعاقل): The man who worked in a printing company visited me.",
          "where للأماكن (حيث / الذي فيه): Lattakia, where I spent my last holiday, is a wonderful city.",
          "whose للملكية (الذي ... له / التي ... لها)، ويأتي بعده اسم مباشرة: The woman whose car was stolen = المرأة التي سُرقت سيارتها. لا تخلط بين whose و who's (= who is).",
          "انتبه: الضمير الموصول يحلّ محلّ الاسم، فلا نكرّر الضمير بعده: The man who worked (وليس who he worked).",
          "إذا كانت جملة الصلة بين فاصلتين (معلومة إضافية) مثل Lattakia, where I spent... أو civil liberties, which are freedoms... فلا نستخدم that.",
          "عندما يكون الضمير الموصول مفعولاً به يمكن حذفه: the bill (which) you sent me = الفاتورة التي أرسلتها لي.",
        ],
        examples: [
          "A drill is a tool which is used to make a hole in something.",
          "Mobile phones are phones that you can carry around in your pocket.",
          "The man who worked in a printing company visited me last night.",
          "The woman whose car was stolen called the police.",
          "Lattakia, where I spent my last holiday, is a wonderful city.",
        ],
        exercises: [
          // Book exercise a — complete the rules
          { type: "fill", prompt: "Rule: Use ___ or that for things. (A drill is a tool which is used to make a hole in something.)", promptAr: "القاعدة: استخدم ___ أو that للأشياء.", promptArFull: "القاعدة: استخدم which أو that للأشياء.", options: ["who", "which", "where", "whose"], answer: 1, explainAr: "الجملة 1: a tool which — الأداة شيء، فنستخدم which (أو that) للأشياء." },
          { type: "fill", prompt: "Rule: Use which or ___ for things. (Mobile phones are phones that you can carry around in your pocket.)", promptAr: "القاعدة: استخدم which أو ___ للأشياء.", promptArFull: "القاعدة: استخدم which أو that للأشياء.", options: ["whose", "where", "that", "who"], answer: 2, explainAr: "الجملة 2: phones that — الهواتف أشياء، و that تُستخدم للأشياء كما تُستخدم which." },
          { type: "fill", prompt: "Rule: Use ___ or that for people. (The man who worked in a printing company visited me last night.)", promptAr: "القاعدة: استخدم ___ أو that للأشخاص.", promptArFull: "القاعدة: استخدم who أو that للأشخاص.", options: ["who", "which", "whose", "where"], answer: 0, explainAr: "الجملة 3: The man who — الرجل شخص، فنستخدم who (أو that) للأشخاص." },
          { type: "fill", prompt: "Rule: Use who or ___ for people.", promptAr: "القاعدة: استخدم who أو ___ للأشخاص.", promptArFull: "القاعدة: استخدم who أو that للأشخاص.", options: ["which", "where", "whose", "that"], answer: 3, explainAr: "that تصلح للأشخاص وللأشياء، فنقول: The man that worked... مثل The man who worked..." },
          { type: "fill", prompt: "Rule: Use ___ for places. (Lattakia, where I spent my last holiday, is a wonderful city.)", promptAr: "القاعدة: استخدم ___ للأماكن.", promptArFull: "القاعدة: استخدم where للأماكن.", options: ["whose", "where", "who", "that"], answer: 1, explainAr: "الجملة 5: Lattakia, where — اللاذقية مكان، فنستخدم where للأماكن." },
          { type: "fill", prompt: "Rule: Use ___ for possession. (The woman whose car was stolen called the police.)", promptAr: "القاعدة: استخدم ___ للملكية.", promptArFull: "القاعدة: استخدم whose للملكية.", options: ["who", "which", "whose", "where"], answer: 2, explainAr: "الجملة 4: The woman whose car — السيارة ملك المرأة، فنستخدم whose للملكية." },
          // Book sentences 1–5
          { type: "fill", prompt: "A drill is a tool ___ is used to make a hole in something.", promptAr: "المِثقب أداة ___ تُستخدم لعمل ثقب في شيء ما.", promptArFull: "المِثقب أداة تُستخدم لعمل ثقب في شيء ما.", options: ["who", "where", "which", "whose"], answer: 2, explainAr: "a tool شيء، فنستخدم which." },
          { type: "fill", prompt: "Mobile phones are phones ___ you can carry around in your pocket.", promptAr: "الهواتف المحمولة هي هواتف ___ يمكنك حملها في جيبك أينما ذهبت.", promptArFull: "الهواتف المحمولة هي هواتف يمكنك حملها في جيبك أينما ذهبت.", options: ["that", "who", "where", "whose"], answer: 0, explainAr: "phones أشياء، فنستخدم that (أو which)." },
          { type: "fill", prompt: "The man ___ worked in a printing company visited me last night.", promptAr: "الرجل ___ كان يعمل في شركة طباعة زارني الليلة الماضية.", promptArFull: "الرجل الذي كان يعمل في شركة طباعة زارني الليلة الماضية.", options: ["which", "who", "whose", "where"], answer: 1, explainAr: "The man شخص، فنستخدم who." },
          { type: "fill", prompt: "The woman ___ car was stolen called the police.", promptAr: "المرأة ___ سُرقت سيارتها اتصلت بالشرطة.", promptArFull: "المرأة التي سُرقت سيارتها اتصلت بالشرطة.", options: ["who", "who's", "which", "whose"], answer: 3, explainAr: "السيارة ملك المرأة (her car)، فنستخدم whose ويأتي بعدها الاسم car مباشرة. أما who's فتعني who is." },
          { type: "fill", prompt: "Lattakia, ___ I spent my last holiday, is a wonderful city.", promptAr: "اللاذقية، ___ قضيت عطلتي الأخيرة، مدينة رائعة.", promptArFull: "اللاذقية، حيث قضيت عطلتي الأخيرة، مدينة رائعة.", options: ["where", "which", "that", "who"], answer: 0, explainAr: "Lattakia مكان، وقضيت العطلة فيه (in Lattakia)، فنستخدم where. ولا نستخدم that بين فاصلتين." },
          // Book exercise b — definitions
          { type: "mcq", prompt: "Which word does this definition describe? “A ... is a machine which makes copies of documents.”", promptAr: "أي كلمة يصفها هذا التعريف؟ “... آلة تصنع نسخاً من الوثائق.”", options: ["vacuum cleaner", "photocopier", "launderette", "plumber"], answer: 1, explainAr: "photocopier = آلة تصوير المستندات، وهي تصنع نسخاً (copies)." },
          { type: "fill", prompt: "A photocopier is a machine ___ makes copies of documents.", promptAr: "آلة التصوير آلةٌ ___ تصنع نسخاً من الوثائق.", promptArFull: "آلة التصوير آلةٌ تصنع نسخاً من الوثائق.", options: ["who", "where", "whose", "which"], answer: 3, explainAr: "a machine شيء، فنستخدم which (أو that)." },
          { type: "mcq", prompt: "Which word does this definition describe? “A ... is a person who protects important people from being attacked.”", promptAr: "أي كلمة يصفها هذا التعريف؟ “... شخص يحمي الأشخاص المهمّين من التعرّض للاعتداء.”", options: ["plumber", "launderette", "bodyguard", "photocopier"], answer: 2, explainAr: "bodyguard = حارس شخصي، يحمي (protects) الأشخاص المهمّين." },
          { type: "fill", prompt: "A bodyguard is a person ___ protects important people from being attacked.", promptAr: "الحارس الشخصي شخصٌ ___ يحمي الأشخاص المهمّين من التعرّض للاعتداء.", promptArFull: "الحارس الشخصي شخصٌ يحمي الأشخاص المهمّين من التعرّض للاعتداء.", options: ["who", "which", "where", "whose"], answer: 0, explainAr: "a person شخص، فنستخدم who (أو that)." },
          { type: "mcq", prompt: "Which word does this definition describe? “A ... is a place with washing machines where you can wash your clothes.”", promptAr: "أي كلمة يصفها هذا التعريف؟ “... مكان فيه غسالات تستطيع أن تغسل فيه ملابسك.”", options: ["photocopier", "launderette", "vacuum cleaner", "bodyguard"], answer: 1, explainAr: "launderette = مغسلة ملابس عامة، مكان فيه غسالات." },
          { type: "fill", prompt: "A launderette is a place with washing machines ___ you can wash your clothes.", promptAr: "المغسلة العامة مكان فيه غسالات ___ تستطيع أن تغسل ملابسك.", promptArFull: "المغسلة العامة مكان فيه غسالات حيث تستطيع أن تغسل ملابسك.", options: ["which", "who", "where", "whose"], answer: 2, explainAr: "نتحدث عن مكان تغسل فيه ملابسك (you wash your clothes there)، فنستخدم where." },
          { type: "mcq", prompt: "Which word does this definition describe? “A ... is a person whose job is to mend central heating, taps, etc.”", promptAr: "أي كلمة يصفها هذا التعريف؟ “... شخص عمله إصلاح التدفئة المركزية والصنابير وغيرها.”", options: ["bodyguard", "photocopier", "launderette", "plumber"], answer: 3, explainAr: "plumber = سبّاك، عمله إصلاح التدفئة والصنابير." },
          { type: "fill", prompt: "A plumber is a person ___ job is to mend central heating, taps, etc.", promptAr: "السبّاك شخص ___ عمله إصلاح التدفئة المركزية والصنابير وغيرها.", promptArFull: "السبّاك شخص عمله إصلاح التدفئة المركزية والصنابير وغيرها.", options: ["who's", "whose", "who", "which"], answer: 1, explainAr: "العمل (job) يخصّ السبّاك (his job)، فنستخدم whose للملكية ويأتي بعدها الاسم job." },
          { type: "mcq", prompt: "Which word does this definition describe? “A ... is a machine which you use to clean floors and carpets.”", promptAr: "أي كلمة يصفها هذا التعريف؟ “... آلة تستخدمها لتنظيف الأرضيات والسجاد.”", options: ["vacuum cleaner", "photocopier", "plumber", "launderette"], answer: 0, explainAr: "vacuum cleaner = مكنسة كهربائية، تنظّف الأرضيات والسجاد." },
          { type: "fill", prompt: "A vacuum cleaner is a machine ___ you use to clean floors and carpets.", promptAr: "المكنسة الكهربائية آلة ___ تستخدمها لتنظيف الأرضيات والسجاد.", promptArFull: "المكنسة الكهربائية آلة تستخدمها لتنظيف الأرضيات والسجاد.", options: ["who", "where", "which", "whose"], answer: 2, explainAr: "a machine شيء، فنستخدم which (أو that)." },
          // Practice inside the unit's world
          { type: "fill", prompt: "Human rights are the rights ___ one acquires by being alive.", promptAr: "حقوق الإنسان هي الحقوق ___ يكتسبها المرء لمجرد كونه حياً.", promptArFull: "حقوق الإنسان هي الحقوق التي يكتسبها المرء لمجرد كونه حياً.", options: ["who", "which", "where", "whose"], answer: 1, explainAr: "the rights أشياء، فنستخدم which (أو that) كما في نص القراءة." },
          { type: "fill", prompt: "Civil rights laws attempt to guarantee full and equal citizenship for people ___ have traditionally been discriminated against.", promptAr: "تسعى قوانين الحقوق المدنية إلى ضمان المواطنة الكاملة والمتساوية للأشخاص ___ تعرّضوا تاريخياً للتمييز.", promptArFull: "تسعى قوانين الحقوق المدنية إلى ضمان المواطنة الكاملة والمتساوية للأشخاص الذين تعرّضوا تاريخياً للتمييز.", options: ["which", "whose", "who", "where"], answer: 2, explainAr: "people أشخاص، فنستخدم who." },
          { type: "fill", prompt: "Restraints are rules ___ limit what people can do.", promptAr: "القيود قواعد ___ تحدّ مما يستطيع الناس فعله.", promptArFull: "القيود قواعد تحدّ مما يستطيع الناس فعله.", options: ["which", "who", "whose", "where"], answer: 0, explainAr: "rules أشياء، فنستخدم which (أو that)." },
          { type: "fill", prompt: "In contrast to civil liberties, ___ are freedoms that are secured by placing restraints on government, civil rights are secured by positive government action.", promptAr: "على عكس الحريات المدنية، ___ هي حريات تُصان بفرض قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي.", promptArFull: "على عكس الحريات المدنية، التي هي حريات تُصان بفرض قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي.", options: ["that", "who", "where", "which"], answer: 3, explainAr: "civil liberties أشياء، وجملة الصلة بين فاصلتين (معلومة إضافية)، فنستخدم which ولا نستخدم that." },
          { type: "fill", prompt: "Voiced sounds are those ___ make our vocal cords vibrate when they are produced.", promptAr: "الأصوات المجهورة هي تلك ___ تجعل حبالنا الصوتية تهتز عند نطقها.", promptArFull: "الأصوات المجهورة هي تلك التي تجعل حبالنا الصوتية تهتز عند نطقها.", options: ["who", "that", "whose", "where"], answer: 1, explainAr: "those تعود على sounds (أشياء)، فنستخدم that (أو which)." },
          { type: "fill", prompt: "A violation is an action ___ breaks a law, an agreement or a principle.", promptAr: "الانتهاك فعلٌ ___ يخرق قانوناً أو اتفاقاً أو مبدأً.", promptArFull: "الانتهاك فعلٌ يخرق قانوناً أو اتفاقاً أو مبدأً.", options: ["where", "whose", "that", "who"], answer: 2, explainAr: "an action شيء، فنستخدم that (أو which)." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["The woman who car was stolen called the police.", "The woman which car was stolen called the police.", "The woman who's car was stolen called the police.", "The woman whose car was stolen called the police."], answer: 3, explainAr: "للملكية نستخدم whose + اسم: whose car. أما who's فهي اختصار who is." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["Lattakia, where I spent my last holiday, is a wonderful city.", "Lattakia, that I spent my last holiday, is a wonderful city.", "Lattakia, who I spent my last holiday, is a wonderful city.", "Lattakia, whose I spent my last holiday, is a wonderful city."], answer: 0, explainAr: "للمكان الذي حدث فيه الفعل نستخدم where، ولا نستخدم that بين فاصلتين." },
          { type: "mcq", prompt: "Choose the correct sentence.", promptAr: "اختر الجملة الصحيحة.", options: ["The man which worked in a printing company visited me last night.", "The man who worked in a printing company visited me last night.", "The man who he worked in a printing company visited me last night.", "The man where worked in a printing company visited me last night."], answer: 1, explainAr: "للأشخاص نستخدم who، ولا نكرّر الضمير he بعد الضمير الموصول." },
          { type: "mcq", prompt: "Which word can replace “that” in “Mobile phones are phones that you can carry around in your pocket.”?", promptAr: "أي كلمة يمكن أن تحلّ محلّ “that” في جملة “Mobile phones are phones that you can carry around in your pocket.”؟", options: ["who", "whose", "which", "where"], answer: 2, explainAr: "that للأشياء تساوي which، فنقول phones which you can carry." },
          { type: "truefalse", prompt: "We use “whose” for places.", promptAr: "نستخدم “whose” للأماكن.", answer: false, explainAr: "خطأ: whose للملكية، أما للأماكن فنستخدم where." },
          { type: "truefalse", prompt: "In “the bill you sent me was incorrect”, the relative pronoun (which / that) is left out because it is the object of the clause.", promptAr: "في عبارة “the bill you sent me was incorrect” حُذف الضمير الموصول (which / that) لأنه مفعول به في جملة الصلة.", answer: true, explainAr: "صحيح: الأصل the bill (which) you sent me؛ الفاعل هو you، والضمير الموصول مفعول به فيجوز حذفه." },
          { type: "truefalse", prompt: "“that” can be used for both things and people.", promptAr: "يمكن استخدام “that” للأشياء وللأشخاص معاً.", answer: true, explainAr: "صحيح: which or that for things, who or that for people." },
          { type: "build", prompt: "رتّب الكلمات: المرأة التي سُرقت سيارتها اتصلت بالشرطة.", answer: "The woman whose car was stolen called the police.", extraWords: ["who", "which"] },
          { type: "build", prompt: "رتّب الكلمات: الرجل الذي كان يعمل في شركة طباعة زارني الليلة الماضية.", answer: "The man who worked in a printing company visited me last night.", extraWords: ["which", "whose"] },
        ],
      },
      pronunciation: {
        title: "Voiced and Voiceless Sounds",
        ruleAr: "كل الأصوات إما مجهورة (voiced) أو مهموسة (voiceless). الصوت المجهور يجعل الحبال الصوتية تهتز عند نطقه، مثل /b/ في bet، والصوت المهموس لا يجعلها تهتز، مثل /p/ في pet. ضع يدك على حنجرتك وقل /z/ ثم /s/ لتشعر بالفرق. المهموسة عادةً: /p/ /t/ /k/ /f/ /θ/ /s/ /ʃ/ /tʃ/. المجهورة عادةً: /dʒ/ /ʒ/ /z/ /ð/ /v/ /g/ /d/ /b/ /ŋ/ /r/، وكل أصوات العلّة (vowels) مجهورة أيضاً. في التمرين ننظر إلى الصوت الأخير في الكلمة لا إلى الحرف المكتوب: laugh تنتهي بصوت /f/ المهموس، و show تنتهي بصوت علّة مجهور.",
        groups: [
          { label: "Voiceless — /p/ /t/ /k/ /f/ /θ/ /s/ /ʃ/ /tʃ/ (pet)", words: ["pet", "mistake", "laugh", "sick", "ash", "path"] },
          { label: "Voiced — /dʒ/ /ʒ/ /z/ /ð/ /v/ /g/ /d/ /b/ /ŋ/ /r/ + all vowels (bet)", words: ["bet", "answer", "show", "run", "sing", "young", "judge"] },
        ],
      },
      everyday: {
        title: "Complaints and Apologies",
        titleAr: "الشكاوى والاعتذارات",
        explainAr: "عندما يحدث خطأ (فاتورة غير صحيحة، خدمة سيئة في فندق، طلبية متأخرة) نقدّم شكوى بأدب: نبدأ بـ I’m afraid I have a complaint to make أو I’m sorry to bother you but...، ونوضح أن الأمر غير مقبول: It really isn’t good enough / It’s very inconvenient. أما الشخص المسؤول فيعتذر: I must apologise / I’m awfully sorry about it، ويطمئن صاحب الشكوى: I assure you it won’t happen again.",
        expressions: [
          { en: "I’m afraid I have a complaint to make.", ar: "أخشى أن لديّ شكوى أريد تقديمها.", note: "starting a complaint politely" },
          { en: "I’m sorry to bother you but …", ar: "آسف لإزعاجك لكن …", note: "starting a complaint politely" },
          { en: "It really isn’t good enough.", ar: "هذا غير مقبول حقاً.", note: "complaining strongly" },
          { en: "Don’t you think it’s about time you got it working properly?", ar: "ألا تعتقد أنه حان الوقت لتجعله يعمل بشكل صحيح؟", note: "complaining" },
          { en: "It’s very inconvenient.", ar: "هذا مزعج جداً.", note: "complaining" },
          { en: "I must apologise.", ar: "يجب أن أعتذر.", note: "apologising" },
          { en: "I’m awfully sorry about it.", ar: "أنا آسف جداً على ذلك.", note: "apologising" },
          { en: "I assure you it won’t happen again.", ar: "أؤكد لك أن ذلك لن يتكرر.", note: "promising after an apology" },
        ],
        dialogue: [
          { speaker: "A", en: "I’m afraid I have a complaint to make.", ar: "أخشى أن لديّ شكوى أريد تقديمها." },
          { speaker: "B", en: "Oh dear. Please take a seat.", ar: "يا إلهي. تفضّلي بالجلوس." },
          { speaker: "A", en: "I’m sorry to bother you but the bill you sent me was incorrect.", ar: "آسفة لإزعاجك لكن الفاتورة التي أرسلتها لي كانت غير صحيحة." },
          { speaker: "B", en: "Incorrect, madam? That’s very strange.", ar: "غير صحيحة يا سيدتي؟ هذا غريب جداً." },
          { speaker: "A", en: "Yes, I know, and what’s more, this isn’t the first time.", ar: "نعم، أعرف، والأكثر من ذلك أنها ليست المرة الأولى." },
          { speaker: "B", en: "Really?! I can't beleive it.", ar: "حقاً؟! لا أستطيع أن أصدّق ذلك." },
          { speaker: "A", en: "It’s happened five or six times in the last three months. It really isn’t good enough.", ar: "لقد حدث ذلك خمس أو ست مرات في الأشهر الثلاثة الماضية. هذا غير مقبول حقاً." },
          { speaker: "B", en: "Ah. Well, I must apologise, madam. It’s the new computer.", ar: "آه. حسناً، يجب أن أعتذر يا سيدتي. إنه الحاسوب الجديد." },
          { speaker: "A", en: "Well, don’t you think it’s about time you got it working properly? It’s very inconvenient.", ar: "حسناً، ألا تعتقد أنه حان الوقت لتجعله يعمل بشكل صحيح؟ هذا مزعج جداً." },
          { speaker: "B", en: "You're right! I’m awfully sorry about it. I assure you it won’t happen again.", ar: "أنتِ محقة! أنا آسف جداً على ذلك. أؤكد لكِ أن ذلك لن يتكرر." },
        ],
        exercises: [
          { type: "mcq", prompt: "The bath in your hotel is full of spiders. You call the manager. How do you start?", promptAr: "حوض الاستحمام في فندقك مليء بالعناكب. تتصل بالمدير. كيف تبدأ كلامك؟", options: ["I assure you it won’t happen again.", "I’m afraid I have a complaint to make.", "I’m awfully sorry about it.", "Oh dear. Please take a seat."], answer: 1, explainAr: "صاحب الشكوى يبدأ بأدب: I’m afraid I have a complaint to make. أما العبارات الأخرى فيقولها المسؤول الذي يعتذر." },
          { type: "mcq", prompt: "You receive a bill higher than it should be. You ring the manager of the shop. What do you say?", promptAr: "وصلتك فاتورة أعلى مما يجب. تتصل بمدير المتجر. ماذا تقول؟", options: ["I’m sorry to bother you but the bill you sent me was incorrect.", "I must apologise, madam.", "That’s very strange.", "You're right!"], answer: 0, explainAr: "I’m sorry to bother you but ... طريقة مهذبة لبدء الشكوى وذكر المشكلة." },
          { type: "mcq", prompt: "The bookshop tells you the book you ordered three months ago still hasn’t arrived. You want to say this is not acceptable.", promptAr: "أخبرتك المكتبة أن الكتاب الذي طلبته قبل ثلاثة أشهر لم يصل بعد. تريد أن تقول إن هذا غير مقبول.", options: ["I assure you it won’t happen again.", "Oh dear. Please take a seat.", "It really isn’t good enough.", "I’m awfully sorry about it."], answer: 2, explainAr: "It really isn’t good enough = هذا غير مقبول حقاً، عبارة شكوى قوية." },
          { type: "mcq", prompt: "You are the manager. A customer complains about a wrong bill. How do you apologise?", promptAr: "أنت المدير. زبون يشتكي من فاتورة خاطئة. كيف تعتذر؟", options: ["It’s very inconvenient.", "I’m afraid I have a complaint to make.", "Don’t you think it’s about time you got it working properly?", "I’m awfully sorry about it."], answer: 3, explainAr: "I’m awfully sorry about it = أنا آسف جداً على ذلك، عبارة اعتذار." },
          { type: "mcq", prompt: "After apologising, the manager wants to promise the customer that the problem will not come back. What does he say?", promptAr: "بعد الاعتذار، يريد المدير أن يعد الزبون بأن المشكلة لن تعود. ماذا يقول؟", options: ["I assure you it won’t happen again.", "It really isn’t good enough.", "This isn’t the first time.", "I’m sorry to bother you."], answer: 0, explainAr: "I assure you it won’t happen again = أؤكد لك أن ذلك لن يتكرر." },
          { type: "fill", prompt: "I’m afraid I have a ___ to make.", promptAr: "أخشى أن لديّ ___ أريد تقديمها.", promptArFull: "أخشى أن لديّ شكوى أريد تقديمها.", options: ["complain", "complaint", "apologise", "sorry"], answer: 1, explainAr: "بعد a نحتاج اسماً: complaint (شكوى). أما complain فهو فعل." },
          { type: "fill", prompt: "I’m sorry to ___ you but the bill you sent me was incorrect.", promptAr: "آسفة ___ لكن الفاتورة التي أرسلتها لي كانت غير صحيحة.", promptArFull: "آسفة لإزعاجك لكن الفاتورة التي أرسلتها لي كانت غير صحيحة.", options: ["bother", "assure", "apologise", "complain"], answer: 0, explainAr: "I’m sorry to bother you = آسف لإزعاجك، بداية مهذبة للشكوى." },
          { type: "fill", prompt: "It’s happened five or six times in the last three months. It really isn’t good ___.", promptAr: "لقد حدث ذلك خمس أو ست مرات في الأشهر الثلاثة الماضية. هذا غير ___ حقاً.", promptArFull: "لقد حدث ذلك خمس أو ست مرات في الأشهر الثلاثة الماضية. هذا غير مقبول حقاً.", options: ["well", "enough", "more", "time"], answer: 1, explainAr: "التعبير الثابت: It really isn’t good enough = غير مقبول حقاً." },
          { type: "fill", prompt: "Ah. Well, I must ___, madam. It’s the new computer.", promptAr: "آه. حسناً، يجب أن ___ يا سيدتي. إنه الحاسوب الجديد.", promptArFull: "آه. حسناً، يجب أن أعتذر يا سيدتي. إنه الحاسوب الجديد.", options: ["complain", "assure", "apologise", "bother"], answer: 2, explainAr: "I must apologise = يجب أن أعتذر، وبعد must نستخدم المصدر." },
          { type: "fill", prompt: "Well, don’t you think it’s about time you got it working properly? It’s very ___.", promptAr: "حسناً، ألا تعتقد أنه حان الوقت لتجعله يعمل بشكل صحيح؟ هذا ___ جداً.", promptArFull: "حسناً، ألا تعتقد أنه حان الوقت لتجعله يعمل بشكل صحيح؟ هذا مزعج جداً.", options: ["strange", "convenient", "sorry", "inconvenient"], answer: 3, explainAr: "صاحبة الشكوى تقول إن الأمر مزعج: It’s very inconvenient. أما convenient فتعني مناسب وهي عكس المقصود." },
          { type: "fill", prompt: "You're right! I’m ___ sorry about it.", promptAr: "أنتِ محقة! أنا آسف ___ على ذلك.", promptArFull: "أنتِ محقة! أنا آسف جداً على ذلك.", options: ["awfully", "awful", "afraid", "strange"], answer: 0, explainAr: "awfully (ظرف) = جداً، يأتي قبل الصفة sorry: I’m awfully sorry." },
          { type: "fill", prompt: "I ___ you it won’t happen again.", promptAr: "___ لك أن ذلك لن يتكرر.", promptArFull: "أؤكد لك أن ذلك لن يتكرر.", options: ["apologise", "assure", "bother", "complain"], answer: 1, explainAr: "I assure you = أؤكد لك، لطمأنة صاحب الشكوى." },
          { type: "truefalse", prompt: "“I must apologise” is used to make a complaint.", promptAr: "تُستخدم عبارة “I must apologise” لتقديم شكوى.", answer: false, explainAr: "خطأ: I must apologise عبارة اعتذار يقولها المسؤول، وليست شكوى." },
          { type: "truefalse", prompt: "“It’s very inconvenient” is said by the person who is complaining.", promptAr: "عبارة “It’s very inconvenient” يقولها الشخص الذي يشتكي.", answer: true, explainAr: "صحيح: صاحبة الشكوى في الحوار تقول It’s very inconvenient لتبيّن أن المشكلة تزعجها." },
        ],
      },
      listening: {
        taskAr: "أ) هل لديك فكرة عن واجباتك وحقوقك في المدرسة بوصفك طالباً؟ أخبر زميلك. ب) استمع إلى حوار بين بيتر ورينا عن المسؤولية وأكمل الفراغات بالكلمات التي تسمعها (الإجابات في التسجيل الصوتي). ثم: برأيك، ما الذي يجعل الشخص مسؤولاً في المجتمع؟ أخبر الصف.",
        items: [
          "As a student, do you have any idea about your duties and rights at school? Tell your partner.",
          "Peter: So what were you …… when you were younger?",
          "Rena: When I was a kid, I …… …… …… irresponsible.",
          "Peter: You? Really? What made you ……?",
          "Rena: …… from high school.",
          "Peter: What do you ……?",
          "Rena: ……, until I graduated, I’d never had any important …… . I knew nothing about my …… and rights. But then, I …… …… to college...",
          "Peter: I …… what you mean. I was really …… when I was a teenager.",
          "Rena: So what made you change?",
          "Peter: I think I …… more mature after I got my first job and moved …… from home. Once I had a job, I became …… independent and …… of everything.",
          "Rena: Where did you ……?",
          "Peter: I worked for my dad at the …… .",
          "In your opinion, what makes a person responsible in society? Tell the class.",
        ],
      },
      writing: {
        taskAr: "أ) حدّد إن كانت العبارات التالية حقوقاً (R) أم واجبات (D): 1 Participating in an election — المشاركة في الانتخابات (R حق). 2 Parents should send their children to school — يجب على الآباء إرسال أطفالهم إلى المدرسة (D واجب). 3 Women go to work — خروج المرأة إلى العمل (R حق). 4 Children have to obey their parents — يجب على الأطفال طاعة والديهم (D واجب). 5 Keeping surroundings clean — الحفاظ على نظافة المحيط (D واجب). ب) اكتب مقالاً عن حقوق الإنسان وواجباته في المجتمع بعنوان «A man is born with rights and duties» (يولد الإنسان ومعه حقوق وواجبات). ج) راجع مقالك لتصحيح الأخطاء الإملائية والنحوية وانتبه لعلامات الترقيم. (قبل الكتابة، في قسم Speaking: صف الصورتين — طلاب في قاعة امتحان وشاب في مقابلة عمل — وأخبر زميلك برأيك.)",
        linkers: ["Simply speaking", "In other words", "while", "Unlike", "In contrast to", "regardless of"],
      },
      sentences: [
        "A drill is a tool which is used to make a hole in something.",
        "Mobile phones are phones that you can carry around in your pocket.",
        "The man who worked in a printing company visited me last night.",
        "The woman whose car was stolen called the police.",
        "Lattakia, where I spent my last holiday, is a wonderful city.",
        "Voiced sounds are those that make our vocal cords vibrate when they are produced.",
        "I’m afraid I have a complaint to make.",
        "It’s happened five or six times in the last three months.",
        "I assure you it won’t happen again.",
        "In other words, civil rights are the rights of citizens to political and social freedom and equality.",
        "You should speak directly and ask for a raise.",
        "The lawyers were unable to collect data against the man.",
        "Parents should send their children to school.",
        "Children have to obey their parents.",
        "A man is born with rights and duties.",
        "So what made you change?",
      ],
    },

    // @@UNIT6@@
  ],
}
