import type { Exam } from '../../../engine/types'

// A final Baccalaureate practice paper in the exact layout of the real paper (term1-a.ts), covering the whole book.
// Passage A: Unit 8 reading "Human Body" (page 75), first part. Passage B: Unit 11 reading "Artificial Intelligence" (pages 108–109), first part.
export const term2B: Exam = {
  id: 't2-b',
  term: 2,
  title: 'Baccalaureate — Final Test (B)',
  titleAr: 'نموذج البكالوريا النهائي (B)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل الدقيق لامتحان البكالوريا الحقيقي، يغطّي الكتاب كاملاً (الوحدات 1–12) ومبنيّ من نصوص الكتاب وقواعده ومفرداته فقط.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'The human body is a wonderful machine which performs several functions without rest from birth. Our body continues to work, without stopping for a second. The main organs of the human body are lungs, heart, kidney, liver and brain. These organs work together and are controlled by the brain. Each system such as digestive system, excretory system, circulatory system, endocrine system, nervous system or muscular system carries out a major function. All of them are controlled by the brain which gives us intelligence to use our physical and mental abilities.',
          'An average person is estimated to contain trillions of human cells, according to recent research. These cells include neurons (nerve cells) and glands (specialised cells). The hormones and enzymes are produced and secreted by these glands that perform different functions.',
          'The human body is covered by the skin, which is a flexible covering that protects the body and keeps water and harmful germs out.',
        ],
        paragraphsAr: [
          'جسم الإنسان آلة رائعة تؤدّي وظائف عديدة دون راحة منذ الولادة. فجسمنا يستمرّ في العمل دون أن يتوقّف لحظة واحدة. والأعضاء الرئيسية في جسم الإنسان هي الرئتان والقلب والكلية والكبد والدماغ. تعمل هذه الأعضاء معاً ويتحكّم بها الدماغ. وكل جهاز، كالجهاز الهضمي والجهاز الإخراجي وجهاز الدوران وجهاز الغدد الصمّاء والجهاز العصبي والجهاز العضلي، يؤدّي وظيفة رئيسية. وكلّها يتحكّم بها الدماغ الذي يمنحنا الذكاء لنستخدم قدراتنا الجسدية والعقلية.',
          'يُقدَّر أن جسم الشخص العادي يحتوي على تريليونات الخلايا البشرية، وفقاً لأبحاث حديثة. وتشمل هذه الخلايا العصبونات (الخلايا العصبية) والغدد (خلايا متخصّصة). وتُنتج هذه الغدد الهرمونات والإنزيمات وتفرزها، وهي تؤدّي وظائف مختلفة.',
          'جسم الإنسان مغطّى بالجلد، وهو غطاء مرن يحمي الجسم ويمنع دخول الماء والجراثيم الضارّة.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'Why is the human body considered a wonderful machine?', promptAr: 'لماذا يُعدّ جسم الإنسان آلة رائعة؟', lines: 3,
              accept: ['Because it performs several functions without rest from birth.', 'It performs several functions without rest from birth.', 'Because it performs several functions without rest from birth and continues to work without stopping for a second.', 'Because it continues to work without stopping for a second.', 'Because it performs several functions without rest.'],
              model: 'Because it performs several functions without rest from birth.',
              modelAr: 'لأنه يؤدّي وظائف عديدة دون راحة منذ الولادة.',
              explainAr: 'الجملة الأولى: "The human body is a wonderful machine which performs several functions without rest from birth". السؤال بـ Why فابدأ الجواب بـ Because.' },
            { n: 2, kind: 'write', prompt: 'What are the main organs of the human body?', promptAr: 'ما الأعضاء الرئيسية في جسم الإنسان؟', lines: 2,
              accept: ['The main organs of the human body are lungs, heart, kidney, liver and brain.', 'They are lungs, heart, kidney, liver and brain.', 'Lungs, heart, kidney, liver and brain.', 'The lungs, the heart, the kidney, the liver and the brain.'],
              model: 'The main organs of the human body are lungs, heart, kidney, liver and brain.',
              modelAr: 'الأعضاء الرئيسية هي الرئتان والقلب والكلية والكبد والدماغ.',
              explainAr: 'النص: "The main organs of the human body are lungs, heart, kidney, liver and brain". انقل الأعضاء الخمسة كلها.' },
            { n: 3, kind: 'write', prompt: 'What do the glands produce and secrete?', promptAr: 'ماذا تُنتج الغدد وتُفرز؟', lines: 2,
              accept: ['They produce and secrete hormones and enzymes.', 'The glands produce and secrete hormones and enzymes.', 'Hormones and enzymes.', 'They produce hormones and enzymes.'],
              model: 'They produce and secrete hormones and enzymes.',
              modelAr: 'تُنتج الهرمونات والإنزيمات وتفرزها.',
              explainAr: 'النص بالمبني للمجهول: "The hormones and enzymes are produced and secreted by these glands". حوّلها إلى المعلوم في الجواب: The glands produce and secrete hormones and enzymes.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', topic: 'vocab', prompt: 'Relating to the system in your body that produces hormones ……..', promptAr: 'متعلّق بالجهاز في جسمك الذي يُنتج الهرمونات', lines: 1,
              accept: ['endocrine'], modelAr: 'الغدد الصمّاء',
              explainAr: 'في النص "endocrine system" — جهاز الغدد الصمّاء، وهو الذي يُنتج الهرمونات. التعريف نفسه في تمرين المفردات في الوحدة 8.' },
            { n: 5, kind: 'write', topic: 'vocab', prompt: 'Having the function of getting rid of waste material from the body ……..', promptAr: 'وظيفته التخلّص من الفضلات من الجسم', lines: 1,
              accept: ['excretory'], modelAr: 'إخراجي',
              explainAr: 'في النص "excretory system" — الجهاز الإخراجي الذي يخلّص الجسم من الفضلات. لا تخلط بينه وبين digestive (هضمي) أو circulatory (دوراني).' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'The main organs of the body work separately and are controlled by the heart.', promptAr: 'تعمل الأعضاء الرئيسية في الجسم منفصلة ويتحكّم بها القلب.', lines: 2,
              accept: ['The main organs of the body work together and are controlled by the brain.', 'The main organs of the human body work together and are controlled by the brain.', 'These organs work together and are controlled by the brain.'],
              model: 'The main organs of the body work together and are controlled by the brain.',
              modelAr: 'تعمل الأعضاء الرئيسية في الجسم معاً ويتحكّم بها الدماغ.',
              explainAr: 'النص: "These organs work together and are controlled by the brain". في الجملة خطآن: separately ← together، و the heart ← the brain.' },
            { n: 7, kind: 'write', prompt: 'The skin is a hard covering that lets water and harmful germs into the body.', promptAr: 'الجلد غطاء صلب يُدخل الماء والجراثيم الضارّة إلى الجسم.', lines: 2,
              accept: ['The skin is a flexible covering that protects the body and keeps water and harmful germs out.', 'The skin is a flexible covering that keeps water and harmful germs out of the body.', 'The skin is a flexible covering that keeps water and harmful germs out.'],
              model: 'The skin is a flexible covering that protects the body and keeps water and harmful germs out.',
              modelAr: 'الجلد غطاء مرن يحمي الجسم ويمنع دخول الماء والجراثيم الضارّة.',
              explainAr: 'النص: "the skin, which is a flexible covering that protects the body and keeps water and harmful germs out". الخطأ: hard ← flexible، و lets ... into ← keeps ... out.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'Artificial Intelligence (AI) is the branch of science and engineering specialised in making clever machines, capable of thinking and imitating human-level intelligence. One of the primary targets of AI field is to produce fully intelligent agents that interact with the surroundings and conduct human-like behaviours. These agents are tools, having the ability to judge matter and differentiate what is wrong.',
          'The field has started with robots, which can sense and react to the world around them. They also cover purely software-based agents, which can be actuated with natural language and multimedia. Currently, the field expands to driving, aviation, medicine, online advertising, image recognition, and personal assistance. The AI field is based on computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields.',
          'The first spark started in the year 1950, when a test of the ability of a machine to exhibit intelligent behaviour equivalent to that of a human was done.',
        ],
        paragraphsAr: [
          'الذكاء الاصطناعي هو فرع العلم والهندسة المتخصّص في صنع آلات ذكية قادرة على التفكير ومحاكاة الذكاء على المستوى البشري. ومن الأهداف الرئيسية لمجال الذكاء الاصطناعي إنتاج وكلاء أذكياء تماماً يتفاعلون مع محيطهم ويسلكون سلوكاً شبيهاً بسلوك البشر. وهؤلاء الوكلاء أدوات لديها القدرة على الحكم على الأمور والتمييز بين ما هو خاطئ.',
          'بدأ هذا المجال بالروبوتات التي تستطيع أن تستشعر العالم من حولها وتتفاعل معه. ويشمل أيضاً وكلاء برمجيين بحتين يمكن تشغيلهم باللغة الطبيعية والوسائط المتعدّدة. ويتوسّع المجال حالياً ليشمل قيادة السيارات والطيران والطب والإعلانات على الإنترنت والتعرّف على الصور والمساعدة الشخصية. ويقوم مجال الذكاء الاصطناعي على علوم الحاسوب وهندسة المعلومات والرياضيات وعلم النفس واللسانيات والفلسفة وحقول أخرى كثيرة.',
          'انطلقت الشرارة الأولى عام 1950، حين أُجري اختبار لقدرة آلة على إظهار سلوك ذكي يعادل سلوك الإنسان.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'The field of AI started with ……..', promptAr: 'بدأ مجال الذكاء الاصطناعي بـ ……..', options: ['software-based agents', 'robots', 'online advertising', 'personal assistance'], answer: 1,
              explainAr: 'النص: "The field has started with robots, which can sense and react to the world around them". أما software-based agents فجاءت بعدها (They also cover...)، و online advertising و personal assistance مجالات توسّع إليها حالياً.' },
            { n: 9, kind: 'mcq', prompt: 'AI agents are tools having the ability to ……..', promptAr: 'وكلاء الذكاء الاصطناعي أدوات لديها القدرة على ……..', options: ['feel basic human emotions', 'work without any software', 'judge matter and differentiate what is wrong', 'replace all human doctors'], answer: 2,
              explainAr: 'النص: "These agents are tools, having the ability to judge matter and differentiate what is wrong". الخيارات الأخرى غير مذكورة في النص.' },
            { n: 10, kind: 'mcq', prompt: 'Purely software-based agents can be actuated with ……..', promptAr: 'يمكن تشغيل الوكلاء البرمجيين البحتين بـ ……..', options: ['natural language and multimedia', 'electrical impulses', 'robots only', 'image recognition'], answer: 0,
              explainAr: 'النص: "They also cover purely software-based agents, which can be actuated with natural language and multimedia" — باللغة الطبيعية والوسائط المتعدّدة.' },
            { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'The designing, building and flying of aircraft is ……..', promptAr: 'تصميم الطائرات وبناؤها وقيادتها هو ……..', options: ['advertising', 'recognition', 'assistance', 'aviation'], answer: 3,
              explainAr: 'aviation = الطيران، وهي في النص "the field expands to driving, aviation, medicine...". advertising = الإعلان، recognition = التعرّف، assistance = المساعدة.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'The AI field is based on ……………………', promptAr: 'يقوم مجال الذكاء الاصطناعي على ……', lines: 2,
              accept: ['computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields', 'computer science, information engineering, mathematics, psychology, linguistics and philosophy', 'computer science, information engineering, mathematics, psychology, linguistics, philosophy and other fields'],
              model: 'computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields.',
              modelAr: 'علوم الحاسوب وهندسة المعلومات والرياضيات وعلم النفس واللسانيات والفلسفة وحقول أخرى كثيرة.',
              explainAr: 'النص: "The AI field is based on computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields".' },
            { n: 13, kind: 'write', prompt: 'One of the primary targets of AI is to produce ……………………', promptAr: 'من الأهداف الرئيسية للذكاء الاصطناعي إنتاج ……', lines: 2,
              accept: ['fully intelligent agents that interact with the surroundings and conduct human-like behaviours', 'fully intelligent agents', 'fully intelligent agents that interact with the surroundings'],
              model: 'fully intelligent agents that interact with the surroundings and conduct human-like behaviours.',
              modelAr: 'وكلاء أذكياء تماماً يتفاعلون مع محيطهم ويسلكون سلوكاً شبيهاً بسلوك البشر.',
              explainAr: 'النص: "One of the primary targets of AI field is to produce fully intelligent agents that interact with the surroundings and conduct human-like behaviours".' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'She didn’t really ……… her workmates in her previous job.', promptAr: 'لم تكن فعلاً ___ زملائها في عملها السابق.', options: ['take up', 'give up', 'fit in with', 'get into'], answer: 2,
          explainAr: 'fit in with = يتأقلم مع مجموعة ويكون مقبولاً فيها (be accepted by other people in a group)، والجملة من كتابك (الوحدة 1). take up = يبدأ هواية، give up = يترك، get into = يبدأ الاهتمام بشيء.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'That is the village ……… my grandparents live.', promptAr: 'تلك هي القرية ___ يعيش فيها جدّاي.', options: ['which', 'where', 'when', 'whose'], answer: 1,
          explainAr: 'بعد اسم مكان (the village) ويليه جملة كاملة (my grandparents live) نستخدم where. which تحتاج حرف جر (in which)، when للزمن، whose للملكية. التمرين من المراجعة 2.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'The doorbell made him ……… .', promptAr: 'جعله جرس الباب ___.', options: ['speak his mind', 'jump out of his skin', 'follow his heart', 'pay an arm and a leg'], answer: 1,
          explainAr: 'jump out of your skin = يفزع/يُصدم فجأة (shocked)، والجملة من تعابير الجسم في الوحدة 8. speak your mind = يقول ما يفكّر فيه بصراحة، follow your heart = يتبع إحساسه، an arm and a leg = مبلغ باهظ.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'Robert is an accredited ……… with herbal medicine and nutritional training.', promptAr: 'روبرت ___ معتمد مدرَّب على الطب العشبي والتغذية.', options: ['pediatrician', 'ophthalmologist', 'dermatologist', 'naturopath'], answer: 3,
          explainAr: 'naturopath = المعالج بالطب الطبيعي (specialises in natural cures and remedies)، ويناسب herbal medicine (الطب العشبي). الجملة من الوحدة 3. pediatrician = طبيب أطفال، ophthalmologist = طبيب عيون، dermatologist = طبيب جلدية. هؤلاء أطباء، أما الطب العشبي فعمل المعالج بالطب الطبيعي.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'In which word is the stress on the second syllable?', promptAr: 'في أيّ كلمة يقع النبر على المقطع الثاني؟', options: ['loudness', 'dangerous', 'unfriendly', 'comfortable'], answer: 2,
          explainAr: 'نبر المقاطع (الوحدة 8): البادئات مثل un لا تُنبر، فالنبر في unfriendly على المقطع الثاني (un-FRIEND-ly). واللواحق ness و ous و able لا تُنبر أيضاً، فالنبر في loudness و dangerous و comfortable على المقطع الأول.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'When she pulled the large lever, the wheel began to ……… .', promptAr: 'عندما سحبت الذراع الكبيرة، بدأت العجلة ___.', options: ['react', 'extract', 'dissect', 'rotate'], answer: 3,
          explainAr: 'rotate = يدور، والعجلة (wheel) تدور. الجملة من كتابك (الوحدة 11، أفعال العلوم والتكنولوجيا). react = يتفاعل (للمواد الكيميائية)، extract = يستخرج، dissect = يشرّح.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'He’s very keen ……… chess.', promptAr: 'إنه مولع جداً ___ الشطرنج.', options: ['on', 'in', 'at', 'of'], answer: 0,
          explainAr: 'الصفة keen يليها حرف الجر on (keen on = مولع بـ)، والجملة من الوحدة 9 (صفات يليها حرف جر). قارن: good at، afraid of.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'In which sentence is the auxiliary verb pronounced in its strong form?', promptAr: 'في أيّ جملة يُلفظ الفعل المساعد بصيغته القوية؟', options: ['Can you speak English?', 'Do they come early?', 'Yes, I can.', 'Was the weather terrible?'], answer: 2,
          explainAr: 'الصيغ القوية والضعيفة للأفعال المساعدة (الوحدة 11): في الأسئلة يُلفظ الفعل المساعد ضعيفاً بصوت schwa /ə/ مثل /kən/ و /də/ و /wəz/، أما في آخر الإجابة القصيرة (Yes, I can.) فيُلفظ قوياً /kæn/.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Individuals have ……… dreams in their day-to-day existence.', promptAr: 'لدى الأفراد أحلام ___ في حياتهم اليومية.', options: ['vary', 'various', 'variety', 'variously'], answer: 1,
          explainAr: 'قبل الاسم dreams نحتاج صفة: various = متنوّعة (من الفعل vary). vary فعل، variety اسم، variously ظرف. الجملة من تمرين عائلة الكلمة في الوحدة 1.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'I can’t watch the match tonight. I wish I ……… watch it.', promptAr: 'لا أستطيع مشاهدة المباراة الليلة. ليتني ___ مشاهدتها.', lines: 1,
          accept: ['could'], explainAr: 'التمنّي (الوحدة 8): عندما يكون الواقع can’t نتمنّى بـ wish + could + المصدر. الجملة من كتابك: "I can’t watch the match tonight. I wish I could watch it."' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'Seldom ……… I leave my house so early.', promptAr: 'نادراً ما ___ أغادر بيتي باكراً إلى هذا الحد.', lines: 1,
          accept: ['do', 'did'], explainAr: 'التقديم والتأخير (الوحدة 12): عندما تبدأ الجملة بظرف نفي أو تقليل مثل Seldom نقدّم الفعل المساعد على الفاعل. في المضارع البسيط نستخدم do (وفي الماضي did). الجملة من كتابك: "Seldom do I leave my house so early."' },
        { n: 25, kind: 'write', topic: 'grammar', prompt: 'A local jewellery shop was broken into ……… someone yesterday.', promptAr: 'اقتُحم محلّ مجوهرات محلّي ___ شخص ما أمس.', lines: 1,
          accept: ['by'], explainAr: 'في المبني للمجهول (الوحدة 3) نذكر الفاعل بعد by. لاحظ أن into جزء من الفعل break into فيبقى، ثم يأتي by someone. الجملة من قصة كتابك.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'Doctors need {a sample of your urine, blood or swab from your nose or throat} to see what infection you have.', promptAr: 'يحتاج الأطباء إلى عيّنة من البول أو الدم أو مسحة من الأنف أو الحلق ليعرفوا ما العدوى التي لديك.', lines: 1,
          accept: ['What do doctors need to see what infection you have?', 'What do doctors need to see what infection I have?', 'What do doctors need?'], model: 'What do doctors need to see what infection you have?', modelAr: 'ماذا يحتاج الأطباء ليعرفوا ما العدوى التي لديك؟',
          explainAr: 'المسطَّر شيء (مفعول به) فنسأل بـ What. الفعل need مضارع بسيط مع فاعل جمع (Doctors) فنستخدم do. الجملة من نص الكائنات الدقيقة (الوحدة 7).' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'Jack is travelling to Spain {tomorrow}.', promptAr: 'جاك مسافر إلى إسبانيا غداً.', lines: 1,
          accept: ['When is Jack travelling to Spain?', 'When is he travelling to Spain?'], modelAr: 'متى سيسافر جاك إلى إسبانيا؟',
          explainAr: 'المسطَّر زمن فنسأل بـ When. الفعل مضارع مستمر (is travelling) فنقدّم is على الفاعل: When is Jack travelling ...? الجملة من حوار التعبير عن الدهشة (الوحدة 10).' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'A few weeks ago, a woman called {to report a robbery at her house}.', promptAr: 'قبل بضعة أسابيع، اتّصلت امرأة للإبلاغ عن سرقة في بيتها.', lines: 1,
          accept: ['Why did a woman call a few weeks ago?', 'Why did the woman call a few weeks ago?', 'Why did a woman call?', 'Why did the woman call?'], model: 'Why did a woman call a few weeks ago?', modelAr: 'لماذا اتّصلت امرأة قبل بضعة أسابيع؟',
          explainAr: 'المسطَّر يبيّن الهدف (to + فعل) فنسأل بـ Why. الفعل called ماضٍ بسيط فنستخدم did ويعود الفعل إلى أصله call. الجملة من الوحدة 2.' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'reported', prompt: '“Where is the key?” my mother asked. (reported speech)', promptAr: 'سألت أمي: "أين المفتاح؟" (الكلام المنقول)', lines: 2,
          accept: ['My mother asked where the key was.', 'My mother wanted to know where the key was.', 'My mother asked me where the key was.'], model: 'My mother wanted to know where the key was.', modelAr: 'أرادت أمي أن تعرف أين المفتاح.',
          explainAr: 'نقل السؤال (الوحدة 11): نحذف علامة الاستفهام ونعيد الترتيب إلى جملة خبرية (الفاعل ثم الفعل): where the key was، ونرجع الزمن خطوة: is ← was. خطأ شائع: where was the key.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'Sua’ad is not in class today. Waleed is not in class today. (neither ... nor)', promptAr: 'سعاد ليست في الصف اليوم. وليد ليس في الصف اليوم. (neither ... nor)', lines: 2,
          accept: ['Neither Sua’ad nor Waleed is in class today.', 'Neither Suaad nor Waleed is in class today.', 'Neither Suad nor Waleed is in class today.'], modelAr: 'لا سعاد ولا وليد في الصف اليوم.',
          explainAr: 'أدوات الربط المزدوجة (الوحدة 9): neither ... nor تحمل معنى النفي، فلا نضع not بعدها. الفعل يتبع الفاعل الأقرب إليه (Waleed مفرد) فنقول is. الجملة من المراجعة 3.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Your friend tells you: “Jack’s got a new job.” (Express surprise)', promptAr: 'يقول لك صديقك: "حصل جاك على عمل جديد". (عبّر عن الدهشة)', lines: 2,
          accept: ['A new job?! Good for him.', 'A new job? Good for him!', 'A new job? How amazing!', 'Really? How amazing!', 'Oh, that’s incredible!', 'That’s incredible!', 'Are you serious?', 'You’re kidding!', 'Has he? How amazing!', 'A new job? That’s interesting!'],
          model: 'A new job?! Good for him.', modelAr: 'عمل جديد؟! هنيئاً له.',
          explainAr: 'التعبير عن الدهشة (Everyday English، الوحدة 10): نكرّر الخبر بنبرة سؤال (A new job?!) أو نقول: How amazing! / That’s incredible! / Are you serious? / You’re kidding!' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'The shop on the corner usually mends my glasses. (causative verb)', promptAr: 'المحل الذي على الزاوية يصلح نظارتي عادةً. (الفعل السببي)', lines: 2,
          accept: ['I usually have my glasses mended at the shop on the corner.', 'I usually get my glasses mended at the shop on the corner.', 'I usually have my glasses mended by the shop on the corner.', 'I usually get my glasses mended by the shop on the corner.', 'I usually have my glasses mended in the shop on the corner.'],
          model: 'I usually have my glasses mended at the shop on the corner.', modelAr: 'أُصلح نظارتي عادةً (عندهم) في المحل الذي على الزاوية.',
          explainAr: 'السببي (الوحدة 4): have/get + مفعول + التصريف الثالث. الفعل الأصلي مضارع بسيط (mends) فنقول I usually have my glasses mended. الجملة من المراجعة 1.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'Jack is my best friend. We ………. (be) friends for more than ten years.', promptAr: 'جاك أعزّ أصدقائي. نحن صديقان منذ أكثر من عشر سنوات.', lines: 1,
          accept: ['have been', "'ve been"], explainAr: 'for more than ten years مع حالة بدأت في الماضي وما زالت صحيحة الآن ← المضارع التام: have + been (الوحدة 1).' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'The poor bird ………. (capture) and all its efforts to escape from the trap were in vain.', promptAr: 'أُمسك الطائر المسكين وذهبت كل محاولاته للهرب من الفخ سدى.', lines: 1,
          accept: ['was captured', 'had been captured'], explainAr: 'الطائر لا يمسك نفسه فنحتاج المبني للمجهول (الوحدة 3)، و were in vain تدلّ على الماضي: was + captured (ويُقبل had been captured).' },
        { n: 35, kind: 'write', topic: 'conditional', prompt: 'If the referee ………. (see) the foul, he would have awarded a penalty kick to our team.', promptAr: 'لو رأى الحكم الخطأ، لمنح فريقنا ركلة جزاء.', lines: 1,
          accept: ['had seen', "'d seen"], explainAr: 'الجواب would have awarded يدلّ على الشرطية الثالثة (الوحدة 7)، فجملة If تأخذ الماضي التام: had + seen.' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'conditional', prompt: 'If you practised more, …………………………..', promptAr: 'لو تدرّبت أكثر، …', lines: 2,
          accept: ['your English would improve.', 'you would win the match.', 'you would be a better player.', 'you would play better.'], model: 'your English would improve.', modelAr: 'لتحسّنت لغتك الإنجليزية.',
          explainAr: 'If + ماضٍ بسيط (practised) هي الشرطية الثانية لموقف تخيّلي في الحاضر، فالجواب: would + المصدر. المثال من كتابك (الوحدة 7).' },
        { n: 37, kind: 'write', topic: 'conditional', prompt: 'Unless you study hard, …………………………..', promptAr: 'ما لم تدرس بجدّ، …', lines: 2,
          accept: ['you will fail the exam.', 'you won’t pass the exam.', 'you will not pass the exam.', 'you will fail.'], model: 'you will fail the exam.', modelAr: 'سترسب في الامتحان.',
          explainAr: 'Unless = if ... not. بعدها مضارع بسيط (study)، والجملة الرئيسية بالمستقبل: will + المصدر (الشرطية الأولى).' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: The UN may not interfere in the domestic affairs of any country.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['لا يجوز للأمم المتحدة أن تتدخل في الشؤون الداخلية لأي دولة', 'لا يحق للأمم المتحدة التدخل في الشؤون الداخلية لأي بلد', 'لا يجوز للأمم المتحدة التدخل في الشؤون الداخلية لأي دولة'], model: 'لا يجوز للأمم المتحدة أن تتدخّل في الشؤون الداخلية لأي دولة.',
          explainAr: 'الجملة من مبادئ الأمم المتحدة (الوحدة 6). may not هنا = لا يجوز / غير مسموح، interfere in = يتدخّل في، domestic affairs = الشؤون الداخلية.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: أتمنّى لو أنني درستُ بجدّ أكبر العام الماضي.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['I wish I had studied harder last year.', 'I wish that I had studied harder last year.'],
          model: 'I wish I had studied harder last year.',
          explainAr: 'التمنّي عن الماضي (الوحدة 8): wish + الماضي التام (had studied) لأن العام الماضي انتهى. بجدّ أكبر ← harder، العام الماضي ← last year.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Using the Internet in learning.',
        topicAr: 'استخدام الإنترنت في التعلّم.',
        words: 80,
        points: ['How can students use the Internet in learning?', 'What are the advantages of using it?', 'What should students be careful about?'],
        model: 'The Internet could be a very positive step towards education. Nowadays, students can use it in many ways. First of all, they can engage in email or video chats with students from other countries, which improves their English and teaches them about other cultures. In addition, they can look up information quickly and download useful lessons and books. Students can also post discussion questions about their study and share ideas with their classmates. However, not all information on the Internet is true, so students should use critical thinking to check their sources. They also mustn’t spend too many hours online. If we use the Internet wisely, it will not only save our time but also make learning more enjoyable.',
        modelAr: 'يمكن أن يكون الإنترنت خطوة إيجابية جداً نحو التعليم. فاليوم يستطيع الطلاب استخدامه بطرق كثيرة: أولاً، يمكنهم التواصل بالبريد الإلكتروني أو محادثات الفيديو مع طلاب من بلدان أخرى، مما يحسّن لغتهم الإنجليزية ويعرّفهم بثقافات أخرى. إضافةً إلى ذلك، يمكنهم البحث عن المعلومات بسرعة وتنزيل دروس وكتب مفيدة. ويمكنهم أيضاً نشر أسئلة للنقاش حول دراستهم وتبادل الأفكار مع زملائهم. لكن ليست كل المعلومات على الإنترنت صحيحة، لذلك على الطلاب استخدام التفكير النقدي للتحقّق من مصادرهم، ويجب ألّا يقضوا ساعات طويلة على الإنترنت. إذا استخدمنا الإنترنت بحكمة، فلن يوفّر وقتنا فحسب، بل سيجعل التعلّم أكثر متعة أيضاً.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: طرق استخدام الإنترنت في التعلّم، ومزاياه، وما يجب الحذر منه.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (First of all, In addition, also, However, so) وأداة مزدوجة مثل not only ... but also.',
          'استخدمتُ can و should و mustn’t بشكل صحيح، وجملة شرطية صحيحة (If + مضارع، will).',
          'استخدمتُ كلمات من الوحدتين 11 و12 (download, look up, post, share, online, critical thinking).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
