import type { Exam } from '../../../engine/types'

// A practice Term 1 paper in the exact layout of the real paper (term1-a), built only from Units 1–6.
// Passage A: Unit 6, the Everyday English "Modesty" conversation (page 63).
// Passage B: Unit 3, "History of Medicine" (second half, page 28).
export const term1E: Exam = {
  id: 't1-e',
  term: 1,
  title: 'Term 1 — Test (E)',
  titleAr: 'الفصل الأول — النموذج (E)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بشكل امتحان الفصل الأول الحقيقي تماماً، مبنيّ فقط من نصوص الوحدات 1–6 ومفرداتها وقواعدها.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'A: Mr Khaled. After such a certificate, you must feel on top of the world.',
          'B: Oh, it was nothing really, nothing at all.',
          'A: No, I can honestly say that it was a great job what you’ve done so far.',
          'B: That’s very kind of you, but I feel the real credit must go to the whole team of the charity for their support.',
          'A: You’re being called an innovator for promoting such services in society. I must say that finding jobs for the young is something not easy at all. We really appreciate your efforts in the charity.',
          'B: You’re embarrassing me. I’ve just been very lucky for having a wonderful team.',
          'A: I hear that you’ve planned the whole project. Tell us about that.',
          'B: Oh, you’re exaggerating. I only played a small part in the whole thing. It was very much a team effort.',
          'A: Well, thank you very much, Mr Khaled.',
          'B: Thank you…',
        ],
        paragraphsAr: [
          'أ: سيد خالد، بعد شهادة كهذه لا بدّ أنك تشعر أنك في قمّة السعادة.',
          'ب: أوه، لم يكن ذلك شيئاً يُذكر حقاً، لا شيء على الإطلاق.',
          'أ: لا، أستطيع أن أقول بصدق إن ما أنجزته حتى الآن كان عملاً رائعاً.',
          'ب: هذا لطف كبير منك، لكنني أشعر أن الفضل الحقيقي يعود إلى فريق الجمعية الخيرية كلّه لدعمهم.',
          'أ: يُطلق عليك لقب "مبتكر" لأنك تروّج لمثل هذه الخدمات في المجتمع. ولا بدّ أن أقول إن إيجاد وظائف للشباب أمر ليس سهلاً على الإطلاق. نحن نقدّر حقاً جهودك في الجمعية الخيرية.',
          'ب: إنك تُحرجني. لقد كنت محظوظاً جداً فحسب لأن لديّ فريقاً رائعاً.',
          'أ: سمعت أنك خطّطت للمشروع كله. حدّثنا عن ذلك.',
          'ب: أوه، إنك تبالغ. لقد أدّيت دوراً صغيراً فقط في الأمر كلّه. كان إلى حدّ كبير عملاً جماعياً.',
          'أ: حسناً، شكراً جزيلاً لك يا سيد خالد.',
          'ب: شكراً لك…',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'Why does the speaker think Mr Khaled must feel on top of the world?', promptAr: 'لماذا يظنّ المتحدّث أن السيد خالد لا بدّ أن يشعر بأنه في قمّة السعادة؟', lines: 2,
              accept: ['Because he got a certificate.', 'Because he has got a certificate.', 'Because he got such a certificate.', 'After such a certificate.', 'Because of the certificate.', 'Because he has received a certificate.', 'Because he received a certificate.'],
              modelAr: 'لأنه حصل على شهادة (تكريم) كهذه.',
              explainAr: 'أول جملة: "After such a certificate, you must feel on top of the world". فسبب سعادته هو الشهادة التي نالها. on top of the world = سعيد جداً.' },
            { n: 2, kind: 'write', prompt: 'Who does Mr Khaled think the real credit must go to?', promptAr: 'لِمَن يرى السيد خالد أن الفضل الحقيقي يجب أن يعود؟', lines: 2,
              accept: ['The real credit must go to the whole team of the charity for their support.', 'It must go to the whole team of the charity.', 'To the whole team of the charity.', 'The whole team of the charity.', 'To the whole team of the charity for their support.', 'The whole team of the charity for their support.'],
              modelAr: 'إلى فريق الجمعية الخيرية كلّه لدعمهم.',
              explainAr: 'قال السيد خالد: "I feel the real credit must go to the whole team of the charity for their support". هكذا يتواضع فينسب الفضل إلى فريقه.' },
            { n: 3, kind: 'write', prompt: 'Why is Mr Khaled being called an innovator?', promptAr: 'لماذا يُطلق على السيد خالد لقب "مبتكر"؟', lines: 2,
              accept: ['He is being called an innovator for promoting such services in society.', 'For promoting such services in society.', 'Because he promotes such services in society.', 'Because he is promoting such services in society.', 'Because he has promoted such services in society.', 'For promoting services in society.'],
              modelAr: 'لأنه يروّج لمثل هذه الخدمات (إيجاد وظائف للشباب) في المجتمع.',
              explainAr: 'النص: "You’re being called an innovator for promoting such services in society". بعد for يأتي الفعل بصيغة ing ليبيّن السبب.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', topic: 'vocab', prompt: 'A person who introduces new ideas or methods. ……..', promptAr: 'شخص يأتي بأفكار أو طرائق جديدة', lines: 1,
              accept: ['innovator', 'an innovator'], modelAr: 'مبتكر / مجدّد',
              explainAr: 'innovator = مبتكر، من الفعل innovate (يبتكر) + اللاحقة or للشخص. وهي في النص: "You’re being called an innovator".' },
            { n: 5, kind: 'write', topic: 'vocab', prompt: 'Making something seem larger, better or more important than it really is. ……..', promptAr: 'جعل شيء يبدو أكبر أو أفضل أو أهمّ مما هو في الحقيقة', lines: 1,
              accept: ['exaggerating', 'exaggerate'], modelAr: 'يبالغ',
              explainAr: 'exaggerate = يبالغ، وفي النص: "Oh, you’re exaggerating". وهو من تعابير التواضع (Modesty) في الوحدة 6.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'Mr Khaled says that he did the whole project by himself.', promptAr: 'يقول السيد خالد إنه أنجز المشروع كلّه بنفسه.', lines: 2,
              accept: ['Mr Khaled says that he only played a small part in the whole thing.', 'Mr Khaled says that he only played a small part; it was very much a team effort.', 'Mr Khaled says that it was very much a team effort.', 'Mr Khaled says that he only played a small part in the whole thing and it was very much a team effort.', 'He says that he only played a small part in the whole thing.', 'He says it was a team effort.', 'Mr Khaled says that it was a team effort.'],
              model: 'Mr Khaled says that he only played a small part in the whole thing; it was very much a team effort.', modelAr: 'يقول السيد خالد إنه أدّى دوراً صغيراً فقط، وإن المشروع كان عملاً جماعياً.',
              explainAr: 'النص: "I only played a small part in the whole thing. It was very much a team effort". فالمشروع لم يكن عمله وحده بل عمل الفريق.' },
            { n: 7, kind: 'write', prompt: 'The speaker thinks that finding jobs for the young is very easy.', promptAr: 'يرى المتحدّث أن إيجاد وظائف للشباب سهل جداً.', lines: 2,
              accept: ['The speaker thinks that finding jobs for the young is not easy at all.', 'The speaker thinks that finding jobs for the young is something not easy at all.', 'Finding jobs for the young is not easy at all.', 'Finding jobs for the young is something not easy at all.', 'The speaker thinks that finding jobs for the young is not easy.', 'Finding jobs for the young is not easy.'],
              model: 'The speaker thinks that finding jobs for the young is not easy at all.', modelAr: 'يرى المتحدّث أن إيجاد وظائف للشباب ليس سهلاً على الإطلاق.',
              explainAr: 'النص: "finding jobs for the young is something not easy at all". نصحّح بتغيير very easy إلى not easy at all.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'Modern medicine started to emerge in the late 18th century and therefore, there were many improvements on medical tools and machines, especially after the Industrial Revolution. In the 1800s, physicians learned that illnesses were caused by germs and hospitals began to focus on keeping clean to keep germs away. As a result, nursing came to be thought of as a respectable job. The 20th century was characterised by new biological treatments such as antibiotics in addition to advancement in chemistry, genetics and radiography.',
          'Arabic medicine has made a major contribution to the development of pharmacy. It is logical for doctors to discover new drugs while looking for ways to treat their patients. They wrote about them in booklets about the history of the disease called “al-Mujarrabat”. Subsequently, good and lesser known drugs were extracted from it. Physicians have tried to use simple medicines to determine the exact effect of the entered component into the disease. Still, some doctors have prescribed and combined the medications that they themselves formulated.',
          'Today healthcare isn\'t just about doctors; nurses, physical therapists and technicians are all part of a large health care system that helps to keep people healthy. Modern medicine is characterised by surgeries, the use of radiation, microscopy, research and analysis in the detection of disease or ailment by using modern technological tools. Due to the rapid advance of technology, it is certain that medicine will continue to develop in ways we have yet to imagine.',
        ],
        paragraphsAr: [
          'بدأ الطب الحديث بالظهور في أواخر القرن الثامن عشر، ولذلك حدثت تحسينات كثيرة على الأدوات والآلات الطبية، ولا سيّما بعد الثورة الصناعية. وفي القرن التاسع عشر عرف الأطباء أن الأمراض تسبّبها الجراثيم، وبدأت المستشفيات تركّز على النظافة لإبعاد الجراثيم. ونتيجة لذلك صار يُنظر إلى التمريض على أنه مهنة محترمة. وتميّز القرن العشرون بعلاجات بيولوجية جديدة مثل المضادات الحيوية، إضافة إلى التقدّم في الكيمياء وعلم الوراثة والتصوير الشعاعي.',
          'قدّم الطب العربي إسهاماً كبيراً في تطوّر علم الصيدلة. فمن المنطقي أن يكتشف الأطباء أدوية جديدة وهم يبحثون عن طرق لعلاج مرضاهم. وقد كتبوا عنها في كتيّبات عن تاريخ المرض سُمّيت "المجرّبات". وبعد ذلك استُخرجت منها أدوية جيدة وأخرى أقلّ شهرة. وقد حاول الأطباء استخدام أدوية بسيطة لتحديد الأثر الدقيق للمكوّن الداخل في المرض. ومع ذلك وصف بعض الأطباء أدوية ركّبوها هم أنفسهم ومزجوها.',
          'اليوم لم تعد الرعاية الصحية مقتصرة على الأطباء؛ فالممرضون والمعالجون الفيزيائيون والفنيّون جميعهم جزء من نظام رعاية صحية كبير يساعد على إبقاء الناس أصحّاء. ويتميّز الطب الحديث بالعمليات الجراحية واستخدام الإشعاع والفحص المجهري والبحث والتحليل في الكشف عن المرض أو العلّة باستخدام أدوات تكنولوجية حديثة. وبسبب التقدّم السريع للتكنولوجيا، من المؤكّد أن الطب سيستمر في التطوّر بطرق لم نتخيّلها بعد.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'In the 1800s, physicians learned that illnesses were caused by ……..', promptAr: 'في القرن التاسع عشر عرف الأطباء أن الأمراض تسبّبها ……..', options: ['herbs', 'supernatural forces', 'radiation', 'germs'], answer: 3,
              explainAr: 'النص: "In the 1800s, physicians learned that illnesses were caused by germs". أما "supernatural forces" فكانت اعتقاد القدماء (في الجزء الأول من النص في كتابك).' },
            { n: 9, kind: 'mcq', prompt: 'Nursing came to be thought of as a respectable job after ……..', promptAr: 'صار يُنظر إلى التمريض على أنه مهنة محترمة بعد أن ……..', options: ['nurses discovered antibiotics', 'hospitals began to focus on keeping clean', 'the 20th century ended', 'doctors wrote al-Mujarrabat'], answer: 1,
              explainAr: 'النص: "hospitals began to focus on keeping clean to keep germs away. As a result, nursing came to be thought of as a respectable job". As a result تربط النتيجة (احترام التمريض) بالسبب (اهتمام المستشفيات بالنظافة).' },
            { n: 10, kind: 'mcq', prompt: '“Al-Mujarrabat” were booklets about ……..', promptAr: '"المجرّبات" كانت كتيّبات عن ……..', options: ['the history of the disease', 'the Industrial Revolution', 'nursing', 'modern technological tools'], answer: 0,
              explainAr: 'النص: "They wrote about them in booklets about the history of the disease called “al-Mujarrabat”" — كتيّبات عن تاريخ المرض.' },
            { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'The word “ailment” in the text is closest in meaning to ……..', promptAr: 'كلمة "ailment" في النص أقرب في معناها إلى ……..', options: ['tool', 'treatment', 'illness', 'nurse'], answer: 2,
              explainAr: 'ailment = علّة / مرض، وهي في النص مع disease: "the detection of disease or ailment"، فأقرب معنى لها "illness". treatment = علاج، tool = أداة.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'The 20th century was characterised by ……………………', promptAr: 'تميّز القرن العشرون بـ ……', lines: 2,
              accept: ['new biological treatments such as antibiotics in addition to advancement in chemistry, genetics and radiography', 'new biological treatments such as antibiotics', 'new biological treatments such as antibiotics in addition to advancement in chemistry genetics and radiography', 'new biological treatments'],
              model: 'new biological treatments such as antibiotics in addition to advancement in chemistry, genetics and radiography.', modelAr: 'علاجات بيولوجية جديدة مثل المضادات الحيوية، إضافة إلى التقدّم في الكيمياء وعلم الوراثة والتصوير الشعاعي.',
              explainAr: 'آخر جملة في الفقرة الأولى: "The 20th century was characterised by new biological treatments such as antibiotics in addition to advancement in chemistry, genetics and radiography".' },
            { n: 13, kind: 'write', prompt: 'Medicine will continue to develop as a result of ……………………', promptAr: 'سيستمر الطب في التطوّر نتيجةً لـ ……', lines: 2,
              accept: ['the rapid advance of technology', 'the rapid advance of technology.', 'the advance of technology'],
              modelAr: 'التقدّم السريع للتكنولوجيا.',
              explainAr: 'آخر جملة في النص: "Due to the rapid advance of technology, it is certain that medicine will continue to develop". due to = as a result of = بسبب.' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'I’m going to ……… learning Chinese because it’s too difficult.', promptAr: 'سوف ___ تعلّم اللغة الصينية لأنها صعبة جداً.', options: ['take up', 'carry on', 'give up', 'fit in'], answer: 2,
          explainAr: 'give up = يتوقّف عن / يترك، والجملة من كتابك (الوحدة 2). take up = يبدأ نشاطاً جديداً، carry on = يستمر، fit in = يندمج مع مجموعة. because it’s too difficult تدلّ على الترك.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'In the Middle Ages, patients were treated by local wise people ……… were skilled in the use of herbs.', promptAr: 'في العصور الوسطى كان المرضى يُعالَجون على أيدي حكماء محلّيين ___ كانوا ماهرين في استخدام الأعشاب.', options: ['which', 'who', 'whose', 'where'], answer: 1,
          explainAr: 'الاسم قبل الفراغ (local wise people) عاقل، وبعد الفراغ فعل مباشرة (were skilled)، فنستخدم who (أو that) كما في قاعدة الوحدة 5، والجملة من نص تاريخ الطب (الوحدة 3). which لغير العاقل، whose للملكية ويأتي بعدها اسم، where للمكان.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'You should speak directly and ask for a raise. Don’t ………', promptAr: 'يجب أن تتكلّم مباشرة وتطلب زيادة في الراتب. لا ___.', options: ['break the law', 'go under the knife', 'join the ranks', 'beat around the bush'], answer: 3,
          explainAr: 'beat around the bush = يلفّ ويدور ولا يدخل في صلب الموضوع (تعابير القانون، الوحدة 5)، وهي عكس speak directly. break the law = يخالف القانون، go under the knife = يخضع لعملية جراحية، join the ranks of = ينضمّ إلى صفوف.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'A/ An ……… is a specialist for babies and children.', promptAr: '___ هو اختصاصي الرضّع والأطفال.', options: ['pediatrician', 'dermatologist', 'naturopath', 'ophthalmologist'], answer: 0,
          explainAr: 'pediatrician = طبيب الأطفال (الوحدة 3). dermatologist = طبيب الجلد، naturopath = المعالج بالطب الطبيعي، ophthalmologist = طبيب العيون.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'Choose the word that ends with a voiceless sound:', promptAr: 'اختر الكلمة التي تنتهي بصوت مهموس (لا تهتزّ معه الأوتار الصوتية):', options: ['run', 'judge', 'laugh', 'sing'], answer: 2,
          explainAr: 'laugh تنتهي بصوت /f/ وهو مهموس (voiceless) لا تهتزّ معه الأوتار الصوتية. أما run (/n/) و judge (/dʒ/) و sing (/ŋ/) فتنتهي بأصوات مجهورة (voiced) (الوحدة 5).' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'Civil rights laws attempt to ……… full and equal citizenship for people who have traditionally been discriminated against.', promptAr: 'تحاول قوانين الحقوق المدنية أن ___ مواطنةً كاملة ومتساوية للأشخاص الذين عانوا تقليدياً من التمييز.', options: ['guarantee', 'deny', 'violate', 'repress'], answer: 0,
          explainAr: 'guarantee = يضمن، والجملة من نص الحقوق المدنية (الوحدة 5). deny = يحرم / ينكر، violate = ينتهك، repress = يقمع — وكلها عكس هدف القوانين.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'Raise both your hands slowly ……… the air.', promptAr: 'ارفع كلتا يديك ببطء ___ الهواء.', options: ['onto', 'off', 'to', 'into'], answer: 3,
          explainAr: 'حروف جر الحركة (الوحدة 4): into = حركة إلى داخل شيء أو مكان (عكس out of)، ونقول raise your hands into the air، والجملة من تمرين الوحدة 4 في كتابك. onto = إلى سطح شيء، off = عن سطح شيء، to = نحو وجهة أو مكان.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: '“I live at number 11 Johnson Street, not Oxford Street.” Which word takes the main stress?', promptAr: '"أسكن في الرقم 11 في شارع جونسون، لا في شارع أكسفورد." أيّ كلمة تحمل النبر الرئيسي؟', options: ['live', 'Johnson', 'number', 'Street'], answer: 1,
          explainAr: 'النبر التوكيدي (الوحدة 3): نضغط على الكلمة التي نريد تصحيحها أو مقارنتها. المقارنة هنا بين Johnson و Oxford، فالنبر على Johnson.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Your idea is ……… ; it doesn’t make sense.', promptAr: 'فكرتك ___ ؛ إنها لا معنى لها.', options: ['unlogical', 'illogical', 'inlogical', 'dislogical'], answer: 1,
          explainAr: 'البادئة il تأتي قبل الكلمات التي تبدأ بحرف l: logical ← illogical (غير منطقي) (البادئات، الوحدة 6). ولا توجد كلمات unlogical أو inlogical أو dislogical.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'A search ……… been organized by the police for the robber.', promptAr: 'نُظّمت عملية بحث عن اللص من قِبل الشرطة.', lines: 1,
          accept: ['has', "'s"], explainAr: 'المبني للمجهول في المضارع التام: has/have + been + التصريف الثالث (الوحدة 3). الفاعل A search مفرد فنستخدم has.' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'A photocopier is a machine ……… makes copies of documents.', promptAr: 'آلة التصوير هي آلة ___ تصنع نسخاً من الوثائق.', lines: 1,
          accept: ['which', 'that'], explainAr: 'اسم الصلة لغير العاقل (machine) الذي يليه فعل هو which أو that (الوحدة 5).' },
        { n: 25, kind: 'write', topic: 'tense', prompt: 'When it goes into orbit, the spacecraft will ……… carrying 25 kilos of plutonium.', promptAr: 'عندما تدخل المدار، ستكون المركبة الفضائية ___ تحمل 25 كيلوغراماً من البلوتونيوم.', lines: 1,
          accept: ['be'], explainAr: 'المستقبل المستمر: will + be + فعل ing، لحدث سيكون مستمراً في وقت معيّن في المستقبل (الوحدة 6).' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'The oldest practical water-powered machines appeared {in Persia} in the fourth century BC.', promptAr: 'ظهرت أقدم الآلات العملية التي تعمل بقوة الماء في بلاد فارس في القرن الرابع قبل الميلاد.', lines: 1,
          accept: ['Where did the oldest practical water-powered machines appear in the fourth century BC?', 'Where did the oldest practical water-powered machines appear?', 'Where did the oldest water-powered machines appear?', 'Where did the oldest water-powered machines appear in the fourth century BC?', 'Where did the first practical water-powered machines appear?'], modelAr: 'أين ظهرت أقدم الآلات العملية التي تعمل بقوة الماء في القرن الرابع قبل الميلاد؟',
          explainAr: 'المسطَّر مكان (in Persia) فنسأل بـ Where. الفعل appeared ماضٍ بسيط، فنستخدم did ويعود الفعل إلى أصله appear: Where did ... appear؟ والجملة من نص تاريخ الهندسة (الوحدة 4).' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'The United Nations has {six} official languages.', promptAr: 'للأمم المتحدة ست لغات رسمية.', lines: 1,
          accept: ['How many official languages does the United Nations have?', 'How many official languages does the UN have?', 'How many official languages has the United Nations got?', 'How many official languages has the UN got?', 'How many official languages are there in the United Nations?', 'How many official languages are there in the UN?'], modelAr: 'كم لغةً رسمية للأمم المتحدة؟',
          explainAr: 'المسطَّر عدد لأشياء معدودة فنسأل بـ How many + اسم جمع (official languages). الفعل has مضارع بسيط مع مفرد، فنستخدم does ويعود الفعل إلى أصله have. وفي نص الأمم المتحدة (الوحدة 6) اللغات الرسمية ست: العربية والصينية والإنجليزية والفرنسية والروسية والإسبانية.' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'The hotel near our office was closed {because it was being renovated by the owner}.', promptAr: 'أُغلق الفندق القريب من مكتبنا لأن مالكه كان يجدّده.', lines: 1,
          accept: ['Why was the hotel near our office closed?', 'Why was the hotel closed?'], modelAr: 'لماذا أُغلق الفندق القريب من مكتبنا؟',
          explainAr: 'المسطَّر سبب (because...) فنسأل بـ Why. الجملة مبنية للمجهول في الماضي (was closed) فنقدّم was على الفاعل: Why was the hotel ... closed؟' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'grammar', prompt: 'Sami’s parents must have brought him up to be more polite. (passive voice)', promptAr: 'لا بدّ أن والدَي سامي قد ربّياه ليكون أكثر تهذيباً. (المبني للمجهول)', lines: 2,
          accept: ['Sami must have been brought up to be more polite.', 'Sami must have been brought up by his parents to be more polite.', 'Sami must have been brought up to be more polite by his parents.', 'He must have been brought up to be more polite.'],
          model: 'Sami must have been brought up by his parents to be more polite.', modelAr: 'لا بدّ أن سامي قد رُبّي ليكون أكثر تهذيباً.',
          explainAr: 'المبني للمجهول مع must في الماضي: must have been + التصريف الثالث (الوحدة 3). المفعول him يصبح فاعلاً (Sami)، ويبقى الفعل المركّب bring up مع حرفه: must have been brought up، ويمكن إضافة by his parents. الجملة من تمرين المبني للمجهول في كتابك.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'Raneem wants a doctor to alter her nose. (causative verb)', promptAr: 'تريد رنيم أن يغيّر طبيبٌ شكل أنفها. (الفعل السببي)', lines: 2,
          accept: ['Raneem wants to have her nose altered.', 'Raneem wants to get her nose altered.', 'Raneem wants to have her nose altered by a doctor.', 'Raneem wants to get her nose altered by a doctor.'],
          model: 'Raneem wants to have her nose altered.', modelAr: 'تريد رنيم أن تُجري تعديلاً لأنفها (عند طبيب).',
          explainAr: 'السببي: have/get + مفعول + التصريف الثالث (الوحدة 4). بعد wants نستخدم to have: Raneem wants to have her nose altered.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'The man visited me last night. He worked in a printing company. (Join using a relative pronoun)', promptAr: 'زارني الرجل الليلة الماضية. كان يعمل في شركة طباعة. (اربط باستخدام ضمير وصل)', lines: 2,
          accept: ['The man who worked in a printing company visited me last night.', 'The man that worked in a printing company visited me last night.', 'The man who visited me last night worked in a printing company.', 'The man that visited me last night worked in a printing company.'],
          model: 'The man who worked in a printing company visited me last night.', modelAr: 'الرجل الذي كان يعمل في شركة طباعة زارني الليلة الماضية.',
          explainAr: 'نستخدم who (أو that) للعاقل، ونضع جملة الصلة مباشرة بعد الاسم الذي تصفه (The man)، ونحذف الضمير He (الوحدة 5).' },
        { n: 32, kind: 'write', topic: 'tense', prompt: 'David intends to get up early tomorrow. (going to)', promptAr: 'ينوي ديفيد أن يستيقظ باكراً غداً. (استخدم going to)', lines: 2,
          accept: ['David is going to get up early tomorrow.', "I'm going to get up early tomorrow.", 'I am going to get up early tomorrow.'],
          model: 'David is going to get up early tomorrow.', modelAr: 'سيستيقظ ديفيد باكراً غداً (ينوي ذلك).',
          explainAr: 'نستخدم be going to + فعل للتعبير عن نيّة أو خطة قرّرناها من قبل (intends) (صيغ المستقبل، الوحدة 6). مع David نستخدم is.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'These clothes ………. (design) for daily use, so you can wear them wherever you want.', promptAr: 'هذه الملابس ___ للاستخدام اليومي، لذا يمكنك ارتداؤها أينما تريد.', lines: 1,
          accept: ['are designed', 'have been designed'], explainAr: 'الملابس لا تصمّم نفسها فنحتاج المبني للمجهول، والجملة تصف حقيقة عامة في الحاضر (so you can wear them) فنستخدم المضارع البسيط المجهول: am/is/are + التصريف الثالث، و clothes جمع فنقول are designed. الجملة من تمرين الوحدة 3 في كتابك.' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'I ………. (want) complete silence now while I try this experiment.', promptAr: 'أريد صمتاً تاماً الآن بينما أجرّب هذه التجربة.', lines: 1,
          accept: ['want'], explainAr: 'want فعل حالة (stative verb) لا يأتي بصيغة المستمر حتى مع now، فنستخدم المضارع البسيط want لا am wanting (الوحدة 1، مراجعة 1).' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'Scientists announced the launch of the new drug last week. They ………. (develop) it for five years.', promptAr: 'أعلن العلماء إطلاق الدواء الجديد الأسبوع الماضي. كانوا يطوّرونه منذ خمس سنوات.', lines: 1,
          accept: ['had been developing', 'had developed'], explainAr: 'حدث استمر مدة (for five years) قبل حدث ماضٍ آخر (announced): الماضي التام المستمر had been + فعل ing (الوحدة 2).' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'tense', prompt: 'By the time you get home, ……………………………', promptAr: 'عندما تصل إلى البيت، …', lines: 2,
          accept: ['I will have cleaned the house from top to bottom.', 'I will have cleaned the house.', 'I will have cooked dinner.', 'I will have finished my homework.', 'I will have prepared lunch.', 'I will have left.'],
          model: 'I will have cleaned the house from top to bottom.', modelAr: 'سأكون قد نظّفتُ البيت من أعلاه إلى أسفله.',
          explainAr: 'By the time + مضارع بسيط (get) للمستقبل ← المستقبل التام will have + التصريف الثالث لحدث سيكتمل قبل ذلك الوقت (الوحدة 6). الجملة النموذجية من كتابك.' },
        { n: 37, kind: 'write', topic: 'conditional', prompt: 'If you run into any trouble, ……………………………', promptAr: 'إذا واجهتَ أيّ مشكلة، …', lines: 2,
          accept: ['just give me a call.', 'give me a call.', 'call me.', 'I will help you.', "I'll help you.", 'phone me.', 'just call me.'],
          model: 'just give me a call.', modelAr: 'اتّصل بي فحسب.',
          explainAr: 'If + مضارع بسيط، ثم جملة رئيسية بصيغة الأمر (give me a call) أو will + فعل. الجملة من كتابك (الوحدة 1، run into = يواجه مشكلة فجأة).' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: There is only one thing that makes a dream impossible to achieve: the fear of failure.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['هناك شيء واحد فقط يجعل الحلم مستحيل التحقيق: الخوف من الفشل', 'يوجد شيء واحد فقط يجعل تحقيق الحلم مستحيلاً وهو الخوف من الفشل', 'هناك شيء واحد فقط يجعل تحقيق الحلم مستحيلاً: الخوف من الفشل', 'لا يوجد إلا شيء واحد يجعل الحلم مستحيل التحقيق: الخوف من الفشل'],
          model: 'هناك شيءٌ واحدٌ فقط يجعل الحلمَ مستحيلَ التحقيق: الخوفُ من الفشل.',
          explainAr: 'الجملة من الوحدة 2 (النجاح) في كتابك. There is = يوجد / هناك، only one thing = شيء واحد فقط، makes a dream impossible to achieve = يجعل الحلم مستحيل التحقيق، the fear of failure = الخوف من الفشل.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: بُني المستشفى الجديد في مدينتنا العام الماضي.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['The new hospital in our city was built last year.', 'The new hospital was built in our city last year.', 'The new hospital in our town was built last year.', 'The new hospital was built in our town last year.'],
          model: 'The new hospital in our city was built last year.',
          explainAr: 'بُني ← was built (مبني للمجهول في الماضي البسيط: was + التصريف الثالث، الوحدة 3)، العام الماضي ← last year. نبدأ بالفاعل: The new hospital in our city.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Students’ rights and duties at school.',
        topicAr: 'حقوق الطلاب وواجباتهم في المدرسة.',
        words: 80,
        points: ['What are the duties of students?', 'What are the rights of students?', 'Why is it important for students to know their rights and duties?'],
        model: 'A man is born with rights and duties, and school is the first place where we learn them. Students have many duties. They should respect their teachers and classmates, obey the school rules, do their homework on time and keep their surroundings clean. At the same time, students have rights. They have the right to a free education, the right to learn in a clean and safe place, and the right to be treated fairly without discrimination. It is important for students to know their rights and duties because a student who knows them will become a responsible citizen in the future. In my opinion, rights and duties go together: we cannot enjoy our rights unless we do our duties.',
        modelAr: 'يولد الإنسان ومعه حقوق وواجبات، والمدرسة هي أول مكان نتعلّمها فيه. للطلاب واجبات كثيرة؛ فعليهم أن يحترموا معلّميهم وزملاءهم، ويطيعوا قوانين المدرسة، ويؤدّوا وظائفهم في وقتها، ويحافظوا على نظافة ما حولهم. وفي الوقت نفسه للطلاب حقوق؛ فلهم الحق في تعليم مجاني، والحق في التعلّم في مكان نظيف وآمن، والحق في أن يُعاملوا بعدل دون تمييز. ومن المهم أن يعرف الطلاب حقوقهم وواجباتهم لأن الطالب الذي يعرفها سيصبح مواطناً مسؤولاً في المستقبل. برأيي، الحقوق والواجبات متلازمة: لا نستطيع أن نتمتّع بحقوقنا إلا إذا أدّينا واجباتنا.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: واجبات الطلاب، وحقوقهم، ولماذا من المهم معرفتها.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (and, At the same time, because, In my opinion...).',
          'استخدمتُ should / have the right to للتعبير عن الواجبات والحقوق، وجملة صلة (a student who...).',
          'استخدمتُ كلمات من الوحدتين 5 و6 (rights, duties, discrimination, responsible, citizen...).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
