import type { Exam } from '../../../engine/types'

// A practice Term 1 paper in the exact layout of the real paper (term1-a), built only from Units 1–6.
// Passage A: Unit 4, "History of Engineering" (pages 38–39). Passage B: Unit 1, "Future Career" (second half, page 10).
export const term1D: Exam = {
  id: 't1-d',
  term: 1,
  title: 'Term 1 — Test (D)',
  titleAr: 'الفصل الأول — النموذج (D)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بشكل امتحان الفصل الأول الحقيقي تماماً، مبنيّ فقط من نصوص الوحدات 1–6 ومفرداتها وقواعدها.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'Throughout history, there have always been people who designed and built tools or other devices to solve problems or improve lives. The concept of engineering has been around since ancient times, as primitive engineers created basic inventions such as pulley, lever, and the wheel. Each of these inventions is consistent with a modern definition of engineering, and makes use of basic mechanical principles to develop useful tools and objects.',
          'Simple classic machines were known in the ancient Near East, and then the wheel, along with the wheel and axle mechanism, was invented in Mesopotamia (modern Iraq) during the fifth millennium BC. The oldest architect, known by name Imhotep, designed and executed the construction of the Pyramid of Djoser (a step pyramid) in the Saqqara region in Egypt around 2630-2611 BC, and he is also credited with first using columns in architecture. In Persia, the oldest practical water-powered machines appeared in the fourth century BC, the water wheel and the watermill.',
          'During the sixth century AD, the Indian engineers invented the cotton gin, and by the ninth century AD they designed wind-powered machines such as the windmill and the wind pump. Later, the Arab engineers designed the spinning wheel in the early eleventh century. This was essential to the growth of the cotton industry, which was the core of The Early Industrial Revolution in the 18th Century.',
        ],
        paragraphsAr: [
          'على مرّ التاريخ، كان هناك دائماً أشخاص صمّموا وبنوا أدوات أو أجهزة أخرى لحلّ المشكلات أو تحسين الحياة. ومفهوم الهندسة موجود منذ العصور القديمة، إذ ابتكر المهندسون البدائيون اختراعات أساسية مثل البكرة والرافعة والعجلة. وكلّ واحد من هذه الاختراعات يتّفق مع التعريف الحديث للهندسة، ويستفيد من المبادئ الميكانيكية الأساسية لتطوير أدوات وأشياء مفيدة.',
          'كانت الآلات البسيطة التقليدية معروفة في الشرق الأدنى القديم، ثم اختُرعت العجلة، ومعها آلية العجلة والمحور، في بلاد ما بين النهرين (العراق الحديث) خلال الألفية الخامسة قبل الميلاد. وأقدم مهندس معماري معروف بالاسم هو إمحوتب، الذي صمّم ونفّذ بناء هرم زوسر (هرم مدرّج) في منطقة سقّارة في مصر نحو 2630–2611 قبل الميلاد، ويُنسب إليه أيضاً أنه أول من استخدم الأعمدة في العمارة. وفي بلاد فارس ظهرت أقدم الآلات العملية التي تعمل بقوة الماء في القرن الرابع قبل الميلاد، وهي الناعورة والطاحونة المائية.',
          'خلال القرن السادس الميلادي اخترع المهندسون الهنود محلج القطن، وبحلول القرن التاسع الميلادي صمّموا آلات تعمل بقوة الرياح مثل طاحونة الهواء ومضخّة الرياح. وبعد ذلك صمّم المهندسون العرب دولاب الغزل في أوائل القرن الحادي عشر. وكان هذا أساسياً لنموّ صناعة القطن، التي كانت جوهر الثورة الصناعية المبكرة في القرن الثامن عشر.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'What did primitive engineers create in ancient times?', promptAr: 'ماذا ابتكر المهندسون البدائيون في العصور القديمة؟', lines: 2,
              accept: ['Primitive engineers created basic inventions such as pulley, lever, and the wheel.', 'They created basic inventions such as pulley, lever and the wheel.', 'They created basic inventions such as the pulley, the lever and the wheel.', 'They created the pulley, the lever and the wheel.', 'Basic inventions such as pulley, lever and the wheel.', 'Basic inventions such as the pulley, the lever and the wheel.', 'Pulley, lever and the wheel.'],
              modelAr: 'ابتكروا اختراعات أساسية مثل البكرة والرافعة والعجلة.',
              explainAr: 'الجواب في الجملة الثانية: "primitive engineers created basic inventions such as pulley, lever, and the wheel". السؤال بالماضي (did ... create) فنجيب بالماضي created.' },
            { n: 2, kind: 'write', prompt: 'What did Imhotep design?', promptAr: 'ماذا صمّم إمحوتب؟', lines: 2,
              accept: ['Imhotep designed the Pyramid of Djoser.', 'He designed the Pyramid of Djoser.', 'He designed and executed the construction of the Pyramid of Djoser.', 'He designed the Pyramid of Djoser in Egypt.', 'He designed the Pyramid of Djoser in the Saqqara region in Egypt.', 'The Pyramid of Djoser.', 'The Pyramid of Djoser in Egypt.'],
              modelAr: 'صمّم هرم زوسر (هرم مدرّج) في منطقة سقّارة في مصر.',
              explainAr: 'النص: "Imhotep, designed and executed the construction of the Pyramid of Djoser (a step pyramid) in the Saqqara region in Egypt". السؤال عن الشيء الذي صمّمه فنذكر اسم الهرم.' },
            { n: 3, kind: 'write', prompt: 'Why was the spinning wheel important?', promptAr: 'لماذا كان دولاب الغزل مهمّاً؟', lines: 3,
              accept: ['It was essential to the growth of the cotton industry.', 'Because it was essential to the growth of the cotton industry.', 'It was essential to the growth of the cotton industry, which was the core of the Early Industrial Revolution.', 'Because it was essential to the growth of the cotton industry, which was the core of the Early Industrial Revolution in the 18th century.', 'The spinning wheel was essential to the growth of the cotton industry.'],
              modelAr: 'لأنه كان أساسياً لنموّ صناعة القطن التي كانت جوهر الثورة الصناعية المبكرة.',
              explainAr: 'آخر جملة في النص: "This was essential to the growth of the cotton industry". كلمة This تعود على دولاب الغزل (the spinning wheel) المذكور في الجملة التي قبلها.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', topic: 'vocab', prompt: 'A piece of equipment consisting of a wheel over which a rope or chain is pulled to lift heavy things. ……..', promptAr: 'أداة مؤلّفة من عجلة يُسحب فوقها حبل أو سلسلة لرفع الأشياء الثقيلة', lines: 1,
              accept: ['pulley', 'a pulley'], modelAr: 'بكرة',
              explainAr: 'هذا تعريف كلمة pulley (البكرة) في تمرين المفردات في كتابك (الوحدة 4)، وهي في الجملة الثانية من النص. انتبه: lever (الرافعة) "آلة بسيطة لرفع شيء ثقيل" لكن ليس فيها عجلة ولا حبل.' },
            { n: 5, kind: 'write', topic: 'vocab', prompt: 'A period of one thousand years. ……..', promptAr: 'فترة من ألف سنة', lines: 1,
              accept: ['millennium', 'a millennium'], modelAr: 'ألفية',
              explainAr: 'millennium = ألفية (ألف سنة)، وهي في النص: "during the fifth millennium BC". لا تخلط بينها وبين century = قرن (مئة سنة).' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'The wheel was invented in Egypt during the fifth millennium BC.', promptAr: 'اختُرعت العجلة في مصر خلال الألفية الخامسة قبل الميلاد.', lines: 2,
              accept: ['The wheel was invented in Mesopotamia during the fifth millennium BC.', 'The wheel was invented in Mesopotamia (modern Iraq) during the fifth millennium BC.', 'The wheel was invented in Mesopotamia, modern Iraq, during the fifth millennium BC.', 'The wheel was invented in Mesopotamia.', 'The wheel was invented in Iraq during the fifth millennium BC.'],
              model: 'The wheel was invented in Mesopotamia (modern Iraq) during the fifth millennium BC.', modelAr: 'اختُرعت العجلة في بلاد ما بين النهرين (العراق الحديث) خلال الألفية الخامسة قبل الميلاد.',
              explainAr: 'النص: "the wheel ... was invented in Mesopotamia (modern Iraq)". الخطأ في المكان: Egypt، أما مصر فذُكرت مع إمحوتب وهرم زوسر.' },
            { n: 7, kind: 'write', prompt: 'The Arab engineers invented the cotton gin in the sixth century AD.', promptAr: 'اخترع المهندسون العرب محلج القطن في القرن السادس الميلادي.', lines: 2,
              accept: ['The Indian engineers invented the cotton gin in the sixth century AD.', 'The Indian engineers invented the cotton gin.', 'Indian engineers invented the cotton gin in the sixth century AD.', 'The Arab engineers designed the spinning wheel in the early eleventh century.', 'The Arab engineers designed the spinning wheel.'],
              model: 'The Indian engineers invented the cotton gin in the sixth century AD.', modelAr: 'اخترع المهندسون الهنود محلج القطن في القرن السادس الميلادي.',
              explainAr: 'النص: "During the sixth century AD, the Indian engineers invented the cotton gin". أما العرب فصمّموا دولاب الغزل (the spinning wheel) في القرن الحادي عشر. نصحّح بتغيير Arab إلى Indian.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'Although it should not be the most important, remuneration of a career holds value in one’s life; nobody likes to earn little. A job’s earnings should match the child’s aspirations and provide a satisfying comfortable life. Modern societies need professionals in every field: utility workers, garbage collectors, farmers, nurses, doctors, engineers, teachers, professors and many others.',
          'Furthermore, demotivation might have a negative impact on the child’s mental health when rejecting all of his/her ideas. Parents can work together to gather information about a career and then help the child in deciding whether it is suitable or not. Most people have dreams of future jobs and there’s no limit to what this could be, but we can\'t be absolutely certain about our career choices. Researchers told us that through self-reflection and guided activities, we would find our core values and a clearer path towards the right career.',
        ],
        paragraphsAr: [
          'مع أنه لا ينبغي أن يكون الأهمّ، فإن أجر المهنة له قيمة في حياة المرء؛ فلا أحد يحب أن يكسب القليل. وينبغي أن يتناسب دخل الوظيفة مع طموحات الطفل وأن يوفّر حياة مريحة مُرضية. وتحتاج المجتمعات الحديثة إلى مهنيّين في كل مجال: عمّال المرافق العامة، وعمّال جمع القمامة، والمزارعين، والممرضين، والأطباء، والمهندسين، والمعلمين، وأساتذة الجامعات وغيرهم كثير.',
          'علاوة على ذلك، قد يكون للإحباط (فقدان الحافز) أثر سلبي على صحة الطفل النفسية عندما تُرفض كل أفكاره. ويمكن للوالدين أن يتعاونا في جمع المعلومات عن مهنة ما ثم يساعدا الطفل في تقرير ما إذا كانت مناسبة له أم لا. لدى معظم الناس أحلام بوظائف مستقبلية ولا حدود لما يمكن أن تكون عليه، لكننا لا نستطيع أن نكون متأكدين تماماً من خياراتنا المهنية. وقد أخبرنا الباحثون أننا من خلال التأمّل الذاتي والأنشطة الموجَّهة سنجد قيمنا الجوهرية وطريقاً أوضح نحو المهنة المناسبة.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'According to the text, the remuneration of a career ……..', promptAr: 'بحسب النص، أجر المهنة ……..', options: ['should be the most important thing', 'has no value at all', 'holds value in one’s life', 'must be very little'], answer: 2,
              explainAr: 'النص: "Although it should not be the most important, remuneration of a career holds value in one’s life". فالجواب "holds value in one’s life". أما "should be the most important thing" فعكس ما يقوله النص (should not be the most important).' },
            { n: 9, kind: 'mcq', prompt: 'A job’s earnings should ……..', promptAr: 'ينبغي أن يكون دخل الوظيفة ……..', options: ['match the child’s aspirations', 'be the same in every field', 'be chosen by the child’s peers', 'be very little at the beginning'], answer: 0,
              explainAr: 'الجملة الثانية في النص: "A job’s earnings should match the child’s aspirations and provide a satisfying comfortable life". aspirations = طموحات.' },
            { n: 10, kind: 'mcq', prompt: 'Demotivation might have a negative impact on the child’s ……..', promptAr: 'قد يكون للإحباط أثر سلبي على ___ الطفل.', options: ['earnings', 'mental health', 'career choices', 'parents'], answer: 1,
              explainAr: 'النص: "demotivation might have a negative impact on the child’s mental health when rejecting all of his/her ideas" — أي الصحة النفسية "mental health".' },
            { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'Money paid for work or services is ……..', promptAr: 'المال المدفوع مقابل العمل أو الخدمات هو ……..', options: ['demotivation', 'aspiration', 'aptitude', 'remuneration'], answer: 3,
              explainAr: 'remuneration = الأجر / المكافأة المالية، وهذا تعريفها في كتابك (الوحدة 1). demotivation = فقدان الحافز، aspiration = طموح، aptitude = موهبة أو قدرة طبيعية.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'Parents can work together to ……………………', promptAr: 'يمكن للوالدين أن يتعاونا من أجل ……', lines: 2,
              accept: ['gather information about a career and then help the child in deciding whether it is suitable or not', 'gather information about a career and then help the child in deciding whether it is suitable or not.', 'gather information about a career', 'gather information about a career and help the child decide whether it is suitable or not'],
              model: 'gather information about a career and then help the child in deciding whether it is suitable or not.', modelAr: 'جمع المعلومات عن مهنة ما ثم مساعدة الطفل في تقرير ما إذا كانت مناسبة أم لا.',
              explainAr: 'النص: "Parents can work together to gather information about a career and then help the child in deciding whether it is suitable or not". انقل ما بعد to كما هو.' },
            { n: 13, kind: 'write', prompt: 'Through self-reflection and guided activities, we would find ……………………', promptAr: 'من خلال التأمّل الذاتي والأنشطة الموجَّهة سنجد ……', lines: 2,
              accept: ['our core values and a clearer path towards the right career', 'our core values and a clearer path towards the right career.', 'our core values', 'a clearer path towards the right career'],
              model: 'our core values and a clearer path towards the right career.', modelAr: 'قيمنا الجوهرية وطريقاً أوضح نحو المهنة المناسبة.',
              explainAr: 'آخر جملة في النص: "through self-reflection and guided activities, we would find our core values and a clearer path towards the right career".' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'A big part of my job is ……… the latest research in medical technology.', promptAr: 'جزء كبير من عملي هو ___ آخر الأبحاث في التكنولوجيا الطبية.', options: ['reaching out to', 'keeping up with', 'fitting in with', 'running into'], answer: 1,
          explainAr: 'keep up with = يبقى مطّلعاً على الجديد في شيء ما، والجملة نفسها في كتابك (الوحدة 1، الأفعال المركّبة). reach out to = يمدّ يد العون لـ، fit in with = يندمج مع مجموعة، run into = يواجه مشكلة فجأة.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'The woman ……… car was stolen called the police.', promptAr: 'المرأة التي سُرقت سيارتها اتصلت بالشرطة.', options: ['who', 'which', 'whose', 'where'], answer: 2,
          explainAr: 'whose للملكية: بعدها اسم مباشرة (whose car = التي سيارتُها). who للعاقل يليه فعل، which لغير العاقل، where للمكان (الوحدة 5، جمل الصلة).' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'His efforts didn’t work at all; I think his project is ………… now.', promptAr: 'لم تنجح جهوده أبداً؛ أظن أن مشروعه ___ الآن.', options: ['dead in the water', 'on a roll', 'on the mend', 'by the book'], answer: 0,
          explainAr: 'be dead in the water = فاشل ولا أمل في نجاحه (تعابير النجاح، الوحدة 2). on a roll = في سلسلة نجاحات، on the mend = يتحسّن بعد مرض، by the book = حسب القواعد تماماً.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'My father says everything looks blurry, so he is going to the ……… to get his eyes checked.', promptAr: 'يقول أبي إن كل شيء يبدو ضبابياً، لذلك سيذهب إلى ___ ليفحص عينيه.', options: ['dermatologist', 'pediatrician', 'allergist', 'ophthalmologist'], answer: 3,
          explainAr: 'ophthalmologist = طبيب العيون، والجملة من كتابك (الوحدة 3). dermatologist = طبيب الجلد، pediatrician = طبيب الأطفال، allergist = طبيب الحساسية.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'The “ed” in the word “needed” is pronounced as:', promptAr: 'تُلفظ "ed" في كلمة "needed":', options: ['/t/', '/id/', '/d/', '/n/'], answer: 1,
          explainAr: 'need تنتهي بصوت /d/، وبعد t و d تُلفظ ed مقطعاً كاملاً /id/ (مثل wanted و needed). بعد الأصوات المهموسة تُلفظ /t/، وبعد بقية الأصوات المجهورة /d/.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'When you take action, you ……… all kinds of things that will inevitably carry you to success.', promptAr: 'عندما تبدأ العمل فإنك ___ كل أنواع الأشياء التي ستحملك حتماً إلى النجاح.', options: ['sacrifice', 'elevate', 'trigger', 'deny'], answer: 2,
          explainAr: 'trigger = يُطلق / يُحرّك شيئاً ويبدؤه، والجملة من نص النجاح (الوحدة 2). sacrifice = يضحّي، elevate = يرفع، deny = ينكر أو يحرم.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'The vase fell ……… the table and shattered on the floor.', promptAr: 'سقطت المزهرية ___ الطاولة وتحطّمت على الأرض.', options: ['off', 'onto', 'into', 'to'], answer: 0,
          explainAr: 'حروف جر الحركة (الوحدة 4): off = عن سطح شيء (عكس onto). المزهرية كانت على الطاولة ثم سقطت عنها إلى الأرض، فالجواب off. onto = إلى سطح شيء، into = إلى داخل شيء.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'Which word is a homophone of “rode”?', promptAr: 'أيّ كلمة تُلفظ مثل "rode" تماماً (لها اللفظ نفسه ومعنى وتهجئة مختلفان)؟', options: ['ride', 'rod', 'rude', 'road'], answer: 3,
          explainAr: 'الكلمات المتجانسة لفظاً (homophones، الوحدة 1) لها اللفظ نفسه وتهجئة ومعنى مختلفان: rode (ماضي ride) و road (طريق) تُلفظان /rəʊd/. أما ride و rod و rude فلفظها مختلف.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'I went to a counselor for ……… on my career.', promptAr: 'ذهبتُ إلى مرشد من أجل ___ بخصوص مهنتي.', options: ['guide', 'guidance', 'guided', 'guiding'], answer: 1,
          explainAr: 'بعد حرف الجر for نحتاج اسماً: guidance = إرشاد/توجيه (الفعل guide + اللاحقة ance)، والجملة من كتابك (الوحدة 1). guided و guiding صيغ فعلية.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'tense', prompt: 'I ……… been using a computer for at least three years.', promptAr: 'أنا ___ أستخدم الحاسوب منذ ثلاث سنوات على الأقل.', lines: 1,
          accept: ['have', "'ve"], explainAr: 'المضارع التام المستمر: have/has + been + فعل ing، ومع I نستخدم have. كلمة for + مدة زمنية دليل على هذا الزمن (الوحدة 1).' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'Nothing happens ……… you take action.', promptAr: 'لا شيء يحدث ___ تبدأ العمل.', lines: 1,
          accept: ['until', 'till', 'unless'], explainAr: 'الجملة من نص النجاح (الوحدة 2): "Nothing happens until you take action" = لا يحدث شيء حتى تبدأ العمل. until تعني "حتى / إلى أن". وتُقبل unless (إلا إذا) لأن المعنى صحيح.' },
        { n: 25, kind: 'write', topic: 'tense', prompt: 'Did anything happen ……… you were watching TV?', promptAr: 'هل حدث شيء ___ كنتِ تشاهدين التلفاز؟', lines: 1,
          accept: ['while', 'when', 'as'], explainAr: 'نستخدم while (أو when) قبل الماضي المستمر للحدث الطويل الذي كان جارياً (were watching) عندما وقع حدث قصير (الوحدة 2).' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'Sofia has been teaching dancing {for three years}.', promptAr: 'تُدرّس صوفيا الرقص منذ ثلاث سنوات.', lines: 1,
          accept: ['How long has Sofia been teaching dancing?', 'How long has she been teaching dancing?'], modelAr: 'منذ متى تُدرّس صوفيا الرقص؟',
          explainAr: 'المسطَّر مدة زمنية (for three years) فنسأل بـ How long. نحافظ على الزمن (المضارع التام المستمر) ونقدّم has على الفاعل: How long has Sofia been teaching...؟' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'Suzan put on her raincoat {because it was raining}.', promptAr: 'لبست سوزان معطف المطر لأنها كانت تمطر.', lines: 1,
          accept: ['Why did Suzan put on her raincoat?', 'Why did Suzan put her raincoat on?', 'Why did she put on her raincoat?', 'Why did she put her raincoat on?'], modelAr: 'لماذا لبست سوزان معطف المطر؟',
          explainAr: 'المسطَّر سبب (because...) فنسأل بـ Why. الفعل put ماضٍ فنستخدم did ويبقى الفعل بصيغة المصدر put.' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'The first steam engine was built {in 1698} by Thomas Savery.', promptAr: 'بُني أول محرّك بخاري عام 1698 على يد توماس سافري.', lines: 1,
          accept: ['When was the first steam engine built?', 'When was the first steam engine built by Thomas Savery?', 'When did Thomas Savery build the first steam engine?'], modelAr: 'متى بُني أول محرّك بخاري؟',
          explainAr: 'المسطَّر تاريخ (in 1698) فنسأل بـ When. الجملة مبنية للمجهول في الماضي، فنقدّم was على الفاعل: When was ... built؟' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'grammar', prompt: 'A decorator has repaired our house. (causative verb)', promptAr: 'أصلح مزخرفٌ (دهّانٌ) بيتنا. (الفعل السببي)', lines: 2,
          accept: ['We have had our house repaired.', 'We have had our house repaired by a decorator.', 'We have got our house repaired.', 'We have got our house repaired by a decorator.'], model: 'We have had our house repaired by a decorator.', modelAr: 'أصلحنا بيتنا (عند دهّان).',
          explainAr: 'السببي: have + مفعول + التصريف الثالث (الوحدة 4). الفعل الأصلي مضارع تام (has repaired)، فنحافظ على الزمن: We have had our house repaired.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'Your father has got a new promotion at work. (Congratulate him)', promptAr: 'حصل أبوك على ترقية جديدة في العمل. (هنّئه)', lines: 2,
          accept: ['Congratulations!', 'Congratulations! We are proud of you.', 'Congratulations! You really deserve this honour.', 'Congratulations, Dad!', 'We are proud of you.', 'You really deserve this honour.', 'Very well done! Keep it up.', 'Well done! Keep it up.', 'Congratulations! Very well done! Keep it up.', 'Congratulations, Dad! We are proud of you.', 'Congratulations, Dad! You really deserve this honour.'],
          model: 'Congratulations! You really deserve this honour.', modelAr: 'مبارك! أنت تستحق هذا التكريم حقاً.',
          explainAr: 'تعابير التهنئة من الوحدة 2 (Everyday English): Congratulations! / We are proud of you. / You really deserve this honour. / Very well done! Keep it up. أما I’m sorry about what happened فهي للمواساة لا للتهنئة.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'The organizers will exhibit the paintings till the end of the month. (passive voice)', promptAr: 'سيعرض المنظّمون اللوحات حتى نهاية الشهر. (المبني للمجهول)', lines: 2,
          accept: ['The paintings will be exhibited till the end of the month.', 'The paintings will be exhibited by the organizers till the end of the month.', 'The paintings will be exhibited until the end of the month.', 'The paintings will be exhibited by the organizers until the end of the month.'],
          model: 'The paintings will be exhibited by the organizers till the end of the month.', modelAr: 'ستُعرض اللوحات حتى نهاية الشهر.',
          explainAr: 'المبني للمجهول في المستقبل: will be + التصريف الثالث (الوحدة 3). نبدأ بالمفعول (The paintings) ثم will be exhibited، ويمكن إضافة by the organizers.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Your friend asks you to join his football team, but you aren’t sure about your father’s opinion. (Express hesitation)', promptAr: 'يطلب منك صديقك الانضمام إلى فريقه لكرة القدم، لكنك لست متأكداً من رأي والدك. (عبّر عن التردّد)', lines: 2,
          accept: ["I'm not sure about that.", "I haven't made up my mind yet.", "I'll have to think about that.", "Oh, I don't know whether I could.", 'Perhaps I can.', "I can't decide yet.", "Well, I'm not sure about it.", "I'm not sure about it."],
          model: "I'm not sure about that. I'll have to think about that.", modelAr: 'لست متأكداً من ذلك. عليّ أن أفكّر في الأمر.',
          explainAr: 'تعابير التردّد وعدم التأكّد من الوحدة 4 (Everyday English): I’m not sure about that / I haven’t made up my mind yet / I’ll have to think about that / I can’t decide yet / Perhaps I can.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'Henry did very well in his exams, which was a shock because he ………. (not take) an exam before.', promptAr: 'أبلى هنري بلاءً حسناً في امتحاناته، وكان ذلك مفاجأة لأنه لم يكن قد قدّم امتحاناً من قبل.', lines: 1,
          accept: ['had not taken', "hadn't taken", 'had never taken'], explainAr: 'حدث سبق حدثاً آخر في الماضي (did very well) مع before: الماضي التام had + التصريف الثالث، والنفي had not taken (الوحدة 2).' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'Is that a new watch? Yes, I ………. (just / buy) it.', promptAr: 'هل هذه ساعة جديدة؟ نعم، اشتريتها للتو.', lines: 1,
          accept: ['have just bought', "'ve just bought"], explainAr: 'just مع حدث قريب لا نذكر وقته: المضارع التام have + just + التصريف الثالث (bought) (الوحدة 1).' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'I ………. (prepare) lunch when my husband came home.', promptAr: 'كنتُ أحضّر الغداء عندما عاد زوجي إلى البيت.', lines: 1,
          accept: ['was preparing'], explainAr: 'حدث طويل كان جارياً (أحضّر الغداء) قطعه حدث قصير بالماضي البسيط (came): الماضي المستمر was + فعل ing (الوحدة 2).' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'tense', prompt: 'By the time I got to the meeting, ……………………………', promptAr: 'عندما وصلتُ إلى الاجتماع، …', lines: 2,
          accept: ['they had discussed the important issues.', 'they had discussed the important issues and they had made the big decisions without me.', 'they had made the big decisions without me.', 'the meeting had finished.', 'the meeting had started.', 'everyone had left.', 'they had already started.'],
          model: 'they had discussed the important issues.', modelAr: 'كانوا قد ناقشوا القضايا المهمّة.',
          explainAr: 'By the time + ماضٍ بسيط (got) ← الماضي التام had + التصريف الثالث لحدث وقع قبله (الوحدة 2). الجملة النموذجية من كتابك.' },
        { n: 37, kind: 'write', topic: 'grammar', prompt: 'I can’t enjoy a job unless ……………………………', promptAr: 'لا أستطيع أن أستمتع بعمل إلا إذا …', lines: 2,
          accept: ['it is quite challenging.', 'it is challenging.', 'it is interesting.', 'it is quite interesting.', 'I like it.', 'I love it.', 'it has regular hours.'],
          model: 'it is quite challenging.', modelAr: 'كان فيه تحدٍّ كبير.',
          explainAr: 'unless = إلا إذا، ويأتي بعدها فعل مضارع بسيط مثبت (it is ...). الجملة من استبيان الوظائف في الوحدة 1: "I can’t enjoy a job unless it is quite challenging."' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: Life is a matter of choices, and every choice you make makes you.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['الحياة مسألة اختيارات، وكل اختيار تتخذه يصنعك', 'الحياة مسألة خيارات، وكل خيار تتخذه يصنعك', 'الحياة مسألة اختيارات وكل اختيار تقوم به يصنعك'],
          model: 'الحياة مسألة اختيارات، وكل اختيار تتخذه يصنعك.',
          explainAr: 'المقولة من كتابك (الوحدة 1، صفحة الكتابة). a matter of = مسألة، choices = اختيارات، every choice you make = كل اختيار تتخذه، makes you = يصنعك (يشكّل شخصيتك).' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: يجب على الآباء أن يساعدوا أطفالهم في اختيار مهنتهم المستقبلية.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['Parents should help their children choose their future career.', 'Parents should help their children to choose their future career.', 'Parents should help their children in choosing their future career.', 'Parents must help their children choose their future career.', 'Parents must help their children to choose their future career.', 'Parents have to help their children choose their future career.', 'Parents have to help their children to choose their future career.', 'Parents should help their children choose their future job.', 'Parents should help their children choose their future careers.'],
          model: 'Parents should help their children choose their future career.',
          explainAr: 'يجب ← should (أو must / have to)، الآباء ← Parents، يساعدوا أطفالهم ← help their children، في اختيار ← choose (أو to choose / in choosing)، مهنتهم المستقبلية ← their future career (من نص الوحدة 1).' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'The role of engineering in our life.',
        topicAr: 'دور الهندسة في حياتنا.',
        words: 80,
        points: ['Advantages of engineering', 'Public health and safety', 'Technology and quality of life'],
        model: 'Engineering has played a vital part in people’s lives, and it has become a must for improving our life. Throughout history, engineers have designed and built tools and machines to solve problems. Today they build our houses, roads and bridges, so we can live and travel easily. Engineering also protects public health and safety. Civil engineers build safe buildings and dams, and engineers check machines over and do their maintenance so that they work well. Moreover, technology has improved our quality of life. Computer engineers have created search engines, so we can keep up with the latest news in seconds. In my opinion, the brilliant minds of engineers are still creating whatever it takes to make our world a better place to live.',
        modelAr: 'أدّت الهندسة دوراً حيوياً في حياة الناس، وأصبحت ضرورة لتحسين حياتنا. فعلى مرّ التاريخ صمّم المهندسون وبنوا أدوات وآلات لحلّ المشكلات. واليوم يبنون بيوتنا وطرقنا وجسورنا، فنعيش ونتنقّل بسهولة. وتحمي الهندسة أيضاً الصحة العامة والسلامة؛ فالمهندسون المدنيون يبنون مباني وسدوداً آمنة، والمهندسون يفحصون الآلات ويقومون بصيانتها كي تعمل جيداً. علاوة على ذلك، حسّنت التكنولوجيا جودة حياتنا؛ فقد أنشأ مهندسو الحاسوب محرّكات البحث، فصرنا نتابع آخر الأخبار في ثوانٍ. برأيي، ما زالت عقول المهندسين اللامعة تبتكر كل ما يلزم لجعل عالمنا مكاناً أفضل للعيش.',
        checklistAr: [
          'تناولتُ النقاط الثلاث: فوائد الهندسة، والصحة العامة والسلامة، والتكنولوجيا وجودة الحياة.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (also, Moreover, so, In my opinion...).',
          'استخدمتُ الأزمنة بشكل صحيح (المضارع التام has played / have created، والمضارع البسيط للحقائق).',
          'استخدمتُ كلمات من الوحدة 4 (maintenance, design, check over, engineer...).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
