import type { Exam } from '../../../engine/types'

// A practice final Baccalaureate paper in the exact layout of the real paper (term1-a.ts), covering the whole book (Units 1–12).
// Passage A: Unit 12 reading "E-government" (Digital Literacy), second part (page 117).
// Passage B: Unit 8 reading "Human Body", second part — from "The backbone supports…" to the end (pages 75–76).
export const term2E: Exam = {
  id: 't2-e',
  term: 2,
  title: 'Baccalaureate — Final Test (E)',
  titleAr: 'نموذج البكالوريا النهائي (E)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان البكالوريا الحقيقي، يغطي الكتاب كاملاً (الوحدات 1–12).',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'E-government services have three classifications. Firstly, Government-to-Government (G2G) involves sharing data and conducting electronic exchanges between governmental sectors, as well as exchanges between the national, regional, and local levels. Secondly, Government-to-Business (G2B) includes business-specific transactions (e.g. payments, sale and purchase of goods and services) as well as delivery online of business-focused services. Finally, Government-to-Consumer (G2C) comprises initiatives designed to simplify people’s interaction with the government as consumers of public services and contribute to the consultation and decision-making process.',
          'In recent years, Syria has adopted this new technology to facilitate public services for its citizens. This requires links to governmental organisations that supply services and information such as governmental documents, fees, etc. electronically. Various ministries are working on completing the data-entry process. This will pave the way to have more e-services. Many observers, experts and politicians expect that Syria will witness a great progress in all fields in the coming years.',
        ],
        paragraphsAr: [
          'لخدمات الحكومة الإلكترونية ثلاثة تصنيفات. أولاً، خدمات "من الحكومة إلى الحكومة" (G2G) وتشمل تبادل البيانات وإجراء المبادلات الإلكترونية بين القطاعات الحكومية، إضافةً إلى المبادلات بين المستويات الوطنية والإقليمية والمحلية. ثانياً، خدمات "من الحكومة إلى قطاع الأعمال" (G2B) وتشمل المعاملات الخاصة بالأعمال (مثل المدفوعات وبيع السلع والخدمات وشرائها) إضافةً إلى تقديم الخدمات الموجّهة لقطاع الأعمال عبر الإنترنت. وأخيراً، خدمات "من الحكومة إلى المستهلك" (G2C) وتضمّ مبادرات مصمَّمة لتبسيط تعامل الناس مع الحكومة بوصفهم مستهلكين للخدمات العامة، وللمساهمة في عملية التشاور واتخاذ القرار.',
          'في السنوات الأخيرة، تبنّت سوريا هذه التقنية الجديدة لتسهيل الخدمات العامة لمواطنيها. ويتطلّب ذلك روابط بالمؤسسات الحكومية التي تقدّم الخدمات والمعلومات، كالوثائق الحكومية والرسوم وغيرها، إلكترونياً. وتعمل وزارات مختلفة على استكمال عملية إدخال البيانات، وهذا سيمهّد الطريق لمزيد من الخدمات الإلكترونية. ويتوقّع كثير من المراقبين والخبراء والسياسيين أن تشهد سوريا تقدّماً كبيراً في جميع المجالات في السنوات القادمة.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'What does Government-to-Government (G2G) involve?', promptAr: 'ماذا تشمل خدمات "من الحكومة إلى الحكومة" (G2G)؟', lines: 3,
              accept: ['It involves sharing data and conducting electronic exchanges between governmental sectors, as well as exchanges between the national, regional, and local levels.', 'Government-to-Government involves sharing data and conducting electronic exchanges between governmental sectors, as well as exchanges between the national, regional and local levels.', 'It involves sharing data and conducting electronic exchanges between governmental sectors.', 'Sharing data and conducting electronic exchanges between governmental sectors.'],
              modelAr: 'تشمل تبادل البيانات وإجراء المبادلات الإلكترونية بين القطاعات الحكومية، وبين المستويات الوطنية والإقليمية والمحلية.',
              explainAr: 'الجواب في الجملة الثانية: "Firstly, Government-to-Government (G2G) involves sharing data and conducting electronic exchanges between governmental sectors...". ابدأ جوابك بـ It involves ثم انقل المعلومة.' },
            { n: 2, kind: 'write', prompt: 'What does Government-to-Consumer (G2C) comprise?', promptAr: 'ماذا تضمّ خدمات "من الحكومة إلى المستهلك" (G2C)؟', lines: 3,
              accept: ['It comprises initiatives designed to simplify people’s interaction with the government as consumers of public services and contribute to the consultation and decision-making process.', 'It comprises initiatives designed to simplify people’s interaction with the government as consumers of public services.', 'Initiatives designed to simplify people’s interaction with the government as consumers of public services.', 'It comprises initiatives designed to simplify people’s interaction with the government.'],
              modelAr: 'تضمّ مبادرات مصمَّمة لتبسيط تعامل الناس مع الحكومة بوصفهم مستهلكين للخدمات العامة، وللمساهمة في التشاور واتخاذ القرار.',
              explainAr: 'آخر جملة في الفقرة الأولى: "Finally, Government-to-Consumer (G2C) comprises initiatives designed to simplify people’s interaction with the government...". comprise = يضمّ/يتألّف من.' },
            { n: 3, kind: 'write', prompt: 'What will pave the way to have more e-services in Syria?', promptAr: 'ما الذي سيمهّد الطريق لمزيد من الخدمات الإلكترونية في سوريا؟', lines: 2,
              accept: ['Completing the data-entry process will pave the way to have more e-services.', 'Completing the data-entry process.', 'The work of various ministries on completing the data-entry process.', 'Various ministries are working on completing the data-entry process, and this will pave the way to have more e-services.'],
              modelAr: 'استكمال عملية إدخال البيانات (الذي تعمل عليه وزارات مختلفة).',
              explainAr: 'النص: "Various ministries are working on completing the data-entry process. This will pave the way to have more e-services." الضمير This يعود على استكمال عملية إدخال البيانات.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'The act of buying something ……..', promptAr: 'فعل شراء شيء ما', lines: 1, topic: 'vocab',
              accept: ['purchase'], modelAr: 'الشراء', explainAr: 'في النص "sale and purchase of goods and services" — بيع السلع وشراؤها. purchase = الشراء، وهي من كلمات الوحدة 12.' },
            { n: 5, kind: 'write', prompt: 'Discussion with a group of people before making a decision ……..', promptAr: 'نقاش مع مجموعة من الناس قبل اتخاذ قرار', lines: 1, topic: 'vocab',
              accept: ['consultation'], modelAr: 'التشاور', explainAr: 'في النص "contribute to the consultation and decision-making process". consultation = التشاور (من الفعل consult).' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'Payments and the sale and purchase of goods are included in Government-to-Consumer (G2C) services.', promptAr: 'المدفوعات وبيع السلع وشراؤها من ضمن خدمات "من الحكومة إلى المستهلك" (G2C).', lines: 2,
              accept: ['Payments and the sale and purchase of goods are included in Government-to-Business (G2B) services.', 'Payments and the sale and purchase of goods are included in Government-to-Business services.', 'Payments and the sale and purchase of goods are included in G2B services.'],
              modelAr: 'المدفوعات وبيع السلع وشراؤها من ضمن خدمات "من الحكومة إلى قطاع الأعمال" (G2B).',
              explainAr: 'النص: "Government-to-Business (G2B) includes business-specific transactions (e.g. payments, sale and purchase of goods and services)". فالخطأ هو Government-to-Consumer، والصواب Government-to-Business.' },
            { n: 7, kind: 'write', prompt: 'Many observers, experts and politicians expect that Syria will witness little progress in the coming years.', promptAr: 'يتوقّع كثير من المراقبين والخبراء والسياسيين أن تشهد سوريا تقدّماً ضئيلاً في السنوات القادمة.', lines: 2,
              accept: ['Many observers, experts and politicians expect that Syria will witness a great progress in all fields in the coming years.', 'Many observers, experts and politicians expect that Syria will witness great progress in all fields in the coming years.', 'They expect that Syria will witness a great progress in all fields in the coming years.', 'Many observers, experts and politicians expect that Syria will witness a great progress in the coming years.'],
              modelAr: 'يتوقّع كثير من المراقبين والخبراء والسياسيين أن تشهد سوريا تقدّماً كبيراً في جميع المجالات في السنوات القادمة.',
              explainAr: 'آخر جملة في النص: "Many observers, experts and politicians expect that Syria will witness a great progress in all fields in the coming years." فالخطأ little والصواب a great ... in all fields.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'The backbone supports the head and limbs and protects the spinal cord. Between the skeleton and the skin, there are about 500 muscles. Nerves spread from the brain to all parts of the body, carrying signals in the form of tiny electrical impulses. The sense organs namely eyes, nose, ears, tongue and skin pass the messages to the brain through nerves, which take the instructions from the brain to the muscles. The brain automatically controls breathing, heartbeat, digestion, etc.',
          'The body keeps on growing. The peak of physical growth is reached at about 18 to 25 years of age. When we grow old, the skin becomes wrinkled and less elastic, the joints become inflexible, muscles loose, and bones become weak.',
          'Here are some tips for aging gracefully: be kind to your skin which is your largest organ. You should also keep your salt intake to a minimum to keep your blood pressure down. Also, getting enough sleep has been proved to lower the risk of heart disease and stroke.',
        ],
        paragraphsAr: [
          'يدعم العمود الفقري الرأس والأطراف ويحمي الحبل الشوكي. وبين الهيكل العظمي والجلد توجد نحو 500 عضلة. وتمتدّ الأعصاب من الدماغ إلى جميع أجزاء الجسم حاملةً إشارات على شكل نبضات كهربائية دقيقة. وتنقل أعضاء الحسّ، وهي العينان والأنف والأذنان واللسان والجلد، الرسائل إلى الدماغ عبر الأعصاب، التي تنقل التعليمات من الدماغ إلى العضلات. ويتحكّم الدماغ تلقائياً في التنفّس ونبض القلب والهضم وغير ذلك.',
          'يستمرّ الجسم في النموّ، ويبلغ ذروة نموّه الجسدي في نحو الثامنة عشرة إلى الخامسة والعشرين من العمر. وعندما نتقدّم في السنّ يصبح الجلد مجعّداً وأقلّ مرونة، وتصبح المفاصل متصلّبة، وترتخي العضلات، وتضعف العظام.',
          'وإليك بعض النصائح لتتقدّم في السنّ بصحة جيدة: اعتنِ بجلدك فهو أكبر أعضائك. وعليك أيضاً أن تقلّل ما تتناوله من الملح إلى أدنى حدّ كي يبقى ضغط دمك منخفضاً. كما ثبت أن النوم الكافي يقلّل خطر الإصابة بأمراض القلب والسكتة الدماغية.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'The sense organs pass the messages to the brain through ……..', promptAr: 'تنقل أعضاء الحسّ الرسائل إلى الدماغ عبر ……..', options: ['bones', 'nerves', 'joints', 'the backbone'], answer: 1,
              explainAr: 'النص: "The sense organs namely eyes, nose, ears, tongue and skin pass the messages to the brain through nerves". أما العظام والمفاصل فهي للهيكل والحركة، والعمود الفقري يدعم الرأس والأطراف.' },
            { n: 9, kind: 'mcq', prompt: 'According to the text, the backbone ……..', promptAr: 'بحسب النص، العمود الفقري ……..', options: ['controls breathing and heartbeat', 'keeps water and harmful germs out', 'passes the messages to the brain', 'supports the head and limbs and protects the spinal cord'], answer: 3,
              explainAr: 'النص: "The backbone supports the head and limbs and protects the spinal cord." أما التحكّم في التنفّس ونبض القلب فهو عمل الدماغ، ونقل الرسائل إلى الدماغ عمل أعضاء الحسّ والأعصاب.' },
            { n: 10, kind: 'mcq', prompt: 'When we grow old, ……..', promptAr: 'عندما نتقدّم في السنّ ……..', options: ['the joints become more flexible', 'bones become stronger', 'the skin becomes wrinkled and less elastic', 'muscles become tighter'], answer: 2,
              explainAr: 'النص: "When we grow old, the skin becomes wrinkled and less elastic, the joints become inflexible, muscles loose, and bones become weak." فالمفاصل تتصلّب لا تصبح أكثر مرونة، والعظام تضعف لا تقوى، والعضلات ترتخي.' },
            { n: 11, kind: 'mcq', prompt: 'A word in the text which means “capable of stretching” is ……..', promptAr: 'كلمة في النص تعني "قابل للتمدّد" هي ……..', options: ['elastic', 'wrinkled', 'inflexible', 'loose'], answer: 0, topic: 'vocab',
              explainAr: 'elastic = مرن قابل للتمدّد (من تمرين المفردات في الوحدة 8). wrinkled = مجعّد فيه خطوط وثنيات، inflexible = غير مرن/متصلّب، loose = يرتخي.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'Nerves spread from the brain to all parts of the body, carrying ……………………', promptAr: 'تمتدّ الأعصاب من الدماغ إلى جميع أجزاء الجسم حاملةً ……', lines: 2,
              accept: ['signals in the form of tiny electrical impulses', 'signals in the form of electrical impulses', 'signals'],
              modelAr: 'إشارات على شكل نبضات كهربائية دقيقة.',
              explainAr: 'النص: "Nerves spread from the brain to all parts of the body, carrying signals in the form of tiny electrical impulses."' },
            { n: 13, kind: 'write', prompt: 'You should keep your salt intake to a minimum to ……………………', promptAr: 'عليك أن تقلّل ما تتناوله من الملح إلى أدنى حدّ كي ……', lines: 2,
              accept: ['keep your blood pressure down', 'keep blood pressure down', 'keep your blood pressure low'],
              modelAr: 'يبقى ضغط دمك منخفضاً.',
              explainAr: 'النص: "You should also keep your salt intake to a minimum to keep your blood pressure down." بعد to نكتب الفعل في مصدره: keep.' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'When are you ……… to Syria?', promptAr: 'متى ___ إلى سوريا؟', options: ['picking up', 'getting out', 'putting on', 'coming back'], answer: 3,
          explainAr: 'come back = يعود، وهو فعل مركّب بمعنى حرفي من الوحدة 12، والجملة من كتابك. pick up = يلتقط، get out = يُخرج، put on = يرتدي.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'February 7 is the day ……… I met my best friend.', promptAr: 'السابع من شباط هو اليوم ___ التقيتُ فيه بأعزّ أصدقائي.', options: ['when', 'where', 'which', 'whose'], answer: 0,
          explainAr: 'بعد اسم يدل على زمن (the day) ويليه جملة كاملة (I met my best friend) نستخدم when، والجملة من مراجعة الوحدة 2 في كتابك. where للمكان، which تحتاج جملة ينقصها فاعل أو مفعول، whose للملكية.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'The man was forced to quit his job after it was discovered that he had ……… .', promptAr: 'أُجبر الرجل على ترك عمله بعد أن اكتُشف أنه ___ .', options: ['assembled the case', 'broken the law', 'been an act of God', 'gone by the book'], answer: 1,
          explainAr: 'break the law = يخالف القانون (تعابير القانون في الوحدة 5)، والجملة من كتابك. assemble the case = يجمع الأدلة في قضية، an act of God = قضاء وقدر (كارثة طبيعية)، by the book = حسب القواعد تماماً.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'The state of being decayed or destroyed is called ……… .', promptAr: 'حالة الخراب أو الدمار تُسمّى ___ .', options: ['disparity', 'ratification', 'devastation', 'charter'], answer: 2,
          explainAr: 'devastation = الدمار/الخراب، وهي من كلمات نص الأمم المتحدة في الوحدة 6 (the devastation caused by the spread of AIDS). disparity = تفاوت، ratification = المصادقة، charter = ميثاق.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'In which word is the letter “w” silent?', promptAr: 'في أي كلمة يكون حرف "w" صامتاً (لا يُلفظ)؟', options: ['window', 'away', 'swim', 'wrong'], answer: 3,
          explainAr: 'الحروف الصامتة (الوحدة 7): حرف w لا يُلفظ غالباً قبل r في أول الكلمة، كما في wrong و write، وكذلك في answer و whole. أما في window و away و swim فيُلفظ w.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'The carpenter has used a special hammer to ……… the nails into the finished doors.', promptAr: 'استخدم النجّار مطرقة خاصة لـ ___ المسامير في الأبواب المُنجزة.', options: ['drive', 'jack', 'shore', 'check'], answer: 0,
          explainAr: 'drive something into = يدقّ شيئاً في شيء آخر بالطَّرق، والجملة من كتابك (الوحدة 4). jack up = يرفع بالرافعة، shore up = يدعم كي لا يسقط، check over = يفحص بحثاً عن عيوب.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'The parents were proud ……… their child’s achievement.', promptAr: 'كان الوالدان فخورين ___ إنجاز طفلهما.', options: ['for', 'of', 'with', 'at'], answer: 1,
          explainAr: 'صفات يليها حرف جر ثابت (الوحدة 9): proud of = فخور بـ، والجملة من كتابك. قارن: grateful for، angry with، good at.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'In which question does the speaker’s voice fall at the end?', promptAr: 'في أي سؤال ينخفض صوت المتكلّم في نهايته؟', options: ['Are you going to the party tonight?', 'Have you got a pen?', 'Where do you live?', 'Do you like pop music?'], answer: 2,
          explainAr: 'التنغيم في الأسئلة (الوحدة 10): في أسئلة wh- مثل "Where do you live?" يرتفع الصوت ثم ينخفض على آخر كلمة مهمة (falling intonation). أما أسئلة Yes/No مثل Are you… و Have you… و Do you… فيرتفع فيها الصوت في النهاية.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Some citizens take an ……… role in the community.', promptAr: 'يؤدّي بعض المواطنين دوراً ___ في المجتمع.', options: ['act', 'action', 'actively', 'active'], answer: 3,
          explainAr: 'قبل الاسم role نحتاج صفة: active = فعّال/نشيط، والجملة من تمرين عائلة الكلمة في الوحدة 9. act فعل، action اسم، actively ظرف.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'If only they ……… asked you for help before they started.', promptAr: 'ليتهم طلبوا مساعدتك قبل أن يبدؤوا.', lines: 1,
          accept: ['had'], explainAr: 'If only مثل I wish (الوحدة 8): للندم على الماضي نستخدم الماضي التام had + التصريف الثالث (asked). والجملة من المراجعة 2 في كتابك.' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'She suddenly turned and crashed ……… the fence.', promptAr: 'استدارت فجأة واصطدمت بالسياج.', lines: 1,
          accept: ['into'], explainAr: 'حروف جر الحركة (الوحدة 4): crash into = يصطدم بـ (يتحرّك نحو شيء ويدخل فيه)، والجملة من تمرين كتابك.' },
        { n: 25, kind: 'write', topic: 'grammar', prompt: 'Food ……… grown all over the country.', promptAr: 'يُزرع الطعام في كل أنحاء البلاد.', lines: 1,
          accept: ['is'], explainAr: 'المبني للمجهول في المضارع البسيط (الوحدة 3 والمراجعة 1): am/is/are + التصريف الثالث. Food مفرد غير معدود فنستخدم is.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'Our boss often loses his temper {when things go wrong}.', promptAr: 'كثيراً ما يفقد مديرنا أعصابه عندما تسوء الأمور.', lines: 1,
          accept: ['When does your boss lose his temper?', 'When does your boss often lose his temper?'], modelAr: 'متى يفقد مديركم أعصابه؟',
          explainAr: 'المسطَّر يدل على زمن (when + جملة) فنسأل بـ When. الفعل loses مضارع بسيط مع مفرد فنستخدم does ويعود الفعل إلى مصدره lose، ونغيّر Our إلى your.' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'Before hospitals developed, patients were treated mostly {in temples}.', promptAr: 'قبل أن تتطوّر المستشفيات كان المرضى يُعالَجون غالباً في المعابد.', lines: 1,
          accept: ['Where were patients treated mostly before hospitals developed?', 'Where were patients mostly treated before hospitals developed?', 'Where were patients treated before hospitals developed?', 'Before hospitals developed, where were patients treated mostly?', 'Where were patients treated mostly?'], modelAr: 'أين كان المرضى يُعالَجون غالباً قبل أن تتطوّر المستشفيات؟',
          explainAr: 'المسطَّر (in temples) مكان فنسأل بـ Where. الفعل مبني للمجهول في الماضي (were treated) فنقدّم were على الفاعل: Where were patients treated...?' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: '{Mr. Bshara’s} friend has had a bad fall.', promptAr: 'تعرّض صديق السيد بشارة لسقطة سيئة.', lines: 1,
          accept: ['Whose friend has had a bad fall?'], modelAr: 'صديقُ مَن تعرّض لسقطة سيئة؟',
          explainAr: 'المسطَّر يدل على الملكية (Mr. Bshara’s) فنسأل بـ Whose + الاسم. وبما أن السؤال عن الفاعل فلا نضيف فعلاً مساعداً ويبقى الترتيب: Whose friend has had...?' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'conditional', prompt: 'I haven’t got enough time, so I can’t visit my aunt in the next town. (conditional type II)', promptAr: 'ليس لديّ وقت كافٍ، لذلك لا أستطيع زيارة عمّتي في البلدة المجاورة. (الشرطية من النوع الثاني)', lines: 2,
          accept: ['If I had enough time, I would visit my aunt in the next town.', 'If I had enough time, I could visit my aunt in the next town.', 'If I had got enough time, I would visit my aunt in the next town.', 'If I had got enough time, I could visit my aunt in the next town.', 'I would visit my aunt in the next town if I had enough time.', 'I could visit my aunt in the next town if I had enough time.'],
          model: 'If I had enough time, I would visit my aunt in the next town.', modelAr: 'لو كان لديّ وقت كافٍ لزرتُ عمّتي في البلدة المجاورة.',
          explainAr: 'الشرطية الثانية لموقف تخيّلي في الحاضر (الوحدة 7): If + ماضٍ بسيط، would/could + المصدر. الجملة الأصلية منفية فتصبح مثبتة: haven’t got ← had، can’t visit ← would (could) visit. والموقف من مراجعة الوحدة 2.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'I regret that I started smoking. (Use: I wish)', promptAr: 'أندم على أنني بدأت التدخين. (استخدم: I wish)', lines: 2,
          accept: ['I wish I hadn’t started smoking.', 'I wish I had not started smoking.', 'I wish I had never started smoking.'],
          modelAr: 'ليتني لم أبدأ التدخين.',
          explainAr: 'التمنّي عن الماضي (الوحدة 8): I wish + ماضٍ تام. الشخص بدأ التدخين فعلاً ويندم، فنعكس المعنى إلى النفي: I wish I hadn’t started smoking. والجملة نفسها في كتابك.' },
        { n: 31, kind: 'write', topic: 'reported', prompt: '“Have you ever been to London?” he asked me. (reported speech)', promptAr: '"هل زرت لندن من قبل؟" سألني. (الكلام المنقول)', lines: 2,
          accept: ['He asked me if I had ever been to London.', 'He asked me whether I had ever been to London.', 'He wanted to know if I had ever been to London.', 'He wanted to know whether I had ever been to London.'],
          modelAr: 'سألني إن كنت قد زرت لندن من قبل.',
          explainAr: 'نقل سؤال Yes/No (الوحدة 11): asked + if/whether + فاعل + فعل (بلا قلب). نرجع الزمن خطوة: have been ← had been، ونغيّر you إلى I.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'The government has also established special banks for giving loans to farmers. (passive voice)', promptAr: 'أنشأت الحكومة أيضاً مصارف خاصة لمنح القروض للمزارعين. (المبني للمجهول)', lines: 2,
          accept: ['Special banks have also been established for giving loans to farmers.', 'Special banks have also been established by the government for giving loans to farmers.', 'Special banks have been established for giving loans to farmers.', 'Special banks have also been established for giving loans to farmers by the government.'],
          modelAr: 'أُنشئت أيضاً مصارف خاصة لمنح القروض للمزارعين.',
          explainAr: 'المبني للمجهول في المضارع التام (الوحدة 3 والمراجعة 1): have/has been + التصريف الثالث. المفعول special banks جمع فنقول have been established، ويبقى also بعد have.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'I’m sorry this office is so dirty, but it ………. (can’t / clean) until tomorrow morning.', promptAr: 'آسف لأن هذا المكتب متّسخ جداً، لكن لا يمكن تنظيفه قبل صباح الغد.', lines: 1,
          accept: ['can’t be cleaned', 'cannot be cleaned', 'can not be cleaned'], explainAr: 'المبني للمجهول مع فعل ناقص (الوحدة 3): can’t + be + التصريف الثالث (cleaned)، لأن المكتب لا يُنظِّف بل يُنظَّف. والجملة من تمرين كتابك.' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'Ahlam Mestaghanmi ………. (write) some of the best novels in recent years.', promptAr: 'كتبت أحلام مستغانمي بعضاً من أفضل الروايات في السنوات الأخيرة.', lines: 1,
          accept: ['has written'], explainAr: 'in recent years تدل على المضارع التام (فترة ممتدّة حتى الآن): has + التصريف الثالث written. والجملة من المراجعة 1 في كتابك.' },
        { n: 35, kind: 'write', topic: 'conditional', prompt: 'If I ………. (have) enough money, I would buy a Ferrari.', promptAr: 'لو كان لديّ ما يكفي من المال لاشتريت سيارة فيراري.', lines: 1,
          accept: ['had'], explainAr: 'الشرطية الثانية لموقف تخيّلي في الحاضر (الوحدة 7): If + ماضٍ بسيط (had)، would + المصدر (would buy).' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'tense', prompt: 'As soon as the plane lands, …………………………..', promptAr: 'بمجرد أن تهبط الطائرة، …', lines: 2,
          accept: ['I will call my parents.', 'I will phone my family.', 'we will take a taxi to the hotel.', 'I will send you a message.', 'I’ll ring you.'], model: 'I will call my parents.', modelAr: 'سأتّصل بوالديّ.',
          explainAr: 'بعد As soon as يأتي المضارع البسيط (lands) بمعنى المستقبل، والجملة الرئيسية بالمستقبل البسيط: will + المصدر.' },
        { n: 37, kind: 'write', topic: 'tense', prompt: 'By the time I finish university, …………………………..', promptAr: 'بحلول الوقت الذي أُنهي فيه الجامعة، …', lines: 2,
          accept: ['I will have learned a lot.', 'I will have learnt three languages.', 'I will have written my CV.', 'I will have found a job.', 'I will have got a lot of experience.'], model: 'I will have learned a lot.', modelAr: 'سأكون قد تعلّمتُ الكثير.',
          explainAr: 'By the time + مضارع بسيط (finish) بمعنى المستقبل ← المستقبل التام في الجملة الرئيسية: will have + التصريف الثالث لحدث سيكتمل قبل ذلك الوقت (الوحدة 6).' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: Everyone has to find his or her own balance between the values of home country and those of the host country.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['على كل شخص أن يجد توازنه الخاص بين قيم وطنه الأم وقيم البلد المضيف', 'يجب على كل إنسان أن يجد توازنه الخاص بين قيم بلده الأصلي وقيم البلد المضيف', 'على كل فرد أن يجد التوازن الخاص به بين قيم وطنه وقيم البلد المضيف'],
          model: 'على كل شخص أن يجد توازنه الخاص بين قيم وطنه الأم وقيم البلد المضيف.',
          explainAr: 'الجملة من كتابك (الوحدة 10، نص الصدمة الثقافية). has to = يجب/عليه، his or her own balance = توازنه الخاص، home country = الوطن الأم، host country = البلد المضيف، those = قيم (بدل تكرار values).' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: بُنيت مدارس كثيرة في مدينتنا في السنوات الأخيرة.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['Many schools have been built in our city in recent years.', 'A lot of schools have been built in our city in recent years.', 'Many schools have been built in our city recently.', 'Many new schools have been built in our city in recent years.', 'Many schools were built in our city in recent years.'],
          model: 'Many schools have been built in our city in recent years.',
          explainAr: 'بُنيت ← مبني للمجهول، و"في السنوات الأخيرة" تدل على المضارع التام: have been + built. مدارس كثيرة ← many schools (جمع فنستخدم have).' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Environmental health: keeping public places healthy.',
        topicAr: 'صحة البيئة: الحفاظ على الأماكن العامة صحية.',
        words: 80,
        points: ['What health risks can be found in public places?', 'How can laws help to reduce health problems?', 'How can we educate people about the importance of a healthy environment?'],
        model: 'Environmental health is about keeping the world around us clean and safe. Public places such as buses, fast food restaurants, schools and hospitals can carry germs, and viruses and bacteria spread quickly there. Polluted air, water and soil also cause many diseases. First, the government should set laws to limit pollution and laws prohibiting smoking in public areas. Second, we need uncontaminated water, air, soil and food. Finally, awareness and health education are very important. Schools and the media should teach people to wash their hands and keep their surroundings clean. If everyone made an effort, our environment would be much healthier.',
        modelAr: 'صحة البيئة تعني الحفاظ على العالم من حولنا نظيفاً وآمناً. فالأماكن العامة مثل الحافلات ومطاعم الوجبات السريعة والمدارس والمستشفيات يمكن أن تحمل الجراثيم، وتنتشر فيها الفيروسات والبكتيريا بسرعة. كما أن تلوّث الهواء والماء والتربة يسبّب أمراضاً كثيرة. أولاً، على الحكومة أن تضع قوانين للحدّ من التلوّث وقوانين تمنع التدخين في الأماكن العامة. ثانياً، نحتاج إلى ماء وهواء وتربة وطعام غير ملوّثة. وأخيراً، التوعية والتثقيف الصحي مهمّان جداً؛ فعلى المدارس ووسائل الإعلام أن تعلّم الناس غسل أيديهم والحفاظ على نظافة محيطهم. لو بذل كل واحد منّا جهداً لأصبحت بيئتنا أكثر صحة بكثير.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: المخاطر الصحية في الأماكن العامة، ودور القوانين، وتوعية الناس.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ترتيب وربط (First, Second, Finally, also, and).',
          'استخدمتُ تراكيب من الكتاب مثل should للنصيحة والشرطية الثانية (If everyone made an effort, … would …).',
          'استخدمتُ كلمات من الوحدة 7 (germs, viruses, bacteria, pollution, uncontaminated, awareness, make an effort).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
