import type { Exam } from '../../../engine/types'

// A final Baccalaureate practice paper in the exact layout of the real paper (term1-a.ts), covering the whole book (Units 1–12).
// Passage A: Unit 9 reading "Citizenship" (page 89), first part (paragraphs 1–2; paper F starts at paragraph 3).
// Passage B: Unit 12 reading "E-government" (pages 116–117), first part (paper E uses the classifications and Syria part).
export const term2C: Exam = {
  id: 't2-c',
  term: 2,
  title: 'Baccalaureate — Final Test (C)',
  titleAr: 'نموذج البكالوريا النهائي (C)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان البكالوريا الحقيقي، يغطّي الكتاب كاملاً (الوحدات 1–12).',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'Citizenship is not only the state of being vested with the rights and duties of a citizen, but it can also be defined as the character of an individual who is viewed as a member of a particular society. The concept of citizenship first arose in towns and city-states of ancient Greece, disappeared in Europe during the Middle Ages and crystallissed in the 18th century. The concept of citizenship has never been fixed or static, but constantly changes within each society.',
          'While citizenship has varied considerably throughout history, and within societies over time, there are some common related elements. Citizenship refers to many aspects of society such as family, military service, individual’s freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.',
          'Although Syrian citizenship provides many rights, it also involves many responsibilities.',
        ],
        paragraphsAr: [
          'المواطنة ليست فقط حالة تمتّع المرء بحقوق المواطن وواجباته، بل يمكن تعريفها أيضاً بأنها صفة الفرد الذي يُنظر إليه على أنه عضو في مجتمع معيّن. نشأ مفهوم المواطنة أولاً في مدن اليونان القديمة ودولها المدينية، واختفى في أوروبا خلال العصور الوسطى، ثم تبلور في القرن الثامن عشر. ولم يكن مفهوم المواطنة يوماً ثابتاً أو جامداً، بل يتغيّر باستمرار داخل كل مجتمع.',
          'ومع أن المواطنة تباينت كثيراً عبر التاريخ، وداخل المجتمعات مع مرور الزمن، فإن هناك بعض العناصر المشتركة المرتبطة بها. فالمواطنة تشير إلى جوانب كثيرة من المجتمع مثل الأسرة، والخدمة العسكرية، وحرية الفرد، ومفاهيم الصواب والخطأ، ودفع الضرائب، وأنماط السلوك التي ينبغي أن يتّبعها الشخص في المجتمع.',
          'ومع أن المواطنة السورية توفّر حقوقاً كثيرة، فإنها تتضمّن أيضاً مسؤوليات كثيرة.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'How can citizenship be defined?', promptAr: 'كيف يمكن تعريف المواطنة؟', lines: 3,
              accept: ['Citizenship is the state of being vested with the rights and duties of a citizen, and it can also be defined as the character of an individual who is viewed as a member of a particular society.', 'It is the state of being vested with the rights and duties of a citizen.', 'It can be defined as the character of an individual who is viewed as a member of a particular society.', 'The state of being vested with the rights and duties of a citizen.', 'The character of an individual who is viewed as a member of a particular society.'],
              modelAr: 'المواطنة هي حالة تمتّع المرء بحقوق المواطن وواجباته، ويمكن تعريفها أيضاً بأنها صفة الفرد الذي يُنظر إليه على أنه عضو في مجتمع معيّن.',
              explainAr: 'الجواب في الجملة الأولى: "Citizenship is not only the state of being vested with the rights and duties of a citizen, but it can also be defined as the character of an individual who is viewed as a member of a particular society". يكفي أحد التعريفين، والأفضل ذكرهما معاً.' },
            { n: 2, kind: 'write', prompt: 'What aspects of society does citizenship refer to?', promptAr: 'إلى أيّ جوانب المجتمع تشير المواطنة؟', lines: 3,
              accept: ['Citizenship refers to family, military service, individual’s freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.', 'It refers to many aspects of society such as family, military service, individual’s freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.', 'Family, military service, individual’s freedom, ideas of right and wrong, paying taxes and patterns for how a person should behave in society.'],
              modelAr: 'تشير المواطنة إلى الأسرة والخدمة العسكرية وحرية الفرد ومفاهيم الصواب والخطأ ودفع الضرائب وأنماط سلوك الشخص في المجتمع.',
              explainAr: 'الجواب في الفقرة الثانية بعد "Citizenship refers to many aspects of society such as...". انقل القائمة كاملة وابدأ جوابك بجملة كاملة: Citizenship refers to ....' },
            { n: 3, kind: 'write', prompt: 'What does Syrian citizenship involve besides rights?', promptAr: 'ماذا تتضمّن المواطنة السورية إلى جانب الحقوق؟', lines: 2,
              accept: ['It also involves many responsibilities.', 'Syrian citizenship also involves many responsibilities.', 'Many responsibilities.', 'It involves many responsibilities.'],
              modelAr: 'تتضمّن أيضاً مسؤوليات كثيرة.',
              explainAr: 'آخر جملة في النص: "Although Syrian citizenship provides many rights, it also involves many responsibilities". Although تربط بين أمرين متقابلين: الحقوق (rights) والمسؤوليات (responsibilities).' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'Given the official right to do or own something ……..', promptAr: 'مُنح الحق الرسمي في فعل شيء أو امتلاكه', lines: 1, topic: 'vocab',
              accept: ['vested'], modelAr: 'مُخوَّل / مُنح (حقاً)', explainAr: 'في الجملة الأولى: "the state of being vested with the rights and duties of a citizen" — أي مَن مُنح الحقوق والواجبات رسمياً. هذا هو تعريف vested في تمرين المفردات في الوحدة 9.' },
            { n: 5, kind: 'write', prompt: 'An idea that is connected with something ……..', promptAr: 'فكرة مرتبطة بشيء ما', lines: 1, topic: 'vocab',
              accept: ['concept'], modelAr: 'مفهوم', explainAr: 'في النص مرتين: "The concept of citizenship first arose..." و"The concept of citizenship has never been fixed". concept = مفهوم، وهذا تعريفها في تمرين المفردات في الوحدة 9.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'The concept of citizenship has always been fixed and static.', promptAr: 'كان مفهوم المواطنة دائماً ثابتاً وجامداً.', lines: 2,
              accept: ['The concept of citizenship has never been fixed or static.', 'The concept of citizenship has never been fixed or static, but constantly changes within each society.', 'The concept of citizenship constantly changes within each society.'],
              modelAr: 'لم يكن مفهوم المواطنة يوماً ثابتاً أو جامداً، بل يتغيّر باستمرار داخل كل مجتمع.',
              explainAr: 'النص يقول العكس: "The concept of citizenship has never been fixed or static, but constantly changes within each society". الخطأ في always.' },
            { n: 7, kind: 'write', prompt: 'The concept of citizenship first arose in Europe during the Middle Ages.', promptAr: 'نشأ مفهوم المواطنة أولاً في أوروبا خلال العصور الوسطى.', lines: 2,
              accept: ['The concept of citizenship first arose in towns and city-states of ancient Greece.', 'The concept of citizenship first arose in ancient Greece.', 'The concept of citizenship disappeared in Europe during the Middle Ages.'],
              modelAr: 'نشأ مفهوم المواطنة أولاً في مدن اليونان القديمة ودولها المدينية، واختفى في أوروبا خلال العصور الوسطى.',
              explainAr: 'النص: "first arose in towns and city-states of ancient Greece, disappeared in Europe during the Middle Ages". فأوروبا في العصور الوسطى هي المكان الذي اختفى فيه المفهوم، لا الذي نشأ فيه.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'E-government means everything from online government services to exchange of information and services electronically with citizens, businesses, and other bodies of the government. Traditionally, e-government has been considered as the use of Information and Communication Technology (ICT) for improving the effectiveness of government agencies and providing government services online. Nowadays, the framework of e-government has been evolving to include the use of ICT by government for conducting a wide range of interactions with citizens and businesses as well as open government data and the use of ICT to enable novelty all over the country.',
          'E-government enables the use of ICT more effectively and professionally by the delivery of government services to citizens and businesses, applying ICT to government operations and achieving public goals by digital means. The essential principle of e-government is to improve the internal mechanisms of the public sector. This can be done to reduce financial costs and transaction times, integrate work flows and processes and enable effective resource applications across the various public sector agencies aiming for workable solutions.',
          'Through innovation and e-government, governments around the world can be more efficient as they provide better services and respond to the demands of their citizens by transparency and liability. They can be more comprehensive and restore the trust of citizens in their governments.',
        ],
        paragraphsAr: [
          'تعني الحكومة الإلكترونية كل شيء بدءاً من الخدمات الحكومية عبر الإنترنت وصولاً إلى تبادل المعلومات والخدمات إلكترونياً مع المواطنين والشركات والهيئات الحكومية الأخرى. تقليدياً، كان يُنظر إلى الحكومة الإلكترونية على أنها استخدام تكنولوجيا المعلومات والاتصالات لتحسين فعالية الأجهزة الحكومية وتقديم الخدمات الحكومية عبر الإنترنت. أما اليوم فإن إطار الحكومة الإلكترونية يتطوّر ليشمل استخدام الحكومة لهذه التكنولوجيا في إجراء مجموعة واسعة من التعاملات مع المواطنين والشركات، إضافةً إلى البيانات الحكومية المفتوحة، واستخدام التكنولوجيا لتمكين التجديد في جميع أنحاء البلاد.',
          'تتيح الحكومة الإلكترونية استخدام تكنولوجيا المعلومات والاتصالات بشكل أكثر فعالية واحترافية من خلال تقديم الخدمات الحكومية للمواطنين والشركات، وتطبيق هذه التكنولوجيا على العمليات الحكومية، وتحقيق الأهداف العامة بوسائل رقمية. والمبدأ الأساسي للحكومة الإلكترونية هو تحسين الآليات الداخلية للقطاع العام. ويمكن القيام بذلك لتقليل التكاليف المالية ومدة المعاملات، ودمج سير العمل والإجراءات، وتمكين الاستخدام الفعّال للموارد عبر مختلف أجهزة القطاع العام سعياً إلى حلول قابلة للتطبيق.',
          'ومن خلال الابتكار والحكومة الإلكترونية، تستطيع الحكومات حول العالم أن تكون أكثر كفاءة، إذ تقدّم خدمات أفضل وتستجيب لمطالب مواطنيها بشفافية ومسؤولية. ويمكنها أن تكون أكثر شمولاً وأن تستعيد ثقة المواطنين بحكوماتهم.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'Traditionally, e-government has been considered as the use of ICT for ……..', promptAr: 'تقليدياً، كان يُنظر إلى الحكومة الإلكترونية على أنها استخدام تكنولوجيا المعلومات والاتصالات من أجل ……..', options: ['closing government agencies', 'improving the effectiveness of government agencies', 'replacing citizens with machines', 'selling goods to other countries'], answer: 1,
              explainAr: 'النص: "e-government has been considered as the use of ... (ICT) for improving the effectiveness of government agencies and providing government services online". الخيارات الأخرى لم تُذكر في النص.' },
            { n: 9, kind: 'mcq', prompt: 'The essential principle of e-government is to ……..', promptAr: 'المبدأ الأساسي للحكومة الإلكترونية هو ……..', options: ['increase transaction times', 'collect more taxes from citizens', 'hire more employees', 'improve the internal mechanisms of the public sector'], answer: 3,
              explainAr: 'النص: "The essential principle of e-government is to improve the internal mechanisms of the public sector". أما "increase transaction times" فهو عكس ما يقوله النص، لأن الحكومة الإلكترونية تقلّل مدة المعاملات (reduce ... transaction times).' },
            { n: 10, kind: 'mcq', prompt: 'Through e-government, governments can restore ……..', promptAr: 'من خلال الحكومة الإلكترونية، تستطيع الحكومات أن تستعيد ……..', options: ['the trust of citizens in their governments', 'the old paper documents', 'higher financial costs', 'longer transaction times'], answer: 0,
              explainAr: 'آخر جملة: "They can be more comprehensive and restore the trust of citizens in their governments". restore = يستعيد، و trust = الثقة.' },
            { n: 11, kind: 'mcq', prompt: 'The quality of something to make it easy to understand is ……..', promptAr: 'صفة الشيء التي تجعله سهل الفهم هي ……..', options: ['liability', 'novelty', 'transparency', 'transaction'], answer: 2, topic: 'vocab',
              explainAr: 'transparency = الشفافية، وهذا تعريفها في تمرين الكلمات في الوحدة 12، وهي في النص "by transparency and liability". liability = المسؤولية القانونية، novelty = الجِدّة والتجديد، transaction = صفقة أو معاملة.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'Nowadays, the framework of e-government has been evolving to include ……………………', promptAr: 'في هذه الأيام، يتطوّر إطار الحكومة الإلكترونية ليشمل ……', lines: 2,
              accept: ['the use of ICT by government for conducting a wide range of interactions with citizens and businesses', 'the use of ICT by government for conducting a wide range of interactions with citizens and businesses as well as open government data', 'the use of ICT by government for conducting a wide range of interactions with citizens and businesses as well as open government data and the use of ICT to enable novelty all over the country'],
              modelAr: 'استخدام الحكومة لتكنولوجيا المعلومات والاتصالات في إجراء مجموعة واسعة من التعاملات مع المواطنين والشركات.',
              explainAr: 'النص: "Nowadays, the framework of e-government has been evolving to include the use of ICT by government for conducting a wide range of interactions with citizens and businesses...". انقل ما بعد include.' },
            { n: 13, kind: 'write', prompt: 'E-government can help the public sector reduce ……………………', promptAr: 'تستطيع الحكومة الإلكترونية أن تساعد القطاع العام على تقليل ……', lines: 1,
              accept: ['financial costs and transaction times'], modelAr: 'التكاليف المالية ومدة المعاملات.',
              explainAr: 'النص: "This can be done to reduce financial costs and transaction times". انتبه أن الشيئين معاً هما الجواب الكامل.' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'Why is the towel on the floor? Please ……… .', promptAr: 'لماذا المنشفة على الأرض؟ من فضلك ___.', options: ['look it up', 'pick it up', 'put it on', 'get it out'], answer: 1,
          explainAr: 'pick up بمعناها الحرفي = يمسك شيئاً ويرفعه (to take hold of something and lift it up)، والجملة من كتابك (الأفعال المركّبة، الوحدة 12). look up = يبحث عن معلومة في القاموس، put on = يرتدي، get out = يُخرج. لاحظ أن الضمير it يقع بين الفعل والأداة.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'A vacuum cleaner is a machine ……… you use to clean floors and carpets.', promptAr: 'المكنسة الكهربائية آلة ___ تستخدمها لتنظيف الأرضيات والسجاد.', options: ['who', 'where', 'which', 'whose'], answer: 2,
          explainAr: 'بعد اسم لشيء غير عاقل (a machine) نستخدم which أو that (الوحدة 5)، والجملة من كتابك. who للأشخاص، where للمكان، whose للملكية ويليها اسم.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'The insurance company refused to pay the money because they said that the forest fire was ……….', promptAr: 'رفضت شركة التأمين دفع المال لأنها قالت إن حريق الغابة كان ___.', options: ['an act of God', 'by the book', 'a pain in the neck', 'on a roll'], answer: 0,
          explainAr: 'an act of God = قضاء وقدر (حدث طبيعي لا يد للإنسان فيه)، من تعابير القانون في الوحدة 5، والجملة من كتابك. by the book = حسب القواعد، a pain in the neck = شيء مزعج (الوحدة 8)، on a roll = في سلسلة نجاحات (الوحدة 2).' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'The feeling of being annoyed because you cannot control a situation is ……….', promptAr: 'الشعور بالانزعاج لأنك لا تستطيع التحكّم في موقف ما هو ___.', options: ['adjustment', 'frustration', 'integration', 'disturbance'], answer: 1,
          explainAr: 'frustration = الإحباط، وهذا تعريفها في تمرين كلمات نص صدمة الثقافة (الوحدة 10). adjustment = التكيّف، integration = الاندماج في المجتمع، disturbance = اضطراب.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'The word “produce” is stressed on the second syllable (proDUCE). Here it is ……….', promptAr: 'كلمة "produce" منبورة على المقطع الثاني (proDUCE). هي هنا ___.', options: ['a noun', 'an adjective', 'a verb', 'a preposition'], answer: 2,
          explainAr: 'النبر في الكلمات ذات المقطعين (الوحدة 6): إذا وقع النبر على المقطع الثاني تكون الكلمة غالباً فعلاً (proDUCE = يُنتج)، وإذا وقع على الأول تكون اسماً أو صفة (PROduce = منتجات زراعية).' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'After analysing the problem, she ……… that there was a flaw in the theory.', promptAr: 'بعد تحليل المشكلة، ___ أن في النظرية خللاً.', options: ['concluded', 'inserted', 'pressed', 'reacted'], answer: 0,
          explainAr: 'conclude = يستنتج، وهو من أفعال العلوم والتكنولوجيا في الوحدة 11، والجملة من كتابك. insert = يُدخل (القرص)، press = يضغط (الزر)، react = يتفاعل (المواد الكيميائية).' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'My grandfather is careless ……… his money.', promptAr: 'جدّي مهمل ___ ماله.', options: ['of', 'about', 'for', 'with'], answer: 3,
          explainAr: 'بعض الصفات يتبعها حرف جر ثابت (الوحدة 9): careless with = مهمل في/بشأن. والجملة من كتابك. ومثلها: afraid of، grateful for، sure about.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'In “I object to being given this object!”, the first “object” means ……….', promptAr: 'في الجملة المعطاة، كلمة "object" الأولى تعني ___.', options: ['an item', 'to disagree', 'a type of metal', 'being nearby'], answer: 1,
          explainAr: 'الكلمات المتجانسة كتابةً (homographs، الوحدة 9) تُكتب بالطريقة نفسها وتختلف في المعنى وربما في اللفظ. object الأولى فعل بعد I = يعترض (to disagree)، والثانية اسم بعد this = شيء (an item). a type of metal معنى lead، و being nearby معنى close.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Patriotism is love of and ……… to one’s country.', promptAr: 'الوطنية هي حبّ الوطن و___ له.', options: ['devotion', 'devote', 'devoted', 'devotedly'], answer: 0,
          explainAr: 'بعد and نحتاج اسماً معطوفاً على الاسم love، فنختار devotion = الإخلاص (عائلة الكلمة في الوحدة 9)، والجملة من كتابك. devote فعل، devoted صفة، devotedly ظرف.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'If I go to a barber, I can ……… my hair cut.', promptAr: 'إذا ذهبتُ إلى الحلاق، يمكنني أن ___ شعري (أي أجعله يقصّه).', lines: 1,
          accept: ['have', 'get'], explainAr: 'الفعل السببي (الوحدة 4): have/get + مفعول + التصريف الثالث (my hair cut) عندما يقوم شخص آخر بالعمل من أجلك. بعد can يأتي الفعل في أصله: have.' },
        { n: 24, kind: 'write', topic: 'reported', prompt: 'He asked me ……… I was going to the cinema at the weekend.', promptAr: 'سألني ___ كنتُ ذاهباً إلى السينما في عطلة نهاية الأسبوع.', lines: 1,
          accept: ['if', 'whether'], explainAr: 'الكلام المنقول (الوحدة 11): عند نقل سؤال Yes/No مثل "Are you going to the cinema?" نستخدم if أو whether، ويصبح ترتيب الجملة ترتيب جملة خبرية (I was going).' },
        { n: 25, kind: 'write', topic: 'tense', prompt: 'The team manager ……… holding a party on our return.', promptAr: 'سيقيم مدير الفريق حفلة عند عودتنا.', lines: 1,
          accept: ['is'], explainAr: 'المضارع المستمر يُستخدم للترتيبات المستقبلية الثابتة (الوحدة 6): is + holding. الفاعل مفرد (The team manager) فنستخدم is. والجملة من كتابك.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'Syria has adopted this new technology {to facilitate public services for its citizens}.', promptAr: 'تبنّت سوريا هذه التكنولوجيا الجديدة لتسهيل الخدمات العامة لمواطنيها.', lines: 1,
          accept: ['Why has Syria adopted this new technology?', 'Why has Syria adopted this technology?', 'Why has Syria adopted e-government?'], modelAr: 'لماذا تبنّت سوريا هذه التكنولوجيا الجديدة؟',
          explainAr: 'المسطَّر يدل على الهدف (to + فعل) فنسأل بـ Why. الفعل مضارع تام (has adopted) فنقدّم has على الفاعل: Why has Syria adopted...؟' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'My phone number is {0303-242892}.', promptAr: 'رقم هاتفي 0303-242892.', lines: 1,
          accept: ['What is your phone number?', 'What is your telephone number?', 'What is your number?'], modelAr: 'ما رقم هاتفك؟',
          explainAr: 'المسطَّر معلومة (رقم) فنسأل بـ What، ونقدّم is على الفاعل، ويتحوّل My إلى your. الجملة من حوار الهاتف في الوحدة 7.' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'The burglar came in {through the front door}.', promptAr: 'دخل اللص من الباب الأمامي.', lines: 1,
          accept: ['How did the burglar come in?', 'How did the burglar get in?', 'Where did the burglar come in?', 'Which door did the burglar come in through?'], modelAr: 'كيف دخل اللص؟',
          explainAr: 'المسطَّر يدل على الطريقة/المكان الذي دخل منه، فنسأل بـ How (أو Where). الفعل came ماضٍ بسيط فنستخدم did ويعود الفعل إلى أصله come. الجملة من كتابك (الوحدة 2).' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'grammar', prompt: 'Wind power is renewable. Solar power is also renewable. (both...and)', promptAr: 'طاقة الرياح متجدّدة. والطاقة الشمسية متجدّدة أيضاً. (both...and)', lines: 2,
          accept: ['Both wind power and solar power are renewable.', 'Both solar power and wind power are renewable.'], modelAr: 'كلٌّ من طاقة الرياح والطاقة الشمسية متجدّدة.',
          explainAr: 'أدوات الربط المزدوجة (الوحدة 9): فاعلان مربوطان بـ both...and يأخذان فعلاً جمعاً، فتصبح is ← are، ونحذف also. الجملة من المراجعة الثالثة في كتابك.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'It isn’t necessary for you to be silent. (Use: don’t have to)', promptAr: 'ليس من الضروري أن تكون صامتاً. (استخدم: don’t have to)', lines: 2,
          accept: ['You don’t have to be silent.', 'You do not have to be silent.'], modelAr: 'لستَ مضطراً أن تكون صامتاً.',
          explainAr: 'الأفعال الناقصة (الوحدة 10): don’t / doesn’t have to تعبّر عن عدم وجود إلزام (absence of obligation)، بخلاف mustn’t التي تعني المنع. والجملة من كتابك: "you don’t have to be silent".' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'You are in a launderette. The instructions on the washing machine are not clear. (Ask for help)', promptAr: 'أنت في مغسلة عامة، وتعليمات الغسالة غير واضحة. (اطلب المساعدة)', lines: 2,
          accept: ['I’m sorry to trouble you, but could you help me with this washing machine?', 'I’m sorry to trouble you, but could you help me?', 'I’m sorry to trouble you, but I need your help.', 'Could you help me, please?', 'Can you help me, please?', 'Could you help me with this washing machine, please?', 'Do you think you could possibly help me with this machine?', 'Could you tell me how to use this washing machine, please?', 'Excuse me, could you help me use this machine?'],
          model: 'I’m sorry to trouble you, but could you help me with this washing machine?', modelAr: 'آسف لإزعاجك، لكن هل يمكنك مساعدتي في استخدام هذه الغسالة؟',
          explainAr: 'طلب المساعدة (Everyday English، الوحدة 8): I’m sorry to trouble you, but... / I need your help / Could you...? / Do you think you could possibly...? والموقف نفسه في كتابك.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Local councils have opened many paths in the farming lands. (passive voice)', promptAr: 'فتحت المجالس المحلية طرقاً كثيرة في الأراضي الزراعية. (المبني للمجهول)', lines: 2,
          accept: ['Many paths have been opened in the farming lands.', 'Many paths have been opened in the farming lands by local councils.', 'Many paths in the farming lands have been opened by local councils.', 'Many paths have been opened by local councils in the farming lands.'],
          modelAr: 'فُتحت طرق كثيرة في الأراضي الزراعية.',
          explainAr: 'المبني للمجهول في المضارع التام (الوحدة 3): have/has + been + التصريف الثالث. المفعول many paths جمع فنقول have been opened، ويمكن ذكر by local councils أو حذفه. الجملة من المراجعة الأولى في كتابك.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'It’s a fantastic novel! I have almost finished it. I wish it ………. (be) longer.', promptAr: 'إنها رواية رائعة! كدتُ أنهيها. ليتها كانت أطول.', lines: 1,
          accept: ['were', 'was'], explainAr: 'التمنّي عن الحاضر (الوحدة 8): I wish + ماضٍ بسيط لشيء غير حقيقي الآن (الرواية ليست طويلة)، ومع be يُفضَّل were لكل الضمائر وتُقبل was. الجملة من المراجعة الثانية في كتابك.' },
        { n: 34, kind: 'write', topic: 'reported', prompt: 'Fuad said, “The teachers are working on the exam results.” Fuad said that the teachers ………. (work) on the exam results.', promptAr: 'قال فؤاد: "المعلمون يعملون على نتائج الامتحان." قال فؤاد إن المعلمين كانوا يعملون على نتائج الامتحان.', lines: 1,
          accept: ['were working'], explainAr: 'الكلام المنقول (الوحدة 11): بعد said في الماضي يرجع الزمن خطوة إلى الوراء، فالمضارع المستمر are working يصبح ماضياً مستمراً were working. الجملة من المراجعة الثالثة في كتابك.' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'I can’t leave now. I ………. (wait) for an important client.', promptAr: 'لا أستطيع المغادرة الآن. أنا أنتظر عميلاً مهمّاً.', lines: 1,
          accept: ['am waiting'], explainAr: 'المضارع المستمر (الوحدة 1): now تدل على حدث يجري في هذه اللحظة، فنستخدم am + waiting مع I. الجملة من المراجعة الأولى في كتابك.' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'conditional', prompt: 'If she had taken the bus, …………………………..', promptAr: 'لو أنها ركبت الحافلة، …', lines: 2,
          accept: ['she wouldn’t have arrived on time.', 'she would have arrived on time.', 'she would have arrived earlier.', 'she wouldn’t have been late.'], model: 'she wouldn’t have arrived on time.', modelAr: 'لما وصلت في الوقت المحدد.',
          explainAr: 'الشرطية الثالثة (الوحدة 7): If + had + التصريف الثالث (had taken)، والجواب would (not) have + التصريف الثالث، لموقف متخيَّل في الماضي لم يحدث.' },
        { n: 37, kind: 'write', topic: 'grammar', prompt: 'Should the alarm ring, …………………………..', promptAr: 'إذا رنّ جرس الإنذار، …', lines: 2,
          accept: ['leave the building immediately.', 'leave the building at once.', 'you should leave the building immediately.', 'we will leave the building immediately.'], model: 'leave the building immediately.', modelAr: 'غادِر المبنى فوراً.',
          explainAr: 'القلب (Inversion، الوحدة 12): Should + فاعل + فعل = If + فاعل + فعل (If the alarm rings). الجواب جملة أمر أو مستقبل. والجملة من المراجعة الثالثة في كتابك.' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: You can’t break bread with everyone you meet in life.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['لا يمكنك أن تكون صديقاً مقرّباً لكل شخص تقابله في الحياة', 'لا تستطيع أن تقيم صداقة حميمة مع كل من تقابله في حياتك', 'لا يمكنك أن تصادق بعمق كل من تلتقي به في الحياة'], model: 'لا يمكنك أن تكون صديقاً مقرّباً لكل شخص تقابله في الحياة.',
          explainAr: 'الجملة من كتابك (التعابير، الوحدة 10). break bread with = يكون صديقاً مقرّباً ذا صلة حقيقية، can’t = لا يمكن، everyone you meet = كل من تقابله. لا تترجم التعبير حرفياً (يكسر الخبز).' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: تعطّلت سيارته، فأوصلته إلى أقرب مرآب.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['His car broke down, so I gave him a lift to the nearest garage.', 'His car broke down, so I took him to the nearest garage.', 'His car broke down, so I drove him to the nearest garage.'],
          model: 'His car broke down, so I gave him a lift to the nearest garage.',
          explainAr: 'الجملة من كتابك (المتلازمات اللفظية، الوحدة 7). تعطّلت ← broke down، أوصلته ← gave him a lift (give someone a lift)، أقرب ← the nearest، والفعلان في الماضي البسيط.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Environmental health in your community.',
        topicAr: 'الصحة البيئية في مجتمعك.',
        words: 80,
        points: ['Laws to limit pollution and to prohibit smoking in public areas.', 'Awareness and health education.', 'Uncontaminated water, air, soil and food.'],
        model: 'Environmental health means keeping the world around us clean and safe, so that people can live healthy lives. First of all, the government should set laws to limit pollution from factories and cars. It should also prohibit smoking in public areas such as schools, hospitals and public transport. However, laws are not enough. People need awareness and health education, because many germs spread in public places. For example, we should wash our hands and keep our homes and cars hygienic. Moreover, everyone has the right to uncontaminated water, air, soil and food. If all citizens took care of their environment, there would be fewer diseases in our community.',
        modelAr: 'تعني الصحة البيئية المحافظة على نظافة العالم من حولنا وسلامته، كي يعيش الناس حياة صحية. أولاً، يجب أن تضع الحكومة قوانين للحدّ من تلوّث المصانع والسيارات، وأن تمنع التدخين في الأماكن العامة كالمدارس والمستشفيات ووسائل النقل العام. لكن القوانين وحدها لا تكفي؛ فالناس يحتاجون إلى التوعية والتثقيف الصحي، لأن كثيراً من الجراثيم تنتشر في الأماكن العامة. فمثلاً، يجب أن نغسل أيدينا ونحافظ على نظافة بيوتنا وسياراتنا. إضافةً إلى ذلك، من حق كل شخص أن يحصل على ماء وهواء وتربة وغذاء غير ملوّثة. لو اعتنى جميع المواطنين ببيئتهم، لقلّت الأمراض في مجتمعنا.',
        checklistAr: [
          'تناولتُ النقاط الثلاث: القوانين (التلوّث والتدخين)، والتوعية والتثقيف الصحي، والماء والهواء والتربة والغذاء غير الملوّثة.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (First of all, also, However, For example, Moreover).',
          'استخدمتُ should للنصيحة، وجملة شرطية من النوع الثاني (If all citizens took..., there would be...).',
          'استخدمتُ مفردات الوحدة 7 (germs, bacteria, hygienic, pollution, public places, uncontaminated).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
