import type { Exam } from '../../../engine/types'

// A final Baccalaureate practice paper in the exact layout of the real paper (term1-a.ts), covering the whole book.
// Passage A: Unit 7 reading "Microorganisms" (pages 66–67). Passage B: Unit 10 reading "Culture Shock" (pages 97–98), first part.
export const term2A: Exam = {
  id: 't2-a',
  term: 2,
  title: 'Baccalaureate — Final Test (A)',
  titleAr: 'نموذج البكالوريا النهائي (A)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل الدقيق لامتحان البكالوريا الحقيقي، يغطّي الكتاب كاملاً (الوحدات 1–12) ومبنيّ من نصوص الكتاب وقواعده ومفرداته فقط.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'Most bacteria aren’t harmful; we have many bacteria on and inside our body, especially in the gut to help digest food. They also serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants. On the other hand, viruses are smaller and aren’t cells. Unlike bacteria, they need a host such as a human or an animal to multiply. Viruses only grow and reproduce inside the host cells they infect. Their life involves the hijacking of the biochemical activities of a living cell. Viruses and bacteria differ in how they cause infections.',
          'As the names suggest, viruses cause viral infections, whereas bacteria cause bacterial infections. Viruses infect a host cell and then multiply by the thousands, leaving the host and infecting other cells of the body. Diseases caused by a viral infection include influenza, common cold, flu, AIDS and COVID-19. Bacteria, on the other hand, have a more varied operation and will often infect when the right opportunity arises. Bacterial infections include pneumonia, strep throat, ear infection and food poisoning.',
        ],
        paragraphsAr: [
          'معظم البكتيريا ليست ضارّة؛ فلدينا كثير من البكتيريا على أجسامنا وداخلها، وخاصةً في الأمعاء لتساعد على هضم الطعام. وهي تؤدّي أيضاً أدواراً حيوية كثيرة في الطبيعة بتحليل المادة العضوية وتحويل النيتروجين إلى مواد كيميائية تستطيع النباتات استخدامها. ومن ناحية أخرى، الفيروسات أصغر حجماً وليست خلايا. وعلى خلاف البكتيريا، تحتاج الفيروسات إلى مضيف كالإنسان أو الحيوان كي تتكاثر. فهي لا تنمو ولا تتكاثر إلا داخل الخلايا المضيفة التي تصيبها، وتقوم حياتها على الاستيلاء على النشاطات الكيميائية الحيوية لخلية حيّة. وتختلف الفيروسات والبكتيريا في الطريقة التي تسبّب بها العدوى.',
          'كما يوحي اسماهما، تسبّب الفيروسات عدوى فيروسية، بينما تسبّب البكتيريا عدوى بكتيرية. تصيب الفيروسات خلية مضيفة ثم تتكاثر بالآلاف، فتغادر المضيف وتصيب خلايا أخرى في الجسم. ومن الأمراض التي تسبّبها العدوى الفيروسية: الإنفلونزا والزكام والنزلة الوافدة والإيدز وكوفيد-19. أما البكتيريا فطريقة عملها أكثر تنوّعاً، وغالباً ما تُحدث العدوى عندما تسنح الفرصة المناسبة. ومن أمثلة العدوى البكتيرية: الالتهاب الرئوي والتهاب الحلق العقدي والتهاب الأذن والتسمّم الغذائي.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'In what ways are bacteria useful to nature?', promptAr: 'بأيّ طرق تفيد البكتيريا الطبيعة؟', lines: 3,
              accept: ['They serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants.', 'By decomposing organic matter and by converting nitrogen to chemicals usable by plants.', 'By decomposing organic matter and converting nitrogen to chemicals usable by plants.', 'They decompose organic matter and convert nitrogen to chemicals usable by plants.', 'Bacteria decompose organic matter and convert nitrogen to chemicals usable by plants.'],
              model: 'They serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants.',
              modelAr: 'تؤدّي أدواراً حيوية في الطبيعة بتحليل المادة العضوية وتحويل النيتروجين إلى مواد كيميائية تستطيع النباتات استخدامها.',
              explainAr: 'الجواب في الجملة الثانية من النص: "They also serve many vital roles in nature by decomposing organic matter and by converting nitrogen to chemicals usable by plants". السؤال عن الطبيعة (nature) لا عن جسم الإنسان، فلا تكتب "هضم الطعام".' },
            { n: 2, kind: 'write', prompt: 'What do viruses need to multiply?', promptAr: 'ماذا تحتاج الفيروسات كي تتكاثر؟', lines: 2,
              accept: ['They need a host such as a human or an animal to multiply.', 'Viruses need a host such as a human or an animal to multiply.', 'They need a host such as a human or an animal.', 'A host such as a human or an animal.', 'They need a host.', 'A host.'],
              model: 'They need a host such as a human or an animal to multiply.',
              modelAr: 'تحتاج إلى مضيف كالإنسان أو الحيوان كي تتكاثر.',
              explainAr: 'النص: "Unlike bacteria, they need a host such as a human or an animal to multiply". الضمير they يعود على viruses. ابدأ جوابك بفاعل كامل: They need ...' },
            { n: 3, kind: 'write', prompt: 'Why do we have many bacteria in the gut?', promptAr: 'لماذا توجد في أمعائنا بكتيريا كثيرة؟', lines: 2,
              accept: ['To help digest food.', 'They help digest food.', 'Because they help digest food.', 'We have many bacteria in the gut to help digest food.', 'To help us digest food.', 'Because they help us digest food.'],
              model: 'We have many bacteria in the gut to help digest food.',
              modelAr: 'توجد في أمعائنا بكتيريا كثيرة لتساعد على هضم الطعام.',
              explainAr: 'النص: "we have many bacteria on and inside our body, especially in the gut to help digest food". السؤال بـ Why، ويمكن أن يبدأ الجواب بـ To (للهدف) أو Because.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', topic: 'vocab', prompt: 'To destroy gradually by natural chemical processes ……..', promptAr: 'يُتلف شيئاً تدريجياً بعمليات كيميائية طبيعية', lines: 1,
              accept: ['decomposing', 'decompose'], model: 'decomposing', modelAr: 'تحليل / تفكيك (يتحلّل)',
              explainAr: 'في النص "by decomposing organic matter" — تحليل المادة العضوية. هذا تعريف decompose نفسه في تمرين المفردات في الوحدة 7.' },
            { n: 5, kind: 'write', topic: 'vocab', prompt: 'Attack to control something ……..', promptAr: 'الهجوم على شيء للسيطرة عليه', lines: 1,
              accept: ['hijacking', 'hijack'], model: 'hijacking', modelAr: 'الاستيلاء / الاختطاف',
              explainAr: 'في النص "Their life involves the hijacking of the biochemical activities of a living cell" — فالفيروس يستولي على نشاطات الخلية ويتحكّم بها. هذا تعريف hijack في تمرين المفردات في الوحدة 7.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'Most bacteria are harmful to the human body.', promptAr: 'معظم البكتيريا ضارّة بجسم الإنسان.', lines: 2,
              accept: ['Most bacteria are not harmful to the human body.', 'Most bacteria aren’t harmful to the human body.', 'Most bacteria are not harmful.', 'Most bacteria aren’t harmful.', 'Most bacteria are harmless to the human body.'],
              model: 'Most bacteria are not harmful to the human body.',
              modelAr: 'معظم البكتيريا ليست ضارّة بجسم الإنسان.',
              explainAr: 'الجملة الأولى في النص: "Most bacteria aren’t harmful; we have many bacteria on and inside our body". فالتصحيح بالنفي: are not harmful.' },
            { n: 7, kind: 'write', prompt: 'Viruses are bigger than bacteria, and they are cells.', promptAr: 'الفيروسات أكبر من البكتيريا، وهي خلايا.', lines: 2,
              accept: ['Viruses are smaller than bacteria, and they are not cells.', 'Viruses are smaller than bacteria and they aren’t cells.', 'Viruses are smaller than bacteria and are not cells.', 'Viruses are smaller and aren’t cells.', 'Viruses are smaller and they are not cells.'],
              model: 'Viruses are smaller than bacteria, and they are not cells.',
              modelAr: 'الفيروسات أصغر من البكتيريا، وليست خلايا.',
              explainAr: 'النص: "On the other hand, viruses are smaller and aren’t cells". في الجملة خطآن: bigger ← smaller، و are cells ← are not cells.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'Culture shock is an experience people may have when they move to a foreign country with a new cultural environment, which is different from their own. These unfamiliar surroundings can lead to a feeling of being a little bit lost. For example, when a student starts studying abroad, he/she experiences different things in custom, dress and food. There are many symptoms of transition shock including: anger, boredom, extreme homesickness, eating disturbances and excessive critical reactions to host culture. Sometimes the symptoms last just few days, but more often they last weeks or even months.',
          'People experiencing culture shock usually move through four stages; they will initially have the honeymoon stage which is characterised by a positive feeling that everything is new and exciting. Then there will be the frustration stage, it may be marked by rejection of the new culture, as well as romanticising one’s home culture. But then, with some time and perhaps help from locals, people will start the adjustment stage and begin to feel more familiar and comfortable with the new environment. Adaption and acceptance is the final stage which contributes to the successful integration.',
        ],
        paragraphsAr: [
          'الصدمة الثقافية تجربة قد يمرّ بها الناس عندما ينتقلون إلى بلد أجنبي ذي بيئة ثقافية جديدة تختلف عن بيئتهم. ويمكن أن يؤدّي هذا المحيط غير المألوف إلى شعور بالضياع قليلاً. فمثلاً، عندما يبدأ طالب أو طالبة الدراسة في الخارج، يواجه أشياء مختلفة في العادات واللباس والطعام. وهناك أعراض كثيرة لصدمة الانتقال، منها: الغضب والملل والحنين الشديد إلى الوطن واضطرابات الأكل وردود الفعل الانتقادية المفرطة تجاه ثقافة البلد المضيف. أحياناً تستمرّ الأعراض بضعة أيام فقط، لكنها في أغلب الأحيان تستمرّ أسابيع أو حتى شهوراً.',
          'يمرّ من يعانون الصدمة الثقافية عادةً بأربع مراحل؛ ففي البداية تكون مرحلة "شهر العسل" التي يميّزها شعور إيجابي بأن كل شيء جديد ومثير. ثم تأتي مرحلة الإحباط، وقد يطبعها رفض الثقافة الجديدة، إلى جانب إضفاء صورة مثالية على ثقافة الوطن. ولكن بعد ذلك، ومع مرور بعض الوقت وربما بمساعدة من السكان المحليين، يبدأ الناس مرحلة التكيّف ويشعرون بألفة وارتياح أكبر مع البيئة الجديدة. أما التأقلم والتقبّل فهي المرحلة الأخيرة التي تسهم في الاندماج الناجح.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'Culture shock is an experience people may have when they ……..', promptAr: 'الصدمة الثقافية تجربة قد يمرّ بها الناس عندما ……..', options: ['move to a foreign country', 'return to their home town', 'change their school', 'meet new friends at home'], answer: 0,
              explainAr: 'الجملة الأولى: "Culture shock is an experience people may have when they move to a foreign country with a new cultural environment" — أي عند الانتقال إلى بلد أجنبي (move to a foreign country).' },
            { n: 9, kind: 'mcq', prompt: 'More often, the symptoms of transition shock last ……..', promptAr: 'في أغلب الأحيان تستمرّ أعراض صدمة الانتقال ……..', options: ['just a few hours', 'only one day', 'for many years', 'weeks or even months'], answer: 3,
              explainAr: 'النص: "Sometimes the symptoms last just few days, but more often they last weeks or even months". انتبه إلى more often = في أغلب الأحيان، فالجواب "weeks or even months".' },
            { n: 10, kind: 'mcq', prompt: 'When a student starts studying abroad, he/she experiences different things in ……..', promptAr: 'عندما يبدأ الطالب الدراسة في الخارج، يواجه أشياء مختلفة في ……..', options: ['language, music and sport', 'custom, dress and food', 'weather, transport and money', 'schools, books and teachers'], answer: 1,
              explainAr: 'النص: "when a student starts studying abroad, he/she experiences different things in custom, dress and food" — العادات واللباس والطعام.' },
            { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'An unhappy and worried mental state is ……..', promptAr: 'حالة نفسية حزينة وقلقة هي ……..', options: ['frustration', 'adjustment', 'disturbance', 'integration'], answer: 2,
              explainAr: 'disturbance = اضطراب (حالة نفسية قلقة)، وهي في النص "eating disturbances". frustration = إحباط، adjustment = تكيّف، integration = اندماج. التعريفات من تمرين المفردات في الوحدة 10.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'The symptoms of transition shock include ……………………', promptAr: 'تشمل أعراض صدمة الانتقال ……', lines: 2,
              accept: ['anger, boredom, extreme homesickness, eating disturbances and excessive critical reactions to host culture', 'anger, boredom, extreme homesickness, eating disturbances and excessive critical reactions to the host culture', 'anger, boredom, homesickness, eating disturbances and critical reactions to host culture'],
              model: 'anger, boredom, extreme homesickness, eating disturbances and excessive critical reactions to host culture.',
              modelAr: 'الغضب والملل والحنين الشديد إلى الوطن واضطرابات الأكل وردود الفعل الانتقادية المفرطة تجاه ثقافة البلد المضيف.',
              explainAr: 'النص: "There are many symptoms of transition shock including: anger, boredom, extreme homesickness, eating disturbances and excessive critical reactions to host culture".' },
            { n: 13, kind: 'write', prompt: 'Unfamiliar surroundings can lead to ……………………', promptAr: 'يمكن أن يؤدّي المحيط غير المألوف إلى ……', lines: 1,
              accept: ['a feeling of being a little bit lost', 'a feeling of being lost', 'a feeling of being a bit lost'],
              model: 'a feeling of being a little bit lost.',
              modelAr: 'شعور بالضياع قليلاً.',
              explainAr: 'النص: "These unfamiliar surroundings can lead to a feeling of being a little bit lost". بعد lead to يأتي اسم (a feeling).' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'She ……… the speaker with some sharp questions.', promptAr: 'هي ___ المتحدّث ببعض الأسئلة اللاذعة.', options: ['picked up', 'came back at', 'got out', 'put on'], answer: 1,
          explainAr: 'come back at somebody = يردّ على شخص بغضب أو بقوة (to reply to somebody angrily or with force)، وهو فعل مركّب بمعنى اصطلاحي من الوحدة 12، والجملة من كتابك. picked up = التقط/أقلّ بالسيارة، got out = أخرج/نشر، put on = ارتدى/اكتسب وزناً.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'That is the doctor ……… patients always talk highly about him.', promptAr: 'ذاك هو الطبيب الذي ___ مرضاه يتحدّثون عنه دائماً بإعجاب.', options: ['who', 'which', 'whom', 'whose'], answer: 3,
          explainAr: 'بعد الفراغ اسم (patients) يملكه الطبيب: "مرضاه"، فنستخدم أداة الملكية whose. who و whom للعاقل دون ملكية، و which لغير العاقل. الجملة من المراجعة 2: "I know that doctor. His patients always talk highly about him."' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'You might make less money from that job, but if it really attracts you, you should ……… .', promptAr: 'قد تكسب مالاً أقل من ذلك العمل، لكن إن كان يجذبك حقاً فعليك أن ___.', options: ['follow your heart', 'speak your mind', 'jump out of your skin', 'pay an arm and a leg'], answer: 0,
          explainAr: 'follow your heart = يتبع إحساسه ورغبته العميقة (to go after your deeper feeling and instinct)، وهي من تعابير الجسم في الوحدة 8، والجملة من كتابك. عبارة if it really attracts you هي المفتاح. speak your mind = يقول رأيه بصراحة، jump out of your skin = يفزع، an arm and a leg = مبلغ باهظ.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'The League of Nations was the ……… of the United Nations.', promptAr: 'كانت عصبة الأمم ___ الأمم المتحدة.', options: ['predecessor', 'charter', 'disparity', 'ratification'], answer: 0,
          explainAr: 'predecessor = السَّلَف، أي نظام كان موجوداً قبل نظام آخر (a system that existed before another one). في نص الوحدة 6: "Its predecessor, the League of Nations, was created by the Treaty of Versailles in 1919". charter = ميثاق، disparity = تفاوت، ratification = تصديق.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'In which phrase are the two words linked (consonant to vowel)?', promptAr: 'في أيّ عبارة تُوصل الكلمتان في اللفظ (صوت ساكن ثم صوت متحرّك)؟', options: ['big car', 'good book', 'an interesting film', 'hot tea'], answer: 2,
          explainAr: 'وصل الأصوات (Sound linking، الوحدة 12): عندما تنتهي كلمة بصوت ساكن وتبدأ التالية بصوت متحرّك نصلهما: an‿interesting. في الخيارات الأخرى تبدأ الكلمة الثانية بصوت ساكن (c, b, t) فلا يوجد هذا الوصل.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'When they were combined, the two chemicals ……… violently with each other.', promptAr: 'عندما مُزجت المادتان الكيميائيتان، ___ مع بعضهما بعنف.', options: ['rotated', 'flashed', 'inserted', 'reacted'], answer: 3,
          explainAr: 'react with = يتفاعل مع، وهو ما تفعله المواد الكيميائية، والجملة من كتابك (الوحدة 11، أفعال العلوم والتكنولوجيا). rotate = يدور، flash = يومض، insert = يُدخل.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'Mr Jack’s dog is afraid of him because he is often cruel ……… it.', promptAr: 'كلب السيد جاك يخاف منه لأنه غالباً ما يكون قاسياً ___ الكلب.', options: ['to', 'with', 'for', 'at'], answer: 0,
          explainAr: 'الصفة cruel يليها حرف الجر to (cruel to = قاسٍ على)، وهي من الوحدة 9 (صفات يليها حرف جر). قارن: afraid of، angry with، good at.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'Which word has the same pronunciation as “hear”?', promptAr: 'أيّ كلمة لها لفظ كلمة "hear" نفسه؟', options: ['her', 'hair', 'here', 'heard'], answer: 2,
          explainAr: 'hear (يسمع) و here (هنا) كلمتان متجانستان لفظاً (homophones): لفظ واحد ومعنى وتهجئة مختلفان (الوحدة 1). her و hair و heard تُلفظ بشكل مختلف.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Future plans and ……… have a great importance in a person’s life.', promptAr: 'للخطط المستقبلية و___ أهمية كبيرة في حياة الإنسان.', options: ['decide', 'decisions', 'decisive', 'decided'], answer: 1,
          explainAr: 'بعد and نحتاج اسماً جمعاً يوازي plans: decisions = قرارات (اسم من الفعل decide). decide فعل، decisive صفة (حاسم)، decided تصريف الفعل. الجملة من تمرين عائلة الكلمة في الوحدة 1.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'conditional', prompt: 'Your brother wouldn’t have found such a nice job if he ……… had a university diploma.', promptAr: 'ما كان أخوك ليجد عملاً جيداً كهذا لو ___ يحمل شهادة جامعية.', lines: 1,
          accept: ['hadn’t', 'had not'], explainAr: 'الشرطية الثالثة (الوحدة 7): الجواب wouldn’t have found، فجملة if تأخذ الماضي التام. المعنى نفي (لو لم يكن معه شهادة) فنكتب hadn’t قبل had (had not had). الجملة من كتابك.' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'No sooner had they eaten dinner ……… the ceiling crashed onto the dining table.', promptAr: 'ما إن تناولوا العشاء ___ سقط السقف على طاولة الطعام.', lines: 1,
          accept: ['than'], explainAr: 'التقديم والتأخير (Inversion، الوحدة 12): No sooner + had + فاعل + تصريف ثالث ... than + ماضٍ بسيط. تأتي No sooner دائماً مع than (أما Hardly فتأتي مع when). الجملة من كتابك.' },
        { n: 25, kind: 'write', topic: 'grammar', prompt: 'Your car is a death trap. It should ……… been sent to the scrap years ago.', promptAr: 'سيارتك فخّ للموت. كان يجب أن تُرسَل إلى الخردة منذ سنوات.', lines: 1,
          accept: ['have'], explainAr: 'المبني للمجهول مع فعل ناقص في الماضي (الوحدة 3): should + have + been + التصريف الثالث، لشيء كان يجب أن يحدث في الماضي (years ago) ولم يحدث. الجملة من كتابك.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'In the Middle Ages, people were bled {to reduce inflammation}.', promptAr: 'في العصور الوسطى، كان الناس يُفصَدون (يُسحب دمهم) لتخفيف الالتهاب.', lines: 1,
          accept: ['Why were people bled in the Middle Ages?', 'Why were people bled?'], model: 'Why were people bled in the Middle Ages?', modelAr: 'لماذا كان الناس يُفصَدون في العصور الوسطى؟',
          explainAr: 'المسطَّر يبيّن الهدف (to + فعل) فنسأل بـ Why. الجملة مبنية للمجهول (were bled) فنقدّم were على الفاعل: Why were people bled...? الجملة من نص تاريخ الطب (الوحدة 3).' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'The first search engine was built {by the computer engineer Alan Emtage}.', promptAr: 'بنى مهندس الحاسوب آلان إمتاج أول محرّك بحث.', lines: 1,
          accept: ['Who was the first search engine built by?', 'Who built the first search engine?', 'By whom was the first search engine built?'], model: 'Who built the first search engine?', modelAr: 'من بنى أول محرّك بحث؟',
          explainAr: 'المسطَّر شخص فنسأل بـ Who. يمكن أن نسأل بالمبني للمعلوم: Who built...? (دون did لأن Who هنا فاعل)، أو بالمجهول: Who was the first search engine built by? الجملة من نص تاريخ الهندسة (الوحدة 4).' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'The necklace would be worth over {SYP 500,000} at current prices.', promptAr: 'ستكون قيمة العقد أكثر من 500,000 ليرة سورية بالأسعار الحالية.', lines: 1,
          accept: ['How much would the necklace be worth at current prices?', 'How much would the necklace be worth?'], model: 'How much would the necklace be worth at current prices?', modelAr: 'كم ستكون قيمة العقد بالأسعار الحالية؟',
          explainAr: 'المسطَّر مبلغ من المال فنسأل بـ How much. في الجملة فعل ناقص (would) فنقدّمه على الفاعل: How much would the necklace be worth...? الجملة من تمرين أقسام الكلام في الوحدة 11.' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'reported', prompt: '“I’ll have to get up early,” Judy said. (reported speech)', promptAr: 'قالت جودي: "سيكون عليّ أن أستيقظ باكراً". (الكلام المنقول)', lines: 2,
          accept: ['Judy said that she would have to get up early.', 'Judy said she would have to get up early.'], model: 'Judy said that she would have to get up early.', modelAr: 'قالت جودي إنه سيكون عليها أن تستيقظ باكراً.',
          explainAr: 'الكلام المنقول (الوحدة 11): بعد said نرجع الزمن خطوة إلى الوراء: will ← would، ويتغيّر الضمير I ← she. الجملة من تمرين رحلة جودي إلى حماة في كتابك.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'My neighbour disappeared six months ago. I haven’t seen him since then. (passive voice)', promptAr: 'اختفى جاري قبل ستة أشهر. لم أره منذ ذلك الحين. (المبني للمجهول)', lines: 2,
          accept: ['My neighbour disappeared six months ago. He hasn’t been seen since then.', 'He hasn’t been seen since then.', 'My neighbour disappeared six months ago. He has not been seen since then.', 'My neighbour hasn’t been seen since then.'],
          model: 'My neighbour disappeared six months ago. He hasn’t been seen since then.', modelAr: 'اختفى جاري قبل ستة أشهر. لم يُرَ منذ ذلك الحين.',
          explainAr: 'المبني للمجهول في المضارع التام (الوحدة 3): has/have + been + التصريف الثالث. المفعول him يصبح فاعلاً He فنقول He hasn’t been seen، ونحذف I لأن الفاعل غير مهم. الفعل disappeared لازم (بلا مفعول) فلا يُبنى للمجهول. الجملة من كتابك.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'A waiter offers you some sugar with your tea, but you are trying to lose weight. (Decline the offer)', promptAr: 'يعرض عليك النادل بعض السكر مع الشاي، لكنك تحاول إنقاص وزنك. (ارفض العرض بلطف)', lines: 2,
          accept: ['No, thank you. I’m trying to lose weight.', 'No thank you. No sugar. I’m trying to lose weight.', 'No, thank you.', 'No sugar, thank you. I’m trying to lose weight.', 'No, thanks. I’m trying to lose weight.', 'Not just at the moment, thank you.'],
          model: 'No, thank you. No sugar. I’m trying to lose weight.', modelAr: 'لا، شكراً. بلا سكر. أحاول أن أُنقص وزني.',
          explainAr: 'رفض العرض بلطف (Everyday English، الوحدة 9): No, thank you. / Not just at the moment, thank you. / It’s OK. ونذكر السبب بأدب. الجملة نفسها في حوار النادل وجون في كتابك.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'If I were you, I would study more. (Begin with: Were)', promptAr: 'لو كنتُ مكانك لدرستُ أكثر. (ابدأ بـ Were)', lines: 2,
          accept: ['Were I you, I would study more.', 'Were I you, I’d study more.'], model: 'Were I you, I would study more.', modelAr: 'لو كنتُ مكانك لدرستُ أكثر.',
          explainAr: 'التقديم والتأخير في الشرط (الوحدة 12): نحذف If ونقدّم were على الفاعل: Were I you = If I were you، ويبقى الجواب كما هو. الجملة من كتابك.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'I ………. (come) to the conclusion that nowadays nobody cares about anything.', promptAr: 'توصّلتُ إلى نتيجة أنه لم يعد أحد يهتمّ بأيّ شيء هذه الأيام.', lines: 1,
          accept: ['have come', "'ve come"], explainAr: 'nowadays تدلّ على نتيجة تخصّ الحاضر لحدث تمّ دون ذكر وقته، فنستخدم المضارع التام: have + come (التصريف الثالث لـ come هو come). الجملة من المراجعة 1.' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'The sun isn’t shining right now. I wish the sun ………. (be) shining.', promptAr: 'الشمس لا تشرق الآن. ليت الشمس تشرق.', lines: 1,
          accept: ['were', 'was'], explainAr: 'التمنّي في الحاضر (الوحدة 8): wish + ماضٍ بسيط، فـ is ← were (وتُقبل was). الجملة من تمرين كتابك.' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'All the goods that were purchased yesterday have defects, so they ………. (send) back to the manufacturer right now.', promptAr: 'كل البضائع التي اشتُريت أمس فيها عيوب، لذلك تُعاد إلى المصنّع الآن.', lines: 1,
          accept: ['are being sent'], explainAr: 'right now تدلّ على المضارع المستمر، والبضائع لا ترسل نفسها فنحتاج المبني للمجهول (الوحدة 3): am/is/are + being + التصريف الثالث (sent).' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'grammar', prompt: 'Hardly had I arrived home when …………………………..', promptAr: 'ما كدتُ أصل إلى البيت حتى …', lines: 2,
          accept: ['the phone rang.', 'it started to rain.', 'it began to rain.', 'my friend called me.', 'the lights went out.'], model: 'the phone rang.', modelAr: 'رنّ الهاتف.',
          explainAr: 'Hardly had + فاعل + تصريف ثالث ... when + ماضٍ بسيط (الوحدة 12): الحدث الثاني وقع مباشرة بعد الأول، فنكمل بجملة في الماضي البسيط (the phone rang).' },
        { n: 37, kind: 'write', topic: 'conditional', prompt: 'If it rains tomorrow, …………………………..', promptAr: 'إذا أمطرت غداً، …', lines: 2,
          accept: ['we will stay at home.', 'I will stay at home.', 'we won’t go to the park.', 'I will take my umbrella.', 'we will not go out.'], model: 'we will stay at home.', modelAr: 'سنبقى في البيت.',
          explainAr: 'If + مضارع بسيط (rains) لحدث ممكن في المستقبل (الشرطية الأولى)، فالجواب: will + المصدر.' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: Try not to become a man of success. Rather become a man of value.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['حاول ألا تصبح رجل نجاح، بل كن رجلاً ذا قيمة', 'لا تحاول أن تصبح رجلاً ناجحاً، بل حاول أن تصبح رجلاً ذا قيمة', 'حاول ألا تكون رجل نجاح بل كن رجل قيمة'], model: 'حاول ألّا تصبح رجلَ نجاح، بل كن رجلاً ذا قيمة.',
          explainAr: 'قول ألبرت أينشتاين من صفحة النجاح في كتابك (الوحدة 2). Try not to = حاول ألّا، Rather = بل، a man of value = رجل ذو قيمة.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: لا توم ولا بول يكذبان على أصدقائهما.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['Neither Tom nor Paul lies to their friends.', 'Neither Tom nor Paul lies to his friends.'],
          model: 'Neither Tom nor Paul lies to their friends.',
          explainAr: 'لا ... ولا ← neither ... nor (الوحدة 9)، وهي منفية بنفسها فلا نضيف not. الفعل يتبع الفاعل الأقرب (Paul مفرد) فنقول lies. المثال نفسه في كتابك.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Environmental health: how we can reduce health problems in public places.',
        topicAr: 'الصحة البيئية: كيف نخفّف المشكلات الصحية في الأماكن العامة.',
        words: 80,
        points: ['What health risks can be found in public places?', 'What laws can help to limit these risks?', 'How can we educate people about keeping a healthy environment?'],
        model: 'Environmental health is very important for all of us. Many public places, such as public transport, fast food restaurants and parks, can be full of germs. Bacteria and viruses spread quickly when people don’t wash their hands or when food and water are contaminated. To reduce these risks, the government should set laws to limit pollution, and there must be laws prohibiting smoking in public areas. Restaurants must keep their food clean, and schools and hospitals should be cleaned every day. In addition, awareness and health education are essential. Schools and the media can teach people how to keep their surroundings clean. If everyone made an effort, our cities would be safer and healthier places to live in.',
        modelAr: 'الصحة البيئية مهمّة جداً لنا جميعاً. فكثير من الأماكن العامة، كوسائل النقل العام ومطاعم الوجبات السريعة والحدائق، قد تكون مليئة بالجراثيم. وتنتشر البكتيريا والفيروسات بسرعة عندما لا يغسل الناس أيديهم أو عندما يتلوّث الطعام والماء. ولتخفيف هذه المخاطر، على الحكومة أن تضع قوانين تحدّ من التلوّث، ويجب أن تكون هناك قوانين تمنع التدخين في الأماكن العامة. ويجب على المطاعم أن تحافظ على نظافة طعامها، وينبغي تنظيف المدارس والمستشفيات كل يوم. إضافةً إلى ذلك، فالتوعية والتثقيف الصحي ضروريان؛ إذ تستطيع المدارس ووسائل الإعلام أن تعلّم الناس كيف يحافظون على نظافة محيطهم. لو بذل كل واحد منّا جهداً، لأصبحت مدننا أماكن أكثر أماناً وصحة للعيش.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: المخاطر الصحية في الأماكن العامة، والقوانين التي تحدّ منها، وتوعية الناس.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (such as, To reduce, In addition, and, If).',
          'استخدمتُ must و should بشكل صحيح، وجملة شرطية صحيحة (If + ماضٍ بسيط، would + مصدر).',
          'استخدمتُ كلمات من الوحدة 7 (germs, bacteria, viruses, pollution, contaminated, make an effort).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
