import type { Exam } from '../../../engine/types'

// A practice final Baccalaureate paper in the exact layout of the real paper (term1-a.ts), covering the whole book (Units 1–12).
// Passage A: Unit 10 cross-cultural situations (Speaking, page 104) — George, Shadi, Mary and Pascale.
// Passage B: Unit 9 reading "Citizenship", second part — from "In spite of the fact…" to the end (page 89).
export const term2F: Exam = {
  id: 't2-f',
  term: 2,
  title: 'Baccalaureate — Final Test (F)',
  titleAr: 'نموذج البكالوريا النهائي (F)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان البكالوريا الحقيقي، يغطي الكتاب كاملاً (الوحدات 1–12).',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'George was raised in the United States. He used to leave tips for waiters as a way of showing his gratitude for their service. But when he attempted to tip in a café in Seoul, his host was a little embarrassed.',
          'Shadi is from Syria. During his study at Yonsei university, he wrote the name of his South Korean friend in red ink. Their relationship was damaged because his friend considered what he did as a sign of ill-will and wishing harm.',
          'Mary is from England. When she was on vacation in Venezuela, some Venezuelan friends invited her to dinner at 9:00. She arrived at exactly 9:00, but her friends had not even arrived home yet.',
          'Pascale is from France. When she went to Egypt, she was invited to lunch at her new friend’s house. She wanted to add more salt to her dish, but her Egyptian friend was kind of upset.',
        ],
        paragraphsAr: [
          'نشأ جورج في الولايات المتحدة، وكان معتاداً أن يترك إكراميات للنُّدُل تعبيراً عن امتنانه لخدمتهم. لكنه عندما حاول أن يترك إكرامية في مقهى في سيول، شعر مضيفه ببعض الإحراج.',
          'شادي من سوريا. وخلال دراسته في جامعة يونسي، كتب اسم صديقه الكوري الجنوبي بالحبر الأحمر، فتضرّرت علاقتهما لأن صديقه عدّ ما فعله علامة على سوء النية وتمنّي الأذى.',
          'ماري من إنجلترا. وعندما كانت في عطلة في فنزويلا، دعاها بعض الأصدقاء الفنزويليين إلى العشاء في الساعة التاسعة. فوصلت في التاسعة تماماً، لكن أصدقاءها لم يكونوا قد وصلوا إلى البيت بعد.',
          'باسكال من فرنسا. وعندما ذهبت إلى مصر، دُعيت إلى الغداء في بيت صديقتها الجديدة. وأرادت أن تضيف مزيداً من الملح إلى طبقها، لكن صديقتها المصرية انزعجت نوعاً ما.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'Why did George use to leave tips for waiters?', promptAr: 'لماذا كان جورج معتاداً أن يترك إكراميات للنُّدُل؟', lines: 2,
              accept: ['He used to leave tips for waiters as a way of showing his gratitude for their service.', 'As a way of showing his gratitude for their service.', 'To show his gratitude for their service.', 'He used to leave tips to show his gratitude for their service.'],
              modelAr: 'كان يتركها تعبيراً عن امتنانه لخدمتهم.',
              explainAr: 'النص: "He used to leave tips for waiters as a way of showing his gratitude for their service." السؤال بـ Why فنجيب بالسبب/الهدف: as a way of showing... أو to show...' },
            { n: 2, kind: 'write', prompt: 'Why was the relationship between Shadi and his South Korean friend damaged?', promptAr: 'لماذا تضرّرت العلاقة بين شادي وصديقه الكوري الجنوبي؟', lines: 3,
              accept: ['Because his friend considered what he did as a sign of ill-will and wishing harm.', 'Because Shadi wrote his friend’s name in red ink, and his friend considered it a sign of ill-will and wishing harm.', 'Because he wrote the name of his South Korean friend in red ink.', 'Because he wrote his friend’s name in red ink.'],
              modelAr: 'لأن شادي كتب اسم صديقه بالحبر الأحمر، فعدّ صديقه ذلك علامة على سوء النية وتمنّي الأذى.',
              explainAr: 'النص: "he wrote the name of his South Korean friend in red ink. Their relationship was damaged because his friend considered what he did as a sign of ill-will and wishing harm." ابدأ الجواب بـ Because.' },
            { n: 3, kind: 'write', prompt: 'What did Mary find when she arrived at exactly 9:00?', promptAr: 'ماذا وجدت ماري عندما وصلت في التاسعة تماماً؟', lines: 2,
              accept: ['Her friends had not even arrived home yet.', 'She found that her friends had not even arrived home yet.', 'Her friends hadn’t arrived home yet.', 'She found that her friends had not arrived home yet.'],
              modelAr: 'وجدت أن أصدقاءها لم يكونوا قد وصلوا إلى البيت بعد.',
              explainAr: 'النص: "She arrived at exactly 9:00, but her friends had not even arrived home yet." لاحظ الماضي التام had not arrived لحدث لم يكن قد وقع قبل وصولها.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'The feeling of being thankful ……..', promptAr: 'الشعور بالشكر والعرفان', lines: 1, topic: 'vocab',
              accept: ['gratitude'], modelAr: 'الامتنان', explainAr: 'في النص "as a way of showing his gratitude for their service". gratitude = الامتنان، وهي اسم من الصفة grateful (grateful for في الوحدة 9).' },
            { n: 5, kind: 'write', prompt: 'Feeling nervous and uncomfortable, especially in front of other people ……..', promptAr: 'يشعر بالتوتّر وعدم الارتياح، خاصةً أمام الآخرين', lines: 1, topic: 'vocab',
              accept: ['embarrassed'], modelAr: 'مُحرَج', explainAr: 'في النص "his host was a little embarrassed". embarrassed = مُحرَج، صفة تنتهي بـ ed لأنها تصف شعور الشخص.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'George’s host in Seoul was pleased when George attempted to tip in a café.', promptAr: 'سُرّ مضيف جورج في سيول عندما حاول جورج أن يترك إكرامية في مقهى.', lines: 2,
              accept: ['George’s host in Seoul was a little embarrassed when George attempted to tip in a café.', 'George’s host in Seoul was embarrassed when George attempted to tip in a café.', 'George’s host in Seoul was a little embarrassed.'],
              modelAr: 'شعر مضيف جورج في سيول ببعض الإحراج عندما حاول جورج أن يترك إكرامية في مقهى.',
              explainAr: 'النص: "But when he attempted to tip in a café in Seoul, his host was a little embarrassed." فالخطأ كلمة pleased والصواب embarrassed.' },
            { n: 7, kind: 'write', prompt: 'Pascale’s Egyptian friend was happy when Pascale wanted to add more salt to her dish.', promptAr: 'فرحت صديقة باسكال المصرية عندما أرادت باسكال أن تضيف مزيداً من الملح إلى طبقها.', lines: 2,
              accept: ['Pascale’s Egyptian friend was kind of upset when Pascale wanted to add more salt to her dish.', 'Pascale’s Egyptian friend was upset when Pascale wanted to add more salt to her dish.', 'Pascale’s Egyptian friend was kind of upset.'],
              modelAr: 'انزعجت صديقة باسكال المصرية نوعاً ما عندما أرادت باسكال أن تضيف مزيداً من الملح إلى طبقها.',
              explainAr: 'النص: "She wanted to add more salt to her dish, but her Egyptian friend was kind of upset." فالخطأ كلمة happy والصواب upset (منزعجة).' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'In spite of the fact that all Syrian citizens enjoy freedom, protection and legal rights, they also have responsibilities that are voluntary as well as obligatory. Every Syrian citizen must obey state laws, and pay the penalties when a law is broken. All citizens must pay taxes in one form or another. It is the responsibility of citizens to pass along the importance of good citizenship to future generations by teaching their children how to obey the law. The nationality law does not give Syrians the right to unilaterally abandon their Syrian nationality.',
          'Syrians have the right to pride themselves on being good citizens in a nation of ancient civilisations that helped to build and enrich human culture. They have had a vital role in developing human civilisation. From the earliest years, laws representing various points of view have been passed and guidelines have been developed through generations to instruct citizens on Syrian history, values, rights, and responsibilities.',
        ],
        paragraphsAr: [
          'رغم أن جميع المواطنين السوريين يتمتّعون بالحرية والحماية والحقوق القانونية، فإن عليهم أيضاً مسؤوليات طوعية وإلزامية معاً. فيجب على كل مواطن سوري أن يطيع قوانين الدولة، وأن يدفع الغرامات عند مخالفة القانون. ويجب على جميع المواطنين دفع الضرائب بشكل أو بآخر. ومن مسؤولية المواطنين أن ينقلوا أهمية المواطنة الصالحة إلى الأجيال القادمة بتعليم أبنائهم كيف يطيعون القانون. ولا يمنح قانون الجنسية السوريين الحق في التخلّي عن جنسيتهم السورية من طرف واحد.',
          'يحقّ للسوريين أن يفخروا بكونهم مواطنين صالحين في وطن حضارات عريقة أسهمت في بناء الثقافة الإنسانية وإغنائها. وقد كان لهم دور حيوي في تطوير الحضارة الإنسانية. ومنذ أقدم السنين صدرت قوانين تمثّل وجهات نظر متنوّعة، ووُضعت عبر الأجيال مبادئ توجيهية لتعريف المواطنين بتاريخ سوريا وقيمها وبحقوقهم ومسؤولياتهم.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'Citizens pass along the importance of good citizenship to future generations by ……..', promptAr: 'ينقل المواطنون أهمية المواطنة الصالحة إلى الأجيال القادمة عن طريق ……..', options: ['paying taxes', 'passing new laws', 'teaching their children how to obey the law', 'abandoning their nationality'], answer: 2,
              explainAr: 'النص: "It is the responsibility of citizens to pass along the importance of good citizenship to future generations by teaching their children how to obey the law."' },
            { n: 9, kind: 'mcq', prompt: 'According to the text, Syrians ……..', promptAr: 'بحسب النص، السوريون ……..', options: ['can abandon their Syrian nationality unilaterally', 'do not have to pay taxes', 'have no responsibilities towards their country', 'have had a vital role in developing human civilisation'], answer: 3,
              explainAr: 'النص: "They have had a vital role in developing human civilisation." أما الخيارات الأخرى فتناقض النص: قانون الجنسية لا يمنحهم حق التخلّي عنها من طرف واحد، وعليهم دفع الضرائب، ولهم مسؤوليات.' },
            { n: 10, kind: 'mcq', prompt: 'Laws representing various points of view have been passed ……..', promptAr: 'صدرت قوانين تمثّل وجهات نظر متنوّعة ……..', options: ['from the earliest years', 'only in the 18th century', 'during the Middle Ages', 'only in recent years'], answer: 0,
              explainAr: 'آخر جملة في النص: "From the earliest years, laws representing various points of view have been passed". لاحظ المضارع التام المبني للمجهول have been passed.' },
            { n: 11, kind: 'mcq', prompt: 'A word in the text which means “done by only one member without the agreement of others” is ……..', promptAr: 'كلمة في النص تعني "يتمّ من طرف واحد دون موافقة الآخرين" هي ……..', options: ['voluntary', 'unilaterally', 'vested', 'obligatory'], answer: 1, topic: 'vocab',
              explainAr: 'unilaterally = من طرف واحد، وهي في النص "the right to unilaterally abandon their Syrian nationality" (من كلمات الوحدة 9). voluntary = طوعي، vested = مُخوَّل رسمياً، obligatory = إلزامي.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'Syrians have the right to pride themselves on ……………………', promptAr: 'يحقّ للسوريين أن يفخروا بـ ……', lines: 2,
              accept: ['being good citizens in a nation of ancient civilisations that helped to build and enrich human culture', 'being good citizens in a nation of ancient civilisations', 'being good citizens'],
              modelAr: 'كونهم مواطنين صالحين في وطن حضارات عريقة أسهمت في بناء الثقافة الإنسانية وإغنائها.',
              explainAr: 'النص: "Syrians have the right to pride themselves on being good citizens in a nation of ancient civilisations that helped to build and enrich human culture." بعد حرف الجر on نستخدم الفعل + ing (being).' },
            { n: 13, kind: 'write', prompt: 'Guidelines have been developed through generations to instruct citizens on ……………………', promptAr: 'وُضعت عبر الأجيال مبادئ توجيهية لتعريف المواطنين بـ ……', lines: 2,
              accept: ['Syrian history, values, rights, and responsibilities', 'Syrian history, values, rights and responsibilities'],
              modelAr: 'تاريخ سوريا وقيمها وحقوقهم ومسؤولياتهم.',
              explainAr: 'آخر جملة في النص: "guidelines have been developed through generations to instruct citizens on Syrian history, values, rights, and responsibilities."' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'My neighbour is a great writer. His new book is about to be ……… next month.', promptAr: 'جاري كاتب عظيم. كتابه الجديد على وشك أن ___ الشهر القادم.', options: ['got out', 'got off', 'picked up', 'put on'], answer: 0,
          explainAr: 'get something out = يُصدر/ينشر شيئاً (كتاباً مثلاً)، وهو فعل مركّب بمعنى مجازي من الوحدة 12، والجملة من المراجعة 3. get off = ينزل من وسيلة نقل، pick up = يلتقط أو يقلّ أحداً، put on = يرتدي أو يزداد وزنه.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'A bodyguard is a person ……… protects important people from being attacked.', promptAr: 'الحارس الشخصي شخصٌ ___ يحمي الأشخاص المهمّين من التعرّض للهجوم.', options: ['which', 'who', 'whose', 'where'], answer: 1,
          explainAr: 'بعد a person (عاقل) ويليه فعل مباشرةً (protects) نستخدم who (الوحدة 5). which لغير العاقل، whose للملكية ويليها اسم، where للمكان.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'I have known her for a long time now. We ……… together.', promptAr: 'أعرفها منذ زمن طويل. ___ معاً.', options: ['gave pumpkins', 'lost face', 'broke bread', 'saved face'], answer: 2,
          explainAr: 'break bread with = أن تكون صديقاً مقرّباً وبينكما صلة عميقة (تعابير الوحدة 10). give someone pumpkins = يرفض شخصاً، lose face = يفقد ماء وجهه، save face = يحفظ ماء وجهه.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'Robert is an accredited ……… with herbal medicine and nutritional training.', promptAr: 'روبرت ___ معتمَد مدرَّب على الطب العشبي والتغذية.', options: ['cardiologist', 'allergist', 'pediatrician', 'naturopath'], answer: 3,
          explainAr: 'naturopath = المعالج بالطب الطبيعي (specialises in natural cures and remedies)، ويناسبه الطب العشبي والتغذية، والجملة من كتابك (الوحدة 3). cardiologist = طبيب القلب، allergist = طبيب الحساسية، pediatrician = طبيب الأطفال.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'In which word is the stress on the second syllable?', promptAr: 'في أي كلمة يقع النبر على المقطع الثاني؟', options: ['unfriendly', 'dangerous', 'comfortable', 'sociable'], answer: 0,
          explainAr: 'نبر المقاطع (الوحدة 8): البادئات مثل un لا تُنبر، فيقع النبر في unfriendly على المقطع الثاني: un-FRIEND-ly. وكذلك اللواحق مثل -ous و -able لا تُنبر، فالنبر في DANgerous و COMfortable و SOciable على المقطع الأول.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'When she pulled the large lever, the wheel began to ……… .', promptAr: 'عندما سحبت الذراع الكبيرة، بدأت العجلة ___ .', options: ['dissect', 'rotate', 'insert', 'extract'], answer: 1,
          explainAr: 'rotate = يدور، وهي من أفعال العلوم والتكنولوجيا في الوحدة 11، والجملة من كتابك. dissect = يشرّح، insert = يُدخل، extract = يستخرج.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'What time does the flight ……… Cairo arrive?', promptAr: 'في أي ساعة تصل الرحلة ___ القاهرة؟', options: ['onto', 'off', 'from', 'out of'], answer: 2,
          explainAr: 'حروف جر الحركة (الوحدة 4): from = من (نقطة الانطلاق)، فالرحلة القادمة من القاهرة. onto = إلى سطح شيء، off = عن سطح شيء، out of = إلى خارج شيء.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: '“The wind blew softly as we watched the river wind its way through the valley.” The second “wind” means ……… .', promptAr: '"هبّت الريح بلطف بينما كنا نشاهد النهر ___ في الوادي." كلمة "wind" الثانية تعني ___ .', options: ['the moving of air', 'to shut', 'a type of metal', 'to move or have a curving course'], answer: 3,
          explainAr: 'الكلمات المتجانسة كتابةً (Homographs، الوحدة 9) تُكتب بالطريقة نفسها وتختلف في المعنى وربما في اللفظ. wind الأولى اسم /wɪnd/ = الريح، والثانية فعل /waɪnd/ = يتعرّج في مساره. to shut معنى close، و a type of metal معنى lead.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Individuals have ……… dreams in their day-to-day existence.', promptAr: 'لدى الأفراد أحلام ___ في حياتهم اليومية.', options: ['vary', 'various', 'variety', 'variously'], answer: 1,
          explainAr: 'قبل الاسم dreams نحتاج صفة: various = متنوّعة، والجملة من تمرين عائلة الكلمة في الوحدة 1. vary فعل، variety اسم، variously ظرف.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'I can’t go with you tomorrow but I wish I ……… go with you.', promptAr: 'لا أستطيع الذهاب معك غداً لكنني أتمنّى لو أستطيع الذهاب معك.', lines: 1,
          accept: ['could'], explainAr: 'التمنّي (الوحدة 8): I wish + could + المصدر للتعبير عن أمنية لا نقدر عليها في الحاضر أو المستقبل. can’t ← wish I could.' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'You ……… use your mobile phone in a gas station. It’s against the rules.', promptAr: 'ممنوع أن تستخدم هاتفك المحمول في محطة الوقود. هذا مخالف للقواعد.', lines: 1,
          accept: ['mustn’t', 'must not', 'can’t', 'cannot'], explainAr: 'الأفعال الناقصة (الوحدة 10): mustn’t تعني أنك غير مسموح لك بفعل الشيء لأنه مخالف للقواعد. لا تخلط بينها وبين don’t have to التي تعني "لست مضطراً".' },
        { n: 25, kind: 'write', topic: 'tense', prompt: 'When she came into the room, the burglar ……… already left.', promptAr: 'عندما دخلت الغرفة كان اللص قد غادر.', lines: 1,
          accept: ['had'], explainAr: 'الماضي التام (الوحدة 2): had + التصريف الثالث (left) لحدث وقع قبل حدث آخر في الماضي (came). والجملة من كتابك.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'They’ll have a flat {in the centre of Madrid}.', promptAr: 'سيكون لهم شقة في وسط مدريد.', lines: 1,
          accept: ['Where will they have a flat?'], modelAr: 'أين ستكون لهم شقة؟',
          explainAr: 'المسطَّر مكان فنسأل بـ Where. الفعل مستقبل (’ll have = will have) فنقدّم will على الفاعل: Where will they have a flat? والجملة من حوار الوحدة 10.' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'Doctors need a sample of your blood {to see what infection you have}.', promptAr: 'يحتاج الأطباء عيّنة من دمك ليعرفوا أي عدوى لديك.', lines: 1,
          accept: ['Why do doctors need a sample of my blood?', 'Why do doctors need a sample of your blood?', 'Why do doctors need a sample of blood?'], modelAr: 'لماذا يحتاج الأطباء عيّنة من دمي؟',
          explainAr: 'المسطَّر يبيّن الهدف (to + فعل) فنسأل بـ Why. الفعل need مضارع بسيط مع جمع (doctors) فنستخدم do. ونغيّر your إلى my لأن السائل يتحدّث عن نفسه.' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'Our team has won {ten} out of our twelve matches this season.', promptAr: 'فاز فريقنا في عشر مباريات من أصل اثنتي عشرة هذا الموسم.', lines: 1,
          accept: ['How many matches has your team won this season?', 'How many matches has your team won out of twelve this season?', 'How many of your twelve matches has your team won this season?', 'How many matches has your team won?'], modelAr: 'كم مباراة فاز فيها فريقكم هذا الموسم؟',
          explainAr: 'المسطَّر عدد (ten) مع اسم معدود فنسأل بـ How many + الاسم الجمع (matches). الفعل مضارع تام (has won) فنقدّم has على الفاعل، ونغيّر our إلى your.' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'grammar', prompt: 'He felt disappointed. He felt misunderstood. (both … and)', promptAr: 'شعر بخيبة الأمل. شعر بأنه أُسيء فهمه. (both … and)', lines: 2,
          accept: ['He felt both disappointed and misunderstood.'],
          modelAr: 'شعر بخيبة الأمل وبأنه أُسيء فهمه معاً.',
          explainAr: 'أدوات الربط المزدوجة (الوحدة 9): نضع both قبل الصفة الأولى و and قبل الثانية، مع التوازي في التركيب (صفة + صفة): felt both disappointed and misunderstood. والجملة من تمرين كتابك.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'I have never been to London before. (Begin with: Never)', promptAr: 'لم أزر لندن من قبل أبداً. (ابدأ بـ Never)', lines: 2,
          accept: ['Never have I been to London before.', 'Never before have I been to London.'],
          modelAr: 'لم أزر لندن من قبل أبداً.',
          explainAr: 'القلب (Inversion، الوحدة 12): عندما نبدأ الجملة بظرف نفي مثل Never نقدّم الفعل المساعد على الفاعل: Never + have + I + been. والجملة من كتابك.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Your brother tells you: “I’ve won a lottery!” (Express surprise)', promptAr: 'يقول لك أخوك: "لقد ربحتُ اليانصيب!" (عبّر عن الدهشة)', lines: 2,
          accept: ['Have you? How amazing!', 'A lottery?! How amazing!', 'You’re kidding!', 'Are you serious?', 'Oh, that’s incredible!', 'Really? How amazing!', 'Have you? That’s incredible!', 'You’ve won a lottery?! Are you serious?'],
          model: 'Have you? How amazing!', modelAr: 'حقاً؟ يا للروعة!',
          explainAr: 'تعابير الدهشة من الوحدة 10 (Everyday English): Is he? / Have you? / How amazing! / That’s incredible! / Are you serious? / You’re kidding! ويمكن تكرار الخبر بنبرة سؤال: A lottery?!' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'A friend of mine, who’s an electrician, is going to repair my DVD player next week. (causative verb)', promptAr: 'صديق لي يعمل كهربائياً سيصلح مشغّل أقراص الـ DVD الخاص بي الأسبوع القادم. (الفعل السببي)', lines: 2,
          accept: ['I am going to have my DVD player repaired next week.', 'I am going to have my DVD player repaired by a friend of mine next week.', 'I am going to get my DVD player repaired next week.', 'I am going to have my DVD player repaired by a friend of mine, who is an electrician, next week.', 'I’m going to have my DVD player repaired next week.'],
          modelAr: 'سأُصلح مشغّل الـ DVD الخاص بي (عند صديق لي) الأسبوع القادم.',
          explainAr: 'السببي (الوحدة 4): have/get + مفعول + التصريف الثالث. الجملة الأصلية بـ is going to فنقول: I am going to have my DVD player repaired. والجملة من تمرين كتابك.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'Jane, why are you sweating? Because I ………. (sweep) the floors.', promptAr: 'جين، لماذا تتعرّقين؟ لأنني كنت أكنس الأرضيات.', lines: 1,
          accept: ['have been sweeping'], explainAr: 'المضارع التام المستمر (الوحدة 1): have been + فعل ing لنشاط استمرّ حتى الآن وأثره ظاهر الآن (التعرّق). والجملة من كتابك.' },
        { n: 34, kind: 'write', topic: 'conditional', prompt: 'If the referee had seen the foul, he ………. (award) a penalty kick to our team.', promptAr: 'لو رأى الحكم الخطأ لمنح فريقنا ركلة جزاء.', lines: 1,
          accept: ['would have awarded'], explainAr: 'If + ماضٍ تام (had seen) ← الشرطية الثالثة (الوحدة 7)، فالجواب would have + التصريف الثالث: would have awarded.' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'Our classroom doesn’t have coloured walls. I wish our classroom ………. (have) coloured walls.', promptAr: 'ليس في صفّنا جدران ملوّنة. أتمنّى لو كانت في صفّنا جدران ملوّنة.', lines: 1,
          accept: ['had'], explainAr: 'التمنّي عن الحاضر (الوحدة 8): I wish + ماضٍ بسيط. doesn’t have (حاضر) ← wish ... had.' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'conditional', prompt: 'If I won the lottery, …………………………..', promptAr: 'لو ربحتُ اليانصيب، …', lines: 2,
          accept: ['I would build a huge house by the beach.', 'I would travel around the world.', 'I would buy a new car.', 'I would help the poor.'], model: 'I would build a huge house by the beach.', modelAr: 'لبنيتُ بيتاً ضخماً على الشاطئ.',
          explainAr: 'If + ماضٍ بسيط (won) ← الشرطية الثانية لموقف تخيّلي، فالجواب: would + المصدر. الجواب النموذجي من تمرين كتابك (الوحدة 7).' },
        { n: 37, kind: 'write', topic: 'conditional', prompt: 'Unless you study hard, …………………………..', promptAr: 'ما لم تدرس بجدّ، …', lines: 2,
          accept: ['you won’t pass the exam.', 'you will fail the exam.', 'you won’t get good marks.', 'you won’t succeed.'], model: 'you won’t pass the exam.', modelAr: 'لن تنجح في الامتحان.',
          explainAr: 'Unless = if ... not، ويليها مضارع بسيط (study)، والجملة الرئيسية بالمستقبل: will/won’t + المصدر (مثل الشرطية الأولى).' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: When in Rome, do as the Romans do.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['عندما تكون في روما افعل كما يفعل الرومان', 'إذا كنت في روما فافعل كما يفعل الرومان', 'حين تكون في روما تصرّف كما يتصرّف الرومان'],
          model: 'عندما تكون في روما افعل كما يفعل الرومان.',
          explainAr: 'القول من كتابك (الوحدة 10). When in Rome = عندما تكون في روما، do as = افعل كما، the Romans = الرومان. ومعناه: احترم عادات البلد الذي تزوره (ويقابله في العربية: "يا غريب كن أديباً").' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: هل يمكنك أن تطلب منها أن تعاود الاتصال بي من فضلك؟', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['Could you ask her to ring me back, please?', 'Could you ask her to call me back, please?', 'Can you ask her to ring me back, please?', 'Can you ask her to call me back, please?', 'Could you please ask her to call me back?', 'Could you please ask her to ring me back?'],
          model: 'Could you ask her to ring me back, please?',
          explainAr: 'تعابير الهاتف (الوحدة 7): Could you ask her to ring me back, please? هل يمكنك ← Could you (طلب مهذّب)، أن تطلب منها أن ← ask her to + المصدر، تعاود الاتصال بي ← ring/call me back.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Studying in another country.',
        topicAr: 'الدراسة في بلد آخر.',
        words: 80,
        points: ['Which country would you choose, and why?', 'What problems (such as culture shock) might you face there?', 'How would you deal with these problems?'],
        model: 'If I had the chance to study in another country, I would choose Britain because I want to improve my English and study medicine there. However, living abroad is not easy. At first, everything would seem new and exciting, but later I might suffer from homesickness and culture shock. People might misunderstand what I am trying to say, and the customs, food and weather would be different. To deal with these problems, I would learn about the customs of the host country before I travel. I would also try to make friends with locals and keep in touch with my family online. I believe this experience would make me stronger and more independent.',
        modelAr: 'لو أُتيحت لي فرصة الدراسة في بلد آخر لاخترتُ بريطانيا لأنني أريد تحسين لغتي الإنجليزية ودراسة الطب هناك. لكن العيش في الخارج ليس سهلاً. في البداية سيبدو كل شيء جديداً ومثيراً، لكنني قد أعاني لاحقاً من الحنين إلى الوطن والصدمة الثقافية. وقد يسيء الناس فهم ما أحاول قوله، وستكون العادات والطعام والطقس مختلفة. وللتعامل مع هذه المشكلات، سأتعرّف على عادات البلد المضيف قبل أن أسافر، وسأحاول أيضاً مصادقة السكان المحليين والبقاء على تواصل مع عائلتي عبر الإنترنت. أعتقد أن هذه التجربة ستجعلني أقوى وأكثر استقلالاً.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: البلد الذي أختاره وسببه، والمشكلات المتوقّعة، وكيف أتعامل معها.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ الشرطية الثانية (If I had the chance…, I would…) وأفعال would / might بشكل صحيح.',
          'استخدمتُ أدوات ربط (However, but, and, also, because, To deal with…).',
          'استخدمتُ كلمات من الوحدة 10 (culture shock, homesickness, customs, host country, locals).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
