import type { Exam } from '../../../engine/types'

// A past Term 1 paper (Grade 12, Scientific Section, 2025/2026), typed in exactly as printed,
// with the teacher's answer key. The header says 150 but the marks printed on the tasks add up to 300,
// so the paper is marked out of 300 here, task by task.
export const term1A: Exam = {
  id: 't1-a',
  term: 1,
  title: 'Term 1 — Test (A)',
  titleAr: 'الفصل الأول — النموذج (A)',
  minutes: 150,
  totalMarks: 300,
  real: true,
  sourceAr: 'امتحان حقيقي للفصل الأول 2025/2026 (الفرع العلمي) كما طُبع، مع حلّ الأستاذ وشرح كل إجابة.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'Medical technology engineering or biomedical engineering is concerned with studying the body from an engineering point of view, in order to design suitable artificial limbs, organs, or other medical devices. It helps doctors define their tasks and facilitates their work more, so the medical device has become an essential assistant for the doctors in all steps, starting from diagnosis, to the end of the treatment course. Medical devices can be divided into two parts, diagnostic medical devices, most notably the ultrasound device, and medical therapeutic devices used in chemical treatments. Another classification includes three categories. Firstly, we have simple devices such as bandages, body temperature meters and others. There are also more complex devices that require a certain amount of caution, such as those that emit X-rays. Finally, there are those which require a deep study before their use, such as the valves used in the artificial heart, in addition to the artificial joints.',
        ],
        paragraphsAr: [
          'هندسة التكنولوجيا الطبية أو الهندسة الطبية الحيوية تهتمّ بدراسة الجسم من وجهة نظر هندسية، من أجل تصميم أطراف أو أعضاء صناعية مناسبة أو أجهزة طبية أخرى. وهي تساعد الأطباء على تحديد مهامّهم وتسهّل عملهم أكثر، لذلك أصبح الجهاز الطبي مساعداً أساسياً للأطباء في كل الخطوات، بدءاً من التشخيص وحتى نهاية مسار العلاج. يمكن تقسيم الأجهزة الطبية إلى قسمين: أجهزة طبية تشخيصية، وأبرزها جهاز الأمواج فوق الصوتية (الإيكو)، وأجهزة طبية علاجية تُستخدم في العلاجات الكيميائية. ويوجد تصنيف آخر يضمّ ثلاث فئات: أولاً، الأجهزة البسيطة مثل الضمادات ومقاييس حرارة الجسم وغيرها. وهناك أيضاً أجهزة أكثر تعقيداً تتطلّب قدراً معيّناً من الحذر، مثل الأجهزة التي تُصدر الأشعة السينية. وأخيراً، هناك أجهزة تتطلّب دراسة عميقة قبل استخدامها، مثل الصمّامات المستخدمة في القلب الصناعي، إضافةً إلى المفاصل الصناعية.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'What is biomedical engineering concerned with?', promptAr: 'بماذا تهتمّ الهندسة الطبية الحيوية؟', lines: 3,
              accept: ['Biomedical engineering is concerned with studying the body from an engineering point of view in order to design artificial limbs, organs and other medical devices.', 'It is concerned with studying the body from an engineering point of view.', 'Studying the body from an engineering point of view.'],
              modelAr: 'تهتمّ الهندسة الطبية الحيوية بدراسة الجسم من وجهة نظر هندسية لتصميم أطراف وأعضاء صناعية وأجهزة طبية أخرى.',
              explainAr: 'الجواب في الجملة الأولى: "is concerned with studying the body from an engineering point of view, in order to design...". انقل الجملة وابدأ بفاعل كامل.' },
            { n: 2, kind: 'write', prompt: 'How is medical technology engineering useful for doctors?', promptAr: 'كيف تفيد هندسة التكنولوجيا الطبية الأطباء؟', lines: 3,
              accept: ['It helps doctors define their tasks and facilitates their work more.', 'It helps them define their tasks and facilitates their work.'],
              modelAr: 'تساعد الأطباء على تحديد مهامّهم وتسهّل عملهم أكثر.',
              explainAr: 'الجملة الثانية في النص: "It helps doctors define their tasks and facilitates their work more".' },
            { n: 3, kind: 'write', prompt: 'Give two examples of complex medical devices which require a deep study.', promptAr: 'أعطِ مثالين على أجهزة طبية معقّدة تتطلّب دراسة عميقة.', lines: 2,
              accept: ['The valves used in the artificial heart, and the artificial joints.', 'The valves used in the artificial heart and the artificial joints.', 'Valves used in the artificial heart and artificial joints.'],
              modelAr: 'الصمّامات المستخدمة في القلب الصناعي، والمفاصل الصناعية.',
              explainAr: 'آخر جملة: "those which require a deep study before their use, such as the valves used in the artificial heart, in addition to the artificial joints". انتبه: الأشعة السينية تتطلّب "حذراً" لا "دراسة عميقة".' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'Relating to the treatment or cure of an illness ……..', promptAr: 'متعلّق بمعالجة المرض أو شفائه', lines: 1, topic: 'vocab',
              accept: ['therapeutic'], modelAr: 'علاجي', explainAr: 'في النص "medical therapeutic devices" — أجهزة علاجية. therapeutic صفة تعني "متعلّق بالعلاج".' },
            { n: 5, kind: 'write', prompt: 'A medical process using the reflections of high-frequency sound waves to construct an image of a body organ. …………', promptAr: 'إجراء طبي يستخدم انعكاسات الأمواج الصوتية عالية التردّد لتكوين صورة لعضو في الجسم', lines: 1, topic: 'vocab',
              accept: ['ultrasound'], modelAr: 'الأمواج فوق الصوتية (الإيكو)', explainAr: 'في النص "diagnostic medical devices, most notably the ultrasound device". ultrasound = التصوير بالأمواج فوق الصوتية.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'Doctors can use medical devices only in diagnosis.', promptAr: 'يمكن للأطباء استخدام الأجهزة الطبية في التشخيص فقط.', lines: 2,
              accept: ['Doctors can use medical devices in diagnosis and treatment.', 'Doctors can use medical devices in all steps, from diagnosis to the end of the treatment course.', 'Doctors can use medical devices in diagnosis and in treatment.'],
              modelAr: 'يمكن للأطباء استخدام الأجهزة الطبية في التشخيص والعلاج.',
              explainAr: 'النص يقول إن الجهاز الطبي مساعد "in all steps, starting from diagnosis, to the end of the treatment course"، فالخطأ كلمة only.' },
            { n: 7, kind: 'write', prompt: 'Bandages and body temperature meters are two examples of complex devices that require a certain amount of caution.', promptAr: 'الضمادات ومقاييس حرارة الجسم مثالان على أجهزة معقّدة تتطلّب قدراً من الحذر.', lines: 2,
              accept: ['Bandages and body temperature meters are two examples of simple devices.', 'Bandages and body temperature meters are simple devices.'],
              modelAr: 'الضمادات ومقاييس حرارة الجسم مثالان على الأجهزة البسيطة.',
              explainAr: 'النص: "Firstly, we have simple devices such as bandages, body temperature meters". أما الأجهزة التي تتطلّب الحذر فهي التي تُصدر الأشعة السينية.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          "Human rights are the rights which one acquires by being alive, while civil rights are the rights that one obtains by being a legal member of a certain political life. In other words, civil rights are the rights of citizens to political and social freedom and equality. They guarantee equal social opportunities and equal protection under the law, regardless of race, religion, or other personal characteristics. Civil rights are a class of rights that protect individuals' freedom from violation by governments, social organizations, and private individuals. They ensure one's right to participate in the civil and political life of society and the state without discrimination or repression. Unlike other rights concepts, such as human rights or natural rights, in which people acquire rights inherently, perhaps from God, civil rights must be given and guaranteed by the power of the state. Examples of civil rights include the right to vote, the right to a fair trial, the right to government services, the right to a public education, and the right to use public facilities. Civil rights are an essential component of democracy; when individuals are prevented from participating in political society, their civil rights are being denied. Civil rights are secured by positive government action, often in the form of legislation.",
        ],
        paragraphsAr: [
          'حقوق الإنسان هي الحقوق التي يكتسبها المرء بكونه حيّاً، بينما الحقوق المدنية هي الحقوق التي يحصل عليها بكونه عضواً قانونياً في حياة سياسية معيّنة. بعبارة أخرى، الحقوق المدنية هي حقوق المواطنين في الحرية والمساواة السياسية والاجتماعية. فهي تضمن فرصاً اجتماعية متساوية وحماية متساوية بموجب القانون، بغضّ النظر عن العِرق أو الدين أو غيرهما من الصفات الشخصية. الحقوق المدنية فئة من الحقوق تحمي حرية الأفراد من الانتهاك من قِبل الحكومات والمنظمات الاجتماعية والأفراد. وهي تضمن حق المرء في المشاركة في الحياة المدنية والسياسية للمجتمع والدولة دون تمييز أو قمع. وعلى خلاف مفاهيم الحقوق الأخرى، كحقوق الإنسان أو الحقوق الطبيعية التي يكتسبها الناس بالفطرة، ربما من الله، فإن الحقوق المدنية يجب أن تمنحها سلطة الدولة وتضمنها. ومن أمثلة الحقوق المدنية: حق التصويت، والحق في محاكمة عادلة، والحق في الخدمات الحكومية، والحق في التعليم العام، والحق في استخدام المرافق العامة. الحقوق المدنية عنصر أساسي من عناصر الديمقراطية؛ فعندما يُمنع الأفراد من المشاركة في المجتمع السياسي، تكون حقوقهم المدنية مسلوبة. وتُصان الحقوق المدنية بعمل حكومي إيجابي، غالباً على شكل تشريعات.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'Individuals get their human rights ……..', promptAr: 'يحصل الأفراد على حقوقهم الإنسانية ……..', options: ['if they are political', 'during lifetime', 'after the age of 18', 'when they vote'], answer: 1,
              explainAr: 'النص: "Human rights are the rights which one acquires by being alive" — أي طوال حياته (during lifetime).' },
            { n: 9, kind: 'mcq', prompt: 'Civil rights are given to individuals ……..', promptAr: 'تُمنح الحقوق المدنية للأفراد ……..', options: ['by governments', 'by being alive', 'if they are rich', 'by violation of law'], answer: 0,
              explainAr: 'النص: "civil rights must be given and guaranteed by the power of the state" — تمنحها الدولة (الحكومات). أما "by being alive" فهي لحقوق الإنسان.' },
            { n: 10, kind: 'mcq', prompt: 'People enjoy their civil rights because of the …………… formed by the government.', promptAr: 'يتمتّع الناس بحقوقهم المدنية بسبب الـ …… التي تضعها الحكومة.', options: ['discrimination', 'violations', 'legislations', 'human rights'], answer: 2,
              explainAr: 'آخر جملة: "Civil rights are secured by positive government action, often in the form of legislation" — التشريعات.' },
            { n: 11, kind: 'mcq', prompt: 'An action that breaks a law or an agreement is …..', promptAr: 'الفعل الذي يخرق قانوناً أو اتفاقاً هو …..', options: ['discrimination', 'trial', 'vote', 'violation'], answer: 3, topic: 'vocab',
              explainAr: 'violation = انتهاك/خرق، وهي في النص "freedom from violation by governments". discrimination = تمييز، trial = محاكمة، vote = تصويت.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: "Civil rights protect individuals' freedom from ……………………", promptAr: 'تحمي الحقوق المدنية حرية الأفراد من ……', lines: 2,
              accept: ['violation by governments, social organizations, and private individuals', 'violation by governments, social organizations and private individuals', 'violation'],
              modelAr: 'الانتهاك من قِبل الحكومات والمنظمات الاجتماعية والأفراد.',
              explainAr: 'النص: "protect individuals\' freedom from violation by governments, social organizations, and private individuals".' },
            { n: 13, kind: 'write', prompt: 'The right to vote, the right to a fair trial, and the right to use public facilities are examples of …………', promptAr: 'حق التصويت والحق في محاكمة عادلة والحق في استخدام المرافق العامة أمثلة على ……', lines: 1,
              accept: ['civil rights'], modelAr: 'الحقوق المدنية', explainAr: 'النص: "Examples of civil rights include the right to vote, the right to a fair trial...".' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'We need to ……the roof before it falls down.', promptAr: 'نحتاج إلى ___ السقف قبل أن يسقط.', options: ['jack up', 'pull down', 'shore up', 'check over'], answer: 2,
          explainAr: 'shore up = يدعم/يسند شيئاً كي لا يسقط، والجملة نفسها في كتابك (الوحدة 4). jack up = يرفع (السيارة بالرافعة)، pull down = يهدم، check over = يفحص.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'The evening is a time ……… we can all relax.', promptAr: 'المساء وقتٌ ___ نستطيع جميعاً أن نرتاح فيه.', options: ['when', 'who', 'which', 'where'], answer: 0,
          explainAr: 'بعد اسم يدل على زمن (a time) ويليه جملة كاملة نستخدم when. which تحتاج فعلاً بلا فاعل أو حرف جر، where للمكان، who للعاقل.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'This is our fifth win in the game! We are ……….', promptAr: 'هذا فوزنا الخامس في اللعبة! نحن ___.', options: ['dead in the water', 'backing the wrong horse', 'joining the ranks', 'on a roll'], answer: 3,
          explainAr: 'on a roll = في سلسلة نجاحات متتالية (تعابير الوحدة 2). dead in the water = فاشل بلا أمل، back the wrong horse = يراهن على الخيار الخاطئ، join the ranks of = ينضمّ إلى صفوف.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'A/ An ……… is a heart specialist.', promptAr: '___ هو اختصاصي القلب.', options: ['naturopath', 'cardiologist', 'dentist', 'allergist'], answer: 1,
          explainAr: 'cardio = القلب، فـ cardiologist طبيب القلب. naturopath = المعالج بالطب الطبيعي، dentist = طبيب الأسنان، allergist = طبيب الحساسية (من الوحدة 3).' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'The “ed” in the word “talked” is pronounced as:', promptAr: 'تُلفظ "ed" في كلمة "talked":', options: ['/id/', '/d/', '/it/', '/t/'], answer: 3,
          explainAr: 'talk تنتهي بصوت /k/ المهموس، وبعد الأصوات المهموسة (p, k, s, ʃ, tʃ, f) تُلفظ ed صوت /t/. تُلفظ /id/ فقط بعد t و d.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'After a brief speech, the minister ……… the new statue.', promptAr: 'بعد كلمة قصيرة، ___ الوزير التمثال الجديد.', options: ['disagree', 'disprove', 'unveil', 'unload'], answer: 2,
          explainAr: 'unveil = يزيح الستار عن (يدشّن). المعنى يناسب تمثالاً جديداً. disagree = يختلف، disprove = يدحض، unload = يفرغ الحمولة.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'The monkey escaped from its cage and jumped ………… the lake.', promptAr: 'هرب القرد من قفصه وقفز ___ البحيرة.', options: ['to', 'into', 'onto', 'out of'], answer: 1,
          explainAr: 'حروف جر الحركة (الوحدة 4): into = إلى داخل شيء (الماء/البحيرة). onto = على سطح شيء، out of = خارج من.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'Spot the time when the sound /t/ may disappear.', promptAr: 'حدّد الحالة التي قد يختفي فيها صوت /t/.', options: ['facts', 'fact', "Let's", 'to face'], answer: 0,
          explainAr: 'يختفي /t/ غالباً عندما يقع بين صوتين ساكنين، كما في facts (c-t-s). في fact و to face و Let\'s لا يقع بين ساكنين فيُلفظ.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'When I grow up, I want to be a ………… to study all types of living things.', promptAr: 'عندما أكبر أريد أن أصبح ___ لأدرس كل أنواع الكائنات الحية.', options: ['biology', 'biological', 'biologist', 'biologically'], answer: 2,
          explainAr: 'بعد a نحتاج اسماً لشخص: biologist = عالِم أحياء (اللاحقة ist). biology اسم العلم نفسه، biological صفة، biologically ظرف.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'conditional', prompt: 'If I ……… rich, I would travel around the world.', promptAr: 'لو كنتُ غنياً، لسافرت حول العالم.', lines: 1,
          accept: ['were', 'was'], explainAr: 'الشرطية الثانية: If + ماضٍ بسيط، would + فعل. مع I يُفضَّل were (وتُقبل was).' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'Opportunities don’t happen. You create ……', promptAr: 'الفرص لا تحدث (وحدها). أنت تصنعها.', lines: 1,
          accept: ['them'], explainAr: 'نحتاج ضمير مفعول به جمعاً يعود على Opportunities، وهو them.' },
        { n: 25, kind: 'write', topic: 'tense', prompt: 'As soon as I graduate, I …….. look for a job.', promptAr: 'بمجرد أن أتخرّج سأبحث عن عمل.', lines: 1,
          accept: ['will', 'shall', "'ll"], explainAr: 'بعد As soon as يأتي المضارع البسيط (graduate) للدلالة على المستقبل، والجملة الرئيسية بالمستقبل: will + فعل.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'I {watch the TV news} in the evening.', promptAr: 'أشاهد الأخبار على التلفاز في المساء.', lines: 1,
          accept: ['What do you do in the evening?'], modelAr: 'ماذا تفعل في المساء؟',
          explainAr: 'المسطَّر فعل وما بعده (نشاط)، فنسأل بـ What ... do؟ والفعل مضارع بسيط مع I، فنستخدم do you.' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'I broke my leg {when I played football.}', promptAr: 'كسرتُ ساقي عندما كنت ألعب كرة القدم.', lines: 1,
          accept: ['When did you break your leg?'], modelAr: 'متى كسرتَ ساقك؟',
          explainAr: 'المسطَّر يدل على زمن فنسأل بـ When. الفعل broke ماضٍ فنستخدم did ويعود الفعل إلى أصله break.' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'I borrowed {Zaina’s} car.', promptAr: 'استعرتُ سيارة زينة.', lines: 1,
          accept: ['Whose car did you borrow?'], modelAr: 'سيارةَ مَن استعرت؟',
          explainAr: 'المسطَّر يدل على الملكية (Zaina\'s) فنسأل بـ Whose + الاسم: Whose car ... ؟ والفعل ماضٍ فنستخدم did.' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'grammar', prompt: 'The hairdresser cuts Rana‘s hair about twice a year. (causative verb)', promptAr: 'يقصّ مصفّف الشعر شعر رنا مرتين تقريباً في السنة. (الفعل السببي)', lines: 2,
          accept: ['Rana has her hair cut about twice a year.', 'Rana gets her hair cut about twice a year.'], modelAr: 'تقصّ رنا شعرها (عند المصفّف) مرتين تقريباً في السنة.',
          explainAr: 'السببي: have/get + مفعول + التصريف الثالث. الفعل الأصلي مضارع بسيط (cuts) فنقول has (مع Rana) + her hair + cut.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'They awarded Tom Cruise a big prize. (passive voice)', promptAr: 'منحوا توم كروز جائزة كبيرة. (المبني للمجهول)', lines: 2,
          accept: ['Tom Cruise was awarded a big prize.', 'A big prize was awarded to Tom Cruise.'], modelAr: 'مُنح توم كروز جائزة كبيرة.',
          explainAr: 'المبني للمجهول في الماضي البسيط: was/were + التصريف الثالث. نبدأ بالمفعول (Tom Cruise) ونحذف They.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Your friend is a heavy smoker. (Give Advice)', promptAr: 'صديقك مدخّن شَرِه. (قدّم نصيحة)', lines: 2,
          accept: ['You should stop smoking.', 'You should quit smoking.', "You'd better stop smoking.", 'You had better stop smoking.', 'If I were you, I would stop smoking.', 'If I were you, I would quit smoking.', 'Try to quit smoking.', 'Try to stop smoking.'],
          model: 'You should stop smoking.', modelAr: 'يجب أن تتوقّف عن التدخين.',
          explainAr: 'تعابير النصيحة من الوحدة 1 (Everyday English): You should… / You’d better… / If I were you, I would… / Try to…. بعد stop/quit نستخدم الفعل + ing.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Mona’s glasses were broken. (causative verb)', promptAr: 'كُسرت نظارة منى. (الفعل السببي)', lines: 2,
          accept: ['Mona had her glasses broken.', 'Mona got her glasses broken.'], modelAr: 'كُسرت نظارة منى (حدث لها ذلك).',
          explainAr: 'السببي يُستخدم أيضاً لشيء سيّئ حدث لنا: had + مفعول + التصريف الثالث. were broken ماضٍ فنقول had her glasses broken.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'My uncle ………. (get) sicker suddenly yesterday.', promptAr: 'ساءت صحة عمّي فجأة أمس.', lines: 1,
          accept: ['got'], explainAr: 'yesterday تدل على الماضي البسيط، وتصريف get الثاني got.' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'The floors are clean. Jane …..... (sweep) them.', promptAr: 'الأرضيات نظيفة. لقد كنستها جين.', lines: 1,
          accept: ['has swept', "'s swept"], explainAr: 'نتيجة ظاهرة الآن (The floors are clean) لحدث انتهى: المضارع التام has + swept (التصريف الثالث لـ sweep).' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'The train to the airport ……... (leave) at 7 o’clock.', promptAr: 'يغادر القطار المتجه إلى المطار الساعة السابعة.', lines: 1,
          accept: ['leaves'], explainAr: 'الجداول والمواعيد الثابتة (قطار، طائرة) تُكتب بالمضارع البسيط حتى للمستقبل: leaves.' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'tense', prompt: 'By the end of the year, …………………………..', promptAr: 'بحلول نهاية العام، …', lines: 2,
          accept: ['I will have graduated.', 'I will have finished the project.', 'I will have written the reports.'], model: 'I will have graduated.', modelAr: 'سأكون قد تخرّجت.',
          explainAr: 'By the end of + زمن مستقبلي ← المستقبل التام: will have + التصريف الثالث (حدث سيكتمل قبل ذلك الوقت).' },
        { n: 37, kind: 'write', topic: 'tense', prompt: 'By the time I arrived, ……………………………', promptAr: 'عندما وصلت، …', lines: 2,
          accept: ['the train had left.', 'the bus had left.', 'they were talking.', 'my mother was preparing lunch.'], model: 'the train had left.', modelAr: 'كان القطار قد غادر.',
          explainAr: 'By the time + ماضٍ بسيط ← الماضي التام (had + التصريف الثالث) لحدث سبقه، أو الماضي المستمر لحدث كان جارياً. حلّ الأستاذ يقبل الاثنين.' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: The rich have to reach out to the poor.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['يجب على الأغنياء أن يبذلوا الجهد في مساعدة الفقراء', 'على الأغنياء أن يساعدوا الفقراء', 'يجب على الأغنياء مساعدة الفقراء'], model: 'يجب على الأغنياء أن يبذلوا الجهد في مساعدة الفقراء.',
          explainAr: 'الجملة من كتابك (الوحدة 1، الأفعال المركّبة). have to = يجب، reach out to = يمدّ يد العون لـ، the rich = الأغنياء، the poor = الفقراء.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: شكر المعلم الطلاب الذين نالوا درجات ممتازة الفصل الماضي.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['The teacher thanked the students whose marks were excellent last term.', 'The teacher thanked the students who got excellent marks last term.', 'The teacher thanked the students who got excellent grades last term.'],
          model: 'The teacher thanked the students whose marks were excellent last term.',
          explainAr: 'شكر ← thanked (ماضٍ)، الذين ← who (أو whose marks)، الفصل الماضي ← last term. انتبه لترتيب الجملة الإنجليزية: فاعل + فعل + مفعول.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'A person who has influenced you to be a better person.',
        topicAr: 'شخص أثّر فيك لتصبح إنساناً أفضل.',
        words: 80,
        points: ['Who is the person?', 'What do you admire the most about this person?', 'What specific things have you learned from this person?'],
        model: 'The person who has influenced me the most is my father. He is a doctor, and he has been working in a small hospital for more than twenty years. What I admire the most about him is his patience. He listens to his patients carefully and treats the rich and the poor in the same way. He always reaches out to people who need help. From my father, I have learned to work hard and never give up. I have also learned that success is not only about money; it is about helping others. If I were a doctor one day, I would follow his example.',
        modelAr: 'الشخص الذي أثّر فيّ أكثر من غيره هو أبي. إنه طبيب، ويعمل في مستشفى صغير منذ أكثر من عشرين عاماً. أكثر ما أعجب به فيه صبره؛ فهو يستمع إلى مرضاه باهتمام ويعامل الغني والفقير بالطريقة نفسها، ويمدّ يد العون دائماً لمن يحتاج المساعدة. تعلّمت من أبي أن أعمل بجد وألّا أستسلم أبداً، وتعلّمت أيضاً أن النجاح ليس المال فقط، بل هو مساعدة الآخرين. لو أصبحت طبيباً يوماً ما لاقتديت به.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: من هو الشخص، وما الذي أعجب به فيه، وما الذي تعلّمته منه.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (and, but, also, so, because, From…).',
          'استخدمتُ الأزمنة بشكل صحيح (المضارع التام has influenced / have learned، والمضارع البسيط للصفات).',
          'استخدمتُ كلمات من الكتاب (مثل success, reach out to, never give up).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
