import type { Exam } from '../../../engine/types'

// Practice paper F for Term 1 (Units 1–6), in the exact layout of the real paper (term1-a.ts).
// Passage A: Unit 2 reading "Stop Wishing Start Doing" (its later part, gaps 7–8 filled with the book's phrases B and C).
// Passage B: Unit 5 reading "Civil Rights" (paragraphs 2–4).
// Sections III–IX lean on Review 1 and on points the other papers are less likely to test.
export const term1F: Exam = {
  id: 't1-f',
  term: 1,
  title: 'Term 1 — Test (F)',
  titleAr: 'الفصل الأول — النموذج (F)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً للامتحان الحقيقي، مبنيّ فقط على الوحدات من 1 إلى 6 من كتابك.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'Actions are louder than words. When you take action, you trigger all kinds of things that will inevitably carry you to success. Every step taken by you in the direction of your dreams and goals brings you closer at jet speed. Nothing happens until you take action. To be successful, you have to do what successful people do. All highly successful people are highly action-oriented people. It is said: “Success is 10% inspiration and 90% perspiration.”',
          'The golden rule to achieve success is to keep learning. These are three dangerous words: “I know that.” If you have read or heard about something, you do not know. If you are not rich and successful the way you want, then you do not know. Become a ‘learn it all’ rather than ‘know it all’.',
          'Finally, it is significant to know that things do not just happen to your benefit by themselves; you must work hard to make them happen. Life is like a game in which playing to win matters more than playing not to lose.',
        ],
        paragraphsAr: [
          'الأفعال أبلغ من الأقوال. عندما تبادر إلى العمل، فإنك تُطلق كل أنواع الأشياء التي ستحملك حتماً إلى النجاح. كل خطوة تخطوها في اتجاه أحلامك وأهدافك تقرّبك منها بسرعة الطائرة النفّاثة. لا يحدث شيء حتى تبادر إلى العمل. لكي تكون ناجحاً، عليك أن تفعل ما يفعله الناجحون. فكل الناجحين جداً أشخاصٌ يهتمّون بالعمل والتنفيذ كثيراً. يُقال: «النجاح 10% إلهام و90% عَرَق (جهد وتعب)».',
          'القاعدة الذهبية لتحقيق النجاح هي أن تستمرّ في التعلّم. هذه ثلاث كلمات خطيرة: «أنا أعرف ذلك». إذا كنت قد قرأت أو سمعت عن شيء ما، فأنت لا تعرفه (حقاً). وإذا لم تكن غنياً وناجحاً بالطريقة التي تريدها، فأنت إذن لا تعرف. كن شخصاً «يتعلّم كل شيء» بدلاً من شخص «يدّعي أنه يعرف كل شيء».',
          'وأخيراً، من المهم أن تعرف أن الأمور لا تحدث لمصلحتك من تلقاء نفسها؛ بل يجب أن تعمل بجدّ لتجعلها تحدث. الحياة مثل لعبة يكون فيها اللعب من أجل الفوز أهمّ من اللعب من أجل عدم الخسارة.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'What happens when you take action?', promptAr: 'ماذا يحدث عندما تبادر إلى العمل؟', lines: 3,
              accept: ['When you take action, you trigger all kinds of things that will inevitably carry you to success.', 'You trigger all kinds of things that will inevitably carry you to success.', 'You trigger all kinds of things that will carry you to success.', 'All kinds of things that will inevitably carry you to success are triggered.'],
              modelAr: 'عندما تبادر إلى العمل تُطلق كل أنواع الأشياء التي ستحملك حتماً إلى النجاح.',
              explainAr: 'الجواب في الجملة الثانية من النص: "When you take action, you trigger all kinds of things that will inevitably carry you to success". انقلها وابدأ بـ You لأن السؤال عن "you".' },
            { n: 2, kind: 'write', prompt: 'What is the golden rule to achieve success?', promptAr: 'ما القاعدة الذهبية لتحقيق النجاح؟', lines: 2,
              accept: ['The golden rule to achieve success is to keep learning.', 'It is to keep learning.', 'To keep learning.', 'Keep learning.'],
              modelAr: 'القاعدة الذهبية لتحقيق النجاح هي الاستمرار في التعلّم.',
              explainAr: 'أول جملة في الفقرة الثانية: "The golden rule to achieve success is to keep learning". keep + فعل مع ing = يستمرّ في.' },
            { n: 3, kind: 'write', prompt: 'What are the three dangerous words mentioned in the text?', promptAr: 'ما الكلمات الثلاث الخطيرة المذكورة في النص؟', lines: 2,
              accept: ['The three dangerous words are "I know that."', 'They are "I know that."', 'I know that.', '"I know that."'],
              modelAr: 'الكلمات الثلاث الخطيرة هي: «أنا أعرف ذلك».',
              explainAr: 'النص: "These are three dangerous words: “I know that.”". الكاتب يرى أن من يظن أنه يعرف كل شيء يتوقّف عن التعلّم.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'Hard work ……..', promptAr: 'العمل الشاق (الجهد والتعب)', lines: 1, topic: 'vocab',
              accept: ['perspiration'], modelAr: 'عَرَق / جهد وتعب',
              explainAr: 'في النص "Success is 10% inspiration and 90% perspiration". perspiration معناها الأصلي "العرق"، والمقصود هنا الجهد والعمل الشاق، وهو معناها في تمرين كتابك (الوحدة 2).' },
            { n: 5, kind: 'write', prompt: 'To initiate or activate something ……..', promptAr: 'أن تبدأ شيئاً أو تُطلقه وتشغّله', lines: 1, topic: 'vocab',
              accept: ['trigger'], modelAr: 'يُطلِق / يُحفِّز',
              explainAr: 'في النص "you trigger all kinds of things". trigger فعل يعني يبدأ شيئاً أو يُطلقه، كما في تمرين المفردات في الوحدة 2.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'Success is 90% inspiration and 10% perspiration.', promptAr: 'النجاح 90% إلهام و10% جهد.', lines: 2,
              accept: ['Success is 10% inspiration and 90% perspiration.', 'Success is 10 percent inspiration and 90 percent perspiration.', 'Success is 90% perspiration and 10% inspiration.'],
              modelAr: 'النجاح 10% إلهام و90% جهد.',
              explainAr: 'النص يقول العكس: "Success is 10% inspiration and 90% perspiration" — أي أن الجهد هو الجزء الأكبر من النجاح.' },
            { n: 7, kind: 'write', prompt: 'Things happen to your benefit by themselves.', promptAr: 'الأمور تحدث لمصلحتك من تلقاء نفسها.', lines: 2,
              accept: ['Things do not just happen to your benefit by themselves; you must work hard to make them happen.', 'Things do not happen to your benefit by themselves.', "Things don't happen to your benefit by themselves; you must work hard to make them happen.", 'You must work hard to make things happen.'],
              modelAr: 'الأمور لا تحدث لمصلحتك من تلقاء نفسها؛ يجب أن تعمل بجدّ لتجعلها تحدث.',
              explainAr: 'الفقرة الأخيرة: "things do not just happen to your benefit by themselves; you must work hard to make them happen". صحّح الجملة بالنفي do not.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          "Civil and political rights are a class of rights that protect individuals' freedom from violation by governments, social organisations, and private individuals. They ensure one's right to participate in the civil and political life of society and the state without discrimination or repression. Unlike other rights concepts, such as human rights or natural rights, in which people acquire rights inherently from God, civil rights must be given and guaranteed by the power of the state.",
          'Examples of civil rights include the right to vote, the right to a fair trial, the right to government services, the right to a public education, and the right to use public facilities.',
          'Civil rights are an essential component of democracy; when individuals are prevented from participating in political society, their civil rights are being denied. In contrast to civil liberties, which are freedoms that are secured by placing restraints on government, civil rights are secured by positive government action, often in the form of legislation. Civil rights laws attempt to guarantee full and equal citizenship for people who have traditionally been discriminated against on the basis of some characteristics.',
        ],
        paragraphsAr: [
          'الحقوق المدنية والسياسية فئة من الحقوق تحمي حرية الأفراد من الانتهاك من قِبل الحكومات والمنظمات الاجتماعية والأفراد. وهي تضمن حق المرء في المشاركة في الحياة المدنية والسياسية للمجتمع والدولة دون تمييز أو قمع. وعلى خلاف مفاهيم الحقوق الأخرى، كحقوق الإنسان أو الحقوق الطبيعية التي يكتسبها الناس بالفطرة من الله، فإن الحقوق المدنية يجب أن تمنحها سلطة الدولة وتضمنها.',
          'ومن أمثلة الحقوق المدنية: حق التصويت، والحق في محاكمة عادلة، والحق في الخدمات الحكومية، والحق في التعليم العام، والحق في استخدام المرافق العامة.',
          'الحقوق المدنية عنصر أساسي من عناصر الديمقراطية؛ فعندما يُمنع الأفراد من المشاركة في المجتمع السياسي، تكون حقوقهم المدنية مسلوبة. وعلى عكس الحريات المدنية، وهي حريات تُصان بوضع قيود على الحكومة، فإن الحقوق المدنية تُصان بعمل حكومي إيجابي، غالباً على شكل تشريعات. وتسعى قوانين الحقوق المدنية إلى ضمان مواطَنة كاملة ومتساوية للناس الذين تعرّضوا تقليدياً للتمييز بسبب بعض صفاتهم.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'Civil rights laws attempt to guarantee full and equal citizenship for people who ……..', promptAr: 'تسعى قوانين الحقوق المدنية إلى ضمان مواطَنة كاملة ومتساوية للناس الذين ……..', options: ['have always been rich', 'acquire rights inherently', 'work for the government', 'have traditionally been discriminated against'], answer: 3,
              explainAr: 'آخر جملة في النص: "for people who have traditionally been discriminated against on the basis of some characteristics" — أي الذين تعرّضوا للتمييز. أما "acquire rights inherently" فهي صفة حقوق الإنسان والحقوق الطبيعية.' },
            { n: 9, kind: 'mcq', prompt: 'Civil liberties are freedoms that are secured by ……..', promptAr: 'الحريات المدنية حرياتٌ تُصان بواسطة ……..', options: ['positive government action', 'placing restraints on government', 'social organisations', 'private individuals'], answer: 1,
              explainAr: 'النص يقارن: "civil liberties, which are freedoms that are secured by placing restraints on government" أي بوضع قيود على الحكومة. انتبه: "positive government action" تخصّ الحقوق المدنية لا الحريات المدنية.' },
            { n: 10, kind: 'mcq', prompt: "Civil and political rights ensure one's right to participate in the life of society and the state ……..", promptAr: 'تضمن الحقوق المدنية والسياسية حق المرء في المشاركة في حياة المجتمع والدولة ……..', options: ['only if he is rich', 'only with the help of God', 'without discrimination or repression', 'by placing restraints on government'], answer: 2,
              explainAr: 'الجملة الثانية في النص: "They ensure one\'s right to participate in the civil and political life of society and the state without discrimination or repression" — أي دون تمييز أو قمع.' },
            { n: 11, kind: 'mcq', prompt: 'To give an assurance that something will be done right is to ……..', promptAr: 'أن تعطي تأكيداً بأن شيئاً ما سيُنفَّذ بشكل صحيح يعني أن ……..', options: ['guarantee', 'deny', 'vote', 'participate'], answer: 0, topic: 'vocab',
              explainAr: 'guarantee = يضمن، وهي في النص "must be given and guaranteed by the power of the state" ومعناها في تمرين مفردات الوحدة 5. deny = يُنكر/يحرم، vote = يصوّت، participate = يشارك.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'Civil rights are an essential component of ……………………', promptAr: 'الحقوق المدنية عنصر أساسي من عناصر ……', lines: 1,
              accept: ['democracy'], modelAr: 'الديمقراطية',
              explainAr: 'بداية الفقرة الأخيرة: "Civil rights are an essential component of democracy".' },
            { n: 13, kind: 'write', prompt: 'When individuals are prevented from participating in political society, ……………………', promptAr: 'عندما يُمنع الأفراد من المشاركة في المجتمع السياسي، ……', lines: 2,
              accept: ['their civil rights are being denied', 'their civil rights are denied'], modelAr: 'تكون حقوقهم المدنية مسلوبة.',
              explainAr: 'النص: "when individuals are prevented from participating in political society, their civil rights are being denied". انقل الجملة كما هي.' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'This harsh environment is going to ……… this concrete over time.', promptAr: 'هذه البيئة القاسية ستـ___ هذا الإسمنت مع مرور الوقت.', options: ['eat away at', 'fence off', 'jack up', 'check over'], answer: 0,
          explainAr: 'eat away at = يَحُتّ/يُآكل شيئاً ببطء (erode)، والجملة نفسها في كتابك (الوحدة 4). fence off = يحيط بسياج ليمنع الدخول، jack up = يرفع بالرافعة، check over = يفحص.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'A plumber is a person ……… job is to mend central heating, taps, etc.', promptAr: 'السبّاك شخصٌ ___ عمله إصلاح التدفئة المركزية والصنابير وغيرها.', options: ['who', 'whose', 'which', 'where'], answer: 1,
          explainAr: 'بعد الفراغ اسم (job) يملكه الشخص، فنستخدم whose للملكية (الوحدة 5). who تحتاج بعدها فعلاً مباشرة، which لغير العاقل، where للمكان.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'Our lawyer is very good and he does everything ……….', promptAr: 'محامينا جيد جداً ويفعل كل شيء ___.', options: ['an act of God', 'beat around the bush', 'by the book', 'break the law'], answer: 2,
          explainAr: 'by the book = تماماً كما تنصّ القواعد (تعابير القانون في الوحدة 5). an act of God = كارثة طبيعية لا يد للإنسان فيها، beat around the bush = يراوغ ولا يدخل في الموضوع، break the law = يخالف القانون.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'A piece of equipment consisting of a wheel over which a rope or chain is pulled to lift heavy things is a/an ……….', promptAr: 'قطعة معدّات تتكوّن من عجلة يُسحب فوقها حبل أو سلسلة لرفع الأشياء الثقيلة هي ___.', options: ['lever', 'cotton gin', 'windmill', 'pulley'], answer: 3,
          explainAr: 'pulley = البكرة (عجلة وحبل لرفع الأثقال)، من مفردات نص الهندسة في الوحدة 4. lever = الرافعة (العتلة) آلة بسيطة بلا عجلة وحبل، cotton gin = محلج القطن، windmill = طاحونة هوائية.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'When the word “record” is stressed on the first syllable (REcord), it is ……….', promptAr: 'عندما يقع النبر على المقطع الأول في كلمة “record” (REcord) فإنها تكون ___.', options: ['a verb', 'a noun', 'an adverb', 'a preposition'], answer: 1,
          explainAr: 'قاعدة الوحدة 6: في الكلمات ذات المقطعين، النبر على المقطع الأول يجعلها اسماً أو صفة (REcord = تسجيل/سجلّ)، والنبر على المقطع الثاني يجعلها فعلاً (reCORD = يسجّل).' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'It is very important not to ……… our children with unreal expectations.', promptAr: 'من المهم جداً ألّا ___ أطفالنا بتوقّعات غير واقعية.', options: ['burden', 'sway', 'trigger', 'guarantee'], answer: 0,
          explainAr: 'burden = يُثقل/يحمّل عبئاً (load)، والجملة من نص الوحدة 1. sway = يؤثّر في رأي أحد، trigger = يُطلق/يبدأ، guarantee = يضمن. المعنى: لا نحمّل أطفالنا توقّعات غير واقعية.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'He got into his car and drove ……….', promptAr: 'ركب سيارته و___.', options: ['from', 'onto', 'off', 'into'], answer: 2,
          explainAr: 'drive off = ينطلق بالسيارة مبتعداً، وهي من حروف جر الحركة (الوحدة 4) ومن المراجعة الأولى. from و onto و into تحتاج بعدها اسماً (مكاناً)، والجملة تنتهي بعد الفراغ.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'The final sound is voiced in the word ……….', promptAr: 'الصوت الأخير مجهور في كلمة ___.', options: ['sick', 'laugh', 'path', 'judge'], answer: 3,
          explainAr: 'الصوت المجهور تهتزّ معه الأوتار الصوتية (الوحدة 5). judge تنتهي بصوت /dʒ/ المجهور. أما sick فتنتهي بـ /k/ و laugh بـ /f/ و path بـ /θ/، وكلها أصوات مهموسة.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'A successful person is able to differentiate between fantasy and ……….', promptAr: 'الشخص الناجح قادر على التمييز بين الخيال و___.', options: ['real', 'reality', 'really', 'realise'], answer: 1,
          explainAr: 'بعد and نحتاج اسماً يقابل الاسم fantasy: reality = الواقع (اللاحقة ity تصنع اسماً). real صفة، really ظرف، realise فعل. الجملة من المراجعة الأولى.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'tense', prompt: 'It happened at four in the afternoon when she ……… watching news on TV.', promptAr: 'حدث ذلك في الساعة الرابعة بعد الظهر عندما ___ تشاهد الأخبار على التلفاز.', lines: 1,
          accept: ['was'], explainAr: 'الماضي المستمر (was + فعل مع ing) يصف حدثاً كان جارياً (خلفية) عندما وقع حدث آخر. الفاعل she مفرد فنستخدم was.' },
        { n: 24, kind: 'write', topic: 'tense', prompt: 'The two companies are ……… to provide very different experiences.', promptAr: 'الشركتان ___ أن تقدّما تجارب مختلفة جداً.', lines: 1,
          accept: ['going'], explainAr: 'صيغة المستقبل be going to + فعل (الوحدة 6). بعد are والفراغ يأتي to provide، فالكلمة الناقصة going.' },
        { n: 25, kind: 'write', topic: 'grammar', prompt: 'It’s hoped he will ……… found in a few days.', promptAr: 'يُؤمَل أن ___ العثور عليه خلال أيام قليلة.', lines: 1,
          accept: ['be'], explainAr: 'المبني للمجهول في المستقبل: will be + التصريف الثالث (found). الجملة من قصة السرقة في الوحدة 3.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'There were {51} founding members in 1945.', promptAr: 'كان هناك 51 عضواً مؤسِّساً عام 1945.', lines: 1,
          accept: ['How many founding members were there in 1945?', 'How many founding members were there?'], modelAr: 'كم عضواً مؤسِّساً كان هناك عام 1945؟',
          explainAr: 'المسطَّر عدد لاسم معدود جمع (members) فنسأل بـ How many + الاسم. وفي There were نقلب الترتيب في السؤال: were there.' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'I’ve been using a computer {for at least three years}.', promptAr: 'أستخدم الحاسوب منذ ثلاث سنوات على الأقل.', lines: 1,
          accept: ['How long have you been using a computer?', 'How long have you used a computer?'], modelAr: 'منذ متى وأنت تستخدم الحاسوب؟',
          explainAr: 'المسطَّر مدة (for + زمن) فنسأل بـ How long. الفعل مضارع تام مستمر (I have been using) فيصبح السؤال: have you been using.' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'Our electricity was cut off {because we had forgotten to pay the bill}.', promptAr: 'قُطعت الكهرباء عنّا لأننا نسينا دفع الفاتورة.', lines: 1,
          accept: ['Why was your electricity cut off?', 'Why was the electricity cut off?'], modelAr: 'لماذا قُطعت الكهرباء عنكم؟',
          explainAr: 'المسطَّر يبدأ بـ because (سبب) فنسأل بـ Why. الجملة مبنية للمجهول (was cut off) فنقدّم was على الفاعل، ونغيّر our إلى your.' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'grammar', prompt: 'The organizers will exhibit the paintings till the end of the month. (passive voice)', promptAr: 'سيعرض المنظّمون اللوحات حتى نهاية الشهر. (المبني للمجهول)', lines: 2,
          accept: ['The paintings will be exhibited till the end of the month.', 'The paintings will be exhibited by the organizers till the end of the month.', 'The paintings will be exhibited by the organisers till the end of the month.', 'The paintings will be exhibited until the end of the month.'],
          modelAr: 'ستُعرض اللوحات حتى نهاية الشهر.',
          explainAr: 'المبني للمجهول في المستقبل: will be + التصريف الثالث. نبدأ بالمفعول (The paintings)، ثم will be exhibited، ويمكن حذف الفاعل أو ذكره بعد by.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'Doctors amputated the patient’s leg after the accident. (causative verb)', promptAr: 'بتر الأطباء ساق المريض بعد الحادث. (الفعل السببي)', lines: 2,
          accept: ['The patient had his leg amputated after the accident.', 'The patient got his leg amputated after the accident.', 'The patient had his leg amputated by doctors after the accident.', 'The patient had his leg amputated by the doctors after the accident.'],
          modelAr: 'بُترت ساق المريض (على يد الأطباء) بعد الحادث.',
          explainAr: 'السببي: have/get + مفعول + التصريف الثالث. الفعل amputated ماضٍ فنستخدم had، ونبدأ بصاحب الساق: The patient had his leg amputated.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'The man visited me last night. He worked in a printing company. (Join using a relative pronoun)', promptAr: 'زارني الرجل الليلة الماضية. كان يعمل في شركة طباعة. (اربط باستخدام ضمير وصل)', lines: 2,
          accept: ['The man who worked in a printing company visited me last night.', 'The man that worked in a printing company visited me last night.'],
          modelAr: 'الرجل الذي كان يعمل في شركة طباعة زارني الليلة الماضية.',
          explainAr: 'He يعود على شخص (The man) فنستبدله بـ who (أو that)، ونضع جملة الوصل مباشرة بعد The man، ثم نكمل: visited me last night. الجملة من قواعد الوحدة 5.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Your little brother has got low marks in the exam. (Express sympathy)', promptAr: 'حصل أخوك الصغير على علامات منخفضة في الامتحان. (عبّر عن التعاطف)', lines: 2,
          accept: ["I'm sorry about what happened.", "You mustn't let this depress you.", "I'm sure this won't happen again.", "I have no doubt that you'll do much better next time.", 'I have no doubt that you will do better next time.', "I'm sorry about what happened. I have no doubt that you'll do much better next time."],
          model: "I'm sorry about what happened. I have no doubt that you'll do much better next time.", modelAr: 'أنا آسف لما حدث. لا شكّ عندي أنك ستؤدي أفضل بكثير في المرة القادمة.',
          explainAr: 'تعابير التعاطف من الوحدة 2 (Everyday English): I’m sorry about what happened / You mustn’t let this depress you / I’m sure this won’t happen again / I have no doubt that you’ll do much better next time. لا تستخدم Congratulations هنا فهي للتهنئة.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'They ………. (run) for three hours when the storm suddenly broke.', promptAr: 'كانوا يركضون منذ ثلاث ساعات عندما هبّت العاصفة فجأة.', lines: 1,
          accept: ['had been running'], explainAr: 'حدث استمرّ مدة (for three hours) قبل حدث آخر في الماضي (broke): الماضي التام المستمر had been + فعل مع ing.' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'She ………. (work) on that manuscript for two years now.', promptAr: 'إنها تعمل على تلك المخطوطة منذ سنتين حتى الآن.', lines: 1,
          accept: ['has been working', "'s been working"], explainAr: 'for two years now = حدث بدأ في الماضي وما زال مستمراً الآن: المضارع التام المستمر has been working (مع she نستخدم has).' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'Camera footage shows that illegal goods ………. (smuggle) into the warehouse last week.', promptAr: 'تُظهر تسجيلات الكاميرا أن بضائع غير قانونية هُرّبت إلى المستودع الأسبوع الماضي.', lines: 1,
          accept: ['were smuggled'], explainAr: 'البضائع لا تهرّب نفسها بل هُرّبت، فالمطلوب مبني للمجهول، و last week تدل على الماضي البسيط: were (لأن goods جمع) + smuggled.' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'conditional', prompt: 'Unless you work hard, …………………………..', promptAr: 'ما لم تعمل بجدّ، …', lines: 2,
          accept: ['you will not succeed.', "you won't succeed.", 'you will fail.', 'you will not achieve your goals.', "you won't achieve your goals.", 'you will not pass the exam.', "you won't pass the exam.", "you won't be successful."],
          model: "you won't achieve your goals.", modelAr: 'لن تحقّق أهدافك.',
          explainAr: 'Unless = إذا لم (if not). بعدها مضارع بسيط (work)، والجملة الرئيسية بالمستقبل البسيط: will/won’t + فعل، مثل الشرطية الأولى.' },
        { n: 37, kind: 'write', topic: 'conditional', prompt: 'If I had the chance to study in another country, ……………………………', promptAr: 'لو أُتيحت لي الفرصة للدراسة في بلد آخر، …', lines: 2,
          accept: ['I would choose England.', 'I would study medicine.', 'I would learn a new language.', 'I would study engineering.', "I'd choose England.", 'I would go to England.'],
          model: 'I would choose England.', modelAr: 'لاخترتُ إنكلترا.',
          explainAr: 'الشرطية الثانية لموقف متخيَّل: If + ماضٍ بسيط (had)، والجواب would + فعل في المصدر. السؤال نفسه في الوحدة 1: "which country would you choose?".' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: Life is a matter of choices, and every choice you make makes you.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['الحياة مسألة خيارات، وكل خيار تتخذه يصنعك', 'الحياة مسألة اختيارات، وكل اختيار تقوم به يصنعك', 'الحياة عبارة عن خيارات، وكل خيار تختاره يصنعك'],
          model: 'الحياة مسألة خيارات، وكل خيار تتخذه يصنعك.',
          explainAr: 'الجملة من كتابك (الوحدة 1، قول جون ماكسويل). a matter of = مسألة، choices = خيارات، every choice you make = كل خيار تتخذه، makes you = يصنعك (يشكّل شخصيتك).' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: بُني أول محرّك بخاري عام 1698.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['The first steam engine was built in 1698.', 'In 1698, the first steam engine was built.'],
          model: 'The first steam engine was built in 1698.',
          explainAr: 'بُني فعل مبني للمجهول في الماضي: was built. أول محرّك بخاري ← the first steam engine (الصفة قبل الاسم)، عام 1698 ← in 1698. الجملة من نص الهندسة في الوحدة 4.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'A personal experience in which you failed at first, but then you could achieve your target.',
        topicAr: 'تجربة شخصية فشلتَ فيها في البداية، ثم استطعت أن تحقّق هدفك.',
        words: 80,
        points: ['What was the problem?', 'What steps did you follow, and who helped you?', 'What advice would you give to people of your age?'],
        model: 'Last year, I failed my first physics test, and I felt really disappointed. The problem was that I had not been studying regularly, and I did not understand the lessons well. Instead of giving up, I decided to take action. First, I set a smart goal which was achievable: to study physics for one hour every day. Then I asked my older brother, who is an engineer, for help, and he explained the difficult lessons to me. I carried on working hard for three months, and my marks got better and better. At the end of the term, I aced the test. My advice to people of my age is this: failure can be a teacher, so keep learning and never give up.',
        modelAr: 'في العام الماضي رسبتُ في أول اختبار فيزياء، وشعرت بخيبة أمل كبيرة. كانت المشكلة أنني لم أكن أدرس بانتظام، ولم أكن أفهم الدروس جيداً. وبدلاً من أن أستسلم، قرّرت أن أبادر إلى العمل. أولاً، وضعت هدفاً ذكياً يمكن تحقيقه: أن أدرس الفيزياء ساعة كل يوم. ثم طلبت المساعدة من أخي الأكبر، وهو مهندس، فشرح لي الدروس الصعبة. واصلت العمل بجدّ ثلاثة أشهر، وتحسّنت علاماتي شيئاً فشيئاً. وفي نهاية الفصل نجحت في الاختبار بتفوّق. نصيحتي لمن هم في مثل سنّي: الفشل يمكن أن يكون معلّماً، فاستمرّوا في التعلّم ولا تستسلموا أبداً.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: المشكلة، والخطوات التي اتبعتها ومن ساعدني، ونصيحتي لمن هم في مثل سنّي.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أزمنة الماضي بشكل صحيح (الماضي البسيط failed/decided، والماضي التام المستمر had not been studying).',
          'استخدمتُ أدوات ترتيب وربط (First, Then, Instead of, At the end of, so, and).',
          'استخدمتُ كلمات وتعابير من الوحدة 2 (take action, give up, carry on, ace a test, keep learning).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
