import type { Exam } from '../../../engine/types'

// A practice final Baccalaureate paper in the exact layout of the real paper (term1-a.ts), covering the whole book (Units 1–12).
// Passage A: Unit 12 reading "E-government" (Digital Literacy), second part (page 117).
// Passage B: Unit 8 reading "Human Body", second part (pages 75–76).
export const term2E: Exam = {
  id: 't2-e',
  term: 2,
  title: 'Baccalaureate — Final Test (E)',
  titleAr: 'نموذج البكالوريا النهائي (E)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان البكالوريا الحقيقي، يغطي الكتاب كاملاً (الوحدات 1–12).',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'E-government services have three classifications. Firstly, Government-to-Government (G2G) involves sharing data and conducting electronic exchanges between governmental sectors, as well as exchanges between the national, regional, and local levels. Secondly, Government-to-Business (G2B) includes business-specific transactions (e.g. payments, sale and purchase of goods and services) as well as delivery online of business-focused services. Finally, Government-to-Consumer (G2C) comprises initiatives designed to simplify people’s interaction with the government as consumers of public services and contribute to the consultation and decision-making process.',
          'In recent years, Syria has adopted this new technology to facilitate public services for its citizens. This requires links to governmental organisations that supply services and information such as governmental documents, fees, etc. electronically. Various ministries are working on completing the data-entry process. This will pave the way to have more e-services. Many observers, experts and politicians expect that Syria will witness a great progress in all fields in the coming years.',
        ],
        paragraphsAr: [
          'لخدمات الحكومة الإلكترونية ثلاثة تصنيفات. أولاً، خدمات "من الحكومة إلى الحكومة" (G2G) وتشمل تبادل البيانات وإجراء المبادلات الإلكترونية بين القطاعات الحكومية، إضافةً إلى المبادلات بين المستويات الوطنية والإقليمية والمحلية. ثانياً، خدمات "من الحكومة إلى قطاع الأعمال" (G2B) وتشمل المعاملات الخاصة بالأعمال (مثل المدفوعات وبيع السلع والخدمات وشرائها) إضافةً إلى تقديم الخدمات الموجّهة لقطاع الأعمال عبر الإنترنت. وأخيراً، خدمات "من الحكومة إلى المستهلك" (G2C) وتضمّ مبادرات مصمَّمة لتبسيط تعامل الناس مع الحكومة بوصفهم مستهلكين للخدمات العامة، وللمساهمة في عملية التشاور واتخاذ القرار.',
          'في السنوات الأخيرة، تبنّت سوريا هذه التقنية الجديدة لتسهيل الخدمات العامة لمواطنيها. ويتطلّب ذلك روابط بالمؤسسات الحكومية التي تقدّم الخدمات والمعلومات، كالوثائق الحكومية والرسوم وغيرها، إلكترونياً. وتعمل وزارات مختلفة على استكمال عملية إدخال البيانات، وهذا سيمهّد الطريق لمزيد من الخدمات الإلكترونية. ويتوقّع كثير من المراقبين والخبراء والسياسيين أن تشهد سوريا تقدّماً كبيراً في جميع المجالات في السنوات القادمة.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'What does Government-to-Government (G2G) involve?', promptAr: 'ماذا تشمل خدمات "من الحكومة إلى الحكومة" (G2G)؟', lines: 3,
              accept: ['It involves sharing data and conducting electronic exchanges between governmental sectors, as well as exchanges between the national, regional, and local levels.', 'Government-to-Government involves sharing data and conducting electronic exchanges between governmental sectors, as well as exchanges between the national, regional and local levels.', 'It involves sharing data and conducting electronic exchanges between governmental sectors.', 'Sharing data and conducting electronic exchanges between governmental sectors.'],
              modelAr: 'تشمل تبادل البيانات وإجراء المبادلات الإلكترونية بين القطاعات الحكومية، وبين المستويات الوطنية والإقليمية والمحلية.',
              explainAr: 'الجواب في الجملة الثانية: "Firstly, Government-to-Government (G2G) involves sharing data and conducting electronic exchanges between governmental sectors...". ابدأ جوابك بـ It involves ثم انقل المعلومة.' },
            { n: 2, kind: 'write', prompt: 'What does Government-to-Consumer (G2C) comprise?', promptAr: 'ماذا تضمّ خدمات "من الحكومة إلى المستهلك" (G2C)؟', lines: 3,
              accept: ['It comprises initiatives designed to simplify people’s interaction with the government as consumers of public services and contribute to the consultation and decision-making process.', 'It comprises initiatives designed to simplify people’s interaction with the government as consumers of public services.', 'Initiatives designed to simplify people’s interaction with the government as consumers of public services.', 'It comprises initiatives designed to simplify people’s interaction with the government.'],
              modelAr: 'تضمّ مبادرات مصمَّمة لتبسيط تعامل الناس مع الحكومة بوصفهم مستهلكين للخدمات العامة، وللمساهمة في التشاور واتخاذ القرار.',
              explainAr: 'آخر جملة في الفقرة الأولى: "Finally, Government-to-Consumer (G2C) comprises initiatives designed to simplify people’s interaction with the government...". comprise = يضمّ/يتألّف من.' },
            { n: 3, kind: 'write', prompt: 'What will pave the way to have more e-services in Syria?', promptAr: 'ما الذي سيمهّد الطريق لمزيد من الخدمات الإلكترونية في سوريا؟', lines: 2,
              accept: ['Completing the data-entry process will pave the way to have more e-services.', 'Completing the data-entry process.', 'The work of various ministries on completing the data-entry process.', 'Various ministries are working on completing the data-entry process, and this will pave the way to have more e-services.'],
              modelAr: 'استكمال عملية إدخال البيانات (الذي تعمل عليه وزارات مختلفة).',
              explainAr: 'النص: "Various ministries are working on completing the data-entry process. This will pave the way to have more e-services." الضمير This يعود على استكمال عملية إدخال البيانات.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'The act of buying something ……..', promptAr: 'فعل شراء شيء ما', lines: 1, topic: 'vocab',
              accept: ['purchase'], modelAr: 'الشراء', explainAr: 'في النص "sale and purchase of goods and services" — بيع السلع وشراؤها. purchase = الشراء، وهي من كلمات الوحدة 12.' },
            { n: 5, kind: 'write', prompt: 'Discussion with a group of people before making a decision ……..', promptAr: 'نقاش مع مجموعة من الناس قبل اتخاذ قرار', lines: 1, topic: 'vocab',
              accept: ['consultation'], modelAr: 'التشاور', explainAr: 'في النص "contribute to the consultation and decision-making process". consultation = التشاور (من الفعل consult).' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'Payments and the sale and purchase of goods are included in Government-to-Consumer (G2C) services.', promptAr: 'المدفوعات وبيع السلع وشراؤها من ضمن خدمات "من الحكومة إلى المستهلك" (G2C).', lines: 2,
              accept: ['Payments and the sale and purchase of goods are included in Government-to-Business (G2B) services.', 'Payments and the sale and purchase of goods are included in Government-to-Business services.', 'Payments and the sale and purchase of goods are included in G2B services.'],
              modelAr: 'المدفوعات وبيع السلع وشراؤها من ضمن خدمات "من الحكومة إلى قطاع الأعمال" (G2B).',
              explainAr: 'النص: "Government-to-Business (G2B) includes business-specific transactions (e.g. payments, sale and purchase of goods and services)". فالخطأ هو Government-to-Consumer، والصواب Government-to-Business.' },
            { n: 7, kind: 'write', prompt: 'Syria has not adopted e-government yet.', promptAr: 'لم تتبنَّ سوريا الحكومة الإلكترونية بعد.', lines: 2,
              accept: ['In recent years, Syria has adopted e-government to facilitate public services for its citizens.', 'Syria has adopted e-government.', 'In recent years, Syria has adopted this new technology to facilitate public services for its citizens.', 'Syria has adopted e-government to facilitate public services for its citizens.'],
              modelAr: 'في السنوات الأخيرة تبنّت سوريا الحكومة الإلكترونية لتسهيل الخدمات العامة لمواطنيها.',
              explainAr: 'النص: "In recent years, Syria has adopted this new technology to facilitate public services for its citizens." فنحذف not ... yet ونكتب الجملة مثبتة.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'The body’s strong internal framework (skeleton) is made of 206 bones, connected at the joint, such as in legs. These joints help us to move. The backbone supports the head and limbs and protects the spinal cord. Between the skeleton and the skin, there are about 500 muscles. Nerves spread from the brain to all parts of the body, carrying signals in the form of tiny electrical impulses. The sense organs namely eyes, nose, ears, tongue and skin pass the messages to the brain through nerves, which take the instructions from the brain to the muscles. The brain automatically controls breathing, heartbeat, digestion, etc.',
          'The body keeps on growing. The peak of physical growth is reached at about 18 to 25 years of age. When we grow old, the skin becomes wrinkled and less elastic, the joints become inflexible, muscles loose, and bones become weak.',
          'Here are some tips for aging gracefully: be kind to your skin which is your largest organ. You should also keep your salt intake to a minimum to keep your blood pressure down. Also, getting enough sleep has been proved to lower the risk of heart disease and stroke.',
        ],
        paragraphsAr: [
          'يتكوّن الهيكل الداخلي القوي للجسم (الهيكل العظمي) من 206 عظمات متصلة عند المفاصل، كما في الساقين. وتساعدنا هذه المفاصل على الحركة. ويدعم العمود الفقري الرأس والأطراف ويحمي الحبل الشوكي. وبين الهيكل العظمي والجلد توجد نحو 500 عضلة. وتمتدّ الأعصاب من الدماغ إلى جميع أجزاء الجسم حاملةً إشارات على شكل نبضات كهربائية دقيقة. وتنقل أعضاء الحسّ، وهي العينان والأنف والأذنان واللسان والجلد، الرسائل إلى الدماغ عبر الأعصاب، التي تنقل التعليمات من الدماغ إلى العضلات. ويتحكّم الدماغ تلقائياً في التنفّس ونبض القلب والهضم وغير ذلك.',
          'يستمرّ الجسم في النموّ، ويبلغ ذروة نموّه الجسدي في نحو الثامنة عشرة إلى الخامسة والعشرين من العمر. وعندما نتقدّم في السنّ يصبح الجلد مجعّداً وأقلّ مرونة، وتصبح المفاصل متصلّبة، وترتخي العضلات، وتضعف العظام.',
          'وإليك بعض النصائح لتتقدّم في السنّ بصحة جيدة: اعتنِ بجلدك فهو أكبر أعضائك. وعليك أيضاً أن تقلّل ما تتناوله من الملح إلى أدنى حدّ كي يبقى ضغط دمك منخفضاً. كما ثبت أن النوم الكافي يقلّل خطر الإصابة بأمراض القلب والسكتة الدماغية.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'The sense organs pass the messages to the brain through ……..', promptAr: 'تنقل أعضاء الحسّ الرسائل إلى الدماغ عبر ……..', options: ['bones', 'nerves', 'joints', 'the backbone'], answer: 1,
              explainAr: 'النص: "The sense organs namely eyes, nose, ears, tongue and skin pass the messages to the brain through nerves". أما العظام والمفاصل فهي للهيكل والحركة، والعمود الفقري يدعم الرأس والأطراف.' },
            { n: 9, kind: 'mcq', prompt: 'According to the text, the backbone ……..', promptAr: 'بحسب النص، العمود الفقري ……..', options: ['controls breathing and heartbeat', 'keeps water and harmful germs out', 'passes the messages to the brain', 'supports the head and limbs and protects the spinal cord'], answer: 3,
              explainAr: 'النص: "The backbone supports the head and limbs and protects the spinal cord." أما التحكّم في التنفّس ونبض القلب فهو عمل الدماغ، ونقل الرسائل إلى الدماغ عمل أعضاء الحسّ والأعصاب.' },
            { n: 10, kind: 'mcq', prompt: 'The peak of physical growth is reached ……..', promptAr: 'يبلغ الجسم ذروة نموّه الجسدي ……..', options: ['at about 10 to 15 years of age', 'at about 25 to 35 years of age', 'at about 18 to 25 years of age', 'when we grow old'], answer: 2,
              explainAr: 'النص: "The peak of physical growth is reached at about 18 to 25 years of age." وعندما نتقدّم في السنّ (when we grow old) يضعف الجسم ولا يبلغ ذروته.' },
            { n: 11, kind: 'mcq', prompt: 'A word in the text which means “capable of stretching” is ……..', promptAr: 'كلمة في النص تعني "قابل للتمدّد" هي ……..', options: ['elastic', 'wrinkled', 'inflexible', 'loose'], answer: 0, topic: 'vocab',
              explainAr: 'elastic = مرن قابل للتمدّد (من تمرين المفردات في الوحدة 8). wrinkled = مجعّد فيه خطوط وثنيات، inflexible = غير مرن/متصلّب، loose = يرتخي.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'Nerves spread from the brain to all parts of the body, carrying ……………………', promptAr: 'تمتدّ الأعصاب من الدماغ إلى جميع أجزاء الجسم حاملةً ……', lines: 2,
              accept: ['signals in the form of tiny electrical impulses', 'signals in the form of electrical impulses', 'signals'],
              modelAr: 'إشارات على شكل نبضات كهربائية دقيقة.',
              explainAr: 'النص: "Nerves spread from the brain to all parts of the body, carrying signals in the form of tiny electrical impulses."' },
            { n: 13, kind: 'write', prompt: 'Getting enough sleep has been proved to ……………………', promptAr: 'ثبت أن النوم الكافي ……', lines: 2,
              accept: ['lower the risk of heart disease and stroke', 'lower the risk of heart disease', 'reduce the risk of heart disease and stroke'],
              modelAr: 'يقلّل خطر الإصابة بأمراض القلب والسكتة الدماغية.',
              explainAr: 'آخر جملة في النص: "getting enough sleep has been proved to lower the risk of heart disease and stroke." بعد to نكتب الفعل في مصدره: lower.' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'We’ve been talking about this project for a while, and it’s time to ……… .', promptAr: 'نتحدّث عن هذا المشروع منذ مدة، وقد حان الوقت لـ ___ .', options: ['fit in with it', 'run into it', 'keep up with it', 'follow it through'], answer: 3,
          explainAr: 'follow something through = يبدأ شيئاً ويكمله حتى النهاية بشكل مُرضٍ، والجملة نفسها في كتابك (الوحدة 1). fit in with = ينسجم مع مجموعة، run into = يصادف مشكلة فجأة، keep up with = يواكب ويبقى مطّلعاً.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'February 7 is the day ……… I met my best friend.', promptAr: 'السابع من شباط هو اليوم ___ التقيتُ فيه بأعزّ أصدقائي.', options: ['when', 'where', 'which', 'whose'], answer: 0,
          explainAr: 'بعد اسم يدل على زمن (the day) ويليه جملة كاملة (I met my best friend) نستخدم when، والجملة من مراجعة الوحدة 2 في كتابك. where للمكان، which تحتاج جملة ينقصها فاعل أو مفعول، whose للملكية.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'You must visit that restaurant; the food is really good but it costs you ……… .', promptAr: 'يجب أن تزور ذلك المطعم؛ الطعام جيد حقاً لكنه يكلّفك ___ .', options: ['a pain in the neck', 'an arm and a leg', 'your heart', 'a wide face'], answer: 1,
          explainAr: 'cost an arm and a leg = يكلّف مبلغاً باهظاً جداً (تعابير الجسم في الوحدة 8). a pain in the neck = شيء مزعج، follow your heart = اتبع إحساسك، have a wide face = أن تكون محبوباً وكثير الأصدقاء (الوحدة 10).' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'A small amount of a substance that is taken from someone’s body in order to test it is a ……… .', promptAr: 'كمية صغيرة من مادة تؤخذ من جسم شخص لفحصها هي ___ .', options: ['symptom', 'gut', 'swab', 'host'], answer: 2,
          explainAr: 'swab = مسحة/عيّنة تؤخذ من الجسم للفحص، وهي من كلمات نص الوحدة 7 (a sample of your urine, blood or swab). symptom = عَرَض، gut = الأمعاء، host = المضيف (الخلية التي يعيش فيها الفيروس).' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'In which word is the letter “w” silent?', promptAr: 'في أي كلمة يكون حرف "w" صامتاً (لا يُلفظ)؟', options: ['window', 'away', 'swim', 'wrong'], answer: 3,
          explainAr: 'الحروف الصامتة (الوحدة 7): حرف w لا يُلفظ غالباً قبل r في أول الكلمة، كما في wrong و write، وكذلك في answer و whole. أما في window و away و swim فيُلفظ w.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'The carpenter has used a special hammer to ……… the nails into the finished doors.', promptAr: 'استخدم النجّار مطرقة خاصة لـ ___ المسامير في الأبواب المُنجزة.', options: ['drive', 'jack', 'shore', 'check'], answer: 0,
          explainAr: 'drive something into = يدقّ شيئاً في شيء آخر بالطَّرق، والجملة من كتابك (الوحدة 4). jack up = يرفع بالرافعة، shore up = يدعم كي لا يسقط، check over = يفحص بحثاً عن عيوب.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'He’s very keen ……… chess.', promptAr: 'إنه شغوف جداً ___ الشطرنج.', options: ['at', 'on', 'of', 'with'], answer: 1,
          explainAr: 'صفات يليها حرف جر ثابت (الوحدة 9): keen on = مولع بـ/شغوف بـ، والجملة من كتابك. قارن: good at، proud of، angry with.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'In which sentence is the auxiliary verb pronounced in its strong form?', promptAr: 'في أي جملة يُلفظ الفعل المساعد بصيغته القوية؟', options: ['Can you speak English?', 'Do they come early?', 'Yes, I can.', 'Was the weather terrible?'], answer: 2,
          explainAr: 'الصيغ القوية والضعيفة (الوحدة 11): يُلفظ الفعل المساعد بصيغته القوية عندما يأتي في آخر الجملة كما في الإجابة القصيرة "Yes, I can." /kæn/. أما في بداية السؤال فيُلفظ ضعيفاً بصوت schwa: Can /kən/، Do /də/، Was /wəz/.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Some citizens take an ……… role in the community.', promptAr: 'يؤدّي بعض المواطنين دوراً ___ في المجتمع.', options: ['act', 'action', 'actively', 'active'], answer: 3,
          explainAr: 'قبل الاسم role نحتاج صفة: active = فعّال/نشيط، والجملة من تمرين عائلة الكلمة في الوحدة 9. act فعل، action اسم، actively ظرف.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'If he has a credit card, he doesn’t ……… to pay for something in cash. He can use the card.', promptAr: 'إذا كانت لديه بطاقة ائتمان فهو ليس مضطراً للدفع نقداً. يمكنه استخدام البطاقة.', lines: 1,
          accept: ['have'], explainAr: 'الأفعال الناقصة (الوحدة 10): don’t/doesn’t have to تعبّر عن عدم الإلزام (لست مضطراً). بعد doesn’t يأتي have بلا s، والجملة من كتابك.' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'Neither my mother ……… my sister is here.', promptAr: 'لا أمّي ولا أختي هنا.', lines: 1,
          accept: ['nor'], explainAr: 'أدوات الربط المزدوجة (الوحدة 9): neither يأتي معها دائماً nor. وكذلك either ... or و both ... and و not only ... but also.' },
        { n: 25, kind: 'write', topic: 'grammar', prompt: 'Food ……… grown all over the country.', promptAr: 'يُزرع الطعام في كل أنحاء البلاد.', lines: 1,
          accept: ['is'], explainAr: 'المبني للمجهول في المضارع البسيط (الوحدة 3 والمراجعة 1): am/is/are + التصريف الثالث. Food مفرد غير معدود فنستخدم is.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'Jack is travelling to Spain {tomorrow}.', promptAr: 'سيسافر جاك إلى إسبانيا غداً.', lines: 1,
          accept: ['When is Jack travelling to Spain?'], modelAr: 'متى سيسافر جاك إلى إسبانيا؟',
          explainAr: 'المسطَّر (tomorrow) يدل على زمن فنسأل بـ When. الفعل مضارع مستمر (is travelling) فنقدّم is على الفاعل: When is Jack travelling...?' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'Before hospitals developed, patients were treated mostly {in temples}.', promptAr: 'قبل أن تتطوّر المستشفيات كان المرضى يُعالَجون غالباً في المعابد.', lines: 1,
          accept: ['Where were patients treated mostly before hospitals developed?', 'Where were patients mostly treated before hospitals developed?', 'Where were patients treated before hospitals developed?', 'Before hospitals developed, where were patients treated mostly?', 'Where were patients treated mostly?'], modelAr: 'أين كان المرضى يُعالَجون غالباً قبل أن تتطوّر المستشفيات؟',
          explainAr: 'المسطَّر (in temples) مكان فنسأل بـ Where. الفعل مبني للمجهول في الماضي (were treated) فنقدّم were على الفاعل: Where were patients treated...?' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: '{Mr. Bshara’s} friend has had a bad fall.', promptAr: 'تعرّض صديق السيد بشارة لسقطة سيئة.', lines: 1,
          accept: ['Whose friend has had a bad fall?'], modelAr: 'صديقُ مَن تعرّض لسقطة سيئة؟',
          explainAr: 'المسطَّر يدل على الملكية (Mr. Bshara’s) فنسأل بـ Whose + الاسم. وبما أن السؤال عن الفاعل فلا نضيف فعلاً مساعداً ويبقى الترتيب: Whose friend has had...?' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'conditional', prompt: 'I haven’t got enough time, so I can’t visit my aunt in the next town. (conditional type II)', promptAr: 'ليس لديّ وقت كافٍ، لذلك لا أستطيع زيارة عمّتي في البلدة المجاورة. (الشرطية من النوع الثاني)', lines: 2,
          accept: ['If I had enough time, I would visit my aunt in the next town.', 'If I had enough time, I could visit my aunt in the next town.', 'If I had got enough time, I would visit my aunt in the next town.', 'If I had got enough time, I could visit my aunt in the next town.', 'I would visit my aunt in the next town if I had enough time.', 'I could visit my aunt in the next town if I had enough time.'],
          model: 'If I had enough time, I would visit my aunt in the next town.', modelAr: 'لو كان لديّ وقت كافٍ لزرتُ عمّتي في البلدة المجاورة.',
          explainAr: 'الشرطية الثانية لموقف تخيّلي في الحاضر (الوحدة 7): If + ماضٍ بسيط، would/could + المصدر. الجملة الأصلية منفية فتصبح مثبتة: haven’t got ← had، can’t visit ← would (could) visit. والموقف من مراجعة الوحدة 2.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'I regret that I started smoking. (Use: I wish)', promptAr: 'أندم على أنني بدأت التدخين. (استخدم: I wish)', lines: 2,
          accept: ['I wish I hadn’t started smoking.', 'I wish I had not started smoking.', 'I wish I had never started smoking.'],
          modelAr: 'ليتني لم أبدأ التدخين.',
          explainAr: 'التمنّي عن الماضي (الوحدة 8): I wish + ماضٍ تام. الشخص بدأ التدخين فعلاً ويندم، فنعكس المعنى إلى النفي: I wish I hadn’t started smoking. والجملة نفسها في كتابك.' },
        { n: 31, kind: 'write', topic: 'reported', prompt: '“Have you ever been to London?” he asked me. (reported speech)', promptAr: '"هل زرت لندن من قبل؟" سألني. (الكلام المنقول)', lines: 2,
          accept: ['He asked me if I had ever been to London.', 'He asked me whether I had ever been to London.', 'He wanted to know if I had ever been to London.', 'He wanted to know whether I had ever been to London.'],
          modelAr: 'سألني إن كنت قد زرت لندن من قبل.',
          explainAr: 'نقل سؤال Yes/No (الوحدة 11): asked + if/whether + فاعل + فعل (بلا قلب). نرجع الزمن خطوة: have been ← had been، ونغيّر you إلى I.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Sami’s parents must have brought him up to be more polite. (passive voice)', promptAr: 'لا بدّ أن والدَي سامي ربّياه ليكون أكثر تهذيباً. (المبني للمجهول)', lines: 2,
          accept: ['Sami must have been brought up to be more polite.', 'Sami must have been brought up by his parents to be more polite.', 'Sami must have been brought up to be more polite by his parents.'],
          modelAr: 'لا بدّ أن سامي قد رُبّي ليكون أكثر تهذيباً.',
          explainAr: 'المبني للمجهول مع فعل ناقص في الماضي (الوحدة 3): must have been + التصريف الثالث. نبدأ بالمفعول him فيصبح Sami، ويبقى up بعد brought. والجملة من تمرين كتابك.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'A: So, Jack is your best friend. B: Yes, we ………. (be) friends for more than ten years.', promptAr: 'أ: إذن جاك هو أعزّ أصدقائك. ب: نعم، نحن صديقان منذ أكثر من عشر سنوات.', lines: 1,
          accept: ['have been', "'ve been"], explainAr: 'المضارع التام (الوحدة 1) لشيء بدأ في الماضي وما زال صحيحاً الآن، مع for + مدة: have been. والحوار من كتابك.' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'I don’t know how to dance. I wish I ………. (know) how to dance.', promptAr: 'لا أعرف كيف أرقص. ليتني أعرف كيف أرقص.', lines: 1,
          accept: ['knew'], explainAr: 'التمنّي عن الحاضر (الوحدة 8): I wish + ماضٍ بسيط. don’t know (حاضر) ← wish I knew (التصريف الثاني لـ know).' },
        { n: 35, kind: 'write', topic: 'conditional', prompt: 'If I ………. (have) enough money, I would buy a Ferrari.', promptAr: 'لو كان لديّ ما يكفي من المال لاشتريت سيارة فيراري.', lines: 1,
          accept: ['had'], explainAr: 'الشرطية الثانية لموقف تخيّلي في الحاضر (الوحدة 7): If + ماضٍ بسيط (had)، would + المصدر (would buy).' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'conditional', prompt: 'If the weather is really rough tomorrow, …………………………..', promptAr: 'إذا كان الطقس عاصفاً جداً غداً، …', lines: 2,
          accept: ['we will cancel the trip.', 'we will stay at home.', 'we won’t go on the boat trip.', 'the boat won’t leave.', 'we will not go out.'], model: 'we will cancel the trip.', modelAr: 'سنُلغي الرحلة.',
          explainAr: 'If + مضارع بسيط (is) ← الشرطية الأولى لاحتمال حقيقي في المستقبل (tomorrow)، فالجواب: will/won’t + المصدر. الفكرة من حوار طلب المعلومات في الوحدة 3.' },
        { n: 37, kind: 'write', topic: 'tense', prompt: 'By the time I finish university, …………………………..', promptAr: 'بحلول الوقت الذي أُنهي فيه الجامعة، …', lines: 2,
          accept: ['I will have learned a lot.', 'I will have learnt three languages.', 'I will have written my CV.', 'I will have found a job.', 'I will have got a lot of experience.'], model: 'I will have learned a lot.', modelAr: 'سأكون قد تعلّمتُ الكثير.',
          explainAr: 'By the time + مضارع بسيط (finish) بمعنى المستقبل ← المستقبل التام في الجملة الرئيسية: will have + التصريف الثالث لحدث سيكتمل قبل ذلك الوقت (الوحدة 6).' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: The Internet could be a very positive step towards education, organisation and participation in a meaningful society.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['يمكن أن يكون الإنترنت خطوة إيجابية جداً نحو التعليم والتنظيم والمشاركة في مجتمع هادف', 'قد يكون الإنترنت خطوة إيجابية جداً نحو التعليم والتنظيم والمشاركة في مجتمع ذي معنى', 'يمكن للإنترنت أن يكون خطوة إيجابية جداً باتجاه التعليم والتنظيم والمشاركة في مجتمع هادف'],
          model: 'يمكن أن يكون الإنترنت خطوة إيجابية جداً نحو التعليم والتنظيم والمشاركة في مجتمع هادف.',
          explainAr: 'الجملة من كتابك (الوحدة 12، الكتابة). could be = يمكن أن يكون، step towards = خطوة نحو، participation = المشاركة، meaningful society = مجتمع هادف/ذو معنى.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: بُنيت مدارس كثيرة في مدينتنا في السنوات الأخيرة.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['Many schools have been built in our city in recent years.', 'A lot of schools have been built in our city in recent years.', 'Many schools have been built in our city recently.', 'Many new schools have been built in our city in recent years.', 'Many schools were built in our city in recent years.'],
          model: 'Many schools have been built in our city in recent years.',
          explainAr: 'بُنيت ← مبني للمجهول، و"في السنوات الأخيرة" تدل على المضارع التام: have been + built. مدارس كثيرة ← many schools (جمع فنستخدم have).' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Using the Internet in learning.',
        topicAr: 'استخدام الإنترنت في التعلّم.',
        words: 80,
        points: ['How can students use the Internet in learning?', 'What are the advantages of learning online?', 'What problems may students face, and what is your advice?'],
        model: 'The Internet could be a very positive step towards education. Nowadays, students can use it not only to look up information but also to take lessons at an e-school. They can engage in email or video chat with students from other countries and share their ideas. One advantage of learning online is that it saves time and money, and students can learn at any time. However, there is a lot of information on the Internet, so students need critical thinking skills to evaluate it. Some students also waste hours on social media instead of studying. My advice is to use the Internet wisely. Never should we forget that technology is a tool, not a teacher.',
        modelAr: 'يمكن أن يكون الإنترنت خطوة إيجابية جداً نحو التعليم. يستطيع الطلاب اليوم استخدامه ليس فقط للبحث عن المعلومات بل أيضاً لتلقّي الدروس في مدرسة إلكترونية. ويمكنهم التواصل بالبريد الإلكتروني أو محادثات الفيديو مع طلاب من بلدان أخرى وتبادل الأفكار معهم. ومن مزايا التعلّم عبر الإنترنت أنه يوفّر الوقت والمال، ويستطيع الطلاب التعلّم في أي وقت. لكن على الإنترنت كمّاً كبيراً من المعلومات، لذلك يحتاج الطلاب إلى مهارات التفكير النقدي لتقييمها. كما يضيّع بعض الطلاب ساعات على وسائل التواصل الاجتماعي بدلاً من الدراسة. نصيحتي أن نستخدم الإنترنت بحكمة، وألّا ننسى أبداً أن التكنولوجيا أداة وليست معلّماً.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: كيف يستخدم الطلاب الإنترنت في التعلّم، ومزايا التعلّم عبر الإنترنت، والمشكلات مع نصيحة.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (not only … but also, However, so, also, instead of).',
          'استخدمتُ تراكيب من الكتاب مثل القلب بعد never (Never should we forget…) والفعل الناقص could.',
          'استخدمتُ كلمات من الوحدة 12 (e-school, video chat, critical thinking, evaluate, social media).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
