import type { Exam } from '../../../engine/types'

// A final Baccalaureate practice paper in the exact layout of the real paper (term1-a.ts), covering the whole book.
// Passage A: Unit 8 reading "Human Body" (page 75), first part. Passage B: Unit 11 reading "Artificial Intelligence" (pages 108–109), first part.
export const term2B: Exam = {
  id: 't2-b',
  term: 2,
  title: 'Baccalaureate — Final Test (B)',
  titleAr: 'نموذج البكالوريا النهائي (B)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل الدقيق لامتحان البكالوريا الحقيقي، يغطّي الكتاب كاملاً (الوحدات 1–12) ومبنيّ من نصوص الكتاب وقواعده ومفرداته فقط.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'The human body is a wonderful machine which performs several functions without rest from birth. Our body continues to work, without stopping for a second. The main organs of the human body are lungs, heart, kidney, liver and brain. These organs work together and are controlled by the brain. Each system such as digestive system, excretory system, circulatory system, endocrine system, nervous system or muscular system carries out a major function. All of them are controlled by the brain which gives us intelligence to use our physical and mental abilities.',
          'An average person is estimated to contain trillions of human cells, according to recent research. These cells include neurons (nerve cells) and glands (specialised cells). The hormones and enzymes are produced and secreted by these glands that perform different functions.',
          'The human body is covered by the skin, which is a flexible covering that protects the body and keeps water and harmful germs out.',
        ],
        paragraphsAr: [
          'جسم الإنسان آلة رائعة تؤدّي وظائف عديدة دون راحة منذ الولادة. فجسمنا يستمرّ في العمل دون أن يتوقّف لحظة واحدة. والأعضاء الرئيسية في جسم الإنسان هي الرئتان والقلب والكلية والكبد والدماغ. تعمل هذه الأعضاء معاً ويتحكّم بها الدماغ. وكل جهاز، كالجهاز الهضمي والجهاز الإخراجي وجهاز الدوران وجهاز الغدد الصمّاء والجهاز العصبي والجهاز العضلي، يؤدّي وظيفة رئيسية. وكلّها يتحكّم بها الدماغ الذي يمنحنا الذكاء لنستخدم قدراتنا الجسدية والعقلية.',
          'يُقدَّر أن جسم الشخص العادي يحتوي على تريليونات الخلايا البشرية، وفقاً لأبحاث حديثة. وتشمل هذه الخلايا العصبونات (الخلايا العصبية) والغدد (خلايا متخصّصة). وتُنتج هذه الغدد الهرمونات والإنزيمات وتفرزها، وهي تؤدّي وظائف مختلفة.',
          'جسم الإنسان مغطّى بالجلد، وهو غطاء مرن يحمي الجسم ويمنع دخول الماء والجراثيم الضارّة.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'Why is the human body considered a wonderful machine?', promptAr: 'لماذا يُعدّ جسم الإنسان آلة رائعة؟', lines: 3,
              accept: ['Because it performs several functions without rest from birth.', 'It performs several functions without rest from birth.', 'Because it performs several functions without rest from birth and continues to work without stopping for a second.', 'Because it continues to work without stopping for a second.', 'Because it performs several functions without rest.'],
              model: 'Because it performs several functions without rest from birth.',
              modelAr: 'لأنه يؤدّي وظائف عديدة دون راحة منذ الولادة.',
              explainAr: 'الجملة الأولى: "The human body is a wonderful machine which performs several functions without rest from birth". السؤال بـ Why فابدأ الجواب بـ Because.' },
            { n: 2, kind: 'write', prompt: 'What are the main organs of the human body?', promptAr: 'ما الأعضاء الرئيسية في جسم الإنسان؟', lines: 2,
              accept: ['The main organs of the human body are lungs, heart, kidney, liver and brain.', 'They are lungs, heart, kidney, liver and brain.', 'Lungs, heart, kidney, liver and brain.', 'The lungs, the heart, the kidney, the liver and the brain.'],
              model: 'The main organs of the human body are lungs, heart, kidney, liver and brain.',
              modelAr: 'الأعضاء الرئيسية هي الرئتان والقلب والكلية والكبد والدماغ.',
              explainAr: 'النص: "The main organs of the human body are lungs, heart, kidney, liver and brain". انقل الأعضاء الخمسة كلها.' },
            { n: 3, kind: 'write', prompt: 'What do the glands produce and secrete?', promptAr: 'ماذا تُنتج الغدد وتُفرز؟', lines: 2,
              accept: ['They produce and secrete hormones and enzymes.', 'The glands produce and secrete hormones and enzymes.', 'Hormones and enzymes.', 'They produce hormones and enzymes.'],
              model: 'They produce and secrete hormones and enzymes.',
              modelAr: 'تُنتج الهرمونات والإنزيمات وتفرزها.',
              explainAr: 'النص بالمبني للمجهول: "The hormones and enzymes are produced and secreted by these glands". حوّلها إلى المعلوم في الجواب: The glands produce and secrete hormones and enzymes.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', topic: 'vocab', prompt: 'Relating to the system in your body that produces hormones ……..', promptAr: 'متعلّق بالجهاز في جسمك الذي يُنتج الهرمونات', lines: 1,
              accept: ['endocrine'], modelAr: 'الغدد الصمّاء',
              explainAr: 'في النص "endocrine system" — جهاز الغدد الصمّاء، وهو الذي يُنتج الهرمونات. التعريف نفسه في تمرين المفردات في الوحدة 8.' },
            { n: 5, kind: 'write', topic: 'vocab', prompt: 'Having the function of getting rid of waste material from the body ……..', promptAr: 'وظيفته التخلّص من الفضلات من الجسم', lines: 1,
              accept: ['excretory'], modelAr: 'إخراجي',
              explainAr: 'في النص "excretory system" — الجهاز الإخراجي الذي يخلّص الجسم من الفضلات. لا تخلط بينه وبين digestive (هضمي) أو circulatory (دوراني).' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'The main organs of the body work separately and are controlled by the heart.', promptAr: 'تعمل الأعضاء الرئيسية في الجسم منفصلة ويتحكّم بها القلب.', lines: 2,
              accept: ['The main organs of the body work together and are controlled by the brain.', 'The main organs of the human body work together and are controlled by the brain.', 'These organs work together and are controlled by the brain.'],
              model: 'The main organs of the body work together and are controlled by the brain.',
              modelAr: 'تعمل الأعضاء الرئيسية في الجسم معاً ويتحكّم بها الدماغ.',
              explainAr: 'النص: "These organs work together and are controlled by the brain". في الجملة خطآن: separately ← together، و the heart ← the brain.' },
            { n: 7, kind: 'write', prompt: 'The skin is a hard covering that lets water and harmful germs into the body.', promptAr: 'الجلد غطاء صلب يُدخل الماء والجراثيم الضارّة إلى الجسم.', lines: 2,
              accept: ['The skin is a flexible covering that protects the body and keeps water and harmful germs out.', 'The skin is a flexible covering that keeps water and harmful germs out of the body.', 'The skin is a flexible covering that keeps water and harmful germs out.'],
              model: 'The skin is a flexible covering that protects the body and keeps water and harmful germs out.',
              modelAr: 'الجلد غطاء مرن يحمي الجسم ويمنع دخول الماء والجراثيم الضارّة.',
              explainAr: 'النص: "the skin, which is a flexible covering that protects the body and keeps water and harmful germs out". الخطأ: hard ← flexible، و lets ... into ← keeps ... out.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'Artificial Intelligence (AI) is the branch of science and engineering specialised in making clever machines, capable of thinking and imitating human-level intelligence. One of the primary targets of AI field is to produce fully intelligent agents that interact with the surroundings and conduct human-like behaviours. These agents are tools, having the ability to judge matter and differentiate what is wrong.',
          'The field has started with robots, which can sense and react to the world around them. They also cover purely software-based agents, which can be actuated with natural language and multimedia. Currently, the field expands to driving, aviation, medicine, online advertising, image recognition, and personal assistance. The AI field is based on computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields.',
          'The first spark started in the year 1950, when a test of the ability of a machine to exhibit intelligent behaviour equivalent to that of a human was done.',
        ],
        paragraphsAr: [
          'الذكاء الاصطناعي هو فرع العلم والهندسة المتخصّص في صنع آلات ذكية قادرة على التفكير ومحاكاة الذكاء على المستوى البشري. ومن الأهداف الرئيسية لمجال الذكاء الاصطناعي إنتاج وكلاء أذكياء تماماً يتفاعلون مع محيطهم ويسلكون سلوكاً شبيهاً بسلوك البشر. وهؤلاء الوكلاء أدوات لديها القدرة على الحكم على الأمور والتمييز بين ما هو خاطئ.',
          'بدأ هذا المجال بالروبوتات التي تستطيع أن تستشعر العالم من حولها وتتفاعل معه. ويشمل أيضاً وكلاء برمجيين بحتين يمكن تشغيلهم باللغة الطبيعية والوسائط المتعدّدة. ويتوسّع المجال حالياً ليشمل قيادة السيارات والطيران والطب والإعلانات على الإنترنت والتعرّف على الصور والمساعدة الشخصية. ويقوم مجال الذكاء الاصطناعي على علوم الحاسوب وهندسة المعلومات والرياضيات وعلم النفس واللسانيات والفلسفة وحقول أخرى كثيرة.',
          'انطلقت الشرارة الأولى عام 1950، حين أُجري اختبار لقدرة آلة على إظهار سلوك ذكي يعادل سلوك الإنسان.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'The field of AI started with ……..', promptAr: 'بدأ مجال الذكاء الاصطناعي بـ ……..', options: ['software-based agents', 'robots', 'online advertising', 'personal assistance'], answer: 1,
              explainAr: 'النص: "The field has started with robots, which can sense and react to the world around them". أما software-based agents فجاءت بعدها (They also cover...)، و online advertising و personal assistance مجالات توسّع إليها حالياً.' },
            { n: 9, kind: 'mcq', prompt: 'AI agents are tools having the ability to ……..', promptAr: 'وكلاء الذكاء الاصطناعي أدوات لديها القدرة على ……..', options: ['feel basic human emotions', 'work without any software', 'judge matter and differentiate what is wrong', 'replace all human doctors'], answer: 2,
              explainAr: 'النص: "These agents are tools, having the ability to judge matter and differentiate what is wrong". الخيارات الأخرى غير مذكورة في النص.' },
            { n: 10, kind: 'mcq', prompt: 'Purely software-based agents can be actuated with ……..', promptAr: 'يمكن تشغيل الوكلاء البرمجيين البحتين بـ ……..', options: ['natural language and multimedia', 'electrical impulses', 'robots only', 'image recognition'], answer: 0,
              explainAr: 'النص: "They also cover purely software-based agents, which can be actuated with natural language and multimedia" — باللغة الطبيعية والوسائط المتعدّدة.' },
            { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'The designing, building and flying of aircraft is ……..', promptAr: 'تصميم الطائرات وبناؤها وقيادتها هو ……..', options: ['advertising', 'recognition', 'assistance', 'aviation'], answer: 3,
              explainAr: 'aviation = الطيران، وهي في النص "the field expands to driving, aviation, medicine...". advertising = الإعلان، recognition = التعرّف، assistance = المساعدة.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'The AI field is based on ……………………', promptAr: 'يقوم مجال الذكاء الاصطناعي على ……', lines: 2,
              accept: ['computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields', 'computer science, information engineering, mathematics, psychology, linguistics and philosophy', 'computer science, information engineering, mathematics, psychology, linguistics, philosophy and other fields'],
              model: 'computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields.',
              modelAr: 'علوم الحاسوب وهندسة المعلومات والرياضيات وعلم النفس واللسانيات والفلسفة وحقول أخرى كثيرة.',
              explainAr: 'النص: "The AI field is based on computer science, information engineering, mathematics, psychology, linguistics, philosophy and many other fields".' },
            { n: 13, kind: 'write', prompt: 'One of the primary targets of AI is to produce ……………………', promptAr: 'من الأهداف الرئيسية للذكاء الاصطناعي إنتاج ……', lines: 2,
              accept: ['fully intelligent agents that interact with the surroundings and conduct human-like behaviours', 'fully intelligent agents', 'fully intelligent agents that interact with the surroundings'],
              model: 'fully intelligent agents that interact with the surroundings and conduct human-like behaviours.',
              modelAr: 'وكلاء أذكياء تماماً يتفاعلون مع محيطهم ويسلكون سلوكاً شبيهاً بسلوك البشر.',
              explainAr: 'النص: "One of the primary targets of AI field is to produce fully intelligent agents that interact with the surroundings and conduct human-like behaviours".' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'If I like this job, I’ll ……… next year.', promptAr: 'إذا أحببتُ هذا العمل، ___ السنة القادمة.', options: ['carry on', 'give up', 'take up', 'fit in'], answer: 0,
          explainAr: 'carry on = يستمر (continue)، والجملة من كتابك (الوحدة 2). give up = يترك، take up = يبدأ نشاطاً جديداً ويحتاج مفعولاً به، fit in = يتأقلم مع مجموعة. إذا أحببت العمل فستستمر فيه.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'That is the village ……… my grandparents live.', promptAr: 'تلك هي القرية ___ يعيش فيها جدّاي.', options: ['which', 'where', 'when', 'whose'], answer: 1,
          explainAr: 'بعد اسم مكان (the village) ويليه جملة كاملة (my grandparents live) نستخدم where. which تحتاج حرف جر (in which)، when للزمن، whose للملكية. التمرين من المراجعة 2.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'The doorbell made him ……… .', promptAr: 'جعله جرس الباب ___.', options: ['speak his mind', 'jump out of his skin', 'follow his heart', 'break bread'], answer: 1,
          explainAr: 'jump out of your skin = يفزع/يُصدم فجأة (shocked)، والجملة من تعابير الجسم في الوحدة 8. speak your mind = يقول ما يفكّر فيه بصراحة، follow your heart = يتبع إحساسه، break bread with = يكون صديقاً مقرّباً.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'A new plan for achieving a particular purpose is a/an ……… .', promptAr: 'الخطة الجديدة لتحقيق هدف معيّن هي ___.', options: ['liability', 'transaction', 'initiative', 'consultation'], answer: 2,
          explainAr: 'initiative = مبادرة (a new plan for achieving a particular purpose)، من كلمات نص الحكومة الإلكترونية (الوحدة 12). liability = مسؤولية قانونية، transaction = صفقة/معاملة، consultation = استشارة.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'In which word is the stress on the third syllable?', promptAr: 'في أيّ كلمة يقع النبر على المقطع الثالث؟', options: ['sensible', 'comfortable', 'irresponsible', 'dangerous'], answer: 2,
          explainAr: 'نبر المقاطع (الوحدة 8): البادئات لا تُنبر، و irresponsible فيها بادئتان (ir + re) فيقع النبر على المقطع الثالث: ir-re-SPON-si-ble. واللواحق ible و able و ous لا تُنبر، فالنبر في sensible و comfortable و dangerous على المقطع الأول.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'A red light started to ……… after a few seconds.', promptAr: 'بدأ ضوء أحمر ___ بعد بضع ثوانٍ.', options: ['rotate', 'react', 'dissect', 'flash'], answer: 3,
          explainAr: 'flash = يومض (للضوء)، والجملة من تمرين أفعال العلوم والتكنولوجيا في الوحدة 11. rotate = يدور، react = يتفاعل، dissect = يشرّح.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'Suzan must be good ……… French. She got a full mark in the exam.', promptAr: 'لا بدّ أن سوزان جيدة ___ الفرنسية. لقد نالت العلامة الكاملة في الامتحان.', options: ['with', 'on', 'for', 'at'], answer: 3,
          explainAr: 'الصفة good (و brilliant) يليها حرف الجر at عند الحديث عن مهارة أو مادة: good at French. من الوحدة 9، والجملة من المراجعة 3.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'In “You’re French, aren’t you?” the speaker is sure and expects confirmation. His voice ……… at the end.', promptAr: 'في "You’re French, aren’t you?" المتكلّم متأكّد وينتظر التأكيد. صوته ___ في النهاية.', options: ['rises', 'falls', 'stays level', 'stops suddenly'], answer: 1,
          explainAr: 'تنغيم السؤال (الوحدة 10): في السؤال الذيلي (question tag) الذي ينتظر تأكيداً يهبط الصوت (falling intonation). أما إذا كان المتكلّم غير متأكّد فيرتفع الصوت.' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'He should be able to solve the problem. He’s reasonably ……… .', promptAr: 'يُفترض أن يستطيع حلّ المشكلة. إنه ___ إلى حدّ معقول.', options: ['intelligent', 'intelligence', 'intelligently', 'intelligences'], answer: 0,
          explainAr: 'بعد He’s (he is) والظرف reasonably نحتاج صفة: intelligent = ذكي. intelligence اسم، intelligently ظرف. الجملة من تمرين أقسام الكلام في الوحدة 11.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'I wish our neighbours ……… stop arguing. They annoy us.', promptAr: 'ليت جيراننا ___ يتوقّفون عن الشجار. إنهم يزعجوننا.', lines: 1,
          accept: ['would'], explainAr: 'التمنّي (الوحدة 8): wish + would + المصدر نستخدمها عندما نتمنّى أن يغيّر شخص آخر تصرّفاً يزعجنا. الجملة من المراجعة 2: "I wish our neighbours would stop arguing."' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'Seldom ……… I leave my house so early.', promptAr: 'نادراً ما ___ أغادر بيتي باكراً إلى هذا الحد.', lines: 1,
          accept: ['do', 'did'], explainAr: 'التقديم والتأخير (الوحدة 12): عندما تبدأ الجملة بظرف نفي أو تقليل مثل Seldom نقدّم الفعل المساعد على الفاعل. في المضارع البسيط نستخدم do (وفي الماضي did). الجملة من كتابك: "Seldom do I leave my house so early."' },
        { n: 25, kind: 'write', topic: 'grammar', prompt: 'A local jewellery shop was broken into ……… someone yesterday.', promptAr: 'اقتُحم محلّ مجوهرات محلّي ___ شخص ما أمس.', lines: 1,
          accept: ['by'], explainAr: 'في المبني للمجهول (الوحدة 3) نذكر الفاعل بعد by. لاحظ أن into جزء من الفعل break into فيبقى، ثم يأتي by someone. الجملة من قصة كتابك.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'We’re taking {the nine o’clock} train.', promptAr: 'سنأخذ قطار الساعة التاسعة.', lines: 1,
          accept: ['Which train are you taking?', 'What train are you taking?'], model: 'Which train are you taking?', modelAr: 'أيّ قطار ستأخذون؟',
          explainAr: 'المسطَّر يحدّد أيّ قطار من بين قطارات عدّة، فنسأل بـ Which + الاسم (Which train). الفعل مضارع مستمر (are taking) فنقدّم are، ويتغيّر We ← you. الجملة من تمرين رحلة جودي (الوحدة 11).' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'There are departures at 10 a.m. and 2 p.m. {every day}.', promptAr: 'هناك رحلات مغادرة في العاشرة صباحاً والثانية ظهراً كل يوم.', lines: 1,
          accept: ['How often are there departures?', 'How often are there departures at 10 a.m. and 2 p.m.?', 'How often does the boat leave?'], model: 'How often are there departures?', modelAr: 'كم مرة توجد رحلات مغادرة؟',
          explainAr: 'المسطَّر يدلّ على التكرار (every day) فنسأل بـ How often. مع There are نقدّم are: How often are there...? الجملة من حوار طلب المعلومات (الوحدة 3).' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'A few weeks ago, a woman called {to report a robbery at her house}.', promptAr: 'قبل بضعة أسابيع، اتّصلت امرأة للإبلاغ عن سرقة في بيتها.', lines: 1,
          accept: ['Why did a woman call a few weeks ago?', 'Why did the woman call a few weeks ago?', 'Why did a woman call?', 'Why did the woman call?'], model: 'Why did a woman call a few weeks ago?', modelAr: 'لماذا اتّصلت امرأة قبل بضعة أسابيع؟',
          explainAr: 'المسطَّر يبيّن الهدف (to + فعل) فنسأل بـ Why. الفعل called ماضٍ بسيط فنستخدم did ويعود الفعل إلى أصله call. الجملة من الوحدة 2.' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'reported', prompt: '“Where is the key?” my mother asked. (reported speech)', promptAr: 'سألت أمي: "أين المفتاح؟" (الكلام المنقول)', lines: 2,
          accept: ['My mother asked where the key was.', 'My mother wanted to know where the key was.', 'My mother asked me where the key was.'], model: 'My mother wanted to know where the key was.', modelAr: 'أرادت أمي أن تعرف أين المفتاح.',
          explainAr: 'نقل السؤال (الوحدة 11): نحذف علامة الاستفهام ونعيد الترتيب إلى جملة خبرية (الفاعل ثم الفعل): where the key was، ونرجع الزمن خطوة: is ← was. خطأ شائع: where was the key.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'Sua’ad is not in class today. Waleed is not in class today. (neither ... nor)', promptAr: 'سعاد ليست في الصف اليوم. وليد ليس في الصف اليوم. (neither ... nor)', lines: 2,
          accept: ['Neither Sua’ad nor Waleed is in class today.', 'Neither Suaad nor Waleed is in class today.', 'Neither Suad nor Waleed is in class today.'], modelAr: 'لا سعاد ولا وليد في الصف اليوم.',
          explainAr: 'أدوات الربط المزدوجة (الوحدة 9): neither ... nor تحمل معنى النفي، فلا نضع not بعدها. الفعل يتبع الفاعل الأقرب إليه (Waleed مفرد) فنقول is. الجملة من المراجعة 3.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Your sister asks: “Does this dress look OK?” You don’t like it. (Be tactful)', promptAr: 'تسألك أختك: "هل يبدو هذا الفستان جيداً؟" لكنه لا يعجبك. (كن لبقاً)', lines: 2,
          accept: ['Well, I think darker colours suit you better.', 'I think darker colours suit you better.', 'Well, I think darker colours suit you better. I’d go for black instead if I were you.', 'I’d go for black instead if I were you.', 'I would go for black instead if I were you.', 'I’ve seen better dresses.', 'Honestly, I’ve seen better dresses.'],
          model: 'Well, I think darker colours suit you better. I’d go for black instead if I were you.', modelAr: 'حسناً، أظنّ أن الألوان الداكنة تناسبك أكثر. لو كنتُ مكانك لاخترتُ الأسود بدلاً منه.',
          explainAr: 'اللباقة (Being tactful، الوحدة 11): نخفّف الرأي السلبي بعبارات مثل I think... suit(s) you better، أو بالفعل الناقص I’d go for... if I were you، أو I’ve seen better...، ولا نقول It’s ugly مباشرة. المثال نفسه في كتابك.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'The shop on the corner usually mends my glasses. (causative verb)', promptAr: 'المحل الذي على الزاوية يصلح نظارتي عادةً. (الفعل السببي)', lines: 2,
          accept: ['I usually have my glasses mended at the shop on the corner.', 'I usually get my glasses mended at the shop on the corner.', 'I usually have my glasses mended by the shop on the corner.', 'I usually get my glasses mended by the shop on the corner.', 'I usually have my glasses mended in the shop on the corner.'],
          model: 'I usually have my glasses mended at the shop on the corner.', modelAr: 'أُصلح نظارتي عادةً (عندهم) في المحل الذي على الزاوية.',
          explainAr: 'السببي (الوحدة 4): have/get + مفعول + التصريف الثالث. الفعل الأصلي مضارع بسيط (mends) فنقول I usually have my glasses mended. الجملة من المراجعة 1.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'Suzan ………. (keep) trying to pass her driving test but fails every time.', promptAr: 'تواصل سوزان محاولة النجاح في اختبار القيادة لكنها ترسب في كل مرة.', lines: 1,
          accept: ['keeps'], explainAr: 'fails every time تدلّ على عادة متكرّرة ← المضارع البسيط، والفاعل Suzan مفرد غائب فنضيف s: keeps. الجملة من المراجعة 1.' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'The poor bird ………. (capture) and all its efforts to escape from the trap were in vain.', promptAr: 'أُمسك الطائر المسكين وذهبت كل محاولاته للهرب من الفخ سدى.', lines: 1,
          accept: ['was captured', 'had been captured'], explainAr: 'الطائر لا يمسك نفسه فنحتاج المبني للمجهول (الوحدة 3)، و were in vain تدلّ على الماضي: was + captured (ويُقبل had been captured).' },
        { n: 35, kind: 'write', topic: 'conditional', prompt: 'If I ………. (not be) in debt, I would quit my job.', promptAr: 'لو لم أكن مَديناً لتركتُ عملي.', lines: 1,
          accept: ['weren’t', 'were not', 'wasn’t', 'was not'], explainAr: 'الجواب would quit يدلّ على الشرطية الثانية (الوحدة 7): If + ماضٍ بسيط، ومع I نفضّل were فنقول weren’t (وتُقبل wasn’t). الجملة من كتابك.' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'conditional', prompt: 'I would ring the police if …………………………..', promptAr: 'سأتّصل بالشرطة لو …', lines: 2,
          accept: ['I saw a burglar breaking into my house.', 'I saw a thief in my house.', 'someone broke into my house.', 'I saw an accident.'], model: 'I saw a burglar breaking into my house.', modelAr: 'رأيتُ لصّاً يقتحم بيتي.',
          explainAr: 'الجملة الرئيسية would ring هي جواب الشرطية الثانية (الوحدة 7)، فجملة if تأخذ الماضي البسيط (saw). المثال من كتابك.' },
        { n: 37, kind: 'write', topic: 'tense', prompt: 'By this time next year, …………………………..', promptAr: 'في مثل هذا الوقت من العام القادم، …', lines: 2,
          accept: ['I will be studying at university.', 'I will have finished secondary school.', 'I will be studying medicine.', 'I will have graduated from school.'], model: 'I will be studying at university.', modelAr: 'سأكون أدرس في الجامعة.',
          explainAr: 'By this time next year وقت في المستقبل، فنستخدم المستقبل المستمر (will be + ing) لحدث سيكون جارياً في ذلك الوقت، أو المستقبل التام (will have + تصريف ثالث) لحدث سيكتمل قبله (الوحدة 6).' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: The UN may not interfere in the domestic affairs of any country.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['لا يجوز للأمم المتحدة أن تتدخل في الشؤون الداخلية لأي دولة', 'لا يحق للأمم المتحدة التدخل في الشؤون الداخلية لأي بلد', 'لا يجوز للأمم المتحدة التدخل في الشؤون الداخلية لأي دولة'], model: 'لا يجوز للأمم المتحدة أن تتدخّل في الشؤون الداخلية لأي دولة.',
          explainAr: 'الجملة من مبادئ الأمم المتحدة (الوحدة 6). may not هنا = لا يجوز / غير مسموح، interfere in = يتدخّل في، domestic affairs = الشؤون الداخلية.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: أتمنّى لو أنني درستُ بجدّ أكبر العام الماضي.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['I wish I had studied harder last year.', 'I wish that I had studied harder last year.'],
          model: 'I wish I had studied harder last year.',
          explainAr: 'التمنّي عن الماضي (الوحدة 8): wish + الماضي التام (had studied) لأن العام الماضي انتهى. بجدّ أكبر ← harder، العام الماضي ← last year.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Healthcare in Syria nowadays.',
        topicAr: 'الرعاية الصحية في سوريا اليوم.',
        words: 80,
        points: ['What are the best ways to avoid getting sick?', 'What skills are needed to be a good doctor or nurse?', 'How will healthcare be in the future?'],
        model: 'Healthcare in Syria has improved a lot in recent years. Today healthcare isn’t just about doctors; nurses, physical therapists and technicians are all part of a large health care system. The best way to avoid getting sick is to live a healthy life. We should wash our hands, eat healthy food and keep our salt intake to a minimum. Getting enough sleep is also important. A good doctor or nurse needs both knowledge and patience. He must listen carefully to patients and treat them kindly. In the future, I think technology will play a bigger role. Clever machines will help doctors diagnose diseases, and many patients will be able to talk to their doctors online.',
        modelAr: 'تحسّنت الرعاية الصحية في سوريا كثيراً في السنوات الأخيرة. فاليوم لم تعد الرعاية الصحية تقتصر على الأطباء؛ فالممرّضون والمعالجون الفيزيائيون والفنّيون جميعهم جزء من نظام رعاية صحية كبير. أفضل طريقة لتجنّب المرض أن نعيش حياة صحية: علينا أن نغسل أيدينا ونأكل طعاماً صحياً ونقلّل الملح إلى الحد الأدنى، والنوم الكافي مهم أيضاً. يحتاج الطبيب أو الممرّض الجيد إلى المعرفة والصبر معاً، وعليه أن يصغي إلى المرضى بانتباه ويعاملهم بلطف. وفي المستقبل أظنّ أن التكنولوجيا ستؤدّي دوراً أكبر؛ فالآلات الذكية ستساعد الأطباء على تشخيص الأمراض، وسيتمكّن كثير من المرضى من التحدّث إلى أطبائهم عبر الإنترنت.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: طرق تجنّب المرض، ومهارات الطبيب أو الممرّض الجيد، ومستقبل الرعاية الصحية.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (also, both ... and, In the future, and).',
          'استخدمتُ should و must بشكل صحيح، و will للتوقّع في المستقبل.',
          'استخدمتُ كلمات من الوحدات 3 و8 و11 (healthcare, patients, diagnose, salt intake, clever machines).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
