import type { Exam } from '../../../engine/types'

// A practice Term 1 paper in the exact layout of the real paper (term1-a.ts), built only from Units 1–6.
// Passage A: Unit 1 reading "Future Career" (pages 9–10). Passage B: Unit 6 reading "History of the United Nations" (page 60).
export const term1B: Exam = {
  id: 't1-b',
  term: 1,
  title: 'Term 1 — Test (B)',
  titleAr: 'الفصل الأول — النموذج (B)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان الفصل الأول الحقيقي، مبنيّ فقط على الوحدات 1–6 من كتابك.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'Not all people have the ability to explore their future and build it with more confidence and clarity. Most studies have highlighted the role of parents as active agents in the career development of their children. Parents want their children to opt for a career they know well about, but what their children want or aspire to become can be completely different. Many parents said they had misguided their children into choosing a career of their choice. It is very important not to burden our children with unreal expectations. There are a few factors that are of great importance in the career selection process. The child’s aptitude is a mirror of his/her personality, strengths, and weaknesses. Hence, a designed aptitude test can reveal a lot of information regarding the child that can help in taking a well-informed career selection. It is very difficult to spend your life working in a field that you are not interested in. Courses leading towards a desired career should be found easily for the young to enable them to make right decisions about their future. Psychologists said that it was very easy for a child to get swayed by peer pressure into choosing a career that the majority was opting rather than the one which was best for him/her.',
        ],
        paragraphsAr: [
          'ليس لدى كل الناس القدرة على استكشاف مستقبلهم وبنائه بمزيد من الثقة والوضوح. وقد أبرزت معظم الدراسات دور الآباء بوصفهم عناصر فاعلة في التطوّر المهني لأبنائهم. يريد الآباء أن يختار أبناؤهم مهنةً يعرفونها جيداً، لكنّ ما يريده الأبناء أو يطمحون أن يصبحوه قد يكون مختلفاً تماماً. وقال كثير من الآباء إنهم ضلّلوا أبناءهم فدفعوهم إلى اختيار مهنة من اختيار الآباء أنفسهم. ومن المهم جداً ألّا نُثقل كاهل أبنائنا بتوقّعات غير واقعية. هناك عوامل قليلة ذات أهمية كبيرة في عملية اختيار المهنة. فاستعداد الطفل (قدرته الفطرية) مرآةٌ لشخصيته ونقاط قوّته وضعفه. لذلك يمكن لاختبار استعداد مُصمَّم جيداً أن يكشف كثيراً من المعلومات عن الطفل، مما يساعد على اختيار مهنة عن معرفة ودراية. ومن الصعب جداً أن تقضي حياتك تعمل في مجال لا يهمّك. وينبغي أن تكون المقرّرات الدراسية المؤدّية إلى المهنة المرغوبة متاحةً بسهولة للشباب لتمكينهم من اتخاذ قرارات صحيحة بشأن مستقبلهم. وقال علماء النفس إنه من السهل جداً أن يتأثّر الطفل بضغط الأقران فيختار المهنة التي تختارها الأغلبية بدلاً من المهنة الأنسب له.',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'What role have most studies highlighted for parents?', promptAr: 'ما الدور الذي أبرزته معظم الدراسات للآباء؟', lines: 3,
              accept: ['Most studies have highlighted the role of parents as active agents in the career development of their children.', 'Parents are active agents in the career development of their children.', 'They are active agents in the career development of their children.', 'The role of active agents in the career development of their children.', 'Active agents in the career development of their children.'],
              modelAr: 'أبرزت الدراسات دور الآباء بوصفهم عناصر فاعلة في التطوّر المهني لأبنائهم.',
              explainAr: 'الجواب في الجملة الثانية: "Most studies have highlighted the role of parents as active agents in the career development of their children". انقل الجملة وابدأ بفاعل كامل.' },
            { n: 2, kind: 'write', prompt: 'How can a designed aptitude test help in choosing a career?', promptAr: 'كيف يمكن لاختبار الاستعداد المصمَّم أن يساعد في اختيار المهنة؟', lines: 3,
              accept: ['It can reveal a lot of information regarding the child that can help in taking a well-informed career selection.', 'A designed aptitude test can reveal a lot of information regarding the child.', 'It can reveal a lot of information about the child.', 'It reveals a lot of information regarding the child that helps in taking a well-informed career selection.'],
              modelAr: 'يمكنه أن يكشف كثيراً من المعلومات عن الطفل مما يساعد على اختيار مهنة عن معرفة.',
              explainAr: 'النص: "a designed aptitude test can reveal a lot of information regarding the child that can help in taking a well-informed career selection". الكلمة المفتاحية reveal = يكشف.' },
            { n: 3, kind: 'write', prompt: 'According to psychologists, why may a child choose a career which is not the best for him/her?', promptAr: 'بحسب علماء النفس، لماذا قد يختار الطفل مهنة ليست الأفضل له؟', lines: 3,
              accept: ['Because it is very easy for a child to get swayed by peer pressure into choosing a career that the majority is opting.', 'Because he gets swayed by peer pressure.', 'Because of peer pressure.', 'Because he is swayed by peer pressure into choosing a career that the majority was opting.', 'Because it was very easy for a child to get swayed by peer pressure.'],
              modelAr: 'لأنه من السهل أن يتأثّر الطفل بضغط الأقران فيختار ما تختاره الأغلبية.',
              explainAr: 'آخر جملة: "it was very easy for a child to get swayed by peer pressure into choosing a career that the majority was opting". السؤال بـ why فنبدأ الجواب بـ Because.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'Seek to attain a goal ……..', promptAr: 'يسعى إلى تحقيق هدف', lines: 1, topic: 'vocab',
              accept: ['aspire'], modelAr: 'يطمح', explainAr: 'في النص "what their children want or aspire to become". aspire = يطمح، وهذا معناها في تمرين الكلمات المظلَّلة في الوحدة 1.' },
            { n: 5, kind: 'write', prompt: 'Natural ability or skill ……..', promptAr: 'قدرة أو مهارة فطرية', lines: 1, topic: 'vocab',
              accept: ['aptitude'], modelAr: 'استعداد / موهبة فطرية', explainAr: 'في النص "The child’s aptitude is a mirror of his/her personality". aptitude = الاستعداد أو القدرة الفطرية، ومنها aptitude test = اختبار الاستعداد.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'What children aspire to become is always the same as what their parents want.', promptAr: 'ما يطمح الأبناء أن يصبحوه هو دائماً نفس ما يريده آباؤهم.', lines: 2,
              accept: ['What children aspire to become can be completely different from what their parents want.', 'What their children want or aspire to become can be completely different.', 'What children aspire to become can be different from what their parents want.', 'What children aspire to become is not always the same as what their parents want.'],
              modelAr: 'ما يطمح الأبناء أن يصبحوه قد يكون مختلفاً تماماً عمّا يريده آباؤهم.',
              explainAr: 'النص: "what their children want or aspire to become can be completely different". الخطأ في الجملة: always the same، والصواب can be completely different.' },
            { n: 7, kind: 'write', prompt: 'It is very easy to spend your life working in a field that you are not interested in.', promptAr: 'من السهل جداً أن تقضي حياتك تعمل في مجال لا يهمّك.', lines: 2,
              accept: ['It is very difficult to spend your life working in a field that you are not interested in.', 'It is difficult to spend your life working in a field that you are not interested in.', 'It is not easy to spend your life working in a field that you are not interested in.'],
              modelAr: 'من الصعب جداً أن تقضي حياتك تعمل في مجال لا يهمّك.',
              explainAr: 'النص: "It is very difficult to spend your life working in a field that you are not interested in". نصحّح الكلمة الخاطئة easy إلى difficult.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'The United Nations was established by the Charter of the United Nations and Statute of the International Court of Justice. The Charter was signed on 26 June 1945 by the representatives of 50 countries including Syria; Poland signed on 15 October 1945. There were 51 founding members in 1945. The United Nations (UN) officially came into existence on 24 October 1945 after ratification of the Charter. The day is now celebrated each year around the world as United Nations Day. The Security Council (SC) contains five permanent members: China, France, Russian Federation, the United Kingdom, and the United States, and ten non-permanent members elected for two-year terms by the General Assembly.',
          'The United Nations (UN) was the second multipurpose international organisation established in the 20th century that was worldwide in scope and membership. Its predecessor, the League of Nations, was created by the Treaty of Versailles in 1919 and disbanded in 1946. The UN also has regional offices in Geneva, Vienna, and Nairobi. Its official languages are Arabic, Chinese, English, French, Russian, and Spanish.',
        ],
        paragraphsAr: [
          'أُسِّست الأمم المتحدة بموجب ميثاق الأمم المتحدة والنظام الأساسي لمحكمة العدل الدولية. وقد وُقِّع الميثاق في 26 حزيران 1945 من قِبل ممثّلي 50 دولة من بينها سوريا، ووقّعت بولندا في 15 تشرين الأول 1945. وكان هناك 51 عضواً مؤسِّساً عام 1945. وبدأت الأمم المتحدة وجودها رسمياً في 24 تشرين الأول 1945 بعد التصديق على الميثاق. ويُحتفَل بهذا اليوم الآن كل عام في أنحاء العالم على أنه يوم الأمم المتحدة. ويضمّ مجلس الأمن خمسة أعضاء دائمين: الصين وفرنسا والاتحاد الروسي والمملكة المتحدة والولايات المتحدة، وعشرة أعضاء غير دائمين تنتخبهم الجمعية العامة لفترات مدّة كلٍّ منها سنتان.',
          'كانت الأمم المتحدة ثاني منظمة دولية متعدّدة الأغراض تُنشأ في القرن العشرين وتكون عالمية في نطاقها وعضويتها. أما سابقتها، عصبة الأمم، فقد أُنشئت بموجب معاهدة فرساي عام 1919 وحُلَّت عام 1946. وللأمم المتحدة أيضاً مكاتب إقليمية في جنيف وفيينا ونيروبي. ولغاتها الرسمية هي العربية والصينية والإنجليزية والفرنسية والروسية والإسبانية.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'The Charter was signed on 26 June 1945 by the representatives of ……. countries.', promptAr: 'وُقِّع الميثاق في 26 حزيران 1945 من قِبل ممثّلي ___ دولة.', options: ['51', '50', '15', '24'], answer: 1,
              explainAr: 'النص: "signed on 26 June 1945 by the representatives of 50 countries". انتبه: 51 هو عدد الأعضاء المؤسِّسين بعد توقيع بولندا، و15 و24 تاريخان في تشرين الأول.' },
            { n: 9, kind: 'mcq', prompt: 'The United Nations officially came into existence ……..', promptAr: 'بدأت الأمم المتحدة وجودها رسمياً ___.', options: ['on 26 June 1945', 'on 15 October 1945', 'on 24 October 1945', 'in 1919'], answer: 2,
              explainAr: 'النص: "officially came into existence on 24 October 1945 after ratification of the Charter". أما "on 26 June 1945" فهو تاريخ توقيع الميثاق، و"on 15 October 1945" تاريخ توقيع بولندا، و"in 1919" سنة إنشاء عصبة الأمم.' },
            { n: 10, kind: 'mcq', prompt: 'The League of Nations was ……..', promptAr: 'كانت عصبة الأمم ___.', options: ['the predecessor of the UN', 'one of the regional offices of the UN', 'a permanent member of the Security Council', 'created in 1946'], answer: 0,
              explainAr: 'النص: "Its predecessor, the League of Nations, was created by the Treaty of Versailles in 1919 and disbanded in 1946". predecessor = السابق (ما وُجد قبل غيره). وقد حُلَّت عام 1946 ولم تُنشأ فيه.' },
            { n: 11, kind: 'mcq', prompt: 'Making something valid by confirming it is ……..', promptAr: 'جعل الشيء نافذاً بتأكيده هو ___.', options: ['charter', 'disparity', 'devastation', 'ratification'], answer: 3, topic: 'vocab',
              explainAr: 'ratification = التصديق، وهي في النص "after ratification of the Charter". charter = ميثاق، disparity = تفاوت غير عادل، devastation = دمار (كلها من تمرين الكلمات في الوحدة 6).' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'The ten non-permanent members of the Security Council are elected ……………………', promptAr: 'يُنتخب الأعضاء العشرة غير الدائمين في مجلس الأمن ……', lines: 2,
              accept: ['for two-year terms by the General Assembly', 'by the General Assembly for two-year terms', 'for two-year terms', 'by the General Assembly'],
              modelAr: 'لفترات مدّتها سنتان من قِبل الجمعية العامة.',
              explainAr: 'النص: "ten non-permanent members elected for two-year terms by the General Assembly".' },
            { n: 13, kind: 'write', prompt: 'The UN has regional offices in ……………………', promptAr: 'للأمم المتحدة مكاتب إقليمية في ……', lines: 1,
              accept: ['Geneva, Vienna, and Nairobi', 'Geneva, Vienna and Nairobi'],
              modelAr: 'جنيف وفيينا ونيروبي.',
              explainAr: 'النص: "The UN also has regional offices in Geneva, Vienna, and Nairobi". لا تخلط بينها وبين اللغات الرسمية.' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'A big part of my job is ……… the latest research in medical technology.', promptAr: 'جزء كبير من عملي هو ___ آخر الأبحاث في التكنولوجيا الطبية.', options: ['fitting in with', 'running into', 'keeping up with', 'reaching out to'], answer: 2,
          explainAr: 'keep up with = يبقى مطّلعاً على آخر المستجدّات، والجملة نفسها في كتابك (الوحدة 1). fit in with = ينسجم مع مجموعة، run into = يصادف مشكلة، reach out to = يمدّ يد العون لـ.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'The woman ……… car was stolen called the police.', promptAr: 'المرأة ___ سُرقت سيارتها اتصلت بالشرطة.', options: ['who', 'whose', 'which', 'where'], answer: 1,
          explainAr: 'بعد الفراغ اسم (car) يملكه الشخص (The woman)، فنستخدم whose للملكية (الوحدة 5). "who" للعاقل ويليه فعل، "which" لغير العاقل، "where" للمكان.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'Our lawyer is very good and he does everything ………', promptAr: 'محامينا جيد جداً ويفعل كل شيء ___.', options: ['beating around the bush', 'an act of God', 'breaking the law', 'by the book'], answer: 3,
          explainAr: 'by the book = تماماً كما تقول القواعد (تعابير القانون في الوحدة 5)، والجملة من كتابك. beat around the bush = يراوغ ولا يدخل في الموضوع، an act of God = قضاء وقدر، break the law = يخالف القانون.' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'The practice of treating someone less fairly than others is called ………', promptAr: 'ممارسة معاملة شخص ما بإنصاف أقلّ من غيره تُسمّى ___.', options: ['discrimination', 'guarantee', 'restraints', 'legislation'], answer: 0,
          explainAr: 'discrimination = التمييز، وهذا تعريفها في تمرين الكلمات في الوحدة 5. guarantee = ضمان، restraints = قيود، legislation = تشريع.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'Which word has the same pronunciation as “weigh”?', promptAr: 'أيّ كلمة لها نفس لفظ "weigh"؟', options: ['why', 'weight', 'way', 'wait'], answer: 2,
          explainAr: 'الكلمات المتجانسة لفظاً (homophones، الوحدة 1) تُلفظ بالطريقة نفسها وتختلف في المعنى والتهجئة: "way" و"weigh" تُلفظان /weɪ/. أما "weight" و"wait" فتنتهيان بصوت /t/، و"why" تُلفظ /waɪ/.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'The police managed to ……… the bomb before it exploded.', promptAr: 'تمكّنت الشرطة من ___ القنبلة قبل أن تنفجر.', options: ['misunderstand', 'deactivate', 'discourage', 'disagree'], answer: 1,
          explainAr: 'السابقة de- تعطي معنى معاكساً (الوحدة 6): activate = يشغّل، deactivate = يعطّل. المعنى يناسب القنبلة. misunderstand = يسيء الفهم، discourage = يُحبط، disagree = يختلف في الرأي.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'Take your hands ……… your pockets and help me!', promptAr: 'أخرج يديك ___ جيبيك وساعدني!', options: ['into', 'onto', 'off', 'out of'], answer: 3,
          explainAr: 'حروف جر الحركة (الوحدة 4): out of = خروج من داخل شيء (الجيب)، وهو عكس into. الجملة من كتابك. "off" عكس onto (عن سطح شيء)، و"onto" إلى سطح شيء.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: 'Choose the word whose final sound is voiceless:', promptAr: 'اختر الكلمة التي صوتها الأخير مهموس:', options: ['path', 'answer', 'young', 'judge'], answer: 0,
          explainAr: 'الصوت المهموس لا تهتزّ معه الأوتار الصوتية (الوحدة 5). "path" تنتهي بصوت /θ/ المهموس. أما "answer" و"young" و"judge" فتنتهي بأصوات مجهورة (/r/ أو صوت علّة، /ŋ/، /dʒ/).' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Everyone endeavours a great deal to make dreams a ……… .', promptAr: 'يبذل كل شخص جهداً كبيراً ليجعل الأحلام ___.', options: ['real', 'reality', 'realise', 'realistic'], answer: 1,
          explainAr: 'بعد أداة النكرة a نحتاج اسماً: reality = حقيقة/واقع (عائلة الكلمة real، الوحدة 1). "real" و"realistic" صفتان، و"realise" فعل.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'I got ……… writing when I was a kid, and I just never stopped loving it.', promptAr: 'بدأ اهتمامي ___ الكتابة عندما كنت طفلاً، ولم أتوقّف قطّ عن حبّها.', lines: 1,
          accept: ['into'], explainAr: 'الفعل المركّب get into = يبدأ الاهتمام بشيء (الوحدة 1)، والجملة من كتابك.' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'Lattakia, ……… I spent my last holiday, is a wonderful city.', promptAr: 'اللاذقية، ___ قضيت عطلتي الأخيرة، مدينة رائعة.', lines: 1,
          accept: ['where'], explainAr: 'بعد اسم مكان (Lattakia) تليه جملة كاملة (I spent my last holiday) نستخدم ضمير الوصل where (الوحدة 5).' },
        { n: 25, kind: 'write', topic: 'tense', prompt: 'By the time you get home, I will ……… cleaned the house from top to bottom.', promptAr: 'بحلول الوقت الذي تصل فيه إلى البيت، سأكون ___ نظّفت البيت من أعلاه إلى أسفله.', lines: 1,
          accept: ['have'], explainAr: 'المستقبل التام will have + التصريف الثالث (cleaned) لحدث سيكتمل قبل وقت في المستقبل، ويأتي كثيراً مع By the time (الوحدة 6).' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'The UN has regional offices {in Geneva, Vienna and Nairobi}.', promptAr: 'للأمم المتحدة مكاتب إقليمية في جنيف وفيينا ونيروبي.', lines: 1,
          accept: ['Where does the UN have regional offices?', 'Where does the United Nations have regional offices?', 'Where are the regional offices of the UN?'], modelAr: 'أين توجد مكاتب إقليمية للأمم المتحدة؟',
          explainAr: 'المسطَّر يدل على مكان فنسأل بـ Where. الفعل has مضارع بسيط مع مفرد، فنستخدم does ويعود الفعل إلى أصله have.' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'I have been using a computer {for three years}.', promptAr: 'أستخدم الحاسوب منذ ثلاث سنوات.', lines: 1,
          accept: ['How long have you been using a computer?'], modelAr: 'منذ متى تستخدم الحاسوب؟',
          explainAr: 'المسطَّر مدّة زمنية (for three years) فنسأل بـ How long. الفعل مضارع تام مستمر، فنقدّم have على الفاعل: How long have you been using...؟' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'The Security Council contains {five} permanent members.', promptAr: 'يضمّ مجلس الأمن خمسة أعضاء دائمين.', lines: 1,
          accept: ['How many permanent members does the Security Council contain?', 'How many permanent members does the Security Council have?'], modelAr: 'كم عضواً دائماً يضمّ مجلس الأمن؟',
          explainAr: 'المسطَّر عدد لاسم جمع معدود (members) فنسأل بـ How many + الاسم. الفعل contains مضارع بسيط مع مفرد، فنستخدم does ويعود الفعل إلى أصله contain.' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'grammar', prompt: 'The man worked in a printing company. He visited me last night. (Join using a relative pronoun)', promptAr: 'الرجل كان يعمل في شركة طباعة. زارني ليلة أمس. (اربط باستخدام ضمير وصل)', lines: 2,
          accept: ['The man who worked in a printing company visited me last night.', 'The man that worked in a printing company visited me last night.'], modelAr: 'الرجل الذي كان يعمل في شركة طباعة زارني ليلة أمس.',
          explainAr: 'ضمير الوصل للعاقل who (أو that) يحلّ محلّ He، ونضع الجملة الموصولة بعد الاسم الذي تصفه مباشرة (The man). الجملة من كتابك (الوحدة 5).' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'The organizers will exhibit the paintings till the end of the month. (passive voice)', promptAr: 'سيعرض المنظّمون اللوحات حتى نهاية الشهر. (المبني للمجهول)', lines: 2,
          accept: ['The paintings will be exhibited till the end of the month.', 'The paintings will be exhibited by the organizers till the end of the month.', 'The paintings will be exhibited until the end of the month.'], modelAr: 'ستُعرض اللوحات حتى نهاية الشهر.',
          explainAr: 'المبني للمجهول في المستقبل: will be + التصريف الثالث (exhibited). نبدأ بالمفعول (The paintings) ويمكن حذف الفاعل. الجملة من تمارين الوحدة 3.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Your friend says: “Your skiing has improved tremendously. You’re really a future champion.” (Respond modestly)', promptAr: 'يقول صديقك: "لقد تحسّن تزلّجك كثيراً. أنت حقاً بطل المستقبل." (ردّ بتواضع)', lines: 2,
          accept: ['Oh, it was nothing really.', 'That is very kind of you.', 'You are embarrassing me.', 'Oh, you are exaggerating.', 'I have just been very lucky.', 'That is very kind of you, but I have just been very lucky.', 'Oh, it was nothing really, nothing at all.'],
          model: 'That’s very kind of you, but I’ve just been very lucky.', modelAr: 'هذا لطف منك، لكنني كنت محظوظاً فقط.',
          explainAr: 'تعابير التواضع من الوحدة 6 (Everyday English): Oh, it was nothing really / That’s very kind of you / You’re embarrassing me / Oh, you’re exaggerating / I’ve just been very lucky.' },
        { n: 32, kind: 'write', topic: 'tense', prompt: 'David intends to get up early tomorrow. (Use: going to)', promptAr: 'ينوي ديفيد أن يستيقظ باكراً غداً. (استخدم going to)', lines: 2,
          accept: ['David is going to get up early tomorrow.', 'I am going to get up early tomorrow.'], modelAr: 'سيستيقظ ديفيد باكراً غداً (ينوي ذلك).',
          explainAr: 'نستخدم be going to + الفعل للتعبير عن نيّة أو خطة مقرَّرة مسبقاً (intends). مع David نقول is going to (الوحدة 6).' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'tense', prompt: 'Look! The sun ……… (shine) now.', promptAr: 'انظر! الشمس ساطعة الآن.', lines: 1,
          accept: ['is shining', "'s shining"], explainAr: 'Look! و now تدلّان على حدث يجري لحظة الكلام، فنستخدم المضارع المستمر: is + shining (نحذف e من shine قبل ing).' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'I ……… (not / see) Jack for months. How is he?', promptAr: 'لم أرَ جاك منذ أشهر. كيف حاله؟', lines: 1,
          accept: ['have not seen', "haven't seen"], explainAr: 'for months تدلّ على مدّة بدأت في الماضي وما زالت حتى الآن، فنستخدم المضارع التام المنفي: haven’t + seen (التصريف الثالث لـ see). الجملة من الوحدة 1.' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'At this time tomorrow, we ……… (travel) to Aleppo.', promptAr: 'في مثل هذا الوقت غداً سنكون مسافرين إلى حلب.', lines: 1,
          accept: ['will be travelling', 'will be traveling', "'ll be travelling", 'shall be travelling'], explainAr: 'At this time tomorrow تدلّ على حدث سيكون جارياً في لحظة محدّدة في المستقبل، فنستخدم المستقبل المستمر: will be + travelling (الوحدة 6).' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'tense', prompt: 'By the time my parents get home, …………………………..', promptAr: 'بحلول الوقت الذي يصل فيه والداي إلى البيت، …', lines: 2,
          accept: ['I will have finished my homework.', 'I will have cleaned the house.', 'I will have cooked dinner.', 'I will have done my homework.'], model: 'I will have finished my homework.', modelAr: 'سأكون قد أنهيت واجبي.',
          explainAr: 'By the time + مضارع بسيط (get) للمستقبل ← المستقبل التام في الجملة الأخرى: will have + التصريف الثالث (حدث سيكتمل قبل ذلك الوقت، الوحدة 6).' },
        { n: 37, kind: 'write', topic: 'conditional', prompt: 'If I were you, …………………………..', promptAr: 'لو كنتُ مكانك، …', lines: 2,
          accept: ['I would study harder.', 'I would stop smoking.', 'I would see a doctor.', 'I would take the job.', 'I would practise English every day.'], model: 'I would study harder.', modelAr: 'لدرستُ بجدّ أكبر.',
          explainAr: 'If I were you تعبير لتقديم النصيحة (الوحدة 1، Everyday English)، ويليه would + الفعل في المصدر: I would ....' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: Countries must try to settle their differences by peaceful means.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['يجب على الدول أن تحاول تسوية خلافاتها بالطرق السلمية', 'على الدول أن تحاول حل خلافاتها بالوسائل السلمية', 'يجب أن تحاول الدول حل خلافاتها بطرق سلمية'], model: 'يجب على الدول أن تحاول تسوية خلافاتها بالوسائل السلمية.',
          explainAr: 'الجملة من مبادئ الأمم المتحدة في كتابك (الوحدة 6). must = يجب، settle their differences = تسوية خلافاتها، by peaceful means = بالوسائل السلمية.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: يجب أن يساعد الآباء أبناءهم على اختيار مهنتهم المستقبلية.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['Parents should help their children choose their future career.', 'Parents should help their children to choose their future career.', 'Parents must help their children choose their future career.', 'Parents must help their children to choose their future career.', 'Parents have to help their children choose their future career.', 'Parents should help their children choose their future job.'],
          model: 'Parents should help their children choose their future career.',
          explainAr: 'يجب ← should (أو must)، الآباء ← Parents، يساعد ... على ← help + مفعول + (to) + فعل، مهنتهم المستقبلية ← their future career (من نص الوحدة 1).' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'The job you want after graduation.',
        topicAr: 'المهنة التي تريدها بعد التخرّج.',
        words: 80,
        points: ['What is the job and why do you want it?', 'What does the job require?', 'What challenges do you expect to face?'],
        model: 'After graduation, I aspire to become a civil engineer. I have always been interested in buildings and bridges, and my teachers say that I have an aptitude for mathematics and physics. This job requires a university degree, hard work and good teamwork skills. I will also need to keep up with the latest technology in my field. The remuneration is good, but money is not my main motivation; I want a job that allows me to contribute to society. Of course, I expect to face some challenges. I may run into difficult problems at work, and I will have to fit in with new workmates. However, I am sure that I will follow my dream through.',
        modelAr: 'بعد التخرّج أطمح أن أصبح مهندساً مدنياً. لطالما اهتممت بالأبنية والجسور، ويقول معلّميّ إن لديّ استعداداً للرياضيات والفيزياء. تتطلّب هذه المهنة شهادة جامعية وعملاً جادّاً ومهارات جيدة في العمل ضمن فريق، وسأحتاج أيضاً إلى متابعة أحدث التقنيات في مجالي. الأجر جيد، لكنّ المال ليس دافعي الرئيسي؛ فأنا أريد عملاً يسمح لي بالمساهمة في خدمة المجتمع. بالطبع أتوقّع أن أواجه بعض التحدّيات؛ فقد أصادف مشكلات صعبة في العمل، وسيكون عليّ أن أنسجم مع زملاء عمل جدد. ومع ذلك فأنا متأكّد أنني سأتابع حلمي حتى النهاية.',
        checklistAr: [
          'أجبتُ عن النقاط الثلاث: ما المهنة ولماذا أريدها، وما تتطلّبه، وما التحدّيات المتوقّعة.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات ربط (and, but, also, Of course, However).',
          'استخدمتُ الأزمنة بشكل صحيح (المضارع التام have always been، والمستقبل will / may للتوقّعات).',
          'استخدمتُ كلمات الوحدة 1 (aspire, aptitude, remuneration, keep up with, fit in with, run into).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
