import type { Exam } from '../../../engine/types'

// A final Baccalaureate practice paper in the exact layout of the real paper (term1-a.ts), covering the whole book (Units 1–12).
// Passage A: Unit 11 reading "Artificial Intelligence" (page 109), second part: from "However, AI technologies…" to the end
//   (paper B uses the text up to "…touch nearly all the industries").
// Passage B: Unit 7 reading "Microorganisms" (page 67), its last paragraphs on how viruses and bacteria cause infections
//   (paper A uses "Most bacteria aren’t harmful…"; Unit 7 prints no other prose long enough, so the paragraph starting
//   "As the names suggest" is shared with paper A; the items here ask about different sentences).
export const term2D: Exam = {
  id: 't2-d',
  term: 2,
  title: 'Baccalaureate — Final Test (D)',
  titleAr: 'نموذج البكالوريا النهائي (D)',
  minutes: 150,
  totalMarks: 300,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان البكالوريا الحقيقي، يغطّي الكتاب كاملاً (الوحدات 1–12).',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text, then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 42,
      passage: {
        paragraphs: [
          'However, AI technologies are still limited to very specific applications. One of the AI limitations is the lack of "common sense"- the power to judge information beyond its acquired knowledge. AI is also limited in terms of emotional intelligence. Moreover, AI can only detect basic human emotional states such as anger, joy, sadness, stress, pain, fear, and neutrality.',
          'Emotional intelligence is one of the next hurdles to higher levels of personalisation. Rational and harmonic interactions are required between application-specific projects and research ideas to sustain the progress of AI.',
          'There are also fears about the impact of technology on our society. Such fears should not hinder the progress of AI, but motivate the development of a systematic framework on which future AI will flourish, so it is quite important to distinguish science fiction from practical reality. Despite the common belief that machines are man-made products, many think of them as the new controllers of our near future!',
        ],
        paragraphsAr: [
          'ومع ذلك، ما تزال تقنيات الذكاء الاصطناعي مقتصرة على تطبيقات محدّدة جداً. ومن حدود الذكاء الاصطناعي افتقاره إلى "الحسّ السليم"، أي القدرة على الحكم على المعلومات بما يتجاوز المعرفة التي اكتسبها. كما أن الذكاء الاصطناعي محدود من حيث الذكاء العاطفي. علاوة على ذلك، لا يستطيع الذكاء الاصطناعي إلا اكتشاف الحالات العاطفية الأساسية لدى الإنسان مثل الغضب والفرح والحزن والتوتر والألم والخوف والحياد.',
          'والذكاء العاطفي هو إحدى العقبات القادمة أمام الوصول إلى مستويات أعلى من التخصيص (مراعاة خصوصية كل شخص). ويتطلّب استمرار تقدّم الذكاء الاصطناعي تفاعلات عقلانية ومتناغمة بين المشاريع التطبيقية المحدّدة والأفكار البحثية.',
          'وهناك أيضاً مخاوف من تأثير التكنولوجيا في مجتمعنا. وينبغي ألّا تعيق هذه المخاوف تقدّم الذكاء الاصطناعي، بل أن تحفّز على تطوير إطار منهجي يزدهر عليه الذكاء الاصطناعي في المستقبل، لذلك من المهم جداً التمييز بين الخيال العلمي والواقع العملي. وعلى الرغم من الاعتقاد الشائع بأن الآلات منتجات من صنع الإنسان، فإن كثيرين يرون فيها المتحكّمين الجدد في مستقبلنا القريب!',
        ],
      },
      groups: [
        {
          title: 'Answer the following questions:',
          titleAr: 'أجب عن الأسئلة التالية:',
          marks: 18,
          questions: [
            { n: 1, kind: 'write', prompt: 'What is meant by “common sense” in the text?', promptAr: 'ما المقصود بـ "الحسّ السليم" في النص؟', lines: 2,
              accept: ['It is the power to judge information beyond its acquired knowledge.', 'Common sense is the power to judge information beyond its acquired knowledge.', 'The power to judge information beyond its acquired knowledge.'],
              modelAr: 'هو القدرة على الحكم على المعلومات بما يتجاوز المعرفة المكتسبة.',
              explainAr: 'الجملة الثانية: "the lack of "common sense"- the power to judge information beyond its acquired knowledge". الشرطة (-) بعد common sense تشرح معناه.' },
            { n: 2, kind: 'write', prompt: 'What basic human emotional states can AI detect?', promptAr: 'ما الحالات العاطفية الأساسية لدى الإنسان التي يستطيع الذكاء الاصطناعي اكتشافها؟', lines: 2,
              accept: ['AI can only detect anger, joy, sadness, stress, pain, fear, and neutrality.', 'It can detect basic human emotional states such as anger, joy, sadness, stress, pain, fear, and neutrality.', 'Anger, joy, sadness, stress, pain, fear, and neutrality.'],
              modelAr: 'يستطيع اكتشاف الغضب والفرح والحزن والتوتر والألم والخوف والحياد فقط.',
              explainAr: 'آخر جملة في الفقرة الأولى: "AI can only detect basic human emotional states such as anger, joy, sadness, stress, pain, fear, and neutrality". انقل القائمة كاملة.' },
            { n: 3, kind: 'write', prompt: 'What is required to sustain the progress of AI?', promptAr: 'ما المطلوب لاستمرار تقدّم الذكاء الاصطناعي؟', lines: 3,
              accept: ['Rational and harmonic interactions are required between application-specific projects and research ideas.', 'Rational and harmonic interactions between application-specific projects and research ideas.', 'Rational and harmonic interactions are required between application-specific projects and research ideas to sustain the progress of AI.'],
              modelAr: 'تفاعلات عقلانية ومتناغمة بين المشاريع التطبيقية المحدّدة والأفكار البحثية.',
              explainAr: 'الفقرة الثانية: "Rational and harmonic interactions are required between application-specific projects and research ideas to sustain the progress of AI". sustain = يحافظ على استمرار الشيء.' },
          ],
        },
        {
          title: 'Find words in the text which mean the following:',
          titleAr: 'جد في النص كلمات تعني ما يلي:',
          marks: 12,
          questions: [
            { n: 4, kind: 'write', prompt: 'To make it difficult for somebody to do something ……..', promptAr: 'أن يجعل القيام بشيء ما صعباً على شخص ما', lines: 1, topic: 'vocab',
              accept: ['hinder'], modelAr: 'يعيق', explainAr: 'في الفقرة الأخيرة: "Such fears should not hinder the progress of AI" — أي يجب ألّا تعيق المخاوف تقدّمه. وهذا تعريف hinder في تمرين الكلمات في الوحدة 11.' },
            { n: 5, kind: 'write', prompt: 'The state of not supporting either side in a disagreement, competition or war ……..', promptAr: 'حالة عدم تأييد أيّ من الطرفين في خلاف أو منافسة أو حرب', lines: 1, topic: 'vocab',
              accept: ['neutrality'], modelAr: 'الحياد', explainAr: 'في آخر الفقرة الأولى: "anger, joy, sadness, stress, pain, fear, and neutrality". neutrality = الحياد، من الصفة neutral، وهذا تعريفها في تمرين الكلمات في الوحدة 11.' },
          ],
        },
        {
          title: 'Rewrite these sentences about the text to correct the information:',
          titleAr: 'أعد كتابة هذه الجمل عن النص لتصحيح المعلومات:',
          marks: 12,
          questions: [
            { n: 6, kind: 'write', prompt: 'AI technologies can now be used in all kinds of applications.', promptAr: 'يمكن الآن استخدام تقنيات الذكاء الاصطناعي في جميع أنواع التطبيقات.', lines: 2,
              accept: ['AI technologies are still limited to very specific applications.', 'AI technologies can only be used in very specific applications.'],
              modelAr: 'ما تزال تقنيات الذكاء الاصطناعي مقتصرة على تطبيقات محدّدة جداً.',
              explainAr: 'الجملة الأولى: "However, AI technologies are still limited to very specific applications". الخطأ في all kinds of.' },
            { n: 7, kind: 'write', prompt: 'Fears about the impact of technology should stop the progress of AI.', promptAr: 'ينبغي أن توقف المخاوف من تأثير التكنولوجيا تقدّمَ الذكاء الاصطناعي.', lines: 2,
              accept: ['Such fears should not hinder the progress of AI, but motivate the development of a systematic framework on which future AI will flourish.', 'Fears about the impact of technology should not hinder the progress of AI.', 'Such fears should not hinder the progress of AI.', 'Fears about the impact of technology should not stop the progress of AI.', 'Fears about the impact of technology should motivate the development of a systematic framework on which future AI will flourish.'],
              modelAr: 'ينبغي ألّا تعيق هذه المخاوف تقدّم الذكاء الاصطناعي، بل أن تحفّز على تطوير إطار منهجي يزدهر عليه في المستقبل.',
              explainAr: 'النص: "Such fears should not hinder the progress of AI, but motivate the development of a systematic framework...". فالمخاوف يجب أن تكون دافعاً لا عائقاً.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 36,
      passage: {
        paragraphs: [
          'Viruses and bacteria differ in how they cause infections. As the names suggest, viruses cause viral infections, whereas bacteria cause bacterial infections. Viruses infect a host cell and then multiply by the thousands, leaving the host and infecting other cells of the body. Diseases caused by a viral infection include influenza, common cold, flu, AIDS and COVID - 19. Bacteria, on the other hand, have a more varied operation and will often infect when the right opportunity arises. Bacterial infections include pneumonia, strep throat, ear infection and food poisoning.',
          'In fact, it is very important to know whether bacteria or viruses cause an infection because the treatments differ. It can be very difficult to know what causes an infection because viral and bacterial infections can cause similar symptoms. Doctors need a sample of your urine, blood or swab from your nose or throat to see what infection you have.',
        ],
        paragraphsAr: [
          'تختلف الفيروسات والبكتيريا في طريقة تسبيبها للعدوى. وكما يوحي الاسمان، تسبّب الفيروسات عدوى فيروسية، بينما تسبّب البكتيريا عدوى بكتيرية. تصيب الفيروسات خلية مضيفة ثم تتكاثر بالآلاف، فتغادر المضيف وتصيب خلايا أخرى في الجسم. ومن الأمراض التي تسبّبها العدوى الفيروسية: الإنفلونزا، والزكام، والرشح، والإيدز، وكوفيد-19. أما البكتيريا، من ناحية أخرى، فلها طريقة عمل أكثر تنوّعاً، وكثيراً ما تُحدث العدوى عندما تسنح الفرصة المناسبة. ومن أنواع العدوى البكتيرية: ذات الرئة، والتهاب الحلق العقدي، والتهاب الأذن، والتسمّم الغذائي.',
          'في الحقيقة، من المهم جداً معرفة ما إذا كانت البكتيريا أو الفيروسات هي التي تسبّب العدوى لأن العلاجات تختلف. وقد يكون من الصعب جداً معرفة سبب العدوى لأن العدوى الفيروسية والبكتيرية قد تسبّبان أعراضاً متشابهة. ويحتاج الأطباء إلى عيّنة من البول أو الدم أو مسحة من الأنف أو الحلق لمعرفة نوع العدوى التي لديك.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer A, B, C or D:',
          titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
          marks: 24,
          questions: [
            { n: 8, kind: 'mcq', prompt: 'The word “whereas” in the text is closest in meaning to ……..', promptAr: 'كلمة "whereas" في النص أقرب في معناها إلى ……..', options: ['because', 'while', 'so', 'unless'], answer: 1, topic: 'vocab',
              explainAr: 'whereas = بينما، وتربط بين أمرين متقابلين: "viruses cause viral infections, whereas bacteria cause bacterial infections"، ومثلها while. because للسبب، so للنتيجة، unless = إلّا إذا.' },
            { n: 9, kind: 'mcq', prompt: 'Which of the following is a bacterial infection?', promptAr: 'أيّ مما يلي عدوى بكتيرية؟', options: ['influenza', 'AIDS', 'common cold', 'strep throat'], answer: 3,
              explainAr: 'النص: "Bacterial infections include pneumonia, strep throat, ear infection and food poisoning". أما influenza و AIDS و common cold فهي أمراض فيروسية مذكورة في الجملة الخاصة بالعدوى الفيروسية.' },
            { n: 10, kind: 'mcq', prompt: 'It can be very difficult to know what causes an infection because ……..', promptAr: 'قد يكون من الصعب جداً معرفة سبب العدوى لأن ……..', options: ['viral and bacterial infections can cause similar symptoms', 'viruses and bacteria are the same thing', 'doctors never take samples', 'the treatments are always the same'], answer: 0,
              explainAr: 'النص: "It can be very difficult to know what causes an infection because viral and bacterial infections can cause similar symptoms". وانتبه: النص يقول إن العلاجات تختلف (the treatments differ) لا أنها متشابهة.' },
            { n: 11, kind: 'mcq', prompt: 'A small amount of a substance that is taken from someone’s body in order to test it is ……..', promptAr: 'كمية صغيرة من مادة تؤخذ من جسم شخص ما لفحصها هي ……..', options: ['symptom', 'gut', 'swab', 'urine'], answer: 2, topic: 'vocab',
              explainAr: 'swab = مسحة (عيّنة تؤخذ من الأنف أو الحلق)، وهذا تعريفها في تمرين الكلمات في الوحدة 7، وهي في النص "swab from your nose or throat". symptom = عَرَض، gut = الأمعاء، urine = البول.' },
          ],
        },
        {
          title: 'Complete the following sentences with information from the text:',
          titleAr: 'أكمل الجمل التالية بمعلومات من النص:',
          marks: 12,
          questions: [
            { n: 12, kind: 'write', prompt: 'It is very important to know whether bacteria or viruses cause an infection because ……………………', promptAr: 'من المهم جداً معرفة ما إذا كانت البكتيريا أو الفيروسات هي التي تسبّب العدوى لأن ……', lines: 1,
              accept: ['the treatments differ', 'the treatments are different'], modelAr: 'العلاجات تختلف.',
              explainAr: 'النص: "it is very important to know whether bacteria or viruses cause an infection because the treatments differ". وهي نفسها جملة الإكمال في كتابك.' },
            { n: 13, kind: 'write', prompt: 'Bacteria have a more varied operation and will often infect ……………………', promptAr: 'للبكتيريا طريقة عمل أكثر تنوّعاً، وكثيراً ما تُحدث العدوى ……', lines: 1,
              accept: ['when the right opportunity arises'], modelAr: 'عندما تسنح الفرصة المناسبة.',
              explainAr: 'النص: "Bacteria, on the other hand, have a more varied operation and will often infect when the right opportunity arises". arise = تنشأ/تسنح.' },
          ],
        },
      ],
    },
    {
      letter: 'III',
      title: 'Choose the correct answer A, B, C or D:',
      titleAr: 'اختر الإجابة الصحيحة A أو B أو C أو D:',
      marks: 54,
      questions: [
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'This harsh environment is going to ……… at this concrete over time.', promptAr: 'ستعمل هذه البيئة القاسية على ___ هذا الإسمنت مع مرور الوقت.', options: ['check over', 'jack up', 'pull down', 'eat away'], answer: 3,
          explainAr: 'eat away at = يتآكل تدريجياً (to erode or corrode)، من الأفعال المركّبة في الوحدة 4، والجملة من كتابك. check over = يفحص بحثاً عن العيوب، jack up = يرفع بالرافعة، pull down = يهدم.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'February 7 is the day ……… I met my best friend.', promptAr: '7 شباط هو اليوم ___ قابلتُ فيه أعزّ أصدقائي.', options: ['which', 'when', 'who', 'whose'], answer: 1,
          explainAr: 'بعد اسم يدل على زمن (the day) تليه جملة كاملة (I met my best friend) نستخدم when، كما في المراجعة الثانية. which تحتاج جملة ينقصها مفعول أو فاعل، who للأشخاص، whose للملكية.' },
        { n: 16, kind: 'mcq', topic: 'vocab', prompt: 'Writing long essays on uninteresting topics is ……….', promptAr: 'كتابة مقالات طويلة عن مواضيع غير ممتعة ___.', options: ['a pain in the neck', 'on the mend', 'by the book', 'on a roll'], answer: 0,
          explainAr: 'a pain in the neck = شيء مزعج جداً (تعابير الجسم، الوحدة 8)، والجملة من كتابك. on the mend = يتماثل للشفاء (الوحدة 3)، by the book = حسب القواعد (الوحدة 5)، on a roll = في سلسلة نجاحات (الوحدة 2).' },
        { n: 17, kind: 'mcq', topic: 'vocab', prompt: 'A new plan for achieving a particular purpose is ……….', promptAr: 'الخطة الجديدة لتحقيق غرض معيّن هي ___.', options: ['consultation', 'liability', 'initiative', 'novelty'], answer: 2,
          explainAr: 'initiative = مبادرة، وهذا تعريفها في تمرين كلمات نص الحكومة الإلكترونية (الوحدة 12). consultation = التشاور، liability = المسؤولية القانونية، novelty = الجِدّة.' },
        { n: 18, kind: 'mcq', topic: 'pronunciation', prompt: 'In which word is the letter “l” silent?', promptAr: 'في أيّ كلمة يكون حرف "l" صامتاً (لا يُلفظ)؟', options: ['cold', 'yolk', 'milk', 'film'], answer: 1,
          explainAr: 'الحروف الصامتة (الوحدة 7): حرف l لا يُلفظ في yolk، كما في calm و talk و should و half. أما في cold و milk و film فحرف l يُلفظ.' },
        { n: 19, kind: 'mcq', topic: 'vocab', prompt: 'To change food you have just eaten into substances that your body can use is to ……….', promptAr: 'تحويل الطعام الذي أكلته للتوّ إلى مواد يستطيع جسمك استخدامها هو أن ___.', options: ['decompose', 'hijack', 'secrete', 'digest'], answer: 3,
          explainAr: 'digest = يهضم، وهذا تعريفها في تمرين الكلمات في الوحدة 7 (البكتيريا في الأمعاء تساعد على هضم الطعام). decompose = يتحلّل، hijack = يستولي على، secrete = يُفرز (الوحدة 8).' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'Are you sure ……… the information he has just given you?', promptAr: 'هل أنت متأكّد ___ المعلومات التي أعطاك إياها للتوّ؟', options: ['of', 'with', 'about', 'for'], answer: 2,
          explainAr: 'الصفات التي يتبعها حرف جر (الوحدة 9): sure about = متأكّد من/بشأن، والجملة من كتابك. ومثلها: proud of، busy with، grateful for.' },
        { n: 21, kind: 'mcq', topic: 'pronunciation', prompt: '“You’re French, aren’t you?” When the speaker expects the listener to confirm this, the intonation on the question tag ……….', promptAr: 'عندما يتوقّع المتكلّم أن يؤكّد المستمع المعلومة، فإن التنغيم على السؤال الذيلي ___.', options: ['falls', 'rises', 'rises on the first choice', 'does not change'], answer: 0,
          explainAr: 'تنغيم الأسئلة (الوحدة 10): السؤال الذيلي الذي ينتظر تأكيداً (المتكلّم شبه متأكّد) ينخفض فيه الصوت. أما إذا كان المتكلّم غير متأكّد فيرتفع الصوت. rises on the first choice خاص بأسئلة الاختيار (or).' },
        { n: 22, kind: 'mcq', topic: 'wordform', prompt: 'Before going to the airport, you should check your travel ……….', promptAr: 'قبل الذهاب إلى المطار، عليك أن تتحقّق من ___ السفر.', options: ['requires', 'required', 'requiring', 'requirements'], answer: 3,
          explainAr: 'بعد صفة الملكية your و travel نحتاج اسماً جمعاً: requirements = متطلّبات (require + ment + s)، والجملة من تمرين أقسام الكلام في الوحدة 11. requires فعل، required و requiring صيغتان للفعل.' },
      ],
    },
    {
      letter: 'IV',
      title: 'Complete the following sentences by filling in each gap with one functional word:',
      titleAr: 'أكمل الجمل التالية بملء كل فراغ بكلمة وظيفية واحدة:',
      marks: 18,
      questions: [
        { n: 23, kind: 'write', topic: 'grammar', prompt: 'Rachel should either apologise ……… leave.', promptAr: 'يجب على رايتشل إمّا أن تعتذر ___ أن تغادر.', lines: 1,
          accept: ['or'], explainAr: 'أدوات الربط المزدوجة (الوحدة 9): either تأتي دائماً مع or (إمّا ... أو)، كما أن neither تأتي مع nor.' },
        { n: 24, kind: 'write', topic: 'grammar', prompt: 'In Britain, you ……… drive on the left. It’s the law.', promptAr: 'في بريطانيا، ___ أن تقود على الجهة اليسرى. هذا هو القانون.', lines: 1,
          accept: ['must', 'have to'], explainAr: 'الأفعال الناقصة للإلزام (الوحدة 10): القانون يعني إلزاماً، فنستخدم must (ويُقبل have to للإلزام العام). should للنصيحة فقط، و mustn’t للمنع.' },
        { n: 25, kind: 'write', topic: 'tense', prompt: 'The two companies ……… going to provide very different experiences.', promptAr: 'ستقدّم الشركتان تجارب مختلفة جداً.', lines: 1,
          accept: ['are'], explainAr: 'صيغة المستقبل be going to (الوحدة 6)، والفاعل جمع (The two companies) فنستخدم are. والجملة من كتابك.' },
      ],
    },
    {
      letter: 'V',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 24,
      questions: [
        { n: 26, kind: 'write', topic: 'grammar', prompt: 'Pascale was invited to lunch at {her new friend’s} house.', promptAr: 'دُعيت باسكال إلى الغداء في بيت صديقتها الجديدة.', lines: 1,
          accept: ['Whose house was Pascale invited to lunch at?', 'At whose house was Pascale invited to lunch?', 'Whose house was she invited to lunch at?'], modelAr: 'في بيت مَن دُعيت باسكال إلى الغداء؟',
          explainAr: 'المسطَّر يدل على الملكية (friend’s) فنسأل بـ Whose + الاسم (house). الفعل مبني للمجهول في الماضي (was invited) فنقدّم was على الفاعل.' },
        { n: 27, kind: 'write', topic: 'grammar', prompt: 'George’s host was {a little embarrassed} when George tried to tip in a café in Seoul.', promptAr: 'شعر مضيف جورج ببعض الإحراج عندما حاول جورج أن يترك بقشيشاً في مقهى في سيول.', lines: 1,
          accept: ['How did George’s host feel when George tried to tip in a café in Seoul?', 'How was George’s host when George tried to tip in a café in Seoul?', 'How did George’s host feel?', 'How was George’s host?'], modelAr: 'بماذا شعر مضيف جورج عندما حاول أن يترك بقشيشاً؟',
          explainAr: 'المسطَّر صفة تصف الشعور فنسأل بـ How (How did ... feel? أو How was ...?). الموقف من الوحدة 10 (العادات المختلفة بين الثقافات).' },
        { n: 28, kind: 'write', topic: 'grammar', prompt: 'The half-day trip costs {10,000 SYP}.', promptAr: 'تكلّف رحلة نصف اليوم 10,000 ليرة سورية.', lines: 1,
          accept: ['How much does the half-day trip cost?', 'How much is the half-day trip?', 'How much does a half-day trip cost?'], modelAr: 'كم تكلّف رحلة نصف اليوم؟',
          explainAr: 'المسطَّر سعر فنسأل بـ How much. الفعل costs مضارع بسيط مع مفرد، فنستخدم does ويعود الفعل إلى أصله cost. من حوار طلب المعلومات (الوحدة 3).' },
      ],
    },
    {
      letter: 'VI',
      title: 'Rewrite the following sentences as required in brackets:',
      titleAr: 'أعد كتابة الجمل التالية كما هو مطلوب بين القوسين:',
      marks: 32,
      questions: [
        { n: 29, kind: 'write', topic: 'reported', prompt: '“What time did the film start?” my friend asked. (Reported speech)', promptAr: '"متى بدأ الفيلم؟" سأل صديقي. (الكلام المنقول)', lines: 2,
          accept: ['My friend asked what time the film had started.', 'My friend asked me what time the film had started.', 'My friend wanted to know what time the film had started.'], modelAr: 'سألني صديقي متى كان الفيلم قد بدأ.',
          explainAr: 'نقل سؤال wh- (الوحدة 11): نُبقي أداة السؤال (what time) ونجعل الترتيب خبرياً بلا did، ويرجع الماضي البسيط started إلى الماضي التام had started.' },
        { n: 30, kind: 'write', topic: 'grammar', prompt: 'The play had hardly started when there was a disturbance in the audience. (Begin with: Hardly)', promptAr: 'ما كادت المسرحية تبدأ حتى حدثت فوضى بين الجمهور. (ابدأ بـ Hardly)', lines: 2,
          accept: ['Hardly had the play started when there was a disturbance in the audience.'], modelAr: 'ما كادت المسرحية تبدأ حتى حدثت فوضى بين الجمهور.',
          explainAr: 'القلب (Inversion، الوحدة 12): عندما نبدأ بظرف مقيِّد مثل Hardly نقدّم الفعل المساعد على الفاعل: Hardly + had + the play + started ... when .... والجملة من كتابك.' },
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Your friend offers you a piece of cake, but you are trying to lose weight. (Decline the offer politely)', promptAr: 'يعرض عليك صديقك قطعة كعك، لكنك تحاول إنقاص وزنك. (ارفض العرض بلطف)', lines: 2,
          accept: ['No, thank you. I’m trying to lose weight.', 'No, thank you.', 'No thanks, I’m trying to lose weight.', 'It’s OK, thank you. I’m trying to lose weight.', 'Not just at the moment, thank you.', 'No, thank you. I’m on a diet.'],
          model: 'No, thank you. I’m trying to lose weight.', modelAr: 'لا، شكراً لك. أحاول أن أُنقص وزني.',
          explainAr: 'رفض العروض (Everyday English، الوحدة 9): No, thank you. / Not just at the moment, thank you. / It’s OK. ويُستحسن ذكر السبب بلطف، كما في حوار كتابك: "No thank you. No sugar. I’m trying to lose weight."' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Ali’s driving licence was taken away by the police. (causative verb)', promptAr: 'سحبت الشرطة رخصة قيادة علي. (الفعل السببي)', lines: 2,
          accept: ['Ali had his driving licence taken away by the police.', 'Ali had his driving licence taken away.', 'Ali got his driving licence taken away by the police.'],
          modelAr: 'سُحبت رخصة قيادة علي من قِبل الشرطة.',
          explainAr: 'الفعل السببي لحدث سيّئ وقع لشخص (الوحدة 4): had + مفعول + التصريف الثالث. was taken away ماضٍ فنقول Ali had his driving licence taken away. والجملة من كتابك.' },
      ],
    },
    {
      letter: 'VII',
      title: 'Correct the verbs in brackets:',
      titleAr: 'صحّح الأفعال بين القوسين:',
      marks: 18,
      questions: [
        { n: 33, kind: 'write', topic: 'conditional', prompt: 'People wouldn’t have crossed the Bosphorus if they ………. (not build) these bridges.', promptAr: 'ما كان الناس ليعبروا البوسفور لو لم يبنوا هذه الجسور.', lines: 1,
          accept: ['hadn’t built', 'had not built'], explainAr: 'الشرطية الثالثة (الوحدة 7): جواب الشرط wouldn’t have crossed يدل على الماضي المتخيَّل، فجملة if تأخذ الماضي التام: hadn’t + built (التصريف الثالث لـ build).' },
        { n: 34, kind: 'write', topic: 'tense', prompt: 'George, you look tired. — Yes, I ………. (cut) the grass.', promptAr: 'جورج، تبدو متعباً. — نعم، كنتُ أقصّ العشب (حتى الآن).', lines: 1,
          accept: ['have been cutting', '’ve been cutting'], explainAr: 'المضارع التام المستمر (الوحدة 1): have been + فعل ing لنشاط استمرّ حتى وقت قريب وأثره ظاهر الآن (you look tired). أما has cut فتدل على نتيجة عمل مكتمل (Is the lawn finished?).' },
        { n: 35, kind: 'write', topic: 'tense', prompt: 'It took us a long time to arrive. I wish we ………. (catch) the train instead.', promptAr: 'استغرق وصولنا وقتاً طويلاً. ليتنا ركبنا القطار بدلاً من ذلك.', lines: 1,
          accept: ['had caught'], explainAr: 'التمنّي عن الماضي (الوحدة 8): It took us (ماضٍ) يدل على أن الأمر انتهى، فنستخدم I wish + had + التصريف الثالث (caught) للندم.' },
      ],
    },
    {
      letter: 'VIII',
      title: 'Complete the following sentences using clauses:',
      titleAr: 'أكمل الجمل التالية باستخدام جُمل مناسبة:',
      marks: 12,
      questions: [
        { n: 36, kind: 'write', topic: 'conditional', prompt: 'Were I you, …………………………..', promptAr: 'لو كنتُ مكانك، …', lines: 2,
          accept: ['I would study more.', 'I would study harder.', 'I would see a doctor.', 'I would accept the job.'], model: 'I would study more.', modelAr: 'لدرستُ أكثر.',
          explainAr: 'القلب في الشرط (الوحدة 12): Were I you = If I were you، والجواب would + فعل في أصله (الشرطية الثانية). الجملة من كتابك: "Were I you, I would study more."' },
        { n: 37, kind: 'write', topic: 'conditional', prompt: 'If I saw a burglar breaking into my house, …………………………..', promptAr: 'لو رأيتُ لصاً يقتحم بيتي، …', lines: 2,
          accept: ['I would ring the police.', 'I would call the police.', 'I would phone the police.'], model: 'I would ring the police.', modelAr: 'لاتّصلتُ بالشرطة.',
          explainAr: 'الشرطية الثانية (الوحدة 7): If + ماضٍ بسيط (saw) لموقف متخيَّل، والجواب would + فعل في أصله. في كتابك: "I would ring the police if I saw a burglar breaking into my house."' },
      ],
    },
    {
      letter: 'IX',
      title: 'Translation:',
      titleAr: 'الترجمة:',
      marks: 14,
      questions: [
        { n: 38, kind: 'write', prompt: 'Translate into Arabic: You have to make an effort to get things done.', promptAr: 'ترجم إلى العربية.', lines: 2,
          accept: ['عليك أن تبذل جهداً لإنجاز الأمور', 'يجب أن تبذل جهداً كي تُنجز الأشياء', 'عليك أن تبذل جهداً لتنجز الأمور'], model: 'عليك أن تبذل جهداً لإنجاز الأمور.',
          explainAr: 'الجملة من كتابك (المتلازمات اللفظية، الوحدة 7). have to = يجب/عليك، make an effort = يبذل جهداً، get things done = يُنجز الأمور.' },
        { n: 39, kind: 'write', prompt: 'ترجم إلى الإنجليزية: أعتقد أن الطقس سيكون حاراً جداً غداً.', promptAr: 'ترجم إلى الإنجليزية.', lines: 2,
          accept: ['I think the weather will be too hot tomorrow.', 'I think the weather will be very hot tomorrow.', 'I think it will be very hot tomorrow.'],
          model: 'I think the weather will be too hot tomorrow.',
          explainAr: 'الجملة من كتابك (صيغ المستقبل، الوحدة 6). للتنبّؤ بعد I think نستخدم will + فعل في أصله: will be. غداً ← tomorrow في آخر الجملة.' },
      ],
    },
    {
      letter: 'X',
      title: 'Write a composition of no less than 80 words on the following topic:',
      titleAr: 'اكتب موضوعاً لا يقل عن 80 كلمة عن الموضوع التالي:',
      marks: 50,
      writing: {
        topic: 'Different uses of artificial intelligence in our modern life.',
        topicAr: 'الاستخدامات المختلفة للذكاء الاصطناعي في حياتنا الحديثة.',
        words: 80,
        points: ['Mention at least three uses of AI.', 'How AI makes our life easier.', 'Its limitations and your opinion.'],
        model: 'Artificial intelligence has become part of our modern life. First of all, it is used in medicine, where clever machines help doctors diagnose diseases and analyse medical images quickly. In addition to medicine, AI is used in driving and aviation; some cars can now park and even drive by themselves. Furthermore, AI helps us in education and personal assistance, as smart phones can answer our questions and translate languages in seconds. Not only does AI save time, but it also reduces human mistakes. However, AI still lacks common sense and emotional intelligence, so it cannot replace people completely. In my opinion, we should use it wisely and not be afraid of it.',
        modelAr: 'أصبح الذكاء الاصطناعي جزءاً من حياتنا الحديثة. فهو أولاً يُستخدم في الطب، حيث تساعد الآلات الذكية الأطباء على تشخيص الأمراض وتحليل الصور الطبية بسرعة. وإضافةً إلى الطب، يُستخدم في قيادة السيارات والطيران؛ فبعض السيارات اليوم تستطيع أن تركن بل وأن تسير وحدها. علاوة على ذلك، يساعدنا في التعليم والمساعدة الشخصية، إذ تستطيع الهواتف الذكية الإجابة عن أسئلتنا وترجمة اللغات في ثوانٍ. ولا يوفّر الذكاء الاصطناعي الوقت فحسب، بل يقلّل الأخطاء البشرية أيضاً. لكنه ما يزال يفتقر إلى الحسّ السليم والذكاء العاطفي، لذلك لا يستطيع أن يحلّ محلّ الإنسان تماماً. برأيي، يجب أن نستخدمه بحكمة وألّا نخاف منه.',
        checklistAr: [
          'ذكرتُ ثلاثة استخدامات على الأقل للذكاء الاصطناعي، وكيف يسهّل حياتنا، وحدوده ورأيي فيه.',
          'كتبتُ 80 كلمة على الأقل في فقرة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ أدوات الربط التي يطلبها كتابك (in addition to, not only ... but also, furthermore, besides, however).',
          'استخدمتُ المبني للمجهول بشكل صحيح (it is used in ...) والمضارع البسيط للحقائق.',
          'استخدمتُ مفردات الوحدة 11 (clever machines, common sense, emotional intelligence, aviation).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
