import type { Exam } from '../../../engine/types'

// A practice certificate paper in the exact layout of the real 2026 Basic Education Certificate paper (term2-a.ts),
// built only from the Grade 9 books.
// Passage A: Student's Book Unit 11 reading "Touch People's Hearts" (page 68).
// Passage B: Activity Book Unit 5 text "Late to Go Back" (page 19).
// C, D and E: sentences from Units 3, 6, 8 and 10 (Student's Book and Activity Book).
// G: two of the book's writing topics (Unit 3 "My life in twenty years' time", Activity Book Unit 10 "manage and organize your time").
export const term2F: Exam = {
  id: 't2-f',
  term: 2,
  title: 'Certificate Exam — Model (F)',
  titleAr: 'نموذج امتحان الشهادة (F)',
  minutes: 90,
  totalMarks: 400,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان شهادة التعليم الأساسي 2026: النص الأول من قراءة الوحدة 11 في كتاب الطالب، والنص الثاني من نص «Late to Go Back» في كتاب النشاط (الوحدة 5)، وأسئلة القواعد والمفردات من جمل الوحدات 3 و6 و8 و10.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text then choose the correct answer a, b, c, or d:',
      titleAr: 'اقرأ النص التالي ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 50,
      passage: {
        paragraphs: [
          'Have you ever been inspired by someone to change your life in a significant way that made you healthier, happier, or more fulfilled? If so, then you understand how inspiration can create a positive difference in a person’s life. Inspiration is powerful. If you want to be positive and capable of inspiring others, here are some tips to follow.',
          'Show people you care. Remember how many times your day was changed by questions like “How are you today?” or “Is everything going well with you?” said by a friend. Your actions are very important too. Many people’s lives are inspired by small acts of kindness.',
          'Earn trust. If you are told a secret by a friend, it stays between you and him/her. Trust takes a long time to be built, but in many cases it can be destroyed in no time.',
          'Keep your promises. If someone is being helped by a volunteer, he/she needs to do it with a smile. Life has many examples of promises that are kept to save many people’s lives. Therefore, you should be wise enough to keep your word no matter what it takes.',
        ],
        paragraphsAr: [
          'هل سبق أن ألهمك أحدٌ أن تغيّر حياتك تغييراً مهماً جعلك أكثر صحة أو سعادة أو رضا؟ إن كان كذلك فأنت تفهم كيف يمكن للإلهام أن يُحدث فرقاً إيجابياً في حياة الإنسان. الإلهام قوي. إن أردت أن تكون إيجابياً وقادراً على إلهام الآخرين، فإليك بعض النصائح لتتبعها.',
          'أظهِر للناس أنك تهتم بهم. تذكّر كم مرة تغيّر يومك بأسئلة مثل «كيف حالك اليوم؟» أو «هل كل شيء يسير على ما يرام معك؟» قالها لك صديق. أفعالك مهمة جداً أيضاً. فحياة كثير من الناس تُلهمها أعمال لطف صغيرة.',
          'اكسب الثقة. إن أخبرك صديق بسرّ فإنه يبقى بينك وبينه. الثقة تحتاج وقتاً طويلاً لتُبنى، لكنها في حالات كثيرة يمكن أن تُهدم في لحظة.',
          'أوفِ بوعودك. إن كان متطوّع يساعد أحداً فعليه أن يفعل ذلك بابتسامة. في الحياة أمثلة كثيرة على وعود وُفي بها فأنقذت حياة كثير من الناس. لذلك يجب أن تكون حكيماً بما يكفي لتفي بكلمتك مهما كلّف الأمر.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer a, b, c, or d:',
          titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
          marks: 50,
          questions: [
            { n: 1, kind: 'mcq', prompt: 'Inspiration can create a ……… difference in a person’s life.', promptAr: 'يمكن للإلهام أن يُحدث فرقاً ___ في حياة الإنسان.',
              options: ['negative', 'small', 'positive', 'dangerous'], answer: 2,
              explainAr: 'الجواب "positive": النص يقول "inspiration can create a positive difference in a person’s life" أي فرقاً إيجابياً.' },
            { n: 2, kind: 'mcq', prompt: 'Many people’s lives are inspired by ………', promptAr: 'حياة كثير من الناس تُلهمها ___.',
              options: ['small acts of kindness', 'expensive presents', 'long letters', 'hard work'], answer: 0,
              explainAr: 'الجواب "small acts of kindness": النص يقول "Many people’s lives are inspired by small acts of kindness" أي أعمال لطف صغيرة.' },
            { n: 3, kind: 'mcq', prompt: 'If a friend tells you a secret, you should ………', promptAr: 'إن أخبرك صديق بسرّ فعليك أن ___.',
              options: ['tell your family', 'keep it between you and him/her', 'forget it quickly', 'write it on the internet'], answer: 1,
              explainAr: 'الجواب "keep it between you and him/her": النص يقول "If you are told a secret by a friend, it stays between you and him/her" أي يبقى السرّ بينكما.' },
            { n: 4, kind: 'mcq', prompt: 'Trust takes a long time to be built, but it can be destroyed ………', promptAr: 'الثقة تحتاج وقتاً طويلاً لتُبنى، لكن يمكن أن تُهدم ___.',
              options: ['after many years', 'very slowly', 'in a long time', 'very quickly'], answer: 3,
              explainAr: 'الجواب "very quickly": في النص "it can be destroyed in no time"، والتعبير in no time يعني بسرعة كبيرة / في لحظة.' },
            { n: 5, kind: 'mcq', prompt: 'A volunteer should help people ………', promptAr: 'على المتطوّع أن يساعد الناس ___.',
              options: ['with a smile', 'for money', 'once a year', 'without talking'], answer: 0,
              explainAr: 'الجواب "with a smile": النص يقول "If someone is being helped by a volunteer, he/she needs to do it with a smile" أي بابتسامة.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 50,
      passage: {
        paragraphs: [
          'Sam walked into a cake shop, after he’d finished his work, to buy his daughter a birthday cake. It was about four o’clock and the store usually closes at five. So he should make his mind quickly and decide what he should buy. Sam asked himself “Which one should I choose?” He began wandering in the shop watching the various kinds of cakes which were kept in the refrigerators around. The cakes looked very delicious and tasty so it was difficult for Sam to choose.',
          'Time was passing but in vain. Sam couldn’t decide yet, when he heard the chef saying “Come on. Hurry up, please, we are about to close the store.”',
          '“No, wait please, I should choose the most suitable and delicious cake.” Sam said sorrowfully. Sam’s eyes kept moving from one refrigerator to another, but all of the options looked so good and he couldn’t make a decision yet.',
          '“Try to be quick Man, make up your mind, we have to close,” the impatient chef said. Suddenly, the chef had enough and asked Sam to leave immediately. Sam walked out of the shop empty-handed feeling depressed and frustrated. He wanted them all, but ended up with nothing because he couldn’t choose any.',
        ],
        paragraphsAr: [
          'دخل سام محلّ حلويات بعد أن أنهى عمله ليشتري لابنته قالب حلوى لعيد ميلادها. كانت الساعة نحو الرابعة، والمحلّ يُغلق عادةً في الخامسة. لذلك كان عليه أن يحسم أمره بسرعة ويقرّر ماذا يشتري. سأل سام نفسه: «أيّها أختار؟» وبدأ يتجوّل في المحلّ يتفرّج على أنواع الحلوى المختلفة المحفوظة في البرّادات حوله. بدت الحلوى لذيذة وشهيّة جداً، فكان من الصعب على سام أن يختار.',
          'كان الوقت يمضي بلا فائدة. لم يستطع سام أن يقرّر بعد، حين سمع الطاهي يقول: «هيا، أسرع من فضلك، نحن على وشك إغلاق المحلّ.»',
          '«لا، انتظر من فضلك، يجب أن أختار أنسب قالب وألذّه.» قال سام بحزن. ظلّت عينا سام تنتقلان من برّاد إلى آخر، لكن كل الخيارات بدت جيدة جداً، ولم يستطع أن يتّخذ قراراً بعد.',
          '«حاول أن تكون سريعاً يا رجل، احسم أمرك، علينا أن نُغلق.» قال الطاهي نافد الصبر. وفجأة فقد الطاهي صبره وطلب من سام أن يغادر فوراً. خرج سام من المحلّ خالي اليدين يشعر بالإحباط والضيق. لقد أرادها كلها، لكنه انتهى بلا شيء لأنه لم يستطع أن يختار أيّاً منها.',
        ],
      },
      groups: [
        {
          title: 'Write true (T) or false (F):',
          titleAr: 'اكتب صح (T) أو خطأ (F):',
          marks: 30,
          questions: [
            { n: 6, kind: 'truefalse', prompt: 'Sam went to the cake shop to buy a birthday cake for his daughter.', promptAr: 'ذهب سام إلى محلّ الحلويات ليشتري قالب حلوى لعيد ميلاد ابنته.', answer: true,
              explainAr: 'صح: النص يقول "Sam walked into a cake shop ... to buy his daughter a birthday cake".' },
            { n: 7, kind: 'truefalse', prompt: 'The store usually closes at four o’clock.', promptAr: 'يُغلق المحلّ عادةً في الساعة الرابعة.', answer: false,
              explainAr: 'خطأ: النص يقول "It was about four o’clock and the store usually closes at five" — الرابعة هي الوقت الذي دخل فيه سام، أما الإغلاق ففي الخامسة.' },
            { n: 8, kind: 'truefalse', prompt: 'Sam left the shop without buying anything.', promptAr: 'غادر سام المحلّ دون أن يشتري شيئاً.', answer: true,
              explainAr: 'صح: النص يقول "Sam walked out of the shop empty-handed" و"ended up with nothing" — خرج خالي اليدين.' },
          ],
        },
        {
          title: 'Answer the following questions about the text:',
          titleAr: 'أجب عن الأسئلة التالية حول النص:',
          marks: 20,
          questions: [
            { n: 9, kind: 'write', prompt: 'What time was it when Sam walked into the cake shop?', promptAr: 'كم كانت الساعة عندما دخل سام محلّ الحلويات؟', lines: 1,
              accept: ['It was about four o’clock.', 'It was about four o clock.', 'It was four o’clock.', 'About four o’clock.', 'Four o’clock.', 'It was about 4 o’clock.', 'It was about four.', 'About four.'],
              model: 'It was about four o’clock.',
              modelAr: 'كانت الساعة نحو الرابعة.',
              explainAr: 'الجواب في الجملة الثانية: "It was about four o’clock and the store usually closes at five". لا تخلط بين وقت دخوله (الرابعة) ووقت الإغلاق (الخامسة).' },
            { n: 10, kind: 'write', prompt: 'Why was it difficult for Sam to choose?', promptAr: 'لماذا كان من الصعب على سام أن يختار؟', lines: 2,
              accept: ['Because the cakes looked very delicious and tasty.', 'Because the cakes looked delicious and tasty.', 'The cakes looked very delicious and tasty.', 'Because all of the options looked so good.', 'Because all the cakes looked so good.', 'Because all of the options looked so good and he wanted them all.', 'Because he wanted them all.'],
              model: 'Because the cakes looked very delicious and tasty.',
              modelAr: 'لأن الحلوى بدت لذيذة وشهيّة جداً.',
              explainAr: 'النص: "The cakes looked very delicious and tasty so it was difficult for Sam to choose". السؤال بـ Why فنبدأ الجواب بـ Because.' },
          ],
        },
      ],
    },
    {
      letter: 'C',
      title: 'Choose the correct answer a, b, c or d:',
      titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 150,
      questions: [
        { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'E-books will ……… traditional books.', promptAr: 'ستحلّ الكتب الإلكترونية ___ الكتب التقليدية.',
          options: ['predict', 'improve', 'obtain', 'replace'], answer: 3,
          explainAr: 'الجواب "replace" = يحلّ محلّ (take the place of)، من نص «Life in the Future» في الوحدة 3: "E-books will replace traditional books". predict = يتنبّأ، improve = يحسّن، obtain = يحصل على.' },
        { n: 12, kind: 'mcq', topic: 'grammar', prompt: 'Take advantage ……… opportunities.', promptAr: 'استفِد ___ الفرص.',
          options: ['in', 'of', 'at', 'for'], answer: 1,
          explainAr: 'الجواب "of": التعبير take advantage of = يستفيد من / يغتنم، من مبدأ «Do It Now» في الوحدة 10: "Opportunity is knocking. Take advantage of opportunities."' },
        { n: 13, kind: 'mcq', topic: 'vocab', prompt: 'They began ……… skyscrapers, cliffs and bridges to capture a photo to remember.', promptAr: 'بدؤوا ___ ناطحات السحاب والمنحدرات والجسور ليلتقطوا صورة للذكرى.',
          options: ['shooting', 'sharing', 'scaling', 'spicing'], answer: 2,
          explainAr: 'الجواب "scaling" = تسلّق شيء عالٍ وشديد الانحدار، من نص «Sky Walkers» في الوحدة 8. shoot = يلتقط صورة، spice up = يضيف إثارة، share = يشارك.' },
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'Edison’s mother wasn’t ………; she wanted Edison to be a scientist.', promptAr: 'لم تكن أم إديسون ___؛ بل أرادت أن يصبح إديسون عالِماً.',
          options: ['frustrated', 'invented', 'memorized', 'quit'], answer: 0,
          explainAr: 'الجواب "frustrated" = محبَط منزعج، من نص إديسون في الوحدة 6: "Edison’s mother wasn’t frustrated; she wanted Edison to be a scientist". بعد wasn’t نحتاج صفة تصف حالتها.' },
        { n: 15, kind: 'mcq', topic: 'grammar', prompt: 'Passenger: ……… too fast, please! I get sick easily.', promptAr: 'الراكب: ___ بسرعة كبيرة من فضلك! أنا أمرض بسهولة.',
          options: ['Doesn’t drive', 'Not drive', 'Didn’t drive', 'Don’t drive'], answer: 3,
          explainAr: 'الجواب "Don’t drive": صيغة الأمر المنفية = Don’t + الفعل المجرّد (الوحدة 6، قاعدة The Imperative): "Don’t drive too fast, please!"' },
        { n: 16, kind: 'mcq', topic: 'tense', prompt: 'While Kate ……… for the boy, her Dad arrived.', promptAr: 'بينما كانت كيت تبحث عن الصبي، وصل والدها.',
          options: ['looks', 'was looking', 'has looked', 'will look'], answer: 1,
          explainAr: 'الجواب "was looking": الماضي المستمر لحدث كان جارياً حين وقع حدث آخر بالماضي البسيط (arrived)، وتأتي while مع الماضي المستمر. الجملة من قصة كيت في الوحدة 8.' },
        { n: 17, kind: 'mcq', topic: 'tense', prompt: 'Hani lost a golden chance because he ……… the value of time.', promptAr: 'أضاع هاني فرصة ذهبية لأنه لم يكن قد تعلّم قيمة الوقت.',
          options: ['has not learnt', 'does not learn', 'had not learnt', 'will not learn'], answer: 2,
          explainAr: 'الجواب "had not learnt": الماضي التام (had + التصريف الثالث) لحدث سبق حدثاً آخر في الماضي (lost). الجملة من قصة هاني في كتاب النشاط (الوحدة 10).' },
        { n: 18, kind: 'mcq', topic: 'tense', prompt: 'It is a heavy box. I ……… it for you.', promptAr: 'إنه صندوق ثقيل. سأرفعه لك.',
          options: ['will lift', 'lifted', 'have lifted', 'was lifting'], answer: 0,
          explainAr: 'الجواب "will lift": نستخدم will لقرار نتّخذه لحظة الكلام (الوحدة 3، will / going to): "It is a heavy box. I will lift it for you."' },
        { n: 19, kind: 'mcq', topic: 'grammar', prompt: 'People can spend ……… time doing various things.', promptAr: 'يمكن للناس أن يقضوا ___ الوقت في فعل أشياء متنوّعة.',
          options: ['many', 'a few', 'a lot of', 'few'], answer: 2,
          explainAr: 'الجواب "a lot of": كلمة time هنا غير معدودة، فلا نستخدم معها many أو a few أو few (للمعدود). الجملة من نص الوحدة 10: "People can spend a lot of time doing various things".' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'Edison ……… by his mother’s decision.', promptAr: 'تعلّم إديسون في البيت بقرار من أمه.',
          options: ['homeschooled', 'was homeschooled', 'is homeschooling', 'homeschools'], answer: 1,
          explainAr: 'الجواب "was homeschooled": المبني للمجهول في الماضي = was + التصريف الثالث، ويأتي الفاعل بعد by. الجملة من نص إديسون في الوحدة 6.' },
        { n: 21, kind: 'mcq', topic: 'reported', prompt: 'He asked me if I ……… happy to be back.', promptAr: 'سألني إن كنتُ سعيداً بالعودة.',
          options: ['am', 'be', 'is', 'was'], answer: 3,
          explainAr: 'الجواب "was": في السؤال المنقول يرجع المضارع البسيط (Are you happy...?) خطوة إلى الماضي البسيط، ومع I نستخدم was (الوحدة 10، Reported Questions).' },
        { n: 22, kind: 'mcq', topic: 'grammar', prompt: 'Time is precious, ………?', promptAr: 'الوقت ثمين، أليس كذلك؟',
          options: ['isn’t it', 'is it', 'doesn’t it', 'wasn’t it'], answer: 0,
          explainAr: 'الجواب "isn’t it": الجملة مثبتة فعلها is (مضارع)، فيكون السؤال المذيّل منفياً بالفعل نفسه وبالضمير it. الجملة من نص الوحدة 10: "Time is precious!"' },
        { n: 23, kind: 'mcq', topic: 'grammar', prompt: 'Isabella decided to follow the footsteps of her grandmother ……… was a designer.', promptAr: 'قرّرت إيزابيلا أن تسير على خطا جدّتها التي كانت مصمّمة أزياء.',
          options: ['which', 'where', 'who', 'whose'], answer: 2,
          explainAr: 'الجواب "who": ضمير وصل للعاقل (grandmother) يقع فاعلاً لـ was. الجملة من نص كتاب النشاط في الوحدة 6.' },
        { n: 24, kind: 'mcq', topic: 'grammar', prompt: 'I wish I ……… too much time watching TV.', promptAr: 'ليتني لم أضيّع وقتاً كثيراً في مشاهدة التلفاز.',
          options: ['don’t waste', 'hadn’t wasted', 'haven’t wasted', 'won’t waste'], answer: 1,
          explainAr: 'الجواب "hadn’t wasted": للتمنّي أو الندم على الماضي نستخدم wish + الماضي التام (الوحدة 8): "I wish I hadn’t wasted too much time watching TV."' },
        { n: 25, kind: 'mcq', topic: 'pronunciation', prompt: 'The word which has a short /u/ sound is ………', promptAr: 'الكلمة التي فيها الصوت القصير /u/ هي ___.',
          options: ['fruit', 'school', 'blue', 'foot'], answer: 3,
          explainAr: 'الجواب "foot" فيها /u/ القصير مثل put و look. أما fruit و school و blue ففيها /u:/ الطويل (الوحدة 10، Short /u/ and long /u:/).' },
      ],
    },
    {
      letter: 'D',
      title: 'Match each item in (A) with the suitable choice from (B):',
      titleAr: 'صِل كل عبارة من العمود (A) بما يناسبها من العمود (B):',
      marks: 50,
      questions: [
        { n: 26, kind: 'mcq', prompt: 'Hundreds of astronauts are going to work and live', promptAr: 'مئات روّاد الفضاء سيعملون ويعيشون',
          options: ['he had not learnt the value of time.', 'social media services.', 'to educate young Thomas at home.', 'gift of God.', 'in the space station.'], answer: 4,
          explainAr: '"Hundreds of astronauts are going to work and live in the space station." — سيعمل مئات الروّاد ويعيشون في محطة الفضاء (كتاب النشاط، الوحدة 3). work and live يحتاجان مكاناً: in the space station.' },
        { n: 27, kind: 'mcq', prompt: 'Edison’s mother hid the letter and decided', promptAr: 'أخفت أم إديسون الرسالة وقرّرت',
          options: ['he had not learnt the value of time.', 'social media services.', 'to educate young Thomas at home.', 'gift of God.', 'in the space station.'], answer: 2,
          explainAr: '"Edison’s mother hid the letter and decided to educate young Thomas at home." — قرّرت أن تعلّم توماس في البيت (الوحدة 6). بعد decide يأتي to + الفعل المجرّد.' },
        { n: 28, kind: 'mcq', prompt: 'Selfies are often shared on', promptAr: 'غالباً ما تُنشر صور السيلفي على',
          options: ['he had not learnt the value of time.', 'social media services.', 'to educate young Thomas at home.', 'gift of God.', 'in the space station.'], answer: 1,
          explainAr: '"Selfies are often shared on social media services." — تُنشر صور السيلفي على مواقع التواصل الاجتماعي (نص «Sky Walkers»، الوحدة 8).' },
        { n: 29, kind: 'mcq', prompt: 'Hani lost a golden chance because', promptAr: 'أضاع هاني فرصة ذهبية لأن',
          options: ['he had not learnt the value of time.', 'social media services.', 'to educate young Thomas at home.', 'gift of God.', 'in the space station.'], answer: 0,
          explainAr: '"Hani lost a golden chance because he had not learnt the value of time." — لأنه لم يكن قد تعلّم قيمة الوقت (كتاب النشاط، الوحدة 10). بعد because تأتي جملة فيها فاعل وفعل.' },
        { n: 30, kind: 'mcq', prompt: 'Time is the greatest', promptAr: 'الوقت هو أعظم',
          options: ['he had not learnt the value of time.', 'social media services.', 'to educate young Thomas at home.', 'gift of God.', 'in the space station.'], answer: 3,
          explainAr: '"Time is the greatest gift of God." — الوقت أعظم هبة من الله (آخر نص الوحدة 10). بعد the greatest نحتاج اسماً: gift.' },
      ],
    },
    {
      letter: 'E',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 30,
      questions: [
        { n: 31, kind: 'write', topic: 'grammar', prompt: '{Marat Dupri} earned the name of “The sky walker”.', promptAr: 'حصل مارات دوبري على لقب «السائر في السماء».', lines: 1,
          accept: ['Who earned the name of “The sky walker”?', 'Who earned the name of The sky walker?', 'Who earned the name “The sky walker”?', 'Who earned the name of the sky walker?'],
          model: 'Who earned the name of “The sky walker”?',
          modelAr: 'من حصل على لقب «السائر في السماء»؟',
          explainAr: 'المسطَّر شخص وهو الفاعل، فنسأل بـ Who ونُبقي الفعل كما هو "earned" بلا did، لأن السؤال عن الفاعل. الجملة من نص «Sky Walkers» (الوحدة 8).' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'The first group of astronauts will live on the moon {for six months}.', promptAr: 'ستعيش المجموعة الأولى من روّاد الفضاء على القمر ستة أشهر.', lines: 1,
          accept: ['How long will the first group of astronauts live on the moon?', 'How long will the first group live on the moon?', 'How long will the astronauts live on the moon?', 'How long will the first group of astronauts stay on the moon?'],
          model: 'How long will the first group of astronauts live on the moon?',
          modelAr: 'كم من الوقت ستعيش المجموعة الأولى من روّاد الفضاء على القمر؟',
          explainAr: 'المسطَّر مدّة زمنية (for six months) فنسأل بـ How long. الجملة مستقبل بـ will فنقدّم will على الفاعل ويبقى الفعل live مجرّداً. الجملة من نص «Living in Space» (كتاب النشاط، الوحدة 3).' },
        { n: 33, kind: 'write', topic: 'grammar', prompt: 'People will have better education {because of technology}.', promptAr: 'سيحظى الناس بتعليم أفضل بسبب التكنولوجيا.', lines: 1,
          accept: ['Why will people have better education?', 'Why will people have a better education?', 'Why will people have better education in the future?'],
          model: 'Why will people have better education?',
          modelAr: 'لماذا سيحظى الناس بتعليم أفضل؟',
          explainAr: 'المسطَّر سبب يبدأ بـ because of، فنسأل بـ Why. الجملة مستقبل بـ will فنقدّم will على الفاعل: Why will people have better education? (نص «Life in the Future»، الوحدة 3).' },
      ],
    },
    {
      letter: 'F',
      title: 'Answer the following questions:',
      titleAr: 'أجب عن الأسئلة التالية:',
      marks: 20,
      questions: [
        { n: 34, kind: 'write', prompt: 'What do you usually do in your free time?', promptAr: 'ماذا تفعل عادةً في وقت فراغك؟', lines: 1,
          accept: ['I usually read books in my free time.', 'I usually read books.', 'I usually play football in my free time.', 'I usually play football.', 'I usually watch TV in my free time.', 'I usually watch TV.', 'I usually play with my friends in my free time.', 'I usually play with my friends.', 'I usually help my mother in my free time.', 'I usually draw pictures in my free time.', 'I usually listen to music in my free time.', 'I usually go for a walk in my free time.', 'I read books.', 'I play football.', 'I read stories in my free time.'],
          model: 'I usually read books in my free time.',
          modelAr: 'أقرأ الكتب عادةً في وقت فراغي.',
          explainAr: 'سؤال شخصي بالمضارع البسيط، فأجب بجملة كاملة بالمضارع البسيط: I usually + الفعل + in my free time. أي نشاط صحيح لغوياً مقبول.' },
        { n: 35, kind: 'write', prompt: 'What would you like to be in the future?', promptAr: 'ماذا تحب أن تصبح في المستقبل؟', lines: 1,
          accept: ['I would like to be a doctor.', 'I would like to be a teacher.', 'I would like to be an engineer.', 'I would like to be an English teacher.', 'I would like to be a pilot.', 'I would like to be a nurse.', 'I would like to be an architect.', 'I would like to be a lawyer.', 'I would like to be a scientist.', 'I would like to be a pharmacist.', 'I would like to be a doctor in the future.', 'I would like to be a teacher in the future.', 'I want to be a doctor.', 'I want to be a teacher.', 'I want to be an engineer.', 'A doctor.', 'A teacher.'],
          model: 'I would like to be a doctor.',
          modelAr: 'أحب أن أصبح طبيباً.',
          explainAr: 'السؤال بـ would like to be، فأجب: I would like to be + a / an + المهنة. استخدم an قبل المهنة التي تبدأ بصوت متحرّك (an engineer).' },
      ],
    },
    {
      letter: 'G',
      title: 'Write a 50-word paragraph about ONE of the following topics:',
      titleAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد من الموضوعين التاليين:',
      marks: 50,
      writing: {
        topic: 'Write a 50-word paragraph about ONE of the following topics: Topic 1: Your life in twenty years’ time. Topic 2: How you manage and organize your time.',
        topicAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد: الموضوع 1: حياتك بعد عشرين سنة. الموضوع 2: كيف تدير وقتك وتنظّمه.',
        words: 50,
        points: ['Topic 1: Your life in twenty years’ time.', 'Topic 2: How you manage and organize your time.'],
        model: 'Topic 1: In twenty years’ time, I will be thirty-four years old. I am going to study medicine, so I will be a doctor in a big hospital. I will help sick people and earn a good living. I will be married and we will have two children. I think my life will be comfortable and happy.\n\nTopic 2: Time is precious, so I try to organize it well. I always get up at six o’clock and go to school. In the afternoon, I do my homework first and then I help my mother. I watch TV for only one hour a day. I never leave today’s work for tomorrow.',
        modelAr: 'الموضوع 1: بعد عشرين سنة سيكون عمري أربعة وثلاثين عاماً. سأدرس الطب، لذلك سأصبح طبيباً في مستشفى كبير. سأساعد المرضى وأكسب عيشاً جيداً. سأكون متزوّجاً وسيكون لدينا طفلان. أظن أن حياتي ستكون مريحة وسعيدة.\n\nالموضوع 2: الوقت ثمين، لذلك أحاول أن أنظّمه جيداً. أستيقظ دائماً في السادسة وأذهب إلى المدرسة. بعد الظهر أكتب وظائفي أولاً ثم أساعد أمي. أشاهد التلفاز ساعة واحدة فقط في اليوم. لا أؤجّل عمل اليوم إلى الغد أبداً.',
        checklistAr: [
          'اخترتُ موضوعاً واحداً فقط وكتبتُ عنه وحده.',
          'كتبتُ نحو 50 كلمة في فقرة واحدة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ الزمن المناسب: المستقبل will و be going to للحديث عن حياتي بعد عشرين سنة، والمضارع البسيط مع ظروف التكرار (always, usually, never) للحديث عن تنظيم وقتي.',
          'استخدمتُ أدوات ربط (and, but, so, because, first, then).',
          'استخدمتُ كلمات من الوحدتين 3 و10 (improve, precious, productive, manage, efficiently).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
