import type { Exam } from '../../../engine/types'

// A practice Certificate paper in the exact layout of the real 2026 paper (term2-a.ts), built only from the book.
// Passage A: Student's Book Unit 9 reading "Who Deserves the Award?" (page 57, paragraphs 1–4).
// Passage B: Activity Book Unit 2 reading "Pay It Forward" (page 7).
// C, D and E: sentences from Units 3, 6, 9 and 12 (Student's Book and Activity Book, with Review 2 and the
// Activity Book's Progress Tests that follow Units 6 and 12). G: two of the book's own writing topics.
export const term2D: Exam = {
  id: 't2-d',
  term: 2,
  title: 'Certificate Exam — Model (D)',
  titleAr: 'نموذج امتحان الشهادة (D)',
  minutes: 90,
  totalMarks: 400,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان شهادة التعليم الأساسي 2026، مبنيّ فقط على كتابَيك: نص القراءة في الوحدة 9 من كتاب الطالب (Who Deserves the Award?)، ونص "Pay It Forward" من كتاب النشاط (الوحدة 2)، وجمل الوحدات 3 و6 و9 و12 من كتاب الطالب وكتاب النشاط، وموضوعا كتابة من الكتاب نفسه.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text then choose the correct answer a, b, c, or d:',
      titleAr: 'اقرأ النص التالي ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 50,
      passage: {
        paragraphs: [
          'Mariam was a teacher who wanted to motivate her students and make them do their best in the exam. So, she told them that she would give a gift, which was a new pair of shoes, to the one whose marks would be excellent. Children rejoiced over this challenge and they all started writing diligently. After collecting the papers, the teacher was surprised to find that everyone had a full mark.',
          'Who would get the gift? she thought. The teacher thanked everyone for their effort but she was confused about who would deserve the award as everyone had got the full mark.',
          'The teacher thought of a suitable solution with her students. The students’ opinion was that each of them would write his/her name on a folded paper and put it in a box from which the teacher would pick one. So, the paper would reveal the name of the award’s winner.',
          'Indeed, the teacher picked a paper in front of all students and read the child’s name, Nada, and said: “You are the owner of the award”. With joy and tears in her eyes, Nada came forward where the shoes were. She thanked everyone for this wonderful gift. Her parents couldn’t afford to buy her new shoes because of their extreme poverty.',
        ],
        paragraphsAr: [
          'كانت مريم معلّمةً أرادت أن تحفّز طلابها وتجعلهم يبذلون أقصى جهدهم في الامتحان. لذلك أخبرتهم أنها ستقدّم هدية، وهي زوج أحذية جديد، لمن تكون علاماته ممتازة. فرح الأطفال بهذا التحدّي وبدؤوا جميعاً يكتبون باجتهاد. وبعد جمع الأوراق، فوجئت المعلّمة بأن الجميع حصلوا على العلامة الكاملة.',
          '«مَن سيحصل على الهدية؟» فكّرت في نفسها. شكرت المعلّمة الجميع على جهدهم، لكنها كانت محتارة فيمن يستحق الجائزة لأن الجميع حصلوا على العلامة الكاملة.',
          'فكّرت المعلّمة مع طلابها في حلّ مناسب. كان رأي الطلاب أن يكتب كلٌّ منهم اسمه على ورقة مطويّة ويضعها في صندوق تسحب منه المعلّمة ورقة واحدة. وهكذا تكشف الورقة اسم الفائز بالجائزة.',
          'وبالفعل، سحبت المعلّمة ورقة أمام جميع الطلاب وقرأت اسم الطفلة، ندى، وقالت: «أنتِ صاحبة الجائزة». وبفرحٍ ودموعٍ في عينيها، تقدّمت ندى إلى حيث كان الحذاء. شكرت الجميع على هذه الهدية الرائعة. فوالداها لم يكونا قادرَين على شراء حذاء جديد لها بسبب فقرهما الشديد.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer a, b, c, or d:',
          titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
          marks: 50,
          questions: [
            { n: 1, kind: 'mcq', prompt: 'Mariam promised to give a gift to the student ……', promptAr: 'وعدت مريم بأن تقدّم هدية للطالب ___', options: ['who was the politest', 'whose marks would be excellent', 'who came to school first', 'who wrote the longest answer'], answer: 1,
              explainAr: 'الفقرة الأولى: "she would give a gift … to the one whose marks would be excellent" — الهدية لمن تكون علاماته ممتازة، فالجواب "whose marks would be excellent". أما الأدب أو الحضور باكراً أو طول الإجابة فغير مذكورة في النص.' },
            { n: 2, kind: 'mcq', prompt: 'The gift was ……', promptAr: 'كانت الهدية ___', options: ['a new pair of shoes', 'a series of stories', 'a new school bag', 'some money'], answer: 0,
              explainAr: 'النص: "a gift, which was a new pair of shoes" — الهدية زوج أحذية جديد، فالجواب "a new pair of shoes". ولذلك تقدّمت ندى في آخر النص "where the shoes were".' },
            { n: 3, kind: 'mcq', prompt: 'The teacher was confused because ……', promptAr: 'كانت المعلّمة محتارة لأن ___', options: ['nobody passed the exam', 'the papers were lost', 'everyone had got the full mark', 'the students refused the gift'], answer: 2,
              explainAr: 'الفقرة الثانية: "she was confused about who would deserve the award as everyone had got the full mark" — كانت محتارة لأن الجميع نالوا العلامة الكاملة، فالجواب "everyone had got the full mark". و as هنا بمعنى because.' },
            { n: 4, kind: 'mcq', prompt: 'Nada’s parents couldn’t buy her new shoes because they were very ……', promptAr: 'لم يستطع والدا ندى شراء حذاء جديد لها لأنهما كانا ___ جداً.', options: ['rich', 'famous', 'busy', 'poor'], answer: 3, topic: 'vocab',
              explainAr: 'آخر جملة: "because of their extreme poverty" — بسبب فقرهما الشديد. و poverty (فقر) اسم، وصفتها "poor" (فقير). أما "rich" فعكسها تماماً.' },
            { n: 5, kind: 'mcq', prompt: 'The winner of the award was chosen by ……', promptAr: 'اختير الفائز بالجائزة عن طريق ___', options: ['the headteacher', 'picking a folded paper from a box', 'the students’ parents', 'counting the marks again'], answer: 1,
              explainAr: 'الفقرة الثالثة: كتب كل طالب اسمه "on a folded paper and put it in a box from which the teacher would pick one"، ثم سحبت المعلّمة ورقة أمام الطلاب. فالجواب "picking a folded paper from a box".' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 50,
      passage: {
        paragraphs: [
          'On March 27, 2013, John Sweeney, a plumber from Ireland, started a Facebook page called Suspended Coffees. His message was simple: Buy a cup of coffee for a stranger, because an act of kindness can change a life and make a difference. Eight hours later, the page had attracted more than 20,000 likes.',
          'Suspended coffee is a tradition that comes from Naples, Italy, and dates back to the 20th century. When customers buy coffee, they also pay in advance for a cup to be given to somebody else; usually someone who otherwise couldn’t afford it. This initiative was forgotten, but then it revived again in 2011. That’s when “Suspended Coffee Day” started to be celebrated each December.',
          'You can buy it for anyone in need. It can be for the homeless person you pass by every day on the street, a stressed student in the middle of exams. It may be a well-dressed man whom you may not think from his appearance that he’s in need but he may be in his third month of job hunting. It’s not up to us to judge - if someone asks, then they’re in need - no CV required.',
        ],
        paragraphsAr: [
          'في 27 آذار 2013، أنشأ جون سويني، وهو سبّاك من إيرلندا، صفحة على فيسبوك اسمها «القهوة المعلّقة». كانت رسالته بسيطة: اشترِ فنجان قهوة لشخص غريب، لأن عملاً لطيفاً واحداً قد يغيّر حياة ويُحدث فرقاً. وبعد ثماني ساعات، كانت الصفحة قد جذبت أكثر من عشرين ألف إعجاب.',
          'القهوة المعلّقة تقليد جاء من نابولي في إيطاليا، ويعود إلى القرن العشرين. عندما يشتري الزبائن القهوة، يدفعون أيضاً مسبقاً ثمن فنجان يُقدَّم لشخص آخر، وغالباً ما يكون شخصاً لا يستطيع دفع ثمنه لولا ذلك. نُسيت هذه المبادرة، ثم عادت إلى الحياة في عام 2011، ومنذ ذلك الحين بدأ الاحتفال بـ«يوم القهوة المعلّقة» في شهر كانون الأول من كل عام.',
          'يمكنك أن تشتريها لأي شخص محتاج: قد تكون للمشرّد الذي تمرّ به كل يوم في الشارع، أو لطالب متوتّر في منتصف الامتحانات. وقد تكون لرجل حسن الهندام لا تظنّ من مظهره أنه محتاج، لكنه قد يكون في شهره الثالث من البحث عن عمل. ليس من شأننا أن نحكم على الناس؛ فإذا طلب أحدهم فهو محتاج، ولا حاجة إلى سيرة ذاتية.',
        ],
      },
      groups: [
        {
          title: 'Write true (T) or false (F):',
          titleAr: 'اكتب صح (T) أو خطأ (F):',
          marks: 30,
          questions: [
            { n: 6, kind: 'truefalse', prompt: 'John Sweeney was a plumber from Ireland.', promptAr: 'كان جون سويني سبّاكاً من إيرلندا.', answer: true,
              explainAr: 'صح: النص يقول "John Sweeney, a plumber from Ireland" — جون سويني سبّاك من إيرلندا.' },
            { n: 7, kind: 'truefalse', prompt: 'Suspended coffee is a tradition that comes from France.', promptAr: 'القهوة المعلّقة تقليد جاء من فرنسا.', answer: false,
              explainAr: 'خطأ: النص يقول "Suspended coffee is a tradition that comes from Naples, Italy" — جاء التقليد من نابولي في إيطاليا لا من فرنسا.' },
            { n: 8, kind: 'truefalse', prompt: 'Eight hours later, the page had more than 20,000 likes.', promptAr: 'بعد ثماني ساعات كان للصفحة أكثر من عشرين ألف إعجاب.', answer: true,
              explainAr: 'صح: النص يقول "Eight hours later, the page had attracted more than 20,000 likes" — بعد ثماني ساعات جذبت الصفحة أكثر من 20,000 إعجاب.' },
          ],
        },
        {
          title: 'Answer the following questions about the text:',
          titleAr: 'أجب عن الأسئلة التالية حول النص:',
          marks: 20,
          questions: [
            { n: 9, kind: 'write', prompt: 'When did John Sweeney start his Facebook page?', promptAr: 'متى أنشأ جون سويني صفحته على فيسبوك؟', lines: 1,
              accept: ['He started it on March 27, 2013.', 'He started his Facebook page on March 27, 2013.', 'John Sweeney started his Facebook page on March 27, 2013.', 'On March 27, 2013.', 'On 27 March 2013.', 'In 2013.', 'He started it in 2013.', 'March 27, 2013'],
              model: 'He started his Facebook page on March 27, 2013.',
              modelAr: 'أنشأ صفحته على فيسبوك في 27 آذار 2013.',
              explainAr: 'السؤال بـ When فالجواب تاريخ. أول جملة في النص: "On March 27, 2013, John Sweeney … started a Facebook page called Suspended Coffees". أجب بجملة كاملة بالماضي البسيط: He started …' },
            { n: 10, kind: 'write', prompt: 'Why did John ask people to buy a cup of coffee for a stranger?', promptAr: 'لماذا طلب جون من الناس أن يشتروا فنجان قهوة لشخص غريب؟', lines: 2,
              accept: ['Because an act of kindness can change a life and make a difference.', 'Because an act of kindness can change a life.', 'Because an act of kindness can make a difference.', 'Because kindness can change a life and make a difference.', 'He asked them because an act of kindness can change a life and make a difference.'],
              model: 'Because an act of kindness can change a life and make a difference.',
              modelAr: 'لأن عملاً لطيفاً واحداً قد يغيّر حياة ويُحدث فرقاً.',
              explainAr: 'السؤال بـ Why فنبدأ بـ Because. النص: "Buy a cup of coffee for a stranger, because an act of kindness can change a life and make a difference".' },
          ],
        },
      ],
    },
    {
      letter: 'C',
      title: 'Choose the correct answer a, b, c or d:',
      titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 150,
      questions: [
        { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'Scientists and researchers will find …… for many diseases like Aids and cancer.', promptAr: 'سيجد العلماء والباحثون ___ لأمراض كثيرة مثل الإيدز والسرطان.', options: ['crops', 'peace', 'cure', 'aspects'], answer: 2,
          explainAr: '"cure" = علاج (دواء شافٍ)، وتأتي مع diseases: find cure for diseases (من نص الوحدة 3 عن الحياة في المستقبل). أما "crops" فمحاصيل، و"peace" سلام، و"aspects" جوانب.' },
        { n: 12, kind: 'mcq', topic: 'grammar', prompt: 'When you are evaluating somebody, pay attention …… the body language.', promptAr: 'عندما تقيّم شخصاً ما، انتبه ___ لغة الجسد.', options: ['on', 'at', 'for', 'to'], answer: 3,
          explainAr: 'التعبير الثابت "pay attention to" = ينتبه إلى، وحرف الجر معه دائماً "to" (من نص الوحدة 12 عن لغة الجسد).' },
        { n: 13, kind: 'mcq', topic: 'vocab', prompt: 'From an early age, Isabella decided to follow the …… of her grandmother who was a designer.', promptAr: 'منذ سنّ مبكرة قرّرت إيزابيلا أن تسير على ___ جدّتها التي كانت مصمّمة.', options: ['footsteps', 'performance', 'instrument', 'accomplishment'], answer: 0,
          explainAr: 'التعبير "follow the footsteps of" = يسير على خطى فلان ويقلّده (من نص الوحدة 6 في كتاب النشاط). أما "performance" فأداء، و"instrument" آلة موسيقية، و"accomplishment" إنجاز.' },
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'A smile may …… approval or happiness.', promptAr: 'قد ___ الابتسامة الموافقةَ أو السعادة.', options: ['fold', 'indicate', 'enrol', 'garner'], answer: 1,
          explainAr: '"indicate" = يدلّ على / يكون علامة على (to be a sign of something)، فالابتسامة تدلّ على الموافقة أو السعادة (الوحدة 12). أما "fold" فيطوي، و"enrol" يسجّل في دورة، و"garner" يجمع.' },
        { n: 15, kind: 'mcq', topic: 'tense', prompt: 'Right now, Liam …… with the owner of the inn.', promptAr: 'في هذه اللحظة، ليام ___ مع صاحب النُّزُل.', options: ['sat', 'is sitting', 'sits', 'has sat'], answer: 1,
          explainAr: '"Right now" (الآن تماماً) تدل على حدث يجري لحظة الكلام، فنستخدم المضارع المستمر "is sitting" (is + sitting، مع مضاعفة t). أما "sat" فماضٍ، و"sits" للعادات.' },
        { n: 16, kind: 'mcq', topic: 'tense', prompt: 'This time last year, she …… at university.', promptAr: 'في مثل هذا الوقت من العام الماضي، ___ في الجامعة.', options: ['studies', 'has studied', 'was studying', 'will study'], answer: 2,
          explainAr: '"This time last year" تدل على حدث كان مستمراً في لحظة محدّدة من الماضي، فنستخدم الماضي المستمر "was studying" (was + studying).' },
        { n: 17, kind: 'mcq', topic: 'tense', prompt: 'When I opened the rest of the papers, I found that all the students …… the same name.', promptAr: 'عندما فتحتُ بقية الأوراق وجدتُ أن جميع الطلاب ___ الاسم نفسه.', options: ['write', 'have written', 'will write', 'had written'], answer: 3,
          explainAr: 'الكتابة حدثت قبل أن تجد المعلّمة الأوراق (found ماضٍ)، والحدث الأسبق في الماضي يأتي بالماضي التام "had written" (had + التصريف الثالث). الجملة من آخر نص الوحدة 9.' },
        { n: 18, kind: 'mcq', topic: 'tense', prompt: 'It is freezing today. It …… snow soon.', promptAr: 'الجو شديد البرودة اليوم. ___ الثلج قريباً.', options: ['is going to', 'was going to', 'has', 'did'], answer: 0,
          explainAr: 'نستخدم "is going to" للتوقّع حين يكون أمامنا دليل الآن: البرد الشديد اليوم دليل على أن الثلج سيتساقط قريباً (الوحدة 3: will و be going to).' },
        { n: 19, kind: 'mcq', topic: 'grammar', prompt: 'Happiness, sadness, anger, surprise, disgust and fear are just …… examples of emotions.', promptAr: 'السعادة والحزن والغضب والمفاجأة والاشمئزاز والخوف ليست إلا ___ الأمثلة على المشاعر.', options: ['a little', 'much', 'a few', 'a'], answer: 2,
          explainAr: '"examples" اسم معدود جمع، فنستخدم "a few" (بعض/قليل من). أما "a little" و"much" فتأتيان مع الاسم غير المعدود، و"a" مع المفرد فقط.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'A chocolate cake …… by the chef yesterday.', promptAr: '___ كعكة شوكولا من قِبل الطاهي البارحة.', options: ['baked', 'is baking', 'has baked', 'was baked'], answer: 3,
          explainAr: 'الكعكة لا تخبز نفسها بل تُخبَز، و"by the chef" تدل على المبني للمجهول، و"yesterday" على الماضي، فنستخدم "was baked" (was + التصريف الثالث). أصل الجملة في المراجعة 2: The chef baked a chocolate cake yesterday.' },
        { n: 21, kind: 'mcq', topic: 'reported', prompt: 'Jennifer: “Where do you play football?” Jennifer wanted to know where I …… football.', promptAr: 'جينيفر: «أين تلعب كرة القدم؟» أرادت جينيفر أن تعرف أين ___ كرة القدم.', options: ['play', 'am playing', 'played', 'will play'], answer: 2,
          explainAr: 'في السؤال المنقول بعد فعل ماضٍ (wanted to know) نرجع الزمن خطوة: المضارع البسيط do you play يصبح الماضي البسيط "played"، ونكتب الفاعل قبل الفعل بلا do: where I played.' },
        { n: 22, kind: 'mcq', topic: 'grammar', prompt: 'The car isn’t in the garage, ……?', promptAr: 'السيارة ليست في المرآب، ___ ؟ (أليس كذلك)', options: ['is it', 'isn’t it', 'does it', 'doesn’t it'], answer: 0,
          explainAr: 'الجملة منفية بـ isn’t، فيكون السؤال الذيلي مثبتاً بالفعل المساعد نفسه، والضمير it يعود على the car: "is it?".' },
        { n: 23, kind: 'mcq', topic: 'grammar', prompt: 'He came with a friend …… waited outside in the car.', promptAr: 'جاء مع صديق ___ انتظر في الخارج في السيارة.', options: ['who', 'which', 'where', 'whose'], answer: 0,
          explainAr: 'بعد اسم لشخص (a friend) وهو فاعل الفعل waited نستخدم ضمير الوصل "who". "which" للأشياء والحيوانات، "where" للمكان، "whose" للملكية.' },
        { n: 24, kind: 'mcq', topic: 'grammar', prompt: 'I can’t play the piano. I wish I …… the piano.', promptAr: 'لا أستطيع العزف على البيانو. أتمنّى لو ___ العزف على البيانو.', options: ['can play', 'could play', 'will play', 'have played'], answer: 1,
          explainAr: 'للتمنّي عن الحاضر (عكس الواقع) نستخدم wish + الماضي البسيط، والماضي من can هو could، فنقول "could play".' },
        { n: 25, kind: 'mcq', topic: 'pronunciation', prompt: 'The word which has the long vowel sound /i:/ is ……', promptAr: 'الكلمة التي فيها صوت العلّة الطويل /i:/ هي ___', options: ['set', 'net', 'wet', 'wheat'], answer: 3,
          explainAr: 'في "wheat" يُلفظ ea صوتاً طويلاً /i:/. أما "set" و"net" و"wet" ففيها الصوت القصير /e/ (الوحدة 3: الصوتان /e/ و /i:/، مثل wet و wheat).' },
      ],
    },
    {
      letter: 'D',
      title: 'Match each item in (A) with the suitable choice from (B):',
      titleAr: 'صِل كل عبارة من العمود (A) بما يناسبها من العمود (B):',
      marks: 50,
      questions: [
        { n: 26, kind: 'mcq', prompt: 'I’d love to go out,', promptAr: 'كنتُ أودّ أن أخرج،', options: ['I get sick easily.', 'certain commands such as “sit” and “come”.', 'but I think it will continue raining.', 'defence, being self-protective.', 'which was robbed yesterday.'], answer: 2,
          explainAr: '"I’d love to go out, but I think it will continue raining." — أودّ أن أخرج لكنني أظن أن المطر سيستمر. but تربط بين الرغبة وما يمنعها (الوحدة 3).' },
        { n: 27, kind: 'mcq', prompt: 'This is the bank', promptAr: 'هذا هو المصرف', options: ['I get sick easily.', 'certain commands such as “sit” and “come”.', 'but I think it will continue raining.', 'defence, being self-protective.', 'which was robbed yesterday.'], answer: 4,
          explainAr: '"This is the bank which was robbed yesterday." — هذا هو المصرف الذي سُرق البارحة. which ضمير وصل للأشياء، ويعود هنا على the bank (الوحدة 9).' },
        { n: 28, kind: 'mcq', prompt: 'Crossing the arms can indicate', promptAr: 'قد يدلّ تكتيف الذراعين على', options: ['I get sick easily.', 'certain commands such as “sit” and “come”.', 'but I think it will continue raining.', 'defence, being self-protective.', 'which was robbed yesterday.'], answer: 3,
          explainAr: '"Crossing the arms can indicate defence, being self-protective." — تكتيف الذراعين قد يدلّ على الدفاع وحماية النفس (نص الوحدة 12 عن لغة الجسد).' },
        { n: 29, kind: 'mcq', prompt: 'Don’t drive too fast, please!', promptAr: 'لا تقُد بسرعة كبيرة من فضلك!', options: ['I get sick easily.', 'certain commands such as “sit” and “come”.', 'but I think it will continue raining.', 'defence, being self-protective.', 'which was robbed yesterday.'], answer: 0,
          explainAr: '"Don’t drive too fast, please! I get sick easily." — لا تقُد بسرعة من فضلك، فأنا أمرض (أشعر بالدوار) بسهولة. Don’t + فعل مجرّد هو الأمر المنفي (الوحدة 6).' },
        { n: 30, kind: 'mcq', prompt: 'Dogs can be trained to follow', promptAr: 'يمكن تدريب الكلاب على اتّباع', options: ['I get sick easily.', 'certain commands such as “sit” and “come”.', 'but I think it will continue raining.', 'defence, being self-protective.', 'which was robbed yesterday.'], answer: 1,
          explainAr: '"Dogs can be trained to follow certain commands such as “sit” and “come”." — يمكن تدريب الكلاب على اتّباع أوامر معيّنة مثل «اجلس» و«تعال» (نص الوحدة 12 في كتاب النشاط).' },
      ],
    },
    {
      letter: 'E',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 30,
      questions: [
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Suzan spends her free time {in the school library}.', promptAr: 'تقضي سوزان وقت فراغها في مكتبة المدرسة.', lines: 1,
          accept: ['Where does Suzan spend her free time?', 'Where does she spend her free time?'],
          model: 'Where does Suzan spend her free time?',
          modelAr: 'أين تقضي سوزان وقت فراغها؟',
          explainAr: 'المسطَّر مكان (in the school library)، فنسأل بـ Where. الفعل spends مضارع بسيط مع فاعل مفرد، فنستخدم does ونعيد الفعل إلى أصله: Where does Suzan spend her free time? (نص الوحدة 9 في كتاب النشاط).' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Pablo Pineda won the Silver Shell Award {in 2009}.', promptAr: 'فاز بابلو بينيدا بجائزة الصدفة الفضية عام 2009.', lines: 1,
          accept: ['When did Pablo Pineda win the Silver Shell Award?', 'When did he win the Silver Shell Award?', 'In which year did Pablo Pineda win the Silver Shell Award?', 'What year did Pablo Pineda win the Silver Shell Award?', 'When did Pablo win the Silver Shell Award?'],
          model: 'When did Pablo Pineda win the Silver Shell Award?',
          modelAr: 'متى فاز بابلو بينيدا بجائزة الصدفة الفضية؟',
          explainAr: 'المسطَّر زمن (in 2009)، فنسأل بـ When. الفعل won ماضٍ بسيط، فنستخدم did ونعيد الفعل إلى أصله win: When did Pablo Pineda win …? (نص الوحدة 6 في كتاب النشاط).' },
        { n: 33, kind: 'write', topic: 'grammar', prompt: 'People won’t have to do housework {because robots will do that for them}.', promptAr: 'لن يضطر الناس إلى القيام بالأعمال المنزلية لأن الروبوتات ستقوم بها عنهم.', lines: 1,
          accept: ['Why won’t people have to do housework?', "Why won't people have to do housework?", 'Why will people not have to do housework?', 'Why won’t they have to do housework?'],
          model: 'Why won’t people have to do housework?',
          modelAr: 'لماذا لن يضطر الناس إلى القيام بالأعمال المنزلية؟',
          explainAr: 'المسطَّر سبب يبدأ بـ because، فنسأل بـ Why. الجملة مستقبل منفي بـ won’t، فنقدّم won’t على الفاعل: Why won’t people have to do housework? (نص الوحدة 3 في كتاب النشاط عن الحياة في الفضاء).' },
      ],
    },
    {
      letter: 'F',
      title: 'Answer the following questions:',
      titleAr: 'أجب عن الأسئلة التالية:',
      marks: 20,
      questions: [
        { n: 34, kind: 'write', prompt: 'What is your favourite subject?', promptAr: 'ما مادتك المفضّلة؟', lines: 1,
          accept: ['My favourite subject is English.', 'My favourite subject is Maths.', 'My favourite subject is Science.', 'My favourite subject is Arabic.', 'My favourite subject is History.', 'My favourite subject is Geography.', 'My favourite subject is Physics.', 'My favourite subject is Chemistry.', 'My favourite subject is Art.', 'It is English.', 'English is my favourite subject.', 'Maths is my favourite subject.', 'English.', 'Maths.'],
          model: 'My favourite subject is English.',
          modelAr: 'مادتي المفضّلة هي اللغة الإنكليزية.',
          explainAr: 'سؤال شخصي: تُقبل أي مادة تحبها بجملة كاملة. الصيغة: My favourite subject is + اسم المادة (بحرف كبير في أولها، مثل English و Maths).' },
        { n: 35, kind: 'write', prompt: 'What do you usually do in your free time?', promptAr: 'ماذا تفعل عادةً في وقت فراغك؟', lines: 1,
          accept: ['I usually read books in my free time.', 'I usually play football in my free time.', 'I usually read books.', 'I usually read stories.', 'I usually play football.', 'I usually watch TV.', 'I usually visit my friends.', 'I usually play with my friends.', 'I usually listen to music.', 'I usually draw pictures.', 'I usually help my mother.', 'I read books.', 'I play football.', 'I watch TV.'],
          model: 'I usually read books in my free time.',
          modelAr: 'عادةً أقرأ الكتب في وقت فراغي.',
          explainAr: 'سؤال شخصي عن عادة، فتُقبل أي إجابة صحيحة بجملة كاملة بالمضارع البسيط: I usually + فعل مجرّد (read, play, watch …) + in my free time.' },
      ],
    },
    {
      letter: 'G',
      title: 'Write a 50-word paragraph about ONE of the following topics:',
      titleAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد من الموضوعين التاليين:',
      marks: 50,
      writing: {
        topic: 'Write a 50-word paragraph about ONE of the following topics: Topic 1: Your life in twenty years’ time. Topic 2: A person who positively affected your life.',
        topicAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد: الموضوع 1: حياتك بعد عشرين عاماً. الموضوع 2: شخص أثّر في حياتك تأثيراً إيجابياً.',
        words: 50,
        points: ['Topic 1: Your life in twenty years’ time.', 'Topic 2: A person who positively affected your life.'],
        model: 'Topic 1: In twenty years’ time, I will be thirty-four years old. I will be a doctor because I want to help sick people. I will be married and I will have two children. We will live in a nice house near the sea, but it will not be very big. I think my life will be comfortable and happy.\n\nTopic 2: My father is the person who affected my life positively. He works hard to give us everything we need. He always tells me to be honest and to respect others. When I failed a test, he encouraged me to study harder and never give up. He inspired me to help people in our community. I am proud of him.',
        modelAr: 'الموضوع 1: بعد عشرين عاماً سأكون في الرابعة والثلاثين من عمري. سأكون طبيباً لأنني أريد أن أساعد المرضى. سأكون متزوجاً وسيكون لديّ طفلان. سنعيش في منزل جميل قرب البحر، لكنه لن يكون كبيراً جداً. أظن أن حياتي ستكون مريحة وسعيدة.\n\nالموضوع 2: أبي هو الشخص الذي أثّر في حياتي تأثيراً إيجابياً. إنه يعمل بجد ليعطينا كل ما نحتاجه. يقول لي دائماً أن أكون صادقاً وأن أحترم الآخرين. عندما رسبتُ في اختبار شجّعني على أن أدرس بجد أكبر وألّا أستسلم أبداً. ألهمني أن أساعد الناس في مجتمعنا. أنا فخور به.',
        checklistAr: [
          'اخترتُ موضوعاً واحداً فقط وكتبتُ عنه وحده.',
          'كتبتُ نحو 50 كلمة في فقرة واحدة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ الزمن المناسب: المستقبل will لحياتي بعد عشرين عاماً، والمضارع البسيط والماضي البسيط للحديث عن الشخص الذي أثّر فيّ.',
          'استخدمتُ أدوات ربط (and, but, because, when) وضمير وصل مثل who.',
          'ذكرتُ في الموضوع الثاني من هو الشخص، وماذا فعل، وكيف ألهمني فعل الخير.',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
