import type { Exam } from '../../../engine/types'

// The real 2026 Basic Education Certificate English paper (Syria, Grade 9), typed in exactly as printed,
// with the official answer key. 400 marks, an hour and a half.
export const term2A: Exam = {
  id: 't2-a',
  term: 2,
  title: 'Certificate Exam 2026 — (A)',
  titleAr: 'امتحان شهادة التعليم الأساسي 2026 — النموذج (A)',
  minutes: 90,
  totalMarks: 400,
  real: true,
  sourceAr: 'امتحان شهادة التعليم الأساسي الحقيقي في اللغة الإنكليزية، دورة 2026 (الجمهورية العربية السورية — وزارة التربية والتعليم)، كما طُبع، مع سلّم التصحيح الرسمي وشرح كل إجابة.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text then choose the correct answer a, b, c, or d:',
      titleAr: 'اقرأ النص التالي ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 50,
      passage: {
        paragraphs: [
          'An unemployed man went to apply for a job with Microsoft as a cleaner. The manager asked him for his email to send him a form to complete and tell him when he could start. The man said that he had no computer or email address.',
          'The manager told him that he virtually didn’t exist and therefore couldn’t be employed.',
          'The man started buying tomatoes in bulk then selling them. Within less than 2 hours, he sold all the tomatoes at 100% profit. Getting up early every day and going to bed late, he multiplied his profits quickly.',
          'By the end of the second year, he became the owner of a fleet of trucks and the manager of a staff of a hundred former unemployed people.',
          'Planning for the future of his wife and children, he decided to buy life insurance.',
        ],
        paragraphsAr: [
          'ذهب رجل عاطل عن العمل ليتقدّم إلى وظيفة عامل تنظيف في شركة مايكروسوفت. طلب منه المدير بريده الإلكتروني ليرسل إليه استمارة يملؤها ويخبره متى يستطيع أن يبدأ العمل. قال الرجل إنه لا يملك حاسوباً ولا عنوان بريد إلكتروني.',
          'قال له المدير إنه غير موجود افتراضياً (على الإنترنت)، ولذلك لا يمكن توظيفه.',
          'بدأ الرجل يشتري البندورة بالجملة ثم يبيعها. وفي أقل من ساعتين باع كل البندورة بربح 100%. وبالاستيقاظ باكراً كل يوم والنوم متأخراً، ضاعف أرباحه بسرعة.',
          'وبحلول نهاية السنة الثانية أصبح مالكاً لأسطول من الشاحنات ومديراً لفريق من مئة شخص كانوا عاطلين عن العمل.',
          'وتخطيطاً لمستقبل زوجته وأطفاله، قرّر أن يشتري تأميناً على الحياة.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer a, b, c, or d:',
          titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
          marks: 50,
          questions: [
            { n: 1, kind: 'mcq', prompt: 'The manager didn’t employ the man because he ……', promptAr: 'لم يوظّف المدير الرجل لأنه ___', options: ['had an email', 'didn’t have an email', 'had a computer', 'was lazy'], answer: 1,
              explainAr: 'قال الرجل "he had no computer or email address"، فقال له المدير إنه غير موجود افتراضياً ولا يمكن توظيفه. إذن السبب "didn’t have an email". أما "had a computer" و"had an email" فعكس ما في النص، و"was lazy" غير مذكور (بل كان مجتهداً).' },
            { n: 2, kind: 'mcq', prompt: 'After the manager rejected the man, he started ……', promptAr: 'بعد أن رفضه المدير، بدأ الرجل ___', options: ['selling tomatoes', 'studying', 'cleaning offices', 'washing cars'], answer: 0,
              explainAr: 'الفقرة الثالثة: "The man started buying tomatoes in bulk then selling them" — بدأ يشتري البندورة بالجملة ويبيعها، فالجواب "selling tomatoes".' },
            { n: 3, kind: 'mcq', prompt: 'The man …… his profits quickly because he worked hard.', promptAr: 'الرجل ___ أرباحه بسرعة لأنه عمل بجد.', options: ['decreased', 'lost', 'increased', 'reduced'], answer: 2,
              explainAr: 'في النص "he multiplied his profits quickly" أي ضاعف أرباحه، وأقرب معنى لها "increased" (زاد). أما "decreased" و"reduced" فتعنيان أنقص، و"lost" خسر.' },
            { n: 4, kind: 'mcq', prompt: 'He became the owner of a fleet after ……', promptAr: 'أصبح مالكاً لأسطول بعد ___', options: ['two years', 'two months', 'two hours', 'two days'], answer: 0,
              explainAr: 'الفقرة الرابعة: "By the end of the second year, he became the owner of a fleet of trucks" — بحلول نهاية السنة الثانية، أي بعد "two years". أما "2 hours" فهي المدة التي باع فيها البندورة، لا مدة امتلاك الأسطول.' },
            { n: 5, kind: 'mcq', prompt: 'Planning for the future, he decided to buy life insurance for ……', promptAr: 'تخطيطاً للمستقبل، قرّر أن يشتري تأميناً على الحياة لـ ___', options: ['his employees', 'his friends', 'his manager', 'his family'], answer: 3,
              explainAr: 'آخر جملة: "Planning for the future of his wife and children" — زوجته وأطفاله هم عائلته، فالجواب "his family".' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 50,
      passage: {
        paragraphs: [
          'In 1912, the “Titanic” hit an iceberg on its first trip across the Atlantic. It was carrying 2207 people, but it had taken on enough lifeboats for only 1178 people. Not more than 651 of the passengers were able to get into lifeboats. Most of the passengers hadn’t lived long; 1502 people had lost their lives. Nobody had prepared for such a tragedy. Nobody had believed that the Titanic could sink.',
          'The steamship company had thought that its ship would be completely safe in all situations. The passengers had not yet received their lifeboat numbers, nor had they practiced lifeboat drill before the accident.',
          'The ship had already received 6 ice warnings on its radio when it hit the iceberg. Nevertheless, it had not changed its direction or its speed.',
        ],
        paragraphsAr: [
          'في عام 1912 اصطدمت السفينة "تايتانيك" بجبل جليدي في رحلتها الأولى عبر المحيط الأطلسي. كانت تحمل 2207 أشخاص، لكنها لم تحمل قوارب نجاة إلا لـ 1178 شخصاً فقط. ولم يتمكّن أكثر من 651 راكباً من الصعود إلى قوارب النجاة. لم يعش معظم الركاب طويلاً؛ فقد فقد 1502 شخص حياتهم. لم يكن أحد قد استعدّ لمأساة كهذه، ولم يكن أحد يصدّق أن التايتانيك يمكن أن تغرق.',
          'كانت شركة السفن البخارية تظن أن سفينتها ستكون آمنة تماماً في كل الظروف. ولم يكن الركاب قد تسلّموا أرقام قوارب النجاة الخاصة بهم بعد، ولم يكونوا قد تدرّبوا على تمرين قوارب النجاة قبل الحادث.',
          'كانت السفينة قد تلقّت 6 تحذيرات من الجليد عبر الراديو حين اصطدمت بالجبل الجليدي. ومع ذلك لم تغيّر اتجاهها ولا سرعتها.',
        ],
      },
      groups: [
        {
          title: 'Write true (T) or false (F):',
          titleAr: 'اكتب صح (T) أو خطأ (F):',
          marks: 30,
          questions: [
            { n: 6, kind: 'truefalse', prompt: 'There were 2207 passengers on the ship.', promptAr: 'كان على متن السفينة 2207 ركاب.', answer: true,
              explainAr: 'صح: النص يقول "It was carrying 2207 people" — كانت تحمل 2207 أشخاص.' },
            { n: 7, kind: 'truefalse', prompt: 'The Titanic wasn’t carrying enough lifeboats for all the passengers.', promptAr: 'لم تكن التايتانيك تحمل قوارب نجاة كافية لكل الركاب.', answer: true,
              explainAr: 'صح: كانت تحمل 2207 أشخاص لكن "it had taken on enough lifeboats for only 1178 people" — القوارب تكفي 1178 شخصاً فقط.' },
            { n: 8, kind: 'truefalse', prompt: 'The passengers had received their lifeboat numbers before the accident.', promptAr: 'كان الركاب قد تسلّموا أرقام قوارب النجاة قبل الحادث.', answer: false,
              explainAr: 'خطأ: النص يقول "The passengers had not yet received their lifeboat numbers" — لم يكونوا قد تسلّموا أرقامهم بعد.' },
          ],
        },
        {
          title: 'Answer the following questions about the text:',
          titleAr: 'أجب عن الأسئلة التالية حول النص:',
          marks: 20,
          questions: [
            { n: 9, kind: 'write', prompt: 'How many passengers had lost their lives?', promptAr: 'كم عدد الركاب الذين فقدوا حياتهم؟', lines: 1,
              accept: ['1502 passengers had lost their lives.', '1502 people had lost their lives.', '1502 passengers lost their lives.', '1502 people lost their lives.', '1502 passengers.', '1502 people.', '1502'],
              model: '1502 passengers had lost their lives.',
              modelAr: 'فقد 1502 راكباً حياتهم.',
              explainAr: 'الجواب في الفقرة الأولى: "1502 people had lost their lives". أجب بجملة كاملة واستعمل الماضي التام نفسه had lost.' },
            { n: 10, kind: 'write', prompt: 'Why did the ship hit the iceberg?', promptAr: 'لماذا اصطدمت السفينة بالجبل الجليدي؟', lines: 2,
              accept: ['Because it had not changed its direction or its speed.', 'Because it had not changed its direction or speed.', 'It hit the iceberg because it had not changed its direction or its speed.', 'Because the ship had not changed its direction or its speed.', 'Because it did not change its direction or its speed.', 'It had not changed its direction or its speed.'],
              model: 'Because it had not changed its direction or its speed.',
              modelAr: 'لأنها لم تغيّر اتجاهها ولا سرعتها.',
              explainAr: 'السؤال بـ Why فنبدأ بـ Because. آخر جملة في النص: "Nevertheless, it had not changed its direction or its speed" — مع أنها تلقّت 6 تحذيرات من الجليد لم تغيّر اتجاهها ولا سرعتها.' },
          ],
        },
      ],
    },
    {
      letter: 'C',
      title: 'Choose the correct answer a, b, c or d:',
      titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 150,
      questions: [
        { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'A lift was put to …… the disabled needs.', promptAr: 'وُضع مصعد ليـ ___ احتياجات ذوي الإعاقة.', options: ['ignore', 'meet', 'deny', 'refuse'], answer: 1,
          explainAr: 'التعبير الصحيح "meet the needs" = يلبّي الاحتياجات؛ فالمصعد وُضع ليلبّي احتياجات ذوي الإعاقة. أما "ignore" (يتجاهل) و"deny" (ينكر) و"refuse" (يرفض) فتعاكس المعنى.' },
        { n: 12, kind: 'mcq', topic: 'grammar', prompt: 'Don’t make fun …… people.', promptAr: 'لا تسخر ___ الناس.', options: ['of', 'in', 'to', 'under'], answer: 0,
          explainAr: 'التعبير الثابت "make fun of" = يسخر من. حرف الجر الذي يأتي معه دائماً "of".' },
        { n: 13, kind: 'mcq', topic: 'vocab', prompt: 'He has to pay …… for speeding.', promptAr: 'عليه أن يدفع ___ بسبب السرعة الزائدة.', options: ['an award', 'a pill', 'a prize', 'a fine'], answer: 3,
          explainAr: '"a fine" = غرامة (مخالفة) تُدفع عند مخالفة القانون مثل السرعة الزائدة. أما "an award" و"a prize" فجائزة تُنال ولا تُدفع، و"a pill" حبّة دواء.' },
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'She …… from university last year.', promptAr: 'هي ___ من الجامعة العام الماضي.', options: ['proved', 'made', 'graduated', 'lost'], answer: 2,
          explainAr: '"graduate from university" = تخرّج في الجامعة، وهو التعبير الذي يأتي مع from university. أما "proved" (أثبت) و"made" (صنع) و"lost" (أضاع) فلا تناسب المعنى.' },
        { n: 15, kind: 'mcq', topic: 'tense', prompt: 'They …… a new bridge nowadays.', promptAr: 'إنهم ___ جسراً جديداً هذه الأيام.', options: ['are building', 'built', 'had built', 'build'], answer: 0,
          explainAr: 'الكلمة "nowadays" (هذه الأيام) تدل على عمل مستمر في الفترة الحالية، فنستخدم المضارع المستمر "are building". "built" و"had built" للماضي.' },
        { n: 16, kind: 'mcq', topic: 'tense', prompt: 'My brother was using the computer while I …… for my trip.', promptAr: 'كان أخي يستخدم الحاسوب بينما ___ أغراضي لرحلتي.', options: ['am packing', 'was packing', 'have packed', 'will pack'], answer: 1,
          explainAr: 'بعد while يصف الجزآن حدثين مستمرين في الوقت نفسه في الماضي؛ الجزء الأول "was using" ماضٍ مستمر، فنكمل بالماضي المستمر "was packing".' },
        { n: 17, kind: 'mcq', topic: 'tense', prompt: 'By the time mum arrived, I …… dinner.', promptAr: 'حين وصلت أمي كنتُ قد ___ العشاء.', options: ['prepare', 'will prepare', 'have prepared', 'had prepared'], answer: 3,
          explainAr: '"By the time" + ماضٍ بسيط (arrived) يعني أن الحدث الآخر تمّ قبله، فنستخدم الماضي التام "had prepared" (كنت قد حضّرت).' },
        { n: 18, kind: 'mcq', topic: 'tense', prompt: 'I think Brazil …… the next World Cup.', promptAr: 'أعتقد أن البرازيل ___ كأس العالم القادمة.', options: ['was winning', 'won', 'will win', 'has won'], answer: 2,
          explainAr: '"I think" مع "the next World Cup" توقّع لحدث في المستقبل، فنستخدم "will win". بقية الخيارات ماضٍ أو مضارع تام.' },
        { n: 19, kind: 'mcq', topic: 'grammar', prompt: 'I would like to ask …… questions.', promptAr: 'أودّ أن أطرح ___ أسئلة.', options: ['a little', 'a', 'much', 'a few'], answer: 3,
          explainAr: '"questions" اسم معدود جمع، فنستخدم "a few" (بعض/قليل من). أما "a little" و"much" فمع الاسم غير المعدود، و"a" مع المفرد فقط.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'Our house …… last year.', promptAr: 'منزلنا ___ العام الماضي.', options: ['decorated', 'is decorating', 'was decorated', 'has decorated'], answer: 2,
          explainAr: 'المنزل لا يزيّن نفسه، بل يُزيَّن، فالجملة مبني للمجهول. و"last year" تدل على الماضي، فنستخدم "was decorated" (was + التصريف الثالث).' },
        { n: 21, kind: 'mcq', topic: 'reported', prompt: 'She asked me if I …… the festival.', promptAr: 'سألتني إن كنتُ ___ بالمهرجان.', options: ['had enjoyed', 'am enjoying', 'has enjoyed', 'enjoy'], answer: 0,
          explainAr: 'في الكلام المنقول بعد فعل ماضٍ (asked) نرجع الزمن خطوة إلى الماضي، فالسؤال الأصلي "Did you enjoy…?" يصبح "if I had enjoyed". كما أن "has enjoyed" لا تأتي مع I.' },
        { n: 22, kind: 'mcq', topic: 'grammar', prompt: 'He didn’t eat a lot, …… he?', promptAr: 'لم يأكل كثيراً، ___ ؟ (أليس كذلك)', options: ['hasn’t', 'did', 'doesn’t', 'does'], answer: 1,
          explainAr: 'السؤال الذيلي يأخذ الفعل المساعد نفسه بعكس النفي: الجملة منفية بـ didn’t (ماضٍ)، فيكون الذيل مثبتاً "did he?".' },
        { n: 23, kind: 'mcq', topic: 'grammar', prompt: 'My sister teaches in a school …… we all studied.', promptAr: 'أختي تدرّس في مدرسة ___ درسنا جميعاً فيها.', options: ['where', 'who', 'whose', 'when'], answer: 0,
          explainAr: 'بعد اسم مكان (a school) وتليه جملة كاملة (we all studied) نستخدم ضمير الوصل "where". "who" للعاقل، "whose" للملكية، "when" للزمن.' },
        { n: 24, kind: 'mcq', topic: 'grammar', prompt: 'He wishes he …… so old.', promptAr: 'يتمنّى لو أنه ___ كبيراً في السن إلى هذا الحد.', options: ['isn’t', 'won’t be', 'hasn’t been', 'weren’t'], answer: 3,
          explainAr: 'للتمنّي عن الحاضر (عكس الواقع) نستخدم wish + الماضي البسيط، ومع فعل be نستخدم "were" مع كل الضمائر، فيصبح النفي "weren’t".' },
        { n: 25, kind: 'mcq', topic: 'pronunciation', prompt: 'The word which has a short vowel sound is ……', promptAr: 'الكلمة التي فيها صوت علّة قصير هي ___', options: ['part', 'man', 'car', 'calm'], answer: 1,
          explainAr: 'في "man" يُلفظ الحرف a صوتاً قصيراً /æ/. أما "part" و"car" و"calm" ففيها الصوت الطويل /ɑː/.' },
      ],
    },
    {
      letter: 'D',
      title: 'Match each item in (A) with the suitable choice from (B):',
      titleAr: 'صِل كل عبارة من العمود (A) بما يناسبها من العمود (B):',
      marks: 50,
      questions: [
        { n: 26, kind: 'mcq', prompt: 'He arrived at seven', promptAr: 'وصل في السابعة', options: ['earn people’s trust', 'if you want all the options.', 'when it was nearly dark.', 'be surrounded by rivers.', 'for two months.'], answer: 2,
          explainAr: '"He arrived at seven when it was nearly dark." — وصل في السابعة حين كان الظلام قد حلّ تقريباً. "when" هنا تصف الوقت المذكور (at seven).' },
        { n: 27, kind: 'mcq', prompt: 'You should be honest to', promptAr: 'يجب أن تكون صادقاً لكي', options: ['earn people’s trust', 'if you want all the options.', 'when it was nearly dark.', 'be surrounded by rivers.', 'for two months.'], answer: 0,
          explainAr: '"You should be honest to earn people’s trust." — يجب أن تكون صادقاً لتكسب ثقة الناس. بعد to (للغاية) يأتي فعل مجرّد: earn.' },
        { n: 28, kind: 'mcq', prompt: 'You may end with nothing', promptAr: 'قد ينتهي بك الأمر بلا شيء', options: ['earn people’s trust', 'if you want all the options.', 'when it was nearly dark.', 'be surrounded by rivers.', 'for two months.'], answer: 1,
          explainAr: '"You may end with nothing if you want all the options." — قد ينتهي بك الأمر بلا شيء إن أردت كل الخيارات (الطمع يضيّع كل شيء).' },
        { n: 29, kind: 'mcq', prompt: 'He has worked here', promptAr: 'لقد عمل هنا', options: ['earn people’s trust', 'if you want all the options.', 'when it was nearly dark.', 'be surrounded by rivers.', 'for two months.'], answer: 4,
          explainAr: '"He has worked here for two months." — المضارع التام has worked يأتي مع for + مدة زمنية: for two months (منذ شهرين).' },
        { n: 30, kind: 'mcq', prompt: 'Future cities should', promptAr: 'يجب أن تكون مدن المستقبل', options: ['earn people’s trust', 'if you want all the options.', 'when it was nearly dark.', 'be surrounded by rivers.', 'for two months.'], answer: 3,
          explainAr: '"Future cities should be surrounded by rivers." — بعد should يأتي فعل مجرّد، و"be surrounded" مبني للمجهول: يجب أن تكون محاطة بالأنهار. أما "earn people’s trust" فتناسب الإنسان لا المدن.' },
      ],
    },
    {
      letter: 'E',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 30,
      questions: [
        { n: 31, kind: 'write', topic: 'grammar', prompt: '{Hussam} drives the car.', promptAr: 'حسام يقود السيارة.', lines: 1,
          accept: ['Who drives the car?'],
          modelAr: 'من يقود السيارة؟',
          explainAr: 'المسطَّر شخص وهو الفاعل، فنسأل بـ Who ونُبقي الفعل كما هو "drives" بلا do/does، لأن السؤال عن الفاعل.' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'Maya has studied Maths {since 2016}.', promptAr: 'درست مايا الرياضيات منذ عام 2016.', lines: 1,
          accept: ['How long has Maya studied Maths?', 'How long has Maya been studying Maths?', 'Since when has Maya studied Maths?', 'How long has she studied Maths?'],
          model: 'How long has Maya studied Maths?',
          modelAr: 'منذ متى تدرس مايا الرياضيات؟',
          explainAr: 'المسطَّر مدة تبدأ بـ since، فنسأل بـ How long. الجملة مضارع تام، فنقدّم has على الفاعل: How long has Maya studied Maths?' },
        { n: 33, kind: 'write', topic: 'grammar', prompt: 'I will be an English teacher {because it is my favourite subject}.', promptAr: 'سأصبح مدرّساً للغة الإنكليزية لأنها مادتي المفضلة.', lines: 1,
          accept: ['Why will you be an English teacher?'],
          modelAr: 'لماذا ستصبح مدرّساً للغة الإنكليزية؟',
          explainAr: 'المسطَّر سبب يبدأ بـ because، فنسأل بـ Why. الجملة مستقبل بـ will فنقدّم will على الفاعل، ويتحوّل I إلى you: Why will you be an English teacher?' },
      ],
    },
    {
      letter: 'F',
      title: 'Answer the following questions:',
      titleAr: 'أجب عن الأسئلة التالية:',
      marks: 20,
      questions: [
        { n: 34, kind: 'write', prompt: 'How old are you?', promptAr: 'كم عمرك؟', lines: 1,
          accept: ['I am fourteen years old.', 'I am 14 years old.', 'I am fourteen.', 'I am 14.', 'I am fifteen years old.', 'I am 15 years old.', 'I am fifteen.', 'I am thirteen years old.', 'I am 13 years old.', 'I am sixteen years old.', 'I am 16 years old.'],
          model: 'I am fourteen years old.',
          modelAr: 'عمري أربعة عشر عاماً.',
          explainAr: 'سؤال شخصي: تُقبل أي إجابة صحيحة عن عمرك الحقيقي بجملة كاملة. الصيغة: I am + العمر + years old (ويجوز I’m).' },
        { n: 35, kind: 'write', prompt: 'How often do you see your friends?', promptAr: 'كم مرة ترى أصدقاءك؟', lines: 1,
          accept: ['I see my friends once a week.', 'I see my friends twice a week.', 'I see my friends every day.', 'I see my friends at the weekend.', 'I see my friends every weekend.', 'I see my friends once a month.', 'I see them once a week.', 'I see them every day.', 'Once a week.', 'Every day.'],
          model: 'I see my friends once a week.',
          modelAr: 'أرى أصدقائي مرة في الأسبوع.',
          explainAr: 'سؤال شخصي بـ How often (كم مرة)، فتُقبل أي إجابة صحيحة بجملة كاملة تذكر عدد المرات، مثل once a week أو every day أو twice a month، مع الفعل في المضارع البسيط: I see my friends …' },
      ],
    },
    {
      letter: 'G',
      title: 'Write a 50-word paragraph about ONE of the following topics:',
      titleAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد من الموضوعين التاليين:',
      marks: 50,
      writing: {
        topic: 'Write a 50-word paragraph about ONE of the following topics: Topic 1: How your future house will be. Topic 2: Where you find happiness.',
        topicAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد: الموضوع 1: كيف سيكون منزلك في المستقبل. الموضوع 2: أين تجد السعادة.',
        words: 50,
        points: ['Topic 1: How your future house will be.', 'Topic 2: Where you find happiness.'],
        model: 'Topic 1: In the future, my house will be a smart house. It will have special gadgets that help us. I can control the lights and temperature with my voice. The fridge will tell us everything about our food. My house will keep us safe and make life easier and more fun every day.\n\nTopic 2: I find happiness in many places. I feel happy when I play with my friends. Spending time with my family makes me smile. I love being outside in nature, watching the trees and birds. Reading a good book or drawing also brings me joy. Happiness is all around if I look!',
        modelAr: 'الموضوع 1: في المستقبل سيكون منزلي منزلاً ذكياً. ستكون فيه أدوات خاصة تساعدنا. أستطيع التحكم بالأضواء ودرجة الحرارة بصوتي. سيخبرنا البرّاد بكل شيء عن طعامنا. سيحافظ منزلي على سلامتنا ويجعل الحياة أسهل وأكثر متعة كل يوم.\n\nالموضوع 2: أجد السعادة في أماكن كثيرة. أشعر بالسعادة عندما ألعب مع أصدقائي. قضاء الوقت مع عائلتي يجعلني أبتسم. أحب أن أكون في الطبيعة أراقب الأشجار والطيور. قراءة كتاب جيد أو الرسم يجلبان لي الفرح أيضاً. السعادة في كل مكان حولي إن نظرت!',
        checklistAr: [
          'اخترتُ موضوعاً واحداً فقط وكتبتُ عنه وحده.',
          'كتبتُ نحو 50 كلمة في فقرة واحدة مترابطة لها جملة بداية وجملة ختام.',
          'استخدمتُ الزمن المناسب: المستقبل will للمنزل في المستقبل، والمضارع البسيط للحديث عن السعادة.',
          'استخدمتُ أدوات ربط (and, when, also, because, or).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
