import type { Exam } from '../../../engine/types'

// A practice paper in the exact layout of the real 2026 Basic Education Certificate paper (400 marks, 90 minutes).
// Passage A: Activity Book Unit 10 "Hurry up Before the Gates are Shut!" (page 47).
// Passage B: Student's Book Unit 4 "Autonomous Vehicles" (page 21).
// Sections C–E: sentences from Units 2, 4, 7 and 11 (Student's Book and Activity Book).
// Section G: the Activity Book's Unit 4 writing task (the planes of the future) and the book's Module 6 task
// (a person who positively affected your life).
export const term2E: Exam = {
  id: 't2-e',
  term: 2,
  title: 'Certificate Exam — Model (E)',
  titleAr: 'نموذج امتحان الشهادة (E)',
  minutes: 90,
  totalMarks: 400,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان شهادة التعليم الأساسي 2026 (400 درجة، ساعة ونصف)، مبنيّ فقط على كتابَيك: النص A من كتاب النشاط (الوحدة 10: «Hurry up Before the Gates are Shut!»)، والنص B من كتاب الطالب (الوحدة 4: «Autonomous Vehicles»)، وبقية الأسئلة من جمل الوحدات 2 و4 و7 و11 في كتاب الطالب وكتاب النشاط.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text then choose the correct answer a, b, c, or d:',
      titleAr: 'اقرأ النص التالي ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 50,
      passage: {
        paragraphs: [
          'Once, a king and a lazy man named Hani were very good friends. One morning, the king said, "Why don’t you work to earn some money?" Hani said, "No one offers me a job. My enemies told everyone that I never do any work in time." The kind king said, "You can go into my treasury and collect as much wealth as you can, but you have to finish before sunset." Hani was so happy and rushed home to tell his wife. She said, "Go and get the gold coins and gems now." He said: "I cannot go now. I am so hungry. I’d like to eat first."',
          'After lunch, he took a nap for an hour. Then in the late afternoon, he picked some bags and went to the palace. On the way, he felt hot so he sat under a tree to rest and drink some water. Two hours later, when he wanted to move on, he saw a man showing some magic tricks. He stopped to watch for an hour again. On the way to the palace, he met an old friend and chatted with him for some time. When he reached the palace, it was already sunset time. The palace gates had been shut.',
        ],
        paragraphsAr: [
          'كان ملكٌ ورجلٌ كسول اسمه هاني صديقين حميمين. وذات صباح قال الملك: "لماذا لا تعمل لتكسب بعض المال؟" فقال هاني: "لا أحد يعرض عليّ عملاً. لقد أخبر أعدائي الجميع أنني لا أنجز أيّ عمل في وقته أبداً." فقال الملك الطيّب: "يمكنك أن تدخل خزانتي وتجمع من الثروة قدر ما تستطيع، لكن عليك أن تنتهي قبل غروب الشمس." ففرح هاني كثيراً وأسرع إلى البيت ليخبر زوجته. فقالت: "اذهب واجلب القطع الذهبية والأحجار الكريمة الآن." فقال: "لا أستطيع الذهاب الآن. أنا جائع جداً. أودّ أن آكل أولاً."',
          'بعد الغداء أخذ قيلولة لمدة ساعة. ثم في آخر العصر أخذ بعض الأكياس وذهب إلى القصر. وفي الطريق شعر بالحرّ فجلس تحت شجرة ليستريح ويشرب بعض الماء. وبعد ساعتين، عندما أراد أن يتابع طريقه، رأى رجلاً يعرض بعض الحيل السحرية، فتوقّف ليتفرّج ساعة أخرى. وفي الطريق إلى القصر التقى صديقاً قديماً وتحدّث معه بعض الوقت. وعندما وصل إلى القصر كان وقت الغروب قد حلّ. كانت بوابات القصر قد أُغلقت.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer a, b, c, or d:',
          titleAr: 'اختر الإجابة الصحيحة:',
          marks: 50,
          questions: [
            { n: 1, kind: 'mcq', prompt: 'Nobody offered Hani a job because ……….', promptAr: 'لم يعرض أحدٌ على هاني عملاً لأنّ ……….',
              options: ['the king didn’t like him', 'his enemies told everyone that he never did any work in time', 'he was always hungry', 'he had a lot of money'], answer: 1,
              explainAr: 'الصواب "his enemies told everyone that he never did any work in time"، ففي النص قال هاني: "No one offers me a job. My enemies told everyone that I never do any work in time" أي أخبر أعداؤه الجميع أنه لا ينجز عمله في وقته.' },
            { n: 2, kind: 'mcq', prompt: 'Hani was so happy and ………. home to tell his wife.', promptAr: 'فرح هاني كثيراً و………. إلى البيت ليخبر زوجته.', topic: 'vocab',
              options: ['hurried', 'walked slowly', 'forgot to go', 'refused to go'], answer: 0,
              explainAr: 'الصواب "hurried"، لأن النص يقول "Hani was so happy and rushed home"، والفعل rushed يعني أسرع، وهو نفس معنى hurried.' },
            { n: 3, kind: 'mcq', prompt: 'The king told Hani that he had to finish collecting the wealth before ……….', promptAr: 'أخبر الملكُ هانياً أن عليه أن ينتهي من جمع الثروة قبل ……….',
              options: ['lunch', 'midnight', 'sunrise', 'sunset'], answer: 3,
              explainAr: 'الصواب "sunset"، فقد قال الملك: "you have to finish before sunset" أي قبل غروب الشمس.' },
            { n: 4, kind: 'mcq', prompt: 'On the way, Hani sat under a tree because he felt ……….', promptAr: 'في الطريق جلس هاني تحت شجرة لأنه شعر بـ ……….',
              options: ['sad', 'cold', 'hot', 'afraid'], answer: 2,
              explainAr: 'الصواب "hot"، ففي النص: "On the way, he felt hot so he sat under a tree to rest and drink some water" أي شعر بالحرّ فجلس تحت شجرة.' },
            { n: 5, kind: 'mcq', prompt: 'When Hani reached the palace, ……….', promptAr: 'عندما وصل هاني إلى القصر ……….',
              options: ['the king was waiting for him', 'the palace gates had been shut', 'his wife was there', 'he collected a lot of gold'], answer: 1,
              explainAr: 'الصواب "the palace gates had been shut"، فآخر جملتين في النص: "When he reached the palace, it was already sunset time. The palace gates had been shut" أي وصل بعد الغروب فوجد البوابات مغلقة.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 50,
      passage: {
        paragraphs: [
          'Some people think that autonomous vehicles will change our lives for the better. They think that they will be safer and transportation will be more efficient. However, others believe that autonomous vehicles will cause many problems that need to be solved before they are allowed to become a part of our daily lives.',
          'First, driverless cars will increase unemployment. Thousands of drivers will lose their jobs if autonomous vehicles are allowed to take over the roads. Truck drivers, delivery drivers, taxi drivers and many other kinds of drivers will lose their jobs. This increase in unemployment could cause serious social problems.',
          'Second, companies and governments will lose money. For example, insurance companies now get about fifty percent of their income from car insurance. Governments and cities, too, will lose much money from parking, speeding fines and petrol taxes.',
          'Finally, there is no planning. Dramatic change is coming, but governments haven’t begun thinking about it. Only some American cities have done long-term planning. Driverless cars could arrive by 2030, but most government officials and transport ministers are only worried about short-term problems.',
        ],
        paragraphsAr: [
          'يعتقد بعض الناس أن المركبات ذاتية القيادة ستغيّر حياتنا نحو الأفضل؛ فهم يظنّون أنها ستكون أكثر أماناً وأن النقل سيصبح أكثر كفاءة. غير أن آخرين يعتقدون أن المركبات ذاتية القيادة ستسبّب مشكلات كثيرة يجب حلّها قبل السماح لها بأن تصبح جزءاً من حياتنا اليومية.',
          'أولاً، ستزيد السيارات بلا سائق من البطالة؛ فآلاف السائقين سيفقدون وظائفهم إذا سُمح للمركبات ذاتية القيادة بالسيطرة على الطرقات. سيفقد سائقو الشاحنات وسائقو التوصيل وسائقو سيارات الأجرة وأنواع أخرى كثيرة من السائقين وظائفهم. وقد تسبّب هذه الزيادة في البطالة مشكلات اجتماعية خطيرة.',
          'ثانياً، ستخسر الشركات والحكومات أموالاً. فعلى سبيل المثال، تحصل شركات التأمين الآن على نحو خمسين بالمئة من دخلها من تأمين السيارات. وستخسر الحكومات والمدن أيضاً أموالاً كثيرة من رسوم مواقف السيارات ومخالفات السرعة وضرائب البنزين.',
          'أخيراً، لا يوجد تخطيط. إن تغييراً كبيراً قادم، لكنّ الحكومات لم تبدأ بالتفكير فيه. فقط بعض المدن الأمريكية قامت بتخطيط طويل الأمد. قد تصل السيارات بلا سائق بحلول عام 2030، لكنّ معظم المسؤولين الحكوميين ووزراء النقل لا يهتمّون إلا بالمشكلات قصيرة الأمد.',
        ],
      },
      groups: [
        {
          title: 'Write true (T) or false (F):',
          titleAr: 'اكتب صح (T) أو خطأ (F):',
          marks: 30,
          questions: [
            { n: 6, kind: 'truefalse', prompt: 'Some people think that transportation will be more efficient with autonomous vehicles.', promptAr: 'يعتقد بعض الناس أن النقل سيصبح أكثر كفاءة مع المركبات ذاتية القيادة.', answer: true,
              explainAr: 'صح (T): في الفقرة الأولى "They think that they will be safer and transportation will be more efficient".' },
            { n: 7, kind: 'truefalse', prompt: 'Only taxi drivers will lose their jobs.', promptAr: 'سائقو سيارات الأجرة فقط هم من سيفقدون وظائفهم.', answer: false,
              explainAr: 'خطأ (F): النص يقول "Truck drivers, delivery drivers, taxi drivers and many other kinds of drivers will lose their jobs"، فليس سائقو الأجرة وحدهم.' },
            { n: 8, kind: 'truefalse', prompt: 'Most government officials are worried about long-term problems.', promptAr: 'معظم المسؤولين الحكوميين قلقون بشأن المشكلات طويلة الأمد.', answer: false,
              explainAr: 'خطأ (F): النص يقول "most government officials and transport ministers are only worried about short-term problems" أي المشكلات قصيرة الأمد فقط.' },
          ],
        },
        {
          title: 'Answer the following questions about the text:',
          titleAr: 'أجب عن الأسئلة التالية حول النص:',
          marks: 20,
          questions: [
            { n: 9, kind: 'write', prompt: 'How much of their income do insurance companies get from car insurance?', promptAr: 'ما مقدار الدخل الذي تحصل عليه شركات التأمين من تأمين السيارات؟', lines: 2,
              accept: ['Insurance companies now get about fifty percent of their income from car insurance.', 'They get about fifty percent of their income from car insurance.', 'They get about fifty percent.', 'About fifty percent.', 'About 50 percent.', 'About 50%.', 'Fifty percent.', 'They get about 50% of their income from car insurance.', 'Insurance companies get about fifty percent of their income from car insurance.'],
              model: 'Insurance companies now get about fifty percent of their income from car insurance.',
              modelAr: 'تحصل شركات التأمين الآن على نحو خمسين بالمئة من دخلها من تأمين السيارات.',
              explainAr: 'الجواب في الفقرة الثالثة: "insurance companies now get about fifty percent of their income from car insurance".' },
            { n: 10, kind: 'write', prompt: 'Why will thousands of drivers lose their jobs?', promptAr: 'لماذا سيفقد آلاف السائقين وظائفهم؟', lines: 2,
              accept: ['Because autonomous vehicles are allowed to take over the roads.', 'Because autonomous vehicles will be allowed to take over the roads.', 'If autonomous vehicles are allowed to take over the roads.', 'Because autonomous vehicles will take over the roads.', 'Because driverless cars will take over the roads.', 'Because driverless cars will increase unemployment.', 'Because of driverless cars.', 'Because of autonomous vehicles.'],
              model: 'Because autonomous vehicles will be allowed to take over the roads.',
              modelAr: 'لأنه سيُسمح للمركبات ذاتية القيادة بالسيطرة على الطرقات.',
              explainAr: 'الجواب في الفقرة الثانية: "Thousands of drivers will lose their jobs if autonomous vehicles are allowed to take over the roads". السؤال بـ Why فنبدأ الجواب بـ Because.' },
          ],
        },
      ],
    },
    {
      letter: 'C',
      title: 'Choose the correct answer a, b, c or d:',
      titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 150,
      questions: [
        { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'The visually impaired person contacts the initiative administration and ………. them with the books needed.', promptAr: 'يتواصل الشخص الكفيف مع إدارة المبادرة و………. هم بالكتب المطلوبة.',
          options: ['provides', 'announces', 'records', 'publishes'], answer: 0,
          explainAr: 'الصواب "provides"، ومعناها يزوّد (provide somebody with something). الجملة من نص Light Initiative في الوحدة 2، وprovide من كلماتها المفتاحية: to give somebody something or to supply.' },
        { n: 12, kind: 'mcq', topic: 'vocab', prompt: 'Trust can be destroyed ………. no time.', promptAr: 'يمكن أن تُهدَم الثقة في لمح البصر.',
          options: ['on', 'at', 'of', 'in'], answer: 3,
          explainAr: 'الصواب "in"، فالتعبير in no time يعني بسرعة كبيرة / في لمح البصر، كما في نص Touch People’s Hearts في الوحدة 11: "it can be destroyed in no time".' },
        { n: 13, kind: 'mcq', topic: 'vocab', prompt: 'Do you have ………. on your house and its contents?', promptAr: 'هل لديك ………. على منزلك ومحتوياته؟',
          options: ['income', 'insurance', 'delivery', 'an official'], answer: 1,
          explainAr: 'الصواب "insurance" أي تأمين (protection against future loss)، وهي من كلمات نص Autonomous Vehicles في الوحدة 4.' },
        { n: 14, kind: 'mcq', topic: 'vocab', prompt: 'Some of the ………. had been in the icy water for hours when they were saved.', promptAr: 'كان بعض ………. في المياه الجليدية لساعات عندما أُنقذوا.',
          options: ['icebergs', 'lifeboats', 'survivors', 'warnings'], answer: 2,
          explainAr: 'الصواب "survivors" أي الناجون (a person who continues to live after danger)، والجملة من نص Titanic في الوحدة 7.' },
        { n: 15, kind: 'mcq', topic: 'tense', prompt: 'She’s very experienced now. She ………. a volunteer for two years.', promptAr: 'إنها ذات خبرة كبيرة الآن. لقد كانت متطوّعة منذ سنتين.',
          options: ['has been', 'is being', 'be', 'are'], answer: 0,
          explainAr: 'الصواب "has been"، فوجود for two years مع حدث بدأ في الماضي وما زال مستمراً يتطلّب المضارع التام has/have + التصريف الثالث (الوحدة 2).' },
        { n: 16, kind: 'mcq', topic: 'tense', prompt: 'Selak’s near-death experiences began in January 1962 when he ………. by a train from Sarajevo to Dubrovnik.', promptAr: 'بدأت تجارب سيلاك مع الموت الوشيك في كانون الثاني 1962 عندما كان يسافر بالقطار من سراييفو إلى دوبروفنيك.',
          options: ['travels', 'has travelled', 'was travelling', 'will travel'], answer: 2,
          explainAr: 'الصواب "was travelling"، فهو الماضي المستمر لحدث كان جارياً عندما بدأ حدث آخر في الماضي (began). الجملة من نص Back to Life في كتاب النشاط، الوحدة 7.' },
        { n: 17, kind: 'mcq', topic: 'tense', prompt: 'I ………. snow until I went to Canada.', promptAr: 'لم أكن قد رأيت الثلج قطّ حتى ذهبت إلى كندا.',
          options: ['have never seen', 'never see', 'will never see', 'had never seen'], answer: 3,
          explainAr: 'الصواب "had never seen"، فالماضي التام (had + التصريف الثالث) يعبّر عن حال سبقت حدثاً ماضياً آخر (went)، كما في قاعدة الوحدة 7.' },
        { n: 18, kind: 'mcq', topic: 'tense', prompt: 'In the future, I think it ………. better to rethink about our health.', promptAr: 'في المستقبل أعتقد أنه سيكون من الأفضل أن نعيد التفكير في صحّتنا.',
          options: ['was', 'will be', 'has been', 'had been'], answer: 1,
          explainAr: 'الصواب "will be"، فنستخدم will للتنبّؤ بالمستقبل بعد I think. والجملة من نص Ecological Cities في كتاب النشاط، الوحدة 4: "It will be better to rethink about our health".' },
        { n: 19, kind: 'mcq', topic: 'grammar', prompt: 'There aren’t ………. students in the library.', promptAr: 'لا يوجد أيّ طلاب في المكتبة.',
          options: ['some', 'much', 'any', 'a little'], answer: 2,
          explainAr: 'الصواب "any"، لأن any تُستخدم في الجمل المنفية والاستفهامية (aren’t)، أما some ففي الجمل المثبتة، وmuch وa little مع غير المعدود وstudents معدود (المحدِّدات في الوحدة 4).' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'The Mona Lisa ………. by Leonardo da Vinci.', promptAr: 'رُسمت الموناليزا بيد ليوناردو دافنشي.',
          options: ['was painted', 'painted', 'is painting', 'was painting'], answer: 0,
          explainAr: 'الصواب "was painted"، فالجملة مبنية للمجهول في الماضي البسيط: was/were + التصريف الثالث + by + الفاعل (الوحدة 11).' },
        { n: 21, kind: 'mcq', topic: 'reported', prompt: '"Have you done your homework?" My mother asked me if I ………. my homework.', promptAr: '"هل أنهيت واجبك؟" سألتني أمي إن كنت قد أنهيت واجبي.',
          options: ['have done', 'had done', 'do', 'am doing'], answer: 1,
          explainAr: 'الصواب "had done"، ففي السؤال المنقول يتحوّل المضارع التام (have done) إلى الماضي التام (had done) لأن فعل النقل asked في الماضي، ونستخدم if لسؤال yes/no.' },
        { n: 22, kind: 'mcq', topic: 'grammar', prompt: 'Their services are absolutely free, ……….?', promptAr: 'خدماتهم مجانية تماماً، أليس كذلك؟',
          options: ['are they', 'don’t they', 'weren’t they', 'aren’t they'], answer: 3,
          explainAr: 'الصواب "aren’t they"، فالجملة مثبتة وفعلها are في المضارع، فيكون السؤال الذيلي منفياً بـ aren’t مع الضمير they العائد على services (من نص Light Initiative، الوحدة 2).' },
        { n: 23, kind: 'mcq', topic: 'grammar', prompt: 'The woman ………. bag was stolen went to the police station.', promptAr: 'ذهبت المرأة التي سُرقت حقيبتها إلى مركز الشرطة.',
          options: ['who', 'which', 'whose', 'where'], answer: 2,
          explainAr: 'الصواب "whose"، فهو ضمير الوصل الدالّ على الملكية (حقيبتها = whose bag)، ويأتي بعده اسم مباشرة.' },
        { n: 24, kind: 'mcq', topic: 'grammar', prompt: 'I don’t have an autonomous car. I wish I ………. one.', promptAr: 'لا أملك سيارة ذاتية القيادة. أتمنّى لو أملك واحدة.',
          options: ['had', 'have', 'will have', 'am having'], answer: 0,
          explainAr: 'الصواب "had"، فبعد wish للتمنّي في الحاضر يأتي الفعل في الماضي البسيط (I wish I had).' },
        { n: 25, kind: 'mcq', topic: 'pronunciation', prompt: 'The word which has the /ei/ sound is ……….', promptAr: 'الكلمة التي فيها الصوت /ei/ هي ……….',
          options: ['sheep', 'sail', 'bet', 'key'], answer: 1,
          explainAr: 'الصواب "sail"، ففيها الصوت المزدوج /ei/ مثل day وhate، أما sheep وkey ففيهما /i:/ وbet فيها /e/ (لفظ الوحدة 7).' },
      ],
    },
    {
      letter: 'D',
      title: 'Match each item in (A) with the suitable choice from (B):',
      titleAr: 'صِل كل عبارة في العمود (A) بما يناسبها من العمود (B):',
      marks: 50,
      questions: [
        { n: 26, kind: 'mcq', prompt: 'If you are told a secret by a friend,', promptAr: 'إذا أخبرك صديق بسرّ،',
          options: ['if you have a network.', 'more than 20,000 likes.', 'it stays between you and him/her.', 'to irrigate the dry land.', 'that had ever travelled on the sea.'], answer: 2,
          explainAr: 'الصواب "it stays between you and him/her": إذا أخبرك صديق بسرّ فإنه يبقى بينكما (نص Touch People’s Hearts، الوحدة 11).' },
        { n: 27, kind: 'mcq', prompt: 'The Titanic was the largest ship', promptAr: 'كانت تايتانيك أكبر سفينة',
          options: ['if you have a network.', 'more than 20,000 likes.', 'it stays between you and him/her.', 'to irrigate the dry land.', 'that had ever travelled on the sea.'], answer: 4,
          explainAr: 'الصواب "that had ever travelled on the sea": كانت تايتانيك أكبر سفينة أبحرت في البحر على الإطلاق (نص Titanic، الوحدة 7).' },
        { n: 28, kind: 'mcq', prompt: 'You can listen to the recordings', promptAr: 'يمكنك الاستماع إلى التسجيلات',
          options: ['if you have a network.', 'more than 20,000 likes.', 'it stays between you and him/her.', 'to irrigate the dry land.', 'that had ever travelled on the sea.'], answer: 0,
          explainAr: 'الصواب "if you have a network.": يمكنك الاستماع إلى تسجيلات Light Initiative إذا كان لديك اتصال بالشبكة (الوحدة 2).' },
        { n: 29, kind: 'mcq', prompt: 'Future cities can collect water and use solar power', promptAr: 'يمكن لمدن المستقبل أن تجمع الماء وتستخدم الطاقة الشمسية',
          options: ['if you have a network.', 'more than 20,000 likes.', 'it stays between you and him/her.', 'to irrigate the dry land.', 'that had ever travelled on the sea.'], answer: 3,
          explainAr: 'الصواب "to irrigate the dry land.": تستخدم مدن المستقبل الطاقة الشمسية لريّ الأرض الجافة (نص Ecological Cities، كتاب النشاط الوحدة 4).' },
        { n: 30, kind: 'mcq', prompt: 'Eight hours later, the page had attracted', promptAr: 'بعد ثماني ساعات كانت الصفحة قد جذبت',
          options: ['if you have a network.', 'more than 20,000 likes.', 'it stays between you and him/her.', 'to irrigate the dry land.', 'that had ever travelled on the sea.'], answer: 1,
          explainAr: 'الصواب "more than 20,000 likes.": بعد ثماني ساعات جذبت صفحة Suspended Coffees أكثر من 20,000 إعجاب (نص Pay It Forward، كتاب النشاط الوحدة 2).' },
      ],
    },
    {
      letter: 'E',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 30,
      questions: [
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'In Fatima’s opinion, schools will have {computers} for all students.', promptAr: 'برأي فاطمة، ستكون في المدارس حواسيب لجميع الطلاب.', lines: 1,
          accept: ['What will schools have for all students in Fatima’s opinion?', 'In Fatima’s opinion, what will schools have for all students?', 'What will schools have for all students?', 'What will schools have?'],
          model: 'In Fatima’s opinion, what will schools have for all students?',
          modelAr: 'برأي فاطمة، ماذا سيكون في المدارس لجميع الطلاب؟',
          explainAr: 'المسطَّر شيء (computers) فنسأل بـ What. الفعل will have مستقبل، فنقدّم will على الفاعل ويبقى have: What will schools have for all students? (من استماع الوحدة 4).' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'The Titanic hit an iceberg {in 1912}.', promptAr: 'اصطدمت تايتانيك بجبل جليدي عام 1912.', lines: 1,
          accept: ['When did the Titanic hit an iceberg?', 'When did Titanic hit an iceberg?', 'In which year did the Titanic hit an iceberg?', 'What year did the Titanic hit an iceberg?'],
          modelAr: 'متى اصطدمت تايتانيك بجبل جليدي؟',
          explainAr: 'المسطَّر زمن (in 1912) فنسأل بـ When. الفعل hit ماضٍ بسيط، فنستخدم did ويعود الفعل إلى أصله hit: When did the Titanic hit an iceberg?' },
        { n: 33, kind: 'write', topic: 'grammar', prompt: 'Fred’s children speak to their grandparents {every week} on Skype.', promptAr: 'يتحدّث أولاد فريد مع أجدادهم كل أسبوع عبر سكايب.', lines: 1,
          accept: ['How often do Fred’s children speak to their grandparents on Skype?', 'How often do Fred’s children speak to their grandparents?', 'How often do his children speak to their grandparents on Skype?'],
          modelAr: 'كم مرة يتحدّث أولاد فريد مع أجدادهم عبر سكايب؟',
          explainAr: 'المسطَّر يدل على التكرار (every week) فنسأل بـ How often. الفعل speak مضارع بسيط مع جمع، فنستخدم do: How often do Fred’s children speak to their grandparents on Skype?' },
      ],
    },
    {
      letter: 'F',
      title: 'Answer the following questions:',
      titleAr: 'أجب عن الأسئلة التالية:',
      marks: 20,
      questions: [
        { n: 34, kind: 'write', prompt: 'How do you go to school?', promptAr: 'كيف تذهب إلى المدرسة؟', lines: 1,
          accept: ['I go to school by bus.', 'I go to school by car.', 'I go to school by taxi.', 'I go to school by bike.', 'I go to school on foot.', 'I walk to school.', 'I usually go to school by bus.', 'I usually walk to school.', 'I usually go to school on foot.', 'I go by bus.', 'I go on foot.', 'I walk.', 'By bus.', 'On foot.'],
          model: 'I go to school on foot.', modelAr: 'أذهب إلى المدرسة سيراً على الأقدام.',
          explainAr: 'سؤال شخصي عن وسائل النقل (موضوع الوحدة 4): أجب بجملة كاملة مثل I go to school by bus / by car / on foot. أي وسيلة صحيحة مقبولة إذا كانت الجملة سليمة.' },
        { n: 35, kind: 'write', prompt: 'Who is your best friend?', promptAr: 'مَن صديقك المفضّل؟', lines: 1,
          accept: ['My best friend is my brother.', 'My best friend is my sister.', 'My best friend is my cousin.', 'My best friend is my classmate.', 'My best friend is my neighbour.', 'My best friend is my mother.', 'My best friend is my father.', 'My brother is my best friend.', 'My sister is my best friend.', 'My cousin is my best friend.'],
          model: 'My best friend is Sami.', modelAr: 'صديقي المفضّل هو سامي.',
          explainAr: 'سؤال شخصي: أجب بجملة كاملة تبدأ بـ My best friend is ... وتذكر اسماً أو صلة قرابة (my brother / my cousin / my classmate). أي اسم صحيح مقبول إذا كانت الجملة سليمة.' },
      ],
    },
    {
      letter: 'G',
      title: 'Write a 50-word paragraph about ONE of the following topics:',
      titleAr: 'اكتب فقرة من 50 كلمة عن أحد الموضوعين التاليين:',
      marks: 50,
      writing: {
        topic: 'Write a 50-word paragraph about ONE of the following topics: Topic 1: The planes of the future. Topic 2: A person who positively affected your life.',
        topicAr: 'اكتب فقرة من 50 كلمة عن أحد الموضوعين: الموضوع 1: طائرات المستقبل. الموضوع 2: شخص أثّر في حياتك تأثيراً إيجابياً.',
        words: 50,
        points: ['Topic 1: The planes of the future.', 'Topic 2: A person who positively affected your life.'],
        model: 'Topic 1: In the future, planes will be faster, quieter and cleaner. They will use solar power and other renewable energy, so they will not pollute the air. Some planes will be driverless, and passengers will travel around the world in a few hours. I think flying will be cheaper and safer for everyone.\n\nTopic 2: My English teacher, Mrs. Huda, has positively affected my life. She always showed us that she cared about us. She listened to our problems and never criticised us in a negative way. She encouraged me to read and to volunteer in my community. Thanks to her, I have become more confident and hard-working.',
        modelAr: 'الموضوع 1: في المستقبل ستكون الطائرات أسرع وأهدأ وأنظف. ستستخدم الطاقة الشمسية وأنواعاً أخرى من الطاقة المتجدّدة، فلن تلوّث الهواء. ستكون بعض الطائرات بلا طيّار، وسيسافر الركّاب حول العالم في ساعات قليلة. أعتقد أن الطيران سيصبح أرخص وأكثر أماناً للجميع.\n\nالموضوع 2: أثّرت معلّمة اللغة الإنجليزية، السيدة هدى، في حياتي تأثيراً إيجابياً. كانت تُظهر لنا دائماً أنها تهتمّ بنا، وتستمع إلى مشكلاتنا ولا تنتقدنا بطريقة سلبية أبداً. شجّعتني على القراءة وعلى التطوّع في مجتمعي. وبفضلها أصبحت أكثر ثقة واجتهاداً.',
        checklistAr: [
          'اخترتُ موضوعاً واحداً فقط وكتبتُ عنه نحو 50 كلمة في فقرة واحدة.',
          'بدأتُ بجملة رئيسية توضّح الفكرة وختمتُ بجملة رأي أو خلاصة.',
          'استخدمتُ الزمن المناسب: will للتنبّؤ في الموضوع 1، والماضي البسيط والمضارع التام في الموضوع 2.',
          'استخدمتُ أدوات ربط (and, so, but, because) وكلمات من الوحدات (renewable, efficient, inspire, care about).',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
