import type { Exam } from '../../../engine/types'

// A practice Basic Education Certificate paper in the exact layout of the real 2026 paper, built only from the book.
// Passage A: Student's Book Unit 3 reading "Life in the Future" (page 17, paragraphs 2–6).
// Passage B: Activity Book Unit 8 reading "On the Edge of Innocence" (page 37, the whole story).
// Sections C, D and E: sentences from Units 1, 4, 7 and 10 (Student's Book and Activity Book).
// G: the writing tasks of Activity Book Unit 1 (page 6) and Unit 10 (page 50).
export const term2B: Exam = {
  id: 't2-b',
  term: 2,
  title: 'Certificate Exam — Model (B)',
  titleAr: 'نموذج امتحان الشهادة (B)',
  minutes: 90,
  totalMarks: 400,
  sourceAr: 'نموذج تدريبي بالشكل نفسه تماماً لامتحان شهادة التعليم الأساسي 2026: نص (A) من قراءة "Life in the Future" (الوحدة 3)، ونص (B) من قصة "On the Edge of Innocence" في كتاب النشاط (الوحدة 8)، وبقية الأسئلة من جمل الوحدات 1 و4 و7 و10 في كتاب الطالب وكتاب النشاط.',
  sections: [
    {
      letter: 'A',
      title: 'Read the following text then choose the correct answer a, b, c, or d:',
      titleAr: 'اقرأ النص التالي ثم اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 50,
      passage: {
        paragraphs: [
          'First, as for education, people will have better education because of technology. E-books will replace traditional books, robots will replace teachers, and students will not have to go to schools every day as they will study at home through on-line teaching. So even absent students will learn.',
          'Second, health will improve. Technology will also play a very important role in that. New medicines will help people get better. Robots will help doctors and sometimes replace them. Add to that, scientists and researchers will find cure to many diseases like Aids and cancer. So people will live longer.',
          'Third, housing problems will end. People will build houses everywhere. So everyone will have a place to live in.',
          'Fourth, hunger will come to an end. People will grow new types of crops everywhere even on the roofs of buildings.',
          'Fifth and last, world peace will spread because of all the previous aspects. The world will have nothing to fight for. Everyone will have education, health, home and food. So everyone will be happier and love will be everywhere.',
        ],
        paragraphsAr: [
          'أولاً، فيما يخصّ التعليم، سيحظى الناس بتعليم أفضل بفضل التكنولوجيا. ستحلّ الكتب الإلكترونية محلّ الكتب التقليدية، وستحلّ الروبوتات محلّ المعلّمين، ولن يضطرّ الطلاب إلى الذهاب إلى المدارس كل يوم لأنهم سيدرسون في البيت من خلال التعليم عبر الإنترنت. لذلك حتى الطلاب الغائبون سيتعلّمون.',
          'ثانياً، ستتحسّن الصحة. وستؤدّي التكنولوجيا أيضاً دوراً مهماً جداً في ذلك. ستساعد الأدوية الجديدة الناس على الشفاء. وستساعد الروبوتات الأطباء وتحلّ محلّهم أحياناً. أضف إلى ذلك أن العلماء والباحثين سيجدون علاجاً لكثير من الأمراض مثل الإيدز والسرطان. لذلك سيعيش الناس مدة أطول.',
          'ثالثاً، ستنتهي مشكلات السكن. سيبني الناس البيوت في كل مكان. لذلك سيكون لكل شخص مكان يسكن فيه.',
          'رابعاً، سينتهي الجوع. سيزرع الناس أنواعاً جديدة من المحاصيل في كل مكان حتى على أسطح المباني.',
          'خامساً وأخيراً، سينتشر السلام العالمي بسبب كل الجوانب السابقة. لن يبقى في العالم شيء يتقاتل الناس من أجله. سيحصل كل شخص على التعليم والصحة والمسكن والطعام. لذلك سيكون الجميع أسعد وستعمّ المحبة كل مكان.',
        ],
      },
      groups: [
        {
          title: 'Choose the correct answer a, b, c, or d:',
          titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
          marks: 50,
          questions: [
            { n: 1, kind: 'mcq', prompt: 'Students will not have to go to schools every day because they will ……….', promptAr: 'لن يضطرّ الطلاب إلى الذهاب إلى المدارس كل يوم لأنهم سوف ___.',
              options: ['read traditional books', 'be absent', 'replace their teachers', 'study at home through on-line teaching'], answer: 3,
              explainAr: 'النص: "students will not have to go to schools every day as they will study at home through on-line teaching". الكلمة as هنا بمعنى because، فالسبب هو "study at home through on-line teaching" أي الدراسة في البيت عبر الإنترنت.' },
            { n: 2, kind: 'mcq', prompt: 'In the future, health will ……….', promptAr: 'في المستقبل، الصحة سوف ___.',
              options: ['get worse', 'get better', 'come to an end', 'stay the same'], answer: 1,
              explainAr: 'النص: "Second, health will improve". الفعل improve = يتحسّن (make something better في الكلمات المفتاحية)، فالمعنى "get better". أما "come to an end" فقيلت عن الجوع (hunger) لا عن الصحة.' },
            { n: 3, kind: 'mcq', prompt: 'People will live longer because scientists and researchers will ……….', promptAr: 'سيعيش الناس مدة أطول لأن العلماء والباحثين سوف ___.',
              options: ['build houses everywhere', 'replace doctors', 'find cure to many diseases', 'grow new types of crops'], answer: 2,
              explainAr: 'النص: "scientists and researchers will find cure to many diseases like Aids and cancer. So people will live longer". إذن السبب "find cure to many diseases" أي إيجاد علاج لأمراض كثيرة. أما الروبوتات فهي التي ستحلّ محلّ الأطباء أحياناً.' },
            { n: 4, kind: 'mcq', prompt: 'People will grow new types of crops everywhere, even ……….', promptAr: 'سيزرع الناس أنواعاً جديدة من المحاصيل في كل مكان، حتى ___.',
              options: ['in schools', 'in hospitals', 'under the sea', 'on the roofs of buildings'], answer: 3,
              explainAr: 'النص: "People will grow new types of crops everywhere even on the roofs of buildings" أي "on the roofs of buildings" = على أسطح المباني. crops = محاصيل.' },
            { n: 5, kind: 'mcq', prompt: 'The world will have nothing to fight for because everyone will have ……….', promptAr: 'لن يبقى في العالم شيء يتقاتل الناس من أجله لأن كل شخص سيحصل على ___.',
              options: ['education, health, home and food', 'robots and e-books', 'a lot of money', 'new medicines only'], answer: 0,
              explainAr: 'النص: "The world will have nothing to fight for. Everyone will have education, health, home and food". إذن الجواب "education, health, home and food" = التعليم والصحة والمسكن والطعام، ولذلك سينتشر السلام العالمي.' },
          ],
        },
      ],
    },
    {
      letter: 'B',
      title: 'Read the following text then do the tasks below:',
      titleAr: 'اقرأ النص التالي ثم نفّذ المهام التي تليه:',
      marks: 50,
      passage: {
        paragraphs: [
          'A poor family was living happily until the son felt severely ill. It was clear from the medical analysis and laboratory tests that he had got a tumour in his head.',
          '"Your son’s condition is critical. He needs a miracle to survive.", the doctor said. After she had heard the doctor’s words the little daughter rushed to the nearest pharmacy with the only pound she had in her money box. "Give me a miracle, please," she said putting the pound on the table. The pharmacist was busy talking to his brother. After a while he replied, "who told you I sell miracles?" She looked helplessly watching in despair. Suddenly the pharmacist’s brother kneeled asking her, "tell me, sweetie, why do you need a miracle?" Without thinking, "I don’t know, the doctor says my brother needs a miracle for an operation not to die."Is this pound enough?" "One pound is exactly enough", he answered with a big smile and a tender voice. "Could I see your brother?" This man was Carlton Armstrong, the famous nerve surgeon who performed the operation successfully and took one pound for it.',
          'Later, he framed the pound with a sentence below, "This pound is the price of a miracle taken from a girl, on the edge of innocence."',
        ],
        paragraphsAr: [
          'كانت أسرة فقيرة تعيش بسعادة إلى أن مرض الابن مرضاً شديداً. واتّضح من التحاليل الطبية والفحوص المخبرية أنه مصاب بورم في رأسه.',
          'قال الطبيب: «حالة ابنكم حرجة. إنه يحتاج إلى معجزة لكي ينجو». وبعد أن سمعت الابنة الصغيرة كلام الطبيب، أسرعت إلى أقرب صيدلية ومعها الليرة الوحيدة التي كانت في حصّالتها. وقالت وهي تضع الليرة على الطاولة: «أعطني معجزة، من فضلك». كان الصيدلاني مشغولاً بالحديث مع أخيه، وبعد قليل أجاب: «من قال لكِ إنني أبيع المعجزات؟» فنظرت بعجز وهي تراقب في يأس. وفجأة جثا أخو الصيدلاني على ركبتيه وسألها: «أخبريني يا حلوتي، لماذا تحتاجين إلى معجزة؟» فأجابت دون تفكير: «لا أعرف، الطبيب يقول إن أخي يحتاج إلى معجزة لكي تُجرى له عملية فلا يموت. هل هذه الليرة تكفي؟» فأجاب بابتسامة عريضة وصوت حنون: «ليرة واحدة تكفي تماماً. هل يمكنني أن أرى أخاكِ؟» كان هذا الرجل كارلتون أرمسترونغ، جرّاح الأعصاب الشهير، الذي أجرى العملية بنجاح وأخذ مقابلها ليرة واحدة.',
          'وفي ما بعد، وضع الليرة في إطار وكتب تحتها جملة: «هذه الليرة ثمن معجزة أُخذت من فتاة، على حافة البراءة».',
        ],
      },
      groups: [
        {
          title: 'Write true (T) or false (F):',
          titleAr: 'اكتب صح (T) أو خطأ (F):',
          marks: 30,
          questions: [
            { n: 6, kind: 'truefalse', prompt: 'The son had got a tumour in his head.', promptAr: 'كان الابن مصاباً بورم في رأسه.', answer: true,
              explainAr: 'صح. النص: "It was clear from the medical analysis and laboratory tests that he had got a tumour in his head".' },
            { n: 7, kind: 'truefalse', prompt: 'The pharmacist sold the little girl a miracle.', promptAr: 'باع الصيدلاني الفتاة الصغيرة معجزة.', answer: false,
              explainAr: 'خطأ. الصيدلاني كان مشغولاً بالحديث مع أخيه وقال لها: "who told you I sell miracles?" أي من قال لكِ إنني أبيع المعجزات؟ والذي ساعدها هو أخوه الجرّاح.' },
            { n: 8, kind: 'truefalse', prompt: 'Carlton Armstrong took one pound for the operation.', promptAr: 'أخذ كارلتون أرمسترونغ ليرة واحدة مقابل العملية.', answer: true,
              explainAr: 'صح. النص: "the famous nerve surgeon who performed the operation successfully and took one pound for it".' },
          ],
        },
        {
          title: 'Answer the following questions about the text:',
          titleAr: 'أجب عن الأسئلة التالية حول النص:',
          marks: 20,
          questions: [
            { n: 9, kind: 'write', prompt: 'What did the little daughter take to the pharmacy?', promptAr: 'ماذا أخذت الابنة الصغيرة معها إلى الصيدلية؟', lines: 2,
              accept: ['She took the only pound she had in her money box.', 'She took the only pound she had.', 'The only pound she had in her money box.', 'She took one pound.', 'She took a pound.', 'One pound.', 'The only pound she had.', 'She took the pound she had in her money box.'],
              model: 'She took the only pound she had in her money box.', modelAr: 'أخذت الليرة الوحيدة التي كانت في حصّالتها.',
              explainAr: 'النص: "the little daughter rushed to the nearest pharmacy with the only pound she had in her money box". نبدأ الجواب بـ She took ثم ننقل المعلومة من النص.' },
            { n: 10, kind: 'write', prompt: 'Who was Carlton Armstrong?', promptAr: 'من كان كارلتون أرمسترونغ؟', lines: 2,
              accept: ['He was the famous nerve surgeon who performed the operation successfully.', 'He was the famous nerve surgeon.', 'He was a famous nerve surgeon.', 'The famous nerve surgeon.', 'He was the pharmacist’s brother, the famous nerve surgeon.', 'He was the pharmacist’s brother.', 'The pharmacist’s brother.', 'He was the famous nerve surgeon who performed the operation successfully and took one pound for it.'],
              model: 'He was the pharmacist’s brother, the famous nerve surgeon who performed the operation successfully.', modelAr: 'كان أخا الصيدلاني، جرّاح الأعصاب الشهير الذي أجرى العملية بنجاح.',
              explainAr: 'النص: "This man was Carlton Armstrong, the famous nerve surgeon who performed the operation successfully". و"This man" هو "the pharmacist’s brother" الذي جثا وسأل الفتاة. surgeon = جرّاح.' },
          ],
        },
      ],
    },
    {
      letter: 'C',
      title: 'Choose the correct answer a, b, c or d:',
      titleAr: 'اختر الإجابة الصحيحة a أو b أو c أو d:',
      marks: 150,
      questions: [
        { n: 11, kind: 'mcq', topic: 'vocab', prompt: 'The teacher began to ……… the students for their excellent work.', promptAr: 'بدأ المعلّم ___ الطلاب على عملهم الممتاز.',
          options: ['refuse', 'praise', 'employ', 'prevent'], answer: 1,
          explainAr: '"praise" = يمدح أو يثني على (to express approval, love, or admiration)، وهي من كلمات نص الوحدة 1 "A Different Class". المعلّم يمدح الطلاب على عملهم الممتاز. أما "refuse" = يرفض، و"employ" = يستخدم، و"prevent" = يمنع.' },
        { n: 12, kind: 'mcq', topic: 'vocab', prompt: 'My parents wouldn’t ……… me to go abroad.', promptAr: 'لم يكن والداي ___ لي بالسفر إلى الخارج.',
          options: ['fine', 'benefit', 'increase', 'allow'], answer: 3,
          explainAr: '"allow" = يسمح (to let someone do something / to permit)، من كلمات نص الوحدة 4 "Autonomous Vehicles"، ويأتي بعدها مفعول ثم to + فعل: allow me to go. أما "fine" = يغرّم، و"benefit" = يفيد، و"increase" = يزيد.' },
        { n: 13, kind: 'mcq', topic: 'vocab', prompt: 'Most of our students ……… high grades in the final exam.', promptAr: 'معظم طلابنا ___ درجات عالية في الامتحان النهائي.',
          options: ['attain', 'waste', 'ignore', 'kill'], answer: 0,
          explainAr: '"attain" = ينال أو يحقّق (gain)، من كلمات نص الوحدة 10 "Killing Time is not a Murder!!!". الطلاب ينالون درجات عالية. أما "waste" = يهدر، و"ignore" = يتجاهل، و"kill" = يقتل.' },
        { n: 14, kind: 'mcq', topic: 'grammar', prompt: 'The bus skidded on the road and fell ……… a river.', promptAr: 'انزلقت الحافلة على الطريق وسقطت ___ نهر.',
          options: ['into', 'off', 'out of', 'at'], answer: 0,
          explainAr: 'حرف الجر "into" يدل على الحركة إلى داخل شيء، فالحافلة سقطت في النهر: fell into a river (من قصة Frane Selak في كتاب النشاط، الوحدة 7). أما "out of" فعكسها (خروج من الداخل)، و"off" = عن سطح شيء، و"at" لا تدل على حركة.' },
        { n: 15, kind: 'mcq', topic: 'tense', prompt: 'Be quiet! John ……… .', promptAr: 'اهدأ! جون ___.',
          options: ['sleeps', 'is sleeping', 'slept', 'has slept'], answer: 1,
          explainAr: '"Be quiet!" تدل على حدث يجري الآن لحظة الكلام، فنستخدم المضارع المستمر "is sleeping" (مراجعة المضارع البسيط والمستمر، الوحدة 1). "sleeps" للعادات والحقائق، و"slept" ماضٍ بسيط.' },
        { n: 16, kind: 'mcq', topic: 'tense', prompt: 'A truck came barreling towards his car as he ……… around a mountain road.', promptAr: 'اندفعت شاحنة نحو سيارته بينما كان ___ على طريق جبلي.',
          options: ['drives', 'is driving', 'was driving', 'has driven'], answer: 2,
          explainAr: 'حدث طويل كان جارياً في الماضي (القيادة) قطعه حدث قصير (اندفاع الشاحنة came)، فنستخدم الماضي المستمر "was driving" بعد as. الجملة من قصة Frane Selak (الوحدة 7). "drives" و"is driving" للحاضر، و"has driven" مضارع تام.' },
        { n: 17, kind: 'mcq', topic: 'tense', prompt: 'The lesson ……… when we arrived.', promptAr: 'كان الدرس ___ عندما وصلنا.',
          options: ['has already begun', 'already begins', 'had already begun', 'will already begin'], answer: 2,
          explainAr: 'حدثان في الماضي: بدء الدرس حصل أولاً ثم وصلنا (arrived ماضٍ بسيط)، فالحدث الأسبق بالماضي التام had + التصريف الثالث: "had already begun" (الوحدة 7). "has already begun" مضارع تام لا يناسب الماضي.' },
        { n: 18, kind: 'mcq', topic: 'tense', prompt: 'Dinosaurs ……… extinct by the time humankind first appeared.', promptAr: 'كانت الديناصورات ___ منقرضة بحلول الوقت الذي ظهر فيه الإنسان لأول مرة.',
          options: ['had become', 'have become', 'become', 'will become'], answer: 0,
          explainAr: 'by the time + ماضٍ بسيط (appeared) يعني أن الحدث الآخر اكتمل قبله، فنستخدم الماضي التام "had become" (الوحدة 7، كتاب النشاط). "have become" مضارع تام، و"will become" مستقبل.' },
        { n: 19, kind: 'mcq', topic: 'tense', prompt: 'Thousands of drivers ……… their jobs if autonomous vehicles are allowed to take over the roads.', promptAr: 'آلاف السائقين ___ وظائفهم إذا سُمح للمركبات ذاتية القيادة بالسيطرة على الطرق.',
          options: ['lost', 'had lost', 'will lose', 'were losing'], answer: 2,
          explainAr: 'الجملة توقّع لما سيحدث في المستقبل، ومع if + مضارع بسيط (are allowed) نستخدم "will lose" (will + الفعل في المصدر). الجملة من نص الوحدة 4. أما "lost" و"had lost" و"were losing" فأزمنة ماضية.' },
        { n: 20, kind: 'mcq', topic: 'grammar', prompt: 'There is ……… milk left in the fridge.', promptAr: 'يوجد ___ حليب متبقٍّ في البرّاد.',
          options: ['a little', 'a few', 'many', 'an'], answer: 0,
          explainAr: 'milk اسم غير معدود، فنستخدم معه "a little" = قليل (المحدِّدات، الوحدة 4). "a few" و"many" للأسماء المعدودة الجمع، و"an" للمفرد المعدود الذي يبدأ بصوت علّة.' },
        { n: 21, kind: 'mcq', topic: 'grammar', prompt: 'The committee praised Mrs. Al-Hroub’s “play and learn” method, ……… she still employs.', promptAr: 'أثنت اللجنة على طريقة السيدة الحروب "العب وتعلّم"، ___ ما زالت تستخدمها.',
          options: ['who', 'whose', 'where', 'which'], answer: 3,
          explainAr: 'نصف اسماً لغير العاقل (method) فنستخدم ضمير الوصل "which". الجملة من نص الوحدة 1 "A Different Class". "who" للعاقل، و"whose" للملكية، و"where" للمكان.' },
        { n: 22, kind: 'mcq', topic: 'reported', prompt: '“Have you read this book?” He asked me if I ……… that book.', promptAr: '"هل قرأتَ هذا الكتاب؟" سألني إن كنتُ ___ ذلك الكتاب.',
          options: ['have read', 'had read', 'am reading', 'will read'], answer: 1,
          explainAr: 'في السؤال المنقول يرجع الزمن خطوة إلى الماضي: المضارع التام (have read) يصبح ماضياً تاماً "had read"، ويتغيّر this إلى that (الأسئلة المنقولة، الوحدة 10).' },
        { n: 23, kind: 'mcq', topic: 'grammar', prompt: 'The water clock ……… by the ancient Greeks.', promptAr: 'الساعة المائية ___ على يد الإغريق القدماء.',
          options: ['created', 'is creating', 'has created', 'was created'], answer: 3,
          explainAr: 'الساعة لم تصنع نفسها، بل صُنعت على يد الإغريق (by the ancient Greeks)، فنستخدم المبني للمجهول في الماضي: was + التصريف الثالث "was created". الجملة من صفحة Focus on Social Studies في الوحدة 10.' },
        { n: 24, kind: 'mcq', topic: 'grammar', prompt: 'Time is precious, ……… ?', promptAr: 'الوقت ثمين، ___؟',
          options: ['doesn’t it', 'isn’t it', 'wasn’t it', 'is it'], answer: 1,
          explainAr: 'الجملة مثبتة وفعلها is في المضارع، فالسؤال الذيلي منفي بالفعل المساعد نفسه: "isn’t it". "doesn’t it" خطأ لأن الفعل is وليس فعلاً عادياً، و"wasn’t it" ماضٍ، و"is it" مثبت. Time is precious من نص الوحدة 10.' },
        { n: 25, kind: 'mcq', topic: 'pronunciation', prompt: 'The word which has a long /u:/ sound is ……… .', promptAr: 'الكلمة التي فيها صوت /u:/ الطويل هي ___.',
          options: ['foot', 'cook', 'fruit', 'pull'], answer: 2,
          explainAr: '"fruit" تُلفظ بصوت /u:/ الطويل مثل juice وschool. أما "foot" و"cook" و"pull" ففيها صوت /u/ القصير مثل put وlook (الوحدة 10).' },
      ],
    },
    {
      letter: 'D',
      title: 'Match each item in (A) with the suitable choice from (B):',
      titleAr: 'صِل كل عبارة في (A) بما يناسبها من (B):',
      marks: 50,
      questions: [
        { n: 26, kind: 'mcq', prompt: 'Parents often refuse', promptAr: 'غالباً ما يرفض الآباء …',
          options: ['from car insurance.', 'to attain more with less effort.', 'the focus on play.', 'he had not learnt the value of time.', 'by the time Sally got there.'], answer: 2,
          explainAr: 'الجملة من نص الوحدة 1: "Parents often refuse the focus on play." أي يرفض الآباء غالباً التركيز على اللعب. الفعل refuse يحتاج مفعولاً به (اسماً)، وهو "the focus on play."' },
        { n: 27, kind: 'mcq', prompt: 'Insurance companies get a lot of money', promptAr: 'تحصل شركات التأمين على كثير من المال …',
          options: ['from car insurance.', 'to attain more with less effort.', 'the focus on play.', 'he had not learnt the value of time.', 'by the time Sally got there.'], answer: 0,
          explainAr: 'الجملة من الوحدة 4: "Insurance companies get a lot of money from car insurance." أي من تأمين السيارات. get money from = يحصل على المال من.' },
        { n: 28, kind: 'mcq', prompt: 'Karen had already left', promptAr: 'كانت كارين قد غادرت …',
          options: ['from car insurance.', 'to attain more with less effort.', 'the focus on play.', 'he had not learnt the value of time.', 'by the time Sally got there.'], answer: 4,
          explainAr: 'مثال الماضي التام في الوحدة 7: "Karen had already left by the time Sally got there." الحدث الأسبق بالماضي التام (had left)، والحدث اللاحق بالماضي البسيط بعد by the time، فالتتمة "by the time Sally got there."' },
        { n: 29, kind: 'mcq', prompt: 'Time management helps you', promptAr: 'تنظيم الوقت يساعدك …',
          options: ['from car insurance.', 'to attain more with less effort.', 'the focus on play.', 'he had not learnt the value of time.', 'by the time Sally got there.'], answer: 1,
          explainAr: 'الجملة من نص الوحدة 10: "Time management helps you to attain more with less effort." أي أن تحقّق أكثر بجهد أقل. help + مفعول + to + فعل.' },
        { n: 30, kind: 'mcq', prompt: 'Hani lost a golden chance because', promptAr: 'أضاع هاني فرصة ذهبية لأن …',
          options: ['from car insurance.', 'to attain more with less effort.', 'the focus on play.', 'he had not learnt the value of time.', 'by the time Sally got there.'], answer: 3,
          explainAr: 'الجملة من قصة الوحدة 10 في كتاب النشاط: "Hani lost a golden chance because he had not learnt the value of time." بعد because نحتاج جملة كاملة (فاعل + فعل)، وهي "he had not learnt the value of time."' },
      ],
    },
    {
      letter: 'E',
      title: 'Write suitable questions about the underlined words:',
      titleAr: 'اكتب أسئلة مناسبة عن الكلمات التي تحتها خط:',
      marks: 30,
      questions: [
        { n: 31, kind: 'write', topic: 'grammar', prompt: 'Frane Selak was born in Croatia {in 1929}.', promptAr: 'وُلد فراني سيلاك في كرواتيا عام 1929.', lines: 1,
          accept: ['When was Frane Selak born?', 'When was Frane Selak born in Croatia?', 'When was Selak born?', 'When was Selak born in Croatia?', 'When was he born?', 'In which year was Frane Selak born?', 'In what year was Frane Selak born?', 'What year was Frane Selak born?'],
          model: 'When was Frane Selak born?', modelAr: 'متى وُلد فراني سيلاك؟',
          explainAr: 'المسطَّر زمن (in 1929) فنسأل بـ When. الفعل was born ماضٍ مبني للمجهول، فنقدّم was على الفاعل: When was Frane Selak born? (من قصة Back to Life، الوحدة 7).' },
        { n: 32, kind: 'write', topic: 'grammar', prompt: 'After lunch, Hani took a nap {for an hour}.', promptAr: 'بعد الغداء، أخذ هاني قيلولة لمدة ساعة.', lines: 1,
          accept: ['How long did Hani take a nap?', 'How long did Hani take a nap after lunch?', 'How long did he take a nap?', 'How long did Hani nap?', 'How long did Hani sleep?', 'How long did Hani take a nap for?'],
          model: 'How long did Hani take a nap after lunch?', modelAr: 'كم من الوقت أخذ هاني قيلولة بعد الغداء؟',
          explainAr: 'المسطَّر مدّة (for an hour) فنسأل بـ How long. الفعل took ماضٍ بسيط، فنستخدم did ويعود الفعل إلى أصله take (من قصة Hurry up Before the Gates are Shut!، الوحدة 10).' },
        { n: 33, kind: 'write', topic: 'grammar', prompt: 'Marsha goes to a sports club {every Thursday}.', promptAr: 'تذهب مارشا إلى نادٍ رياضي كل يوم خميس.', lines: 1,
          accept: ['How often does Marsha go to a sports club?', 'How often does she go to a sports club?', 'When does Marsha go to a sports club?', 'How often does Marsha go to the sports club?'],
          model: 'How often does Marsha go to a sports club?', modelAr: 'كم مرة تذهب مارشا إلى النادي الرياضي؟',
          explainAr: 'المسطَّر تكرار (every Thursday) فنسأل بـ How often. الفعل goes مضارع بسيط مع مفرد، فنستخدم does ويعود الفعل إلى أصله go (مثال المضارع البسيط للعادات، الوحدة 1).' },
      ],
    },
    {
      letter: 'F',
      title: 'Answer the following questions:',
      titleAr: 'أجب عن الأسئلة التالية:',
      marks: 20,
      questions: [
        { n: 34, kind: 'write', prompt: 'What would you like to be in the future?', promptAr: 'ماذا تحبّ أن تكون في المستقبل؟', lines: 1,
          accept: ['I would like to be a doctor.', 'I would like to be a teacher.', 'I would like to be an engineer.', 'I would like to be a pilot.', 'I would like to be a nurse.', 'I would like to be a lawyer.', 'I would like to be a pharmacist.', 'I would like to be a surgeon.', 'I would like to be a journalist.', 'I would like to be a farmer.', 'I want to be a doctor.', 'I want to be a teacher.', 'I want to be an engineer.', 'I want to be a pilot.', 'I would like to be an English teacher.', 'I would like to be a doctor in the future.', 'I would like to be a teacher in the future.', 'I would like to be an engineer in the future.'],
          model: 'I would like to be a doctor.', modelAr: 'أحبّ أن أكون طبيباً.',
          explainAr: 'سؤال شخصي (من أسئلة المحادثة في الوحدة 1). نجيب بجملة كاملة تبدأ بـ I would like to be ثم a/an والمهنة: I would like to be a doctor / an engineer. أي مهنة صحيحة لغوياً تُقبل.' },
        { n: 35, kind: 'write', prompt: 'What form of transport do you usually use?', promptAr: 'ما وسيلة النقل التي تستخدمها عادةً؟', lines: 1,
          accept: ['I usually use the bus.', 'I usually use a bus.', 'I usually go by bus.', 'I usually take the bus.', 'I usually use the car.', 'I usually use a car.', 'I usually go by car.', 'I usually use my father’s car.', 'I usually use a taxi.', 'I usually go by taxi.', 'I usually use the train.', 'I usually go by train.', 'I usually use a bike.', 'I usually ride a bike.', 'I usually ride my bike.', 'I usually walk.', 'I usually go on foot.', 'I usually use the microbus.', 'I use the bus.', 'I go by bus.'],
          model: 'I usually use the bus.', modelAr: 'أستخدم الحافلة عادةً.',
          explainAr: 'سؤال شخصي (من أسئلة المحادثة في الوحدة 4). نجيب بجملة كاملة بالمضارع البسيط مع usually: I usually use the bus / I usually go by car. أي وسيلة نقل صحيحة تُقبل.' },
      ],
    },
    {
      letter: 'G',
      title: 'Write a 50-word paragraph about ONE of the following topics:',
      titleAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد من الموضوعين التاليين:',
      marks: 50,
      writing: {
        topic: 'Write a 50-word paragraph about ONE of the following topics:\nTopic 1: A job you would like to have in the future.\nTopic 2: How you manage and organize your time.',
        topicAr: 'اكتب فقرة من 50 كلمة عن موضوع واحد من الموضوعين التاليين:\nالموضوع 1: مهنة تحبّ أن تعمل بها في المستقبل.\nالموضوع 2: كيف تدير وقتك وتنظّمه.',
        words: 50,
        points: ['Topic 1: A job you would like to have in the future.', 'Topic 2: How you manage and organize your time.'],
        model: 'Topic 1: In the future, I would like to be a teacher. I love children and I want to make a difference in their lives. Like Mrs. Al-Hroub, I will use games, balloons and videos to explain my lessons. My pupils will learn while they play. Teaching is a great job because it builds good people.\nTopic 2: Time is precious, so I never waste it. I always get up early and divide what I have to do. In the morning, I go to school. In the afternoon, I do my homework and ignore interruptions. I only watch TV for an hour. I always go to bed before ten.',
        modelAr: 'الموضوع 1: في المستقبل أحبّ أن أكون معلّماً. أحبّ الأطفال وأريد أن أُحدث فرقاً في حياتهم. ومثل السيدة الحروب، سأستخدم الألعاب والبالونات ومقاطع الفيديو لشرح دروسي. سيتعلّم تلاميذي وهم يلعبون. التعليم مهنة عظيمة لأنها تبني أناساً صالحين.\nالموضوع 2: الوقت ثمين، لذلك لا أهدره أبداً. أستيقظ دائماً باكراً وأقسّم ما عليّ فعله. في الصباح أذهب إلى المدرسة. وفي فترة ما بعد الظهر أكتب واجباتي وأتجاهل المقاطعات. أشاهد التلفاز ساعة واحدة فقط. وأخلد إلى النوم دائماً قبل العاشرة.',
        checklistAr: [
          'اخترتُ موضوعاً واحداً فقط من الموضوعين وكتبتُ عنه وحده.',
          'كتبتُ نحو 50 كلمة في فقرة واحدة لها جملة بداية وجملة ختام.',
          'استخدمتُ الزمن المناسب: will / would like للمهنة في المستقبل، والمضارع البسيط مع always / usually / never للعادات اليومية.',
          'استخدمتُ أدوات ربط مثل and, so, because, In the morning, In the afternoon.',
          'استخدمتُ كلمات من الكتاب مثل make a difference, precious, waste, divide, ignore interruption.',
          'التهجئة وعلامات الترقيم والحروف الكبيرة صحيحة.',
        ],
      },
    },
  ],
}
