import type { GrammarExercise } from '../../../engine/types'
import type { ModuleExtras } from './merge'

// Module 1 "Make a Difference" — Activity Book pages 3–10 (Unit 1: 3–6, Unit 2: 7–10). No Progress Test.
// Left out: the Speaking discussions (open answers), reading questions that ask for the student's own opinion
// (U1 A4, U2 A4) and the Listening tasks (U1 p. 5, U2 p. 9), whose answers depend on the recording.

const fill = (prompt: string, promptAr: string, promptArFull: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, promptAr, promptArFull, options, answer, explainAr })
const mcq = (prompt: string, promptAr: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, promptAr, options, answer, explainAr })
const tf = (prompt: string, promptAr: string, answer: boolean, explainAr: string): GrammarExercise =>
  ({ type: 'truefalse', prompt, promptAr, answer, explainAr })
const build = (answer: string, prompt: string, explainAr: string): GrammarExercise =>
  ({ type: 'build', prompt, answer, explainAr })

/** A Key Words item: the printed meaning and three other meanings from the same box, sorted so the answer moves. */
function keyItem(word: string, wordAr: string, meanings: string[], right: number, others: number[], explainAr: string): GrammarExercise {
  const options = [right, ...others].map(i => meanings[i]).sort()
  return mcq(`Key Words: what does "${word}" mean?`, `الكلمات المفتاحية: ما معنى «${word}» (${wordAr})؟`, options, options.indexOf(meanings[right]), explainAr)
}

// ---------- Unit 1, page 4: Key Words ----------
const u1Keys = [
  'goods bought and sold in large quantities/wholesale',
  'the money that you can make in business or by selling things',
  'to increase',
  'a vehicle with two or four wheels that is pulled by a horse',
  'a group of ships or trucks',
  'previous/past',
]

// ---------- Unit 1, page 4 B: the (B) column of the matching ----------
const u1MatchB = [
  'he decided to buy life insurance.',
  'virtually you don’t exist.',
  'he ended up with almost £100.',
  'a hundred former unemployed people, all selling tomatoes.',
]

// ---------- Unit 2, page 7: Key Words ----------
const u2Keys = [
  'pay in advance',
  'a person whose job is to repair water pipes, toilets, etc',
  'stopped for a while',
  'to have enough money to pay for something',
  'to bring something back after it has not been used or existed for a period of time',
  'the act of looking for work',
]

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 1 — Work Together to Make it Better (Activity Book pages 3–6) =====================
    u1: {
      workbook: {
        pages: '3–6',
        readings: [
          {
            title: 'From Microsoft to Tomatoes',
            paragraphs: [
              `One day, an unemployed man went to apply for a job with Microsoft as a cleaner. The manager said: "Let me have your e-mail address, so that I can send you a form to complete and tell you when you can start." The man said that he had no computer or email address. The manager: "Well, then, that means that you virtually don’t exist and therefore can’t be employed."`,
              `The man looked at the last £10 in his wallet and thought of buying tomatoes in bulk. Within less than 2 hours, he sold all the tomatoes at 100% profit. Repeating the process several times that day, he ended up with almost £100 before going to sleep that night. Getting up early every day and going to bed late, he multiplied his profits quickly. After a short time he bought a cart to transport several dozen boxes of tomatoes.`,
              `By the end of the second year, he became the owner of a fleet of trucks and the manager of a staff of a hundred former unemployed people, all selling tomatoes.`,
              `Planning for the future of his wife and children, he decided to buy life insurance. An adviser asked him for his e-mail address in order to send the final documents electronically. When the man replied that he has no e-mail, the adviser felt astonished and said: "How did you make such wealth without Internet and e-mail? Just imagine where you would-be now, if you had been connected to the internet from the very start!"`,
              `After a moment of thought, the tomato millionaire replied: "I would be a floor cleaner at Microsoft!"`,
              `Even with the lack of technology, with determination and the required skills one can make a difference.`,
            ],
            paragraphsAr: [
              'في أحد الأيام، ذهب رجل عاطل عن العمل ليتقدّم لوظيفة عامل تنظيف في شركة مايكروسوفت. قال له المدير: «أعطني عنوان بريدك الإلكتروني لكي أرسل إليك استمارة تملؤها، وأخبرك متى يمكنك أن تبدأ». فقال الرجل إنه لا يملك حاسوباً ولا عنوان بريد إلكتروني. فقال المدير: «حسناً إذن، هذا يعني أنك عملياً غير موجود، ولذلك لا يمكن توظيفك».',
              'نظر الرجل إلى آخر عشرة جنيهات في محفظته، وفكّر في شراء الطماطم بالجملة. وفي أقلّ من ساعتين باع كل الطماطم بربح مئة في المئة. وبتكرار العملية عدة مرات في ذلك اليوم، صار معه نحو مئة جنيه قبل أن ينام تلك الليلة. وبالاستيقاظ باكراً كل يوم والنوم متأخراً، ضاعف أرباحه بسرعة. وبعد وقت قصير اشترى عربة لينقل عليها عشرات الصناديق من الطماطم.',
              'وبحلول نهاية السنة الثانية، أصبح مالكاً لأسطول من الشاحنات ومديراً لفريق من مئة شخص كانوا عاطلين عن العمل سابقاً، وجميعهم يبيعون الطماطم.',
              'وتخطيطاً لمستقبل زوجته وأولاده، قرّر أن يشتري تأميناً على الحياة. فطلب منه أحد المستشارين عنوان بريده الإلكتروني ليرسل إليه الوثائق النهائية إلكترونياً. وعندما أجاب الرجل بأنه لا يملك بريداً إلكترونياً، شعر المستشار بالدهشة وقال: «كيف جمعت هذه الثروة كلها من دون إنترنت ولا بريد إلكتروني؟ تخيّل فقط أين كنت ستكون الآن لو كنت متّصلاً بالإنترنت منذ البداية!»',
              'وبعد لحظة تفكير، أجاب مليونير الطماطم: «كنت سأكون عامل تنظيف أرضيات في مايكروسوفت!»',
              'حتى مع قلّة التكنولوجيا، يستطيع الإنسان بالعزيمة والمهارات اللازمة أن يُحدث فرقاً.',
            ],
            questions: [
              {
                q: 'Why didn’t the man succeed to have the job of a cleaner?', qAr: 'لماذا لم ينجح الرجل في الحصول على وظيفة عامل التنظيف؟',
                options: ['Because he had no computer or email address.', 'Because he was not a good cleaner.', 'Because he wanted to sell tomatoes.', 'Because he was late for the interview.'],
                answer: 0, explainAr: 'النص يقول: "The man said that he had no computer or email address" فقال المدير إنه "virtually doesn’t exist" أي غير موجود عملياً، ولذلك لا يمكن توظيفه.',
              },
              {
                q: 'What job did he take after being rejected by Microsoft?', qAr: 'ما العمل الذي قام به بعد أن رفضته مايكروسوفت؟',
                options: ['He became a floor cleaner.', 'He sold computers.', 'He bought and sold tomatoes.', 'He became an insurance adviser.'],
                answer: 2, explainAr: 'اشترى الطماطم بالجملة (in bulk) بآخر عشرة جنيهات معه ثم باعها بربح: "he sold all the tomatoes at 100% profit".',
              },
              {
                q: 'How many years did it take for him to become a millionaire?', qAr: 'كم سنة احتاج ليصبح مليونيراً؟',
                options: ['One year.', 'About two years.', 'Two hours.', 'Ten years.'],
                answer: 1, explainAr: 'النص يقول: "By the end of the second year, he became the owner of a fleet of trucks" أي خلال سنتين تقريباً. (Two hours هي المدة التي باع فيها أول طماطم.)',
              },
              {
                q: 'How did he multiply his profits quickly?', qAr: 'كيف ضاعف أرباحه بسرعة؟',
                options: ['By using the Internet and e-mail.', 'By getting up early every day and going to bed late.', 'By buying life insurance.', 'By working at Microsoft.'],
                answer: 1, explainAr: 'النص يقول: "Getting up early every day and going to bed late, he multiplied his profits quickly" أي بالعمل الجادّ من الصباح الباكر حتى وقت متأخر.',
              },
              {
                q: 'Why did the adviser ask him for his e-mail address?', qAr: 'لماذا طلب المستشار عنوان بريده الإلكتروني؟',
                options: ['To send him a form for a cleaning job.', 'To tell him when he can start.', 'To send the final documents electronically.', 'To buy tomatoes from him.'],
                answer: 2, explainAr: 'النص يقول: "An adviser asked him for his e-mail address in order to send the final documents electronically" أي ليرسل وثائق التأمين النهائية إلكترونياً.',
              },
              {
                q: 'What is the lesson of the story?', qAr: 'ما العبرة من القصة؟',
                options: ['Without the Internet, nobody can succeed.', 'Every millionaire must have an e-mail.', 'Selling tomatoes is better than working at Microsoft.', 'With determination and the required skills, one can make a difference.'],
                answer: 3, explainAr: 'الجملة الأخيرة في النص: "Even with the lack of technology, with determination and the required skills one can make a difference."',
              },
            ],
          },
        ],
        exercises: [
          // ---- page 4: Key Words ----
          keyItem('bulk', 'بالجملة', u1Keys, 0, [1, 4, 5], 'bulk = بضائع تُشترى وتُباع بكميات كبيرة (بالجملة wholesale)، كما في: "buying tomatoes in bulk".'),
          keyItem('profit', 'ربح', u1Keys, 1, [0, 2, 5], 'profit = الربح: المال الذي تكسبه من التجارة أو البيع، كما في: "he sold all the tomatoes at 100% profit".'),
          keyItem('multiply', 'يضاعف', u1Keys, 2, [1, 3, 5], 'multiply = يزيد ويضاعف (to increase)، كما في: "he multiplied his profits quickly".'),
          keyItem('cart', 'عربة', u1Keys, 3, [0, 4, 2], 'cart = عربة بعجلتين أو أربع يجرّها حصان، اشتراها الرجل لينقل صناديق الطماطم.'),
          keyItem('fleet', 'أسطول', u1Keys, 4, [0, 3, 5], 'fleet = أسطول: مجموعة من السفن أو الشاحنات، كما في: "a fleet of trucks".'),
          keyItem('former', 'سابق', u1Keys, 5, [2, 4, 1], 'former = سابق (previous/past)، كما في: "a hundred former unemployed people" أي كانوا عاطلين عن العمل في السابق.'),

          // ---- page 4 B: match (A) with (B) to make full sentences ----
          fill('He managed a staff of ___',
            'كان يدير فريقاً من ___',
            'كان يدير فريقاً من مئة شخص كانوا عاطلين عن العمل سابقاً، وجميعهم يبيعون الطماطم.',
            u1MatchB, 3,
            'بعد "a staff of" (فريق مؤلّف من) نحتاج عدداً من الأشخاص: "a hundred former unemployed people". والجمل الأخرى تبدأ بفاعل وفعل ولا تكمل هذا التعبير.'),
          fill('Repeating the process several times that day, ___',
            'بتكرار العملية عدة مرات في ذلك اليوم، ___',
            'بتكرار العملية عدة مرات في ذلك اليوم، انتهى به الأمر ومعه نحو مئة جنيه.',
            u1MatchB, 2,
            'الجملة تتحدث عن نتيجة تكرار بيع الطماطم في يوم واحد: صار معه نحو £100 (he ended up with almost £100).'),
          fill('Not having an email means that ___',
            'عدم امتلاك بريد إلكتروني يعني أنّ ___',
            'عدم امتلاك بريد إلكتروني يعني أنك عملياً غير موجود.',
            u1MatchB, 1,
            'هذا كلام مدير مايكروسوفت: من لا يملك بريداً إلكترونياً "virtually doesn’t exist" أي غير موجود عملياً.'),
          fill('Planning for the future of his family, ___',
            'تخطيطاً لمستقبل عائلته، ___',
            'تخطيطاً لمستقبل عائلته، قرّر أن يشتري تأميناً على الحياة.',
            u1MatchB, 0,
            'التأمين على الحياة (life insurance) هو ما يخطّط به الإنسان لمستقبل زوجته وأولاده، والنص يقول: "he decided to buy life insurance".'),

          // ---- page 4: Vocabulary — choose the correct word between brackets ----
          fill('She had a problem in the bank, so she asked to meet the ___.',
            'كانت لديها مشكلة في المصرف، فطلبت أن تقابل ___.',
            'كانت لديها مشكلة في المصرف، فطلبت أن تقابل المدير.',
            ['manage', 'manager', 'managed'], 1,
            'بعد أداة التعريف the نحتاج اسماً: manager (مدير). أما manage فهو فعل (يدير)، وmanaged فعل ماضٍ.'),
          fill('He has no money; he has been ___ for months.',
            'ليس معه مال؛ فهو ___ منذ أشهر.',
            'ليس معه مال؛ فهو عاطل عن العمل منذ أشهر.',
            ['unemployment', 'unemployed', 'employ'], 1,
            'بعد الفعل has been نحتاج صفة تصف الشخص: unemployed (عاطل عن العمل). unemployment اسم (البطالة) وemploy فعل (يوظّف).'),
          fill('Life doesn’t ___ on Mars.',
            'الحياة لا ___ على المريخ.',
            'الحياة لا توجد على المريخ.',
            ['existence', 'exist', 'exists'], 1,
            'بعد doesn’t يأتي الفعل في صيغة المصدر دون s: exist (يوجد). existence اسم (الوجود)، وexists خطأ لأن doesn’t أخذت علامة الغائب.'),
          fill('I was ___ when my nine-months brother could walk.',
            'كنتُ ___ عندما استطاع أخي ذو الأشهر التسعة أن يمشي.',
            'كنتُ مندهشاً عندما استطاع أخي ذو الأشهر التسعة أن يمشي.',
            ['astonishment', 'astonished', 'astonishing'], 1,
            'بعد I was نحتاج صفة تصف شعوري: astonished (مندهش). الصفة المنتهية بـ ed تصف الشعور، أما astonishing فتعني «مدهش» أي الشيء الذي يسبّب الدهشة. astonishment اسم (الدهشة).'),

          // ---- page 5 A: select the correct form of the verbs between brackets ----
          fill('Every Monday, Sally ___ her kids to football practice.',
            'كل يوم اثنين، ___ سالي أولادها إلى تدريب كرة القدم.',
            'كل يوم اثنين، تُوصل سالي أولادها بالسيارة إلى تدريب كرة القدم.',
            ['is driving', 'drives', 'drive'], 1,
            'Every Monday تدلّ على عادة تتكرّر، والعادات نستخدم لها المضارع البسيط. الفاعل Sally مفرد غائب فنضيف s: drives.'),
          fill('Usually, I ___ as a secretary, but this summer, I ___ French at a language school.',
            'عادةً ___ سكرتيراً، لكن هذا الصيف ___ الفرنسية في مدرسة لغات.',
            'عادةً أعمل سكرتيراً، لكن هذا الصيف أدرس الفرنسية في مدرسة لغات.',
            ['work … am studying', 'am working … study', 'work … study', 'am working … am studying'], 0,
            'Usually تدلّ على عادة فنستخدم المضارع البسيط: work. أما this summer فتدلّ على عمل مؤقّت (temporary action) فنستخدم المضارع المستمر: am studying.'),
          fill('Be quiet! John ___.',
            'اهدأ! جون ___.',
            'اهدأ! جون نائم الآن.',
            ['sleeps', 'is sleeping', 'sleep'], 1,
            'Be quiet! تدلّ على أن النوم يحدث الآن في لحظة الكلام، فنستخدم المضارع المستمر: is sleeping.'),
          fill('Don’t forget to take your umbrella. It ___.',
            'لا تنسَ أن تأخذ مظلّتك. إنها ___.',
            'لا تنسَ أن تأخذ مظلّتك. إنها تمطر الآن.',
            ['rains', 'is raining', 'rain'], 1,
            'نأخذ المظلة لأن المطر يهطل الآن، فالحدث يجري لحظة الكلام ونستخدم المضارع المستمر: is raining.'),
          fill('She is fit because she always ___ as an exercise.',
            'هي رشيقة لأنها دائماً ___ كتمرين رياضي.',
            'هي رشيقة لأنها دائماً تركض كتمرين رياضي.',
            ['is running', 'runs', 'run'], 1,
            'always تدلّ على عادة متكرّرة، فنستخدم المضارع البسيط، والفاعل she مفرد غائب فنضيف s: runs.'),

          // ---- page 5 B: put the verbs between brackets in the correct question form ----
          fill('What ___ under the table? – Is there anything wrong? (you do)',
            'ماذا ___ تحت الطاولة؟ – هل هناك مشكلة ما؟',
            'ماذا تفعل تحت الطاولة الآن؟ – هل هناك مشكلة ما؟',
            ['do you do', 'are you doing', 'you are doing', 'are you do'], 1,
            'السؤال عن شيء يحدث الآن أمامنا، فنستخدم سؤال المضارع المستمر: What + are + you + doing? (الفعل المساعد قبل الفاعل، والفعل مع ing).'),
          fill('Where ___ when she goes to Homs? (she/usually/stay)',
            'أين ___ عندما تذهب إلى حمص؟',
            'أين تقيم عادةً عندما تذهب إلى حمص؟',
            ['does she usually stay', 'is she usually staying', 'does she usually stays', 'she usually stays'], 0,
            'usually تدلّ على عادة، فنستخدم سؤال المضارع البسيط: Where + does + she + usually + stay? وبعد does يأتي الفعل دون s.'),
          fill('What a delicious smell! What ___ for dinner? (your mother/prepare)',
            'يا لها من رائحة شهية! ماذا ___ للعشاء؟',
            'يا لها من رائحة شهية! ماذا تحضّر أمك للعشاء الآن؟',
            ['does your mother prepare', 'is your mother preparing', 'your mother is preparing', 'is your mother prepare'], 1,
            'الرائحة تدلّ على أن الطبخ يحدث الآن، فنستخدم سؤال المضارع المستمر: What + is + your mother + preparing?'),
          fill('What time ___ on weekdays? (he/wake up)',
            'في أيّ ساعة ___ في أيام الأسبوع؟',
            'في أيّ ساعة يستيقظ في أيام الأسبوع؟',
            ['is he waking up', 'does he wakes up', 'does he wake up', 'do he wake up'], 2,
            'on weekdays تدلّ على عادة، فنستخدم سؤال المضارع البسيط. الفاعل he مفرد غائب فنستخدم does، وبعدها الفعل دون s: does he wake up.'),
          fill('Where ___? (you / live)',
            'أين ___؟',
            'أين تسكن؟',
            ['do you live', 'are you live', 'does you live', 'you live'], 0,
            'السكن حالة دائمة (حقيقة)، فنستخدم سؤال المضارع البسيط، ومع you نستخدم do: Where do you live?'),

          // ---- extra practice: the book's own examples from the revision tables (pages 4–5) ----
          fill('It rarely ___ in the desert.',
            'نادراً ما ___ في الصحراء.',
            'نادراً ما تمطر في الصحراء.',
            ['is raining', 'rains', 'rain'], 1,
            'هذه حقيقة عامة (general fact)، والحقائق نستخدم لها المضارع البسيط، والفاعل it مفرد غائب: rains.'),
          fill('Marsha ___ to a sports club every Thursday.',
            'مارشا ___ إلى نادٍ رياضي كل يوم خميس.',
            'مارشا تذهب إلى نادٍ رياضي كل يوم خميس.',
            ['is going', 'go', 'goes'], 2,
            'every Thursday تدلّ على عادة (present habit)، فنستخدم المضارع البسيط مع s للغائب المفرد: goes.'),
          fill('She ___ a newspaper upstairs now.',
            'هي ___ صحيفة في الطابق العلوي الآن.',
            'هي تقرأ صحيفة في الطابق العلوي الآن.',
            ['reads', 'is reading', 'read'], 1,
            'now تدلّ على حدث يجري الآن (action happening now)، فنستخدم المضارع المستمر: is reading.'),
          fill('We ___ our cousins next week.',
            'نحن ___ أبناء عمومتنا الأسبوع القادم.',
            'نحن سنزور أبناء عمومتنا الأسبوع القادم.',
            ['visits', 'are visiting', 'is visiting'], 1,
            'هذه خطة مرتّبة للمستقبل (future arrangement) مع next week، ويُستخدم لها المضارع المستمر. الفاعل we فنستخدم are: are visiting.'),
          fill('He’s ___ a lot these days.',
            'إنه ___ كثيراً هذه الأيام.',
            'إنه يأكل كثيراً هذه الأيام.',
            ['eat', 'eating', 'eats'], 1,
            'these days تدلّ على عمل مؤقّت (temporary action)، فنستخدم المضارع المستمر: He’s (He is) + eating.'),
          fill('She ___ always drink tea.',
            'هي ___ الشاي دائماً.',
            'هي لا تشرب الشاي دائماً.',
            ['isn’t', 'doesn’t', 'don’t'], 1,
            'النفي في المضارع البسيط يكون بـ doesn’t مع he/she/it وdon’t مع I/you/we/they، ثم الفعل في المصدر drink. isn’t تُستخدم مع المضارع المستمر.'),
          fill('They ___ working nowadays.',
            'هم ___ هذه الأيام.',
            'هم لا يعملون هذه الأيام.',
            ['don’t', 'aren’t', 'doesn’t'], 1,
            'الفعل working (مع ing) يعني أننا في المضارع المستمر، ونفيه يكون بـ am/is/are + not. الفاعل they فنستخدم aren’t (are not).'),
          fill('___ he travel every year?',
            '___ يسافر كل عام؟',
            'هل يسافر كل عام؟',
            ['Is', 'Does', 'Do'], 1,
            'every year عادة، فالسؤال في المضارع البسيط يبدأ بـ Does مع he/she/it، والفعل بعدها في المصدر: Does he travel…?'),
          fill('___ they having a good time?',
            '___ يقضون وقتاً ممتعاً؟',
            'هل يقضون وقتاً ممتعاً الآن؟',
            ['Do', 'Are', 'Is'], 1,
            'الفعل having (مع ing) يعني المضارع المستمر، فالسؤال يبدأ بـ Are مع they: Are they having a good time?'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Order the following three parts of a paragraph to compose a well-organised one.',
          topicAr: 'رتّب الأجزاء الثلاثة التالية من فقرة لتكتب فقرة جيدة التنظيم (وأكمل الفراغ في نهاية كل جزء).',
          words: 100,
          points: [
            'Volunteering can help you make friends, learn new skills, advance your career, and even feel happier and healthier. Researchers also say that nearly half of volunteers enjoy improved health and fitness, and a quarter lose weight - especially those working with children. Two-thirds feel less stressed. So, it seems that volunteering may improve your life …',
            'The benefits of volunteering can be enormous. …',
            'To sum up, by volunteering you can make a huge difference. …',
          ],
          pointsAr: [
            'التطوّع يمكن أن يساعدك على تكوين صداقات، وتعلّم مهارات جديدة، وتطوير مسيرتك المهنية، بل والشعور بسعادة وصحة أكبر. ويقول الباحثون أيضاً إن نحو نصف المتطوّعين يتمتّعون بصحة ولياقة أفضل، وإن ربعهم يخسرون بعض الوزن، خاصة الذين يعملون مع الأطفال. ويشعر الثلثان بتوتّر أقل. إذن، يبدو أن التطوّع قد يحسّن حياتك …',
            'فوائد التطوّع يمكن أن تكون هائلة. …',
            'خلاصة القول، بالتطوّع يمكنك أن تُحدث فرقاً كبيراً. …',
          ],
          plan: [
            { en: 'Topic sentence (first): "The benefits of volunteering can be enormous." Then add one sentence that completes the idea.', ar: 'الجملة الرئيسية (أولاً): "The benefits of volunteering can be enormous." ثم أضف جملة تكمل الفكرة.' },
            { en: 'Supporting ideas and details (second): the part about friends, skills, career, health and stress; finish "improve your life …".', ar: 'الأفكار الداعمة والتفاصيل (ثانياً): الجزء الذي يتحدث عن الأصدقاء والمهارات والمهنة والصحة والتوتّر، وأكمل عبارة "improve your life …".' },
            { en: 'Concluding sentence (last): "To sum up, by volunteering you can make a huge difference." Then add a final thought.', ar: 'الجملة الختامية (أخيراً): "To sum up, by volunteering you can make a huge difference." ثم أضف فكرة أخيرة.' },
          ],
          phrases: [
            { en: 'The benefits of volunteering can be enormous.', ar: 'فوائد التطوّع يمكن أن تكون هائلة.' },
            { en: 'make friends', ar: 'يكوّن صداقات' },
            { en: 'learn new skills', ar: 'يتعلّم مهارات جديدة' },
            { en: 'advance your career', ar: 'يطوّر مسيرتك المهنية' },
            { en: 'feel happier and healthier', ar: 'يشعر بسعادة وصحة أكبر' },
            { en: 'Researchers also say that …', ar: 'ويقول الباحثون أيضاً إن …' },
            { en: 'So, it seems that …', ar: 'إذن، يبدو أن …' },
            { en: 'To sum up, …', ar: 'خلاصة القول، …' },
            { en: 'make a huge difference', ar: 'يُحدث فرقاً كبيراً' },
            { en: 'work together to make it better', ar: 'نعمل معاً لنجعله أفضل' },
            { en: 'people in need', ar: 'المحتاجون' },
          ],
          model: 'The benefits of volunteering can be enormous. They help both the volunteers and the people in need. Volunteering can help you make friends, learn new skills, advance your career, and even feel happier and healthier. Researchers also say that nearly half of volunteers enjoy improved health and fitness, and a quarter lose weight - especially those working with children. Two-thirds feel less stressed. So, it seems that volunteering may improve your life in many different ways. To sum up, by volunteering you can make a huge difference. When we work together, we make our community better and our own lives happier.',
          modelAr: 'فوائد التطوّع يمكن أن تكون هائلة. فهي تساعد المتطوّعين أنفسهم والمحتاجين معاً. التطوّع يمكن أن يساعدك على تكوين صداقات، وتعلّم مهارات جديدة، وتطوير مسيرتك المهنية، بل والشعور بسعادة وصحة أكبر. ويقول الباحثون أيضاً إن نحو نصف المتطوّعين يتمتّعون بصحة ولياقة أفضل، وإن ربعهم يخسرون بعض الوزن، خاصة الذين يعملون مع الأطفال. ويشعر الثلثان بتوتّر أقل. إذن، يبدو أن التطوّع قد يحسّن حياتك بطرق كثيرة ومختلفة. خلاصة القول، بالتطوّع يمكنك أن تُحدث فرقاً كبيراً. عندما نعمل معاً نجعل مجتمعنا أفضل وحياتنا أسعد.',
          checklistAr: [
            'هل بدأت بالجملة الرئيسية "The benefits of volunteering can be enormous."؟',
            'هل وضعت الجزء الطويل (الأفكار الداعمة والتفاصيل) في الوسط؟',
            'هل ختمت بالجملة الختامية "To sum up, …"؟',
            'هل أكملت الفراغ في نهاية كل جزء بكلام مناسب ومرتبط بالفكرة؟',
            'هل استخدمت المضارع البسيط للحقائق العامة (can help, feel, say) بشكل صحيح؟',
            'هل راجعت التهجئة وعلامات الترقيم والحروف الكبيرة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Think of a job you would like to have in the future and how it will make a difference to your life and to others’ lives and write about it.',
          topicAr: 'فكّر في وظيفة تودّ أن تعمل بها في المستقبل، وكيف ستُحدث فرقاً في حياتك وفي حياة الآخرين، واكتب عنها.',
          words: 100,
          points: ['Topic sentence', 'Supporting ideas', 'Additional details', 'Concluding sentence'],
          pointsAr: ['الجملة الرئيسية', 'الأفكار الداعمة', 'تفاصيل إضافية', 'الجملة الختامية'],
          plan: [
            { en: 'Topic sentence: name the job you would like to have and say that it can make a difference.', ar: 'الجملة الرئيسية: اذكر الوظيفة التي تودّ أن تعمل بها وقل إنها تستطيع أن تُحدث فرقاً.' },
            { en: 'Supporting idea 1: how the job will make a difference to others’ lives, with an example.', ar: 'الفكرة الداعمة الأولى: كيف ستُحدث الوظيفة فرقاً في حياة الآخرين، مع مثال.' },
            { en: 'Supporting idea 2 and additional details: how it will make a difference to your own life, and what you are doing now to get ready (present progressive).', ar: 'الفكرة الداعمة الثانية وتفاصيل إضافية: كيف ستُحدث فرقاً في حياتك أنت، وماذا تفعل الآن لتستعدّ لها (المضارع المستمر).' },
            { en: 'Concluding sentence: sum up with "To sum up, …".', ar: 'الجملة الختامية: لخّص فكرتك بـ "To sum up, …".' },
          ],
          phrases: [
            { en: 'I would like to be …', ar: 'أودّ أن أكون …' },
            { en: 'make a difference', ar: 'يُحدث فرقاً' },
            { en: 'a calm and fun place', ar: 'مكان هادئ وممتع' },
            { en: 'We play first, and when we play we learn.', ar: 'نلعب أولاً، وعندما نلعب نتعلّم.' },
            { en: 'open their minds', ar: 'يفتح عقولهم' },
            { en: 'build their characters', ar: 'يبني شخصياتهم' },
            { en: 'improve behaviour', ar: 'يحسّن السلوك' },
            { en: 'with determination and the required skills', ar: 'بالعزيمة والمهارات اللازمة' },
            { en: 'Nowadays, I am studying …', ar: 'في هذه الأيام أدرس …' },
            { en: 'First, … Second, …', ar: 'أولاً، … ثانياً، …' },
            { en: 'To sum up, …', ar: 'خلاصة القول، …' },
          ],
          model: 'In the future, I would like to be a primary school teacher, because I believe that teachers can make a difference. First, a good teacher builds the characters of the children and opens their minds. Like Hanan Al-Hroub, I want to make my classroom a calm and fun place where children play and learn. Second, this job will make a difference to my life, too. I will feel proud and happy every day when I see my pupils improve. Nowadays, I am studying hard and I am reading about new ways of teaching. To sum up, with determination and the required skills, I can make a difference to many lives.',
          modelAr: 'في المستقبل، أودّ أن أكون معلّماً في مدرسة ابتدائية، لأنني أؤمن بأن المعلّمين يستطيعون أن يُحدثوا فرقاً. أولاً، المعلّم الجيد يبني شخصيات الأطفال ويفتح عقولهم. ومثل حنان الحروب، أريد أن أجعل صفّي مكاناً هادئاً وممتعاً يلعب فيه الأطفال ويتعلّمون. ثانياً، هذه الوظيفة ستُحدث فرقاً في حياتي أيضاً، فسأشعر بالفخر والسعادة كل يوم عندما أرى تلاميذي يتحسّنون. في هذه الأيام أدرس بجدّ وأقرأ عن طرق جديدة في التعليم. خلاصة القول، بالعزيمة والمهارات اللازمة أستطيع أن أُحدث فرقاً في حياة كثيرين.',
          checklistAr: [
            'هل بدأت بجملة رئيسية تذكر الوظيفة بوضوح؟',
            'هل ذكرت كيف ستُحدث الوظيفة فرقاً في حياة الآخرين وفي حياتك أنت؟',
            'هل أضفت تفاصيل أو أمثلة تدعم أفكارك؟',
            'هل ختمت بجملة ختامية تلخّص الفكرة؟',
            'هل استخدمت المضارع البسيط للحقائق والمضارع المستمر لما تفعله الآن بشكل صحيح؟',
            'هل الفقرة نحو 100 كلمة، وراجعت التهجئة وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'One day, an unemployed man went to apply for a job with Microsoft as a cleaner.', ar: 'في أحد الأيام، ذهب رجل عاطل عن العمل ليتقدّم لوظيفة عامل تنظيف في شركة مايكروسوفت.' },
        { en: 'The man said that he had no computer or email address.', ar: 'قال الرجل إنه لا يملك حاسوباً ولا عنوان بريد إلكتروني.' },
        { en: 'Getting up early every day and going to bed late, he multiplied his profits quickly.', ar: 'كان يستيقظ باكراً كل يوم وينام متأخراً، فضاعف أرباحه بسرعة.' },
        { en: 'After a short time he bought a cart to transport several dozen boxes of tomatoes.', ar: 'بعد وقت قصير اشترى عربة لينقل عليها عشرات الصناديق من الطماطم.' },
        { en: 'Planning for the future of his wife and children, he decided to buy life insurance.', ar: 'تخطيطاً لمستقبل زوجته وأولاده، قرّر أن يشتري تأميناً على الحياة.' },
        { en: 'I would be a floor cleaner at Microsoft!', ar: 'كنت سأكون عامل تنظيف أرضيات في مايكروسوفت!' },
        { en: 'It rarely rains in the desert.', ar: 'نادراً ما تمطر في الصحراء.' },
        { en: 'The birds return to the island every morning.', ar: 'تعود الطيور إلى الجزيرة كل صباح.' },
        { en: 'I’m busy, I’m doing my homework at the moment.', ar: 'أنا مشغول، أكتب وظيفتي المدرسية في هذه اللحظة.' },
        { en: 'We are visiting our cousins next week.', ar: 'سنزور أبناء عمومتنا الأسبوع القادم.' },
        { en: 'They don’t usually go out in the evening.', ar: 'هم لا يخرجون عادةً في المساء.' },
        { en: 'Hanan Al-Hroub was a poorly paid teacher in the West Bank.', ar: 'كانت حنان الحروب معلّمة ذات راتب ضعيف في الضفة الغربية.' },
        { en: '“We play first, and when we play we learn,” she said.', ar: 'قالت: «نلعب أولاً، وعندما نلعب نتعلّم».' },
        { en: 'The kids don’t even realise they are learning.', ar: 'الأطفال لا يدركون حتى أنهم يتعلّمون.' },
        { en: 'Parents often refuse the focus on play.', ar: 'كثيراً ما يرفض الأهل التركيز على اللعب.' },
        { en: 'She also sees it as her duty to build their characters.', ar: 'وهي ترى أيضاً أن من واجبها أن تبني شخصياتهم.' },
        { en: 'The benefits of volunteering can be enormous.', ar: 'فوائد التطوّع يمكن أن تكون هائلة.' },
        { en: 'To sum up, by volunteering you can make a huge difference.', ar: 'خلاصة القول، بالتطوّع يمكنك أن تُحدث فرقاً كبيراً.' },
      ],
    },

    // ===================== UNIT 2 — Creativity & Initiatives (Activity Book pages 7–10) =====================
    u2: {
      workbook: {
        pages: '7–10',
        readings: [
          {
            title: 'Pay It Forward',
            paragraphs: [
              `On March 27, 2013, John Sweeney, a plumber from Ireland, started a Facebook page called Suspended Coffees. His message was simple: Buy a cup of coffee for a stranger, because an act of kindness can change a life and make a difference. Eight hours later, the page had attracted more than 20,000 likes.`,
              `Suspended coffee is a tradition that comes from Naples, Italy, and dates back to the 20th century. When customers buy coffee, they also pay in advance for a cup to be given to somebody else; usually someone who otherwise couldn't afford it. This initiative was forgotten, but then it revived again in 2011. That's when "Suspended Coffee Day" started to be celebrated each December.`,
              `You can buy it for anyone in need. It can be for the homeless person you pass by every day on the street, a stressed student in the middle of exams. It may be a well-dressed man whom you may not think from his appearance that he's in need but he may be in his third month of job hunting. It's not up to us to judge - if someone asks, then they're in need - no CV required.`,
            ],
            paragraphsAr: [
              'في 27 آذار 2013، أنشأ جون سويني، وهو سبّاك من إيرلندا، صفحة على فيسبوك اسمها «القهوة المعلّقة». كانت رسالته بسيطة: اشترِ فنجان قهوة لشخص غريب، لأن عملاً لطيفاً واحداً قد يغيّر حياة ويُحدث فرقاً. وبعد ثماني ساعات، كانت الصفحة قد جذبت أكثر من عشرين ألف إعجاب.',
              'القهوة المعلّقة تقليد جاء من نابولي في إيطاليا، ويعود إلى القرن العشرين. عندما يشتري الزبائن القهوة، يدفعون أيضاً مسبقاً ثمن فنجان يُقدَّم لشخص آخر، وغالباً ما يكون شخصاً لا يستطيع دفع ثمنه لولا ذلك. نُسيت هذه المبادرة، ثم عادت إلى الحياة في عام 2011، ومنذ ذلك الحين بدأ الاحتفال بـ«يوم القهوة المعلّقة» في شهر كانون الأول من كل عام.',
              'يمكنك أن تشتريها لأي شخص محتاج: قد تكون للمشرّد الذي تمرّ به كل يوم في الشارع، أو لطالب متوتّر في منتصف الامتحانات. وقد تكون لرجل حسن الهندام لا تظنّ من مظهره أنه محتاج، لكنه قد يكون في شهره الثالث من البحث عن عمل. ليس من شأننا أن نحكم على الناس؛ فإذا طلب أحدهم فهو محتاج، ولا حاجة إلى سيرة ذاتية.',
            ],
            questions: [
              {
                q: 'Explain the idea of suspended coffee.', qAr: 'اشرح فكرة القهوة المعلّقة.',
                options: [
                  'Customers pay for their coffee after they drink it.',
                  'When customers buy coffee, they also pay in advance for a cup to be given to someone who can’t afford it.',
                  'Cafés stop selling coffee for a while every December.',
                  'Students get free coffee from the café in the middle of exams.',
                ],
                answer: 1, explainAr: 'النص يقول: "When customers buy coffee, they also pay in advance for a cup to be given to somebody else; usually someone who otherwise couldn\'t afford it" أي يدفع الزبون ثمن فنجان إضافي لشخص محتاج.',
              },
              {
                q: 'Where did this idea start?', qAr: 'أين بدأت هذه الفكرة؟',
                options: ['In Sweden.', 'In Syria.', 'In Naples, Italy.', 'In London.'],
                answer: 2, explainAr: 'النص يقول: "Suspended coffee is a tradition that comes from Naples, Italy" أي من نابولي في إيطاليا.',
              },
              {
                q: 'When did it revive again?', qAr: 'متى عادت إلى الحياة من جديد؟',
                options: ['In 2011.', 'In 2013.', 'In the 20th century.', 'Every January.'],
                answer: 0, explainAr: 'النص يقول: "This initiative was forgotten, but then it revived again in 2011." أما 2013 فهو تاريخ صفحة جون سويني على فيسبوك.',
              },
              {
                q: 'Who started the Facebook page called Suspended Coffees?', qAr: 'من أنشأ صفحة فيسبوك التي اسمها «القهوة المعلّقة»؟',
                options: ['A student in the middle of exams.', 'John Sweeney, a plumber from Ireland.', 'A café owner from Naples.', 'A homeless man.'],
                answer: 1, explainAr: 'النص يقول: "John Sweeney, a plumber from Ireland, started a Facebook page called Suspended Coffees."',
              },
              {
                q: 'What does a person in need have to show to get a suspended coffee?', qAr: 'ماذا يجب أن يُظهر الشخص المحتاج ليحصل على قهوة معلّقة؟',
                options: ['His CV.', 'That he is in his third month of job hunting.', 'Nothing: if someone asks, then they’re in need.', 'A student card.'],
                answer: 2, explainAr: 'النص يقول: "It\'s not up to us to judge - if someone asks, then they\'re in need - no CV required." أي لا يُطلب منه أي إثبات.',
              },
            ],
            trueFalse: [
              { statement: 'Many people liked John’s initiative.', answer: true },
              { statement: 'Suspended Coffee Day is celebrated in January.', answer: false },
              { statement: 'The person who needs suspended coffee must prove that he is poor.', answer: false },
            ],
          },
        ],
        exercises: [
          // ---- page 7: Key Words ----
          keyItem('pay forward', 'يدفع مسبقاً', u2Keys, 0, [2, 3, 5], 'pay forward = يدفع مسبقاً (pay in advance)، وهي فكرة القهوة المعلّقة: تدفع اليوم ثمن فنجان يشربه غيرك لاحقاً.'),
          keyItem('plumber', 'سبّاك', u2Keys, 1, [0, 4, 5], 'plumber = سبّاك: شخص عمله إصلاح أنابيب المياه والمراحيض، ومهنة جون سويني في النص.'),
          keyItem('suspended', 'معلّق', u2Keys, 2, [0, 3, 4], 'suspended = معلّق: متوقّف لفترة من الزمن، فالقهوة المعلّقة مدفوعة وتنتظر من يأخذها.'),
          keyItem('afford', 'يستطيع دفع الثمن', u2Keys, 3, [0, 2, 5], 'afford = أن يكون معك مال كافٍ لتدفع ثمن شيء، كما في: "someone who otherwise couldn\'t afford it".'),
          keyItem('revive', 'يُحيي / يعود إلى الحياة', u2Keys, 4, [2, 3, 1], 'revive = يُعيد شيئاً بعد أن توقّف استخدامه أو وجوده مدة من الزمن، كما في: "it revived again in 2011".'),
          keyItem('job hunting', 'البحث عن عمل', u2Keys, 5, [0, 1, 3], 'job hunting = البحث عن عمل، كما في: "he may be in his third month of job hunting".'),

          // ---- page 8 B: True / False ----
          tf('Many people liked John’s initiative.', 'أحبّ كثير من الناس مبادرة جون.', true,
            'صحيحة: بعد ثماني ساعات فقط جذبت صفحته أكثر من 20,000 إعجاب: "the page had attracted more than 20,000 likes".'),
          tf('Suspended Coffee Day is celebrated in January.', 'يُحتفل بيوم القهوة المعلّقة في كانون الثاني (يناير).', false,
            'خاطئة. التصحيح: Suspended Coffee Day is celebrated each December. أي في كانون الأول (ديسمبر).'),
          tf('The person who needs suspended coffee must prove that he is poor.', 'يجب على الشخص الذي يحتاج القهوة المعلّقة أن يُثبت أنه فقير.', false,
            'خاطئة. التصحيح: It\'s not up to us to judge - if someone asks, then they\'re in need - no CV required. أي لا يحتاج إلى أي إثبات.'),

          // ---- page 8: Vocabulary — find the opposites in the text ----
          fill('Find the opposite in the text: finish / end / stop ≠ ___',
            'ابحث في النص عن عكس: finish / end / stop (ينهي / يتوقّف) ≠ ___',
            'ابحث في النص عن عكس: finish / end / stop (ينهي / يتوقّف) ≠ start (يبدأ)',
            ['judge', 'start', 'buy'], 1,
            'عكس ينهي/يتوقّف هو start (يبدأ)، وقد جاء في النص: "John Sweeney … started a Facebook page".'),
          fill('Find the opposite in the text: complicated ≠ ___',
            'ابحث في النص عن عكس: complicated (معقّد) ≠ ___',
            'ابحث في النص عن عكس: complicated (معقّد) ≠ simple (بسيط)',
            ['stressed', 'forgotten', 'simple'], 2,
            'عكس معقّد هو simple (بسيط)، وقد جاء في النص: "His message was simple".'),
          fill('Find the opposite in the text: similarity ≠ ___',
            'ابحث في النص عن عكس: similarity (تشابه) ≠ ___',
            'ابحث في النص عن عكس: similarity (تشابه) ≠ difference (اختلاف / فرق)',
            ['difference', 'kindness', 'tradition'], 0,
            'عكس التشابه هو difference (الاختلاف)، وقد جاء في النص: "make a difference".'),
          fill('Find the opposite in the text: sell ≠ ___',
            'ابحث في النص عن عكس: sell (يبيع) ≠ ___',
            'ابحث في النص عن عكس: sell (يبيع) ≠ buy (يشتري)',
            ['pay', 'buy', 'afford'], 1,
            'عكس يبيع هو buy (يشتري)، وقد جاء في النص: "Buy a cup of coffee for a stranger". أما pay فتعني يدفع وليست عكس يبيع.'),
          fill('Find the opposite in the text: remember ≠ ___',
            'ابحث في النص عن عكس: remember (يتذكّر) ≠ ___',
            'ابحث في النص عن عكس: remember (يتذكّر) ≠ forget (ينسى)',
            ['celebrate', 'attract', 'forget'], 2,
            'عكس يتذكّر هو forget (ينسى)، وجاء في النص بصيغة التصريف الثالث: "This initiative was forgotten".'),
          fill('Find the opposite in the text: relaxed / unstressed ≠ ___',
            'ابحث في النص عن عكس: relaxed / unstressed (مرتاح / غير متوتّر) ≠ ___',
            'ابحث في النص عن عكس: relaxed / unstressed (مرتاح / غير متوتّر) ≠ stressed (متوتّر)',
            ['stressed', 'homeless', 'well-dressed'], 0,
            'عكس مرتاح هو stressed (متوتّر)، وقد جاء في النص: "a stressed student in the middle of exams".'),

          // ---- page 9 A: put the verbs in the present perfect tense ----
          fill('I am not hungry. I ___ already ___ (eat).',
            'لستُ جائعاً. ___ مسبقاً.',
            'لستُ جائعاً. لقد أكلتُ مسبقاً.',
            ['have … eaten', 'has … eaten', 'have … ate', 'am … eating'], 0,
            'المضارع التام: have/has + التصريف الثالث. مع I نستخدم have، والتصريف الثالث لـ eat هو eaten (أما ate فهو الماضي البسيط). already تأتي بين have والتصريف الثالث.'),
          fill('We ___ for our holiday yet. (not/plan)',
            'نحن ___ لعطلتنا بعد.',
            'نحن لم نخطّط لعطلتنا بعد.',
            ['didn’t plan', 'haven’t planned', 'hasn’t planned', 'haven’t plan'], 1,
            'مع yet في النفي نستخدم المضارع التام المنفي: haven’t + التصريف الثالث. الفاعل we فنستخدم haven’t، والتصريف الثالث planned (نضاعف n ونضيف ed).'),
          fill('___ you ___ any interesting books? (read)',
            '___ أيّ كتب ممتعة؟',
            'هل قرأت أيّ كتب ممتعة؟',
            ['Did … read', 'Has … read', 'Have … read', 'Have … reading'], 2,
            'السؤال في المضارع التام: Have/Has + الفاعل + التصريف الثالث. مع you نستخدم Have، والتصريف الثالث لـ read هو read (يُكتب مثل المصدر ويُلفظ /red/).'),
          fill('She ___ the cat yet. (feed)',
            'هي ___ القطة بعد.',
            'هي لم تُطعم القطة بعد.',
            ['has fed', 'hasn’t fed', 'haven’t fed', 'hasn’t feed'], 1,
            'yet في الجملة الخبرية تأتي مع النفي: hasn’t + التصريف الثالث. الفاعل she فنستخدم hasn’t، والتصريف الثالث لـ feed هو fed. (ويمكن أيضاً السؤال: Has she fed the cat yet?)'),
          fill('___ Amer ___ a car yet? (buy)',
            '___ عامر سيارة بعد؟',
            'هل اشترى عامر سيارة بعد؟',
            ['Have … bought', 'Has … bought', 'Has … buy', 'Did … bought'], 1,
            'السؤال في المضارع التام: Has مع المفرد الغائب (Amer) + التصريف الثالث bought. وyet تأتي في آخر السؤال.'),

          // ---- page 9 B: change the statements into questions ----
          mcq('Change into a question: "She is working on a new project."',
            'حوّل إلى سؤال: «إنها تعمل على مشروع جديد».',
            ['Is she working on a new project?', 'Does she working on a new project?', 'Is she work on a new project?', 'Has she working on a new project?'], 0,
            'الجملة في المضارع المستمر (is working)، فنقدّم is على الفاعل ونبقي الفعل مع ing: Is she working…?'),
          mcq('Change into a question: "He has returned from Europe."',
            'حوّل إلى سؤال: «لقد عاد من أوروبا».',
            ['Does he returned from Europe?', 'Has he returned from Europe?', 'Is he returned from Europe?', 'Has he return from Europe?'], 1,
            'الجملة في المضارع التام (has returned)، فنقدّم has على الفاعل ويبقى التصريف الثالث returned: Has he returned…?'),
          mcq('Change into a question: "Maya has taught English since 2019."',
            'حوّل إلى سؤال: «تُدرّس مايا اللغة الإنكليزية منذ عام 2019».',
            ['Does Maya taught English since 2019?', 'Has Maya teach English since 2019?', 'Has Maya taught English since 2019?', 'Is Maya taught English since 2019?'], 2,
            'الجملة في المضارع التام مع since، فنقدّم has على الفاعل ويبقى التصريف الثالث taught: Has Maya taught…?'),
          mcq('Change into a question: "Susan enjoys reading."',
            'حوّل إلى سؤال: «سوزان تستمتع بالقراءة».',
            ['Does Susan enjoys reading?', 'Is Susan enjoy reading?', 'Do Susan enjoy reading?', 'Does Susan enjoy reading?'], 3,
            'الجملة في المضارع البسيط (enjoys)، فالسؤال يبدأ بـ Does مع المفرد الغائب، ونحذف s من الفعل لأن does أخذتها: Does Susan enjoy reading?'),
          mcq('Change into a question: "This car belongs to Martin."',
            'حوّل إلى سؤال: «هذه السيارة ملك لمارتن».',
            ['Does this car belong to Martin?', 'Is this car belong to Martin?', 'Does this car belongs to Martin?', 'Is this car belonging to Martin?'], 0,
            'الجملة في المضارع البسيط (belongs)، فالسؤال: Does + this car + belong (دون s). الفعل belong يدلّ على ملكية ولا يُستخدم عادةً في المضارع المستمر.'),

          // ---- extra practice: the book's own examples from the present perfect table (pages 8–9) ----
          fill('___ you tried sushi?',
            '___ جرّبت السوشي؟',
            'هل جرّبت السوشي من قبل؟',
            ['Do', 'Has', 'Have'], 2,
            'سؤال المضارع التام: Have/Has + الفاعل + التصريف الثالث. مع you نستخدم Have.'),
          fill('She has already ___ this film.',
            'لقد ___ هذا الفيلم مسبقاً.',
            'لقد شاهدت هذا الفيلم مسبقاً.',
            ['saw', 'seen', 'see'], 1,
            'بعد has نستخدم التصريف الثالث: seen. أما saw فهي الماضي البسيط ولا تأتي بعد has.'),
          fill('They have ___ several awards.',
            'لقد ___ عدة جوائز.',
            'لقد فازوا بعدة جوائز.',
            ['win', 'won', 'wins'], 1,
            'نستخدم المضارع التام لحدث وقع في وقت غير محدّد من الماضي: have + التصريف الثالث won.'),
          fill('I have been in this city ___ last year.',
            'أنا في هذه المدينة ___ العام الماضي.',
            'أنا في هذه المدينة منذ العام الماضي.',
            ['for', 'since', 'yet'], 1,
            'since تأتي قبل نقطة بداية في الزمن (last year, 2019)، أما for فتأتي قبل مدة زمنية (nine years).'),
          fill('Mr. Smith has been a teacher ___ nine years.',
            'السيد سميث معلّم ___ تسع سنوات.',
            'السيد سميث معلّم منذ تسع سنوات.',
            ['since', 'for', 'already'], 1,
            'nine years مدة زمنية، فنستخدم for. (since تأتي قبل نقطة بداية مثل since 2019.)'),
          fill('I ___ my pen. I am unable to do my exercise.',
            '___ قلمي. لا أستطيع أن أحلّ تمريني.',
            'لقد أضعتُ قلمي. لا أستطيع أن أحلّ تمريني.',
            ['have lost', 'lose', 'has lost'], 0,
            'حدث انتهى في الماضي لكن نتيجته ما زالت الآن (لا أستطيع الكتابة)، فنستخدم المضارع التام. مع I نستخدم have: have lost.'),
          fill('They haven’t discovered a cure for the common cold ___.',
            'لم يكتشفوا علاجاً لنزلة البرد الشائعة ___.',
            'لم يكتشفوا علاجاً لنزلة البرد الشائعة بعد.',
            ['already', 'yet', 'since'], 1,
            'yet تأتي في آخر الجملة المنفية أو السؤال في المضارع التام، لتدلّ على شيء لم يحدث حتى الآن. already تأتي في الجملة المثبتة.'),

          // ---- extra practice: write the page 9 B questions yourself ----
          build('Is she working on a new project?', 'اكتب السؤال: هل تعمل على مشروع جديد؟',
            'مضارع مستمر: Is + she + working.'),
          build('Has he returned from Europe?', 'اكتب السؤال: هل عاد من أوروبا؟',
            'مضارع تام: Has + he + returned.'),
          build('Has Maya taught English since 2019?', 'اكتب السؤال: هل تُدرّس مايا الإنكليزية منذ 2019؟',
            'مضارع تام مع since: Has + Maya + taught.'),
          build('Does Susan enjoy reading?', 'اكتب السؤال: هل تستمتع سوزان بالقراءة؟',
            'مضارع بسيط: Does + Susan + enjoy (دون s).'),
          build('Does this car belong to Martin?', 'اكتب السؤال: هل هذه السيارة ملك لمارتن؟',
            'مضارع بسيط: Does + this car + belong (دون s).'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Ahmed is your neighbour. He has a problem with his legs, so he can’t walk. You always see him watching you sadly playing with your friends. Think of an idea to help him and write the steps you will follow to solve his problem.',
          topicAr: 'أحمد جارك، ولديه مشكلة في ساقيه فلا يستطيع المشي. تراه دائماً يراقبك بحزن وأنت تلعب مع أصدقائك. فكّر في فكرة تساعده بها، واكتب الخطوات التي ستتبعها لحلّ مشكلته.',
          words: 100,
          plan: [
            { en: 'Introduction: describe Ahmed’s problem and say that you have decided to help him (present perfect).', ar: 'المقدّمة: صِف مشكلة أحمد وقل إنك قرّرت أن تساعده (المضارع التام).' },
            { en: 'Steps 1–2: talk to Ahmed, then form a team of volunteers with your friends.', ar: 'الخطوتان 1–2: تحدّث مع أحمد، ثم كوّن فريقاً من المتطوّعين مع أصدقائك.' },
            { en: 'Steps 3–4: provide what he needs (a wheelchair) and choose games he can play with you.', ar: 'الخطوتان 3–4: وفّر له ما يحتاجه (كرسي متحرّك) واختر ألعاباً يستطيع أن يلعبها معكم.' },
            { en: 'Conclusion: the last step and the difference it will make to his life.', ar: 'الخاتمة: الخطوة الأخيرة والفرق الذي ستُحدثه في حياته.' },
          ],
          phrases: [
            { en: 'I have decided to …', ar: 'لقد قرّرت أن …' },
            { en: 'I have always seen him …', ar: 'لطالما رأيته …' },
            { en: 'First, … Second, … Then, … After that, … Finally, …', ar: 'أولاً، … ثانياً، … ثم، … بعد ذلك، … أخيراً، …' },
            { en: 'an initiative', ar: 'مبادرة' },
            { en: 'a team of volunteers', ar: 'فريق من المتطوّعين' },
            { en: 'provide him with …', ar: 'يزوّده بـ …' },
            { en: 'He can’t afford it.', ar: 'لا يستطيع أن يدفع ثمنه.' },
            { en: 'anyone in need', ar: 'أي شخص محتاج' },
            { en: 'bring some light into his life', ar: 'يُدخل بعض النور إلى حياته' },
            { en: 'make a difference', ar: 'يُحدث فرقاً' },
          ],
          model: 'Ahmed is my neighbour, and he can’t walk because he has a problem with his legs. I have always seen him watching us sadly, so I have decided to help him. First, I will visit Ahmed and ask him which games he likes. Second, I will talk to my friends and we will form a team of volunteers. Then, we will collect money from our neighbours to provide him with a new wheelchair, because his family can’t afford it. After that, we will choose games that he can play with us, like chess and table tennis. Finally, we will invite him to play with us every afternoon. In this way, we can bring some light into his life and make a difference.',
          modelAr: 'أحمد جاري، ولا يستطيع المشي لأن لديه مشكلة في ساقيه. لطالما رأيته يراقبنا بحزن، لذلك قرّرت أن أساعده. أولاً، سأزور أحمد وأسأله عن الألعاب التي يحبّها. ثانياً، سأتحدّث مع أصدقائي وسنكوّن فريقاً من المتطوّعين. ثم سنجمع المال من جيراننا لنقدّم له كرسياً متحرّكاً جديداً، لأن عائلته لا تستطيع دفع ثمنه. بعد ذلك، سنختار ألعاباً يستطيع أن يلعبها معنا، مثل الشطرنج وكرة الطاولة. وأخيراً، سندعوه ليلعب معنا كل مساء. وبهذه الطريقة نستطيع أن نُدخل بعض النور إلى حياته ونُحدث فرقاً.',
          checklistAr: [
            'هل وصفت مشكلة أحمد في البداية؟',
            'هل ذكرت فكرة واضحة لمساعدته؟',
            'هل كتبت الخطوات بالترتيب مستخدماً First, Second, Then, After that, Finally؟',
            'هل استخدمت will للخطوات التي ستقوم بها والمضارع التام (I have decided) بشكل صحيح؟',
            'هل ختمت بالنتيجة والفرق الذي ستُحدثه في حياته؟',
            'هل الفقرة نحو 100 كلمة، وراجعت التهجئة وعلامات الترقيم؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Think of a personal initiative that you can launch to help your community. Write about how you and your friends are going to apply it.',
          topicAr: 'فكّر في مبادرة شخصية تستطيع أن تُطلقها لمساعدة مجتمعك. اكتب كيف ستطبّقها أنت وأصدقاؤك (فقرة تشرح الخطوات).',
          words: 100,
          points: [
            'Step 1: (announce for the initiative in the school magazine)',
            'Step 2: (assign a task for each member of the team).',
          ],
          pointsAr: [
            'الخطوة 1: (الإعلان عن المبادرة في مجلة المدرسة)',
            'الخطوة 2: (توزيع مهمة على كل عضو في الفريق).',
          ],
          plan: [
            { en: 'Topic sentence: name your initiative and say who it will help.', ar: 'الجملة الرئيسية: سمِّ مبادرتك وقل من ستساعد.' },
            { en: 'Steps 1–2: announce the initiative in the school magazine and assign a task for each member of the team.', ar: 'الخطوتان 1–2: أعلن عن المبادرة في مجلة المدرسة ووزّع مهمة على كل عضو في الفريق.' },
            { en: 'Steps 3–5: what the team is going to do, in order (First, Then, After that).', ar: 'الخطوات 3–5: ما سيفعله الفريق بالترتيب (First, Then, After that).' },
            { en: 'Last step and conclusion: finish the process and say what difference it will make.', ar: 'الخطوة الأخيرة والخاتمة: أنهِ العملية وقل ما الفرق الذي ستُحدثه.' },
          ],
          phrases: [
            { en: 'launch an initiative', ar: 'يُطلق مبادرة' },
            { en: 'We are going to …', ar: 'سوف … (نحن ننوي أن …)' },
            { en: 'announce the initiative in the school magazine', ar: 'يعلن عن المبادرة في مجلة المدرسة' },
            { en: 'assign a task for each member of the team', ar: 'يوزّع مهمة على كل عضو في الفريق' },
            { en: 'volunteers', ar: 'متطوّعون' },
            { en: 'anyone in need', ar: 'أي شخص محتاج' },
            { en: 'a wall of kindness', ar: 'جدار اللطف' },
            { en: 'absolutely free', ar: 'مجاني تماماً' },
            { en: 'a Facebook page', ar: 'صفحة على فيسبوك' },
            { en: 'An act of kindness can change a life.', ar: 'عملٌ لطيف واحد قد يغيّر حياة.' },
            { en: 'First, … Then, … After that, … Finally, …', ar: 'أولاً، … ثم، … بعد ذلك، … أخيراً، …' },
          ],
          model: 'My friends and I are going to launch an initiative called "Wall of Kindness" to help people in need in our town. First, we are going to announce the initiative in the school magazine and on a Facebook page. Second, we are going to assign a task for each member of the team. Then, we are going to ask our headmaster for a wall next to the school gate. After that, some volunteers are going to collect warm clothes from families, and others are going to hang them on the wall. Anyone in need can take a jacket, absolutely free. Finally, we are going to thank everyone who has helped us, because an act of kindness can change a life.',
          modelAr: 'أنا وأصدقائي سنُطلق مبادرة اسمها «جدار اللطف» لمساعدة المحتاجين في بلدتنا. أولاً، سنعلن عن المبادرة في مجلة المدرسة وعلى صفحة في فيسبوك. ثانياً، سنوزّع مهمة على كل عضو في الفريق. ثم سنطلب من مدير المدرسة جداراً بجانب بوابة المدرسة. بعد ذلك، سيجمع بعض المتطوّعين الملابس الدافئة من العائلات، وسيعلّقها آخرون على الجدار. ويستطيع أي محتاج أن يأخذ سترة مجاناً تماماً. وأخيراً، سنشكر كل من ساعدنا، لأن عملاً لطيفاً واحداً قد يغيّر حياة.',
          checklistAr: [
            'هل سمّيت المبادرة وذكرت من ستساعد في الجملة الأولى؟',
            'هل كتبت الخطوات بالترتيب، وبدأت بالإعلان عن المبادرة وتوزيع المهام كما يطلب الكتاب؟',
            'هل استخدمت كلمات الترتيب (First, Second, Then, After that, Finally)؟',
            'هل استخدمت going to للخطط المستقبلية بشكل صحيح (we are going to + المصدر)؟',
            'هل ختمت بالفرق الذي ستُحدثه المبادرة؟',
            'هل الفقرة نحو 100 كلمة، وراجعت التهجئة وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'Eight hours later, the page had attracted more than 20,000 likes.', ar: 'بعد ثماني ساعات، كانت الصفحة قد جذبت أكثر من عشرين ألف إعجاب.' },
        { en: 'This initiative was forgotten, but then it revived again in 2011.', ar: 'نُسيت هذه المبادرة، لكنها عادت إلى الحياة من جديد في عام 2011.' },
        { en: 'You can buy it for anyone in need.', ar: 'يمكنك أن تشتريها لأي شخص محتاج.' },
        { en: 'She is working on a new project.', ar: 'إنها تعمل على مشروع جديد.' },
        { en: 'Maya has taught English since 2019.', ar: 'تُدرّس مايا اللغة الإنكليزية منذ عام 2019.' },
        { en: 'She has already seen this film.', ar: 'لقد شاهدت هذا الفيلم من قبل.' },
        { en: 'I have been in this city since last year.', ar: 'أنا في هذه المدينة منذ العام الماضي.' },
        { en: 'Mr. Smith has been a teacher for nine years.', ar: 'السيد سميث يعمل معلّماً منذ تسع سنوات.' },
        { en: 'They haven’t discovered a cure for the common cold yet.', ar: 'لم يكتشفوا علاجاً لنزلة البرد الشائعة حتى الآن.' },
        { en: 'Light Initiative started with two people and now it includes more than 350 volunteers.', ar: 'بدأت مبادرة «نور» بشخصين، وهي تضمّ الآن أكثر من 350 متطوّعاً.' },
        { en: 'They voluntarily record school and college books for the benefit of the visually impaired people.', ar: 'إنهم يسجّلون الكتب المدرسية والجامعية تطوّعاً لصالح المكفوفين وضعاف البصر.' },
        { en: 'They use a Facebook page and a YouTube channel.', ar: 'إنهم يستخدمون صفحة على فيسبوك وقناة على يوتيوب.' },
        { en: 'These records are saved in mp3 format.', ar: 'تُحفظ هذه التسجيلات بصيغة mp3.' },
        { en: 'Anyone with a network can have access to their records.', ar: 'يستطيع أي شخص لديه اتصال بالشبكة أن يصل إلى تسجيلاتهم.' },
        { en: 'They use mobiles for recording and laptops to do the montage.', ar: 'يستخدمون الهواتف المحمولة للتسجيل والحواسيب المحمولة لإجراء المونتاج.' },
        { en: 'Light Initiative’s new project is turning the Syrian curriculum into Braille.', ar: 'مشروع مبادرة «نور» الجديد هو تحويل المنهاج السوري إلى طريقة بريل.' },
        { en: 'This will help Syrian students who suffer from sight problems.', ar: 'سيساعد هذا الطلاب السوريين الذين يعانون من مشكلات في البصر.' },
        { en: 'Light Initiative is trying to bring some light into the visually impaired people’s lives.', ar: 'تحاول مبادرة «نور» أن تُدخل بعض النور إلى حياة المكفوفين وضعاف البصر.' },
      ],
    },
  },
}
