import type { ModuleExtras } from './merge'
import type { GrammarExercise } from '../../../engine/types'

// Activity Book, Module 3 "Decision Making": Unit 5 (pages 19–22), Unit 6 (pages 23–26),
// Progress Test (I) (pages 27–31). Every item the pages print, solved, in the book's order.
// Left out: the listening tasks (their answers are in the recording), the open speaking questions,
// and the Progress Test's open writing task.

const fill = (prompt: string, options: string[], answer: number, promptAr: string, promptArFull: string, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, options, answer, promptAr, promptArFull, explainAr })
const mcq = (prompt: string, options: string[], answer: number, promptAr: string, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, options, answer, promptAr, explainAr })
const tf = (prompt: string, answer: boolean, promptAr: string, explainAr: string): GrammarExercise =>
  ({ type: 'truefalse', prompt, answer, promptAr, explainAr })
const build = (answer: string, prompt: string, explainAr: string): GrammarExercise =>
  ({ type: 'build', answer, prompt, explainAr })

// ---------------------------------------------------------------- Unit 5: Make up your Mind (Activity Book 19–22)

const KEY_U5 = {
  sorrowfully: 'sadly',
  option: 'a choice you can make in a particular situation',
  impatient: 'annoyed because of delays, or because of someone else\'s mistakes (restless)',
}

const MATCH_U5 = {
  a: 'you\'ll only regret it.',
  b: 'decision about our career.',
  c: 'options available to us.',
  d: 'what we all might do in life.',
  e: 'if you want to get all the options.',
  f: 'to be successful.',
}

const u5Exercises: GrammarExercise[] = [
  // Key Words (page 19)
  mcq('Key Words: what does “sorrowfully” mean?', ['happily', KEY_U5.sorrowfully, 'quickly', 'angrily'], 1,
    'الكلمات المفتاحية: ما معنى sorrowfully؟',
    'sorrowfully = بحزن (sadly). في النص: "No, wait please, I should choose the most suitable and delicious cake." Sam said sorrowfully.'),
  mcq('Key Words: what does “an option” mean?', ['a large shop that sells cakes', 'a feeling of sadness', KEY_U5.option, 'a person who makes cakes'], 2,
    'الكلمات المفتاحية: ما معنى an option؟',
    'option = خيار: شيء يمكنك أن تختاره في موقف معيّن. في النص: all of the options looked so good (كل الخيارات بدت جيدة جداً).'),
  mcq('Key Words: what does “impatient” mean?', [KEY_U5.impatient, 'calm and relaxed', 'very tired after hard work', 'happy and friendly'], 0,
    'الكلمات المفتاحية: ما معنى impatient؟',
    'impatient = نافد الصبر: منزعج بسبب التأخير أو بسبب أخطاء غيره (restless). في النص: the impatient chef — الطاهي الذي لم يعد يحتمل تردّد سام.'),

  // Reading B — match column A with B (page 20)
  mcq('Match: “This world is full of …”', [MATCH_U5.a, MATCH_U5.c, MATCH_U5.d, MATCH_U5.f], 1,
    'صِل: «هذا العالم مليء بـ …»',
    'This world is full of options available to us = هذا العالم مليء بالخيارات المتاحة لنا. بعد full of نحتاج اسماً (options)، والنص يقول: We have extremely large numbers of options available to us.'),
  mcq('Match: “If you don\'t make the right decision now, …”', [MATCH_U5.e, MATCH_U5.b, MATCH_U5.a, MATCH_U5.d], 2,
    'صِل: «إذا لم تتخذ القرار الصحيح الآن، …»',
    'If you don\'t make the right decision now, you\'ll only regret it = ستندم فقط. هذه جملة شرطية من النوع الأول: If + مضارع بسيط، ثم will + المصدر (you\'ll regret).'),
  mcq('Match: “You may end with nothing …”', [MATCH_U5.f, MATCH_U5.e, MATCH_U5.c, MATCH_U5.a], 1,
    'صِل: «قد ينتهي بك الأمر بلا شيء …»',
    'You may end with nothing if you want to get all the options = إذا أردت أن تحصل على كل الخيارات. هذا ما حدث لسام: He wanted them all, but ended up with nothing.'),
  mcq('Match: “Make up your mind …”', [MATCH_U5.f, MATCH_U5.d, MATCH_U5.b, MATCH_U5.c], 0,
    'صِل: «اتّخذ قرارك …»',
    'Make up your mind to be successful = اتّخذ قرارك لكي تنجح. بعد make up your mind نضع to + المصدر لبيان الهدف.'),
  mcq('Match: “Sam did …”', [MATCH_U5.a, MATCH_U5.b, MATCH_U5.e, MATCH_U5.d], 3,
    'صِل: «فعل سام …»',
    'Sam did what we all might do in life = فعل سام ما قد نفعله جميعاً في الحياة. النص: It\'s just that we\'re all Sam and the world is that cake shop. (الجملة b فائضة لا تُستخدم.)'),

  // Vocabulary — complete the statements (page 20)
  fill('Tickets are ___ in the box office.', ['extremely', 'available', 'investment', 'regret'], 1,
    'التذاكر ___ في شبّاك التذاكر.',
    'التذاكر متوفّرة في شبّاك التذاكر.',
    'available = متوفّر / متاح (صفة). بعد are نحتاج صفة تصف التذاكر، ومنها في النص: options available to us.'),
  fill('Earthquakes are ___ difficult to predict.', ['available', 'regret', 'extremely', 'investment'], 2,
    'الزلازل ___ صعبة التنبؤ.',
    'الزلازل صعبة التنبؤ للغاية.',
    'extremely = للغاية / جداً (ظرف). يأتي قبل الصفة difficult ليقوّيها، كما في النص: extremely large numbers of options.'),
  fill('Don\'t do anything you might ___.', ['regret', 'available', 'extremely', 'investment'], 0,
    'لا تفعل أي شيء قد ___.',
    'لا تفعل أي شيء قد تندم عليه.',
    'regret = يندم (فعل). بعد might نضع فعلاً في صيغة المصدر: might regret. وفي النص: What if we regret the direction that we take?'),
  fill('We plan to buy some property as an ___.', ['regret', 'extremely', 'available', 'investment'], 3,
    'نخطّط لشراء بعض العقارات كـ ___.',
    'نخطّط لشراء بعض العقارات كاستثمار.',
    'investment = استثمار (اسم). بعد an نحتاج اسماً يبدأ بصوت متحرّك (an investment). وفي النص: career, education, relationships, investments.'),

  // Grammar — the rule box examples
  build('He was playing football at 10 am yesterday.', 'كان يلعب كرة القدم في الساعة العاشرة صباح أمس.',
    'الماضي المستمر (was/were + فعل ing) لحدث كان مستمراً في وقت محدّد في الماضي: at 10 am yesterday.'),
  build('Anne was writing a letter while Steve was reading the newspaper.', 'كانت آن تكتب رسالة بينما كان ستيف يقرأ الجريدة.',
    'حدثان كانا مستمرّين في الوقت نفسه في الماضي ولا يؤثر أحدهما في الآخر: الماضي المستمر في الجملتين، ونربطهما بـ while.'),
  build('When I was having breakfast, the phone suddenly rang.', 'عندما كنت أتناول الفطور، رنّ الهاتف فجأة.',
    'الحدث الطويل الذي بدأ أولاً وكان مستمراً ← ماضٍ مستمر (was having)، والحدث القصير الذي قطعه ← ماضٍ بسيط (rang).'),
  build('Sue bought a book, went home and started to read it.', 'اشترت سو كتاباً، وذهبت إلى البيت، وبدأت تقرؤه.',
    'أحداث متتالية في الماضي، واحد بعد الآخر في وقت قصير ← الماضي البسيط لكل الأفعال: bought, went, started.'),

  // Grammar A — select the correct answer between brackets (page 21)
  fill('He ___ an e-mail when the phone rang.', ['was writing', 'wrote', 'is writing'], 0,
    'هو ___ رسالة إلكترونية عندما رنّ الهاتف.',
    'كان يكتب رسالة إلكترونية عندما رنّ الهاتف.',
    'الحدث الطويل الذي كان جارياً (الكتابة) ← الماضي المستمر was writing، والحدث القصير الذي قطعه (رنين الهاتف) ← الماضي البسيط rang بعد when.'),
  fill('I ___ dinner while Melanie was working upstairs.', ['were preparing', 'was preparing', 'am preparing'], 1,
    'أنا ___ العشاء بينما كانت ميلاني تعمل في الطابق العلوي.',
    'كنت أحضّر العشاء بينما كانت ميلاني تعمل في الطابق العلوي.',
    'مع I نستخدم was وليس were. وحدثان مستمران في الوقت نفسه ← الماضي المستمر في الجملتين (was preparing … was working).'),
  fill('I wasn\'t sleeping when you ___ home last night.', ['come', 'were coming', 'came'], 2,
    'لم أكن نائماً عندما ___ إلى البيت الليلة الماضية.',
    'لم أكن نائماً عندما عدتَ إلى البيت الليلة الماضية.',
    'last night تدل على الماضي، فلا نستخدم المضارع come. والحدث القصير بعد when يأتي في الماضي البسيط: came.'),
  fill('When Mrs. Brown ___, the girls were studying.', ['arrived', 'arrives', 'was arriving'], 0,
    'عندما ___ السيدة براون، كانت الفتيات يدرسن.',
    'عندما وصلت السيدة براون، كانت الفتيات يدرسن.',
    'الوصول حدث قصير قطع حدثاً مستمراً (were studying) ← الماضي البسيط arrived بعد when.'),
  fill('I lost my keys while I ___ to school.', ['walked', 'was walking', 'am walking'], 1,
    'أضعت مفاتيحي بينما ___ إلى المدرسة.',
    'أضعت مفاتيحي بينما كنت أمشي إلى المدرسة.',
    'بعد while نستخدم عادة الماضي المستمر للحدث الطويل: was walking، والحدث القصير (أضعت) في الماضي البسيط lost.'),

  // Grammar B — past progressive or past simple (page 21)
  fill('Tom ___ the gift when I ___ into the room. (wrap / walk)', ['was wrapping … walked', 'wrapped … was walking', 'was wrapping … was walking', 'wraps … walked'], 0,
    'توم ___ الهدية عندما ___ إلى الغرفة.',
    'كان توم يغلّف الهدية عندما دخلتُ إلى الغرفة.',
    'هذا مثال الكتاب: الحدث الطويل (تغليف الهدية) ← was wrapping، والحدث القصير الذي قطعه (دخولي) ← walked بعد when.'),
  fill('What ___ the manager ___ at 7:00 pm yesterday? (do)', ['did … doing', 'was … do', 'were … doing', 'was … doing'], 3,
    'ماذا ___ المدير في الساعة السابعة من مساء أمس؟',
    'ماذا كان المدير يفعل في الساعة السابعة من مساء أمس؟',
    'وقت محدّد في الماضي (at 7:00 pm yesterday) ← الماضي المستمر. في السؤال: What + was + الفاعل + فعل ing ← What was the manager doing? (المدير مفرد فنستخدم was).'),
  fill('Tina and Shelly ___ to the hotel when it ___ to rain. (walk / start)', ['was walking … started', 'were walking … started', 'walked … was starting', 'were walking … starts'], 1,
    'تينا وشيلي ___ إلى الفندق عندما ___ المطر بالهطول.',
    'كانت تينا وشيلي تمشيان إلى الفندق عندما بدأ المطر بالهطول.',
    'Tina and Shelly جمع ← were walking (الحدث الطويل)، وبدء المطر حدث قصير قطعه ← started بعد when.'),
  fill('When Donny ___ the room, everyone ___. (enter / talk)', ['entered … was talking', 'was entering … talked', 'entered … were talking', 'enters … was talking'], 0,
    'عندما ___ دوني الغرفة، ___ الجميع.',
    'عندما دخل دوني الغرفة، كان الجميع يتحدثون.',
    'الدخول حدث قصير ← entered بعد when، والحديث كان جارياً قبله ← الماضي المستمر. انتبه: everyone مفرد في الإنجليزية فنقول everyone was talking.'),
  fill('I ___ in the sales department when I first ___ Sofie. (work / meet)', ['worked … was meeting', 'were working … met', 'was working … met', 'was working … meet'], 2,
    'أنا ___ في قسم المبيعات عندما ___ صوفي لأول مرة.',
    'كنت أعمل في قسم المبيعات عندما التقيت صوفي لأول مرة.',
    'العمل في القسم كان مستمراً ← was working (مع I نستخدم was)، واللقاء الأول حدث قصير ← met (الماضي البسيط من meet).'),
  fill('My brother ___ the computer while I ___ for my trip. (use / pack)', ['were using … was packing', 'was using … was packing', 'is using … was packing', 'was using … were packing'], 1,
    'أخي ___ الحاسوب بينما ___ أغراضي لرحلتي.',
    'كان أخي يستخدم الحاسوب بينما كنت أحزم أغراضي لرحلتي.',
    'حدثان كانا مستمرّين في الوقت نفسه ← الماضي المستمر في الجملتين مع while. My brother مفرد ← was using، وI ← was packing.'),
  fill('This morning, while I ___ breakfast, someone ___ at the door. (have / knock)', ['had … was knocking', 'were having … knocked', 'was having … knocks', 'was having … knocked'], 3,
    'هذا الصباح، بينما ___ الفطور، ___ أحدهم على الباب.',
    'هذا الصباح، بينما كنت أتناول الفطور، طرق أحدهم الباب.',
    'بعد while الحدث الطويل ← was having، والطرق على الباب حدث قصير قطعه ← knocked (الماضي البسيط).'),
]

// ---------------------------------------------------------------- Unit 6: Exciting Challenge (Activity Book 23–26)

const KEY_U6 = {
  eventually: 'after a long time, or after a lot of things have happened',
  enrol: 'to arrange to join a school, university or course',
  garner: 'to take or collect something, especially information',
  accomplishment: 'something successful that is achieved after hard work',
  ovation: 'when the audience stands up and clap',
  implementing: 'putting a decision/plan/etc. into effect',
}

const u6Exercises: GrammarExercise[] = [
  // Reading B — true or false (page 24)
  tf('Isabella Springmuhl Tejada decided to follow the footsteps of her mother.', false,
    'قرّرت إيزابيلا سبرينغمول تيخادا أن تسير على خطى أمّها.',
    'خطأ. التصحيح: Isabella decided to follow the footsteps of her grandmother who was a designer. (جدّتها المصمّمة وليس أمّها).'),
  tf('In 2016 Isabella\'s designs were shown at London Fashion Week.', true,
    'في عام 2016 عُرضت تصاميم إيزابيلا في أسبوع لندن للموضة.',
    'صحيح. النص: in 2016 her designs were shown at London Fashion Week, which was followed by another exhibit in Rome.'),
  tf('Sujeet Desai decided to study Maths.', false,
    'قرّر سوجيت ديساي أن يدرس الرياضيات.',
    'خطأ. التصحيح: Sujeet Desai decided to study music and graduated from Berkshire Hills Music Academy.'),
  tf('Pablo Pineda lost the Silver Shell Award.', false,
    'خسر بابلو بينيدا جائزة الصدفة الفضية.',
    'خطأ. التصحيح: In 2009, Pablo Pineda won the Silver Shell Award at the International Film Festival. (won = فاز، عكس lost).'),

  // Key Words (page 24)
  mcq('Key Words: what does “eventually” mean?', [KEY_U6.garner, KEY_U6.eventually, KEY_U6.enrol, KEY_U6.implementing], 1,
    'الكلمات المفتاحية: ما معنى eventually؟',
    'eventually = في النهاية / بعد وقت طويل. في النص: playing eventually turned into work (تحوّل اللعب في النهاية إلى عمل).'),
  mcq('Key Words: what does “enrol” mean?', [KEY_U6.enrol, KEY_U6.accomplishment, KEY_U6.ovation, KEY_U6.eventually], 0,
    'الكلمات المفتاحية: ما معنى enrol؟',
    'enrol = يلتحق / يسجّل في مدرسة أو جامعة أو دورة. في النص: when she enrolled in a fashion course.'),
  mcq('Key Words: what does “garner” mean?', [KEY_U6.implementing, KEY_U6.enrol, KEY_U6.garner, KEY_U6.ovation], 2,
    'الكلمات المفتاحية: ما معنى garner؟',
    'garner = يجمع / يحصد (خاصةً المعلومات أو الاهتمام). في النص: The success of her show garnered international attention.'),
  mcq('Key Words: what does “accomplishment” mean?', [KEY_U6.eventually, KEY_U6.garner, KEY_U6.ovation, KEY_U6.accomplishment], 3,
    'الكلمات المفتاحية: ما معنى accomplishment؟',
    'accomplishment = إنجاز: شيء ناجح يتحقّق بعد عمل شاق. في النص: His greatest accomplishment so far was his 2015 performance at Carnegie Hall.'),
  mcq('Key Words: what does “standing ovation” mean?', [KEY_U6.ovation, KEY_U6.implementing, KEY_U6.enrol, KEY_U6.accomplishment], 0,
    'الكلمات المفتاحية: ما معنى standing ovation؟',
    'standing ovation = تصفيق حارّ وقوفاً: عندما يقف الجمهور ويصفّق. حصل عليه ديساي بعد عرضه في قاعة كارنيغي.'),
  mcq('Key Words: what does “implementing” mean?', [KEY_U6.garner, KEY_U6.implementing, KEY_U6.eventually, KEY_U6.ovation], 1,
    'الكلمات المفتاحية: ما معنى implementing؟',
    'implementing = تنفيذ: وضع قرار أو خطة موضع التنفيذ. في النص: Pineda is currently working on implementing an international strategy.'),

  // Vocabulary — fill the gaps (page 24)
  fill('He heard someone\'s ___ in the hall.', ['footsteps', 'performance', 'instrument', 'prove'], 0,
    'سمع ___ أحدهم في الممرّ.',
    'سمع وقع خطوات أحدهم في الممرّ.',
    'footsteps = وقع الخطوات. بعد someone\'s (ملكية) نحتاج اسماً، وما يُسمع في الممرّ هو الخطوات. وفي النص: follow the footsteps of her grandmother (يسير على خطاها).'),
  fill('You are wrong, and I can ___ it.', ['graduated', 'prove', 'specifically', 'footsteps'], 1,
    'أنت مخطئ، ويمكنني أن ___ ذلك.',
    'أنت مخطئ، ويمكنني أن أثبت ذلك.',
    'prove = يُثبت (فعل). بعد can نضع الفعل في صيغة المصدر: can prove. وفي النص: people ... who have proved that they have been really good at making decisions.'),
  fill('She ___ from university this year.', ['performance', 'instrument', 'graduated', 'prove'], 2,
    'هي ___ من الجامعة هذا العام.',
    'تخرّجت من الجامعة هذا العام.',
    'graduate from = يتخرّج من. نحتاج فعلاً في الماضي بعد الفاعل She: graduated. وفي النص: graduated from Berkshire Hills Music Academy.'),
  fill('I ___ told you not to go near the water.', ['footsteps', 'graduated', 'performance', 'specifically'], 3,
    'أنا ___ قلت لك ألا تقترب من الماء.',
    'قلت لك تحديداً ألا تقترب من الماء.',
    'specifically = تحديداً / بشكل خاص (ظرف) يأتي قبل الفعل told. وفي النص: Her designs aimed specifically at people with Down Syndrome.'),
  fill('She gave the greatest ___ of her career.', ['performance', 'prove', 'specifically', 'graduated'], 0,
    'قدّمت أعظم ___ في مسيرتها المهنية.',
    'قدّمت أعظم أداء في مسيرتها المهنية.',
    'performance = أداء / عرض (اسم) بعد the greatest. وفي النص: his 2015 performance at Carnegie Hall.'),
  fill('Is he learning to play an ___?', ['footsteps', 'instrument', 'performance', 'prove'], 1,
    'هل يتعلّم العزف على ___؟',
    'هل يتعلّم العزف على آلة موسيقية؟',
    'instrument = آلة موسيقية. play an instrument = يعزف على آلة، وan تناسب الكلمة لأنها تبدأ بصوت متحرّك. وفي النص: Desai can play seven instruments.'),

  // Grammar — the rule box examples
  build('Please, have a seat!', 'تفضّل، اجلس من فضلك!',
    'الأمر المثبت: نبدأ بالفعل في صيغة المصدر (have) دون فاعل، وplease تجعل الطلب مهذّباً.'),
  build('Don\'t speak Arabic in class!', 'لا تتكلّم العربية في الصف!',
    'الأمر المنفي: Don\'t (do not) + الفعل في صيغة المصدر: Don\'t speak.'),

  // Grammar A — select the best imperative (page 25)
  fill('___ warmly so you don\'t get cold outside. It\'s snowing!', ['Dressing', 'To dress', 'Dress'], 2,
    '___ ملابس دافئة حتى لا تبرد في الخارج. إنها تثلج!',
    'البس ملابس دافئة حتى لا تبرد في الخارج. إنها تثلج!',
    'الأمر المثبت يبدأ بالفعل في صيغة المصدر: Dress. لا نستخدم ing ولا to في صيغة الأمر.'),
  fill('___ after you eat a big meal. It\'s not a good idea.', ['Exercise', 'Don\'t exercise', 'Not exercise'], 1,
    '___ بعد أن تأكل وجبة كبيرة. إنها ليست فكرة جيدة.',
    'لا تمارس الرياضة بعد أن تأكل وجبة كبيرة. إنها ليست فكرة جيدة.',
    'عبارة It\'s not a good idea تدل على تحذير ← الأمر المنفي: Don\'t + المصدر (Don\'t exercise). لا نقول Not exercise.'),
  fill('Boss: Always ___ your documents as soon as you finish writing them. Employee: OK, I will.', ['save', 'don\'t save', 'saving'], 0,
    'المدير: ___ مستنداتك دائماً فور انتهائك من كتابتها. الموظف: حسناً، سأفعل.',
    'المدير: احفظ مستنداتك دائماً فور انتهائك من كتابتها. الموظف: حسناً، سأفعل.',
    'الموظف يجيب OK, I will أي سيفعل ذلك، فهو أمر مثبت: Always save. نستطيع وضع always قبل فعل الأمر.'),
  fill('Wife: ___ me when I am speaking. Husband: Sorry.', ['Interrupt', 'Please, not interrupt', 'Please, don\'t interrupt'], 2,
    'الزوجة: ___ عندما أتكلّم. الزوج: آسف.',
    'الزوجة: من فضلك، لا تقاطعني عندما أتكلّم. الزوج: آسف.',
    'الزوج يعتذر (Sorry)، إذن الزوجة طلبت منه ألّا يقاطعها ← أمر منفي مهذّب: Please, don\'t interrupt.'),

  // Grammar B — select the correct verbs between brackets (page 25)
  fill('A: ___ careful! B: Why? What\'s wrong? A: You\'re standing on my foot.', ['To be', 'Be', 'Being'], 1,
    'أ: ___ حذراً! ب: لماذا؟ ما الخطب؟ أ: أنت تقف على قدمي.',
    'أ: كن حذراً! ب: لماذا؟ ما الخطب؟ أ: أنت تقف على قدمي.',
    'فعل الأمر من to be هو Be (المصدر دون to): Be careful! مثل Be quiet! في قاعدة الكتاب.'),
  fill('A: Hello everybody. Please ___ down and open your books.', ['sit', 'sits', 'sitting'], 0,
    'أ: مرحباً بالجميع. من فضلكم ___ وافتحوا كتبكم.',
    'أ: مرحباً بالجميع. من فضلكم اجلسوا وافتحوا كتبكم.',
    'فعل الأمر يأتي في صيغة المصدر دون s: Please sit down. لا نضيف s لأنه لا يوجد فاعل he/she.'),
  fill('A: No, today we\'re going to study. ___ your books, and let\'s start!', ['Opening', 'To open', 'Open'], 2,
    'أ: لا، اليوم سندرس. ___ كتبكم، ولنبدأ!',
    'أ: لا، اليوم سندرس. افتحوا كتبكم، ولنبدأ!',
    'الأمر المثبت = المصدر: Open your books. الصيغة Opening ليست أمراً.'),
  fill('A: No, today we\'re going to study. Open your books, and ___ start!', ['let', 'let\'s', 'lets'], 1,
    'أ: لا، اليوم سندرس. افتحوا كتبكم، و ___ نبدأ!',
    'أ: لا، اليوم سندرس. افتحوا كتبكم، ولنبدأ!',
    'let\'s (let us) + المصدر = لِنفعل: اقتراح يشمل المتكلّم مع الآخرين. Let\'s start = لنبدأ.'),
  fill('The kitchen is really dirty! So ___ the dishes now! And vacuum the floor!', ['do', 'does', 'did'], 0,
    'المطبخ متّسخ جداً! لذلك ___ الصحون الآن! ونظّف الأرض بالمكنسة الكهربائية!',
    'المطبخ متّسخ جداً! لذلك اغسل الصحون الآن! ونظّف الأرض بالمكنسة الكهربائية!',
    'فعل الأمر في صيغة المصدر: do the dishes (اغسل الصحون)، مثل vacuum the floor بعده. لا نقول does.'),
  fill('___ make the same mistake twice.', ['Do', 'Doesn\'t', 'Don\'t'], 2,
    '___ الخطأ نفسه مرتين.',
    'لا ترتكب الخطأ نفسه مرتين.',
    'تكرار الخطأ شيء سيئ، فنحتاج تحذيراً ← الأمر المنفي: Don\'t + المصدر. لا نستخدم Doesn\'t في صيغة الأمر.'),
]

// ---------------------------------------------------------------- Progress Test (I) (Activity Book 27–31)

const MATCH_PT = {
  a: 'restless - intolerant',
  b: 'very tired',
  c: 'a long hard walk lasting several days, especially in the mountains',
  d: 'the process of losing blood from the body',
  e: 'extremely interesting and attractive',
  f: 'to change your behaviour in order to deal more successfully with a new situation',
  g: 'an old-fashioned hotel, usually in the country where people can stay the night',
  h: 'further forward in space or time',
}

const PUZZLE = {
  revive: 'to bring something back after it has not been used or existed for a period of time',
  announce: 'to tell people something officially',
  fleet: 'a group of ships or trucks',
  sustainability: 'the ability of continuing without causing damage',
  initiative: 'a new plan for dealing with a particular problem',
  bulk: 'goods bought and sold in large quantities/wholesale',
  praise: 'to express approval, love, or admiration for something',
  degradation: 'the process by which something changes to a worse condition',
  impaired: 'people with sight problems',
  profit: 'the money that you can make in business or by selling things',
  futurologist: 'someone who forecasts the future based on existing conditions',
  ascertain: 'to find out something',
}
const puzzle = (def: string, options: string[], answer: number, defAr: string, explainAr: string) =>
  mcq(`Solve the puzzle: which word means “${def}”?`, options, answer, `حلّ الأحجية: أي كلمة تعني «${defAr}»؟`, explainAr)

const ptExercises: GrammarExercise[] = [
  // Reading B — match the words with their meanings (page 28)
  mcq('Match: “bleeding”', [MATCH_PT.b, MATCH_PT.d, MATCH_PT.h, MATCH_PT.e], 1,
    'صِل الكلمة بمعناها: bleeding',
    'bleeding = نزيف (d): عملية فقدان الدم من الجسم. في النص: my toes are bleeding (أصابع قدميّ تنزف).'),
  mcq('Match: “inn”', [MATCH_PT.c, MATCH_PT.a, MATCH_PT.g, MATCH_PT.f], 2,
    'صِل الكلمة بمعناها: inn',
    'inn = نُزُل / خان (g): فندق قديم الطراز، عادةً في الريف، يبيت فيه الناس ليلة. في النص: Liam is sitting with the owner of the inn.'),
  mcq('Match: “adapt”', [MATCH_PT.f, MATCH_PT.h, MATCH_PT.b, MATCH_PT.d], 0,
    'صِل الكلمة بمعناها: adapt',
    'adapt = يتكيّف (f): يغيّر سلوكه ليتعامل بنجاح أكبر مع وضع جديد. في النص: I am trying to adapt to the new way of life here.'),
  mcq('Match: “impatient”', [MATCH_PT.e, MATCH_PT.c, MATCH_PT.g, MATCH_PT.a], 3,
    'صِل الكلمة بمعناها: impatient',
    'impatient = نافد الصبر (a): restless - intolerant. في النص: He is a nice guy, but impatient. ودرسنا الكلمة نفسها في الوحدة 5 (the impatient chef).'),
  mcq('Match: “exhausted”', [MATCH_PT.a, MATCH_PT.b, MATCH_PT.e, MATCH_PT.h], 1,
    'صِل الكلمة بمعناها: exhausted',
    'exhausted = منهك جداً (b: very tired). في النص: I am exhausted and my legs are shaking.'),
  mcq('Match: “ahead”', [MATCH_PT.d, MATCH_PT.f, MATCH_PT.h, MATCH_PT.c], 2,
    'صِل الكلمة بمعناها: ahead',
    'ahead = في المقدّمة / إلى الأمام (h): أبعد إلى الأمام في المكان أو الزمان. في النص: He always walks ahead of me.'),
  mcq('Match: “trek”', [MATCH_PT.c, MATCH_PT.g, MATCH_PT.b, MATCH_PT.e], 0,
    'صِل الكلمة بمعناها: trek',
    'trek = رحلة مشي طويلة وشاقّة (c) تستمرّ عدة أيام، خاصةً في الجبال. في النص: the second day of my trek around Mount Annapurna.'),
  mcq('Match: “fascinating”', [MATCH_PT.h, MATCH_PT.a, MATCH_PT.f, MATCH_PT.e], 3,
    'صِل الكلمة بمعناها: fascinating',
    'fascinating = رائع / ساحر (e): ممتع وجذّاب للغاية. في النص: Nepal is a fascinating country.'),

  // Vocabulary A — complete the sentences with words from the list (page 28)
  fill('The accident has not caused any ___ damage.', ['beneficial', 'permanent', 'fine', 'choice'], 1,
    'لم يسبّب الحادث أي ضرر ___.',
    'لم يسبّب الحادث أي ضرر دائم.',
    'permanent = دائم (صفة) تأتي قبل الاسم damage. ضرر دائم = لا يزول.'),
  fill('All the information that we ___ has been kept in a file.', ['gathered', 'discover', 'implemented', 'fine'], 0,
    'كل المعلومات التي ___ حُفظت في ملف.',
    'كل المعلومات التي جمعناها حُفظت في ملف.',
    'gathered = جمعنا (ماضي gather). بعد we نحتاج فعلاً، والمعلومات تُجمَع. discover لا تناسب لأن الجملة تحتاج فعلاً في الماضي.'),
  fill('The police are working hard to ___ the cause of the fire.', ['gathered', 'choice', 'discover', 'permanent'], 2,
    'تعمل الشرطة بجدّ لـ ___ سبب الحريق.',
    'تعمل الشرطة بجدّ لاكتشاف سبب الحريق.',
    'بعد to نضع الفعل في صيغة المصدر: to discover = لكي تكتشف. discover the cause = يكتشف السبب.'),
  fill('A good diet is ___ for your health.', ['permanent', 'fine', 'implemented', 'beneficial'], 3,
    'النظام الغذائي الجيد ___ لصحتك.',
    'النظام الغذائي الجيد مفيد لصحتك.',
    'beneficial = مفيد (having a good effect)، وهي من كلمات الوحدة 5 في كتاب الطالب. نقول beneficial for.'),
  fill('A new work programme for young people will be ___ soon.', ['implemented', 'gathered', 'discover', 'beneficial'], 0,
    'سيتمّ ___ برنامج عمل جديد للشباب قريباً.',
    'سيتمّ تنفيذ برنامج عمل جديد للشباب قريباً.',
    'will be + التصريف الثالث = مبني للمجهول في المستقبل: will be implemented = سيُنفَّذ. implement = يضع الخطة موضع التنفيذ (implementing في الوحدة 6).'),
  fill('We have no ___ but to study hard.', ['fine', 'choice', 'permanent', 'discover'], 1,
    'ليس لدينا ___ سوى أن ندرس بجدّ.',
    'ليس لدينا خيار سوى أن ندرس بجدّ.',
    'have no choice but to = ليس أمامه خيار سوى أن. بعد no نحتاج اسماً: choice.'),
  fill('She has to pay a ___ for speeding.', ['choice', 'beneficial', 'fine', 'gathered'], 2,
    'عليها أن تدفع ___ بسبب السرعة الزائدة.',
    'عليها أن تدفع غرامة بسبب السرعة الزائدة.',
    'fine هنا اسم يعني غرامة: money that you have to pay as a punishment. pay a fine = يدفع غرامة (وليس بمعنى «بخير»).'),

  // Vocabulary B — unscramble the words (page 28)
  mcq('Unscramble the word: “dticper” (to say that something will happen in the future)', ['direct', 'predict', 'credit', 'picture'], 1,
    'رتّب الحروف لتكوّن كلمة: dticper (أن تقول إن شيئاً ما سيحدث في المستقبل)',
    'الحروف d-t-i-c-p-e-r تكوّن predict = يتنبّأ. انتبه: direct وcredit تنقصهما p، وpicture فيها u غير موجودة.'),
  mcq('Unscramble the word: “mlebupr” (a person whose job is to repair water pipes, toilets, etc)', ['number', 'humble', 'plumber', 'rumble'], 2,
    'رتّب الحروف لتكوّن كلمة: mlebupr (شخص عمله إصلاح أنابيب المياه والمراحيض وغيرها)',
    'الحروف m-l-e-b-u-p-r تكوّن plumber = سبّاك (من قصة المقهى المعلّق في الوحدة 2). حرف b في plumber لا يُلفَظ.'),
  mcq('Unscramble the word: “lnaciifbee” (having a good effect)', ['beneficial', 'financial', 'official', 'available'], 0,
    'رتّب الحروف لتكوّن كلمة: lnaciifbee (له أثر جيد)',
    'الحروف العشرة l-n-a-c-i-i-f-b-e-e تكوّن beneficial = مفيد. financial تنقصها b وe واحدة، ولها n زائدة.'),
  mcq('Unscramble the word: “iervve” (to bring something back after it has not been used or existed for a period of time)', ['review', 'arrive', 'reverse', 'revive'], 3,
    'رتّب الحروف لتكوّن كلمة: iervve (أن تعيد شيئاً بعد أن توقّف استخدامه أو وجوده مدةً من الزمن)',
    'الحروف i-e-r-v-v-e (فيها حرفا v) تكوّن revive = يُحيي / يُنعش. review فيها w غير موجودة.'),
  mcq('Unscramble the word: “uitlypm” (to increase)', ['utility', 'multiply', 'simply', 'multiple'], 1,
    'رتّب الحروف لتكوّن كلمة: uitlypm (أن يزيد)',
    'الكلمة المقصودة multiply = يضاعف / يزيد (he multiplied his profits في الوحدة 1). ملاحظة: الكتاب طبع حرف l مرة واحدة، والكلمة الصحيحة فيها حرفا l: m-u-l-t-i-p-l-y.'),
  mcq('Unscramble the word: “lgturseg” (something that is difficult for you to do or achieve)', ['gesture', 'trouble', 'struggle', 'guest'], 2,
    'رتّب الحروف لتكوّن كلمة: lgturseg (شيء يصعب عليك فعله أو تحقيقه)',
    'الحروف l-g-t-u-r-s-e-g (فيها حرفا g) تكوّن struggle = صراع / كفاح.'),
  mcq('Unscramble the word: “ilalvaeab” (that you can get or use)', ['available', 'valuable', 'variable', 'liable'], 0,
    'رتّب الحروف لتكوّن كلمة: ilalvaeab (يمكنك الحصول عليه أو استخدامه)',
    'الحروف i-l-a-l-v-a-e-a-b (فيها ثلاثة a وحرفا l) تكوّن available = متاح / متوفّر، كما في الوحدة 5: options available to us.'),
  mcq('Unscramble the word: “ilnfanaic” (relating to money)', ['official', 'final', 'beneficial', 'financial'], 3,
    'رتّب الحروف لتكوّن كلمة: ilnfanaic (متعلّق بالمال)',
    'الحروف i-l-n-f-a-n-a-i-c تكوّن financial = مالي.'),
  mcq('Unscramble the word: “llnroe” (to arrange to join a school, university or course)', ['loner', 'enroll', 'online', 'roll'], 1,
    'رتّب الحروف لتكوّن كلمة: llnroe (أن تلتحق بمدرسة أو جامعة أو دورة)',
    'الحروف l-l-n-r-o-e تكوّن enroll = يلتحق / يسجّل (وتُكتب أيضاً enrol كما في كلمات الوحدة 6).'),
  mcq('Unscramble the word: “tacr” (a vehicle with two or four wheels that is pulled by a horse)', ['card', 'act', 'cart', 'car'], 2,
    'رتّب الحروف لتكوّن كلمة: tacr (عربة لها عجلتان أو أربع عجلات يجرّها حصان)',
    'الحروف t-a-c-r تكوّن cart = عربة (bought a cart في الوحدة 1). car تنقصها t، وact تنقصها r.'),

  // Vocabulary C — solve the puzzle (page 29): each word with its meaning from the book
  puzzle(PUZZLE.revive, ['REVIVE', 'PRAISE', 'PROFIT', 'BULK'], 0, 'أن تعيد شيئاً بعد أن توقّف استخدامه أو وجوده مدةً من الزمن',
    'REVIVE = يُحيي / يُعيد. في الوحدة 2: then it revived again in 2011 (عادت الفكرة إلى الحياة).'),
  puzzle(PUZZLE.announce, ['FLEET', 'ANNOUNCE', 'ASCERTAIN', 'INITIATIVE'], 1, 'أن تخبر الناس بشيء بشكل رسمي',
    'ANNOUNCE = يُعلن. في الوحدة 2: On the Facebook page they announce ... (يعلنون على صفحة فيسبوك).'),
  puzzle(PUZZLE.fleet, ['BULK', 'PROFIT', 'FLEET', 'REVIVE'], 2, 'مجموعة من السفن أو الشاحنات',
    'FLEET = أسطول. في الوحدة 1: he became the owner of a fleet of trucks.'),
  puzzle(PUZZLE.sustainability, ['DEGRADATION', 'INITIATIVE', 'FUTUROLOGIST', 'SUSTAINABILITY'], 3, 'القدرة على الاستمرار دون إحداث ضرر',
    'SUSTAINABILITY = الاستدامة، من الوحدة 4 (مدن المستقبل).'),
  puzzle(PUZZLE.initiative, ['INITIATIVE', 'ANNOUNCE', 'PRAISE', 'ASCERTAIN'], 0, 'خطة جديدة للتعامل مع مشكلة معيّنة',
    'INITIATIVE = مبادرة، مثل Light Initiative في الوحدة 2.'),
  puzzle(PUZZLE.bulk, ['FLEET', 'BULK', 'PROFIT', 'DEGRADATION'], 1, 'بضائع تُشترى وتُباع بكميات كبيرة / بالجملة',
    'BULK = بالجملة. في الوحدة 1: thought of buying tomatoes in bulk.'),
  puzzle(PUZZLE.praise, ['REVIVE', 'ANNOUNCE', 'PRAISE', 'PROFIT'], 2, 'أن تعبّر عن الاستحسان أو الحب أو الإعجاب بشيء',
    'PRAISE = يمدح / يُثني على، من كلمات الوحدة 1.'),
  puzzle(PUZZLE.degradation, ['SUSTAINABILITY', 'INITIATIVE', 'FUTUROLOGIST', 'DEGRADATION'], 3, 'العملية التي يتحوّل بها شيء إلى حالة أسوأ',
    'DEGRADATION = تدهور، مثل environmental degradation (التدهور البيئي) في الوحدة 4.'),
  puzzle(PUZZLE.impaired, ['VISUALLY-IMPAIRED', 'FUTUROLOGIST', 'INITIATIVE', 'SUSTAINABILITY'], 0, 'أشخاص لديهم مشكلات في البصر',
    'VISUALLY-IMPAIRED = ضعاف البصر / المكفوفون. في الوحدة 2: Light Initiative is trying to bring some light into the visually impaired people\'s lives.'),
  puzzle(PUZZLE.profit, ['BULK', 'PROFIT', 'FLEET', 'PRAISE'], 1, 'المال الذي تكسبه من التجارة أو من بيع الأشياء',
    'PROFIT = ربح. في الوحدة 1: he multiplied his profits quickly.'),
  puzzle(PUZZLE.futurologist, ['ASCERTAIN', 'DEGRADATION', 'FUTUROLOGIST', 'ANNOUNCE'], 2, 'شخص يتنبّأ بالمستقبل اعتماداً على الظروف الحالية',
    'FUTUROLOGIST = عالم مستقبليات / مستشرف المستقبل، من كلمات الوحدة 3.'),
  puzzle(PUZZLE.ascertain, ['REVIVE', 'PRAISE', 'INITIATIVE', 'ASCERTAIN'], 3, 'أن تكتشف شيئاً / تتحقّق منه',
    'ASCERTAIN = يتحقّق من / يكتشف، من نص الوحدة 5: allows one to ascertain the problem.'),

  // Grammar A — select the correct verb form (page 29)
  fill('We ___ a garage next to our house. We ___ somewhere to put the car.', ['build … need', 'are building … need', 'are building … are needing', 'build … have needed'], 1,
    'نحن ___ مرآباً بجانب بيتنا. ___ مكاناً نضع فيه السيارة.',
    'نحن نبني مرآباً بجانب بيتنا. نحتاج إلى مكان نضع فيه السيارة.',
    'البناء يحدث في هذه الفترة ← المضارع المستمر are building. أما need فهو فعل حالة (state verb) لا يأتي عادة بصيغة ing ← المضارع البسيط need.'),
  fill('Mrs. James ___ early every day.', ['leaves', 'has left', 'is leaving'], 0,
    'السيدة جيمس ___ باكراً كل يوم.',
    'السيدة جيمس تغادر باكراً كل يوم.',
    'every day تدل على عادة متكرّرة ← المضارع البسيط، ومع الفاعل المفرد نضيف s: leaves.'),
  fill('They ___ the museum since 2014.', ['didn\'t visit', 'don\'t visit', 'haven\'t visited'], 2,
    'هم ___ المتحف منذ عام 2014.',
    'لم يزوروا المتحف منذ عام 2014.',
    'since + نقطة بداية في الماضي ← المضارع التام: haven\'t visited (have + not + التصريف الثالث).'),
  fill('Sarah hurt her ankle while she ___.', ['ran', 'run', 'was running'], 2,
    'آذت سارة كاحلها بينما ___.',
    'آذت سارة كاحلها بينما كانت تركض.',
    'بعد while نستخدم الماضي المستمر للحدث الطويل: was running، والإصابة حدث قصير قطعه (hurt).'),
  fill('Leila ___ lunch when her friends came.', ['was having', 'had', 'has'], 0,
    'ليلى ___ الغداء عندما جاء أصدقاؤها.',
    'كانت ليلى تتناول الغداء عندما جاء أصدقاؤها.',
    'الحدث الطويل الذي كان جارياً ← was having، ومجيء الأصدقاء حدث قصير ← came بعد when.'),
  fill('As soon as I graduate, I ___ for a job.', ['have looked', 'will look', 'looked'], 1,
    'فور تخرّجي، ___ عن عمل.',
    'فور تخرّجي، سأبحث عن عمل.',
    'الجملة عن المستقبل: بعد as soon as نستخدم المضارع البسيط (graduate)، وفي الجملة الرئيسية will + المصدر: will look.'),
  fill('This time last year, she ___ at university.', ['studied', 'is studying', 'was studying'], 2,
    'في مثل هذا الوقت من العام الماضي، هي ___ في الجامعة.',
    'في مثل هذا الوقت من العام الماضي، كانت تدرس في الجامعة.',
    'this time last year = وقت محدّد في الماضي ← الماضي المستمر was studying (حدث كان جارياً في ذلك الوقت).'),
  fill('I ___ your call because I was working.', ['missed', 'will miss', 'miss'], 0,
    'أنا ___ مكالمتك لأنني كنت أعمل.',
    'فاتتني مكالمتك لأنني كنت أعمل.',
    'I was working في الماضي، والمكالمة فاتتني أثناء ذلك ← الماضي البسيط missed.'),
  fill('When we saw the accident, we ___ the police.', ['are calling', 'called', 'call'], 1,
    'عندما رأينا الحادث، ___ الشرطة.',
    'عندما رأينا الحادث، اتصلنا بالشرطة.',
    'حدثان متتاليان في الماضي (رأينا ثم اتصلنا) ← الماضي البسيط في الجملتين: saw … called.'),
  fill('___ out! You are driving very fast.', ['Watching', 'Watch', 'To watch'], 1,
    '___! أنت تقود بسرعة كبيرة.',
    'انتبه! أنت تقود بسرعة كبيرة.',
    'تحذير ← صيغة الأمر بالمصدر: Watch out! (انتبه!)، وهي من أمثلة قاعدة الأمر في الوحدة 6.'),

  // Grammar B — complete the paragraph with the missing words (page 29)
  fill('Two men wanted ___ go swimming.', ['for', 'to', 'at'], 1,
    'أراد رجلان ___ يذهبا للسباحة.',
    'أراد رجلان أن يذهبا للسباحة.',
    'want + to + المصدر: wanted to go.'),
  fill('___ drove down to a lake.', ['Them', 'Their', 'They'], 2,
    '___ قادا السيارة إلى بحيرة.',
    'قادا السيارة إلى بحيرة.',
    'نحتاج ضمير فاعل يعود على two men في أول الجملة: They. أما Them فضمير مفعول به وTheir صفة ملكية.'),
  fill('On a little rock they saw ___ boy.', ['a', 'an', 'the'], 0,
    'على صخرة صغيرة رأيا ___ صبياً.',
    'على صخرة صغيرة رأيا صبياً.',
    'نذكر الصبي لأول مرة وهو مفرد معدود يبدأ بصوت ساكن ← a boy.'),
  fill('He had a fishing rod in ___ hands.', ['him', 'his', 'he'], 1,
    'كانت في ___ صنّارة صيد.',
    'كانت في يديه صنّارة صيد.',
    'قبل الاسم hands نحتاج صفة ملكية: his hands (يداه). him ضمير مفعول وhe ضمير فاعل.'),
  fill('“Are ___ fish biting?” one of the men asked.', ['the', 'a', 'an'], 0,
    '«هل ___ السمك يعضّ الطُّعم؟» سأل أحد الرجلين.',
    '«هل السمك يعضّ الطُّعم؟» سأل أحد الرجلين.',
    'الفعل Are جمع، فلا نستخدم a أو an (للمفرد). نقصد السمك الموجود في هذه البحيرة ← the fish.'),
  fill('“Are the fish biting?” one of ___ men asked.', ['them', 'a', 'the'], 2,
    '«هل السمك يعضّ الطُّعم؟» سأل أحد ___ الرجلين.',
    '«هل السمك يعضّ الطُّعم؟» سأل أحد الرجلين.',
    'one of + the + اسم جمع: one of the men (رجلان معروفان ذُكرا من قبل). لا نقول one of them men.'),
  fill('“No, they aren\'t,” the boy answered, “___ the worms are.”', ['and', 'so', 'but'], 2,
    '«لا، ليس كذلك،» أجاب الصبي، «___ الديدان تعضّ.»',
    '«لا، ليس كذلك،» أجاب الصبي، «لكن الديدان تعضّ.»',
    'هناك تضادّ: السمك لا يعضّ، لكن الديدان تعضّ ← but. (وهذه نكتة القصة: الديدان كانت أفاعي صغيرة!)'),
  fill('They looked at him and saw lots of little red bites on his hands ___ arms.', ['but', 'and', 'or'], 1,
    'نظرا إليه ورأيا الكثير من العضّات الحمراء الصغيرة على يديه ___ ذراعيه.',
    'نظرا إليه ورأيا الكثير من العضّات الحمراء الصغيرة على يديه وذراعيه.',
    'نجمع بين شيئين (اليدين والذراعين) ← and.'),
  fill('So, they looked ___ the can with the worms in it.', ['of', 'into', 'for'], 1,
    'لذلك نظرا ___ العلبة التي فيها الديدان.',
    'لذلك نظرا داخل العلبة التي فيها الديدان.',
    'look into = ينظر داخل شيء (العلبة). look for = يبحث عن، ولا نقول look of.'),
  fill('They found out that it was full ___ baby rattlesnakes.', ['with', 'from', 'of'], 2,
    'اكتشفا أنها كانت مليئة ___ صغار الأفاعي ذات الأجراس.',
    'اكتشفا أنها كانت مليئة بصغار الأفاعي ذات الأجراس.',
    'التعبير الصحيح full of = مليء بـ. الخطأ الشائع full with.'),

  // Speaking C — complete the dialogue with questions and answers (page 30)
  mcq('Complete the dialogue. a: Well, … — b: I have one older sister and a younger brother.', [
    'how old are you?',
    'how many brothers and sisters do you have?',
    'what does your sister do?',
    'where do you live?',
  ], 1,
    'أكمل الحوار. أ: حسناً، … — ب: لديّ أخت كبرى وأخ أصغر.',
    'الجواب يذكر عدد الإخوة، فالسؤال عن العدد مع اسم جمع: How many brothers and sisters do you have?'),
  mcq('Complete the dialogue. a: Do they look like you? — b: …', ['Yes, they are.', 'Yes, they does.', 'Yes, they do.', 'No, they aren\'t.'], 2,
    'أكمل الحوار. أ: هل يشبهونك؟ — ب: …',
    'السؤال يبدأ بـ Do، فالجواب القصير يكون بـ do: Yes, they do. أو No, they don\'t. لا نجيب بـ are لأن السؤال ليس بفعل to be.'),
  mcq('Complete the dialogue. a: So, … — b: She is a graphic designer. She works at Panorama Designs.', [
    'what does your sister do?',
    'where does your brother study?',
    'how old is your sister?',
    'does your sister like cakes?',
  ], 0,
    'أكمل الحوار. أ: إذن، … — ب: إنها مصمّمة غرافيك. تعمل في شركة بانوراما للتصميم.',
    'الجواب عن المهنة، والسؤال عن المهنة: What does she do? (ماذا تعمل؟). ولأن الحديث عن الأخت نقول what does your sister do?'),
  mcq('Complete the dialogue. a: That\'s great. … — b: She has been working there for three years.', [
    'When did she start school?',
    'Where does she work?',
    'How long has she been working there?',
    'How long does she work every day?',
  ], 2,
    'أكمل الحوار. أ: هذا رائع. … — ب: إنها تعمل هناك منذ ثلاث سنوات.',
    'الجواب for three years يدل على المدة ← How long ...? وبالزمن نفسه الذي في الجواب (المضارع التام المستمر): How long has she been working there?'),
  mcq('Complete the dialogue. a: … — b: He doesn\'t have a job right now. He is a student.', [
    'Does your sister like her job?',
    'How old is your brother?',
    'Where does your sister work?',
    'What about your brother? What does he do?',
  ], 3,
    'أكمل الحوار. أ: … — ب: ليس لديه عمل الآن. إنه طالب.',
    'الجواب عن الأخ (He) وعن عمله، فالسؤال: What about your brother? What does he do? (وماذا عن أخيك؟ ماذا يعمل؟)'),
]

// ---------------------------------------------------------------- the module

export const extras: ModuleExtras = {
  units: {
    u5: {
      workbook: {
        pages: '19–22',
        readings: [
          {
            title: 'Late to Go Back',
            paragraphs: [
              'Sam walked into a cake shop, after he\'d finished his work, to buy his daughter a birthday cake. It was about four o\'clock and the store usually closes at five. So he should make his mind quickly and decide what he should buy. Sam asked himself "Which one should I choose?" He began wandering in the shop watching the various kinds of cakes which were kept in the refrigerators around. The cakes looked very delicious and tasty so it was difficult for Sam to choose.',
              'Time was passing but in vain. Sam couldn\'t decide yet, when he heard the chef saying "Come on. Hurry up, please, we are about to close the store."',
              '"No, wait please, I should choose the most suitable and delicious cake." Sam said sorrowfully. Sam\'s eyes kept moving from one refrigerator to another, but all of the options looked so good and he couldn\'t make a decision yet.',
              '"Try to be quick Man, make up your mind, we have to close," the impatient chef said.',
              'Suddenly, the chef had enough and asked Sam to leave immediately. Sam walked out of the shop empty-handed feeling depressed and frustrated. He wanted them all, but ended up with nothing because he couldn\'t choose any.',
              'Think of what happened to Sam. It\'s just that we\'re all Sam and the world is that cake shop. We have extremely large numbers of options available to us, but if we don\'t make a decision about our career, education, relationships, investments, or other important issues, we end up empty-handed.',
              'Sometimes we worry about making the wrong decision. What if we regret the direction that we take and it\'s too late to go back? The real danger is that we make no decision at all and end up going nowhere and doing nothing.',
            ],
            paragraphsAr: [
              'دخل سام محلّاً للحلويات، بعد أن أنهى عمله، ليشتري لابنته قالب حلوى لعيد ميلادها. كانت الساعة نحو الرابعة، والمحلّ يُغلق عادةً في الخامسة. لذلك كان عليه أن يحسم أمره بسرعة ويقرّر ماذا يشتري. سأل سام نفسه: «أيّها أختار؟» وبدأ يتجوّل في المحلّ متأمّلاً الأنواع المختلفة من قوالب الحلوى المحفوظة في الثلّاجات من حوله. بدت الحلويات لذيذة وشهية جداً، لذلك كان صعباً على سام أن يختار.',
              'كان الوقت يمرّ دون فائدة. لم يستطع سام أن يقرّر بعد، حين سمع الطاهي يقول: «هيّا، أسرع من فضلك، نحن على وشك إغلاق المحلّ.»',
              '«لا، انتظر من فضلك، يجب أن أختار أنسب قالب حلوى وألذّه.» قال سام بحزن. ظلّت عينا سام تنتقلان من ثلاجة إلى أخرى، لكن كل الخيارات بدت جيدة جداً، ولم يستطع أن يتّخذ قراراً بعد.',
              '«حاول أن تكون سريعاً يا رجل، احسم أمرك، علينا أن نُغلق،» قال الطاهي نافد الصبر.',
              'وفجأة، نفد صبر الطاهي وطلب من سام أن يغادر فوراً. خرج سام من المحلّ خالي اليدين، يشعر بالكآبة والإحباط. لقد أرادها كلها، لكنه انتهى بلا شيء لأنه لم يستطع أن يختار أيّاً منها.',
              'فكّر فيما حدث لسام. الأمر ببساطة أننا جميعاً سام، والعالم هو ذلك المحلّ. لدينا أعداد كبيرة جداً من الخيارات المتاحة لنا، لكن إذا لم نتّخذ قراراً بشأن مهنتنا أو تعليمنا أو علاقاتنا أو استثماراتنا أو غيرها من الأمور المهمة، فسننتهي خاليي الأيدي.',
              'أحياناً نقلق من اتخاذ القرار الخاطئ. ماذا لو ندمنا على الطريق الذي نسلكه وكان قد فات الأوان للعودة؟ الخطر الحقيقي هو ألّا نتّخذ أي قرار على الإطلاق، فننتهي إلى لا مكان ولا نفعل شيئاً.',
            ],
            questions: [
              {
                q: 'Where did Sam go?',
                qAr: 'إلى أين ذهب سام؟',
                options: ['He went to his daughter\'s school.', 'He went into a cake shop.', 'He went to a restaurant for dinner.', 'He went home after work.'],
                answer: 1,
                explainAr: 'أول جملة في النص: Sam walked into a cake shop (دخل سام محلّاً للحلويات).',
              },
              {
                q: 'Why did he go there?',
                qAr: 'لماذا ذهب إلى هناك؟',
                options: ['To work as a chef.', 'To have lunch with his daughter.', 'To buy his daughter a birthday cake.', 'To sell his cakes.'],
                answer: 2,
                explainAr: 'النص: to buy his daughter a birthday cake. (to + المصدر تبيّن الهدف: ليشتري).',
              },
              {
                q: 'Why did the chef ask Sam to leave?',
                qAr: 'لماذا طلب الطاهي من سام أن يغادر؟',
                options: [
                  'Because Sam didn\'t have enough money.',
                  'Because Sam was rude to him.',
                  'Because Sam broke a refrigerator.',
                  'Because Sam couldn\'t make up his mind and the shop had to close.',
                ],
                answer: 3,
                explainAr: 'كان المحل سيُغلق (we are about to close the store) وسام لم يستطع أن يقرّر (he couldn\'t make a decision yet)، فنفد صبر الطاهي: the chef had enough and asked Sam to leave immediately.',
              },
              {
                q: 'How did Sam go out of the store?',
                qAr: 'كيف خرج سام من المحلّ؟',
                options: [
                  'Empty-handed, feeling depressed and frustrated.',
                  'Happy, with a big birthday cake.',
                  'With two cakes for his daughter.',
                  'Angry, after he paid the chef.',
                ],
                answer: 0,
                explainAr: 'النص: Sam walked out of the shop empty-handed feeling depressed and frustrated. (خالي اليدين، مكتئباً ومحبَطاً).',
              },
              {
                q: 'If you were Sam, what would you do?',
                qAr: 'لو كنت مكان سام، ماذا كنت ستفعل؟',
                options: [
                  'I would keep watching all the cakes until the shop closed.',
                  'I would make up my mind quickly and choose one cake before the shop closed.',
                  'I would try to buy all the cakes in the shop.',
                  'I would leave the shop without choosing anything.',
                ],
                answer: 1,
                explainAr: 'سؤال رأي، لكن درس النص واضح: الخطر الحقيقي ألّا نقرّر أبداً. لذلك الأفضل أن أحسم أمري بسرعة (make up my mind) وأختار. لاحظ القاعدة: If I were … , I would + المصدر.',
              },
              {
                q: 'According to the text, what is the real danger?',
                qAr: 'بحسب النص، ما الخطر الحقيقي؟',
                options: [
                  'That we choose the most delicious cake.',
                  'That we have too few options.',
                  'That we make no decision at all and end up going nowhere and doing nothing.',
                  'That shops close at five o\'clock.',
                ],
                answer: 2,
                explainAr: 'الجملة الأخيرة: The real danger is that we make no decision at all and end up going nowhere and doing nothing.',
              },
            ],
          },
        ],
        exercises: u5Exercises,
      },
      compositions: [
        {
          source: 'book',
          topic: 'Writing: a paragraph about a visit',
          topicAr: 'الكتابة: فقرة عن زيارة. اكتب فقرة عن زيارة قمت بها أنت أو مجموعتك (مثل زيارة القرية في كتابك)، ورتّب الأحداث مستخدماً كلمات الربط first, then, after that, finally.',
          words: 100,
          plan: [
            { en: 'Opening: where you decided to go, who went with you and why.', ar: 'البداية: إلى أين قرّرت أن تذهب، ومن ذهب معك، ولماذا.' },
            { en: 'First: how you set out and what you did when you arrived.', ar: 'أولاً: كيف انطلقت، وماذا فعلت عندما وصلت.' },
            { en: 'Then / After that: the places you visited and what people were doing (past simple and past progressive).', ar: 'ثم / بعد ذلك: الأماكن التي زرتها وماذا كان الناس يفعلون (الماضي البسيط والماضي المستمر).' },
            { en: 'Finally: how the visit ended and how you felt.', ar: 'أخيراً: كيف انتهت الزيارة وبماذا شعرت.' },
          ],
          phrases: [
            { en: 'decided to visit', ar: 'قرّر أن يزور' },
            { en: 'get away from the noise of the city', ar: 'يبتعد عن ضجيج المدينة' },
            { en: 'get an insight into the lifestyle of the local people', ar: 'يتعرّف عن قرب إلى أسلوب حياة السكان المحليين' },
            { en: 'set out for a day trip', ar: 'ينطلق في رحلة ليوم واحد' },
            { en: 'I was over the moon', ar: 'كنت في غاية السعادة' },
            { en: 'had a look at', ar: 'ألقى نظرة على' },
            { en: 'First, … / Then, … / After that, … / Finally, …', ar: 'أولاً، … / ثم، … / بعد ذلك، … / أخيراً، …' },
            { en: 'while we were walking, …', ar: 'بينما كنّا نمشي، … (الماضي المستمر)' },
            { en: 'when it began to rain', ar: 'عندما بدأ المطر بالهطول (الماضي البسيط)' },
            { en: 'friendly villagers', ar: 'قرويون ودودون' },
          ],
          model: 'Last spring, my class decided to visit my grandfather\'s village because we wanted to get away from the noise of the city. We set out early in the morning by bus. First, we walked around the village and talked to the farmers. They were working in the fields while their children were playing near the river. Then, we had a look at an old mill and some ancient houses. After that, we had lunch with a friendly family, and the food was delicious. While we were eating, it began to rain, so we stayed inside and listened to old stories. Finally, we went back home in the evening. I was over the moon, and I hope we can go there again.',
          modelAr: 'في الربيع الماضي، قرّر صفّي أن يزور قرية جدّي لأننا أردنا أن نبتعد عن ضجيج المدينة. انطلقنا باكراً في الصباح بالحافلة. أولاً، تجوّلنا في القرية وتحدّثنا إلى المزارعين. كانوا يعملون في الحقول بينما كان أطفالهم يلعبون قرب النهر. ثم ألقينا نظرة على طاحونة قديمة وبعض البيوت العتيقة. بعد ذلك، تناولنا الغداء مع عائلة ودودة، وكان الطعام لذيذاً. وبينما كنّا نأكل، بدأ المطر بالهطول، فبقينا في الداخل واستمعنا إلى حكايات قديمة. أخيراً، عدنا إلى البيت في المساء. كنت في غاية السعادة، وآمل أن نذهب إلى هناك مرة أخرى.',
          checklistAr: [
            'هل ذكرت في البداية إلى أين ذهبت ولماذا؟',
            'هل رتّبت الأحداث بكلمات الربط first, then, after that, finally؟',
            'هل استخدمت الماضي البسيط للأحداث المتتالية (walked, visited, had)؟',
            'هل استخدمت الماضي المستمر لحدث كان جارياً (were working, were playing) مع while أو when؟',
            'هل ختمت بما شعرت به في نهاية الزيارة؟',
            'هل كتبت نحو 100 كلمة وراجعت الإملاء وعلامات الترقيم؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write about a decision you have made recently. What are the steps you have followed?',
          topicAr: 'اكتب عن قرار اتخذته مؤخراً. ما الخطوات التي اتبعتها؟',
          words: 100,
          points: [
            'What was your decision about?',
            'When did you make it?',
            'What was the result?',
            'How did you feel about it?',
          ],
          pointsAr: [
            'عمَّ كان قرارك؟',
            'متى اتخذته؟',
            'ماذا كانت النتيجة؟',
            'بماذا شعرت تجاهه؟',
          ],
          plan: [
            { en: 'Say what your decision was about and when you made it.', ar: 'اذكر موضوع قرارك ومتى اتخذته.' },
            { en: 'At first: why it was not easy to make up your mind.', ar: 'في البداية: لماذا لم يكن من السهل أن تحسم أمرك.' },
            { en: 'Then / After that: the steps you followed (the options, who you asked, your plan).', ar: 'ثم / بعد ذلك: الخطوات التي اتبعتها (الخيارات، من استشرت، خطتك).' },
            { en: 'Finally: the result of your decision.', ar: 'أخيراً: نتيجة قرارك.' },
            { en: 'How you felt about it.', ar: 'بماذا شعرت تجاهه.' },
          ],
          phrases: [
            { en: 'make a decision', ar: 'يتّخذ قراراً' },
            { en: 'make up my mind', ar: 'أحسم أمري' },
            { en: 'the options available to me', ar: 'الخيارات المتاحة لي' },
            { en: 'stick to it', ar: 'يلتزم به / يتمسّك به' },
            { en: 'a top priority', ar: 'أولوية قصوى' },
            { en: 'collaborate with my family', ar: 'أتعاون مع عائلتي' },
            { en: 'time management', ar: 'إدارة الوقت' },
            { en: 'beneficial', ar: 'مفيد' },
            { en: 'regret', ar: 'يندم' },
            { en: 'At first, … / Then, … / After that, … / Finally, …', ar: 'في البداية، … / ثم، … / بعد ذلك، … / أخيراً، …' },
          ],
          model: 'Last month, I made an important decision: I decided to join the English club at my school. At first, it was not easy to make up my mind because I was worried about my other lessons. Then, I thought about all the options available to me, and I talked to my parents and my teacher. They helped me to see that English was a top priority for my future. After that, I made a plan and organized my time well. Finally, I joined the club and I stuck to my decision. The result was great: my marks went up and I made new friends. I felt proud, and I don\'t regret my decision at all.',
          modelAr: 'في الشهر الماضي، اتخذت قراراً مهماً: قرّرت أن أنضمّ إلى نادي اللغة الإنجليزية في مدرستي. في البداية، لم يكن من السهل أن أحسم أمري لأنني كنت قلقاً بشأن دروسي الأخرى. ثم فكّرت في كل الخيارات المتاحة لي، وتحدّثت إلى والديّ ومعلّمي. ساعدوني على أن أرى أن اللغة الإنجليزية أولوية قصوى لمستقبلي. بعد ذلك، وضعت خطة ونظّمت وقتي جيداً. أخيراً، انضممت إلى النادي والتزمت بقراري. كانت النتيجة رائعة: ارتفعت علاماتي وكوّنت صداقات جديدة. شعرت بالفخر، ولست نادماً على قراري أبداً.',
          checklistAr: [
            'هل أجبت عن الأسئلة الأربعة: عمَّ كان القرار؟ متى؟ ما النتيجة؟ بماذا شعرت؟',
            'هل رتّبت الخطوات بكلمات التسلسل (At first, Then, After that, Finally)؟',
            'هل استخدمت الماضي البسيط لسرد ما حدث؟',
            'هل استخدمت تعابير الوحدة مثل make up my mind وmake a decision وregret؟',
            'هل ختمت بشعورك تجاه القرار؟',
            'هل كتبت نحو 100 كلمة وراجعت الإملاء وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'We make thousands of decisions a day.', ar: 'نتّخذ آلاف القرارات في اليوم.' },
        { en: 'Choosing well takes knowledge and skill.', ar: 'الاختيار الجيد يتطلّب معرفة ومهارة.' },
        { en: 'Decision making is an ongoing process in every aspect of life, large or small.', ar: 'اتخاذ القرار عملية مستمرة في كل جانب من جوانب الحياة، كبيراً كان أم صغيراً.' },
        { en: 'Teamwork helps you to make the right decision.', ar: 'العمل الجماعي يساعدك على اتخاذ القرار الصحيح.' },
        { en: 'Also, organization is vital in your making a final decision.', ar: 'كما أن التنظيم ضروري جداً عندما تتّخذ قرارك النهائي.' },
        { en: 'We wanted to get an insight into the lifestyle of the local people there.', ar: 'أردنا أن نتعرّف عن قرب إلى أسلوب حياة السكان المحليين هناك.' },
        { en: 'It was about four o\'clock and the store usually closes at five.', ar: 'كانت الساعة نحو الرابعة، والمحلّ يُغلق عادةً في الخامسة.' },
        { en: 'The cakes looked very delicious and tasty so it was difficult for Sam to choose.', ar: 'بدت الحلويات لذيذة وشهية جداً، لذلك كان صعباً على سام أن يختار.' },
        { en: 'Suddenly, the chef had enough and asked Sam to leave immediately.', ar: 'وفجأة، نفد صبر الطاهي وطلب من سام أن يغادر فوراً.' },
        { en: 'He wanted them all, but ended up with nothing because he couldn\'t choose any.', ar: 'أرادها كلها، لكنه انتهى بلا شيء لأنه لم يستطع أن يختار أيّاً منها.' },
        { en: 'Sometimes we worry about making the wrong decision.', ar: 'أحياناً نقلق من اتخاذ القرار الخاطئ.' },
        { en: 'He was playing football at 10 am yesterday.', ar: 'كان يلعب كرة القدم في الساعة العاشرة صباح أمس.' },
        { en: 'Anne was writing a letter while Steve was reading the newspaper.', ar: 'كانت آن تكتب رسالة بينما كان ستيف يقرأ الجريدة.' },
        { en: 'I was walking down the street when it began to rain.', ar: 'كنت أمشي في الشارع عندما بدأ المطر بالهطول.' },
        { en: 'We were walking down the street when the accident happened.', ar: 'كنّا نمشي في الشارع عندما وقع الحادث.' },
        { en: 'I lost my keys while I was walking to school.', ar: 'أضعت مفاتيحي بينما كنت أمشي إلى المدرسة.' },
      ],
    },
    u6: {
      workbook: {
        pages: '23–26',
        readings: [
          {
            title: 'All are Involved Without Exception',
            paragraphs: [
              'Do you think that all individuals can make decisions?',
              'Here are some examples of successful people with Down\'s Syndrome who have proved that they have been really good at making decisions and they achieved their aims.',
              'From an early age, Isabella Springmuhl Tejada decided to follow the footsteps of her grandmother who was a designer. As a child, Isabella would create clothes for her dolls, but playing eventually turned into work when she enrolled in a fashion course. Her designs aimed specifically at people with Down Syndrome.',
              'Springmuhl had her first big showcase in 2015, where she sold her complete collection. The success of her show garnered international attention, and in 2016 her designs were shown at London Fashion Week, which was followed by another exhibit in Rome.',
              'Sujeet Desai is from Buffalo, New York. He graduated from high school. Two years later, he decided to study music and graduated from Berkshire Hills Music Academy. Now he is a famous musician. All in all, Desai can play seven instruments. His greatest accomplishment so far was his 2015 performance at Carnegie Hall, for which he received a standing ovation.',
              'Pablo Pineda is an actor and educator most well-known for being the first European with Down Syndrome who made his decision to obtain a university degree. In 2009, he won the Silver Shell Award at the International Film Festival for his role in YoTambien, a film about a university graduate with Down Syndrome. Although he still acts, Pineda is currently working on implementing an international strategy to increase employment opportunities for people with disabilities.',
              'People are able to challenge difficult circumstances and be successful. They can make the right decision if they are well-trained and if they intend to do so.',
            ],
            paragraphsAr: [
              'هل تظنّ أن كل الأفراد يستطيعون اتخاذ القرارات؟',
              'إليك بعض الأمثلة على أشخاص ناجحين من ذوي متلازمة داون أثبتوا أنهم بارعون حقاً في اتخاذ القرارات، وحقّقوا أهدافهم.',
              'منذ سنّ مبكرة، قرّرت إيزابيلا سبرينغمول تيخادا أن تسير على خطى جدّتها التي كانت مصمّمة أزياء. وحين كانت طفلة، كانت إيزابيلا تصنع الملابس لدُماها، لكن اللعب تحوّل في النهاية إلى عمل عندما التحقت بدورة في تصميم الأزياء. وقد استهدفت تصاميمها تحديداً الأشخاصَ من ذوي متلازمة داون.',
              'أقامت سبرينغمول أول عرض كبير لها عام 2015، حيث باعت مجموعتها كاملة. وقد حصد نجاح عرضها اهتماماً دولياً، وفي عام 2016 عُرضت تصاميمها في أسبوع لندن للموضة، وتلاه معرض آخر في روما.',
              'سوجيت ديساي من مدينة بافالو في نيويورك. تخرّج من المدرسة الثانوية، وبعد سنتين قرّر أن يدرس الموسيقى وتخرّج من أكاديمية بيركشاير هيلز للموسيقى. وهو الآن موسيقي مشهور. وإجمالاً، يستطيع ديساي العزف على سبع آلات موسيقية. وكان أعظم إنجازاته حتى الآن عرضه عام 2015 في قاعة كارنيغي، الذي نال عليه تصفيقاً حارّاً وقوفاً.',
              'بابلو بينيدا ممثّل ومربٍّ اشتهر أكثر ما اشتهر بكونه أول أوروبي من ذوي متلازمة داون يتّخذ قراره بالحصول على شهادة جامعية. في عام 2009 فاز بجائزة الصدفة الفضية في مهرجان الأفلام الدولي عن دوره في فيلم «يو تامبيين» (أنا أيضاً)، وهو فيلم عن خرّيج جامعي من ذوي متلازمة داون. ومع أنه ما زال يمثّل، يعمل بينيدا حالياً على تنفيذ استراتيجية دولية لزيادة فرص العمل للأشخاص ذوي الإعاقة.',
              'الناس قادرون على تحدّي الظروف الصعبة وعلى النجاح. ويمكنهم أن يتّخذوا القرار الصحيح إذا كانوا مدرَّبين جيداً وإذا عزموا على ذلك.',
            ],
            questions: [
              {
                q: 'For whom did Isabella design clothes?',
                qAr: 'لمن صمّمت إيزابيلا الملابس؟',
                options: ['For famous actors.', 'For people with Down Syndrome.', 'For her grandmother only.', 'For musicians at Carnegie Hall.'],
                answer: 1,
                explainAr: 'النص: Her designs aimed specifically at people with Down Syndrome. (استهدفت تصاميمها تحديداً ذوي متلازمة داون).',
              },
              {
                q: 'Why do you think Sujeet Desai received a standing ovation?',
                qAr: 'لماذا برأيك نال سوجيت ديساي تصفيقاً حارّاً وقوفاً؟',
                options: [
                  'Because he graduated from high school.',
                  'Because he won the Silver Shell Award.',
                  'Because his 2015 performance at Carnegie Hall was excellent — his greatest accomplishment.',
                  'Because he designed clothes for the audience.',
                ],
                answer: 2,
                explainAr: 'النص: His greatest accomplishment so far was his 2015 performance at Carnegie Hall, for which he received a standing ovation. فالجمهور وقف وصفّق لأن أداءه كان رائعاً.',
              },
              {
                q: 'What makes Pablo Pineda different?',
                qAr: 'ما الذي يجعل بابلو بينيدا مختلفاً؟',
                options: [
                  'He can play seven instruments.',
                  'He had a fashion show in Rome.',
                  'He is from Buffalo, New York.',
                  'He was the first European with Down Syndrome who made his decision to obtain a university degree.',
                ],
                answer: 3,
                explainAr: 'النص: the first European with Down Syndrome who made his decision to obtain a university degree. (أول أوروبي من ذوي متلازمة داون يحصل على شهادة جامعية).',
              },
              {
                q: 'Why is Pablo working hard to produce a new international strategy?',
                qAr: 'لماذا يعمل بابلو بجدّ لوضع استراتيجية دولية جديدة؟',
                options: [
                  'To increase employment opportunities for people with disabilities.',
                  'To win another film award.',
                  'To open a fashion school.',
                  'To become a famous musician.',
                ],
                answer: 0,
                explainAr: 'النص: an international strategy to increase employment opportunities for people with disabilities. (لزيادة فرص العمل لذوي الإعاقة).',
              },
              {
                q: 'How many instruments can Sujeet Desai play?',
                qAr: 'على كم آلة موسيقية يستطيع سوجيت ديساي أن يعزف؟',
                options: ['Two.', 'Five.', 'Seven.', 'Nine.'],
                answer: 2,
                explainAr: 'النص: All in all, Desai can play seven instruments.',
              },
            ],
            trueFalse: [
              { statement: 'Isabella Springmuhl Tejada decided to follow the footsteps of her mother.', answer: false },
              { statement: 'In 2016 Isabella\'s designs were shown at London Fashion Week.', answer: true },
              { statement: 'Sujeet Desai decided to study Maths.', answer: false },
              { statement: 'Pablo Pineda lost the Silver Shell Award.', answer: false },
            ],
          },
        ],
        exercises: u6Exercises,
      },
      compositions: [
        {
          source: 'book',
          topic: 'Let\'s say you\'re at school and you hear people making fun of someone in your class. Write what you would do. Choose one of the following solutions and write about it.',
          topicAr: 'لنفترض أنك في المدرسة وسمعت بعض الناس يسخرون من أحد زملائك في الصف. اكتب ماذا كنت ستفعل. اختر أحد الحلّين التاليين واكتب عنه.',
          words: 100,
          points: ['to be kind.', 'to defend your colleague who is being bullied.'],
          pointsAr: ['أن تكون لطيفاً.', 'أن تدافع عن زميلك الذي يتعرّض للتنمّر.'],
          plan: [
            { en: 'Describe the situation and say it is important to think carefully before you decide.', ar: 'صِف الموقف، وقل إنه من المهم أن تفكّر جيداً قبل أن تقرّر.' },
            { en: 'Say which solution you choose.', ar: 'اذكر الحلّ الذي تختاره.' },
            { en: 'First / Then: what you would say and do (use imperatives: Stop it! Don\'t laugh at him!).', ar: 'أولاً / ثم: ماذا ستقول وماذا ستفعل (استخدم صيغة الأمر: Stop it! Don\'t laugh at him!).' },
            { en: 'After that / Finally: how you would help your classmate later.', ar: 'بعد ذلك / أخيراً: كيف ستساعد زميلك لاحقاً.' },
            { en: 'Conclusion: why this is the right decision.', ar: 'الخاتمة: لماذا هذا هو القرار الصحيح.' },
          ],
          phrases: [
            { en: 'make fun of someone', ar: 'يسخر من شخص ما' },
            { en: 'defend my colleague who is being bullied', ar: 'أدافع عن زميلي الذي يتعرّض للتنمّر' },
            { en: 'think carefully and ask yourself some questions', ar: 'فكّر جيداً واسأل نفسك بعض الأسئلة' },
            { en: 'make the right decision', ar: 'يتّخذ القرار الصحيح' },
            { en: 'I would …', ar: 'كنت سأ… (لموقف افتراضي)' },
            { en: 'Stop it!', ar: 'توقّفوا عن ذلك!' },
            { en: 'Don\'t laugh at him!', ar: 'لا تضحكوا عليه!' },
            { en: 'Be kind!', ar: 'كونوا لطفاء!' },
            { en: 'Please, don\'t …', ar: 'من فضلك، لا …' },
            { en: 'First, … / Then, … / After that, … / Finally, …', ar: 'أولاً، … / ثم، … / بعد ذلك، … / أخيراً، …' },
          ],
          model: 'If I heard some students making fun of a classmate, I would think carefully and ask myself some questions before I decided what to do. I would choose to defend my colleague who is being bullied. First, I would go to the students and say, “Stop it! Don\'t laugh at him. Be kind!” Then, I would stand next to my classmate and talk to him in a friendly way, so he doesn\'t feel alone. After that, if the students didn\'t stop, I would tell our teacher. Finally, I would invite my classmate to join my friends at break time. Everyone deserves respect, and one right decision can change someone\'s day.',
          modelAr: 'لو سمعت بعض الطلاب يسخرون من زميل في الصف، لفكّرت جيداً وسألت نفسي بعض الأسئلة قبل أن أقرّر ماذا أفعل. سأختار أن أدافع عن زميلي الذي يتعرّض للتنمّر. أولاً، سأذهب إلى الطلاب وأقول: «توقّفوا! لا تضحكوا عليه. كونوا لطفاء!» ثم سأقف بجانب زميلي وأتحدّث إليه بطريقة ودودة كي لا يشعر بالوحدة. بعد ذلك، إذا لم يتوقّف الطلاب، سأخبر معلّمنا. أخيراً، سأدعو زميلي لينضمّ إلى أصدقائي في الاستراحة. كل إنسان يستحقّ الاحترام، وقرار واحد صحيح يمكن أن يغيّر يوم شخص ما.',
          checklistAr: [
            'هل وصفت الموقف واخترت أحد الحلّين بوضوح؟',
            'هل استخدمت صيغة الأمر المثبت والمنفي بشكل صحيح (Stop it! / Don\'t laugh!)؟',
            'هل استخدمت would + المصدر لتقول ماذا كنت ستفعل؟',
            'هل رتّبت خطواتك بكلمات الربط First, Then, After that, Finally؟',
            'هل ختمت بسبب يبيّن أن قرارك صحيح؟',
            'هل كتبت نحو 100 كلمة وراجعت الإملاء وعلامات الترقيم؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write a short biography about a famous person you know.',
          topicAr: 'اكتب سيرة ذاتية قصيرة عن شخص مشهور تعرفه.',
          words: 100,
          points: [
            'A biography is a story written about someone\'s life.',
            'Most biographies are written in time order: birth, childhood, teenage years, young adulthood, adulthood, old age.',
          ],
          pointsAr: [
            'السيرة الذاتية قصة تُكتب عن حياة شخص ما.',
            'تُكتب معظم السِّيَر بترتيب زمني: الولادة، الطفولة، سنوات المراهقة، بداية الشباب، سنّ الرشد، الشيخوخة.',
          ],
          plan: [
            { en: 'Introduce the person: who he or she is and why he or she is famous.', ar: 'عرّف بالشخص: من هو ولماذا هو مشهور.' },
            { en: 'Birth and childhood: when and where he or she was born, and his or her early life.', ar: 'الولادة والطفولة: متى وأين وُلد، وحياته المبكرة.' },
            { en: 'Teenage years and young adulthood: education, first steps and decisions.', ar: 'المراهقة وبداية الشباب: التعليم والخطوات والقرارات الأولى.' },
            { en: 'Adulthood: his or her greatest accomplishments and difficulties.', ar: 'سنّ الرشد: أعظم إنجازاته والصعوبات التي واجهها.' },
            { en: 'Old age or today: what he or she left for the world.', ar: 'الشيخوخة أو اليوم: ماذا ترك للعالم.' },
          ],
          phrases: [
            { en: 'was born in …', ar: 'وُلد في …' },
            { en: 'as a child', ar: 'حين كان طفلاً' },
            { en: 'decided to …', ar: 'قرّر أن …' },
            { en: 'graduated from …', ar: 'تخرّج من …' },
            { en: 'set up a laboratory', ar: 'أنشأ مختبراً' },
            { en: 'at the age of 30', ar: 'في سنّ الثلاثين' },
            { en: 'accomplishment', ar: 'إنجاز' },
            { en: 'he never quit; he persisted', ar: 'لم يستسلم أبداً، بل ثابر' },
            { en: 'eventually', ar: 'في النهاية' },
            { en: 'a genius', ar: 'عبقري' },
            { en: 'one of the greatest inventors', ar: 'أحد أعظم المخترعين' },
          ],
          model: 'Thomas Alva Edison was one of the greatest inventors in history. He was born in Ohio, in the USA, in 1847. As a child, he went to school, but his teacher sent a letter home saying he could not stay there. His mother decided to teach him at home. She believed in him and she was never frustrated. As a teenager, he set up a laboratory at home and began his own experiments. He also set up his own telegraph station. As a young man, he worked very hard, and at the age of 30 he invented the phonograph. He failed many times, but he never quit; he persisted. Eventually, he became famous all over the world. Edison died in 1931, but his work created the basis for many technologies that we enjoy today.',
          modelAr: 'كان توماس ألفا إديسون أحد أعظم المخترعين في التاريخ. وُلد في ولاية أوهايو في الولايات المتحدة عام 1847. حين كان طفلاً ذهب إلى المدرسة، لكن معلّمه أرسل رسالة إلى البيت تقول إنه لا يستطيع البقاء فيها. فقرّرت أمه أن تعلّمه في البيت. لقد آمنت به ولم تُصَب بالإحباط أبداً. وفي سنوات مراهقته أنشأ مختبراً في البيت وبدأ تجاربه الخاصة، كما أنشأ محطة تلغراف خاصة به. وفي شبابه عمل بجدّ كبير، وفي سنّ الثلاثين اخترع الفونوغراف (الحاكي). فشل مرات كثيرة لكنه لم يستسلم أبداً، بل ثابر. وفي النهاية أصبح مشهوراً في العالم كله. تُوفّي إديسون عام 1931، لكن عمله وضع الأساس لكثير من التقنيات التي نستمتع بها اليوم.',
          checklistAr: [
            'هل عرّفت بالشخص وسبب شهرته في الجملة الأولى؟',
            'هل رتّبت حياته بترتيب زمني (الولادة، الطفولة، الشباب، الرشد…)؟',
            'هل استخدمت الماضي البسيط بشكل صحيح (was born, decided, invented)؟',
            'هل ذكرت إنجازاته والصعوبات التي تغلّب عليها؟',
            'هل استخدمت كلمات من الوحدة (accomplishment, eventually, graduated, persisted)؟',
            'هل كتبت نحو 100 كلمة وراجعت الإملاء وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'One day Thomas Edison came home and gave his mother a letter from his teacher.', ar: 'في أحد الأيام عاد توماس إديسون إلى البيت وأعطى أمّه رسالة من معلّمه.' },
        { en: 'As she read the letter, his mother\'s eyes were tearful.', ar: 'وبينما كانت تقرأ الرسالة، امتلأت عينا أمّه بالدموع.' },
        { en: 'Edison\'s mother hid the letter and decided to educate young Thomas at home.', ar: 'خبّأت أمّ إديسون الرسالة وقرّرت أن تعلّم توماس الصغير في البيت.' },
        { en: 'Edison\'s mother wasn\'t frustrated; she wanted Edison to be a scientist.', ar: 'لم تُصَب أمّ إديسون بالإحباط؛ لقد أرادت أن يصبح إديسون عالماً.' },
        { en: 'He grew up and set up a laboratory at home and began his own experiments.', ar: 'كبر وأنشأ مختبراً في البيت وبدأ تجاربه الخاصة.' },
        { en: 'He also set up his own telegraph station and sent out messages by using a train whistle.', ar: 'كما أنشأ محطة تلغراف خاصة به وأرسل رسائل باستخدام صفّارة قطار.' },
        { en: 'At the age of 30, Edison invented the phonograph.', ar: 'في سنّ الثلاثين اخترع إديسون الفونوغراف (الحاكي).' },
        { en: 'However, like anyone else, he suffered through failure numerous times, but where others quit, he persisted.', ar: 'ومع ذلك، ومثل أي شخص آخر، عانى الفشل مرات عديدة، لكنه ثابر حيث استسلم الآخرون.' },
        { en: 'Don\'t make the same mistake twice.', ar: 'لا ترتكب الخطأ نفسه مرتين.' },
        { en: 'Her designs aimed specifically at people with Down Syndrome.', ar: 'استهدفت تصاميمها تحديداً الأشخاصَ من ذوي متلازمة داون.' },
        { en: 'Springmuhl had her first big showcase in 2015, where she sold her complete collection.', ar: 'أقامت سبرينغمول أول عرض كبير لها عام 2015، حيث باعت مجموعتها كاملة.' },
        { en: 'Sujeet Desai is from Buffalo, New York.', ar: 'سوجيت ديساي من مدينة بافالو في نيويورك.' },
        { en: 'Two years later, he decided to study music and graduated from Berkshire Hills Music Academy.', ar: 'بعد سنتين قرّر أن يدرس الموسيقى وتخرّج من أكاديمية بيركشاير هيلز للموسيقى.' },
        { en: 'Now he is a famous musician.', ar: 'وهو الآن موسيقي مشهور.' },
        { en: 'All in all, Desai can play seven instruments.', ar: 'وإجمالاً، يستطيع ديساي العزف على سبع آلات موسيقية.' },
        { en: 'People are able to challenge difficult circumstances and be successful.', ar: 'الناس قادرون على تحدّي الظروف الصعبة وعلى النجاح.' },
      ],
    },
  },
  progressTest: {
    title: 'Progress Test (I)',
    titleAr: 'اختبار التقدّم الأول',
    pages: '27–31',
    reading: {
      title: 'Trekking',
      paragraphs: [
        'Today is the second day of my trek around Mount Annapurna. I am exhausted and my legs are shaking; I just hope I am able to complete the trek. My feet are really killing me and my toes are bleeding, but I still want to continue. Nepal is a fascinating country, but I have a great deal to learn. Everything is so different, and I am trying to adapt to the new way of life here. I\'ve learnt a little bit of the language to make communication easier; unfortunately, I don\'t learn foreign languages quickly. Although I have not understood much yet, I believe that I will improve gradually. I am currently travelling with Liam, a student from Leeds University in England. He is a nice guy, but impatient. He always walks ahead of me and complains that I am too slow. I am doing my best to keep up with him, but he is younger and stronger than I am. Maybe, I am just feeling sorry for myself because I am getting old. Right now, Liam is sitting with the owner of the inn. They are discussing the differences between life in England and life in Nepal. I don\'t know the real name of the owner, but everybody just calls him Tam. Tam speaks English very well and he is trying to teach Liam some words in Nepali. Every time Tam says a new word, Liam tries to repeat it. Unfortunately, Liam also seems to have difficulty learning foreign languages. I just hope we don\'t get lost and have to ask for directions.',
      ],
      paragraphsAr: [
        'اليوم هو اليوم الثاني من رحلتي سيراً على الأقدام حول جبل أنابورنا. أنا منهك وساقاي ترتجفان؛ كل ما أرجوه أن أتمكّن من إكمال الرحلة. قدماي تؤلمانني بشدّة وأصابع قدميّ تنزف، لكنني ما زلت أريد أن أستمر. نيبال بلد رائع، لكن عليّ أن أتعلّم الكثير. كل شيء مختلف جداً، وأحاول أن أتكيّف مع طريقة الحياة الجديدة هنا. تعلّمت قليلاً من اللغة لأجعل التواصل أسهل؛ لكن للأسف، لا أتعلّم اللغات الأجنبية بسرعة. ومع أنني لم أفهم الكثير بعد، أعتقد أنني سأتحسّن تدريجياً. أسافر حالياً مع ليام، وهو طالب من جامعة ليدز في إنجلترا. إنه شاب لطيف، لكنه نافد الصبر. فهو يمشي دائماً أمامي ويشتكي من أنني بطيء جداً. أبذل قصارى جهدي لأجاريه، لكنه أصغر مني سنّاً وأقوى. ربما أنا فقط أشفق على نفسي لأنني أتقدّم في السن. الآن، يجلس ليام مع صاحب النُّزُل. إنهما يتناقشان في الفروق بين الحياة في إنجلترا والحياة في نيبال. لا أعرف الاسم الحقيقي لصاحب النُّزُل، لكن الجميع ينادونه تام. يتكلّم تام الإنجليزية جيداً جداً، ويحاول أن يعلّم ليام بعض الكلمات النيبالية. وكلما قال تام كلمة جديدة، يحاول ليام أن يكرّرها. وللأسف، يبدو أن ليام أيضاً يجد صعوبة في تعلّم اللغات الأجنبية. كل ما أرجوه ألّا نضلّ الطريق فنضطرّ إلى السؤال عن الاتجاهات.',
      ],
      questions: [
        {
          q: 'How does the writer feel?',
          qAr: 'بماذا يشعر الكاتب؟',
          options: [
            'He is full of energy and wants to walk faster.',
            'He is exhausted, his legs are shaking and his feet are hurting.',
            'He is bored and wants to go home.',
            'He is angry with Tam.',
          ],
          answer: 1,
          explainAr: 'النص: I am exhausted and my legs are shaking ... My feet are really killing me. (exhausted = منهك جداً).',
        },
        {
          q: 'Why did he learn Nepali language?',
          qAr: 'لماذا تعلّم اللغة النيبالية؟',
          options: [
            'To teach it to Liam.',
            'To get a job in Nepal.',
            'To make communication easier.',
            'Because he learns foreign languages quickly.',
          ],
          answer: 2,
          explainAr: 'النص: I\'ve learnt a little bit of the language to make communication easier. (to + المصدر تبيّن السبب/الهدف). والخيار الأخير خطأ لأنه يقول: I don\'t learn foreign languages quickly.',
        },
        {
          q: 'Who is Liam?',
          qAr: 'من هو ليام؟',
          options: [
            'The owner of the inn.',
            'A guide from Nepal.',
            'The writer\'s teacher of Nepali.',
            'A student from Leeds University in England who is travelling with the writer.',
          ],
          answer: 3,
          explainAr: 'النص: I am currently travelling with Liam, a student from Leeds University in England. أما صاحب النُّزُل فاسمه تام.',
        },
        {
          q: 'Why can\'t the writer keep up with Liam?',
          qAr: 'لماذا لا يستطيع الكاتب أن يجاري ليام؟',
          options: [
            'Because Liam is younger and stronger than him.',
            'Because Liam walks very slowly.',
            'Because the writer got lost.',
            'Because Liam is always sitting in the inn.',
          ],
          answer: 0,
          explainAr: 'النص: I am doing my best to keep up with him, but he is younger and stronger than I am. (keep up with = يجاري / يلحق بـ).',
        },
        {
          q: 'What are the owner of the inn and Liam talking about?',
          qAr: 'عمَّ يتحدّث صاحب النُّزُل وليام؟',
          options: [
            'The way to Mount Annapurna.',
            'The differences between life in England and life in Nepal.',
            'The price of the rooms in the inn.',
            'The writer\'s bleeding toes.',
          ],
          answer: 1,
          explainAr: 'النص: They are discussing the differences between life in England and life in Nepal.',
        },
        {
          q: 'What does the writer hope at the end of the text?',
          qAr: 'بماذا يأمل الكاتب في نهاية النص؟',
          options: [
            'That Liam will walk more slowly.',
            'That Tam will travel with them.',
            'That they don\'t get lost and have to ask for directions.',
            'That he will go back to England soon.',
          ],
          answer: 2,
          explainAr: 'الجملة الأخيرة: I just hope we don\'t get lost and have to ask for directions. فكلاهما لا يتقن النيبالية.',
        },
      ],
    },
    exercises: ptExercises,
  },
}
