import type { GrammarExercise } from '../../../engine/types'
import type { ModuleExtras } from './merge'

// Module 5 "Values & Time" — Activity Book pages 42–50 (Unit 9: 42–46, Unit 10: 47–50). No Progress Test.
// Left out: the Listening tasks of both units (p. 45 "The Song of Peace", pp. 49–50 the story of Rami and Rosa):
// their answers are in the recording. The Speaking tasks (pp. 42, 47) are open discussion.

const fill = (prompt: string, promptAr: string, promptArFull: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, promptAr, promptArFull, options, answer, explainAr })
const mcq = (prompt: string, promptAr: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, promptAr, options, answer, explainAr })
const tf = (prompt: string, promptAr: string, answer: boolean, explainAr: string): GrammarExercise =>
  ({ type: 'truefalse', prompt, promptAr, answer, explainAr })

// ---------- Unit 9, page 43B: match A with B ----------
const u9B = [
  'an important skill of good citizens.',
  'what is black tonight turns white in the morning.',
  'the advice of her father.',
  'Susan’s mother works hard.',
]
function u9Match(start: string, startAr: string, right: number, explainAr: string): GrammarExercise {
  return mcq(`Match A with B: "${start} …"`, `صِل العمود (A) بالعمود (B) لتكوّن جملة كاملة: «${startAr} …»`, u9B, right, explainAr)
}

// ---------- Unit 9, page 43: Key Words ----------
const u9Keys = [
  'a child whose parents are dead',
  'to show polite behaviour',
  'doing or achieving a lot',
  'an action or a service that helps to cause or increase something',
  'the general health, happiness and safety of a person or a group',
]
function u9Key(word: string, right: number, explainAr: string): GrammarExercise {
  return mcq(`Key Words: what does "${word}" mean?`, `الكلمات المفتاحية: ما معنى كلمة "${word}"؟`, u9Keys, right, explainAr)
}

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 9 — Stay Positive (Activity Book pages 42–46) =====================
    u9: {
      workbook: {
        pages: '42–46',
        readings: [
          {
            title: 'An active Citizen, A Better World',
            paragraphs: [
              'Suzan is an orphan whose father died when she was a baby. Before his death, he had a strong will of taking care of Suzan and encouraging her to study hard.',
              'After her husband\'s death, the mother worked hard to make her daughter feel comfortable and tried to afford her all what she needed.',
              'At night, before they sleep, the mother tells Suzan how much it is important to be a responsible citizen who respects the principles of the country. She encourages her daughter to be a productive member of society and a person who makes a positive contribution to the nation. The mother also clarifies the necessity of developing her daughter\'s character to be strong and effective in society. She tells her that she must understand her legal rights as well as her duties.',
              'Suzan is sure that life is difficult when you cannot have what you want. But she has learnt from her mother to fight till the end. She always says: "when we don\'t have what we like, we must like what we have".',
              'Suzan, who is now 15 years old, works hard to achieve her dreams. She loves reading so she spends her free time in the school library reading about her country’s history and social studies. She studies a lot because she believes that what is hard today, will be easy tomorrow and what is black tonight will be white in the morning.',
              'She shares her skills, talents, and abilities with others. On holidays she participates in the social activities of her city and looks for ways to make her community a better place to live in. She also urges people of her age to work for welfare services.',
            ],
            paragraphsAr: [
              'سوزان يتيمة توفّي والدها عندما كانت رضيعة. وقبل وفاته، كانت لديه رغبة قوية في أن يعتني بسوزان ويشجّعها على الدراسة بجدّ.',
              'بعد وفاة زوجها، عملت الأم بجدّ لتجعل ابنتها تشعر بالراحة، وحاولت أن توفّر لها كل ما تحتاج إليه.',
              'في الليل، قبل أن تناما، تخبر الأمّ سوزان كم هو مهمّ أن تكون مواطنة مسؤولة تحترم مبادئ الوطن. وتشجّع ابنتها على أن تكون عضواً منتجاً في المجتمع وشخصاً يقدّم إسهاماً إيجابياً للوطن. وتوضّح الأم أيضاً ضرورة تنمية شخصية ابنتها لتكون قوية وفعّالة في المجتمع. وتخبرها أنه يجب عليها أن تعرف حقوقها القانونية وواجباتها أيضاً.',
              'سوزان متأكّدة من أن الحياة صعبة عندما لا تستطيع أن تحصل على ما تريد. لكنها تعلّمت من أمّها أن تكافح حتى النهاية. وهي تقول دائماً: «عندما لا نملك ما نحبّ، يجب أن نحبّ ما نملك».',
              'سوزان، التي أصبح عمرها الآن 15 عاماً، تعمل بجدّ لتحقّق أحلامها. إنها تحبّ القراءة، لذلك تقضي وقت فراغها في مكتبة المدرسة تقرأ عن تاريخ بلدها وعن الدراسات الاجتماعية. وهي تدرس كثيراً لأنها تؤمن أن ما هو صعب اليوم سيكون سهلاً غداً، وأن ما هو أسود الليلة سيصبح أبيض في الصباح.',
              'وهي تشارك مهاراتها ومواهبها وقدراتها مع الآخرين. وفي العطل تشارك في النشاطات الاجتماعية في مدينتها، وتبحث عن طرق تجعل مجتمعها مكاناً أفضل للعيش. كما تحثّ من هم في مثل عمرها على العمل في خدمات الرعاية الاجتماعية.',
            ],
            questions: [
              {
                q: 'What principles does Suzan’s mother teach her?', qAr: 'ما المبادئ التي تعلّمها أمّ سوزان لابنتها؟',
                options: [
                  'To keep away from people and live only for herself.',
                  'To be a responsible citizen who respects the principles of the country and a productive member of society.',
                  'To leave school and work to earn money.',
                  'To spend all her free time playing games.',
                ],
                answer: 1,
                explainAr: 'في الفقرة الثالثة: تخبرها أمّها كم هو مهمّ أن تكون "a responsible citizen who respects the principles of the country" (مواطنة مسؤولة تحترم مبادئ الوطن)، وتشجّعها أن تكون "a productive member of society" (عضواً منتجاً في المجتمع)، وأن تعرف حقوقها وواجباتها.',
              },
              {
                q: 'What is Suzan’s best motto?', qAr: 'ما أفضل شعار (حكمة) تردّده سوزان؟',
                options: [
                  'It is better to take than to give.',
                  'Life is easy when you have what you want.',
                  'When we don’t have what we like, we must like what we have.',
                  'What is easy today will be hard tomorrow.',
                ],
                answer: 2,
                explainAr: 'في الفقرة الرابعة: "She always says: when we don\'t have what we like, we must like what we have" أي: عندما لا نملك ما نحبّ، يجب أن نحبّ ما نملك. كلمة always (دائماً) تدلّنا على أنه شعارها.',
              },
              {
                q: 'How does Suzan spend her free time?', qAr: 'كيف تقضي سوزان وقت فراغها؟',
                options: [
                  'In the school library, reading about her country’s history and social studies.',
                  'At home, watching TV with her mother.',
                  'In the street, playing with her friends.',
                  'In a shop, working to earn money.',
                ],
                answer: 0,
                explainAr: 'في الفقرة الخامسة: "she spends her free time in the school library reading about her country’s history and social studies" أي تقضيه في مكتبة المدرسة تقرأ عن تاريخ بلدها والدراسات الاجتماعية.',
              },
              {
                q: 'Mention two other examples of activities someone does to be a good citizen.', qAr: 'اذكر مثالين آخرين على نشاطات يقوم بها الشخص ليكون مواطناً صالحاً.',
                options: [
                  'Cheating in exams and breaking the rules.',
                  'Keeping a wallet he found in the street.',
                  'Wasting water and throwing rubbish in the street.',
                  'Following the rules and taking care of the earth.',
                ],
                answer: 3,
                explainAr: 'الصورة في الصفحة 42 "How to be a Good Citizen" تذكر أمثلة: Follow the rules (اتّبع القوانين)، Take care of the earth (حافظ على الأرض)، Be honest (كن صادقاً)، Be kind and helpful (كن لطيفاً ومساعداً). أما الغشّ ورمي القمامة والاحتفاظ بمحفظة ليست لك فهي أفعال سيئة.',
              },
              {
                q: 'Who died when Suzan was a baby?', qAr: 'من الذي توفّي عندما كانت سوزان رضيعة؟',
                options: ['Her mother.', 'Her father.', 'Her grandfather.', 'Her teacher.'],
                answer: 1,
                explainAr: 'أول جملة في النص: "Suzan is an orphan whose father died when she was a baby" أي توفّي والدها. لاحظ whose (الذي ... له) للملكية: يتيمة والدُها توفّي.',
              },
              {
                q: 'What does Suzan urge people of her age to do?', qAr: 'على ماذا تحثّ سوزان من هم في مثل عمرها؟',
                options: ['To play more games.', 'To leave school early.', 'To work for welfare services.', 'To travel to other countries.'],
                answer: 2,
                explainAr: 'آخر جملة في النص: "She also urges people of her age to work for welfare services" أي تحثّهم على العمل في خدمات الرعاية الاجتماعية. urge = يحثّ.',
              },
            ],
          },
        ],
        exercises: [
          // ---- page 43B: match A with B ----
          u9Match('1. Encouraging Susan to finish her studies was', '1. تشجيع سوزان على إنهاء دراستها كان', 2,
            'الجملة الكاملة: "Encouraging Susan to finish her studies was the advice of her father." = تشجيع سوزان على إنهاء دراستها كان نصيحة أبيها. النص يقول إن الأب قبل وفاته أراد أن يشجّعها على الدراسة بجدّ.'),
          u9Match('2. To make her daughter feel comfortable,', '2. لكي تجعل ابنتها تشعر بالراحة،', 3,
            'الجملة الكاملة: "To make her daughter feel comfortable, Susan’s mother works hard." = لكي تجعل ابنتها تشعر بالراحة، تعمل أمّ سوزان بجدّ. الجملة الأولى ناقصة (فيها فاصلة) وتحتاج فاعلاً وفعلاً.'),
          u9Match('3. Susan believes that', '3. تؤمن سوزان أن', 1,
            'الجملة الكاملة: "Susan believes that what is black tonight turns white in the morning." = تؤمن سوزان أن ما هو أسود الليلة يصبح أبيض في الصباح. بعد believes that نحتاج جملة كاملة تعبّر عن فكرة.'),
          u9Match('4. Working for the welfare of society is', '4. العمل من أجل رفاهية المجتمع هو', 0,
            'الجملة الكاملة: "Working for the welfare of society is an important skill of good citizens." = العمل من أجل رفاهية المجتمع مهارة مهمة من مهارات المواطنين الصالحين.'),

          // ---- page 43 Vocabulary: other parts of speech of words from the text ----
          fill('Verb: die → Noun: ___',
            'الفعل: die (يموت) ← الاسم: ___',
            'الفعل: die (يموت) ← الاسم: death (الموت / الوفاة)',
            ['dead', 'death', 'died', 'deadly'], 1,
            'الاسم من die هو death (الوفاة)، كما في النص: "Before his death". أما dead فصفة (ميّت)، وdied ماضي الفعل، وdeadly صفة (قاتل).'),
          fill('Noun: encouragement → Verb: ___',
            'الاسم: encouragement (تشجيع) ← الفعل: ___',
            'الاسم: encouragement (تشجيع) ← الفعل: encourage (يشجّع)',
            ['encouraging', 'courage', 'encourage', 'courageous'], 2,
            'نحذف اللاحقة ‎-ment‎ من الاسم فنحصل على الفعل encourage (يشجّع)، كما في النص: "She encourages her daughter". courage اسم آخر (شجاعة) وcourageous صفة.'),
          fill('Noun: production → Adjective: ___',
            'الاسم: production (إنتاج) ← الصفة: ___',
            'الاسم: production (إنتاج) ← الصفة: productive (منتج)',
            ['productive', 'produce', 'product', 'productively'], 0,
            'اللاحقة ‎-ive‎ تصنع صفة: productive (منتج)، كما في النص: "a productive member of society". produce فعل، وproduct اسم (منتَج)، وproductively ظرف.'),
          fill('Verb: comfort → Noun: ___',
            'الفعل: comfort (يريح / يواسي) ← الاسم: ___',
            'الفعل: comfort (يريح / يواسي) ← الاسم: comfort (الراحة)',
            ['comfortable', 'comfort', 'comfortably', 'comforting'], 1,
            'الاسم هنا له نفس شكل الفعل: comfort (الراحة). comfortable صفة (مريح)، وcomfortably ظرف (براحة).'),
          fill('Verb: comfort → Adjective: ___',
            'الفعل: comfort ← الصفة: ___',
            'الفعل: comfort ← الصفة: comfortable (مرتاح / مريح)',
            ['comfort', 'comfortably', 'comfortable', 'comforted'], 2,
            'اللاحقة ‎-able‎ تصنع صفة: comfortable، كما في النص: "to make her daughter feel comfortable". بعد feel تأتي صفة.'),
          fill('Noun: responsibility → Adjective: ___',
            'الاسم: responsibility (مسؤولية) ← الصفة: ___',
            'الاسم: responsibility (مسؤولية) ← الصفة: responsible (مسؤول)',
            ['responsibly', 'response', 'responsibilities', 'responsible'], 3,
            'الصفة responsible (مسؤول)، كما في النص: "a responsible citizen" (مواطن مسؤول). responsibly ظرف، وresponse اسم آخر (ردّ).'),
          fill('Adjective: respectable → Verb: ___',
            'الصفة: respectable (محترم) ← الفعل: ___',
            'الصفة: respectable (محترم) ← الفعل: respect (يحترم)',
            ['respect', 'respectful', 'respectably', 'respecting'], 0,
            'نحذف اللاحقة ‎-able‎ فنحصل على الفعل respect (يحترم)، كما في النص: "a responsible citizen who respects the principles of the country".'),
          fill('Adjective: respectable → Noun: ___',
            'الصفة: respectable ← الاسم: ___',
            'الصفة: respectable ← الاسم: respect (الاحترام)',
            ['respectful', 'respect', 'respectably', 'respected'], 1,
            'الاسم له نفس شكل الفعل: respect (الاحترام). respectful صفة (يُظهر الاحترام) وrespected صفة (محترَم).'),
          fill('Verb: contribute → Noun: ___',
            'الفعل: contribute (يُسهم) ← الاسم: ___',
            'الفعل: contribute (يُسهم) ← الاسم: contribution (إسهام / مساهمة)',
            ['contributive', 'contributed', 'contribution', 'contributing'], 2,
            'اللاحقة ‎-tion‎ تصنع اسماً: contribution، كما في النص: "a person who makes a positive contribution to the nation".'),
          fill('Adjective: talented → Noun: ___',
            'الصفة: talented (موهوب) ← الاسم: ___',
            'الصفة: talented (موهوب) ← الاسم: talent (موهبة)',
            ['talentless', 'talent', 'talentedly'], 1,
            'نحذف اللاحقة ‎-ed‎ من الصفة فنحصل على الاسم talent (موهبة)، كما في النص: "She shares her skills, talents, and abilities with others".'),

          // ---- page 44A: choose the correct relative pronoun ----
          fill('My sister wore a mask ___ made her look like Mickey Mouse.',
            'ارتدت أختي قناعاً ___ جعلها تبدو مثل ميكي ماوس.',
            'ارتدت أختي قناعاً جعلها تبدو مثل ميكي ماوس.',
            ['who', 'which', 'whose', 'where'], 1,
            'a mask (قناع) شيء وليس شخصاً، فنستخدم which للأشياء والحيوانات. who للأشخاص فقط.'),
          fill('He came with a friend ___ waited outside in the car.',
            'جاء مع صديقٍ ___ انتظر في الخارج في السيارة.',
            'جاء مع صديقٍ انتظر في الخارج في السيارة.',
            ['who', 'which', 'whose', 'when'], 0,
            'a friend شخص، وبعد الفراغ فعل مباشرة (waited)، أي أن الضمير فاعل: نستخدم who للأشخاص.'),
          fill('The man ___ mobile was ringing did not know what to do.',
            'الرجل ___ هاتفُه المحمول يرنّ لم يعرف ماذا يفعل.',
            'الرجل الذي كان هاتفه المحمول يرنّ لم يعرف ماذا يفعل.',
            ['who', 'which', 'whose', 'whom'], 2,
            'بعد الفراغ اسم (mobile) يملكه الرجل: هاتف الرجل = his mobile. للملكية نستخدم whose ويليها اسم مباشرة.'),
          fill('I still remember the days ___ grandmother told us interesting stories.',
            'ما زلت أتذكّر الأيام ___ كانت جدّتي تحكي لنا فيها قصصاً ممتعة.',
            'ما زلت أتذكّر الأيام التي كانت جدّتي تحكي لنا فيها قصصاً ممتعة.',
            ['where', 'when', 'which', 'who'], 1,
            'the days (الأيام) زمن، فنستخدم when للزمن. where للمكان فقط.'),
          fill('He didn\'t wait at the traffic light ___ was red.',
            'لم ينتظر عند إشارة المرور ___ كانت حمراء.',
            'لم ينتظر عند إشارة المرور التي كانت حمراء.',
            ['who', 'where', 'which', 'when'], 2,
            'the traffic light (إشارة المرور) شيء، وبعد الفراغ فعل (was)، فنستخدم which للأشياء. لا نستخدم where لأننا نصف الإشارة نفسها لا المكان.'),
          fill('Is that the hospital ___ your brother works?',
            'هل ذلك هو المستشفى ___ يعمل فيه أخوك؟',
            'هل ذلك هو المستشفى الذي يعمل فيه أخوك؟',
            ['where', 'which', 'when', 'who'], 0,
            'the hospital مكان، وبعد الفراغ جملة كاملة (your brother works)، أي يعمل فيه: نستخدم where للمكان.'),
          fill('Who was that lady ___ you were talking to?',
            'من كانت تلك السيدة ___ كنت تتحدّث إليها؟',
            'من كانت تلك السيدة التي كنت تتحدّث إليها؟',
            ['whose', 'which', 'whom', 'where'], 2,
            'the lady شخص، وهي هنا مفعول به (you were talking to her)، فنستخدم whom للأشخاص في حالة المفعول به. which للأشياء فقط.'),
          fill('I live in the city ___ my friend studies.',
            'أعيش في المدينة ___ يدرس فيها صديقي.',
            'أعيش في المدينة التي يدرس فيها صديقي.',
            ['which', 'when', 'where', 'whose'], 2,
            'the city مكان، وبعد الفراغ جملة كاملة (my friend studies)، أي يدرس فيها: نستخدم where للمكان.'),
          fill('Do you know a good store ___ I can buy a new shirt?',
            'هل تعرف متجراً جيداً ___ أستطيع أن أشتري منه قميصاً جديداً؟',
            'هل تعرف متجراً جيداً أستطيع أن أشتري منه قميصاً جديداً؟',
            ['which', 'where', 'who', 'when'], 1,
            'a store (متجر) مكان، وبعد الفراغ جملة كاملة لها فاعل ومفعول (I can buy a new shirt)، فنستخدم where. لو استخدمنا which لنقص حرف الجر (which I can buy a shirt in).'),

          // ---- page 45B: combine the sentences using relative pronouns ----
          mcq('Combine the sentences: "A person is lucky." + "That person has a lot of friends."',
            'ادمج الجملتين باستخدام ضمير وصل: «الشخص محظوظ.» + «ذلك الشخص لديه الكثير من الأصدقاء.»',
            ['A person which has a lot of friends is lucky.', 'A person who has a lot of friends is lucky.', 'A person who he has a lot of friends is lucky.', 'A person whose has a lot of friends is lucky.'], 1,
            'الجملة الصحيحة: "A person who has a lot of friends is lucky." = الشخص الذي لديه الكثير من الأصدقاء محظوظ. نستخدم who للأشخاص، ونحذف That person لأن who حلّت محلّه، ولا نكرّر الضمير he بعد who.'),
          mcq('Combine the sentences: "Martha has a brother." + "Her brother’s name is Manuel."',
            'ادمج الجملتين: «لمارثا أخ.» + «اسم أخيها مانويل.»',
            ['Martha has a brother who his name is Manuel.', 'Martha has a brother which name is Manuel.', 'Martha has a brother whose name is Manuel.', 'Martha has a brother whose his name is Manuel.'], 2,
            'الجملة الصحيحة: "Martha has a brother whose name is Manuel." = لمارثا أخ اسمه مانويل. brother’s name ملكية، فنستخدم whose ويليها الاسم مباشرة (whose name) من دون his.'),
          mcq('Combine the sentences: "That is the house." + "I grew up with my sister Emilia."',
            'ادمج الجملتين: «ذلك هو البيت.» + «نشأت مع أختي إميليا.»',
            ['That is the house where I grew up with my sister Emilia.', 'That is the house which I grew up with my sister Emilia.', 'That is the house when I grew up with my sister Emilia.', 'That is the house where I grew up in it with my sister Emilia.'], 0,
            'الجملة الصحيحة: "That is the house where I grew up with my sister Emilia." = ذلك هو البيت الذي نشأت فيه مع أختي إميليا. the house مكان، فنستخدم where، ولا نضيف in it لأن where تعني «فيه».'),
          mcq('Combine the sentences: "I remember that wonderful summer." + "The whole family gathered again."',
            'ادمج الجملتين: «أتذكّر ذلك الصيف الرائع.» + «اجتمعت العائلة كلها من جديد.»',
            ['I remember that wonderful summer where the whole family gathered again.', 'I remember that wonderful summer who the whole family gathered again.', 'I remember that wonderful summer when the whole family gathered again in it.', 'I remember that wonderful summer when the whole family gathered again.'], 3,
            'الجملة الصحيحة: "I remember that wonderful summer when the whole family gathered again." = أتذكّر ذلك الصيف الرائع الذي اجتمعت فيه العائلة كلها من جديد. summer زمن، فنستخدم when للزمن، ولا نضيف in it.'),
          mcq('Combine the sentences: "Leila gave me a beautiful souvenir." + "Leila bought the souvenir from Al-Hamideya souk."',
            'ادمج الجملتين: «أعطتني ليلى تذكاراً جميلاً.» + «اشترت ليلى التذكار من سوق الحميدية.»',
            ['Leila gave me a beautiful souvenir who she bought from Al-Hamideya souk.', 'Leila gave me a beautiful souvenir which she bought from Al-Hamideya souk.', 'Leila gave me a beautiful souvenir which she bought it from Al-Hamideya souk.', 'Leila gave me a beautiful souvenir where she bought from Al-Hamideya souk.'], 1,
            'الجملة الصحيحة: "Leila gave me a beautiful souvenir which she bought from Al-Hamideya souk." = أعطتني ليلى تذكاراً جميلاً اشترته من سوق الحميدية. souvenir شيء فنستخدم which، وهي مفعول به للفعل bought، لذلك لا نكرّر it.'),
          mcq('Combine the sentences: "The teacher smiled at Sami." + "Sami was working very hard."',
            'ادمج الجملتين: «ابتسم المعلّم لسامي.» + «كان سامي يعمل بجدّ كبير.»',
            ['The teacher smiled at Sami, which was working very hard.', 'The teacher smiled at Sami, whose was working very hard.', 'The teacher smiled at Sami, who was working very hard.', 'The teacher smiled at Sami, who he was working very hard.'], 2,
            'الجملة الصحيحة: "The teacher smiled at Sami, who was working very hard." = ابتسم المعلّم لسامي الذي كان يعمل بجدّ كبير. Sami شخص فنستخدم who، ولا نكرّر he بعدها. نضع فاصلة قبل who لأن الاسم علم معروف (معلومة إضافية).'),
          mcq('Combine the sentences: "I couldn’t write with that pen." + "Dana gave me a pen."',
            'ادمج الجملتين: «لم أستطع الكتابة بذلك القلم.» + «أعطتني دانة قلماً.»',
            ['I couldn’t write with the pen which Dana gave me.', 'I couldn’t write with the pen who Dana gave me.', 'I couldn’t write with the pen which Dana gave me it.', 'I couldn’t write with the pen where Dana gave me.'], 0,
            'الجملة الصحيحة: "I couldn’t write with the pen which Dana gave me." (أو that Dana gave me) = لم أستطع الكتابة بالقلم الذي أعطتني إياه دانة. pen شيء فنستخدم which أو that، ولا نكرّر it في آخر الجملة.'),
          mcq('Combine the sentences: "I like to eat at that restaurant." + "The food is healthy and the price is reasonable there."',
            'ادمج الجملتين: «أحبّ أن آكل في ذلك المطعم.» + «الطعام هناك صحّي والسعر معقول.»',
            ['I like to eat at that restaurant which the food is healthy and the price is reasonable.', 'I like to eat at that restaurant when the food is healthy and the price is reasonable.', 'I like to eat at that restaurant where the food is healthy and the price is reasonable there.', 'I like to eat at that restaurant where the food is healthy and the price is reasonable.'], 3,
            'الجملة الصحيحة: "I like to eat at that restaurant where the food is healthy and the price is reasonable." = أحبّ أن آكل في ذلك المطعم الذي طعامه صحّي وسعره معقول. restaurant مكان، وكلمة there تدلّ على المكان، فنستخدم where ونحذف there.'),
          mcq('Combine the sentences: "Last week I met Mrs. Smith." + "She lives next door."',
            'ادمج الجملتين: «قابلت السيدة سميث الأسبوع الماضي.» + «إنها تسكن في البيت المجاور.»',
            ['Last week I met Mrs. Smith, which lives next door.', 'Last week I met Mrs. Smith, who lives next door.', 'Last week I met Mrs. Smith, who she lives next door.', 'Last week I met Mrs. Smith, whose lives next door.'], 1,
            'الجملة الصحيحة: "Last week I met Mrs. Smith, who lives next door." = قابلت الأسبوع الماضي السيدة سميث التي تسكن في البيت المجاور. who تحلّ محلّ She، فلا نكرّرها.'),

          // ---- page 43 Key Words (extra practice on the text's words) ----
          u9Key('orphan', 0, 'orphan = يتيم: طفل والداه (أو أحدهما) متوفّيان، كما في النص: "Suzan is an orphan whose father died when she was a baby".'),
          u9Key('respect', 1, 'respect = يحترم: أن تُظهر سلوكاً مهذّباً، كما في: "a responsible citizen who respects the principles of the country".'),
          u9Key('productive', 2, 'productive = منتج: يعمل أو ينجز الكثير، كما في: "a productive member of society".'),
          u9Key('contribution', 3, 'contribution = إسهام: عمل أو خدمة تساعد في حدوث شيء أو زيادته، كما في: "a positive contribution to the nation".'),
          u9Key('welfare', 4, 'welfare = الرفاهية / الرعاية: الصحة والسعادة والأمان لشخص أو لمجموعة، كما في: "welfare services" (خدمات الرعاية الاجتماعية).'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Read the paragraph and write suitable pieces of advice below. My friend complained about her teenage son\'s behaviour and his struggle with the family about studying and academic failure. He used to waste time with things that were not useful, rebell against the authority of his parents and showing a desire for complete independence from the family. She told me that he began to show negative feelings towards others and his relationship with his community has no longer become based on mutual understanding and giving.',
          topicAr: 'اقرأ الفقرة واكتب نصائح مناسبة في الأسفل. اشتكت صديقتي من سلوك ابنها المراهق ومن صراعه مع العائلة بشأن الدراسة والفشل الدراسي. كان يضيّع وقته في أشياء غير مفيدة، ويتمرّد على سلطة والديه، ويُظهر رغبة في الاستقلال التام عن العائلة. وأخبرتني أنه بدأ يُظهر مشاعر سلبية تجاه الآخرين، ولم تعد علاقته بمجتمعه قائمة على التفاهم المتبادل والعطاء.',
          words: 100,
          points: ['I advised her to …', 'She is supposed to …', 'It is better to …', 'I added that …', 'She should …', 'She shouldn’t …'],
          pointsAr: ['نصحتها أن …', 'يُفترض بها أن …', 'من الأفضل أن …', 'وأضفت أن …', 'ينبغي لها أن …', 'لا ينبغي لها أن …'],
          plan: [
            { en: 'Introduction: sum up the problem in one sentence (the son wastes time, rebels and has negative feelings).', ar: 'المقدّمة: لخّص المشكلة في جملة واحدة (الابن يضيّع وقته ويتمرّد وعنده مشاعر سلبية).' },
            { en: 'Advice 1–2: I advised her to … / She is supposed to … (talk to him and be patient).', ar: 'النصيحتان 1 و2: I advised her to … / She is supposed to … (أن تتحدّث معه وتصبر عليه).' },
            { en: 'Advice 3–4: It is better to … / I added that … (encourage him and organise his time).', ar: 'النصيحتان 3 و4: It is better to … / I added that … (أن تشجّعه وتنظّم وقته).' },
            { en: 'Advice 5–6: She should … / She shouldn’t … (what to do and what to avoid), then a hopeful ending.', ar: 'النصيحتان 5 و6: She should … / She shouldn’t … (ما تفعله وما تتجنّبه)، ثم خاتمة متفائلة.' },
          ],
          phrases: [
            { en: 'I advised her to …', ar: 'نصحتها أن …' },
            { en: 'She is supposed to …', ar: 'يُفترض بها أن …' },
            { en: 'It is better to …', ar: 'من الأفضل أن …' },
            { en: 'I added that …', ar: 'وأضفت أن …' },
            { en: 'She should … / She shouldn’t …', ar: 'ينبغي لها أن … / لا ينبغي لها أن …' },
            { en: 'waste time with things that are not useful', ar: 'يضيّع الوقت في أشياء غير مفيدة' },
            { en: 'mutual understanding and giving', ar: 'التفاهم المتبادل والعطاء' },
            { en: 'encourage him to study hard', ar: 'تشجّعه على الدراسة بجدّ' },
            { en: 'share his skills and talents with others', ar: 'يشارك مهاراته ومواهبه مع الآخرين' },
            { en: 'participate in social activities', ar: 'يشارك في النشاطات الاجتماعية' },
            { en: 'a productive member of society', ar: 'عضو منتج في المجتمع' },
            { en: 'It is better to give than to take.', ar: 'العطاء أفضل من الأخذ.' },
            { en: 'a son who … / a boy whose … (relative clauses)', ar: 'ابنٌ الذي … / ولدٌ الذي … له (جمل الصلة)' },
          ],
          model: 'My friend’s teenage son wastes his time, rebels against his parents and shows negative feelings towards others. I advised her to talk to him calmly and listen to his problems. She is supposed to be patient, because teenagers want to feel independent. It is better to encourage him with kind words than to shout at him. I added that she should help him organise his time between studying and useful activities. She should encourage him to share his skills and talents with others and participate in social activities. She shouldn’t compare him with other boys, because this makes him angry. With love and patience, he will become a productive member of society.',
          modelAr: 'ابن صديقتي المراهق يضيّع وقته، ويتمرّد على والديه، ويُظهر مشاعر سلبية تجاه الآخرين. نصحتها أن تتحدّث معه بهدوء وأن تستمع إلى مشكلاته. يُفترض بها أن تكون صبورة، لأن المراهقين يريدون أن يشعروا بالاستقلال. من الأفضل أن تشجّعه بكلمات لطيفة بدلاً من أن تصرخ في وجهه. وأضفت أنه ينبغي لها أن تساعده على تنظيم وقته بين الدراسة والنشاطات المفيدة. ينبغي لها أن تشجّعه على مشاركة مهاراته ومواهبه مع الآخرين والمشاركة في النشاطات الاجتماعية. ولا ينبغي لها أن تقارنه بالأولاد الآخرين، لأن هذا يغضبه. بالحبّ والصبر سيصبح عضواً منتجاً في المجتمع.',
          checklistAr: [
            'هل بدأت بجملة تلخّص مشكلة الابن كما وردت في الفقرة؟',
            'هل استخدمت البدايات الستّ المطبوعة: I advised her to, She is supposed to, It is better to, I added that, She should, She shouldn’t؟',
            'هل جاء بعد to وshould وshouldn’t فعل في صيغة المصدر (to talk, should help, shouldn’t compare)؟',
            'هل كانت كل نصيحة مرتبطة بجزء من المشكلة (إضاعة الوقت، التمرّد، المشاعر السلبية)؟',
            'هل استخدمت مفردات الوحدة (encourage, productive, share his skills, social activities…)؟',
            'هل الموضوع في حدود 100 كلمة، وراجعت التهجئة وعلامات الترقيم؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Your friend always cheats in the exam. Write about this bad behaviour and give some advice.',
          topicAr: 'صديقك يغشّ دائماً في الامتحان. اكتب عن هذا السلوك السيّئ وقدّم له بعض النصائح.',
          words: 100,
          points: ['Specify the problem', 'Give details', 'Use words such as: I think, advise, recommend, it is better, you should'],
          pointsAr: ['حدّد المشكلة', 'اذكر التفاصيل', 'استخدم كلمات مثل: I think (أعتقد)، advise (أنصح)، recommend (أوصي)، it is better (من الأفضل)، you should (ينبغي لك)'],
          plan: [
            { en: 'Specify the problem: who your friend is and what he does.', ar: 'حدّد المشكلة: من هو صديقك وماذا يفعل.' },
            { en: 'Give details: how he cheats and why it is wrong.', ar: 'اذكر التفاصيل: كيف يغشّ ولماذا هذا خطأ.' },
            { en: 'Give advice with I think, I advise, I recommend, It is better, You should.', ar: 'قدّم النصائح باستخدام I think وI advise وI recommend وIt is better وYou should.' },
            { en: 'End with a wise saying that encourages him to study.', ar: 'اختم بقول حكيم يشجّعه على الدراسة.' },
          ],
          phrases: [
            { en: 'I think …', ar: 'أعتقد أن …' },
            { en: 'I advise him to …', ar: 'أنصحه أن …' },
            { en: 'I recommend that he should …', ar: 'أوصي بأن …' },
            { en: 'It is better to …', ar: 'من الأفضل أن …' },
            { en: 'You should …', ar: 'ينبغي لك أن …' },
            { en: 'cheat in the exam', ar: 'يغشّ في الامتحان' },
            { en: 'the students who study diligently', ar: 'الطلاب الذين يدرسون باجتهاد' },
            { en: 'deserve the mark', ar: 'يستحقّ العلامة' },
            { en: 'honesty', ar: 'الصدق / الأمانة' },
            { en: 'respect yourself and the rules', ar: 'احترم نفسك والقوانين' },
            { en: 'What is hard today will be easy tomorrow.', ar: 'ما هو صعب اليوم سيكون سهلاً غداً.' },
          ],
          model: 'My friend Sami is a clever boy, but he has a bad habit: he always cheats in the exam. He copies answers from the students who sit next to him, and he sometimes writes notes on small papers. I think cheating is a kind of lying, and it is not fair to the students who study diligently. Sami doesn’t deserve the marks which he gets this way. I advise him to stop cheating at once. It is better to get a low mark than to lose your honesty. I recommend that he should study a little every day. I always tell him, "You should respect yourself, because what is hard today will be easy tomorrow."',
          modelAr: 'صديقي سامي ولد ذكي، لكن لديه عادة سيئة: إنه يغشّ دائماً في الامتحان. ينقل الإجابات من الطلاب الذين يجلسون بجانبه، ويكتب أحياناً ملاحظات على أوراق صغيرة. أعتقد أن الغشّ نوع من الكذب، وأنه ليس عادلاً للطلاب الذين يدرسون باجتهاد. سامي لا يستحقّ العلامات التي يحصل عليها بهذه الطريقة. أنصحه أن يتوقّف عن الغشّ فوراً. من الأفضل أن تحصل على علامة منخفضة على أن تخسر صدقك. وأوصي بأن يدرس قليلاً كل يوم. وأقول له دائماً: «ينبغي لك أن تحترم نفسك، لأن ما هو صعب اليوم سيكون سهلاً غداً».',
          checklistAr: [
            'هل حدّدت المشكلة بوضوح في الجملة الأولى (صديقك يغشّ في الامتحان)؟',
            'هل ذكرت تفاصيل: كيف يغشّ ولماذا هذا السلوك خطأ؟',
            'هل استخدمت كلمات النصيحة: I think, advise, recommend, it is better, you should؟',
            'هل استخدمت جملة صلة واحدة على الأقل (who / which)؟',
            'هل جاء الفعل بعد should وto في صيغة المصدر (should study, to stop)؟',
            'هل الموضوع في حدود 100 كلمة، وراجعت التهجئة وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'It is better to give than to take.', ar: 'العطاء أفضل من الأخذ.' },
        { en: 'Children rejoiced over this challenge and they all started writing diligently.', ar: 'فرح الأطفال بهذا التحدّي وبدؤوا جميعاً يكتبون باجتهاد.' },
        { en: 'After collecting the papers, the teacher was surprised to find that everyone had a full mark.', ar: 'بعد جمع الأوراق، تفاجأت المعلّمة حين وجدت أن الجميع حصلوا على العلامة الكاملة.' },
        { en: 'The teacher thought of a suitable solution with her students.', ar: 'فكّرت المعلّمة في حلّ مناسب مع طلابها.' },
        { en: 'She thanked everyone for this wonderful gift.', ar: 'شكرت الجميع على هذه الهدية الرائعة.' },
        { en: 'Her parents couldn\'t afford to buy her new shoes because of their extreme poverty.', ar: 'لم يكن والداها قادرين على شراء حذاء جديد لها بسبب فقرهما الشديد.' },
        { en: 'The teacher returned home crying and told her husband what had happened.', ar: 'عادت المعلّمة إلى البيت باكية وأخبرت زوجها بما حدث.' },
        { en: 'Suzan is an orphan whose father died when she was a baby.', ar: 'سوزان يتيمة توفّي والدها عندما كانت رضيعة.' },
        { en: 'Suzan is sure that life is difficult when you cannot have what you want.', ar: 'سوزان متأكّدة من أن الحياة صعبة عندما لا تستطيع أن تحصل على ما تريد.' },
        { en: 'But she has learnt from her mother to fight till the end.', ar: 'لكنها تعلّمت من أمّها أن تكافح حتى النهاية.' },
        { en: 'Suzan, who is now 15 years old, works hard to achieve her dreams.', ar: 'سوزان، التي أصبح عمرها الآن 15 عاماً، تعمل بجدّ لتحقّق أحلامها.' },
        { en: 'She shares her skills, talents, and abilities with others.', ar: 'إنها تشارك مهاراتها ومواهبها وقدراتها مع الآخرين.' },
        { en: 'She also urges people of her age to work for welfare services.', ar: 'كما تحثّ من هم في مثل عمرها على العمل في خدمات الرعاية الاجتماعية.' },
        { en: 'He talked to the man who lives next door.', ar: 'تحدّث إلى الرجل الذي يسكن في البيت المجاور.' },
        { en: 'I told you about the woman who lost her bag.', ar: 'أخبرتك عن المرأة التي أضاعت حقيبتها.' },
        { en: 'The parents whom we interviewed were all involved in education.', ar: 'الآباء الذين أجرينا معهم مقابلات كانوا جميعاً يعملون في التعليم.' },
        { en: 'Grandma remembers the time when radio shows were popular.', ar: 'تتذكّر جدّتي الزمن الذي كانت فيه برامج الإذاعة مشهورة.' },
        { en: 'I want to visit the island where my teacher lives.', ar: 'أريد أن أزور الجزيرة التي يعيش فيها معلّمي.' },
      ],
    },

    // ===================== UNIT 10 — Time Waits for No One (Activity Book pages 47–50) =====================
    u10: {
      workbook: {
        pages: '47–50',
        readings: [
          {
            title: 'Hurry up Before the Gates are Shut!',
            paragraphs: [
              'Once, a king and a lazy man named Hani were very good friends. One morning, the king said, "Why don\'t you work to earn some money?" Hani said, "No one offers me a job. My enemies told everyone that I never do any work in time." The kind king said, "You can go into my treasury and collect as much wealth as you can, but you have to finish before sunset." Hani was so happy and rushed home to tell his wife. She said, "Go and get the gold coins and gems now." He said: "I cannot go now. I am so hungry. I\'d like to eat first."',
              'After lunch, he took a nap for an hour. Then in the late afternoon, he picked some bags and went to the palace. On the way, he felt hot so he sat under a tree to rest and drink some water. Two hours later, when he wanted to move on, he saw a man showing some magic tricks. He stopped to watch for an hour again. On the way to the palace, he met an old friend and chatted with him for some time. When he reached the palace, it was already sunset time. The palace gates had been shut.',
              'Hani lost a golden chance because he had not learnt the value of time. If Hani worked hard, he wouldn’t be poor. This story teaches us that once time is spent, it will never come back again.',
            ],
            paragraphsAr: [
              'ذات مرة، كان ملكٌ ورجلٌ كسول اسمه هاني صديقين حميمين. وذات صباح قال الملك: «لماذا لا تعمل لتكسب بعض المال؟» فقال هاني: «لا أحد يعرض عليّ عملاً. لقد أخبر أعدائي الجميع أنني لا أنجز أيّ عمل في وقته أبداً». فقال الملك الطيّب: «يمكنك أن تدخل خزانتي وتجمع من الثروة قدر ما تستطيع، لكن عليك أن تنتهي قبل غروب الشمس». ففرح هاني كثيراً وأسرع إلى بيته ليخبر زوجته. فقالت: «اذهب واحضر القطع الذهبية والجواهر الآن». فقال: «لا أستطيع أن أذهب الآن. أنا جائع جداً. أودّ أن آكل أولاً».',
              'بعد الغداء، أخذ قيلولة لمدة ساعة. ثم في آخر العصر، أخذ بعض الأكياس وذهب إلى القصر. وفي الطريق شعر بالحرّ، فجلس تحت شجرة ليستريح ويشرب بعض الماء. وبعد ساعتين، عندما أراد أن يتابع طريقه، رأى رجلاً يعرض بعض الحيل السحرية، فتوقّف ليتفرّج ساعة أخرى. وفي الطريق إلى القصر، قابل صديقاً قديماً وتحدّث معه بعض الوقت. وعندما وصل إلى القصر كان وقت الغروب قد حلّ. كانت أبواب القصر قد أُغلقت.',
              'أضاع هاني فرصة ذهبية لأنه لم يكن قد تعلّم قيمة الوقت. لو عمل هاني بجدّ لما كان فقيراً. تعلّمنا هذه القصة أن الوقت متى مضى فلن يعود أبداً.',
            ],
            questions: [
              {
                q: 'What was the reason behind Hani\'s poverty?', qAr: 'ما سبب فقر هاني؟',
                options: [
                  'The king took all his money.',
                  'He was lazy and never did any work in time.',
                  'He lost his job at the palace.',
                  'His wife spent all his money.',
                ],
                answer: 1,
                explainAr: 'النص يصفه بأنه "a lazy man" (رجل كسول)، وأعداؤه قالوا إنه "never do any work in time" (لا ينجز أي عمل في وقته). وفي النهاية: "If Hani worked hard, he wouldn’t be poor" = لو عمل بجدّ لما كان فقيراً.',
              },
              {
                q: 'What did the king tell him to do?', qAr: 'ماذا طلب منه الملك أن يفعل؟',
                options: [
                  'To work in the palace garden.',
                  'To leave the city before sunset.',
                  'To go into his treasury and collect as much wealth as he could before sunset.',
                  'To bring him gold coins and gems.',
                ],
                answer: 2,
                explainAr: 'قال الملك: "You can go into my treasury and collect as much wealth as you can, but you have to finish before sunset" = يمكنك أن تدخل خزانتي وتجمع قدر ما تستطيع من الثروة، لكن عليك أن تنتهي قبل الغروب.',
              },
              {
                q: 'How did Hani react?', qAr: 'كيف كانت ردّة فعل هاني؟',
                options: [
                  'He refused the king’s offer.',
                  'He went to the palace immediately.',
                  'He was angry and sad.',
                  'He was so happy and rushed home to tell his wife, but he didn’t go at once.',
                ],
                answer: 3,
                explainAr: 'النص: "Hani was so happy and rushed home to tell his wife" = فرح كثيراً وأسرع ليخبر زوجته. لكنه لم يذهب فوراً، بل قال: "I cannot go now. I am so hungry."',
              },
              {
                q: 'When did he arrive at the palace?', qAr: 'متى وصل إلى القصر؟',
                options: [
                  'In the early morning.',
                  'At sunset, when the palace gates had been shut.',
                  'At lunch time.',
                  'Before sunset, while the gates were still open.',
                ],
                answer: 1,
                explainAr: 'النص: "When he reached the palace, it was already sunset time. The palace gates had been shut." = وصل وقت الغروب وكانت الأبواب قد أُغلقت.',
              },
              {
                q: 'What lesson does the story teach us?', qAr: 'ما الدرس الذي تعلّمنا إياه القصة؟',
                options: [
                  'Once time is spent, it will never come back again.',
                  'Kings always help lazy people.',
                  'It is better to rest before any work.',
                  'Old friends are more important than work.',
                ],
                answer: 0,
                explainAr: 'آخر جملة في النص: "This story teaches us that once time is spent, it will never come back again" = الوقت متى مضى فلن يعود أبداً. وهذا معنى عنوان الوحدة: Time Waits for No One.',
              },
            ],
            trueFalse: [
              { statement: 'Hani is the name of the king.', answer: false },
              { statement: 'He went immediately to the palace to get money.', answer: false },
              { statement: 'Hani watched a man who was showing some magical tricks.', answer: true },
              { statement: 'He came across an old friend.', answer: true },
              { statement: 'He didn\'t get any treasure because he wasted time.', answer: true },
            ],
          },
        ],
        exercises: [
          // ---- page 48B: True or False ----
          tf('Hani is the name of the king.', 'هاني هو اسم الملك.', false,
            'خطأ. هاني هو الرجل الكسول صديق الملك: "a king and a lazy man named Hani". الملك لا يُذكر اسمه في القصة.'),
          tf('He went immediately to the palace to get money.', 'ذهب فوراً إلى القصر ليأخذ المال.', false,
            'خطأ. لم يذهب فوراً: أكل الغداء أولاً، ثم نام ساعة، ثم ذهب في آخر العصر: "After lunch, he took a nap for an hour. Then in the late afternoon, he … went to the palace."'),
          tf('Hani watched a man who was showing some magical tricks.', 'تفرّج هاني على رجل كان يعرض بعض الحيل السحرية.', true,
            'صحيح. النص: "he saw a man showing some magic tricks. He stopped to watch for an hour again."'),
          tf('He came across an old friend.', 'صادف صديقاً قديماً.', true,
            'صحيح. came across = صادف / التقى مصادفةً. النص: "he met an old friend and chatted with him for some time."'),
          tf('He didn\'t get any treasure because he wasted time.', 'لم يحصل على أي كنز لأنه أضاع الوقت.', true,
            'صحيح. وصل بعد الغروب وكانت الأبواب قد أُغلقت: "Hani lost a golden chance because he had not learnt the value of time."'),

          // ---- page 49A: complete the sentences with the correct tense ----
          fill('\'Have you met Angela?\' She asked us if ___ Angela.',
            '«هل قابلتم أنجيلا؟» سألتنا إذا ___ أنجيلا.',
            '«هل قابلتم أنجيلا؟» سألتنا إذا كنّا قد قابلنا أنجيلا.',
            ['we have met', 'we had met', 'had we met', 'you had met'], 1,
            'سؤال yes/no نبدؤه بـ if. المضارع التام (have met) يصبح ماضياً تاماً (had met). الضمير you يصبح we لأنها سألتنا (us). وبعد if يأتي الفاعل قبل الفعل (we had met) لا ترتيب السؤال.'),
          fill('\'Did Mark pass all his exams?\' He asked if Mark ___ all of his exams.',
            '«هل نجح مارك في كل امتحاناته؟» سأل إذا كان مارك ___ في كل امتحاناته.',
            '«هل نجح مارك في كل امتحاناته؟» سأل إذا كان مارك قد نجح في كل امتحاناته.',
            ['had passed', 'has passed', 'did pass', 'passes'], 0,
            'الماضي البسيط (Did … pass) يصبح في الكلام المنقول ماضياً تاماً: had passed. ونحذف did المساعدة لأن الجملة لم تعد سؤالاً.'),
          fill('\'Are you excited about going on a picnic?\' He asked the children ___ excited about going on a picnic.',
            '«هل أنتم متحمّسون للذهاب في نزهة؟» سأل الأطفال ___ متحمّسين للذهاب في نزهة.',
            '«هل أنتم متحمّسون للذهاب في نزهة؟» سأل الأطفال إذا كانوا متحمّسين للذهاب في نزهة.',
            ['were they', 'if they are', 'if they were', 'if you were'], 2,
            'سؤال yes/no ← نستخدم if. المضارع البسيط (are) يصبح ماضياً بسيطاً (were). الضمير you يعود على الأطفال فيصبح they. والترتيب: if + فاعل + فعل.'),
          fill('\'Have you read this book?\' He asked me if ___ that book.',
            '«هل قرأت هذا الكتاب؟» سألني إذا ___ ذلك الكتاب.',
            '«هل قرأت هذا الكتاب؟» سألني إذا كنت قد قرأت ذلك الكتاب.',
            ['I have read', 'had I read', 'you had read', 'I had read'], 3,
            'سألني (me) فيصبح you ← I. المضارع التام (have read) يصبح ماضياً تاماً (had read). ولاحظ أن this تصبح that.'),
          fill('\'How much did the concert tickets cost?\' She asked how much the concert tickets ___.',
            '«كم كان ثمن بطاقات الحفلة الموسيقية؟» سألت كم ___ ثمن بطاقات الحفلة الموسيقية.',
            '«كم كان ثمن بطاقات الحفلة الموسيقية؟» سألت كم كان ثمن بطاقات الحفلة الموسيقية.',
            ['had cost', 'did cost', 'have cost', 'did they cost'], 0,
            'الماضي البسيط (did … cost) يصبح ماضياً تاماً: had cost. نحذف did لأن السؤال المنقول ليس سؤالاً حقيقياً، ونضع الفاعل قبل الفعل.'),
          fill('\'Are you going to the party?\' John asked me if I ___ to the party.',
            '«هل أنت ذاهب إلى الحفلة؟» سألني جون إذا ___ إلى الحفلة.',
            '«هل أنت ذاهب إلى الحفلة؟» سألني جون إذا كنت ذاهباً إلى الحفلة.',
            ['am going', 'was going', 'will go', 'have gone'], 1,
            'المضارع المستمر (are going) يصبح ماضياً مستمراً (was going). ومع الفاعل I نستخدم was.'),

          // ---- page 49B: report the questions ----
          fill('"Where is my umbrella?" She asked ___.',
            '«أين مظلّتي؟» سألت ___.',
            '«أين مظلّتي؟» سألت أين كانت مظلّتها.',
            ['where was her umbrella', 'where her umbrella was', 'where is my umbrella', 'where her umbrella is'], 1,
            'في السؤال المنقول نضع الفاعل قبل الفعل (her umbrella was) ولا نضع علامة استفهام. is تصبح was، وmy تصبح her.'),
          fill('"How are you?" Martin asked us ___.',
            '«كيف حالكم؟» سألنا مارتن ___.',
            '«كيف حالكم؟» سألنا مارتن كيف كان حالنا.',
            ['how we were', 'how were we', 'how are you', 'how you were'], 0,
            'سألنا (us) فيصبح you ← we. are تصبح were. والترتيب: how + فاعل + فعل = how we were.'),
          fill('"Do I have to do it?" He asked ___.',
            '«هل عليّ أن أفعل ذلك؟» سأل ___.',
            '«هل عليّ أن أفعل ذلك؟» سأل إذا كان عليه أن يفعل ذلك.',
            ['did he have to do it', 'if he has to do it', 'if he had to do it', 'if I had to do it'], 2,
            'سؤال yes/no يبدأ بـ Do ← نستخدم if أو whether. نحذف do، والمضارع have يصبح ماضياً had، والضمير I يصبح he لأن المتكلّم هو.'),
          fill('"Where have you been?" The mother asked her daughter ___.',
            '«أين كنتِ؟» سألت الأم ابنتها ___.',
            '«أين كنتِ؟» سألت الأم ابنتها أين كانت.',
            ['where had she been', 'where she has been', 'where you have been', 'where she had been'], 3,
            'المضارع التام (have been) يصبح ماضياً تاماً (had been). you تعود على الابنة فتصبح she. والترتيب: where + فاعل + فعل.'),
          fill('"Which dress do you like best?" She asked her friend ___.',
            '«أيّ فستان يعجبك أكثر؟» سألت صديقتها ___.',
            '«أيّ فستان يعجبك أكثر؟» سألت صديقتها أيّ فستان يعجبها أكثر.',
            ['which dress she liked best', 'which dress did she like best', 'which dress she likes best', 'which dress do you like best'], 0,
            'نحذف do، والمضارع like يصبح ماضياً liked، وyou تصبح she (الصديقة). والترتيب: which dress + فاعل + فعل.'),
          fill('"What are they doing?" She asked ___.',
            '«ماذا يفعلون؟» سألت ___.',
            '«ماذا يفعلون؟» سألت ماذا كانوا يفعلون.',
            ['what were they doing', 'what they are doing', 'what they were doing', 'what they did'], 2,
            'المضارع المستمر (are doing) يصبح ماضياً مستمراً (were doing). والترتيب في السؤال المنقول: what + فاعل + فعل = what they were doing.'),
          fill('"Did you enjoy the festival?" He wanted to know ___.',
            '«هل استمتعت بالمهرجان؟» أراد أن يعرف ___.',
            '«هل استمتعت بالمهرجان؟» أراد أن يعرف إذا كنت قد استمتعت بالمهرجان.',
            ['did I enjoy the festival', 'if I have enjoyed the festival', 'if I had enjoyed the festival', 'if had I enjoyed the festival'], 2,
            'سؤال yes/no ← if. الماضي البسيط (Did … enjoy) يصبح ماضياً تاماً (had enjoyed)، ونحذف did. والترتيب: if + I + had enjoyed.'),

          // ---- page 48 grammar box: the book's examples, practised ----
          fill('"Where is the Post Office, please?" She asked me ___.',
            '«أين مكتب البريد من فضلك؟» سألتني ___.',
            '«أين مكتب البريد من فضلك؟» سألتني أين كان مكتب البريد.',
            ['where was the Post Office', 'where the Post Office was', 'where the Post Office is'], 1,
            'قاعدة الكتاب: المضارع البسيط ← ماضٍ بسيط (is ← was). ونضع الفاعل (the Post Office) قبل الفعل (was)، ونحذف please.'),
          fill('"Who was that fantastic engineer?" She asked me who that fantastic engineer ___.',
            '«من كان ذلك المهندس الرائع؟» سألتني من ___ ذلك المهندس الرائع.',
            '«من كان ذلك المهندس الرائع؟» سألتني من كان ذلك المهندس الرائع.',
            ['has been', 'had been', 'was been', 'is'], 1,
            'قاعدة الكتاب: الماضي البسيط ← ماضٍ تام (was ← had been).'),
          fill('"When has he met his friend?" My mother wanted to know when he ___ his friend.',
            '«متى قابل صديقه؟» أرادت أمي أن تعرف متى ___ صديقه.',
            '«متى قابل صديقه؟» أرادت أمي أن تعرف متى كان قد قابل صديقه.',
            ['has met', 'had met', 'met had', 'meets'], 1,
            'قاعدة الكتاب: المضارع التام ← ماضٍ تام (has met ← had met). ولاحظ أن wanted to know فعل نقل مثل asked.'),
          fill('"Why are you crying?" He inquired why I ___.',
            '«لماذا تبكي؟» استفسر لماذا ___.',
            '«لماذا تبكي؟» استفسر لماذا كنت أبكي.',
            ['am crying', 'was crying', 'were crying', 'cry'], 1,
            'قاعدة الكتاب: المضارع المستمر ← ماضٍ مستمر (are crying ← was crying). you تصبح I، ومع I نستخدم was.'),
          fill('"Do you know him?" He asked me ___ I knew him.',
            '«هل تعرفه؟» سألني ___ كنت أعرفه.',
            '«هل تعرفه؟» سألني إن كنت أعرفه.',
            ['that', 'whether', 'what', 'do'], 1,
            'عندما ننقل سؤالاً جوابه yes/no نستخدم if أو whether (بمعنى: إن / إذا). لا نستخدم that ولا do.'),
          fill('"Have you ever been to Mexico?" She asked me if I ___ to Mexico.',
            '«هل سبق أن ذهبت إلى المكسيك؟» سألتني إذا ___ إلى المكسيك.',
            '«هل سبق أن ذهبت إلى المكسيك؟» سألتني إذا كنت قد ذهبت يوماً إلى المكسيك.',
            ['have ever been', 'had ever been', 'ever was', 'had ever went'], 1,
            'المضارع التام (have been) يصبح ماضياً تاماً (had been)، والتصريف الثالث لـ go هنا been (لا went).'),
          fill('"Are you living here?" She asked me if I was living ___.',
            '«هل تسكن هنا؟» سألتني إذا كنت أسكن ___.',
            '«هل تسكن هنا؟» سألتني إذا كنت أسكن هناك.',
            ['here', 'there', 'this', 'now'], 1,
            'من التغييرات الأخرى في الكلام المنقول: here ← there (هنا ← هناك).'),
          mcq('In a reported question, "tomorrow" becomes:', 'في السؤال المنقول، تصبح كلمة "tomorrow" (غداً):',
            ['that day', 'the next day', 'the previous day', 'then'], 1,
            'حسب جدول الكتاب: tomorrow ← the next day (اليوم التالي).'),
          mcq('In a reported question, "yesterday" becomes:', 'في السؤال المنقول، تصبح كلمة "yesterday" (أمس):',
            ['the next day', 'that day', 'the previous day', 'there'], 2,
            'حسب جدول الكتاب: yesterday ← the previous day أو the day before (اليوم السابق).'),
          mcq('In a reported question, "now" becomes:', 'في السؤال المنقول، تصبح كلمة "now" (الآن):',
            ['then', 'there', 'that day', 'those'], 0,
            'حسب جدول الكتاب: now ← then (عندئذٍ / في ذلك الوقت).'),
          mcq('In a reported question, "these" becomes:', 'في السؤال المنقول، تصبح كلمة "these" (هؤلاء / هذه):',
            ['that', 'those', 'there', 'this'], 1,
            'حسب جدول الكتاب: these ← those، وthis ← that.'),
          mcq('The pronouns change: "Where is my umbrella?" → She asked where ___ umbrella was.', 'تتغيّر الضمائر: «أين مظلّتي؟» ← سألت أين كانت ___ (مظلّتـ...).',
            ['my', 'her', 'your', 'our'], 1,
            'حسب جدول الضمائر: my ← your / her / his حسب المتكلّم. المتكلّمة هنا هي (She)، فتصبح my ← her.'),
          fill('"Why don\'t you work to earn some money?" The king asked Hani why he ___ to earn some money.',
            '«لماذا لا تعمل لتكسب بعض المال؟» سأل الملكُ هانيَ لماذا ___ ليكسب بعض المال.',
            '«لماذا لا تعمل لتكسب بعض المال؟» سأل الملكُ هانيَ لماذا لا يعمل ليكسب بعض المال.',
            ['doesn\'t work', 'didn\'t work', 'don\'t work', 'not worked'], 1,
            'سؤال الملك من قصة هاني بالمضارع البسيط (don\'t work)، فيصبح في الكلام المنقول ماضياً بسيطاً (didn\'t work). you تصبح he (هاني).'),

          // ---- page 47 Key Words ----
          mcq('Key Words: what does "treasury" mean?', 'الكلمات المفتاحية: ما معنى كلمة "treasury"؟',
            ['precious stones', 'a place where treasure (money, jewellery) is kept', 'a big house where a king lives', 'a short sleep in the afternoon'], 1,
            'treasury = الخزانة / بيت المال: مكان يُحفظ فيه الكنز (المال والمجوهرات)، كما في: "You can go into my treasury".'),
          mcq('Key Words: what does "gems" mean?', 'الكلمات المفتاحية: ما معنى كلمة "gems"؟',
            ['gold coins', 'magic tricks', 'precious stones', 'bags of money'], 2,
            'gems = الأحجار الكريمة / الجواهر، كما في: "Go and get the gold coins and gems now."'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Rewrite the following paragraph using correct punctuation and capitalization. The post office is in a city centre.There is alot of people. They are wait in line.some people wants to buy stambs. Others want to mail letters. Some people want to sent packages There are not many parking space near the post office. The drivers are waiting for parking places honking there horns.',
          topicAr: 'أعد كتابة الفقرة التالية مستخدماً علامات الترقيم والأحرف الكبيرة بشكل صحيح. (معنى الفقرة: مكتب البريد في وسط المدينة. هناك الكثير من الناس. إنهم ينتظرون في الطابور. بعض الناس يريدون شراء طوابع. وآخرون يريدون إرسال رسائل. وبعضهم يريدون إرسال طرود. لا توجد أماكن كثيرة لركن السيارات قرب مكتب البريد. السائقون ينتظرون أماكن للركن وهم يطلقون أبواق سياراتهم.)',
          words: 56,
          plan: [
            { en: 'Start every sentence with a capital letter (some people → Some people).', ar: 'ابدأ كل جملة بحرف كبير (some people ← Some people).' },
            { en: 'End every sentence with a full stop and leave a space after it (centre.There → centre. There; packages There → packages. There).', ar: 'أنهِ كل جملة بنقطة واترك مسافة بعدها (centre.There ← centre. There، وpackages There ← packages. There).' },
            { en: 'Correct the verbs: There is → There are, are wait → are waiting, wants → want, to sent → to send.', ar: 'صحّح الأفعال: There is ← There are (لأن people جمع)، are wait ← are waiting، wants ← want، to sent ← to send (بعد to مصدر).' },
            { en: 'Correct the spelling and the plurals: alot → a lot, stambs → stamps, space → spaces, there horns → their horns; put a comma before "honking".', ar: 'صحّح التهجئة والجمع: alot ← a lot، stambs ← stamps، space ← spaces، there horns ← their horns (their = ـهم للملكية)؛ وضع فاصلة قبل honking.' },
          ],
          phrases: [
            { en: 'There are a lot of people.', ar: 'هناك الكثير من الناس.' },
            { en: 'They are waiting in line.', ar: 'إنهم ينتظرون في الطابور.' },
            { en: 'Some people want to buy stamps.', ar: 'بعض الناس يريدون شراء طوابع.' },
            { en: 'Others want to mail letters.', ar: 'وآخرون يريدون إرسال رسائل بالبريد.' },
            { en: 'want to send packages', ar: 'يريدون إرسال طرود' },
            { en: 'not many parking spaces', ar: 'أماكن قليلة لركن السيارات' },
            { en: 'honking their horns', ar: 'يطلقون أبواق سياراتهم' },
            { en: 'a capital letter', ar: 'حرف كبير' },
            { en: 'a full stop (.)', ar: 'نقطة (.)' },
            { en: 'a comma (,)', ar: 'فاصلة (,)' },
          ],
          model: 'The post office is in a city centre. There are a lot of people. They are waiting in line. Some people want to buy stamps. Others want to mail letters. Some people want to send packages. There are not many parking spaces near the post office. The drivers are waiting for parking places, honking their horns.',
          modelAr: 'مكتب البريد في وسط المدينة. هناك الكثير من الناس. إنهم ينتظرون في الطابور. بعض الناس يريدون شراء طوابع. وآخرون يريدون إرسال رسائل بالبريد. وبعض الناس يريدون إرسال طرود. لا توجد أماكن كثيرة لركن السيارات قرب مكتب البريد. السائقون ينتظرون أماكن للركن وهم يطلقون أبواق سياراتهم.',
          checklistAr: [
            'هل بدأت كل جملة بحرف كبير؟',
            'هل أنهيت كل جملة بنقطة وتركت مسافة بعدها (ولم تنسَ النقطة بعد packages)؟',
            'هل صحّحت الأفعال: There are، are waiting، want، to send؟',
            'هل صحّحت التهجئة: a lot، stamps، their horns؟',
            'هل كتبت الجمع parking spaces بعد many؟',
            'هل حافظت على معنى الفقرة من دون أن تضيف أو تحذف أفكاراً؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write a diary about what you do to manage and organize your time.',
          topicAr: 'اكتب مذكّرات (يوميات) عمّا تفعله لتدير وقتك وتنظّمه.',
          words: 100,
          points: [
            'Paragraph 1: Introduction and things you do in the morning.',
            'Paragraph 2: Things you do during the afternoon.',
            'Paragraph 3: Things you do at night before bed time.',
            'Please include adverbs of frequency (always – usually – often – sometimes – rarely – never) or time expression (once a week – twice a week – everyday – three times a week – etc. ...)',
          ],
          pointsAr: [
            'الفقرة 1: مقدّمة وما تفعله في الصباح.',
            'الفقرة 2: ما تفعله خلال فترة بعد الظهر.',
            'الفقرة 3: ما تفعله في الليل قبل وقت النوم.',
            'استخدم ظروف التكرار (always دائماً – usually عادةً – often غالباً – sometimes أحياناً – rarely نادراً – never أبداً) أو تعابير زمنية (once a week مرة في الأسبوع – twice a week مرتين في الأسبوع – everyday كل يوم – three times a week ثلاث مرات في الأسبوع …).',
          ],
          plan: [
            { en: 'Paragraph 1: a short introduction (why time is precious) and what you do in the morning.', ar: 'الفقرة 1: مقدّمة قصيرة (لماذا الوقت ثمين) وما تفعله في الصباح.' },
            { en: 'Paragraph 2: what you do in the afternoon: lunch, rest, homework and activities.', ar: 'الفقرة 2: ما تفعله بعد الظهر: الغداء والراحة والواجبات والنشاطات.' },
            { en: 'Paragraph 3: what you do at night before bed time, and how you avoid time stealers.', ar: 'الفقرة 3: ما تفعله في الليل قبل النوم، وكيف تتجنّب سارقي الوقت.' },
            { en: 'Use the present simple with adverbs of frequency and time expressions in every paragraph.', ar: 'استخدم المضارع البسيط مع ظروف التكرار والتعابير الزمنية في كل فقرة.' },
          ],
          phrases: [
            { en: 'Time is precious.', ar: 'الوقت ثمين.' },
            { en: 'manage my time efficiently', ar: 'أدير وقتي بكفاءة' },
            { en: 'Divide what you have to do.', ar: 'قسّم ما عليك فعله.' },
            { en: 'Organise your materials.', ar: 'نظّم أدواتك.' },
            { en: 'Ignore interruption.', ar: 'تجاهل المقاطعات.' },
            { en: 'Watch out for time stealers.', ar: 'احذر من سارقي الوقت.' },
            { en: 'Now, not tomorrow.', ar: 'الآن، لا غداً.' },
            { en: 'always / usually / often / sometimes / rarely / never', ar: 'دائماً / عادةً / غالباً / أحياناً / نادراً / أبداً' },
            { en: 'once a week / twice a week / three times a week', ar: 'مرة في الأسبوع / مرتين في الأسبوع / ثلاث مرات في الأسبوع' },
            { en: 'productive', ar: 'منتج / مثمر' },
            { en: 'waste time', ar: 'يضيّع الوقت' },
            { en: 'Time waits for no one.', ar: 'الوقت لا ينتظر أحداً.' },
          ],
          model: 'Time is precious, so I always try to manage it efficiently. I usually get up at six o\'clock. I have breakfast with my family and leave home at seven, so I am never late for school. At school, I listen carefully and I rarely waste time.\nIn the afternoon, I have lunch and rest for half an hour. Then I divide what I have to do into small tasks. I often start with the most difficult one. I go to the library twice a week, and I play football once a week.\nAt night, I sometimes watch TV for an hour, but I watch out for time stealers like the Internet. Before bed, I organise my materials for the next day. Now, not tomorrow!',
          modelAr: 'الوقت ثمين، لذلك أحاول دائماً أن أديره بكفاءة. أستيقظ عادةً في الساعة السادسة. أتناول الفطور مع عائلتي وأغادر البيت في السابعة، لذلك لا أتأخّر عن المدرسة أبداً. في المدرسة أُصغي جيداً ونادراً ما أضيّع الوقت.\nبعد الظهر، أتناول الغداء وأرتاح نصف ساعة. ثم أقسّم ما عليّ فعله إلى مهام صغيرة، وغالباً ما أبدأ بأصعبها. أذهب إلى المكتبة مرتين في الأسبوع، وألعب كرة القدم مرة في الأسبوع.\nفي الليل، أشاهد التلفاز أحياناً لمدة ساعة، لكنني أحذر من سارقي الوقت مثل الإنترنت. وقبل النوم أنظّم أدواتي لليوم التالي. الآن، لا غداً!',
          checklistAr: [
            'هل قسمت اليوميات إلى ثلاث فقرات: الصباح، بعد الظهر، الليل؟',
            'هل بدأت بمقدّمة قصيرة عن أهمية الوقت؟',
            'هل استخدمت ظروف التكرار (always, usually, often, sometimes, rarely, never) وتعابير زمنية (once a week, twice a week)؟',
            'هل وضعت ظرف التكرار قبل الفعل الأساسي (I usually get up) وبعد فعل be (I am never late)؟',
            'هل استخدمت المضارع البسيط وأضفت ‎-s‎ مع he/she/it؟',
            'هل استخدمت أفكاراً من الوحدة لإدارة الوقت (Divide, Organise, Watch out for time stealers, Now, not tomorrow)؟',
          ],
        },
      ],
      translations: [
        { en: 'We should never waste it in any way.', ar: 'يجب ألّا نضيّعه أبداً بأيّ شكل من الأشكال.' },
        { en: 'That is why most of successful people consider time more important and valuable than money.', ar: 'لهذا يَعدّ معظم الناجحين الوقت أهمّ وأثمن من المال.' },
        { en: 'We all should use our time in productive ways.', ar: 'يجب علينا جميعاً أن نستخدم وقتنا بطرق مثمرة.' },
        { en: 'If you master the technique of managing time efficiently, you can achieve anything in your life.', ar: 'إذا أتقنت أسلوب إدارة الوقت بكفاءة، فستستطيع أن تحقّق أيّ شيء في حياتك.' },
        { en: 'Time management helps you to attain more with less effort.', ar: 'تساعدك إدارة الوقت على تحقيق المزيد بجهد أقلّ.' },
        { en: 'Eventually, this will encourage you to achieve more in life.', ar: 'في النهاية، سيشجّعك هذا على تحقيق المزيد في الحياة.' },
        { en: 'Time is the greatest gift of God.', ar: 'الوقت أعظم هبة من الله.' },
        { en: 'He asked me if I was happy to be back.', ar: 'سألني إذا كنت سعيداً بالعودة.' },
        { en: 'They wanted to know whether we had a computer.', ar: 'أرادوا أن يعرفوا إن كان لدينا حاسوب.' },
        { en: 'Once, a king and a lazy man named Hani were very good friends.', ar: 'ذات مرة، كان ملكٌ ورجلٌ كسول اسمه هاني صديقين حميمين.' },
        { en: 'Hani was so happy and rushed home to tell his wife.', ar: 'فرح هاني كثيراً وأسرع إلى بيته ليخبر زوجته.' },
        { en: 'After lunch, he took a nap for an hour.', ar: 'بعد الغداء، أخذ قيلولة لمدة ساعة.' },
        { en: 'The palace gates had been shut.', ar: 'كانت أبواب القصر قد أُغلقت.' },
        { en: 'Hani lost a golden chance because he had not learnt the value of time.', ar: 'أضاع هاني فرصة ذهبية لأنه لم يكن قد تعلّم قيمة الوقت.' },
        { en: 'This story teaches us that once time is spent, it will never come back again.', ar: 'تعلّمنا هذه القصة أن الوقت متى مضى فلن يعود أبداً.' },
        { en: 'She asked me where the Post Office was.', ar: 'سألتني أين كان مكتب البريد.' },
        { en: 'My mother wanted to know when he had met his friend.', ar: 'أرادت أمي أن تعرف متى كان قد قابل صديقه.' },
        { en: 'She asked me if I had ever been to Mexico.', ar: 'سألتني إذا كنت قد ذهبت يوماً إلى المكسيك.' },
      ],
    },
  },
}
