import type { GrammarExercise } from '../../../engine/types'
import type { ModuleExtras } from './merge'

// Module 2 "The Future World" — Activity Book pages 11–18 (Unit 3: 11–13, Unit 4: 14–18). No Progress Test.
// Left out: the Speaking discussion questions (open speaking) and both Listening tasks (p. 13 Malik,
// p. 17 the trip around the moon), whose answers depend on the recording.

const fill = (prompt: string, promptAr: string, promptArFull: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, promptAr, promptArFull, options, answer, explainAr })
const mcq = (prompt: string, promptAr: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, promptAr, options, answer, explainAr })
const build = (answer: string, prompt: string, explainAr: string): GrammarExercise =>
  ({ type: 'build', answer, prompt, explainAr })

/** A Key Words item: the right meaning and three others, in alphabetical order so the answer does not always sit first. */
function matchItem(word: string, meanings: string[], right: number, others: number[], explainAr: string): GrammarExercise {
  const options = [right, ...others].map(i => meanings[i]).sort()
  return mcq(`Match the word to its meaning: "${word}"`, `ما معنى كلمة "${word}"؟`, options, options.indexOf(meanings[right]), explainAr)
}

// ---------- Unit 3, page 11: Key Words of "Living in Space" ----------
const u3Meanings = [
  'a new place to live in for large groups',
  'a vehicle used for travelling or carrying astronauts into space',
  'very big/huge',
  'get',
  'an organized journey with a particular purpose',
]

// ---------- Unit 4, page 15: Key Words of "Ecological Cities" ----------
const u4Meanings = [
  'interested in preserving the environment',
  'to think that something is true',
  'the process of getting better at doing something',
  'great and sudden',
  'continuously moving or changing',
  'to treat something as being more important than other things',
  'the ability of continuing without causing damage',
  'when an activity or process begins again',
  'the process by which something changes to a worse condition',
  'to supply land or crops with water',
]

// ---------- Unit 4, page 15 B: match the beginnings (A) with the ends (B) ----------
const u4Ends = [
  "a dynamic solution to society's recent problems.",
  'surrounded by rivers.',
  'most things will stay the same in the future.',
  'to rethink of our health.',
  'to prioritize environmental renewal.',
  'are very dramatic.',
]
function matchEnd(begin: string, beginAr: string, right: number, others: number[], explainAr: string): GrammarExercise {
  const options = [right, ...others].map(i => u4Ends[i]).sort()
  return mcq(`Match the beginning with its end: "${begin} …"`, `اختر النهاية المناسبة لبداية الجملة: «${beginAr} …»`,
    options, options.indexOf(u4Ends[right]), explainAr)
}

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 3 — A More Comfortable Life (Activity Book pages 11–13) =====================
    u3: {
      workbook: {
        pages: '11–13',
        readings: [
          {
            title: 'Living in Space',
            paragraphs: [
              "Someday people will live in space. By the end of this century, there will be permanent settlements that will allow people to lead a normal life in space. Hundreds of astronauts are going to work and live in the space station, which will take ten years to build. In some way, living on the moon will be easier than living in a space station and it will be cheaper because people won't bring everything from the Earth by rockets. The space city will be like a gigantic glass wheel that will contain buildings, factories and special meeting places. Inside it, people won't live differently from small towns on the Earth. It will have air so that inhabitants can breathe and they won't need to wear special space-suits inside the buildings. Scientists also believe that they will obtain water from a large ice lake on the moon. People won't have to do housework because robots will do that for them. Food won't be a problem, as settlers won't need to eat. Instead, they will take a pill three times a day. The first group of astronauts will live on the moon for six months and then they will return to the Earth and another group will travel. This will be repeated until the first settlers can finish establishing the new city. Life on the moon will be just the beginning. We hope they will use the knowledge we get there to plan expeditions to Mars, Mercury and even Pluto.",
            ],
            paragraphsAr: [
              'سيعيش الناس يوماً ما في الفضاء. فبحلول نهاية هذا القرن ستكون هناك مستوطنات دائمة تسمح للناس بأن يعيشوا حياة طبيعية في الفضاء. وسيعمل مئات من روّاد الفضاء ويعيشون في المحطة الفضائية التي سيستغرق بناؤها عشر سنوات. ومن بعض النواحي سيكون العيش على القمر أسهل من العيش في محطة فضائية، وسيكون أرخص أيضاً لأن الناس لن يجلبوا كل شيء من الأرض بالصواريخ. ستكون المدينة الفضائية مثل عجلة زجاجية عملاقة تضمّ مبانيَ ومصانع وأماكن خاصة للاجتماعات. وفي داخلها لن يعيش الناس بطريقة مختلفة عن البلدات الصغيرة على الأرض. سيكون فيها هواء لكي يتمكّن سكانها من التنفّس، ولن يحتاجوا إلى ارتداء بزّات فضائية خاصة داخل المباني. ويعتقد العلماء أيضاً أنهم سيحصلون على الماء من بحيرة جليدية كبيرة على القمر. لن يضطرّ الناس إلى القيام بالأعمال المنزلية لأن الروبوتات ستقوم بها عنهم. ولن يكون الطعام مشكلة، إذ لن يحتاج المستوطنون إلى الأكل، بل سيتناولون حبّة ثلاث مرات في اليوم. ستعيش المجموعة الأولى من روّاد الفضاء على القمر ستة أشهر، ثم يعودون إلى الأرض وتسافر مجموعة أخرى. وسيتكرّر هذا إلى أن يتمكّن المستوطنون الأوائل من إنهاء تأسيس المدينة الجديدة. والحياة على القمر ستكون مجرّد البداية. ونأمل أن يستخدموا المعرفة التي نكتسبها هناك للتخطيط لرحلات استكشافية إلى المريخ وعطارد وحتى بلوتو.',
            ],
            questions: [
              {
                q: 'How will people live on the moon?', qAr: 'كيف سيعيش الناس على القمر؟',
                options: [
                  'They will live in permanent settlements and lead a normal life, like people in small towns on the Earth.',
                  'They will live inside rockets and wear special space-suits all the time.',
                  'They will live in tents and cook their own food.',
                  'They will live alone without any buildings or factories.',
                ],
                answer: 0,
                explainAr: 'يقول النص: "there will be permanent settlements that will allow people to lead a normal life in space" و"people won\'t live differently from small towns on the Earth"، أي سيعيشون في مستوطنات دائمة حياة طبيعية مثل البلدات الصغيرة على الأرض.',
              },
              {
                q: 'How long will each group stay in the space city?', qAr: 'كم من الوقت ستبقى كل مجموعة في المدينة الفضائية؟',
                options: ['For six months.', 'For ten years.', 'For three days.', 'Until the end of this century.'],
                answer: 0,
                explainAr: 'يقول النص: "The first group of astronauts will live on the moon for six months" ثم تعود وتأتي مجموعة أخرى. أما ten years فهي مدة بناء المحطة الفضائية، وليست مدة البقاء.',
              },
              {
                q: 'When will people live on the moon?', qAr: 'متى سيعيش الناس على القمر؟',
                options: ['By the end of this century.', 'Nowadays.', 'Next year.', 'In six months.'],
                answer: 0,
                explainAr: 'يقول النص: "By the end of this century, there will be permanent settlements" أي بحلول نهاية هذا القرن. لاحظ أن ذلك في المستقبل وليس الآن (nowadays).',
              },
              {
                q: 'Where will people in the space take water from?', qAr: 'من أين سيأخذ الناس في الفضاء الماء؟',
                options: ['From a large ice lake on the moon.', 'From the Earth by rockets.', 'From the rivers of Mars.', 'From the pills they take.'],
                answer: 0,
                explainAr: 'يقول النص: "they will obtain water from a large ice lake on the moon" أي من بحيرة جليدية كبيرة على القمر. (obtain = get: يحصل على).',
              },
              {
                q: 'What will the space city be like?', qAr: 'كيف ستكون المدينة الفضائية؟',
                options: ['Like a gigantic glass wheel.', 'Like a small rocket.', 'Like a large ice lake.', 'Like a big space-suit.'],
                answer: 0,
                explainAr: 'يقول النص: "The space city will be like a gigantic glass wheel" أي مثل عجلة زجاجية عملاقة تضمّ مباني ومصانع وأماكن للاجتماعات. (gigantic = very big/huge).',
              },
              {
                q: 'Why won\'t food be a problem on the moon?', qAr: 'لماذا لن يكون الطعام مشكلة على القمر؟',
                options: [
                  'Because settlers won\'t need to eat; they will take a pill three times a day.',
                  'Because robots will cook for them.',
                  'Because they will grow crops on the moon.',
                  'Because rockets will bring food from the Earth every day.',
                ],
                answer: 0,
                explainAr: 'يقول النص: "Food won\'t be a problem, as settlers won\'t need to eat. Instead, they will take a pill three times a day." أي لن يحتاجوا إلى الأكل بل سيتناولون حبّة ثلاث مرات يومياً.',
              },
            ],
            trueFalse: [
              { statement: 'Nowadays, it is possible for people to live on the moon.', answer: false },
              { statement: 'On the moon, people will have to wear special clothes.', answer: false },
              { statement: 'Astronauts will cook on the moon.', answer: false },
              { statement: 'Robots will do the work of humans.', answer: true },
            ],
          },
        ],
        exercises: [
          // ---- page 11: Key Words ----
          matchItem('settlement', u3Meanings, 0, [1, 2, 4], 'settlement = مستوطنة: مكان جديد تسكن فيه مجموعات كبيرة من الناس، كما في النص: "there will be permanent settlements".'),
          matchItem('rocket', u3Meanings, 1, [0, 3, 4], 'rocket = صاروخ: مركبة تُستخدم للسفر أو لنقل روّاد الفضاء إلى الفضاء، كما في النص: "people won\'t bring everything from the Earth by rockets".'),
          matchItem('gigantic', u3Meanings, 2, [0, 3, 4], 'gigantic = عملاق، ضخم جداً (very big/huge)، كما في النص: "a gigantic glass wheel".'),
          matchItem('obtain', u3Meanings, 3, [0, 1, 2], 'obtain = يحصل على (get)، كما في النص: "they will obtain water from a large ice lake".'),
          matchItem('expedition', u3Meanings, 4, [0, 1, 3], 'expedition = رحلة استكشافية: رحلة منظّمة لها هدف محدّد، كما في النص: "to plan expeditions to Mars".'),

          // ---- page 12 B: correct the false statements ----
          mcq('"Nowadays, it is possible for people to live on the moon." This statement is false. Choose the correction.',
            'العبارة «في الوقت الحاضر، من الممكن أن يعيش الناس على القمر» خاطئة. اختر التصحيح.',
            [
              'People will live on the moon by the end of this century.',
              'People have lived on the moon for ten years.',
              'People will never live on the moon.',
              'Only robots can live on the moon nowadays.',
            ], 0,
            'النص يتحدّث عن المستقبل لا عن الحاضر: "Someday people will live in space. By the end of this century, there will be permanent settlements". لذلك التصحيح: سيعيش الناس على القمر بحلول نهاية هذا القرن.'),
          mcq('"On the moon, people will have to wear special clothes." This statement is false. Choose the correction.',
            'العبارة «على القمر، سيضطرّ الناس إلى ارتداء ملابس خاصة» خاطئة. اختر التصحيح.',
            [
              'They won\'t need to wear special space-suits inside the buildings.',
              'They will have to wear special space-suits all the time.',
              'They will wear the same clothes for six months.',
              'They will make their clothes from glass.',
            ], 0,
            'يقول النص: "It will have air so that inhabitants can breathe and they won\'t need to wear special space-suits inside the buildings." فالمدينة فيها هواء، ولن يحتاجوا إلى البزّات الفضائية داخل المباني.'),
          mcq('"Astronauts will cook on the moon." This statement is false. Choose the correction.',
            'العبارة «سيطبخ روّاد الفضاء على القمر» خاطئة. اختر التصحيح.',
            [
              'Settlers won\'t need to eat; they will take a pill three times a day.',
              'Robots will cook for the astronauts three times a day.',
              'Astronauts will bring cooked food from the Earth by rockets.',
              'Astronauts will cook only once a day.',
            ], 0,
            'يقول النص: "Food won\'t be a problem, as settlers won\'t need to eat. Instead, they will take a pill three times a day." فلن يطبخوا أصلاً لأنهم لن يحتاجوا إلى الأكل.'),

          // ---- page 12 Vocabulary: circle the correct words in brackets ----
          fill('It is ___ to feel nervous before an exam.',
            'من ___ أن تشعر بالتوتّر قبل الامتحان.',
            'من الطبيعي أن تشعر بالتوتّر قبل الامتحان.',
            ['normally', 'normal', 'normality'], 1,
            'بعد الفعل is نحتاج صفة تصف الحالة: normal (طبيعي). normally ظرف يصف فعلاً، وnormality اسم.'),
          fill('Property in Homs is ___ than property in Damascus.',
            'العقارات في حمص ___ من العقارات في دمشق.',
            'العقارات في حمص أرخص من العقارات في دمشق.',
            ['cheaper', 'cheap', 'cheapest'], 0,
            'وجود than يعني أننا نقارن بين شيئين، فنستخدم صيغة المقارنة: cheap + er = cheaper (أرخص). cheapest للتفضيل بين أكثر من شيئين مع the.'),
          fill('Doctors gave Hani oxygen to help him ___.',
            'أعطى الأطباء هاني الأكسجين لمساعدته على ___.',
            'أعطى الأطباء هاني الأكسجين لمساعدته على التنفّس.',
            ['breath', 'breathe', 'breathing'], 1,
            'بعد help + مفعول به (him) يأتي الفعل في المصدر: help him breathe. انتبه: breathe فعل (يتنفّس)، أما breath بدون e فاسم (نَفَس).'),
          fill('You will need to ___ permission from the teacher if you want to leave the class.',
            'ستحتاج إلى ___ إذن من المعلّم إذا أردت مغادرة الصف.',
            'ستحتاج إلى الحصول على إذن من المعلّم إذا أردت مغادرة الصف.',
            ['obtained', 'obtain', 'obtaining'], 1,
            'بعد need to يأتي الفعل في صيغة المصدر بلا إضافات: to obtain (يحصل على). لا نقول to obtained ولا to obtaining.'),
          fill('He has to take ___ to control his blood pressure.',
            'يجب أن يتناول ___ ليضبط ضغط دمه.',
            'يجب أن يتناول الحبوب (الأقراص) ليضبط ضغط دمه.',
            ['bills', 'pills', 'bells'], 1,
            'pills = حبوب/أقراص دواء، وهي ما نتناوله لضبط ضغط الدم (وفي النص: "they will take a pill three times a day"). bills = فواتير، وbells = أجراس.'),
          fill('Our goal is to ___ a new research centre in our city.',
            'هدفنا أن ___ مركز أبحاث جديداً في مدينتنا.',
            'هدفنا أن نؤسّس مركز أبحاث جديداً في مدينتنا.',
            ['establishment', 'establish', 'established'], 1,
            'بعد is to نحتاج فعلاً في صيغة المصدر: to establish (يؤسّس). establishment اسم (مؤسّسة/تأسيس). وفي النص: "finish establishing the new city".'),

          // ---- page 12 Grammar A: select the correct answer (will / going to) ----
          fill('Amal has bought a new book. Tonight she ___ stay at home and start reading it.',
            'اشترت أمل كتاباً جديداً. الليلة ___ في البيت وتبدأ بقراءته.',
            'اشترت أمل كتاباً جديداً. الليلة ستبقى (تنوي أن تبقى) في البيت وتبدأ بقراءته.',
            ['will', 'is going to', 'are going to'], 1,
            'هذه خطة قرّرتها أمل مسبقاً (اشترت الكتاب لتقرأه الليلة)، والخطط والنوايا تأخذ be going to. والفاعل she مفرد فنقول is going to.'),
          fill('The phone is ringing. I ___ answer it.',
            'الهاتف يرنّ. ___ عليه.',
            'الهاتف يرنّ. سأردّ عليه.',
            ['am going to', 'will', 'am'], 1,
            'قرّرت الردّ في لحظة الكلام (سمعت الهاتف الآن)، والقرار الفوري لحظة الكلام يأخذ will: I\'ll answer it.'),
          fill('I am not free tomorrow. I ___ see the doctor.',
            'لستُ متفرّغاً غداً. ___ الطبيب.',
            'لستُ متفرّغاً غداً. سأزور (أنوي أن أرى) الطبيب.',
            ['will', 'am going to', 'is going to'], 1,
            'موعد الطبيب خطة مرتّبة مسبقاً للمستقبل، لذلك نستخدم be going to. ومع I نقول am going to.'),
          fill('We forgot to buy bread. We ___ go back to buy some.',
            'نسينا شراء الخبز. ___ لنشتري بعضه.',
            'نسينا شراء الخبز. سنعود لنشتري بعضه.',
            ['are going to', 'will', 'were'], 1,
            'اكتشفوا الآن أنهم نسوا الخبز فقرّروا العودة في لحظة الكلام، والقرار الفوري يأخذ will.'),
          fill('She is so tired. She needs some rest. I think she ___ take a week off.',
            'إنها متعبة جداً وتحتاج إلى بعض الراحة. أظنّ أنها ___ إجازة لمدة أسبوع.',
            'إنها متعبة جداً وتحتاج إلى بعض الراحة. أظنّ أنها ستأخذ إجازة لمدة أسبوع.',
            ['is going to', 'will', 'are going to'], 1,
            'عبارة I think تعبّر عن رأي وتوقّع شخصي، والكتاب يستخدم معها will كما في مثاله: "I think Brazil will win the next World Cup."'),

          // ---- page 12–13 Grammar B: complete with will or the correct form of be going to ----
          fill('Do you want to go with us next Saturday? We ___ a football match.',
            'هل تريد أن تذهب معنا يوم السبت القادم؟ ___ مباراة كرة قدم.',
            'هل تريد أن تذهب معنا يوم السبت القادم؟ سنحضر (ننوي أن نحضر) مباراة كرة قدم.',
            ['are going to attend', 'is going to attend', 'will attended', 'attending'], 0,
            'حضور المباراة يوم السبت خطة مرتّبة مسبقاً، فنستخدم be going to + المصدر. ومع We نقول are going to attend.'),
          fill('The weather ___ dreadful tomorrow.',
            'الطقس ___ سيئاً جداً غداً.',
            'الطقس سيكون سيئاً جداً غداً.',
            ['will be', 'will is', 'is going to being', 'be'], 0,
            'هذا توقّع للمستقبل بلا دليل ظاهر أمامنا (لا نرى غيوماً مثلاً)، فنستخدم will + المصدر: will be. بعد will لا نضع is.'),
          fill('I ___ that heavy box for you.',
            '___ ذلك الصندوق الثقيل عنك.',
            'سأرفع ذلك الصندوق الثقيل عنك.',
            ['will lift', 'am going to lifting', 'lifts', 'will lifted'], 0,
            'هذا عرض مساعدة وقرار في لحظة الكلام (رأيت الصندوق الثقيل الآن)، فنستخدم will + المصدر: I will lift. وفي كتاب الطالب: "It is a heavy box. I will lift it for you."'),
          fill('Tonight we ___ a birthday party for our mother.',
            'الليلة ___ حفلة عيد ميلاد لأمّنا.',
            'الليلة سنقيم (نخطّط لإقامة) حفلة عيد ميلاد لأمّنا.',
            ['are going to have', 'is going to have', 'will had', 'going to have'], 0,
            'الحفلة خطة مرتّبة مسبقاً لهذه الليلة، فنستخدم be going to + المصدر. ومع we نقول are going to have، ولا يجوز حذف are.'),
          fill('I think our team ___ the match.',
            'أظنّ أن فريقنا ___ المباراة.',
            'أظنّ أن فريقنا سيفوز بالمباراة.',
            ['will win', 'will wins', 'are going to win', 'won'], 0,
            'بعد I think نعبّر عن توقّع لا دليل عليه، فنستخدم will + المصدر بلا s: will win.'),

          // ---- more practice: build sentences of "Living in Space" with will / won't ----
          build('Someday people will live in space.', 'رتّب الجملة: سيعيش الناس يوماً ما في الفضاء.',
            'توقّع عن المستقبل: will + المصدر (live).'),
          build('Life on the moon will be just the beginning.', 'رتّب الجملة: ستكون الحياة على القمر مجرّد البداية.',
            'will be = سيكون. الفاعل Life on the moon ثم will be ثم الباقي.'),
          build('Instead, they will take a pill three times a day.', 'رتّب الجملة: بدلاً من ذلك، سيتناولون حبّة ثلاث مرات في اليوم.',
            'Instead في أول الجملة تليها فاصلة، ثم الفاعل they ثم will take.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'A paragraph about one’s life in 20 years’ time',
          topicAr: 'اكتب فقرة عن حياتك بعد عشرين سنة (حياتي بعد عشرين عاماً).',
          words: 100,
          plan: [
            { en: 'Start with your age in twenty years’ time and your family (married, children).', ar: 'ابدأ بعمرك بعد عشرين سنة وبأسرتك (متزوّج، أطفال).' },
            { en: 'Say what job you will have and why (because …).', ar: 'اذكر الوظيفة التي ستعمل فيها ولماذا (because …).' },
            { en: 'Describe your house and your free time (but …, so …).', ar: 'صِف بيتك وكيف ستقضي وقت فراغك (but …, so …).' },
            { en: 'End with how technology will make life more comfortable and your hope for the future.', ar: 'اختم بكيف ستجعل التكنولوجيا الحياة أكثر راحة وبأملك في المستقبل.' },
          ],
          phrases: [
            { en: 'In twenty years\' time', ar: 'بعد عشرين عاماً' },
            { en: 'I will be over thirty years old.', ar: 'سيكون عمري أكثر من ثلاثين سنة.' },
            { en: 'I will be married', ar: 'سأكون متزوّجاً' },
            { en: 'I am going to …', ar: 'أنوي أن … (خطة)' },
            { en: 'I think that …', ar: 'أظنّ أن …' },
            { en: 'because', ar: 'لأن' },
            { en: 'but', ar: 'لكن' },
            { en: 'so', ar: 'لذلك' },
            { en: 'a more comfortable life', ar: 'حياة أكثر راحة' },
            { en: 'robots will replace …', ar: 'ستحلّ الروبوتات محلّ …' },
            { en: 'on-line teaching', ar: 'التعليم عبر الإنترنت' },
            { en: 'health will improve', ar: 'ستتحسّن الصحة' },
            { en: 'world peace will spread', ar: 'سينتشر السلام في العالم' },
          ],
          model: 'In twenty years\' time, I will be over thirty years old. I will be married and we will have two children. I am going to study hard at school, so I think I will be a doctor. I want this job because I love helping sick people. We will live in a comfortable house, but it will not be very big. Robots will do the housework, so we will have more time for our children. My children will study at home through on-line teaching. I think health will improve and people will live longer. In the future, we will have a more comfortable life, and I hope world peace will spread everywhere.',
          modelAr: 'بعد عشرين عاماً سيكون عمري أكثر من ثلاثين سنة. سأكون متزوّجاً وسيكون لدينا طفلان. أنوي أن أدرس بجدّ في المدرسة، لذلك أظنّ أنني سأصبح طبيباً. أريد هذه الوظيفة لأنني أحبّ مساعدة المرضى. سنعيش في بيت مريح، لكنه لن يكون كبيراً جداً. ستقوم الروبوتات بالأعمال المنزلية، لذلك سيكون لدينا وقت أكثر لأطفالنا. سيدرس أطفالي في البيت عبر التعليم على الإنترنت. أظنّ أن الصحة ستتحسّن وأن الناس سيعيشون أطول. في المستقبل ستكون حياتنا أكثر راحة، وآمل أن ينتشر السلام في العالم كله.',
          checklistAr: [
            'هل بدأت بجملة تحدّد الزمن: In twenty years\' time …؟',
            'هل استخدمت will للتوقّعات وbe going to للخطط استخداماً صحيحاً، والفعل بعدهما في المصدر؟',
            'هل ربطت الجمل بأدوات الربط التي في الكتاب: and, but, so, because؟',
            'هل تحدّثت عن أسرتك ووظيفتك وبيتك ووقت فراغك؟',
            'هل استخدمت مفردات الوحدة (comfortable, improve, replace, robots, on-line teaching)؟',
            'هل الفقرة في حدود 100 كلمة، وراجعت التهجئة وعلامات الترقيم والحروف الكبيرة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Imagine how your future house will be and write a paragraph about it.',
          topicAr: 'تخيّل كيف سيكون بيتك في المستقبل واكتب فقرة عنه.',
          words: 100,
          points: [
            'The best descriptive paragraphs are full of details: names, dates, physical characteristics and background information.',
            'Collect these details, and then group them into specific categories of information that you can organize as needed.',
          ],
          pointsAr: [
            'أفضل الفقرات الوصفية مليئة بالتفاصيل: الأسماء والتواريخ والصفات الشكلية والمعلومات الخلفية.',
            'اجمع هذه التفاصيل، ثم صنّفها في مجموعات محدّدة من المعلومات تستطيع ترتيبها كما تحتاج.',
          ],
          plan: [
            { en: 'Topic sentence: where and when you are going to have your future house (a name and a date).', ar: 'الجملة الرئيسية: أين ومتى ستملك بيتك المستقبلي (اسم مكان وتاريخ).' },
            { en: 'Physical characteristics: its size, colour, floors, rooms and garden.', ar: 'الصفات الشكلية: حجمه ولونه وطوابقه وغرفه وحديقته.' },
            { en: 'Technology inside the house: robots, computers and on-line teaching.', ar: 'التكنولوجيا داخل البيت: الروبوتات والحواسيب والتعليم عبر الإنترنت.' },
            { en: 'Concluding sentence: how you will feel living in it.', ar: 'الجملة الختامية: بماذا ستشعر وأنت تعيش فيه.' },
          ],
          phrases: [
            { en: 'My future house will be …', ar: 'سيكون بيتي في المستقبل …' },
            { en: 'I am going to build it in …', ar: 'أنوي أن أبنيه في …' },
            { en: 'a more comfortable life', ar: 'حياة أكثر راحة' },
            { en: 'gigantic', ar: 'ضخم، عملاق' },
            { en: 'Robots will do the housework.', ar: 'ستقوم الروبوتات بالأعمال المنزلية.' },
            { en: 'technology will play a very important role', ar: 'ستؤدّي التكنولوجيا دوراً مهماً جداً' },
            { en: 'on-line teaching', ar: 'التعليم عبر الإنترنت' },
            { en: 'grow crops on the roof', ar: 'يزرع محاصيل على السطح' },
            { en: 'I think that …', ar: 'أظنّ أن …' },
            { en: 'but', ar: 'لكن' },
            { en: 'so', ar: 'لذلك' },
            { en: 'because', ar: 'لأن' },
          ],
          model: 'I think my future house will give my family a more comfortable life. I am going to build it in 2045 in a quiet village near Homs, because my grandparents lived there. It will be a white house with two floors, five rooms and a big garden. I will grow vegetables on the roof, so we will always have fresh food. Technology will play a very important role in the house. Robots will do the housework, and a computer will control the lights and the doors. My children will study at home through on-line teaching. The house will not be gigantic, but it will be warm and happy.',
          modelAr: 'أظنّ أن بيتي في المستقبل سيمنح أسرتي حياة أكثر راحة. أنوي أن أبنيه عام 2045 في قرية هادئة قرب حمص، لأن جدّي وجدّتي عاشا هناك. سيكون بيتاً أبيض من طابقين، فيه خمس غرف وحديقة كبيرة. سأزرع الخضار على السطح، لذلك سيكون لدينا دائماً طعام طازج. ستؤدّي التكنولوجيا دوراً مهماً جداً في البيت؛ فالروبوتات ستقوم بالأعمال المنزلية، وحاسوب سيتحكّم بالأضواء والأبواب. وسيدرس أطفالي في البيت عبر التعليم على الإنترنت. لن يكون البيت ضخماً، لكنه سيكون دافئاً وسعيداً.',
          checklistAr: [
            'هل في الفقرة تفاصيل كما يطلب الكتاب: اسم مكان وتاريخ وصفات شكلية ومعلومات خلفية؟',
            'هل رتّبت التفاصيل في مجموعات: المكان والزمان، ثم شكل البيت، ثم ما في داخله؟',
            'هل استخدمت will وbe going to استخداماً صحيحاً والفعل بعدهما في المصدر؟',
            'هل استخدمت أدوات الربط (and, but, so, because)؟',
            'هل استخدمت مفردات الوحدة (comfortable, gigantic, robots, technology)؟',
            'هل الفقرة في حدود 100 كلمة، وراجعت التهجئة والقواعد وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'Someday people will live in space.', ar: 'سيعيش الناس يوماً ما في الفضاء.' },
        { en: "Inside it, people won't live differently from small towns on the Earth.", ar: 'في داخلها لن يعيش الناس بطريقة مختلفة عن البلدات الصغيرة على الأرض.' },
        { en: 'Scientists also believe that they will obtain water from a large ice lake on the moon.', ar: 'ويعتقد العلماء أيضاً أنهم سيحصلون على الماء من بحيرة جليدية كبيرة على القمر.' },
        { en: "People won't have to do housework because robots will do that for them.", ar: 'لن يضطرّ الناس إلى القيام بالأعمال المنزلية لأن الروبوتات ستقوم بها عنهم.' },
        { en: "Food won't be a problem, as settlers won't need to eat.", ar: 'لن يكون الطعام مشكلة، إذ لن يحتاج المستوطنون إلى الأكل.' },
        { en: 'Instead, they will take a pill three times a day.', ar: 'بدلاً من ذلك، سيتناولون حبّة ثلاث مرات في اليوم.' },
        { en: 'Life on the moon will be just the beginning.', ar: 'ستكون الحياة على القمر مجرّد البداية.' },
        { en: 'Our goal is to establish a new research centre in our city.', ar: 'هدفنا أن نؤسّس مركز أبحاث جديداً في مدينتنا.' },
        { en: 'Life in the future will be very different.', ar: 'ستكون الحياة في المستقبل مختلفة جداً.' },
        { en: 'I think that in the future we will have a more comfortable life.', ar: 'أظنّ أننا سنحظى في المستقبل بحياة أكثر راحة.' },
        { en: 'This will be obvious in all aspects of life.', ar: 'وسيكون هذا واضحاً في جميع جوانب الحياة.' },
        { en: 'First, as for education, people will have better education because of technology.', ar: 'أولاً، بالنسبة إلى التعليم، سيحصل الناس على تعليم أفضل بفضل التكنولوجيا.' },
        { en: 'New medicines will help people get better.', ar: 'ستساعد الأدوية الجديدة الناس على الشفاء.' },
        { en: 'Robots will help doctors and sometimes replace them.', ar: 'ستساعد الروبوتات الأطباء وأحياناً ستحلّ محلّهم.' },
        { en: 'People will grow new types of crops everywhere even on the roofs of buildings.', ar: 'سيزرع الناس أنواعاً جديدة من المحاصيل في كل مكان، حتى على أسطح المباني.' },
        { en: 'The world will have nothing to fight for.', ar: 'لن يكون لدى العالم شيء يتقاتل من أجله.' },
      ],
    },

    // ===================== UNIT 4 — Transport and Tourism (Activity Book pages 14–18) =====================
    u4: {
      workbook: {
        pages: '14–18',
        readings: [
          {
            title: 'Ecological Cities',
            paragraphs: [
              'When we think about the future, we tend to assume that most things will stay the same. This is almost never the case. We are experiencing a technological progress every month now.',
              'The world is changing and the changes are very dramatic. Imagining future cities with modern technology appears as a dynamic solution to society’s recent problems.',
              'Some recent researches have suggested that we need to think about the way we imagine future cities, and to focus on some forms of alternative energy such as solar power, wind power, and water power which lead to environmental sustainability.',
              'We need to answer questions about what can be sustained and what cannot, where cities can be located and where they cannot, and how we might travel in and between them and how we can physically live and work together.',
              'We may want our future cities to prioritize environmental renewal. We need to prevent environmental degradation and stop the expansion of deserts. Future cities can collect water and use solar power to irrigate the dry land. Future cities should be surrounded by rivers and provided with renewable energy resources and green vehicles heading towards more ecological forms of public transport.',
              "Imagining these cities helps us understand how we want our future lives and tomorrow's world to look like. It will be better to rethink about our health, other species and the planet we share.",
            ],
            paragraphsAr: [
              'عندما نفكّر في المستقبل نميل إلى الافتراض أن معظم الأشياء ستبقى على حالها. وهذا لا يحدث تقريباً أبداً. فنحن نشهد تقدّماً تكنولوجياً كل شهر الآن.',
              'العالم يتغيّر، والتغيّرات كبيرة ومفاجئة جداً. ويبدو تخيّل مدن المستقبل بالتكنولوجيا الحديثة حلاً متجدّداً (ديناميكياً) لمشكلات المجتمع الحديثة.',
              'اقترحت بعض الأبحاث الحديثة أننا بحاجة إلى التفكير في الطريقة التي نتخيّل بها مدن المستقبل، والتركيز على بعض أشكال الطاقة البديلة مثل الطاقة الشمسية وطاقة الرياح وطاقة المياه، التي تؤدّي إلى الاستدامة البيئية.',
              'نحن بحاجة إلى الإجابة عن أسئلة حول ما يمكن أن يستمرّ وما لا يمكن، وأين يمكن أن تُقام المدن وأين لا يمكن، وكيف يمكن أن نتنقّل داخلها وبينها، وكيف يمكننا أن نعيش ونعمل معاً فعلياً.',
              'قد نريد لمدننا المستقبلية أن تعطي الأولوية لتجديد البيئة. نحن بحاجة إلى منع تدهور البيئة وإيقاف زحف الصحارى. تستطيع مدن المستقبل أن تجمع المياه وتستخدم الطاقة الشمسية لريّ الأراضي الجافة. وينبغي أن تحيط الأنهار بمدن المستقبل، وأن تُزوَّد بمصادر طاقة متجدّدة ومركبات صديقة للبيئة تتّجه نحو أشكال أكثر مراعاةً للبيئة من النقل العام.',
              'إن تخيّل هذه المدن يساعدنا على فهم الشكل الذي نريده لحياتنا المستقبلية ولعالم الغد. وسيكون من الأفضل أن نعيد التفكير في صحتنا وفي الكائنات الأخرى وفي الكوكب الذي نتشاركه.',
            ],
            questions: [
              {
                q: 'How often are we experiencing a technological progress now?', qAr: 'كم مرة نشهد تقدّماً تكنولوجياً الآن؟',
                options: ['Every month.', 'Every year.', 'Every ten years.', 'Almost never.'],
                answer: 0,
                explainAr: 'يقول النص: "We are experiencing a technological progress every month now." أي كل شهر. أما almost never فجاءت في جملة أخرى عن افتراض أن الأشياء ستبقى كما هي.',
              },
              {
                q: 'Name some of the alternative powers.', qAr: 'اذكر بعض أنواع الطاقة البديلة.',
                options: ['Solar power, wind power and water power.', 'Petrol, gas and coal.', 'Rockets, cars and planes.', 'Rivers, deserts and dry land.'],
                answer: 0,
                explainAr: 'يقول النص: "some forms of alternative energy such as solar power, wind power, and water power" أي الطاقة الشمسية وطاقة الرياح وطاقة المياه.',
              },
              {
                q: 'What do future cities use to irrigate the dry land?', qAr: 'ماذا تستخدم مدن المستقبل لريّ الأرض الجافة؟',
                options: ['They collect water and use solar power.', 'They use petrol and gas.', 'They bring water from the moon.', 'They use green vehicles.'],
                answer: 0,
                explainAr: 'يقول النص: "Future cities can collect water and use solar power to irrigate the dry land." أي تجمع المياه وتستخدم الطاقة الشمسية. (irrigate = يروي الأرض).',
              },
              {
                q: 'Mention two ecological forms of transport.', qAr: 'اذكر شكلين من أشكال النقل الصديقة للبيئة.',
                options: ['Green vehicles and public transport.', 'Private cars and trucks.', 'Rockets and space stations.', 'Taxis and delivery vans.'],
                answer: 0,
                explainAr: 'يذكر النص "green vehicles heading towards more ecological forms of public transport" أي المركبات الخضراء (الصديقة للبيئة) والنقل العام. (ecological = يهتمّ بالحفاظ على البيئة).',
              },
              {
                q: 'How can we prevent environmental degradation?', qAr: 'كيف يمكننا منع تدهور البيئة؟',
                options: [
                  'By stopping the expansion of deserts and using renewable energy such as solar power.',
                  'By building more factories in the desert.',
                  'By using more cars and fewer buses.',
                  'By assuming that most things will stay the same.',
                ],
                answer: 0,
                explainAr: 'هذا سؤال رأي في الكتاب، والجواب المدعوم بالنص: "We need to prevent environmental degradation and stop the expansion of deserts" مع استخدام الطاقة المتجدّدة كالطاقة الشمسية لريّ الأرض الجافة. (degradation = تدهور).',
              },
              {
                q: 'What should future cities be surrounded by?', qAr: 'بماذا ينبغي أن تُحاط مدن المستقبل؟',
                options: ['Rivers.', 'Deserts.', 'Factories.', 'Walls.'],
                answer: 0,
                explainAr: 'يقول النص: "Future cities should be surrounded by rivers" أي تحيط بها الأنهار.',
              },
            ],
          },
        ],
        exercises: [
          // ---- page 15: Key Words ----
          matchItem('ecological', u4Meanings, 0, [2, 6, 8], 'ecological = بيئي، صديق للبيئة: مهتمّ بالحفاظ على البيئة، كما في عنوان النص "Ecological Cities".'),
          matchItem('assume', u4Meanings, 1, [3, 5, 9], 'assume = يفترض: أن تظنّ أن شيئاً ما صحيح، كما في النص: "we tend to assume that most things will stay the same".'),
          matchItem('progress', u4Meanings, 2, [4, 7, 8], 'progress = تقدّم: عملية التحسّن في فعل شيء ما، كما في: "a technological progress every month".'),
          matchItem('dramatic', u4Meanings, 3, [0, 4, 6], 'dramatic = كبير ومفاجئ (great and sudden)، كما في: "the changes are very dramatic".'),
          matchItem('dynamic', u4Meanings, 4, [1, 3, 7], 'dynamic = ديناميكي، متجدّد: يتحرّك أو يتغيّر باستمرار، كما في: "a dynamic solution".'),
          matchItem('prioritize', u4Meanings, 5, [1, 6, 9], 'prioritize = يعطي الأولوية: يعامل شيئاً على أنه أهمّ من غيره، كما في: "to prioritize environmental renewal".'),
          matchItem('sustainability', u4Meanings, 6, [2, 7, 8], 'sustainability = الاستدامة: القدرة على الاستمرار من دون إحداث ضرر، كما في: "environmental sustainability".'),
          matchItem('renewal', u4Meanings, 7, [2, 6, 8], 'renewal = تجديد: عندما يبدأ نشاط أو عملية من جديد، كما في: "environmental renewal".'),
          matchItem('degradation', u4Meanings, 8, [2, 6, 7], 'degradation = تدهور: عملية تغيّر الشيء إلى حال أسوأ، كما في: "prevent environmental degradation".'),
          matchItem('irrigate', u4Meanings, 9, [0, 1, 5], 'irrigate = يروي: يزوّد الأرض أو المحاصيل بالماء، كما في: "use solar power to irrigate the dry land".'),

          // ---- page 15 B: match the beginnings in column A with the ends in column B ----
          matchEnd('We tend to assume that', 'نميل إلى الافتراض أنّ', 2, [0, 3, 5],
            'الجملة في النص: "We tend to assume that most things will stay the same." بعد that نحتاج جملة كاملة لها فاعل وفعل: most things will stay the same.'),
          matchEnd('The world is changing and the changes', 'العالم يتغيّر والتغيّرات', 5, [0, 1, 4],
            'بعد الفاعل the changes نحتاج فعلاً: are very dramatic (كبيرة ومفاجئة جداً)، كما في النص.'),
          matchEnd('Modern technology appears as', 'تبدو التكنولوجيا الحديثة', 0, [2, 3, 5],
            'appears as تحتاج بعدها اسماً: a dynamic solution to society\'s recent problems (حلاً متجدّداً لمشكلات المجتمع الحديثة).'),
          matchEnd('We may want our future cities', 'قد نريد لمدننا المستقبلية', 4, [1, 3, 5],
            'بعد want + مفعول به يأتي to + المصدر: want our future cities to prioritize environmental renewal (أن تعطي الأولوية لتجديد البيئة).'),
          matchEnd('Future cities should be', 'ينبغي أن تكون مدن المستقبل', 1, [0, 4, 5],
            'should be + اسم مفعول: should be surrounded by rivers (محاطة بالأنهار)، كما في النص.'),
          matchEnd('It will be better', 'سيكون من الأفضل', 3, [0, 2, 4],
            'It will be better + to + المصدر: It will be better to rethink of our health (أن نعيد التفكير في صحتنا).'),

          // ---- page 15 Vocabulary: select the correct words in brackets ----
          fill('I didn’t see your bike, so I ___ you had gone out.',
            'لم أرَ درّاجتك، لذلك ___ أنك خرجت.',
            'لم أرَ درّاجتك، لذلك افترضت أنك خرجت.',
            ['assumption', 'assumed', 'assuming'], 1,
            'بعد الفاعل I نحتاج فعلاً، والجملة في الماضي (didn’t see) فنستخدم الماضي: assumed (افترضتُ). assumption اسم (افتراض).'),
          fill('The two cars are very ___ in size and design.',
            'السيارتان ___ جداً في الحجم والتصميم.',
            'السيارتان متشابهتان جداً في الحجم والتصميم.',
            ['similar', 'similarly', 'similarity'], 0,
            'بعد are very نحتاج صفة: similar (متشابه). similarly ظرف، وsimilarity اسم (تشابه).'),
          fill('John lived a life of ___ after he lost his fortune.',
            'عاش جون حياة ___ بعد أن خسر ثروته.',
            'عاش جون حياة تدهور وانحطاط بعد أن خسر ثروته.',
            ['degrade', 'degradation', 'degraded'], 1,
            'بعد حرف الجر of نحتاج اسماً: degradation (تدهور). degrade فعل.'),
          fill('The solar power is a ___ energy.',
            'الطاقة الشمسية طاقة ___.',
            'الطاقة الشمسية طاقة متجدّدة.',
            ['renew', 'renewable', 'renewal'], 1,
            'بين a والاسم energy نحتاج صفة: renewable (متجدّدة). renew فعل، وrenewal اسم (تجديد).'),
          fill('Cycling is a totally ___ form of transport.',
            'ركوب الدرّاجة شكل ___ تماماً من أشكال النقل.',
            'ركوب الدرّاجة شكل مستدام تماماً من أشكال النقل.',
            ['sustain', 'sustainable', 'sustainability'], 1,
            'قبل الاسم form نحتاج صفة: sustainable (مستدام، لا يضرّ بالبيئة). sustain فعل، وsustainability اسم (استدامة).'),

          // ---- page 17 Grammar A: select the correct determiners ----
          fill('Does anyone know ___ answer?',
            'هل يعرف أحدٌ ___ جواب؟',
            'هل يعرف أحدٌ الجواب؟',
            ['an', 'the', 'a'], 1,
            'نقصد جواباً محدّداً عن سؤال معروف، فنستخدم أداة التعريف the. لا تنخدع بأن answer تبدأ بحرف علّة؛ an تعني «جواباً ما» غير محدّد.'),
          fill('I haven’t got pictures in ___ bedroom.',
            'ليس لديّ صور في ___ نومي.',
            'ليس لديّ صور في غرفة نومي.',
            ['a', 'my', 'an'], 1,
            'نتحدّث عن غرفتي أنا، فنستخدم صفة الملكية my (تدلّ على الملكية). a تعني «غرفة ما» ولا تناسب المعنى.'),
          fill('I have told you to pay attention ___ times before.',
            'لقد قلتُ لك أن تنتبه ___ من قبل.',
            'لقد قلتُ لك أن تنتبه مرات كثيرة من قبل.',
            ['any', 'many', 'much'], 1,
            'times اسم معدود جمع، والجملة مثبتة، فنستخدم many (كثير للمعدود). any للنفي والسؤال، وmuch لغير المعدود.'),
          fill('I have only ___ coins in my wallet.',
            'لديّ فقط ___ من القطع النقدية في محفظتي.',
            'لديّ فقط بضع قطع نقدية في محفظتي.',
            ['a little', 'a few', 'much'], 1,
            'coins اسم معدود جمع، فنستخدم a few (قليل من المعدود). a little لغير المعدود. ومثال الكتاب: "I have only a few coins in my pocket."'),
          fill('There aren’t ___ students in the library.',
            'لا يوجد ___ طلاب في المكتبة.',
            'لا يوجد أيّ طلاب في المكتبة.',
            ['some', 'any', 'a'], 1,
            'الجملة منفية (aren’t)، ومع النفي والسؤال نستخدم any، أما some فللجمل المثبتة.'),
          fill('There is ___ milk left in the fridge.',
            'بقي ___ من الحليب في البرّاد.',
            'بقي قليل من الحليب في البرّاد.',
            ['a few', 'a little', 'many'], 1,
            'milk اسم غير معدود، فنستخدم a little (قليل من غير المعدود). a few وmany للمعدود فقط.'),

          // ---- page 17 Grammar B: complete with appropriate determiners (more than one answer can be correct) ----
          fill('___ people drive cars nowadays.',
            '___ الناس يقودون السيارات في هذه الأيام.',
            'كثير من الناس يقودون السيارات في هذه الأيام.',
            ['Much', 'Many', 'An', 'A little'], 1,
            'people اسم معدود جمع، فنستخدم Many (ويصحّ أيضاً A lot of أو Some). Much وA little لغير المعدود، وAn للمفرد فقط.'),
          fill('Sami likes to eat ___ food before he sits down to study.',
            'يحبّ سامي أن يأكل ___ الطعام قبل أن يجلس ليدرس.',
            'يحبّ سامي أن يأكل بعض الطعام قبل أن يجلس ليدرس.',
            ['some', 'many', 'a few', 'an'], 0,
            'food اسم غير معدود والجملة مثبتة، فنستخدم some (ويصحّ أيضاً a little). many وa few للمعدود فقط، وan للمفرد المعدود.'),
          fill('___ children will hurt themselves if they don’t get off that tree!',
            '___ الأطفال سيؤذون أنفسهم إن لم ينزلوا عن تلك الشجرة!',
            'أولئك الأطفال سيؤذون أنفسهم إن لم ينزلوا عن تلك الشجرة!',
            ['That', 'Those', 'This', 'A'], 1,
            'children جمع، والأطفال بعيدون عنّا (على تلك الشجرة that tree)، فنستخدم اسم الإشارة للجمع البعيد Those (ويصحّ أيضاً The أو These). That وThis للمفرد، وA للمفرد.'),
          fill('The doctor advised me to eat ___ apple every morning.',
            'نصحني الطبيب أن آكل ___ تفاحة كل صباح.',
            'نصحني الطبيب أن آكل تفاحة كل صباح.',
            ['a', 'an', 'some', 'many'], 1,
            'apple اسم مفرد معدود يبدأ بصوت حرف علّة (a)، فنستخدم an لا a. ومثال الكتاب: "an apple, an egg".'),
          fill('She got her license without ___ problems.',
            'حصلت على رخصتها من دون ___ مشكلات.',
            'حصلت على رخصتها من دون أيّ مشكلات.',
            ['any', 'much', 'a little', 'an'], 0,
            'without تعطي معنى النفي، ومع النفي نستخدم any. much وa little لغير المعدود، وproblems اسم معدود جمع، وan للمفرد.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: "A paragraph about one's dream means of transport",
          topicAr: 'اكتب فقرة عن وسيلة النقل التي تحلم بها.',
          words: 100,
          plan: [
            { en: 'Topic sentence: name your dream means of transport.', ar: 'الجملة الرئيسية: سمِّ وسيلة النقل التي تحلم بها.' },
            { en: 'Describe it: what it looks like and how it works.', ar: 'صِفها: شكلها وكيف تعمل.' },
            { en: 'Its benefits: safer, more efficient, cleaner.', ar: 'فوائدها: أكثر أماناً وكفاءة ونظافة.' },
            { en: 'Concluding sentence: how it will change our lives in the future.', ar: 'الجملة الختامية: كيف ستغيّر حياتنا في المستقبل.' },
          ],
          phrases: [
            { en: 'My dream means of transport is …', ar: 'وسيلة النقل التي أحلم بها هي …' },
            { en: 'a driverless car', ar: 'سيارة بلا سائق' },
            { en: 'autonomous vehicles', ar: 'المركبات ذاتية القيادة' },
            { en: 'safer', ar: 'أكثر أماناً' },
            { en: 'efficient', ar: 'فعّال، يعمل جيداً دون إضاعة الوقت أو الطاقة' },
            { en: 'change our lives for the better', ar: 'يغيّر حياتنا نحو الأفضل' },
            { en: 'benefit', ar: 'يفيد' },
            { en: 'renewable energy', ar: 'الطاقة المتجدّدة' },
            { en: 'many people', ar: 'كثير من الناس' },
            { en: 'much time', ar: 'وقت كثير' },
            { en: 'I think …', ar: 'أظنّ …' },
            { en: 'First, … Second, … Finally, …', ar: 'أولاً… ثانياً… وأخيراً…' },
          ],
          model: 'My dream means of transport is a small driverless car. It will look like a normal car, but it will not need a driver. First, I will tell the car where I want to go, and it will take me there safely. I will read a book or do some homework during the journey. Second, the car will use renewable energy, so it will not pollute the air. It will be very efficient and it will not waste much time or energy. Finally, it will be safer than the cars we have now. I think many people will have this car, and it will change our lives for the better.',
          modelAr: 'وسيلة النقل التي أحلم بها سيارة صغيرة بلا سائق. ستبدو مثل سيارة عادية، لكنها لن تحتاج إلى سائق. أولاً، سأخبر السيارة إلى أين أريد أن أذهب، وستأخذني إلى هناك بأمان. سأقرأ كتاباً أو أكتب بعض الوظائف خلال الرحلة. ثانياً، ستستخدم السيارة طاقة متجدّدة، لذلك لن تلوّث الهواء. ستكون فعّالة جداً ولن تهدر كثيراً من الوقت أو الطاقة. وأخيراً، ستكون أكثر أماناً من السيارات التي لدينا الآن. أظنّ أن كثيراً من الناس سيملكون هذه السيارة، وأنها ستغيّر حياتنا نحو الأفضل.',
          checklistAr: [
            'هل سمّيت وسيلة النقل في الجملة الأولى؟',
            'هل وصفتها وذكرت فائدتين على الأقل؟',
            'هل رتّبت أفكارك بـ First, Second, Finally؟',
            'هل استخدمت أدوات التعريف والتنكير والكمّيات صحيحاً (a/an, the, this, many, much, some)؟',
            'هل استخدمت مفردات الوحدة (driverless, efficient, safer, benefit, renewable)؟',
            'هل الفقرة في حدود 100 كلمة، وراجعت التهجئة والقواعد وعلامات الترقيم؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write a short paragraph about the planes of the future. Include both facts and opinions about this means of transport.',
          topicAr: 'اكتب فقرة قصيرة عن طائرات المستقبل. ضمّنها حقائق وآراء عن وسيلة النقل هذه.',
          words: 100,
          points: ['Facts about planes', 'Opinions about the planes of the future'],
          pointsAr: ['حقائق عن الطائرات', 'آراء عن طائرات المستقبل'],
          plan: [
            { en: 'Topic sentence: planes and why they matter for transport and tourism.', ar: 'الجملة الرئيسية: الطائرات وأهميتها للنقل والسياحة.' },
            { en: 'Facts: what we know about planes today (speed, fuel, pollution).', ar: 'الحقائق: ما نعرفه عن الطائرات اليوم (السرعة، الوقود، التلوّث).' },
            { en: 'Opinions: what you think the planes of the future will be like (I think…, In my opinion…).', ar: 'الآراء: كيف تظنّ أن طائرات المستقبل ستكون (I think…, In my opinion…).' },
            { en: 'Concluding sentence: how these planes will change travelling.', ar: 'الجملة الختامية: كيف ستغيّر هذه الطائرات السفر.' },
          ],
          phrases: [
            { en: 'means of transport', ar: 'وسيلة نقل' },
            { en: 'tourism', ar: 'السياحة' },
            { en: 'a lot of fuel', ar: 'كثير من الوقود' },
            { en: 'In my opinion, …', ar: 'في رأيي …' },
            { en: 'I think …', ar: 'أظنّ …' },
            { en: 'solar power', ar: 'الطاقة الشمسية' },
            { en: 'renewable energy', ar: 'الطاقة المتجدّدة' },
            { en: 'ecological', ar: 'صديق للبيئة' },
            { en: 'efficient', ar: 'فعّال' },
            { en: 'dramatic changes', ar: 'تغيّرات كبيرة ومفاجئة' },
            { en: 'technological progress', ar: 'التقدّم التكنولوجي' },
            { en: 'However, …', ar: 'ومع ذلك …' },
          ],
          model: 'Planes are the fastest means of transport today. Every day, many people travel by plane for work and tourism. However, planes use a lot of fuel, and they cause pollution. In my opinion, the planes of the future will be very different because we are experiencing a technological progress every month. I think they will use solar power and other renewable energy, so they will be more ecological. I believe they will also be quieter, cheaper and more efficient. Some planes may even fly without pilots. These will be dramatic changes, but I think they will make travelling safer and more comfortable.',
          modelAr: 'الطائرات هي أسرع وسيلة نقل اليوم. ففي كل يوم يسافر كثير من الناس بالطائرة للعمل والسياحة. ومع ذلك، تستهلك الطائرات كثيراً من الوقود وتسبّب التلوّث. في رأيي، ستكون طائرات المستقبل مختلفة جداً لأننا نشهد تقدّماً تكنولوجياً كل شهر. أظنّ أنها ستستخدم الطاقة الشمسية وأنواعاً أخرى من الطاقة المتجدّدة، لذلك ستكون أكثر مراعاةً للبيئة. وأعتقد أنها ستكون أيضاً أهدأ وأرخص وأكثر كفاءة. وقد تطير بعض الطائرات حتى من دون طيّارين. ستكون هذه تغيّرات كبيرة، لكنني أظنّ أنها ستجعل السفر أكثر أماناً وراحة.',
          checklistAr: [
            'هل كتبت حقائق (أشياء صحيحة يعرفها الجميع) بالمضارع البسيط، مثل: Planes use a lot of fuel؟',
            'هل كتبت آراء واضحة تبدأ بـ In my opinion أو I think أو I believe، مع will للمستقبل؟',
            'هل استخدمت مفردات الوحدة (renewable, ecological, efficient, dramatic, progress)؟',
            'هل استخدمت أدوات التعريف والكمّيات صحيحاً (a, the, many, a lot of, some, these)؟',
            'بعد الكتابة كما ينصح الكتاب: هل قرأت الفقرة مرة أخرى؟',
            'هل راجعت التهجئة والقواعد والمفردات وعلامات الترقيم والحروف الكبيرة، وصحّحت الأخطاء؟',
          ],
        },
      ],
      translations: [
        { en: 'This is almost never the case.', ar: 'وهذا لا يحدث تقريباً أبداً.' },
        { en: 'We are experiencing a technological progress every month now.', ar: 'نحن نشهد تقدّماً تكنولوجياً كل شهر الآن.' },
        { en: 'The world is changing and the changes are very dramatic.', ar: 'العالم يتغيّر، والتغيّرات كبيرة ومفاجئة جداً.' },
        { en: 'Imagining future cities with modern technology appears as a dynamic solution to society’s recent problems.', ar: 'يبدو تخيّل مدن المستقبل بالتكنولوجيا الحديثة حلاً متجدّداً لمشكلات المجتمع الحديثة.' },
        { en: 'We may want our future cities to prioritize environmental renewal.', ar: 'قد نريد لمدننا المستقبلية أن تعطي الأولوية لتجديد البيئة.' },
        { en: 'We need to prevent environmental degradation and stop the expansion of deserts.', ar: 'نحن بحاجة إلى منع تدهور البيئة وإيقاف زحف الصحارى.' },
        { en: 'Future cities can collect water and use solar power to irrigate the dry land.', ar: 'تستطيع مدن المستقبل أن تجمع المياه وتستخدم الطاقة الشمسية لريّ الأرض الجافة.' },
        { en: 'It will be better to rethink about our health, other species and the planet we share.', ar: 'سيكون من الأفضل أن نعيد التفكير في صحتنا وفي الكائنات الأخرى وفي الكوكب الذي نتشاركه.' },
        { en: 'The solar power is a renewable energy.', ar: 'الطاقة الشمسية طاقة متجدّدة.' },
        { en: 'Cycling is a totally sustainable form of transport.', ar: 'ركوب الدرّاجة شكل مستدام تماماً من أشكال النقل.' },
        { en: 'They think that they will be safer and transportation will be more efficient.', ar: 'يعتقدون أنها ستكون أكثر أماناً وأن النقل سيكون أكثر كفاءة.' },
        { en: 'First, driverless cars will increase unemployment.', ar: 'أولاً، ستزيد السيارات ذاتية القيادة البطالة.' },
        { en: 'This increase in unemployment could cause serious social problems.', ar: 'قد تسبّب هذه الزيادة في البطالة مشكلات اجتماعية خطيرة.' },
        { en: 'Second, companies and governments will lose money.', ar: 'ثانياً، ستخسر الشركات والحكومات أموالاً.' },
        { en: 'Dramatic change is coming, but governments haven’t begun thinking about it.', ar: 'هناك تغيّر كبير قادم، لكن الحكومات لم تبدأ التفكير فيه.' },
        { en: 'Only some American cities have done long-term planning.', ar: 'بعض المدن الأمريكية فقط قامت بتخطيط طويل الأمد.' },
      ],
    },
  },
}
