import type { ModuleExtras } from './merge'
import type { GrammarExercise } from '../../../engine/types'

// Activity Book, Module 6 "Keep in Touch": Unit 11 (pages 51–55), Unit 12 (pages 56–60),
// Progress Test (II) (pages 61–64). Every item the pages print, solved, in the book's order.
// Left out: the Listening tasks (they need the recording) and the open Speaking questions.

const fill = (prompt: string, options: string[], answer: number, promptAr: string, promptArFull: string, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, options, answer, promptAr, promptArFull, explainAr })
const mcq = (prompt: string, options: string[], answer: number, promptAr: string, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, options, answer, promptAr, explainAr })
const build = (answer: string, prompt: string, explainAr: string): GrammarExercise =>
  ({ type: 'build', answer, prompt, explainAr })

// ---------------------------------------------------------------- Unit 11: Ready to Contact? (Activity Book 51–55)

const u11Exercises: GrammarExercise[] = [
  // Reading A — the four statements are all false: choose the correction the text gives
  mcq('Correct the false statement: “Scientists first adopted the idea of the existence of life on other planets.”', [
    'The Media was captured by the idea of communicating with Mars, but it did not find much serious interest from scientists.',
    'Scientists were the first to prove that there is life on Mars.',
    'Scientists adopted the idea before the newspapers heard about it.',
    'Nobody was interested in the idea of life on other planets.',
  ], 0,
    'صحّح العبارة الخاطئة: «العلماء هم أول من تبنّى فكرة وجود حياة على كواكب أخرى.»',
    'العبارة خاطئة. النص يقول إن وسائل الإعلام هي التي انشغلت بالفكرة: The Media was captured by the idea of communicating with Mars but it did not find much serious interest from scientists. أي أن العلماء لم يهتمّوا بها اهتماماً جدّياً في البداية.'),
  mcq('Correct the false statement: “Inventing the Wireless made the idea of connecting the world unreasonable.”', [
    'Inventing the Wireless stopped people from searching for signals.',
    'The idea of wirelessly sending and receiving waves through the air was developed, and new methods of searching for communications from space were offered.',
    'The Wireless was invented only in the 1960s.',
    'The Wireless made it impossible to send messages through the air.',
  ], 1,
    'صحّح العبارة الخاطئة: «اختراع اللاسلكي جعل فكرة ربط العالم غير منطقية.»',
    'العبارة خاطئة. النص يقول إن فكرة إرسال الموجات واستقبالها لاسلكياً تطوّرت، وطُرحت طرق جديدة للبحث عن اتصالات من الفضاء: the idea of wirelessly sending and receiving waves through the air, was developed. New methods ... were offered too.'),
  mcq('Correct the false statement: “Tesla claimed that he received messages from the sun.”', [
    'Tesla claimed that he was sending messages to the sun.',
    'Tesla claimed that he was receiving radio communications from the moon.',
    'Tesla claimed that he was receiving radio communications from Mars.',
    'Tesla claimed that nobody could receive messages from space.',
  ], 2,
    'صحّح العبارة الخاطئة: «ادّعى تسلا أنه استقبل رسائل من الشمس.»',
    'العبارة خاطئة: الرسائل لم تكن من الشمس بل من المريخ. النص: In 1901, engineer Nicola Tesla made the astonishing claim that he was receiving radio communications from Mars.'),
  mcq('Correct the false statement: “After many experiments, it was proved that there might be life on other planets.”', [
    'It was proved that there is intelligent life in the solar system.',
    'Scientists proved that there were civilizations on Mars in 1901.',
    'Many experiments proved that there are people trying to contact us.',
    'Radio signals were detected to look for life or civilizations out in the galaxy, but none was proved.',
  ], 3,
    'صحّح العبارة الخاطئة: «بعد تجارب كثيرة، ثبت أنه قد تكون هناك حياة على كواكب أخرى.»',
    'العبارة خاطئة: لم يثبت شيء. النص: Radio signals were detected to look for life or civilizations out in the galaxy but none was proved. (none was proved = لم يثبت أيٌّ منها).'),

  // Vocabulary — the opposites of the words, found in the reading text
  fill('The opposite of “familiar” in the text is ___.', ['strange', 'known', 'clear', 'serious'], 0,
    'عكس كلمة familiar (مألوف) في النص هو ___.',
    'عكس كلمة familiar (مألوف) في النص هو strange (غريب).',
    'familiar = مألوف، وعكسها strange = غريب. في النص: as many strange ways to communicate.'),
  fill('The opposite of “impossible” in the text is ___.', ['unpossible', 'possible', 'clear', 'early'], 1,
    'عكس كلمة impossible (مستحيل) في النص هو ___.',
    'عكس كلمة impossible (مستحيل) في النص هو possible (ممكن).',
    'نحذف البادئة im- فتصبح possible = ممكن. في النص: it became possible to detect signals. انتبه: كلمة unpossible غير موجودة.'),
  fill('The opposite of “late” in the text is ___.', ['early', 'later', 'farther', 'strange'], 0,
    'عكس كلمة late (متأخّر) في النص هو ___.',
    'عكس كلمة late (متأخّر) في النص هو early (مبكر / أوائل).',
    'late = متأخّر / أواخر، وعكسها early = مبكر / أوائل. في النص: In the late 19th and early 20th centuries (أواخر القرن التاسع عشر وأوائل القرن العشرين).'),
  fill('The opposite of “silly” in the text is ___.', ['possible', 'strange', 'serious', 'astonishing'], 2,
    'عكس كلمة silly (سخيف) في النص هو ___.',
    'عكس كلمة silly (سخيف) في النص هو serious (جادّ).',
    'silly = سخيف / غير جادّ، وعكسها serious = جادّ. في النص: it did not find much serious interest from scientists.'),
  fill('The opposite of “ambiguous” in the text is ___.', ['strange', 'clear', 'early', 'serious'], 1,
    'عكس كلمة ambiguous (غامض) في النص هو ___.',
    'عكس كلمة ambiguous (غامض) في النص هو clear (واضح).',
    'ambiguous = غامض، وعكسها clear = واضح. في النص: As it became increasingly clear that there was no intelligent life.'),
  fill('The opposite of “nearer” in the text is ___.', ['closer', 'early', 'farther', 'later'], 2,
    'عكس كلمة nearer (أقرب) في النص هو ___.',
    'عكس كلمة nearer (أقرب) في النص هو farther (أبعد).',
    'nearer = أقرب (صيغة مقارنة)، وعكسها farther = أبعد (صيغة مقارنة أيضاً). في النص: signals from much farther away.'),

  // Grammar A — complete the passive sentences with the expressions in the box
  fill('A lot of coffee ___.', ['is grown in Brazil', 'are made in Japan', 'are found in the Himalayas', 'was given'], 0,
    'الكثير من البنّ ___.',
    'الكثير من البنّ يُزرع في البرازيل.',
    'coffee اسم غير معدود (مفرد) فنستخدم is + التصريف الثالث grown: is grown = يُزرَع. وهي حقيقة عامة لذلك نستخدم المضارع البسيط المبني للمجهول (am/is/are + V3).'),
  fill('The world\'s highest mountains ___.', ['is grown in Brazil', 'are found in the Himalayas', 'was painted by Leonardo da Vinci', 'were held in 1896'], 1,
    'أعلى جبال العالم ___.',
    'أعلى جبال العالم توجد في جبال الهيمالايا.',
    'mountains جمع فنستخدم are + V3: are found = توجد (يُعثَر عليها). حقيقة ثابتة فنستخدم المضارع البسيط المبني للمجهول.'),
  fill('The Mona Lisa ___.', ['were held in 1896', 'are made in Japan', 'was painted by Leonardo da Vinci', 'has been furnished'], 2,
    'الموناليزا ___.',
    'الموناليزا رُسمت على يد ليوناردو دافنشي.',
    'حدث في الماضي والموناليزا مفرد، فنستخدم الماضي البسيط المبني للمجهول was + V3: was painted by = رُسمت على يد. وby تُذكر قبل الفاعل (agent).'),
  fill('Many electronic goods ___.', ['are made in Japan', 'is grown in Brazil', 'was painted by Leonardo da Vinci', 'was being fixed'], 0,
    'الكثير من البضائع الإلكترونية ___.',
    'الكثير من البضائع الإلكترونية تُصنع في اليابان.',
    'goods جمع فنستخدم are + V3: are made = تُصنَع. حقيقة عامة ← المضارع البسيط المبني للمجهول.'),
  fill('The first modern Olympic Games ___.', ['are found in the Himalayas', 'was given', 'were held in 1896', 'is grown in Brazil'], 2,
    'أول ألعاب أولمبية حديثة ___.',
    'أول ألعاب أولمبية حديثة أُقيمت عام 1896.',
    'Games جمع والحدث في الماضي (1896) ← الماضي البسيط المبني للمجهول were + V3: were held = أُقيمت.'),
  fill('Papers ___ from all the students at this moment.', ['had been cancelled', 'are being taken', 'was being fixed', 'has been furnished'], 1,
    'الأوراق ___ من جميع الطلاب في هذه اللحظة.',
    'الأوراق تُؤخذ (يجري جمعها) من جميع الطلاب في هذه اللحظة.',
    'at this moment تدلّ على المضارع المستمر، والمبني للمجهول منه: am/is/are + being + V3. Papers جمع ← are being taken.'),
  fill('When we reached the airport, we found that all the flights ___ due to the storm.', ['are being taken', 'has been furnished', 'had been cancelled', 'was given'], 2,
    'عندما وصلنا إلى المطار، وجدنا أن جميع الرحلات ___ بسبب العاصفة.',
    'عندما وصلنا إلى المطار، وجدنا أن جميع الرحلات كانت قد أُلغيت بسبب العاصفة.',
    'الإلغاء حدث قبل وصولنا (حدث ماضٍ قبل حدث ماضٍ آخر) ← الماضي التام المبني للمجهول: had + been + V3 = had been cancelled.'),
  fill('My laptop ___ when the teacher asked about the project.', ['was being fixed', 'are being taken', 'had been cancelled', 'were held in 1896'], 0,
    'حاسوبي المحمول ___ عندما سأل المعلّم عن المشروع.',
    'حاسوبي المحمول كان يجري إصلاحه عندما سأل المعلّم عن المشروع.',
    'حدث كان مستمراً في الماضي عندما قطعه حدث آخر (when the teacher asked) ← الماضي المستمر المبني للمجهول: was/were + being + V3. laptop مفرد ← was being fixed.'),
  fill('Our house ___ with antiques.', ['was being fixed', 'has been furnished', 'are being taken', 'are made in Japan'], 1,
    'بيتنا ___ بالتحف القديمة.',
    'بيتنا قد فُرِش (أُثِّث) بالتحف القديمة.',
    'house مفرد، والنتيجة ظاهرة الآن ← المضارع التام المبني للمجهول: has + been + V3 = has been furnished.'),
  fill('He ___ a book for his birthday.', ['had been cancelled', 'are being taken', 'has been furnished', 'was given'], 3,
    'هو ___ كتاباً في عيد ميلاده.',
    'هو أُعطي (أُهدي) كتاباً في عيد ميلاده.',
    'He مفرد والحدث في الماضي ← was + V3: was given = أُعطِي. (والمعلوم: Someone gave him a book.)'),

  // Grammar B — change the sentences into the passive voice
  mcq('Change into the passive: “The Factory bought new machinery.”', [
    'New machinery is bought by the factory.',
    'New machinery was bought by the factory.',
    'New machinery was buy by the factory.',
    'New machinery were bought by the factory.',
  ], 1,
    'حوّل إلى المبني للمجهول: «اشترى المصنع آلات جديدة.»',
    'الفعل bought ماضٍ بسيط ← was/were + V3. machinery اسم غير معدود (مفرد) ← was bought. المفعول new machinery يصبح في أول الجملة، والفاعل يأتي بعد by.'),
  build('A new school is being built in this area.',
    'حوّل إلى المبني للمجهول: «The workers are building a new school in this area.» (تُبنى مدرسة جديدة في هذه المنطقة.)',
    'are building مضارع مستمر ← is/are + being + V3. school مفرد ← is being built. يمكن حذف by the workers لأن الفاعل معروف وغير مهم، ويمكن ذكره أيضاً.'),
  mcq('Change into the passive: “Two horses were pulling the farmer\'s wagon.”', [
    'The farmer\'s wagon was pulled by two horses.',
    'The farmer\'s wagon were being pulled by two horses.',
    'The farmer\'s wagon was being pulled by two horses.',
    'The farmer\'s wagon is being pulled by two horses.',
  ], 2,
    'حوّل إلى المبني للمجهول: «كان حصانان يجرّان عربة المزارع.»',
    'were pulling ماضٍ مستمر ← was/were + being + V3. wagon مفرد ← was being pulled by two horses. (was pulled ماضٍ بسيط، فهو زمن مختلف.)'),
  build('The passive voice rule is being explained by the teacher.',
    'حوّل إلى المبني للمجهول: «The teacher is explaining the passive voice rule.» (يجري شرح قاعدة المبني للمجهول من قبل المعلّم.)',
    'is explaining مضارع مستمر ← is + being + V3 = is being explained، ثم by the teacher.'),
  mcq('Change into the passive: “Mark had returned the book to the library.”', [
    'The book had been returned to the library by Mark.',
    'The book has been returned to the library by Mark.',
    'The book had returned to the library by Mark.',
    'The book was being returned to the library by Mark.',
  ], 0,
    'حوّل إلى المبني للمجهول: «كان مارك قد أعاد الكتاب إلى المكتبة.»',
    'had returned ماضٍ تام ← had + been + V3 = had been returned. لا تنسَ been: الجملة The book had returned تعني أن الكتاب عاد بنفسه!'),
  build('A mistake has been made.',
    'حوّل إلى المبني للمجهول: «Someone has made a mistake.» (لقد ارتُكب خطأ.)',
    'has made مضارع تام ← has + been + V3 = has been made. الفاعل someone مجهول فلا نكتب by someone.'),
  mcq('Change into the passive: “Italy produces a lot of olive oil.”', [
    'A lot of olive oil was produced in Italy.',
    'A lot of olive oil is producing in Italy.',
    'A lot of olive oil are produced in Italy.',
    'A lot of olive oil is produced in Italy.',
  ], 3,
    'حوّل إلى المبني للمجهول: «تُنتج إيطاليا الكثير من زيت الزيتون.»',
    'produces مضارع بسيط ← am/is/are + V3. olive oil غير معدود (مفرد) ← is produced. ويمكن أن نقول by Italy، لكن in Italy أكثر طبيعية لأنها مكان.'),
  build('Many places in the city were destroyed by a storm.',
    'حوّل إلى المبني للمجهول: «A storm destroyed many places in the city.» (دُمّرت أماكن كثيرة في المدينة بسبب عاصفة.)',
    'destroyed ماضٍ بسيط، و places جمع ← were + V3 = were destroyed، ثم by a storm.'),
  mcq('Change into the passive: “He had already delivered the mail by the time I left school.”', [
    'The mail has already been delivered by the time I left school.',
    'The mail had already been delivered by the time I left school.',
    'The mail had already delivered by the time I left school.',
    'The mail was already being delivered by the time I left school.',
  ], 1,
    'حوّل إلى المبني للمجهول: «كان قد سلّم البريد قبل أن أغادر المدرسة.»',
    'had delivered ماضٍ تام ← had + been + V3 = had been delivered، وتبقى already بعد had. نحذف by him لأن الفاعل ضمير غير مهم.'),
  build('The hard-working students have been rewarded by teachers.',
    'حوّل إلى المبني للمجهول: «Teachers have rewarded the hard-working students.» (كوفئ الطلاب المجتهدون من قبل المعلّمين.)',
    'have rewarded مضارع تام، و students جمع ← have + been + V3 = have been rewarded، ثم by teachers.'),
]

// ---------------------------------------------------------------- Unit 12: Silent, yet Talking! (Activity Book 56–60)

const u12Exercises: GrammarExercise[] = [
  // Reading B — correct the false statements (1 and 3 are true: see the reading's true/false list)
  mcq('Correct the false statement: “Animals can slowly learn the words of the language and use them as a form of communication.”', [
    'Animals learn the words of the language faster than children.',
    'Children slowly learn the words of language and use them as a form of communication.',
    'Dogs slowly learn the words and use them to talk to their owners.',
    'Birds can learn all the words of the language.',
  ], 1,
    'صحّح العبارة الخاطئة: «تستطيع الحيوانات أن تتعلّم كلمات اللغة شيئاً فشيئاً وتستخدمها وسيلةً للتواصل.»',
    'العبارة خاطئة: الذين يتعلّمون الكلمات شيئاً فشيئاً هم الأطفال لا الحيوانات. النص: Children ... slowly learn the words of language and use them as a form of communication.'),
  mcq('Correct the false statement: “Animals have a true language like us, humans.”', [
    'Animals have a better language than humans.',
    'Only dogs have a true language like humans.',
    'Animals do not have a true language like humans, but they can still communicate.',
    'Animals cannot communicate at all.',
  ], 2,
    'صحّح العبارة الخاطئة: «للحيوانات لغة حقيقية مثلنا نحن البشر.»',
    'العبارة خاطئة. النص: Researchers say that animals do not have a true language like humans، وفي الخاتمة: although animals do not have a true language like humans, they can still communicate. لاحظ: هي تتواصل، لكن بلا لغة حقيقية.'),

  // Vocabulary — fill in the spaces with the key words (make changes if necessary)
  fill('The student was very ___; he gave a smart answer to a very difficult quiz.', ['intellectual', 'gesture', 'motivation', 'command'], 0,
    'كان الطالب ___ جداً؛ فقد أعطى إجابة ذكية عن اختبار قصير صعب جداً.',
    'كان الطالب ذكياً (مفكّراً) جداً؛ فقد أعطى إجابة ذكية عن اختبار قصير صعب جداً.',
    'بعد very نحتاج صفة، والصفة الوحيدة في الكلمات المفتاحية هي intellectual = متعلّق بالقدرة على الفهم بذكاء. وجملة «أعطى إجابة ذكية» تؤكّد المعنى.'),
  fill('The police are always ready to ___ to people\'s calls for help.', ['response', 'respond', 'engage', 'command'], 1,
    'الشرطة مستعدّة دائماً لـ ___ لنداءات الناس طلباً للمساعدة.',
    'الشرطة مستعدّة دائماً للاستجابة لنداءات الناس طلباً للمساعدة.',
    'بعد to (ready to) نحتاج فعلاً في المصدر، لذلك نغيّر الاسم response (استجابة) إلى الفعل respond (يستجيب). هذا معنى make changes if necessary.'),
  fill('The dog was wagging its tail as a ___ of happiness.', ['sign', 'command', 'response', 'motivation'], 0,
    'كان الكلب يهزّ ذيله ___ على السعادة.',
    'كان الكلب يهزّ ذيله علامةً على السعادة.',
    'a sign of = علامة على. sign: حركة أو صوت نقوم به لنخبر أحداً بشيء، وهزّ الذيل علامة على فرح الكلب. في النص: a dog wagging its tail when excited.'),
  fill('The animals at the circus do the movements following their trainers\' ___.', ['intellectual', 'commands', 'engage', 'wag'], 1,
    'تؤدّي الحيوانات في السيرك الحركات متّبعةً ___ مدرّبيها.',
    'تؤدّي الحيوانات في السيرك الحركات متّبعةً أوامر مدرّبيها.',
    'بعد trainers\' (المضاف) نحتاج اسماً، و command = order (أمر). نجعلها جمعاً commands لأن المدرّبين يعطون أوامر كثيرة. في النص: Dogs can be trained to follow certain commands.'),

  // Grammar A — replace the personal pronouns by possessive pronouns
  fill('This book is ___. (you)', ['your', 'yours', 'you', 'yourself'], 1,
    'هذا الكتاب ___. (أنت)',
    'هذا الكتاب لك (مُلكك).',
    'ضمير الملكية يقف وحده ولا يأتي بعده اسم: you ← yours = لك. أما your فهي صفة ملكية يجب أن يأتي بعدها اسم (your book).'),
  fill('The ball is ___. (I)', ['my', 'me', 'mine', 'myself'], 2,
    'الكرة ___. (أنا)',
    'الكرة لي (مُلكي).',
    'I ← mine = لي. لا نقول The ball is my لأن my تحتاج اسماً بعدها (my ball).'),
  fill('The blue car is ___. (we)', ['our', 'ours', 'us', 'ourselves'], 1,
    'السيارة الزرقاء ___. (نحن)',
    'السيارة الزرقاء لنا (مُلكنا).',
    'we ← ours = لنا. ضمير الملكية لا يتبعه اسم، ويأتي في آخر الجملة بعد is.'),
  fill('The ring is ___. (she)', ['her', 'hers', 'she', 'herself'], 1,
    'الخاتم ___. (هي)',
    'الخاتم لها (مُلكها).',
    'she ← hers = لها، مثل مثال الكتاب: That car is hers.'),
  fill('We met Paul and Jane last night. This house is ___. (they)', ['their', 'them', 'theirs', 'themselves'], 2,
    'قابلنا بول وجين الليلة الماضية. هذا البيت ___. (هم)',
    'قابلنا بول وجين الليلة الماضية. هذا البيت لهما (مُلكهما).',
    'they ← theirs = لهم. أما their فتحتاج اسماً بعدها (their house).'),
  fill('The luggage is ___. (he)', ['his', 'him', 'he', 'himself'], 0,
    'الأمتعة ___. (هو)',
    'الأمتعة له (مُلكه).',
    'he ← his = له. لاحظ أن his تبقى كما هي سواء كانت صفة ملكية (his bag) أو ضمير ملكية (It is his).'),
  fill('There is a bird in our garden. The nest is ___. (it)', ['it', 'its', 'it\'s', 'itself'], 1,
    'هناك طائر في حديقتنا. العشّ ___. (هو، لغير العاقل)',
    'هناك طائر في حديقتنا. العشّ له (مُلكه).',
    'it ← its = له (لغير العاقل)، كما في جدول الكتاب: It is its. انتبه: it\'s تعني it is وليست للملكية.'),

  // Grammar B — complete the sentences with the correct reflexive pronoun
  fill('Robert made this T-shirt ___.', ['himself', 'herself', 'itself', 'themselves'], 0,
    'صنع روبرت هذا القميص ___.',
    'صنع روبرت هذا القميص بنفسه.',
    'Robert = he ← himself = بنفسه. ضمير التأكيد/الانعكاس يطابق الفاعل.'),
  fill('Tim and Gerry, if you want more milk, help ___.', ['yourself', 'yourselves', 'themselves', 'ourselves'], 1,
    'تيم وجيري، إن أردتما مزيداً من الحليب، فاخدما ___.',
    'تيم وجيري، إن أردتما مزيداً من الحليب، فاخدما نفسيكما.',
    'نخاطب شخصين (you جمع) ← yourselves. أما yourself فللمخاطَب المفرد. help yourselves = اخدموا أنفسكم (خذوا بأنفسكم).'),
  fill('Alice and Doris collected the stickers ___.', ['herself', 'themselves', 'yourselves', 'theirselves'], 1,
    'جمعت أليس ودوريس الملصقات ___.',
    'جمعت أليس ودوريس الملصقات بنفسيهما.',
    'Alice and Doris = they ← themselves. انتبه: كلمة theirselves خطأ شائع وغير موجودة.'),
  fill('The girl looked at ___ in the mirror.', ['her', 'himself', 'herself', 'hers'], 2,
    'نظرت الفتاة إلى ___ في المرآة.',
    'نظرت الفتاة إلى نفسها في المرآة.',
    'الفاعل والمفعول هما الشخص نفسه (the girl) ← نستخدم الضمير الانعكاسي herself، مثل: She saw herself in the mirror.'),
  fill('Freddy, you\'ll have to do your homework ___.', ['yourselves', 'himself', 'yourself', 'myself'], 2,
    'فريدي، سيكون عليك أن تكتب وظيفتك ___.',
    'فريدي، سيكون عليك أن تكتب وظيفتك بنفسك.',
    'نخاطب شخصاً واحداً (Freddy) ← you مفرد ← yourself = بنفسك.'),
  fill('I introduced ___ to my new neighbour.', ['me', 'myself', 'mine', 'himself'], 1,
    'عرّفتُ ___ إلى جاري الجديد.',
    'عرّفتُ نفسي إلى جاري الجديد.',
    'الفاعل I والمفعول هو الشخص نفسه ← myself. لا نقول I introduced me.'),
  fill('We can move the table ___.', ['ourselves', 'ourself', 'themselves', 'us'], 0,
    'نستطيع أن نحرّك الطاولة ___.',
    'نستطيع أن نحرّك الطاولة بأنفسنا.',
    'We ← ourselves = بأنفسنا (جمع، لذلك -selves وليس -self).'),

  // Grammar C — review of question tags
  fill('You like fish, ___?', ['don\'t you', 'do you', 'aren\'t you', 'didn\'t you'], 0,
    'أنت تحبّ السمك، ___؟',
    'أنت تحبّ السمك، أليس كذلك؟',
    'جملة مثبتة ← سؤال ذيلي منفي. الفعل like مضارع بسيط بلا فعل مساعد ← نستخدم do: don\'t you? مثل: You like tea, don\'t you?'),
  fill('John isn\'t very happy, ___?', ['isn\'t he', 'is he', 'does he', 'is John'], 1,
    'جون ليس سعيداً جداً، ___؟',
    'جون ليس سعيداً جداً، أليس كذلك؟',
    'جملة منفية (isn\'t) ← سؤال ذيلي مثبت بالفعل المساعد نفسه: is، ونستبدل الاسم John بالضمير he ← is he?'),
  fill('Your parents aren\'t at home, ___?', ['are they', 'aren\'t they', 'do they', 'were they'], 0,
    'والداك ليسا في البيت، ___؟',
    'والداك ليسا في البيت، أليس كذلك؟',
    'جملة منفية بـ aren\'t ← سؤال ذيلي مثبت are، و your parents ← they ← are they?'),
  fill('He didn\'t eat much lunch, ___?', ['did he', 'didn\'t he', 'does he', 'was he'], 0,
    'لم يأكل كثيراً على الغداء، ___؟',
    'لم يأكل كثيراً على الغداء، أليس كذلك؟',
    'جملة منفية بالماضي didn\'t ← سؤال ذيلي مثبت بالماضي: did he?'),
  fill('Your friends haven\'t left yet, ___?', ['haven\'t they', 'have they', 'did they', 'are they'], 1,
    'أصدقاؤك لم يغادروا بعد، ___؟',
    'أصدقاؤك لم يغادروا بعد، أليس كذلك؟',
    'جملة منفية بالمضارع التام haven\'t ← سؤال ذيلي مثبت: have they? مثل: They haven\'t left, have they?'),
  fill('Let\'s go to the party, ___?', ['shall we', 'don\'t we', 'let\'s we', 'do we'], 0,
    'لنذهب إلى الحفلة، ___؟',
    'لنذهب إلى الحفلة، ما رأيك؟',
    'قاعدة الكتاب: السؤال الذيلي بعد Let\'s هو دائماً shall we?'),
]

// ---------------------------------------------------------------- Progress Test (II) (Activity Book 61–64)

const testExercises: GrammarExercise[] = [
  // Vocabulary — match (A) with (B) to make meaningful expressions
  fill('make ___', ['friends', 'a profile', 'to Facebook', 'new experiences'], 0,
    'يكوّن ___',
    'يكوّن صداقات',
    'make friends = يكوّن صداقات. في النص: Making friends from all over the world is easy nowadays.'),
  fill('start ___', ['to Facebook', 'a conversation', 'friends', 'a profile'], 1,
    'يبدأ ___',
    'يبدأ محادثة',
    'start a conversation = يبدأ محادثة. وفي النص قريب منها: have conversations with new friends.'),
  fill('create ___', ['new experiences', 'friends', 'a profile', 'to Facebook'], 2,
    'يُنشئ ___',
    'يُنشئ ملفاً شخصياً',
    'create a profile = يُنشئ ملفاً شخصياً (على موقع إلكتروني). في النص: When we create a profile, we will be asked to fill out basic details.'),
  fill('sign up ___', ['a conversation', 'new experiences', 'friends', 'to Facebook'], 3,
    'يشترك ___',
    'يشترك في فيسبوك',
    'sign up to = يشترك / يسجّل في (موقع). في النص: sign up to a pen pal website. لذلك تأتي to بعد sign up.'),
  fill('learn about ___', ['new experiences', 'a profile', 'to Facebook', 'a conversation'], 0,
    'يتعرّف على ___',
    'يتعرّف على تجارب جديدة',
    'learn about new experiences = يتعرّف على تجارب جديدة. في النص: willing to learn about new experiences.'),

  // Grammar A — choose the correct word between brackets
  fill('You have to fill in ___ personal details.', ['you', 'your', 'yours', 'yourself'], 1,
    'عليك أن تملأ ___ الشخصية.',
    'عليك أن تملأ معلوماتك الشخصية.',
    'بعد الفراغ اسم (personal details) ← نحتاج صفة ملكية your = ـكَ. أما you فضمير فاعل، و yours تقف وحدها بلا اسم.'),
  fill('It\'s important to learn ___ language.', ['they', 'them', 'their', 'theirs'], 2,
    'من المهم أن نتعلّم ___.',
    'من المهم أن نتعلّم لغتهم.',
    'قبل الاسم language نستخدم صفة الملكية their = ـهم. they ضمير فاعل ولا يأتي قبل اسم.'),
  fill('Sami will be happy if ___ gets high marks.', ['he', 'his', 'him', 'himself'], 0,
    'سيكون سامي سعيداً إذا ___ على علامات عالية.',
    'سيكون سامي سعيداً إذا حصل هو على علامات عالية.',
    'نحتاج فاعلاً للفعل gets ← ضمير الفاعل he. أما his فللملكية وتحتاج اسماً بعدها.'),
  fill('We shouldn\'t be limited to friends living in ___ neighbourhood.', ['we', 'us', 'ours', 'our'], 3,
    'يجب ألّا نقتصر على الأصدقاء الذين يعيشون في ___.',
    'يجب ألّا نقتصر على الأصدقاء الذين يعيشون في حيّنا.',
    'قبل الاسم neighbourhood نستخدم صفة الملكية our = ـنا.'),

  // Grammar B — past simple, past perfect or past continuous (the fire story)
  fill('It happened three years ago while I was staying at my sister\'s house. I ___ the house for them.', ['looked after', 'was looking after', 'had looked after', 'was holding'], 1,
    'حدث ذلك قبل ثلاث سنوات بينما كنت أقيم في بيت أختي. ___ البيت من أجلهم.',
    'حدث ذلك قبل ثلاث سنوات بينما كنت أقيم في بيت أختي. كنت أعتني بالبيت من أجلهم.',
    'الاعتناء بالبيت كان حدثاً مستمراً في تلك الفترة (مثل was staying) ← الماضي المستمر: was looking after.'),
  fill('One night I ___ a lot of noise outside.', ['was hearing', 'had heard', 'heard', 'was hear'], 2,
    'في إحدى الليالي ___ ضجّة كبيرة في الخارج.',
    'في إحدى الليالي سمعتُ ضجّة كبيرة في الخارج.',
    'حدث قصير مكتمل في الماضي ضمن تسلسل القصة ← الماضي البسيط: heard (التصريف الثاني لـ hear).'),
  fill('… and I ___ to see what was wrong.', ['went out', 'was going out', 'had gone out', 'go out'], 0,
    '… و ___ لأرى ما الخطب.',
    '… وخرجتُ لأرى ما الخطب.',
    'حدث مكتمل يأتي بعد سماع الضجّة مباشرة ← الماضي البسيط: went out.'),
  fill('The house next door was on fire. Smoke and flames ___ out of the upstairs windows.', ['came', 'were coming', 'had come', 'was coming'], 1,
    'كان البيت المجاور يحترق. ___ الدخان واللهب من النوافذ العلوية.',
    'كان البيت المجاور يحترق. كان الدخان واللهب يخرجان من النوافذ العلوية.',
    'نصف مشهداً كان مستمراً لحظة وصوله ← الماضي المستمر. smoke and flames جمع ← were coming.'),
  fill('A woman shouted, "Help, help. Tommy\'s still inside." Without thinking I ___ into the house, but it was no good.', ['was running', 'had run', 'ran', 'was holding'], 2,
    'صرخت امرأة: «النجدة، النجدة. تومي ما زال في الداخل.» ومن دون تفكير ___ إلى داخل البيت، لكن ذلك لم يُجدِ نفعاً.',
    'صرخت امرأة: «النجدة، النجدة. تومي ما زال في الداخل.» ومن دون تفكير ركضتُ إلى داخل البيت، لكن ذلك لم يُجدِ نفعاً.',
    'حدث سريع مكتمل يلي صراخ المرأة ← الماضي البسيط: ran (التصريف الثاني لـ run).'),
  fill('Everything ___ and it was terribly hot.', ['burned', 'was burning', 'had burned', 'were burning'], 1,
    'كان كل شيء ___ وكان الجوّ حارّاً جداً.',
    'كان كل شيء يحترق وكان الجوّ حارّاً جداً.',
    'وصف لما كان يجري لحظة دخوله ← الماضي المستمر. everything مفرد ← was burning (وليس were).'),
  fill('Then, while I ___, something hit me on the back of the head.', ['stood', 'had stood', 'was standing', 'was lying'], 2,
    'ثم بينما ___، ضربني شيء على مؤخرة رأسي.',
    'ثم بينما كنت واقفاً، ضربني شيء على مؤخرة رأسي.',
    'while + الماضي المستمر للحدث الطويل الذي قاطعه حدث قصير (hit) ← was standing.'),
  fill('The next thing that I remember I ___ on the grass in front of the house.', ['was lying', 'lay', 'had lain', 'was standing'], 0,
    'أول ما أتذكّره بعد ذلك أنني ___ على العشب أمام البيت.',
    'أول ما أتذكّره بعد ذلك أنني كنت مستلقياً على العشب أمام البيت.',
    'حالة مستمرة لحظة استعادة وعيه ← الماضي المستمر: was lying (من lie: يستلقي؛ نحذف ie ونضيف ying).'),
  fill('The fire brigade ___ me out of the house.', ['pulled', 'was pulling', 'had pulled', 'had been pull'], 2,
    'رجال الإطفاء ___ من البيت.',
    'كان رجال الإطفاء قد سحبوني من البيت.',
    'سحبه من البيت حدث قبل أن يجد نفسه على العشب (حدث ماضٍ قبل حدث ماضٍ آخر) ← الماضي التام: had pulled.'),
  fill('The woman was there and she ___, "It\'s all right. Tommy\'s safe."', ['said', 'was saying', 'had said', 'says'], 0,
    'كانت المرأة هناك و ___: «كل شيء على ما يرام. تومي بأمان.»',
    'كانت المرأة هناك وقالت: «كل شيء على ما يرام. تومي بأمان.»',
    'حدث قصير مكتمل ضمن تسلسل القصة ← الماضي البسيط: said.'),
  fill('Then I ___ that she was holding a cat.', ['was realizing', 'realized', 'had realized', 'realize'], 1,
    'ثم ___ أنها كانت تحمل قطّة.',
    'ثم أدركتُ أنها كانت تحمل قطّة.',
    'حدث مكتمل في لحظة معيّنة (then) ← الماضي البسيط: realized. ولاحظ أن realize فعل حالة لا يُستخدم عادةً بالمستمر.'),
  fill('Then I realized that she ___ a cat.', ['held', 'had hold', 'was holding', 'was lying'], 2,
    'ثم أدركتُ أنها ___ قطّة.',
    'ثم أدركتُ أنها كانت تحمل قطّة.',
    'كانت تحمل القطّة في تلك اللحظة (حدث مستمر) ← الماضي المستمر: was holding.'),
  fill('I ___ my life for a cat.', ['had risked', 'was risking', 'risk', 'have risked'], 0,
    '___ بحياتي من أجل قطّة.',
    'لقد كنتُ خاطرتُ بحياتي من أجل قطّة.',
    'المخاطرة حدثت قبل أن يدرك الحقيقة (realized) ← الماضي التام: had risked. (يبقى الفعل go في الصندوق زائداً.)'),

  // Grammar C — report the questions and statements
  fill('“How old was your father when you went to school?” He asked me ___.', [
    'how old was my father when I went to school',
    'how old my father had been when I had gone to school',
    'how old your father had been when you had gone to school',
    'how old is my father when I go to school',
  ], 1,
    '«كم كان عمر والدك عندما ذهبتَ إلى المدرسة؟» سألني ___.',
    'سألني كم كان عمر والدي عندما ذهبتُ إلى المدرسة.',
    'في السؤال المنقول: 1) نحوّله إلى ترتيب الجملة الخبرية (الفاعل قبل الفعل): my father had been لا was my father. 2) نرجع الزمن خطوة: was ← had been و went ← had gone. 3) your ← my و you ← I لأن المتكلّم يسألني أنا.'),
  fill('“I liked classical music when I was at school.” She said ___.', [
    'that I had liked classical music when I was at school',
    'that she likes classical music when she is at school',
    'that she had liked classical music when she was at school',
    'she had liked classical music when was she at school',
  ], 2,
    '«كنت أحبّ الموسيقى الكلاسيكية عندما كنت في المدرسة.» قالت ___.',
    'قالت إنها كانت تحبّ الموسيقى الكلاسيكية عندما كانت في المدرسة.',
    'الكلام المنقول: I ← she، والماضي البسيط liked ← الماضي التام had liked. وبعد when في جملة الزمن يمكن إبقاء was، ويمكن أيضاً had been.'),
  fill('“Do you usually play any sports at the university?” My teacher wondered ___.', [
    'if I usually played any sports at the university',
    'do I usually play any sports at the university',
    'if you usually play any sports at the university',
    'that did I usually play any sports at the university',
  ], 0,
    '«هل تمارس عادةً أي رياضة في الجامعة؟» تساءل معلّمي ___.',
    'تساءل معلّمي إن كنت أمارس عادةً أي رياضة في الجامعة.',
    'السؤال بـ Do/Does (نعم/لا) يُنقل بـ if أو whether، ونحذف do، ونرجع الزمن: play ← played، و you ← I.'),
  fill('“They have been to France for a month.” Mark told us ___.', [
    'that they have been to France for a month',
    'that they had been to France for a month',
    'that they were being to France for a month',
    'that we had been to France for a month',
  ], 1,
    '«لقد ذهبوا إلى فرنسا لمدة شهر.» أخبرنا مارك ___.',
    'أخبرنا مارك أنهم كانوا قد ذهبوا إلى فرنسا لمدة شهر.',
    'بعد told us (فعل ماضٍ) نرجع الزمن: المضارع التام have been ← الماضي التام had been.'),
  fill('“When did you go to the party?” I asked Sally ___.', [
    'when did she go to the party',
    'when she had gone to the party',
    'when had she gone to the party',
    'when you went to the party',
  ], 1,
    '«متى ذهبتِ إلى الحفلة؟» سألتُ سالي ___.',
    'سألتُ سالي متى كانت قد ذهبت إلى الحفلة.',
    'السؤال بأداة استفهام (when) نُبقي الأداة ونحذف did ونكتب ترتيب الجملة الخبرية: she had gone. go (بعد did) ← had gone، و you ← she.'),
  fill('“Was it cold?” He wondered ___.', [
    'if was it cold',
    'if it is cold',
    'that it had been cold',
    'if it had been cold',
  ], 3,
    '«هل كان الجوّ بارداً؟» تساءل ___.',
    'تساءل إن كان الجوّ بارداً.',
    'سؤال نعم/لا ← if/whether + ترتيب الجملة الخبرية (it قبل الفعل) + إرجاع الزمن: was ← had been.'),
  fill('“We stayed in a big hotel.” She told me ___.', [
    'that they had stayed in a big hotel',
    'that we had stayed in a big hotel',
    'that they stay in a big hotel',
    'if they had stayed in a big hotel',
  ], 0,
    '«أقمنا في فندق كبير.» أخبرتني ___.',
    'أخبرتني أنهم كانوا قد أقاموا في فندق كبير.',
    'جملة خبرية ← told me + that. we ← they، والماضي البسيط stayed ← الماضي التام had stayed. (if للأسئلة فقط.)'),
  fill('“Do you need directions to reach your destination?” I asked the tourist ___.', [
    'if he needed directions to reach his destination',
    'do you need directions to reach your destination',
    'if he needs directions to reach your destination',
    'that he needed directions to reach his destination',
  ], 0,
    '«هل تحتاج إلى إرشادات لتصل إلى وجهتك؟» سألتُ السائح ___.',
    'سألتُ السائح إن كان يحتاج إلى إرشادات ليصل إلى وجهته.',
    'سؤال Do ← if + إرجاع الزمن need ← needed، والضمائر you ← he و your ← his.'),
  fill('“Why did you leave your job?” He asked him ___.', [
    'why did he leave his job',
    'why he had left his job',
    'why you had left your job',
    'if he had left his job',
  ], 1,
    '«لماذا تركت عملك؟» سأله ___.',
    'سأله لماذا كان قد ترك عمله.',
    'نُبقي why، ونحذف did، ونستخدم ترتيب الجملة الخبرية: he had left. leave (بعد did) ← had left، و you/your ← he/his.'),
  fill('“Where is the post office?” He asked ___.', [
    'where is the post office',
    'where the post office is',
    'where the post office was',
    'where was the post office',
  ], 2,
    '«أين مكتب البريد؟» سأل ___.',
    'سأل أين يقع مكتب البريد.',
    'نُبقي where ونضع الفاعل قبل الفعل (the post office was) ونرجع الزمن is ← was. where was the post office خطأ لأنها بترتيب السؤال.'),

  // Grammar D — change the statements into the passive voice
  mcq('Change into the passive: “The teacher corrected the mistakes.”', [
    'The mistakes was corrected by the teacher.',
    'The mistakes were corrected by the teacher.',
    'The mistakes are corrected by the teacher.',
    'The mistakes were correct by the teacher.',
  ], 1,
    'حوّل إلى المبني للمجهول: «صحّح المعلّم الأخطاء.»',
    'corrected ماضٍ بسيط، و mistakes جمع ← were + V3 = were corrected by the teacher.'),
  build('The wallet was given to the police station by Lauren.',
    'حوّل إلى المبني للمجهول: «Lauren gave the wallet to the police station.» (سُلّمت المحفظة إلى مركز الشرطة من قبل لورين.)',
    'gave ماضٍ بسيط، و wallet مفرد ← was given (given هو التصريف الثالث لـ give)، ثم to the police station ثم by Lauren.'),
  mcq('Change into the passive: “The children rang the bell a few minutes ago.”', [
    'The bell was rang by the children a few minutes ago.',
    'The bell has been rung by the children a few minutes ago.',
    'The bell was rung by the children a few minutes ago.',
    'The bell were rung by the children a few minutes ago.',
  ], 2,
    'حوّل إلى المبني للمجهول: «قرع الأطفال الجرس قبل بضع دقائق.»',
    'rang ماضٍ بسيط (ring – rang – rung) ← was + التصريف الثالث rung. لا نقول was rang. و ago تدلّ على الماضي البسيط لا المضارع التام.'),
  mcq('Change into the passive: “The kids forgot the whole story in a few days.”', [
    'The whole story was forgotten by the kids in a few days.',
    'The whole story was forgot by the kids in a few days.',
    'The whole story is forgotten by the kids in a few days.',
    'The whole story were forgotten by the kids in a few days.',
  ], 0,
    'حوّل إلى المبني للمجهول: «نسي الأولاد القصة كلّها خلال بضعة أيام.»',
    'forgot ماضٍ بسيط (forget – forgot – forgotten)، و story مفرد ← was forgotten by the kids.'),
  build('He wasn\'t questioned very closely by the police.',
    'حوّل إلى المبني للمجهول: «The police didn\'t question him very closely.» (لم يُستجوَب بدقّة شديدة من قبل الشرطة.)',
    'didn\'t question ماضٍ بسيط منفي ← wasn\'t + V3 = wasn\'t questioned. المفعول him يصبح فاعلاً he في أول الجملة.'),
  mcq('Change into the passive: “The wild animals killed two men yesterday.”', [
    'Two men was killed by the wild animals yesterday.',
    'Two men were killing by the wild animals yesterday.',
    'Two men had killed by the wild animals yesterday.',
    'Two men were killed by the wild animals yesterday.',
  ], 3,
    'حوّل إلى المبني للمجهول: «قتلت الحيوانات البرّية رجلين البارحة.»',
    'killed ماضٍ بسيط، و two men جمع ← were killed، ثم by the wild animals، وتبقى yesterday في آخر الجملة.'),

  // Grammar E — combine the sentences using the correct relative pronoun (item 1 is the book's example)
  mcq('Combine: “She worked for a man. The man used to be an athlete.”', [
    'She worked for a man which used to be an athlete.',
    'She worked for a man who used to be an athlete.',
    'She worked for a man whose used to be an athlete.',
    'She worked for a man who he used to be an athlete.',
  ], 1,
    'اربط الجملتين: «عملت لدى رجل. كان الرجل رياضياً في الماضي.»',
    'a man إنسان ← نستخدم who. ونحذف the man من الجملة الثانية لأن who حلّت محلّه (لا نقول who he).'),
  mcq('Combine: “We broke the computer. The computer belonged to my father.”', [
    'We broke the computer who belonged to my father.',
    'We broke the computer which it belonged to my father.',
    'We broke the computer which belonged to my father.',
    'We broke the computer whose belonged to my father.',
  ], 2,
    'اربط الجملتين: «كسرنا الحاسوب. كان الحاسوب مُلكاً لأبي.»',
    'the computer شيء ← نستخدم which، ونحذف the computer المكرّرة.'),
  build('She loves books which have happy endings.',
    'اربط الجملتين بضمير وصل: «She loves books. The books have happy endings.» (إنها تحبّ الكتب التي لها نهايات سعيدة.)',
    'books أشياء ← which، ونحذف the books المكرّرة.'),
  mcq('Combine: “He sent an email to my brother. My brother lives in Australia.”', [
    'He sent an email to my brother who lives in Australia.',
    'He sent an email to my brother which lives in Australia.',
    'He sent an email to my brother whose lives in Australia.',
    'He sent an email to my brother who he lives in Australia.',
  ], 0,
    'اربط الجملتين: «أرسل بريداً إلكترونياً إلى أخي. يعيش أخي في أستراليا.»',
    'my brother إنسان ← who، ونحذف my brother المكرّرة.'),
  mcq('Combine: “Michael is in the garden. He is wearing a blue jumper.”', [
    'Michael, which is wearing a blue jumper, is in the garden.',
    'Michael, whose is wearing a blue jumper, is in the garden.',
    'Michael, who he is wearing a blue jumper, is in the garden.',
    'Michael, who is wearing a blue jumper, is in the garden.',
  ], 3,
    'اربط الجملتين: «مايكل في الحديقة. إنه يرتدي كنزة زرقاء.»',
    'Michael إنسان ← who، ونحذف he. ولأن Michael اسم علم معروف نضع الجملة الموصولة بين فاصلتين.'),
  build('The television which was bought 20 years ago was stolen.',
    'اربط الجملتين بضمير وصل: «The television was stolen. The television was bought 20 years ago.» (سُرق التلفاز الذي اشتُري قبل 20 سنة.)',
    'the television شيء ← which، ونضع الجملة الموصولة مباشرة بعد الاسم الذي تصفه، ثم نكمل الجملة الأولى: was stolen.'),
  mcq('Combine: “The fruit is on the table. The fruit isn\'t fresh.”', [
    'The fruit which is on the table isn\'t fresh.',
    'The fruit who is on the table isn\'t fresh.',
    'The fruit is on the table which isn\'t fresh.',
    'The fruit which it is on the table isn\'t fresh.',
  ], 0,
    'اربط الجملتين: «الفاكهة على الطاولة. الفاكهة ليست طازجة.»',
    'the fruit شيء ← which توضع بعد the fruit مباشرة. الخيار الثالث يجعل الطاولة هي غير الطازجة!'),
  mcq('Combine: “The table got broken. The table was my grandmother\'s.”', [
    'The table who was my grandmother\'s got broken.',
    'The table which was my grandmother\'s got broken.',
    'The table got broken which was my grandmother\'s it.',
    'The table whose was my grandmother\'s got broken.',
  ], 1,
    'اربط الجملتين: «انكسرت الطاولة. كانت الطاولة لجدّتي.»',
    'the table شيء ← which بعد the table مباشرة، ثم نكمل: got broken.'),

  // Grammar F — question tags
  fill('I am good at math, ___?', ['am not I', 'aren\'t I', 'isn\'t I', 'don\'t I'], 1,
    'أنا جيّد في الرياضيات، ___؟',
    'أنا جيّد في الرياضيات، أليس كذلك؟',
    'حالة خاصة: السؤال الذيلي المنفي بعد I am هو aren\'t I?'),
  fill('The shops close at 7pm, ___?', ['don\'t they', 'doesn\'t it', 'aren\'t they', 'do they'], 0,
    'تُغلق المتاجر في السابعة مساءً، ___؟',
    'تُغلق المتاجر في السابعة مساءً، أليس كذلك؟',
    'جملة مثبتة بالمضارع البسيط (close) بلا فعل مساعد ← don\'t، و the shops ← they ← don\'t they?'),
  fill('Jane won\'t be here tonight, ___?', ['won\'t she', 'will she', 'is she', 'will Jane'], 1,
    'جين لن تكون هنا الليلة، ___؟',
    'جين لن تكون هنا الليلة، أليس كذلك؟',
    'جملة منفية بـ won\'t (will not) ← سؤال ذيلي مثبت will، و Jane ← she ← will she?'),
  fill('He can\'t swim very fast, ___?', ['can\'t he', 'can he', 'does he', 'could he'], 1,
    'لا يستطيع أن يسبح بسرعة كبيرة، ___؟',
    'لا يستطيع أن يسبح بسرعة كبيرة، أليس كذلك؟',
    'جملة منفية بـ can\'t ← سؤال ذيلي مثبت بالفعل نفسه: can he? مثل: Jack can\'t come to the party, can he?'),
  fill('We were almost late, ___?', ['weren\'t we', 'were we', 'wasn\'t we', 'didn\'t we'], 0,
    'كدنا نتأخّر، ___؟',
    'كدنا نتأخّر، أليس كذلك؟',
    'جملة مثبتة بـ were ← سؤال ذيلي منفي weren\'t we? (و almost لا تجعل الجملة منفية).'),
  fill('I should wash the dishes, ___?', ['should I', 'shouldn\'t I', 'don\'t I', 'shan\'t I'], 1,
    'يجب أن أغسل الصحون، ___؟',
    'يجب أن أغسل الصحون، أليس كذلك؟',
    'جملة مثبتة بالفعل المساعد should ← سؤال ذيلي منفي بالفعل نفسه: shouldn\'t I?'),
]

// ---------------------------------------------------------------- export

export const extras: ModuleExtras = {
  units: {
    u11: {
      workbook: {
        pages: '51–55',
        readings: [
          {
            title: 'Messages to and from Outer Space',
            paragraphs: [
              'If you look up at the stars, you might wonder if anyone is really out there. You might also wonder if they have found as many strange ways to communicate with each other as we have. The wish to communicate with the outer space has always been there in our minds. As the 20th century began, interest in the possible life on Mars and the possible civilizations there led to a search for signals. Could we communicate with another planet? How might we look for signals and messages from other worlds? An example of how we might receive communications from the planet was mentioned in 1896 when a newspaper article entitled "A Signal from Mars" had offered one. In the late 19th and early 20th centuries the idea of wirelessly sending and receiving waves through the air, was developed. New methods of searching for communications from space were offered too. In 1901, engineer Nicola Tesla made the astonishing claim that he was receiving radio communications from Mars. His story was picked up and reported in the press.',
              'The Media was captured by the idea of communicating with Mars but it did not find much serious interest from scientists. In the 1960s a number of other scientists began searching for signals showing the existence of another life elsewhere in the universe. As it became increasingly clear that there was no intelligent life on other planets in the solar system, it became possible to detect signals from much farther away. Radio signals were detected to look for life or civilizations out in the galaxy but none was proved, yet most of us still look at the sky and wonder if there is someone trying to contact us.',
            ],
            paragraphsAr: [
              'إذا نظرتَ إلى النجوم في الأعلى، فقد تتساءل إن كان هناك أحدٌ ما حقاً هناك. وقد تتساءل أيضاً إن كانوا قد وجدوا طرقاً غريبة للتواصل فيما بينهم بقدر ما وجدنا نحن. لطالما كانت الرغبة في التواصل مع الفضاء الخارجي حاضرةً في أذهاننا. ومع بداية القرن العشرين، أدّى الاهتمام بإمكانية وجود حياة على المريخ وبالحضارات المحتملة هناك إلى البحث عن إشارات. هل يمكننا أن نتواصل مع كوكب آخر؟ وكيف لنا أن نبحث عن إشارات ورسائل من عوالم أخرى؟ وقد ذُكر مثالٌ على الطريقة التي قد نستقبل بها اتصالات من ذلك الكوكب عام 1896، حين قدّم مقالٌ في صحيفة بعنوان «إشارة من المريخ» مثالاً على ذلك. وفي أواخر القرن التاسع عشر وأوائل القرن العشرين تطوّرت فكرة إرسال الموجات واستقبالها لاسلكياً عبر الهواء، وطُرحت أيضاً طرق جديدة للبحث عن اتصالات من الفضاء. وفي عام 1901 أطلق المهندس نيكولا تسلا ادّعاءً مذهلاً بأنه يستقبل اتصالات لاسلكية من المريخ. وقد تناقلت الصحافة قصّته ونشرتها.',
              'استحوذت فكرة التواصل مع المريخ على اهتمام وسائل الإعلام، لكنها لم تلقَ اهتماماً جدّياً كبيراً من العلماء. وفي ستينيات القرن العشرين بدأ عدد من العلماء الآخرين البحث عن إشارات تُظهر وجود حياة أخرى في مكان ما من الكون. ومع ازدياد وضوح أنه لا توجد حياة ذكية على الكواكب الأخرى في المجموعة الشمسية، أصبح من الممكن رصد إشارات من مسافات أبعد بكثير. فقد رُصدت إشارات لاسلكية للبحث عن حياة أو حضارات في أرجاء المجرّة، لكن لم يثبت وجود أيٍّ منها، ومع ذلك ما زال معظمنا ينظر إلى السماء ويتساءل إن كان هناك من يحاول الاتصال بنا.',
            ],
            questions: [
              {
                q: 'Match: “If you look up at the stars, …”',
                qAr: 'صِل: «إذا نظرتَ إلى النجوم في الأعلى، …»',
                options: [
                  'has always been there in our minds.',
                  'you might wonder if anyone is really out there.',
                  'they might receive from another planet.',
                  'shows the existence of intelligent life in the universe.',
                ],
                answer: 1,
                explainAr: 'الجملة الأولى في النص: If you look up at the stars, you might wonder if anyone is really out there. (1 ← c)',
              },
              {
                q: 'Match: “The desire to communicate with the outer space …”',
                qAr: 'صِل: «الرغبة في التواصل مع الفضاء الخارجي …»',
                options: [
                  'you might wonder if anyone is really out there.',
                  'they might receive from another planet.',
                  'has always been there in our minds.',
                  'shows the existence of intelligent life in the universe.',
                ],
                answer: 2,
                explainAr: 'desire = wish (رغبة). النص: The wish to communicate with the outer space has always been there in our minds. (2 ← a)',
              },
              {
                q: 'Match: “A newspaper article entitled "A Signal from Mars" …”',
                qAr: 'صِل: «مقال في صحيفة بعنوان "إشارة من المريخ" …»',
                options: [
                  'offered an example of how they might receive communications from another planet.',
                  'has always been there in our minds.',
                  'you might wonder if anyone is really out there.',
                  'proved that there is life on Mars.',
                ],
                answer: 0,
                explainAr: 'النص: An example of how we might receive communications from the planet was mentioned in 1896 when a newspaper article entitled "A Signal from Mars" had offered one. أي أن المقال قدّم مثالاً على الاتصالات التي قد نستقبلها من كوكب آخر. (3 ← b)',
              },
              {
                q: 'Match: “Scientists began searching for signals …”',
                qAr: 'صِل: «بدأ العلماء البحث عن إشارات …»',
                options: [
                  'has always been there in our minds.',
                  'they might receive from another planet.',
                  'you might wonder if anyone is really out there.',
                  'showing the existence of intelligent life in the universe.',
                ],
                answer: 3,
                explainAr: 'النص: In the 1960s a number of other scientists began searching for signals showing the existence of another life elsewhere in the universe. (4 ← d)',
              },
              {
                q: 'What did Nicola Tesla claim in 1901?',
                qAr: 'ماذا ادّعى نيكولا تسلا عام 1901؟',
                options: [
                  'That he had found life on the moon.',
                  'That he was receiving radio communications from Mars.',
                  'That there was no life in the universe.',
                  'That he had invented a newspaper.',
                ],
                answer: 1,
                explainAr: 'النص: In 1901, engineer Nicola Tesla made the astonishing claim that he was receiving radio communications from Mars. (astonishing = مذهل يصعب تصديقه).',
              },
              {
                q: 'Why did it become possible to detect signals from much farther away?',
                qAr: 'لماذا أصبح من الممكن رصد إشارات من مسافات أبعد بكثير؟',
                options: [
                  'Because Tesla sent messages to Mars.',
                  'Because the Media stopped talking about Mars.',
                  'Because it became increasingly clear that there was no intelligent life on other planets in the solar system.',
                  'Because scientists found a civilization on Mars.',
                ],
                answer: 2,
                explainAr: 'النص: As it became increasingly clear that there was no intelligent life on other planets in the solar system, it became possible to detect signals from much farther away. (As هنا بمعنى «مع / لأنّ»).',
              },
            ],
            trueFalse: [
              { statement: 'Scientists first adopted the idea of the existence of life on other planets.', answer: false },
              { statement: 'Inventing the Wireless made the idea of connecting the world unreasonable.', answer: false },
              { statement: 'Tesla claimed that he received messages from the sun.', answer: false },
              { statement: 'After many experiments, it was proved that there might be life on other planets.', answer: false },
            ],
          },
        ],
        exercises: u11Exercises,
      },
      compositions: [
        {
          source: 'book',
          topic: 'Complete the following paragraph with words from the box. Keeping in Touch as an Emigrant (friends, presents, gifts, attend, button, daughter, photographs)',
          topicAr: 'أكمل الفقرة التالية بكلمات من الصندوق. «البقاء على تواصل عندما تكون مغترباً» (friends، presents، gifts، attend، button، daughter، photographs)',
          words: 80,
          plan: [
            { en: 'Who moved abroad: my sister and her little daughter used to live close to us.', ar: 'مَن سافر: أختي وابنتها الصغيرة كانتا تعيشان قريباً منّا ثم انتقلتا إلى الخارج.' },
            { en: 'What I did today: I attended my niece\'s birthday on Skype and gave her presents from the internet.', ar: 'ما فعلته اليوم: حضرت عيد ميلاد ابنة أختي عبر سكايب وقدّمت لها هدايا اخترتها من الإنترنت.' },
            { en: 'How Facebook and email help: family and friends see up-to-date photographs and events.', ar: 'كيف يساعد فيسبوك والبريد الإلكتروني: يرى الأهل والأصدقاء أحدث الصور والمناسبات العائلية.' },
            { en: 'Sending flowers and gifts by just pressing a button.', ar: 'إرسال الزهور والهدايا بمجرّد الضغط على زرّ.' },
            { en: 'Closing exclamation: What a wonderful world we live in these days!', ar: 'خاتمة تعجّبية: يا له من عالم رائع نعيش فيه هذه الأيام!' },
          ],
          phrases: [
            { en: 'daughter', ar: 'ابنة' },
            { en: 'niece', ar: 'ابنة الأخ / ابنة الأخت' },
            { en: 'used to live close to us', ar: 'كانت تعيش قريباً منّا (عادة في الماضي انتهت)' },
            { en: 'move abroad', ar: 'ينتقل إلى الخارج' },
            { en: 'attend a birthday on Skype', ar: 'يحضر عيد ميلاد عبر سكايب' },
            { en: 'presents / gifts', ar: 'هدايا' },
            { en: 'friends', ar: 'أصدقاء' },
            { en: 'up-to-date family photographs', ar: 'أحدث صور العائلة' },
            { en: 'stay in touch with', ar: 'يبقى على تواصل مع' },
            { en: 'by just pressing a button', ar: 'بمجرّد الضغط على زرّ' },
            { en: 'What a wonderful world we live in these days!', ar: 'يا له من عالم رائع نعيش فيه هذه الأيام!' },
          ],
          model: 'My sister and her little daughter used to live close to us. They have moved abroad now; yet today, I was able to attend my niece\'s birthday on Skype and give her presents I chose from the internet. Facebook and email mean that grandparents, family and friends can see the most up-to-date family photographs and events and stay in touch with them. We can send flowers and gifts to our family by just pressing a button. What a wonderful world we live in these days!',
          modelAr: 'كانت أختي وابنتها الصغيرة تعيشان قريباً منّا. لقد انتقلتا إلى الخارج الآن؛ ومع ذلك تمكّنتُ اليوم من حضور عيد ميلاد ابنة أختي عبر سكايب وتقديم هدايا لها اخترتُها من الإنترنت. فبفضل فيسبوك والبريد الإلكتروني يستطيع الأجداد والأهل والأصدقاء رؤية أحدث صور العائلة ومناسباتها والبقاء على تواصل معهم. ونستطيع أن نرسل الزهور والهدايا إلى عائلتنا بمجرّد الضغط على زرّ. يا له من عالم رائع نعيش فيه هذه الأيام!',
          checklistAr: [
            'هل وضعت كل كلمة من الصندوق مرة واحدة فقط في مكانها الصحيح؟',
            'هل انتبهت إلى نوع الكلمة المطلوبة (اسم بعد her little، فعل بعد to)؟',
            'هل وضعت presents و gifts في الفراغين 3 و6 (الكلمتان بمعنى واحد)؟',
            'هل تبدو الفقرة منطقية حين تقرؤها كاملة؟',
            'هل كتبت الكلمات بإملاء صحيح (photographs، daughter، attend)؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Imagine you have a friend living on another planet. Write an email to tell him/her about your life on Earth. What things would you like to mention? What technology have people on Earth reached? What would you like to ask him about?',
          topicAr: 'تخيّل أن لديك صديقاً يعيش على كوكب آخر. اكتب له/لها رسالة بريد إلكتروني تخبره فيها عن حياتك على الأرض. ما الأشياء التي تودّ أن تذكرها؟ ما التكنولوجيا التي وصل إليها الناس على الأرض؟ وعمّ تودّ أن تسأله؟',
          words: 100,
          points: [
            'What things would you like to mention?',
            'What technology have people on Earth reached?',
            'What would you like to ask him about?',
            'The form: To ------ / From -------- / Hi, I\'m writing to tell you about -------. / I miss you so much / See you soon',
          ],
          pointsAr: [
            'ما الأشياء التي تودّ أن تذكرها عن حياتك؟',
            'ما التكنولوجيا التي وصل إليها الناس على الأرض؟',
            'عمّ تودّ أن تسأل صديقك؟',
            'الشكل (Keep in mind): إلى / من / مرحباً، أكتب إليك لأخبرك عن ... / اشتقت إليك كثيراً / أراك قريباً',
          ],
          plan: [
            { en: 'Start with the form: To …, From …, then “Hi, I\'m writing to tell you about my life on Earth.”', ar: 'ابدأ بالشكل: إلى …، من …، ثم «مرحباً، أكتب إليك لأخبرك عن حياتي على الأرض.»' },
            { en: 'Mention things about your life: your city, your family, your school.', ar: 'اذكر أشياء عن حياتك: مدينتك وعائلتك ومدرستك.' },
            { en: 'Describe the technology people on Earth have reached (use the passive: messages are sent…).', ar: 'صِف التكنولوجيا التي وصل إليها الناس على الأرض (استخدم المبني للمجهول: messages are sent…).' },
            { en: 'Ask your friend two or three questions about his/her planet.', ar: 'اسأل صديقك سؤالين أو ثلاثة عن كوكبه.' },
            { en: 'End with “I miss you so much. See you soon,” and your name.', ar: 'اختم بـ «اشتقت إليك كثيراً. أراك قريباً،» ثم اسمك.' },
          ],
          phrases: [
            { en: 'I\'m writing to tell you about …', ar: 'أكتب إليك لأخبرك عن …' },
            { en: 'communicate with each other', ar: 'يتواصلون فيما بينهم' },
            { en: 'messages are sent in seconds', ar: 'تُرسل الرسائل في ثوانٍ (مبني للمجهول)' },
            { en: 'mobile phones are used everywhere', ar: 'تُستخدم الهواتف المحمولة في كل مكان' },
            { en: 'satellites have been sent into space', ar: 'أُرسلت أقمار صناعية إلى الفضاء (مضارع تام مبني للمجهول)' },
            { en: 'search for signals', ar: 'يبحث عن إشارات' },
            { en: 'look up at the stars and wonder', ar: 'ينظر إلى النجوم ويتساءل' },
            { en: 'the universe / the galaxy', ar: 'الكون / المجرّة' },
            { en: 'civilization', ar: 'حضارة' },
            { en: 'on Skype', ar: 'عبر سكايب' },
            { en: 'I miss you so much.', ar: 'اشتقت إليك كثيراً.' },
            { en: 'See you soon', ar: 'أراك قريباً' },
          ],
          model: 'To: Zed\nFrom: Sami\nHi Zed, I\'m writing to tell you about my life on Earth. I live with my family in Damascus, and I go to school every day. On Earth, people communicate with each other in many ways. Messages are sent in seconds by email, and we can see our friends on Skype. Mobile phones are used everywhere, and satellites have been sent into space. Some scientists are still searching for signals from other planets, so I often look up at the stars and wonder about you. What is your planet like? How do you communicate with each other? Is there a school on your planet? I miss you so much.\nSee you soon,\nSami',
          modelAr: 'إلى: زِد\nمن: سامي\nمرحباً زِد، أكتب إليك لأخبرك عن حياتي على الأرض. أعيش مع عائلتي في دمشق، وأذهب إلى المدرسة كل يوم. على الأرض يتواصل الناس فيما بينهم بطرق كثيرة. فالرسائل تُرسل في ثوانٍ بالبريد الإلكتروني، ونستطيع أن نرى أصدقاءنا عبر سكايب. والهواتف المحمولة تُستخدم في كل مكان، وقد أُرسلت أقمار صناعية إلى الفضاء. وما زال بعض العلماء يبحثون عن إشارات من كواكب أخرى، لذلك أنظر كثيراً إلى النجوم وأتساءل عنك. كيف هو كوكبك؟ كيف تتواصلون فيما بينكم؟ هل توجد مدرسة على كوكبك؟ اشتقت إليك كثيراً.\nأراك قريباً،\nسامي',
          checklistAr: [
            'هل اتّبعت شكل الرسالة (To / From / Hi, I\'m writing to tell you about … / I miss you so much / See you soon)؟',
            'هل ذكرت أشياء عن حياتك على الأرض؟',
            'هل وصفت التكنولوجيا التي وصل إليها الناس، واستخدمت المبني للمجهول بشكل صحيح (are sent, have been sent)؟',
            'هل سألت صديقك أسئلة صحيحة الترتيب (What is your planet like? How do you …?)؟',
            'هل استخدمت كلمات الوحدة (communicate, signals, wonder, universe)؟',
            'هل راجعت الإملاء والحروف الكبيرة وعلامات الترقيم، وكتبت نحو 100 كلمة؟',
          ],
        },
      ],
      translations: [
        { en: 'If you look up at the stars, you might wonder if anyone is really out there.', ar: 'إذا نظرتَ إلى النجوم في الأعلى، فقد تتساءل إن كان هناك أحدٌ ما حقاً هناك.' },
        { en: 'The wish to communicate with the outer space has always been there in our minds.', ar: 'لطالما كانت الرغبة في التواصل مع الفضاء الخارجي حاضرةً في أذهاننا.' },
        { en: 'How might we look for signals and messages from other worlds?', ar: 'كيف لنا أن نبحث عن إشارات ورسائل من عوالم أخرى؟' },
        { en: 'His story was picked up and reported in the press.', ar: 'تناقلت الصحافة قصّته ونشرتها.' },
        { en: 'The students were rewarded by the teacher.', ar: 'كوفئ الطلاب من قبل المعلّم.' },
        { en: 'The flowers are watered by the gardener every morning.', ar: 'تُسقى الأزهار من قبل البستاني كل صباح.' },
        { en: 'We were invited to John and Mary\'s wedding.', ar: 'دُعينا إلى حفل زفاف جون وماري.' },
        { en: 'Their cars were being washed while they were shopping in the mall.', ar: 'كانت سياراتهم تُغسل بينما كانوا يتسوّقون في المركز التجاري.' },
        { en: 'Lunch had been served in the hotel restaurant.', ar: 'كان الغداء قد قُدّم في مطعم الفندق.' },
        { en: 'Laws of motion were discovered by Newton.', ar: 'اكتُشفت قوانين الحركة على يد نيوتن.' },
        { en: 'The workers are building a new school in this area.', ar: 'يبني العمّال مدرسة جديدة في هذه المنطقة.' },
        { en: 'Many people\'s lives are inspired by small acts of kindness.', ar: 'تُلهَم حياة كثير من الناس بأفعال لطف صغيرة.' },
        { en: 'This poem was written by Nizar Qabani.', ar: 'كُتبت هذه القصيدة بقلم نزار قباني.' },
        { en: 'Our house is being decorated now.', ar: 'يجري تزيين بيتنا الآن.' },
        { en: 'The dam hadn\'t been built before 1963.', ar: 'لم يكن السدّ قد بُني قبل عام 1963.' },
        { en: 'What a wonderful world we live in these days!', ar: 'يا له من عالم رائع نعيش فيه هذه الأيام!' },
      ],
    },

    u12: {
      workbook: {
        pages: '56–60',
        readings: [
          {
            title: 'Do Animals Have a Language?',
            paragraphs: [
              'Language is considered a very complex form of communication that occurs among humans who use words while talking to express their needs and they cry and make faces when they want to express feelings. Animals also show signs of communication such as a bird singing a song or a dog wagging its tail when excited. However, do animals have their language? Scientists are still unsure about this question.',
              'Researchers say that animals do not have a true language like humans. However, they do communicate with each other with sounds and gestures. Children show these same forms of communication as babies when crying and gesturing, but they slowly learn the words of language and use them as a form of communication.',
              'So what about animals such as dogs that understand commands or birds that can "talk"? Dogs can be trained to follow certain commands such as "sit", "come" and "roll over", but does this mean they understand language and use it as well? Dogs are known to be experts at reading their owner\'s intentions and that they do not respond to actual words but the tone in which it is said.',
              'There is no doubt that animals communicate with each other to one degree or another in response to different motivations such as hunger or fear.',
              'Human language is creative and consists of unique characteristics that give us the ability to engage in intellectual and logical ways. However, it can be said that although animals do not have a true language like humans, they can still communicate.',
            ],
            paragraphsAr: [
              'تُعدّ اللغة شكلاً معقّداً جداً من أشكال التواصل يحدث بين البشر، الذين يستخدمون الكلمات أثناء الكلام للتعبير عن حاجاتهم، ويبكون ويغيّرون تعابير وجوههم عندما يريدون التعبير عن مشاعرهم. وتُظهر الحيوانات أيضاً علاماتٍ على التواصل، مثل طائر يغرّد أغنية أو كلب يهزّ ذيله عندما يكون متحمّساً. لكن هل للحيوانات لغتها الخاصة؟ ما زال العلماء غير متأكّدين من إجابة هذا السؤال.',
              'يقول الباحثون إن الحيوانات لا تملك لغةً حقيقية مثل البشر. ومع ذلك فهي تتواصل فعلاً فيما بينها بالأصوات والإيماءات. ويُظهر الأطفال أشكال التواصل هذه نفسها وهم رُضّع، عندما يبكون ويومئون، لكنهم يتعلّمون كلمات اللغة شيئاً فشيئاً ويستخدمونها وسيلةً للتواصل.',
              'فماذا عن حيوانات مثل الكلاب التي تفهم الأوامر، أو الطيور التي تستطيع أن «تتكلّم»؟ يمكن تدريب الكلاب على اتّباع أوامر معيّنة مثل «اجلس» و«تعال» و«تدحرج»، لكن هل يعني هذا أنها تفهم اللغة وتستخدمها أيضاً؟ من المعروف أن الكلاب خبيرة في قراءة نوايا أصحابها، وأنها لا تستجيب للكلمات نفسها بل للنبرة التي تُقال بها.',
              'لا شكّ في أن الحيوانات تتواصل فيما بينها بدرجة أو بأخرى استجابةً لدوافع مختلفة مثل الجوع أو الخوف.',
              'أما لغة الإنسان فهي مبدعة وتتألّف من خصائص فريدة تمنحنا القدرة على الانخراط بطرق فكرية ومنطقية. ومع ذلك يمكن القول إنه على الرغم من أن الحيوانات لا تملك لغةً حقيقية مثل البشر، فإنها تستطيع مع ذلك أن تتواصل.',
            ],
            questions: [
              {
                q: 'Define Language.',
                qAr: 'عرّف اللغة.',
                options: [
                  'A song that birds sing when they are excited.',
                  'A very complex form of communication that occurs among humans who use words while talking to express their needs.',
                  'The tone in which a command is said to a dog.',
                  'A simple movement of the tail from side to side.',
                ],
                answer: 1,
                explainAr: 'الجملة الأولى في النص: Language is considered a very complex form of communication that occurs among humans who use words while talking to express their needs.',
              },
              {
                q: 'What ways can humans use to communicate?',
                qAr: 'ما الطرق التي يستطيع البشر استخدامها للتواصل؟',
                options: [
                  'Only singing songs.',
                  'Only wagging and roll over.',
                  'They use words while talking to express their needs, and they cry and make faces to express feelings.',
                  'They cannot communicate without a computer.',
                ],
                answer: 2,
                explainAr: 'النص: humans who use words while talking to express their needs and they cry and make faces when they want to express feelings. أي: الكلمات للحاجات، والبكاء وتعابير الوجه للمشاعر.',
              },
              {
                q: 'In what ways do animals communicate?',
                qAr: 'بأيّ طرق تتواصل الحيوانات؟',
                options: [
                  'With sounds and gestures, such as a bird singing or a dog wagging its tail.',
                  'With written words.',
                  'With a true language like humans.',
                  'They do not communicate at all.',
                ],
                answer: 0,
                explainAr: 'النص: they do communicate with each other with sounds and gestures، ومن أمثلتها: a bird singing a song or a dog wagging its tail when excited.',
              },
              {
                q: 'When do humans use signs like animals? And how do they develop them?',
                qAr: 'متى يستخدم البشر العلامات مثل الحيوانات؟ وكيف يطوّرونها؟',
                options: [
                  'When they are old; they forget the words of language.',
                  'When they are angry; they stop talking.',
                  'When they travel abroad; they learn a foreign language.',
                  'As babies, when crying and gesturing; then they slowly learn the words of language and use them.',
                ],
                answer: 3,
                explainAr: 'النص: Children show these same forms of communication as babies when crying and gesturing, but they slowly learn the words of language and use them as a form of communication.',
              },
              {
                q: 'What do dogs respond to, according to the text?',
                qAr: 'بحسب النص، لأيّ شيء تستجيب الكلاب؟',
                options: [
                  'The actual words.',
                  'The tone in which the words are said.',
                  'The songs of birds.',
                  'Written commands.',
                ],
                answer: 1,
                explainAr: 'النص: they do not respond to actual words but the tone in which it is said. أي أنها تستجيب لنبرة الصوت لا للكلمات نفسها.',
              },
              {
                q: 'Why do animals communicate with each other?',
                qAr: 'لماذا تتواصل الحيوانات فيما بينها؟',
                options: [
                  'To learn human language.',
                  'To follow their owners\' commands only.',
                  'In response to different motivations such as hunger or fear.',
                  'Because they want to talk like birds.',
                ],
                answer: 2,
                explainAr: 'النص: animals communicate with each other ... in response to different motivations such as hunger or fear. (motivations = دوافع).',
              },
            ],
            trueFalse: [
              { statement: 'Animals communicate with each other through sounds and gestures.', answer: true },
              { statement: 'Animals can slowly learn the words of the language and use them as a form of communication.', answer: false },
              { statement: 'Dogs follow the commands by being trained.', answer: true },
              { statement: 'Animals have a true language like us, humans.', answer: false },
            ],
          },
        ],
        exercises: u12Exercises,
      },
      compositions: [
        {
          source: 'book',
          topic: 'Complete the following paragraph by adding your own ideas. When I started travelling, one of my favourite things to do in order to stay connected with friends and family was …',
          topicAr: 'أكمل الفقرة التالية بإضافة أفكارك الخاصة. «عندما بدأت السفر، كان من أحبّ الأشياء التي أفعلها لأبقى على تواصل مع الأصدقاء والعائلة …»',
          words: 100,
          points: [
            'When I started travelling, one of my favourite things to do in order to stay connected with friends and family was …',
            'It was an exciting experience when I was able to talk to my family through …',
            'I was even able to use the …',
            'When I missed my mother\'s voice, I used to use …',
            'To send birthday cards or invitations I used to …',
          ],
          pointsAr: [
            'عندما بدأت السفر، كان من أحبّ الأشياء التي أفعلها لأبقى على تواصل مع الأصدقاء والعائلة …',
            'كانت تجربة مثيرة عندما تمكّنت من التحدّث إلى عائلتي عبر …',
            'بل تمكّنت أيضاً من استخدام …',
            'عندما كنت أشتاق إلى صوت أمي، كنت أستخدم …',
            'لإرسال بطاقات أعياد الميلاد أو الدعوات كنت …',
          ],
          plan: [
            { en: 'Sentence 1: your favourite way to stay connected (e.g. sending photographs on Facebook).', ar: 'الجملة 1: طريقتك المفضّلة للبقاء على تواصل (مثل إرسال الصور على فيسبوك).' },
            { en: 'Sentence 2: the program you used to talk to your family (e.g. Skype) and how it felt.', ar: 'الجملة 2: البرنامج الذي استخدمته لتتحدّث إلى عائلتك (مثل سكايب) وشعورك.' },
            { en: 'Sentence 3: something more you could do with it (e.g. a video call to attend a party).', ar: 'الجملة 3: شيء إضافي استطعت فعله (مثل مكالمة فيديو لحضور حفلة).' },
            { en: 'Sentences 4–5: how you heard your mother\'s voice and how you sent cards or invitations.', ar: 'الجملتان 4 و5: كيف كنت تسمع صوت أمك، وكيف كنت ترسل البطاقات أو الدعوات.' },
          ],
          phrases: [
            { en: 'stay connected with friends and family', ar: 'يبقى على تواصل مع الأصدقاء والعائلة' },
            { en: 'send photographs on Facebook', ar: 'يرسل الصور على فيسبوك' },
            { en: 'talk to my family through Skype', ar: 'يتحدّث إلى عائلته عبر سكايب' },
            { en: 'see their faces / facial expressions', ar: 'يرى وجوههم / تعابير وجوههم' },
            { en: 'a video call', ar: 'مكالمة فيديو' },
            { en: 'attend a birthday party', ar: 'يحضر حفلة عيد ميلاد' },
            { en: 'I used to …', ar: 'كنت (عادةً) … (عادة في الماضي)' },
            { en: 'my mobile phone', ar: 'هاتفي المحمول' },
            { en: 'write emails', ar: 'يكتب رسائل بريد إلكتروني' },
            { en: 'by pressing a button', ar: 'بالضغط على زرّ' },
          ],
          model: 'When I started travelling, one of my favourite things to do in order to stay connected with friends and family was sending photographs and short messages on Facebook every evening. It was an exciting experience when I was able to talk to my family through Skype and see their faces and their happy smiles on the screen. I was even able to use the video call to attend my little cousin\'s birthday party. When I missed my mother\'s voice, I used to use my mobile phone and call her at night. To send birthday cards or invitations I used to write emails and send them by pressing a button.',
          modelAr: 'عندما بدأت السفر، كان من أحبّ الأشياء التي أفعلها لأبقى على تواصل مع الأصدقاء والعائلة إرسال الصور والرسائل القصيرة على فيسبوك كل مساء. وكانت تجربة مثيرة عندما تمكّنت من التحدّث إلى عائلتي عبر سكايب ورؤية وجوههم وابتساماتهم السعيدة على الشاشة. بل تمكّنت أيضاً من استخدام مكالمة الفيديو لحضور حفلة عيد ميلاد ابن عمّي الصغير. وعندما كنت أشتاق إلى صوت أمي، كنت أستخدم هاتفي المحمول وأتصل بها ليلاً. ولإرسال بطاقات أعياد الميلاد أو الدعوات كنت أكتب رسائل بريد إلكتروني وأرسلها بالضغط على زرّ.',
          checklistAr: [
            'هل أكملت الجمل الخمس كلها بأفكار مناسبة؟',
            'هل انتبهت إلى ما يأتي بعد كل بداية (was + اسم أو -ing، through + وسيلة، used to + فعل مصدر)؟',
            'هل استخدمت used to + المصدر للعادات الماضية بشكل صحيح (I used to write)؟',
            'هل استخدمت كلمات التواصل من الوحدتين (Skype، photographs، video call، button)؟',
            'هل راجعت الإملاء والنقاط والحروف الكبيرة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write a paragraph about an event or a celebration you\'ve been to or read about.',
          topicAr: 'اكتب فقرة عن مناسبة أو احتفال حضرته أو قرأت عنه.',
          words: 100,
          points: [
            'kind of event',
            'date and place',
            'the important instructions to go there',
          ],
          pointsAr: [
            'نوع المناسبة',
            'التاريخ والمكان',
            'التعليمات المهمة للوصول إلى هناك',
          ],
          plan: [
            { en: 'Say what kind of event it was and whose event it was.', ar: 'اذكر نوع المناسبة ولمن كانت.' },
            { en: 'Give the date, the time and the place.', ar: 'اذكر التاريخ والوقت والمكان.' },
            { en: 'Give the important instructions to go there (bus, stop, directions).', ar: 'اذكر التعليمات المهمة للوصول (الحافلة، المحطة، الاتجاهات).' },
            { en: 'Describe what people did and felt (smiles, signs of happiness).', ar: 'صِف ما فعله الناس وما شعروا به (الابتسامات، علامات السعادة).' },
            { en: 'End with how you felt about the event.', ar: 'اختم بشعورك تجاه المناسبة.' },
          ],
          phrases: [
            { en: 'graduation party / birthday party / wedding', ar: 'حفلة تخرّج / حفلة عيد ميلاد / حفل زفاف' },
            { en: 'It was held on … at … in …', ar: 'أُقيمت في (يوم) … في (الساعة) … في (مكان) …' },
            { en: 'To get there, we took the bus from the city centre.', ar: 'للوصول إلى هناك أخذنا الحافلة من مركز المدينة.' },
            { en: 'decorated the garden themselves', ar: 'زيّنوا الحديقة بأنفسهم (ضمير انعكاسي)' },
            { en: 'I wore mine too.', ar: 'وأنا أيضاً لبست ملابسي (ضمير ملكية).' },
            { en: 'a clear sign of his happiness', ar: 'علامة واضحة على سعادته' },
            { en: 'a smile', ar: 'ابتسامة' },
            { en: 'took a lot of photographs', ar: 'التقطنا صوراً كثيرة' },
            { en: 'I really enjoyed myself.', ar: 'استمتعت كثيراً.' },
          ],
          model: 'Last summer, I went to my cousin Rami\'s graduation party. It was held on Friday, the fifth of July, at seven o\'clock in the evening in a big garden near the city centre. To get there, we took the bus from the city centre and got off at the last stop, then we walked for five minutes. Rami\'s family decorated the garden themselves with flowers and coloured lights. Everyone wore their best clothes, and I wore mine too. Rami\'s big smile was a clear sign of his happiness. We ate cakes, sang songs and took a lot of photographs. I really enjoyed myself that night.',
          modelAr: 'في الصيف الماضي ذهبت إلى حفلة تخرّج ابن عمّي رامي. أُقيمت يوم الجمعة، الخامس من تمّوز، في الساعة السابعة مساءً في حديقة كبيرة قرب مركز المدينة. وللوصول إلى هناك أخذنا الحافلة من مركز المدينة ونزلنا في المحطة الأخيرة، ثم مشينا خمس دقائق. زيّنت عائلة رامي الحديقة بأنفسهم بالأزهار والأضواء الملوّنة. ولبس الجميع أجمل ثيابهم، ولبست أنا أجمل ثيابي أيضاً. وكانت ابتسامة رامي الكبيرة علامة واضحة على سعادته. أكلنا الكعك وغنّينا والتقطنا صوراً كثيرة. لقد استمتعت كثيراً تلك الليلة.',
          checklistAr: [
            'هل ذكرت نوع المناسبة؟',
            'هل ذكرت التاريخ والمكان بوضوح؟',
            'هل كتبت التعليمات المهمة للوصول إلى المكان؟',
            'هل استخدمت الماضي البسيط لسرد ما حدث، وضمائر الملكية والانعكاس بشكل صحيح (mine، themselves، myself)؟',
            'هل ربطت الجمل بأدوات ربط (and، then، so)؟',
            'هل راجعت الإملاء والحروف الكبيرة وعلامات الترقيم، وكتبت نحو 100 كلمة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write a letter to a pen pal who is living abroad.',
          topicAr: 'اكتب رسالة إلى صديق مراسلة يعيش في الخارج. (مهمة الكتابة في اختبار التقدّم الثاني)',
          words: 100,
          plan: [
            { en: 'Greeting: Dear …, and one sentence saying why you are writing.', ar: 'التحية: Dear …، وجملة واحدة تذكر فيها سبب كتابتك.' },
            { en: 'Introduce yourself: name, age, city, school.', ar: 'عرّف بنفسك: الاسم والعمر والمدينة والمدرسة.' },
            { en: 'Tell about your interests and your country\'s culture.', ar: 'تحدّث عن اهتماماتك وعن ثقافة بلدك.' },
            { en: 'Ask your pen pal polite questions about his/her life and country.', ar: 'اسأل صديقك أسئلة مهذّبة عن حياته وبلده.' },
            { en: 'Closing: Write back soon. Best wishes, and your name.', ar: 'الخاتمة: اكتب لي قريباً. مع أطيب التمنيات، ثم اسمك.' },
          ],
          phrases: [
            { en: 'Dear …,', ar: 'عزيزي …،' },
            { en: 'I\'m writing to tell you about myself and my country.', ar: 'أكتب إليك لأخبرك عن نفسي وعن بلدي.' },
            { en: 'make friends from all around the world', ar: 'يكوّن صداقات من جميع أنحاء العالم' },
            { en: 'sign up to a pen pal website', ar: 'يشترك في موقع لأصدقاء المراسلة' },
            { en: 'my interests', ar: 'اهتماماتي' },
            { en: 'a city which is on the coast', ar: 'مدينة تقع على الساحل (جملة موصولة)' },
            { en: 'different cultures and life styles', ar: 'ثقافات وأنماط حياة مختلفة' },
            { en: 'learn about new experiences', ar: 'يتعرّف على تجارب جديدة' },
            { en: 'meet you face to face', ar: 'ألقاك وجهاً لوجه' },
            { en: 'Write back soon. Best wishes,', ar: 'اكتب لي قريباً. مع أطيب التمنيات،' },
          ],
          model: 'Dear Tom,\nThank you for your last letter. I\'m writing to tell you about myself and my country. My name is Sami, and I\'m fifteen years old. I live in Latakia, a city which is on the coast of Syria. I\'m in Grade 9, so I study hard for the big exam at the end of the year. In my free time, I play football and read books which have happy endings. Syria is famous for its old cities, and many of them were built thousands of years ago. What is life like in your country? What do you usually do at the weekend? I would like to visit you one day and meet you face to face.\nWrite back soon.\nBest wishes,\nSami',
          modelAr: 'عزيزي توم،\nشكراً على رسالتك الأخيرة. أكتب إليك لأخبرك عن نفسي وعن بلدي. اسمي سامي، وعمري خمس عشرة سنة. أعيش في اللاذقية، وهي مدينة تقع على ساحل سورية. أنا في الصف التاسع، لذلك أدرس بجدّ للامتحان الكبير في نهاية العام. وفي وقت فراغي ألعب كرة القدم وأقرأ كتباً لها نهايات سعيدة. سورية مشهورة بمدنها القديمة، وكثير منها بُني قبل آلاف السنين. كيف هي الحياة في بلدك؟ ماذا تفعل عادةً في عطلة نهاية الأسبوع؟ أودّ أن أزورك يوماً ما وألقاك وجهاً لوجه.\nاكتب لي قريباً.\nمع أطيب التمنيات،\nسامي',
          checklistAr: [
            'هل بدأت بتحية مناسبة (Dear …,) وختمت بخاتمة مناسبة (Best wishes, + اسمك)؟',
            'هل عرّفت بنفسك وببلدك؟',
            'هل سألت صديقك أسئلة مهذّبة صحيحة الترتيب؟',
            'هل استخدمت قواعد الوحدتين: المبني للمجهول (were built) والجمل الموصولة (which / who)؟',
            'هل قسّمت الرسالة إلى تحية ونصّ وخاتمة؟',
            'هل راجعت الإملاء والحروف الكبيرة وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'Scientists are still unsure about this question.', ar: 'ما زال العلماء غير متأكّدين من إجابة هذا السؤال.' },
        { en: 'Researchers say that animals do not have a true language like humans.', ar: 'يقول الباحثون إن الحيوانات لا تملك لغةً حقيقية مثل البشر.' },
        { en: 'However, they do communicate with each other with sounds and gestures.', ar: 'ومع ذلك فهي تتواصل فعلاً فيما بينها بالأصوات والإيماءات.' },
        { en: 'I looked at myself for a long time.', ar: 'نظرت إلى نفسي مدّة طويلة.' },
        { en: 'Please give me that book. It is mine.', ar: 'من فضلك أعطني ذلك الكتاب. إنه لي.' },
        { en: 'My father bought a new car. It is ours.', ar: 'اشترى أبي سيارة جديدة. إنها لنا.' },
        { en: 'They live in a beautiful house. It is theirs.', ar: 'إنهم يعيشون في بيت جميل. إنه مُلكهم.' },
        { en: 'Jack can\'t come to the party, can he?', ar: 'جاك لا يستطيع أن يأتي إلى الحفلة، أليس كذلك؟' },
        { en: 'Body language refers to the nonverbal signals that we use to communicate.', ar: 'تشير لغة الجسد إلى الإشارات غير اللفظية التي نستخدمها للتواصل.' },
        { en: 'According to experts, these nonverbal signals make up a huge part of our daily communication.', ar: 'بحسب الخبراء، تشكّل هذه الإشارات غير اللفظية جزءاً كبيراً من تواصلنا اليومي.' },
        { en: 'A smile may indicate approval or happiness.', ar: 'قد تدلّ الابتسامة على الموافقة أو السعادة.' },
        { en: 'A frown can signal disapproval or unhappiness.', ar: 'قد يدلّ العبوس على عدم الموافقة أو التعاسة.' },
        { en: 'Facial expressions are also among the universal forms of body language.', ar: 'تعابير الوجه هي أيضاً من أشكال لغة الجسد العالمية.' },
        { en: 'The expressions used to convey fear, anger, sadness, and happiness are similar throughout the world.', ar: 'التعابير المستخدمة لنقل الخوف والغضب والحزن والسعادة متشابهة في جميع أنحاء العالم.' },
        { en: 'Crossing the arms can indicate defence, being self-protective.', ar: 'قد يدلّ تشبيك الذراعين على الدفاع، أي حماية النفس.' },
        { en: 'Crossed legs can indicate that a person is feeling in need of privacy.', ar: 'قد تدلّ الساقان المتصالبتان على أن الشخص يشعر بحاجة إلى الخصوصية.' },
      ],
    },
  },

  progressTest: {
    title: 'Progress Test (II)',
    titleAr: 'اختبار التقدّم الثاني',
    pages: '61–64',
    reading: {
      title: 'Overseas Pen Friends',
      paragraphs: [
        'Most people are curious about different countries and their cultures. So, some tend to make friends from all around the world.',
        'Making friends from all over the world is easy nowadays. We only have to sign up to a pen pal website under the supervision of parents. When we create a profile, we will be asked to fill out basic details about ourselves; like our interests, the country we are from, and our birth date. We will be able to have conversations with new friends in different countries, so learning another language can help us build bonds with people that speak foreign languages. We must be polite when asking them about their lives and things that they are interested in. Being a nice person and willing to learn about new experiences will help you make friends wherever you go. If we have the chance to travel one day, we may meet these friends face to face. We have to keep in mind that different people in different countries have different cultures and different life styles which enrich our knowledge about various topics. We have to respect other people\'s privacy and try to learn the best from them.',
      ],
      paragraphsAr: [
        'معظم الناس فضوليون لمعرفة البلدان المختلفة وثقافاتها. لذلك يميل بعضهم إلى تكوين صداقات من جميع أنحاء العالم.',
        'أصبح تكوين الصداقات من جميع أنحاء العالم سهلاً في هذه الأيام. فكل ما علينا هو أن نشترك في موقع لأصدقاء المراسلة تحت إشراف الأهل. وعندما ننشئ ملفاً شخصياً، سيُطلب منا أن نملأ معلومات أساسية عن أنفسنا، مثل اهتماماتنا والبلد الذي ننتمي إليه وتاريخ ميلادنا. وسنتمكّن من إجراء محادثات مع أصدقاء جدد في بلدان مختلفة، لذا فإن تعلّم لغة أخرى يمكن أن يساعدنا على بناء روابط مع أشخاص يتحدّثون لغات أجنبية. ويجب أن نكون مهذّبين عندما نسألهم عن حياتهم وعن الأشياء التي يهتمّون بها. إن كونك شخصاً لطيفاً ومستعداً للتعرّف على تجارب جديدة سيساعدك على تكوين صداقات أينما ذهبت. وإذا سنحت لنا الفرصة للسفر يوماً ما، فقد نلتقي هؤلاء الأصدقاء وجهاً لوجه. وعلينا أن نتذكّر أن الناس في البلدان المختلفة لديهم ثقافات مختلفة وأنماط حياة مختلفة تُغني معرفتنا بمواضيع متنوّعة. وعلينا أن نحترم خصوصية الآخرين وأن نحاول أن نتعلّم منهم أفضل ما لديهم.',
      ],
      questions: [
        {
          q: 'How can we make friends nowadays?',
          qAr: 'كيف يمكننا أن نكوّن صداقات في هذه الأيام؟',
          options: [
            'By travelling to every country in the world.',
            'By signing up to a pen pal website under the supervision of parents.',
            'By learning about their birth date only.',
            'By sending letters to strangers without our parents\' knowledge.',
          ],
          answer: 1,
          explainAr: 'النص: We only have to sign up to a pen pal website under the supervision of parents. (under the supervision of parents = تحت إشراف الأهل).',
        },
        {
          q: 'Why is it necessary to learn a foreign language?',
          qAr: 'لماذا من الضروري أن نتعلّم لغة أجنبية؟',
          options: [
            'Because it helps us build bonds with people that speak foreign languages.',
            'Because we must fill out our profile in a foreign language.',
            'Because we cannot travel without it.',
            'Because our parents ask us to.',
          ],
          answer: 0,
          explainAr: 'النص: learning another language can help us build bonds with people that speak foreign languages. (build bonds = نبني روابط وعلاقات).',
        },
        {
          q: 'What helps us to make friends?',
          qAr: 'ما الذي يساعدنا على تكوين الصداقات؟',
          options: [
            'Having a lot of money.',
            'Asking people about their privacy.',
            'Being a nice person and willing to learn about new experiences.',
            'Staying in our own neighbourhood.',
          ],
          answer: 2,
          explainAr: 'النص: Being a nice person and willing to learn about new experiences will help you make friends wherever you go.',
        },
        {
          q: 'In your opinion, what do people usually like to know about others in different countries?',
          qAr: 'برأيك، ماذا يحبّ الناس عادةً أن يعرفوا عن الآخرين في البلدان المختلفة؟',
          options: [
            'Their passwords and private secrets.',
            'Nothing at all.',
            'Only the price of their houses.',
            'Their lives, their interests, their cultures and their life styles.',
          ],
          answer: 3,
          explainAr: 'سؤال رأي، لكن النص يساعدنا: people are curious about different countries and their cultures، ونسألهم about their lives and things that they are interested in. ولا نسأل عن الأسرار لأننا يجب أن نحترم خصوصيتهم (privacy).',
        },
        {
          q: 'Complete: Most people care about …',
          qAr: 'أكمل: معظم الناس يهتمّون بـ …',
          options: [
            'different countries and their cultures.',
            'their birth date only.',
            'pen pal websites only.',
            'other people\'s privacy.',
          ],
          answer: 0,
          explainAr: 'care about = are curious about. الجملة الأولى في النص: Most people are curious about different countries and their cultures.',
        },
        {
          q: 'Complete: We make relations with people …',
          qAr: 'أكمل: نبني علاقات مع أشخاص …',
          options: [
            'who live next door only.',
            'that speak foreign languages.',
            'who never use the internet.',
            'who have the same birth date as ours.',
          ],
          answer: 1,
          explainAr: 'make relations = build bonds. النص: learning another language can help us build bonds with people that speak foreign languages.',
        },
        {
          q: 'Complete: We have to remember that people in other countries have …',
          qAr: 'أكمل: علينا أن نتذكّر أن الناس في البلدان الأخرى لديهم …',
          options: [
            'the same life style as ours.',
            'no interest in other cultures.',
            'different cultures and different life styles.',
            'the same language as ours.',
          ],
          answer: 2,
          explainAr: 'remember = keep in mind. النص: We have to keep in mind that different people in different countries have different cultures and different life styles.',
        },
        {
          q: 'Complete: Being polite with people means to …',
          qAr: 'أكمل: أن تكون مهذّباً مع الناس يعني أن …',
          options: [
            'ask them about all their secrets.',
            'talk only about yourself.',
            'never ask them any questions.',
            'respect other people\'s privacy and try to learn the best from them.',
          ],
          answer: 3,
          explainAr: 'النص: We must be polite when asking them about their lives ... We have to respect other people\'s privacy and try to learn the best from them.',
        },
      ],
    },
    exercises: testExercises,
  },
}
