import type { ModuleExtras } from './merge'

// Activity Book (Workbook) pages, writing tasks as guided compositions, and translation sentences
// for Module 5 "Culture": Unit 9 = Activity Book pages 68–73, Unit 10 = Activity Book pages 74–81.
// No Progress Test in this module.

const HOMO_OPTS = (w: string, a: string, b: string) => [
  `${w}¹ = b (${b}) · ${w}² = a (${a})`,
  `${w}¹ = a (${a}) · ${w}² = b (${b})`,
  `${w}¹ = a · ${w}² = a (both ${a})`,
  `${w}¹ = b · ${w}² = b (both ${b})`,
]

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 9 — Citizenship (Activity Book pages 68–73) =====================
    u9: {
      workbook: {
        pages: "68–73",
        readings: [
          {
            title: "Our Duties and Responsibilities in Society",
            paragraphs: [
              "Living in a society means we share both rights and duties. While enjoying rights like education and safety, we must also contribute to the common good. Understanding our duties ensures a balanced, fair community where everyone thrives.",
              "Firstly, we have basic duties: obeying laws that protect order, paying taxes to fund services like healthcare and schools, and showing respect for others’ rights and dignity. These actions create trust and stability.",
              "Beyond this, active participation strengthens society. Volunteering for example allows us to meet the local needs, like protecting the environment—through recycling or reducing waste—which is considered vital for future generations.",
              "Personal responsibility matters too. Pursuing education and maintaining health empower us to contribute effectively. Staying informed about global and local issues helps us make thoughtful and powerful decisions.",
              "Empathy bridges individual and collective well-being. Supporting those facing hardships - through kindness or charity- fosters solidarity. Even small acts, like aiding a neighbour, ripple into broader positive change.",
              "Ultimately, a harmonious society relies on everyone’s effort. By embracing our roles with dedication and compassion, we build a foundation for progress. Each responsible choice, no matter how minor, weaves into the larger tapestry of a just, sustainable world. Let’s commit to these duties, knowing that together, we shape tomorrow.",
            ],
            paragraphsAr: [
              "العيش في مجتمع يعني أننا نتشارك الحقوق والواجبات معاً. فبينما نتمتّع بحقوق مثل التعليم والأمان، يجب علينا أيضاً أن نُسهم في الصالح العام. وفهمُنا لواجباتنا يضمن مجتمعاً متوازناً وعادلاً يزدهر فيه الجميع.",
              "أولاً، لدينا واجبات أساسية: طاعة القوانين التي تحمي النظام، ودفع الضرائب لتمويل خدمات مثل الرعاية الصحية والمدارس، وإظهار الاحترام لحقوق الآخرين وكرامتهم. هذه الأفعال تبني الثقة والاستقرار.",
              "وأبعد من ذلك، فإن المشاركة الفعّالة تقوّي المجتمع. فالتطوّع مثلاً يتيح لنا تلبية الاحتياجات المحلية، مثل حماية البيئة — عن طريق إعادة التدوير أو تقليل النفايات — وهو أمر يُعدّ حيوياً للأجيال القادمة.",
              "والمسؤولية الشخصية مهمة أيضاً. فمتابعة التعليم والمحافظة على الصحة تمنحاننا القدرة على الإسهام بفعالية. والبقاء على اطّلاع على القضايا العالمية والمحلية يساعدنا على اتخاذ قرارات مدروسة وقوية.",
              "التعاطف يصل بين رفاهية الفرد ورفاهية الجماعة. ودعم الذين يواجهون المصاعب — بالّلطف أو بالعمل الخيري — يعزّز التضامن. وحتى الأفعال الصغيرة، مثل مساعدة جار، تمتدّ آثارها لتصنع تغييراً إيجابياً أوسع.",
              "وفي النهاية، يعتمد المجتمع المتناغم على جهد كل فرد فيه. فبتقبّلنا أدوارنا بإخلاص ورحمة نبني أساساً للتقدّم. وكل خيار مسؤول، مهما كان صغيراً، يُنسَج في اللوحة الكبيرة لعالم عادل ومستدام. فلنلتزم بهذه الواجبات، ونحن نعلم أننا معاً نصنع الغد.",
            ],
            questions: [
              { q: "1. Name two basic duties mentioned in the text.", qAr: "1. اذكر واجبين أساسيين ورد ذكرهما في النص.", options: ["Obeying laws and paying taxes", "Volunteering and recycling", "Pursuing education and maintaining health", "Aiding a neighbour and giving to charity"], answer: 0, explainAr: "الفقرة الثانية: basic duties: obeying laws that protect order, paying taxes … and showing respect for others’ rights. أما التطوّع وإعادة التدوير فهي من المشاركة الفعّالة، والتعليم والصحة من المسؤولية الشخصية." },
              { q: "2. What are two examples of services funded by taxes?", qAr: "2. ما مثالان على الخدمات التي تُموَّل بالضرائب؟", options: ["Recycling and reducing waste", "Healthcare and schools", "Kindness and charity", "Order and stability"], answer: 1, explainAr: "النص: paying taxes to fund services like healthcare and schools — أي دفع الضرائب لتمويل خدمات مثل الرعاية الصحية والمدارس." },
              { q: "3. What environmental actions does the text suggest to protect future generations?", qAr: "3. ما الأفعال البيئية التي يقترحها النص لحماية الأجيال القادمة؟", options: ["Paying taxes and obeying laws", "Staying informed about global issues", "Recycling and reducing waste", "Aiding a neighbour"], answer: 2, explainAr: "الفقرة الثالثة: protecting the environment—through recycling or reducing waste—which is considered vital for future generations." },
              { q: "4. Why is personal health mentioned as a responsibility to society?", qAr: "4. لماذا ذُكرت الصحة الشخصية على أنها مسؤولية تجاه المجتمع؟", options: ["Because healthcare is paid for by taxes", "Because maintaining health empowers us to contribute effectively", "Because it is a basic duty that protects order", "Because it helps us stay informed about local issues"], answer: 1, explainAr: "الفقرة الرابعة: Pursuing education and maintaining health empower us to contribute effectively — المحافظة على الصحة تجعلنا قادرين على الإسهام بفعالية في المجتمع." },
              { q: "5. According to the text, what fosters solidarity?", qAr: "5. بحسب النص، ما الذي يعزّز التضامن؟", options: ["Paying taxes", "Supporting those facing hardships through kindness or charity", "Staying informed about global issues", "Obeying laws that protect order"], answer: 1, explainAr: "الفقرة الخامسة: Supporting those facing hardships - through kindness or charity- fosters solidarity." },
              { q: "6. What does a harmonious society rely on?", qAr: "6. علامَ يعتمد المجتمع المتناغم؟", options: ["The government only", "Everyone’s effort", "Rich people’s charity", "Laws only"], answer: 1, explainAr: "الفقرة الأخيرة: Ultimately, a harmonious society relies on everyone’s effort — على جهد الجميع." },
            ],
            trueFalse: [
              { statement: "Paying taxes provides money for services like healthcare and schools.", answer: true },
              { statement: "Obeying laws is optional if you disagree with them.", answer: false },
              { statement: "Protecting the environment is only important for the current generation.", answer: false },
              { statement: "Empathy has a vital connection to collective well-being.", answer: true },
            ],
          },
        ],
        exercises: [
          // ---- Reading a: match the words to their definitions (p. 68)
          { type: "mcq", prompt: "Match the word to its definition: common good", promptAr: "طابق الكلمة مع تعريفها: common good (الصالح العام)", options: ["the well-being and benefit of all people in a community", "unity and support among people, especially during hardships", "continual for a long time", "to give somebody the power to do something"], answer: 0, explainAr: "common good = الصالح العام، أي خير جميع الناس في المجتمع ومنفعتهم (d). وفي النص: we must also contribute to the common good." },
          { type: "mcq", prompt: "Match the word to its definition: thrive", promptAr: "طابق الكلمة مع تعريفها: thrive (يزدهر)", options: ["a deep sympathy for another’s suffering and a desire to help", "to become successful, strong, healthy, etc.", "to give somebody the power to do something", "continual for a long time"], answer: 1, explainAr: "thrive = يزدهر وينجح ويصبح قوياً (e). وفي النص: a balanced, fair community where everyone thrives." },
          { type: "mcq", prompt: "Match the word to its definition: empower", promptAr: "طابق الكلمة مع تعريفها: empower (يمكّن / يمنح القدرة)", options: ["to become successful, strong, healthy, etc.", "the well-being and benefit of all people in a community", "to give somebody the power to do something", "unity and support among people, especially during hardships"], answer: 2, explainAr: "empower = يمنح شخصاً القدرة على فعل شيء (f). وفي النص: Pursuing education and maintaining health empower us to contribute effectively." },
          { type: "mcq", prompt: "Match the word to its definition: compassion", promptAr: "طابق الكلمة مع تعريفها: compassion (الرحمة / الشفقة)", options: ["unity and support among people, especially during hardships", "a deep sympathy for another’s suffering and a desire to help", "continual for a long time", "to become successful, strong, healthy, etc."], answer: 1, explainAr: "compassion = تعاطف عميق مع معاناة الآخرين ورغبة في مساعدتهم (c). وفي النص: with dedication and compassion." },
          { type: "mcq", prompt: "Match the word to its definition: solidarity", promptAr: "طابق الكلمة مع تعريفها: solidarity (التضامن)", options: ["a deep sympathy for another’s suffering and a desire to help", "the well-being and benefit of all people in a community", "unity and support among people, especially during hardships", "to give somebody the power to do something"], answer: 2, explainAr: "solidarity = الوحدة والدعم بين الناس، خصوصاً في الأوقات الصعبة (a). وفي النص: Supporting those facing hardships … fosters solidarity." },
          { type: "mcq", prompt: "Match the word to its definition: sustainable", promptAr: "طابق الكلمة مع تعريفها: sustainable (مستدام)", options: ["continual for a long time", "to become successful, strong, healthy, etc.", "unity and support among people, especially during hardships", "the well-being and benefit of all people in a community"], answer: 0, explainAr: "sustainable = مستدام، يستمر لوقت طويل (b). وفي النص: a just, sustainable world." },
          // ---- Vocabulary: use words from the list (p. 69) — laws, respect, taxes, voting, balanced, environment
          { type: "fill", prompt: "Fulfilling our responsibilities leads to a ___ society where equality thrives.", promptAr: "القيام بمسؤولياتنا يؤدي إلى مجتمع ___ تزدهر فيه المساواة.", promptArFull: "القيام بمسؤولياتنا يؤدي إلى مجتمع متوازن تزدهر فيه المساواة.", options: ["voting", "balanced", "laws", "respect"], answer: 1, explainAr: "بين a والاسم society نحتاج صفة: balanced (متوازن). والنص يقول: Understanding our duties ensures a balanced, fair community." },
          { type: "fill", prompt: "Following ___ is a basic duty that prevents chaos and harm.", promptAr: "اتّباع ___ واجب أساسي يمنع الفوضى والأذى.", promptArFull: "اتّباع القوانين واجب أساسي يمنع الفوضى والأذى.", options: ["taxes", "laws", "environment", "voting"], answer: 1, explainAr: "نتّبع القوانين (Following laws) فتمنع الفوضى؛ وفي النص: obeying laws that protect order." },
          { type: "fill", prompt: "Citizens’ ___ fund infrastructure, healthcare, and education systems.", promptAr: "___ المواطنين تموّل البنية التحتية والرعاية الصحية وأنظمة التعليم.", promptArFull: "ضرائب المواطنين تموّل البنية التحتية والرعاية الصحية وأنظمة التعليم.", options: ["respect", "voting", "taxes", "laws"], answer: 2, explainAr: "الضرائب هي التي تموّل الخدمات: paying taxes to fund services like healthcare and schools. والفعل fund جمع فيحتاج فاعلاً جمعاً: taxes." },
          { type: "fill", prompt: "Preserving the ___ safeguards natural resources for those who come after us.", promptAr: "الحفاظ على ___ يصون الموارد الطبيعية لمن يأتون بعدنا.", promptArFull: "الحفاظ على البيئة يصون الموارد الطبيعية لمن يأتون بعدنا.", options: ["environment", "balanced", "taxes", "voting"], answer: 0, explainAr: "بعد the نحتاج اسماً، والموارد الطبيعية جزء من البيئة: the environment. وفي النص: protecting the environment … vital for future generations." },
          { type: "fill", prompt: "Treating others with ___ builds mutual trust and social cohesion.", promptAr: "معاملة الآخرين بـ___ تبني الثقة المتبادلة والتماسك الاجتماعي.", promptArFull: "معاملة الآخرين باحترام تبني الثقة المتبادلة والتماسك الاجتماعي.", options: ["laws", "respect", "voting", "balanced"], answer: 1, explainAr: "treat someone with respect = يعامل شخصاً باحترام. وفي النص: showing respect for others’ rights … These actions create trust. (كلمة voting زائدة في القائمة ولا تُستخدم)." },
          // ---- Pronunciation: Homographs (p. 70) — match the bold words with a or b
          { type: "mcq", prompt: "1. I object¹ to that object² in class because a cell phone is distracting. (a. noun /ˈɒb•dʒɪkt/: an item — b. verb /əbˈdʒekt/: to disagree)", promptAr: "1. أنا أعترض¹ على ذلك الشيء² في الصف لأن الهاتف الخلوي يشتّت الانتباه. طابق كل كلمة مع a أو b.", options: HOMO_OPTS("object", "noun, an item", "verb, to disagree"), answer: 0, explainAr: "بعد الفاعل I نحتاج فعلاً: object¹ = يعترض (b) ويُلفظ /əbˈdʒekt/ بنبرة على المقطع الثاني. وبعد that نحتاج اسماً: object² = شيء (a) ويُلفظ /ˈɒbdʒɪkt/ بنبرة على المقطع الأول." },
          { type: "mcq", prompt: "2. It is the perfect time to present¹ the present² to your mother. (a. verb /prɪˈzent/: to offer or give — b. noun /ˈprez•ənt/: a gift)", promptAr: "2. إنه الوقت المثالي لتقديم¹ الهدية² إلى أمك. طابق كل كلمة مع a أو b.", options: HOMO_OPTS("present", "verb, to offer or give", "noun, a gift"), answer: 1, explainAr: "بعد to نحتاج فعلاً: present¹ = يقدّم (a) /prɪˈzent/ بنبرة على المقطع الثاني. وبعد the نحتاج اسماً: present² = هدية (b) /ˈprezənt/ بنبرة على المقطع الأول." },
          { type: "mcq", prompt: "3. She has tears¹ in her eyes whenever she tears² old photos. (a. verb /teər/: to damage — b. noun /tɪər/: drops of liquid come out of eyes)", promptAr: "3. تمتلئ عيناها بالدموع¹ كلما مزّقت² صوراً قديمة. طابق كل كلمة مع a أو b.", options: HOMO_OPTS("tears", "verb, to damage", "noun, drops from the eyes"), answer: 0, explainAr: "tears¹ جاءت بعد has وقبل in her eyes فهي اسم = دموع (b) وتُلفظ /tɪər/. و tears² جاءت بعد الفاعل she فهي فعل = يمزّق (a) ويُلفظ /teər/." },
          { type: "mcq", prompt: "4. The bandage was wound¹ around the wound². (a. noun /wuːnd/: an injury in the skin — b. verb /waʊnd/: twisted or wrapped around)", promptAr: "4. لُفَّت¹ الضمادة حول الجرح². طابق كل كلمة مع a أو b.", options: HOMO_OPTS("wound", "noun, an injury", "verb, wrapped around"), answer: 0, explainAr: "was wound¹ مبني للمجهول: wound هنا التصريف الثالث للفعل wind = لُفّ (b) ويُلفظ /waʊnd/. وبعد the نحتاج اسماً: wound² = جرح (a) ويُلفظ /wuːnd/." },
          { type: "mcq", prompt: "5. How long will the live¹ fish live² without food? (a. verb /lɪv/: to survive — b. adjective /laɪv/: not dead)", promptAr: "5. كم ستعيش² السمكة الحيّة¹ بدون طعام؟ طابق كل كلمة مع a أو b.", options: HOMO_OPTS("live", "verb, to survive", "adjective, not dead"), answer: 0, explainAr: "live¹ جاءت بين the والاسم fish فهي صفة = حيّ (b) وتُلفظ /laɪv/. و live² جاءت بعد will فهي فعل = يعيش (a) ويُلفظ /lɪv/." },
          { type: "mcq", prompt: "6. The shoes were too close¹ to the door for it to close² completely. (a. adjective /kləʊs/: near — b. verb /kləʊz/: to shut)", promptAr: "6. كان الحذاء قريباً¹ جداً من الباب فلم يُغلَق² تماماً. طابق كل كلمة مع a أو b.", options: HOMO_OPTS("close", "adjective, near", "verb, to shut"), answer: 1, explainAr: "too close¹ to the door: صفة = قريب (a) وتُلفظ /kləʊs/ بصوت s. و to close²: فعل بعد to = يُغلق (b) ويُلفظ /kləʊz/ بصوت z." },
          // ---- Grammar a: Paired conjunctions — complete with is / are / have / has (p. 70)
          { type: "fill", prompt: "Both the teacher and the student ___ here.", promptAr: "كلٌّ من المعلّم والطالب ___ هنا.", promptArFull: "كلٌّ من المعلّم والطالب موجودان هنا.", options: ["is", "are", "has", "have"], answer: 1, explainAr: "مع both … and يكون الفاعل شخصين، فالفعل دائماً جمع: are." },
          { type: "fill", prompt: "Neither the teacher nor the student ___ here.", promptAr: "لا المعلّم ولا الطالب ___ هنا.", promptArFull: "لا المعلّم ولا الطالب موجود هنا.", options: ["are", "is", "have", "has"], answer: 1, explainAr: "مع neither … nor يتبع الفعل الفاعل الأقرب إليه: the student مفرد، إذن is. (والفعل مثبت لأن neither … nor منفية أصلاً)." },
          { type: "fill", prompt: "Not only the teacher but also the student ___ here.", promptAr: "ليس المعلّم فقط بل الطالب أيضاً ___ هنا.", promptArFull: "ليس المعلّم فقط بل الطالب أيضاً موجود هنا.", options: ["are", "have", "is", "has"], answer: 2, explainAr: "مع not only … but also ننظر إلى الفاعل الأقرب إلى الفعل: the student مفرد، إذن is." },
          { type: "fill", prompt: "Not only my brother but also my sister ___ a doctorate in science.", promptAr: "ليس أخي فقط بل أختي أيضاً ___ دكتوراه في العلوم.", promptArFull: "ليس أخي فقط بل أختي أيضاً تحمل دكتوراه في العلوم.", options: ["have", "has", "is", "are"], answer: 1, explainAr: "المعنى «يملك / يحمل» فنحتاج have أو has، والفاعل الأقرب my sister مفرد، إذن has." },
          { type: "fill", prompt: "Either the students or the teacher ___ planning to come.", promptAr: "إمّا الطلاب أو المعلّم ___ يخطّط للمجيء.", promptArFull: "إمّا الطلاب أو المعلّم هو من يخطّط للمجيء.", options: ["are", "is", "have", "has"], answer: 1, explainAr: "بعد الفراغ planning (ing) فنحتاج is / are. ومع either … or يتبع الفعل الفاعل الأقرب: the teacher مفرد، إذن is." },
          { type: "fill", prompt: "Either the teacher or the students ___ planned to come.", promptAr: "إمّا المعلّم أو الطلاب ___ خطّطوا للمجيء.", promptArFull: "إمّا المعلّم أو الطلاب قد خطّطوا للمجيء.", options: ["has", "have", "is", "are"], answer: 1, explainAr: "بعد الفراغ التصريف الثالث planned، فنحتاج has / have (المضارع التام). والفاعل الأقرب the students جمع، إذن have." },
          { type: "fill", prompt: "Either my brother or my sister ___ going to tutor me in science.", promptAr: "إمّا أخي أو أختي ___ سيدرّسني العلوم.", promptArFull: "إمّا أخي أو أختي هو من سيدرّسني العلوم.", options: ["are", "is", "has", "have"], answer: 1, explainAr: "going to يحتاج is / are قبله. والفاعل الأقرب my sister مفرد، إذن is." },
          { type: "fill", prompt: "Neither my brother nor my sisters ___ teachers.", promptAr: "لا أخي ولا أخواتي ___ معلّمين.", promptArFull: "لا أخي ولا أخواتي معلّمون.", options: ["is", "has", "are", "have"], answer: 2, explainAr: "مع neither … nor يتبع الفعل الفاعل الأقرب: my sisters جمع، إذن are (والخبر teachers جمع أيضاً)." },
          // ---- Grammar b: Rewrite using paired conjunctions (p. 71)
          { type: "mcq", prompt: "Rewrite with a paired conjunction: I didn’t need to visit the Cathedral. You didn’t need to either.", promptAr: "أعد الكتابة باستخدام أداة ربط مزدوجة: لم أكن بحاجة إلى زيارة الكاتدرائية. وأنت لم تكن بحاجة إلى ذلك أيضاً.", options: ["Neither you nor I needed to visit the Cathedral.", "Neither you nor I didn’t need to visit the Cathedral.", "Either you or I needed to visit the Cathedral.", "Both you and I needed to visit the Cathedral."], answer: 0, explainAr: "الجملتان منفيتان (didn’t … either) فنستخدم neither … nor مع فعل مثبت: Neither you nor I needed … ولا نضع didn’t لأن neither … nor منفية بذاتها." },
          { type: "mcq", prompt: "Rewrite with a paired conjunction: A hammer might help us with this kind of work. In fact, a piece of stone might also work.", promptAr: "أعد الكتابة باستخدام أداة ربط مزدوجة: قد تساعدنا مطرقة في هذا النوع من العمل. وفي الحقيقة، قد تنفع قطعة حجر أيضاً.", options: ["Neither a hammer nor a piece of stone might help us with this kind of work.", "Either a hammer or a piece of stone might help us with this kind of work.", "Either a hammer nor a piece of stone might help us with this kind of work.", "Not only a hammer or also a piece of stone might help us with this kind of work."], answer: 1, explainAr: "الأداتان بديلتان (هذه أو تلك تنفع) فنستخدم either … or. انتبه: either تأتي مع or، و neither مع nor، ولا نخلط بينهما." },
          { type: "mcq", prompt: "Rewrite with a paired conjunction: You shouldn’t have called the police. Actually, it was silly of you to call the neighbours as well.", promptAr: "أعد الكتابة باستخدام أداة ربط مزدوجة: ما كان ينبغي أن تتصل بالشرطة. وفي الحقيقة، كان من السخف أن تتصل بالجيران أيضاً.", options: ["You should have called either the police or the neighbours.", "You should have called neither the police nor the neighbours.", "You should have called both the police and the neighbours.", "You shouldn’t have called neither the police nor the neighbours."], answer: 1, explainAr: "المعنى: الاتصال بالاثنين كان خطأً، فنستخدم neither … nor مع should have (مثبت): You should have called neither the police nor the neighbours. ويصحّ أيضاً: You shouldn’t have called either the police or the neighbours. أما shouldn’t مع neither فهو نفي مزدوج خاطئ." },
          { type: "mcq", prompt: "Rewrite with a paired conjunction: Breaking the silence was not the only good thing she did. She also said something very useful.", promptAr: "أعد الكتابة باستخدام أداة ربط مزدوجة: لم يكن كسر الصمت الشيء الجيد الوحيد الذي فعلته. فقد قالت أيضاً شيئاً مفيداً جداً.", options: ["She not only broke the silence but also said something very useful.", "She not only broke the silence but also says something very useful.", "She neither broke the silence nor said something very useful.", "She either broke the silence or said something very useful."], answer: 0, explainAr: "not the only … also = not only … but also. والتوازي مهم: فعلان ماضيان بعد الجزأين (broke … said)، لذلك says خطأ." },
          { type: "mcq", prompt: "Rewrite with a paired conjunction: Peter didn’t like the idea of going for a walk. His wife seemed quite unwilling too.", promptAr: "أعد الكتابة باستخدام أداة ربط مزدوجة: لم تعجب بيتر فكرة الخروج في نزهة سيراً. وبدت زوجته غير راغبة أيضاً.", options: ["Both Peter and his wife liked the idea of going for a walk.", "Neither Peter nor his wife didn’t like the idea of going for a walk.", "Neither Peter nor his wife liked the idea of going for a walk.", "Either Peter or his wife liked the idea of going for a walk."], answer: 2, explainAr: "كلاهما لم يرغب في النزهة، فنستخدم neither … nor مع فعل مثبت (liked)، لأن neither … nor تحمل معنى النفي." },
          { type: "mcq", prompt: "Rewrite with a paired conjunction: You can take Sally or any other person with you. I really don’t care that much.", promptAr: "أعد الكتابة باستخدام أداة ربط مزدوجة: يمكنك أن تأخذ سالي أو أي شخص آخر معك. لا يهمّني ذلك كثيراً.", options: ["You can take neither Sally nor any other person with you.", "You can take either Sally or any other person with you.", "You can take both Sally and any other person with you.", "You can take either Sally nor any other person with you."], answer: 1, explainAr: "المعنى اختيار بين بديلين (سالي أو غيرها)، فنستخدم either … or." },
          // ---- Everyday English: Accepting and Declining Offers — match the requests to the replies (p. 71)
          { type: "mcq", prompt: "1. We need to see Mr. Jackson and his team. Shall I arrange for an early meeting next week?", promptAr: "1. نحتاج إلى مقابلة السيد جاكسون وفريقه. هل أرتّب لاجتماع مبكر الأسبوع القادم؟ اختر الردّ المناسب.", options: ["Can you make it the week after? I need to write the report first.", "Sorry, I’m afraid I can’t at the moment, as the machine is broken. We’re waiting for someone to come and fix it.", "No problem. Shall I do the same with the faxes?", "Yes, of course. Do you want me to write the reply too?"], answer: 0, explainAr: "العرض عن موعد اجتماع، فالردّ المناسب يقترح موعداً آخر ويرفض بلطف: Can you make it the week after? (d)." },
          { type: "mcq", prompt: "2. I’m going to be late for the meeting, can you tell Rose for me?", promptAr: "2. سأتأخر عن الاجتماع، هل يمكنك أن تُخبر روز بذلك نيابةً عني؟ اختر الردّ المناسب.", options: ["No problem. Shall I do the same with the faxes?", "Sure. I don’t think it will start on time anyway.", "Can you make it the week after? I need to write the report first.", "Yes, of course. Do you want me to write the reply too?"], answer: 1, explainAr: "الحديث عن التأخر عن الاجتماع، والردّ يقبل ويطمئن: Sure. I don’t think it will start on time anyway (c) — لا أظن أنه سيبدأ في موعده على أي حال." },
          { type: "mcq", prompt: "3. I have a lot of things to do today, so could you do some photocopying for me?", promptAr: "3. لديّ أشياء كثيرة لأفعلها اليوم، فهل يمكنك أن تصوّر بعض الأوراق لي؟ اختر الردّ المناسب.", options: ["Sure. I don’t think it will start on time anyway.", "No problem. Shall I do the same with the faxes?", "Sorry, I’m afraid I can’t at the moment, as the machine is broken. We’re waiting for someone to come and fix it.", "Can you make it the week after? I need to write the report first."], answer: 2, explainAr: "التصوير يحتاج آلة، والردّ يرفض بلطف ويذكر السبب: Sorry, I’m afraid I can’t … the machine is broken (a)." },
          { type: "mcq", prompt: "4. I’ve just got a fax from Mr. Ramos in Paris. Could you read it and translate it for me, please?", promptAr: "4. وصلني للتوّ فاكس من السيد راموس في باريس. هل يمكنك أن تقرأه وتترجمه لي من فضلك؟ اختر الردّ المناسب.", options: ["Yes, of course. Do you want me to write the reply too?", "Sorry, I’m afraid I can’t at the moment, as the machine is broken. We’re waiting for someone to come and fix it.", "Sure. I don’t think it will start on time anyway.", "Can you make it the week after? I need to write the report first."], answer: 0, explainAr: "الفاكس رسالة تحتاج إلى ردّ، فالجواب يقبل ويعرض مساعدة إضافية: Yes, of course. Do you want me to write the reply too? (e)." },
          { type: "mcq", prompt: "5. I’m away next week. If I get any important e-mails, can you forward them to me?", promptAr: "5. سأكون غائباً الأسبوع القادم. إن وصلتني رسائل إلكترونية مهمة، هل يمكنك أن تعيد توجيهها إليّ؟ اختر الردّ المناسب.", options: ["Yes, of course. Do you want me to write the reply too?", "No problem. Shall I do the same with the faxes?", "Sure. I don’t think it will start on time anyway.", "Sorry, I’m afraid I can’t at the moment, as the machine is broken. We’re waiting for someone to come and fix it."], answer: 1, explainAr: "الطلب إعادة توجيه الرسائل، والردّ يقبل ويعرض الشيء نفسه للفاكسات: No problem. Shall I do the same with the faxes? (b)." },
        ],
      },
      compositions: [
        {
          source: "book",
          topic: "Write an article about what it takes to be a good citizen in your community.",
          topicAr: "اكتب مقالاً عمّا يلزم ليكون الإنسان مواطناً صالحاً في مجتمعك.",
          words: 100,
          points: ["Your article should include rights and duties of a citizen in your community."],
          pointsAr: ["يجب أن يتضمّن مقالك حقوق المواطن وواجباته في مجتمعك."],
          plan: [
            { en: "Introduction (topic sentence): being a good citizen means enjoying rights and doing duties.", ar: "المقدمة (الجملة الرئيسية): أن تكون مواطناً صالحاً يعني أن تتمتّع بالحقوق وتؤدي الواجبات." },
            { en: "Rights: what the government protects for every individual (education, safety, freedom, legal rights).", ar: "الحقوق: ما تحميه الدولة لكل فرد (التعليم، الأمان، الحرية، الحقوق القانونية)." },
            { en: "Duties: obligatory duties (obey laws, pay taxes) and voluntary ones (volunteering, helping neighbours, protecting the environment).", ar: "الواجبات: الإلزامية (طاعة القوانين، دفع الضرائب) والطوعية (التطوّع، مساعدة الجيران، حماية البيئة)." },
            { en: "Behaviour: be polite, respect others and teach good citizenship to future generations.", ar: "السلوك: التهذيب واحترام الآخرين وتعليم المواطنة الصالحة للأجيال القادمة." },
            { en: "Conclusion (clincher): your opinion — good citizens work together for the common good.", ar: "الخاتمة (جملة ختامية): رأيك — المواطنون الصالحون يعملون معاً من أجل الصالح العام." },
          ],
          phrases: [
            { en: "both rights and duties", ar: "الحقوق والواجبات معاً" },
            { en: "regardless of their background or culture", ar: "بغضّ النظر عن خلفيتهم أو ثقافتهم" },
            { en: "Although citizenship provides many rights, it also involves many responsibilities.", ar: "مع أن المواطنة تمنح حقوقاً كثيرة، فإنها تتضمّن أيضاً مسؤوليات كثيرة." },
            { en: "voluntary as well as obligatory", ar: "طوعية وإلزامية أيضاً" },
            { en: "obey state laws and pay taxes", ar: "يطيع قوانين الدولة ويدفع الضرائب" },
            { en: "not only … but also", ar: "ليس فقط … بل أيضاً" },
            { en: "neither … nor", ar: "لا … ولا" },
            { en: "be polite in everyday activities", ar: "يكون مهذّباً في أنشطته اليومية" },
            { en: "pass along the importance of good citizenship to future generations", ar: "ينقل أهمية المواطنة الصالحة إلى الأجيال القادمة" },
            { en: "contribute to the common good", ar: "يُسهم في الصالح العام" },
            { en: "pride ourselves on", ar: "نفخر بـ" },
            { en: "In my opinion, …", ar: "في رأيي، …" },
          ],
          model: "Being a good citizen means enjoying both rights and duties. In my community, the government protects the rights of each individual regardless of their background or culture. We have the right to education, safety, freedom and legal protection. Although citizenship provides many rights, it also involves many responsibilities. A good citizen must obey state laws and pay taxes. Some duties are voluntary as well as obligatory. For example, a good citizen should not only respect other people but also help his neighbours and protect the environment. He should be polite in everyday activities, too. Parents should pass along the importance of good citizenship to future generations. In my opinion, good citizens pride themselves on their country and contribute to the common good.",
          modelAr: "أن تكون مواطناً صالحاً يعني أن تتمتّع بالحقوق وتؤدي الواجبات معاً. في مجتمعي، تحمي الحكومة حقوق كل فرد بغضّ النظر عن خلفيته أو ثقافته. لنا الحق في التعليم والأمان والحرية والحماية القانونية. ومع أن المواطنة تمنح حقوقاً كثيرة، فإنها تتضمّن أيضاً مسؤوليات كثيرة. يجب على المواطن الصالح أن يطيع قوانين الدولة ويدفع الضرائب. وبعض الواجبات طوعية وبعضها إلزامي. فمثلاً، ينبغي للمواطن الصالح ألّا يحترم الآخرين فحسب، بل أن يساعد جيرانه ويحمي البيئة أيضاً. وينبغي أن يكون مهذّباً في أنشطته اليومية كذلك. وعلى الآباء أن ينقلوا أهمية المواطنة الصالحة إلى الأجيال القادمة. في رأيي، يفخر المواطنون الصالحون ببلدهم ويُسهمون في الصالح العام.",
          checklistAr: [
            "هل بدأت بجملة رئيسية واضحة تجيب عن السؤال: ما الذي يجعل الإنسان مواطناً صالحاً؟",
            "هل ذكرت الحقوق (التعليم، الأمان، الحرية) والواجبات (طاعة القوانين، دفع الضرائب) كما يطلب السؤال؟",
            "هل استخدمت أداة ربط مزدوجة واحدة على الأقل بشكل صحيح مع توافق الفعل (not only … but also / neither … nor)؟",
            "هل استخدمت روابط مثل Although / For example / In my opinion لتنظيم الأفكار؟",
            "هل أنهيت بجملة ختامية تلخّص رأيك؟",
            "هل راجعت الإملاء والأحرف الكبيرة وعلامات الترقيم، وطول المقال نحو 100 كلمة؟",
          ],
        },
        {
          source: "workbook",
          topic: "Write a composition of about 100 words about “The importance of law in people’s lives”.",
          topicAr: "اكتب موضوعاً إنشائياً من نحو 100 كلمة عن «أهمية القانون في حياة الناس».",
          words: 100,
          points: [
            "Why is it important?",
            "How should parents encourage their children to obey laws?",
            "What should schools do to empower the sense of dedication to law?",
            "What should be done to those who do not obey law?",
          ],
          pointsAr: [
            "لماذا هو مهم؟",
            "كيف ينبغي للآباء أن يشجّعوا أبناءهم على طاعة القوانين؟",
            "ماذا ينبغي للمدارس أن تفعل لتقوية الشعور بالالتزام بالقانون؟",
            "ماذا ينبغي أن يُفعل بمن لا يطيعون القانون؟",
          ],
          plan: [
            { en: "Topic sentence + why law is important: it protects order, safety and people’s rights; without laws there is chaos.", ar: "الجملة الرئيسية ولماذا القانون مهم: يحمي النظام والأمان وحقوق الناس، وبدون قوانين تعمّ الفوضى." },
            { en: "Parents: be good examples and teach children that obeying laws is not optional.", ar: "الآباء: أن يكونوا قدوة حسنة ويعلّموا أبناءهم أن طاعة القوانين ليست أمراً اختيارياً." },
            { en: "Schools: teach students their rights and duties and organise activities about good citizenship.", ar: "المدارس: تعليم الطلاب حقوقهم وواجباتهم وتنظيم أنشطة عن المواطنة الصالحة." },
            { en: "People who break the law: they must pay the penalties and be helped to understand their mistakes.", ar: "من يخالف القانون: يجب أن يدفع العقوبات وأن يُساعَد على فهم خطئه." },
            { en: "Clincher: both citizens and the government have to respect the law to build a just society.", ar: "الجملة الختامية: على المواطنين والحكومة معاً احترام القانون لبناء مجتمع عادل." },
          ],
          phrases: [
            { en: "Without laws, everything would be full of chaos.", ar: "بدون قوانين، سيكون كل شيء مليئاً بالفوضى." },
            { en: "obeying laws that protect order", ar: "طاعة القوانين التي تحمي النظام" },
            { en: "a balanced, fair community where everyone thrives", ar: "مجتمع متوازن وعادل يزدهر فيه الجميع" },
            { en: "regardless of their background", ar: "بغضّ النظر عن خلفيتهم" },
            { en: "Obeying laws is not optional.", ar: "طاعة القوانين ليست أمراً اختيارياً." },
            { en: "empower the sense of dedication to law", ar: "يقوّي الشعور بالالتزام بالقانون" },
            { en: "rights and duties", ar: "الحقوق والواجبات" },
            { en: "pay the penalties when a law is broken", ar: "يدفع العقوبات عندما يُخالَف القانون" },
            { en: "both … and", ar: "كلٌّ من … و …" },
            { en: "not only … but also", ar: "ليس فقط … بل أيضاً" },
            { en: "a just society / trust and stability", ar: "مجتمع عادل / الثقة والاستقرار" },
            { en: "In short, …", ar: "باختصار، …" },
          ],
          model: "Law is very important in people’s lives. Without laws, everything would be full of chaos. Laws protect order, safety and the rights of each individual regardless of their background, so they create trust and stability. Parents should encourage their children to obey laws by being good examples themselves. They must teach them that obeying laws is not optional. Schools should empower the sense of dedication to law. They should not only teach students their rights and duties but also organise activities about good citizenship. Those who do not obey the law must pay the penalties, but they should also be helped to understand their mistakes. In short, both citizens and the government have to respect the law to build a balanced, fair society.",
          modelAr: "القانون مهم جداً في حياة الناس. فبدون قوانين، سيكون كل شيء مليئاً بالفوضى. تحمي القوانين النظام والأمان وحقوق كل فرد بغضّ النظر عن خلفيته، ولذلك فهي تبني الثقة والاستقرار. ينبغي للآباء أن يشجّعوا أبناءهم على طاعة القوانين بأن يكونوا هم أنفسهم قدوة حسنة. ويجب أن يعلّموهم أن طاعة القوانين ليست أمراً اختيارياً. وينبغي للمدارس أن تقوّي الشعور بالالتزام بالقانون، فلا تكتفي بتعليم الطلاب حقوقهم وواجباتهم، بل تنظّم أيضاً أنشطة عن المواطنة الصالحة. أما الذين لا يطيعون القانون فيجب أن يدفعوا العقوبات، ولكن ينبغي أيضاً مساعدتهم على فهم أخطائهم. باختصار، على المواطنين والحكومة معاً احترام القانون لبناء مجتمع متوازن وعادل.",
          checklistAr: [
            "هل أجبت عن الأسئلة الأربعة المساعدة: لماذا القانون مهم، ودور الآباء، ودور المدارس، وماذا نفعل بالمخالفين؟",
            "هل بدأت بجملة رئيسية وأنهيت بجملة ختامية (clincher)؟",
            "هل استخدمت should / must / have to بشكل صحيح مع الفعل في المصدر؟",
            "هل استخدمت أداة ربط مزدوجة (both … and / not only … but also) مع توازي الأفعال؟",
            "هل استخدمت مفردات الوحدة: obey, penalties, rights and duties, order, chaos؟",
            "هل راجعت الإملاء وعلامات الترقيم، وطول الموضوع نحو 100 كلمة؟",
          ],
        },
      ],
      translations: [
        { en: "Living in a society means we share both rights and duties.", ar: "العيش في مجتمع يعني أننا نتشارك الحقوق والواجبات معاً." },
        { en: "Understanding our duties ensures a balanced, fair community where everyone thrives.", ar: "فهمُنا لواجباتنا يضمن مجتمعاً متوازناً وعادلاً يزدهر فيه الجميع." },
        { en: "These actions create trust and stability.", ar: "هذه الأفعال تبني الثقة والاستقرار." },
        { en: "Pursuing education and maintaining health empower us to contribute effectively.", ar: "متابعة التعليم والمحافظة على الصحة تمكّناننا من الإسهام بفعالية." },
        { en: "Staying informed about global and local issues helps us make thoughtful and powerful decisions.", ar: "البقاء على اطّلاع على القضايا العالمية والمحلية يساعدنا على اتخاذ قرارات مدروسة وقوية." },
        { en: "Empathy bridges individual and collective well-being.", ar: "التعاطف يصل بين رفاهية الفرد ورفاهية الجماعة." },
        { en: "Even small acts, like aiding a neighbour, ripple into broader positive change.", ar: "حتى الأفعال الصغيرة، مثل مساعدة جار، تمتدّ آثارها لتصنع تغييراً إيجابياً أوسع." },
        { en: "Ultimately, a harmonious society relies on everyone’s effort.", ar: "في النهاية، يعتمد المجتمع المتناغم على جهد كل فرد فيه." },
        { en: "By embracing our roles with dedication and compassion, we build a foundation for progress.", ar: "بتقبّلنا أدوارنا بإخلاص ورحمة، نبني أساساً للتقدّم." },
        { en: "Paying taxes provides money for services like healthcare and schools.", ar: "دفع الضرائب يوفّر المال لخدمات مثل الرعاية الصحية والمدارس." },
        { en: "Empathy has a vital connection to collective well-being.", ar: "للتعاطف صلة حيوية برفاهية الجماعة." },
        { en: "All citizens must pay taxes in one form or another.", ar: "يجب على جميع المواطنين دفع الضرائب بشكل أو بآخر." },
        { en: "Every Syrian citizen must obey state laws, and pay the penalties when a law is broken.", ar: "يجب على كل مواطن سوري أن يطيع قوانين الدولة، وأن يدفع العقوبات عندما يُخالَف القانون." },
        { en: "Although Syrian citizenship provides many rights, it also involves many responsibilities.", ar: "مع أن المواطنة السورية تمنح حقوقاً كثيرة، فإنها تتضمّن أيضاً مسؤوليات كثيرة." },
        { en: "The Syrian government protects the rights of each individual regardless of their background or culture.", ar: "تحمي الحكومة السورية حقوق كل فرد بغضّ النظر عن خلفيته أو ثقافته." },
        { en: "They have had a vital role in developing human civilisation.", ar: "لقد كان لهم دور حيوي في تطوير الحضارة الإنسانية." },
      ],
    },
    // ===================== UNIT 10 — Culture Shock (Activity Book pages 74–81) =====================
    u10: {
      workbook: {
        pages: "74–81",
        readings: [
          {
            title: "Diana’s diary: six months in Montreal",
            paragraphs: [
              "Diana, a student from Aleppo, Syria, is studying in Montreal. The following passages are taken from her diary during her first six months in Canada.",
              "February 17: Moving to a country with a very different climate could be a challenge! In Syria we have a Mediterranean weather, with mild, rainy winters. Here in Canada winter is very cold and snowy. Temperature average is between the single digits and the -20s. I was very worried about the cold. But it wasn’t a problem because most buildings here are well heated. Actually this city knows how to stay warm. When the weather gets too chilly, I head to the Underground City – a series of interconnected tunnels beneath Montreal which run for over 32 kms. The tunnels connect shopping malls, universities, banks and seven metro stations.",
              "April 10: I miss my mom’s cooking a lot, the food here is delicious but it’s not really the same. Foods, typically considered national dishes of Canada, include poutine, Montreal bagels and butter tarts. My most amazing experience was Sugar time, usually at the end of March. It is the season when maple syrup is produced, and some parties are organised in “la cabane à sucre”, a place where maple sap is boiled to produce maple syrup. it is heated above 100 degrees, and the drops are placed on the snow. It becomes like a candy, a caramel that is served on a stick!",
              "July 31: Getting used to different culture is difficult. My experience during these six months taught me to avoid quick judgements and try to understand the point of view of the people in another culture. I’m staying in a building with a Quebecois family who are teaching me about Montreal a lot. They told me not to make quick decisions, and not to leave right away even if I wanted to. They were right! People don’t take the time to adapt, so they don’t accept the new culture and just go back.",
              "Sirop d'érable (Maple syrup) is made from the sap of maple trees. The Canadian province Quebec is the largest producer, responsible for 70% of the world’s output of maple syrup. Maple syrup production farm is called Sugar shack. The maple leaf has come to symbolise Canada, and is depicted on the country’s flag.",
            ],
            paragraphsAr: [
              "ديانا طالبة من حلب في سوريا، تدرس في مونتريال. المقاطع التالية مأخوذة من مذكّراتها خلال أشهرها الستة الأولى في كندا.",
              "17 شباط: قد يكون الانتقال إلى بلد مناخه مختلف جداً تحدّياً! في سوريا لدينا طقس متوسطي، بشتاء معتدل وماطر. أما هنا في كندا فالشتاء بارد جداً ومثلج. ويتراوح متوسط درجات الحرارة بين الآحاد (من 1 إلى 9) وما دون العشرين تحت الصفر. كنت قلقة جداً من البرد. لكنه لم يكن مشكلة لأن معظم المباني هنا مُدفّأة جيداً. في الحقيقة، هذه المدينة تعرف كيف تبقى دافئة. عندما يصبح الطقس بارداً جداً، أتوجّه إلى المدينة الجوفية — سلسلة من الأنفاق المترابطة تحت مونتريال يزيد طولها على 32 كم. تصل الأنفاق بين مراكز التسوّق والجامعات والمصارف وسبع محطات مترو.",
              "10 نيسان: أشتاق كثيراً إلى طبخ أمي؛ الطعام هنا لذيذ لكنه ليس مثله تماماً. ومن الأطعمة التي تُعدّ عادةً أطباقاً وطنية في كندا: البوتين، وخبز البيغل المونتريالي، وفطائر الزبدة. أروع تجربة مررت بها كانت «موسم السكّر»، الذي يكون عادةً في نهاية آذار. إنه الموسم الذي يُنتَج فيه شراب القيقب، وتُقام بعض الحفلات في «كوخ السكّر»، وهو مكان تُغلى فيه عُصارة شجر القيقب لإنتاج شراب القيقب. يُسخَّن الشراب إلى أكثر من 100 درجة، ثم توضع قطراته على الثلج، فيصبح مثل الحلوى، كراميلاً يُقدَّم على عود!",
              "31 تموز: التعوّد على ثقافة مختلفة أمر صعب. علّمتني تجربتي خلال هذه الأشهر الستة أن أتجنّب الأحكام السريعة وأن أحاول فهم وجهة نظر الناس في الثقافة الأخرى. أسكن في مبنى مع عائلة من كيبيك تعلّمني الكثير عن مونتريال. قالوا لي ألّا أتخذ قرارات سريعة، وألّا أغادر فوراً حتى لو أردت ذلك. وكانوا على حق! فالناس لا يأخذون الوقت الكافي للتكيّف، فلا يتقبّلون الثقافة الجديدة ويعودون ببساطة.",
              "هل تعلم؟ يُصنع شراب القيقب (Sirop d'érable) من عُصارة أشجار القيقب. ومقاطعة كيبيك الكندية هي أكبر منتج له، إذ تنتج 70% من إنتاج العالم من شراب القيقب. وتُسمّى مزرعة إنتاج شراب القيقب «كوخ السكّر». وقد أصبحت ورقة القيقب رمزاً لكندا، وهي مرسومة على علم البلاد.",
            ],
            questions: [
              { q: "1. Diana wears heavy clothes when it is very cold in Canada. (True / False / Not Given)", qAr: "1. ترتدي ديانا ملابس ثقيلة عندما يكون الجو بارداً جداً في كندا. (صح / خطأ / غير مذكور)", options: ["True", "False", "Not Given"], answer: 2, explainAr: "غير مذكور: النص يقول إن المباني مُدفّأة جيداً وإنها تذهب إلى المدينة الجوفية عندما يشتد البرد، لكنه لا يذكر ملابسها أبداً." },
              { q: "2. In Canada, people can go shopping underground. (True / False / Not Given)", qAr: "2. يستطيع الناس في كندا التسوّق تحت الأرض. (صح / خطأ / غير مذكور)", options: ["True", "False", "Not Given"], answer: 0, explainAr: "صح: the Underground City – a series of interconnected tunnels … The tunnels connect shopping malls — الأنفاق تحت الأرض تصل بين مراكز التسوّق." },
              { q: "3. Montreal has been a destination for many immigrants. (True / False / Not Given)", qAr: "3. كانت مونتريال وجهةً لكثير من المهاجرين. (صح / خطأ / غير مذكور)", options: ["True", "False", "Not Given"], answer: 2, explainAr: "غير مذكور: النص لا يتحدث عن المهاجرين إلى مونتريال إطلاقاً، بل عن تجربة ديانا وحدها." },
              { q: "4. Maple syrup is prepared in Canada around the year. (True / False / Not Given)", qAr: "4. يُحضَّر شراب القيقب في كندا طوال السنة. (صح / خطأ / غير مذكور)", options: ["True", "False", "Not Given"], answer: 1, explainAr: "خطأ: Sugar time, usually at the end of March. It is the season when maple syrup is produced — يُنتَج في موسم معيّن (نهاية آذار) وليس طوال السنة." },
              { q: "5. The people Diana lived with taught her to take more time when making decisions. (True / False / Not Given)", qAr: "5. علّمها الناس الذين عاشت معهم أن تأخذ وقتاً أطول عند اتخاذ القرارات. (صح / خطأ / غير مذكور)", options: ["True", "False", "Not Given"], answer: 0, explainAr: "صح: the Quebecois family … They told me not to make quick decisions — أي أن تتمهّل في قراراتها." },
              { q: "6. What do you do to avoid culture shock in Diana’s opinion?", qAr: "6. ماذا تفعل لتتجنّب الصدمة الثقافية في رأي ديانا؟", options: ["Leave right away and go back home", "Avoid quick judgements and try to understand the point of view of the people in another culture", "Go to the Underground City when it is cold", "Eat only the food of your own country"], answer: 1, explainAr: "النص (31 تموز): My experience … taught me to avoid quick judgements and try to understand the point of view of the people in another culture — وأيضاً ألّا تتخذ قرارات سريعة وألّا تغادر فوراً، وأن تأخذ وقتك للتكيّف." },
            ],
            trueFalse: [
              { statement: "In Canada, people can go shopping underground.", answer: true },
              { statement: "Maple syrup is prepared in Canada around the year.", answer: false },
              { statement: "The people Diana lived with taught her to take more time when making decisions.", answer: true },
            ],
          },
        ],
        exercises: [
          // ---- Reading a: check the words in bold (p. 74)
          { type: "mcq", prompt: "Montreal bagels — what are bagels?", promptAr: "Montreal bagels — ما معنى bagels؟", options: ["a kind of bread roll in the shape of a ring", "a kind of hot soup", "a sweet drink made from fruit", "a kind of tree"], answer: 0, explainAr: "bagel = خبز البيغل، خبز صغير على شكل حلقة. وهو من الأطباق الوطنية في كندا بحسب النص: Montreal bagels and butter tarts." },
          { type: "mcq", prompt: "It is the season when maple syrup is produced. — What is a maple?", promptAr: "إنه الموسم الذي يُنتَج فيه شراب القيقب. — ما معنى maple؟", options: ["a kind of sweet cake", "a kind of tree whose leaf is on Canada’s flag", "a small farm animal", "a kind of snow"], answer: 1, explainAr: "maple = شجرة القيقب، ومن عصارتها يُصنع maple syrup، وورقتها رمز كندا: The maple leaf … is depicted on the country’s flag." },
          { type: "mcq", prompt: "a place where maple sap is boiled to produce maple syrup — What is sap?", promptAr: "مكان تُغلى فيه عُصارة القيقب لإنتاج الشراب — ما معنى sap؟", options: ["the liquid that flows inside a tree or plant", "the hard outer part of a tree", "a kind of sugar made in factories", "a stick used to serve candy"], answer: 0, explainAr: "sap = عُصارة، السائل الذي يجري داخل الشجرة أو النبتة. وفي النص: Maple syrup is made from the sap of maple trees." },
          { type: "mcq", prompt: "I’m staying in a building with a Quebecois family. — What does Quebecois mean?", promptAr: "أسكن في مبنى مع عائلة Quebecois. — ما معنى Quebecois؟", options: ["from Montreal’s Underground City", "from Quebec, the Canadian province", "from the Mediterranean", "from Syria"], answer: 1, explainAr: "Quebecois = من كيبيك، المقاطعة الكندية التي تقع فيها مونتريال والتي تُعدّ أكبر منتج لشراب القيقب." },
          // ---- Reading c: add the missing prepositions (p. 75)
          { type: "fill", prompt: "Moving ___ a country with a very different climate could be a challenge!", promptAr: "قد يكون الانتقال ___ بلد مناخه مختلف جداً تحدّياً!", promptArFull: "قد يكون الانتقال إلى بلد مناخه مختلف جداً تحدّياً!", options: ["to", "in", "at", "for"], answer: 0, explainAr: "move to + مكان = ينتقل إلى. حرف الجر to يدل على الاتجاه نحو مكان جديد." },
          { type: "fill", prompt: "I was very worried ___ the cold.", promptAr: "كنت قلقة جداً ___ البرد.", promptArFull: "كنت قلقة جداً من البرد.", options: ["of", "about", "with", "for"], answer: 1, explainAr: "worry about / be worried about = يقلق بشأن. هذه صفة يتبعها حرف جر ثابت يجب حفظه." },
          { type: "fill", prompt: "When the weather gets too chilly, I head ___ the Underground City.", promptAr: "عندما يصبح الطقس بارداً جداً، أتوجّه ___ المدينة الجوفية.", promptArFull: "عندما يصبح الطقس بارداً جداً، أتوجّه إلى المدينة الجوفية.", options: ["in", "at", "to", "on"], answer: 2, explainAr: "head to + مكان = يتوجّه إلى. (ويُقال أيضاً head for بالمعنى نفسه)." },
          { type: "fill", prompt: "Some parties are organised ___ “la cabane à sucre”.", promptAr: "تُقام بعض الحفلات ___ «كوخ السكّر».", promptArFull: "تُقام بعض الحفلات في «كوخ السكّر».", options: ["on", "in", "to", "from"], answer: 1, explainAr: "organise something in + مكان = يُقيم / يُنظّم شيئاً في مكان. نستخدم in للمكان المغلق مثل الكوخ." },
          { type: "fill", prompt: "I’m staying ___ a building with a Quebecois family.", promptAr: "أسكن ___ مبنى مع عائلة من كيبيك.", promptArFull: "أسكن في مبنى مع عائلة من كيبيك.", options: ["on", "to", "in", "for"], answer: 2, explainAr: "stay in + مكان = يقيم في. نستخدم in مع المباني والمدن والبلدان." },
          // ---- Reading d: tips to face culture shock (p. 75)
          { type: "mcq", prompt: "Diana misses her mom’s cooking a lot. Which tip from the box “Tips to face culture shock” can help her?", promptAr: "تشتاق ديانا كثيراً إلى طبخ أمها. أي نصيحة من مربّع «نصائح لمواجهة الصدمة الثقافية» يمكن أن تساعدها؟", options: ["find food from home", "learn the language", "pick up a hobby", "make friends"], answer: 0, explainAr: "المشكلة هي الشوق إلى طعام الوطن، فالحلّ المباشر: find food from home (ابحث عن طعام من بلدك)." },
          { type: "mcq", prompt: "Which tip from the box helps a newcomer understand and talk to the local people?", promptAr: "أي نصيحة من المربّع تساعد القادم الجديد على فهم أهل البلد والتحدث إليهم؟", options: ["find food from home", "learn the language", "pick up a hobby", "talk about your feelings"], answer: 1, explainAr: "للتواصل مع أهل البلد نحتاج لغتهم: learn the language (تعلّم اللغة)." },
          // ---- Vocabulary: Idioms — replace the underlined phrases (p. 76)
          { type: "fill", prompt: "I don’t want to ruin my friendship with him for we have ___ together. (= we have built a good bond)", promptAr: "لا أريد أن أفسد صداقتي معه لأننا ___ معاً. (= بنينا علاقة قوية)", promptArFull: "لا أريد أن أفسد صداقتي معه لأننا صرنا صديقين مقرّبين (كسرنا الخبز معاً).", options: ["lost face", "broken bread", "saved face", "given pumpkins"], answer: 1, explainAr: "to break bread with = أن تكون صديقاً مقرّباً لشخص وبينكما علاقة عميقة. بعد have نحتاج التصريف الثالث: break → broken." },
          { type: "fill", prompt: "He thinks he would ___ if he admitted the mistake. (= be disrespected)", promptAr: "يظنّ أنه سـ___ إن اعترف بالخطأ. (= سيفقد احترام الناس)", promptArFull: "يظنّ أنه سيفقد ماء وجهه إن اعترف بالخطأ.", options: ["save face", "lose face", "have a wide face", "break bread"], answer: 1, explainAr: "to lose face = يفقد ماء وجهه، أي يفقد احترام الآخرين. بعد would يأتي الفعل في المصدر: lose." },
          { type: "fill", prompt: "She has many friends; she ___. (= everyone at work likes her)", promptAr: "لديها أصدقاء كثيرون؛ ___. (= الجميع في العمل يحبّونها)", promptArFull: "لديها أصدقاء كثيرون؛ إنها محبوبة ولها وجه عريض (معارف كثيرون).", options: ["loses face", "has a wide face", "gives pumpkins", "saves face"], answer: 1, explainAr: "to have a wide face (تعبير صيني) = أن يكون لك أصدقاء كثيرون وأن يحبّك الناس. مع she نقول has." },
          { type: "fill", prompt: "I wanted to ___ with my colleagues by explaining why I’ve been late. (= avoid embarrassment)", promptAr: "أردت أن ___ أمام زملائي بتوضيح سبب تأخّري. (= أتجنّب الإحراج)", promptArFull: "أردت أن أحفظ ماء وجهي أمام زملائي بتوضيح سبب تأخّري.", options: ["lose face", "give pumpkins", "save face", "break bread"], answer: 2, explainAr: "to save face = يحفظ ماء وجهه، أي يفعل شيئاً ليمنع الإحراج عن نفسه. بعد to يأتي المصدر: save." },
          { type: "fill", prompt: "He invited her to the party, but she ___. (= she turned him down)", promptAr: "دعاها إلى الحفلة، لكنها ___. (= رفضته)", promptArFull: "دعاها إلى الحفلة، لكنها رفضته (أعطته اليقطين).", options: ["broke bread with him", "gave him pumpkins", "saved face", "had a wide face"], answer: 1, explainAr: "to give someone pumpkins (من إسبانيا) = أن ترفض شخصاً (turn someone down). والجملة في الماضي: give → gave." },
          // ---- Pronunciation: Question intonation — draw the correct arrow (p. 76)
          { type: "mcq", prompt: "1. Your parents are from Italy, aren’t they? (The speaker is almost sure and just wants you to agree.)", promptAr: "1. والداك من إيطاليا، أليس كذلك؟ (المتكلم متأكد تقريباً ويريد منك الموافقة فقط.) ما النغمة الصحيحة؟", options: ["↘ falling", "↗ rising", "↗ … ↘ rising on the choices, falling on the last one"], answer: 0, explainAr: "في السؤال الذيلي (question tag) الذي ينتظر فيه المتكلم تأكيداً لما يعرفه تكون النغمة هابطة ↘. (إن كان غير متأكد وينتظر معلومة تكون صاعدة ↗)." },
          { type: "mcq", prompt: "2. Do you prefer to study nursing or education?", promptAr: "2. هل تفضّل دراسة التمريض أم التربية؟ ما النغمة الصحيحة؟", options: ["↘ falling", "↗ rising", "↗ … ↘ rising on the choices, falling on the last one"], answer: 2, explainAr: "السؤال الذي يعرض اختيارات: ترتفع النغمة على الخيار الأول (nursing ↗) وتهبط على الخيار الأخير (education ↘)." },
          { type: "mcq", prompt: "3. Have you talked to a professor?", promptAr: "3. هل تحدّثت إلى أستاذ جامعي؟ ما النغمة الصحيحة؟", options: ["↘ falling", "↗ rising", "↗ … ↘ rising on the choices, falling on the last one"], answer: 1, explainAr: "سؤال Yes / No يبدأ بفعل مساعد (Have) فتكون النغمة صاعدة ↗ في آخره." },
          { type: "mcq", prompt: "4. Where was the article published?", promptAr: "4. أين نُشرت المقالة؟ ما النغمة الصحيحة؟", options: ["↘ falling", "↗ rising", "↗ … ↘ rising on the choices, falling on the last one"], answer: 0, explainAr: "سؤال wh- يبدأ بـ Where فتكون النغمة هابطة ↘ على آخر كلمة مهمة (published)." },
          { type: "mcq", prompt: "5. Would you rather have tea, coffee or cappuccino?", promptAr: "5. هل تفضّل أن تشرب الشاي أم القهوة أم الكابتشينو؟ ما النغمة الصحيحة؟", options: ["↘ falling", "↗ rising", "↗ … ↘ rising on the choices, falling on the last one"], answer: 2, explainAr: "سؤال يعرض اختيارات: ترتفع النغمة على tea ↗ و coffee ↗ ثم تهبط على الخيار الأخير cappuccino ↘." },
          // ---- Grammar b: Chris and Miranda — cross out the wrong modal forms (p. 78)
          { type: "fill", prompt: "Chris: ___ wear a uniform?", promptAr: "كريس: ___ ارتداء زيّ موحّد؟", promptArFull: "كريس: هل عليّ ارتداء زيّ موحّد؟", options: ["Do I have to", "Do I must", "Do I should"], answer: 0, explainAr: "must و should لا تأخذان do في السؤال. نسأل عن قاعدة الكلية (إلزام من الخارج) بـ Do I have to …?" },
          { type: "fill", prompt: "Miranda: No, but ___ dress smartly. You can't wear jeans.", promptAr: "ميراندا: لا، لكن ___ ترتدي ملابس أنيقة. لا يمكنك ارتداء الجينز.", promptArFull: "ميراندا: لا، لكن عليك أن ترتدي ملابس أنيقة. لا يمكنك ارتداء الجينز.", options: ["you must", "you have to", "you don't have to"], answer: 1, explainAr: "هذه قاعدة الكلية، أي إلزام من الخارج (ليس من المتكلم)، فنستخدم have to. و don’t have to خطأ لأنها تعني «ليس ضرورياً» وهذا يناقض You can't wear jeans." },
          { type: "fill", prompt: "Chris: ___ take my laptop computer with me?", promptAr: "كريس: ___ آخذ حاسوبي المحمول معي؟", promptArFull: "كريس: هل يجب أن آخذ حاسوبي المحمول معي؟", options: ["Must I", "Should I", "Do I should"], answer: 0, explainAr: "ردّ ميراندا «No, you don’t have to» يدل على أن كريس سأل عن الإلزام (هل هذا واجب؟)، فالسؤال Must I …? وجوابه بالنفي don’t have to (ليس ضرورياً). و Do I should خطأ لأن should لا تأخذ do." },
          { type: "fill", prompt: "Miranda: No, ___! You have to write all your essays by hand!", promptAr: "ميراندا: لا، ___! عليك أن تكتب كل مقالاتك بخط اليد!", promptArFull: "ميراندا: لا، ليس ضرورياً! عليك أن تكتب كل مقالاتك بخط اليد!", options: ["you mustn’t", "you don’t have to", "you shouldn’t to"], answer: 1, explainAr: "المقالات تُكتب باليد، إذن الحاسوب ليس ضرورياً (غياب الإلزام): you don’t have to. أما mustn’t فتعني «ممنوع» وهذا أقوى من المعنى المقصود." },
          { type: "fill", prompt: "Chris: What? I ___ use email!", promptAr: "كريس: ماذا؟ ___ استخدام البريد الإلكتروني!", promptArFull: "كريس: ماذا؟ أنا بحاجة إلى استخدام البريد الإلكتروني!", options: ["have to", "don’t have to", "must to"], answer: 0, explainAr: "كريس يحتجّ: أنا مضطر إلى استخدام البريد الإلكتروني (have to = ضرورة). وتردّ ميراندا بأسف: No, I'm afraid not. و must to خطأ لأن must لا يتبعها to." },
          { type: "fill", prompt: "Chris: I don’t get a ticket for the train this evening. ___ a seat, though.", promptAr: "كريس: لم أحصل على تذكرة للقطار هذا المساء. ___ مقعداً على أي حال.", promptArFull: "كريس: لم أحصل على تذكرة للقطار هذا المساء. كان ينبغي أن أحجز مقعداً على أي حال.", options: ["I must have reserved", "I should have reserved", "I should reserved"], answer: 1, explainAr: "لانتقاد تصرّف في الماضي (لم يحجز وكان ذلك خطأ) نستخدم should have + التصريف الثالث. أما must have فهي للاستنتاج عن الماضي وليست للإلزام." },
          { type: "fill", prompt: "Chris: I ___ stand all the way to Scotland.", promptAr: "كريس: ___ الوقوف طوال الطريق إلى اسكتلندا.", promptArFull: "كريس: سأضطر إلى الوقوف طوال الطريق إلى اسكتلندا.", options: ["should", "have to", "must to"], answer: 1, explainAr: "لا يوجد مقعد، فالوقوف ضرورة يفرضها الظرف (إلزام من الخارج): have to. و should تعني نصيحة، وهذا ليس المعنى." },
          { type: "fill", prompt: "Miranda: ___ give you a ring later and see how things are going?", promptAr: "ميراندا: ___ أتصل بك لاحقاً لأطمئن على أحوالك؟", promptArFull: "ميراندا: هل أتصل بك لاحقاً لأطمئن على أحوالك؟", options: ["Should I", "Must I", "Do I must"], answer: 0, explainAr: "ميراندا تعرض خدمة (عرض / اقتراح)، فنستخدم Should I …? وليس Must I (لا يوجد إلزام)." },
          { type: "fill", prompt: "Miranda: Yes, don't worry. But ___ switch it off during the school day.", promptAr: "ميراندا: نعم، لا تقلق. لكن ___ تطفئه خلال اليوم الدراسي.", promptArFull: "ميراندا: نعم، لا تقلق. لكن يجب أن تطفئه خلال اليوم الدراسي.", options: ["you should", "you must", "you mustn’t"], answer: 1, explainAr: "إطفاء الهاتف في أثناء الدوام قاعدة ملزمة وليس مجرد نصيحة، فنستخدم must. و mustn’t تعني «ممنوع أن تطفئه» وهذا عكس المعنى." },
          { type: "fill", prompt: "Miranda: Yes. You ___ visit the lake near the collage. It’s beautiful.", promptAr: "ميراندا: نعم. ___ تزور البحيرة القريبة من الكلية. إنها جميلة.", promptArFull: "ميراندا: نعم. ينبغي أن تزور البحيرة القريبة من الكلية. إنها جميلة.", options: ["must", "should", "mustn’t"], answer: 1, explainAr: "كريس طلب نصيحة (Can you give me any more advice?)، وزيارة البحيرة توصية وليست إلزاماً، فنستخدم should (advice or recommendations)." },
          // ---- Grammar c: signs — mustn’t / don’t have to (p. 78)
          { type: "fill", prompt: "LIBRARY — No talking: You ___ talk in the library.", promptAr: "المكتبة — ممنوع الكلام: ___ تتكلم في المكتبة.", promptArFull: "المكتبة — ممنوع الكلام: يُمنع أن تتكلم في المكتبة.", options: ["mustn’t", "don’t have to", "must"], answer: 0, explainAr: "اللافتة تقول No talking أي ممنوع، والمنع = mustn’t." },
          { type: "fill", prompt: "LIBRARY — Please leave books on tables: You ___ put the books back on the shelf.", promptAr: "المكتبة — اترك الكتب على الطاولات من فضلك: ___ تعيد الكتب إلى الرف.", promptArFull: "المكتبة — اترك الكتب على الطاولات من فضلك: ليس عليك أن تعيد الكتب إلى الرف.", options: ["mustn’t", "don’t have to", "must"], answer: 1, explainAr: "المكتبة تطلب ترك الكتب على الطاولات، فإعادتها إلى الرف ليست ضرورية: don’t have to (غياب الإلزام)." },
          { type: "fill", prompt: "ANTIQUES — Please feel free to come in: You ___ go in.", promptAr: "التحف القديمة — تفضّل بالدخول بحرية: ___ تدخل.", promptArFull: "التحف القديمة — تفضّل بالدخول بحرية: لست مضطراً إلى الدخول.", options: ["mustn’t", "don’t have to", "must"], answer: 1, explainAr: "Feel free to come in تعني أن الدخول مسموح واختياري، أي ليس إلزامياً: don’t have to. و mustn’t خطأ لأن الدخول غير ممنوع." },
          { type: "fill", prompt: "ANTIQUES — No eating inside: You ___ eat inside.", promptAr: "التحف القديمة — ممنوع الأكل في الداخل: ___ تأكل في الداخل.", promptArFull: "التحف القديمة — ممنوع الأكل في الداخل: يُمنع أن تأكل في الداخل.", options: ["mustn’t", "don’t have to", "must"], answer: 0, explainAr: "No eating inside = ممنوع الأكل، والمنع = mustn’t." },
          { type: "fill", prompt: "CONCERT — Entry possible 30 minutes before the concert: You ___ arrive half an hour early.", promptAr: "الحفل الموسيقي — الدخول ممكن قبل 30 دقيقة من الحفل: ___ تصل قبل نصف ساعة.", promptArFull: "الحفل الموسيقي — الدخول ممكن قبل 30 دقيقة من الحفل: ليس عليك أن تصل قبل نصف ساعة.", options: ["mustn’t", "don’t have to", "must"], answer: 1, explainAr: "Entry possible تعني أن الدخول المبكر ممكن لا واجب، فالوصول قبل نصف ساعة ليس ضرورياً: don’t have to." },
          { type: "fill", prompt: "CONCERT — No late arrivals allowed: You ___ arrive late.", promptAr: "الحفل الموسيقي — لا يُسمح بالتأخر: ___ تصل متأخراً.", promptArFull: "الحفل الموسيقي — لا يُسمح بالتأخر: يُمنع أن تصل متأخراً.", options: ["mustn’t", "don’t have to", "must"], answer: 0, explainAr: "No late arrivals allowed = غير مسموح، أي منع: mustn’t." },
          // ---- Grammar d: Heathrow work plan — had to / didn’t have to / should have (p. 79)
          { type: "fill", prompt: "(Colin/ Sunday) Colin ___ on Sunday.", promptAr: "(كولن/ الأحد) كولن ___ يوم الأحد.", promptArFull: "(كولن/ الأحد) كولن اضطُرّ إلى العمل يوم الأحد.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 0, explainAr: "كولن مناوب يوم الأحد (✓) وقد عمل، فهذا إلزام في الماضي: had to work." },
          { type: "fill", prompt: "(Joan/ Sunday) Joan ___ on Sunday.", promptAr: "(جوان/ الأحد) جوان ___ يوم الأحد.", promptArFull: "(جوان/ الأحد) جوان لم يكن عليها أن تعمل يوم الأحد.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 1, explainAr: "جوان ليست في قائمة مناوبي الأحد، فلم يكن العمل مطلوباً منها: didn’t have to work (غياب الإلزام في الماضي)." },
          { type: "fill", prompt: "(Derek/ Sunday) Derek ___ on Sunday but he was ill.", promptAr: "(ديريك/ الأحد) ديريك ___ يوم الأحد لكنه كان مريضاً.", promptArFull: "(ديريك/ الأحد) كان ينبغي أن يعمل ديريك يوم الأحد لكنه كان مريضاً.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 2, explainAr: "ديريك مناوب يوم الأحد لكنه كان مريضاً فلم يعمل: should have worked = كان ينبغي أن يعمل ولم يفعل." },
          { type: "fill", prompt: "(Mary/ Saturday) Mary ___ on Saturday.", promptAr: "(ماري/ السبت) ماري ___ يوم السبت.", promptArFull: "(ماري/ السبت) ماري لم يكن عليها أن تعمل يوم السبت.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 1, explainAr: "ماري مناوبة يوم الأحد فقط، وليست في قائمة السبت: didn’t have to work." },
          { type: "fill", prompt: "(Brian/ Saturday) Brian ___ on Saturday but he was ill.", promptAr: "(برايان/ السبت) برايان ___ يوم السبت لكنه كان مريضاً.", promptArFull: "(برايان/ السبت) كان ينبغي أن يعمل برايان يوم السبت لكنه كان مريضاً.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 2, explainAr: "برايان مناوب يوم السبت والتعليق ill، فلم يعمل: should have worked." },
          { type: "fill", prompt: "(Daniel/ Saturday) Daniel ___ on Saturday.", promptAr: "(دانيال/ السبت) دانيال ___ يوم السبت.", promptArFull: "(دانيال/ السبت) دانيال اضطُرّ إلى العمل يوم السبت.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 0, explainAr: "دانيال مناوب يوم السبت (✓): had to work." },
          { type: "fill", prompt: "(Joan/ Saturday) Joan ___ on Saturday but she was ill.", promptAr: "(جوان/ السبت) جوان ___ يوم السبت لكنها كانت مريضة.", promptArFull: "(جوان/ السبت) كان ينبغي أن تعمل جوان يوم السبت لكنها كانت مريضة.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 2, explainAr: "جوان مناوبة يوم السبت والتعليق ill: should have worked." },
          { type: "fill", prompt: "(Derek/ Saturday) Derek ___ on Saturday.", promptAr: "(ديريك/ السبت) ديريك ___ يوم السبت.", promptArFull: "(ديريك/ السبت) ديريك لم يكن عليه أن يعمل يوم السبت.", options: ["had to work", "didn’t have to work", "should have worked"], answer: 1, explainAr: "ديريك مناوب يوم الأحد فقط، وليس في قائمة السبت: didn’t have to work." },
          // ---- Everyday English: Expressing Surprise — choose responses from (a–j) (p. 79)
          { type: "mcq", prompt: "1. A friend tells you she’s going to have her hair dyed orange.", promptAr: "1. تخبرك صديقة أنها ستصبغ شعرها باللون البرتقالي. ماذا تقول؟", options: ["I’m not surprised.", "You’re going to do WHAT??", "No wonder."], answer: 1, explainAr: "خبر صادم عن خطة غريبة، فنكرّر الخبر بسؤال مندهش: You’re going to do WHAT?? أما I’m not surprised و No wonder فتقالان لشيء متوقّع." },
          { type: "mcq", prompt: "1. A friend tells you she’s going to have her hair dyed orange. (another response)", promptAr: "1. تخبرك صديقة أنها ستصبغ شعرها باللون البرتقالي. (ردّ آخر)", options: ["No wonder.", "I’m not surprised.", "You’re kidding"], answer: 2, explainAr: "You’re kidding = أنت تمزحين! تعبير عن دهشة شديدة من خبر غير متوقّع." },
          { type: "mcq", prompt: "2. Your partner is late for your date as usual, but promises to be on time next time.", promptAr: "2. تأخّر شريكك عن موعدكما كالعادة، لكنه يعدك أن يأتي في الوقت المحدد في المرة القادمة. ماذا تقول؟", options: ["I’ll believe that when I see it.", "That’s absolutely amazing!", "You’re going to do WHAT??"], answer: 0, explainAr: "أنت لا تصدّق الوعد لأنه يتأخر دائماً: I’ll believe that when I see it = سأصدّق ذلك عندما أراه." },
          { type: "mcq", prompt: "2. Your partner is late for your date as usual, but promises to be on time next time. (another response)", promptAr: "2. تأخّر شريكك كالعادة لكنه يعدك بالالتزام بالوقت. (ردّ آخر)", options: ["That’s absolutely amazing!", "Do you seriously expect me to believe that?", "You’re going to do WHAT??"], answer: 1, explainAr: "Do you seriously expect me to believe that? = هل تتوقّع جدياً أن أصدّق ذلك؟ — للتعبير عن عدم التصديق." },
          { type: "mcq", prompt: "3. A taxi driver tells you that you have to pay double fare.", promptAr: "3. يخبرك سائق سيارة أجرة أن عليك دفع الأجرة مضاعفة. ماذا تقول؟", options: ["That’s totally ridiculous.", "That’s absolutely amazing!", "No wonder."], answer: 0, explainAr: "طلب غير مقبول، فنعبّر عن الدهشة والرفض: That’s totally ridiculous = هذا سخيف تماماً." },
          { type: "mcq", prompt: "3. A taxi driver tells you that you have to pay double fare. (another response)", promptAr: "3. يخبرك سائق الأجرة أن عليك دفع الأجرة مضاعفة. (ردّ آخر)", options: ["No wonder.", "That’s absolutely amazing!", "You’re kidding"], answer: 2, explainAr: "You’re kidding = أنت تمزح! دهشة من خبر غير متوقّع وغير مقبول. أما amazing فللخبر الجميل." },
          { type: "mcq", prompt: "4. Someone tells you that their dog can sing pop songs.", promptAr: "4. يخبرك شخص أن كلبه يستطيع غناء أغاني البوب. ماذا تقول؟", options: ["I’m not surprised.", "I’ll believe that when I see it.", "No wonder."], answer: 1, explainAr: "خبر لا يُصدَّق، فتقول: I’ll believe that when I see it = لن أصدّق حتى أرى بعيني." },
          { type: "mcq", prompt: "4. Someone tells you that their dog can sing pop songs. (another response)", promptAr: "4. يخبرك شخص أن كلبه يغنّي أغاني البوب. (ردّ آخر)", options: ["No wonder.", "I’m not surprised.", "Do you seriously expect me to believe that?"], answer: 2, explainAr: "Do you seriously expect me to believe that? = هل تتوقّع جدياً أن أصدّق ذلك؟ — لخبر غير معقول." },
          { type: "mcq", prompt: "5. Your friend tells you that he’s tired … you know that he’s always staying up late.", promptAr: "5. يخبرك صديقك أنه متعب … وأنت تعرف أنه يسهر دائماً حتى وقت متأخر. ماذا تقول؟", options: ["I’m not surprised.", "You’re going to do WHAT??", "That’s absolutely amazing!"], answer: 0, explainAr: "التعب متوقّع لأنه يسهر دائماً، فتقول: I’m not surprised = لست متفاجئاً." },
          { type: "mcq", prompt: "5. Your friend tells you that he’s tired … you know that he’s always staying up late. (another response)", promptAr: "5. يخبرك صديقك أنه متعب وأنت تعرف أنه يسهر دائماً. (ردّ آخر)", options: ["That’s absolutely amazing!", "No wonder.", "You’re going to do WHAT??"], answer: 1, explainAr: "No wonder = لا عجب! نقولها عندما نعرف سبب الأمر فلا نستغربه." },
          { type: "mcq", prompt: "6. Someone tells you that he’s just seen Misse at the local supermarket.", promptAr: "6. يخبرك شخص أنه رأى للتوّ ميسي في السوبرماركت المحلي. ماذا تقول؟", options: ["I’m not surprised.", "No wonder.", "That’s absolutely amazing!"], answer: 2, explainAr: "رؤية شخص مشهور في مكان عادي خبر مدهش وجميل: That’s absolutely amazing! = هذا مذهل تماماً!" },
          { type: "mcq", prompt: "6. Someone tells you that he’s just seen Misse at the local supermarket. (another response)", promptAr: "6. يخبرك شخص أنه رأى ميسي في السوبرماركت المحلي. (ردّ آخر)", options: ["You’re kidding", "I’m not surprised.", "No wonder."], answer: 0, explainAr: "You’re kidding = أنت تمزح! دهشة من خبر غير متوقّع." },
        ],
      },
      compositions: [
        {
          source: "book",
          topic: "Write a reply to the email in exercise a. Write a formal version. Make use of the Chinese customs given below.",
          topicAr: "اكتب رداً على الرسالة الإلكترونية في التمرين a. اكتب نسخة رسمية، واستفد من العادات الصينية المذكورة أدناه.",
          words: 100,
          points: [
            "It is important to learn Mandarin. Chinese is the most spoken language in the world.",
            "Make slurping sounds and noise while eating. It is a way of indicating that you’re really enjoying the food.",
            "Be sure to leave a little food behind. In China, finishing everything on your plate is a sign that your host didn’t have enough food to offer you.",
            "Don’t expect a thank-you card for these gifts in China. Clocks, handkerchiefs and straw sandals are all associated with death and funerals.",
          ],
          pointsAr: [
            "من المهم أن تتعلّم لغة الماندرين. فالصينية هي اللغة الأكثر تحدّثاً في العالم.",
            "أصدِر أصوات مصّ وضجيجاً في أثناء الأكل. إنها طريقة للدلالة على أنك تستمتع بالطعام حقاً.",
            "احرص على ترك قليل من الطعام. ففي الصين، إنهاء كل ما في طبقك علامة على أن مضيفك لم يكن لديه طعام كافٍ ليقدّمه لك.",
            "لا تنتظر بطاقة شكر على هذه الهدايا في الصين: الساعات والمناديل والصنادل المصنوعة من القش كلها مرتبطة بالموت والجنازات.",
          ],
          plan: [
            { en: "Formal greeting and opening: Dear Mr Melton, thank him for his email and say you are glad to help.", ar: "التحية والافتتاح الرسميان: Dear Mr Melton، اشكره على رسالته وقل إنك سعيد بالمساعدة." },
            { en: "Language: learning a few words of Mandarin is important; hosts will not be offended, but they will appreciate it.", ar: "اللغة: من المهم تعلّم بعض كلمات الماندرين؛ لن ينزعج المضيفون لكنهم سيقدّرون ذلك." },
            { en: "Eating customs: slurping sounds show you enjoy the food; leave a little food on your plate.", ar: "عادات الأكل: أصوات المصّ تدلّ على الاستمتاع بالطعام، واترك قليلاً من الطعام في طبقك." },
            { en: "Gifts: you may take gifts, but you mustn’t give clocks, handkerchiefs or straw sandals; don’t expect a thank-you card.", ar: "الهدايا: يمكنك أخذ هدايا، لكن يُمنع إهداء الساعات أو المناديل أو صنادل القش، ولا تنتظر بطاقة شكر." },
            { en: "Formal closing: wish him a successful trip; With kind regards + full name. No contractions.", ar: "الختام الرسمي: تمنَّ له رحلة ناجحة، ثم With kind regards والاسم الكامل. بدون اختصارات مثل don’t." },
          ],
          phrases: [
            { en: "Dear Mr Melton, / With kind regards", ar: "عزيزي السيد ميلتون، / مع أطيب التحيات" },
            { en: "Thank you for your email.", ar: "شكراً لك على رسالتك الإلكترونية." },
            { en: "It has been a pleasure to meet you.", ar: "كان من دواعي سروري أن ألتقي بك." },
            { en: "It is important to learn Mandarin.", ar: "من المهم أن تتعلّم لغة الماندرين." },
            { en: "Chinese is the most spoken language in the world.", ar: "الصينية هي اللغة الأكثر تحدّثاً في العالم." },
            { en: "It is a way of indicating that you are really enjoying the food.", ar: "إنها طريقة للدلالة على أنك تستمتع بالطعام حقاً." },
            { en: "Be sure to leave a little food behind.", ar: "احرص على ترك قليل من الطعام." },
            { en: "are all associated with death and funerals", ar: "كلها مرتبطة بالموت والجنازات" },
            { en: "you should / you must not / you do not have to", ar: "ينبغي أن / يُمنع أن / ليس عليك أن" },
            { en: "offended / displease your hosts", ar: "مستاء / تُزعج مضيفيك" },
            { en: "I am unfamiliar with … / be particularly aware of", ar: "لست على دراية بـ … / أن تنتبه بشكل خاص إلى" },
            { en: "I hope you have a successful trip.", ar: "أتمنى لك رحلة ناجحة." },
          ],
          model: "Dear Mr Melton,\nThank you for your email. It has been a pleasure to meet you, too. I am glad to give you some advice. Firstly, it is important to learn a few words of Mandarin, as Chinese is the most spoken language in the world. Your hosts will not be offended, but they will appreciate your effort. Secondly, do not be surprised when people make slurping sounds while eating. It is a way of indicating that they are enjoying the food. You should also leave a little food on your plate. Finally, you may take some gifts, but you must not give clocks, handkerchiefs or straw sandals, as they are associated with death. I hope you have a successful trip.\nWith kind regards,\nAnastasia Brown",
          modelAr: "عزيزي السيد ميلتون،\nشكراً لك على رسالتك الإلكترونية. وقد كان من دواعي سروري أن ألتقي بك أيضاً. يسعدني أن أقدّم لك بعض النصائح. أولاً، من المهم أن تتعلّم بعض كلمات الماندرين، لأن الصينية هي اللغة الأكثر تحدّثاً في العالم. لن ينزعج مضيفوك، لكنهم سيقدّرون جهدك. ثانياً، لا تتفاجأ عندما يُصدر الناس أصوات مصّ في أثناء الأكل، فهي طريقة للدلالة على أنهم يستمتعون بالطعام. وينبغي أيضاً أن تترك قليلاً من الطعام في طبقك. وأخيراً، يمكنك أن تأخذ بعض الهدايا، لكن يُمنع أن تُهدي ساعات أو مناديل أو صنادل من القش، لأنها مرتبطة بالموت. أتمنى لك رحلة ناجحة.\nمع أطيب التحيات،\nأناستازيا براون",
          checklistAr: [
            "هل بدأت بتحية رسمية (Dear Mr Melton,) وأنهيت بختام رسمي (With kind regards) والاسم الكامل؟",
            "هل تجنّبت الاختصارات واللغة غير الرسمية (do not بدلاً من don’t، و I would be … بدلاً من it’d be)؟",
            "هل استفدت من العادات الصينية الأربع: اللغة، أصوات الأكل، ترك الطعام، الهدايا؟",
            "هل استخدمت الأفعال الناقصة بشكل صحيح: should (نصيحة)، must not (منع)، do not have to (ليس ضرورياً)؟",
            "هل رتّبت النصائح بروابط مثل Firstly / Secondly / Finally؟",
            "هل راجعت الإملاء والقواعد وعلامات الترقيم، وطول الرسالة نحو 100 كلمة؟",
          ],
        },
        {
          source: "workbook",
          topic: "Many people visit your country, but they don’t know a lot about it. Write an article to help them be culturally aware of your country. Use information from your answers in exercise speaking ‘a’.",
          topicAr: "يزور كثير من الناس بلدك، لكنهم لا يعرفون الكثير عنه. اكتب مقالاً يساعدهم على الوعي بثقافة بلدك، مستفيداً من إجاباتك في تمرين التحدث (a).",
          words: 100,
          points: [
            "The most common form of greeting",
            "Common gestures that visitors are not used to",
            "Common eating customs",
            "Common misconceptions visitors have about your country",
          ],
          pointsAr: [
            "أكثر أشكال التحية شيوعاً",
            "إيماءات شائعة لم يعتد عليها الزوّار",
            "عادات الأكل الشائعة",
            "مفاهيم خاطئة شائعة لدى الزوّار عن بلدك",
          ],
          plan: [
            { en: "Introduction: welcome visitors to Syria, a nation of ancient civilisations famous for its hospitality.", ar: "المقدمة: رحّب بالزوّار في سوريا، بلد الحضارات القديمة المشهور بكرم الضيافة." },
            { en: "Greetings and gestures: how people greet each other, and a gesture visitors are not used to.", ar: "التحية والإيماءات: كيف يحيّي الناس بعضهم، وإيماءة لم يعتد عليها الزوّار." },
            { en: "Eating customs: what you should do if you are invited to dinner (arrive on time, take a small gift, the host offers food again and again).", ar: "عادات الأكل: ما ينبغي فعله إذا دُعيت إلى العشاء (الوصول في الموعد، أخذ هدية صغيرة، المضيف يعرض الطعام مراراً)." },
            { en: "Misconceptions: correct one wrong idea visitors have about Syria.", ar: "المفاهيم الخاطئة: صحّح فكرة خاطئة لدى الزوّار عن سوريا." },
            { en: "Conclusion: advice — respect local customs: When in Rome, do as the Romans do.", ar: "الخاتمة: نصيحة — احترم العادات المحلية: «إذا كنت في روما فافعل كما يفعل الرومان»." },
          ],
          phrases: [
            { en: "be culturally aware of", ar: "يكون واعياً بثقافة …" },
            { en: "customs / a custom", ar: "عادات / عادة" },
            { en: "The most common form of greeting is …", ar: "أكثر أشكال التحية شيوعاً هو …" },
            { en: "Visitors are not used to …", ar: "لم يعتد الزوّار على …" },
            { en: "What do you think I should do if I’m invited to dinner?", ar: "ماذا تظن أنه ينبغي أن أفعل إن دُعيت إلى العشاء؟" },
            { en: "Make sure that you arrive on time.", ar: "احرص على أن تصل في الموعد." },
            { en: "you should / you don’t have to / you mustn’t", ar: "ينبغي أن / ليس عليك أن / يُمنع أن" },
            { en: "host / hospitality", ar: "مضيف / كرم الضيافة" },
            { en: "offended / embarrassed", ar: "مستاء / محرَج" },
            { en: "a nation of ancient civilisations", ar: "أمة ذات حضارات قديمة" },
            { en: "misconception", ar: "مفهوم خاطئ" },
            { en: "When in Rome, do as the Romans do.", ar: "إذا كنت في روما فافعل كما يفعل الرومان." },
          ],
          model: "Welcome to Syria! Syria is a nation of ancient civilisations, and its people are famous for their hospitality. Here are some customs you should know. The most common form of greeting is shaking hands and saying “Marhaba”. Close friends often kiss each other on the cheeks. Visitors are not used to some gestures. For example, Syrians often put their right hand on their heart to say thank you. If you are invited to dinner, make sure that you arrive on time and take a small gift. Your host will offer you food again and again, so you don’t have to be embarrassed. Many visitors think Syria is only a desert, but it has green mountains, beautiful beaches and old cities. When in Rome, do as the Romans do!",
          modelAr: "أهلاً بكم في سوريا! سوريا بلد الحضارات القديمة، وأهلها مشهورون بكرم الضيافة. إليكم بعض العادات التي ينبغي أن تعرفوها. أكثر أشكال التحية شيوعاً هو المصافحة وقول «مرحبا». وكثيراً ما يقبّل الأصدقاء المقرّبون بعضهم على الخدّين. لم يعتد الزوّار على بعض الإيماءات؛ فمثلاً، كثيراً ما يضع السوريون يدهم اليمنى على قلوبهم ليقولوا شكراً. إذا دُعيت إلى العشاء، فاحرص على أن تصل في الموعد وأن تأخذ هدية صغيرة. سيعرض عليك مضيفك الطعام مرة بعد مرة، فلا داعي لأن تشعر بالحرج. يظن كثير من الزوّار أن سوريا صحراء فقط، لكن فيها جبالاً خضراء وشواطئ جميلة ومدناً قديمة. وإذا كنت في روما فافعل كما يفعل الرومان!",
          checklistAr: [
            "هل غطّيت النقاط الأربع: التحية، الإيماءات، عادات الأكل، المفاهيم الخاطئة؟",
            "هل كتبت للزوّار بأسلوب مقال واضح بمقدمة وخاتمة؟",
            "هل استخدمت الأفعال الناقصة للنصيحة والإلزام بشكل صحيح (should / don’t have to / mustn’t)؟",
            "هل استخدمت مفردات الوحدة: customs, host, offended, embarrassed, culture shock؟",
            "هل استخدمت روابط مثل For example / so / but؟",
            "هل راجعت الإملاء وعلامات الترقيم، وطول المقال نحو 100 كلمة؟",
          ],
        },
      ],
      translations: [
        { en: "Moving to a country with a very different climate could be a challenge!", ar: "قد يكون الانتقال إلى بلد مناخه مختلف جداً تحدّياً!" },
        { en: "Here in Canada winter is very cold and snowy.", ar: "هنا في كندا يكون الشتاء بارداً جداً ومثلجاً." },
        { en: "I was very worried about the cold.", ar: "كنت قلقة جداً من البرد." },
        { en: "But it wasn’t a problem because most buildings here are well heated.", ar: "لكنه لم يكن مشكلة لأن معظم المباني هنا مُدفّأة جيداً." },
        { en: "Actually this city knows how to stay warm.", ar: "في الحقيقة، هذه المدينة تعرف كيف تبقى دافئة." },
        { en: "The tunnels connect shopping malls, universities, banks and seven metro stations.", ar: "تصل الأنفاق بين مراكز التسوّق والجامعات والمصارف وسبع محطات مترو." },
        { en: "It becomes like a candy, a caramel that is served on a stick!", ar: "يصبح مثل الحلوى، كراميلاً يُقدَّم على عود!" },
        { en: "Getting used to different culture is difficult.", ar: "التعوّد على ثقافة مختلفة أمر صعب." },
        { en: "The maple leaf has come to symbolise Canada, and is depicted on the country’s flag.", ar: "أصبحت ورقة القيقب رمزاً لكندا، وهي مرسومة على علم البلاد." },
        { en: "He invited her to the party, but she turned him down.", ar: "دعاها إلى الحفلة، لكنها رفضت دعوته." },
        { en: "Passengers must fasten their seat belts.", ar: "يجب على الركّاب أن يربطوا أحزمة الأمان." },
        { en: "We have to get up early tomorrow to catch the plane.", ar: "علينا أن نستيقظ باكراً غداً لنلحق بالطائرة." },
        { en: "You should apologise to the boss for being late.", ar: "ينبغي أن تعتذر إلى المدير عن تأخّرك." },
        { en: "I had to report the incident to the police.", ar: "اضطُررت إلى إبلاغ الشرطة بالحادثة." },
        { en: "In fact, there is no magic solution for dealing with culture shock.", ar: "في الحقيقة، لا يوجد حلّ سحري للتعامل مع الصدمة الثقافية." },
        { en: "These unfamiliar surroundings can lead to a feeling of being a little bit lost.", ar: "قد تؤدي هذه الأجواء غير المألوفة إلى شعور بالضياع قليلاً." },
      ],
    },
  },
}
