import type { ModuleExtras } from './merge'

// Activity Book pages 36–51 (Unit 5: 36–43, Unit 6: 44–51), the writing tasks of both books, and translation sentences.
export const extras: ModuleExtras = {
  units: {
    // ================= Unit 5 — Civil Rights (Activity Book pp. 36–43) =================
    u5: {
      workbook: {
        pages: '36–43',
        readings: [
          {
            title: 'The Right to Education',
            paragraphs: [
              'The right to education is one of the basic universal rights of the human being. It is one of the goals that the education schedule supports and is expected for the year 2030 in order to achieve sustainable development aimed by the United Nations. It is a force that enables individuals to get rid of poverty and achieve individual and social well-being. It is something mandatory for the state, guaranteed by its own law, for all individuals without any form of discrimination. It is the right to education in all parts of the world that includes a number of freedoms and rights that individuals are entitled to. It is the right to have primary education for all, free of charge, the right to have secondary education available to everyone without exception, and in all its fields, whether technical, vocational, or training. Above all, it guarantees equal access to higher education without any distinction or discrimination, and ensures quality and meaningful education, whether in public or private schools and universities.',
              'Education is the right for parents to choose freely appropriate schools for their children and enroll them in, regardless of their beliefs and religions. In addition, it is the right to freely establish any educational institution that adheres to the standards set by the government and the state regarding students and academic staff.',
              'Education is of great importance because of its great role in building society, which is made up of all segments of teachers, leaders, politicians and others. Its importance lies in getting to know a new world. Through education, people get to know other cultures and worlds, and it helps to enhance understanding and communication between them, and open the horizon to the knowledge of the great and their philosophies. It also helps in bringing fun and adventure by getting to know new things, interests and new people, without looking only at the subject of books and difficult exams. Through education, a person can get to know other people and build a social network and develop different life skills by applying what one learns in different aspects of economic, social or political life.',
              'Here in Syria, the government is working hard to promote all these principles in society through free education and adopting new methods of teaching.',
            ],
            paragraphsAr: [
              'الحق في التعليم هو أحد الحقوق العالمية الأساسية للإنسان. وهو أحد الأهداف التي تدعمها خطة التعليم، ومن المتوقَّع تحقيقه بحلول عام 2030 من أجل الوصول إلى التنمية المستدامة التي تهدف إليها الأمم المتحدة. إنه قوة تمكّن الأفراد من التخلّص من الفقر وتحقيق الرفاه الفردي والاجتماعي. وهو أمر إلزامي على الدولة، يكفله قانونها، لجميع الأفراد دون أي شكل من أشكال التمييز. إنه الحق في التعليم في جميع أنحاء العالم، ويشمل عدداً من الحريات والحقوق التي يستحقها الأفراد. إنه الحق في التعليم الابتدائي للجميع مجاناً، والحق في أن يكون التعليم الثانوي متاحاً للجميع دون استثناء وفي جميع مجالاته، سواء أكان تقنياً أم مهنياً أم تدريبياً. وفوق كل شيء، يضمن المساواة في الوصول إلى التعليم العالي دون أي تفرقة أو تمييز، ويكفل تعليماً جيداً وهادفاً، سواء في المدارس والجامعات العامة أو الخاصة.',
              'التعليم هو حق الآباء في أن يختاروا بحرية المدارس المناسبة لأطفالهم وأن يسجّلوهم فيها، بغضّ النظر عن معتقداتهم وأديانهم. إضافةً إلى ذلك، هو الحق في أن يُنشئ المرء بحرية أي مؤسسة تعليمية تلتزم بالمعايير التي وضعتها الحكومة والدولة فيما يخص الطلاب والكادر الأكاديمي.',
              'للتعليم أهمية كبيرة بسبب دوره الكبير في بناء المجتمع، الذي يتكوّن من جميع الشرائح من معلمين وقادة وسياسيين وغيرهم. وتكمن أهميته في التعرّف إلى عالم جديد. فمن خلال التعليم يتعرّف الناس إلى ثقافات وعوالم أخرى، ويساعد على تعزيز التفاهم والتواصل بينهم، ويفتح الأفق للتعرّف إلى العظماء وفلسفاتهم. كما يساعد على جلب المتعة والمغامرة من خلال التعرّف إلى أشياء واهتمامات وأشخاص جدد، دون النظر فقط إلى موضوع الكتب والامتحانات الصعبة. ومن خلال التعليم يستطيع الإنسان أن يتعرّف إلى أشخاص آخرين وأن يبني شبكة علاقات اجتماعية وأن يطوّر مهارات حياتية مختلفة بتطبيق ما يتعلّمه في مختلف جوانب الحياة الاقتصادية أو الاجتماعية أو السياسية.',
              'وهنا في سوريا، تعمل الحكومة بجدّ على تعزيز كل هذه المبادئ في المجتمع من خلال التعليم المجاني واعتماد أساليب تدريس جديدة.',
            ],
            questions: [
              {
                q: 'What is expected to be achieved by the year 2030?',
                qAr: 'ما الذي يُتوقَّع تحقيقه بحلول عام 2030؟',
                options: ['Free higher education in private universities only', 'Sustainable development aimed by the United Nations', 'The end of all difficult exams', 'A new law for academic staff'],
                answer: 1,
                explainAr: 'يقول النص: "is expected for the year 2030 in order to achieve sustainable development aimed by the United Nations" أي التنمية المستدامة التي تهدف إليها الأمم المتحدة.',
              },
              {
                q: 'How is education beneficial for individuals?',
                qAr: 'كيف يفيد التعليمُ الأفراد؟',
                options: ['It helps them avoid paying taxes.', 'It makes them leave their country.', 'It enables them to get rid of poverty and achieve individual and social well-being.', 'It gives them the right to vote.'],
                answer: 2,
                explainAr: 'في الفقرة الأولى: "It is a force that enables individuals to get rid of poverty and achieve individual and social well-being" أي يمكّنهم من التخلّص من الفقر وتحقيق الرفاه الفردي والاجتماعي.',
              },
              {
                q: 'To what level is education accessible according to the UN education schedule?',
                qAr: 'إلى أي مستوى يكون التعليم متاحاً وفق خطة الأمم المتحدة للتعليم؟',
                options: ['Only primary education is available to everyone.', 'Primary and secondary education only, not higher education.', 'Only technical and vocational education.', 'At all levels: free primary education, secondary education for everyone and equal access to higher education.'],
                answer: 3,
                explainAr: 'النص يذكر التعليم الابتدائي المجاني للجميع، والتعليم الثانوي المتاح للجميع دون استثناء، والمساواة في الوصول إلى التعليم العالي (equal access to higher education)، فالتعليم متاح في جميع المراحل.',
              },
              {
                q: 'What is guaranteed for parents by education schedule?',
                qAr: 'ما الذي تضمنه خطة التعليم للآباء؟',
                options: ['The right to choose freely appropriate schools for their children, regardless of their beliefs and religions', 'Free private schools for their children', 'The right to set the standards for academic staff', 'A job in an educational institution'],
                answer: 0,
                explainAr: 'في الفقرة الثانية: "Education is the right for parents to choose freely appropriate schools for their children and enroll them in, regardless of their beliefs and religions."',
              },
              {
                q: 'How can a person develop life skills?',
                qAr: 'كيف يستطيع الإنسان أن يطوّر مهاراته الحياتية؟',
                options: ['By looking only at books and difficult exams', 'By applying what one learns in different aspects of economic, social or political life', 'By establishing an educational institution', 'By choosing a private school'],
                answer: 1,
                explainAr: 'يقول النص: "develop different life skills by applying what one learns in different aspects of economic, social or political life" أي بتطبيق ما يتعلّمه في جوانب الحياة المختلفة.',
              },
              {
                q: 'How is the government in Syria promoting these principles?',
                qAr: 'كيف تعزّز الحكومة في سوريا هذه المبادئ؟',
                options: ['By closing private schools', 'By making higher education expensive', 'Through free education and adopting new methods of teaching', 'By reducing the number of schools'],
                answer: 2,
                explainAr: 'الفقرة الأخيرة: "through free education and adopting new methods of teaching" أي من خلال التعليم المجاني واعتماد أساليب تدريس جديدة.',
              },
            ],
            trueFalse: [
              { statement: 'Individuals are able to achieve social security through communication.', answer: false },
              { statement: 'The right to education prevents individuals from making decisions freely.', answer: false },
              { statement: 'Education schedule ensures quality and meaningful education only in public schools.', answer: false },
              { statement: 'Education decreases people’s knowledge about the world.', answer: false },
              { statement: 'Primary education should be available for all, free of charge.', answer: true },
            ],
          },
        ],
        exercises: [
          // ---- Reading a: match the words with their meanings ----
          {
            type: 'mcq', prompt: 'Match the word with its meaning: sustainable',
            promptAr: 'اختر معنى الكلمة sustainable.',
            options: ['a part of something', 'can continue for a long time', 'professional', 'obligatory or compulsory'], answer: 1,
            explainAr: 'sustainable = مُستدام: يمكن أن يستمر وقتاً طويلاً، كما في sustainable development (التنمية المستدامة) في النص.',
          },
          {
            type: 'mcq', prompt: 'Match the word with its meaning: mandatory',
            promptAr: 'اختر معنى الكلمة mandatory.',
            options: ['obligatory or compulsory', 'behave according to law', 'can continue for a long time', 'any specific feature or element of something'], answer: 0,
            explainAr: 'mandatory = إلزامي: أي obligatory or compulsory، كما في "It is something mandatory for the state".',
          },
          {
            type: 'mcq', prompt: 'Match the word with its meaning: vocational',
            promptAr: 'اختر معنى الكلمة vocational.',
            options: ['a part of something', 'obligatory or compulsory', 'professional', 'behave according to law'], answer: 2,
            explainAr: 'vocational = مهني: يتعلّق بتعلّم مهنة، أي professional، كما في "technical, vocational, or training".',
          },
          {
            type: 'mcq', prompt: 'Match the word with its meaning: adhere',
            promptAr: 'اختر معنى الكلمة adhere.',
            options: ['professional', 'can continue for a long time', 'a part of something', 'behave according to law'], answer: 3,
            explainAr: 'adhere (to) = يلتزم بـ: أي يتصرّف وفق القانون أو القواعد، كما في "institution that adheres to the standards".',
          },
          {
            type: 'mcq', prompt: 'Match the word with its meaning: segment',
            promptAr: 'اختر معنى الكلمة segment.',
            options: ['a part of something', 'any specific feature or element of something', 'obligatory or compulsory', 'professional'], answer: 0,
            explainAr: 'segment = شريحة / جزء: a part of something، كما في "all segments of teachers, leaders, politicians".',
          },
          {
            type: 'mcq', prompt: 'Match the word with its meaning: aspect',
            promptAr: 'اختر معنى الكلمة aspect.',
            options: ['behave according to law', 'can continue for a long time', 'any specific feature or element of something', 'a part of something'], answer: 2,
            explainAr: 'aspect = جانب: any specific feature or element of something، كما في "different aspects of economic, social or political life".',
          },
          // ---- Reading c: rewrite the statements to correct the information ----
          {
            type: 'mcq', prompt: 'Correct the information: "Individuals are able to achieve social security through communication."',
            promptAr: 'صحّح المعلومة: «يستطيع الأفراد تحقيق الأمن الاجتماعي من خلال التواصل.»',
            options: ['Individuals are able to achieve social security through exams.', 'Individuals are able to get rid of poverty and achieve individual and social well-being through education.', 'Individuals are unable to achieve social well-being through education.', 'Only the state is able to achieve social security through communication.'], answer: 1,
            explainAr: 'النص يقول إن التعليم (وليس التواصل) قوة تمكّن الأفراد من التخلّص من الفقر وتحقيق الرفاه الفردي والاجتماعي (individual and social well-being).',
          },
          {
            type: 'mcq', prompt: 'Correct the information: "The right to education prevents individuals from making decisions freely."',
            promptAr: 'صحّح المعلومة: «الحق في التعليم يمنع الأفراد من اتخاذ القرارات بحرية.»',
            options: ['The right to education allows only the government to make decisions.', 'The right to education prevents parents from choosing schools.', 'The right to education gives individuals freedoms, such as the parents’ right to choose schools freely for their children.', 'The right to education makes decisions for individuals.'], answer: 2,
            explainAr: 'النص يقول إن الحق في التعليم يتضمن حريات وحقوقاً، منها حق الآباء في اختيار المدارس المناسبة لأطفالهم بحرية (to choose freely)، وحق إنشاء مؤسسة تعليمية بحرية؛ فهو يعطي الحرية ولا يمنعها.',
          },
          {
            type: 'mcq', prompt: 'Correct the information: "Education schedule ensures quality and meaningful education only in public schools."',
            promptAr: 'صحّح المعلومة: «خطة التعليم تكفل تعليماً جيداً وهادفاً في المدارس العامة فقط.»',
            options: ['Education schedule ensures quality and meaningful education whether in public or private schools and universities.', 'Education schedule ensures quality education only in private schools.', 'Education schedule ensures quality education only in universities.', 'Education schedule does not ensure quality education.'], answer: 0,
            explainAr: 'النص: "ensures quality and meaningful education, whether in public or private schools and universities" أي في المدارس والجامعات العامة والخاصة، لا في العامة فقط.',
          },
          {
            type: 'mcq', prompt: 'Correct the information: "Education decreases people’s knowledge about the world."',
            promptAr: 'صحّح المعلومة: «التعليم يُنقص معرفة الناس بالعالم.»',
            options: ['Education has nothing to do with people’s knowledge.', 'Education decreases people’s interest in other cultures.', 'Education only increases knowledge of books and exams.', 'Education increases people’s knowledge about the world: through it they get to know other cultures and worlds.'], answer: 3,
            explainAr: 'النص: "Its importance lies in getting to know a new world. Through education, people get to know other cultures and worlds" فالتعليم يزيد المعرفة بالعالم.',
          },
          // ---- Vocabulary a: choose the correct words ----
          {
            type: 'fill', prompt: 'Education must be ___ to the development of human personality.',
            promptAr: 'يجب أن يكون التعليم ___ نحو تنمية الشخصية الإنسانية.',
            promptArFull: 'يجب أن يكون التعليم مُوجَّهاً نحو تنمية الشخصية الإنسانية.',
            options: ['direction', 'directed', 'directly'], answer: 1,
            explainAr: 'بعد must be نحتاج التصريف الثالث للفعل (مبني للمجهول): must be directed. أما direction فاسم وdirectly ظرف.',
          },
          {
            type: 'fill', prompt: 'Civil rights are secured by a positive government ___.',
            promptAr: 'تُصان الحقوق المدنية عن طريق ___ حكومي إيجابي.',
            promptArFull: 'تُصان الحقوق المدنية عن طريق عمل حكومي إيجابي.',
            options: ['active', 'actively', 'action'], answer: 2,
            explainAr: 'بعد أداة النكرة a والصفة positive نحتاج اسماً: action (عمل / إجراء). active صفة وactively ظرف.',
          },
          {
            type: 'fill', prompt: 'Political rights are a class of rights that ___ individual’s freedom.',
            promptAr: 'الحقوق السياسية فئة من الحقوق التي ___ حرية الفرد.',
            promptArFull: 'الحقوق السياسية فئة من الحقوق التي تحمي حرية الفرد.',
            options: ['protect', 'protection', 'protective'], answer: 0,
            explainAr: 'بعد ضمير الوصل that نحتاج فعلاً للجملة الموصولة، والاسم الذي يعود عليه rights جمع، فنقول protect دون s. protection اسم وprotective صفة.',
          },
          {
            type: 'fill', prompt: 'Civil rights guarantee equal ___ opportunities.',
            promptAr: 'تضمن الحقوق المدنية فرصاً ___ متساوية.',
            promptArFull: 'تضمن الحقوق المدنية فرصاً اجتماعية متساوية.',
            options: ['society', 'social', 'socially'], answer: 1,
            explainAr: 'قبل الاسم opportunities نحتاج صفة: social (اجتماعي). society اسم وsocially ظرف.',
          },
          {
            type: 'fill', prompt: 'Education ___ the respect for human rights.',
            promptAr: 'التعليم ___ احترام حقوق الإنسان.',
            promptArFull: 'التعليم يقوّي احترام حقوق الإنسان.',
            options: ['strong', 'strength', 'strengthens'], answer: 2,
            explainAr: 'الجملة تحتاج فعلاً مضارعاً بسيطاً، والفاعل Education مفرد فنضيف s: strengthens (يقوّي). strong صفة وstrength اسم.',
          },
          // ---- Vocabulary b: complete the paragraph ----
          {
            type: 'fill', prompt: 'The rights of all children from early ___ stem from the 1948 Universal Declaration of Human Rights.',
            promptAr: 'تنبع حقوق جميع الأطفال منذ ___ المبكرة من الإعلان العالمي لحقوق الإنسان لعام 1948.',
            promptArFull: 'تنبع حقوق جميع الأطفال منذ الطفولة المبكرة من الإعلان العالمي لحقوق الإنسان لعام 1948.',
            options: ['childhood', 'beings', 'assistance', 'states'], answer: 0,
            explainAr: 'early childhood = الطفولة المبكرة؛ بعد الصفة early نحتاج اسماً يناسب حقوق الأطفال.',
          },
          {
            type: 'fill', prompt: '‘All human ___ are born free and equal in dignity and rights’.',
            promptAr: '«يولد جميع ___ البشر أحراراً ومتساوين في الكرامة والحقوق».',
            promptArFull: '«يولد جميع الكائنات البشرية (الناس) أحراراً ومتساوين في الكرامة والحقوق».',
            options: ['states', 'beings', 'including', 'childhood'], answer: 1,
            explainAr: 'human beings = البشر / الكائنات البشرية، والفعل are جمع فنحتاج اسماً جمعاً: beings.',
          },
          {
            type: 'fill', prompt: 'The declaration ___ that human rights begin at birth.',
            promptAr: 'الإعلان ___ أن حقوق الإنسان تبدأ منذ الولادة.',
            promptArFull: 'الإعلان ينصّ على أن حقوق الإنسان تبدأ منذ الولادة.',
            options: ['including', 'assistance', 'states', 'beings'], answer: 2,
            explainAr: 'نحتاج فعلاً مع الفاعل المفرد The declaration: states (ينصّ / يذكر) + that.',
          },
          {
            type: 'fill', prompt: 'Childhood is a period demanding special care and ___.',
            promptAr: 'الطفولة مرحلة تتطلّب رعاية خاصة و___.',
            promptArFull: 'الطفولة مرحلة تتطلّب رعاية خاصة ومساعدة.',
            options: ['assistance', 'childhood', 'states', 'including'], answer: 0,
            explainAr: 'بعد and نحتاج اسماً يعطَف على care: assistance (مساعدة).',
          },
          {
            type: 'fill', prompt: 'The 1959 Declaration of the Rights of the Child affirmed that: ‘mankind owes to the child the best it has to give’, ___ education.',
            promptAr: 'أكّد إعلان حقوق الطفل لعام 1959 أن: «على البشرية أن تقدّم للطفل أفضل ما لديها»، ___ التعليم.',
            promptArFull: 'أكّد إعلان حقوق الطفل لعام 1959 أن: «على البشرية أن تقدّم للطفل أفضل ما لديها»، بما في ذلك التعليم.',
            options: ['beings', 'states', 'assistance', 'including'], answer: 3,
            explainAr: 'including = بما في ذلك، يأتي قبل مثال (education) مما سبق ذكره.',
          },
          // ---- Pronunciation b: classify the sounds ----
          {
            type: 'mcq', prompt: 'Which sounds in bold are voiced? (church, John, sister, zoo)',
            promptAr: 'أي الأصوات المكتوبة بالخط العريض مجهورة (voiced)؟',
            options: ['/tʃ/ (church) and /s/ (sister)', '/dʒ/ (John) and /z/ (zoo)', '/tʃ/ (child) and /z/ (zone)', '/s/ (see) and /dʒ/ (gentle)'], answer: 1,
            explainAr: 'الصوت المجهور تهتز معه الأحبال الصوتية: /dʒ/ و/z/ مجهوران، أما /tʃ/ و/s/ فمهموسان (voiceless).',
          },
          {
            type: 'mcq', prompt: 'Which sounds in bold are voiceless? (chair, January, Simon, zigzag)',
            promptAr: 'أي الأصوات المكتوبة بالخط العريض مهموسة (voiceless)؟',
            options: ['/dʒ/ and /z/', '/dʒ/ and /s/', '/tʃ/ and /s/', '/z/ and /tʃ/'], answer: 2,
            explainAr: 'الصوت المهموس لا تهتز معه الأحبال الصوتية: /tʃ/ (chair) و/s/ (Simon). كل منهما له نظير مجهور: /tʃ/–/dʒ/ و/s/–/z/.',
          },
          {
            type: 'truefalse', prompt: 'The sound /tʃ/ in church, child and chair is voiced.', answer: false,
            promptAr: 'الصوت /tʃ/ في church وchild وchair مجهور.',
            explainAr: 'خطأ: /tʃ/ صوت مهموس (voiceless)؛ نظيره المجهور هو /dʒ/.',
          },
          {
            type: 'truefalse', prompt: 'The sound /dʒ/ in John, gentle and January is voiced.', answer: true,
            promptAr: 'الصوت /dʒ/ في John وgentle وJanuary مجهور.',
            explainAr: 'صحيح: عند نطق /dʒ/ تهتز الأحبال الصوتية، فهو مجهور (voiced).',
          },
          {
            type: 'truefalse', prompt: 'The sound /s/ in sister, Simon and see is voiceless.', answer: true,
            promptAr: 'الصوت /s/ في sister وSimon وsee مهموس.',
            explainAr: 'صحيح: /s/ مهموس (voiceless) لا تهتز معه الأحبال الصوتية.',
          },
          {
            type: 'truefalse', prompt: 'The sound /z/ in zoo, zigzag and zone is voiceless.', answer: false,
            promptAr: 'الصوت /z/ في zoo وzigzag وzone مهموس.',
            explainAr: 'خطأ: /z/ مجهور (voiced)؛ نظيره المهموس هو /s/.',
          },
          {
            type: 'mcq', prompt: 'Which word begins with a voiced sound?',
            promptAr: 'أي كلمة تبدأ بصوت مجهور؟',
            options: ['chair', 'Simon', 'January', 'see'], answer: 2,
            explainAr: 'January تبدأ بالصوت /dʒ/ وهو مجهور. أما chair (/tʃ/) وSimon وsee (/s/) فتبدأ بأصوات مهموسة.',
          },
          // ---- Grammar a: choose the correct pronoun ----
          {
            type: 'fill', prompt: 'We have a package for the man ___ stopped by today.',
            promptAr: 'لدينا طرد للرجل ___ مرّ اليوم.',
            promptArFull: 'لدينا طرد للرجل الذي مرّ اليوم.',
            options: ['which', 'who', 'whose'], answer: 1,
            explainAr: 'the man شخص، وضمير الوصل هنا فاعل للفعل stopped، فنستخدم who. which للأشياء.',
          },
          {
            type: 'fill', prompt: 'I met the author ___ book is on the best-seller list.',
            promptAr: 'قابلت المؤلف ___ كتابه على قائمة الكتب الأكثر مبيعاً.',
            promptArFull: 'قابلت المؤلف الذي كتابه على قائمة الكتب الأكثر مبيعاً.',
            options: ['who', 'which', 'whose'], answer: 2,
            explainAr: 'whose يدل على الملكية (كتابه = his book) ويأتي بعده اسم مباشرة: whose book.',
          },
          {
            type: 'fill', prompt: 'The income tax, ___ he paid last year, is accurate.',
            promptAr: 'ضريبة الدخل، ___ دفعها العام الماضي، صحيحة.',
            promptArFull: 'ضريبة الدخل، التي دفعها العام الماضي، صحيحة.',
            options: ['that', 'which', 'who'], answer: 1,
            explainAr: 'الجملة الموصولة هنا غير محدِّدة (non-defining) لأنها بين فاصلتين، و that لا تُستخدم إلا في الجمل المحدِّدة، فنستخدم which للأشياء.',
          },
          {
            type: 'fill', prompt: 'Will you be presenting the slides ___ you took in Canada last summer?',
            promptAr: 'هل ستعرض الشرائح (الصور) ___ التقطتها في كندا الصيف الماضي؟',
            promptArFull: 'هل ستعرض الشرائح (الصور) التي التقطتها في كندا الصيف الماضي؟',
            options: ['whose', 'which', 'who'], answer: 1,
            explainAr: 'the slides أشياء وهي مفعول به للفعل took، فنستخدم which (أو that). whose للملكية.',
          },
          {
            type: 'fill', prompt: 'This is the city in ___ Shakespeare was born.',
            promptAr: 'هذه هي المدينة ___ وُلد شكسبير.',
            promptArFull: 'هذه هي المدينة التي وُلد فيها شكسبير.',
            options: ['where', 'that', 'which'], answer: 2,
            explainAr: 'بعد حرف الجر in نستخدم which (in which = where). لا نقول in where ولا in that.',
          },
          {
            type: 'fill', prompt: 'The evening is a time ___ we can all relax.',
            promptAr: 'المساء وقت ___ نستطيع جميعاً أن نرتاح.',
            promptArFull: 'المساء وقت نستطيع فيه جميعاً أن نرتاح.',
            options: ['where', 'which', 'when'], answer: 2,
            explainAr: 'a time يدل على زمن، فنستخدم when للأوقات. where للأماكن.',
          },
          // ---- Grammar b: combine the sentences ----
          {
            type: 'mcq', prompt: 'Combine: Lubna bought a dress. The dress cost $45. She had to return it.',
            promptAr: 'ادمج: اشترت لبنى فستاناً. كلّف الفستان 45 دولاراً. اضطرت إلى إعادته.',
            options: ['Lubna bought a dress who cost $45, but she had to return it.', 'Lubna bought a dress which it cost $45, but she had to return it.', 'Lubna bought a dress which cost $45, but she had to return it.', 'Lubna bought a dress whose cost $45, but she had to return it.'], answer: 2,
            explainAr: 'the dress شيء فنستخدم which (أو that) ونحذف الكلمة المكررة The dress؛ ولا نضيف it بعد which لأن which حلّت محلّها.',
          },
          {
            type: 'mcq', prompt: 'Combine: Mrs. Duncan is talking to her students. The students’ projects are due on Friday.',
            promptAr: 'ادمج: السيدة دنكن تتحدث إلى طلابها. مشاريع الطلاب مستحقة يوم الجمعة.',
            options: ['Mrs. Duncan is talking to her students whose projects are due on Friday.', 'Mrs. Duncan is talking to her students who projects are due on Friday.', 'Mrs. Duncan is talking to her students which projects are due on Friday.', 'Mrs. Duncan is talking to her students whose their projects are due on Friday.'], answer: 0,
            explainAr: 'The students’ projects تدل على الملكية، فنستبدلها بـ whose + الاسم: whose projects، دون إضافة their.',
          },
          {
            type: 'mcq', prompt: 'Combine: Sally introduced me to her sister. Her sister is a civil engineer.',
            promptAr: 'ادمج: عرّفتني سالي إلى أختها. أختها مهندسة مدنية.',
            options: ['Sally introduced me to her sister, which is a civil engineer.', 'Sally introduced me to her sister, who is a civil engineer.', 'Sally introduced me to her sister, that is a civil engineer.', 'Sally introduced me to her sister, who she is a civil engineer.'], answer: 1,
            explainAr: 'her sister شخص فنستخدم who، والمعلومة إضافية (non-defining) فنضع فاصلة، ولا نستخدم that بعد الفاصلة، ولا نكرر الضمير she.',
          },
          {
            type: 'build', prompt: 'ادمج باستخدام when: الصيف هو الوقت من السنة الذي يكون فيه الطقس الأشد حرارة.',
            answer: 'Summer is the time of year when the weather is the hottest.',
          },
          {
            type: 'mcq', prompt: 'Combine: We went to a café on Sunday. It was very nice.',
            promptAr: 'ادمج: ذهبنا إلى مقهى يوم الأحد. كان جميلاً جداً.',
            options: ['The café where we went to on Sunday was very nice.', 'The café which we went to it on Sunday was very nice.', 'The café who we went to on Sunday was very nice.', 'The café which we went to on Sunday was very nice.'], answer: 3,
            explainAr: 'café مكان نذكره كشيء مع حرف الجر to في آخر الجملة: which ... went to. لا نقول where ... to، ولا نكرر it.',
          },
          {
            type: 'mcq', prompt: 'Combine: Yesterday I ran into an old friend. I hadn’t seen him for years.',
            promptAr: 'ادمج: صادفت أمس صديقاً قديماً. لم أكن قد رأيته منذ سنوات.',
            options: ['Yesterday I ran into an old friend whom I hadn’t seen for years.', 'Yesterday I ran into an old friend whom I hadn’t seen him for years.', 'Yesterday I ran into an old friend which I hadn’t seen for years.', 'Yesterday I ran into an old friend whose I hadn’t seen for years.'], answer: 0,
            explainAr: 'friend شخص وهو مفعول به للفعل seen، فنستخدم whom (أو who)، ونحذف him لأن whom حلّت محلّه.',
          },
          {
            type: 'build', prompt: 'ادمج باستخدام whose: أعرف رجلاً اسم عائلته Goose.',
            answer: 'I know a man whose last name is Goose.',
          },
          // ---- Grammar c: complete the sentences with relative clauses ----
          {
            type: 'fill', prompt: 'I know someone ___.',
            promptAr: 'أعرف شخصاً ___.',
            promptArFull: 'أعرف شخصاً يعمل محامياً.',
            options: ['which works as a lawyer', 'who works as a lawyer', 'whose works as a lawyer'], answer: 1,
            explainAr: 'someone شخص، وضمير الوصل فاعل للفعل works، فنستخدم who.',
          },
          {
            type: 'fill', prompt: 'The courses I’m taking this term are more difficult than the ones ___.',
            promptAr: 'المقررات التي أدرسها هذا الفصل أصعب من تلك ___.',
            promptArFull: 'المقررات التي أدرسها هذا الفصل أصعب من تلك التي درستها في الفصل الماضي.',
            options: ['I took last term', 'who I took last term', 'where I took last term'], answer: 0,
            explainAr: 'the ones = the courses (أشياء) وهي مفعول به، فيمكن حذف ضمير الوصل (that/which) في الجملة المحدِّدة: the ones (that) I took last term. who للأشخاص وwhere للأماكن.',
          },
          {
            type: 'fill', prompt: 'The teacher thanked the students ___.',
            promptAr: 'شكر المعلم الطلاب ___.',
            promptArFull: 'شكر المعلم الطلاب الذين ساعدوه.',
            options: ['which helped him', 'whose helped him', 'who helped him'], answer: 2,
            explainAr: 'the students أشخاص وضمير الوصل فاعل للفعل helped، فنستخدم who.',
          },
          {
            type: 'fill', prompt: 'We enjoyed the city ___.',
            promptAr: 'استمتعنا بالمدينة ___.',
            promptArFull: 'استمتعنا بالمدينة التي قضينا فيها عطلتنا.',
            options: ['where we spent our holiday', 'which we spent our holiday', 'when we spent our holiday'], answer: 0,
            explainAr: 'the city مكان، والجملة بعدها كاملة (we spent our holiday) فنستخدم where. which تحتاج إلى حرف جر (which we spent our holiday in).',
          },
          {
            type: 'fill', prompt: 'I will never forget the day ___.',
            promptAr: 'لن أنسى أبداً اليوم ___.',
            promptArFull: 'لن أنسى أبداً اليوم الذي تخرّجت فيه.',
            options: ['where I graduated', 'when I graduated', 'which I graduated'], answer: 1,
            explainAr: 'the day زمن، فنستخدم when للأوقات.',
          },
          // ---- Everyday English: complaints and apologies ----
          {
            type: 'fill', prompt: 'Boss: Emily! What’s the matter with you? ___.',
            promptAr: 'المدير: إيميلي! ما مشكلتك؟ ___.',
            promptArFull: 'المدير: إيميلي! ما مشكلتك؟ أنتِ تتأخرين عن العمل دائماً.',
            options: ['You’re always coming late to work', 'Please forgive me', 'I promise it won’t happen again', 'That isn’t an excuse'], answer: 0,
            explainAr: 'المدير يشتكي، والشكوى من سلوك متكرر تأتي بالمضارع المستمر مع always: You’re always coming late to work.',
          },
          {
            type: 'fill', prompt: 'Employee: Please ___, sir. I’ve been busy taking care of my son these days.',
            promptAr: 'الموظفة: أرجو أن ___ يا سيدي. كنت مشغولة برعاية ابني هذه الأيام.',
            promptArFull: 'الموظفة: أرجو أن تقبل عذري يا سيدي. كنت مشغولة برعاية ابني هذه الأيام.',
            options: ['hurt your feelings', 'accept my excuse', 'that isn’t an excuse', 'promise it won’t happen again'], answer: 1,
            explainAr: 'الموظفة تعتذر وتقدّم سبب تأخرها، فتقول: Please accept my excuse (أرجو أن تقبل عذري).',
          },
          {
            type: 'fill', prompt: 'Boss: Oh, in that case ___, for shouting at you like that.',
            promptAr: 'المدير: أوه، في هذه الحالة ___ لأنني صرخت عليكِ هكذا.',
            promptArFull: 'المدير: أوه، في هذه الحالة أرجو أن تسامحيني لأنني صرخت عليكِ هكذا.',
            options: ['accept my excuse', 'You’re always coming late to work', 'please forgive me', 'hurt your feelings'], answer: 2,
            explainAr: 'المدير يعتذر عن صراخه: please forgive me (أرجو أن تسامحيني).',
          },
          {
            type: 'fill', prompt: 'Jack: Come on darling! You know I’d never ___.',
            promptAr: 'جاك: هيا يا عزيزتي! تعرفين أنني لن ___ أبداً.',
            promptArFull: 'جاك: هيا يا عزيزتي! تعرفين أنني لن أجرح مشاعرك أبداً.',
            options: ['hurt your feelings', 'accept my excuse', 'please forgive me', 'that isn’t an excuse'], answer: 0,
            explainAr: 'بعد I’d never نحتاج فعلاً في المصدر: hurt your feelings (أجرح مشاعرك).',
          },
          {
            type: 'fill', prompt: 'Kate: I know that but ___! I work too and I’m going through a tough period in my career.',
            promptAr: 'كيت: أعرف ذلك لكن ___! أنا أعمل أيضاً وأمرّ بفترة صعبة في عملي.',
            promptArFull: 'كيت: أعرف ذلك لكن هذا ليس عذراً! أنا أعمل أيضاً وأمرّ بفترة صعبة في عملي.',
            options: ['please forgive me', 'that isn’t an excuse', 'hurt your feelings', 'accept my excuse'], answer: 1,
            explainAr: 'كيت ترفض عذر جاك (ضغط العمل): that isn’t an excuse (هذا ليس عذراً).',
          },
          {
            type: 'fill', prompt: 'Jack: I apologise for not remembering our special day and I ___.',
            promptAr: 'جاك: أعتذر عن عدم تذكّر يومنا المميز و___.',
            promptArFull: 'جاك: أعتذر عن عدم تذكّر يومنا المميز وأعدك أن ذلك لن يتكرر.',
            options: ['accept my excuse', 'hurt your feelings', 'promise it won’t happen again', 'You’re always coming late to work'], answer: 2,
            explainAr: 'بعد الاعتذار نَعِد بعدم التكرار: I promise it won’t happen again (أعدك أن ذلك لن يتكرر).',
          },
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Write an article about a person’s rights and duties in society.',
          topicAr: 'اكتب مقالاً عن حقوق الإنسان وواجباته في المجتمع بعنوان «A man is born with rights and duties» (يولد الإنسان ومعه حقوق وواجبات)، ثم راجعه لتصحيح الأخطاء الإملائية والنحوية وانتبه لعلامات الترقيم.',
          words: 100,
          points: ['A man is born with rights and duties', 'Participating in an election', 'Parents should send their children to school', 'Women go to work', 'Children have to obey their parents', 'Keeping surroundings clean'],
          pointsAr: ['العنوان: يولد الإنسان ومعه حقوق وواجبات', 'المشاركة في الانتخابات (حق)', 'يجب على الآباء إرسال أطفالهم إلى المدرسة (واجب)', 'خروج المرأة إلى العمل (حق)', 'يجب على الأطفال طاعة والديهم (واجب)', 'الحفاظ على نظافة المحيط (واجب)'],
          plan: [
            { en: 'Topic sentence: every person is born with rights and duties.', ar: 'الجملة الافتتاحية (topic sentence): كل إنسان يولد ومعه حقوق وواجبات.' },
            { en: 'Rights: the right to vote, to a fair trial, to a public education and to work — regardless of race or religion.', ar: 'الحقوق: حق التصويت، والمحاكمة العادلة، والتعليم العام، والعمل — بغضّ النظر عن العرق أو الدين.' },
            { en: 'Duties: parents send their children to school, children obey their parents, everyone keeps the surroundings clean and never breaks the law.', ar: 'الواجبات: يرسل الآباء أطفالهم إلى المدرسة، ويطيع الأطفال والديهم، ويحافظ الجميع على نظافة المحيط ولا يخالفون القانون.' },
            { en: 'Conclusion (clincher): a good citizen enjoys his rights and does his duties.', ar: 'الخاتمة: المواطن الصالح يتمتع بحقوقه ويؤدي واجباته.' },
          ],
          phrases: [
            { en: 'Simply speaking, …', ar: 'ببساطة، …' },
            { en: 'In other words, …', ar: 'بعبارة أخرى، …' },
            { en: 'In contrast, …', ar: 'على النقيض من ذلك، …' },
            { en: 'regardless of race, religion, or other personal characteristics', ar: 'بغضّ النظر عن العرق أو الدين أو الصفات الشخصية الأخرى' },
            { en: 'the right to vote', ar: 'حق التصويت' },
            { en: 'the right to a fair trial', ar: 'حق المحاكمة العادلة' },
            { en: 'the right to a public education', ar: 'حق التعليم العام' },
            { en: 'without discrimination', ar: 'دون تمييز' },
            { en: 'citizen / citizenship', ar: 'مواطن / مواطنة' },
            { en: 'break the law', ar: 'يخالف القانون' },
            { en: 'responsibility / obligations', ar: 'مسؤولية / التزامات' },
            { en: 'a person who …', ar: 'شخص الذي … (جملة موصولة)' },
          ],
          model: 'A man is born with rights and duties. Simply speaking, rights are what society gives us, while duties are what we give back to it. Every citizen has the right to vote, the right to a fair trial and the right to a public education, regardless of race, religion or other personal characteristics. Women also have the right to go to work. In contrast, duties are our responsibilities towards others. Parents should send their children to school, children have to obey their parents, and everyone must keep their surroundings clean and never break the law. In other words, a good citizen is a person who enjoys his rights and does his duties.',
          modelAr: 'يولد الإنسان ومعه حقوق وواجبات. ببساطة، الحقوق هي ما يعطينا إياه المجتمع، بينما الواجبات هي ما نردّه إليه. لكل مواطن حق التصويت وحق المحاكمة العادلة وحق التعليم العام، بغضّ النظر عن العرق أو الدين أو الصفات الشخصية الأخرى. وللمرأة أيضاً حق الخروج إلى العمل. وعلى النقيض من ذلك، فإن الواجبات هي مسؤولياتنا تجاه الآخرين. يجب على الآباء أن يرسلوا أطفالهم إلى المدرسة، وعلى الأطفال أن يطيعوا والديهم، وعلى كل شخص أن يحافظ على نظافة محيطه وألا يخالف القانون أبداً. بعبارة أخرى، المواطن الصالح هو الشخص الذي يتمتع بحقوقه ويؤدي واجباته.',
          checklistAr: [
            'تبدأ بجملة افتتاحية واضحة تجيب عن الموضوع (يولد الإنسان ومعه حقوق وواجبات).',
            'تذكر حقوقاً بأمثلة (التصويت، المحاكمة العادلة، التعليم، العمل).',
            'تذكر واجبات بأمثلة (إرسال الأطفال إلى المدرسة، طاعة الوالدين، نظافة المحيط، احترام القانون).',
            'تستخدم روابط الوحدة: Simply speaking, In other words, In contrast, while.',
            'تستخدم جملة موصولة واحدة على الأقل (who / which).',
            'تنتهي بجملة ختامية، وتخلو من الأخطاء الإملائية والنحوية مع ترقيم صحيح.',
          ],
        },
        {
          source: 'workbook',
          topic: 'In no more than 100 words, write an essay about the government efforts in Syria to improve education at schools.',
          topicAr: 'اكتب مقالاً في ما لا يزيد على 100 كلمة عن جهود الحكومة في سوريا لتحسين التعليم في المدارس.',
          words: 100,
          points: ['building schools', 'free education', 'private education', 'compulsory education', 'online education'],
          pointsAr: ['بناء المدارس', 'التعليم المجاني', 'التعليم الخاص', 'التعليم الإلزامي', 'التعليم عبر الإنترنت'],
          plan: [
            { en: 'Topic sentence: the Syrian government is working hard to improve education at schools.', ar: 'الجملة الافتتاحية: تعمل الحكومة السورية بجدّ لتحسين التعليم في المدارس.' },
            { en: 'Building schools and free education for all, without discrimination.', ar: 'بناء المدارس والتعليم المجاني للجميع دون تمييز.' },
            { en: 'Compulsory primary education, and private schools that adhere to the state’s standards.', ar: 'التعليم الابتدائي الإلزامي، والمدارس الخاصة الملتزمة بمعايير الدولة.' },
            { en: 'Online education and new methods of teaching.', ar: 'التعليم عبر الإنترنت وأساليب التدريس الجديدة.' },
            { en: 'Conclusion: education is a right which the state guarantees for everyone.', ar: 'الخاتمة: التعليم حق تكفله الدولة للجميع.' },
          ],
          phrases: [
            { en: 'the government is working hard to …', ar: 'تعمل الحكومة بجدّ على …' },
            { en: 'free of charge', ar: 'مجاناً' },
            { en: 'mandatory / compulsory', ar: 'إلزامي' },
            { en: 'without any form of discrimination', ar: 'دون أي شكل من أشكال التمييز' },
            { en: 'adhere to the standards set by the state', ar: 'يلتزم بالمعايير التي وضعتها الدولة' },
            { en: 'adopting new methods of teaching', ar: 'اعتماد أساليب تدريس جديدة' },
            { en: 'quality and meaningful education', ar: 'تعليم جيد وهادف' },
            { en: 'guarantee', ar: 'يضمن / يكفل' },
            { en: 'First, … Second, … In addition, … Finally, …', ar: 'أولاً، … ثانياً، … إضافةً إلى ذلك، … أخيراً، …' },
            { en: 'which means that …', ar: 'مما يعني أن … (جملة موصولة)' },
          ],
          model: 'The Syrian government is working hard to improve education at schools. First, it is building new schools, so that every child has a place to learn. Second, education in public schools is free of charge for all, without any form of discrimination. In addition, primary education is compulsory, which means that parents must send their children to school. There are also private schools which adhere to the standards set by the state. Finally, online education and new methods of teaching help students everywhere. In other words, education is a right which the state guarantees for everyone.',
          modelAr: 'تعمل الحكومة السورية بجدّ لتحسين التعليم في المدارس. أولاً، تبني مدارس جديدة حتى يكون لكل طفل مكان يتعلّم فيه. ثانياً، التعليم في المدارس العامة مجاني للجميع دون أي شكل من أشكال التمييز. إضافةً إلى ذلك، التعليم الابتدائي إلزامي، مما يعني أن على الآباء إرسال أطفالهم إلى المدرسة. وهناك أيضاً مدارس خاصة تلتزم بالمعايير التي وضعتها الدولة. أخيراً، يساعد التعليم عبر الإنترنت وأساليب التدريس الجديدة الطلابَ في كل مكان. بعبارة أخرى، التعليم حق تكفله الدولة للجميع.',
          checklistAr: [
            'لا يزيد على 100 كلمة (المطلوب: in no more than 100 words).',
            'جملة افتتاحية تذكر جهود الحكومة لتحسين التعليم.',
            'تغطي النقاط المساعدة: بناء المدارس، التعليم المجاني، الخاص، الإلزامي، عبر الإنترنت.',
            'تستخدم روابط الترتيب والإضافة: First, Second, In addition, Finally, In other words.',
            'تستخدم جملاً موصولة (which / who) ومفردات الوحدة (free of charge, compulsory, discrimination).',
            'جملة ختامية، وتدقيق الإملاء والأحرف الكبيرة وعلامات الترقيم.',
          ],
        },
      ],
      translations: [
        { en: 'The right to education is one of the basic universal rights of the human being.', ar: 'الحق في التعليم هو أحد الحقوق العالمية الأساسية للإنسان.' },
        { en: 'Education must be directed to the development of human personality.', ar: 'يجب أن يكون التعليم موجَّهاً نحو تنمية الشخصية الإنسانية.' },
        { en: 'Civil rights are secured by a positive government action.', ar: 'تُصان الحقوق المدنية عن طريق عمل حكومي إيجابي.' },
        { en: 'Political rights are a class of rights that protect individual’s freedom.', ar: 'الحقوق السياسية فئة من الحقوق التي تحمي حرية الفرد.' },
        { en: 'Civil rights guarantee equal social opportunities.', ar: 'تضمن الحقوق المدنية فرصاً اجتماعية متساوية.' },
        { en: 'Education strengthens the respect for human rights.', ar: 'يقوّي التعليم احترام حقوق الإنسان.' },
        { en: 'Civil rights are an essential component of democracy.', ar: 'الحقوق المدنية عنصر أساسي من عناصر الديمقراطية.' },
        { en: 'We have a package for the man who stopped by today.', ar: 'لدينا طرد للرجل الذي مرّ اليوم.' },
        { en: 'I met the author whose book is on the best-seller list.', ar: 'قابلت المؤلف الذي يوجد كتابه على قائمة الكتب الأكثر مبيعاً.' },
        { en: 'This is the city in which Shakespeare was born.', ar: 'هذه هي المدينة التي وُلد فيها شكسبير.' },
        { en: 'The evening is a time when we can all relax.', ar: 'المساء وقت نستطيع فيه جميعاً أن نرتاح.' },
        { en: 'Here is the website which my sister created.', ar: 'هذا هو الموقع الإلكتروني الذي أنشأته أختي.' },
        { en: 'My cousin, who volunteers at a local homeless shelter, won the lottery.', ar: 'ابن عمي، الذي يتطوّع في مأوى محلي للمشرّدين، ربح اليانصيب.' },
        { en: 'The woman whose car was stolen called the police.', ar: 'المرأة التي سُرقت سيارتها اتصلت بالشرطة.' },
        { en: 'Lattakia, where I spent my last holiday, is a wonderful city.', ar: 'اللاذقية، حيث قضيت عطلتي الأخيرة، مدينة رائعة.' },
        { en: 'I’m sorry to bother you but the bill you sent me was incorrect.', ar: 'آسف لإزعاجك، لكن الفاتورة التي أرسلتها لي كانت غير صحيحة.' },
        { en: 'Our lawyer is very good and he does every thing exactly as the rules say.', ar: 'محامينا جيد جداً ويفعل كل شيء تماماً كما تنص القواعد.' },
      ],
    },

    // ================= Unit 6 — United Nations (Activity Book pp. 44–51) =================
    u6: {
      workbook: {
        pages: '44–51',
        readings: [
          {
            title: 'UNICEF',
            paragraphs: [
              'The United Nations Children\'s Fund (UNICEF), originally known as the United Nations International Children\'s Emergency Fund, is responsible for providing humanitarian and developmental aid to children worldwide and it has won the Nobel Prize, the first to be awarded to an organisation. Despite being highly active in fundraising, awareness, relief work and research, very few people know the origin of the organisation. UNICEF is supported entirely by the voluntary contributions of governments, non-governmental organisations, foundations, corporations and private individuals and receives no funding from the assessed dues of the United Nations. Most of the fundraising is done by UNICEF\'s 36 national committees, the voluntary support of millions of people around the world, partners in government, civil society and the private sector.',
              'UNICEF was created in 1946 and began with a definite mission of providing emergency food and healthcare to children in the countries that had been destroyed by World War II. In 1953, its original name was changed to the United Nation’s Children Fund to reflect its broader mission, but it retained the original acronym, after being officially adopted as a permanent branch of the UN in 1954.',
              'The agency is among the most widespread and recognisable social welfare organisations in the world. Though its headquarters are in New York City, it operates in over 190 countries, focusing on the welfare of children in at-risk areas. Since 2006, the organisation has concentrated on a few specific issues; child survival and development, basic education and gender equality, child protection and policy advocacy, and partnerships. UNICEF has been a key player in global development work since its beginning. UNICEF operates during emergencies in addition to supporting developing countries to provide children with basic resources and advocate for their rights.',
              'At last, UNICEF is working to create a world in which no child is ever bought or sold, stolen from a family or otherwise victimised. UNICEF believes that every child deserves to grow up in a loving family and it supports inter-country adoption when conducted ethically in accordance with prevailing law and best practices. At the same time, UNICEF works to support families in need so that no one ever feels forced by poverty or insecurity to give up a child.',
            ],
            paragraphsAr: [
              'منظمة الأمم المتحدة للطفولة (اليونيسف)، التي عُرفت في الأصل باسم صندوق الأمم المتحدة الدولي لرعاية الطفولة في حالات الطوارئ، مسؤولة عن تقديم المساعدات الإنسانية والتنموية للأطفال في جميع أنحاء العالم، وقد فازت بجائزة نوبل، وكانت أول منظمة تُمنح هذه الجائزة. ورغم نشاطها الكبير في جمع التبرعات والتوعية وأعمال الإغاثة والبحث، فإن قلة قليلة من الناس يعرفون أصل هذه المنظمة. تعتمد اليونيسف كلياً على المساهمات الطوعية من الحكومات والمنظمات غير الحكومية والمؤسسات والشركات والأفراد، ولا تتلقى أي تمويل من الاشتراكات المقرَّرة للأمم المتحدة. ويتولى معظمَ جمع التبرعات 36 لجنة وطنية تابعة لليونيسف، إلى جانب الدعم الطوعي لملايين الناس حول العالم، وشركائها في الحكومات والمجتمع المدني والقطاع الخاص.',
              'أُنشئت اليونيسف عام 1946 وبدأت بمهمة محدّدة هي تقديم الغذاء والرعاية الصحية الطارئة للأطفال في البلدان التي دمّرتها الحرب العالمية الثانية. وفي عام 1953 تغيّر اسمها الأصلي إلى صندوق الأمم المتحدة للطفولة ليعكس مهمتها الأوسع، لكنها احتفظت بالاختصار الأصلي، بعد أن اعتُمدت رسمياً فرعاً دائماً من فروع الأمم المتحدة عام 1954.',
              'تُعدّ هذه الوكالة من أوسع منظمات الرعاية الاجتماعية انتشاراً وأكثرها شهرة في العالم. ومع أن مقرها الرئيسي في مدينة نيويورك، فإنها تعمل في أكثر من 190 دولة، مركّزةً على رعاية الأطفال في المناطق المعرّضة للخطر. ومنذ عام 2006 ركّزت المنظمة على عدد قليل من القضايا المحددة: بقاء الطفل ونموّه، والتعليم الأساسي والمساواة بين الجنسين، وحماية الطفل والدفاع عن السياسات، والشراكات. وقد كانت اليونيسف لاعباً رئيسياً في أعمال التنمية العالمية منذ بدايتها. وتعمل اليونيسف في حالات الطوارئ، إضافةً إلى دعم البلدان النامية لتزويد الأطفال بالموارد الأساسية والدفاع عن حقوقهم.',
              'وأخيراً، تعمل اليونيسف على خلق عالم لا يُباع فيه أي طفل أو يُشترى، ولا يُخطف من أسرته، ولا يقع ضحية بأي شكل آخر. وتؤمن اليونيسف بأن كل طفل يستحق أن ينشأ في أسرة محبّة، وهي تدعم التبنّي بين البلدان عندما يُجرى بطريقة أخلاقية وفقاً للقانون السائد وأفضل الممارسات. وفي الوقت نفسه، تعمل اليونيسف على دعم الأسر المحتاجة حتى لا يشعر أحد أبداً بأن الفقر أو انعدام الأمان يجبره على التخلّي عن طفله.',
            ],
            questions: [
              {
                q: 'What does the acronym UNICEF stand for?',
                qAr: 'إلامَ يشير الاختصار UNICEF؟',
                options: ['United Nations International Children\'s Emergency Fund', 'United Nations Children\'s Education Foundation', 'United Nations International Committee for Education and Families', 'United Nations Institute for Children\'s Equality'], answer: 0,
                explainAr: 'النص: "originally known as the United Nations International Children\'s Emergency Fund"، وقد احتفظت المنظمة بهذا الاختصار الأصلي (it retained the original acronym) رغم تغيير اسمها.',
              },
              {
                q: 'Where does UNICEF get its funding?',
                qAr: 'من أين تحصل اليونيسف على تمويلها؟',
                options: ['From the assessed dues of the United Nations', 'From the voluntary contributions of governments, non-governmental organisations, foundations, corporations and private individuals', 'Only from the government of the United States', 'From selling children\'s books'], answer: 1,
                explainAr: 'النص: "UNICEF is supported entirely by the voluntary contributions of governments, non-governmental organisations, foundations, corporations and private individuals and receives no funding from the assessed dues of the United Nations."',
              },
              {
                q: 'Mention two purposes of establishing UNICEF.',
                qAr: 'اذكر هدفين من أهداف تأسيس اليونيسف.',
                options: ['Building schools and hospitals in New York City', 'Organising the Nobel Prize and World War II', 'Providing emergency food and healthcare to children in countries destroyed by World War II, and providing humanitarian and developmental aid to children worldwide', 'Collecting the assessed dues of the United Nations and choosing its members'], answer: 2,
                explainAr: 'النص يذكر أن اليونيسف أُنشئت بمهمة "providing emergency food and healthcare to children in the countries that had been destroyed by World War II"، وأنها مسؤولة عن "providing humanitarian and developmental aid to children worldwide".',
              },
              {
                q: 'Why did UNICEF change its name?',
                qAr: 'لماذا غيّرت اليونيسف اسمها؟',
                options: ['Because it moved its headquarters', 'Because it won the Nobel Prize', 'Because it stopped working in emergencies', 'To reflect its broader mission'], answer: 3,
                explainAr: 'النص: "its original name was changed to the United Nation’s Children Fund to reflect its broader mission" أي ليعكس مهمتها الأوسع.',
              },
              {
                q: 'What are UNICEF’s main goals?',
                qAr: 'ما الأهداف الرئيسية لليونيسف؟',
                options: ['Child survival and development, basic education and gender equality, child protection and policy advocacy, and partnerships', 'Trade and finance between countries', 'Fighting diseases among adults only', 'Choosing the members of the Security Council'], answer: 0,
                explainAr: 'النص: "Since 2006, the organisation has concentrated on a few specific issues; child survival and development, basic education and gender equality, child protection and policy advocacy, and partnerships." كما تعمل على خلق عالم يُحمى فيه كل طفل.',
              },
              {
                q: 'Where are UNICEF’s headquarters?',
                qAr: 'أين يقع المقر الرئيسي لليونيسف؟',
                options: ['In Geneva', 'In New York City', 'In Vienna', 'In Nairobi'], answer: 1,
                explainAr: 'النص: "Though its headquarters are in New York City, it operates in over 190 countries".',
              },
            ],
            trueFalse: [
              { statement: 'UNICEF receives funding from the assessed dues of the United Nations.', answer: false },
              { statement: 'UNICEF was created in 1946.', answer: true },
              { statement: 'UNICEF operates in over 190 countries.', answer: true },
              { statement: 'UNICEF supports inter-country adoption in all cases, even when it is not ethical.', answer: false },
            ],
          },
        ],
        exercises: [
          // ---- Reading b: match the definitions with the highlighted words ----
          {
            type: 'mcq', prompt: 'Which highlighted word means "to defend or support"?',
            promptAr: 'أي كلمة من الكلمات المظلّلة تعني «يدافع عن أو يدعم»؟',
            options: ['adopted', 'advocate', 'prevailing', 'corporations'], answer: 1,
            explainAr: 'advocate = يدافع عن / يؤيّد، كما في "advocate for their rights" (الدفاع عن حقوقهم).',
          },
          {
            type: 'mcq', prompt: 'Which highlighted word means "the activity of collecting money for a specific purpose, especially in order to help people"?',
            promptAr: 'أي كلمة من الكلمات المظلّلة تعني «جمع المال لغرض محدد، وخاصة لمساعدة الناس»؟',
            options: ['prevailing', 'advocate', 'Fund', 'adopted'], answer: 2,
            explainAr: 'Fund = صندوق (مالي): المال الذي يُجمع لغرض محدد، كما في United Nations Children\'s Fund. وهي الكلمة المظلّلة الوحيدة المتصلة بجمع المال.',
          },
          {
            type: 'mcq', prompt: 'Which highlighted word means "existing or accepted in a particular place or at a particular time"?',
            promptAr: 'أي كلمة من الكلمات المظلّلة تعني «موجود أو مقبول في مكان معيّن أو في وقت معيّن»؟',
            options: ['corporations', 'Fund', 'advocate', 'prevailing'], answer: 3,
            explainAr: 'prevailing = سائد / معمول به، كما في "in accordance with prevailing law" (وفقاً للقانون السائد).',
          },
          {
            type: 'mcq', prompt: 'Which highlighted word means "to select and take or approve"?',
            promptAr: 'أي كلمة من الكلمات المظلّلة تعني «يختار ويأخذ أو يوافق على»؟',
            options: ['adopted', 'prevailing', 'Fund', 'advocate'], answer: 0,
            explainAr: 'adopt = يتبنّى / يعتمد، كما في "after being officially adopted as a permanent branch of the UN" (بعد اعتمادها رسمياً فرعاً دائماً).',
          },
          {
            type: 'mcq', prompt: 'Which highlighted word means "an organisation or a group of organisations that work together for a particular purpose"?',
            promptAr: 'أي كلمة من الكلمات المظلّلة تعني «منظمة أو مجموعة منظمات تعمل معاً لغرض معيّن»؟',
            options: ['advocate', 'corporations', 'prevailing', 'adopted'], answer: 1,
            explainAr: 'corporation = شركة / مؤسسة كبرى: مجموعة تعمل معاً لغرض محدد، كما في "foundations, corporations and private individuals".',
          },
          // ---- Vocabulary: prefixes un- / dis- ----
          {
            type: 'fill', prompt: 'Children love ___ parcels at Christmas time. (wrap)',
            promptAr: 'يحب الأطفال ___ الطرود في عيد الميلاد.',
            promptArFull: 'يحب الأطفال فتحَ (فكّ تغليف) الطرود في عيد الميلاد.',
            options: ['unwrapping', 'diswrapping', 'unwrap'], answer: 0,
            explainAr: 'البادئة un- مع wrap تعطي المعنى المعاكس: unwrap (يفكّ الغلاف). بعد love نستخدم الفعل مع -ing: unwrapping.',
          },
          {
            type: 'fill', prompt: 'I almost find that he has unusual opinions. I often ___ with him. (agree)',
            promptAr: 'أجد تقريباً أن لديه آراء غير مألوفة. غالباً ما ___ معه.',
            promptArFull: 'أجد تقريباً أن لديه آراء غير مألوفة. غالباً ما أختلف معه.',
            options: ['unagree', 'disagree', 'disagrees'], answer: 1,
            explainAr: 'نفي agree يكون بالبادئة dis-: disagree (يختلف في الرأي). الفاعل I فلا نضيف s.',
          },
          {
            type: 'fill', prompt: 'I’m sure he’s lying but it’s going to be hard to ___ his story. (prove)',
            promptAr: 'أنا متأكد أنه يكذب لكن سيكون من الصعب ___ قصته.',
            promptArFull: 'أنا متأكد أنه يكذب لكن سيكون من الصعب إثبات عدم صحة قصته (دحضها).',
            options: ['unprove', 'disproved', 'disprove'], answer: 2,
            explainAr: 'disprove = يُثبت عدم صحة الشيء (عكس prove) بالبادئة dis-. بعد to نستخدم المصدر: to disprove.',
          },
          {
            type: 'fill', prompt: 'After a brief speech, the minister ___ the new statue. (veil)',
            promptAr: 'بعد كلمة قصيرة، ___ الوزير التمثال الجديد.',
            promptArFull: 'بعد كلمة قصيرة، أزاح الوزير الستار عن التمثال الجديد.',
            options: ['disveiled', 'unveils', 'unveiled'], answer: 2,
            explainAr: 'unveil = يزيح الستار عن (بالبادئة un-). الحدث في الماضي فنستخدم الماضي البسيط: unveiled.',
          },
          {
            type: 'fill', prompt: 'It took the removal men an hour to ___ our things from the van. (load)',
            promptAr: 'استغرق عمال نقل الأثاث ساعة لـ___ أغراضنا من الشاحنة.',
            promptArFull: 'استغرق عمال نقل الأثاث ساعة لتفريغ أغراضنا من الشاحنة.',
            options: ['unload', 'disload', 'unloaded'], answer: 0,
            explainAr: 'unload = يُفرغ الحمولة (عكس load) بالبادئة un-. بعد to نستخدم المصدر: to unload.',
          },
          {
            type: 'fill', prompt: 'His phone was ___ because he didn’t pay his last bill. (connect)',
            promptAr: '___ هاتفه لأنه لم يدفع فاتورته الأخيرة.',
            promptArFull: 'قُطع (فُصل) هاتفه لأنه لم يدفع فاتورته الأخيرة.',
            options: ['unconnected', 'disconnected', 'disconnect'], answer: 1,
            explainAr: 'disconnect = يفصل / يقطع الخدمة بالبادئة dis-. بعد was نستخدم التصريف الثالث (مبني للمجهول): was disconnected.',
          },
          // ---- Pronunciation: word stress with two syllables ----
          {
            type: 'mcq', prompt: 'Stress and word class: "We need to increase our sales figures." (increase)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «نحتاج إلى زيادة أرقام مبيعاتنا.»',
            options: ['INcrease — 1st syllable stressed (noun)', 'inCREASE — 2nd syllable stressed (verb)', 'INcrease — 1st syllable stressed (verb)'], answer: 1,
            explainAr: 'بعد to نحتاج فعلاً، والأفعال ذات المقطعين تُنبَر عادةً على المقطع الثاني: inCREASE (verb).',
          },
          {
            type: 'mcq', prompt: 'Stress and word class: "He\'s showed an increased interest in the project." (increased)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «أظهر اهتماماً متزايداً بالمشروع.»',
            options: ['INcreased — 1st syllable stressed (adjective)', 'inCREASED — 2nd syllable stressed (verb)', 'INcreased — 1st syllable stressed (noun)'], answer: 0,
            explainAr: 'increased هنا تصف الاسم interest فهي صفة، والصفات ذات المقطعين تُنبَر عادةً على المقطع الأول حسب قاعدة الكتاب: INcreased (adjective).',
          },
          {
            type: 'mcq', prompt: 'Stress and word class: "They import their goods from the UK." (import)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «يستوردون بضائعهم من المملكة المتحدة.»',
            options: ['IMport — 1st syllable stressed (noun)', 'IMport — 1st syllable stressed (verb)', 'imPORT — 2nd syllable stressed (verb)'], answer: 2,
            explainAr: 'import هنا فعل (They import)، والفعل يُنبَر على المقطع الثاني: imPORT.',
          },
          {
            type: 'mcq', prompt: 'Stress and word class: "This is a cheap import." (import)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «هذه سلعة مستوردة رخيصة.»',
            options: ['imPORT — 2nd syllable stressed (verb)', 'IMport — 1st syllable stressed (noun)', 'imPORT — 2nd syllable stressed (noun)'], answer: 1,
            explainAr: 'بعد a cheap نحتاج اسماً، والاسم ذو المقطعين يُنبَر على المقطع الأول: IMport (noun).',
          },
          {
            type: 'mcq', prompt: 'Stress and word class: "The present city was founded in 944." (present)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «أُسّست المدينة الحالية عام 944.»',
            options: ['PRESent — 1st syllable stressed (adjective)', 'preSENT — 2nd syllable stressed (verb)', 'preSENT — 2nd syllable stressed (adjective)'], answer: 0,
            explainAr: 'present هنا صفة بمعنى «الحالي» تصف city، والصفة تُنبَر على المقطع الأول: PRESent.',
          },
          {
            type: 'mcq', prompt: 'Stress and word class: "He’s going to present his friend, Maher." (present)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «سيقدّم صديقه ماهر.»',
            options: ['PRESent — 1st syllable stressed (noun)', 'PRESent — 1st syllable stressed (verb)', 'preSENT — 2nd syllable stressed (verb)'], answer: 2,
            explainAr: 'بعد going to نحتاج فعلاً (يقدّم)، والفعل يُنبَر على المقطع الثاني: preSENT.',
          },
          {
            type: 'mcq', prompt: 'Stress and word class: "This is one of the rejects from the factory." (rejects)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «هذه إحدى المنتجات المرفوضة من المصنع.»',
            options: ['reJECTS — 2nd syllable stressed (verb)', 'REjects — 1st syllable stressed (noun)', 'REjects — 1st syllable stressed (verb)'], answer: 1,
            explainAr: 'بعد one of the نحتاج اسماً (السلع المعيبة المرفوضة)، والاسم يُنبَر على المقطع الأول: REjects.',
          },
          {
            type: 'mcq', prompt: 'Stress and word class: "He rejected her advice." (rejected)',
            promptAr: 'أين النبرة وما نوع الكلمة؟ «رفض نصيحتها.»',
            options: ['REjected — 1st syllable stressed (noun)', 'REjected — 1st syllable stressed (adjective)', 'reJECTed — 2nd syllable stressed (verb)'], answer: 2,
            explainAr: 'rejected هنا فعل ماضٍ (رفض)، والفعل يُنبَر على المقطع الثاني: reJECTed.',
          },
          // ---- Grammar a: find the verb in the wrong tense ----
          {
            type: 'fill', prompt: 'When ___ the answer, I’ll let you know.',
            promptAr: 'عندما ___ الجواب، سأخبرك.',
            promptArFull: 'عندما أجد الجواب، سأخبرك.',
            options: ['I’ll find', 'I find', 'I’m going to find'], answer: 1,
            explainAr: 'بعد when (من أدوات الزمن) نستخدم المضارع البسيط بمعنى المستقبل، لا will: When I find. (الجملة في الكتاب خاطئة: I’ll find.)',
          },
          {
            type: 'fill', prompt: 'My exams ___ on 27th June.',
            promptAr: 'امتحاناتي ___ في 27 حزيران.',
            promptArFull: 'امتحاناتي تنتهي في 27 حزيران.',
            options: ['will have finished', 'have finished', 'finish'], answer: 2,
            explainAr: 'مواعيد الامتحانات جدول ثابت (timetable) فنستخدم المضارع البسيط بمعنى المستقبل: finish. الجملة في الكتاب صحيحة.',
          },
          {
            type: 'fill', prompt: 'I’ll be fine in the interview as long as they ___ me technical questions.',
            promptAr: 'سأكون بخير في المقابلة ما داموا ___ أسئلة تقنية.',
            promptArFull: 'سأكون بخير في المقابلة ما داموا لا يسألونني أسئلة تقنية.',
            options: ['won’t ask', 'don’t ask', 'aren’t going to ask'], answer: 1,
            explainAr: 'بعد as long as نستخدم المضارع البسيط بمعنى المستقبل: as long as they don’t ask. (الجملة في الكتاب خاطئة: won’t ask.)',
          },
          {
            type: 'fill', prompt: 'What time ___ tomorrow?',
            promptAr: 'في أي ساعة ___ غداً؟',
            promptArFull: 'في أي ساعة تُقلع طائرتك غداً؟',
            options: ['will your plane have taken off', 'does your plane take off', 'your plane takes off'], answer: 1,
            explainAr: 'مواعيد إقلاع الطائرات جدول زمني ثابت (timetable)، فنستخدم المضارع البسيط بمعنى المستقبل مع does في السؤال: What time does your plane take off? (هذه إحدى الجمل الست التي يعدّها التمرين خاطئة.)',
          },
          {
            type: 'fill', prompt: 'I’ll hand in my notice for this job after ___ the contract for my new one.',
            promptAr: 'سأقدّم استقالتي من هذا العمل بعد أن ___ العقد لعملي الجديد.',
            promptArFull: 'سأقدّم استقالتي من هذا العمل بعد أن أحصل على العقد لعملي الجديد.',
            options: ['I’ll get', 'I get', 'I will have got'], answer: 1,
            explainAr: 'بعد after نستخدم المضارع البسيط بمعنى المستقبل: after I get. (الجملة في الكتاب خاطئة: after I’ll get.)',
          },
          {
            type: 'fill', prompt: 'I’ll text you before we ___.',
            promptAr: 'سأرسل لك رسالة قبل أن ___.',
            promptArFull: 'سأرسل لك رسالة قبل أن ننطلق.',
            options: ['will set off', 'set off', 'will be setting off'], answer: 1,
            explainAr: 'بعد before نستخدم المضارع البسيط: before we set off. الجملة في الكتاب صحيحة.',
          },
          {
            type: 'fill', prompt: 'The bus ___ until 7.30 in the evening.',
            promptAr: 'الحافلة ___ حتى الساعة 7:30 مساءً.',
            promptArFull: 'الحافلة لا تصل حتى الساعة 7:30 مساءً.',
            options: ['doesn’t arrive', 'don’t arrive', 'isn’t arrive'], answer: 0,
            explainAr: 'مواعيد الحافلات جدول ثابت فنستخدم المضارع البسيط، والنفي مع المفرد doesn’t + المصدر: doesn’t arrive. الجملة في الكتاب صحيحة.',
          },
          {
            type: 'fill', prompt: 'I’ve got my schedule for the Japan trip. We ___ to Tokyo at 10 a.m. on Monday, and then travel by train to Kyoto for one night.',
            promptAr: 'حصلت على جدول رحلتي إلى اليابان. ___ إلى طوكيو الساعة العاشرة صباح الاثنين، ثم نسافر بالقطار إلى كيوتو لليلة واحدة.',
            promptArFull: 'حصلت على جدول رحلتي إلى اليابان. نطير إلى طوكيو الساعة العاشرة صباح الاثنين، ثم نسافر بالقطار إلى كيوتو لليلة واحدة.',
            options: ['will have flown', 'fly', 'flew', 'have flown'], answer: 1,
            explainAr: 'هذا جدول رحلة (schedule) فنستخدم المضارع البسيط بمعنى المستقبل: We fly ... and then travel. المستقبل التام will have flown لا يناسب لأنه ليس حدثاً ينتهي قبل وقت محدد. (الجملة في الكتاب خاطئة.)',
          },
          {
            type: 'fill', prompt: 'The moment ___ my results, I’ll phone you.',
            promptAr: 'في اللحظة التي ___ فيها نتائجي، سأتصل بك.',
            promptArFull: 'في اللحظة التي أتسلّم فيها نتائجي، سأتصل بك.',
            options: ['I’ll receive', 'I receive', 'I’ll have received'], answer: 1,
            explainAr: 'The moment (= as soon as) أداة زمن، وبعدها نستخدم المضارع البسيط: The moment I receive. (الجملة في الكتاب خاطئة: I’ll receive.)',
          },
          // ---- Grammar b: will be / will have + the verb in brackets ----
          {
            type: 'fill', prompt: 'I think I ___ in the same city. (still live)',
            promptAr: 'أعتقد أنني ___ في المدينة نفسها.',
            promptArFull: 'أعتقد أنني سأظل أعيش في المدينة نفسها.',
            options: ['will still have lived', 'will still be living', 'will be still live'], answer: 1,
            explainAr: 'المستقبل المستمر (will be + V-ing) لحدث مستمر خلال فترة في المستقبل، والظرف still يأتي بعد will: will still be living.',
          },
          {
            type: 'fill', prompt: 'By that time, I ___ my studies. (finish)',
            promptAr: 'بحلول ذلك الوقت، ___ دراستي.',
            promptArFull: 'بحلول ذلك الوقت، سأكون قد أنهيت دراستي.',
            options: ['will be finishing', 'will have finished', 'will have finish'], answer: 1,
            explainAr: 'By that time تدل على حدث ينتهي قبل وقت محدد في المستقبل، فنستخدم المستقبل التام: will have + التصريف الثالث (finished).',
          },
          {
            type: 'fill', prompt: 'And, who knows, perhaps I ___ a good job. (find)',
            promptAr: 'ومن يدري، ربما ___ عملاً جيداً.',
            promptArFull: 'ومن يدري، ربما أكون قد وجدت عملاً جيداً.',
            options: ['will have found', 'will be finding', 'will have find'], answer: 0,
            explainAr: 'ما زلنا في سياق By that time (قبل ذلك الوقت)، فالحدث منتهٍ: المستقبل التام will have found (found هو التصريف الثالث لـ find).',
          },
          {
            type: 'fill', prompt: 'And I ___ with the same friends too! (probably go out)',
            promptAr: 'وعلى الأرجح ___ مع الأصدقاء أنفسهم أيضاً!',
            promptArFull: 'وعلى الأرجح سأكون ما زلت أخرج مع الأصدقاء أنفسهم أيضاً!',
            options: ['will probably have gone out', 'will probably be going out', 'will be probably go out'], answer: 1,
            explainAr: 'نشاط مستمر خلال تلك الفترة في المستقبل فنستخدم المستقبل المستمر will be + V-ing، والظرف probably بعد will: will probably be going out.',
          },
          {
            type: 'fill', prompt: 'By the time I’m sixty, I expect that nearly everything ___. (change)',
            promptAr: 'بحلول الوقت الذي أبلغ فيه الستين، أتوقع أن كل شيء تقريباً ___.',
            promptArFull: 'بحلول الوقت الذي أبلغ فيه الستين، أتوقع أن كل شيء تقريباً سيكون قد تغيّر.',
            options: ['will be changing', 'will have changed', 'will have change'], answer: 1,
            explainAr: 'By the time تدل على حدث ينتهي قبل وقت محدد في المستقبل: المستقبل التام will have changed.',
          },
          {
            type: 'fill', prompt: 'And everyone ___ their best to adapt to new circumstances. (try)',
            promptAr: 'وسيكون الجميع ___ جهدهم للتكيّف مع الظروف الجديدة.',
            promptArFull: 'وسيكون الجميع يبذلون قصارى جهدهم للتكيّف مع الظروف الجديدة.',
            options: ['will have tried', 'will be trying', 'will be try'], answer: 1,
            explainAr: 'نشاط مستمر في ذلك الوقت المستقبلي (يحاولون التكيّف) فنستخدم المستقبل المستمر: will be trying.',
          },
          {
            type: 'fill', prompt: 'For example, I can’t imagine that we ___ cars. (use)',
            promptAr: 'على سبيل المثال، لا أستطيع أن أتخيّل أننا ___ السيارات.',
            promptArFull: 'على سبيل المثال، لا أستطيع أن أتخيّل أننا سنظل نستخدم السيارات.',
            options: ['will be using', 'will have used', 'will be use'], answer: 0,
            explainAr: 'استخدام السيارات نشاط مستمر في تلك الفترة المستقبلية، فنستخدم المستقبل المستمر: will be using.',
          },
          {
            type: 'fill', prompt: 'Because by then most of the oil in the world ___. (run out)',
            promptAr: 'لأنه بحلول ذلك الوقت ___ معظم النفط في العالم.',
            promptArFull: 'لأنه بحلول ذلك الوقت سيكون معظم النفط في العالم قد نفد.',
            options: ['will be running out', 'will have run out', 'will have ran out'], answer: 1,
            explainAr: 'by then تدل على حدث ينتهي قبل ذلك الوقت: المستقبل التام will have run out (run هو التصريف الثالث لـ run، وليس ran).',
          },
          {
            type: 'fill', prompt: 'People ___ in electric cars. (travel)',
            promptAr: 'سيكون الناس ___ في سيارات كهربائية.',
            promptArFull: 'سيكون الناس يسافرون في سيارات كهربائية.',
            options: ['will have travelled', 'will be travelling', 'will be travel'], answer: 1,
            explainAr: 'نشاط مستمر في ذلك الوقت المستقبلي فنستخدم المستقبل المستمر: will be travelling.',
          },
          {
            type: 'fill', prompt: 'Or perhaps we ___ everywhere. (walk)',
            promptAr: 'أو ربما ___ إلى كل مكان.',
            promptArFull: 'أو ربما سنكون نمشي إلى كل مكان.',
            options: ['will be walking', 'will have walked', 'will walking'], answer: 0,
            explainAr: 'نشاط مستمر في المستقبل (بدل السيارات) فنستخدم المستقبل المستمر: will be walking.',
          },
          {
            type: 'fill', prompt: 'I hope that scientists ___ pollution problem. (solve)',
            promptAr: 'آمل أن العلماء ___ مشكلة التلوث.',
            promptArFull: 'آمل أن يكون العلماء قد حلّوا مشكلة التلوث.',
            options: ['will be solving', 'will have solved', 'will have solve'], answer: 1,
            explainAr: 'حدث نأمل أن ينتهي قبل ذلك الوقت (by then) فنستخدم المستقبل التام: will have solved.',
          },
          {
            type: 'fill', prompt: 'Perhaps some other worse problems ___ along by then! (come)',
            promptAr: 'ربما ___ مشكلات أخرى أسوأ بحلول ذلك الوقت!',
            promptArFull: 'ربما تكون مشكلات أخرى أسوأ قد ظهرت بحلول ذلك الوقت!',
            options: ['will be coming', 'will have come', 'will have came'], answer: 1,
            explainAr: 'by then = قبل ذلك الوقت، فنستخدم المستقبل التام: will have come (come هو التصريف الثالث لـ come).',
          },
          // ---- Everyday English: Modesty — put the dialogue in order ----
          {
            type: 'mcq', prompt: 'B: "Oh no. They’re a splendid group of young people. I don’t deserve any of the credit." — What does A say next (line 3)?',
            promptAr: 'ب: «أوه لا. إنهم مجموعة رائعة من الشباب. لا أستحق أي فضل.» — ماذا يقول أ بعد ذلك (السطر 3)؟',
            options: ['Oh, come on. It can’t have been easy, and I don’t agree that anyone could have done it.', 'I’m sure they are splendid, but I don’t agree that you don’t deserve any credit. I know for sure that you planned the lovely decorations in their classroom.', 'I’m sorry, I just can’t believe it had nothing to do with you.', 'Perhaps they did, but you gave them the idea in the first place, didn’t you?'], answer: 1,
            explainAr: 'أ يرد على «إنهم رائعون ولا أستحق الفضل» بقوله: I’m sure they are splendid, but I don’t agree that you don’t deserve any credit — ثم يذكر الزينة التي خططت لها المعلمة.',
          },
          {
            type: 'mcq', prompt: 'A: "…I know for sure that you planned the lovely decorations in their classroom." — What does B say next (line 4)?',
            promptAr: 'أ: «…أعرف يقيناً أنك خطّطت للزينة الجميلة في صفهم.» — ماذا يقول ب بعد ذلك (السطر 4)؟',
            options: ['I had very little to do with it. The children contributed lots of ideas themselves.', 'You’re very kind but it wasn’t difficult at all. Anyone could have done it.', 'That had really nothing to do with me. They suggested it in the first place.'], answer: 2,
            explainAr: 'ب يتواضع وينسب فكرة الزينة للأطفال: That had really nothing to do with me. They suggested it in the first place. — ولذلك يرد أ بعدها: Perhaps they did…',
          },
          {
            type: 'mcq', prompt: 'B: "That had really nothing to do with me. They suggested it in the first place." — What does A say next (line 5)?',
            promptAr: 'ب: «لم يكن لي علاقة بذلك حقاً. هم من اقترحوه أصلاً.» — ماذا يقول أ بعد ذلك (السطر 5)؟',
            options: ['Oh, come on. It can’t have been easy, and I don’t agree that anyone could have done it.', 'Perhaps they did, but you gave them the idea in the first place, didn’t you? And that project for helping old people is the finest thing I’ve seen for years.', 'I’m sorry, I just can’t believe it had nothing to do with you.'], answer: 1,
            explainAr: 'Perhaps they did تردّ مباشرة على They suggested it (ربما اقترحوه فعلاً، لكنك أعطيتهم الفكرة)، ثم ينتقل أ إلى مدح مشروع مساعدة كبار السن.',
          },
          {
            type: 'mcq', prompt: 'A: "…And that project for helping old people is the finest thing I’ve seen for years." — What does B say next (line 6)?',
            promptAr: 'أ: «…وذلك المشروع لمساعدة كبار السن أروع شيء رأيته منذ سنوات.» — ماذا يقول ب بعد ذلك (السطر 6)؟',
            options: ['That had really nothing to do with me. They suggested it in the first place.', 'You’re very kind but it wasn’t difficult at all. Anyone could have done it.', 'I had very little to do with it. The children contributed lots of ideas themselves.'], answer: 2,
            explainAr: 'ب يتواضع بشأن المشروع: I had very little to do with it. The children contributed lots of ideas themselves (الأطفال قدّموا أفكاراً كثيرة بأنفسهم).',
          },
          {
            type: 'mcq', prompt: 'B: "I had very little to do with it. The children contributed lots of ideas themselves." — What does A say next (line 7)?',
            promptAr: 'ب: «لم يكن لي إلا دور صغير جداً فيه. الأطفال قدّموا أفكاراً كثيرة بأنفسهم.» — ماذا يقول أ بعد ذلك (السطر 7)؟',
            options: ['I’m sorry, I just can’t believe it had nothing to do with you. And, even if they had the original idea, I’m sure you guided them in how to organise it.', 'Oh, come on. It can’t have been easy, and I don’t agree that anyone could have done it.', 'I’m sure they are splendid, but I don’t agree that you don’t deserve any credit.'], answer: 0,
            explainAr: 'أ يرفض تواضع ب: حتى لو كانت الفكرة من الأطفال (even if they had the original idea) فأنت أرشدتهم في تنظيمها.',
          },
          {
            type: 'mcq', prompt: 'A: "…I’m sure you guided them in how to organise it." — What does B say next (line 8)?',
            promptAr: 'أ: «…أنا متأكد أنك أرشدتهم إلى كيفية تنظيمه.» — ماذا يقول ب بعد ذلك (السطر 8)؟',
            options: ['You’re very kind but it wasn’t difficult at all. Anyone could have done it.', 'That had really nothing to do with me. They suggested it in the first place.', 'I had very little to do with it. The children contributed lots of ideas themselves.'], answer: 0,
            explainAr: 'ب يتواضع بشأن التنظيم: You’re very kind but it wasn’t difficult at all. Anyone could have done it.',
          },
          {
            type: 'mcq', prompt: 'B: "You’re very kind but it wasn’t difficult at all. Anyone could have done it." — What does A say last (line 9)?',
            promptAr: 'ب: «أنت لطيف جداً، لكنه لم يكن صعباً أبداً. كان بإمكان أي شخص أن يفعله.» — ماذا يقول أ في النهاية (السطر 9)؟',
            options: ['Perhaps they did, but you gave them the idea in the first place, didn’t you?', 'Oh, come on. It can’t have been easy, and I don’t agree that anyone could have done it.', 'I’m sure they are splendid, but I don’t agree that you don’t deserve any credit.'], answer: 1,
            explainAr: 'أ يرد على «لم يكن صعباً… كان بإمكان أي شخص أن يفعله» بقوله: It can’t have been easy, and I don’t agree that anyone could have done it.',
          },
          // ---- Listening a: match the words and phrases with their definitions ----
          {
            type: 'mcq', prompt: 'Match: barrier',
            promptAr: 'اختر تعريف الكلمة barrier.',
            options: ['represent', 'a physical object that keeps two areas, people etc. apart', 'joined the parts of something together again', 'the official line that separates two countries, states, or areas'], answer: 1,
            explainAr: 'barrier = حاجز: جسم مادي يفصل بين منطقتين أو بين الناس، مثل جدار برلين.',
          },
          {
            type: 'mcq', prompt: 'Match: border',
            promptAr: 'اختر تعريف الكلمة border.',
            options: ['the official line that separates two countries, states, or areas', 'represent', 'a physical object that keeps two areas, people etc. apart', 'joined the parts of something together again'], answer: 0,
            explainAr: 'border = حدود: الخط الرسمي الذي يفصل بين بلدين أو ولايتين أو منطقتين.',
          },
          {
            type: 'mcq', prompt: 'Match: symbolise',
            promptAr: 'اختر تعريف الكلمة symbolise.',
            options: ['joined the parts of something together again', 'the official line that separates two countries, states, or areas', 'represent', 'a physical object that keeps two areas, people etc. apart'], answer: 2,
            explainAr: 'symbolise = يرمز إلى: represent.',
          },
          {
            type: 'mcq', prompt: 'Match: Iron Curtain',
            promptAr: 'اختر تعريف العبارة Iron Curtain.',
            options: ['represent', 'joined the parts of something together again', 'a physical object that keeps two areas, people etc. apart', 'the name that was used for the border between the Communist countries of Eastern Europe and the rest of Europe'], answer: 3,
            explainAr: 'Iron Curtain = الستار الحديدي: الاسم الذي أُطلق على الحدود بين الدول الشيوعية في أوروبا الشرقية وبقية أوروبا.',
          },
          {
            type: 'mcq', prompt: 'Match: reunified',
            promptAr: 'اختر تعريف الكلمة reunified.',
            options: ['joined the parts of something together again', 'represent', 'the official line that separates two countries, states, or areas', 'a physical object that keeps two areas, people etc. apart'], answer: 0,
            explainAr: 'reunified = أُعيد توحيده: البادئة re- تعني «من جديد»، أي جُمعت أجزاء الشيء معاً مرة أخرى (مثل ألمانيا بعد سقوط الجدار).',
          },
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'In no more than 100 words, write an article to your school magazine about students’ rights and duties at school.',
          topicAr: 'اكتب مقالاً لمجلة مدرستك في ما لا يزيد على 100 كلمة عن حقوق الطلاب وواجباتهم في المدرسة، مستعيناً بإجابات الأسئلة التالية.',
          words: 100,
          points: ['What are the duties of students?', 'What are the rights of students?', 'Why is it important for students to know their rights and duties?', 'How can students be aware of their duties?', 'Who is responsible for assuring students’ rights?'],
          pointsAr: ['ما واجبات الطلاب؟', 'ما حقوق الطلاب؟', 'لماذا من المهم أن يعرف الطلاب حقوقهم وواجباتهم؟', 'كيف يمكن أن يكون الطلاب واعين لواجباتهم؟', 'من المسؤول عن ضمان حقوق الطلاب؟'],
          plan: [
            { en: 'Topic sentence: every student has rights and duties at school.', ar: 'الجملة الافتتاحية: لكل طالب حقوق وواجبات في المدرسة.' },
            { en: 'Rights: a good education, fair treatment regardless of religion, gender and language, expressing opinions.', ar: 'الحقوق: تعليم جيد، ومعاملة عادلة بغضّ النظر عن الدين والجنس واللغة، والتعبير عن الرأي.' },
            { en: 'Duties: respect teachers, do homework, keep the school clean.', ar: 'الواجبات: احترام المعلمين، وأداء الواجبات المنزلية، والحفاظ على نظافة المدرسة.' },
            { en: 'Why it is important and how students become aware of their duties.', ar: 'لماذا هذا مهم، وكيف يصبح الطلاب واعين لواجباتهم.' },
            { en: 'Conclusion: who is responsible for assuring students’ rights.', ar: 'الخاتمة: من المسؤول عن ضمان حقوق الطلاب.' },
          ],
          phrases: [
            { en: 'regardless of their religion, gender and language', ar: 'بغضّ النظر عن دينهم وجنسهم ولغتهم' },
            { en: 'without discrimination', ar: 'دون تمييز' },
            { en: 'It is the duty of … to make sure that …', ar: 'من واجب … أن يتأكد من أن …' },
            { en: 'responsible for ensuring the rights of children', ar: 'مسؤول عن ضمان حقوق الأطفال' },
            { en: 'advocate for their rights', ar: 'يدافع عن حقوقهم' },
            { en: 'encourage respect for each other’s rights', ar: 'يشجّع احترام حقوق بعضنا بعضاً' },
            { en: 'At the same time, …', ar: 'في الوقت نفسه، …' },
            { en: 'a school where everyone respects the rules', ar: 'مدرسة يحترم فيها الجميع القواعد (جملة موصولة)' },
            { en: 'Finally, …', ar: 'أخيراً، …' },
            { en: 'students will be …', ar: 'سيكون الطلاب … (صيغة المستقبل)' },
          ],
          model: 'Every student has rights and duties at school. Students have the right to a good education, to be treated fairly regardless of their religion, gender and language, and to express their opinions. At the same time, they have duties: they should respect their teachers, do their homework and keep their school clean. Knowing their rights and duties is important because a school where everyone respects the rules is a better place to learn. Students can learn their duties from school rules and their teachers’ advice. Finally, it is the duty of the headmaster, teachers and parents to assure students’ rights.',
          modelAr: 'لكل طالب حقوق وواجبات في المدرسة. للطلاب الحق في تعليم جيد، وفي أن يُعاملوا بعدل بغضّ النظر عن دينهم وجنسهم ولغتهم، وفي التعبير عن آرائهم. وفي الوقت نفسه، عليهم واجبات: يجب أن يحترموا معلميهم، وأن يؤدوا واجباتهم المنزلية، وأن يحافظوا على نظافة مدرستهم. إن معرفة حقوقهم وواجباتهم أمر مهم لأن المدرسة التي يحترم فيها الجميع القواعد مكان أفضل للتعلّم. ويستطيع الطلاب أن يتعرّفوا إلى واجباتهم من قواعد المدرسة ونصائح معلميهم. وأخيراً، من واجب المدير والمعلمين والأهل ضمان حقوق الطلاب.',
          checklistAr: [
            'لا يزيد على 100 كلمة ومكتوب بأسلوب مقال لمجلة المدرسة.',
            'يجيب عن الأسئلة الخمسة: الواجبات، الحقوق، أهمية معرفتها، كيف يعي الطلاب واجباتهم، ومن يضمن حقوقهم.',
            'يبدأ بجملة افتتاحية وينتهي بجملة ختامية.',
            'يستخدم روابط مثل At the same time, because, Finally.',
            'يستخدم مفردات الوحدة: regardless of, rights, duty, assure / ensure.',
            'خالٍ من الأخطاء الإملائية والنحوية، مع ترقيم صحيح.',
          ],
        },
        {
          source: 'workbook',
          topic: 'Your elder brother asks you for help. He has graduated and is now thinking of writing his resume. He is seeking a part-time job in a retail company.',
          topicAr: 'يطلب منك أخوك الأكبر المساعدة. لقد تخرّج ويفكّر الآن في كتابة سيرته الذاتية (CV). إنه يبحث عن عمل بدوام جزئي في شركة بيع بالتجزئة. اكتب سيرته الذاتية.',
          words: 100,
          points: ['Your name', 'Contact information', 'Languages and international travel', 'Hobbies', 'Summary', 'Skill highlights', 'Experience', 'Education', 'Certifications'],
          pointsAr: ['الاسم', 'معلومات الاتصال', 'اللغات والسفر إلى الخارج', 'الهوايات', 'ملخّص', 'أبرز المهارات', 'الخبرة', 'التعليم', 'الشهادات'],
          plan: [
            { en: 'Name and contact information at the top.', ar: 'الاسم ومعلومات الاتصال في الأعلى.' },
            { en: 'Summary: one sentence about who he is and the job he is seeking.', ar: 'الملخّص: جملة واحدة عن هويته والعمل الذي يبحث عنه.' },
            { en: 'Education and certifications, then experience (most recent first).', ar: 'التعليم والشهادات، ثم الخبرة (الأحدث أولاً).' },
            { en: 'Skill highlights useful for a retail job.', ar: 'أبرز المهارات المفيدة في عمل البيع بالتجزئة.' },
            { en: 'Languages and international travel, then hobbies.', ar: 'اللغات والسفر إلى الخارج، ثم الهوايات.' },
          ],
          phrases: [
            { en: 'seeking a part-time job in a retail company', ar: 'يبحث عن عمل بدوام جزئي في شركة بيع بالتجزئة' },
            { en: 'a graduate who …', ar: 'خرّيج … (جملة موصولة)' },
            { en: 'fundraising', ar: 'جمع التبرعات' },
            { en: 'charity', ar: 'جمعية خيرية' },
            { en: 'volunteer / voluntary', ar: 'متطوّع / تطوّعي' },
            { en: 'a team effort', ar: 'عمل جماعي' },
            { en: 'certificate', ar: 'شهادة' },
            { en: 'responsible for …', ar: 'مسؤول عن …' },
            { en: 'fluent in English', ar: 'يتقن الإنجليزية بطلاقة' },
            { en: 'communication skills', ar: 'مهارات التواصل' },
          ],
          model: 'Name: Sami Hasan. Contact information: Damascus, Syria; phone 0933 123 456. Summary: A hard-working graduate who is seeking a part-time job in a retail company. Education: Bachelor’s degree in Business Administration, Damascus University, 2025. Certifications: a computer skills certificate and an English language course certificate. Experience: sales assistant in a bookshop for two years, where I was responsible for serving customers; volunteer in a charity fundraising campaign for children. Skill highlights: good communication skills, working in a team, using computers and dealing with money. Languages and international travel: Arabic and English (fluent); I have travelled to Lebanon and Jordan. Hobbies: reading, football and volunteering.',
          modelAr: 'الاسم: سامي حسن. معلومات الاتصال: دمشق، سوريا؛ الهاتف 0933 123 456. الملخّص: خرّيج مجتهد يبحث عن عمل بدوام جزئي في شركة بيع بالتجزئة. التعليم: إجازة في إدارة الأعمال، جامعة دمشق، 2025. الشهادات: شهادة في مهارات الحاسوب وشهادة دورة في اللغة الإنجليزية. الخبرة: مساعد مبيعات في مكتبة لمدة سنتين، حيث كنت مسؤولاً عن خدمة الزبائن؛ ومتطوّع في حملة خيرية لجمع التبرعات للأطفال. أبرز المهارات: مهارات تواصل جيدة، والعمل ضمن فريق، واستخدام الحاسوب، والتعامل مع المال. اللغات والسفر إلى الخارج: العربية والإنجليزية (بطلاقة)؛ سافرت إلى لبنان والأردن. الهوايات: القراءة وكرة القدم والتطوّع.',
          checklistAr: [
            'يتضمن كل البنود المطلوبة: الاسم، معلومات الاتصال، الملخّص، التعليم، الشهادات، الخبرة، المهارات، اللغات والسفر، الهوايات.',
            'الملخّص يذكر العمل المطلوب: part-time job in a retail company.',
            'المهارات والخبرة مناسبة لعمل البيع (التعامل مع الزبائن والمال).',
            'عبارات قصيرة وواضحة، بالترتيب نفسه تحت عناوين واضحة.',
            'استخدام الأحرف الكبيرة في العناوين وأسماء الأماكن، والنقطتين (:) بعد كل عنوان.',
            'خالٍ من الأخطاء الإملائية.',
          ],
        },
      ],
      translations: [
        { en: 'There were 51 founding members in 1945.', ar: 'كان هناك 51 عضواً مؤسِّساً عام 1945.' },
        { en: 'The UN also has regional offices in Geneva, Vienna, and Nairobi.', ar: 'للأمم المتحدة أيضاً مكاتب إقليمية في جنيف وفيينا ونيروبي.' },
        { en: 'Its official languages are Arabic, Chinese, English, French, Russian, and Spanish.', ar: 'لغاتها الرسمية هي العربية والصينية والإنجليزية والفرنسية والروسية والإسبانية.' },
        { en: 'The day is now celebrated each year around the world as United Nations Day.', ar: 'يُحتفل بهذا اليوم الآن كل عام في أنحاء العالم بوصفه يوم الأمم المتحدة.' },
        { en: 'UNICEF has been a key player in global development work since its beginning.', ar: 'كانت اليونيسف لاعباً رئيسياً في أعمال التنمية العالمية منذ بدايتها.' },
        { en: 'I think the weather will be too hot tomorrow.', ar: 'أعتقد أن الطقس سيكون حاراً جداً غداً.' },
        { en: 'The two companies are going to provide very different experiences.', ar: 'ستقدّم الشركتان تجارب مختلفة جداً.' },
        { en: 'The team manager is holding a party on our return.', ar: 'سيقيم مدير الفريق حفلة عند عودتنا.' },
        { en: 'By the time you get home, I will have cleaned the house from top to bottom.', ar: 'بحلول الوقت الذي تصل فيه إلى المنزل، سأكون قد نظّفت البيت من أعلاه إلى أسفله.' },
        { en: 'Manchester United will win their next game.', ar: 'سيفوز مانشستر يونايتد في مباراته القادمة.' },
        { en: 'My exams finish on 27th June.', ar: 'تنتهي امتحاناتي في 27 حزيران.' },
        { en: 'I’ll text you before we set off.', ar: 'سأرسل لك رسالة قبل أن ننطلق.' },
        { en: 'The bus doesn’t arrive until 7.30 in the evening.', ar: 'لا تصل الحافلة حتى الساعة 7:30 مساءً.' },
        { en: 'They import their goods from the UK.', ar: 'يستوردون بضائعهم من المملكة المتحدة.' },
        { en: 'I’ve never seen such an attractive and talented class of children.', ar: 'لم أرَ قط صفاً من الأطفال بهذا القدر من الجاذبية والموهبة.' },
        { en: 'The children contributed lots of ideas themselves.', ar: 'قدّم الأطفال أفكاراً كثيرة بأنفسهم.' },
        { en: 'I only played a small part in the whole thing.', ar: 'لم أؤدِّ إلا دوراً صغيراً في الأمر كله.' },
      ],
    },
  },
}
