import type { ModuleExtras } from './merge'
import type { GrammarExercise } from '../../../engine/types'

// Activity Book, Module 2 "Sciences": Unit 3 (pages 16–25), Unit 4 (pages 26–32), Progress Test 1 (pages 33–35).
// Every item the pages print, solved; recording-based and open speaking items are left out.

const fill = (prompt: string, options: string[], answer: number, promptAr: string, promptArFull: string, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, options, answer, promptAr, promptArFull, explainAr })
const mcq = (prompt: string, options: string[], answer: number, promptAr: string, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, options, answer, promptAr, explainAr })
const tf = (prompt: string, answer: boolean, promptAr: string, explainAr: string): GrammarExercise =>
  ({ type: 'truefalse', prompt, answer, promptAr, explainAr })
const build = (answer: string, prompt: string, explainAr: string): GrammarExercise =>
  ({ type: 'build', answer, prompt, explainAr })

// ---------------------------------------------------------------- Unit 3: Medicine (Activity Book 16–25)

const MEANINGS_U3 = {
  a: 'a sound that is produced or increased in one object by sound waves from another sound',
  b: 'a neat cut made into the skin',
  c: 'related to medical treatments involving cutting into someone’s body',
  d: 'the state of being accurate and careful',
  e: 'being fixed or inserted firmly into something else',
  f: 'an important development that may lead to an achievement',
  g: 'a medical operation to replace a damaged organ with another one',
}

const u3Exercises: GrammarExercise[] = [
  // Reading a — match the words to their meanings
  mcq('What does “breakthrough” mean?', [MEANINGS_U3.f, MEANINGS_U3.e, MEANINGS_U3.d, MEANINGS_U3.g], 0,
    'ما معنى كلمة breakthrough؟',
    'breakthrough = اختراق / إنجاز كبير: تطوّر مهم قد يؤدي إلى إنجاز (f). في النص: Breakthroughs have found new solutions.'),
  mcq('What does “transplant” mean?', [MEANINGS_U3.b, MEANINGS_U3.g, MEANINGS_U3.c, MEANINGS_U3.a], 1,
    'ما معنى كلمة transplant؟',
    'transplant = زراعة عضو: عملية طبية لاستبدال عضو تالف بعضو آخر (g)، مثل زراعة القلب والكبد والكلية.'),
  mcq('What does “incision” mean?', [MEANINGS_U3.c, MEANINGS_U3.e, MEANINGS_U3.b, MEANINGS_U3.d], 2,
    'ما معنى كلمة incision؟',
    'incision = شقّ جراحي: جرح نظيف يُحدث في الجلد (b). انتبه: invasive صفة للعلاج الذي يتطلّب الجرح، أما incision فهو الشقّ نفسه.'),
  mcq('What does “resonance” mean?', [MEANINGS_U3.d, MEANINGS_U3.f, MEANINGS_U3.g, MEANINGS_U3.a], 3,
    'ما معنى كلمة resonance؟',
    'resonance = رنين: صوت يُنتَج أو يزداد في جسم بسبب موجات صوتية من صوت آخر (a)، ومنه Magnetic Resonance Imaging (التصوير بالرنين المغناطيسي).'),
  mcq('What does “invasive” mean?', [MEANINGS_U3.c, MEANINGS_U3.b, MEANINGS_U3.e, MEANINGS_U3.d], 0,
    'ما معنى كلمة invasive؟',
    'invasive = باضِع / جراحي: متعلّق بعلاج طبي يتطلّب شقّ جسم المريض (c). والجراحة الروبوتية minimally invasive أي بأقلّ قدر من الشقّ.'),
  mcq('What does “precision” mean?', [MEANINGS_U3.a, MEANINGS_U3.d, MEANINGS_U3.f, MEANINGS_U3.b], 1,
    'ما معنى كلمة precision؟',
    'precision = دقّة: حالة الإتقان والحرص (d). في النص: surgeons can perform very complex steps with more precision.'),
  mcq('What does “embedded” mean?', [MEANINGS_U3.g, MEANINGS_U3.c, MEANINGS_U3.e, MEANINGS_U3.a], 2,
    'ما معنى كلمة embedded؟',
    'embedded = مُدمَج / مغروس: مثبّت بإحكام داخل شيء آخر (e). في النص: tiny Nano-sized sensors embedded in several electronic devices.'),

  // Reading c — rewrite the sentences to correct the information from the text
  mcq('Correct the information: “Nowadays deaths among human beings have been increased due to up-to-date medical discoveries.”', [
    'Nowadays deaths among human beings have decreased due to up-to-date medical discoveries.',
    'Nowadays deaths among human beings have increased due to old medical discoveries.',
    'Nowadays deaths among human beings have not changed due to up-to-date medical discoveries.',
    'Nowadays births among human beings have been increased due to up-to-date medical discoveries.',
  ], 0,
    'صحّح المعلومة: «في هذه الأيام ازدادت الوفيات بين البشر بسبب الاكتشافات الطبية الحديثة.»',
    'النص يقول: Today\'s techniques, surgeries and drugs have decreased the overall deaths among humans. إذن الوفيات انخفضت ولم تزدد.'),
  mcq('Correct the information: “X-ray techniques require strong radio waves to produce images of the body organs.”', [
    'X-ray techniques require strong magnetic fields to produce images of the body organs.',
    'X-ray techniques use an external radiation to produce images of the body.',
    'X-ray techniques require an incision to produce images of the body organs.',
    'X-ray techniques require tiny sensors to produce images of the body organs.',
  ], 1,
    'صحّح المعلومة: «تحتاج تقنيات الأشعة السينية إلى موجات راديو قوية لإنتاج صور لأعضاء الجسم.»',
    'الموجات الراديوية والحقول المغناطيسية القوية تخصّ جهاز الرنين MRI. أما الأشعة السينية فتستخدم using an external radiation to produce images of the body.'),
  mcq('Correct the information: “During X-ray Imaging, surgeons have to make an incision to view the patient\'s body.”', [
    'During X-ray Imaging, surgeons have to make two incisions to view the patient\'s body.',
    'During X-ray Imaging, surgeons have to use robots to view the patient\'s body.',
    'During X-ray Imaging, doctors can view the inside of the patient\'s body without having to make an incision.',
    'During X-ray Imaging, surgeons have to make a small incision to view the patient\'s bones.',
  ], 2,
    'صحّح المعلومة: «أثناء التصوير بالأشعة السينية يجب على الجرّاحين إحداث شقّ لرؤية جسم المريض.»',
    'النص: X-ray Imaging can help doctors view the inside of the patient\'s body without having to make an incision. أي دون الحاجة إلى شقّ.'),
  mcq('Correct the information: “Like Robotic Surgeries, traditional surgeries are operated with precision and flexibility.”', [
    'Unlike traditional surgeries, Robotic Surgeries are operated with more precision, flexibility and control.',
    'Like Robotic Surgeries, traditional surgeries result in smaller incisions.',
    'Traditional surgeries are operated with more precision and flexibility than Robotic Surgeries.',
    'Like traditional surgeries, Robotic Surgeries result in more pain and longer time in hospital.',
  ], 0,
    'صحّح المعلومة: «مثل الجراحات الروبوتية، تُجرى الجراحات التقليدية بدقّة ومرونة.»',
    'النص: surgeons can perform very complex steps with more precision, flexibility and control than it is possible with conventional techniques. فالدقّة والمرونة الأكبر ميزة الجراحة الروبوتية لا التقليدية.'),
  mcq('Correct the information: “The fast pace development of medical health technologies would stop monitoring of patients remotely.”', [
    'The fast pace development of medical health technologies would stop health data collection.',
    'The slow development of medical health technologies would allow remote monitoring of patients.',
    'The fast pace development of medical health technologies would stop patients\' access to healthcare.',
    'The new technologies will allow remote monitoring of patients, and such benefits would continue to increase with the fast pace development of medical health technologies.',
  ], 3,
    'صحّح المعلومة: «التطوّر السريع لتقنيات الصحة الطبية سيوقف مراقبة المرضى عن بُعد.»',
    'النص: The new technologies will allow remote monitoring of patients ... Such benefits would continue to increase with the fast pace development. أي أنها تسمح بالمراقبة عن بُعد ولا توقفها.'),

  // Vocabulary a — medical idioms
  fill('Don\'t worry. It\'s a minor procedure and you\'ll be ___ within a week.',
    ['at death\'s door', 'on the mend', 'a taste of your own medicine', 'just what the doctor ordered'], 1,
    'لا تقلق. إنها عملية بسيطة وستكون ___ خلال أسبوع.',
    'لا تقلق. إنها عملية بسيطة وستكون في طريقك إلى الشفاء خلال أسبوع.',
    'on the mend = يتحسّن / في طريقه إلى الشفاء. «لا تقلق» و«عملية بسيطة» تدلّان على الشفاء القريب.'),
  fill('I drove all night to reach the hospital because they told me my mother was ___.',
    ['on the mend', 'just what the doctor ordered', 'at death\'s door', 'a taste of her own medicine'], 2,
    'قدت السيارة طوال الليل لأصل إلى المستشفى لأنهم أخبروني أن أمي كانت ___.',
    'قدت السيارة طوال الليل لأصل إلى المستشفى لأنهم أخبروني أن أمي كانت على حافة الموت.',
    'at death\'s door = مريض جداً على وشك الموت. السفر طوال الليل يدلّ على حالة خطيرة جداً.'),
  fill('My kids just left for three weeks of camp and it\'s ___.',
    ['at death\'s door', 'just what the doctor ordered', 'on the mend', 'a turn for the worse'], 1,
    'غادر أطفالي للتوّ إلى مخيّم لمدة ثلاثة أسابيع وهذا ___.',
    'غادر أطفالي للتوّ إلى مخيّم لمدة ثلاثة أسابيع وهذا بالضبط ما كنت أحتاجه.',
    'just what the doctor ordered = الشيء المناسب تماماً الذي نحتاجه (هنا: راحة للأهل). نستخدمه لشيء مفيد جاء في وقته.'),
  fill('Even when you ___ and went into a coma, I never lost hope you\'d fully recover one day.',
    ['took a turn for the worse', 'were on the mend', 'gave a taste of your own medicine', 'were just what the doctor ordered'], 0,
    'حتى عندما ___ ودخلت في غيبوبة، لم أفقد الأمل أبداً في أنك ستتعافى تماماً يوماً ما.',
    'حتى عندما ساءت حالتك فجأة ودخلت في غيبوبة، لم أفقد الأمل أبداً في أنك ستتعافى تماماً يوماً ما.',
    'take a turn for the worse = تسوء الحالة فجأة. نضعه في الماضي took لأن went في الجملة ماضٍ.'),
  fill('My grandfather is ___ tomorrow, so we\'ll need to be at the hospital to support my grandmother.',
    ['on the mend', 'going under the knife', 'just what the doctor ordered', 'getting a taste of his own medicine'], 1,
    'جدّي ___ غداً، لذلك سنحتاج إلى أن نكون في المستشفى لنساند جدّتي.',
    'جدّي سيخضع لعملية جراحية غداً، لذلك سنحتاج إلى أن نكون في المستشفى لنساند جدّتي.',
    'go under the knife = يخضع لعملية جراحية. نستخدم is going (المضارع المستمر للمستقبل المرتّب) مع tomorrow.'),
  fill('She always teases everyone and now that her father is in jail she is getting ___.',
    ['on the mend', 'a turn for the worse', 'a taste of her own medicine', 'under the knife'], 2,
    'هي دائماً تسخر من الجميع، والآن بعد أن دخل والدها السجن صارت ___.',
    'هي دائماً تسخر من الجميع، والآن بعد أن دخل والدها السجن صارت تُعامَل بالطريقة نفسها التي كانت تعامل بها الآخرين.',
    'get a taste of one\'s own medicine = يُعامَل بالطريقة السيئة نفسها التي عامل بها غيره. نغيّر one\'s إلى her لأن الفاعل she.'),

  // Vocabulary b — which medical specialist?
  mcq('“I have had chest pains and I\'m also having trouble breathing.” This patient should see a / an …', ['dermatologist', 'cardiologist', 'naturopath', 'ophthalmologist'], 1,
    '«أعاني من آلام في الصدر وأجد صعوبة في التنفّس.» يجب أن يراجع هذا المريض …',
    'cardiologist = طبيب القلب (a heart specialist). آلام الصدر وصعوبة التنفّس من أعراض القلب.'),
  mcq('“I have a terrible rash on my arms and legs. I think I\'m allergic to dairy food, but it might also be grass.” This patient should see a / an …', ['pediatrician', 'cardiologist', 'allergist', 'ophthalmologist'], 2,
    '«لديّ طفح جلدي شديد على ذراعيّ وساقيّ. أظن أن لديّ حساسية من مشتقات الحليب، وربما من العشب.» يجب أن يراجع هذا المريض …',
    'allergist = طبيب الحساسية، يختصّ بتحديد حساسية الطعام والبيئة (food and environmental allergies) مثل الحليب والعشب.'),
  mcq('“My little girl hasn\'t put on weight for two months and she keeps getting an infection.” This patient should see a / an …', ['pediatrician', 'dermatologist', 'naturopath', 'allergist'], 0,
    '«ابنتي الصغيرة لم يزدد وزنها منذ شهرين وتصاب بالالتهاب باستمرار.» يجب أن يراجع هذا المريض …',
    'pediatrician = طبيب الأطفال (a specialist for babies and children). المريضة طفلة صغيرة.'),
  mcq('“My left eye is itchy and my vision has been blurry for two weeks.” This patient should see a / an …', ['cardiologist', 'ophthalmologist', 'allergist', 'pediatrician'], 1,
    '«عيني اليسرى تحكّني ورؤيتي مشوّشة منذ أسبوعين.» يجب أن يراجع هذا المريض …',
    'ophthalmologist = طبيب العيون (specialises in eye diseases).'),
  mcq('“I\'ve had problems with drugs that cause side effects, so I\'d like to try some natural remedies.” This patient should see a / an …', ['dermatologist', 'ophthalmologist', 'cardiologist', 'naturopath'], 3,
    '«عانيت من أدوية لها آثار جانبية، لذلك أودّ أن أجرّب بعض العلاجات الطبيعية.» يجب أن يراجع هذا المريض …',
    'naturopath = المعالج بالطب الطبيعي (specialises in natural cures and remedies).'),
  mcq('“I have got terrible acne and nothing in the pharmacy has worked. I don\'t know what to do now.” This patient should see a / an …', ['naturopath', 'dermatologist', 'pediatrician', 'cardiologist'], 1,
    '«لديّ حبّ شباب شديد ولم ينفع أي شيء من الصيدلية. لا أعرف ماذا أفعل الآن.» يجب أن يراجع هذا المريض …',
    'dermatologist = طبيب الجلدية (treats skin diseases). حبّ الشباب مرض جلدي.'),

  // Pronunciation a — emphatic stress: place stress according to the meaning
  mcq('A: Did John buy a car yesterday?  B: No, Frank bought a car yesterday. — Which word does B stress?', ['Frank', 'bought', 'car', 'yesterday'], 0,
    'أ: هل اشترى جون سيارة البارحة؟ ب: لا، فرانك اشترى سيارة البارحة. — على أيّ كلمة يضع ب النبر؟',
    'النبر التوكيدي يقع على المعلومة التي تصحّح الخطأ: السائل قال John، والصحيح FRANK.'),
  mcq('A: Did Frank buy a motorbike yesterday?  B: No, Frank bought a car yesterday. — Which word does B stress?', ['Frank', 'bought', 'car', 'yesterday'], 2,
    'أ: هل اشترى فرانك دراجة نارية البارحة؟ ب: لا، فرانك اشترى سيارة البارحة. — على أيّ كلمة يضع ب النبر؟',
    'السائل أخطأ في الشيء المشترى (motorbike)، فننبر الكلمة المصحِّحة CAR.'),
  mcq('A: Did Frank buy a car last week?  B: No, Frank bought a car yesterday. — Which word does B stress?', ['Frank', 'bought', 'car', 'yesterday'], 3,
    'أ: هل اشترى فرانك سيارة الأسبوع الماضي؟ ب: لا، فرانك اشترى سيارة البارحة. — على أيّ كلمة يضع ب النبر؟',
    'الخطأ في الزمن (last week)، فننبر YESTERDAY.'),
  mcq('A: Did Frank sell a car yesterday?  B: No, Frank bought a car yesterday. — Which word does B stress?', ['Frank', 'bought', 'car', 'yesterday'], 1,
    'أ: هل باع فرانك سيارة البارحة؟ ب: لا، فرانك اشترى سيارة البارحة. — على أيّ كلمة يضع ب النبر؟',
    'الخطأ في الفعل (sell)، فننبر الفعل المصحِّح BOUGHT.'),
  mcq('A: Did Liam teach at London University for three years?  B: No, David taught at London University for three years. — Which word does B stress?', ['David', 'taught', 'London', 'three'], 0,
    'أ: هل درّس ليام في جامعة لندن ثلاث سنوات؟ ب: لا، ديفيد درّس في جامعة لندن ثلاث سنوات. — على أيّ كلمة يضع ب النبر؟',
    'الخطأ في الشخص (Liam)، فننبر DAVID.'),
  mcq('A: Did David teach at Oxford University for three years?  B: No, David taught at London University for three years. — Which word does B stress?', ['David', 'taught', 'London', 'years'], 2,
    'أ: هل درّس ديفيد في جامعة أكسفورد ثلاث سنوات؟ ب: لا، ديفيد درّس في جامعة لندن ثلاث سنوات. — على أيّ كلمة يضع ب النبر؟',
    'الخطأ في المكان (Oxford)، فننبر LONDON.'),
  mcq('A: Did David teach at London University for ten years?  B: No, David taught at London University for three years. — Which word does B stress?', ['David', 'taught', 'London', 'three'], 3,
    'أ: هل درّس ديفيد في جامعة لندن عشر سنوات؟ ب: لا، ديفيد درّس في جامعة لندن ثلاث سنوات. — على أيّ كلمة يضع ب النبر؟',
    'الخطأ في المدة (ten years)، فننبر THREE.'),

  // Pronunciation b — match the sentence to its implied meaning (words in italics are stressed)
  mcq('“PETER told John that a deal like this wasn\'t allowed.” (stress on Peter) — What does it imply?', [
    'It clarifies that Peter, as opposed to someone else, told John not to make the deal.',
    'It clarifies that John was told not to make the deal, not someone else.',
    'It emphasizes that Peter said the deal was not allowed, indicating that John thought or said the opposite.',
    'It emphasizes the fact that John had been told not to make the deal but did so anyway.',
  ], 0,
    '«بيتر أخبر جون أن صفقة كهذه غير مسموحة» (النبر على Peter) — ماذا تعني الجملة؟',
    'النبر على الفاعل Peter يعني: بيتر وليس شخصاً آخر هو الذي أخبر جون (1-b كما في المثال).'),
  mcq('“Peter told JOHN that a deal like this wasn\'t allowed.” (stress on John) — What does it imply?', [
    'It clarifies that Peter, as opposed to someone else, told John not to make the deal.',
    'It clarifies that John was told not to make the deal, not someone else.',
    'It emphasizes that Peter said the deal was not allowed, indicating that John thought or said the opposite.',
    'It emphasizes the fact that John had been told not to make the deal but did so anyway.',
  ], 1,
    '«بيتر أخبر جون أن صفقة كهذه غير مسموحة» (النبر على John) — ماذا تعني الجملة؟',
    'النبر على John يعني: جون هو من قيل له ذلك وليس شخصاً آخر (2-a).'),
  mcq('“Peter told John that A DEAL LIKE THIS wasn\'t allowed.” (stress on a deal like this) — What does it imply?', [
    'It clarifies that Peter, as opposed to someone else, told John not to make the deal.',
    'It clarifies that John was told not to make the deal, not someone else.',
    'It emphasizes the fact that John had been told not to make the deal but did so anyway.',
    'It emphasizes that Peter said the deal was not allowed, indicating that John thought or said the opposite.',
  ], 2,
    '«بيتر أخبر جون أن صفقة كهذه غير مسموحة» (النبر على a deal like this) — ماذا تعني الجملة؟',
    'النبر على a deal like this يركّز على الصفقة نفسها: جون قيل له ألّا يعقد هذه الصفقة بالذات ومع ذلك عقدها (3-d).'),
  mcq('“Peter told John that a deal like this WASN\'T ALLOWED.” (stress on wasn\'t allowed) — What does it imply?', [
    'It clarifies that Peter, as opposed to someone else, told John not to make the deal.',
    'It emphasizes that Peter said the deal was not allowed, indicating that John thought or said the opposite.',
    'It clarifies that John was told not to make the deal, not someone else.',
    'It emphasizes the fact that John had been told not to make the deal but did so anyway.',
  ], 1,
    '«بيتر أخبر جون أن صفقة كهذه غير مسموحة» (النبر على wasn\'t allowed) — ماذا تعني الجملة؟',
    'النبر على wasn\'t allowed يؤكّد أن الصفقة غير مسموحة، أي عكس ما ظنّه جون أو قاله (4-c).'),

  // Grammar a — change the sentences into passive
  fill('The workers buried tons of rocks and earth under the railway line. → Tons of rocks and earth ___ under the railway line.',
    ['was buried', 'were buried', 'are buried', 'had buried'], 1,
    'دفن العمال أطناناً من الصخور والتراب تحت خط السكة الحديدية. ← ___ أطنان من الصخور والتراب تحت خط السكة الحديدية.',
    'دُفنت أطنان من الصخور والتراب تحت خط السكة الحديدية.',
    'الماضي البسيط buried ← المبني للمجهول was/were + التصريف الثالث. الفاعل الجديد tons (جمع) ← were buried.'),
  fill('Farmers cut 1500 square kilometres of rainforests every year. → 1500 square kilometres of rainforests ___ every year.',
    ['were cut', 'are cutting', 'are cut', 'have cut'], 2,
    'يقطع المزارعون 1500 كيلومتر مربع من الغابات المطيرة كل عام. ← ___ 1500 كيلومتر مربع من الغابات المطيرة كل عام.',
    'تُقطع 1500 كيلومتر مربع من الغابات المطيرة كل عام.',
    'every year تدلّ على المضارع البسيط (cut هنا مضارع) ← am/is/are + التصريف الثالث: are cut.'),
  fill('Environmentalists are debating a critical issue around the world. → A critical issue ___ around the world.',
    ['is debated', 'is being debated', 'was being debated', 'has been debated'], 1,
    'يناقش علماء البيئة قضية حرجة حول العالم. ← ___ قضية حرجة حول العالم.',
    'تُناقَش قضية حرجة حول العالم (الآن).',
    'المضارع المستمر are debating ← am/is/are + being + التصريف الثالث: is being debated.'),
  fill('The professor is showing his students the results of his research in the laboratory now. → His students ___ the results of his research in the laboratory now.',
    ['are shown', 'are being shown', 'are showing', 'were being shown'], 1,
    'يُري الأستاذ طلابه نتائج بحثه في المختبر الآن. ← ___ طلابُه نتائج بحثه في المختبر الآن.',
    'يُرى طلابُه (يُعرض على طلابه) نتائج بحثه في المختبر الآن.',
    'فعل بمفعولين (show someone something): نبدأ عادة بالشخص. المضارع المستمر ← are being shown.'),
  fill('The professor is showing his students the results of his research in the laboratory now. → The results of his research ___ to his students in the laboratory now.',
    ['are being shown', 'is being shown', 'are showing', 'have been shown'], 0,
    'يُري الأستاذ طلابه نتائج بحثه في المختبر الآن. ← ___ نتائج بحثه لطلابه في المختبر الآن.',
    'تُعرض نتائج بحثه على طلابه في المختبر الآن.',
    'الصيغة الثانية: نبدأ بالشيء ونضع to قبل الشخص. results جمع ← are being shown.'),
  fill('The government will pay Dr. Mahmoud 20 million Syrian pounds for his great invention. → Dr. Mahmoud ___ 20 million Syrian pounds for his great invention.',
    ['will pay', 'will be paid', 'would be paid', 'will been paid'], 1,
    'ستدفع الحكومة للدكتور محمود 20 مليون ليرة سورية مقابل اختراعه العظيم. ← ___ الدكتور محمود 20 مليون ليرة سورية مقابل اختراعه العظيم.',
    'سيُدفع للدكتور محمود 20 مليون ليرة سورية مقابل اختراعه العظيم.',
    'مع الفعل الناقص will ← will + be + التصريف الثالث: will be paid.'),
  fill('The government will pay Dr. Mahmoud 20 million Syrian pounds for his great invention. → 20 million Syrian pounds ___ to Dr. Mahmoud for his great invention.',
    ['will be paid', 'will pay', 'will be paying', 'is paid'], 0,
    'ستدفع الحكومة للدكتور محمود 20 مليون ليرة سورية مقابل اختراعه العظيم. ← ___ 20 مليون ليرة سورية للدكتور محمود مقابل اختراعه العظيم.',
    'ستُدفع 20 مليون ليرة سورية للدكتور محمود مقابل اختراعه العظيم.',
    'الصيغة الثانية تبدأ بالشيء المدفوع وتضع to قبل الشخص: will be paid to Dr. Mahmoud.'),
  fill('The secretary has told the manager some bad news about the new project. → The manager ___ some bad news about the new project.',
    ['has told', 'has been told', 'have been told', 'had been telling'], 1,
    'أخبرت السكرتيرة المدير ببعض الأخبار السيئة عن المشروع الجديد. ← ___ المدير ببعض الأخبار السيئة عن المشروع الجديد.',
    'أُخبِر المدير ببعض الأخبار السيئة عن المشروع الجديد.',
    'المضارع التام has told ← has/have + been + التصريف الثالث. the manager مفرد ← has been told.'),
  fill('The secretary has told the manager some bad news about the new project. → Some bad news ___ to the manager about the new project.',
    ['have been told', 'has told', 'has been told', 'was telling'], 2,
    'أخبرت السكرتيرة المدير ببعض الأخبار السيئة عن المشروع الجديد. ← ___ بعض الأخبار السيئة للمدير عن المشروع الجديد.',
    'قيلت بعض الأخبار السيئة للمدير عن المشروع الجديد.',
    'news اسم غير معدود يأخذ فعلاً مفرداً رغم حرف s ← has been told.'),
  fill('The teacher was asking us a very difficult question when the schoolbell rang. → We ___ a very difficult question when the schoolbell rang.',
    ['were asked', 'was being asked', 'were being asked', 'were asking'], 2,
    'كان المعلّم يسألنا سؤالاً صعباً جداً عندما رنّ جرس المدرسة. ← ___ سؤالاً صعباً جداً عندما رنّ جرس المدرسة.',
    'كنّا نُسأل سؤالاً صعباً جداً عندما رنّ جرس المدرسة.',
    'الماضي المستمر was asking ← was/were + being + التصريف الثالث. we ← were being asked.'),

  // Grammar b — change the questions using the passive voice
  mcq('When is he going to pay the taxes? — Choose the passive question.', [
    'When is the taxes going to be paid by him?',
    'When are the taxes going to be paid by him?',
    'When are the taxes going to pay by him?',
    'When the taxes are going to be paid by him?',
  ], 1,
    'متى سيدفع الضرائب؟ — اختر السؤال بالمبني للمجهول.',
    'be going to ← be going to + be + التصريف الثالث. taxes جمع ← are، ونحافظ على ترتيب السؤال (are قبل الفاعل).'),
  mcq('How much do they spend on these activities? — Choose the passive question.', [
    'How much is spent on these activities?',
    'How much is spending on these activities?',
    'How much was spent on these activities?',
    'How much do spent on these activities?',
  ], 0,
    'كم ينفقون على هذه الأنشطة؟ — اختر السؤال بالمبني للمجهول.',
    'المضارع البسيط do spend ← is/are + التصريف الثالث، والمال (how much) غير معدود ← is spent. نحذف by them لأنه فاعل عام.'),
  mcq('Will you pay the fine tomorrow? — Choose the passive question.', [
    'Will the fine been paid by you tomorrow?',
    'Will be the fine paid by you tomorrow?',
    'Will the fine be paid by you tomorrow?',
    'Will the fine is paid by you tomorrow?',
  ], 2,
    'هل ستدفع الغرامة غداً؟ — اختر السؤال بالمبني للمجهول.',
    'will ← Will + الفاعل الجديد + be + التصريف الثالث: Will the fine be paid ...?'),
  build('Have you been shown what to do?', 'حوّل إلى المبني للمجهول: Has anybody shown you what to do? (هل أراك أحد ماذا تفعل؟)',
    'المضارع التام has shown ← Have + you + been + shown. نحذف anybody لأنه فاعل غير محدّد.'),
  build('Why wasn\'t the roof mended before it fell down?', 'حوّل إلى المبني للمجهول: Why didn\'t they mend the roof before it fell down? (لماذا لم يُصلحوا السقف قبل أن يسقط؟)',
    'الماضي البسيط المنفي didn\'t mend ← wasn\'t + mended (the roof مفرد). ويبقى it fell down كما هو.'),

  // Everyday English a — choose the best follow-up question
  mcq('“I\'ve heard that a huge amount of oil has just been found in my country.” — Best follow-up question:', [
    'Don\'t you think you\'d feel isolated?',
    'Could this have an impact on the price of petrol for car drivers?',
    'How long have you had yours?',
    'How have the students reacted?',
  ], 1,
    '«سمعت أنه قد عُثر للتوّ على كمية ضخمة من النفط في بلدي.» — أفضل سؤال متابعة:',
    'النفط مرتبط بسعر البنزين، فالسؤال المناسب: Could this have an impact on the price of petrol? (1-c).'),
  mcq('“My perfect house would be high in the mountains.” — Best follow-up question:', [
    'Don\'t you think you\'d feel isolated?',
    'But what could be the reason behind that?',
    'Do you mean it\'s worth working for nothing?',
    'How long have you had yours?',
  ], 0,
    '«بيتي المثالي سيكون عالياً في الجبال.» — أفضل سؤال متابعة:',
    'البيت البعيد في الجبال قد يسبّب الشعور بالعزلة ← Don\'t you think you\'d feel isolated? (2-a).'),
  mcq('“Many celebrities like to get involved in charity work.” — Best follow-up question:', [
    'How have the students reacted?',
    'Could this have an impact on the price of petrol for car drivers?',
    'Do you mean it\'s worth working for nothing?',
    'Don\'t you think you\'d feel isolated?',
  ], 2,
    '«كثير من المشاهير يحبون المشاركة في العمل الخيري.» — أفضل سؤال متابعة:',
    'العمل الخيري عمل بلا أجر ← Do you mean it\'s worth working for nothing? (3-e).'),
  mcq('“I heard that constant texting can cause brain disorders.” — Best follow-up question:', [
    'How long have you had yours?',
    'But what could be the reason behind that?',
    'How have the students reacted?',
    'Don\'t you think you\'d feel isolated?',
  ], 1,
    '«سمعت أن كتابة الرسائل النصية باستمرار قد تسبّب اضطرابات في الدماغ.» — أفضل سؤال متابعة:',
    'نسأل عن سبب هذه المعلومة الغريبة ← But what could be the reason behind that? (4-b).'),
  mcq('“The government in my country has extended the school day by one hour each day.” — Best follow-up question:', [
    'Do you mean it\'s worth working for nothing?',
    'How long have you had yours?',
    'Could this have an impact on the price of petrol for car drivers?',
    'How have the students reacted?',
  ], 3,
    '«مدّدت الحكومة في بلدي اليوم الدراسي ساعة واحدة كل يوم.» — أفضل سؤال متابعة:',
    'الأمر يخصّ الطلاب، فنسأل عن ردّة فعلهم ← How have the students reacted? (5-f).'),
  mcq('“About 85% of the world\'s population now own a mobile phone.” — Best follow-up question:', [
    'How long have you had yours?',
    'Don\'t you think you\'d feel isolated?',
    'But what could be the reason behind that?',
    'Do you mean it\'s worth working for nothing?',
  ], 0,
    '«نحو 85% من سكان العالم يملكون الآن هاتفاً محمولاً.» — أفضل سؤال متابعة:',
    'yours = your mobile phone ← How long have you had yours? (6-d).'),

  // Everyday English b — write an appropriate response (asking for information)
  mcq('A: Our teachers are planning to take us on a weeklong boat trip to explore the sea bed.  B: …', [
    'Really? Can you tell me when the boat leaves?',
    'I\'m afraid the boat left yesterday.',
    'Certainly! The half-day trip is 10.000 SPY.',
    'Don\'t you think you\'d feel isolated in the mountains?',
  ], 0,
    'أ: يخطّط معلّمونا لأخذنا في رحلة بحرية مدتها أسبوع لاستكشاف قاع البحر. ب: …',
    'الردّ الطبيعي أن نطلب معلومات عن الرحلة بعبارة مهذبة مثل Can you tell me ...? و When ...?'),
  mcq('A: The funding for our local youth club has been cut.  B: …', [
    'Certainly! There are departures at 10 a.m. and 2 p.m.',
    'How long have you had yours?',
    'Oh no! Can you tell me why it has been cut?',
    'Is it necessary to book the boat in advance?',
  ], 2,
    'أ: خُفّض التمويل المخصّص لنادي الشباب المحلي عندنا. ب: …',
    'نطلب معلومات عن السبب ← Can you tell me why it has been cut? (لاحظ ترتيب الجملة الخبرية بعد Can you tell me).'),
  mcq('A: NASA has just discovered eight earth-like planets outside our solar system.  B: …', [
    'Is it necessary to book in advance?',
    'Really? What happens if people want to live there one day?',
    'I\'m afraid the trip is cancelled.',
    'Do you mean it\'s worth working for nothing?',
  ], 1,
    'أ: اكتشفت ناسا للتوّ ثمانية كواكب شبيهة بالأرض خارج مجموعتنا الشمسية. ب: …',
    'سؤال متابعة يطلب معلومة مرتبطة بالخبر، مستخدماً عبارة الوحدة What happens if ...?'),
]

// ---------------------------------------------------------------- Unit 4: Engineering (Activity Book 26–32)

const MEANINGS_U4 = {
  a: 'to carry out or do something',
  b: 'a medical process using the reflections of high-frequency sound waves to construct an image of a body organ',
  c: 'an arm or a leg',
  d: 'a field of study',
  e: 'relating to the treatment or cure of an illness',
}

const HEADINGS = {
  h1: 'Classification of medical devices',
  h2: 'How medical engineering works today',
  h3: 'Disadvantages of medical engineering',
  h4: 'Importance of medical technology engineering',
  h5: 'Medical engineering with animals',
  h6: 'The concept of medical engineering',
  h7: 'How doctors are injured at work',
  h8: 'Work field of medical engineers',
}

const u4Exercises: GrammarExercise[] = [
  // Reading a — match the words with their meanings
  mcq('What does “discipline” mean?', [MEANINGS_U4.a, MEANINGS_U4.d, MEANINGS_U4.c, MEANINGS_U4.e], 1,
    'ما معنى كلمة discipline؟',
    'discipline هنا = مجال دراسة / تخصّص (d). في النص: development that affected many disciplines.'),
  mcq('What does “limb” mean?', [MEANINGS_U4.c, MEANINGS_U4.e, MEANINGS_U4.a, MEANINGS_U4.d], 0,
    'ما معنى كلمة limb؟',
    'limb = طَرَف (ذراع أو ساق) (c). في النص: to design suitable artificial limbs (أطراف صناعية).'),
  mcq('What does “ultrasound” mean?', [MEANINGS_U4.e, MEANINGS_U4.d, MEANINGS_U4.b, MEANINGS_U4.c], 2,
    'ما معنى كلمة ultrasound؟',
    'ultrasound = التصوير بالأمواج فوق الصوتية: عملية طبية تستخدم انعكاس موجات صوتية عالية التردّد لتكوين صورة لعضو في الجسم (b).'),
  mcq('What does “therapeutic” mean?', [MEANINGS_U4.a, MEANINGS_U4.c, MEANINGS_U4.d, MEANINGS_U4.e], 3,
    'ما معنى كلمة therapeutic؟',
    'therapeutic = علاجي: متعلّق بمعالجة مرض أو شفائه (e). في النص: medical therapeutic devices used in chemical treatments.'),
  mcq('What does “conduct” mean?', [MEANINGS_U4.a, MEANINGS_U4.b, MEANINGS_U4.e, MEANINGS_U4.d], 0,
    'ما معنى الفعل conduct؟',
    'conduct = يُجري / يقوم بـ (a). في النص: conduct research needed to solve clinical problems (يُجري البحوث).'),

  // Reading b — choose the most suitable heading for each paragraph
  mcq('Which is the most suitable heading for paragraph A?', [HEADINGS.h1, HEADINGS.h6, HEADINGS.h5, HEADINGS.h8], 1,
    'ما العنوان الأنسب للفقرة A؟',
    'الفقرة A تعرّف الهندسة الطبية: This field is concerned with studying the body from an engineering point of view ← The concept of medical engineering (مفهوم الهندسة الطبية).'),
  mcq('Which is the most suitable heading for paragraph B?', [HEADINGS.h7, HEADINGS.h3, HEADINGS.h4, HEADINGS.h2], 2,
    'ما العنوان الأنسب للفقرة B؟',
    'الفقرة B تشرح كيف تساعد الأطباء وتسهّل عملهم فأصبح الجهاز الطبي an essential assistant ← Importance of medical technology engineering.'),
  mcq('Which is the most suitable heading for paragraph C?', [HEADINGS.h1, HEADINGS.h8, HEADINGS.h6, HEADINGS.h5], 0,
    'ما العنوان الأنسب للفقرة C؟',
    'الفقرة C تقسّم الأجهزة الطبية: divided into two parts ... Another classification includes three categories ← Classification of medical devices.'),
  mcq('Which is the most suitable heading for paragraph D?', [HEADINGS.h2, HEADINGS.h7, HEADINGS.h4, HEADINGS.h8], 3,
    'ما العنوان الأنسب للفقرة D؟',
    'الفقرة D تذكر أماكن العمل: hospitals and clinics, medical companies, research centers ← Work field of medical engineers.'),
  mcq('Which is the most suitable heading for paragraph E?', [HEADINGS.h3, HEADINGS.h2, HEADINGS.h1, HEADINGS.h6], 1,
    'ما العنوان الأنسب للفقرة E؟',
    'الفقرة E تتحدث عن الحاضر: 3D printing ... Nowadays biomedical engineers are able to develop new procedures ← How medical engineering works today.'),
  tf('The heading “Disadvantages of medical engineering” suits one of the paragraphs.', false,
    'العنوان «سلبيات الهندسة الطبية» يناسب إحدى الفقرات.',
    'خطأ: النص لا يذكر أي سلبيات، بل يؤكد أن هذا الفرع has improved healthcare to a great extent. هذا من العناوين الزائدة الثلاثة.'),
  tf('The heading “Medical engineering with animals” suits one of the paragraphs.', false,
    'العنوان «الهندسة الطبية مع الحيوانات» يناسب إحدى الفقرات.',
    'خطأ: النص يتحدث عن جسم الإنسان (the human body) ولا يذكر الحيوانات.'),
  tf('The heading “How doctors are injured at work” suits one of the paragraphs.', false,
    'العنوان «كيف يُصاب الأطباء في العمل» يناسب إحدى الفقرات.',
    'خطأ: لا يذكر النص إصابات الأطباء؛ هذا عنوان زائد.'),

  // More comprehension on the text (reference words, details, meanings in context)
  mcq('Paragraph A: “... medical technology engineering, which is also called biomedical engineering.” What does “which” refer to?', [
    'technological development', 'medical technology engineering', 'the specialisation of engineering', 'many disciplines',
  ], 1,
    'الفقرة A: علامَ يعود الضمير which في «... which is also called biomedical engineering»؟',
    'which تعود على أقرب اسم مناسب قبلها: medical technology engineering، وهي التي تُسمّى أيضاً biomedical engineering.'),
  mcq('Paragraph B: “... but rather, they must be familiar with all aspects of human body.” Who does “they” refer to?', [
    'doctors', 'patients', 'electrical, mechanical, computer engineers and others', 'medical devices',
  ], 2,
    'الفقرة B: على مَن يعود الضمير they في «they must be familiar with all aspects of human body»؟',
    'they تعود على المهندسين الذين تدخّلوا في تصميم الأجهزة: electrical, mechanical computer engineers and others، فمعرفتهم لا تقتصر على اختصاصهم.'),
  mcq('Paragraph C: “... more complex devices that require a certain amount of caution, such as those that emit X-rays.” What does “those” refer to?', [
    'devices', 'categories', 'bandages', 'doctors',
  ], 0,
    'الفقرة C: علامَ يعود those في «such as those that emit X-rays»؟',
    'those = the devices (الأجهزة المعقّدة التي تُصدر الأشعة السينية).'),
  mcq('According to paragraph C, which is an example of a diagnostic medical device?', [
    'bandages', 'the ultrasound device', 'the valves used in the artificial heart', 'artificial joints',
  ], 1,
    'بحسب الفقرة C، ما مثال الجهاز الطبي التشخيصي؟',
    'النص: diagnostic medical devices, most notably the ultrasound device.'),
  mcq('According to paragraph C, which devices require a deep study before their use?', [
    'bandages and body temperature meters',
    'devices used in chemical treatments',
    'mobile phones and sensors',
    'the valves used in the artificial heart and the artificial joints',
  ], 3,
    'بحسب الفقرة C، ما الأجهزة التي تتطلّب دراسة عميقة قبل استخدامها؟',
    'النص: there are those which require a deep study before their use, such as the valves used in the artificial heart, in addition to the artificial joints.'),
  mcq('According to paragraph B, engineers who design medical devices must be familiar with …', [
    'biology, anatomy and physiology', 'nursing and teaching', 'only their own specialty', 'business and marketing',
  ], 0,
    'بحسب الفقرة B، يجب أن يكون المهندسون الذين يصمّمون الأجهزة الطبية مُلمّين بـ …',
    'النص: they must be familiar with all aspects of human body, from biology, anatomy and physiology.'),
  mcq('According to paragraph E, what is the most favoured new tool in the design process?', [
    'X-rays', 'the ultrasound device', '3D printing', 'body temperature meters',
  ], 2,
    'بحسب الفقرة E، ما الأداة الجديدة الأكثر تفضيلاً في عملية التصميم؟',
    'النص: with 3D printing being the most favoured new tool (الطباعة ثلاثية الأبعاد).'),
  mcq('Paragraph B: “Medical technology engineering helps doctors define their tasks and facilitates their work.” “Facilitates” means …', [
    'makes more difficult', 'makes easier', 'stops', 'describes',
  ], 1,
    'الفقرة B: ما معنى facilitates في «... and facilitates their work»؟',
    'facilitate = يسهّل، أي يجعل العمل أسهل (makes easier).'),
  mcq('Paragraph A: “As a result of the substantial scientific and technological development ...” “Substantial” means …', [
    'large and important', 'small and slow', 'dangerous', 'old-fashioned',
  ], 0,
    'الفقرة A: ما معنى substantial في «the substantial scientific and technological development»؟',
    'substantial = كبير / جوهري (large and important).'),
  tf('Medical technology engineering is also called biomedical engineering.', true,
    'تُسمّى هندسة التكنولوجيا الطبية أيضاً الهندسة الطبية الحيوية.',
    'صح: medical technology engineering, which is also called biomedical engineering.'),
  tf('Medical engineers work only with other engineers.', false,
    'يعمل المهندسون الطبيون مع مهندسين آخرين فقط.',
    'خطأ: medical engineers work in cooperation with all disciplines, including nursing, medicine, biology, and other disciplines.'),
  tf('Simple devices such as bandages need a deep study before their use.', false,
    'الأجهزة البسيطة مثل الضمادات تحتاج إلى دراسة عميقة قبل استخدامها.',
    'خطأ: الضمادات من الأجهزة البسيطة (simple devices)، أما التي تحتاج دراسة عميقة فهي صمّامات القلب الاصطناعي والمفاصل الاصطناعية.'),
  tf('The need for development has made designing medical devices a great priority.', true,
    'جعلت الحاجة إلى التطوير تصميمَ الأجهزة الطبية أولوية كبرى.',
    'صح: The need for development in this field has made designing medical devices a great priority.'),

  // Vocabulary a — choose the correct phrasal verbs
  fill('The engineer has to ___ the joints before leaving the site.', ['drive into', 'check over', 'jack up'], 1,
    'على المهندس أن ___ المفاصل قبل مغادرة الموقع.',
    'على المهندس أن يفحص المفاصل بدقّة قبل مغادرة الموقع.',
    'check over = يفحص بحثاً عن أي عيوب أو أخطاء (to inspect for any faults).'),
  fill('We need a suitable size of nails to be ___ that old chair to be repaired.', ['shored up', 'driven into', 'pulled down'], 1,
    'نحتاج إلى مسامير بحجم مناسب كي ___ ذلك الكرسي القديم لإصلاحه.',
    'نحتاج إلى مسامير بحجم مناسب كي تُدَقّ في ذلك الكرسي القديم لإصلاحه.',
    'drive into = يدقّ شيئاً في شيء آخر بالطرق (to force something into something else by hitting it). والمسامير تُدَقّ، وبعد to be نستخدم التصريف الثالث driven.'),
  fill('Houses by the sea are usually ___ faster because of moisture.', ['eaten away', 'fenced off', 'jacked up'], 0,
    'البيوت القريبة من البحر عادةً ___ أسرع بسبب الرطوبة.',
    'البيوت القريبة من البحر عادةً تتآكل أسرع بسبب الرطوبة.',
    'eat away = يُآكِل / يَحُتّ (to erode or corrode)، والرطوبة تسبّب التآكل. الجملة مبنية للمجهول: are eaten away.'),
  fill('The police have ___ the crime theatre in order to start investigation.', ['knocked at', 'fenced off', 'pulled down'], 1,
    'قامت الشرطة ___ مسرح الجريمة لتبدأ التحقيق.',
    'قامت الشرطة بتطويق مسرح الجريمة بحاجز لتبدأ التحقيق.',
    'fence off = يمنع الوصول إلى مكان بحاجز (to restrict access using some kind of barrier).'),

  // Vocabulary b — prepositions of movement (to, from, off, into, onto, out of)
  fill('The monkey escaped from its cage and jumped ___ the lake.', ['onto', 'into', 'off', 'from'], 1,
    'هرب القرد من قفصه وقفز ___ البحيرة.',
    'هرب القرد من قفصه وقفز إلى داخل البحيرة.',
    'into = حركة إلى داخل شيء (الماء). ونقيضها out of.'),
  fill('It took a long time to get it ___ the lake and back into its cage.', ['into', 'onto', 'out of', 'to'], 2,
    'استغرق الأمر وقتاً طويلاً لإخراجه ___ البحيرة وإعادته إلى قفصه.',
    'استغرق الأمر وقتاً طويلاً لإخراجه من البحيرة وإعادته إلى قفصه.',
    'out of = حركة من داخل شيء إلى خارجه، وهي عكس into.'),
  fill('It took a long time to get it out of the lake and back ___ its cage.', ['into', 'off', 'from', 'out of'], 0,
    'استغرق الأمر وقتاً طويلاً لإخراجه من البحيرة وإعادته ___ قفصه.',
    'استغرق الأمر وقتاً طويلاً لإخراجه من البحيرة وإعادته إلى داخل قفصه.',
    'القفص مكان مغلق ندخل إليه ← into.'),
  fill('Henry drove his car ___ the beach and then he couldn\'t move it because the wheels sank into the sand.', ['off', 'onto', 'out of', 'from'], 1,
    'قاد هنري سيارته ___ الشاطئ ثم لم يستطع تحريكها لأن العجلات غاصت في الرمل.',
    'قاد هنري سيارته إلى سطح الشاطئ ثم لم يستطع تحريكها لأن العجلات غاصت في الرمل.',
    'onto = حركة إلى سطح شيء (الشاطئ سطح). ونقيضها off.'),
  fill('Henry drove his car onto the beach and then he couldn\'t move it because the wheels sank ___ the sand.', ['onto', 'to', 'into', 'off'], 2,
    'قاد هنري سيارته إلى الشاطئ ثم لم يستطع تحريكها لأن العجلات غاصت ___ الرمل.',
    'قاد هنري سيارته إلى الشاطئ ثم لم يستطع تحريكها لأن العجلات غاصت في داخل الرمل.',
    'العجلات دخلت في الرمل ← into (حركة إلى الداخل).'),
  fill('In the end he needed eight people to push it ___ the beach and back onto the road.', ['onto', 'off', 'into', 'to'], 1,
    'في النهاية احتاج إلى ثمانية أشخاص ليدفعوها ___ الشاطئ ويعيدوها إلى الطريق.',
    'في النهاية احتاج إلى ثمانية أشخاص ليدفعوها بعيداً عن الشاطئ ويعيدوها إلى الطريق.',
    'off = حركة بعيداً عن سطح شيء، وهي عكس onto (drove onto the beach ← push it off the beach).'),
  fill('In the end he needed eight people to push it off the beach and back ___ the road.', ['out of', 'off', 'from', 'onto'], 3,
    'في النهاية احتاج إلى ثمانية أشخاص ليدفعوها بعيداً عن الشاطئ ويعيدوها ___ الطريق.',
    'في النهاية احتاج إلى ثمانية أشخاص ليدفعوها بعيداً عن الشاطئ ويعيدوها إلى سطح الطريق.',
    'الطريق سطح نصعد إليه ← onto.'),
  fill('We thought we should walk ___ the bakery for breakfast because it is such a beautiful day.', ['to', 'onto', 'off', 'out of'], 0,
    'فكّرنا أن نمشي ___ المخبز لتناول الفطور لأن اليوم جميل جداً.',
    'فكّرنا أن نمشي إلى المخبز لتناول الفطور لأن اليوم جميل جداً.',
    'to = حركة نحو مكان (الوجهة): walk to the bakery، مثل They walked to the next town.'),

  // Pronunciation — elision: where may /t/ or /d/ disappear?
  mcq('Elision: in which word may /t/ or /d/ disappear? “My neighbour asked me over for dinner.”', ['neighbour', 'asked', 'over', 'dinner'], 1,
    'الحذف: في أيّ كلمة قد يختفي الصوت /t/ أو /d/؟ «دعاني جاري إلى العشاء.»',
    'في asked me تقع /t/ (نهاية الماضي -ed) بين صامتين /k/ و /m/ فتُحذف في الكلام السريع: aske(d) me.'),
  mcq('Elision: in which word may /t/ or /d/ disappear? “My best friend let me borrow his car.”', ['best', 'borrow', 'his', 'car'], 0,
    'الحذف: في أيّ كلمة قد يختفي الصوت /t/ أو /d/؟ «سمح لي أعزّ أصدقائي باستعارة سيارته.»',
    'في best friend تقع /t/ بين /s/ و /f/ فتُحذف: bes(t) friend. (وقد تُحذف /d/ في friend let أيضاً.)'),
  mcq('Elision: where may /t/ disappear? “I don\'t know when it is the best time to call you.”', ['in “call” and “you”', 'in “know” and “when”', 'in “don\'t” and “best”', 'in “it” and “is”'], 2,
    'الحذف: أين قد تختفي /t/؟ «لا أعرف متى يكون أفضل وقت للاتصال بك.»',
    'don\'t know: /t/ بين /n/ و /n/ ← I don\'(t) know. و best time: /t/ بين /s/ و /t/ ← bes(t) time.'),
  mcq('Elision: in which word may /t/ or /d/ disappear? “They went fishing on a boat.”', ['they', 'went', 'fishing', 'boat'], 1,
    'الحذف: في أيّ كلمة قد يختفي الصوت /t/ أو /d/؟ «ذهبوا للصيد في قارب.»',
    'went fishing: /t/ بين /n/ و /f/ ← wen(t) fishing. أما /t/ في boat فليست بين صامتين.'),
  mcq('Elision: where may /t/ or /d/ disappear? “Don\'t hold back - say what you mean.”', ['in “say” and “what”', 'in “don\'t” and “hold”', 'in “you” and “mean”', 'in “what” and “say”'], 1,
    'الحذف: أين قد يختفي /t/ أو /d/؟ «لا تتردّد – قل ما تعنيه.»',
    'don\'t hold: /t/ بين /n/ و /h/، و hold back: /d/ بين /l/ و /b/ ← don\'(t) hol(d) back.'),
  mcq('Elision: in which word may /t/ or /d/ disappear? “Can you lend me some money?”', ['can', 'some', 'lend', 'money'], 2,
    'الحذف: في أيّ كلمة قد يختفي الصوت /t/ أو /d/؟ «هل يمكنك أن تُقرضني بعض المال؟»',
    'lend me: /d/ بين /n/ و /m/ ← len(d) me.'),

  // Grammar — causative: have something done
  fill('At the butcher\'s Ahmad said, “Please cut the meat into small pieces”. → Ahmad ___ into pieces.',
    ['cut the meat', 'had the meat cut', 'had cut the meat', 'has the meat cutting'], 1,
    'عند اللحّام قال أحمد: «من فضلك قطّع اللحم قطعاً صغيرة.» ← أحمد ___ قطعاً.',
    'أحمد جعل (اللحّام) يقطّع اللحم قطعاً.',
    'الصيغة السببية: have + المفعول + التصريف الثالث. الحدث في الماضي (said) ← had the meat cut. اللحّام هو من قطع لا أحمد.'),
  fill('The hairdresser cuts Rana\'s hair about twice a year. → Rana ___ about twice a year.',
    ['has her hair cut', 'has cut her hair', 'had her hair cutting', 'cuts her hair'], 0,
    'تقصّ مصفّفة الشعر شعر رنا مرتين تقريباً في السنة. ← رنا ___ مرتين تقريباً في السنة.',
    'رنا تقصّ شعرها (عند المصفّفة) مرتين تقريباً في السنة.',
    'عادة متكرّرة (twice a year) ← المضارع البسيط: has + her hair + cut.'),
  fill('Yesterday, the optician checked my mother\'s eyes. → Yesterday, my mother ___.',
    ['has her eyes checked', 'checked her eyes', 'had her eyes checked', 'had checked her eyes'], 2,
    'البارحة فحص طبيب البصريات عيني أمي. ← البارحة أمي ___.',
    'البارحة فحصت أمي عينيها (عند طبيب البصريات).',
    'yesterday ← الماضي البسيط: had + her eyes + checked. (had checked her eyes تعني أنها فحصتها بنفسها في الماضي التام.)'),
  fill('Mrs. Hakim\'s doctor says to her: “When you come to see me next week, I\'ll check your heartbeat.” → When Mrs. Hakim goes to see the doctor next week, she ___.',
    ['had her heartbeat checked', 'will check her heartbeat', 'will have her heartbeat checked', 'has her heartbeat check'], 2,
    'يقول طبيب السيدة حكيم لها: «عندما تأتين لرؤيتي الأسبوع القادم سأفحص نبضات قلبك.» ← عندما تذهب السيدة حكيم إلى الطبيب الأسبوع القادم ___.',
    'عندما تذهب السيدة حكيم إلى الطبيب الأسبوع القادم ستفحص نبضات قلبها (عند الطبيب).',
    'المستقبل (next week) ← will have + her heartbeat + checked.'),
  fill('A carpenter is going to mend the front door of our house. → We ___ of our house.',
    ['are going to mend the front door', 'are going to have the front door mended', 'had the front door mended', 'are going to have mended the front door'], 1,
    'سيُصلح نجّار الباب الأمامي لبيتنا. ← نحن ___ لبيتنا.',
    'نحن سنُصلح الباب الأمامي لبيتنا (عند نجّار).',
    'be going to ← are going to have + the front door + mended. انتبه لترتيب: المفعول قبل التصريف الثالث.'),
  fill('I repainted the house myself last month. → I ___.',
    ['had the house repainted', 'didn\'t have the house repainted', 'have the house repainted', 'didn\'t repaint the house'], 1,
    'أعدت طلاء البيت بنفسي الشهر الماضي. ← أنا ___.',
    'أنا لم أجعل أحداً يعيد طلاء البيت (بل طليته بنفسي).',
    'بما أنني طليته بنفسي فلم يقم به شخص آخر ← النفي: didn\'t have the house repainted (مثل: My father didn\'t have the car mended).'),
  fill('After being late for work every day for two weeks, Tom\'s boss reduced his pay. → Tom ___.',
    ['reduced his pay', 'had reduced his pay', 'had his pay reduced', 'has his pay reduced'], 2,
    'بعد أن تأخّر عن العمل كل يوم مدة أسبوعين، خفّض مدير توم راتبه. ← توم ___.',
    'خُفِّض راتب توم.',
    'نستخدم have something done لشيء غير سارّ حدث لشخص خارج إرادته. الماضي ← Tom had his pay reduced.'),

  // Everyday English — hesitation and uncertainty
  mcq('A: Do you think that students will study at home in the future instead of going to school?  B: …', [
    'Hm, I\'m not sure about that. I haven\'t made up my mind yet.',
    'Yes, definitely. I\'m completely sure they will.',
    'No, never. That\'s impossible.',
    'Certainly! The half-day trip is 10.000 SPY.',
  ], 0,
    'أ: هل تظن أن الطلاب سيدرسون في البيت في المستقبل بدلاً من الذهاب إلى المدرسة؟ ب: …',
    'المطلوب التعبير عن التردّد وعدم اليقين: I\'m not sure about that و I haven\'t made up my mind yet. أما الخيارات الأخرى فجازمة.'),
  mcq('A: Would science and technology find a cure for cancer?  B: …', [
    'Of course! I\'m absolutely sure.',
    'Perhaps. It might work one day, but I don\'t know much about medicine.',
    'Yes, they found it yesterday.',
    'Can you tell me how much a sightseeing tour costs?',
  ], 1,
    'أ: هل سيجد العلم والتكنولوجيا علاجاً للسرطان؟ ب: …',
    'Perhaps و It might work و I don\'t know much about تعبّر عن عدم اليقين.'),
  mcq('A: I\'ve heard that Moroccan people won\'t need a visa to go to Europe. Is that certain for you?  B: …', [
    'Yes, it is one hundred per cent certain.',
    'No doubt about it.',
    'I\'ll have to think about that. I don\'t know much about it.',
    'Certainly! There are departures at 10 a.m.',
  ], 2,
    'أ: سمعت أن المغاربة لن يحتاجوا إلى تأشيرة للذهاب إلى أوروبا. هل هذا مؤكّد بالنسبة إليك؟ ب: …',
    'I\'ll have to think about that و I don\'t know much about it تعبّران عن التردّد.'),
  mcq('A: Do you think that Indonesian will be an international language in the future?  B: …', [
    'Of course it will. Everyone knows that.',
    'Yes, I\'m sure.',
    'No, it never will.',
    'Maybe, maybe not. I can\'t decide yet.',
  ], 3,
    'أ: هل تظن أن الإندونيسية ستصبح لغة عالمية في المستقبل؟ ب: …',
    'Maybe, maybe not و I can\'t decide yet من عبارات التردّد في الوحدة.'),
  fill('A: Are you sure that Arsenal will win the game?  B: ___ They\'ve looked unstable lately.',
    ['Yes, I\'m completely sure.', 'I\'m not sure about that.', 'Of course they will win.', 'Certainly!'], 1,
    'أ: هل أنت متأكّد أن أرسنال سيفوز بالمباراة؟ ب: ___ لقد بدوا غير مستقرّين مؤخراً.',
    'أ: هل أنت متأكّد أن أرسنال سيفوز بالمباراة؟ ب: لست متأكّداً من ذلك. لقد بدوا غير مستقرّين مؤخراً.',
    'الجملة التالية (بدوا غير مستقرّين) تدلّ على الشكّ ← I\'m not sure about that.'),
]

// ---------------------------------------------------------------- export

export const extras: ModuleExtras = {
  units: {
    u3: {
      workbook: {
        pages: '16–25',
        readings: [
          {
            title: 'Medical Inventions',
            paragraphs: [
              'Over the years, technology has played a significant role in developing the medical science. Advances in medicine have created alternatives to dangerous or even ineffective procedures. Breakthroughs have found new solutions to historical medical challenges and have opened up possibilities beyond what doctors thought was impossible years ago. Today\'s techniques, surgeries and drugs have decreased the overall deaths among humans. Medical inventions like X-ray Imaging, functional Magnetic Resonance Imaging (MRI), Robotic Surgery and Organ Transplants have changed medicine forever.',
              'An X-ray is a common imaging test that has been used for decades. It is an image created on a photographic film or electronically on a digital system, using an external radiation to produce images of the body. X-ray Imaging can help doctors view the inside of the patient\'s body without having to make an incision. This can help surgeons diagnose, monitor and treat many medical conditions.',
              'Magnetic Resonance Imaging (MRI) is a medical imaging technique used in radiography to form pictures of the anatomy and the physiological-processes of the body. MRI scanners use strong magnetic fields and radio waves to generate images of the organs in the body. MRI allows to access soft tissues and bone marrow involvement in case of the inflammation and infection.',
              'Robotic Surgery is usually associated with minimally invasive procedures. During Robotic Surgery, surgeons can perform very complex steps with more precision, flexibility and control than it is possible with conventional techniques. Compared to traditional open surgery, Robotic Surgery results in smaller incisions which reduce pain and lead to less time spent in hospitals and quicker recovery time.',
              'Such an invention can greatly improve the health of patients, allowing them to return to normal activities. Moreover, doctors have been successfully transplanting various body parts like heart, liver and kidney and have performed various brain surgeries, too. Besides, artificial heart transplanting has evolved over decades saving countless lives.',
              'In summary, the emerging medical devices and technologies, especially the mobile phones and tiny Nano-sized sensors embedded in several electronic devices that enable sending and receiving information wirelessly, are changing the face of 21st century medical practice. Currently, people born with diseases or any other body defects can now be healed with the help of advanced technology. Furthermore, various advances in medical field have saved millions of lives and improved many others. The new technologies will allow remote monitoring of patients and their access to healthcare, health data collection and information exchange with the providers and other patients. Such benefits would continue to increase with the fast pace development of medical health technologies.',
            ],
            paragraphsAr: [
              'على مرّ السنين، أدّت التكنولوجيا دوراً مهماً في تطوير العلوم الطبية. فقد أوجدت التطوّرات في الطب بدائل للإجراءات الخطيرة أو حتى غير الفعّالة. ووجدت الإنجازات الكبرى حلولاً جديدة لتحدّيات طبية قديمة، وفتحت آفاقاً تتجاوز ما ظنّه الأطباء مستحيلاً قبل سنوات. لقد خفّضت التقنيات والجراحات والأدوية الحديثة مجمل الوفيات بين البشر. وغيّرت اختراعات طبية مثل التصوير بالأشعة السينية، والتصوير الوظيفي بالرنين المغناطيسي، والجراحة الروبوتية، وزراعة الأعضاء، الطبَّ إلى الأبد.',
              '(التصوير بالأشعة السينية) الصورة بالأشعة السينية فحص تصويري شائع يُستخدم منذ عقود. وهي صورة تُنشأ على فيلم فوتوغرافي أو إلكترونياً على نظام رقمي، باستخدام إشعاع خارجي لإنتاج صور للجسم. ويمكن للتصوير بالأشعة السينية أن يساعد الأطباء على رؤية داخل جسم المريض دون الحاجة إلى إحداث شقّ جراحي. وهذا يساعد الجرّاحين على تشخيص كثير من الحالات الطبية ومتابعتها وعلاجها.',
              '(التصوير بالرنين المغناطيسي) التصوير بالرنين المغناطيسي تقنية تصوير طبي تُستخدم في التصوير الإشعاعي لتكوين صور لتشريح الجسم وعملياته الفيزيولوجية. تستخدم أجهزة الرنين المغناطيسي حقولاً مغناطيسية قوية وموجات راديوية لتوليد صور لأعضاء الجسم. ويتيح الرنين المغناطيسي الوصول إلى الأنسجة الرخوة ومعرفة إصابة نقي العظم في حالات الالتهاب والعدوى.',
              '(الجراحة الروبوتية) ترتبط الجراحة الروبوتية عادة بالإجراءات الأقلّ تدخّلاً (بأصغر شقّ ممكن). ففي أثناء الجراحة الروبوتية يستطيع الجرّاحون تنفيذ خطوات معقّدة جداً بدقّة ومرونة وتحكّم أكبر ممّا تسمح به التقنيات التقليدية. وبالمقارنة مع الجراحة المفتوحة التقليدية، تنتج عن الجراحة الروبوتية شقوق أصغر تخفّف الألم وتؤدي إلى قضاء وقت أقلّ في المستشفيات وشفاء أسرع.',
              '(زراعة الأعضاء) يمكن لمثل هذا الاختراع أن يحسّن صحة المرضى كثيراً، ويسمح لهم بالعودة إلى أنشطتهم الطبيعية. علاوة على ذلك، ينجح الأطباء في زراعة أعضاء مختلفة من الجسم مثل القلب والكبد والكلية، وقد أجروا أيضاً جراحات متنوعة في الدماغ. إضافة إلى ذلك، تطوّرت زراعة القلب الاصطناعي على مدى عقود وأنقذت أرواحاً لا تُحصى.',
              'خلاصة القول، إن الأجهزة والتقنيات الطبية الناشئة، وخاصة الهواتف المحمولة والمستشعرات النانوية الدقيقة المدمجة في أجهزة إلكترونية عديدة والتي تتيح إرسال المعلومات واستقبالها لاسلكياً، تغيّر وجه الممارسة الطبية في القرن الحادي والعشرين. وحالياً، صار بالإمكان علاج الأشخاص المولودين بأمراض أو بأي عيوب جسدية أخرى بمساعدة التكنولوجيا المتقدّمة. علاوة على ذلك، أنقذت التطوّرات المختلفة في المجال الطبي ملايين الأرواح وحسّنت حياة كثيرين غيرهم. وستسمح التقنيات الجديدة بمراقبة المرضى عن بُعد وبوصولهم إلى الرعاية الصحية، وبجمع البيانات الصحية وتبادل المعلومات مع مقدّمي الرعاية ومع المرضى الآخرين. وستستمر هذه الفوائد في الازدياد مع التطوّر السريع لتقنيات الصحة الطبية.',
            ],
            questions: [
              {
                q: 'What role have new discoveries played in developing medical science?',
                qAr: 'ما الدور الذي أدّته الاكتشافات الجديدة في تطوير العلوم الطبية؟',
                options: [
                  'They have made traditional procedures more dangerous.',
                  'They have found new solutions to historical medical challenges and opened up possibilities beyond what doctors thought was impossible.',
                  'They have increased the overall deaths among humans.',
                  'They have replaced doctors with robots in all hospitals.',
                ],
                answer: 1,
                explainAr: 'الفقرة الأولى: Breakthroughs have found new solutions to historical medical challenges and have opened up possibilities beyond what doctors thought was impossible.',
              },
              {
                q: 'How does the X-ray work to produce images?',
                qAr: 'كيف تعمل الأشعة السينية لإنتاج الصور؟',
                options: [
                  'It uses strong magnetic fields and radio waves.',
                  'It uses tiny Nano-sized sensors inside the body.',
                  'It uses an external radiation to produce images on a photographic film or on a digital system.',
                  'It needs a small incision to view the inside of the body.',
                ],
                answer: 2,
                explainAr: 'النص: It is an image created on a photographic film or electronically on a digital system, using an external radiation to produce images of the body.',
              },
              {
                q: 'How can the images of the body organs be generated by MRI?',
                qAr: 'كيف تُولَّد صور أعضاء الجسم بجهاز الرنين المغناطيسي؟',
                options: [
                  'By using strong magnetic fields and radio waves.',
                  'By using an external radiation on a photographic film.',
                  'By making smaller incisions in the skin.',
                  'By sending information wirelessly from mobile phones.',
                ],
                answer: 0,
                explainAr: 'النص: MRI scanners use strong magnetic fields and radio waves to generate images of the organs in the body.',
              },
              {
                q: 'Why do surgeons prefer Robotic Surgery to the conventional one?',
                qAr: 'لماذا يفضّل الجرّاحون الجراحة الروبوتية على الجراحة التقليدية؟',
                options: [
                  'Because it is cheaper and does not need doctors.',
                  'Because it gives more precision, flexibility and control, and its smaller incisions mean less pain and quicker recovery.',
                  'Because it uses radio waves instead of incisions.',
                  'Because patients must spend more time in hospital after it.',
                ],
                answer: 1,
                explainAr: 'النص: more precision, flexibility and control ... smaller incisions which reduce pain and lead to less time spent in hospitals and quicker recovery time.',
              },
              {
                q: 'What\'s the impact of Organ Transplant techniques on medicine?',
                qAr: 'ما أثر تقنيات زراعة الأعضاء في الطب؟',
                options: [
                  'They have stopped all brain surgeries.',
                  'They are used only for the heart.',
                  'They have made patients stay in hospital for a longer time.',
                  'They greatly improve patients\' health, let them return to normal activities and have saved countless lives.',
                ],
                answer: 3,
                explainAr: 'النص: Such an invention can greatly improve the health of patients, allowing them to return to normal activities ... saving countless lives.',
              },
              {
                q: 'What factors help change the face of medical field in the 21st century?',
                qAr: 'ما العوامل التي تساعد على تغيير وجه المجال الطبي في القرن الحادي والعشرين؟',
                options: [
                  'Old photographic films and conventional techniques.',
                  'Traditional open surgery and long stays in hospital.',
                  'The emerging medical devices and technologies, especially mobile phones and tiny Nano-sized sensors that send and receive information wirelessly.',
                  'Herbs and natural remedies.',
                ],
                answer: 2,
                explainAr: 'الفقرة الأخيرة: the emerging medical devices and technologies, especially the mobile phones and tiny Nano-sized sensors ... are changing the face of 21st century medical practice.',
              },
            ],
            trueFalse: [
              { statement: 'Nowadays deaths among human beings have been increased due to up-to-date medical discoveries.', answer: false },
              { statement: 'X-ray Imaging can help doctors view the inside of the patient\'s body without having to make an incision.', answer: true },
              { statement: 'X-ray techniques require strong radio waves to produce images of the body organs.', answer: false },
              { statement: 'Robotic Surgery results in smaller incisions which reduce pain.', answer: true },
              { statement: 'The fast pace development of medical health technologies would stop monitoring of patients remotely.', answer: false },
            ],
          },
        ],
        exercises: u3Exercises,
      },
      compositions: [
        {
          source: 'book',
          topic: 'In no more than 120 words, use your answers to write a composition about the healthcare in Syria nowadays.',
          topicAr: 'في ما لا يزيد على 120 كلمة، استخدم إجاباتك لكتابة موضوع عن الرعاية الصحية في سورية في هذه الأيام.',
          words: 120,
          points: [
            'What are the best ways to avoid getting sick?',
            'What skills are needed to be a good doctor or nurse?',
            'Do you think that healthcare should be free? Why / Why not?',
            'In your opinion, how will healthcare be in the future?',
          ],
          pointsAr: [
            'ما أفضل الطرق لتجنّب المرض؟',
            'ما المهارات اللازمة ليكون المرء طبيباً أو ممرضاً جيداً؟',
            'هل تظن أن الرعاية الصحية يجب أن تكون مجانية؟ لماذا؟',
            'برأيك، كيف ستكون الرعاية الصحية في المستقبل؟',
          ],
          plan: [
            { en: 'Topic sentence: say what healthcare in Syria is like nowadays (services, hospitals, vaccination).', ar: 'الجملة الافتتاحية: صِف حال الرعاية الصحية في سورية اليوم (الخدمات، المستشفيات، التلقيح).' },
            { en: 'Give the best ways to avoid getting sick.', ar: 'اذكر أفضل الطرق لتجنّب المرض.' },
            { en: 'Say which skills a good doctor or nurse needs.', ar: 'اذكر المهارات التي يحتاجها الطبيب أو الممرض الجيد.' },
            { en: 'Give your opinion: should healthcare be free? Why?', ar: 'أبدِ رأيك: هل يجب أن تكون الرعاية الصحية مجانية؟ ولماذا؟' },
            { en: 'Conclusion: how healthcare will be in the future (a hope or a recommendation).', ar: 'الخاتمة: كيف ستكون الرعاية الصحية في المستقبل (أمنية أو توصية).' },
          ],
          phrases: [
            { en: 'patients are treated by skilled doctors', ar: 'يُعالَج المرضى على أيدي أطباء مهرة (مبني للمجهول)' },
            { en: 'children are vaccinated against dangerous diseases', ar: 'يُلقَّح الأطفال ضد الأمراض الخطيرة' },
            { en: 'vaccination', ar: 'التلقيح' },
            { en: 'physician / surgery / nursing', ar: 'طبيب / جراحة / تمريض' },
            { en: 'prescribe medicine', ar: 'يصف الدواء' },
            { en: 'be on the mend', ar: 'يكون في طريقه إلى الشفاء' },
            { en: 'remote monitoring of patients', ar: 'مراقبة المرضى عن بُعد' },
            { en: 'new hospitals will be built', ar: 'ستُبنى مستشفيات جديدة (مبني للمجهول مع will)' },
            { en: 'In my opinion, ...', ar: 'برأيي، ...' },
            { en: 'However, ... / Furthermore, ...', ar: 'لكن، ... / علاوة على ذلك، ...' },
            { en: 'health is a basic right', ar: 'الصحة حقّ أساسي' },
          ],
          model: 'Healthcare in Syria has improved in many ways, although it still faces some challenges. Today, many services are offered free of charge in public hospitals and health centres, and children are vaccinated against dangerous diseases. The best ways to avoid getting sick are eating healthy food, doing exercise and keeping clean. A good doctor or nurse needs knowledge, patience and kindness, because patients are treated better when they feel safe. However, modern devices are still needed in small towns, and private clinics can be expensive. In my opinion, healthcare should be free for everyone because health is a basic right. In the future, I hope new hospitals will be built and patients will be monitored remotely.',
          modelAr: 'تحسّنت الرعاية الصحية في سورية في نواحٍ كثيرة، مع أنها ما زالت تواجه بعض التحدّيات. فاليوم تُقدَّم خدمات كثيرة مجاناً في المستشفيات والمراكز الصحية العامة، ويُلقَّح الأطفال ضد الأمراض الخطيرة. وأفضل الطرق لتجنّب المرض هي تناول الطعام الصحي وممارسة الرياضة والحفاظ على النظافة. ويحتاج الطبيب أو الممرض الجيد إلى المعرفة والصبر واللطف، لأن المرضى يُعالَجون بشكل أفضل عندما يشعرون بالأمان. لكن ما زالت هناك حاجة إلى أجهزة حديثة في البلدات الصغيرة، وقد تكون العيادات الخاصة مكلفة. برأيي يجب أن تكون الرعاية الصحية مجانية للجميع لأن الصحة حقّ أساسي. وفي المستقبل آمل أن تُبنى مستشفيات جديدة وأن يُراقَب المرضى عن بُعد.',
          checklistAr: [
            'هل بدأت بجملة افتتاحية واضحة عن الرعاية الصحية في سورية اليوم؟',
            'هل أجبت عن الأسئلة الأربعة (تجنّب المرض، مهارات الطبيب، المجانية، المستقبل)؟',
            'هل استخدمت المبني للمجهول بشكل صحيح (are treated, are vaccinated, will be built)؟',
            'هل ربطت الأفكار بأدوات ربط مثل However و In my opinion و because؟',
            'هل أنهيت بجملة ختامية عن المستقبل أو توصية؟',
            'هل راجعت الإملاء وعلامات الترقيم والحروف الكبيرة، ولم تتجاوز 120 كلمة؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'In no more than 120 words, write an essay about one of the recent medical inventions that has a great impact on medicine nowadays.',
          topicAr: 'في ما لا يزيد على 120 كلمة، اكتب مقالة عن أحد الاختراعات الطبية الحديثة التي لها أثر كبير في الطب في هذه الأيام.',
          words: 120,
          points: [
            'What is the name of the medical invention?',
            'When was it invented?',
            'Who was it invented by?',
            'What are the advantages of such an invention?',
            'Is it available in all hospitals or clinics?',
            'Show your opinion of the invention.',
          ],
          pointsAr: [
            'ما اسم الاختراع الطبي؟',
            'متى اختُرع؟',
            'مَن اخترعه؟',
            'ما مزايا هذا الاختراع؟',
            'هل هو متوفّر في كل المستشفيات أو العيادات؟',
            'أبدِ رأيك في الاختراع.',
          ],
          plan: [
            { en: 'Introduction: name the invention and say what it is used for (its purpose).', ar: 'المقدّمة: سمِّ الاختراع واذكر الغرض منه.' },
            { en: 'History: when it was invented and who it was invented by (use the past passive).', ar: 'التاريخ: متى اختُرع ومَن اخترعه (استخدم الماضي المبني للمجهول).' },
            { en: 'Main body: how it works and its advantages, with suitable adjectives.', ar: 'صلب الموضوع: كيف يعمل ومزاياه، مع صفات مناسبة.' },
            { en: 'Say whether it is available in all hospitals or clinics.', ar: 'اذكر إن كان متوفّراً في كل المستشفيات والعيادات.' },
            { en: 'Conclusion: your opinion / personal impression or a recommendation.', ar: 'الخاتمة: رأيك وانطباعك الشخصي أو توصية.' },
          ],
          phrases: [
            { en: 'breakthrough', ar: 'إنجاز كبير / اختراق' },
            { en: 'Magnetic Resonance Imaging (MRI)', ar: 'التصوير بالرنين المغناطيسي' },
            { en: 'strong magnetic fields and radio waves', ar: 'حقول مغناطيسية قوية وموجات راديوية' },
            { en: 'without having to make an incision', ar: 'دون الحاجة إلى شقّ جراحي' },
            { en: 'diagnose, monitor and treat', ar: 'يشخّص ويتابع ويعالج' },
            { en: 'soft tissues and bone marrow', ar: 'الأنسجة الرخوة ونقي العظم' },
            { en: 'it was developed in ... / it was invented by ...', ar: 'طُوِّر في ... / اختُرع على يد ... (مبني للمجهول)' },
            { en: 'with more precision', ar: 'بدقّة أكبر' },
            { en: 'saving countless lives', ar: 'منقذاً أرواحاً لا تُحصى' },
            { en: 'Moreover, ... / Besides, ... / In summary, ...', ar: 'علاوة على ذلك ... / إضافة إلى ذلك ... / خلاصة القول ...' },
            { en: 'Unfortunately, ...', ar: 'لسوء الحظ، ...' },
          ],
          model: 'Magnetic Resonance Imaging (MRI) is one of the most important medical inventions of recent times. It is used to form clear pictures of the body\'s organs. It was developed in the 1970s, and scientists such as Paul Lauterbur and Peter Mansfield were awarded the Nobel Prize for their work on it in 2003. MRI scanners use strong magnetic fields and radio waves, so doctors can see soft tissues and bone marrow without having to make an incision. As a result, many diseases are diagnosed early and treated with more precision. Unfortunately, it is not available in all hospitals because the scanners are very expensive. In my opinion, MRI is a real breakthrough that has saved countless lives.',
          modelAr: 'التصوير بالرنين المغناطيسي من أهم الاختراعات الطبية في العصر الحديث. يُستخدم لتكوين صور واضحة لأعضاء الجسم. وقد طُوِّر في سبعينيات القرن العشرين، ومُنح علماء مثل بول لوتربر وبيتر مانسفيلد جائزة نوبل على عملهم فيه عام 2003. تستخدم أجهزة الرنين حقولاً مغناطيسية قوية وموجات راديوية، فيستطيع الأطباء رؤية الأنسجة الرخوة ونقي العظم دون الحاجة إلى شقّ جراحي. ونتيجة لذلك تُشخَّص أمراض كثيرة مبكراً وتُعالَج بدقّة أكبر. لسوء الحظ، ليس متوفّراً في كل المستشفيات لأن الأجهزة غالية جداً. برأيي، الرنين المغناطيسي إنجاز حقيقي أنقذ أرواحاً لا تُحصى.',
          checklistAr: [
            'هل عرّفت بالاختراع وذكرت الغرض منه في المقدّمة (كما تطلب مهارة المقالة الوصفية)؟',
            'هل أجبت عن أسئلة الكتاب الستة (الاسم، متى، مَن، المزايا، التوفّر، الرأي)؟',
            'هل استخدمت الماضي المبني للمجهول بشكل صحيح (was developed, were awarded)؟',
            'هل وصفت الاختراع بصفات مناسبة وكلمات من الوحدة (incision, precision, breakthrough)؟',
            'هل ختمت برأيك الشخصي أو بتوصية؟',
            'هل راجعت القواعد والإملاء وعلامات الترقيم، ولم تتجاوز 120 كلمة؟',
          ],
        },
      ],
      translations: [
        { en: 'Over the years, technology has played a significant role in developing the medical science.', ar: 'على مرّ السنين، أدّت التكنولوجيا دوراً مهماً في تطوير العلوم الطبية.' },
        { en: 'Advances in medicine have created alternatives to dangerous or even ineffective procedures.', ar: 'أوجدت التطوّرات في الطب بدائل للإجراءات الخطيرة أو حتى غير الفعّالة.' },
        { en: 'Today\'s techniques, surgeries and drugs have decreased the overall deaths among humans.', ar: 'خفّضت التقنيات والجراحات والأدوية الحديثة مجمل الوفيات بين البشر.' },
        { en: 'An X-ray is a common imaging test that has been used for decades.', ar: 'الصورة بالأشعة السينية فحص تصويري شائع يُستخدم منذ عقود.' },
        { en: 'This can help surgeons diagnose, monitor and treat many medical conditions.', ar: 'هذا يمكن أن يساعد الجرّاحين على تشخيص كثير من الحالات الطبية ومتابعتها وعلاجها.' },
        { en: 'Robotic Surgery is usually associated with minimally invasive procedures.', ar: 'ترتبط الجراحة الروبوتية عادة بالإجراءات الأقلّ تدخّلاً جراحياً.' },
        { en: 'Besides, artificial heart transplanting has evolved over decades saving countless lives.', ar: 'إضافة إلى ذلك، تطوّرت زراعة القلب الاصطناعي على مدى عقود وأنقذت أرواحاً لا تُحصى.' },
        { en: 'Furthermore, various advances in medical field have saved millions of lives and improved many others.', ar: 'علاوة على ذلك، أنقذت التطوّرات المختلفة في المجال الطبي ملايين الأرواح وحسّنت حياة كثيرين غيرهم.' },
        { en: 'I have had chest pains and I\'m also having trouble breathing.', ar: 'أعاني من آلام في الصدر وأجد أيضاً صعوبة في التنفّس.' },
        { en: 'My left eye is itchy and my vision has been blurry for two weeks.', ar: 'عيني اليسرى تحكّني ورؤيتي مشوّشة منذ أسبوعين.' },
        { en: 'The workers buried tons of rocks and earth under the railway line.', ar: 'دفن العمال أطناناً من الصخور والتراب تحت خط السكة الحديدية.' },
        { en: 'Environmentalists are debating a critical issue around the world.', ar: 'يناقش علماء البيئة قضية حرجة حول العالم.' },
        { en: 'The secretary has told the manager some bad news about the new project.', ar: 'أخبرت السكرتيرة المدير ببعض الأخبار السيئة عن المشروع الجديد.' },
        { en: 'Many celebrities like to get involved in charity work.', ar: 'يحب كثير من المشاهير المشاركة في العمل الخيري.' },
        { en: 'I heard that constant texting can cause brain disorders.', ar: 'سمعت أن كتابة الرسائل النصية باستمرار قد تسبّب اضطرابات في الدماغ.' },
        { en: 'A local jewellery shop was broken into by someone yesterday.', ar: 'اقتحم أحدهم محلّ مجوهرات محلياً البارحة.' },
        { en: 'The owner of the shop is being treated by doctors for shock.', ar: 'يُعالَج صاحب المحل على أيدي الأطباء من الصدمة.' },
      ],
    },
    u4: {
      workbook: {
        pages: '26–32',
        readings: [
          {
            title: 'Medical Technology Engineering',
            paragraphs: [
              'A. As a result of the substantial scientific and technological development that affected many disciplines, many branches have appeared within the specialisation of engineering in particular, including medical technology engineering, which is also called biomedical engineering. This field is concerned with studying the body from an engineering point of view, in order to design suitable artificial limbs, organs, or other medical devices.',
              'B. Medical technology engineering helps doctors define their tasks and facilitates their work more, so the medical device has become an essential assistant for the doctors in all steps, starting from diagnosis, to the end of the treatment course. The need for development in this field has made designing medical devices a great priority, and this in turn led to the intervention of electrical, mechanical computer engineers and others, whose knowledge does not depend on their specialties only, but rather, they must be familiar with all aspects of human body, from biology, anatomy and physiology. So that the medical devices designed are useful for the human body.',
              'C. Medical devices can be divided into two parts, diagnostic medical devices, most notably the ultrasound device, and medical therapeutic devices used in chemical treatments. Another classification includes three categories. Firstly, we have simple devices such as bandages, body temperature meters and others. There are also more complex devices that require a certain amount of caution, such as those that emit X-rays. Finally, there are those which require a deep study before their use, such as the valves used in the artificial heart, in addition to the artificial joints.',
              'D. Medical engineers work in many fields like well-equipped hospitals and clinics in particular, medical companies and the advanced major research centers in universities. In the end, medical engineers work in cooperation with all disciplines, including nursing, medicine, biology, and other disciplines.',
              'E. In short, it is certain that this new branch of engineering has improved healthcare to a great extent. Furthermore, the design process is better as a result of new technology with 3D printing being the most favoured new tool. Nowadays biomedical engineers are able to develop new procedures using knowledge from many technical sources; or conduct research needed to solve clinical problems.',
            ],
            paragraphsAr: [
              'A. نتيجةً للتطوّر العلمي والتكنولوجي الكبير الذي أثّر في تخصّصات كثيرة، ظهرت فروع عديدة ضمن اختصاص الهندسة بشكل خاص، ومنها هندسة التكنولوجيا الطبية، التي تُسمّى أيضاً الهندسة الطبية الحيوية. ويهتمّ هذا المجال بدراسة الجسم من وجهة نظر هندسية، من أجل تصميم أطراف وأعضاء صناعية مناسبة أو أجهزة طبية أخرى.',
              'B. تساعد هندسة التكنولوجيا الطبية الأطباء على تحديد مهامّهم وتسهّل عملهم أكثر، ولذلك أصبح الجهاز الطبي مساعداً أساسياً للأطباء في جميع المراحل، بدءاً من التشخيص وحتى نهاية مسار العلاج. وقد جعلت الحاجة إلى التطوير في هذا المجال تصميمَ الأجهزة الطبية أولوية كبرى، وأدّى هذا بدوره إلى تدخّل مهندسي الكهرباء والميكانيك والحاسوب وغيرهم، الذين لا تقتصر معرفتهم على اختصاصاتهم فقط، بل يجب أن يكونوا مُلمّين بجميع جوانب جسم الإنسان، من علم الأحياء والتشريح ووظائف الأعضاء، لكي تكون الأجهزة الطبية المصمَّمة مفيدة لجسم الإنسان.',
              'C. يمكن تقسيم الأجهزة الطبية إلى قسمين: الأجهزة الطبية التشخيصية، وأبرزها جهاز التصوير بالأمواج فوق الصوتية، والأجهزة الطبية العلاجية المستخدمة في العلاجات الكيميائية. وهناك تصنيف آخر يضمّ ثلاث فئات: أولاً، لدينا الأجهزة البسيطة مثل الضمادات وموازين حرارة الجسم وغيرها. وهناك أيضاً أجهزة أكثر تعقيداً تتطلّب قدراً معيّناً من الحذر، مثل تلك التي تُصدر الأشعة السينية. وأخيراً، هناك الأجهزة التي تتطلّب دراسة عميقة قبل استخدامها، مثل الصمّامات المستخدمة في القلب الاصطناعي، إضافة إلى المفاصل الاصطناعية.',
              'D. يعمل المهندسون الطبيون في مجالات كثيرة، مثل المستشفيات والعيادات المجهّزة جيداً بشكل خاص، والشركات الطبية، ومراكز البحث الكبرى المتقدّمة في الجامعات. وفي النهاية، يعمل المهندسون الطبيون بالتعاون مع جميع التخصّصات، ومنها التمريض والطب وعلم الأحياء وغيرها من التخصّصات.',
              'E. باختصار، من المؤكّد أن هذا الفرع الجديد من الهندسة قد حسّن الرعاية الصحية إلى حدّ كبير. علاوة على ذلك، أصبحت عملية التصميم أفضل نتيجة التكنولوجيا الجديدة، والطباعة ثلاثية الأبعاد هي الأداة الجديدة الأكثر تفضيلاً. وفي هذه الأيام أصبح مهندسو الطب الحيوي قادرين على تطوير إجراءات جديدة باستخدام معارف من مصادر تقنية كثيرة، أو إجراء الأبحاث اللازمة لحلّ المشكلات السريرية.',
            ],
            questions: [
              {
                q: 'What does medical engineering mean?',
                qAr: 'ماذا تعني الهندسة الطبية؟',
                options: [
                  'A field that trains doctors to repair hospital buildings.',
                  'A field that studies the body from an engineering point of view in order to design artificial limbs, organs or other medical devices.',
                  'A field that treats illnesses with herbs and natural remedies.',
                  'A field that studies animals from a medical point of view.',
                ],
                answer: 1,
                explainAr: 'الفقرة A: This field is concerned with studying the body from an engineering point of view, in order to design suitable artificial limbs, organs, or other medical devices.',
              },
              {
                q: 'How is medical engineering useful for doctors?',
                qAr: 'كيف تفيد الهندسة الطبية الأطباء؟',
                options: [
                  'It does the doctors\' work instead of them.',
                  'It makes the treatment course longer.',
                  'It helps doctors define their tasks and facilitates their work in all steps, from diagnosis to the end of the treatment course.',
                  'It helps doctors only in writing reports.',
                ],
                answer: 2,
                explainAr: 'الفقرة B: helps doctors define their tasks and facilitates their work ... an essential assistant for the doctors in all steps, starting from diagnosis, to the end of the treatment course.',
              },
              {
                q: 'Name the parts of medical devices.',
                qAr: 'سمِّ قسمَي الأجهزة الطبية.',
                options: [
                  'Diagnostic medical devices and medical therapeutic devices.',
                  'Electrical devices and mechanical devices.',
                  'Mobile phones and computers.',
                  'Bandages and artificial hearts.',
                ],
                answer: 0,
                explainAr: 'الفقرة C: Medical devices can be divided into two parts, diagnostic medical devices ... and medical therapeutic devices.',
              },
              {
                q: 'What kind of devices need more caution?',
                qAr: 'ما نوع الأجهزة التي تحتاج إلى حذر أكبر؟',
                options: [
                  'Simple devices such as bandages.',
                  'Body temperature meters.',
                  'Devices used by nurses only.',
                  'More complex devices, such as those that emit X-rays.',
                ],
                answer: 3,
                explainAr: 'الفقرة C: more complex devices that require a certain amount of caution, such as those that emit X-rays.',
              },
              {
                q: 'What fields can medical engineering contribute to?',
                qAr: 'في أيّ مجالات يمكن أن تسهم الهندسة الطبية؟',
                options: [
                  'Only car factories and building sites.',
                  'Hospitals and clinics, medical companies and research centres, working with nursing, medicine and biology.',
                  'Only schools and banks.',
                  'Farming and fishing.',
                ],
                answer: 1,
                explainAr: 'الفقرة D: hospitals and clinics ... medical companies and the advanced major research centers ... in cooperation with all disciplines, including nursing, medicine, biology.',
              },
              {
                q: 'Mention three advantages of medical engineering.',
                qAr: 'اذكر ثلاث مزايا للهندسة الطبية.',
                options: [
                  'It has made hospitals more expensive, slower and more dangerous.',
                  'It has replaced nurses, doctors and patients.',
                  'It has improved healthcare, made the design process better with 3D printing, and helps solve clinical problems.',
                  'It has stopped research in universities.',
                ],
                answer: 2,
                explainAr: 'الفقرة E: has improved healthcare to a great extent ... the design process is better ... 3D printing ... conduct research needed to solve clinical problems.',
              },
            ],
            trueFalse: [
              { statement: 'Medical technology engineering is also called biomedical engineering.', answer: true },
              { statement: 'Engineers who design medical devices only need to know about their own specialties.', answer: false },
              { statement: 'Bandages and body temperature meters are examples of simple devices.', answer: true },
              { statement: 'Medical engineers work only in hospitals.', answer: false },
              { statement: '3D printing is the most favoured new tool in the design process.', answer: true },
            ],
          },
        ],
        exercises: u4Exercises,
      },
      compositions: [
        {
          source: 'book',
          topic: 'Engineering has played a vital part in people\'s lives today. It has become a must for improving our life. Write an article about the role of engineering in the modern world.',
          topicAr: 'لقد أدّت الهندسة دوراً حيوياً في حياة الناس اليوم، وأصبحت ضرورة لتحسين حياتنا. اكتب مقالة عن دور الهندسة في العالم الحديث.',
          words: 100,
          points: ['advantages of engineering', 'public health and safety', 'technology and quality of life'],
          pointsAr: ['فوائد الهندسة', 'الصحة العامة والسلامة', 'التكنولوجيا وجودة الحياة'],
          plan: [
            { en: 'Topic sentence: engineering plays a vital part in our lives today.', ar: 'الجملة الافتتاحية: الهندسة تؤدي دوراً حيوياً في حياتنا اليوم.' },
            { en: 'Advantages of engineering: machines, roads, bridges and buildings make work faster and easier.', ar: 'فوائد الهندسة: الآلات والطرق والجسور والمباني تجعل العمل أسرع وأسهل.' },
            { en: 'Public health and safety: clean water, dams, medical devices.', ar: 'الصحة العامة والسلامة: الماء النظيف والسدود والأجهزة الطبية.' },
            { en: 'Technology and quality of life: computers, the Internet, search engines.', ar: 'التكنولوجيا وجودة الحياة: الحواسيب والإنترنت ومحركات البحث.' },
            { en: 'Conclusion: engineering has become a must; give your opinion or a recommendation.', ar: 'الخاتمة: أصبحت الهندسة ضرورة؛ أبدِ رأيك أو قدّم توصية.' },
          ],
          phrases: [
            { en: 'play a vital part in', ar: 'يؤدي دوراً حيوياً في' },
            { en: 'essential', ar: 'ضروري / أساسي' },
            { en: 'machinery / device', ar: 'الآلات / جهاز' },
            { en: 'give rise to', ar: 'يؤدي إلى' },
            { en: 'mass production', ar: 'الإنتاج الضخم' },
            { en: 'maintenance', ar: 'صيانة' },
            { en: 'search engine', ar: 'محرك بحث' },
            { en: 'elevate our quality of life', ar: 'يرتقي بجودة حياتنا' },
            { en: 'dams are built / water is brought (passive)', ar: 'تُبنى السدود / يُجلب الماء (مبني للمجهول)' },
            { en: 'First of all, ... / Furthermore, ... / In conclusion, ...', ar: 'أولاً ... / علاوة على ذلك ... / في الختام ...' },
          ],
          model: 'Engineering has played a vital part in people\'s lives today. First of all, engineers design the machines, roads, bridges and buildings we use every day, so our work is done faster and more easily. Engineering also protects public health and safety. Clean water is brought to our homes, dams are built to control floods, and modern medical devices help doctors diagnose and treat patients. Furthermore, technology has elevated our quality of life. Thanks to computer engineers, we can communicate with people all over the world, and search engines give us information in seconds. In conclusion, engineering has become essential for improving our life, and young people should be encouraged to study it.',
          modelAr: 'أدّت الهندسة دوراً حيوياً في حياة الناس اليوم. أولاً، يصمّم المهندسون الآلات والطرق والجسور والمباني التي نستخدمها كل يوم، فيُنجَز عملنا بسرعة وسهولة أكبر. وتحمي الهندسة أيضاً الصحة العامة والسلامة؛ فالماء النظيف يُجلب إلى بيوتنا، والسدود تُبنى للسيطرة على الفيضانات، والأجهزة الطبية الحديثة تساعد الأطباء على تشخيص المرضى وعلاجهم. علاوة على ذلك، ارتقت التكنولوجيا بجودة حياتنا؛ فبفضل مهندسي الحاسوب نستطيع التواصل مع الناس في كل أنحاء العالم، وتعطينا محركات البحث المعلومات في ثوانٍ. في الختام، أصبحت الهندسة ضرورية لتحسين حياتنا، ويجب تشجيع الشباب على دراستها.',
          checklistAr: [
            'هل بدأت بجملة افتتاحية واضحة عن دور الهندسة اليوم؟',
            'هل غطّيت الأفكار الثلاث: فوائد الهندسة، الصحة العامة والسلامة، التكنولوجيا وجودة الحياة؟',
            'هل استخدمت كلمات الوحدة (essential, machinery, search engine, elevate)؟',
            'هل ربطت الأفكار بأدوات ربط مثل First of all و Furthermore و In conclusion؟',
            'هل استخدمت المبني للمجهول بشكل صحيح (is brought, are built)؟',
            'هل راجعت الإملاء وعلامات الترقيم والقواعد؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'In no more than 120 words, write a description of a recent engineering project.',
          topicAr: 'في ما لا يزيد على 120 كلمة، اكتب وصفاً لمشروع هندسي حديث.',
          words: 120,
          points: ['name the project', 'place and time of performance', 'advantages and disadvantages', 'opinion'],
          pointsAr: ['اذكر اسم المشروع', 'مكان التنفيذ وزمانه', 'المزايا والسلبيات', 'رأيك'],
          plan: [
            { en: 'Introduction: name the project and say what kind of project it is.', ar: 'المقدّمة: سمِّ المشروع واذكر نوعه.' },
            { en: 'Place and time: where and when it was carried out (past passive).', ar: 'المكان والزمان: أين ومتى نُفّذ (الماضي المبني للمجهول).' },
            { en: 'Advantages: what it gives people and the country.', ar: 'المزايا: ماذا يقدّم للناس وللبلد.' },
            { en: 'Disadvantages: cost, environment or other problems.', ar: 'السلبيات: التكلفة أو البيئة أو مشكلات أخرى.' },
            { en: 'Conclusion: your opinion of the project.', ar: 'الخاتمة: رأيك في المشروع.' },
          ],
          phrases: [
            { en: 'engineering project', ar: 'مشروع هندسي' },
            { en: 'it was carried out in ... / it was opened in ...', ar: 'نُفّذ في ... / افتُتح في ... (مبني للمجهول)' },
            { en: 'engineers and workers', ar: 'مهندسون وعمّال' },
            { en: 'essential / vital', ar: 'أساسي / حيوي' },
            { en: 'The main advantage is that ...', ar: 'الميزة الأساسية هي أن ...' },
            { en: 'However, ...', ar: 'لكن، ...' },
            { en: 'risky', ar: 'محفوف بالمخاطر' },
            { en: 'brilliant', ar: 'رائع / لامع' },
            { en: 'opportunity', ar: 'فرصة' },
            { en: 'In my opinion, ...', ar: 'برأيي، ...' },
          ],
          model: 'The New Suez Canal is one of the most impressive engineering projects of recent years. It was carried out in Egypt, next to the old Suez Canal, and it was opened in August 2015 after about one year of work. Thousands of engineers and workers dug a new channel and made parts of the old canal deeper and wider. The main advantage is that ships can now sail in both directions at the same time, so they wait less and Egypt earns more money. However, the project cost billions of dollars, and some scientists worry that it could harm sea life. In my opinion, it is a brilliant project which shows how engineering can change a country\'s economy.',
          modelAr: 'قناة السويس الجديدة من أكثر المشاريع الهندسية إثارة للإعجاب في السنوات الأخيرة. نُفّذ المشروع في مصر بجانب قناة السويس القديمة، وافتُتح في آب 2015 بعد نحو عام واحد من العمل. حفر آلاف المهندسين والعمّال مجرى جديداً وجعلوا أجزاء من القناة القديمة أعمق وأعرض. والميزة الأساسية أن السفن تستطيع الآن الإبحار في الاتجاهين في الوقت نفسه، فتنتظر وقتاً أقل وتكسب مصر مالاً أكثر. لكن المشروع كلّف مليارات الدولارات، ويخشى بعض العلماء أن يضرّ بالحياة البحرية. برأيي، إنه مشروع رائع يبيّن كيف يمكن للهندسة أن تغيّر اقتصاد بلد.',
          checklistAr: [
            'هل ذكرت اسم المشروع ونوعه في المقدّمة؟',
            'هل ذكرت مكان التنفيذ وزمانه مستخدماً الماضي (was carried out, was opened)؟',
            'هل ذكرت المزايا والسلبيات معاً وربطتها بـ However؟',
            'هل ختمت برأيك الشخصي؟',
            'هل كتبت فقرة مترابطة لا تتجاوز 120 كلمة؟',
            'هل راجعت علامات الترقيم والإملاء والأخطاء النحوية؟',
          ],
        },
      ],
      translations: [
        { en: 'Firstly, we have simple devices such as bandages, body temperature meters and others.', ar: 'أولاً، لدينا الأجهزة البسيطة مثل الضمادات وموازين حرارة الجسم وغيرها.' },
        { en: 'The engineer has to check over the joints before leaving the site.', ar: 'على المهندس أن يفحص المفاصل بدقّة قبل مغادرة الموقع.' },
        { en: 'Houses by the sea are usually eaten away faster because of moisture.', ar: 'البيوت القريبة من البحر تتآكل عادةً بشكل أسرع بسبب الرطوبة.' },
        { en: 'My neighbour asked me over for dinner.', ar: 'دعاني جاري إلى العشاء في بيته.' },
        { en: 'My best friend let me borrow his car.', ar: 'سمح لي أعزّ أصدقائي باستعارة سيارته.' },
        { en: 'They went fishing on a boat.', ar: 'ذهبوا لصيد السمك في قارب.' },
        { en: 'Can you lend me some money?', ar: 'هل يمكنك أن تُقرضني بعض المال؟' },
        { en: 'I don\'t know when it is the best time to call you.', ar: 'لا أعرف متى يكون أفضل وقت للاتصال بك.' },
        { en: 'Tareq\'s windows were dirty, but he didn\'t have time to clean them himself.', ar: 'كانت نوافذ طارق متّسخة، لكن لم يكن لديه وقت لتنظيفها بنفسه.' },
        { en: 'Yesterday, the optician checked my mother\'s eyes.', ar: 'البارحة فحص طبيب البصريات عيني أمي.' },
        { en: 'A carpenter is going to mend the front door of our house.', ar: 'سيُصلح نجّار الباب الأمامي لبيتنا.' },
        { en: 'The hairdresser cuts Rana\'s hair about twice a year.', ar: 'تقصّ مصفّفة الشعر شعر رنا مرتين تقريباً في السنة.' },
        { en: 'We\'ll have to pull the old building down before they start work.', ar: 'سيكون علينا هدم المبنى القديم قبل أن يبدؤوا العمل.' },
        { en: 'We need to shore up the roof before it falls down.', ar: 'نحتاج إلى تدعيم السقف قبل أن ينهار.' },
        { en: 'I have to jack up the car to change the tire.', ar: 'عليّ أن أرفع السيارة بالرافعة لأغيّر الإطار.' },
        { en: 'My father had the car mended.', ar: 'أصلح أبي السيارة (عند ميكانيكي، لا بنفسه).' },
        { en: 'Huda had her bag pulled off her shoulder.', ar: 'انتُزعت حقيبة هدى عن كتفها.' },
      ],
    },
  },
}
