import type { GrammarExercise } from '../../../engine/types'
import type { ModuleExtras } from './merge'

// Module 1 "Learning for Life" — Activity Book pages 2–15 (Unit 1: 2–8, Unit 2: 9–15). No Progress Test.

const fill = (prompt: string, promptAr: string, promptArFull: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'fill', prompt, promptAr, promptArFull, options, answer, explainAr })
const mcq = (prompt: string, promptAr: string, options: string[], answer: number, explainAr: string): GrammarExercise =>
  ({ type: 'mcq', prompt, promptAr, options, answer, explainAr })

// ---------- Unit 1, Activity Book page 3a: match the words to their meanings ----------
const u1Meanings = [
  'not serious, important or valuable',
  "too much pride in one's self",
  'allowing people to do, say, or believe what they want',
  'jealousy or desire for something which belongs to another person',
  'modesty',
  'a mark that something has been in a place',
]
/** A matching item: the right meaning and three others, in alphabetical order so the answer does not always sit first. */
function matchItem(word: string, meanings: string[], right: number, others: number[], explainAr: string): GrammarExercise {
  const options = [right, ...others].map(i => meanings[i]).sort()
  return mcq(`Match the word to its meaning: "${word}"`, `ما معنى كلمة "${word}"؟`, options, options.indexOf(meanings[right]), explainAr)
}

// ---------- Unit 1, page 8a: the paragraphs of the personal experience ----------
const u1Details = [
  'For me, it was a day in tenth grade when I had a math test. / That day taught me listen to my teacher and prepare properly.',
  'The teacher had told us to prepare carefully for it. / But I hadn’t studied at all for the test.',
  'However, the test was awful, and I could not understand anything. / Later, when I got my score and saw 5%, I was angry with myself.',
  'I shouldn’t have thought I could pass a test without studying. / From that day on, I decided to study harder.',
]
const u1Topics = [
  'Have you ever had a day you wished never happened?',
  'Actually, I had known we had an important test to get ready for.',
  'When the test day came, I was confident I would do well.',
  'To tell the truth, I don’t think I have ever felt that bad.',
]

// ---------- Unit 2, page 13a: the conversation in its correct order ----------
const u2Lines: [string, string][] = [
  ['A: I haven’t told you what happened yet, have I?', 'أ: لم أخبرك بما حدث بعد، أليس كذلك؟'],
  ['B: I haven’t heard anything.', 'ب: لم أسمع شيئاً.'],
  ['A: My boss offered me a promotion, and I took it.', 'أ: عرض عليّ مديري ترقية، فقبلتها.'],
  ['B: Are you serious?', 'ب: هل أنت جادّ؟'],
  ['A: Yes, I’m really excited.', 'أ: نعم، أنا متحمّس جداً.'],
  ['B: That’s great! Congratulations.', 'ب: هذا رائع! تهانينا.'],
  ['A: I appreciate that.', 'أ: أقدّر ذلك.'],
  ['B: You have no idea how happy I am for you.', 'ب: لا تتخيّل كم أنا سعيد من أجلك.'],
  ['A: For real?', 'أ: حقاً؟'],
  ['B: I believe you really deserve it. I really do.', 'ب: أعتقد أنك تستحقّها فعلاً. حقاً.'],
]
const u2Why = [
  '',
  'بعد أن يقول A إنه لم يخبره بما حدث، يردّ B بأنه لم يسمع شيئاً.',
  'الآن يخبره A بالخبر: حصل على ترقية.',
  'يعبّر B عن دهشته من الخبر: Are you serious?',
  'يؤكّد A الخبر ويعبّر عن حماسه.',
  'يهنّئه B: That’s great! Congratulations.',
  'يشكره A على التهنئة: I appreciate that.',
  'يؤكّد B فرحه له: You have no idea how happy I am for you.',
  'يتفاجأ A بهذا الفرح: For real?',
  'يختم B بأنه يستحقّ الترقية فعلاً: I believe you really deserve it.',
]
function u2Order(): GrammarExercise[] {
  return u2Lines.slice(1).map((line, k) => {
    const n = k + 1
    const others = [n + 1, n + 2, n + 3].map(i => (i < u2Lines.length ? i : i - 8)).filter(i => i !== n && i > 0)
    const options = [n, ...others].slice(0, 4).map(i => u2Lines[i][0]).sort()
    return mcq(`Put the conversation in order. Which line comes after "${u2Lines[n - 1][0]}"?`,
      `رتّب المحادثة: أيّ سطر يأتي بعد «${u2Lines[n - 1][1]}»؟`,
      options, options.indexOf(line[0]), `${u2Why[n]} (${line[1]})`)
  })
}

export const extras: ModuleExtras = {
  units: {
    // ===================== UNIT 1 — Life Choices (Activity Book pages 2–8) =====================
    u1: {
      workbook: {
        pages: '2–8',
        readings: [
          {
            title: 'A Learned Lesson is a Good Lesson',
            paragraphs: [
              'Our life is a short journey, and every day we learn many important lessons that we must benefit from in order to be able to achieve more successes, and to make life beautiful and prosperous.',
              'Most people think that education is limited to schools only, but the truth is that there are lessons that we can only learn from life, and they may be more important than those learnt at schools. Life lessons are sometimes painful before they are acquired, and in order to avoid this, we must benefit from the experiences of others.',
              'We shouldn\'t pay too much attention to the trivial things that are not important and waste our time and effort. Since life is so unpredictable, we must not live on expectations only and meet everything new in life with optimism and positive thinking. There is no word more boring and monotonous than the word "I". We must be confident of ourselves, but that does not mean we talk about ourselves and our accomplishments all the time, as this leads to vanity. Human relationships are also important because without love and support from family and friends, you would not feel happy and would not achieve success in life.',
              'Man by nature makes mistakes, so be tolerant and seek excuses for those around you, and if someone comes to you with an apology, do not stop him, and do not carry in your heart any envy of anyone. Take care of your health and make it a priority for your entire life. There are no alternatives to exercising, eating well, fresh air and sunshine.',
              'The pursuit of success will make you succeed in the end, no matter how long the period is, but keep trying. Failure is a great teacher in life. It teaches us humility and how to correct our course of life. A great example is Thomas Edison. He failed many times, but he did not give up until he succeeded. Even when he failed, Edison learned something. ‘I get results in everything I try,’ he said.',
              'The golden rule for everybody is to be honest, trustful, useful and generous so that they leave life with a trace that those around them will not forget about.',
            ],
            paragraphsAr: [
              'حياتنا رحلة قصيرة، وفي كل يوم نتعلّم دروساً مهمة كثيرة يجب أن نستفيد منها لكي نتمكّن من تحقيق مزيد من النجاحات، ولنجعل الحياة جميلة ومزدهرة.',
              'يظنّ معظم الناس أن التعليم يقتصر على المدارس فقط، لكن الحقيقة أن هناك دروساً لا نتعلّمها إلا من الحياة، وقد تكون أهمّ من تلك التي نتعلّمها في المدارس. دروس الحياة مؤلمة أحياناً قبل أن نكتسبها، ولكي نتجنّب ذلك يجب أن نستفيد من تجارب الآخرين.',
              'لا ينبغي أن نُولي اهتماماً كبيراً للأشياء التافهة التي ليست مهمة وتُضيّع وقتنا وجهدنا. وبما أن الحياة لا يمكن التنبّؤ بها، يجب ألّا نعيش على التوقّعات فقط، وأن نستقبل كل جديد في الحياة بالتفاؤل والتفكير الإيجابي. لا توجد كلمة أكثر مللاً ورتابة من كلمة «أنا». يجب أن نكون واثقين بأنفسنا، لكن هذا لا يعني أن نتحدّث عن أنفسنا وعن إنجازاتنا طوال الوقت، لأن هذا يؤدّي إلى الغرور. والعلاقات الإنسانية مهمة أيضاً، لأنك من دون حبّ الأسرة والأصدقاء ودعمهم لن تشعر بالسعادة ولن تحقّق النجاح في الحياة.',
              'الإنسان بطبيعته يخطئ، فكن متسامحاً والتمس الأعذار لمن حولك، وإذا جاءك أحد معتذراً فلا تردّه، ولا تحمل في قلبك حسداً لأحد. اعتنِ بصحتك واجعلها أولوية طوال حياتك. لا بدائل عن ممارسة الرياضة والأكل الجيد والهواء النقي وأشعة الشمس.',
              'السعي إلى النجاح سيجعلك تنجح في النهاية مهما طالت المدة، فاستمرّ في المحاولة. الفشل معلّم عظيم في الحياة؛ فهو يعلّمنا التواضع وكيف نصحّح مسار حياتنا. ومن الأمثلة الرائعة توماس إديسون؛ فقد فشل مرات كثيرة، لكنه لم يستسلم حتى نجح. وحتى عندما كان يفشل، كان إديسون يتعلّم شيئاً. قال: «أحصل على نتائج في كل شيء أجرّبه».',
              'القاعدة الذهبية للجميع أن يكونوا صادقين وجديرين بالثقة ونافعين وكرماء، حتى يغادروا الحياة تاركين أثراً لا ينساه من حولهم.',
            ],
            questions: [
              {
                q: "How can people avoid life's painful lessons?", qAr: 'كيف يستطيع الناس تجنّب دروس الحياة المؤلمة؟',
                options: ['By benefiting from the experiences of others.', 'By staying at school for a longer time.', 'By living on expectations only.', 'By talking about their accomplishments.'],
                answer: 0, explainAr: 'يقول النص: "in order to avoid this, we must benefit from the experiences of others" أي نستفيد من تجارب الآخرين.',
              },
              {
                q: "Why shouldn't people live on expectations only?", qAr: 'لماذا لا ينبغي أن يعيش الناس على التوقّعات فقط؟',
                options: ['Because expectations are trivial things.', 'Because life is so unpredictable.', 'Because expectations lead to vanity.', 'Because schools do not teach them.'],
                answer: 1, explainAr: 'يقول النص: "Since life is so unpredictable, we must not live on expectations only" أي لأن الحياة لا يمكن التنبّؤ بها.',
              },
              {
                q: 'Why shouldn’t someone use the word "I"?', qAr: 'لماذا لا ينبغي أن يُكثر الشخص من استخدام كلمة «أنا»؟',
                options: ['Because it shows that he is not confident.', 'Because it is boring and talking about ourselves all the time leads to vanity.', 'Because it makes other people envious.', 'Because it is a difficult word to say.'],
                answer: 1, explainAr: 'النص يقول إنه لا توجد كلمة أكثر مللاً ورتابة من «أنا»، وإن الحديث عن أنفسنا وإنجازاتنا طوال الوقت يؤدّي إلى الغرور (vanity).',
              },
              {
                q: 'Why should we be tolerant of others?', qAr: 'لماذا يجب أن نكون متسامحين مع الآخرين؟',
                options: ['Because they are always right.', 'Because man by nature makes mistakes.', 'Because they will give us money.', 'Because health is a priority.'],
                answer: 1, explainAr: 'يقول النص: "Man by nature makes mistakes, so be tolerant" أي الإنسان يخطئ بطبيعته فكن متسامحاً.',
              },
              {
                q: 'How did Edison deal with failure during his life?', qAr: 'كيف تعامل إديسون مع الفشل في حياته؟',
                options: ['He gave up after his first failure.', 'He blamed the people around him.', 'He kept trying, learned something from every failure and did not give up until he succeeded.', 'He stopped inventing and became a teacher.'],
                answer: 2, explainAr: 'يقول النص إن إديسون فشل مرات كثيرة لكنه لم يستسلم حتى نجح، وكان يتعلّم شيئاً حتى عندما يفشل.',
              },
              {
                q: 'How can a person leave a memorable trace?', qAr: 'كيف يستطيع الإنسان أن يترك أثراً لا يُنسى؟',
                options: ['By being honest, trustful, useful and generous.', 'By becoming rich and famous.', 'By talking about his accomplishments.', 'By avoiding other people.'],
                answer: 0, explainAr: 'القاعدة الذهبية في الفقرة الأخيرة: أن تكون صادقاً وجديراً بالثقة ونافعاً وكريماً حتى تترك أثراً لا ينساه من حولك.',
              },
            ],
            trueFalse: [
              { statement: 'The best life lessons can only be learnt at schools.', answer: false },
              { statement: 'Silly things are important and teach us great lessons.', answer: false },
              { statement: 'Being optimistic and positive leads to vanity.', answer: false },
              { statement: 'Family plays an essential role in someone’s success.', answer: true },
              { statement: 'Taking care of our health increases our chance to achieve success.', answer: true },
            ],
          },
        ],
        exercises: [
          // ---- page 3a: match the words to their meanings ----
          matchItem('trivial', u1Meanings, 0, [1, 4, 5], 'trivial = تافه: شيء غير جادّ أو مهم أو ذي قيمة، كما في النص: "the trivial things that are not important".'),
          matchItem('vanity', u1Meanings, 1, [0, 4, 3], 'vanity = الغرور: الإفراط في الإعجاب بالنفس، والنص يقول إن الحديث عن إنجازاتنا طوال الوقت يؤدّي إليه.'),
          matchItem('tolerant', u1Meanings, 2, [1, 3, 5], 'tolerant = متسامح: يسمح للناس أن يفعلوا أو يقولوا أو يعتقدوا ما يريدون.'),
          matchItem('envy', u1Meanings, 3, [1, 4, 0], 'envy = الحسد: الغيرة أو الرغبة في شيء يملكه شخص آخر.'),
          matchItem('humility', u1Meanings, 4, [1, 2, 5], 'humility = التواضع (modesty)، وهو عكس الغرور vanity.'),
          matchItem('trace', u1Meanings, 5, [0, 3, 4], 'trace = أثر: علامة تدلّ على أن شيئاً كان في مكان ما، كما في: "leave life with a trace".'),

          // ---- page 4a: choose the correct word (word family) ----
          fill('We need to ___ people so that they understand the importance of a good and a healthy diet.',
            'نحن بحاجة إلى ___ الناس لكي يفهموا أهمية النظام الغذائي الجيد والصحي.',
            'نحن بحاجة إلى تثقيف الناس لكي يفهموا أهمية النظام الغذائي الجيد والصحي.',
            ['education', 'educate', 'educational'], 1,
            'بعد need to نحتاج فعلاً في صيغة المصدر: educate (يثقّف). education اسم، وeducational صفة.'),
          fill('She hated to say the words for fear of causing ___ to him.',
            'كرهت أن تقول تلك الكلمات خوفاً من أن تسبّب له ___.',
            'كرهت أن تقول تلك الكلمات خوفاً من أن تسبّب له الألم.',
            ['pain', 'painful', 'painfully'], 0,
            'بعد الفعل causing نحتاج مفعولاً به وهو اسم: pain (ألم). painful صفة وpainfully ظرف.'),
          fill('The situation is so uncertain that it is hard to make a confident ___.',
            'الوضع غير مؤكّد إلى درجة أنه من الصعب تقديم ___ واثق.',
            'الوضع غير مؤكّد إلى درجة أنه من الصعب تقديم توقّع واثق.',
            ['predictable', 'prediction', 'predict'], 1,
            'بعد أداة النكرة a والصفة confident نحتاج اسماً: prediction (توقّع). predictable صفة وpredict فعل.'),
          fill('The airline company ___ to passengers for the delay.',
            'شركة الطيران ___ للمسافرين بسبب التأخير.',
            'شركة الطيران اعتذرت للمسافرين بسبب التأخير.',
            ['apologised', 'apology', 'apologetic'], 0,
            'الجملة تحتاج فعلاً بعد الفاعل The airline company: apologised (اعتذرت). apology اسم وapologetic صفة.'),
          fill('In recent years, Syria has undergone a lot of economic ___.',
            'في السنوات الأخيرة، شهدت سوريا كثيراً من ___ الاقتصادي.',
            'في السنوات الأخيرة، شهدت سوريا كثيراً من الازدهار الاقتصادي.',
            ['prosperity', 'prosperous', 'prosper'], 0,
            'بعد a lot of والصفة economic نحتاج اسماً: prosperity (ازدهار). prosperous صفة وprosper فعل.'),
          fill('Many old people have more ___ than others when dealing with the young generation.',
            'كثير من كبار السن لديهم ___ أكثر من غيرهم عند التعامل مع جيل الشباب.',
            'كثير من كبار السن لديهم تسامح أكثر من غيرهم عند التعامل مع جيل الشباب.',
            ['tolerant', 'tolerance', 'tolerate'], 1,
            'بعد have more نحتاج اسماً مفعولاً به: tolerance (تسامح). tolerant صفة وtolerate فعل.'),

          // ---- page 4b: phrasal verbs in the correct form ----
          fill('I can always ___ you if you feel tired with your school work.',
            'أستطيع دائماً أن ___ إذا شعرت بالتعب من واجباتك المدرسية.',
            'أستطيع دائماً أن أمدّ لك يد العون إذا شعرت بالتعب من واجباتك المدرسية.',
            ['reach out to', 'fit in', 'run into', 'keep up with'], 0,
            'reach out to = يمدّ يد العون إلى شخص. بعد can يأتي الفعل في صيغة المصدر.'),
          fill('When I travelled to Spain, I tried hard to ___ with the locals.',
            'عندما سافرت إلى إسبانيا، حاولت جاهداً أن ___ مع السكان المحليين.',
            'عندما سافرت إلى إسبانيا، حاولت جاهداً أن أندمج مع السكان المحليين.',
            ['get into', 'fit in', 'follow through', 'reach out to'], 1,
            'fit in (with) = يندمج ويتأقلم مع مجموعة من الناس. بعد tried to يأتي المصدر.'),
          fill('The group had one successful song but failed to ___ with another hit record.',
            'حقّقت الفرقة أغنية ناجحة واحدة لكنها فشلت في ___ بأغنية ناجحة أخرى.',
            'حقّقت الفرقة أغنية ناجحة واحدة لكنها فشلت في المتابعة حتى النهاية بأغنية ناجحة أخرى.',
            ['run into', 'fit in', 'get into', 'follow through'], 3,
            'follow through (with) = يتابع العمل حتى يكمله. الفرقة لم تستطع إكمال نجاحها بأغنية أخرى.'),
          fill('Nowadays, students can ___ the latest news by using the Internet.',
            'في الوقت الحاضر، يستطيع الطلاب ___ آخر الأخبار باستخدام الإنترنت.',
            'في الوقت الحاضر، يستطيع الطلاب مواكبة آخر الأخبار باستخدام الإنترنت.',
            ['keep up with', 'run into', 'get into', 'fit in'], 0,
            'keep up with = يواكب ويبقى على اطّلاع بـ. نقول keep up with the latest news.'),
          fill('She has been ___ yoga recently.',
            'لقد ___ اليوغا مؤخراً.',
            'لقد بدأت تهتمّ باليوغا مؤخراً.',
            ['getting into', 'get into', 'got into', 'running into'], 0,
            'get into = يبدأ الاهتمام بشيء. بعد has been (المضارع التام المستمر) يأتي الفعل مع ing: getting into.'),
          fill('Our company has ___ financial difficulties this month.',
            'شركتنا ___ صعوبات مالية هذا الشهر.',
            'شركتنا واجهت صعوبات مالية هذا الشهر.',
            ['run into', 'ran into', 'running into', 'fit in'], 0,
            'run into = يواجه (مشكلة) فجأة. بعد has نستخدم التصريف الثالث، وتصريف run الثالث هو run نفسه: has run into.'),

          // ---- page 4: pronunciation — homophones ----
          fill('When teaching my daughter how to drive, I told her if she didn’t hit the ___ in time she would ___ the car’s side mirror.',
            'عندما كنت أعلّم ابنتي القيادة، قلت لها إنها إن لم تضغط على ___ في الوقت المناسب فسوف ___ مرآة السيارة الجانبية.',
            'عندما كنت أعلّم ابنتي القيادة، قلت لها إنها إن لم تضغط على المكابح في الوقت المناسب فسوف تكسر مرآة السيارة الجانبية.',
            ['brake … break', 'break … brake', 'brake … brake', 'break … break'], 0,
            'الكلمتان تُلفظان /breɪk/: brake = مكابح السيارة، وbreak = يكسر.'),
          fill('If you ___ rotten food, you will get arrested and end up in a prison ___.',
            'إذا ___ طعاماً فاسداً فسيُقبض عليك وينتهي بك الأمر في ___ السجن.',
            'إذا بعت طعاماً فاسداً فسيُقبض عليك وينتهي بك الأمر في زنزانة السجن.',
            ['cell … sell', 'sell … cell', 'sell … sell', 'cell … cell'], 1,
            'الكلمتان تُلفظان /sel/: sell = يبيع، وcell = زنزانة (a prison cell).'),
          fill('To bake a ___-shaped cake, you’ll need some ___.',
            'لكي تخبز كعكة على شكل ___، ستحتاج إلى بعض ___.',
            'لكي تخبز كعكة على شكل زهرة، ستحتاج إلى بعض الطحين.',
            ['flower … flour', 'flour … flower', 'flour … flour', 'flower … flower'], 0,
            'الكلمتان تُلفظان /ˈflaʊə/: flower = زهرة، وflour = طحين نصنع منه الكعك.'),
          fill('I wanted to sit ___, so I could ___ the singer performing without any distractions.',
            'أردت أن أجلس ___ لكي أستطيع أن ___ المغنّي وهو يغنّي دون أي تشتيت.',
            'أردت أن أجلس هنا لكي أستطيع أن أسمع المغنّي وهو يغنّي دون أي تشتيت.',
            ['hear … here', 'here … hear', 'here … here', 'hear … hear'], 1,
            'الكلمتان تُلفظان /hɪə/: here = هنا (مكان)، وhear = يسمع.'),
          fill('We have one ___ before ___ appointment with the real estate agent.',
            'لدينا ___ واحدة قبل ___ مع الوكيل العقاري.',
            'لدينا ساعة واحدة قبل موعدنا مع الوكيل العقاري.',
            ['our … hour', 'hour … hour', 'hour … our', 'our … our'], 2,
            'الكلمتان تُلفظان /ˈaʊə/ (حرف h في hour صامت): hour = ساعة، وour = ـنا (ضمير ملكية).'),
          fill('The ___ is on his way to the castle, but traveling at ___ is very dangerous.',
            '___ في طريقه إلى القلعة، لكن السفر في ___ خطير جداً.',
            'الفارس في طريقه إلى القلعة، لكن السفر في الليل خطير جداً.',
            ['night … knight', 'knight … night', 'knight … knight', 'night … night'], 1,
            'الكلمتان تُلفظان /naɪt/ (حرف k في knight صامت): knight = فارس، وnight = ليل.'),
          fill('My little brother feels excited every time he ___ a ___ turtle.',
            'يشعر أخي الصغير بالحماس كلما ___ سلحفاة ___.',
            'يشعر أخي الصغير بالحماس كلما رأى سلحفاة بحرية.',
            ['sees … sea', 'seas … see', 'sees … see', 'seas … sea'], 0,
            'sees = يرى (فعل مع he يأخذ s)، وsea turtle = سلحفاة بحرية؛ seas جمع بحر وsee فعل المصدر.'),
          fill('My ___ is 13 years old. He likes to spend time outside in the ___.',
            '___ عمره 13 سنة. يحبّ أن يقضي وقته في الخارج تحت ___.',
            'ابني عمره 13 سنة. يحبّ أن يقضي وقته في الخارج تحت الشمس.',
            ['sun … son', 'son … son', 'son … sun', 'sun … sun'], 2,
            'الكلمتان تُلفظان /sʌn/: son = ابن، وsun = شمس.'),
          fill('I don’t know ___ to bring a jacket or not. The ___ looks unpredictable today.',
            'لا أعرف ___ أحضر سترة أم لا. ___ يبدو متقلّباً اليوم.',
            'لا أعرف إن كان عليّ أن أحضر سترة أم لا. الطقس يبدو متقلّباً اليوم.',
            ['weather … whether', 'whether … weather', 'whether … whether', 'weather … weather'], 1,
            'الكلمتان تُلفظان /ˈweðə/: whether = إذا/فيما إذا (whether … or not)، وweather = الطقس.'),

          // ---- page 5a: Jane's letter — correct the verb forms ----
          fill('We ___ at seven o’clock every morning.',
            'نحن ___ في الساعة السابعة كل صباح.',
            'نحن نستيقظ في الساعة السابعة كل صباح.',
            ['are getting up', 'get up', 'got up'], 1,
            'الصيغة في الرسالة "are getting up" خطأ: every morning تدلّ على عادة متكرّرة، فنستخدم المضارع البسيط get up.'),
          fill('We get up at seven o’clock every morning, and we ___ coffee.',
            'نستيقظ في الساعة السابعة كل صباح، و___ القهوة.',
            'نستيقظ في الساعة السابعة كل صباح، ونشرب القهوة.',
            ['have', 'are having', 'had'], 0,
            'الصيغة "have" صحيحة ✓: عادة يومية، فنستخدم المضارع البسيط.'),
          fill('I ___ the flat at eight and walk to the university.',
            'أنا ___ الشقة في الثامنة وأمشي إلى الجامعة.',
            'أنا أغادر الشقة في الثامنة وأمشي إلى الجامعة.',
            ['am leaving', 'leave', 'left'], 1,
            'الصيغة "leave" صحيحة ✓: روتين يومي، فنستخدم المضارع البسيط مثل walk بعدها.'),
          fill('I ___ classes at five, and I arrive home at six.',
            'أنا ___ الدروس في الخامسة، وأصل إلى البيت في السادسة.',
            'أنا أُنهي الدروس في الخامسة، وأصل إلى البيت في السادسة.',
            ['am finishing', 'finish', 'finished'], 1,
            'الصيغة في الرسالة "am finishing" خطأ: هذا روتين يومي فنستخدم المضارع البسيط finish.'),
          fill('I finish classes at five, and I ___ home at six.',
            'أُنهي الدروس في الخامسة، و___ إلى البيت في السادسة.',
            'أُنهي الدروس في الخامسة، وأصل إلى البيت في السادسة.',
            ['arrive', 'am arriving', 'arrived'], 0,
            'الصيغة "arrive" صحيحة ✓: روتين يومي، فنستخدم المضارع البسيط.'),
          fill('This month I ___ very hard for my first exams.',
            'هذا الشهر ___ بجدّ كبير من أجل امتحاناتي الأولى.',
            'هذا الشهر أعمل بجدّ كبير من أجل امتحاناتي الأولى.',
            ['work', 'am working', 'worked'], 1,
            'الصيغة في الرسالة "work" خطأ: this month تدلّ على وضع مؤقت حول الوقت الحاضر، فنستخدم المضارع المستمر am working.'),
          fill('At the moment, I ___ breakfast in the kitchen of our flat.',
            'في هذه اللحظة، ___ الفطور في مطبخ شقتنا.',
            'في هذه اللحظة، أتناول الفطور في مطبخ شقتنا.',
            ['eat', 'am eating', 'ate'], 1,
            'الصيغة في الرسالة "eat" خطأ: At the moment تدلّ على حدث يجري الآن، فنستخدم المضارع المستمر am eating.'),
          fill('At the moment, my mother ___ coffee.',
            'في هذه اللحظة، أمي ___ القهوة.',
            'في هذه اللحظة، أمي تشرب القهوة.',
            ['drinks', 'is drinking', 'drank'], 1,
            'الصيغة في الرسالة "drinks" خطأ: الحدث يجري الآن (At the moment) فنستخدم المضارع المستمر is drinking.'),
          fill('At the moment, my sisters ___ magazines.',
            'في هذه اللحظة، أخواتي ___ المجلات.',
            'في هذه اللحظة، أخواتي يقرأن المجلات.',
            ['read', 'are reading', 'were reading'], 1,
            'الصيغة "are reading" صحيحة ✓: حدث يجري الآن فنستخدم المضارع المستمر.'),
          fill('On Saturday afternoons, I ___ tennis with my friends, or I go to the cinema.',
            'في أمسيات أيام السبت، ___ التنس مع أصدقائي، أو أذهب إلى السينما.',
            'في أمسيات أيام السبت، ألعب التنس مع أصدقائي، أو أذهب إلى السينما.',
            ['am playing', 'play', 'played'], 1,
            'الصيغة في الرسالة "am playing" خطأ: On Saturday afternoons تدلّ على عادة متكرّرة، فنستخدم المضارع البسيط play.'),
          fill('On Saturday afternoons, I play tennis with my friends, or I ___ to the cinema.',
            'في أمسيات أيام السبت، ألعب التنس مع أصدقائي، أو ___ إلى السينما.',
            'في أمسيات أيام السبت، ألعب التنس مع أصدقائي، أو أذهب إلى السينما.',
            ['go', 'am going', 'went'], 0,
            'الصيغة "go" صحيحة ✓: عادة متكرّرة فنستخدم المضارع البسيط.'),
          fill('Sometimes I watch American films on TV, but I ___ the words!',
            'أحياناً أشاهد أفلاماً أمريكية على التلفاز، لكنني ___ الكلمات!',
            'أحياناً أشاهد أفلاماً أمريكية على التلفاز، لكنني لا أفهم الكلمات!',
            ['am not understanding', 'don’t understand', 'didn’t understand'], 1,
            'الصيغة في الرسالة "I’m not understanding" خطأ: understand فعل حالة (state verb) لا يأتي في المستمر، فنقول don’t understand.'),
          fill('Jane asks David: "___ films?"',
            'تسأل جين ديفيد: "___ الأفلام؟"',
            'تسأل جين ديفيد: "هل تحبّ الأفلام؟"',
            ['Are you liking', 'Do you like', 'Did you like'], 1,
            'الصيغة في الرسالة "Are you liking" خطأ: like فعل حالة (شعور) لا يأتي في المستمر، فنسأل Do you like…?'),

          // ---- page 5b: Lucy and Ella — past simple or present perfect ----
          fill('Lucy: Have you ever been to Canada? Ella: Yes, I ___ there last year.',
            'لوسي: هل سبق أن زرتِ كندا؟ إيلا: نعم، ___ إلى هناك السنة الماضية.',
            'لوسي: هل سبق أن زرتِ كندا؟ إيلا: نعم، ذهبت إلى هناك السنة الماضية.',
            ['have gone', 'went', 'go'], 1,
            'last year وقت محدّد في الماضي، فنستخدم الماضي البسيط went ولا نستخدم المضارع التام.'),
          fill('Lucy: ___ it? Ella: Yes, I enjoyed the trip a lot.',
            'لوسي: ___ ذلك؟ إيلا: نعم، استمتعت بالرحلة كثيراً.',
            'لوسي: هل أعجبكِ ذلك؟ إيلا: نعم، استمتعت بالرحلة كثيراً.',
            ['Have you liked', 'Did you like', 'Do you like'], 1,
            'نسأل عن رحلة انتهت في الماضي (السنة الماضية)، فنستخدم سؤال الماضي البسيط Did you like…?'),
          fill('Ella: Yes, I ___ the trip a lot.',
            'إيلا: نعم، ___ بالرحلة كثيراً.',
            'إيلا: نعم، استمتعت بالرحلة كثيراً.',
            ['have enjoyed', 'enjoyed', 'enjoy'], 1,
            'الرحلة حدثت وانتهت السنة الماضية، فنستخدم الماضي البسيط enjoyed.'),
          fill('Lucy: What ___ there?',
            'لوسي: ماذا ___ هناك؟',
            'لوسي: ماذا فعلتِ هناك؟',
            ['have you done', 'did you do', 'do you do'], 1,
            'السؤال عن أحداث رحلة منتهية في الماضي، فنستخدم الماضي البسيط: What did you do there?'),
          fill('Ella: I ___ Niagara Falls and Stanley Park.',
            'إيلا: ___ شلالات نياغرا ومنتزه ستانلي.',
            'إيلا: زرت شلالات نياغرا ومنتزه ستانلي.',
            ['have visited', 'visited', 'visit'], 1,
            'الزيارة جزء من رحلة السنة الماضية المنتهية، فنستخدم الماضي البسيط visited.'),
          fill('Ella: ___ to Canada before, Lucy?',
            'إيلا: ___ إلى كندا من قبل يا لوسي؟',
            'إيلا: هل سبق أن ذهبتِ إلى كندا من قبل يا لوسي؟',
            ['Did you go', 'Have you been', 'Do you go'], 1,
            'السؤال عن تجربة في الحياة دون وقت محدّد (before) يكون بالمضارع التام، ومع go نقول Have you been to…?'),
          fill('Lucy: No, but I ___ a holiday there. I’ve got my ticket and I’m going next week!',
            'لوسي: لا، لكنني ___ عطلة هناك. معي تذكرتي وسأسافر الأسبوع القادم!',
            'لوسي: لا، لكنني حجزت عطلة هناك. معي تذكرتي وسأسافر الأسبوع القادم!',
            ['booked', 'have booked', 'book'], 1,
            'حدث في الماضي دون وقت محدّد وله نتيجة الآن (معي التذكرة)، فنستخدم المضارع التام have booked.'),

          // ---- page 6c: present perfect simple or continuous ----
          fill('A: Excuse me. ___ this mobile here?',
            'أ: عفواً. ___ هذا الهاتف المحمول هنا؟',
            'أ: عفواً. هل ترك أحدٌ هذا الهاتف المحمول هنا؟',
            ['Has someone left', 'Has someone been leaving', 'Have someone left'], 0,
            'الترك حدث واحد انتهى وله نتيجة الآن (الهاتف هنا)، فنستخدم المضارع التام البسيط Has someone left…? (someone مفرد فنقول has).'),
          fill('B: I don’t know. I ___ here all afternoon, but I haven’t noticed it until now.',
            'ب: لا أعرف. أنا ___ هنا طوال فترة بعد الظهر، لكنني لم ألاحظه حتى الآن.',
            'ب: لا أعرف. أنا أجلس هنا طوال فترة بعد الظهر، لكنني لم ألاحظه حتى الآن.',
            ['have been sitting', 'am sitting', 'sat'], 0,
            'نشاط بدأ في الماضي واستمرّ حتى الآن مع التركيز على المدة (all afternoon)، فنستخدم المضارع التام المستمر have been sitting.'),
          fill('B: I have been sitting here all afternoon, but I ___ it until now.',
            'ب: أنا أجلس هنا طوال فترة بعد الظهر، لكنني ___ حتى الآن.',
            'ب: أنا أجلس هنا طوال فترة بعد الظهر، لكنني لم ألاحظه حتى الآن.',
            ['haven’t been noticing', 'haven’t noticed', 'don’t notice'], 1,
            'notice حدث لحظي وليس نشاطاً مستمراً، ومع until now نستخدم المضارع التام البسيط haven’t noticed.'),
          fill('A: Excuse me. ___ in this queue for a long time?',
            'أ: عفواً. ___ في هذا الطابور منذ وقت طويل؟',
            'أ: عفواً. هل أنت واقف في هذا الطابور منذ وقت طويل؟',
            ['Have you been standing', 'Were you standing', 'Do you stand'], 0,
            'نشاط بدأ في الماضي وما زال مستمراً مع التركيز على المدة (for a long time)، فنستخدم المضارع التام المستمر.'),
          fill('B: Yes, I ___ for almost an hour.',
            'ب: نعم، ___ منذ ساعة تقريباً.',
            'ب: نعم، أنا أقف في الطابور منذ ساعة تقريباً.',
            ['have been queuing', 'am queuing', 'queued'], 0,
            'مع for almost an hour وعن نشاط مستمر حتى الآن نستخدم المضارع التام المستمر have been queuing.'),
          fill('A: Why are you crying? B: Because my brother ___ an accident.',
            'أ: لماذا تبكي؟ ب: لأن أخي ___ لحادث.',
            'أ: لماذا تبكي؟ ب: لأن أخي تعرّض لحادث.',
            ['has had', 'has been having', 'have had'], 0,
            'حادث واحد انتهى وله نتيجة الآن (أنا أبكي)، فنستخدم المضارع التام البسيط has had (brother مفرد فنقول has).'),
          fill('He ___ both of his legs.',
            'لقد ___ ساقيه كلتيهما.',
            'لقد كسر ساقيه كلتيهما.',
            ['has been breaking', 'has broken', 'have broken'], 1,
            'الكسر حدث مكتمل له نتيجة الآن، فنستخدم المضارع التام البسيط has broken وليس المستمر.'),

          // ---- page 6: Everyday English — giving advice ----
          fill('___ leave the university. If you’ve studied hard, you probably have nothing to worry about. (not/ think/ good/ idea)',
            '___ تترك الجامعة. إذا كنت قد درست بجدّ فربما لا يوجد ما يقلقك.',
            'لا أظنّ أنها فكرة جيدة أن تترك الجامعة. إذا كنت قد درست بجدّ فربما لا يوجد ما يقلقك.',
            ['I don’t think it’s a good idea to', 'I think it isn’t good idea', 'I’m not thinking it’s a good idea to'], 0,
            'للنصح بعدم فعل شيء نقول: I don’t think it’s a good idea to + المصدر. نضع النفي مع think، وthink بمعنى الرأي لا تأتي في المستمر.'),
          fill('___ talking to your university professor? He can probably help. (why/ you/ try)',
            '___ التحدّث إلى أستاذك في الجامعة؟ ربما يستطيع أن يساعدك.',
            'لماذا لا تجرّب التحدّث إلى أستاذك في الجامعة؟ ربما يستطيع أن يساعدك.',
            ['Why don’t you try', 'Why you try', 'Why do you try to'], 0,
            'لتقديم اقتراح نقول: Why don’t you + المصدر…? ثم try + ing (talking).'),
          fill('___ try some relaxation techniques to help you with the exam stress. (think/ should)',
            '___ تجرّب بعض أساليب الاسترخاء لتساعدك على ضغط الامتحانات.',
            'أظنّ أنه يجب أن تجرّب بعض أساليب الاسترخاء لتساعدك على ضغط الامتحانات.',
            ['I think you should', 'I think you should to', 'I’m thinking you should'], 0,
            'للنصيحة نقول: I think you should + المصدر بدون to.'),
          fill('___ go to the exams even if you feel like you won’t pass them. You should at least try. Good luck! (good/ idea)',
            '___ تذهب إلى الامتحانات حتى لو شعرت أنك لن تنجح فيها. يجب أن تحاول على الأقل. بالتوفيق!',
            'من الجيد أن تذهب إلى الامتحانات حتى لو شعرت أنك لن تنجح فيها. يجب أن تحاول على الأقل. بالتوفيق!',
            ['It’s a good idea to', 'It’s good idea', 'It’s a good idea'], 0,
            'التعبير الكامل للنصيحة: It’s a good idea to + المصدر (مع a قبل good ومع to قبل الفعل).'),

          // ---- page 8a: writing — connect topic sentences to details, then order the paragraphs ----
          mcq(`Which details complete the paragraph that begins: "${u1Topics[0]}"`,
            'ما الجملتان اللتان تكمّلان الفقرة التي تبدأ بـ: "هل مرّ عليك يوم تمنّيت لو أنه لم يحدث؟"',
            u1Details, 0,
            'هذه فقرة المقدّمة: تجذب اهتمام القارئ بسؤال، ثم تسمّي التجربة (اختبار الرياضيات في الصف العاشر) وتلمّح إلى الدرس المستفاد.'),
          mcq(`Which details complete the paragraph that begins: "${u1Topics[1]}"`,
            'ما الجملتان اللتان تكمّلان الفقرة التي تبدأ بـ: "في الحقيقة، كنت أعرف أن لدينا اختباراً مهماً علينا أن نستعدّ له."',
            u1Details, 1,
            'هذه فقرة ما حدث قبل التجربة: المعلّم طلب الاستعداد جيداً لكن الكاتب لم يدرس. لاحظ الماضي التام (had told / hadn’t studied) لأحداث سبقت يوم الاختبار.'),
          mcq(`Which details complete the paragraph that begins: "${u1Topics[2]}"`,
            'ما الجملتان اللتان تكمّلان الفقرة التي تبدأ بـ: "عندما جاء يوم الاختبار، كنت واثقاً أنني سأبلي بلاءً حسناً."',
            u1Details, 2,
            'هذه فقرة الجزء الرئيسي من التجربة: الاختبار كان صعباً جداً ثم جاءت العلامة 5% وغضب الكاتب من نفسه.'),
          mcq('Which paragraph is number 1 in the text?', 'أيّ فقرة هي رقم 1 في النص؟', u1Topics, 0,
            'المقدّمة تجذب اهتمام القارئ (Get the reader’s interest) بسؤال: Have you ever had a day…?'),
          mcq('Which paragraph is number 2 in the text?', 'أيّ فقرة هي رقم 2 في النص؟', u1Topics, 1,
            'الفقرة الثانية تصف ما حدث قبل التجربة (Describe important things that happened before the experience).'),
          mcq('Which paragraph is number 3 in the text?', 'أيّ فقرة هي رقم 3 في النص؟', u1Topics, 2,
            'الفقرة الثالثة تصف الجزء الرئيسي من التجربة (يوم الاختبار نفسه)، أما الفقرة 4 فهي الخاتمة: المشاعر الأخيرة والدرس المستفاد.'),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'In no more than 100 words, write a composition in which you describe the job you want after graduation. What kind of challenges do you expect to face in your future career?',
          topicAr: 'اكتب موضوعاً لا يزيد على 100 كلمة تصف فيه الوظيفة التي تريدها بعد التخرّج. ما نوع التحدّيات التي تتوقّع أن تواجهها في مهنتك المستقبلية؟',
          words: 100,
          points: ['Job requirements', 'Your needs', 'Expectations', 'Beliefs and knowledge'],
          pointsAr: ['متطلبات الوظيفة', 'احتياجاتك', 'التوقّعات', 'المعتقدات والمعرفة'],
          plan: [
            { en: 'Topic sentence: name the job you aspire to after graduation.', ar: 'جملة رئيسية: اذكر الوظيفة التي تطمح إليها بعد التخرّج.' },
            { en: 'Job requirements: the studies, skills and aptitude the job needs.', ar: 'متطلبات الوظيفة: الدراسة والمهارات والاستعداد الذي تحتاجه.' },
            { en: 'Your needs and expectations: what you want from the job and the challenges you expect to run into.', ar: 'احتياجاتك وتوقّعاتك: ما تريده من الوظيفة والتحدّيات التي تتوقّع أن تواجهها.' },
            { en: 'Beliefs and knowledge: what you believe will help you, then a concluding sentence.', ar: 'معتقداتك ومعرفتك: ما تؤمن أنه سيساعدك، ثم جملة ختامية.' },
          ],
          phrases: [
            { en: 'I aspire to become …', ar: 'أطمح أن أصبح …' },
            { en: 'my future career', ar: 'مهنتي المستقبلية' },
            { en: 'an aptitude for science', ar: 'استعداد وموهبة في العلوم' },
            { en: 'I want a job that allows me to contribute to society.', ar: 'أريد وظيفة تسمح لي بالإسهام في المجتمع.' },
            { en: 'I can’t enjoy a job unless it is quite challenging.', ar: 'لا أستطيع أن أستمتع بوظيفة إلا إذا كانت فيها تحدٍّ.' },
            { en: 'carry a lot of responsibility', ar: 'يتحمّل مسؤولية كبيرة' },
            { en: 'run into difficulties', ar: 'يواجه صعوبات' },
            { en: 'keep up with the latest developments', ar: 'يواكب آخر التطوّرات' },
            { en: 'fit in with my workmates', ar: 'أندمج مع زملائي في العمل' },
            { en: 'follow through with my plans', ar: 'أتابع خططي حتى النهاية' },
            { en: 'However, I believe that …', ar: 'ومع ذلك، أؤمن أن …' },
            { en: 'Life is a matter of choices, and every choice you make makes you.', ar: 'الحياة مسألة خيارات، وكل خيار تتخذه يصنعك.' },
          ],
          model: 'After graduation, I aspire to become a doctor. This career requires excellent marks, six years of hard study and a real aptitude for science. I want a job that allows me to contribute to society, and I can’t enjoy a job unless it is quite challenging. I expect to work long hours and carry a lot of responsibility. I will probably run into difficulties, such as keeping up with new medicines and fitting in with a hospital team. However, I believe that patience and hard work lead to success. Life is a matter of choices, and I have made mine.',
          modelAr: 'بعد التخرّج، أطمح أن أصبح طبيباً. تتطلّب هذه المهنة علامات ممتازة، وست سنوات من الدراسة الشاقة، واستعداداً حقيقياً للعلوم. أريد وظيفة تسمح لي بالإسهام في المجتمع، ولا أستطيع أن أستمتع بوظيفة إلا إذا كانت فيها تحدٍّ. أتوقّع أن أعمل ساعات طويلة وأن أتحمّل مسؤولية كبيرة. ومن المحتمل أن أواجه صعوبات، مثل مواكبة الأدوية الجديدة والاندماج مع فريق المستشفى. ومع ذلك، أؤمن أن الصبر والعمل الجادّ يقودان إلى النجاح. الحياة مسألة خيارات، وقد اتّخذت خياري.',
          checklistAr: [
            'هل ذكرت الوظيفة في جملة رئيسية واضحة في البداية؟',
            'هل غطّيت النقاط الأربع: متطلبات الوظيفة، واحتياجاتك، وتوقّعاتك، ومعتقداتك ومعرفتك؟',
            'هل ذكرت تحدّياً واحداً على الأقل تتوقّع أن تواجهه؟',
            'هل استخدمت مفردات الوحدة (aspire, challenging, contribute, run into, keep up with…)؟',
            'هل استخدمت المضارع البسيط للحقائق والرغبات وwill للتوقّعات بشكل صحيح؟',
            'هل الموضوع في حدود 100 كلمة، وراجعت التهجئة والقواعد وعلامات الترقيم؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Life is about the choices and decisions we make. Write about a personal experience in which you have made an important decision that changed your life.',
          topicAr: 'الحياة تقوم على الخيارات والقرارات التي نتّخذها. اكتب عن تجربة شخصية اتّخذت فيها قراراً مهماً غيّر حياتك.',
          words: 100,
          points: [
            'Get the reader’s interest.',
            'Name the experience.',
            'Describe important things that happened before the experience.',
            'Describe the main part of the experience.',
            'End with final feelings or something you learned.',
          ],
          pointsAr: [
            'اجذب اهتمام القارئ.',
            'سمِّ التجربة.',
            'صِف الأشياء المهمة التي حدثت قبل التجربة.',
            'صِف الجزء الرئيسي من التجربة.',
            'اختم بمشاعرك الأخيرة أو بشيء تعلّمته.',
          ],
          plan: [
            { en: 'Introduction: get the reader’s interest with a question and name the decision.', ar: 'المقدّمة: اجذب اهتمام القارئ بسؤال وسمِّ القرار الذي اتّخذته.' },
            { en: 'Body paragraph 1: what happened before the decision (use the past perfect: had told, had chosen).', ar: 'فقرة العرض 1: ما حدث قبل القرار (استخدم الماضي التام: had told, had chosen).' },
            { en: 'Body paragraph 2: the main part of the experience — the decision and what happened next.', ar: 'فقرة العرض 2: الجزء الرئيسي من التجربة — القرار وما حدث بعده.' },
            { en: 'Conclusion: your final feelings and the lesson you learned.', ar: 'الخاتمة: مشاعرك الأخيرة والدرس الذي تعلّمته.' },
          ],
          phrases: [
            { en: 'Have you ever …?', ar: 'هل سبق لك أن …؟' },
            { en: 'For me, it was …', ar: 'بالنسبة لي، كان ذلك …' },
            { en: 'Actually, I had known …', ar: 'في الحقيقة، كنت أعرف …' },
            { en: 'To tell the truth, …', ar: 'لأقول الحقيقة، …' },
            { en: 'From that day on, …', ar: 'منذ ذلك اليوم، …' },
            { en: 'make an important decision', ar: 'يتّخذ قراراً مهماً' },
            { en: 'benefit from the experiences of others', ar: 'يستفيد من تجارب الآخرين' },
            { en: 'my aptitude and my future career', ar: 'استعدادي ومهنتي المستقبلية' },
            { en: 'fit in with a new class', ar: 'يندمج مع صفّ جديد' },
            { en: 'Failure is a great teacher in life.', ar: 'الفشل معلّم عظيم في الحياة.' },
            { en: 'Life is a matter of choices, and every choice you make makes you.', ar: 'الحياة مسألة خيارات، وكل خيار تتخذه يصنعك.' },
          ],
          model: 'Have you ever made a decision that changed your whole life? For me, it was the day I decided to join the scientific section in tenth grade.\nActually, all my friends had chosen the literary section, and I wanted to stay with them. However, my father had told me to think carefully about my aptitude and my future career, so I spent a week thinking about my choice.\nIn the end, I chose science because I love biology and I aspire to become a doctor. At first, it was hard to fit in with a new class, but I kept trying.\nFrom that day on, I have been studying harder than ever. I have learned that life is a matter of choices, and every choice you make makes you.',
          modelAr: 'هل سبق لك أن اتّخذت قراراً غيّر حياتك كلها؟ بالنسبة لي، كان ذلك اليوم الذي قرّرت فيه الانضمام إلى الفرع العلمي في الصف العاشر.\nفي الحقيقة، كان كل أصدقائي قد اختاروا الفرع الأدبي، وكنت أريد البقاء معهم. لكن أبي كان قد طلب مني أن أفكّر جيداً في استعدادي ومهنتي المستقبلية، فقضيت أسبوعاً أفكّر في خياري.\nفي النهاية، اخترت العلوم لأنني أحبّ علم الأحياء وأطمح أن أصبح طبيباً. في البداية كان من الصعب أن أندمج مع صفّ جديد، لكنني واصلت المحاولة.\nمنذ ذلك اليوم وأنا أدرس بجدّ أكثر من أي وقت مضى. لقد تعلّمت أن الحياة مسألة خيارات، وأن كل خيار تتخذه يصنعك.',
          checklistAr: [
            'هل تبدأ المقدّمة بجملة تجذب اهتمام القارئ وتسمّي التجربة؟',
            'هل تصف فقرة ما حدث قبل التجربة، وفقرة الجزء الرئيسي منها؟',
            'هل تختم بمشاعرك الأخيرة أو بالدرس الذي تعلّمته؟',
            'هل استخدمت أزمنة الماضي بشكل صحيح (الماضي البسيط للأحداث، والماضي التام لما حدث قبلها)؟',
            'هل استخدمت أدوات ربط مثل Actually, However, In the end, From that day on؟',
            'هل راجعت التهجئة والحروف الكبيرة وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'Failure is a great teacher in life.', ar: 'الفشل معلّم عظيم في الحياة.' },
        { en: 'It teaches us humility and how to correct our course of life.', ar: 'إنه يعلّمنا التواضع وكيف نصحّح مسار حياتنا.' },
        { en: 'He failed many times, but he did not give up until he succeeded.', ar: 'فشل مرات كثيرة، لكنه لم يستسلم حتى نجح.' },
        { en: 'Even when he failed, Edison learned something.', ar: 'حتى عندما كان يفشل، كان إديسون يتعلّم شيئاً.' },
        { en: 'Take care of your health and make it a priority for your entire life.', ar: 'اعتنِ بصحتك واجعلها أولوية طوال حياتك.' },
        { en: 'There are no alternatives to exercising, eating well, fresh air and sunshine.', ar: 'لا بدائل عن ممارسة الرياضة والأكل الجيد والهواء النقي وأشعة الشمس.' },
        { en: 'There is no word more boring and monotonous than the word "I".', ar: 'لا توجد كلمة أكثر مللاً ورتابة من كلمة «أنا».' },
        { en: 'I have studied hard for three years, but now I feel like I don’t know anything.', ar: 'لقد درست بجدّ لثلاث سنوات، لكنني الآن أشعر أنني لا أعرف شيئاً.' },
        { en: 'When the test day came, I was confident I would do well.', ar: 'عندما جاء يوم الاختبار، كنت واثقاً أنني سأبلي بلاءً حسناً.' },
        { en: 'From that day on, I decided to study harder.', ar: 'منذ ذلك اليوم، قرّرت أن أدرس بجدّ أكبر.' },
        { en: 'Later, when I got my score and saw 5%, I was angry with myself.', ar: 'لاحقاً، عندما حصلت على علامتي ورأيت 5%، غضبت من نفسي.' },
        { en: 'Life is a matter of choices, and every choice you make makes you.', ar: 'الحياة مسألة خيارات، وكل خيار تتخذه يصنعك.' },
        { en: 'I can’t enjoy a job unless it is quite challenging.', ar: 'لا أستطيع أن أستمتع بوظيفة إلا إذا كانت فيها تحدٍّ.' },
        { en: 'I want a job that allows me to contribute to society.', ar: 'أريد وظيفة تسمح لي بالإسهام في المجتمع.' },
        { en: 'She didn’t really fit in with her workmates in her previous job.', ar: 'لم تندمج حقاً مع زملائها في العمل في وظيفتها السابقة.' },
        { en: 'If you run into any trouble, just give me a call.', ar: 'إذا واجهت أي مشكلة، فقط اتصل بي.' },
      ],
    },
    // ===================== UNIT 2 — Success (Activity Book pages 9–15) =====================
    u2: {
      workbook: {
        pages: '9–15',
        readings: [
          {
            title: 'Famous Failures Who Refused to Give up',
            paragraphs: [
              'One of the most destructive moments in our lives is failure. When we work hard and keep faith with clear heart and soul to accomplish something and fail, it will surely have negative consequences for our lives. When we fail, life turns upside down. Everything seems to disappear into thin air. However, most people don’t realise that failure acts as a stepping-stone towards success. They don’t know that we can learn more about our lives when we fail. Throughout history, there have been many famous people who had once the greatest failures in their lives, but later they could learn from their experience and were able to reach the top.',
              'Thomas Edison is by far one of the most famous inventors in history. He holds 1,093 patents to his name. However, when attempting to invent a commercially-viable electric lightbulb, he failed over 10,000 times. When asked by a reporter how it felt to fail so many times, he merely stated, “I have not failed 10,000 times. I have not failed once. I have succeeded in proving that those 10,000 ways will not work. When I have eliminated the ways that will not work, I will find the way that will work.”',
              'Albert Einstein, one of the greatest thinkers of our time, didn’t speak until he was four-years old. He also failed his entrance exam to the Swiss Federal Polytechnic school located in Zurich at sixteen-years old. And, even his father, up until the time of his death, considered his son to be a major failure. After eventually graduating from college, Einstein actually worked as an insurance salesman, but quit after some time because he failed at that as well.',
              'Bill Gates has amassed a mind-boggling net worth of close to $80 billion, and is known as the father of modern personal-computing software. He brought us operating systems such as Microsoft DOS and Windows, along with wildly-popular titles such as Microsoft Office’s Word, Excel and PowerPoint. However, at the age of seventeen-years old, his first software company called, Traf-O-Data, which analyzed raw traffic logs, failed.',
              'Walt Disney is the creative genius who brought us the likes of Mickey Mouse, Donald Duck and Snow White. He created the Walt Disney Company after his own namesake. Yet, he faced many failures. His first company, Laugh-O-Gram went bankrupt. It wasn’t until 5 years later and plenty of heartache - after he created Mickey Mouse - did he begin to experience a small amount of success and fame.',
            ],
            paragraphsAr: [
              'من أكثر اللحظات تدميراً في حياتنا الفشل. عندما نعمل بجدّ ونحافظ على إيماننا بقلب وروح صافيين لننجز شيئاً ثم نفشل، فسيكون لذلك بالتأكيد عواقب سلبية على حياتنا. عندما نفشل تنقلب الحياة رأساً على عقب، ويبدو كل شيء وكأنه يتلاشى في الهواء. ومع ذلك، لا يدرك معظم الناس أن الفشل يعمل كنقطة انطلاق (حجر عبور) نحو النجاح. إنهم لا يعرفون أننا نستطيع أن نتعلّم المزيد عن حياتنا عندما نفشل. وعلى مرّ التاريخ، كان هناك كثير من المشاهير الذين مرّوا يوماً بأكبر الإخفاقات في حياتهم، لكنهم استطاعوا لاحقاً أن يتعلّموا من تجربتهم وتمكّنوا من الوصول إلى القمة.',
              'توماس إديسون هو بلا منازع واحد من أشهر المخترعين في التاريخ، ويحمل 1093 براءة اختراع باسمه. ومع ذلك، عندما حاول اختراع مصباح كهربائي صالح للاستخدام التجاري فشل أكثر من 10000 مرة. وعندما سأله صحفي عن شعوره بعد أن فشل كل تلك المرات، قال ببساطة: «لم أفشل 10000 مرة. لم أفشل ولا مرة واحدة. لقد نجحت في إثبات أن تلك الطرق العشرة آلاف لا تنجح. وعندما أستبعد الطرق التي لا تنجح، سأجد الطريقة التي تنجح».',
              'ألبرت أينشتاين، أحد أعظم المفكّرين في عصرنا، لم يتكلّم حتى بلغ الرابعة من عمره. كما رسب في امتحان القبول في معهد البوليتكنيك الفدرالي السويسري في زيورخ وهو في السادسة عشرة. بل إن أباه ظلّ حتى وفاته يعتبر ابنه فاشلاً فشلاً كبيراً. وبعد أن تخرّج أخيراً من الجامعة، عمل أينشتاين بائعاً للتأمين، لكنه ترك العمل بعد مدة لأنه فشل فيه أيضاً.',
              'جمع بيل غيتس ثروة صافية مذهلة تقارب 80 مليار دولار، ويُعرف بأنه أبو برمجيات الحاسوب الشخصي الحديثة. فقد قدّم لنا أنظمة تشغيل مثل مايكروسوفت دوس وويندوز، إلى جانب برامج واسعة الانتشار مثل وورد وإكسل وباوربوينت من حزمة مايكروسوفت أوفيس. ومع ذلك، عندما كان في السابعة عشرة من عمره، فشلت أول شركة برمجيات أسّسها، واسمها ترافـ-أو-داتا، وكانت تحلّل سجلات حركة المرور الخام.',
              'والت ديزني هو العبقري المبدع الذي قدّم لنا شخصيات مثل ميكي ماوس ودونالد داك وسنو وايت، وأسّس شركة والت ديزني التي تحمل اسمه. ومع ذلك، واجه كثيراً من الإخفاقات؛ فقد أفلست شركته الأولى «لاف-أو-غرام». ولم يبدأ يذوق قليلاً من النجاح والشهرة إلا بعد خمس سنوات وكثير من الألم، بعد أن ابتكر شخصية ميكي ماوس.',
            ],
            questions: [
              {
                q: 'What are the good sides and bad sides of failures?', qAr: 'ما الجوانب الجيدة والجوانب السيئة للفشل؟',
                options: [
                  'Failure has negative consequences for our lives, but it is a stepping-stone towards success and teaches us more about our lives.',
                  'Failure has no bad sides because it always makes us rich.',
                  'Failure only makes us famous, and it has no good sides.',
                  'Failure makes life easier, but it stops us from learning.',
                ],
                answer: 0, explainAr: 'الفقرة الأولى: للفشل عواقب سلبية (negative consequences) وتنقلب الحياة رأساً على عقب، لكنه نقطة انطلاق نحو النجاح (a stepping-stone towards success) ونتعلّم منه أكثر عن حياتنا.',
              },
              {
                q: 'How did Edison react to his failures?', qAr: 'كيف كان ردّ فعل إديسون على إخفاقاته؟',
                options: [
                  'He felt ashamed and stopped inventing.',
                  'He said he had not failed; he had succeeded in proving that 10,000 ways would not work.',
                  'He blamed the reporter for his failures.',
                  'He decided to work as an insurance salesman.',
                ],
                answer: 1, explainAr: 'قال إديسون: "I have not failed 10,000 times… I have succeeded in proving that those 10,000 ways will not work" أي نظر إلى كل محاولة فاشلة على أنها خطوة نحو الطريقة الصحيحة.',
              },
              {
                q: 'How did Einstein’s father see his son? Did he change his mind towards him later?', qAr: 'كيف كان والد أينشتاين يرى ابنه؟ وهل غيّر رأيه فيه لاحقاً؟',
                options: [
                  'He saw him as a genius from the beginning.',
                  'He saw him as a major failure, but he changed his mind when Einstein graduated.',
                  'He considered him a major failure and never changed his mind until his death.',
                  'He saw him as a good insurance salesman.',
                ],
                answer: 2, explainAr: 'يقول النص: "even his father, up until the time of his death, considered his son to be a major failure" أي ظلّ يراه فاشلاً حتى وفاته ولم يغيّر رأيه.',
              },
              {
                q: 'What is the thing that we owe Gates?', qAr: 'ما الشيء الذي ندين به لغيتس؟',
                options: [
                  'The electric lightbulb.',
                  'Mickey Mouse and Donald Duck.',
                  'Modern personal-computing software such as Windows, Word, Excel and PowerPoint.',
                  'The Swiss Federal Polytechnic school.',
                ],
                answer: 2, explainAr: 'يُعرف غيتس بأنه أبو برمجيات الحاسوب الشخصي الحديثة، فقد قدّم لنا أنظمة التشغيل مثل DOS وWindows وبرامج Word وExcel وPowerPoint.',
              },
              {
                q: 'When did Disney experience a period of success?', qAr: 'متى بدأ ديزني يعيش فترة من النجاح؟',
                options: [
                  'As soon as he created his first company, Laugh-O-Gram.',
                  'Five years after his first company went bankrupt, after he created Mickey Mouse.',
                  'When he was seventeen years old.',
                  'Before he faced any failures.',
                ],
                answer: 1, explainAr: 'يقول النص: "It wasn’t until 5 years later and plenty of heartache - after he created Mickey Mouse - did he begin to experience a small amount of success and fame".',
              },
            ],
          },
        ],
        exercises: [
          // ---- page 10b: match the words in bold with their meanings ----
          mcq('Which word in bold means "reduced to a state of financial ruins"?', 'أيّ كلمة من الكلمات الغامقة تعني «وصل إلى حالة الخراب المالي»؟',
            ['bankrupt', 'insurance', 'eliminated', 'patents'], 0,
            'bankrupt = مفلس، كما في: "His first company, Laugh-O-Gram went bankrupt".'),
          mcq('Which word in bold means "put an end to or get rid of"?', 'أيّ كلمة من الكلمات الغامقة تعني «وضع حداً لشيء أو تخلّص منه»؟',
            ['stepping-stone', 'eliminated', 'mind-boggling', 'bankrupt'], 1,
            'eliminate = يستبعد / يتخلّص من، كما في: "When I have eliminated the ways that will not work".'),
          mcq('Which word in bold means "a means of guaranteeing protection or safety"?', 'أيّ كلمة من الكلمات الغامقة تعني «وسيلة لضمان الحماية أو الأمان»؟',
            ['patents', 'bankrupt', 'insurance', 'stepping-stone'], 2,
            'insurance = التأمين، كما في: "Einstein actually worked as an insurance salesman".'),
          mcq('Which word in bold means "a means of progress or advancement"?', 'أيّ كلمة من الكلمات الغامقة تعني «وسيلة للتقدّم والارتقاء»؟',
            ['mind-boggling', 'eliminated', 'insurance', 'stepping-stone'], 3,
            'stepping-stone = نقطة انطلاق / خطوة نحو التقدّم، كما في: "failure acts as a stepping-stone towards success".'),
          mcq('Which word in bold means "amazingly or confusingly large, great, etc."?', 'أيّ كلمة من الكلمات الغامقة تعني «كبير أو عظيم بشكل مذهل أو محيّر»؟',
            ['mind-boggling', 'bankrupt', 'patents', 'stepping-stone'], 0,
            'mind-boggling = مذهل / يحيّر العقل، كما في: "a mind-boggling net worth of close to $80 billion".'),
          mcq('Which word in bold means "a special document that gives you the right to make or sell a new invention or product"?', 'أيّ كلمة من الكلمات الغامقة تعني «وثيقة خاصة تمنحك حق صنع اختراع أو منتج جديد أو بيعه»؟',
            ['insurance', 'patents', 'eliminated', 'mind-boggling'], 1,
            'patent = براءة اختراع، كما في: "He holds 1,093 patents to his name".'),

          // ---- page 11c: use the words in bold to complete the sentences ----
          fill('Their companies went ___ before they reached a great economic recovery.',
            'أصبحت شركاتهم ___ قبل أن تصل إلى تعافٍ اقتصادي كبير.',
            'أصبحت شركاتهم مفلسة قبل أن تصل إلى تعافٍ اقتصادي كبير.',
            ['insurance', 'bankrupt', 'stepping-stone', 'patents'], 1,
            'نقول go bankrupt = يُفلس. بعد went نحتاج صفة: bankrupt.'),
          fill('Failures are often considered a ___ of success in all areas of life.',
            'غالباً ما يُعتبر الفشل ___ للنجاح في جميع مجالات الحياة.',
            'غالباً ما يُعتبر الفشل نقطة انطلاق للنجاح في جميع مجالات الحياة.',
            ['stepping-stone', 'mind-boggling', 'bankrupt', 'patent'], 0,
            'بعد a نحتاج اسماً مفرداً بمعنى وسيلة للتقدّم: stepping-stone.'),
          fill('He obtained ___ for inventing new things.',
            'حصل على ___ لاختراعه أشياء جديدة.',
            'حصل على براءات اختراع لاختراعه أشياء جديدة.',
            ['insurance', 'eliminated', 'patents', 'stepping-stones'], 2,
            'patents = براءات الاختراع، وهي الوثيقة التي يحصل عليها المخترع (مثل إديسون).'),
          fill('Throughout his career, he won a ___ fortune of billions of dollars.',
            'طوال مسيرته المهنية، جمع ثروة ___ بمليارات الدولارات.',
            'طوال مسيرته المهنية، جمع ثروة مذهلة بمليارات الدولارات.',
            ['bankrupt', 'insurance', 'stepping-stone', 'mind-boggling'], 3,
            'قبل الاسم fortune نحتاج صفة بمعنى كبير بشكل مذهل: mind-boggling (مثل ثروة بيل غيتس).'),
          fill('He retired after failing as a/an ___ employee.',
            'تقاعد بعد أن فشل بوصفه موظّف ___.',
            'تقاعد بعد أن فشل بوصفه موظّف تأمين.',
            ['insurance', 'patent', 'bankrupt', 'eliminated'], 0,
            'an insurance employee = موظّف تأمين، مثل أينشتاين الذي عمل بائعاً للتأمين وفشل.'),
          fill('He ___ useless methods until he finally succeeded.',
            'لقد ___ الطرق غير المجدية حتى نجح في النهاية.',
            'لقد استبعد الطرق غير المجدية حتى نجح في النهاية.',
            ['bankrupt', 'eliminated', 'patents', 'insurance'], 1,
            'الجملة تحتاج فعلاً في الماضي بعد He: eliminated (استبعد)، مثل إديسون الذي استبعد الطرق التي لا تنجح.'),

          // ---- page 11: Vocabulary — success idioms ----
          fill('If you study hard enough, you will be able to ___ with no troubles.',
            'إذا درست بجدّ كافٍ، فستتمكّن من ___ دون أي مشكلات.',
            'إذا درست بجدّ كافٍ، فستتمكّن من التفوّق في الاختبار دون أي مشكلات.',
            ['back the wrong horse', 'ace a test', 'be dead in the water', 'join the ranks of'], 1,
            'ace a test = يتفوّق في الاختبار بسهولة. بعد be able to يأتي المصدر.'),
          fill('You really ___ when you picked that swimmer to win the race.',
            'لقد ___ حقاً عندما اخترت ذلك السبّاح ليفوز بالسباق.',
            'لقد راهنت على الخاسر حقاً عندما اخترت ذلك السبّاح ليفوز بالسباق.',
            ['backed the wrong horse', 'aced a test', 'were on a roll', 'joined the ranks of'], 0,
            'back the wrong horse = يراهن على الطرف الخاسر. نستخدم الماضي backed لأن picked في الماضي.'),
          fill('I didn’t get the results I was hoping for in my exams. My dream of going to Cambridge University ___.',
            'لم أحصل على النتائج التي كنت آملها في امتحاناتي. حلمي بالذهاب إلى جامعة كامبريدج ___.',
            'لم أحصل على النتائج التي كنت آملها في امتحاناتي. حلمي بالذهاب إلى جامعة كامبريدج انتهى ولا أمل فيه.',
            ['is on a roll', 'aces a test', 'is dead in the water', 'backs the wrong horse'], 2,
            'be dead in the water = فاشل لا أمل في نجاحه. الحلم أصبح بلا أمل بعد النتائج السيئة.'),
          fill('In a few years our company should be able to ___ the world’s most developed nations.',
            'بعد بضع سنوات، ينبغي أن تتمكّن شركتنا من ___ أكثر دول العالم تقدّماً.',
            'بعد بضع سنوات، ينبغي أن تتمكّن شركتنا من الانضمام إلى صفوف أكثر دول العالم تقدّماً.',
            ['ace a test', 'be on a roll', 'back the wrong horse', 'join the ranks of'], 3,
            'join the ranks of = ينضمّ إلى صفوف مجموعة ما. بعد be able to يأتي المصدر.'),
          fill('This is our fifth win in the game! We are ___. If we keep this up, we are sure to make it to the state championship game!',
            'هذا فوزنا الخامس في اللعبة! نحن ___. إذا حافظنا على هذا فسنصل بالتأكيد إلى مباراة بطولة الولاية!',
            'هذا فوزنا الخامس في اللعبة! نحن في سلسلة نجاحات. إذا حافظنا على هذا فسنصل بالتأكيد إلى مباراة بطولة الولاية!',
            ['dead in the water', 'on a roll', 'backing the wrong horse', 'joining the ranks of'], 1,
            'on a roll = في سلسلة من النجاحات المتتالية، مثل الفوز الخامس على التوالي.'),

          // ---- page 11–12: Pronunciation — -ed endings /t/, /d/, /id/ ----
          ...([
            ['reminded', 2, 'ينتهي الفعل remind بصوت /d/، فتُلفظ ed مقطعاً إضافياً /id/.'],
            ['believed', 1, 'ينتهي believe بصوت /v/ وهو صوت مجهور، فتُلفظ ed كـ /d/.'],
            ['talked', 0, 'ينتهي talk بصوت /k/ وهو صوت مهموس (voiceless)، فتُلفظ ed كـ /t/.'],
            ['ordered', 1, 'ينتهي order بصوت مجهور (/ə/ أو /r/)، فتُلفظ ed كـ /d/.'],
            ['dressed', 0, 'ينتهي dress بصوت /s/ وهو صوت مهموس، فتُلفظ ed كـ /t/.'],
            ['matched', 0, 'ينتهي match بصوت /tʃ/ وهو صوت مهموس، فتُلفظ ed كـ /t/.'],
            ['started', 2, 'ينتهي start بصوت /t/، فتُلفظ ed مقطعاً إضافياً /id/.'],
            ['passed', 0, 'ينتهي pass بصوت /s/ وهو صوت مهموس، فتُلفظ ed كـ /t/.'],
            ['recorded', 2, 'ينتهي record بصوت /d/، فتُلفظ ed مقطعاً إضافياً /id/.'],
            ['screamed', 1, 'ينتهي scream بصوت /m/ وهو صوت مجهور، فتُلفظ ed كـ /d/.'],
            ['asked', 0, 'ينتهي ask بصوت /k/ وهو صوت مهموس، فتُلفظ ed كـ /t/.'],
            ['improved', 1, 'ينتهي improve بصوت /v/ وهو صوت مجهور، فتُلفظ ed كـ /d/.'],
            ['phoned', 1, 'ينتهي phone بصوت /n/ وهو صوت مجهور، فتُلفظ ed كـ /d/.'],
            ['painted', 2, 'ينتهي paint بصوت /t/، فتُلفظ ed مقطعاً إضافياً /id/.'],
            ['connected', 2, 'ينتهي connect بصوت /t/، فتُلفظ ed مقطعاً إضافياً /id/.'],
          ] as [string, number, string][]).map(([w, a, why]) =>
            mcq(`How is the -ed ending of "${w}" pronounced?`, `كيف تُلفظ النهاية ed في كلمة "${w}"؟`, ['/t/', '/d/', '/id/'], a, why)),

          // ---- page 12a: past simple or past continuous (Mrs. Wilson) ----
          fill('I ___ a wonderful biology teacher, Mrs. Wilson.',
            '___ معلّمة أحياء رائعة، السيدة ويلسون.',
            'كانت لديّ معلّمة أحياء رائعة، السيدة ويلسون.',
            ['was having', 'had', 'have'], 1,
            'have بمعنى يملك فعل حالة لا يأتي في المستمر، والقصة في الماضي فنستخدم الماضي البسيط had.'),
          fill('She ___ us excited about the subject because she was so interested herself.',
            'كانت ___ متحمّسين للمادة لأنها هي نفسها كانت مهتمة بها جداً.',
            'كانت تجعلنا متحمّسين للمادة لأنها هي نفسها كانت مهتمة بها جداً.',
            ['made', 'was making', 'makes'], 0,
            'حقيقة عامة عن الماضي وليست حدثاً جارياً في لحظة معيّنة، فنستخدم الماضي البسيط made.'),
          fill('I remember one lesson in particular; we ___ different types of plants.',
            'أتذكّر درساً واحداً بالتحديد؛ كنّا ___ أنواعاً مختلفة من النباتات.',
            'أتذكّر درساً واحداً بالتحديد؛ كنّا ندرس أنواعاً مختلفة من النباتات.',
            ['studied', 'were studying', 'was studying'], 1,
            'هذا حدث خلفي كان جارياً عندما وقعت الأحداث الأخرى، فنستخدم الماضي المستمر were studying (مع we نستخدم were).'),
          fill('We were studying different types of plants, and Mrs. Wilson ___ the types of the flower.',
            'كنّا ندرس أنواعاً مختلفة من النباتات، وكانت السيدة ويلسون ___ أنواع الزهرة.',
            'كنّا ندرس أنواعاً مختلفة من النباتات، وكانت السيدة ويلسون تصف أنواع الزهرة.',
            ['described', 'were describing', 'was describing'], 2,
            'حدث خلفي جارٍ في الوقت نفسه، فنستخدم الماضي المستمر was describing (مع Mrs. Wilson المفرد نستخدم was).'),
          fill('She ___ a white flower, which was tulip, and then suddenly we noticed that she was crying!',
            'ثم ___ زهرة بيضاء، وكانت زهرة توليب، وفجأة لاحظنا أنها كانت تبكي!',
            'ثم التقطت زهرة بيضاء، وكانت زهرة توليب، وفجأة لاحظنا أنها كانت تبكي!',
            ['was picking up', 'picked up', 'picks up'], 1,
            'حدث قصير مكتمل ضمن سلسلة أحداث في القصة، فنستخدم الماضي البسيط picked up.'),
          fill('She picked up a white flower, which was tulip, and then suddenly we ___ that she was crying!',
            'التقطت زهرة بيضاء، وكانت زهرة توليب، وفجأة ___ أنها كانت تبكي!',
            'التقطت زهرة بيضاء، وكانت زهرة توليب، وفجأة لاحظنا أنها كانت تبكي!',
            ['noticed', 'were noticing', 'notice'], 0,
            'suddenly تدلّ على حدث مفاجئ قصير، فنستخدم الماضي البسيط noticed.'),
          fill('Suddenly we noticed that she ___!',
            'فجأة لاحظنا أنها ___!',
            'فجأة لاحظنا أنها كانت تبكي!',
            ['cried', 'was crying', 'is crying'], 1,
            'البكاء كان جارياً في لحظة ملاحظتنا له، فنستخدم الماضي المستمر was crying.'),
          fill('She ___ and said that sometimes nature was so beautiful that it just made her cry!',
            '___ وقالت إن الطبيعة أحياناً تكون جميلة جداً لدرجة أنها تجعلها تبكي!',
            'اعتذرت وقالت إن الطبيعة أحياناً تكون جميلة جداً لدرجة أنها تجعلها تبكي!',
            ['was apologising', 'apologised', 'apologises'], 1,
            'حدثان متتاليان مكتملان (اعتذرت ثم قالت)، فنستخدم الماضي البسيط apologised.'),
          fill('She apologised and ___ that sometimes nature was so beautiful that it just made her cry!',
            'اعتذرت و___ إن الطبيعة أحياناً تكون جميلة جداً لدرجة أنها تجعلها تبكي!',
            'اعتذرت وقالت إن الطبيعة أحياناً تكون جميلة جداً لدرجة أنها تجعلها تبكي!',
            ['said', 'was saying', 'says'], 0,
            'حدث مكتمل يلي الاعتذار مباشرة، فنستخدم الماضي البسيط said.'),
          fill('We ___ what to do at first, but it certainly made us think.',
            'في البداية ___ ماذا نفعل، لكن ذلك بالتأكيد جعلنا نفكّر.',
            'في البداية لم نعرف ماذا نفعل، لكن ذلك بالتأكيد جعلنا نفكّر.',
            ['didn’t know', 'weren’t knowing', 'don’t know'], 0,
            'know فعل حالة لا يأتي في المستمر، فنستخدم نفي الماضي البسيط didn’t know.'),
          fill('Somehow her enthusiasm ___ me, and I started to like biology.',
            'بطريقة ما، ___ حماسُها، وبدأت أحبّ علم الأحياء.',
            'بطريقة ما، ألهمني حماسُها، وبدأت أحبّ علم الأحياء.',
            ['was inspiring', 'inspired', 'inspires'], 1,
            'حدث مكتمل في الماضي أدّى إلى نتيجة، فنستخدم الماضي البسيط inspired.'),
          fill('Somehow her enthusiasm inspired me, and I ___ to like biology.',
            'بطريقة ما، ألهمني حماسُها، و___ أحبّ علم الأحياء.',
            'بطريقة ما، ألهمني حماسُها، وبدأت أحبّ علم الأحياء.',
            ['started', 'was starting', 'start'], 0,
            'حدث مكتمل يلي الحدث السابق، فنستخدم الماضي البسيط started.'),

          // ---- page 12b: correct the mistakes (or tick) ----
          fill('They went on a big tour of Britain. First, they stayed in London for a few days. Then they ___ Cambridge.',
            'قاموا بجولة كبيرة في بريطانيا. أولاً أقاموا في لندن بضعة أيام. ثم ___ كامبريدج.',
            'قاموا بجولة كبيرة في بريطانيا. أولاً أقاموا في لندن بضعة أيام. ثم زاروا كامبريدج.',
            ['were visiting', 'visited', 'had been visiting'], 1,
            'الصيغة المكتوبة "were visiting" خطأ: هذه أحداث متتالية مكتملة (First… Then…)، فنستخدم الماضي البسيط visited.'),
          fill('They ___ to Cambridge before, but they liked it so much that they decided to go back.',
            '___ إلى كامبريدج من قبل، لكنها أعجبتهم كثيراً فقرّروا العودة إليها.',
            'كانوا قد زاروا كامبريدج من قبل، لكنها أعجبتهم كثيراً فقرّروا العودة إليها.',
            ['went', 'had been', 'were going'], 1,
            'الصيغة المكتوبة "went" خطأ: الزيارة السابقة حدثت قبل حدث آخر في الماضي (before)، فنستخدم الماضي التام had been.'),
          fill('They had been to Cambridge before, but they liked it so much that they ___ to go back.',
            'كانوا قد زاروا كامبريدج من قبل، لكنها أعجبتهم كثيراً ف___ العودة إليها.',
            'كانوا قد زاروا كامبريدج من قبل، لكنها أعجبتهم كثيراً فقرّروا العودة إليها.',
            ['had decided', 'decided', 'were deciding'], 1,
            'الصيغة المكتوبة "had decided" خطأ: القرار جاء نتيجة لإعجابهم بها (liked)، أي بعده وليس قبله، فنستخدم الماضي البسيط decided.'),
          fill('I looked terrible when I ___ Joe last night because I had been running for over an hour and I was exhausted.',
            'كان شكلي فظيعاً عندما ___ جو الليلة الماضية لأنني كنت أركض لأكثر من ساعة وكنت منهكاً.',
            'كان شكلي فظيعاً عندما رأيت جو الليلة الماضية لأنني كنت أركض لأكثر من ساعة وكنت منهكاً.',
            ['had seen', 'saw', 'was seeing'], 1,
            'الصيغة "saw" صحيحة ✓: حدث قصير مكتمل الليلة الماضية، فنستخدم الماضي البسيط.'),
          fill('I looked terrible when I saw Joe last night because I ___ for over an hour and I was exhausted.',
            'كان شكلي فظيعاً عندما رأيت جو الليلة الماضية لأنني ___ لأكثر من ساعة وكنت منهكاً.',
            'كان شكلي فظيعاً عندما رأيت جو الليلة الماضية لأنني كنت أركض لأكثر من ساعة وكنت منهكاً.',
            ['had been running', 'have been running', 'ran'], 0,
            'الصيغة "had been running" صحيحة ✓: نشاط استمرّ مدة (for over an hour) قبل حدث في الماضي وترك أثراً (التعب)، فنستخدم الماضي التام المستمر.'),
          fill('When I ___ the noise at the window, I knew that someone was trying to break into the house.',
            'عندما ___ الضجة عند النافذة، عرفت أن أحداً كان يحاول اقتحام البيت.',
            'عندما سمعت الضجة عند النافذة، عرفت أن أحداً كان يحاول اقتحام البيت.',
            ['was hearing', 'had been hearing', 'heard'], 2,
            'الصيغة "heard" صحيحة ✓: حدث قصير مكتمل، وhear فعل حالة لا يأتي عادة في المستمر.'),
          fill('When I heard the noise at the window, I knew that someone ___ to break into the house.',
            'عندما سمعت الضجة عند النافذة، عرفت أن أحداً ___ اقتحام البيت.',
            'عندما سمعت الضجة عند النافذة، عرفت أن أحداً كان يحاول اقتحام البيت.',
            ['tried', 'was trying', 'has tried'], 1,
            'الصيغة المكتوبة "tried" خطأ: المحاولة كانت جارية لحظة سماع الضجة، فنستخدم الماضي المستمر was trying.'),
          fill('I knew her because I ___ her several times.',
            'كنت أعرفها لأنني ___ عدة مرات.',
            'كنت أعرفها لأنني كنت قد زرتها عدة مرات.',
            ['had been visiting', 'had visited', 'have visited'], 1,
            'الصيغة المكتوبة "had been visiting" خطأ: several times تدلّ على عدد مرات مكتملة لا على مدة، فنستخدم الماضي التام البسيط had visited.'),
          fill('The program that was stopped ___ well since 1945.',
            'البرنامج الذي أُوقف ___ بشكل جيد منذ عام 1945.',
            'البرنامج الذي أُوقف كان يعمل بشكل جيد منذ عام 1945.',
            ['has been working', 'had been working', 'was working'], 1,
            'الصيغة "had been working" صحيحة ✓: نشاط استمرّ منذ 1945 حتى لحظة في الماضي (عندما أُوقف)، فنستخدم الماضي التام المستمر.'),

          // ---- page 13c: complete the sentences with suitable past tense forms ----
          fill('When I arrived, ___.',
            'عندما وصلت، ___.',
            'عندما وصلت، كانت المحاضرة قد بدأت بالفعل.',
            ['the lecture has already started', 'the lecture had already started', 'the lecture already starts'], 1,
            'المحاضرة بدأت قبل وصولي، والحدث الأسبق في الماضي يأتي بالماضي التام had started.'),
          fill('Maha was playing the guitar when ___.',
            'كانت مها تعزف على الغيتار عندما ___.',
            'كانت مها تعزف على الغيتار عندما وصل أصدقاؤها.',
            ['her friends arrived', 'her friends have arrived', 'her friends arrive'], 0,
            'حدث طويل جارٍ (الماضي المستمر) يقطعه حدث قصير بعد when في الماضي البسيط: arrived.'),
          fill('By the time the boss left his office, ___.',
            'بحلول الوقت الذي غادر فيه المدير مكتبه، ___.',
            'بحلول الوقت الذي غادر فيه المدير مكتبه، كان كل الموظفين قد عادوا إلى بيوتهم.',
            ['all the employees go home', 'all the employees have gone home', 'all the employees had gone home'], 2,
            'بعد By the time + ماضٍ بسيط، نستخدم الماضي التام للحدث الذي وقع قبله: had gone.'),
          fill('The enemy retreated to the sea after ___.',
            'انسحب العدوّ إلى البحر بعد ___.',
            'انسحب العدوّ إلى البحر بعد أن خسر المعركة.',
            ['they had lost the battle', 'they have lost the battle', 'they lose the battle'], 0,
            'الخسارة وقعت قبل الانسحاب، فنستخدم الماضي التام بعد after: had lost.'),
          fill('He had been speaking for an hour before ___.',
            'كان يتحدّث منذ ساعة قبل أن ___.',
            'كان يتحدّث منذ ساعة قبل أن يبدأ الجمهور بالمغادرة.',
            ['the audience starts to leave', 'the audience started to leave', 'the audience has started to leave'], 1,
            'الماضي التام المستمر (had been speaking) يصف نشاطاً استمرّ حتى حدث في الماضي، وهذا الحدث بعد before يأتي بالماضي البسيط started.'),

          // ---- page 13a: Everyday English — put the conversation in order ----
          ...u2Order(),

          // ---- page 13b: Jack and Noah — complete with the phrases in the box ----
          fill('Jack: ___ the accident. How are you feeling now?',
            'جاك: ___ الحادث. كيف تشعر الآن؟',
            'جاك: أنا آسف بشأن الحادث. كيف تشعر الآن؟',
            ['I’ll never be able to', 'I’m sorry about', 'be feeling better soon', 'it would have been worse'], 1,
            'للتعبير عن المواساة نقول: I’m sorry about + اسم (the accident).'),
          fill('Jack: Oh dear. I suppose ___ if you’d landed on the motorway instead of in the trees?',
            'جاك: يا إلهي. أظنّ أن ___ لو أنك هبطت على الطريق السريع بدلاً من الأشجار؟',
            'جاك: يا إلهي. أظنّ أن الأمر كان سيكون أسوأ لو أنك هبطت على الطريق السريع بدلاً من الأشجار؟',
            ['be as bad as it seems', 'ever be all right', 'it would have been worse', 'I’m sorry about'], 2,
            'مع if you’d landed (الماضي التام) نستخدم الشرط الثالث: would have + التصريف الثالث: it would have been worse.'),
          fill('Noah: It couldn’t be worse. I’m sure ___ walk again.',
            'نوح: لا يمكن أن يكون أسوأ. أنا متأكد أنني ___ المشي مرة أخرى.',
            'نوح: لا يمكن أن يكون أسوأ. أنا متأكد أنني لن أستطيع أبداً المشي مرة أخرى.',
            ['I’ll never be able to', 'be feeling better soon', 'ever be all right', 'I’m sorry about'], 0,
            'بعد I’m sure نحتاج جملة كاملة، وبعد be able to يأتي المصدر walk: I’ll never be able to walk.'),
          fill('Jack: It is bad luck. But it may not ___.',
            'جاك: إنه حظ سيئ. لكنه قد لا ___.',
            'جاك: إنه حظ سيئ. لكنه قد لا يكون بالسوء الذي يبدو عليه.',
            ['ever be all right', 'be feeling better soon', 'I’ll never be able to', 'be as bad as it seems'], 3,
            'بعد may not يأتي المصدر be، وعبارة المواساة: it may not be as bad as it seems.'),
          fill('Noah: I won’t ___ and –if I am- I certainly won’t ever try hang-gliding again!',
            'نوح: لن ___ أبداً، وإن تعافيت فبالتأكيد لن أجرّب الطيران الشراعي مرة أخرى!',
            'نوح: لن أكون بخير أبداً، وإن تعافيت فبالتأكيد لن أجرّب الطيران الشراعي مرة أخرى!',
            ['be as bad as it seems', 'ever be all right', 'be feeling better soon', 'it would have been worse'], 1,
            'بعد won’t يأتي المصدر، وif I am تعني if I am all right، فالجواب: I won’t ever be all right.'),
          fill('Jack: You’ll ___ - and ready for another try.',
            'جاك: ستكون ___ ومستعداً لمحاولة أخرى.',
            'جاك: ستكون أفضل حالاً قريباً ومستعداً لمحاولة أخرى.',
            ['be feeling better soon', 'ever be all right', 'be as bad as it seems', 'I’m sorry about'], 0,
            'عبارة مواساة وتشجيع بعد You’ll: be feeling better soon (ستتحسّن قريباً).'),

          // ---- page 15a: writing — match each paragraph to its step ----
          ...([
            ['I know I will face many new challenges in college, but I also know that if I apply the lessons from my coach, I will be able to overcome any obstacle.', 2,
              'هذه الفقرة تختم بقوّة وتترك للقارئ فكرة يتأمّلها (كلمات المدرّب عن النهوض بعد السقوط)، فهي الخطوة 3.'],
            ['My uncle is always willing to help out a neighbour. I also believe it’s important to contribute to my community.', 1,
              'هذه الفقرة تعطي مثالاً من الشخص المؤثّر (العمّ يساعد الجيران) ثم تربطه بحياة الكاتب (المشاركة في خدمة المجتمع)، فهي الخطوة 2.'],
            ['My English teacher has inspired me to pursue a career in education.', 0,
              'هذه الفقرة تحدّد من هو الشخص المؤثّر وماذا تعلّم الكاتب منه، فهي الخطوة 1.'],
          ] as [string, number, string][]).map(([p, a, why]) =>
            mcq(`Which step does this paragraph match? "${p}"`, 'أيّ خطوة تناسب هذه الفقرة؟',
              ['Step 1: Identify who has an impact on you', 'Step 2: Find some examples from this person and then try to connect them back to you', 'Step 3: End strong by adding something for the reader to think about.'], a, why)),
        ],
      },
      compositions: [
        {
          source: 'book',
          topic: 'Write a composition of no more than 100 words about a personal experience in which you failed but then you could achieve your target.',
          topicAr: 'اكتب موضوعاً لا يزيد على 100 كلمة عن تجربة شخصية فشلت فيها ثم استطعت أن تحقّق هدفك.',
          words: 100,
          points: ['Name the problem', 'Steps you followed to help you', 'Getting help from others if any', 'Advice to people of your own age'],
          pointsAr: ['اذكر المشكلة', 'الخطوات التي اتّبعتها لتساعد نفسك', 'المساعدة التي حصلت عليها من الآخرين إن وُجدت', 'نصيحة لمن هم في عمرك'],
          plan: [
            { en: 'Name the problem: when and how you failed, and how you felt.', ar: 'اذكر المشكلة: متى وكيف فشلت، وبماذا شعرت.' },
            { en: 'The steps you followed: set goals and take action (First…, Then…).', ar: 'الخطوات التي اتّبعتها: حدّد أهدافك وابدأ العمل (First…, Then…).' },
            { en: 'Help from others: a teacher, a friend or your family.', ar: 'المساعدة من الآخرين: معلّم أو صديق أو أسرتك.' },
            { en: 'The result and your advice to people of your age.', ar: 'النتيجة ونصيحتك لمن هم في عمرك.' },
          ],
          phrases: [
            { en: 'I failed my first … test.', ar: 'رسبت في أول اختبار … لي.' },
            { en: 'My dream was dead in the water.', ar: 'بدا حلمي فاشلاً لا أمل فيه.' },
            { en: 'I did not give up.', ar: 'لم أستسلم.' },
            { en: 'set clear, achievable goals', ar: 'يضع أهدافاً واضحة قابلة للتحقيق' },
            { en: 'take action', ar: 'يبدأ العمل / يتّخذ خطوات' },
            { en: 'perseverance', ar: 'المثابرة' },
            { en: 'self-confidence', ar: 'الثقة بالنفس' },
            { en: 'carry on', ar: 'يستمرّ' },
            { en: 'ace a test', ar: 'يتفوّق في الاختبار' },
            { en: 'Failure acts as a stepping-stone towards success.', ar: 'الفشل نقطة انطلاق نحو النجاح.' },
            { en: 'First, … Then, … After three months, …', ar: 'أولاً… ثم… وبعد ثلاثة أشهر…' },
            { en: 'My advice to people of my age is …', ar: 'نصيحتي لمن هم في عمري هي …' },
          ],
          model: 'Last year, I failed my first English test. I got only 40%, and I felt that my dream of studying medicine was dead in the water. However, I did not give up. First, I set clear, achievable goals: I learned ten new words and read a short text every day. Then, I asked my English teacher for help, and she gave me useful advice and extra exercises. After three months, I aced the test and got 90%. My advice to people of my age is: failure is a stepping-stone towards success, so carry on and never give up.',
          modelAr: 'في السنة الماضية، رسبت في أول اختبار لغة إنجليزية لي. حصلت على 40% فقط، وشعرت أن حلمي بدراسة الطب أصبح بلا أمل. لكنني لم أستسلم. أولاً، وضعت أهدافاً واضحة قابلة للتحقيق: كنت أتعلّم عشر كلمات جديدة وأقرأ نصاً قصيراً كل يوم. ثم طلبت المساعدة من معلّمة اللغة الإنجليزية، فأعطتني نصائح مفيدة وتمارين إضافية. وبعد ثلاثة أشهر تفوّقت في الاختبار وحصلت على 90%. نصيحتي لمن هم في عمري: الفشل نقطة انطلاق نحو النجاح، فاستمرّوا ولا تستسلموا أبداً.',
          checklistAr: [
            'هل ذكرت المشكلة (الفشل) بوضوح في البداية؟',
            'هل وصفت الخطوات التي اتّبعتها بترتيب واضح (First, Then, After…)؟',
            'هل ذكرت المساعدة التي حصلت عليها من الآخرين؟',
            'هل ختمت بنصيحة لمن هم في عمرك؟',
            'هل استخدمت أزمنة الماضي بشكل صحيح ومفردات الوحدة وتعابيرها (give up, ace a test, dead in the water…)؟',
            'هل الموضوع في حدود 100 كلمة، وراجعت القواعد والتهجئة وعلامات الترقيم؟',
          ],
        },
        {
          source: 'workbook',
          topic: 'Write an essay about someone who has influenced you to be the best version.',
          topicAr: 'اكتب مقالاً عن شخص أثّر فيك لتكون أفضل نسخة من نفسك.',
          words: 100,
          points: [
            'Who has been an influential person in your life?',
            'What do you admire the most about this person?',
            'What specific things have you learned from this person?',
            'Which of his traits (e.g., special talents, skills, way of treating others) do you hope to have yourself one day?',
            'How has your life changed since meeting your role model?',
          ],
          pointsAr: [
            'من الشخص الذي كان له تأثير في حياتك؟',
            'ما أكثر ما تُعجب به في هذا الشخص؟',
            'ما الأشياء المحدّدة التي تعلّمتها من هذا الشخص؟',
            'أيّ صفاته (مثل المواهب الخاصة والمهارات وطريقة معاملة الآخرين) تأمل أن تمتلكها يوماً ما؟',
            'كيف تغيّرت حياتك منذ أن عرفت قدوتك؟',
          ],
          plan: [
            { en: 'Step 1: identify who has an impact on you — answer at least three of the questions (who, what you admire, what you learned).', ar: 'الخطوة 1: حدّد الشخص المؤثّر فيك — أجب عن ثلاثة أسئلة على الأقل (من هو، ماذا تُعجب فيه، ماذا تعلّمت منه).' },
            { en: 'Step 2: give examples from this person, then connect them back to your own life.', ar: 'الخطوة 2: أعطِ أمثلة من حياة هذا الشخص ثم اربطها بحياتك أنت.' },
            { en: 'Step 3: end strong by adding something for the reader to think about.', ar: 'الخطوة 3: اختم بقوّة بفكرة يتأمّلها القارئ.' },
          ],
          phrases: [
            { en: 'The most influential person in my life is …', ar: 'أكثر شخص أثّر في حياتي هو …' },
            { en: 'What I admire most about him is …', ar: 'أكثر ما أُعجب به فيه هو …' },
            { en: 'role model', ar: 'قدوة' },
            { en: 'He has inspired me to …', ar: 'لقد ألهمني أن …' },
            { en: 'perseverance', ar: 'المثابرة' },
            { en: 'he never gave up', ar: 'لم يستسلم أبداً' },
            { en: 'always willing to help out a neighbour', ar: 'مستعدّ دائماً لمساعدة الجار' },
            { en: 'overcome any obstacle', ar: 'يتغلّب على أي عقبة' },
            { en: 'live up to my potential', ar: 'أرتقي إلى مستوى قدراتي' },
            { en: 'Failure acts as a stepping-stone towards success.', ar: 'الفشل نقطة انطلاق نحو النجاح.' },
          ],
          model: 'The most influential person in my life is my grandfather. What I admire most about him is his perseverance. He lost his small shop twice, but he never gave up and started again each time.\nFrom him, I have learned to be patient and to work hard. When I failed my first maths exam, I remembered his story. Instead of crying, I made a plan, studied every evening and finally passed with a high mark. I also hope to have his kindness one day; he is always willing to help out a neighbour.\nToday, I know that failure is a stepping-stone towards success. With a role model like mine, you can overcome any obstacle and live up to your potential.',
          modelAr: 'أكثر شخص أثّر في حياتي هو جدّي. وأكثر ما أُعجب به فيه مثابرته؛ فقد خسر دكّانه الصغير مرتين، لكنه لم يستسلم أبداً وبدأ من جديد في كل مرة.\nتعلّمت منه أن أكون صبوراً وأن أعمل بجدّ. عندما رسبت في أول امتحان رياضيات لي تذكّرت قصته. وبدلاً من البكاء وضعت خطة، ودرست كل مساء، ونجحت في النهاية بعلامة عالية. وأتمنّى أيضاً أن أمتلك طيبته يوماً ما؛ فهو مستعدّ دائماً لمساعدة الجيران.\nاليوم أعرف أن الفشل نقطة انطلاق نحو النجاح. ومع قدوة مثل قدوتي، تستطيع أن تتغلّب على أي عقبة وأن ترتقي إلى مستوى قدراتك.',
          checklistAr: [
            'هل حدّدت الشخص المؤثّر وأجبت عن ثلاثة من الأسئلة الخمسة على الأقل؟',
            'هل أعطيت مثالاً من حياة هذا الشخص وربطته بحياتك؟',
            'هل ختمت بقوّة بفكرة يتأمّلها القارئ؟',
            'هل استخدمت المضارع التام (has inspired, have learned) والماضي البسيط بشكل صحيح؟',
            'هل كل فقرة تدور حول فكرة واحدة وتبدأ بجملة رئيسية؟',
            'هل راجعت التهجئة والحروف الكبيرة وعلامات الترقيم؟',
          ],
        },
      ],
      translations: [
        { en: 'One of the most destructive moments in our lives is failure.', ar: 'من أكثر اللحظات تدميراً في حياتنا الفشل.' },
        { en: 'When we fail, life turns upside down.', ar: 'عندما نفشل تنقلب الحياة رأساً على عقب.' },
        { en: 'Everything seems to disappear into thin air.', ar: 'يبدو كل شيء وكأنه يتلاشى في الهواء.' },
        { en: 'They don’t know that we can learn more about our lives when we fail.', ar: 'إنهم لا يعرفون أننا نستطيع أن نتعلّم المزيد عن حياتنا عندما نفشل.' },
        { en: 'Thomas Edison is by far one of the most famous inventors in history.', ar: 'توماس إديسون هو بلا منازع واحد من أشهر المخترعين في التاريخ.' },
        { en: 'He holds 1,093 patents to his name.', ar: 'يحمل 1093 براءة اختراع باسمه.' },
        { en: 'He created the Walt Disney Company after his own namesake.', ar: 'أسّس شركة والت ديزني التي تحمل اسمه.' },
        { en: 'They went on a big tour of Britain.', ar: 'قاموا بجولة كبيرة في بريطانيا.' },
        { en: 'The program that was stopped had been working well since 1945.', ar: 'البرنامج الذي أُوقف كان يعمل بشكل جيد منذ عام 1945.' },
        { en: 'My boss offered me a promotion, and I took it.', ar: 'عرض عليّ مديري ترقية، فقبلتها.' },
        { en: 'You have no idea how happy I am for you.', ar: 'لا تتخيّل كم أنا سعيد من أجلك.' },
        { en: 'My uncle is always willing to help out a neighbour.', ar: 'عمّي مستعدّ دائماً لمساعدة الجيران.' },
        { en: 'My English teacher has inspired me to pursue a career in education.', ar: 'ألهمتني معلّمة اللغة الإنجليزية أن أسعى إلى مهنة في التعليم.' },
        { en: 'Timing also is a crucial ingredient to success.', ar: 'التوقيت أيضاً عنصر حاسم في النجاح.' },
        { en: 'The golden rule to achieve success is to keep learning.', ar: 'القاعدة الذهبية لتحقيق النجاح هي الاستمرار في التعلّم.' },
        { en: 'When she came into the room, the burglar had already left.', ar: 'عندما دخلت الغرفة، كان اللصّ قد غادر بالفعل.' },
      ],
    },
  },
}
