// Adversarial QA of the billing module (review pass): validation edge cases, double submit, Escape/Enter, refunds,
// long names, deleted references, permissions, read-only, phone 390×844, English, and laptop widths with SYP amounts.
// Usage: npx vite build --outDir /tmp/dist-billing-r && QA_DIST=/tmp/dist-billing-r QA_PORT=4355 QA_SHOTS=qa-shots/billing-review node scripts/qa/billing-review.mjs [a|b|c|d]
import { startServer, openBrowser, seedAndLogin, shot, BASE } from './lib.mjs'

const only = process.argv.slice(2)
const want = s => !only.length || only.includes(s)
const failures = []
const consoleErrors = []
const check = (cond, msg) => { if (!cond) { failures.push(msg); console.error('FAIL:', msg) } else console.log('ok:', msg) }
const wait = (page, ms = 350) => page.waitForTimeout(ms)
const go = async (page, hash) => { await page.goto(`${BASE}/index.html#${hash}`); await page.waitForLoadState('networkidle'); await wait(page, 500) }
const q = (page, fn, arg) => page.evaluate(fn, arg)
async function overflow(page, label) {
  const r = await page.evaluate(() => {
    const out = { sw: document.documentElement.scrollWidth, w: window.innerWidth, inner: [] }
    for (const el of document.querySelectorAll('.modal, .modal-body, .bl-sheet, .card, .bl-mcard, .bl-target, .bl-acct, .stat-card, .page-header, .bl-acct-cell')) {
      const cs = getComputedStyle(el)
      if (cs.overflowX === 'auto' || cs.overflowX === 'scroll') continue
      if (el.scrollWidth > el.clientWidth + 1) out.inner.push(`${el.className.toString().slice(0, 40)} ${el.scrollWidth}>${el.clientWidth}`)
    }
    for (const el of document.querySelectorAll('.bl-acct-cell .money, .stat-value .money, .bl-target-end .money')) {
      if (el.scrollWidth > el.clientWidth + 1) out.inner.push(`money cut ${el.textContent}`)
    }
    return out
  })
  check(r.sw <= r.w, `${label}: no page overflow (${r.sw} <= ${r.w})`)
  check(r.inner.length === 0, `${label}: no clipped/overflowing boxes ${r.inner.slice(0, 4).join(' | ')}`)
}
async function snap(page, name, opts) { await overflow(page, name); await shot(page, name, opts) }
function watch(page, tag) {
  page.on('pageerror', e => consoleErrors.push(`[${tag}] ${e.message}`))
  page.on('console', m => { if (m.type() === 'error') consoleErrors.push(`[${tag}] ${m.text()}`) })
}
async function printShot(page, name, modal = false) {
  const vp = page.viewportSize()
  if (modal) await page.evaluate(() => document.body.classList.add('bl-printing'))
  await page.setViewportSize({ width: 720, height: vp.height })
  await page.emulateMedia({ media: 'print' })
  await wait(page, 300)
  await shot(page, name, { full: true })
  await page.emulateMedia({ media: 'screen' })
  await page.setViewportSize(vp)
  if (modal) await page.evaluate(() => document.body.classList.remove('bl-printing'))
  await wait(page, 150)
}
const dismissToasts = page => page.evaluate(() => document.querySelectorAll('.toast-stack .toast button[aria-label], .toast-stack button.toast-x').forEach(b => b.click())).catch(() => {})
const LONG_AR = 'عبد الرحمن محمد سعيد الدين الحسيني الأنصاري القرشي آل عبد الكريم الشامي الدمشقي'
const LONG_EN = 'Abdulrahman Mohammad Saeed Aldeen Alhusseini Alansari Alqurashi Al Abdulkarim Alshami'

async function seed(page, lang = 'ar', { decimals = 0, tax = 0 } = {}) {
  return q(page, async ({ lang, LONG_AR, LONG_EN, decimals, tax }) => {
    const db = window.__dentora.db
    const now = new Date().toISOString()
    await db.clinic.update('clinic', { email: 'info@smile-dental.sy', invoiceFooter: lang === 'ar' ? 'تُستحق الفواتير خلال 30 يوماً.' : 'Invoices are due within 30 days.', currencyDecimals: decimals, taxPercent: tax })
    const names = lang === 'ar' ? ['محمد العلي', 'رنا الحسن', LONG_AR, 'بلا هاتف'] : ['Mohammad Ali', 'Rana Hassan', LONG_EN, 'No Phone']
    await db.patients.bulkPut(names.map((name, i) => ({ id: `pat-${i + 1}`, fileNo: 101 + i, name, gender: 'male', phone: i === 3 ? undefined : `0944${String(100000 + i)}`, allergies: [], chronicDiseases: [], medications: [], tags: [], archived: false, createdAt: now, updatedAt: now, lastVisit: now })))
    await db.procedures.bulkPut([
      { id: 'proc-fill', code: 'D2391', name: 'حشوة كومبوزيت', nameEn: 'Composite filling', category: 'restorative', price: 60, active: true, sortOrder: 1, createdAt: now, updatedAt: now },
      { id: 'proc-rct', code: 'D3330', name: 'معالجة لبية', nameEn: 'Root canal', category: 'endodontic', price: 180, active: true, sortOrder: 2, createdAt: now, updatedAt: now },
    ])
    const tr = (id, pid, tooth, price, discount = 0) => ({ id, patientId: pid, procedureId: 'proc-fill', procedureName: lang === 'ar' ? 'حشوة كومبوزيت' : 'Composite filling', tooth, price, discount, status: 'completed', doctorId: 'u-admin', completedAt: now, createdAt: now, updatedAt: now })
    await db.treatments.bulkPut([tr('tr-1', 'pat-1', 36, 60), tr('tr-2', 'pat-1', 46, 180, 20), tr('tr-3', 'pat-3', 11, 333.33), tr('tr-4', 'pat-3', 21, 1250000)])
  }, { lang, LONG_AR, LONG_EN, decimals, tax })
}
const invoices = page => q(page, async () => window.__dentora.db.invoices.toArray())
const payments = page => q(page, async () => window.__dentora.db.payments.toArray())
const isoInstant = s => typeof s === 'string' && /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}/.test(s)

const server = await startServer()
try {
  // ======================= A. desktop Arabic: adversarial flows =======================
  if (want('a')) {
    const { browser, page } = await openBrowser({ lang: 'ar' })
    watch(page, 'a')
    await seedAndLogin(page, { lang: 'ar' })
    await seed(page, 'ar', { decimals: 0, tax: 5 })

    // --- invoice form: validation edge cases ---
    await go(page, '/invoices?patient=pat-1&new=1')
    await page.getByRole('button', { name: /إضافة المحدد/ }).click()
    await wait(page)
    await page.getByLabel('الضريبة %').fill('150')
    await page.getByLabel('خصم على الفاتورة').fill('-10')
    await page.getByRole('button', { name: 'إصدار الفاتورة' }).click()
    await wait(page, 500)
    await snap(page, 'a-01-form-tax-discount-errors')
    check((await invoices(page)).length === 0, 'form: tax 150% / negative discount are not saved')
    check(await page.getByText('نسبة الضريبة بين 0 و100').count() > 0, 'form: a message explains the tax error')
    check(await page.getByText('لا يمكن أن يكون الخصم سالباً').count() > 0, 'form: a message explains the negative discount')
    await page.getByLabel('الضريبة %').fill('5')
    await page.getByLabel('خصم على الفاتورة').fill('')
    const dates = page.locator('.bl-form-top input[type="date"]')
    await dates.nth(1).fill('2020-01-01')
    await page.getByRole('button', { name: 'سطر حر' }).click()
    const free = page.locator('.bl-line').last()
    await free.locator('input').nth(0).fill('بند اختبار')
    await free.locator('input').nth(2).fill('0')
    await free.locator('input').nth(3).fill('-5')
    await page.getByRole('button', { name: 'إصدار الفاتورة' }).click()
    await wait(page, 500)
    await snap(page, 'a-02-form-line-negative')
    check((await invoices(page)).length === 0, 'form: qty 0 / negative price rejected')
    check(await page.locator('.bl-line-err').count() > 0, 'form: line error message shown')
    check(await page.getByText('تاريخ الاستحقاق يسبق تاريخ الإصدار').count() > 0, 'form: due date before issue date is flagged')
    await free.locator('input').nth(2).fill('1')
    await free.locator('input').nth(3).fill('15')
    await dates.nth(1).fill('')
    // clearing the tax field keeps it cleared (the clinic default does not jump back)
    await page.getByLabel('الضريبة %').fill('')
    await wait(page, 200)
    check(await page.getByLabel('الضريبة %').inputValue() === '', 'form: a cleared tax field stays cleared')
    await page.getByLabel('الضريبة %').fill('5')
    // Escape with unsaved lines
    await page.keyboard.press('Escape')
    await wait(page, 400)
    const formStillOpen = await page.locator('.bl-form').count()
    const confirmShown = await page.getByRole('dialog').filter({ hasText: /تجاهل هذه الفاتورة/ }).count()
    check(formStillOpen > 0 && confirmShown > 0, `form: Escape with unsaved lines asks before discarding (open=${formStillOpen}, confirm=${confirmShown})`)
    await snap(page, 'a-03-form-escape')
    if (confirmShown) { await page.keyboard.press('Escape'); await wait(page, 300) }
    check(await page.locator('.bl-form').count() > 0 && await page.getByRole('dialog').filter({ hasText: /تجاهل هذه الفاتورة/ }).count() === 0, 'form: Escape on the prompt keeps the form open')
    const totalsText = await page.locator('.bl-tp-total').innerText()
    await page.getByRole('button', { name: 'إصدار الفاتورة' }).dblclick()
    await page.waitForURL(/#\/invoices\/[^?]+$/, { timeout: 5000 }).catch(() => {})
    await wait(page, 800)
    let inv = await invoices(page)
    check(inv.length === 1, `issue: double click creates one invoice (${inv.length})`)
    const counter = await q(page, async () => (await window.__dentora.db.clinic.get('clinic')).nextInvoiceNumber)
    check(counter === 2, `issue: counter advanced once (${counter})`)
    const i1 = inv[0]
    check(i1 && i1.total === 247 && i1.tax === 12, `issue: 0-decimal currency → whole tax and total (${i1?.tax} ${i1?.total}; on screen ${totalsText.replace(/\n/g, ' ')})`)
    check(i1 && isoInstant(i1.createdAt) && isoInstant(i1.updatedAt) && i1.createdBy === 'u-admin', 'issue: createdAt/updatedAt/createdBy set')
    check(i1 && i1.items.every(it => it.id && typeof it.total === 'number'), 'issue: items have ids and totals')
    check(i1 && i1.items.filter(it => it.treatmentItemId).length === 2, 'issue: two treatment lines linked')
    const trs = await q(page, async () => window.__dentora.db.treatments.where('patientId').equals('pat-1').toArray())
    check(trs.every(t => t.invoiceId === i1?.id), 'issue: treatments carry the invoiceId')
    let acts = await q(page, async () => window.__dentora.db.activity.toArray())
    check(acts.filter(a => a.type === 'invoice' && a.action === 'create').length === 1, `issue: exactly one activity row (${acts.filter(a => a.type === 'invoice').length})`)
    check(acts.every(a => !a.message.includes('⁠')), 'activity: no invisible joiners in stored messages')
    await snap(page, 'a-04-invoice-issued', { full: true })

    // --- payment: Enter submits, double Enter must not double-pay ---
    await page.getByRole('button', { name: 'تسجيل دفعة' }).first().click()
    await wait(page, 700)
    const pre = await page.locator('.bl-amount input').inputValue()
    check(Number(pre) === i1.total, `payment: prefilled with the balance (${pre} vs ${i1.total})`)
    await page.locator('.bl-amount input').fill('100')
    await page.locator('.bl-amount input').press('Enter')
    await page.locator('.bl-amount input').press('Enter').catch(() => {})
    await wait(page, 900)
    let pays = await payments(page)
    check(pays.length === 1, `payment: double Enter records one payment (${pays.length})`)
    check(pays[0] && pays[0].receivedBy === 'u-admin' && isoInstant(pays[0].createdAt) && pays[0].invoiceId === i1.id, 'payment: receivedBy/createdAt/invoiceId stored')
    let i1b = (await invoices(page))[0]
    check(i1b.paid === 100 && i1b.status === 'partial' && i1b.updatedAt >= i1.updatedAt, `payment: invoice recomputed to partial (${i1b.paid} ${i1b.status})`)
    acts = await q(page, async () => window.__dentora.db.activity.toArray())
    check(acts.filter(a => a.type === 'payment').length === 1, 'payment: one activity row')
    await snap(page, 'a-05-after-payment')

    // --- payment validation: zero, negative, Escape closes ---
    await page.getByRole('button', { name: 'تسجيل دفعة' }).first().click()
    await wait(page, 600)
    await page.locator('.bl-amount input').fill('0')
    await page.locator('.bl-amount input').press('Enter')
    await wait(page)
    check(await page.getByText('يجب أن يكون أكبر من صفر').count() > 0 && (await payments(page)).length === 1, 'payment: zero amount rejected')
    await page.locator('.bl-amount input').fill('-30')
    await page.locator('.bl-amount input').press('Enter')
    await wait(page)
    check((await payments(page)).length === 1, 'payment: negative typed amount rejected (use the refund switch)')
    await snap(page, 'a-06-payment-invalid')
    await page.keyboard.press('Escape')
    await wait(page, 400)
    check(await page.locator('.bl-pay').count() === 0, 'payment: Escape closes the modal')

    // --- refund on the invoice → back to unpaid, the rest off the account ---
    await page.getByRole('button', { name: 'تسجيل دفعة' }).first().click()
    await wait(page, 600)
    await page.locator('.bl-refund-row .track').click()
    await page.locator('.bl-amount input').fill('150')
    await wait(page)
    await snap(page, 'a-07-refund-split')
    await page.getByRole('button', { name: 'حفظ الاسترداد' }).click()
    await wait(page, 800)
    pays = await payments(page)
    const onInv = pays.filter(p => p.invoiceId === i1.id).reduce((a, p) => a + p.amount, 0)
    check(onInv === 0 && pays.some(p => !p.invoiceId && p.amount === -50), `refund: 100 back off the invoice, 50 off the account (${JSON.stringify(pays.map(p => [p.invoiceId ? 'inv' : 'acc', p.amount]))})`)
    i1b = (await invoices(page))[0]
    check(i1b.paid === 0 && i1b.status === 'unpaid', `refund: invoice back to unpaid (${i1b.paid} ${i1b.status})`)
    const toastBtn = page.getByRole('button', { name: 'طباعة الإيصال' })
    if (await toastBtn.count()) {
      await toastBtn.first().click()
      await wait(page, 600)
      await snap(page, 'a-08-refund-receipt')
      await page.keyboard.press('Escape')
      await wait(page, 400)
      check(await page.locator('.bl-receipt').count() === 0, 'receipt: Escape closes it')
    } else check(false, 'refund: toast offers the receipt')

    // --- patient picker: Escape closes only the dropdown; Enter picks ---
    await go(page, '/payments')
    await page.getByRole('button', { name: 'دفعة جديدة' }).first().click()
    await wait(page, 600)
    await page.getByPlaceholder('ابحث عن مريض بالاسم أو رقم الملف أو الهاتف…').fill('عبد')
    await wait(page)
    await page.keyboard.press('Escape')
    await wait(page)
    check(await page.locator('.bl-dropdown').count() === 0 && await page.locator('.bl-pay').count() === 1, 'picker: Escape closes the dropdown, not the modal')
    await page.getByPlaceholder('ابحث عن مريض بالاسم أو رقم الملف أو الهاتف…').fill('عبد الرحمن')
    await wait(page)
    await page.keyboard.press('ArrowDown')
    await page.keyboard.press('Enter')
    await wait(page, 600)
    await snap(page, 'a-09-payment-long-name')
    check(await page.locator('.bl-pay').count() === 1 && (await payments(page)).length === pays.length, 'picker: Enter picks the patient without submitting')
    await page.keyboard.press('Escape')

    // --- long name invoice + big numbers ---
    await go(page, '/invoices?patient=pat-3&new=1')
    await page.getByRole('button', { name: /إضافة المحدد/ }).click()
    await wait(page)
    await snap(page, 'a-10-form-long-name')
    await page.getByRole('button', { name: 'إصدار الفاتورة' }).click()
    await page.waitForURL(/#\/invoices\/[^?]+$/, { timeout: 5000 }).catch(() => {})
    await wait(page, 700)
    await snap(page, 'a-11-invoice-long-name', { full: true })
    await printShot(page, 'a-12-invoice-long-name-print')
    await go(page, '/invoices')
    const tw = await page.evaluate(() => { const w = document.querySelector('.bl-table'); return { sw: w.scrollWidth, cw: w.clientWidth } })
    check(tw.sw <= tw.cw + 1, `list: a long name does not push columns out of the card (${tw.sw} <= ${tw.cw})`)
    await snap(page, 'a-13-list-long-name')

    // --- draft: review & issue from the invoice page ---
    await go(page, '/invoices?patient=pat-2&new=1')
    await page.getByRole('button', { name: 'من قائمة الإجراءات' }).click()
    await page.locator('.bl-panel-item', { hasText: 'معالجة لبية' }).click()
    await page.getByRole('button', { name: 'حفظ كمسودة' }).click()
    await wait(page, 700)
    let draft = (await invoices(page)).find(i => i.status === 'draft')
    check(draft && draft.number === 'DRAFT', 'draft: saved with DRAFT')
    await go(page, `/invoices/${draft.id}`)
    await page.getByRole('button', { name: 'مراجعة وإصدار' }).click()
    await wait(page, 600)
    await page.getByRole('dialog').getByRole('button', { name: 'إصدار الفاتورة' }).click()
    await wait(page, 800)
    draft = (await invoices(page)).find(i => i.id === draft.id)
    check(draft.status === 'unpaid' && draft.number === 'INV-000003', `draft → issued gets the next number (${draft.number} ${draft.status})`)

    // --- a treatment billed elsewhere while the form is open ---
    await q(page, async () => { const db = window.__dentora.db; const now = new Date().toISOString(); await db.treatments.put({ id: 'tr-9', patientId: 'pat-1', procedureName: 'تنظيف', price: 40, discount: 0, status: 'completed', completedAt: now, createdAt: now, updatedAt: now }) })
    await go(page, '/invoices?patient=pat-1&new=1')
    await page.getByRole('button', { name: /إضافة المحدد/ }).click()
    await wait(page)
    await q(page, async () => { await window.__dentora.db.treatments.update('tr-9', { invoiceId: 'inv-elsewhere' }) })
    const before = (await invoices(page)).length
    await page.getByRole('button', { name: 'إصدار الفاتورة' }).click()
    await wait(page, 700)
    check((await invoices(page)).length === before && await page.getByText(/أصبح مفوتراً في فاتورة أخرى/).count() > 0, 'double billing: refused with an explanation')
    await snap(page, 'a-13b-already-billed')
    check((await q(page, async () => (await window.__dentora.db.clinic.get('clinic')).nextInvoiceNumber)) === 4, 'double billing: no invoice number consumed')
    await page.getByRole('button', { name: 'إلغاء' }).click()
    await wait(page, 300)
    await page.getByRole('dialog').getByRole('button', { name: 'تجاهل' }).click()
    await wait(page, 300)

    // --- deleting referenced records ---
    await q(page, async () => { const db = window.__dentora.db; await db.users.delete('u-doc2'); await db.procedures.delete('proc-rct') })
    await q(page, async () => { await window.__dentora.db.patients.delete('pat-2') })
    await go(page, `/invoices/${draft.id}`)
    await snap(page, 'a-14-invoice-orphan', { full: true })
    check(await page.locator('.bl-sheet').count() === 1, 'orphan: the invoice of a deleted patient still opens')
    await go(page, '/invoices')
    await snap(page, 'a-15-list-orphan')
    await page.locator('.bl-table tbody tr', { hasText: 'INV-000003' }).locator('.bl-menu-btn').click()
    await page.getByRole('menuitem', { name: 'تسجيل دفعة' }).click()
    await wait(page, 700)
    await snap(page, 'a-16-pay-orphan')
    const pc = (await payments(page)).length
    await page.getByRole('button', { name: 'حفظ الدفعة' }).click()
    await wait(page, 700)
    check((await payments(page)).length === pc + 1, 'orphan: a payment can still be recorded on the invoice')
    await go(page, '/payments')
    await page.getByRole('tab', { name: 'هذا الشهر' }).click()
    await wait(page)
    await snap(page, 'a-17-ledger')

    // --- custom period: typing the end year must not jump the fields ---
    await go(page, '/invoices')
    await page.getByRole('tab', { name: 'مخصص' }).click()
    await wait(page)
    const r = page.locator('.bl-range input')
    const fromBefore = await r.nth(0).inputValue()
    await r.nth(1).click()
    await page.keyboard.press('End')
    await r.nth(1).pressSequentially('2027', { delay: 40 }).catch(() => {})
    await wait(page)
    check(await r.nth(0).inputValue() === fromBefore, `period: typing the end date keeps the start date (${fromBefore} → ${await r.nth(0).inputValue()}, end ${await r.nth(1).inputValue()})`)
    await r.nth(0).fill('2030-01-01')
    await wait(page)
    await snap(page, 'a-18-custom-backwards')
    const per = await q(page, () => JSON.parse(localStorage.getItem('dentora.billing.period.invoices') || '{}'))
    check(per.from <= per.to, `period: backwards range is stored the right way round (${per.from} → ${per.to})`)
    await page.getByRole('tab', { name: 'هذا الشهر' }).click()

    // --- assistant (no billing permission) ---
    await q(page, async () => { const db = window.__dentora.db; const now = new Date().toISOString(); const u = await db.users.get('u-admin'); await db.users.put({ ...u, id: 'u-asst', name: 'مساعدة', role: 'assistant', createdAt: now, updatedAt: now }); localStorage.setItem('dentora.session', 'u-asst') })
    await go(page, '/invoices')
    await page.reload(); await wait(page, 800)
    await snap(page, 'a-19-assistant')
    check(await page.getByRole('button', { name: 'فاتورة جديدة' }).count() === 0 && await page.getByText('لا تملك صلاحية الوصول إلى الفواتير').count() > 0, 'permissions: an assistant sees the no-access screen')
    await go(page, `/invoices/${draft.id}`)
    check(await page.locator('.bl-sheet').count() === 0, 'permissions: an assistant cannot open an invoice')
    await q(page, () => localStorage.setItem('dentora.session', 'u-admin'))

    // --- read-only (expired trial): Enter in the payment form must not save ---
    await go(page, '/invoices')
    await page.reload(); await wait(page, 600)
    await q(page, async () => { await window.__dentora.db.settings.put({ key: 'installedAt', value: new Date(Date.now() - 40 * 86400000).toISOString() }); await window.__dentora.db.settings.delete('license') })
    await page.reload(); await wait(page, 900)
    await go(page, '/patients/pat-1?tab=billing')
    const roCount = (await payments(page)).length
    await page.evaluate(() => { const b = [...document.querySelectorAll('.bl-tab-actions button')]; b.forEach(x => x.removeAttribute('disabled')); b[1]?.click() })
    await wait(page, 700)
    if (await page.locator('.bl-amount input').count()) {
      await page.locator('.bl-amount input').fill('10')
      await page.locator('.bl-amount input').press('Enter')
      await wait(page, 600)
    }
    check((await payments(page)).length === roCount, 'read-only: Enter does not record a payment')
    await browser.close()
  }

  // ======================= B. phone 390×844 =======================
  if (want('b')) {
    const { browser, page } = await openBrowser({ mobile: true, width: 390, height: 844, lang: 'ar' })
    watch(page, 'b')
    await seedAndLogin(page, { lang: 'ar' })
    await go(page, '/invoices'); await snap(page, 'b-01-invoices-empty', { full: true })
    await go(page, '/payments'); await snap(page, 'b-02-payments-empty', { full: true })
    await seed(page, 'ar', { decimals: 2, tax: 0 })
    await go(page, '/invoices?patient=pat-3&new=1')
    await snap(page, 'b-03-form-treatments')
    await page.getByRole('button', { name: /إضافة المحدد/ }).click()
    await page.getByRole('button', { name: 'من قائمة الإجراءات' }).click()
    await wait(page)
    await snap(page, 'b-04-form-procedures')
    await page.locator('.bl-panel-item').first().click()
    await page.locator('.modal-body').evaluate(el => el.scrollTo(0, 99999))
    await wait(page)
    await snap(page, 'b-05-form-bottom')
    await page.getByRole('button', { name: 'إصدار الفاتورة' }).click()
    await page.waitForURL(/#\/invoices\/[^?]+$/, { timeout: 5000 }).catch(() => {})
    await wait(page, 700)
    await dismissToasts(page)
    await snap(page, 'b-06-invoice', { full: true })
    await page.getByRole('button', { name: 'تسجيل دفعة' }).first().click()
    await wait(page, 700)
    await snap(page, 'b-07-payment')
    await page.locator('.bl-amount input').fill('2000000')
    await wait(page)
    await page.locator('.modal-body').evaluate(el => el.scrollTo(0, 400))
    await snap(page, 'b-08-payment-split')
    await page.getByRole('button', { name: 'حفظ الدفعة' }).click()
    await wait(page, 800)
    await page.getByRole('button', { name: 'طباعة الإيصال' }).first().click()
    await wait(page, 700)
    await dismissToasts(page)
    await snap(page, 'b-09-receipt')
    await page.keyboard.press('Escape')
    await go(page, '/invoices'); await snap(page, 'b-10-invoices', { full: true })
    await go(page, '/payments'); await snap(page, 'b-11-payments', { full: true })
    await page.getByRole('button', { name: 'تقرير الصندوق' }).click()
    await wait(page, 700)
    await snap(page, 'b-12-cash-report')
    await page.keyboard.press('Escape')
    await go(page, '/patients/pat-3?tab=billing')
    await wait(page, 500)
    await page.locator('.bl-tab').scrollIntoViewIfNeeded()
    await snap(page, 'b-13-patient-tab')
    await snap(page, 'b-13b-patient-tab-full', { full: true })
    await page.getByRole('button', { name: 'كشف حساب' }).click()
    await wait(page, 700)
    await page.locator('.modal-body').evaluate(el => el.scrollTo(0, 99999))
    await wait(page)
    await snap(page, 'b-14-statement')
    await page.keyboard.press('Escape')
    await browser.close()
  }

  // ======================= C. desktop English =======================
  if (want('c')) {
    const { browser, page } = await openBrowser({ lang: 'en' })
    watch(page, 'c')
    await seedAndLogin(page, { lang: 'en' })
    await seed(page, 'en', { decimals: 2, tax: 15 })
    await go(page, '/invoices')
    await snap(page, 'c-01-invoices-empty')
    await page.getByRole('button', { name: 'New invoice' }).first().click()
    await wait(page, 500)
    await page.getByPlaceholder('Search patients by name, file number or phone…').fill('Abdul')
    await wait(page)
    await snap(page, 'c-02-picker-long')
    await page.getByRole('dialog').getByRole('option').first().click()
    await wait(page, 500)
    await page.getByRole('button', { name: /Add selected/ }).click()
    await page.getByRole('button', { name: 'Free line' }).click()
    const free = page.locator('.bl-line').last()
    await free.locator('input').nth(0).fill('Sterilisation kit')
    await free.locator('input').nth(1).fill('99')
    await free.locator('input').nth(3).fill('12.5')
    await page.getByRole('button', { name: 'Issue invoice' }).click()
    await wait(page, 500)
    await snap(page, 'c-03-form-tooth-error')
    check(await page.getByText(/Invalid tooth number/).count() > 0, 'en: bad tooth number flagged')
    await free.locator('input').nth(1).fill('')
    await page.getByRole('button', { name: 'Issue invoice' }).click()
    await page.waitForURL(/#\/invoices\/[^?]+$/, { timeout: 5000 }).catch(() => {})
    await wait(page, 700)
    const inv = (await invoices(page))[0]
    check(inv && inv.subtotal === 1250345.83 && inv.tax === 187551.87 && inv.total === 1437897.7, `en: totals with tax (${inv?.subtotal} ${inv?.tax} ${inv?.total})`)
    await snap(page, 'c-04-invoice', { full: true })
    await printShot(page, 'c-05-invoice-print')
    await page.getByRole('button', { name: 'Record payment' }).first().click()
    await wait(page, 600)
    await snap(page, 'c-06-payment')
    await page.getByRole('button', { name: 'Save payment' }).click()
    await wait(page, 800)
    const i2 = (await invoices(page))[0]
    check(i2.status === 'paid' && i2.paid === i2.total, `en: paying the prefilled balance marks it paid (${i2.paid}/${i2.total} ${i2.status})`)
    check(await page.getByText('1 payment', { exact: false }).count() >= 0, 'en: singular wording')
    await go(page, `/invoices/${inv.id}`)
    await snap(page, 'c-07-invoice-paid', { full: true })
    await printShot(page, 'c-08-invoice-paid-print')
    await page.getByRole('button', { name: 'More' }).click()
    await page.getByRole('menuitem', { name: 'Cancel invoice' }).click()
    await wait(page)
    await snap(page, 'c-09-cancel-paid')
    await page.getByRole('dialog').getByRole('button', { name: 'Cancel invoice' }).click()
    await wait(page, 700)
    await go(page, '/patients/pat-3?tab=billing')
    await wait(page, 500)
    await snap(page, 'c-10-patient-credit', { full: true })
    check(await page.getByText('1 payment', { exact: true }).count() === 1, 'en: "1 payment" (not "1 payments")')
    await page.getByRole('button', { name: 'Account statement' }).click()
    await wait(page, 700)
    await snap(page, 'c-11-statement')
    await printShot(page, 'c-12-statement-print', true)
    await page.keyboard.press('Escape')
    await go(page, '/payments')
    await snap(page, 'c-13-payments')
    await page.getByRole('button', { name: 'Daily cash report' }).click()
    await wait(page, 700)
    await printShot(page, 'c-14-cash-report-print', true)
    await page.keyboard.press('Escape')
    await browser.close()
  }

  // ======================= D. laptop / tablet widths with large SYP-style amounts =======================
  if (want('d')) {
    for (const [w, h] of [[1280, 800], [1366, 768], [1024, 768], [820, 1180]]) {
      const { browser, page } = await openBrowser({ width: w, height: h, lang: 'ar' })
      watch(page, `d${w}`)
      await seedAndLogin(page, { lang: 'ar' })
      await seed(page, 'ar', { decimals: 0, tax: 0 })
      await q(page, async () => { await window.__dentora.db.clinic.update('clinic', { currency: 'SYP', currencySymbol: 'ل.س' }) })
      await go(page, '/invoices?patient=pat-3&new=1')
      await page.getByRole('button', { name: /إضافة المحدد/ }).click()
      await page.getByRole('button', { name: 'إصدار الفاتورة' }).click()
      await page.waitForURL(/#\/invoices\/[^?]+$/, { timeout: 5000 }).catch(() => {})
      await wait(page, 600)
      await page.getByRole('button', { name: 'تسجيل دفعة' }).first().click()
      await wait(page, 600)
      await page.locator('.bl-amount input').fill('250000')
      await page.getByRole('button', { name: 'حفظ الدفعة' }).click()
      await wait(page, 700)
      await dismissToasts(page)
      await go(page, '/invoices')
      const r = await page.evaluate(() => { const w = document.querySelector('.bl-table'); return w ? { sw: w.scrollWidth, cw: w.clientWidth } : null })
      check(!r || r.sw <= r.cw + 1, `d${w}: invoices table fits its card (${r?.sw} <= ${r?.cw})`)
      await snap(page, `d-${w}-invoices`)
      await go(page, '/payments')
      const r2 = await page.evaluate(() => { const w = document.querySelector('.bl-table'); return w ? { sw: w.scrollWidth, cw: w.clientWidth } : null })
      check(!r2 || r2.sw <= r2.cw + 1, `d${w}: payments table fits its card (${r2?.sw} <= ${r2?.cw})`)
      await snap(page, `d-${w}-payments`)
      await go(page, '/patients/pat-3?tab=billing')
      await wait(page, 400)
      const r3 = await page.evaluate(() => [...document.querySelectorAll('.bl-table')].map(w => w.scrollWidth - w.clientWidth))
      check(r3.every(d => d <= 1), `d${w}: patient tab tables fit (${r3})`)
      await snap(page, `d-${w}-patient-tab`)
      await browser.close()
    }
  }
} finally {
  server.kill()
}
if (consoleErrors.length) { console.error('\nCONSOLE ERRORS:'); for (const e of consoleErrors) console.error(' ', e) }
console.log(`\n${failures.length ? `${failures.length} FAILED:\n - ${failures.join('\n - ')}` : 'ALL CHECKS PASSED'} · console errors: ${consoleErrors.length}`)
process.exit(failures.length || consoleErrors.length ? 1 : 0)
